### ISSUE TITLE
Clean tries to drop a function from an extension and fails

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#100]
_Original author: Martin.A...@gmail.com (May 11, 2012 10:11:31)_

We are using PostgreSQL 9.1 and are using the uuid-ossp extension. Clean tries to drop one of its functions. The extension has been installed manually as it required adding binaries to the DBMS.

Any way to work around this?

FlywayException: Error executing statement at line 64: DROP FUNCTION IF EXISTS &quot;public&quot;.&quot;uuid_nil&quot;() CASCADE
Occured in com.googlecode.flyway.core.migration.sql.SqlStatement in method execute, line number 78
Caused by org.postgresql.util.PSQLException: ERROR: cannot drop function uuid_nil() because extension uuid-ossp requires it
  Hint: You can drop extension uuid-ossp instead.
Occured in org.postgresql.core.v3.QueryExecutorImpl in method receiveErrorResponse, line number 2102

_Original issue: http://code.google.com/p/flyway/issues/detail?id=257_

**Comment by imjoshholloway** [comment]
Just incase someone comes looking here and doesn't fancy jumping between the issues to figure out a work around:

Create a `beforeClean.sql` file in your migrations folder and add the required `DROP...` command into it.

For example, if like me, when doing `flyway clean -X` you get: `ERROR: cannot drop function uuid_nil() because extension uuid-ossp requires it` you would add the following into the `beforeClean.sql` file:

```sql
DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
```

**Comment by esetnik** [comment]
Wrong migration name format: beforeClean.sql(It should look like this: 1_2__Description.sql)

**Comment by dustinevan** [comment]
@imjoshholloway, Beautiful summary. Thanks man.

**Comment by tdonohue** [comment]
A complication to add into this:  Some Postgres extensions (e.g. uuid-ossp, pgcrypto) can only be dropped (DROP EXTENSION) by accounts with "superuser" privileges.  This means that @imjoshholloway's solution is great if your database owner also has "superuser" privileges, but won't work if you don't have "superuser" rights.

This unfortunately means that while normally a "clean" could be performed by a database owner, when extensions are installed, that database owner may not even have rights to remove them (unless they also have superuser privileges).

This seems to vary extension by extension though. The official docs say that some extensions should be manageable by database owners, while others require superuser privileges.
http://www.postgresql.org/docs/9.4/static/sql-createextension.html

**Comment by cowwoc** [comment]
@tdonohue Are you saying that a user can install an extension that he/she cannot drop even though their permissions have not changed?

**Comment by tdonohue** [comment]
Not at all. Some extensions can only be installed or dropped by superuser
accounts. So if the extension was installed via flyway, then flyway would
have rights to remove it. But if the extension was installed prior to
running flyway, then it may or may not be removable by flyway. It all
depends on whether the acct flyway is using has superuser permissions or if
it is just a normal database owner acct.

**Comment by cowwoc** [comment]
@tdonohue Okay, so I don't see this as a problem. Users should either create/drop the schema exclusively through Flyway or provide it with the necessary permissions to clean up after themselves if they used some other user account.

**Comment by tdonohue** [comment]
It's not a bug per say, you are correct. But because extensions can require
a different level of privileges than just DB owner, they can result
in possibly unexpected errors should you try to run "clean". Here's a
scenario:

Suppose you have two applications, app1 and app2. They run off the same
machine but use different databases, db1 and db2, respectively. Both use
Flyway, but for safety/security, the sysadmin has them use different DB
accounts, db1-owner (owner of db1) and db2-owner (owner of db2).  This
setup works great with Flyway and both apps can manage their DB schemas
separately (and neither DB owner can access the other app's DB).

But, at some point in the future app2 decides they need to use the
"pgcrypto" extension. This throws a wrench in the above setup as there are
only two options available:
1. The db2-owner would need to be given "superuser" privileges to manage
the extension via Flyway. Unfortunately this means the db2-owner would also
now have full access to db1 and any other databases on that
machine (possibly less safe/secure)
2. Or, the PostgreSQL superuser acct (e.g. postgres) can actually "CREATE"
the extension in db2. Flyway migration scripts can then make use of the
extension in db2. But, Flyway will no longer be able to "clean" db2, as the
db2-owner will not have the superuser privileges necessary to remove the
extension ( or anything it created).

In some institutions the second scenario is preferable from a database
security standpoint (even though Flyway "clean" will no longer work on such
databases). But, I do see your point that the core problem is that
something was changed outside of Flyway.

**Comment by brianm** [comment]
This occurs with postgis as well, trying to clean yields:

```
Caused by: org.postgresql.util.PSQLException: ERROR: cannot drop view geography_columns because extension postgis requires it
```

Basically, extensions can create objects which are "special"

It is also not abnormal to have a DBA user which does NOT have permissions to load/unload extensions, but can execute DDL, used for migrations.

**Comment by tdonohue** [comment]
For what it's worth, the only way around this issue seems to be to install extensions (at least those requiring superuser privileges) in a separate database schema (as initially recommended by @axelfontaine). That way, when you run 'clean' on your primary database schema (e.g. public), Flyway won't attempt to remove those extension's functions.

Here's an example for how you could (manually) install the `pgcrypto` extension in a separate schema, and make its functions available on your database's "search_path":

```
# Login to the database as a superuser
psql --username=postgres [db-name]
# Create a new schema in this database named "extensions" (or whatever you want to name it)
CREATE SCHEMA extensions;
# Install pgcrypto extension in this new schema
CREATE EXTENSION pgcrypto SCHEMA extensions;
# Determine what your database "search_path" is set to
SHOW search_path;
# Update your database's "search_path" to also search the new "extensions" schema.
# You are just appending "extensions" on the end of the existing comma-separated list.
ALTER DATABASE [db-name] SET search_path TO [existing-search_path-list],extensions;
```

With `pgcrypto` installed into a separate "extensions" schema, a Flyway 'clean' can be performed using a non-superuser account (as 'clean' will no longer attempt to remove the extension)

**Comment by ptahchiev** [comment]
+1

**Comment by cikorka** [comment]
+1

**Comment by tjholmes66** [comment]
So, I just started following this thread.   I have Postgres 9.4 and PostGIS installed, and using Flyway 3.2.1.     I have my tables and my sequences in the public schema.
  In following this thread, I created a "beforeClean.SQL" which does the following.

DROP EXTENSION IF EXISTS postgis CASCADE;
DROP EXTENSION IF EXISTS citext CASCADE;
DROP EXTENSION IF EXISTS fuzzystrmatch CASCADE;

The maven flyway clean now does work, and does go through, at least I think it does.

So, now I presume that I have to re-add these extensions?    In following this thread, I presume that I need to add these extensions into a new schema?   call this new schema "extensions" and add the extensions there?   Will that work for my tables in the public schema?

**Comment by bladeoflight16** [comment]
A possible workaround here would be to create the extension in a schema that Flyway does not manage. If you want to drop the extension, you would still need to add the drop somewhere. ("after clean" seems like the best place to drop extensions, since objects might depend on them.)

**Comment by smrnv** [comment]
+1

**Comment by b0dh1** [comment]
+1

**Comment by matsandreassen** [comment]
+1

Just attempted to use Flyway with a PostGIS-enabled database in an integration test. Cleaning fails with:

org.flywaydb.core.internal.dbsupport.FlywaySqlException: 
Unable to drop "public"."spatial_ref_sys"
-----------------------------------------
SQL State  : 2BP01
Error Code : 0
Message    : ERROR: cannot drop table spatial_ref_sys because extension postgis requires it
  Hint: You can drop extension postgis instead.

**Comment by ttaranov** [comment]
+1, same as above - clean doesn't work with Postgres databases with PostGIS extension installed.

**Comment by matsandreassen** [comment]
The reason we're encountering this is because we put our tables inside "public". There's a workaround to this which I've "uncovered" on Stackoverflow and the like. I'll try to re-iterate the solution:

1. Create new schema. E.g. "myschema"
2. To enable PostGIS extension on "myschema", execute:
ALTER DATABASE <YOUR_DATABASE> SET search_path = myschema, public;
ALTER USER <YOUR_USER> SET search_path = myschema, public;
3. Ensure all your migrations create tables in "myschema".
4. Finally, and I'm not sure why right now, Flyway does not seem to honor the schema setting in your jdbc-url. E.g. jdbc:postgresql://locahost:5432/mydb?currentSchema=myschema
I came over this script (pretty sure it was on Stackoverflow):

Put in 'beforeEachMigrate.sql' on your migration path:

DO $$
DECLARE
  default_search_path TEXT := NULL;
BEGIN
  SELECT setting_value INTO default_search_path
  FROM (
         SELECT
           substring(setting from 1 for eq_position - 1) AS setting_name,
           substring(setting from eq_position + 1) AS setting_value
         FROM (
                SELECT position('=' in setting) AS eq_position, setting
                FROM (
                       SELECT UNNEST(setconfig) AS setting FROM pg_db_role_setting s JOIN pg_database d ON s.setdatabase = d.oid WHERE d.datname = current_database()
                     ) raw_db_role_settings
              ) presplit_db_role_settings
       ) split_db_role_settings
  WHERE setting_name = 'search_path';

  IF default_search_path IS NOT NULL THEN
    EXECUTE 'SET search_path = '||default_search_path;
  END IF;
END;
$$

Took me a while to figure this out but this solution seems to have no side effects. :)

**Comment by foal** [comment]
I had the same issue with hstore extension (required superuser). Just create it in PG_CATALOG schema. 
```sql
CREATE EXTENSION hstore SCHEMA pg_catalog
```
In that case no need to set up search_paht.

**Comment by axelfontaine** [comment]
This is now working as expected. As long as you create your extensions with `CREATE EXTENSION IF NOT EXISTS` you should now be able to clean your schema and rebuild it just fine.

**Comment by maraswrona** [comment]
@axelfontaine unfortunately this is still not working for me. My setup:

flyway version: tried both 5.0.7 (recent) and 3.2.1 (embedded in spring boot)

V1__init.sql:
```
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE mytable (
    id SERIAL PRIMARY KEY,    
    location geometry NOT NULL    
);
```

Then running against clean db:
```
$ ./flyway migrate
Flyway Community Edition 5.0.7 by Boxfuse

Database: jdbc:postgresql://localhost:5432/airlydb (PostgreSQL 9.5)
Successfully validated 1 migration (execution time 00:00.009s)
Creating Schema History table: "public"."flyway_schema_history"
Current version of schema "public": << Empty Schema >>
Migrating schema "public" to version 1 - init
Successfully applied 1 migration to schema "public" (execution time 00:00.900s)
```

And then:
```
$ ./flyway clean -X
Flyway Community Edition 5.0.7 by Boxfuse

DEBUG: Java 1.8.0_152 (Oracle Corporation)
DEBUG: Windows 10 10.0 amd64

DEBUG: Loading config file: C:\dev\apps\flyway-5.0.7\conf\flyway.conf
DEBUG: Unable to load config file: C:\Users\m.woroniecki\flyway.conf
DEBUG: Unable to load config file: C:\dev\apps\flyway-5.0.7\flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> C:\dev\apps\flyway-5.0.7\jars
DEBUG: flyway.password -> *****
DEBUG: flyway.url -> jdbc:postgresql://localhost:5432/airlydb
DEBUG: flyway.user -> postgres
DEBUG: flyway.locations -> filesystem:C:\dev\apps\flyway-5.0.7\sql
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\derby-10.12.1.1.jar
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\derbyclient-10.12.1.1.jar
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\h2-1.4.196.jar
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\hsqldb-2.4.0.jar
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\jtds-1.3.1.jar
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\mariadb-java-client-2.2.0.jar
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\mssql-jdbc-6.2.2.jre7.jar
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\postgresql-42.1.4.jre6.jar
DEBUG: Adding location to classpath: C:\dev\apps\flyway-5.0.7\drivers\sqlite-jdbc-3.20.1.jar
Database: jdbc:postgresql://localhost:5432/airlydb (PostgreSQL 9.5)
DEBUG: DDL Transactions Supported: true
DEBUG: Schema: public
DEBUG: Spring Jdbc available: false
DEBUG: Scanning for SQL callbacks ...
DEBUG: Scanning for filesystem resources at 'C:/dev/apps/flyway-5.0.7/sql' (Prefix: '', Suffixes: '.sql')
DEBUG: Scanning for resources in path: C:\dev\apps\flyway-5.0.7\sql (C:/dev/apps/flyway-5.0.7/sql)
DEBUG: Filtering out resource: C:\dev\apps\flyway-5.0.7\sql\put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
DEBUG: Found filesystem resource: C:\dev\apps\flyway-5.0.7\sql\V1__init.sql
DEBUG: Cleaning schema "public" ...
DEBUG: Rolling back transaction...
DEBUG: Transaction rolled back
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to drop "public"."spatial_ref_sys"
-----------------------------------------
SQL State  : 2BP01
Error Code : 0
Message    : ERROR: cannot drop table spatial_ref_sys because extension postgis requires it
  Wskaz▒wka: You can drop extension postgis instead.

        at org.flywaydb.core.internal.database.SchemaObject.drop(SchemaObject.java:83)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLSchema.doClean(PostgreSQLSchema.java:86)
        at org.flywaydb.core.internal.database.Schema.clean(Schema.java:149)
        at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:179)
        at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:176)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:176)
        at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:124)
        at org.flywaydb.core.Flyway$3.execute(Flyway.java:1306)
        at org.flywaydb.core.Flyway$3.execute(Flyway.java:1299)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1655)
        at org.flywaydb.core.Flyway.clean(Flyway.java:1299)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:157)
        at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot drop table spatial_ref_sys because extension postgis requires it
  Wskaz▒wka: You can drop extension postgis instead.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:158)
        at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.execute(JdbcTemplate.java:246)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLTable.doDrop(PostgreSQLTable.java:43)
        at org.flywaydb.core.internal.database.SchemaObject.drop(SchemaObject.java:81)
        ... 13 more

```

You said 
>This is now working as expected. As long as you create your extensions with CREATE EXTENSION IF NOT EXISTS you should now be able to clean your schema and rebuild it just fine.

Could you provide a working example please?

**Comment by axelfontaine** [comment]
@maraswrona Check the milestone set for this issue. The fix is in the latest sources.

**Comment by maraswrona** [comment]
ah.... so I guess the fix will be in the next release? Thanks for the clarification.

**Comment by hgl** [comment]
Does the fix work with users without superuser privilege?

Sorry if I could just build from source myself and find out, but I'm not familiar with java, have no idea how to build 5.1.0 from github source.

**Comment by silentsnooc** [comment]
This is not working for me either.

I am using 

```xml
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-core</artifactId>
</dependency>
<dependency>
    <groupId>org.flywaydb.flyway-test-extensions</groupId>
    <artifactId>flyway-spring-test</artifactId>
    <version>5.0.0</version>
    <scope>test</scope>
</dependency>
```
or
```
[INFO] +- org.flywaydb:flyway-core:jar:5.0.7:compile
[INFO] +- org.flywaydb.flyway-test-extensions:flyway-spring-test:jar:5.0.0:test
```

in a Spring Boot (2.0.1.RELEASE) application. However, running my unit tests will throw:

```
org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to clean schema "public"
-------------------------------
SQL State  : 2BP01
Error Code : 0
Message    : ERROR: cannot drop type cube because extension cube requires it
  Hint: You can drop extension cube instead.


	at org.flywaydb.core.internal.database.Schema.clean(Schema.java:151)
	at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:179)
	at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:176)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
	at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:176)
	at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:124)
	at org.flywaydb.core.Flyway$3.execute(Flyway.java:1306)
	at org.flywaydb.core.Flyway$3.execute(Flyway.java:1299)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1655)
	at org.flywaydb.core.Flyway.clean(Flyway.java:1299)
	at org.flywaydb.test.FlywayTestExecutionListener.dbResetWithAnnotation(FlywayTestExecutionListener.java:378)
	at org.flywaydb.test.FlywayTestExecutionListener.handleFlywayTestAnnotationForClass(FlywayTestExecutionListener.java:178)
	at org.flywaydb.test.FlywayTestExecutionListener.beforeTestClass(FlywayTestExecutionListener.java:157)
	at org.springframework.test.context.TestContextManager.beforeTestClass(TestContextManager.java:215)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:60)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot drop type cube because extension cube requires it
  Hint: You can drop extension cube instead.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:158)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.execute(JdbcTemplate.java:246)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLSchema.doClean(PostgreSQLSchema.java:90)
	at org.flywaydb.core.internal.database.Schema.clean(Schema.java:149)
	... 22 more
```

**Comment by silentsnooc** [comment]
@axelfontaine Oh I only just saw your comment: Is it not supposed to work with `5.0.7`?

**Comment by silentsnooc** [comment]
Okay, I'll repeat what @foal said because it's easily overlooked.

If you can, just install your extensions with `pg_catalog`. In my case I put 

```sql
CREATE EXTENSION IF NOT EXISTS cube WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA pg_catalog;
```
in my `V1__init.sql` script.

Now my tests are running without problems.

**Comment by zarinfam** [comment]
I had this problem for test environment, see this answer https://stackoverflow.com/questions/46656531#51038385

**Comment by axelfontaine** [comment]
@svpace Please open a new issue with exact steps how to reproduce.
