### ISSUE TITLE
Gradle plugin can not set placeholderReplacement property

### ISSUE THREAD

**Issue by neowu** [flyway/flyway#1001]
it's due to invalid value type flyway task used to set placeholderReplacement

/flyway/flyway-gradle-plugin/src/main/groovy/org/flywaydb/gradle/task/AbstractFlywayTask.groovy
org.flywaydb.gradle.task.AbstractFlywayTask

line 106:
propSet(flyway, 'placeholderReplacement')
should be
propSetAsBoolean(flyway, 'placeholderReplacement')

**Comment by axelfontaine** [comment]
Good catch! Thanks! Consider this fixed in time for the next release.

Cheers
Axel

**Comment by neowu** [comment]
Thanks for update!
