### ISSUE TITLE
Version number is getting truncated

### ISSUE THREAD

**Issue by rajmalhotra2000** [flyway/flyway#1004]
The Version number of the SQL is getting truncated when using the flyway info.

I have sqls like V1_13_0_20141201_1__mod_pki_qrtz_job_listeners_T.sql
The version in the DB is shown correctly as 1.13.0.20141201.1.
However "flyway info" command line is showing it as "1.13.0.2014120". Its loosing last 3 characters.

Here is the output line
| 1.13.0.2014120 | mod pki qrtz job listeners T | 2015-03-02 13:56:23 | Success |

**Comment by axelfontaine** [comment]
Please upgrade to 3.2.1. This problem has already been fixed a while ago.

**Comment by axelfontaine** [comment]
Duplicate of #742
