### ISSUE TITLE
"No signature of method" when flyway.baselineVersion is specified on a Gradle build

### ISSUE THREAD

**Issue by mauromol** [flyway/flyway#1005]
After upgrading from Flyway 3.1 to 3.2.1, I see this error when I specify the following in my Gradle properties and run the `flywayMigrate` task:

    flyway.baselineVersion=0

The error is:
>Caused by: groovy.lang.MissingMethodException: No signature of method: org.flywaydb.core.Flyway.setBaselineVersionAsString() is applicable for argument types (java.lang.String) values: [0]
>at org.flywaydb.gradle.task.AbstractFlywayTask.createFlyway(AbstractFlywayTask.groovy:98)
>at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.groovy:75)`

**Comment by axelfontaine** [comment]
Hmmm that message puzzles me, as that method does exist: https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L821

**Comment by mauromol** [comment]
Yes, it puzzles me also. Maybe it's a bad error message caused by the fact that the plugin Groovy code passes the parameter in a bad way? "[0]" seems like an array to me, but once again the error message may be misleading.
I double checked that I'm not polluting my classpath with mixed Flyway versions, but I'm almost certain it should be only 3.2.1 there. The same error happens with 3.2, but not with 3.1. If I comment out the `baselineVersion property`, all works fine (I would have expected instead to see something similar with the other properties...). Also, I verified that I'm using the new version because, once I comment that line out, I can finally run Flyway with Gradle and JRE 1.6 (this can't be done with 3.1 because of the issue I filed some time ago).

Can you reproduce?

**Comment by mauromol** [comment]
Also please note that running the Gradle `flywayBaseline` task produces the following output:

>Flyway.init() is deprecated. Use baseline() instead. Will be removed in Flyway 4.0.

**Comment by mauromol** [comment]
OK, as I suspected I had a mixed classpath situation, since my `buildSrc` still depended on version 3.1, while my main build depended on 3.2.1. This was causing the `buildSrc` project build to fail.
Sorry for the false report.
However, please note that the deprecation warning when running the `flywayBaseline` task should be effective, since I got it on another system where the first Flyway version ever used is 3.2.1 :-)

**Comment by axelfontaine** [comment]
Thanks for the update. Yes, I noticed the deprecation warning, but it unfortunately doesn't make sense to fix it anymore as the next release will be 4.0.
