### ISSUE TITLE
Flyway classpath scanning

### ISSUE THREAD

**Issue by daddykotex** [flyway/flyway#1008]
I'm working on a tool which is basically a schema manager. It uses Flyway to handle the migrations. The tool works with the gradle plugin.

```
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
└── src
    └── main
        ├── java
        │   └── pkg
        │        └── migration
        └── resources
            └── migration
```

I want to use this structure as a template. I can clone this, update the connection information and starts off right away by putting SQL files in the `ressources/migration` folder or `JdbcMigration` in the `java/pkg`.

But when I run `./gradlew flywayMigrate -i`, I get an error during the scanning. I think the Flyway tool doesn't like finding no `JdbcMigration` in the specified packages.

Here is my `build.gradle` :
```
ext {
    postgresqlJDBCVersion = "9.4-1201-jdbc41"
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.flywaydb:flyway-gradle-plugin:3.2.1'
    }
}

apply plugin: 'org.flywaydb.flyway'
apply plugin: 'java'

repositories{
    mavenCentral()
}

dependencies {
    compile "org.flywaydb:flyway-core:3.2.1"
    compile "org.postgresql:postgresql:9.4-1201-jdbc41"
}


flyway {
    url = "jdbc:postgresql://dbhost:5432/test"
    user = 'test'
    password = 'test'
    table = 'schema_history'
    locations = ['classpath:pkg/migration', 'migration'] //here it doesn't like the first location if it is empty
}

```

Is there a way to avoid this error when there are no `JdbcMigration` to apply yet?

Error :
```
* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  Unable to scan for SQL migrations in location: classpath:pkg/migration
  Unable to determine URL for classpath location: pkg/migration (ClassLoader: java.net.URLClassLoader@86733)
```

**Comment by axelfontaine** [comment]
Place an empty file in the directory. Sometimes empty directories aren't copied and Flyway complains about not seeing them.

**Comment by daddykotex** [comment]
There is currently a README.md file inside of the folder. I thought about it but it didn't seem to work out. Should it be an empty Java class?

**Comment by axelfontaine** [comment]
Hmmm. Can you try gradlew build flywayMigrate -i ?

**Comment by daddykotex** [comment]
I'll update as soon as I get home.

**Comment by daddykotex** [comment]
Ok it worked. I was expecting flywayMigrate to depend on build. I guess it is not. Thanks.

**Comment by daddykotex** [comment]
No, same error here. If I keep the two locations, but the java packages empty. I get the scanning error.

An empty class fixes the problem even though I think it's ugly. A package-info.java doesn't work either.
