### ISSUE TITLE
Primary key on metadata table

### ISSUE THREAD

**Issue by jessenr** [flyway/flyway#1009]
Running flyway baseline with the table argument creates a primary key with the name schema_verison_pk rather than {{metadata table name}}_pk.

**Comment by axelfontaine** [comment]
Thank you for the report. 

What Flyway version are you using?
Which client are you using?
What database are you using?

**Comment by jessenr** [comment]
version 3.2.1 
command line
postgres

**Comment by jessenr** [comment]
Looks like this wasn't an issue, just the table being renamed rather than creating it with baseline. Sorry for the inconvenience.
