### ISSUE TITLE
Problem with validation and migration when out_of_order is false

### ISSUE THREAD

**Issue by sogft** [flyway/flyway#1015]
Hi,
I'm using flyway command line ver. **3.1** and I occurred some problem when I have in my repository some sql files with an older version that the last executed. 
In this case, with out_of_order=false when I execute the migrate I receive the error : 

" *Validated 167 migrations (execution time 00:00.143s)
ERROR: Validate failed. Found differences between applied migrations and available migrations: Migration on the classpath has not been applied to database: 2410.5.2* "

The only way to resolve in this case is set the out_of_order=true and execute also the older sql files.

The same problem are present if execute a simple "validate" command , in this case I receive the same error with out_of_order equals "true" and "false". 

Please,
can you help us in order to understand how we can resolve the problem ?

Thanks,
Marco.

**Comment by axelfontaine** [comment]
This works as designed.
