### ISSUE TITLE
Will Not migrate Mulitple Schemas

### ISSUE THREAD

**Issue by mmistretta** [flyway/flyway#1016]
I tried this type of configuration:

    <schemas>
        <schema>schema1</schema>
        <schema>schema2</schema>
        <schema>schema3</schema>
    </schemas>

As well as a maven property comma separated list.  It will not migrate multiple schemas at once, even though the documentation clearly states that it should.

**Comment by axelfontaine** [comment]
This works as designed. See http://stackoverflow.com/a/27588444/350428

Cheers
Axel
