### ISSUE TITLE
Problem with default locations

### ISSUE THREAD

**Issue by hkz-dev** [flyway/flyway#1017]
1. Flyway#locations property cannot be empty.
	* [Flyway.java#L81](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L81)
	```java
	private Locations locations = new Locations("db/migration");
	```
	* [Flyway.java#L608](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L608)
	```java
	public void setLocations(String... locations) {
	    this.locations = new Locations(locations);
	}
	```

1. Therefore, CompositeMigrationResolver always create default migration resolvers.
	* [Flyway.java#L1219](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L1219)
	* [CompositeMigrationResolver.java#L72](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/resolver/CompositeMigrationResolver.java#L72)
	```java
	for (Location location : locations.getLocations()) {
		migrationResolvers.add(new SqlMigrationResolver(dbSupport, classLoader, location, placeholderReplacer,
	......
	```

1. If I use only custom migration resolvers, I delete default locations forcedly.
	* Example
	```java
	// create flyway
	Flyway flyway = new Flyway();
	flyway.setSchemas("test");
	flyway.setDataSource(new DataSource());
	
	// clear default locations
	Locations locations;
	try {
		Field field = flyway.getClass().getDeclaredField("locations");
		field.setAccessible(true);
		locations = (Locations) field.get(flyway);
	}
	catch (Exception e) {
		throw new IllegalStateException("Failed to get locations", e);
	}
	locations.getLocations().clear();
	
	// set custom resolvers
	flyway.setResolvers(new CustomMigrationResolver(......));
	
	// start migration
	flyway.clean();
	flyway.migrate();
	```

1. To use custom migration resolvers quickly, is there an easy way to delete default locations? Or default locations should be empty?

**Comment by mgurov** [comment]
`locations` cannot be null but can well be empty.  

````java
flyway.setLocations();
````
will effectively replace your 

````java
// clear default locations
Locations locations;
try {
    Field field = flyway.getClass().getDeclaredField("locations");
    field.setAccessible(true);
    locations = (Locations) field.get(flyway);
}
catch (Exception e) {
    throw new IllegalStateException("Failed to get locations", e);
}
locations.getLocations().clear();
````

Thus not a bug IMHO.

**Comment by axelfontaine** [comment]
@mgurov Thanks for the analysis. I also wasn't able to reproduce this.

@hkz-dev Please reopen with an exact test case to demonstrate the problem should it reappear.

**Comment by hkz-dev** [comment]
Sorry for mistaken issue. It was my oversight about varargs.
And configuration 'skipDefaultResolvers' in Flyway 4.0 cleared up this issue without regard of locations.
Thank you!!
