### ISSUE TITLE
Converting SQL before migration

### ISSUE THREAD

**Issue by hkz-dev** [flyway/flyway#1019]
( Thank you for watching issues 1017 and 1018. )

I use MySQL at production, and use H2 at local/development.

MySQL script and H2 script is not the same, but I want to use MySQL scripts not only production but also H2 with Flyway.

So I tried to create **SqlConverter** to convert SQL before migration. **SqlConverter** is interface, and Flyway user implements suitably.

* [SqlConverter.java](https://github.com/hkz-dev/flyway/blob/feature/add_sql_converter/flyway-core/src/main/java/org/flywaydb/core/internal/converter/SqlConverter.java)
* [MySqlToH2SqlConverter.java](https://github.com/hkz-dev/flyway/blob/feature/add_sql_converter/flyway-core/src/test/java/org/flywaydb/core/internal/converter/MySqlToH2SqlConverter.java) ( [Test](https://github.com/hkz-dev/flyway/blob/feature/add_sql_converter/flyway-core/src/test/java/org/flywaydb/core/internal/dbsupport/SqlScriptSmallTest.java#L318-L337) )

* [Other modification](https://github.com/hkz-dev/flyway/pull/1/files)

* How to use
	```java
	Flyway flyway = new Flyway();
	flyway.setSchemas("test");
	flyway.setDataSource(new DataSource());
	
	// set converter
	flyway.setSqlConverter(new MySqlToH2SqlConverter());
	
	flyway.clean();
	flyway.migrate();
	```

I dont know this is the best way to solve issue. Please review above code and consider it.

**Comment by axelfontaine** [comment]
Use either the H2 MySQL compatibility mode or Flyway placeholders to fix this. See also: http://localhost:4000/documentation/faq#db-specific-sql

Not a Flyway issue. Closing.
