### ISSUE TITLE
Sybase ASE support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#102]
_Original author: eduardo....@gmail.com (October 24, 2012 08:08:44)_

Hi, your frameworks looks very good but it'd be fine to support Sybase. It's very similar to SQL Server.

I'll be looking forward for this enhancement if accepted.

Thanks in advance.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=350_

**Comment by hakkika** [comment]
Any news about the progress of Sybase support?

**Comment by billybong** [comment]
+1, would love Sybase support

**Comment by urquilla** [comment]
+1 
Same here, Sybase ASE would be awesome

**Comment by PratikModi** [comment]
Sybase support will be awesome

**Comment by PratikModi** [comment]
+1 SYBASE

**Comment by rafik991** [comment]
+1 any updates?

**Comment by axelfontaine** [comment]
Thanks @super132 for the PR! Merged.

**Comment by RichardGet** [comment]
+1

**Comment by rcolin** [comment]
+1
