### ISSUE TITLE
V1 is not applied on MariaDB with existing tables in the schema

### ISSUE THREAD

**Issue by stijnvanbael** [flyway/flyway#1020]
I had a MariaDB database with existing tables in the schema. When I provide a script starting with V1__, it is not applied and no warning is given. The schema_version table is initialised on version 1 with type BASELINE. When I provide a script starting with V2__, it is correctly applied and I see two versions in the schema_version table.

The fact that the script is simply ignored without a warning got me on the wrong track for quite some time, looking for classpath issues. Then when I started debugging Flyway, I saw that it did find my script.

**Comment by axelfontaine** [comment]
Thank you for your report. This really works as designed. If you baseline with V1, Flyway assumes that a V1 script contains the migration to recreate the baseline. Any suggestion on how we could make this clearer in the docs?

Cheers
Axel

**Comment by stijnvanbael** [comment]
It could be mentioned on this page: http://flywaydb.org/documentation/command/baseline.html
But I wouldn't have found it there when I had this problem. I was just gazing at the logs:

MetaDataTableImpl - Creating Metadata table: `my_schema`.`schema_version`
DbBaseline - Schema baselined with version: 1
DbMigrate - Current version of schema `my_schema`: 1
DbMigrate - Schema `my_schema` is up to date. No migration necessary.

And I kept asking myself: why doesn't it run my script? Perhaps it could log that it assumes the V1 script contains the baseline, and that the script is not ran because the schema is not empty.
