### ISSUE TITLE
Parser does not handle comments directly beside a variable inside a function call

### ISSUE THREAD

**Issue by gpaulissen** [flyway/flyway#1021]
When a query in an Oracle package body contains the following:

```
  and    upper(coalesce(rle.volledige_naam2, '-1')) like
         upper( b_naam/*test*/
                || '%')
```

or

```
  and    upper(coalesce(rle.volledige_naam2, '-1')) like
         upper( /*test*/b_naam
                || '%')
```

the result of compiling the package body is:

PLS-00103: Encountered the symbol "/" The symbol "/" was ignored.

When you specify a space between the /_test_/ comment and the variable b_naam, then everything works fine.

**Comment by axelfontaine** [comment]
Thanks for the report. I tried to reproduce the issue, but failed. Could you post a complete example of a small migration file that fails parsing?

Cheers
Axel

**Comment by gpaulissen** [comment]
Hi Axel,

Here is the package spec and body. For your eyes only because it is our company code.

Regards,

Gert-Jan Paulissen

**Comment by axelfontaine** [comment]
Your email went to the Github issue (https://github.com/flyway/flyway/issues/1021). Please cut down the package code to something you can share and paste it in the issue comments.

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter.
