### ISSUE TITLE
Flyway should not expect "org/flywaydb/core/internal/version.txt" to be on the custom classpath

### ISSUE THREAD

**Issue by dukeyin** [flyway/flyway#1023]
If I try to run Flyway 3.2.1 in OSGi and set a different ClassLoader into Flyway, then flyway.migrate() will fail immediately because VersionPrinter requires that an "org/flywaydb/core/internal/version.txt" exists.

**Comment by axelfontaine** [comment]
What OSGi container are you using? Our tests pass just fine in Equinox.

Cheers
Axel

**Comment by dukeyin** [comment]
I am currently running in Eclipse, but I believe this issue would happen in any OSGi container.

If I do something as simple as
```
Flyway flyway = new Flyway();
flyway.setClassLoader(getClass().getClassLoader()); // this tells Flyway to use my Bundle's ClassLoader, as opposed to Flyway's ClassLoader, because my SQL scripts are inside my Bundle, not Flyway's
flyway.setDataSource(dataSource);
flyway.migrate();
```

Then Flyway will always fail because of https://github.com/flyway/flyway/blob/43ca80caebd3bd3ee8ddbd78bb4df25df8c66c51/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L1373 existing:
```
Caused by: org.flywaydb.core.api.FlywayException: Unable to obtain
inputstream for resource: org/flywaydb/core/internal/version.txt
    at org.flywaydb.core.internal.util.scanner.classpath.ClassPathResource.loadAsString(ClassPathResource.java:84)
    at org.flywaydb.core.internal.util.VersionPrinter.printVersion(VersionPrinter.java:44)
    at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
    at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
```
This is because Flyway is expecting "org/flywaydb/core/internal/version.txt" to exist within the custom ClassLoader.

If I instead have Flyway use its own ClassLoader, then of course Flyway can find "org/flywaydb/core/internal/version.txt" within the Flyway JAR, but it will never find my SQL scripts in a different bundle.

**Comment by axelfontaine** [comment]
Thanks for investigating. That was incredibly helpful. Consider this fixed in time for the next release.

Cheers
Axel

**Comment by Andy-L** [comment]
FWIW I am having the same issue running in Felix. Is there a workaround or a recommended alternate approach?

**Comment by okharkovskyi** [comment]
Same issue in Felix

**Comment by brianduguid** [comment]
Has a work-around been discovered yet?

**Comment by dukeyin** [comment]
For now, it would seem that your SQL migrations must be in the same bundle as Flyway (stored in a fragment hosted by org.flywaydb.core, for example).

**Comment by brianduguid** [comment]
Thank you.


Brian

**Comment by axelfontaine** [comment]
Fixed.

**Comment by andrehil** [comment]
Could you please release this fix in version 3?
