### ISSUE TITLE
support non transactional migrations in SQL api 

### ISSUE THREAD

**Issue by Omie** [flyway/flyway#1026]
support for this was added in #655, exposing it to the sql api is pending

I will send a PR for this

**Comment by kbalyasnikov** [comment]
Hi!

Is there any progress on this issue?

**Comment by axelfontaine** [comment]
Closing. See my comment on #1027

**Comment by axelfontaine** [comment]
Fixed in Flyway 4.1. See #350 and #851

**Comment by pencilcheck** [comment]
Still seeing issues about "alter type" in 5.0.7

**Comment by pulkitent** [comment]
@pencilcheck @axelfontaine Flyway isn't automatically detecting to run below SQL statement outside transaction

"ALTER TYPE <enum name> ADD VALUE IF NOT EXISTS <value>;" 

I am using the 4.1.2 version of Flyway with Postgres version 9.5. I even tried the same SQL with the "NTV__" prefix but it's getting ignored in my Gitlab CI pipeline.
