### ISSUE TITLE
error prompt command

### ISSUE THREAD

**Issue by SPARKAG** [flyway/flyway#1032]
ERROR: Found non-empty schema "SPARK" without metadata table! Use baseline() or
set baselineOnMigrate to true to initialize the metadata table.

Hello,

how could I solve this problem,

I am unable to solve,

wait.

note: I'm doing everything by the command prompt

**Comment by axelfontaine** [comment]
The error message contains the solution. Works as designed. See: http://flywaydb.org/documentation/existing.html
