### ISSUE TITLE
Make Flyway more pluggable

### ISSUE THREAD

**Issue by nickhristov** [flyway/flyway#1035]
Right now it looks very difficult to be able to plug in components into Flyway... and so it limits the extension capabilities.

I had submitted a ticket in the past for specific extension and it got denied, and since there is no mechanism to plugin custom components (custom migration resolvers, etc), the only way to navigate around this is to fork the project and work on a forked version (which will then naturally diverge from the mainline).

**Comment by axelfontaine** [comment]
You can already write custom migration resolvers: http://flywaydb.org/documentation/api/hooks.html

What is missing exactly in the current functionality?

**Comment by nickhristov** [comment]
I see, I did not spend enough time with the code. I see that I can plug in my own migration resolver, so I think that may be enough and it will be executed along with the other java and sql based migrations. 

Thanks
