### ISSUE TITLE
ORA-00911: invalid character

### ISSUE THREAD

**Issue by nitingautam** [flyway/flyway#1036]
You can see in below statement space is missing between 'NITS' and AND, it is throwing error in FlyWay DB where as it works fine in SQLPlus and AQT, Toad.

This gives error in Update, Insert, Merge all statements if space is missing.

DELETE FROM TEST.TABLE1 where CFG_AREA_ID_1 like '%NAME%' AND SOME_ID='NITS'AND CFG_AREA_CD IN ('COND_TXT','FORM');

**Comment by nitingautam** [comment]
This can be fixed with #990?

**Comment by nitingautam** [comment]
Did any one noticed this?

**Comment by nitingautam** [comment]
Is this forum dead :)

**Comment by axelfontaine** [comment]
No this forum isn't dead, it's just that sometimes people are busy :-)

**Comment by nitingautam** [comment]
Thanks Axel :)
