### ISSUE TITLE
Problem: gradle flywayValidate

### ISSUE THREAD

**Issue by camilasmbastos** [flyway/flyway#1037]
I'm having problem in this command.It is returning error that does not make much sense.

12:15:55.708 [INFO] [org.flywaydb.core.internal.command.DbValidate] Validated 257 migrations (execution time 00:03.833s)
12:15:55.730 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':flywayValidate'
12:15:55.737 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :flywayValidate FAILED
12:15:55.744 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :flywayValidate (Thread[main,5,main]) completed. Took 6.397 secs.
12:15:55.749 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 6.629 secs, idle: 0.083 secs
12:15:55.760 [ERROR] [org.gradle.BuildExceptionReporter]
12:15:55.765 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:15:55.771 [ERROR] [org.gradle.BuildExceptionReporter]
12:15:55.778 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
12:15:55.783 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':flywayValidate'.
12:15:55.788 [ERROR] [org.gradle.BuildExceptionReporter] > Error occurred while executing flywayValidate
Validate failed. Detected resolved migration not applied to database: 1
12:15:55.793 [ERROR] [org.gradle.BuildExceptionReporter]
12:15:55.798 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
12:15:55.803 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
12:15:55.810 [LIFECYCLE] [org.gradle.BuildResultLogger]
12:15:55.815 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
12:15:55.820 [LIFECYCLE] [org.gradle.BuildResultLogger]
12:15:55.824 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 12.472 secs
12:15:55.830 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).
12:15:55.832 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopped 0 compiler daemon(s).

**Comment by axelfontaine** [comment]
The error message says that you have one migration that you haven't applied yet. gradle flywayMigrate will take care of this.
