### ISSUE TITLE
Need attention on Issue #1022

### ISSUE THREAD

**Issue by DhruvDhaka** [flyway/flyway#1038]
Apologies for creating an issue with this subject line.
But, can anyone update on issue #1022 created a month back.

I've provided the requested details there, not sure if its under analysis/implementation since haven't received any comment there.
If I can get an update there, it'd be helpful in identifying the current state of issue #1022 .

**Comment by axelfontaine** [comment]
We'll look at it in time for the next release.

Duplicate of #1022
