### ISSUE TITLE
Informix support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#104]
_Original author: Tomislav...@gmail.com (August 19, 2011 15:19:48)_

Is there any possibility to support Informix database? Thx

_Original issue: http://code.google.com/p/flyway/issues/detail?id=155_

**Comment by gc8** [comment]
+1

**Comment by noerstad** [comment]
+1

Any news on if this will be prioritized in the near future or if we have to start looking at "competing" frameworks? ;)

**Comment by ogjerstad** [comment]
+1

**Comment by belingueres** [comment]
+1

**Comment by ceinmart** [comment]
+1

**Comment by struesda** [comment]
is there any documentation on the steps to add support for a DB?   We are considering FlywayDB but will need to add Informix support to fully leverage it.

**Comment by carljmosca** [comment]
Given that dbaccess is required for certain changes (such as creating stored procedures), would this not be of limited use?

**Comment by belingueres** [comment]
You can create stored procedures using the JDBC driver (I do it with dbVisualizer client tool). The only thing I coudn't do with a client tool is to get the query plan since Informix stores it in a text file on the server filesystem.

**Comment by carljmosca** [comment]
Which version of the driver are you using?  I also use DbVis and it is currently failing for me.  I assume this is outdated since it's working for you: http://www-01.ibm.com/support/docview.wss?uid=swg21689642

**Comment by belingueres** [comment]
I'm using driver version 4.10.JC7DE, but I've doing this for years.
To create the stored proc in dbVis, you need to execute it using the button
which shows the tooltip "execute the complete buffer as one SQL statement".

2016-12-22 0:12 GMT-03:00 Carl J. Mosca <notifications@github.com>:

**Comment by carljmosca** [comment]
Ah, I think I now see my confusion.  Are you able to use the "execute the complete buffer as one SQL statement" for complex DDL including create table and triggers along with some DML?

I have also used DbVis for years for individual DDL and some more complex but have not currently found a way to execute complex ones (DDL and DML).

**Comment by belingueres** [comment]
Yes. The point is that if its working with other JDBC drivers and
databases, then adapting it to informix should be possible too.

2016-12-23 14:08 GMT-03:00 Carl J. Mosca <notifications@github.com>:

**Comment by carljmosca** [comment]
I am not saying it's not possible.  I was asking for an example. I don't think it's a showstopper anyhow.

**Comment by carljmosca** [comment]
I have submitted a pull request with some initial, very limited support for Informix from here: https://github.com/carljmosca/flyway

**Comment by carljmosca** [comment]
I have now added and tested support for the DELIMITER in the Informix support.  The example I asked for above can now be achieved with the DELIMITER.

For example:

DELIMITER $$
create trigger "informix".my_trigger delete on
    "informix".some_table referencing old as old
    for each row
        (
        execute procedure "informix".special_update(old.some_id
    ,NULL ,NULL ));
$$

A second (or third) set of eyes would be great.

**Comment by davalente** [comment]
+1

**Comment by carljmosca** [comment]
thank you - I believe I addressed this in my fork

the pull request was rejected due to tests which apparently I don't understand because last I checked they worked for me

**Comment by axelfontaine** [comment]
This has now been implemented.
