### ISSUE TITLE
Version prefixing parameter

### ISSUE THREAD

**Issue by CSchulz** [flyway/flyway#1040]
Hello,

we have a directory structure like sql/general/<version>/ and all sql files with index in this folder with smallest ddl changes as possible.

We will encounter an issue if we have the next version, because the index starts with 01 again.
Using timestamp for the scripts would be a solution but it doesn't help to identify the version fast.

I would like to have a parameter which is used by flyway as version prefix, together with the index it would be a full qualified version **<version>.<index>**

What do you think?

**Comment by axelfontaine** [comment]
This is too niche a use-case to be put in the core, but you can implement your own MigrationResolver to do this.
