### ISSUE TITLE
Single connection in DriverDataSource can never be closed

### ISSUE THREAD

**Issue by mbosecke** [flyway/flyway#1042]
I believe there is a bug in the DriverDataSource that prevents a "singleConnection" from ever being closed. My understanding is that you are typically suppressing the closing of this connection because the rest of flyway assumes there are actually two connections. However, when the entire data source is being closed there is [a line of code](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/jdbc/DriverDataSource.java#L378) that is explicitly trying to close the single connection but I believe this is still being caught by the [SuppressCloseHandler](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/jdbc/DriverDataSource.java#L357).

**Comment by axelfontaine** [comment]
Excellent catch! Fixed.
