### ISSUE TITLE
Using both custom and SQL callbacks

### ISSUE THREAD

**Issue by barryoneill** [flyway/flyway#1047]
If I specify

`flyway.callbacks=com.myclass.CustomCallBack`

it gets called fine, but I notice it seems to suppress the SQL callback functionality. Is there any way to have both? I notice there's a SqlScriptFlywayCallback that could be potentially used to enable SQL callbacks as well as the custom one - but that's one of your 'internal' classes and can't be used directly without some wrapper code..

Alternatively, even just a clarification in the documentation that you can generally only use one or the other by default would be fine, I found this out by experimentation.

Thanks!

**Comment by axelfontaine** [comment]
I agree, there is certainly room for improvement here.

**Comment by barryoneill** [comment]
Thanks for the work on this, I look forward to trying it out soon!
