### ISSUE TITLE
ORA-32794 in Oracle 12c using identity columns

### ISSUE THREAD

**Issue by Ringerl** [flyway/flyway#1049]
"flyway clean" can not clean a schema with *identity columns*, because the auto generated sequences can not be deleted. These must be [purged from the recycle bin](http://blog.mclaughlinsoftware.com/2014/01/17/cleaning-up-a-schema/):

```sql
CREATE TABLE test
(
   test_id NUMBER GENERATED BY DEFAULT AS IDENTITY
)
```

**Comment by axelfontaine** [comment]
This should be fixed now, unfortunately I don't have access to an Oracle 12 installation at this time. Could you build the latest sources of Flyway-core (it's easy with -DskipTests) and confirm that it is indeed working for you?

Cheers
Axel

**Comment by 0x6e6562** [comment]
I can confirm that this works with a 12.1.0.2.0 installation. I generated the command line utility by building b18394c794082884de6c59bed53b9bd42078d5c7 using the following profile:

```
$ mvn install -P-InstallableDBTest -P-CommercialDBTest -DskipTests=true -P-CommandlinePlatformAssemblies
```

I also commented out the modules from the parent POM that caused the build to fail that were not required:

```xml
<modules>
    <module>flyway-core</module>
    <!--module>flyway-gradle-plugin</module>
    <module>flyway-gradle-plugin-largetest</module>
    <module>flyway-maven-plugin</module>
    <module>flyway-maven-plugin-largetest</module>
    <module>flyway-sample</module>
    <module>flyway-sample-webapp</module>
    <module>flyway-sample-osgi</module>
    <module>flyway-sample-osgi-fragment</module>
    <module>flyway-osgi-largetest</module-->
    <module>flyway-commandline</module>
    <!--module>flyway-commandline-largetest</module>
    <module>flyway-ant</module>
    <module>flyway-ant-largetest</module>
    <module>flyway-sbt</module>
    <module>flyway-sbt-largetest</module-->
</modules>
```

Is there any chance that this patch might get back ported to the 3.2.x series?

**Comment by davidkarlsen** [comment]
@axelfontaine Any chance you could release - we really need this one. Additionally do you think it's a good idea to push out snapshots for the .travis.yml - so fresh builds will be available? In the mean time I can push one to our own private repo.

**Comment by gooeywizard** [comment]
Was this ever put into a release? I'm using version 5.1.4, but I'm still seeing this same error when I run clean.
" ORA-32794: cannot drop a system-generated sequence"

**Comment by axelfontaine** [comment]
@gooeywizard Yes and it works flawlessly with the latest code. If you are still seeing an error, please try the latest code, including 6.0.0-beta and if it persists, then open a new issue with clear steps how to reproduce.
