### ISSUE TITLE
DB2 for IBM i (also known as AS/400 - iSeries - ...) support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#105]
_Original author: degraef....@gmail.com (March 08, 2012 20:53:53)_

<b>Purpose of code changes on this branch:</b>
I provided an additional database flavor: in fact &quot;DB2 for IBM i&quot; is a member of the DB2 family, but there are some adaptations, mostly related to the catalog...

Regards
Luc

_Original issue: http://code.google.com/p/flyway/issues/detail?id=229_

**Comment by DanielNovo** [comment]
Hi Axel,

What can i do to help? What's missing to include this in flyway?

Thanks

**Comment by axelfontaine** [comment]
We have decided not to implement this as it is very unlikely we will *never* have access to such a system for testing.

**Comment by m1h43l** [comment]
@axelfontaine It would be a shame if Flyway couldn't support the best relational database out there. Is there a way we can add support for DB2 on i by just adding an existing jar to the classpath? Then someone else could support DB2 on IBM i in Flyway and you don't need to have it in you source.
