### ISSUE TITLE
Incompatibility with Postges URLs

### ISSUE THREAD

**Issue by keleshev** [flyway/flyway#1050]
Hello, I'm a happy user of flyway. I'm using it only for SQL migrations, and wanted to highlight some of the minor pain points I have. This is the first one. 

For background I'm using Flyway with a Python app, and in process of integrating it into a Rust app. I'm using Postgres locally and on Heroku. 

The URI format that Flyway accepts differs considerably with what Postgres accepts. Based on my experience it differs in *many* subtle ways. Here's just a few I recall:

* Postgres takes either `postgres://db` or `postgresql://db` URIs, while Flyway takes only `postgresql://db`.
* Postgres takes user/password as either `postgresql://user:password@db` or `postgresql://db?user=user&password=password` (less prevalent). Flyway supports only the less prevalent version, or supplying user/password separately.
* Postgres defaults to the name of local user, Flyway does not.

Here's an example of URL that Heroku gives with its hosted Postgres service:

```
postgres://hxxxxxxxxxxxxg:Mxxxxxxxxxxxxxxxxxxxxxxxxk@ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com:5432/dxxxxxxxxxxxxu
```

And I need to change it to the following to make it work with Flyway:

```
jdbc:postgresql://exxxxxxxxxxxxxxx2.eu-west-1.compute.amazonaws.com:5432/dxxxxxxxxxxxxu?sslmode=require&user=hxxxxxxxxxxxxg&password=Mxxxxxxxxxxxxxxxxxxxxxxxxk
```

But because of the `jdbc:` part, it cannot work with vanilla Postgres commands.

I understand that this is probably the outcome of using JDBC, and probably won't change, but I wanted to let you know anyway.

**Comment by axelfontaine** [comment]
Thanks. Yes, we support whatever the POstgreSQL JDBC driver supports. If you want a broader set of URLs supported by them, they are the one to contact. Or Maybe Heroku should provide you JDBC-compatible URLs when your application is a JVM-based app.

Won't fix.
