### ISSUE TITLE
Introduce option for scripts that apply to different builds

### ISSUE THREAD

**Issue by blootac** [flyway/flyway#1056]
We are moving to flyway from dbdeploy.

We've written a wrapper around dbdeploy to give us the following functionality and are planning to do the same for flyway but thought that it would be useful by others as well.

We have a lot of reference data (~6GB) that needs to make it to the production environments. we also have a lot of developers (~60) who each has their own schema to develop against.

For unit/integration testing and development they only need a very small subset or sometimes different data entirely and not the complete set. To meet this requirement we have a kind of branching of files which is based on the naming convention.
e.g.
1.1.0001__create_table.sql
1.1.0002__TEST_insert_test_data.sql
1.1.0002__PROD_insert_production_data.sql
1.1.0003__do_some_more_stuff.sql

When we currently deploy we say whether we want a dev build or a prod build. We then copy all of the files that either don't have __TEST_ or __PROD_ in the name or the files with either __TEST_ or __PROD_ depending on the build required. these files are copied into the working directory for DBDeploy (or in this case flyway) and the deployment proceeds as normal.

i.e. For a dev build the following files would be used 
1.1.0001__create_table.sql
1.1.0002__TEST_insert_test_data.sql
1.1.0003__do_some_more_stuff.sql

and for a production build the following files would be used
1.1.0001__create_table.sql
1.1.0002__PROD_insert_production_data.sql
1.1.0003__do_some_more_stuff.sql

It would be good if this could be done within flyway using defined tags within the conf file.
I can imagine that this is also something that other projects would find useful.

**Comment by axelfontaine** [comment]
You have two ways to do this:

1. Use multiple locations and configure different combinations based on the needs of each environment/developer => works out of the box, but requires you to rearrange your files
2. Write your own MigrationResolver => more work, but can be made to work with your current setup without requiring it to change.

This is not something we'll add to the core distribution of Flyway.

Cheers
Axel
