### ISSUE TITLE
Introduce option to refuse to migrate if missing file from sequence

### ISSUE THREAD

**Issue by blootac** [flyway/flyway#1057]
We number our files as such:
1.1_0001_create_table.sql
1.1_0002_populate_table.sql
1.1_0003_index_table.sql
2.0_0001_do_some_stuff.sql
2.0_0002_do_some_more_stuff.sql

We have written a wrapper that inspects the available files and if a file number is missing from the sequence then the migration is aborted.
e.g. if 1.1_0002 had been deleted or was never merged, the migration would not start as a file in the same major and minor version exists with a higher number (i.e. 1.1_0003). either the file must be found, a 'do nothing' script must be created (select 1 from dual), or 1.1_0003 must be renamed to be 1.1_0002. This relies on our naming scheme expecting the first two numbers to be a major and minor version number and the next four numbers to be sequential deltas.

The advantage this functionality gives is missing files are easily highlighted. In our instance there should never be missing files and the absence means they have either been accidentally deleted or not merged into master properly.

At the moment we implement this as a wrapper prior to calling flyway but can see that other projects might benefit from this functionality so if this is the case this quite simple functionality might want to be included into flyway properly. 

In the conf table the sequence digits could be defined as either the number of least significant digits that must be contiguous (in our case and example 4) or the number of most significant digits that can be non-contiguous (in our case and example 2). i.e. allow gaps where the first two digits differ but not where the first two are the same.

**Comment by axelfontaine** [comment]
Thank you for your suggestion, and I can see why it's useful for you but this is too niche a usecase to include in the main distribution of Flyway.
