### ISSUE TITLE
Flyway Performance Profiling

### ISSUE THREAD

**Issue by Patrick1701** [flyway/flyway#1061]
Hi FlyWay Team,
thanx a lot for this great framework!

We are using it in a heavy way for integration tests (setup and migrate for each test) and due to a profiling of our tests today, we also have a cpu usage profiling as by-product and maybe this could be helpfull for your development as well.

Currently, we are on v2.1.1. I know its quite old, but possible you can still get some interesting information.

Attached a screenshot...

best regards
Patrick

![flyway_performance](https://cloud.githubusercontent.com/assets/3428658/8800053/b841df2e-2faf-11e5-8b03-1f3299d04ce9.png)

**Comment by axelfontaine** [comment]
Thank you Patrick. If you find any performance low hanging fruits with the latest release, please let us know. We'll be happy to look at fixing them.

Cheers
Axel
