### ISSUE TITLE
Create independent flyway-spring module

### ISSUE THREAD

**Issue by guylabs** [flyway/flyway#1064]
Hi,

I thought about adding a new module to the Flyway project called `flyway-spring` (or something like that) which then adds more support for Spring and we could move the Spring dependencies out of the `flyway-core` module and put all Spring related things into this module (e.g. like #1062). This way the people which use Spring can add this module and the ones who don't do not have any useless Spring dependencies in their projects.

I know that the Spring support is hard wired into the `flyway-core` project, see `org.flywaydb.core.api.MigrationType#SPRING_JDBC` for instance, but I think this could be refactored such that all Spring related things are in its own module.

What do you think about that? If you like the idea, I could create an initial pull request with the new module and the refactorings.

Thanks and regards,

Guy

**Comment by axelfontaine** [comment]
Thank you for your suggestion. However it is not clear to me what the advantage would be. I actually quite like the fact one doesn't need to include many Jars. Simply add flyway-core and you're done. No need to think whether you need a special jar from Spring, OSGi, JBoss, ... And if you don't use Spring, you'll simply have a few unused classes on the classpath. So what? You're probably not using most of the JDK anyway.

Cheers
Axel

**Comment by guylabs** [comment]
Hi Axel,

well my intention was to just separate the flyway core classes with the Spring related classes. You could also add a module dependency to the flyway spring project inside the flyway core project such that you do not need to add the flyway spring dependency by your own. This way the Spring classes are more separated and could easily be excluded by a customer which does not need Spring at all. 

But you are right, most of the people do not care about all the transitive dependencies and just let them on the classpath, till they have version conflicts with same libraries. ;)

So you can close the issue as won't fix if you do not want to create such a module and decouple the Spring classes from the flyway core module.

For us the #1062 would be more important as this issue here is just a suggestion.

Thanks a lot for the fast response.

Cheers,

Guy

**Comment by edbrannin** [comment]
@guylabs If I recall correctly, Maven has a way to exclude specific transitive dependencies -- would that satisfy your use-case, or does it not quite work liek I expect?

**Comment by guylabs** [comment]
@edbrannin Well it is more about separating the integration of Spring and the rest of Flyway and add some more Spring support in a separate module. And as I wrote in the former comment we would need to have #1062 integrated somehow and this here is just a suggestion, as the only thing Flyway uses from the Spring dependency is the `JdbcTemplate` which then gets passed to a Java migration and that is the Spring support.

I hope you see what my intention is.

Thanks and regards,

Guy
