### ISSUE TITLE
Can't set baseline-version from application.properties

### ISSUE THREAD

**Issue by buddhistpirate** [flyway/flyway#1065]
Greetings,

 We have a Spring-boot application and we are trying to set a `baseline-version` in concert with `baseline-on-migrate` in some environments. We would love to be able to set `flyway.baseline-version=5` in our properties file, since we are just using the default flow provided by flyway and spring. The fix in #752 does not give us a way to do this since there is no 'bean' created for `baseline-version-as-string`. 

From reading [Juergen's comment](https://jira.spring.io/browse/SPR-4931?focusedCommentId=48117&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-48117) it seems that if there was a getter that returned a string, then the original string setter would have worked, and possibly would have let us use the .properties file to set it.

In either case, could there by a way to set the baseline-version from a properties file ie have a bean that is a string that we can set?

Thanks,
 Tim & Joel

```ini
flyway.baseline-on-migrate=true
flyway.baseline-version=1
```

```shell
gradle bootRun
```

> Failed to convert property value of type 'java.lang.String' to required type org.flywaydb.core.api.MigrationVersion' for property 'baselineVersion'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [org.flywaydb.core.api.MigrationVersion] for property 'baselineVersion': no matching editors or conversion strategy found

**Comment by axelfontaine** [comment]
This is a Spring Boot issue, not a Flyway one. Closing.

**Comment by billnreed** [comment]
Is there any corresponding Spring Boot bug that goes along with this? We're running into an issue related to this for our product.

**Comment by foby** [comment]
Use `baselineVersionAsString` instead of `baseline-version` in your application.yaml (or whatever config file you are using). This calls `Flyway#setBaselineVersionAsString(String baselineVersion)` directly.
```
flyway:
  baselineVersionAsString: 2.2
  baseline-on-migrate: true
```

**Comment by vir2610** [comment]
@snowbillr Can you please tell me how you solved the issue ? because same thing is happening with me using **application.properties** in spring boot project.
