### ISSUE TITLE
SBT application.conf support?

### ISSUE THREAD

**Issue by EdgeCaseBerg** [flyway/flyway#1066]
I've looked through the documentation for a half hour and done some experimentation but can't seem to figure this out. Sorry if I missed something obvious somewhere. Right now it looks like for SBT you're stuck doing this for database credentials in build.sbt: 

    flywayUrl := ""
    flywayUser := ""
    flywayPassword := ""
    flywayDriver := ""

Is there a way to support an [application.conf](https://github.com/typesafehub/config) style file for providing these values? Something like:

    flyway.url = xxxx

or

    flyway { 
        url = xxx
    }

being used for the `flywayUrl` and similar keys? If possible using `db.default.url` would be great, as I'm trying to not repeat my db credentials multiple times in multiple places. But if support for application.conf or a properties file could be made that would be really useful.

**Comment by nafg** [comment]
I just recently dealt with this. Here's my solution:

## `project/Conf.scala`
```scala
import sbt._

object Conf {
  lazy val dbConf = settingKey[(String, String, String)]("Typesafe config file with slick settings")
}
```

## In `build.sbt`

```scala
Conf.dbConf := {
  val cfg = ConfigFactory.parseFile((resourceDirectory in Compile).value / "application.conf")
  val prefix = "slick.dbs.default.db"
  (cfg.getString(s"$prefix.url"), cfg.getString(s"$prefix.user"), cfg.getString(s"$prefix.password"))
}
```

## `flyway.sbt`
(If you prefer you can put this in `build.sbt` instead)
```scala
flywaySettings

flywayUrl := Conf.dbConf.value._1
flywayUser := Conf.dbConf.value._2
flywayPassword := Conf.dbConf.value._3
```

**Comment by nafg** [comment]
(I use this with a play-slick setup)

**Comment by EdgeCaseBerg** [comment]
Hmm. This looks promising @nafg but I'm getting
```
error: not found: value ConfigFactory
  val cfg = ConfigFactory.parseFile((resourceDirectory in Compile).value / "application.conf")
```

I'm not very good at handling sbt's build files. I tried adding `resolvers += Classpaths.typesafeResolver` to a project/build.sbt file but that didn't seem to help

**Comment by EdgeCaseBerg** [comment]
Ignore my last comment, I had to add `libraryDependencies += "com.typesafe" % "config" % "1.2.1"` to my _project/build.sbt_ file. And that seems to be working. Thanks so much @nafg!

**Comment by nafg** [comment]
Apologies about that, my project uses Play so I didn't need to add that.

**Comment by axelfontaine** [comment]
We already support loading flyway.conf from a number of clients and this probably would be easy to add to the SBT plugin too.

@cdedie Thoughts?

**Comment by EdgeCaseBerg** [comment]
@axelfontaine can you point me to some examples in the codebase that do that? I could take a crack at it and open a PR if I can figure it out

**Comment by axelfontaine** [comment]
Example from Maven Plugin: https://github.com/flyway/flyway/blob/master/flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java#L520

**Comment by EdgeCaseBerg** [comment]
Ok, I've been staring at the code base for a bit between the example you linked and the FlywayPlugin.scala file. Correct me if I'm wrong here, and I'm just working out what happens, but:

```
  private implicit class FlywayOps(val flyway: Flyway) extends AnyVal {
    def configure(config: Config): Flyway = {
      flyway
      .configure(config.base)
      .configure(config.migrationLoading)
      .configure(config.migrate)
      .configureSysProps(config.dataSource)
    }
    ...
```
loads the data source last. Which calls down:

```
    def configureSysProps(config: ConfigDataSource): Flyway = {
      val props = new Properties()
      System.getProperties.filter(e => e._1.startsWith("flyway")).foreach(e => props.put(e._1, e._2))
      config.asProps.filter(e => !sys.props.contains(e._1)).foreach(e => props.put(e._1, e._2))
      flyway.configure(props)
      flyway
    }
```
Which loads all environmental variables first, then loads any unspecified properties from the pass `ConfigDataSource` class. The config passed in is taken from the sbt task `flywayConfigDataSource`

```
flywayConfigDataSource <<= (flywayDriver, flywayUrl, flywayUser, flywayPassword) map {
        (driver, url, user, password, confFile) => ConfigDataSource(driver, url, user, password) 
}
```

So if we wanted to have a flyway.conf file load these values, then we would need to make changes within the `flywayConfigDataSource` task. Adding in a new string key and maybe doing something like this:
```
 flywayConfigDataSource <<= (flywayDriver, flywayUrl, flywayUser, flywayPassword, flywayConfigFile) map {
        (driver, url, user, password, confFile) => 
          //load up conf file and set settings
          //override conf file settings with specified url,user,pass, driver
          //return configured data source
        }
      },
```

OR

Perhaps just change
```
def configureSysProps(config: ConfigDataSource): Flyway = {
      val props = new Properties()
      System.getProperties.filter(e => e._1.startsWith("flyway")).foreach(e => props.put(e._1, e._2))
      config.asProps.filter(e => !sys.props.contains(e._1)).foreach(e => props.put(e._1, e._2))
      flyway.configure(props)
      flyway
    }
```
to use [typesafe's config](https://github.com/typesafehub/config) and load the properties at some point before or after the other (not sure on order)

```
def configureSysProps(config: ConfigDataSource): Flyway = {
      val props = new Properties()
      import com.typesafe.config.ConfigFactory
      val mainConf : com.typesafe.config.Config = ConfigFactory.load()
      if (mainConf.hasPath("flyway")) {
        import scala.collection.JavaConverters._
        //Load up flyway.* properties
        mainConf.getConfig("flyway").entrySet.asScala.map(configValue => props.put(configValue.getKey, configValue.getValue))        
      }
      
      System.getProperties.filter(e => e._1.startsWith("flyway")).foreach(e => props.put(e._1, e._2))
      config.asProps.filter(e => !sys.props.contains(e._1)).foreach(e => props.put(e._1, e._2))
      flyway.configure(props)
      flyway
    }
```
This might be redundant to call the `System.getProperties` there, since according to the overview in the readme:

>users can override the config with Java system properties, java -Dmyapp.foo.bar=10

The above is a bit messy but I'm just trying to get feedback on the idea. (I haven't test the code above yet since I can't figure out how to actually tried to compile the sbt plugin yet.

**Comment by axelfontaine** [comment]
I looked a bit further into this. This is really a Play-specific file in Typesafe's own format (hocon). At this point I don't feel Flyway should add native support for it. However if this issue gathers support, I could reconsider in the feature, albeit limited to the SBT plugin.

**Comment by arturaz** [comment]
I think this isn't integration, but documentation issue. There's only a few lines of code to be written for the integration and they could be provided as an example in the https://flywaydb.org/getstarted/firststeps/sbt page.

I could write them if you're up for the idea.
