### ISSUE TITLE
Documentation or Sample code for disabled transaction

### ISSUE THREAD

**Issue by smougenot** [flyway/flyway#1072]
Issue #655 introduced disabling transaction support.
But there is no sample, no documentation and only a unit test to demonstrate this.

Todo : 
- add sample in flyway-sample module
- add relevant documentation

**Comment by CRegenschein** [comment]
Hi, is there some small example, anywhere?

Thanks.

**Comment by lukas-gitl** [comment]
Example would be great...

**Comment by cosmopetrich** [comment]
I came across this issue while looking into `CREATE INDEX CONCURRENTLY` support in Flyway. Can this issue be closed now that Flyway >= 4.1.0 supports autodetection of non-transactional statements?

**Comment by MikielAgutu** [comment]
I've updated the documentation site regarding this. We aim to release it with v6.
