### ISSUE TITLE
Support option to use Slf4j/Commons Logging/JUL when using the command line tool

### ISSUE THREAD

**Issue by ericparton** [flyway/flyway#1075]
Currently, when using the command line tool, Flyway only supports logging to standard out. It would be useful if the command line tool could optionally leverage Flyway's existing ability to use Slf4j or Commons Logging if their jars are on the classpath.

**Comment by axelfontaine** [comment]
Thanks for your suggestion. What would be the real world use case for this?

Cheers
Axel

**Comment by ericparton** [comment]
It would allow users of the command line tool to log the output of the tool to a file on disk if a jar with a logging configuration file and the logging jars were on the classpath. You could also do things like configure the logger to print the info statements to the console, but only log the debug statements to a file, so you don't have to run the tool with the debug flag and you still have the ability to consult the logs if there's an issue.

Thanks,
Eric

**Comment by axelfontaine** [comment]
I ended up implementing it with an automatic switch instead.

Cheers
Axel
