### ISSUE TITLE
Change of Delimiter does not work correct for SQLite

### ISSUE THREAD

**Issue by stkuehnl** [flyway/flyway#1081]
I would create the following two tables in a SQLite Database by using flyway:
```
CREATE TABLE my_patch_level
  (
    db_id                     INTEGER PRIMARY KEY autoincrement,
    db_level                  NUMBER (3) NOT NULL ,
    db_svn                    VARCHAR2 (35) NOT NULL ,
    db_zp_beginn              DATE NOT NULL ,
    db_zp_ende                DATE
   ) ;
CREATE TABLE adr_verfahren
  (
    vrf_id   INTEGER PRIMARY KEY autoincrement ,
    vrf_knz  VARCHAR2 (3) NOT NULL ,
    vrf_name VARCHAR2 (80) ,
    vrf_zid  NUMBER (12) ,
    vrf_dm   DATE DEFAULT (datetime('now','localtime'))
  ) ;
```
After executing the script with flyway - there has been created only one table without any exception.
I have debug flyway. The class SQLiteSqlStatementBuilder overrides the method changeDelimiterIfNecessary. In this method flyway checks if it is necessary to change the delimiter. This is useful for database-specific stored procedures or trigger. But in my case - there is no stored procedures or trigger. 
Due the column **db_zp_beginn** (in my first table) the following code assigned the field *insideBeginEndBlock* to true and the method returns null for the delimiter and flyway puts all the following statemets to the current statement.
Here the code:
```
    @Override
    protected Delimiter changeDelimiterIfNecessary(String line, Delimiter delimiter) {
        if (line.contains("BEGIN")) {
            insideBeginEndBlock = true;
        }

        if (line.endsWith("END;")) {
            insideBeginEndBlock = false;
        }

        if (insideBeginEndBlock) {
            return null;
        }
        return getDefaultDelimiter();
    }
```
The condition for setting the field *insideBeginEndBlock* should be fixed. There could also be a problem if I would insert a text in a column which contains *begin* or if I have a column such as *beginners*.

**Comment by axelfontaine** [comment]
Thanks for researching this! Fixed.
