### ISSUE TITLE
Clean on embedded derby database does not clean triggers

### ISSUE THREAD

**Issue by khelsen** [flyway/flyway#1085]
When calling flyway.clean() from our Java application (on derby embedded db) using the maven Flyway plugin (v3.2.1), we get exceptions telling that there still are triggers depending on tables. It seems thus that the triggers are forgotten in the clean. 

Exception:
Operation 'DROP TABLE' cannot be performed on object 'table-name' because TRIGGER 'trigger-name' is dependent on that object.

Example script:

CREATE TABLE TEST (
	ID INTEGER NOT NULL,
	NAME VARCHAR(128) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE TEST_REFERENCE (
	REF_ID INTEGER NOT NULL,
	TEST_ID INTEGER NOT NULL,
	PRIMARY KEY (REF_ID),
	CONSTRAINT FK_TEST_ID FOREIGN KEY (TEST_ID) REFERENCES TEST (ID)
);

CREATE TRIGGER TRG_Del_Test AFTER DELETE ON TEST_REFERENCE
REFERENCING OLD AS EXISTING
FOR EACH ROW MODE DB2SQL
        DELETE FROM TEST
        WHERE ID = EXISTING.TEST_ID
        ;
        
INSERT INTO TEST VALUES (1, 'Test trigger');
INSERT INTO TEST_REFERENCE VALUES (1, 1);

**Comment by axelfontaine** [comment]
Thank you very much. Your sample script was hugely helpful in creating a test for this. Fixed.
