### ISSUE TITLE
Run arbitrary shell scripts as migrations

### ISSUE THREAD

**Issue by kshep** [flyway/flyway#1086]
We're a Python shop searching for a DB migration tool. We appreciate the philosophy and maturity of Flyway, but in our case we really need the ability to run Python scripts as migrations. In some cases, it'd be desirable to execute migrations via SQLAlchemy ORM, but more often we simply want to do backfill operations using our own app data models and libraries.

After exploring some Jython based options (e.g. for compiling our Python scripts) and exploring the MigrationResolver API, it dawned on me that it'd be pretty darn convenient to simply have shell scripts exist as "first class" migrations. If you could run any script, you'd have the ability to write migrations any any language (either via #! in your scripts or with simple shell script wrappers).

That's the motivation behind https://github.com/rollbar/flyway/pull/1, which is a PR against our fork.

Any feedback's welcome, although I have my fingers crossed it tends towards "Neat" vs "WTF are  you doing?" Prior to this I hadn't touched Java or Maven in a year or so, so constructive criticism/tips would be very much appreciated.

If others think this would be useful, I'd be happy to PR it against flyway/flyway.

**Comment by kshep** [comment]
Here's the version we're using:

https://github.com/rollbar/flyway/releases/tag/flyway-3.2.1-rollbar1

I could open a PR if there's any interest in this.

**Comment by axelfontaine** [comment]
This can now be implemented with a custom MigrationResolver and MigrationExecutor.
