### ISSUE TITLE
Flyway Puppet Module

### ISSUE THREAD

**Issue by smbambling** [flyway/flyway#1087]
I've written a Puppet module to manage and install the current version of Flyway.  Just wanted to share this with you guys in case it might be helpful for others.  The documentation is still a work in progress ..but the module is 100% functional

Support version of Puppet 2.7 or greater including Puppet 4 and supports hiera

https://github.com/arineng/arin-flyway

**Comment by axelfontaine** [comment]
Thanks! Feel free to contribute a pull request against flyway/flywaydb.org to have it listed on the Other Tools and Frameworks page.
