### ISSUE TITLE
support for reading placeholders from property file

### ISSUE THREAD

**Issue by chgangaraju** [flyway/flyway#1088]
As discussed over here, http://stackoverflow.com/questions/9418173/how-do-placeholders-work-in-flyway

We need to add placeholders like below. Can you provide support to read all the placeholders from a property file?

```
<property name="placeholders">

		<map>

			<entry key="key1" value="${value1}"></entry>

			<entry key="key2" value="${value2}"></entry>

		</map>

</property>
```

**Comment by axelfontaine** [comment]
I assume you are using ant. You can already load placeholders from properties using the Ant property task: https://ant.apache.org/manual/Tasks/property.html

Example: flyway.placeholders.key1=value1
