### ISSUE TITLE
SQL cannot be parsed when using binary type "char (16) for bit data": X'0123'

### ISSUE THREAD

**Issue by pascalgruen** [flyway/flyway#1089]
When using UUIDs in DB2 (or Derby, they are very similar), the column is defined as

    CREATE TABLE my_table (my_uuid CHAR (16) FOR BIT DATA NOT NULL,
    CONSTRAINT pk_my_table PRIMARY KEY (my_uuid));

Binary literals for CHAR FOR BIT DATA are written like string literals, but with a leading X:

    SELECT * FROM my_table WHERE my_uuid = X'123';

So, when I want to add a new column in a Flyway SQL migration, this syntax is used:

    ALTER TABLE my_table ADD my_other_uuid CHAR (16) FOR BIT DATA
    NOT NULL DEFAULT X'0000';

Unfortunately, Flyway does not recognize the `X'` as an opening string quote token, so the migration script cannot be parsed (The exact error in my case is: Syntax error: Encountered ";" at line 2, column 25.).

I found no clear documentation for specifying binary literals, but I found a short summary of the most common syntaxes:
http://stackoverflow.com/questions/9320200/inline-blob-binary-data-types-in-sql-jdbc

Due to this bug, new CHAR FOR BIT DATA columns cannot be added with NOT NULL, because that would require a DEFAULT clause.

**Comment by axelfontaine** [comment]
Thank you for reporting this and providing the fix! Merged!
