### ISSUE TITLE
flyway shows wrong info (mvn flyway:info)

### ISSUE THREAD

**Issue by Fatmehwq** [flyway/flyway#1092]
- using database sqlserver 2014
- created maven project, added flyway plugin 3.2.1 in pom.xml
- created flyway.properties file at the same path of pom.xml

scenario:
it happens sometime; I am testing my scripts and sometimes I need to delete schema_version table and rerun scripts
but sometime flyway doesn't work correctly
although I deleted the table schema_version, when I run the command ( mvn flyway:info ) it shows me that we have some scripts ran and etc

I tried to resolve the issue with running ( mvn eclipse:eclipse)   ( mvn clean install) ( mvn flyway:repair ) but no resolution

---------------
here is my properties file, flyway.properties\

flyway.url=jdbc:sqlserver://MYSERVER:1433;DatabaseName=schema1
flyway.user=sa
flyway.table_name=test_flywa

-----------------
here is my pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.test</groupId>
	<artifactId>database-scripts</artifactId>
	<version>0.0.0</version>
	<packaging>jar</packaging>

	<name>database-scripts</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<finalName>database-scripts</finalName>

		<plugins>
			<plugin>
				<groupId>org.flywaydb</groupId>
				<artifactId>flyway-maven-plugin</artifactId>
				<version>3.2.1</version>
				<configuration>
				    <baselineOnMigrate>true</baselineOnMigrate> 
				
					<url>${flyway.url}</url> 
					<user>${flyway.user}</user>
					<password>OOOOO</password>
					<schemas>
						<schema>schema1</schema>
					</schemas>

				</configuration>

				<dependencies>
					<dependency>
						<groupId>com.microsoft.sqlserver</groupId>
						<artifactId>sqljdbc4</artifactId>
						<version>3.0</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>

	</dependencies>
</project>

----
here are a sample result of running ( mvn flyway:info )
however in practice, the table is empty!!!

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building database-scripts 0.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- flyway-maven-plugin:3.2.1:info (default-cli) @ database-scripts ---
[INFO] Flyway 3.2.1 by Boxfuse
[INFO] Database: jdbc:sqlserver://MYSERVER:1433;xopenStates=false;trustServerCertificate=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;packetSize=8000;loginTimeout=15;lockTime
out=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=schema1;applicationName=Microsoft SQL Server JDBC Driver; (Microsoft SQL Server 12.0)
[INFO]
+---------+------------------------------+---------------------+---------+
| Version | Description                  | Installed on        | State   |
+---------+------------------------------+---------------------+---------+
| 0       | << Flyway Schema Creation >> | 2015-09-04 14:47:39 | Success |
| 1       | Baseline script              | 2015-09-04 14:47:39 | Success |
| 1.1     | first script                 | 2015-09-04 14:52:50 | Success |
| 1.2     | first script                 | 2015-09-04 14:52:50 | Success |
| 2.2     | second script                | 2015-09-04 14:52:50 | Success |
| 2.3     | third script                 | 2015-09-04 17:00:26 | Success |
| 2.4     | third script                 |                     | Pending |
+---------+------------------------------+---------------------+---------+

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.290s
[INFO] Finished at: Wed Sep 09 11:22:17 EDT 2015
[INFO] Final Memory: 4M/15M
[INFO] ------------------------------------------------------------------------

**Comment by axelfontaine** [comment]
Thanks for reporting this. Flyway doesn't pull this information out of thin air. It always queries the database to obtain it, hence I strongly suspect the schema_version table is still there. Are you sure you are dropping the correct one in the correct schema?

Please reopen the issue with a link to a GitHub project that reproduces this if you can  isolate it.

Cheers
Axel

**Comment by makouk20** [comment]
Hello i have the same problem here did you resolve your problem sir?
