### ISSUE TITLE
Multi Module Maven Project and Running Flyway before build start

### ISSUE THREAD

**Issue by sreekanthsnair** [flyway/flyway#1094]
Hi,
    I have a maven multi module (EAR) project in the following structure
```
Parent-Proj
+-- ear-proj
+-- war-proj
+-- java-projA
|    +--src/main/resources/db/migration/ scripts for proj A
+-- java-projB
|    +--src/main/resources/db/migration/ scripts for proj B
+-- java-projC
|    +--src/main/resources/db/migration/ scripts for proj C
```

Usually we do migration using spring flyway integration that works perfectly on server start, but here the problem is we want to run flyway migration from maven build but not independent of each project but as an aggregate (means projA+projB+projC migration scripts) before any project junit runs. Is it possible using maven to aggreate and run flyway script at the start of the build.

**Comment by axelfontaine** [comment]
You can probably create a separate db module that loads the migrations using locations with relative paths and have all other modules depend on it to make sure it runs first.

Closing. Not a Flyway defect. Belongs on StackOverflow under the Flyway tag :-)

**Comment by sreekanthsnair** [comment]
I agree this is not a flyway issue, was waiting almost a month in stackoverflow to get an answer for this and nobody yet have any solution for this. The target audience for my question is to fly developer and maven expert who can direct us how to integrate in multi module project not as a last module which run the DB migartion as you mentioned but as the first module which aggregates all child modules script in to single place and run the migration script before any other child module starts building. Since our junit depends on that + we can not do future migrations without maven integration in development env.

**Comment by axelfontaine** [comment]
I wrote you the solution in my previous comment.

**Comment by sreekanthsnair** [comment]
I saw it and i'm very grateful to that, but unfortunately i couldn't find a single solution in web, how to copy child module resource to the top, if you have any idea or some articles where i can grab, it would be great. I have tried every possible way i could. Like i have given above i want to copy the migration resources of child module B and C to the child module A (flyway module for migration). I have tried with relative path but nothing seems to be working even i'm very much not sure the relative paths i have tried is correct.

**Comment by wadacoder** [comment]
@axelfontaine Thanks for the tip.
I followed your advice. I have a separate db module under the main/parent project. I placed the SQL files under the default src/main/resources/db/migration folder
Although I am unable point the migration scripts location to the correct folder.
Is there a way to inspect the path to those files. It's gotta be some file path combination that should work.

**Comment by gauravbrills** [comment]
Another solution that I use is have multiple profiles in the parent for each submodule with relative paths and run with parent non recursive when building respective Db . IF you want to build everything then you might not need profiles .

**Comment by dbelyaev** [comment]
for someone who'll find this ticket in future, this blogpost can be helpful (explains how to setup separate submodule to run flyway migration in other app modules in a multimodule Maven project): https://smyachenkov.com/posts/flyway-migrations-in-multi-module-maven-projects/
