### ISSUE TITLE
MSSQL Server: exclude microsoft tools procedures/functions from empty schema detection

### ISSUE THREAD

**Issue by JeanRev** [flyway/flyway#1095]
SQL Server Management Studio automatically creates some procedures and function (eg. sp_alterdiagram, sp_renamediagram, fn_diagramobjects, etc.) for dealing with database diagrams.

Those objects are showing up in the INFORMATION_SCHEMA.ROUTINES view, which in turn will cause the schema to be considered non empty by Flyway. Strictly speaking, they are indeed user-defined objects, but their handling should be (in my opinion) kept outside of the versioning system.

SQL Server Studio will actually list those procedures and functions as "System" objects, relying on the "microsoft_database_tools_support" extended property in addition to the "is_ms_shipped" object field (see: http://stackoverflow.com/questions/1976248/how-do-i-list-all-non-system-stored-procedures ).

I propose to implement the same kind of check in the doEmpty() of the SQLServerSchema class.

**Comment by axelfontaine** [comment]
Yes, that makes sense. This could also be used for clean by explicitly excluding those.

**Comment by axelfontaine** [comment]
Would you like to contribute a PR for this?

**Comment by JeanRev** [comment]
Yes, I should be able to find some time for this.

**Comment by axelfontaine** [comment]
Perfect! Looking forward to it!

**Comment by axelfontaine** [comment]
@JeanRev See my comments on #1272
