### ISSUE TITLE
Flyway fails to connect with the database if the OS user name is longer than 30 characters

### ISSUE THREAD

**Issue by sastorsl** [flyway/flyway#1099]
Flyway fails to connect to the if the OS user name is longer than 30 characters.
My client runs on RedHat Linux (RHEL7), and the user name is 31 characters long.

```
$ ./flyway info
Flyway 3.2.1 by Boxfuse

ERROR: Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:@server:1530:SID) for user 'myuser': Connection property: format error: Property is 'v$session.osuser' and value is 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

I can temporarily solve this with JAVA_TOOL_OPTIONS and reduce the user name length.

```
JAVA_TOOL_OPTIONS="-Doracle.jdbc.v\$session.osuser=${USER:0:29}" ./flyway info
```

The max length of a username on Linux is 32 characters.

**Comment by axelfontaine** [comment]
This will of help when fixing this: http://stackoverflow.com/questions/1612657/change-oracle-jdbc-thin-client-identifier
