### ISSUE TITLE
Migrations are invoked only on first schema.

### ISSUE THREAD

**Issue by kristerr** [flyway/flyway#1104]
In flywaySbt when set:
flywaySchemas := Seq("public", "test")
Flyway creates schema public and test, but migrations are invoked only on public.

[info] Database: jdbc:postgresql://localhost:5432/test_db (PostgreSQL 9.4)
[info] Validated 1 migration (execution time 00:00.040s)
[info] Creating schema "public" ...
[info] Creating schema "test" ...
[info] Creating Metadata table: "public"."schema_version"
[info] Current version of schema "public": 0
[info] Migrating schema "public" to version 0.0.1 - create
[info] Successfully applied 1 migration to schema "public" (execution time 00:00.181s).
[success] Total time: 1 s, completed Oct 11, 2015 12:56:51 PM

The problem is probably in file: java/org/flywaydb/core/Flyway.java
Code from 1054 line should be invoked for all schemas, not only for schemas[0]

**Comment by axelfontaine** [comment]
This works as designed: http://flywaydb.org/documentation/faq.html#multiple-schemas

If you want to migrate multiple identical schemas, you must invoke Flyway multiple times with the appropriate configuration
