### ISSUE TITLE
A tableName """t""" cause error on PostgreSQLSchema.doAllTables() 

### ISSUE THREAD

**Issue by lisboa** [flyway/flyway#1106]
The test PostgreSQLMigrationMediumTest.view(),  used to test quoted table names, fail when try to cleanup the schema. I using the PostgreSQL 9.4.4.

The cause of error is the query used to get all table names. See the line 268 of [PostgreSQLSchema](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLSchema.java):

```
   "SELECT t.table_name FROM information_schema.tables t" +
    //in this schema
   " WHERE table_schema=?" +
   //that are real tables (as opposed to views)
  " AND table_type='BASE TABLE'" +
  //and are not child tables (= do not inherit from another table).
  " AND NOT (SELECT EXISTS (SELECT inhrelid FROM pg_catalog.pg_inherits" +
  " WHERE inhrelid = ('\"'||t.table_schema||'\".\"'||t.table_name||'\"')::regclass::oid))"  <== erro is here
```
Instead of

```
 " WHERE inhrelid = ('\"'||t.table_schema||'\".\"'||t.table_name||'\"')::regclass::oid))"  <== erro is here 
```
Using the <b>quot_ident</b> function fix the problem, as showed bellow:

```
" WHERE inhrelid = (quote_ident(t.table_schema)||'.'||quote_ident(t.table_name))::regclass::oid))"
```

Note: Seem that the function <b>quot_ident</b> exists since PostgreSQL 7.3.

Thanks,
Fabio.

**Comment by axelfontaine** [comment]
Thanks! Fixed.
