### ISSUE TITLE
Flyway does not find sql files with dots in their name

### ISSUE THREAD

**Issue by glowinghands** [flyway/flyway#1113]
I had a file V1.0.1__initial_tables.sql and it couldn't find it. I know it found the location because if I change the location to something bogus it would say it couldn't find it. So I replaced the 1.0.1 with 1_0_1 and it worked just fine. The documentation specifically says "version: Dots or underscores separate the parts, you can use as many parts as you like" but it would appear the code didn't get the memo. :-)

It's not a big deal, just have to either change the documentation or make it support dots like the docs say.

**Comment by axelfontaine** [comment]
I am unable to reproduce this. Please re-open with exact steps to reproduce if this happens again.
