### ISSUE TITLE
Fingerprint DB schema against stored hash

### ISSUE THREAD

**Issue by rschueler** [flyway/flyway#1115]
It would be great if the verify command could detect schema drifts caused by manually executed DML on the given DB. This could be archived by extracting meta data after baselining or after each applied patch, hashing this information and store this hash in the schema_version table.

In an advanced version configurable table data could be added for hashing as well to detect changes in configuration data.

**Comment by axelfontaine** [comment]
Thank you for your suggestion. However this is both complex to implement and opposite to the ideas of disciplined database changes Flyway encourages.

This is not something I see as part of the core product anytime soon. However I can see how this could be useful in certain organizations.

Feel free to reopen and provide a PR if you want to tackle this (it's a huge task for all DBs).

Cheers
Axel

**Comment by rschueler** [comment]
Maybe you could provide an interface or callback to hook in a sql to produce this hash.
