### ISSUE TITLE
Transparently upgrade metadata table from 3.x to 4.x format

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#1117]
- [x] MigrationType INIT -> BASELINE
- [x] Recalculate checksums by ignoring line endings
- [x] Drop version_rank column
- [ ] Make version nullable
- [ ] Make installed_rank the new primary key
- [ ] Drop installed_rank index
- [ ] Drop version_rank index

**Comment by numero-six** [comment]
> Recalculate checksums by ignoring line endings

In my opinion, we should also ignore comments. Many copyright and licensing policies require to place a license header on every file of a project. It means that if the project using Flyway has its license changed, all checksum will changes, raising Flyway errors.

**Comment by axelfontaine** [comment]
@cteig Flyway 4.0 will be released next week. Can you check **this week** that `MigrationTestCase.upgradeMetadataTableTo40Format()` passes for DB2 zOS to ensure those users will have a smooth migration path to Flyway 4.0.

**Comment by axelfontaine** [comment]
@nathanvick Flyway 4.0 will be released next week. Can you check **this week** that `MigrationTestCase.upgradeMetadataTableTo40Format()` passes for Redshift & Vertica to ensure those users will have a smooth migration path to Flyway 4.0.

**Comment by axelfontaine** [comment]
@MichaelF25 Flyway 4.0 will be released next week. Can you check **this week** that `MigrationTestCase.upgradeMetadataTableTo40Format()` passes for SolidDB to ensure those users will have a smooth migration path to Flyway 4.0.

**Comment by nathanvick** [comment]
@axelfontaine,

I regret that I've been feeling sick this week. I hope get to it early this
week.

-Nathan

**Comment by axelfontaine** [comment]
@MichaelF25 Did you have a chance to check this?

**Comment by axelfontaine** [comment]
@nathanvick No worries. Worst case this will be for 4.0.1

**Comment by MichaelF25** [comment]
@axelfontaine I am now working for a different company and we do not use SolidDB. I've handed over this issue to my former colleagues and hopefully one of them will provide an update about this issue soon.
