### ISSUE TITLE
clean() does not drop foreign keys in MySQL

### ISSUE THREAD

**Issue by cthielen** [flyway/flyway#1118]
MySQL does not remove foreign keys when tables are dropped.

This lead us in practice to a "errno 150" when we ran Flyway clean() and then re-ran our migrations after having renamed a table in a later migration but neglected to drop the old foreign key.

Should the behavior of Flyway's clean() also remove foreign keys? It already removes tables, views, and events.

Thanks!

**Comment by axelfontaine** [comment]
Please post an example migration script that Flyway then fails to clean so we can reproduce this.

Cheers
Axel

**Comment by axelfontaine** [comment]
Any news?

**Comment by cthielen** [comment]
I'm unable to reproduce this currently. I did not capture the particular details and a superficial migration removing tables with data and foreign keys does work.
