### ISSUE TITLE
Adding include/exclude in clean goal

### ISSUE THREAD

**Issue by mikesac** [flyway/flyway#1121]
Provide include/exclude configuration into clean target in order to be able not to drop specific table in clean phase.

It would be really useful to preserve some reporting/log table while updating all other data.

**Comment by axelfontaine** [comment]
This can already easily be achieved today by placing that table in a separate schema.

Implementing this feature is not a priority at this point.

**Comment by mikesac** [comment]
Sadly moving table to another schema is not an option on already-existing database.
Looking forward for a future milestone where this can be included, thanks for your time

**Comment by MikielAgutu** [comment]
Closing, see https://github.com/flyway/flyway/issues/2271#issuecomment-601223715
