### ISSUE TITLE
flywayMigrate emits 'DB: PROCEDURE does not exists' error message

### ISSUE THREAD

**Issue by markzlu** [flyway/flyway#1123]
I used flywayMigrate gradle task to create stored procedures like below:

DROP PROCEDURE IF EXISTS mds.get_mds_entity_id_per_mapping //
CREATE PROCEDURE mds.get_mds_entity_id_per_mapping(
    IN param_entity_type VARCHAR(100),
    IN param_entity_id INT,
    IN param_account_id VARCHAR(60),
    OUT param_mds_entity_id VARCHAR(60))
BEGIN

END

But it always emit the following error message in the console when the gralde flywayMigrate task runs. I checked the MySQL database, the stored procedure was created correctly. This is just annoying.

DB: PROCEDURE mds.get_mds_entity_id_per_mapping does not exist (SQL State: 42000 - Error Code: 1305)

**Comment by axelfontaine** [comment]
This is a warning emitted by the MySQL JDBC driver and is therefore logged as a warning by Flyway.

You have two options:
- suppress warning from the output with gradle -q
- if you don't feel this should be a warning, contact the MySQL JDBC driver team and take it up with them.

Not a Flyway issue. Works as designed.
