### ISSUE TITLE
Ability to exclude/filter migrations files based on a property/parameter

### ISSUE THREAD

**Issue by eilonreshef** [flyway/flyway#1125]
It'd be great if it was possible to exclude certain files based on (say) an Ant expression.

The scenario is as follows:
- Multiple directories/modules 
  - root
    - module 1
    - module 2
- SQL files in some modules, also created (by Maven) in the target directory
- We'd like to migrate all files

Migrating based on the root location results in errors because the SQL files are "double-counted" (once in src/, once in target/).

If we could specify e.g., exclude=**/target/**, that'd allow the usage of flyway to be seamless.

**Comment by axelfontaine** [comment]
Thanks for your suggestion. I currently have no plans to implement this as it is a niche feature and one can easily work around this by specifying multiple locations (one for each module).

**Comment by eilonreshef** [comment]
Thanks

We are indeed using multiple locations as you suggested. 

The challenge with the current approach is that with multi-module configurations the list of modules may change and this approach requires frequent changes in scripts, maven files etc. (or dynamic generation of configurations - which is what we do now). 

I would be surprised if this is an esoteric need for complex projects (presumably 90%+ of the projects are simple, one directory, indeed), and since Flyway is a powerful well designed tool overall it seems like there's no reason to not use it in such projects. 

If you feel an opt-out option is inconsistent with Flyway's design, perhaps there could be a more powerful opt-in approach, e.g.,
Files=*/src/**/*.sql
(Perhaps a superset of the current Locations property? Perhaps also  overriding of prefix and suffix?)

I believe Spring has support for searching using Ant expressions so it's probably less of an implementation challenge and more about finding the right design...

What do you think?

**Comment by ThirupathiMuniswamy** [comment]
@axelfontaine Could you please help me to understand how to exclude the specific db migration files from a list of migration files we have.. 

for example: 
under sql/ directory i have the below files 
V1__INSERT_****_***_NBR.sql
V2__INSERT_COLUMN_****_******_** .sql
V3__INSERT_COLUMN_*****_UPDATE.sql
V4__INSERT_COLUMN_******_ACCESS.sql

Now i wanted to exclude v3__ migration file during my flyway migration execution.. any help will be helpful.

**Comment by MikielAgutu** [comment]
Related to #1192

**Comment by MikielAgutu** [comment]
We don't think this is the right direction for Flyway.
