### ISSUE TITLE
ClassNotFoundException: org.sqlite.JDBC in android robolectric test

### ISSUE THREAD

**Issue by fschramm001** [flyway/flyway#1127]
Hey,

the flyway installation in our app works great in production mode but it will fail with a ClassNotFoundException: org.sqlite.JDBC Exception when we want to test our app with robolectric.

Even adding testCompile 'org.sqldroid:sqldroid:1.0.3' to our gradle file didn't solve the problem. 

How can we avoid the ClassNotFoundException with Robolectric?

Best
Flo

**Comment by axelfontaine** [comment]
This is most likely a config issue on your end and not a Flyway issue. Please reopen if you can pinpoint it to an issue with Flyway.
