### ISSUE TITLE
Incomplete Migrations

### ISSUE THREAD

**Issue by evbo** [flyway/flyway#1132]
It is possible for a migration to be performed incompletely, where, everything is migrated except for statements that have errors (e.g.) syntax errors.

For instance:

`CREATE TABLE schema.blah(foo INT);`
`GRAaNT SELECT on blah Too someone;`

Although the second line has clear errors, the first line does not and successfully migrates (the table gets created but permissions are not granted). Unfortunately, because the second line failed, the migration is identified as a failure. Ideally, failed migrations would not be applied to the database. Otherwise, the user must then manually delete everything that succeeded and then re-migrate.

**Comment by axelfontaine** [comment]
This is due to your database not supporting DDL transactions. 
Works as designed. See http://flywaydb.org/documentation/faq.html#rollback
