### ISSUE TITLE
Organizing SQL migrations in a specific order

### ISSUE THREAD

**Issue by kalypzo** [flyway/flyway#1133]
Can we implement a solution for ordering the SQL migrations via some additional file.

Here's one scenario off the top of my head:
I need to put my version numbers in a way that they execute in order.
Application 1 Migration
V1_1_1__mytable.sql
V2_1_1__myview.sql
V3_1_1__myproc.sql

Now, a new change comes in where I need to create a new table and my view needs to be modified to use this new table. This change, however, has no real impact the myproc procedure, so no code change is required. Now, to ensure that the move happens correctly, I need to perform the following.

V1_1_1__mytable.sql        << NEW
V2_1_1__mytable2.sql      << ORIGINAL
V3_1_2__myview.sql         << MODIFIED
V4_1_1__myproc.sql         << MODIFIED

Now it appears that I have to migrate my procedure once again with a new version when in fact there's no real change in the contents at all.

It would also be helpful to include a setComparator method so we have more control in how we organize migrations through our own custom ResolvedMigrationComparator implementation.

Thanks

**Comment by axelfontaine** [comment]
Thank you for your suggestion. This will be resolved with #128 instead.
