### ISSUE TITLE
Multi Line comments are not handled correctly

### ISSUE THREAD

**Issue by dermojoo** [flyway/flyway#1136]
Flyway ( tried version 3.2.1 ) does not handle multiline comments inside ORACLE PLSQL Skripts correctly.
The first and second comment inside Package A is handled correctly the third is not. The third comment somehow escapes the package terminating / of package A.
After the migration this creates an invalid package A with the additional code from SOME_OTHER_PACKAGE_TO_FOLLOW inside.
Multi Line comments inside lines that start with a plain sql keywords (select, update, delete...) seam to work.
If the line starts with anything else it does not.

```
CREATE OR REPLACE 
PACKAGE BODY A
IS
PROCEDURE test
IS 
    test number;
BEGIN
    select count(*) into test /* working comment */ from dual;
	/* working comment */
    test:=/*not working comment*/1;
END;

END A;
/

CREATE OR REPLACE 
PACKAGE BODY SOME_OTHER_PACKAGE_TO_FOLLOW
....
...
..
.
```

**Comment by dermojoo** [comment]
*update*
i made a mistake in my example code. The fist example ii posted did actually work. Now after my edit its not working and reproduces the error. The whitespaces before and after the opening/closing line comments made the code work. I debugged the code and drilled the issue down to org.flywaydb.core.internal.dbsupport.SqlStatementBuilder#applyStateChanges
the line 
TEST:=/*NOT WORKING COMMENT*/1;
is tokenized to
 0 = "TEST"
1 = ""
2 = "/*NOT"
3 = "WORKING"
4 = "COMMENT*/1"
and are parsed to this tokenTypes
0 = {SqlStatementBuilder$TokenType@1310} "OTHER"
1 = {SqlStatementBuilder$TokenType@1310} "OTHER"
2 = {SqlStatementBuilder$TokenType@1311} "MULTI_LINE_COMMENT"
3 = {SqlStatementBuilder$TokenType@1310} "OTHER"
4 = {SqlStatementBuilder$TokenType@1310} "OTHER"

So it missed the closing muli line comment.

**Comment by axelfontaine** [comment]
Thank you very much for reporting this and providing a fix! Great work! Merged. (I've also added you to the hall of fame page (flywaydb 4.0 branch until merged))
