### ISSUE TITLE
Flyway OutOfOrder issue

### ISSUE THREAD

**Issue by artizani** [flyway/flyway#1138]
Installed rank and version rank mismatch....
I cant be 100% sure this is a bug. But every time we run flyway migrate  all our deployment have a OutOrder status. I know for a fact that the deployments are not out or order e.g i have scripts V1.sql, V2.sql and V3.sql. V1 and V2 have been deployed successfully and flyway info reports that v1 and v2 have a status of success. Now everytime I run flyway migrate for v3.sql. the migrations is successful but the status of the last migration is OurOrder instead of sucess. 

Possible Cause....
When I look into the fly way metadata table I notice that the install rank value is different from version rank value.  I proceeded to delete the last entry in the metadata table so I can re-rerun the migration. 
when I deleted the last entry in the metadata table. I notice the installed rank and the version rank columns have exactly the same values for all my previous migration . But when I run a new migration. I notice the version rank for the new migration is incremented by 2 while the installed rank value for the same migration is incremented by 1 

![image](https://cloud.githubusercontent.com/assets/2330673/11505019/19df068c-9840-11e5-8a23-e83c4a6e009b.png)

**Comment by axelfontaine** [comment]
Please post a small GitHub project or the *exact* steps to reproduce the issue.

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter
