### ISSUE TITLE
flyway:clean is unable to delete system generated sequence (Oracle 12c)

### ISSUE THREAD

**Issue by mcmoulis** [flyway/flyway#1139]
Schema clean is failing for Oracle 12c due to system generated sequence defined for table.

ORA-32794: cannot drop a system-generated sequence

create table my_table
(
ID NUMBER GENERATED ALWAYS AS IDENTITY,
...
)

Adding purge to drop table command is possible to delete generated sequence along with.

drop table my_table purge;

 Is this valid/possible to add 'purge' to flyway clean process to avoid the error for Oracle 12c?

**Comment by 0x6e6562** [comment]
Have you looked at [this patch](https://github.com/flyway/flyway/issues/1049)?

**Comment by mcmoulis** [comment]
Sorry I missed, yes it's working with that patch. Thank you.
