### ISSUE TITLE
Unable to login via Browser

### ISSUE THREAD

**Issue by rishi3195** [flyway/flyway#1141]
I am facing problem while logging in OrientDB via browser. I have tried Chrome as well as Internet explorer.

It repeatedly pops up the dialog box for user credentials (screenshot below).

Config file snippet for users. Also tried guest/admin/reader/writer user.
<users>
        <user name="root" password="'root'" resources="*"/>
        <user name="guest" password="guest" resources="connect,server.listDatabases,server.dblist"/>
    </users>
![orientdb_error_screenshot](https://cloud.githubusercontent.com/assets/16130042/11553881/f79cf94c-99b8-11e5-9ab3-8b771ee61441.png)

**Comment by axelfontaine** [comment]
Wrong forum.

**Comment by rishi3195** [comment]
what would be correct forum??
