### ISSUE TITLE
DbSupportFactory and DbSupport impls are not exported via OSGi

### ISSUE THREAD

**Issue by dzharikhin** [flyway/flyway#1144]
This functionality is very powerful to use even before you start migration. You could check DB vendor, check schema and table names. 
But there's no exports for these classes, so you can't use flyway bundle delivery pros and you're forced to use compile-time dependency, if you don't want to duplicate code responsible for getting vendor, schema&table names

**Comment by axelfontaine** [comment]
Thanks for your suggestion. These classes are not part of the public API and will not be exposed.
