### ISSUE TITLE
Clean does not remove triggers in MySQL

### ISSUE THREAD

**Issue by apmasell** [flyway/flyway#1145]
I've noticed that the clean operation doesn't seem to remove triggers from MySQL databases. There's a test migration in `flyway-core/src/test/resources/migration/dbsupport/mysql/sql/trigger/V1__Trigger.sql` that creates triggers, but the schema emptiness check: https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/mysql/MySQLSchema.java#L49 doesn't seem to include a check for triggers.

Would something like https://github.com/oicr-gsi/flyway/commit/1be335d3254a1d020d94ab0b3afe8b7cbb80d6dc be sufficient?

Is there a way I can only run the MySQL test suite without having to install and configure all the other databases for testing?

**Comment by axelfontaine** [comment]
I'm having trouble reproducing this. Can you post a small migration file that Flyway fails to clean?

**Comment by apmasell** [comment]
I can't reproduce this any more. I had the problem with the Maven plugin 3.2.1 on a complex schema. I've since changed the schema to avoid this. I haven't been able to generate a test case that does it.

I'll close this and if I managed to reproduce it, I'll re-open it. Thanks.
