### ISSUE TITLE
Placeholder replacement from command line

### ISSUE THREAD

**Issue by fatmanmclone90** [flyway/flyway#1146]
I am trying to pass in values for the flyway.placeholders in the command line to override values in configuration.  But error thrown with invalid format even though it appears to match the example given:

./flyway -locations=filesystem:"C:\Temp" -placeholders.mydbname="Bridge-UGH" -baselineOnMigrate=true migrate

ERROR: Invalid operation: .mydbname=Bridge

---
- Usage

Scripts run successfully when reading the custom placeholders from the configuration file, e.g.:
in flyway.conf:
flyway.placeholders.mydbname= Bridge
flyway.placeholders.mytablename= Person

Also, how would you pass in multiple replacement values:

./flyway -locations=filesystem:"C:\Temp" -placeholders.mydbname=Bridge -placeholders.mytablename=Person -baselineOnMigrate=true migrate

**Comment by axelfontaine** [comment]
Please re-run this with -X also ensure you wrap the entire argument (not just parts of it) with double quotes. Example: "-placeholders.mydbname=Bridge-UGH" and not -placeholders.mydbname="Bridge-UGH"

Did that work?

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter

**Comment by Kireyko** [comment]
> Please re-run this with -X also ensure you wrap the entire argument (not just parts of it) with double quotes. Example: "-placeholders.mydbname=Bridge-UGH" and not -placeholders.mydbname="Bridge-UGH"
> 
> Did that work?

I had the same issue, and used double quotes as you advised and it works(v.6.4), thanks a lot!
