### ISSUE TITLE
command line version for IBM-AIX

### ISSUE THREAD

**Issue by javathought** [flyway/flyway#1147]
We'll use Flyway on Linux, but today we mainly have AIX OS. 
If DBAs agree with the use on Linux, they'll want it on AIX too.

**Comment by axelfontaine** [comment]
Are the current bash scripts not working for you?

**Comment by axelfontaine** [comment]
Any news?

**Comment by javathought** [comment]
I'll check if I have a server to test by myself.

**Comment by bodinger** [comment]
Hey guys - is there any progress on that topic: CLI for AIX?

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter
