### ISSUE TITLE
Integrate Percona pt-online-schema-changes

### ISSUE THREAD

**Issue by ivonyamin** [flyway/flyway#1153]
Integrate pt-online-schema-changes in order to make migrations without downtime

**Comment by anandsunderraman** [comment]
has this feature been implemented , can we find docs for this ??

**Comment by devshorts** [comment]
Are there any flyway hooks to be able to allow wiring in percona to drive a sql statement?

**Comment by ede-n** [comment]
Is this feature on the roadmap?

**Comment by lejtmany** [comment]
this would be really really useful. or even just a callback you could specify on the sql statement to be executed would be enough.

**Comment by MikielAgutu** [comment]
@ivonyamin @ede-n @anandsunderraman @devshorts What do you propose the integration would look like? How would this tool be surfaced in Flyway?

**Comment by MikielAgutu** [comment]
In Flyway 7 we shipped a feature that allows you to run arbitrary scripts as migrations (PowerShell, bash, etc). I'm not familiar with this tool but would it be possible to use this new feature to invoke it, say, as a bash script migration? https://flywaydb.org/documentation/migrations#script-migrations

@ivonyamin @ede-n @anandsunderraman @devshorts any ideas?

**Comment by MikielAgutu** [comment]
Closing for lack of interest.
