### ISSUE TITLE
Support for SAP Hana DB

### ISSUE THREAD

**Issue by rsmilyanov** [flyway/flyway#1158]
Hello,

I am trying to use flyway to manage my DB updates via flyway. Unfortunately SAP Hana is not supported by flyway and I am getting the Unsupported DB exception. I did not look at the source code carefully but isn't it supposed that the flyway to support all kind DBs since if there are some DB specific queries the developer has to make sure that he/she is having the correct DB scripts/java code based on the target DB. Are there some DB specific code inside the flyway that currently supports only the the following DBs - Supported databases are Oracle, SQL Server, SQL Azure, DB2, DB2 z/OS, MySQL (including Amazon RDS), MariaDB, Google Cloud SQL, PostgreSQL (including Amazon RDS and Heroku), Redshift, Vertica, H2, Hsql, Derby, SQLite and solidDB?

Thanks,
Radoslav

**Comment by rsmilyanov** [comment]
Hello,

I saw that the support for SAP Hana is being added into master branch. Can you please share when it is expected the current dev branch to be a final release? 

Thanks,
Radoslav

**Comment by dimitarg** [comment]
Just to let everyone now, we use this now and everything works - though our usecases are pretty simple. (create column table, alter table etc). But the overall infrastructure works smoothly - using the snapshot version.
