### ISSUE TITLE
optional package locations - do not throw exception when classpath does not exist

### ISSUE THREAD

**Issue by jangalinski** [flyway/flyway#1161]
I have an optional migration that should only apply when I activate a special maven profile.
I implemented this with a jdbc migration class that resides in a custom jar that is only added to the project in that special profile.
Unfortunately, I can not add the location directly now, because flyway fails when the classpath package to scan does not exist. I have to check for this manually befaore adding the location.

I think it would be a good idea to just ignore non existing packages while scanning, there are just no jdbcmigration classes found ... or allow "OptionalLocations" in addition to "MandatoryLocations" ... but I'd prefer the simple: "just do not raise an exception" solution.

**Comment by axelfontaine** [comment]
Since Flyway 4.0.x this is now a warning instead.
