### ISSUE TITLE
Clean on DB2 functions or procedures fails when two procedures have the same name

### ISSUE THREAD

**Issue by pswrdf** [flyway/flyway#1167]
Nobody get load on my comment there https://github.com/flyway/flyway/issues/464, so I create this issue

I faced with same error flyway 3.2.1: 
INFO: Database: jdbc:db2://localhost:50001/TEST1 (DB2/NT64 9.7)
Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to clean schema "DB2ADMIN"
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-476, SQLSTATE=42725, SQLERRMC=DB2ADMIN.MYFUNCTION, DRIVER=3.63.75

REFERENCE TO FUNCTION function-name WAS NAMED WITHOUT A SIGNATURE, BUT THE FUNCTION IS NOT UNIQUE WITHIN ITS SCHEMA

**Comment by axelfontaine** [comment]
Please include exacts steps on how to reproduce (small sample script that Flyway fails to clean).

Also please try the version from GitHub (flyway-core can easily be built from source with -DskipTests) and see if the problem still occurs.

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter.

**Comment by axelfontaine** [comment]
Fixed by #1722
