### ISSUE TITLE
Source command MYsql - flyway doesnt run 

### ISSUE THREAD

**Issue by 869kartik** [flyway/flyway#1168]
i have wrapper.sql where all the scripts in order are written for execution.(with source command)

like it has 
source insert.sql 
source  alter.sql 

flyway finds wrapper.sql but cant run insert.sql or alter.sql..
how can i resolve this

**Comment by axelfontaine** [comment]
You can only run valid SQL commands that are also supported by the MySQL JDBC driver. source is not one of them.

However you can probably use callbacks (http://flywaydb.org/documentation/callbacks.html) to achieve what you want.

**Comment by 869kartik** [comment]
ok ..thanks
one more thing.. suppose i migrate from 3.1 to 3.2 ... can i rollback again to 3.1 with the help of flyway
