### ISSUE TITLE
Unable to Rollback

### ISSUE THREAD

**Issue by 869kartik** [flyway/flyway#1169]
Hi , 
(a) i have migrated from 3.1 to 3.2 . How can i rollback..
(b) Suppose i have migrated to 3.2 and but i made some changes in 3.2 sql file . How do run it again ...

**Comment by axelfontaine** [comment]
This is *literally* the first result on Google when you search for "flyway rollback" : http://flywaydb.org/documentation/faq.html#downgrade ...

Please post such questions (after you've tried googling them) on StackOverflow.
