### ISSUE TITLE
Flyway supporting zip or tar.gz

### ISSUE THREAD

**Issue by arthurtaborda** [flyway/flyway#1173]
I am introducing Flyway in our company and I want to know if it is possible to flyway support scripts in tar.gz or zip. Our dump is huge (600MB) and even if I dump only the necessary tables it is still big enough (100MB). Github only supports files lower than 50MB, so I can't commit this baseline.

Or am I doing something wrong using the production dump as a baseline?

**Comment by axelfontaine** [comment]
Typically Flyway is only used to manage DB structure & reference data, not user data. You can implement custom migration resolvers and executors if you need support for compressed migration files.

**Comment by arthurtaborda** [comment]
To do local tests I must have some data in local databases. How can I do that is I don't have a dump script to insert all data? If I use flyway to manage only db structure I will have a empty database all the time.
