### ISSUE TITLE
sqlite: flyway migrate fails, reports database is locked

### ISSUE THREAD

**Issue by masc3d** [flyway/flyway#1180]
I'm trying to setup flyway with sqlite, org.xerial:sqlite-jdbc and gradle.
While `baseline` works fine, `migrate` always reports `database is locked`

```
Unable to restore autocommit to original value for connection
java.sql.SQLException: database is locked
    at org.sqlite.core.DB.throwex(DB.java:859)
    at org.sqlite.core.DB.exec(DB.java:142)
    at org.sqlite.jdbc3.JDBC3Connection.setAutoCommit(JDBC3Connection.java:155)
    at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:96)
        ...
```

**Comment by axelfontaine** [comment]
How did you set up your datasource? Please include a small test case to reproduce.

**Comment by masc3d** [comment]
sure. happens with the most basic setup. https://github.com/masc3d/flyway-issue-1180

**Comment by masc3d** [comment]
issue persists with flyway/gradle-plugin 4.0. do you require more feedback?

**Comment by masc3d** [comment]
adding a task using flyway directly works pretty much flawlessly.

```
/** masc20160330. workaround for flyway bug https://github.com/flyway/flyway/issues/1180 */
task flywayMigrateWorkaround << {
    Flyway flyway = new Flyway();
    flyway.setDataSource("jdbc:sqlite:${db_file}", "", "");
    flyway.migrate();
}
tasks.flywayMigrateWorkaround.group = "flyway"
```

btw flywayClean fails as well. looks like flyway-gradle-plugin is pretty much incompatible with sqlite.

```
  Unable to drop "main"."sqlite_sequence"
  [SQLITE_ERROR] SQL error or missing database (table sqlite_sequence may not be dropped)
```

**Comment by axelfontaine** [comment]
Both the original and the sqlite_sequence issue have now been fixed. See my comment on #1499

Thanks for investigating!
