### ISSUE TITLE
Feature Request: using profile name to call config files

### ISSUE THREAD

**Issue by stuart1975** [flyway/flyway#1181]
Would be great to call flyway command line only with a profile name and the right configuration would be set.
 <configuration>
	<url>jdbc:mysql://xxxx</url>
	<user>userxxx</user>
	<password>xxx</password>
</configuration>
I have various databases with the same database model which need all to be updated when a new version comes.

Currently I have always to comment the lines of the other configurations.

**Comment by axelfontaine** [comment]
You can already achieve this with the -configFile parameter. See http://flywaydb.org/documentation/commandline/#configFile
