### ISSUE TITLE
flyway info checks/parses or executes beforeMigrate.sql

### ISSUE THREAD

**Issue by vrf888** [flyway/flyway#1182]
When i ran flyway info and i have beforeMigrate.sql in sql directory it's trying to parse it and probably execute. I've found out it by running flyway info with beforeMigrate.sql in sql directory and noticed it tries to substitute placeholders in beforeMigrate.sql and also scans and complains on beforeMigrate.sql scripts in subdirs.

**Comment by axelfontaine** [comment]
Please post a small test project that reproduces the issue.

**Comment by vrf888** [comment]
For ex. sql dir contains two files:
beforeMigrate.sql:
ALTER SESSION SET CURRENT_SCHEMA=${schema};
V_011404.001.001__create_table.sql:
CREATE TABLE IF NOT EXISTS test1 ( id INT, c VARCHAR(20) );

Actual migration files does not matter as if i run than:
./flyway info 
i get following output:
Flyway 3.2.1 by Boxfuse

Database: jdbc:oracle:thin:@(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=1.2.3.4)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=testserv))) (Oracle 11.2)
ERROR: No value provided for placeholder expressions: ${schema}.  Check your configuration!

So "flyway info" tries placeholder replacement in beforeMigrate.sql.

**Comment by axelfontaine** [comment]
This has already been fixed in the current release
