### ISSUE TITLE
Redshift 'create library' is not supported

### ISSUE THREAD

**Issue by zacharynanfelt** [flyway/flyway#1184]
The following does not work due to the error shown below.

CREATE OR REPLACE LIBRARY f_urlparse 
LANGUAGE plpythonu 
FROM 'https://example.com/packages/urlparse3-1.0.3.zip';

SQL State  : 25001
Error Code : 0
Message    : ERROR: CREATE LIBRARY cannot run inside a transaction block
Location   : db/sql/V82_1_5__UrlParseFunction.sql (/../db/sql/V82_1_5__UrlParseFunction.sql)
Line       : 1

**Comment by axelfontaine** [comment]
You can work around this by implementing your own resolver & executor that disables transactions.
