### ISSUE TITLE
allow wildcard in flyway.locations

### ISSUE THREAD

**Issue by hohwille** [flyway/flyway#1192]
Flyway can be configured to scan multiple locations for migration scripts.
After some learning I discovered that you want to create folders for releases to get structure into larger and complex projects. However I would like to have something like this:
- db
  - migration
    - 1.0
      - schema
        - V0001__create_schema_core.sql
        - ...
      - data
        - V0008__create_masterdata.sql
        - ...
      - test
        - V0020__create_masterdata.sql
    - 1.1
      - schema
        - ...
      - data
        - ...
      - test
        - ...
    - ...

Via Flyway locations I would like to switch e.g. `test` on and off:

```
flyway.locations=db/migration/*/schema,db/migration/*/data
```

This is currently not possible. Instead I would have to reverse the structure to:
- db
  - migration
    - schema
      - 1.0
        - V0001__create_schema_core.sql
        - ...
      - 1.1
        - ...
    - data
      - 1.0
        - V0008__create_masterdata.sql
        - ...
      - 1.1
        - ...
    - test
      - 1.0
        - V0020__create_masterdata.sql
      - 1.1
        - ...

Does this feature request make sense to you? Are there other users having the same need? Would you welcome PRs for this?

**Comment by axelfontaine** [comment]
Thanks for your suggestion. This is not something I plan to add a t this time as the workaround is quite easy (as you already demonstrated). I am however happy to leave this open and see if this gathers support over time.

**Comment by hohwille** [comment]
The two directory layouts are not fully equivalent. Maybe you want to even lock the previous version folders in your VCS to prevent that they are changed. Also things that belong together for the current release are closer together in the first layout...

**Comment by ThiyaguE** [comment]
+1

**Comment by rljohnsn** [comment]
+1

**Comment by roni-frantchi** [comment]
+1

**Comment by aquimi** [comment]
+1

**Comment by darkio14** [comment]
+1

**Comment by suryaprabhakark** [comment]
+1
