### ISSUE TITLE
Encrypting configuration file

### ISSUE THREAD

**Issue by ThiyaguE** [flyway/flyway#1194]
Flyway should have in-built support for an option to encrypt the configuration file as per user requirement using different  algorithms. This is first requirement for enterprises as we store db user credentials. We are bein forced to use third party crpter algorithms now.

**Comment by ThiyaguE** [comment]
I saw its already raised. Issue # 416. Just a thought, why can't we bundle some of open source encryption methods/classes along with flyway. Atleast in 4.1. Encryption key could be set by user.

**Comment by shorif2000** [comment]
any update on this

**Comment by davidjeddy** [comment]
@ThiyaguE When you say `store` do you mean on the File system? Is global ENV VARS or command args not valid solutions? I would take a long hard look at any process that required auth. credentials to be store on a machines file system. I do not know anything about the process at hand of course, it just sounds... not safe.

**Comment by zingyb** [comment]
Rather than managing the password encryption itself I imagine that flyway could instead wrap around e.g. gpg - no need to reinvent the wheel. For example, Flyway could be altered to accept stdin and the following could work:

```
gpg -q --decrypt conf/blah.conf.gpg | flyway info -configFiles=conf/blah.conf -password=-
```

**Comment by zingyb** [comment]
Rather than managing the password encryption itself I imagine that flyway could instead wrap around e.g. gpg - no need to reinvent the wheel. For example, Flyway could be altered to accept stdin and the following could work:

```
$ gpg -q --decrypt conf/blah.conf.gpg | flyway info -configFiles=conf/blah.conf -password=-
```

**Comment by MikielAgutu** [comment]
#2695 will allow this workflow, as @zingyb says. We'll document the solution when it's shipped.

**Comment by MikielAgutu** [comment]
Regarding https://github.com/flyway/flyway/issues/1194#issuecomment-590964001:
>Rather than managing the password encryption itself I imagine that flyway could instead wrap around e.g. gpg - no need to reinvent the wheel. For example, Flyway could be altered to accept stdin...

 This is now possible in Flyway 6.4. Thanks for the suggestion! https://flywaydb.org/blog/flyway-6.4

**Comment by Yogashri12** [comment]
how to encrypt password and user name in windows machine?
