### ISSUE TITLE
Build Error (Maven Version: Apache Maven 3.3.9)

### ISSUE THREAD

**Issue by asiripurapu** [flyway/flyway#1195]
Hi Alex,
Getting the following error ...while trying to build the 4.0 code.
[ERROR] Failed to execute goal on project flyway-core: Could not resolve dependencies for project org.flywaydb:flyway-core:jar:0-SNAPSHOT: Failed to collect dependencies at com.oracle:ojdbc6:jar:12.1.0.1: Failed to read artifact descriptor for com.oracle:ojdbc6:jar:12.1.0.1: Could not transfer artifact com.oracle:ojdbc6:pom:12.1.0.1 from/to flyway-repo (s3://flyway-repo/release): The S3 wagon needs AWS Access Key set as the username and AWS Secret Key set as the password. eg:
[ERROR] <server>
[ERROR] <id>my.server</id>
[ERROR] <username>[AWS Access Key ID]</username>
[ERROR] <password>[AWS Secret Access Key]</password>
[ERROR] </server>

Could you please help?

**Comment by axelfontaine** [comment]
Follow the instructions here and everything will work as expected: http://flywaydb.org/contribute/code/
