### ISSUE TITLE
Oracle 12c ORA-14656 Error

### ISSUE THREAD

**Issue by sqldbguy** [flyway/flyway#1205]
I'm using the Flyway 3.2.1 command line  to run a "clean" command against an oracle 12c database  schema and I get an "ORA-14656: cannot drop the parent of a reference-partitioned table" error.

Just to be specific, I'm executing "flyway -user=xxx -password=yyyy clean" from a windows 8 laptop against an oracle 12c database running on top of linux.

**Comment by davidkarlsen** [comment]
Does this duplicate  #178 ?

**Comment by sqldbguy** [comment]
Yes it does. I didn't find the earlier issue. closing this issue as a duplicate.
