### ISSUE TITLE
Custom comparator for repeatable migrations

### ISSUE THREAD

**Issue by ericparton** [flyway/flyway#1206]
Hello,

Thanks for all of the work that you've done on flyway! I've been looking forward to all of the cool new features in Flyway 4.0 and I've been playing around with the latest version of the code to see how I might be able to use it in the future. 

I'm faced with a situation where it would be useful to have the ability to always apply one or more repeatable migrations before any versioned migrations so that the versioned migrations can all make use of a number of version controlled functions/stored procedures.

Allowing users to supply a custom MigrationInfo comparator that would only be used to compare repeatable migrations would make it possible to run repeatable migrations in any desired order. Just as an example, repeatable migrations in a "procedures" subdirectory could always be run before all other migrations, while repeatable migrations in a "views" subdirectory could always be run after all other migrations, etc.

I have a barebones implementation of this feature in [this fork](https://github.com/ericparton/flyway/commit/a72fc4968babdd1db1337b8d61ef0b2c0fb9da45), and I would be happy to submit a pull request after adding tests and the plugin configurations if you think that this would be a worthwhile contribution.

Thanks

**Comment by axelfontaine** [comment]
Hi Eric,

Thanks for giving the repeatable migrations a try. What you describe can already be achieved, albeit in two passes:
- first run flyway migrate -target=current (applies all repeatable migrations whose checksums have changed)
- then run flyway migrate again to apply all remaining new versioned migrations

I am therefore reluctant to add the custom comparator feature to the core distribution.

Best regards,
Axel

**Comment by alkamo** [comment]
I'm finding that I would use this functionality. I have two scenarios where this would be useful:

I have files that contain all of the synonyms and grants that I'd like to ensure run last (so I can be sure they run after all objects have been created). I can manually do this by naming these files something like `R__ZZZZZ_Privileges.sql`, but that's more of a workaround than a solution in my view.

Additionally, I have many packages that are split into two files: specification and body. These were originally differentiated by extension ("pks" and "pkb" respectively). Since Flyway needs a consistent extension, we're simply tacking a ".sql" extension after the original. So, for package `example`, the two files are `R__example.pkb.sql` and `R__example.pks.sql`. Of course, since they are resolved in alphabetical order, the body is executed before the specification.

There are functional solutions for both of these issues, but being able to set a custom sort order would nicely solve both of them.

**Comment by egil** [comment]
@alkamo, I am considering flywaydb and too would like to keep my package definition and body separate as it is custom in Oracle space. I am wondering if this is solveable with a custom resolver, that resolves the definition (pks) and body (pkb) in the desired order?

**Comment by bye4u** [comment]
I have a number of similar problems.
a. 
Can not specify startup order by:
1. version migration (added the field to table)
2. repeatable migration (procedure change)
3. version migration: update data (run the procedure from step 2)

b.
During merging between branches of git (dev => test => prod): the order of the scripts is lost, if there are repeated migrations. Сommits are grouping  into one and repeatable migrations is run at the end.

Is it possible to specify in the version migration (via placeholders maybe) or somehow differently that the next one is to run a certain repeatable migration ?

**Comment by arlowhite** [comment]
Yes, the alphasort is a bit annoying and you can't have the same name because the "description" part of the file must be unique. So I do this:

**flyway.conf**
`flyway.sqlMigrationSuffixes=.sql,.pks,.pkb`

For each package:
- R__foo.pks
- R__foo_body.pkb

**Comment by MikielAgutu** [comment]
Related to #2174

**Comment by MikielAgutu** [comment]
It's possible to define execution order with the [`cherryPick` option](https://flywaydb.org/documentation/configuration/parameters/cherryPick) that was introduced in version 7. This means you can specify exactly which migrations to execute per `migrate` run. Note the ordering remains the same, so you'll have to cherry pick with migrate one at a time if you need very specific ordering for many scripts, e.g;

```
flyway migrate -cherryPick=firstRepeatable
flyway migrate -cherryPick=secondRepeatable
flyway migrate -cherryPick=2 // versioned migration
flyway migrate -outOfOrder=true // Everything else
```

I think this is a good solution for @ericparton , given the requirement to run 'one or two' repeatables before the main migration run.

What do you all think? Can cherry pick solve your problems with deployment ordering?

**Comment by DoodleBobBuffPants** [comment]
See https://github.com/flyway/flyway/issues/3030 for anything related to migration ordering
