### ISSUE TITLE
Allow "migrateUpTo" option for migrate

### ISSUE THREAD

**Issue by mweksler** [flyway/flyway#1207]
Flyway currently migrates all available migrations it can find. It would be useful if you could tell it to only migrate up to a certain version.
This is of particular use when using auto-generated database access classes, e.g. [jooq] (http://www.jooq.org/).

The scenario:

1. Current db version is 7. Auto generated db access code is compatible with 7.
2. New migration version 8 is available. 
3. To build an artifcat with the migration version 8 that is still compatible with the database that is in production, the auto generator needs to use version 7 of the database. So it would need to tell flyway to migrate the build db up to version 7 only.
4. The artifact gets pushed to production.
5. Flyway migrates the production db to version 8.
6. A new build tells flyway to migrate the build db to version 8, and code can now use the new schema.

If this looks like a good feature to add, I'm happy to collaborate on making it happen.

**Comment by axelfontaine** [comment]
This is what flyway.target is for.
