### ISSUE TITLE
Rewrite Gradle plugin in Java

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#1215]

**Comment by alkamo** [comment]
I don't think there's any harm in converting the majority of the plugin to Java, but it could introduce some issues with the plugin class itself. There are some things that Gradle does that that use Groovy idioms that I think would be difficult to access in Java.

A key example is rule-based tasks. While it is probably possible to implement them in Java, I think trying to do so would result in unnecessarily complex code.

**Comment by axelfontaine** [comment]
Done
