### ISSUE TITLE
Parsing of string literals

### ISSUE THREAD

**Issue by mabrarov** [flyway/flyway#1216]
# Description
I have an issue with this script:
```sql
ALTER TRIGGER CUSTOMER_INSERT ON CUSTOMER AFTER
INSERT AS
BEGIN
    SELECT TOP 1 1 FROM CUSTOMER WHERE [name] LIKE'%test';
END
GO
```
It makes Flyway maven plugin to fail and produce this output:
```
[ERROR] SQL State  : 42000
[ERROR] Error Code : 102
[ERROR] Message    : Incorrect syntax near 'GO'.
```
At the same time SQL Server Management Studio (the one shipped with SQL Server 2008 R2) executes this script without errors and modifies the trigger.

If I modify the script this way (if I add whitespace between `LIKE` and `'%test'`):
```sql
ALTER TRIGGER CUSTOMER_INSERT ON CUSTOMER AFTER
INSERT AS
BEGIN
    SELECT TOP 1 1 FROM CUSTOMER WHERE [name] LIKE '%test';
END
GO
```
then Flyway maven plugin applies the script successfully.
# Repro project
https://github.com/mabrarov/flyway-678/tree/feature/string_literal_parsing_error (i.e.feature/string_literal_parsing_error branch)
# Environment
Tested with 
* Java(TM) SE Runtime Environment (build 1.7.0_72-b14).
* Apache Maven 3.2.3.
* SQL Server 2008 R2 Developer edition.

**Comment by mabrarov** [comment]
It seems (tested with [SQL Maven Plugin](http://www.mojohaus.org/sql-maven-plugin)) that this issue is not related to JDBC driver (JTDS is used).

**Comment by axelfontaine** [comment]
Thanks for the excellent analysis! Fixed.
