### ISSUE TITLE
Command line interface does not work without "drivers" folder present

### ISSUE THREAD

**Issue by biran0079** [flyway/flyway#1218]
I am trying to invoke flyway command line interface through `flyway-commandline.jar`, but it complains about not finding `drivers` folder. 
I did pass jdbc driver class through class path. I think this should be a legit use case, and the `drivers` folder should be optional.

**Comment by axelfontaine** [comment]
Thanks for reporting this. What was the reason you needed another driver? And how exactly did this fail?

**Comment by ricardo-s-ferreira** [comment]
I've the same problem. For organization issue I want put all jar files in one folder called lib, but the command line failed if the folder drivers doesn't exist. "Directory for Jdbc Drivers not found: ..../drivers"

**Comment by axelfontaine** [comment]
You can leave an empty folder to save space or use the Java API if you want more control.

Won't fix.
