### ISSUE TITLE
Don't support encoding comments in MySql tables

### ISSUE THREAD

**Issue by AlmazKo** [flyway/flyway#1225]
###### What version of Flyway are you using?

 3.2.1  & 4.0
###### What database are you using (type & version)?

MySql   5.6.28-0ubuntu0.15.04.1
###### What operating system are you using?

Ubuntu 15.04
###### What did you do?

my gradle.properties:

```
flyway.user=root
flyway.password=SOME_PASSWORD
flyway.encoding=UTF-8
flyway.url=jdbc:mysql://localhost:3306/some_db
```

I executed in gradle task 'flywayMigrate'
###### What did you expect to see?

``` sql
CREATE TABLE `user_groups` (
  `id`    INT(10),
  `name`  VARCHAR(12) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = 'user groups - Группы счетов';
```
###### What did you see instead?

``` sql
CREATE TABLE `user_groups` (
  `id` int(10) NOT NULL DEFAULT '0',
  `name` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='user groups - ?????? ??????'
```

**Comment by axelfontaine** [comment]
Thanks. Are you sure the original migration files are UTF-8 encoded? Could you post a small GitHub repo that reproduces the issue?

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter

**Comment by tagackt** [comment]
I resolved a similar issue.  
I changed character_set_server of mysql setting from latain to utf8.
