### ISSUE TITLE
Resources not found from bundles without wiring to org.osgi.framework

### ISSUE THREAD

**Issue by renat-sabitov** [flyway/flyway#1227]
###### What version of Flyway are you using?
4.0.0-20160210

###### What did you do?
There are three bundles - flyway, "migration service provider"  and "migration service consumer"

*migration service provider* - provides a service to migrate schema

*migration service consumer* - has migration resources and consumes service via OSGI blueprints to migrate itself. Note here that migration service consumer doesn't have any wiring to org.osgi.framework.

When flyway tries to find out if OSGI framework available or not, it checks for org.osgi.framework.Bundle class to be available in *migration service consumer* classloader, which is not available.

It would make much more sense to check if the class available in flyway's classloader.

###### What did you expect to see?
resources scanned properly

###### What did you see instead?
DEBUG - 09:52:10,126 - ywaydb.core.internal.util.scanner.classpath.ClassPathScanner - [rdbms-schema-task-0] - Scanning URL: bundle://55.0:1/db/migration
DEBUG - 09:52:10,126 -              org.flywaydb.core.internal.util.FeatureDetector - [rdbms-schema-task-0] - JBoss VFS v2 available: false
DEBUG - 09:52:10,127 -              org.flywaydb.core.internal.util.FeatureDetector - [rdbms-schema-task-0] - JBoss VFS v3 available: false
DEBUG - 09:52:10,127 -              org.flywaydb.core.internal.util.FeatureDetector - [rdbms-schema-task-0] - OSGi framework available: false
 WARN - 09:52:10,140 - ywaydb.core.internal.util.scanner.classpath.ClassPathScanner - [rdbms-schema-task-0] - Unable to scan location: /db/migration (unsupported protocol: bundle)

**Comment by axelfontaine** [comment]
Can you work around this by explicitly setting flyway.setClassloader(..)?

**Comment by renat-sabitov** [comment]
I'm setting the classloader to the "migration service consumer" bundle, which contains migration resources but doesn't have org.osgi.framework in it.

**Comment by renat-sabitov** [comment]
As for now the workaround is to add an explicit Import-Package requirement for org.osgi.framework

**Comment by renat-sabitov** [comment]
PR: https://github.com/flyway/flyway/pull/1228

Also, this test case displays our usage of flyway, it'd be awesome if you merged it 
https://github.com/flyway/flyway/pull/1204

**Comment by axelfontaine** [comment]
Fixed by PR.
