### ISSUE TITLE
Feature: allow FlywayConfiguration to hold Properties

### ISSUE THREAD

**Issue by jangalinski** [flyway/flyway#1229]
I am using ConfigurationAware to access the configuration in my JdbcMigration class. However, I depend on some properties that I configure via resources (pattern to identify sql files, databaseType, ...). Since I do not have controll over creation of the migration instance, I would love to use the aware-hook to access properties of my application. 
Today this is not possible. 

Idea: Allow "setProperties" on Flyway.class and transport those properties (default: empty) via flywayConfiguration.

**Comment by axelfontaine** [comment]
Related to #1200 and #1201
