### ISSUE TITLE
SQL based databased init script does not work when prepended as V1__bootstrap.sql

### ISSUE THREAD

**Issue by bkco** [flyway/flyway#1230]
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
"PostgreSQL 9.3.5 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit"

###### What operating system are you using?
Ubuntu 15.04

###### What did you do?
1. Download this: https://github.com/kabisa/dokku-boot-demo
2. Edited application.properties file by adding this:
   flyway.baseline-on-migrate=true
3. Follow instructions on readme to compile and run.

###### What did you expect to see?
1. Expected database table to be created.

###### What did you see instead?
1. No table created.... problem is the script V1__bootstrap.sql did not run and the table "quotes" was not created.
2. Work around solution was rename V1__bootstrap.sql to V2_bootstrap.sql
3. Table creation successfully worked then.

**Comment by axelfontaine** [comment]
Baseline is for existing databases only. Your step number 2 caused this to fail.

Works as designed.
