### ISSUE TITLE
How can I use classpath feature in migrate ant target?

### ISSUE THREAD

**Issue by husnusenturk** [flyway/flyway#1234]
###### What version of Flyway are you using?
3.2.1 or 4.0

###### What database are you using (type & version)?
oracle 11.2.0.4.0

###### What operating system are you using?
linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
- I created db/migration directories under my-project/src/main/resources
- I put V1__test.sql file under db/migration/ directory
- Builded my project. I have my-project.jar package.
- When I extract my-project.jar package, I can see db/migration/V1__test.sql
- I try to use classpath feature for locations but I took "Unable to resolve location classpath:db/migration" error.

Where should I put my-project.jar in migrate ant target?
What should I write to lyway.locations value in migrate ant target?

###### What did you expect to see?
I expected to migrate sql files from my-project.jar without extract its content anywhere.

###### What did you see instead?
I took "Unable to resolve location classpath:db/migration" error.

**Comment by vitalibr** [comment]
I'm having the same problem @husnusenturk

**Comment by axelfontaine** [comment]
Add your jar to the Flyway classpath (as described in the usage section) and everything should work as expected: https://flywaydb.org/documentation/ant/

**Comment by husnusenturk** [comment]
Thanks for your help.
