### ISSUE TITLE
Publish Gradle plugin version 4.0 to https://plugins.gradle.org/plugin/org.flywaydb.flyway

### ISSUE THREAD

**Issue by WolverineFan** [flyway/flyway#1239]
###### What version of Flyway are you using?

4.0

###### What database are you using (type & version)?

Oracle

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

plugins {
    id "org.flywaydb.flyway" version "4.0"
}

###### What did you expect to see?

Download the plugin

###### What did you see instead?

Plugin was missing

**Comment by axelfontaine** [comment]
Plugin reclaimed and 4.0 published
