### ISSUE TITLE
Add a goal to do an SQL backup before the migration

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#124]
_Original author: Sebastie...@gmail.com (March 21, 2012 08:12:49)_

It would be great if flyway could do an SQL backup of the database before the migration.
With the maven plugin, the backup file should be saved by default in the target directory.

In the same idea, an option or goal to execute the backup if the migration failed (with a truncate before ?).
A third parameter to failed the maven build or not if the migration failed and the backup was execute without error. By default, the build should failed if the migration failed.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=233_

**Comment by axelfontaine** [comment]
This should now be possible with callbacks and some custom code. Closing.
