### ISSUE TITLE
Postgres URL does not support new schema param

### ISSUE THREAD

**Issue by Jeetah** [flyway/flyway#1240]
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
Postgres 9.4

###### What operating system are you using?
OSX

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Specified new schema param:
jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema

###### What did you expect to see?
Successful migration.

###### What did you see instead?
15:27:20.633 WARN [restartedMain] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext [?:?:?] Exception encountered during context initialization - cancelling refresh attempt Exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [applicationContext.xml]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Error restoring current schema to its original setting
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
...
Caused by: org.postgresql.util.PSQLException: No value specified for parameter 1.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:225)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:190)

-> Seems like to work only with old notation:
jdbc:postgresql://localhost:5432/mydatabase?searchpath=myschema
as well as with both:
jdbc:postgresql://localhost:5432/mydatabase?searchpath=myschema?currentSchema=myschema

**Comment by axelfontaine** [comment]
The URL is something your PG driver parses and manages. Flyway has no control over this. I suggest you file an issue with them.

Cheers
Axel
