### ISSUE TITLE
Flyway source won't build due to missing sqlline indirect dependency

### ISSUE THREAD

**Issue by PredatorVI** [flyway/flyway#1241]
I've pulled the latest source as of March 14, 2016 (commit# 36091a0eba2f0dc2f3860b029fa617412247bb7f) and am attempting to build/test a change.

I've been looking at the [Dev Environment Setup](https://flywaydb.org/documentation/contribute/code/setup) and [Database Setup](https://flywaydb.org/documentation/contribute/code/database) pages to get the process going but keep hitting the error below when compiling flyway-core using the command-line:

C:\Dropbox\Projects\3rdParty\flyway>**mvn -U clean install -DskipTests -Dmaven.tes
t.skip=true -P-InstallableDBTest,-CommercialDBTest,-CommandlinePlatformAssemblie
s**

> **[ERROR] Failed to execute goal on project flyway-core: Could not resolve dependencies for project org.flywaydb:flyway-core:jar:0-SNAPSHOT: Could not find artifact sqlline:sqlline:jar:1.1.8 in nexus**

Full output available at [out.txt](https://github.com/flyway/flyway/files/174283/out.txt).

The code I'm interested in is really the command-line client so I really don't need/want any of the database stuff at this point, so I've attempted to prevent all tests from both compiling (-Dmaven.test.skip=true) or running (-DskipTests) per the [Surefire documentation](https://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-test.html), but the error still happens.

The only version of sqlline available in Maven Central is [sqlline:sqlline:1.1.9](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22sqlline%22) and I'm unaware of another way to get v1.1.8.

**Comment by axelfontaine** [comment]
Please give the latest version a go. Thanks, Axel
