### ISSUE TITLE
Flyway 4.0 config Postgres requires user/pass

### ISSUE THREAD

**Issue by krispii** [flyway/flyway#1245]
###### What version of Flyway are you using?
4.0 (command line)

###### What database are you using (type & version)?
Postgres 9.4.x (x=5 as of this writing)

###### What operating system are you using?
Ubuntu 15.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I left the ```flyway.user``` and ```flyway.password``` out of my config file in order to not have them available for all to see as our flyaway configs and evolutions are in a Git repo

###### What did you expect to see?

As per the documentation (https://flywaydb.org/documentation/commandline/) I expected to be prompted for credentials.

###### What did you see instead?
STDOUT: ERROR: Unable to obtain Jdbc connection from DataSource (jdbc:postgresql://localhost/krispii_dev) for user 'null': The server requested password-based authentication, but no password was provided.

**Comment by axelfontaine** [comment]
There was a last minute bug that got introduced in #724 and that has now been fixed. This will be part of 4.0.1. You can of course build from source until then.
