### ISSUE TITLE
Cannot create multiple schemas from single flywayMigrate call where each schema in separate project

### ISSUE THREAD

**Issue by bluegod359** [flyway/flyway#1252]
###### What version of Flyway are you using?

4.0
###### What database are you using (type & version)?

SQL Server 2014
###### What operating system are you using?

Windows 7
###### What did you do?

I have a number of subprojects for each Schema in the database, the below works but only for one subproject specified in the settings.gradle. If I remove the subproject whose schema get's created, and rerun then the other is created. Seems like some issue with the migrate where I can't call it repeatedly.

subprojects {
    task createSchema << {
        doFirst {
            flyway {
                url = project.url
                driver = project.driver
                user = project.user
                password = project.password
                schemas = [project.schema]
                def schemaUpgradeLoc = 'filesystem:' + project.projectDir + '/schema_upgrade'
                def storedprocsLoc = 'filesystem:' + project.projectDir + '/storedprocs'
                println "schemaUpgradeLoc-->" +  schemaUpgradeLoc
                locations = [ schemaUpgradeLoc, storedprocsLoc ]
            }
        }
        doLast {
            println "Upgrading Database Schema-->" + project.schema
            flywayMigrate.execute()
        }
    }

}
###### What did you expect to see?

I was expecting to see, schema created for all subprojects.

**Comment by bluegod359** [comment]
Just wondering if the below from https://flywaydb.org/documentation/faq.html could help, me (but since I'm new to gradle and flywaydb not sure what to tdo)

If you have multiple identical schemas, say one per tenant, invoke Flyway in a loop and change flyway.schemas to match the name of the schema of the current tenant.

How do you invoke Flyway in a loop in gradle, sorry about the stupid question.

**Comment by alayor** [comment]
@bluegod359 did you solve your question? I have the same problem.

**Comment by axelfontaine** [comment]
Related to #1039

**Comment by juliahayward** [comment]
Largely superseded by #2995 - I'm not sure how to achieve the desired effect in gradle, but if we can add a configuration option to iterate over the schemas this should be resolved.
