### ISSUE TITLE
gradle flywayMigrate failes with alter table syntax (using H2)

### ISSUE THREAD

**Issue by sandakith** [flyway/flyway#1253]
###### What version of Flyway are you using?
        classpath 'org.flywaydb:flyway-gradle-plugin:3.2.1'

###### What database are you using (type & version)?

        classpath 'com.h2database:h2:1.3.170'

###### What operating system are you using?

gradle 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

 gradle --version 

------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Linux 3.19.0-51-generic amd64

 uname -a
Linux vbox 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

###### What did you expect to see?

Please see the following info ... 
http://stackoverflow.com/questions/36165437/gradle-flywaymigrate-failes-with-alter-table-syntax-using-h2

**Comment by axelfontaine** [comment]
This is an issue in either the H2 JDBC driver or server. Not much we can do here.

**Comment by sandakith** [comment]
Not sure, but seems not be since its web console works well, ...

**Comment by sandakith** [comment]
I verified that it was an issue with h2 1.3.* drivers and in 1.4.* driver it was fixed. Thanks
