### ISSUE TITLE
Support custom maintenance scripts

### ISSUE THREAD

**Issue by Nthalk** [flyway/flyway#1254]
How about a new callback: insteadOfClean.sql?

I have a multi-product, co-mingled schema, and clean is a bit... heavy handed.

With the new callbacks, I can replace all of my supporting scripts except my reset-database (single product) script.

Any interest in a: insteadOfClean.sql?

**Comment by axelfontaine** [comment]
What you are really asking for is the ability run a custom script. Let's leave this open and see if this gathers support.

**Comment by aheuermann** [comment]
This would be very useful. Relates to #1086
