### ISSUE TITLE
Issue with create schema_version for Sybase ASE

### ISSUE THREAD

**Issue by hntran8** [flyway/flyway#1255]
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
Sybase ASE 16.0

###### What operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Flyway failed to create the schema_version table. There seems to be a bug in this file: flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/sybaseASE/createMetaDataTable.sql

Those two lines should be removed as part of the Issue #128 

CREATE INDEX ${table}_vr_idx ON ${table} (version_rank)
go

CREATE INDEX ${table}_ir_idx ON ${table} (installed_rank)
go

###### What did you expect to see?
Expect the schema_version table to be created successfully

###### What did you see instead?
Flyway failed to create schema_version table

**Comment by axelfontaine** [comment]
Thanks for pointing this out! Fixed.
