### ISSUE TITLE
Publish deb package for Ubuntu

### ISSUE THREAD

**Issue by ikle-tiskok** [flyway/flyway#1258]
Is it possible?

**Comment by axelfontaine** [comment]
Not that I know of. Want to step up and create a package?

**Comment by ckchow** [comment]
I could do this, but setting up the deploy from Travis to Launchpad should probably be done by the maintainer since you have to generate some keys on github.  https://docs.travis-ci.com/user/deployment/launchpad/

**Comment by axelfontaine** [comment]
Duplicate of #734
