### ISSUE TITLE
Unit test failing for Phoenix DB support

### ISSUE THREAD

**Issue by anirudha13** [flyway/flyway#1262]
###### What version of Flyway are you using?

Flyway version 4.0
###### What database are you using (type & version)?

Phoenix - 4.6
###### What operating system are you using?

Mac OS X
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Running the PhoenixMigrationMediumTest, when trying to build flyway with a particular version of Phoenix. Command used from the **flyway-core** module,
**mvn clean install -P-InstallableDBTest -P-CommercialDBTest -P-CommandlinePlatformAssemblies -PPhoenixDBTest -Dmaven.failsafe.debug -Dmaven.surefire.debug -Dtest=PhoenixMigrationMediumTest#repairChecksum**
###### What did you expect to see?

Build should pass successfully.
###### What did you see instead?

Build failed with the error,
`Running org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 306.38 sec <<< FAILURE! - in org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest
repairChecksum(org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest)  Time elapsed: 306.38 sec  <<< ERROR!
org.flywaydb.core.api.FlywayException: Unable to update checksum in metadata table "schema_version" for version 1 to -84236181`

This seems to happen because the **schema_version** table in Phoenix is created using the script,

> -- Create table
> CREATE TABLE "${schema}"."${table}" (
>     "version" VARCHAR(50),
>     "installed_rank" INTEGER NOT NULL PRIMARY KEY,
>     "description" VARCHAR(200),
>     "type" VARCHAR(20),
>     "script" VARCHAR(1000),
>     "checksum" INTEGER,
>     "installed_by" VARCHAR(100),
>     "installed_on" TIMESTAMP,
>     "execution_time" INTEGER,
>     "success" BOOLEAN
> );

But the update checksum script is,

> -- Update checksum for a version
> UPSERT INTO "${schema}"."${table}" (
>     "version",
>     "checksum"
> ) VALUES (
>      '${version_val}',
>      ${checksum_val}
> );

**Comment by axelfontaine** [comment]
@jmahonin Thoughts?

**Comment by jmahonin** [comment]
This commit appears to have modified the createMetaData.sql script in a way that Phoenix doesn't like:
https://github.com/flyway/flyway/commit/3bc7dc3c9b3b39a4af344333a5b7cfe7792b32a4

Will investigate further and attempt a patch.

**Comment by jmahonin** [comment]
So the issue was actually the updateChecksum.sql query. Basically Phoenix does an UPDATE via 'UPSERT ... SELECT ...', and it always has to reference the primary key.

Pull request gets all the unit tests running again for me.

**Comment by MikielAgutu** [comment]
When we work on https://github.com/flyway/flyway/issues/2112 we'll ensure this is fixed.

**Comment by Lyeeedar** [comment]
The code has changed a lot since this was created, closing as being out of date.
