### ISSUE TITLE
Flyway forces metadata table (schema_version) to have case-sensitive names on Oracle

### ISSUE THREAD

**Issue by mjs510** [flyway/flyway#1267]
I'm using flyway 4.0 with oracle 11.2.0.4.0.

When flyway creates the the metadata table with its default name, it specifically sets it to lower case. The same is true for the table's columns. This causes the table name and columns to become case sensitive on Oracle. This is unusual, and can lead to confusion and errors.

When creating the table, Flyway causes DDL similar to the following to be used:
```
CREATE TABLE "<schema>"."schema_version" ("installed_rank" NUMBER(*,0) NOT NULL ENABLE, "version" VARCHAR2(50 BYTE), "description" VARCHAR2(200 BYTE) NOT NULL ENABLE, "type" VARCHAR2(20 BYTE) NOT NULL ENABLE, "script" VARCHAR2(1000 BYTE) NOT NULL ENABLE, "checksum" NUMBER(*,0), "installed_by" VARCHAR2(100 BYTE) NOT NULL ENABLE, "installed_on" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, "execution_time" NUMBER(*,0) NOT NULL ENABLE, "success" NUMBER(1,0) NOT NULL ENABLE,  CONSTRAINT "schema_version_pk" PRIMARY KEY ("installed_rank");
```

By surrounding the table and column names in double quotes, they are forced to be lower case. This means that the following sql fails on oracle:

`select * from schema_version`

Instead, you have to run:

`select * from "schema_version"`

You also cannot run the following:

`select checksum from "schema_version"`

Instead, you have to say:

`select "checksum" from "schema_version"`

This is a source of some confusion!

It would be better if flyway did not double quote the table and column names when creating the metadata table on Oracle. This would then allow them to be treated as case-insensitive on Oracle, and the following would all work:

`select * from SCHEMA_VERSION`
`select * from schema_version`
`select CHECKSUM from schema_version`

etc

**Comment by axelfontaine** [comment]
Works as designed. See the FAQ entry: https://flywaydb.org/documentation/faq#case-sensitive

The table is an internal implementation detail that should not be relied upon from your code.
