### ISSUE TITLE
Adding support for unit testing

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#127]
_Original author: shrey.aw...@gmail.com (September 04, 2012 11:33:36)_

Hi,
   If you are not already working on this, I would suggest to add support in flyway for unit testing data patches. This will enable anyone to easily verify that database is changed as expected and flyway has applied patch correctly. Of-course this can be checked from metadata table as well, but its always good to verify in detail using tests for complex patches.

Thanks,
Shrey

_Original issue: http://code.google.com/p/flyway/issues/detail?id=321_

**Comment by axelfontaine** [comment]
Closing obsolete issue
