### ISSUE TITLE
Vertica does not support repeatable migrations.

### ISSUE THREAD

**Issue by mezuzza** [flyway/flyway#1270]
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
Vertica v7.2.1

###### What operating system are you using?
Mac, but specifically in a docker container

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Create a series of versioned migrations: V1__foo.sql
Create a repeatable migration: R__bar.sql
Run flyway migrate.

###### What did you expect to see?
A successful run with the repeatable migration added.

###### What did you see instead?
Migration fails trying to add the repeatable migration since schema_version table requires version to not be null.

###### Additional Details
I suspect Vertica support for repeatable migrations works if upgrading from flyway-3.0 to flyway-4.0, but not if you start from flyway-4.0.

To fix, simply need to remove the `NOT NULL' constraint from `flyway/flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/vertica/createMetaDataTable.sql'.

**Comment by axelfontaine** [comment]
Good catch! Fixed.
