### ISSUE TITLE
Document SBT custom configuration usage

### ISSUE THREAD

**Issue by sourcesmith** [flyway/flyway#1275]
Observed with Flyway-sbt 4.0.

A custom configuration with flyway specific settings was created, including url, username and password.  This was verified by show and inspect

```
> show local-deployment:flywayUrl
[info] jdbc:postgresql://localhost:5432/db

> inspect local-deployment:flywayUrl
...
[info] Delegates:
[info] 	local-deployment:flywayUrl
[info] 	deployment-internal:flywayUrl
[info] 	runtime:flywayUrl
[info] 	compile:flywayUrl
[info] 	*:flywayUrl
[info] 	{.}/local-deployment:flywayUrl
[info] 	{.}/deployment-internal:flywayUrl
[info] 	{.}/runtime:flywayUrl
[info] 	{.}/compile:flywayUrl
[info] 	{.}/*:flywayUrl
[info] 	*/local-deployment:flywayUrl
[info] 	*/deployment-internal:flywayUrl
[info] 	*/runtime:flywayUrl
[info] 	*/compile:flywayUrl
[info] 	*/*:flywayUrl
...
```

When a flyway task is executed scoped to a custom configuration rather than the task being actioned, the following error was displayed:

```
> local-deployment:flywayInfo
[info] Flyway 4.0 by Boxfuse
[trace] Stack trace suppressed: run last *:flywayInfo for the full output.
[error] (*:flywayInfo) org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
[error] Total time: 1 s, completed 08-Apr-2016 12:01:51
```

From the sbt plugins best practise, hence the expectation the task should have actioned correctly:

> "a plugin should strive to support multiple configurations, including those created by the build user. Some tasks that are tied to a particular configuration can be re-used in other configurations. While you may not see the need immediately in your plugin, some project may and will ask you for the flexibility."

**Comment by axelfontaine** [comment]
@cdedie Thoughts?

**Comment by sourcesmith** [comment]
Having looked into the implementation of sbt plugins in general and the source of the Flyway plugin, I see that this is possible, so this has become a documentation issue.  I suggest that the SBT Overview page includes a section for custom configurations:

## Custom Configurations

The **flywayBaseSettings** value of the Flyway plugin provides base configuration and task definitions for the plugin.  This can be reused in custom configurations other than the those provided for the runtime and test configurations, if projects require it.  These settings may be reused as follows:

```
import org.flywaydb.sbt.FlywayPlugin

lazy val CustomConfig = config("custom") describedAs "A custom config." extend Runtime

lazy val localDeploymentSettings: Seq[Def.Setting[_]] = Seq(
  flywayUser := "customUser",
  flywayPassword := "customPassword",
  flywayUrl := "jdbc:driver://host:port/db",
   ...
)

lazy val app = (project in file("app")).
  settings(inConfig(CustomConfig)(FlywayPlugin.flywayBaseSettings(CustomConfig)): _*)
```

The configuration passed to flywayBaseSettings is use to derive the classpath for locating migrations implemented in Java.

**Comment by axelfontaine** [comment]
Thanks! Docs updated.

**Comment by autodidacticon** [comment]
This may be an sbt question, but where would the custom configurations in the above example be used? build.scala?

**Comment by edmondo1984** [comment]
Hello, when I try to use the suggested file I get a number of undefined settings,

References to undefined settings: 

  app/custom:fullClasspath from app/custom:flywayBaseline ((org.flywaydb.sbt.FlywayPlugin) FlywayPlugin.scala:202)

  app/custom:fullClasspath from app/custom:flywayInfo ((org.flywaydb.sbt.FlywayPlugin) FlywayPlugin.scala:189)

  app/custom:fullClasspath from app/custom:flywayValidate ((org.flywaydb.sbt.FlywayPlugin) FlywayPlugin.scala:186)

  app/custom:fullClasspath from app/custom:flywayRepair ((org.flywaydb.sbt.FlywayPlugin) FlywayPlugin.scala:196)

  app/custom:fullClasspath from app/custom:flywayMigrate ((org.flywaydb.sbt.FlywayPlugin) FlywayPlugin.scala:183)

Is there anything missing in the doc?

**Comment by alexnikitchuk** [comment]
@edmondo1984 I've faced the same error and fixed that by changing 
`FlywayPlugin.flywayBaseSettings(CustomConfig)` 
to 
`FlywayPlugin.flywayBaseSettings(Runtime)`

**Comment by binshi** [comment]
Currently I am getting 
org.flywaydb.core.api.FlywayException: Unable to instantiate JDBC driver: org.postgresql.Driver => Check whether the jar file is present

Am I missing anything in the above setting?
