### ISSUE TITLE
The fact that repeatable migrations are applied after versioned migrations should be documented explicitly

### ISSUE THREAD

**Issue by akobiakov** [flyway/flyway#1277]
Currently there is no statement anywhere in the documentation about an order in which versioned and repeatable migrations are applied. Would be great to explicitly document the fact that by default the repeatable migrations are always applied after the versioned ones.

**Comment by axelfontaine** [comment]
You are correct. There is definitely room for improvement here. Would you like to submit a PR against flyway/flywaydb.org ?

**Comment by maxsoelalberton** [comment]
@axelfontaine, I had a problem when I run a migration, a repeatable script run before the versioned ones. This problem can be ocurred because the migration are out of order?
P.S.: I need to execute out of order migrations.

**Comment by axelfontaine** [comment]
Please open a new issue with exact steps how to reproduce
