### ISSUE TITLE
3.2.1 upgrade to 4.0 on Oracle fails with ORA-01451: column to be modified to NULL cannot be modified to NULL

### ISSUE THREAD

**Issue by rrodo** [flyway/flyway#1278]
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
Oracle 11g (11.2.0.4)

###### What operating system are you using?
Windows 7 64bit

###### What did you do?
When trying to run Flyway 4.0 command line for the first time, the metadata table upgrade fails with:

Script failed
-------------
SQL State  : 72000
Error Code : 1451
Message    : ORA-01451: column to be modified to NULL cannot be modified to NULL
Line       : 21
Statement  : ALTER TABLE "schema_version" MODIFY "version" NULL

Oracle throws this error because "version" column is already NULL.  Even though it is defined as the primary key on the "schema_version" table, it is still null because the primary key constraint was applied with 'NOVALIDATE' option when initially created by flyway. Because the constraint isn't validated, the column definition remains as 'NULL'.

Here is the metadata table constraint from the flyway 3.0 install:
```
SELECT constraint_name,
       constraint_type,
       table_name,
       deferrable,
       validated,
       index_name
  FROM dba_constraints
 WHERE table_name = 'schema_version'
```

CONSTRAINT_NAME | TABLE_NAME | DEFERRABLE | VALIDATED | INDEX_NAME
 ---------------------------|--------------------|---------------------|----------------|-------------------
schema_version_pk | schema_version | NOT DEFERRABLE | NOT VALIDATED | schema_version_pk

`SELECT nullable
  FROM dba_tab_columns
 WHERE table_name = 'schema_version' 
 AND column_name = 'version'; `

NULLABLE | 
--------------|
Y|

###### What did you expect to see?
Expect to see the metadata table upgraded successfully without errors

###### What did you see instead?
The metadata table upgrade fails with an error

**Comment by axelfontaine** [comment]
No idea what happened to your installation (did you create the table manually yourself or was it modified?), but Flyway has always created the version column as NOT NULL: see https://github.com/flyway/flyway/blob/flyway-3.2.1/flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/oracle/createMetaDataTable.sql
