### ISSUE TITLE
Repeatable Migrations support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#128]
_Original author: ospy...@gmail.com (September 25, 2012 10:36:53)_

Hello,

and thanks a lot for the effort you put in flyway. We are currently searching for a solution as close as possible to the way we work:

DDL code is maintained in a number of files categorized mostly by type e.g. Tables.sql, Views.sql, while procedural code is kept in a Packages directory with one file per package e.g. Package1.sql, Package2.sql etc.

For Tables and Views changes are appended at the bottom of each file (starting with a comment with the issue number). Example Tables.sql:

...
... #  3453 Add column x
ALTER TABLE x ADD COLUMN y;

- Packages are edited in place and committed with a similar comment appended on the top of the file.

For us this is a very convenient setup, allowing to apply migrations after a specific issue - revision by opening a minimal set of files and copying from the desired line to the bottom of the file (or using the file as is for packages).

Is this a use case excluded from flyway initial design for some reason? Do you think it could be included at some point in the future? 

Thanks again, hope the above makes some sense!

_Original issue: http://code.google.com/p/flyway/issues/detail?id=336_

**Comment by KevinSheedy** [comment]
+1 flyway is great for DDL eg create table, alter table
However, it would be great if it had a built-in mechanism for redeploying procedures, functions etc from a **single source of the truth** in a git repo.

**Comment by axelfontaine** [comment]
Fixed.
