### ISSUE TITLE
Feature Request: new Callback: afterEachMigrateError

### ISSUE THREAD

**Issue by DanskerDave** [flyway/flyway#1283]
I'd like to see a Callback in org.flywaydb.core.api.callback.FlywayCallback to handle errors:
void afterEachMigrateError(Connection con, MigrationInfo info, SQLException e, Log log);
The change to DbMigrate.doMigrate(...) could look something like this...

> ```
>     try {
>       migrationExecutor.execute(connectionUserObjects);
>       LOG.debug("Successfully completed migration of " + migrationText);
>   }
>    catch (final Exception rethrowAfterCallback) {
>         for (final FlywayCallback callback : callbacks) {
>             try {
>                 dbSupportUserObjects.changeCurrentSchemaTo(schema);
>             }
>             catch (final Exception ignoreSchemaChangeException) {
>             }
>             callback.afterEachMigrateError(connectionUserObjects, migration, rethrowAfterCallback, LOG);
>         }
>         throw rethrowAfterCallback;
>     }
> ```
> 
> The Log argument may be a bad idea.
> Apart from that, if its as easy as that, I could help with some code...

**Comment by reda-alaoui** [comment]
Hello,
I think it would be great to allow those callbacks to prevent exception rethrow.
It would allow to create script that could fail without stopping the whole migration process.

**Comment by axelfontaine** [comment]
This should now be possible in Flyway 5.0.0 (coming soon) with custom error handlers.
