### ISSUE TITLE
Statement-level callbacks: before, after and after error

### ISSUE THREAD

**Issue by DanskerDave** [flyway/flyway#1289]
As I've been unable to find a way to process multiple queries with a single Statement in Oracle with JDBC, I assume that for Oracle somewhere in Flyway each *.sql file is parsed into a Collection of Statements before being executed one-by-one (in JdbcTemplate oder?).

If that is the case, it would be nice to have yet another pair of FlywayCallback methods...
before/afterEachMigrateStatement, say
...to handle each Statement.
The signature should be something like:
`void beforeEachMigrateStatement(Connection con, MigrationInfo info, ?String? statement);`

A Statement-level Error Callback similar to that described in [Feature Request #1283](https://github.com/flyway/flyway/issues/1283) would then be quite useful too...

**Comment by axelfontaine** [comment]
What exactly is your use case for this?

**Comment by DanskerDave** [comment]
Unfortunately it's nearly 2 years since I submitted the request & I haven't worked with flyway since.
As far as I recall, the main use I had at the time was Logging.
But I can imagine there may well be other use cases.

**Comment by axelfontaine** [comment]
@DanskerDave Thanks. I'm closing this now since there hasn't been anybody else in this time needing this.

**Comment by axelfontaine** [comment]
This has now been implemented with 6 new callbacks:

- `beforeEachMigrateStatement`
- `afterEachMigrateStatement`
- `afterEachMigrateStatementError`
- `beforeEachUndoStatement`
- `afterEachUndoStatement`
- `afterEachUndoStatementError`

They allow for
- statement validation against rules (no grants for example)
- regular maintenance after specific statements
- overriding errorhandling of specific statements
