### ISSUE TITLE
Clean does not delete procedures on case sensitive SQLServer

### ISSUE THREAD

**Issue by mrjeffjohnston** [flyway/flyway#1292]
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
SQL Server 2012.  Database collation is Latin1_General_CS_AS

###### What operating system are you using?
Windows

###### What did you do?
mvn flyway:clean

###### What did you expect to see?
That all procedures would be deleted in the managed schema.

###### What did you see instead?
No procedures were deleted.

The issue is caused by the call cleanRoutines("procedure") within SQLServerSchema.  In the INFORMATION_SCHEMA.ROUTINES table the ROUTINE_TYPE column is upper case.  The call needs to be changed to cleanRoutines("PROCEDURE").  Other parts of the class may have similar case issues.

**Comment by mrjeffjohnston** [comment]
Submitted pull request #1297 to fix

**Comment by axelfontaine** [comment]
Thanks!
