### ISSUE TITLE
Improve Flyway validation error messaging for out of order versions

### ISSUE THREAD

**Issue by berlin-ab** [flyway/flyway#1295]
###### What version of Flyway are you using?
3.2.1

###### What database are you using (type & version)?
MySQL

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

While running migrations we noticed this error: 

"Validate failed. Detected resolved migration not applied to database: 20160420141503"

After doing some debugging we realized that this migration was created before migration version 20160425000000.  The version from April 25th was deployed before the version from April 20th because the earlier version had not yet been merged in to master. 

I expected to see a more obvious error message from Flyway.  Something like:  "Migration is out of order. 20160420141503 is a lower version than 20160425000000, and 20160425000000 has already been migrated."

**Comment by axelfontaine** [comment]
The error message is pretty clear though. It simply says you now have a new migrations that hasn't been applied to the database yet. This could happen regardless of whether you are choosing to use outOfOrder migrations or not.

**Comment by berlin-ab** [comment]
@axelfontaine As a new user of Flyway, I did not understand that error message.  I wonder if there is a way to improve the wording so it is more clear to new comers?

**Comment by axelfontaine** [comment]
@berlin-ab Sure. Always open for improvement. Suggestions welcome.
