### ISSUE TITLE
Order in which callbacks are executed

### ISSUE THREAD

**Issue by ridiekel** [flyway/flyway#1296]
Hi,

In Flyway 4.0.0 we are using callback to do validation and other tasks that need to be executed after every migration.
We would expect those callbacks to be executed in the order we give them to Flyway. However they are executed in random order.

We looked at flyway code and found that the callbacks are being put in a HashSet. We think this causes the callbacks to be put in random order (Set<FlywayCallback> flywayCallbacks = new HashSet<FlywayCallback>(Arrays.asList(callbacks)); in Flyway.java at 1348)

For now we can work around this issue by creating a callback that contains callbacks and executes them in the correct order, but we doubt this is a good practice.

**Comment by axelfontaine** [comment]
Good catch! Changed to LinkedHashSet instead.
