### ISSUE TITLE
Using MySQL Connector/J 6.x warns about JDBC driver class name

### ISSUE THREAD

**Issue by cowwoc** [flyway/flyway#1299]
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
AWS Aurora (equivalent to MySQL 5.6)

###### What operating system are you using?
Windows 7, 64-bit

###### What did you do?
Included the following lines in the Maven pom.xml:

```
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>4.0</version>
                <executions>
                    <execution>
                        <id>migrate-db</id>
                        <goals>
                            <goal>migrate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <url>jdbc:mysql://someHostname/someDatabase</url>
                    <user>someUser</user>
                    <password>somePassword</password>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>6.0.2</version>
                    </dependency>
                </dependencies>
            </plugin>
```

###### What did you expect to see?
No warning messages

###### What did you see instead?
```
--- flyway-maven-plugin:4.0:migrate (migrate-db) @ pandemic-web-service ---
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Unknown configuration property: flyway.version
```

**Comment by cowwoc** [comment]
The first warning is caused by https://dev.mysql.com/doc/connector-j/6.0/en/connector-j-api-changes.html. You can work around it using: `<driver>com.mysql.cj.jdbc.Driver</driver>`

I have no idea what is causing (or how to workaround) the second warning: `Unknown configuration property: flyway.version`

**Comment by axelfontaine** [comment]
Fixed the first warning. The second one is to due to logic that warns for accidental Flyway config argument name misspellings by issuing a message for all unknown flyway.XXX properties. Rename to `version.flyway` or anything else that doesn't start with `flyway.` to eliminate the warning.

**Comment by cowwoc** [comment]
@axelfontaine We don't actually have a `flyway.version` property anywhere in our pom, so I have no idea why we are getting this warning.

**Comment by axelfontaine** [comment]
It must be set from somewhere. Can you run your build with debug output and check?

**Comment by cowwoc** [comment]
@axelfontaine Nevermind. Another team member redid our entire pom so I can no longer reproduce the problem. I'll let you know if I ever see it again.
