### ISSUE TITLE
Fail if user is set in Flyway config, but password is only present in settings.xml

### ISSUE THREAD

**Issue by cowwoc** [flyway/flyway#1300]
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
AWS Aurora (MySQL 5.6)

###### What operating system are you using?
Windows 7, 64bit

###### What did you do?
In pom.xml:
```
                        <configuration>
                            <user>someUser</user>
                            <serverId>myServerId</serverId>
                        </configuration>
```

In settings.xml:
```
    <servers>
        <server>
            <id>myServerId</id>
            <password>somePassword</password>
        </server>
    </servers>
```

###### What did you expect to see?
I expect the username to be taken from pom.xml and password from settings.xml because I only need to hide the password, not the username.

Alternatively (since it's probably best to specify both in the same place) Flyway should issue an error message when encountering this case.

###### What did you see instead?
The username from pom.xml is used, but the password in settings.xml is ignored.

**Comment by axelfontaine** [comment]
Error message added.
