### ISSUE TITLE
ClassPathScanner fails for WebLogic classloader

### ISSUE THREAD

**Issue by anilarora** [flyway/flyway#1304]
###### What version of Flyway are you using?

4.0
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
The location of the sql and java migrations exist in the same JAR file as the class that invokes the Flyway.migrate command.  The locations are set up to use the classpath prefix.  
###### What did you see instead?

It shows the error "Unable to resolve location:"

Doing my own tests, it seems like the appropriate fix would be to do what is being done for WebSphere classloaders.  Test for the flyway.location file instead because the WebLogic classloader cannot return resources that are folders.

**Comment by axelfontaine** [comment]
Thanks for pointing this out. We did fix a bug in the ClassLoading as part of 4.0.1 and it definitely worked with WLS in the past. Can you try again with the latest code? If it stills fails, we would certainly welcome a PR.

Thanks!
Axel

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
