### ISSUE TITLE
Tighter intergration with JOOQ via JAVA

### ISSUE THREAD

**Issue by rit001** [flyway/flyway#1310]
I'm trying to use Flyway in conjunction with JOOQ in a dynamic way using the Java interface. As such I'm finding some limitations as few others are likely to have tried this in the past.

I've already posted at stackoverflow.com 

     http://stackoverflow.com/questions/37079995/order-of-processing-when-using-flyway-java-based-migrations

The full text is

I have just started to experiment with Java based migrations combined with providing a checksum by implementing MigrationChecksumProvider.

Currently Flyway seems to handle things as a 2 step process

    Call the Checksum routine
    Call the JdbcMigration routine

This 2 step approach works well if the JdbcMigration routine is static in nature (such as a script) as the checksum can be easily calculated. It get more interesting if the JdbcMigration routine is dynamic in nature as its result is not known at the time that the checksum routine is called.

The current solution for this is to have the checksum routine also call some form of pre JdbcMigration routine that generates the dynamic DDL to be checksummed and so allowing checksum to be calculated and returned. Flyway can then move onto calling the JdbcMigration routine which then executes the DDL.

The above works, but would it not be better in the future for Flyway to handle this as a 3 step process that it can correctly track and report on.

    Call the preparation routine
    Call the Checksum routine
    Call the JdbcMigration routine

This question/comment/idea has come about because I am currently looking at using JOOQ as a way to express the DDL, which means that the DDL only exists at run time.

Follow up 1

As the checksum needs to be calculated based on the underlying database there is a need for the connection to be passed to the checksum routine as well as the migrate routine. The reason for this is that JOOQ may create different DDL statements depending on what the database target is.

Follow up 2

It would be useful if the ConfigurationAware interface could provide 'discovered' information about the java migration it is calling, such as the version and description it has decoded from the class name.

**Comment by axelfontaine** [comment]
You can already achieve what you describe here. The preparation routine can be called from the constructor of your Java-based migration. And the checksum is there for accidental modification detection and is purely based on the available migration, not on the applied one, hence there is no need to access the DB to calculate it. If you want exact access to your Version and Description you can implement the MigrationInfoProvider interface and call those methods yourself as needed.

Everything you mentioned is therefore already possible today. No changes necessary.

**Comment by rit001** [comment]
With JOOQ it is possible to have JOOQ generate DDL statements based on the database it is connecting against, while you may express a field in a table as BIT it may create DDL that expresses the DDL using BOOL, because the database does not directly support BIT. This means the checksum should be generated from the DDL rather than be a hard coded value. It becomes more important over time as JOOQ may change the DDL it creates as it gains features, again creating the checksum from the generated DDL would be beneficial as it would catch such a change.

My overall aim is to use Flyway and JOOQ so that within JAVA I can target a number of different database engines and JOOQ handles the DDL level differences via it's DDL capabilities.

I am already playing with work arounds, but they are not as clean as Flyway is not longer fully involved in managing the process

- I use the checksum routine to call the function that is generating the DDL with flags to inform it to generate a checksum value from the generated DDL, rather than execute the DDL.

- The checksum routine is not passed the database connection that is passed when the migrate routine is call, so I plan to generate my own using the DataSource object made available if I implement ConfigurationAware interface. While this should work it is fair to say that they are not the truly the same and will become more complicated if I start to use Spring.

I am aware of the MigrationInfoProvider interface, but what I was raising was a way to gain access to the automatically computed values that have been created from the class name.
