### ISSUE TITLE
Clarify validate javadoc

### ISSUE THREAD

**Issue by cowwoc** [flyway/flyway#1312]
###### What version of Flyway are you using?
4.0.1

###### What database are you using (type & version)?
MySQL 5.6

###### What operating system are you using?
Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Flyway.migrate()

###### What did you expect to see?
Unable to resolve location classpath:db/migration

###### What did you see instead?
Build-time or runtime failure.

I want to throw an error if no migrations were found. This means either throwing an exception on my behalf if no migrations are found, or providing me a means to query how many SQL, Java migrations were found and letting me acting on it.

**Comment by cowwoc** [comment]
I suspect this feature would fit into `Flyway.info()`.

**Comment by axelfontaine** [comment]
Flyway.validate() should be able to do this for you in case migrations have already been executed against the DB. Would that do the job for you?

**Comment by cowwoc** [comment]
The Javadoc for `Flyway.validate()` is very vague. What exactly does it check for? (and I suggest updating the Javadoc accordingly)
