### ISSUE TITLE
SQL Callbacks - more than one .sql file per event

### ISSUE THREAD

**Issue by KevinSheedy** [flyway/flyway#1315]
###### What version of Flyway are you using?

4.0.1
###### What database are you using (type & version)?

Oracle 11.2
###### What operating system are you using?

Windows 7 & RHEL
###### Feature Request

At present, a Sql Callback can execute only one .sql file eg **afterMigrate.sql**. This file can't import code from another .sql files or 'call' another .sql file. I would like to execute multiple .sql files in a callback.

At present, I use Oracle SqlPlus to execute a list of files after migration but I would prefer if I could do this with Flyway.
###### Suggested implementation:

Have flyway scan for callback files named something like this: **afterMigrate.sql.list**
Execute all the .sql files listed.

```
# This is a comment

# Execute this file
test/validate-code.sql

# Execute another file
reports/generate-mi.sql

# Scan this folder and apply every .sql file
unit-test/
```

**Comment by DemianTinkiel** [comment]
+1 on this.

**Comment by sguillope** [comment]
Could we make the callback names only be prefixes instead?
So for example you could have multiple "afterMigrate" SQL files. Something like:
- `afterMigrate1__my_first_after_migrate.sql`
- `afterMigrate2__my_second_after_migrate.sql`

**Comment by jowe** [comment]
One additional aspect:

**Comment by tinproject** [comment]
It would be nice to have callbacks before and after a specific migration only.
An example of the file name could be: `prefixVERSIONseparatorDESCRIPTIONseparatorCALLBACKsuffix`

This could be used to insert test data after schema creation to allow that the next migrations could be run with existing data. For example, having the sql scripts for the migration in an `sql` location and the callbacks on other location like `test`, running flyway for migrations only with the `sql` location and for testing with the `sql,test` location.

**Comment by axelfontaine** [comment]
@tinproject Multiple locations combined with dotted version numbers (7.1, 8.1, ...) already let you achieve this today.

**Comment by goofy77** [comment]
@axelfontaine could you explain a little bit more?

**Comment by axelfontaine** [comment]
This has now been implemented. Multiple SQL callbacks for the same event are now allowed. They then must have a description and are executed in the order of their description.

Example: `beforeRepair__vacuum.sql`
