### ISSUE TITLE
Migrate maven goal generate exception with postgres (COPY command)

### ISSUE THREAD

**Issue by gbenmansour** [flyway/flyway#1316]
###### What version of Flyway are you using?
4.0.1 (maven plugin)

###### What database are you using (type & version)?
postgreSQL 9.5

###### What operating system are you using?
Windows

###### What did you do?
When I migrate using the command line tools everything works fine.

But when I want to use maven command mvn flyway:migrate the exception below is generated 
[ERROR] SQL State  : 0A000
[ERROR] Error Code : 0
[ERROR] Message    : La fonction org.postgresql.jdbc4.Jdbc4Connection.unwrap(Class<T>) n'est pas encore implémentée.
[ERROR] Location   : C:/ERDF/disporeseau2/src/main/resources/db/migration/V1__Initial_version.sql (C:\ERDF\disporeseau2\src\main\resources\db\migration\V1__Initial_version.sql)
[ERROR] Line       : 913
[ERROR] Statement  : COPY acr (id, code, haseplaning, mailhisto, nom, ville, mailgeneric) FROM stdin;

Here is my pom.xml plugin configuration 
                        

It look like it's the same problem as described in this issue [issue](http://stackoverflow.com/questions/23025471/method-org-postgresql-jdbc4-jdbc4connection-unwrap-is-not-yet-implemented) .
I'm wondering why this is only happening on the maven plugin ? Any help I need to use the maven plugin to integrate the migrate goal into the deployment process.
Thanks.

Here is my plugin config:
```
 <plugin>
					<groupId>org.flywaydb</groupId>
					<artifactId>flyway-maven-plugin</artifactId>
					<version>4.0.1</version>
					<configuration>
						<driver>org.postgresql.Driver</driver>
						<url>jdbc:postgresql://localhost:5432/dbTest</url>
						<user>postgres</user>
						<password>admin</password>
						<schemas>public</schemas>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.flywaydb</groupId>
							<artifactId>flyway-core</artifactId>
							<version>4.0.1</version>
						</dependency>
					</dependencies>
				</plugin>
```
###### What did you expect to see?
to work successfully like the command line tool do.
###### What did you see instead?
Exception.

**Comment by axelfontaine** [comment]
This is due to your outdated JDBC driver. Please update to the latest progresal JDBC driver and everything should work as expected.
