### ISSUE TITLE
MemSQL Support

### ISSUE THREAD

**Issue by nycjay** [flyway/flyway#1317]
We are looking to leverage Flyway to support our migrations against a set of MemSQL databases. Unfortunately, Flyway don't currently have support out of the box. MemSQL uses the MySQL driver, and is mostly the same from the application point of view, but the _create table_ syntax is slightly different, and Flyway failed to create a table when I tested with version 4.0.

**Comment by nycjay** [comment]
@pradheeps pull request https://github.com/flyway/flyway/pull/1386 should hopefully add the support we need.

**Comment by nycjay** [comment]
Following up on this - has the pull request been looked at yet? Trying to determine if we will wait for it to be included in an upcoming build (or rejected), or if we will need to compile and deploy our own fork (which we would like to avoid if possible).

**Comment by eram** [comment]
Would love to see this feature implemented. We are currently built a flyway-like tool to run migrations, but it would be great if this minor take on mySQL driver is properly added.

**Comment by nycjay** [comment]
This can be replaced by the SingleStore implementation, in #3417

**Comment by DoodleBobBuffPants** [comment]
Closed by https://github.com/flyway/flyway/commit/c015f2dde4dc379f97b8796e31a37c119d6b0f7c which adds SingleStore support

**Comment by buremba** [comment]
The source code is licensed with Apache but on the website, it's stated that the integration is part of the enterprise offering. Can you please clarify the licensing?
