### ISSUE TITLE
Allow multiple scripts per version

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#132]
_Original author: torr0...@gmail.com (March 25, 2013 15:02:15)_

I have a large schema with a large seed data set. It is unmanageable (I can barely open an editor) to have this in one file. We have traditionally broken this up into one sql file per table. However, Flyway doesn't support this.

I know I can work around this by versioning each script as a pre-1.0 script, but that's not accurate. Ideally, Flyway would support multiple files at the same version, but with different names, so that we can migrate to a 1.0 and have the scripts match.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=460_

**Comment by GuidoGeloso** [comment]
Is there anyone interested in a fork of this project?

**Comment by lusu007** [comment]
Has something happened here? I think the idea from post before the last is very good.
Is this introduced?

**Comment by walec51** [comment]
if your running a non trivial project where features are developed concurrently on feature branches then policing every one to use unique version numbers is a real pain

full file names should be used to check if a given migration was applied or not

version numbers by them self should be only used for ordering, if two changes have version 107 then they don't care which one will go first as the have been developed independently - they do however care if all the changes before them 106, 105, ... have been already applied to the database

one can solve the problem by adding a random number to your version like

V107.3trgfs34__my_feature_a.sql 
V107.gy654e5__my_feature_b.sql 

but this is just hacking a feature that is lacking in flyway in my opinion

**Comment by bernstein82** [comment]
we've "solved" this by abusing flyway's numbering scheme :

we create files like :
com/mycompany/moduleA/1.0.0__Aggregate_A.sql
...
com/mycompany/moduleA/1.0.0__Aggregate_Z.sql
...
com/mycompany/moduleZ/1.0.0__Aggregate_A.sql
...
com/mycompany/moduleZ/1.0.0__Aggregate_Z.sql

and then use a maven build plugin to transform these into names like :
com/mycompany/moduleA/1.0.0.01.01__Aggregate_A.sql
...
com/mycompany/moduleA/1.0.0.01.99__Aggregate_Z.sql
...
com/mycompany/moduleZ/1.0.0.99.01__Aggregate_A.sql
...
com/mycompany/moduleZ/1.0.0.99.99__Aggregate_Z.sql

this allows for 99 modules, each with 99 sql files. obviously :
- it's ugly as hell, but hey it works... 
- module numbers would need to be preassigned (unless everything lives in a single build tree)
- the history db get's blown up like crazy, however if a migration fails the offending file is right there
- as a bonus, if sql files need to be ordered, it can easily be achieved
