### ISSUE TITLE
Generation of version name

### ISSUE THREAD

**Issue by mhartwig** [flyway/flyway#1323]
Hi,

if you are using version name patterns like "V20160527_1" and if you are working in branches and with distributed developers, there is the possibility, that two developers are using the same version name in different branches. This leads to errors, when you are migrating, because, there is the same version, but is has a different descrioption.

A solution could be, that the pattern of the version name contains the initials of the developer (e.g.: V20160527_MH1), but this leads to the error, that the version can only containt numeric characters. So, the solution is, that each developer becomes a number, but this is ugly I think.

Can anyone provide a solution for this scenario? Or is it possible, that you can change the behaviour for the version names?

**Comment by nycjay** [comment]
We also use a feature development methodology, and have multiple teams working on different branches. To avoid (as much as possible) collisions, we have them include the enhancement/bug number (from Jira) they are working on as part of their script name. That gives them their own namespace which is nearly unique (it is _possible_ that an enhancement and a bug could share the same number, but it is very unlikely that that will happen during the same 7 week release cycle, so it is a risk we are OK taking). 
So, something like V<enhancement-number>_<script within that enhancement>.sql
V_123_1.sql
V_123_2.sql

We then enable outOfOrder mode. If there are dependencies between different features/bugs, we manually fold those into the same namespace, but in our case, this is very unlikely.

For objects like stored procedures / UDFs / etc, where multiple teams may be working on the same object for a given release, we plan on taking advantage of the new repeatable migrations. We will make a file for each stored procedure R<procedure-name>.sql. Then, if multiple teams are both touching the same file, they will hit a conflict when they rebase, and it is up to the individual engineers to resolve.

**Comment by zolrag13** [comment]
Hopefully, you found a solution to your issue but for future reference I think that the following article is a good source [Lessons Learned Using Flyway DB with Distributed Version Control](http://www.jeremyjarrell.com/using-flyway-db-with-distributed-version-control/)

The basic idea is to use a timestamp with milliseconds precision.

Here is a quote from the article: 

> But, if you choose to prefix your migrations using timestamps rather than integers, then the likelihood of a collision virtually disappears, even across branches.  For example, using a pattern such as yyyyMMddHHmmssSSS...

**Comment by gnomff** [comment]
I created a gradle plugin that does just this https://github.com/gnomff/FlywayRename

**Comment by Joltd** [comment]
Tracking version uniqueness always very hard when yours more then one in the team.

There will be more suitable if we can to skip checking version duplication (method
org.flywaydb.core.internal.resolver.CompositeMigrationResolver # checkForIncompatibilities) - e.g. via some additional option in Flyway properties (with outOfOrder = true of course).

In this case, the developer team can use the version system accepted in their project. For more iformative they can add a ticket in the description. So migration scripts may looks like:

V5.1.0_jira_1240_add_column.sql
V5.1.0_jira_1135_big_changes.sql
V5.1.1_jira_2356_small_fixes.sql

This method is more like the one used in the Liquibase, and there is not necessary to adding some redundant timestamps / unique dev number / etc.

**Comment by DoodleBobBuffPants** [comment]
Flyway does not generate migration names for you. You can read more about a potential solution using git hooks in our blog post [here](https://flywaydb.org/blog/using-git-hooks-with-flyway).
