### ISSUE TITLE
Add initSql for all clients

### ISSUE THREAD

**Issue by JeP42** [flyway/flyway#1324]
Flyway's Java API provides capability to specify SQL statements which are executed right after the connection to the target database was established via Flyway.setDatasource (=> [javadoc)](https://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/Flyway.html#setDataSource-java.lang.String-java.lang.String-java.lang.String-java.lang.String...-). 

`Flyway flyway = new Flyway();`
`// datasource with initilization SQL`
`flyway.setDataSource(url, user, password, initSQL);`
`flyway.setLocations("sql/migrations");`
`flyway.migrate();`

This is very useful functionality  as it allows to provide custom SQL statements to initialize the DB session which is used later to apply migrations. 

Unfortunately, _the command line tool does not provide similar functionality_. Therefore, when using the command line tool it is not possible to initialize the DB session with custom SQL statements. There are scenarios in which the command line tool would be more appropriate than the Java API. However, if session initialization is mandatory it is not possible to actually use the command line tool for such scenarios. Therefore, adding this feature to the commad line tool would really be appreciated.

**Comment by axelfontaine** [comment]
It should be easy to work around this for now with SQL callbacks.

**Comment by axelfontaine** [comment]
A new initSql property has now been added which allows one to pass in SQL statements to initialize a database connection immediately after Flyway opens it.
