### ISSUE TITLE
SqlScriptFlywayCallback errors in ALL_CALLBACKS list

### ISSUE THREAD

**Issue by frbo42** [flyway/flyway#1326]
###### What version of Flyway are you using?
4.0.1

###### What database are you using (type & version)?
Oracle 12c

###### What operating system are you using?
Windows (for development)
Linux (prod)

By inspecting the code below, you will see that before_clean and after_clean, is added twice in the all_callback list. 
while before_info and after_info is not added to the list:

    public class SqlScriptFlywayCallback implements FlywayCallback {
    private static final Log LOG = LogFactory.getLog(SqlScriptFlywayCallback.class);
    private static final String BEFORE_CLEAN = "beforeClean";
    private static final String AFTER_CLEAN = "afterClean";
    private static final String BEFORE_MIGRATE = "beforeMigrate";
    private static final String AFTER_MIGRATE = "afterMigrate";
    private static final String BEFORE_EACH_MIGRATE = "beforeEachMigrate";
    private static final String AFTER_EACH_MIGRATE = "afterEachMigrate";
    private static final String BEFORE_VALIDATE = "beforeValidate";
    private static final String AFTER_VALIDATE = "afterValidate";
    private static final String BEFORE_BASELINE = "beforeBaseline";
    private static final String AFTER_BASELINE = "afterBaseline";
    private static final String BEFORE_REPAIR = "beforeRepair";
    private static final String AFTER_REPAIR = "afterRepair";
    private static final String BEFORE_INFO = "beforeInfo";
    private static final String AFTER_INFO = "afterInfo";

    public static final List<String> ALL_CALLBACKS = Arrays.asList(
            **BEFORE_CLEAN**, **AFTER_CLEAN**,
            BEFORE_MIGRATE, BEFORE_EACH_MIGRATE, AFTER_EACH_MIGRATE, AFTER_MIGRATE,
            BEFORE_VALIDATE, AFTER_VALIDATE,
            BEFORE_BASELINE, AFTER_BASELINE,
            BEFORE_REPAIR, AFTER_REPAIR,
            **BEFORE_CLEAN**, **AFTER_CLEAN**);`

The fix should be simple enough :)

**Comment by axelfontaine** [comment]
Good catch! Thanks!
