### ISSUE TITLE
SBT don't enable Plugin automatically

### ISSUE THREAD

**Issue by schmitch** [flyway/flyway#1329]
Hello, currently I'm trying to use Flyway with SBT.

However due to the natur of the current Plugin it will be automatically enabled on **all** projects, this is really really ugly when you have a multi module project since it will try to run tasks as flywayMigrate on **every** project.
It would be great if the tasks won't be activated or when you would need to manually enable the plugin via `.enablePlugins.` (`def trigger: PluginTrigger = noTrigger`)

Disabling the Plugin won't work and I don't think that Flyway-sbt should trigger on allRequirements since it mostly won't be included in **every** subproject.

```
[error] sbt.AutoPluginException: Error determining plugins for project 'server' in ...:
[error] Contradiction in selected plugins.  These plugins were both included and excluded: org.flywaydb.sbt.FlywayPlugin
```

**Comment by amertum** [comment]
Completely agree. Automatic is not the way to go as it is problematic with multi-modules project.
I have the same problem to resolve and looking for a workaround.

**Comment by amertum** [comment]
Maybe related to the way sbt handle AutoPlugin as we can't even disable them on per module basis cf. https://github.com/sbt/sbt/issues/1926

**Comment by schmitch** [comment]
But actually I guess Flyway shouldn't be triggered by "allRequirements" thats odd since mostly you don't need **all** modules to have the flyway module

**Comment by frosforever** [comment]
Currently being hit by this as well. 
@schmitch Makes sense to me. Seems like https://github.com/flyway/flyway/blob/35893a6dfdbd6e45e0aff37a2aac2ffb36421aad/flyway-sbt/src/main/scala/org/flywaydb/sbt/FlywayPlugin.scala#L32 isn't needed and should be left as the default `noTrigger` for the user to manually enable on the desired project.

**Comment by simao** [comment]
Did you manage to disable the plugin for some modules?

**Comment by skylve** [comment]
What @frosforever said is right. @axelfontaine what do you think about this ?

**Comment by axelfontaine** [comment]
@cdedie Thoughts?

**Comment by cdedie** [comment]
Seems reasonable to disable the plugin per default. 
I will look for a workaround later.

**Comment by ennru** [comment]
On the same theme one might need to configure different Flyway datasources for different modules.

**Comment by phile314-isska** [comment]
Has there been any progress on this issue yet? Does anyone know a workaround?

**Comment by frosforever** [comment]
@phile314-isska my current work around is a fork that is exactly the same but removes the offending `override def trigger = allRequirements`.

**Comment by clhodapp** [comment]
I believe that https://github.com/sbt/sbt/issues/1926 doesn't mean that `disablePlugins` is entirely broken. Rather, I think that it's just saying that if you put both an `enablePlugins` and a `disablePlugins` on the same project, you get an error (rather than e.g. the last one taking precedence, which would be nicer).

I think you should still be able to explicitly add a `disablePlugins` for flyway to all the projects that you don't want flyway enabled on and simply not mention flyway for your other projects. For the ones that don't have an explicit `enable` or `disable`, flyway will be auto-applied. For ones where you `disable` it, your explicit `disable` should take precedence over the trigger.

**Comment by clhodapp** [comment]
To be clear, I'm not saying that it wouldn't be better to change the trigger. It probably still would.

**Comment by davidmweber** [comment]
I am maintaining the flyway-sbt pluging and would very much like to not set a trigger as per the suggestion by @cdedie that got 6 upvotes? I can make a snapshot available in hours.

**Comment by danxmoran** [comment]
@davidmweber yes please!

**Comment by axelfontaine** [comment]
Closing as the SBT plugin has now moved to its own repo: https://github.com/flyway/flyway-sbt
