### ISSUE TITLE
Microsoft Parallel Data Warehouse support

### ISSUE THREAD

**Issue by fdefalco** [flyway/flyway#1330]
Add support for Microsoft Parallel Data Warehouse.  I had started with a simpler question on StackOverflow but I am realizing what is necessary is general support for Microsoft Parallel Data Warehouse.  I have started work on adding this support in my own fork but will need some guidance in order to complete it.  Happy to contribute my time or attempt to provide some sponsorship for the feature.

Here is a link to my ongoing work as I've been capturing on [StackOverflow](http://stackoverflow.com/questions/37501311/override-default-script-for-initialization-of-flyway-metadata-table).

**Comment by NeilP-global** [comment]
Microsoft's azure SQL DW also works in the same way as PDW. 

azure SQL DW support would be awesome, as I'm struggling to find any tool that currently supports it.

**Comment by scuderig** [comment]
Please add the ADWH support

**Comment by DoodleBobBuffPants** [comment]
Azure Synapse (Data Warehouse) support is in V7. You can read more about it [here](https://flywaydb.org/blog/flyway-7.0.0-beta)
