### ISSUE TITLE
State column contents truncated in Info command

### ISSUE THREAD

**Issue by LowlyDBA** [flyway/flyway#1336]
On version 4.0.1, the "Status" column is one character (7 instead of 8) too short to fit the word _Baseline_ in [MigrationInfoDumper.java](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/info/MigrationInfoDumper.java)

![image](https://cloud.githubusercontent.com/assets/16843041/15909188/2e530684-2d93-11e6-8b1b-2bddd46fc428.png)

**Comment by axelfontaine** [comment]
The whole table is actually fixed with. This could indeed be revisited.
