### ISSUE TITLE
Create Schema - is not supported in db2 on zOS

### ISSUE THREAD

**Issue by tbsalling** [flyway/flyway#1344]
###### What version of Flyway are you using?

4.0.2

###### What database are you using (type & version)?

DB2 v11 z/OS

###### What operating system are you using?

Windows 7

###### What did you do?

Try to perform initial migration using Flyway through Gradle plugin.

build.gradle contains:

```
buildscript {
	repositories {
	   flatDir {
	       dirs 'lib'
	   }
	}

	dependencies {
    	classpath name: 'db2jcc4'
  		classpath name: 'db2jcc_license_cisuz'
	}
}

plugins {
    id "org.flywaydb.flyway" version "4.0.2"
}

...

flyway {
    url = 'jdbc:db2://host:9999/DB2'
    user = System.getenv("DB_USER")
    password = System.getenv("DB_PASSWORD")
    schemas = "TEST"
    table = 'TB000_SCHEMA_VERSION'
}

```

###### What did you expect to see?

Successful migration.

###### What did you see instead?

```
$ ./gradlew.bat :module:flywayMigrate
:module:flywayMigrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':module:flywayMigrate'.
> Error occurred while executing flywayMigrate
Create Schema - is not supported in db2 on zOS
```

**Comment by axelfontaine** [comment]
Works as designed. This is a limitation of the underlying DB. Nothing we can do on our end.

**Comment by tbsalling** [comment]
OK - thanks for the reply. 

But Gradle stops with this **error**:
```
> Error occurred while executing flywayMigrate
Create Schema - is not supported in db2 on zOS
...
BUILD FAILED
```
and nothing seems to be changed in the database after I run Gradle target :flywayMigrate.

So how is the DB2 support of Flyway any use? I don't get it. Is there a way to steer around the attempt to create a schema?

**Comment by axelfontaine** [comment]
Remove the schemas setting from your config and you should be good

**Comment by tbsalling** [comment]
Doesn't work.

If I remove the schema entry completely from build.gradle, then Flyway assumes that my username is the default schema.

Have also tried:

```
flyway {
    schemas = [];
}

```
```
flyway {
    schemas = [ null ];
}
```

```
flyway {
    schemas = null ;
}
```

Neither work.

Reading the code for Flyway and the plugin - I agree, that no schemas should do the trick. But somehow my username if applied as schema name if no schemas are given. How can I avoid this?

**Comment by tbsalling** [comment]
Just a note, that I managed to proceed with this somewhat hacky approach:

https://github.com/tbsalling/flyway/commit/3b517d25a56d9fa4698e6bdf78ae193031f76211
