### ISSUE TITLE
Feature request to make wrapping migration in a transaction optional and configurable

### ISSUE THREAD

**Issue by hntran8** [flyway/flyway#1347]
###### What version of Flyway are you using?

4.0.1

###### What database are you using (type & version)?

Sybase, Oracle, SQL Server

###### What operating system are you using?

Linux, Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Flyway is wrapping the migration (have both DDL and DML) in a transaction. Our company policy does not allow wrapping DDL in a transaction since this could cause issues in some cases.

###### What did you expect to see?

This is a feature request to have the wrapping in the transaction optional and configurable.

###### What did you see instead?

Migrations fail because DB settings do not allow wrapping DDL in a transaction

**Comment by axelfontaine** [comment]
You can achieve this today by writing your own MigrationResolver.

I do not expect this to ever make it into the main distribution as the rule you invoke doesn't seem to be based on specific technical grounds and is unique to your company.
