### ISSUE TITLE
Remove warning when using flyway.version maven property

### ISSUE THREAD

**Issue by squawk979** [flyway/flyway#1348]
###### What did you see instead? [WARNING] Unknown configuration property: flyway.version

There's actually no problem, but the warning made me think there was and threw me for a while.  I use a number of maven properties called flyway.whatever.  For example let's take flyway.version.  At the top of the POM:

```
<properties>
    <flyway.version>4.0.3</flyway.version>
</properties>
```

and later in the dependencies:

```
  <dependency>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-core</artifactId>
        <version>${flyway.version}</version>
    </dependency>
```

The flyway maven plugin passes all properties into core flyway which then filters them and logs a warning because it has a property starting with "flyway." that it doesn't recognize.  Of course it's not a problem at all, it was used correctly by maven and was never intended for flyway core.

Might be worth considering whether this kind of warning should be printed.  Realize that it's helpful in scenarios where a user may have intended a genuine flyway setting but got the name wrong.  I'm really not sure what the best course of action is.  Any thoughts?

**Comment by axelfontaine** [comment]
This works as designed for the reason you mentioned.

We could however add an exception for `flyway.version` as this is really a common pattern on the Maven side of things.

**Comment by jeromerg** [comment]
I get the warning even if maven doesn't contain any property "flyway.version".

It would be nice, to lower the logging level: Every developer spends half an hour to try to remove this warning and to figure out, that it is a false positive. ;-)

**Comment by axelfontaine** [comment]
@jeromerg I promise you, somewhere your Maven build contains a definition for that property. No warning is generated out of thin air...

**Comment by squawk979** [comment]
... spring boot dependencies defines <flyway.version> for example...

**Comment by jeromerg** [comment]
Indeed it is certainly spring-boot depedencies. Thank you for the explanation. Does it help to solve the issue? Is there any mean to remove the warning at my pom's level?

**Comment by squawk979** [comment]
I think Axel's suggestion above is a good idea: it's a minimal change but will remove the unnecessary warning (for flyway.version) people are likely to see.  I'd wait for that change and put up with the warning for now

**Comment by jeromerg** [comment]
Thank you for your help!

**Comment by Jelledb** [comment]
I'm also getting the warning without specifying the flyway.version property. I am using Spring Boot.

**Comment by abuabdul** [comment]
Im using flyway version 4.0.2. I just renamed maven properties to flywaydb.version. guess what? I see no more warning. Thanks @axelfontaine

**Comment by narwajea** [comment]
When using Spring Boot, you may inherit from spring-boot-starter-parent, which in turn inherits the "flyway.version" property from spring-boot-dependencies.

**Comment by SingleShot** [comment]
I am not aware of any other plugin that logs warnings of this nature. I'd like to see it removed.

**Comment by axelfontaine** [comment]
Fixed.
