### ISSUE TITLE
Output warnings

### ISSUE THREAD

**Issue by davidkarlsen** [flyway/flyway#1349]
###### What version of Flyway are you using?

4.0.3
###### What database are you using (type & version)?

oracle 12c
###### What operating system are you using?

Linux / RHEL 7.2
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

We get warnings during repeatable migrations (which there might very well be good reasons for) - what I want is that flyway collect these with https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#getWarnings() and output them
[WARNING] DB: Warning: execution completed with warning (SQL State: 99999 - Error Code: 17110)
###### What did you expect to see?

the reason behind the warning from https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#getWarnings()
###### What did you see instead?

just that there is a warning
[WARNING] DB: Warning: execution completed with warning (SQL State: 99999 - Error Code: 17110)

**Comment by axelfontaine** [comment]
Flyway already retrieves and displays the message from the warning, which in your case was `Warning: execution completed with warning` as returned by your JDBC driver

**Comment by davidkarlsen** [comment]
If I recollect this well calling the mentioned methods will reveal a lot more information leading the user to the readable plaintext root cause rather than a wildcard error code which is not tied to the statement causing it

**Comment by axelfontaine** [comment]
Be my guest. How would you improve https://github.com/flyway/flyway/blob/7925112a1041d7763d722a4d36cbbb39277e7b5c/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/JdbcTemplate.java#L270
?
