### ISSUE TITLE
Windows Authentication

### ISSUE THREAD

**Issue by venkateshla** [flyway/flyway#1350]
###### What version of Flyway are you using?

flyway 4.0.3

###### What database are you using (type & version)?

SQL Server 2008

###### What operating system are you using?

Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Folks,
I am facing a issue with windows authentication when i tired flyway url as below,
flyway.url=jdbc:jtds:sqlserver://SOMESERVER;instance=SOMEINSTANCE;databaseName=SOMEDATABASE;SendStringParametersAsUnicode=false;useNTLMv2=true;domain=SOMEDOMAIN;

flyway.user=SOMESERVER\SOMEUSER

flyway.password=SOMEPASSWORD

I am referring a issue raised earlier to flyway, https://github.com/flyway/flyway/issues/360 which is in a closed state. But when use the configuration values flyway.url, flyway.user, flyway.password, I am receiving below error.

 **Login Failed for user 'SOMESERVER\SOMEUSER'**

I am able to login for the same user 'SOMESERVER\SOMEUSER' using windows authentication in SQL server and i have logged in the system with the same user 'SOMESERVER\SOMEUSER'.

Whether flyway support windows windows authentication ? If so what is the syntax we have to follow in flyway.config file ? Can we access remote SQL server using windows authentication ? Appreciate your help regarding !!
  
###### What did you expect to see?

When i trigger ./flyway info command, it should show the information from schema_version table from DB which i am configured with windows authentication for a particular user.   

###### What did you see instead?

**Login Failed for user 'SOMESERVER\SOMEUSER'**

**Comment by axelfontaine** [comment]
This is something that clearly falls under the responsibility of the JDBC driver you use. There is not much we can do on our end. Make sure to try the MS driver as well to see if that helps.
