### ISSUE TITLE
Problem to execute migration with Amazon RDS MySQL

### ISSUE THREAD

**Issue by gvagenas** [flyway/flyway#1354]
###### What version of Flyway are you using?
**4.0.3**

###### What database are you using (type & version)?
**Amazon RDS MySQL - version 5.6.23-log**

###### What operating system are you using?
**Amazon Linux AMI release 2016.03**

###### What did you do?
Trying to add row to an existing table. 

- Script that causes problem https://gist.github.com/gvagenas/f853e761b4624f1f3a6e2fa804e643b5

This script run fine with Flyway 4.0.3 and a local running MySQL (tested with both 5.6 and 5.7) but fails with Amazon RDS MySQL.

There is a Warning:
```
WARNING: DB: No data - zero rows fetched, selected, or processed (SQL State: 02000 - Error Code: 1329)
```
The migration is shown as **Success**, but the table hasn't changed.

I also did a test to run the script (withouth the USE clause) with mysql command and it worked fine, so it looks ok in terms of SQL. Script: https://gist.github.com/gvagenas/cbf9a9819a5024e5917335c335c2a834

A similar script that works perfect: https://gist.github.com/gvagenas/3aac061eba86081f4f5e05cc90a9b0d7

I also removed mariadb driver and tried with mysql driver, but no luck.

###### What did you expect to see?
I expect the script to update the table

###### What did you see instead?
Table stays unchanged.

**Comment by axelfontaine** [comment]
I am afraid there is not much we can do on Flyway's side for this. Ensure you are using the very latest version of the MySQL JDBC driver and raise an issue with them or AWS.

**Comment by gvagenas** [comment]
The problem was the '@colName' I used in all the scripts. For example:
```
CREATE PROCEDURE updateProcedure()
 BEGIN
 SELECT DISTINCTROW IFNULL(column_name, '') INTO @colName
 FROM information_schema.columns
 WHERE table_schema='${RESTCOMM_DBNAME}'
 AND table_name = 'restcomm_call_detail_records'
 AND column_name = 'on_hold';

IF @colName IS NULL THEN
CREATE TABLE .... 
```

If the '@colName' was set in one of the previous scripts then subsequent scripts are using this value and was never getting into the IF THEN.

This happened only at Amazon RDS because of the data that we have there but its not RDS or driver related.

To workaround this I made the @colName unique by adding the migration number, for example

```
CREATE PROCEDURE updateProcedure()
 BEGIN
 SELECT DISTINCTROW IFNULL(column_name, '') INTO @colName776
 FROM information_schema.columns
 WHERE table_schema='${RESTCOMM_DBNAME}'
 AND table_name = 'restcomm_call_detail_records'
 AND column_name = 'on_hold';

IF @colName776 IS NULL THEN
CREATE TABLE 
```

I am not sure if this is FlyWay bug.

George
