### ISSUE TITLE
QUOTED_IDENTIFIER is set off in some stored procedures when migrating 46 stored procedures using Flyway

### ISSUE THREAD

**Issue by nasiqn** [flyway/flyway#1355]
###### What version of Flyway are you using?

4.0.3

###### What database are you using (type & version)?

MS SQL server 2014

###### What operating system are you using?

Windows Server 2012

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I'm running Flyway Migration for 46+ stored procedures,
command : Flyway Migrate
In the initial run, out of those 46 procedures 6 of them get the QUOTED_IDENTIFIER value as OFF. The default value of this attribute is ON in MS SQL. But when i execute the those stored procedures individually then the QUOTED_IDENTIFIER value is set ON.

###### What did you expect to see?

All the stored procedures to have the QUOTED_IDENTIFIER attribute set to ON in the initial migration. 

###### What did you see instead?

some stored procedures having the value OFF

**Comment by axelfontaine** [comment]
Flyway does not do anything special with it. It is your responsibility to ensure it is set and stays set. You can also easily enforce this with the beforeEachMigration callback.

**Comment by nasiqn** [comment]
why does Flyway set this attribute differently ? i mean in the initial migration at the stage where we apply flyway versioning then this attribute is set to OFF and then when i execute it individually it is set to ON ?
