### ISSUE TITLE
Clean fails to DROP AGGREGATE in SQL Server

### ISSUE THREAD

**Issue by jcoulehan** [flyway/flyway#1361]
###### What version of Flyway are you using?

Maven plugin 4.0.3
###### What database are you using (type & version)?

SQL Server 2014
###### What operating system are you using?

Windows 7
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Created repeatable script to drop and recreate CLR functions. 1 of the functions is an aggregate function.

> > drop aggregate dbo.HarmonicMeanWithWeight
> > go

CREATE AGGREGATE [dbo].[HarmonicMeanWithWeight](@value [float], @Weight [int])
RETURNS[float]
EXTERNAL NAME [MathUtils].[Intelematics.Data.HarmonicMeanWithWeight]
GO
<<

When running clean the aggregate function does not get dropped. From the error it looks like flyway is calling drop function instead of drop aggregate.
###### What did you expect to see?

no errors when cleaning the schema.
###### What did you see instead?

[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:4.0.3:clean (default-cli) on project mwra-test-db: org.flywaydb.core.api.FlywayException: Unable to clean schema [dbo]: Can
not use DROP FUNCTION with 'dbo.HarmonicMeanWithWeight' because 'dbo.HarmonicMeanWithWeight' is a aggregate function. Use DROP AGGREGATE. -> [Help 1]

**Comment by axelfontaine** [comment]
This has been fixed as part of the Flyway 5.0.0 work.
