### ISSUE TITLE
Migrations are not performed in order when outOfOrder=true

### ISSUE THREAD

**Issue by static-max** [flyway/flyway#1365]
###### What version of Flyway are you using?

4.0
###### What database are you using (type & version)?

PostgreSQL 9.3.11
###### What operating system are you using?

Ubuntu 14.04, Windows 8.1
###### What did you do?

Created two migrations. When performing the migrations in our java application (flyway-core), the two migrations where called in the wrong order (2 ran before 1).
###### What did you expect to see?

I expect that the migration with the lower version is called before the one with the later version, even if outOfOrder is set to true. The outOfOrder switch is misleading here as it ignores versions that should be already applied when multiple developers create migrations. We need this outOfOrder setting as we create multiple migrations in parallel by different developers, but we need that the migrations are applied in order regarding the version name. I propose the the setting will be renamed or new setting for "don't ignore not-yet applied versions that are past the latest applied version" will be added.
###### What did you see instead?

Migration 2 was performend before migration 1, causing an error.

**Comment by axelfontaine** [comment]
Unable to reproduce. See my commit.
