### ISSUE TITLE
callback scripts for afterInfo and beforeInfo are not called in flyway 4.0.3

### ISSUE THREAD

**Issue by fertroya** [flyway/flyway#1366]
###### What version of Flyway are you using?
4.0.3

###### What database are you using (type & version)?
postgres 9.5

###### What operating system are you using?
ubuntu

###### What did you do?
This is a follow up on issue #1271. I have a `afterInfo.sql` which is not being executed.

**Comment by fertroya** [comment]
Closing the issue; the problem was I had a suffix defined which I needed to add to the "afterInfo.sql" filename. A note on that in https://flywaydb.org/documentation/callbacks.html would be appropiate.

**Comment by axelfontaine** [comment]
Good point! Note added.
