### ISSUE TITLE
support for IBM DB2 users with dashes in username (like 'A-A')

### ISSUE THREAD

**Issue by qwazer** [flyway/flyway#1369]
###### What version of Flyway are you using?

4.0.3
###### What database are you using (type & version)?

IBM DB2 LUW 9.7
DRIVER=4.19.26
###### What operating system are you using?

linux, windows
###### What did you do?

use database user with dashes in names
like A-B-C

run flywayInfo goal

got

> Error occurred while executing flywayInfo
> 
> ```
>  Error restoring current schema to its original setting
>  DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=SET SCHEMA SRV-T;BEGIN-OF-STATEMENT;<values>, DRIVER=4.19.26
> ```

need to use next sql statement 
`set SCHEMA "A-B-C";`

instead of
`set SCHEMA A-B-C;`

**Comment by axelfontaine** [comment]
Thanks for the report. Fixed!

**Comment by pik0** [comment]
Thanks Axel for working so hard on all these bug reports! Looks like milestone 4.1 is imminent! :D

Andrew

**Comment by qwazer** [comment]
Thanks!
