### ISSUE TITLE
Command line: unable to pass war file as a location

### ISSUE THREAD

**Issue by TomDmitriev** [flyway/flyway#1370]
###### What version of Flyway are you using?
4.0.3

###### What database are you using (type & version)?
PostgreSQL 9.4

###### What operating system are you using?
Linux 3.16.0-38-generic amd64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
According to #824 classpath scanner should be able to locate sql files under WEB-INF/classes directory in a WAR file. The problem is it seems to be impossible to tell flyway to look inside a certain WAR file when it is used via command line. Here is what I type in:
`./flyway locations=classpath:/path/to/dir/my.war migrate`
And here is what I get:
`Unable to resolve location classpath:path/to/dir/my/war`

###### What did you expect to see?
The files under /path/to/dir/my.war/WEB-INF/classes are found. Migration is executed successfully.

###### What did you see instead?
The following error message:
`Unable to resolve location classpath:path/to/dir/my/war`

**Comment by axelfontaine** [comment]
Issue #824 was for using the API directly, not the command-line tool.

This issue is a really niche feature that I currently don't feel belongs in the main distribution. As a workaround, you can package your migration files in a jar, which you can then also bundle directly in the war if you wish.
