### ISSUE TITLE
host names should not be resolved to ip addresses [mysql] [cli]

### ISSUE THREAD

**Issue by tommc** [flyway/flyway#1372]
###### What version of Flyway are you using?
4.0.3

###### What database are you using (type & version)?
mysql 5.5.30

###### What operating system are you using?
rhel 6

###### What did you do?
Tried using this connection: flyway.url=jdbc:mysql://localhost/schema

###### What did you expect to see?
Successful connection.

###### What did you see instead?
Connection refused.  admin@localhost has access to the database I'm trying to connect to, but flyway is trying to connect 127.0.0.1.  Here's the output: ERROR: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost/schema) for user 'admin': Could not connect: Access denied for user 'admin'@'127.0.0.1' to database 'schema'.

This akin to trying to connect to an https web site using the ip address.  I.e. your browser will warn you about a certificate mismatch if you try to connect to google.com via it's ip address: https://216.58.193.78

As a work-around I added a admin@127.0.0.1 mysql user, but it would be better if flyway followed the rules.

**Comment by axelfontaine** [comment]
Flyway passes the JDBC url as-is to your JDBC driver. This is not an issue  we can fix on our end.

**Comment by tommc** [comment]
thanks. I opened an issue on the mariadb connector jira.
