### ISSUE TITLE
Flyway Username And Password For Oracle Wallet

### ISSUE THREAD

**Issue by vickie1991** [flyway/flyway#1373]
###### What version of Flyway are you using?

Flyway 3.2
###### What database are you using (type & version)?

Oracle 12C
###### What operating system are you using?

Windows
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I have configured Oracle Credentials in a Oracle Wallet so that I can connect to oracle DB as /@Username

I configured Flyway as flyway.user = /@Username

and kept the Password as Blank.  When I tried to connect to DB through Flyway, it says invalid username, password.

With wallet I can connect to DB without credentials and only from server where it has been configured.
###### What did you expect to see?

I wish to login the same way as that of Logging in through Wallet user
###### What did you see instead?

Instead I get invalid credentials.

**Comment by axelfontaine** [comment]
This is not a Flyway issue. Follow the steps outlined here and you should be OK: http://stackoverflow.com/a/9772728/350428

**Comment by vickie1991** [comment]
I am not using Java Code to handle system properties.  All I have it is Oracle Wallet and Flyway.  I have configured the TNS_Name, Wallet_Location, CLASSPATH as mentioned in the link in the Environment Variables and trying to start Flyway... Yet it error out with Configure url, user, password

In url section I mentioned jdbc:oracle:thin:/@Walletuser

flyway.user and flyway.password left blank as it has to override

**Comment by rikcarve** [comment]
Actually I think it is a flyway issue. Let me explain: Making 'Oracle Wallet' work requires NOT setting a username/password. With the current command-line version of flyway this is not possible as it prompts for user/password when not providing them in the config.
I would personally suggest to add parameter "--no-prompt", to disable the call to promptForCredentialsIfMissing() in the Main class of the commandline project.

**Comment by axelfontaine** [comment]
Wouldn't putting a blank user and password in the config and including the wallet user in the url do the trick here?

**Comment by axelfontaine** [comment]
This has now been implemented as part of #1477
