### ISSUE TITLE
Failed to upgrade flyway from 2.0.2 to 4.0.3 (via 3.2.1)

### ISSUE THREAD

**Issue by zoza** [flyway/flyway#1374]
###### What version of Flyway are you using?
2.0.2 
3.2.1
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

java

###### What database are you using (type & version)?
postgres

###### What operating system are you using?
ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
upgrade flyway from 2.0.2 to 3.2.1 and to 4.0.3

###### What did you expect to see?
all ok

###### What did you see instead?
error.
##############

version 4.0.3 have upgradeMetaDataTable.sql with:
ALTER TABLE "${schema}"."${table}" DROP CONSTRAINT "${table}_pk";

version 3.2.1 have createMetaDataTable.sql with:
ALTER TABLE "${schema}"."${table}" ADD CONSTRAINT "${table}_pk" PRIMARY KEY ("version");

but don't have upgradeMetaDataTable.sql at all

and version 2.0.2 don't have 'CONSTRAINT "${table}_pk" '

so you cant upgrade from 2.0.2 to 3.2.1 to 4.0.3

**Comment by zoza** [comment]
UPDATE

i see that 2.1 have upgradeTo21Format.sql with:
ALTER TABLE "${schema}"."${table}" ADD CONSTRAINT "${table}_pk" PRIMARY KEY ("version");

but we already upgraded to 3.2.1

**Comment by axelfontaine** [comment]
The upgrade path is always clean if you move to the last minor and patch version of the current major version, before moving to the next major version.

In your case your best bet may be to simply drop the metadata table and recreate it using baseline.
