### ISSUE TITLE
risky cleanDisabled default value

### ISSUE THREAD

**Issue by chrstnk** [flyway/flyway#1376]
###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
integrating with flyway with a database that already has tables

###### What did you expect to see?
cleanDisabled has a defensive default of YES

###### What did you see instead?
cleanDisabled has a default of NO

**Comment by axelfontaine** [comment]
We are happy with the current default as people usually start using Flyway in dev (where the current default is fine) before moving to test and prod.
