### ISSUE TITLE
Add options to support managing multiple schemas more cleanly

### ISSUE THREAD

**Issue by bladeoflight16** [flyway/flyway#1378]
I would like to propose adding a couple new flags/options/keys/properties (not exactly clear what terminology is typically used) to ease managing multiple schemas.

These options would all be mutually exclusive with the `schemas` option and each other.
1. `excludedschemas`: This would switch Flyway from managing a list of schemas to managing all schemas _except_ the ones listed here.
   - This would be a comma-separated list of schema names like `schemas`.
   - This would be preferable when you want Flyway to manage most schemas in the database, including new ones added as development progresses.
2. `allschemas`: This would switch Flyway from managing a list of schemas to managing all schemas in the database.
   - This would be a `true`/`false` (on/off) value, with a default of `false`.
   - This would be preferable when you want Flyway to manage all schemas in the database, including new ones added as development progresses.

Obviously, the names could be changed, but this functionality would be very useful for the scenario when you want Flyway to manage the database as a whole instead of just individual schemas within it. Having distinct databases for different environments (rather than different schemas like in Oracle) is common with SQL Server and PostgreSQL, so this would make developing with these technologies simpler.
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-Line
###### What database are you using (type & version)?

PostgreSQL 9.3 to 9.5
###### What operating system are you using?

PostgreSQL is hosted on Linux. Flyway currently running on Windows.

**Comment by PaulStegler** [comment]
I also think this feature would be very beneficial.

**Comment by MikielAgutu** [comment]
We think this adds a fair bit of complexity without much gain.
