### ISSUE TITLE
Flyway doesn't respect changes to search_path

### ISSUE THREAD

**Issue by bladeoflight16** [flyway/flyway#1379]
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command line
###### What database are you using (type & version)?

PostgreSQL 9.3 and 9.5
###### What operating system are you using?

Windows
###### What did you do?

This is my `beforeMigrate.sql` script:

```
CREATE SCHEMA IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS hstore SCHEMA hstore;
DO $$
BEGIN
    -- This is only dynamic to grab the current DB
    EXECUTE 'ALTER DATABASE ' || current_database() || ' SET search_path TO "$user",public,hstore';
END;
$$;

-- The current session doesn't pick up on the updated search_path, so we update it manually.
SET search_path TO "$user",public,hstore;

-- This just proves our change works by calling functions without prefix
SELECT hstore_eq(hstore('akey', 'avalue'), hstore('akey', 'avalue'));
```

This is a migration script (I named mine `V1__create_a_table.sql`):

```
CREATE TABLE my_table_with_hstore(
    id SERIAL PRIMARY KEY,
    some_date HSTORE
);
```

I executed `flyway.cmd migrate`, no other arguments. I set the `url`, `user`, and `password` in the default conf file. All my files are in the default sql directory.
###### What did you expect to see?

I expected the migration to succeed on the first try.

What did you see instead?

Instead, it fails on the first try:

```
Flyway 4.0.3 by Boxfuse

Database: jdbc:postgresql://*******:5432/******* (PostgreSQL 9.3)
Successfully validated 1 migration (execution time 00:00.014s)
Executing SQL callback: beforeMigrate
Creating Metadata table: "public"."schema_version"
Current version of schema "public": << Empty Schema >>
Migrating schema "public" to version 1 - create a table
ERROR: Migration of schema "public" to version 1 - create a table failed! Changes successfully rolled back.
ERROR:
Migration V1__create_a_table.sql failed
---------------------------------------
SQL State  : 42704
Error Code : 0
Message    : ERROR: type "hstore" does not exist
  Position: 77
Location   : *******/flyway-4.0.3/sql/V1__create_a_table.sql (*******\flyway-4.0.3\sql\V1__create_a_table.sql)
Line       : 1
Statement  : CREATE TABLE my_table_with_hstore(
    id SERIAL PRIMARY KEY,
    some_date HSTORE
)
```

But it succeeds when I run again, presumably because it's picking up the updated default `search_path` on the second run:

```
Flyway 4.0.3 by Boxfuse

Database: jdbc:postgresql://xendb03:5432/johnmflywaytest (PostgreSQL 9.3)
Successfully validated 1 migration (execution time 00:00.018s)
Executing SQL callback: beforeMigrate
WARNING: DB: schema "hstore" already exists, skipping (SQL State: 42P06 - Error Code: 0)
WARNING: DB: extension "hstore" already exists, skipping (SQL State: 42710 - Error Code: 0)
Current version of schema "public": << Empty Schema >>
Migrating schema "public" to version 1 - create a table
Successfully applied 1 migration to schema "public" (execution time 00:00.043s).
```

(The `WARNING`s are normal. They're from my  `CREATE IF EXISTS` commands.)
###### Thoughts:

Note that I both `ALTER` the database level default `search_path` and `SET` the value of the current connection. This makes it extremely strange that Flyway isn't picking up on the updated `search_path`. New connections should have the database default value when they're established, and it should have the value I set in my script if the connection is reused. This means that Flyway must be setting or resetting the `search_path` somewhere.

I did some testing with PostgreSQL outside of Flyway, and it looks like PostgreSQL doesn't actually pick up on the new database default until you establish a new connection. That is,

```
SET search_path TO DEFAULT;
```

will ignore changes to the database default `search_path` until a new connection is established. Strange.

So this could be an issue where Flyway is resetting the `search_path` using built in PostgreSQL functionality, or it could be setting it to a cached value somewhere. Either way, though, this prevents you from adding extensions in a separate schema to the `search_path`.

**Comment by bladeoflight16** [comment]
I think I've found a workaround in the meantime.

You can set the `search_path` in `beforeEachMigrate.sql`. My main problem with this is that you then have to duplicate the new `search_path` in multiple places since PG wasn't recognizing the new default, but I found a way to obtain the new default. If you put this in `beforeEachMigrate.sql`, it works on the first run:

```
DO $$
DECLARE
    default_search_path TEXT := NULL;
BEGIN
    SELECT setting_value INTO default_search_path
    FROM (
        SELECT
            substring(setting from 1 for eq_position - 1) AS setting_name,
            substring(setting from eq_position + 1) AS setting_value
        FROM (
            SELECT position('=' in setting) AS eq_position, setting
            FROM (
                SELECT UNNEST(setconfig) AS setting FROM pg_db_role_setting s JOIN pg_database d ON s.setdatabase = d.oid WHERE d.datname = current_database()
            ) raw_db_role_settings
        ) presplit_db_role_settings
    ) split_db_role_settings
    WHERE setting_name = 'search_path';

    IF default_search_path IS NOT NULL THEN
        EXECUTE 'SET search_path = '||default_search_path;
    END IF;
END;
$$
```

**Comment by kpashka** [comment]
@bladeoflight16 Thanks, man, can confirm it worked for me!

**Comment by axelfontaine** [comment]
Closing as workaround is available and current default behavior is preferable for most users.

**Comment by ps2goat** [comment]
This seems inconvenient when deploying multiple schemas.  Granted, I'm trying to not type as much.

I have a schema-per-file approach for organization, and set the search path at the top of the script.  Then I know anything below that will be created in the first schema set, unless otherwise specified.

My workaround would be to just prepend `schema.` to every object.  It can be done, but it would be nice if this utility would honor calls to `set search_path`.
