### ISSUE TITLE
I am facing the following issue while trying to migrate.

### ISSUE THREAD

**Issue by practokimkb** [flyway/flyway#1380]
###### What version of Flyway are you using?

using Flyway 4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Migrating using shell script.

###### What database are you using (type & version)?

MySql

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

###### What did you expect to see?

migration should be successfull

###### What did you see instead?

Flyway 4.0.3 by Boxfuse

WARNING: Discarding INCOMPLETE dataSource configuration! flyway.url must be set.
ERROR: Unable to connect to the database. Configure the url, user and password!

###

Setting the placeholders using a shell script in the following way:-

FILE_PATH="/root/flyway-4.0.3/conf/flyway.conf"

	sed -i "s/# flyway.schemas=/flyway.schemas=$KONY_ACCOUNTS_DB_NAME/" $FILE_PATH 
	sed -i "s/flyway.url=/flyway.url=jdbc:mysql:\/\/$DB_HOST:$DB_PORT/ " $FILE_PATH 
	sed -i "s/# flyway.user=/flyway.user=$DB_USER/" $FILE_PATH 
	sed -i "s/# flyway.password=/flyway.password=$DB_PASS/" $FILE_PATH

and then trying to migrate:- 

/root/flyway-4.0.3/flyway migrate

**Comment by axelfontaine** [comment]
This is an issue with your shell script, not Flyway itself.

**Comment by practokimkb** [comment]
Hey can u guide me as to what is going wrong here...?

I have just started using shell script, and i am not able to figure out the
issue.

Thanks,
Prashant
