### ISSUE TITLE
Support multiple deployment suffixes (pl/sql -sql,prc,fnc,pck, etc)

### ISSUE THREAD

**Issue by aquimi** [flyway/flyway#1381]
###### What version of Flyway are you using?
flyway 4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java, Gradle

###### What database are you using (type & version)?
Oracle 10.2

###### What operating system are you using?
System     : GNU/Linux
Kernel Ver : Linux 2.6.32-431.el6.x86_64
OS Release : Red Hat Enterprise Linux Server release 6.5 (Santiago)
Platform   : x86_64

###### What did you do?
Configure multiple suffixes, as in my workplace we use the pl / sql and have suffixes like sql, prc, pck, view, test, but currently only displays flyway .sql me.

I think I have the solution with a little  change develop, but I want to know if someone else needs.

The deployment command was:
flyway.migrate ()

###### What did you expect to see?
Someone else that needs development

@axelfontaine Waiting for your comment

**Comment by aquimi** [comment]
![support flyway](https://cloud.githubusercontent.com/assets/15113824/17255906/bf281630-5580-11e6-806e-54c04f5f8456.jpg)

**Comment by axelfontaine** [comment]
Simply go with an empty suffix and you should already have the result you want.

**Comment by aquimi** [comment]
Thanks you
