### ISSUE TITLE
Inconsistent usage documentation: `conf/flyway.conf` vs `conf/flyway.properties` vs `./flyway.conf`

### ISSUE THREAD

**Issue by sw00** [flyway/flyway#1382]
I'm using flyway as a standalone CLI and found the information with regard to the default `configFile` option to be inconsistent and confusing. As I understand, flyway will look for a `conf/flyway.properties` only if invoked as a Maven plugin and not as a CLI.

```
$ flyway -h
Flyway 4.0.3 by Boxfuse

Usage
=====

flyway [options] command

By default, the configuration will be read from conf/flyway.conf.
Options passed from the command-line override the configuration.
```

```
configFile                   : Config file to use (default: conf/flyway.properties)
```

**Comment by axelfontaine** [comment]
Flyway will look for config files in the order specified here: https://flywaydb.org/documentation/commandline/#configFile

Works as designed.

**Comment by sw00** [comment]
Hi, thanks for looking at this.

In your link, I see no mention of a `flyway.properties` file - only `flyway.conf`. 

If you could, please explain where a `*.properties` file is loaded from when using the CLI - I can find no line where this happens in `org.flywaydb.commandline.Main`.

**Comment by axelfontaine** [comment]
Sorry I was a bit too quick here. Please see my comment on #1383

**Comment by sw00** [comment]
Great, thanks for the clarification. See https://github.com/flyway/flyway/pull/1383
