### ISSUE TITLE
Feature Request: Automatic placeholder containing name of schema I'm operating on.

### ISSUE THREAD

**Issue by janzankowski** [flyway/flyway#1384]
### Problem

I'd like to run a Flyway SQL script using the command line interface, and apply it in sequence to multiple schemas. Inside of the SQL script, I'd like to use a placeholder for the schema name that I'm currently operating on.
### Proposed solution

Automatically define a placeholder variable with some distinct name, e.g. _CURRENT_SCHEMA_, containing the name of the schema that Flyway is currently acting on.
### Existing workaround

Use `-placeholders.myPlaceholder=..` option.
### Why proposed solution is better than workaround
- Shorter commands.
- Avoid errors when I forget to specify the placeholder.
- Avoid errors when I set placeholder to something else than the schema name specified in the Flyway URL.

**Comment by axelfontaine** [comment]
Related to #1039
