### ISSUE TITLE
Script column of schema version table, showing scripts with name trimmed(1001__t.sql, instead of V1001__t.sql)

### ISSUE THREAD

**Issue by ranas7786** [flyway/flyway#1390]
###### What version of Flyway are you using?

flyway-commandline-4.0.2.tar.gz (without JRE)
and
flyway-commandline-4.0.2-windows-x64.zip
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

MAVEN
###### What database are you using (type & version)?

Oracle 11.2.0.4.0
###### What operating system are you using?

UNIX
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

My folder structure is : 
folder 1      : flyway\ddl ; flyway\ddl\procs
files in ddl : V10001__t_t1.sql , V10002__t_t2.sql
file in procs folder : R__proc1.sql

CASE 1 -
On executing migrate command on my local machine using **flyway-commandline-4.0.2-windows-x64.zip**,  the schema_version table column "SCRIPT" , shows data as :
_V10001__t_t1.sql
V10002__t_t2.sql
proc/R__proc1.sql_

CASE 2 -
On executing migrate command on our server machine configured using maven, using **flyway-commandline-4.0.2.tar.gz (without JRE)**,  the schema_version table column "SCRIPT" , shows data as :
_10001__t_t1.sql
10002__t_t2.sql
roc/R__proc1.sql_
###### What did you expect to see?

For CASE 2 also I expect , the results to be same as in CASE 1.
But somehow, names of scripts(including folder path) are being left trimmed by one character
###### What did you see instead?

CASE 2

**Comment by axelfontaine** [comment]
Hmmm... the code is 100% identical for all distributions, so I am afraid you'll need to dig a little deeper to find out what is going on. How do the configurations and the debug output compare?

**Comment by ranas7786** [comment]
Config file is same. Debug, I will compare and confirm in some time.

**Comment by ranas7786** [comment]
have compared both debugs(commandline windows and commandline tar.gz ).
Both are deploying in same manner.. 

Example of Repeatable Migration script
_**windows**:--
DEBUG: Successfully completed migration of schema "SCHEMA1" with repeatable migration log rx
DEBUG: MetaData table "SCHEMA1"."schema_version" successfully updated to reflect changes

**tar.gz** :--
259	notice	DEBUG: Successfully completed migration of schema "SCHEMA1" with repeatable migration log rx
260	notice	DEBUG: MetaData table "SCHEMA1"."SCHEMA_CODE" successfully updated to reflect changes_

**Comment by ranas7786** [comment]
@axelfontaine  Any clue buddy?

**Comment by axelfontaine** [comment]
I am afraid we'll need more information to be able to find the problem here. Can you post a _minimal_ GIthub repo with instructions to _clearly_ reproduce the issue?

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter

**Comment by mehta-m** [comment]
This happened for me too. Check if you have doub '\\' in the conf file - flyway.locations.
There should only be a single back slash: '\'

**Comment by ranas7786** [comment]
@mehta-m  Thanks for response.. I will check.

Because of on restricted networks, I can't simulate the same scenario at home. so can't explain the issue. But it is still happening in our project. The tar.gz file is placed on Unix server and is being called using PUPPET from an internal CD tool.
