### ISSUE TITLE
Classpath scanner for JAR files

### ISSUE THREAD

**Issue by esaichik** [flyway/flyway#1391]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using?
Maven plugin

###### What database are you using (type & version)?
PostgreSQL 9.5

###### What operating system are you using?
Win 10

###### What did you do?
I've got multi module application (i.e. few war files and few jar files). Some war (!) files should contain migrations. To read them from Flyway I've added these files to dependencies in plugin configuration. I configured settings, names, dependencies, etc.
So. If I configure migration location &lt;location&gt;classpath:db/migration&lt;/location&gt; Flyway unable to find migrations. Even if I configure migration location &lt;location&gt;classpath:WEB-INF/classes/db/migration&lt;/location&gt;. But. Flyway can see migrations in jar files if migration location configured &lt;location&gt;classpath:db/migration&lt;/location&gt;.
I solved this trouble by next way: I configure migration location &lt;location&gt;classpath:WEB-INF/classes/db/migration&lt;/location&gt; and made changes in flyway-core\src\main\java\org\flywaydb\core\internal\util\scanner\classpath\JarFileClassPathLocationScanner.java:
```java
public Set<String> findResourceNames(String location, URL locationUrl) throws IOException {
        JarFile jarFile = getJarFromUrl(locationUrl);
        try {
            // For Tomcat and non-expanded WARs.
            String prefix = jarFile.getName().toLowerCase().endsWith(".war") ? "WEB-INF/classes/" : "";
            return findResourceNamesFromJarFile(jarFile, prefix, location);
        } finally {
            jarFile.close();
        }
    }
```
was replaced to
```java
public Set<String> findResourceNames(String location, URL locationUrl) throws IOException {
        JarFile jarFile = getJarFromUrl(locationUrl);
        try {
            String prefix = "";
            return findResourceNamesFromJarFile(jarFile, prefix, location);
        } finally {
            jarFile.close();
        }
    }
```

**Comment by axelfontaine** [comment]
Using war as jars is really not a common scenario. In addition to that the changes here break Tomcat support for non expanded wars. You also have a workaround available: extract the wars in /target and read the migrations from the file system.

I think we'll leave this as won't fix for now.
