### ISSUE TITLE
Callbacks for errors

### ISSUE THREAD

**Issue by ctmay4** [flyway/flyway#1392]
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API
###### What database are you using (type & version)?

PostgreSQL
###### What operating system are you using?

CentOS, Windows
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

This is not a bug, but a use-case I don't think is handled.  For our migrations, we have a "pre()" script that runs before we do migrations.  It's purpose is to revoke connection privileges to other users to the database we are migrating.  It works perfectly with a `beforeMigrate` callback.  We also have a "post()" script that restores the connect privileges.  We are using `afterMigrate` for that.  When the `migrate()` call is successful, this works fine.  When one of the migration scripts fails, however, we still want to run our post script.  However `afterMigrate` is not triggered if one of the scripts fails.  

Is there a way have a callback that is called after a migration whether the migration was successful or not?

**Comment by axelfontaine** [comment]
This has now been implemented. We added error callbacks for all actions, not just migrate.
