### ISSUE TITLE
clean command not removing vertica temporary tables

### ISSUE THREAD

**Issue by zvika77** [flyway/flyway#1404]
###### What version of Flyway are you using?

flyway-4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line
###### What database are you using (type & version)?

vertica 7.1.1-10
###### What operating system are you using?

centos 6.8
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

./flyway -X -schemas=stage -location=/Users/zvika/Downloads/sql  -placeholders.zvika1_owner=etl clean
###### What did you expect to see?

the stage schema will be empty from objects
###### What did you see instead?

one temporary table

**Comment by axelfontaine** [comment]
@nathanvick Thoughts?
