### ISSUE TITLE
Flyway for Android migrates from 3.x to 4.x unnecessarily every time migrate is called

### ISSUE THREAD

**Issue by jonschmidt** [flyway/flyway#1408]
###### What version of Flyway are you using?

FlyWay 4.0.3 / SqlDroid 1.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java Api
###### What database are you using (type & version)?

SQLite 3.9.2:
###### What operating system are you using?

Android (Nougat, but any version should do)
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Implemented database migrations on application startup
###### What did you expect to see?

Flyway executing my migrations, and no other significant work on startup
###### What did you see instead?

Flyway takes too long to execute, because it falsely performs a migration from flyway 3.x to 4.x everytime `migrate()` is called. This takes anywhere from 200 - 500 ms rendering it more or less unusable on Android.

The problem seems to be in the way FlyWay checks to see whether it should be migrated or not. It checks whether the metadata table has the column version_rank

https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/metadatatable/MetaDataTableImpl.java#L68

Internally, this uses SQLDroid to check for the existence of the column, by passing the column name into the columnNamePattern here

https://github.com/SQLDroid/SQLDroid/blob/master/src/main/java/org/sqldroid/SQLDroidDatabaseMetaData.java

Which is never used in that function, so it will always return true, and FlyWay will think it needs to migrate every time you start the app, adding a few hundred ms to the operation.

I opened a stackoverflow issue with not much progress here : http://stackoverflow.com/questions/38919267/flyway-for-android-takes-500ms-to-do-absolutely-no-migrations

**Comment by axelfontaine** [comment]
This sounds like a SQLDroid issue. Did you open an issue with them?

**Comment by jonschmidt** [comment]
https://github.com/SQLDroid/SQLDroid/issues/75

**Comment by jonschmidt** [comment]
Can we keep this open until we hear from them? I agree it is an issue in that library of course.

**Comment by axelfontaine** [comment]
Closing as it is an SQLDroid issue.
