### ISSUE TITLE
Plugin Migration Support

### ISSUE THREAD

**Issue by digulla** [flyway/flyway#1409]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What did you do?
We have a software with a core and plugins. Some plugins need additional database tables. It would be nice to have a "plugin" feature or a "defined baseline" like so:

```
flyway.baseline = extends # Extend an existing Flyway managed database
flyway.extend.table = ...core metadata table; defaults to schema_version...
flyway.extend.version = ...version of the core migration...
```

The migration should fail if the core/parent metadata table doesn't contain the specified version.

Using this approach, you could have any number of recursive migrations, one for each plugin. This wouldn't protect you against plugins using the same table names but I feel this would be a better than disabling all checks when the database isn't empty.

**Comment by axelfontaine** [comment]
I am unsure about this. Wouldn't it be simpler to let the plugins contribute migrations to the main application and have just one regular Flyway workflow?

**Comment by digulla** [comment]
Dependencies kill you. Look at Eclipse. Dozens of teams contribute plugins. The core just defines an API per version. As long as you compile against the correct API/version tuple, your plugin will work. The main app doesn't need to know about the plugins. Plugins don't need to know about each other. Anyone can write plugins.

Using your approach, any change to a plugin would cause a new release of the main application. Which could cause a release of many other plugins. A change that I make would trigger work for many other people. That doesn't scale.

With my approach, the main app doesn't care about plugins. Each plugin just tracks it's parent (usually the app itself). When I need more migrations for my plugin, I just add them as needed. Only users who have my plugin installed need to care about it, no one else. Each plugin is as isolated from everyone else as possible.

**Comment by axelfontaine** [comment]
Well if it is isolation you want, then why not simply give each plugin its own Flyway instance and metadata table and optionally enforce compatibility with the parent via plugin metadata?

**Comment by digulla** [comment]
I feel that you're not considering the downsides of your suggestions.

Right now, I can only run the plugin migrations when I say `baselineOnMigrate=true` which means that plugin migrations have no way to know whether the actual core migration has been run or what core version the database is at. That's junior level programming where the developer assumes that everything will be all right - if something breaks someone else will fix it and who cares how long it takes and how much it costs. I believe in fail early and with a useful error message. I prefer "expected database with core version V1_0_33" over "there was some SQL error but I'm not telling you any details."

I guess I could insert a Java step in every plugin which checks and fails accordingly. Another solution would be an SQL script which queries the core metadata table but I couldn't find a way to make it fail when the version is wrong; it only fails when the table is missing.

Maybe my core concern is that `baselineOnMigrate=true` is such a killer switch. Instead, I'd prefer some kind of custom check that replaces the "schema is empty" check.

Maybe a new property which defines which task to run pre-migration with the "schema must be empty" check being the default?

**Comment by axelfontaine** [comment]
Oh trust me. I am considering much more than you think. Including the impact of an additional setting on all the different use cases Flyway currently supports, the new combinations this potentially opens up and what the effect is both on existing users and the overall complexity of the product.

**Comment by digulla** [comment]
I found a solution which works for me.
