### ISSUE TITLE
Feature Request: MigrationInfo should expose validate() method

### ISSUE THREAD

**Issue by luengnat** [flyway/flyway#1412]
###### What version of Flyway are you using?

4.0
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API
###### What database are you using (type & version)?

Oracle
###### What operating system are you using?

Linux
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
###### What did you expect to see?

It would be nice if MigrationInfo exposes validate() which is already implemented by MigrationInfoImpl so that we can validate each migration step manually.

**Comment by axelfontaine** [comment]
Please explain why `Flyway.validate()` isn't sufficient for your needs

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter
