### ISSUE TITLE
Add SpringFlywayCallback

### ISSUE THREAD

**Issue by edbrannin** [flyway/flyway#1414]
###### What version of Flyway are you using?  (etc.)

None yet, just reading the docs.  https://flywaydb.org/documentation/api/hooks#callsbacks

###### What did you expect to see?

I like how there is a `SpringJdbcMigration`, but it would be nice to have a similar interface/base-class for `FlywayCallback`.

###### What did you see instead?

No other Spring-related classes except `(Base)?SpringJdbcMigration`

**Comment by axelfontaine** [comment]
Could you describe your usecase in a bit more detail? What problem exactly would this solve?

**Comment by edbrannin** [comment]
Honestly I haven't yet started migrating my team's DDL to Flyway and I don't know if we will want to use a `FlywayCallback` for anything now that repeatable migrations exist. 

That said, if I were to want to implement `FlywayCallback`, I would much rather do it with a `JdbcTemplate` than a bare JDBC `Connection`. 

I would understand if this is so low a priority you want to close the issue for now. But having `SpringJdbcMigration` without `SpringFlywayCallback` seems like a gap in the API.

**Comment by axelfontaine** [comment]
We are very careful about adding new features and only do so when there is a real need. With such a large install base, every feature we add requires careful though as well as time (our most valuable commodity) to implement, test and maintain.
