### ISSUE TITLE
Request: prompt for missing password on Maven execution

### ISSUE THREAD

**Issue by lfischer** [flyway/flyway#1417]
###### What version of Flyway are you using?

4.0.3
###### Which client are you using?

Maven plugin
###### What did you do?

Executing one of the maven goals. Without specifying the _password_ parameter.
###### What did you expect to see?

An interactive password prompt.
###### What did you see instead?

```
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:4.0.3:migrate (default-cli) on project mfc-communication: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:postgresql://localhost:63334/postgres) for user 'admin': FATAL: password authentication failed for user "admin" -> [Help 1]
```

**Comment by MikielAgutu** [comment]
There hasn't been any reaction to this issue since it was created. @lfischer do you still think this is important?

**Comment by alextercete** [comment]
Closing due to lack of interest.
