### ISSUE TITLE
Clustered migration hangs - postgresql

### ISSUE THREAD

**Issue by nampas** [flyway/flyway#1421]
###### What version of Flyway are you using?
4.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
PostgreSQL 9.5.3

###### What operating system are you using?
Centos 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
We do rolling deploys of our web servers, 3 instances at a time. We do Flyway migrations on startup. Occasionally, we'll have one instance fail to start up. It will hang while attempting to run migration. The final log statements we see are as follows:

```
2016-08-29 13:31:09,497 localhost-startStop-1:org.flywaydb.core.internal.command.DbMigrate []
WARN outOfOrder mode is active. Migration of schema "public" may not be reproducible.
2016-08-29 13:31:09,503 localhost-startStop-1:org.flywaydb.core.internal.dbsupport.JdbcTemplate []
WARN DB: there is already a transaction in progress (SQL State: 25001 - Error Code: 0)
```

Migration is kicked off like so:
```
Flyway flyway = new Flyway();
flyway.setDataSource(dataSource);
flyway.setOutOfOrder(true);
flyway.migrate();
```

###### What did you expect to see?
If 2 web servers instances try to run migration at the same time, I'd expect the instance that issues the SQL statement first to lock the db during execution. The 2nd instance should block until the migration has run, and the lock is lifted. Then both instances should continue startup.

###### What did you see instead?
It appears that migrations are sometimes unable to recover when they encounter a lock on the metadata table. In that case, they just hang. And we have to kill the process and re-start the server.
This is an intermittent issue, sometimes all instances start up fine.

I'm digging around the Flyway code to see how it handles locking, and how it recovers from contention, but I thought I'd post this in the meantime, in case anyone has insight on the issue.

Thanks!

**Comment by nampas** [comment]
Turns out this was caused by something else

**Comment by rhamedy** [comment]
@nampas I come across the same issue and I wonder what is the *cause* and proposed solution? Do you mind sharing your findings on this issue? 

I am using the *flyway 4.0.3* gradle plugin to migrate PostgreSQL 9.6.1 database on a Ubuntu 16.04 VM. 

Cheers.

**Comment by wayne-o** [comment]
> Turns out this was caused by something else

Grrrrr cheers - super heplful

**Comment by nampas** [comment]
@wayne-o  @rhamedy Sorry. This was a while a go so I don't remember it super well. But I'm pretty sure in our case it was caused by a lock-heavy postMigrate script. If I remember correctly, postMigrate runs on every instance (??), even instances that don't apply any migrations, so our scripts was deadlocking against other instances running the same script.

**Comment by wayne-o** [comment]
Hi! Thank you for getting back. I’ve posted an issue as I’m sure it’s a bug somewhere or maybe some missing docs
