### ISSUE TITLE
Flyway compatibility with Java 8 in JDK 8.0 compatibility mode

### ISSUE THREAD

**Issue by sachinwalia2k8** [flyway/flyway#1423]
###### What version of Flyway are you using?

Flyway 4.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

Oracle 11g XE

###### What operating system are you using?

Centos, Ubuntu 16

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

- Created Java based Migration JAR with JDK 8 compatibility mode to use some streaming features by extending JdbcMigration.
- Tried to apply migration

###### What did you expect to see?

- Migration should have been successful

###### What did you see instead?
- Migration failed with "Java unsupported major minor version 52.0".

**Comment by axelfontaine** [comment]
This is caused by the JRE you use to run Flyway. To make things easy, simply pick the Flyway download with a bundled JRE and all Java 8 features should work.
