### ISSUE TITLE
flyway didn't migrate all schema but report migrate successfully

### ISSUE THREAD

**Issue by winger007** [flyway/flyway#1425]
###### What version of Flyway are you using?

flyway-3.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

mysql  Ver 15.1 Distrib 5.5.47-MariaDB, for Linux (x86_64) using readline 5.1

###### What operating system are you using?

CentOS Linux release 7.2.1511 (Core)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Due to I add some new sql to  V1.x__schema.sql , I run "flyway migrate" to migrate my schema.
As I expect, this operation failed, reports checksum is not match.
Then I use "flyway repair" to clean this version schema_version, and run "flyway migrate"  again.
flyway reports migrate successfully.

###### What did you expect to see?

All schema should be updated

###### What did you see instead?
Some schema didn't update to database

**Comment by winger007** [comment]
seems repair will only to update the checksum, so I should manual migrate the database firstly and then repair the checksum.

**Comment by axelfontaine** [comment]
Correct. With repair Flyway only fixes the metadata table. You still need to manually undo any other changes before running migrate again.
