### ISSUE TITLE
Make Gradle 3.0 the new minimum supported version

### ISSUE THREAD

**Issue by djohnsonmach** [flyway/flyway#1429]
###### What version of Flyway are you using?

4.0.3 (also tried 4.0.2)
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Gradle plugin
###### What database are you using (type & version)?

MySQL 5.6.27
###### What operating system are you using?

MacOS X
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Created a custom Gradle task in the buildSrc directory that extends AbstractFlywayTask with Gradle 3.0.  (Works fine in Gradle 2.13).  I created a sample project to duplicate the issue, which can be found here: [Gradle 3.0/FlywayDB 4.0.3 Issue](https://github.com/djohnsonmach/gradle-flywaydb-issue)

Ran the command:

`./gradlew build`
###### What did you expect to see?

Expected to be able to perform a Gradle build, including database migrations.
###### What did you see instead?

The build fails with an exception:

```
Dustins-MBP:gradle-flywaydb-issue djohnson$ ./gradlew build
Listening for transport dt_socket at address: 5006
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Unable to load class org.flywaydb.gradle.task.AbstractFlywayTask due to missing dependency org/gradle/api/internal/DynamicObject
```

**Comment by djohnsonmach** [comment]
From the same issue posted on the Gradle forums, it appears the solution may be to simply release another version to clear up the bytecode incompatibiility:

https://discuss.gradle.org/t/missing-dependency-org-gradle-api-internal-dynamicobject-prevents-extending-plugin-task/19472/2

**Comment by axelfontaine** [comment]
We have now bumped the minimum supported Gradle version to 3.0 as part of the Flyway 5.0 release.
