### ISSUE TITLE
Having only Repeatable Migrations crashes Flyway

### ISSUE THREAD

**Issue by cristalp** [flyway/flyway#1430]
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line
###### What database are you using (type & version)?

Oracle, SQL Server
###### What operating system are you using?

Red Hat Linux
###### What did you do?

We're using the new Repeatable Migration feature. However, in one of our JARs there was no migration script, just a Repeatable Migration script. Flyway apparently doesn't like that  ;-)
`ERROR: java.lang.ArrayIndexOutOfBoundsException: -1`
###### What did you expect to see?

I would have liked the Repeatable Migration to be executed.
###### What did you see instead?

The error above

**Comment by axelfontaine** [comment]
Could you please post the full stacktrace?

**Comment by cristalp** [comment]
Sure:

`
Successfully validated 25 migrations (execution time 00:00.076s)
SQLServer does not support setting the schema for the current session. Default schema NOT changed to dbo
DEBUG: Schema [dbo] already exists. Skipping schema creation.
DEBUG: Locking table [dbo].[schema_version]...
DEBUG: Lock acquired for table [dbo].[schema_version]
Current version of schema [dbo]: 2.1.0.35
WARNING: outOfOrder mode is active. Migration of schema [dbo] may not be reproducible.
ERROR: Unexpected error
java.lang.ArrayIndexOutOfBoundsException: -1
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:201)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:139)
        at org.flywaydb.commandline.Main.main(Main.java:102)
`

**Comment by satahippy** [comment]
@cristalp do you apply migrations from different applications?
like you have one application that apply migrations from location1, and another from location2?

**Comment by cristalp** [comment]
We have different applications that define the database server and schema with different paths, like db/migration/database/schema/V1.0.0__my_script.sql. During the build, all scripts found for an application are packed into a ZIP file. Then we have a shell script that takes the ZIP file, unpacks it and applies all migrations that it finds. Our Flyway configuration has a correspoding directory structure with /stage/database/schema/conf/flyway.conf
I hope I understood correctly what you were asking  :-)

**Comment by satahippy** [comment]
Just we have the same issue.
We are using one database for different parts of application and each part has its own migrations set and they apply independently.
And i don't sure that flyway allow this :smile:

**Comment by cristalp** [comment]
Well, most of our application just use one database and leave the others alone. But there's one database which is used by most applications, and for that database we set `outOfOrder` to `true`, and we will probably also set `validateOnMigrate=false`, since some applied migrations from other applications may be missing for the application. It's ugly, I admit, but it's the only way it works.

**Comment by blai-cartera** [comment]
I believe I just ran into this error as well, even on 4.1.1 which has your commit https://github.com/flyway/flyway/commit/beae6ffc3768dae56f6deb7534194f10f1e1d140

However, the commit seems like it just adds some tests. Am I missing something?

**Comment by 18thletter** [comment]
@blai-cartera I just ran into this as well. Looks like it's still not fixed on 4.1.2.

**Comment by axelfontaine** [comment]
@18thletter Please open a new issue and provide *exact* steps on how to reproduce.

**Comment by axelfontaine** [comment]
@blai-cartera We have a test that covers this exact scenario and it passes: https://github.com/flyway/flyway/blob/master/flyway-core/src/test/java/org/flywaydb/core/FlywayMediumTest.java#L637

**Comment by jbrusis** [comment]
I just ran into the same error with version 4.1.2. Having configured a location on the filesystem that only contains repeatable migrations led to the same ArrayIndexOutOfBoundsException as above. I then added a versioned dummy script and it worked.

**Comment by axelfontaine** [comment]
@jbrusis Please open a new issue and provide exact steps on how to reproduce.
