### ISSUE TITLE
The input streams used to read resource bytes are not closed properly

### ISSUE THREAD

**Issue by lgoldstein** [flyway/flyway#1431]
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API + Maven

###### What database are you using (type & version)?

PostgreSQL 9.3

###### What operating system are you using?

Fedora 23

###### What did you do?

Reviewed the code

###### What did you expect to see?

The code in both `ClassPathResource` and `FileSystemResource` obtains an `InputStream` but never closes it. While it is true that the stream will be closed eventually, it may cause a problem with having too many open files/descriptors at once. The fix is simple: either use a _try-with-resource_ or _try-finally_ block to ensure that the stream is closed once its bytes have been read.

###### What did you see instead?

Stream not closed.

**Comment by axelfontaine** [comment]
This is not correct. The `FileCopyUtils` call does cleanly close the streams/files. Please reopen with a testcase if you believe this doesn't work in its current form.
