### ISSUE TITLE
Recommend making MetaDataTableImpl#createIfNotExists public

### ISSUE THREAD

**Issue by lgoldstein** [flyway/flyway#1433]
It is a useful method to invoke in certain circumstances

###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API + Maven

###### What database are you using (type & version)?

PostgreSQL 9.3

###### What operating system are you using?

Fedora 23

**Comment by axelfontaine** [comment]
This is private API not meant for outside consumption.
