### ISSUE TITLE
In OSGI environment with duplicated resource paths wrong resources being loaded

### ISSUE THREAD

**Issue by renat-sabitov** [flyway/flyway#1442]
###### What version of Flyway are you using?

4.0.1
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API
###### What database are you using (type & version)?

Postgres
###### What operating system are you using?

Linux
###### What did you do?

We have flyway in OSGI environment where each bundle has it's own migrations and another bundle let's call it manager runs migrations for every bundle separately. Each bundle has it's own version history. Given two bundles have migrations with same path:

Bundle1: 
db/migrations/V1__create_db.sql 

Bundle2:
db/migrations/V1__create_db.sql 
###### What did you expect to see?

while loading resources for Bundle1 and Bundle2 flyway loads files from the corresponding bundle
###### What did you see instead?

while loading resources for Bundle1 and Bundle2 flyway always loads the same file

This is because flyway loads resources via

`classLoader.getResourceAsStream(location)`

instead of

`resourceUrl.openConnection().getInputStream()`

see `org.flywaydb.core.internal.util.scanner.classpath.ClassPathResource`

**Comment by axelfontaine** [comment]
Did you set the ClassLoader correctly with `Flyway.setClassLoader()`?

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
