### ISSUE TITLE
Flyway Migration fails with "Specified key was too long; max key length is 767 bytes" while using with MySQL

### ISSUE THREAD

**Issue by prasadus92** [flyway/flyway#1443]
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

MySQL 5.6.21

###### What operating system are you using?

Mac El Captain 10.11.4 (15E65)

###### What did you do?

Migration fails with the below error:

`Specified key was too long; max key length is 767 bytes`

This happens for the below DDL:

`CREATE TABLE RMATCH.mapping_info (
      id int(11) NOT NULL AUTO_INCREMENT,
      child_sku varchar(500) NOT NULL,
      parent_sku varchar(500) DEFAULT NULL,
      src_retailer varchar(100) DEFAULT NULL,
      boomerang_id varchar(1001) DEFAULT NULL,
      dst_sku varchar(500) NOT NULL,
      dst_retailer varchar(100) DEFAULT NULL,
      dst_parent_sku varchar(500) DEFAULT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY i_uniq (child_sku, dst_sku, dst_retailer),
      KEY i_parentsku (parent_sku),
      KEY i_boomerangid (boomerang_id),
      KEY i_dstsku (dst_sku),
      KEY i_dstretailer (dst_retailer),
      KEY i_dstparentsku (dst_parent_sku),
      KEY i_childsku (child_sku)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1`

If I run the same CREATE statement directly on the DB, it works without any issue/error.

###### What did you expect to see?

CREATE statement mentioned above would have executed successfully.

###### What did you see instead?

Migration failed with `Specified key was too long; max key length is 767 bytes`.

**Comment by axelfontaine** [comment]
This is a common issue with MySQL due to the length of your keys (`boomerang_id varchar(1001)`) with InnoDB. Reduce the length of the key or upgrade MySQL to 5.7 to fix. Flyway simply passes your statement unchanged to the JDBC driver and database.

**Comment by prasadus92** [comment]
Thanks Axel.
