### ISSUE TITLE
Add ignoreMissingMigrations flag

### ISSUE THREAD

**Issue by expeditioneer** [flyway/flyway#1447]
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API
###### What database are you using (type & version)?

h2 1.3.175
###### What operating system are you using?

Windows
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Removed already applied migration script
###### What did you expect to see?

Flyway ignoring the missing, but already applied migration
###### What did you see instead?

Validate failed: Detected applied migration not resolved locally

This was maybe introduced by accident with #988.

Possible solution:
Check also for the MigrationState.MISSING SUCCESS in MigrationInfoImpl::validate()

**Comment by axelfontaine** [comment]
The solution here would be to have something like an `ignoreMissingMigrations` flag, set to `false` by default. You could then set it to `true`to get the behavior you want.

**Comment by gsaslis** [comment]
👍  need this too

**Comment by sdrzazga** [comment]
we need this too

**Comment by axelfontaine** [comment]
Duplicate of #1352
