### ISSUE TITLE
Update Gradle Version!

### ISSUE THREAD

**Issue by aadrian** [flyway/flyway#1450]
Please upgrade the Gradle version to a more current one!
_(FlyWay seems to use Gradle 1.6 ~Apr 2013, and considering how much has changed in Gradle since that time, that version is very old by all standards )_

Thank you.

**Comment by axelfontaine** [comment]
Are you running into any specific issues?

**Comment by aadrian** [comment]
> Are you running into any specific issues?

It's not even building on new machines that have not m2 cache :).

**Comment by axelfontaine** [comment]
What I meant was: Are you hitting any issues at runtime?

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter
