### ISSUE TITLE
Concurrent execution of flyway tasks

### ISSUE THREAD

**Issue by mnadeem** [flyway/flyway#1451]
Not sure if flyway supports concurrent execution of tasks, if not, then it can be done very easily using [Dexecutor](https://github.com/dexecutor/dexecutor-core), its main purpose is to execute the dependent tasks in a reliable way very easily. You can refer the [wiki ](https://github.com/dexecutor/dexecutor-core/wiki) for more details. Further there is [sample application](https://github.com/dexecutor/dexecutor-examples), which demonstrate how dbmigration operation can be parallelized very easily.

**Comment by axelfontaine** [comment]
Not an issue.
