### ISSUE TITLE
Option to allow ALL repeatable scripts to run (even if unchanged).

### ISSUE THREAD

**Issue by tohagan** [flyway/flyway#1453]
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command line 
###### What database are you using (type & version)?

MySQL 5.6
###### What operating system are you using?

Windows 7
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

`flyway migrate`
###### What did you expect to see?

Feature Request: 

Needs a config, command line and API option to allow ALL repeatable scripts to run (even if unchanged) after the versioned scripts run.

Use Case: I want to recompile ALL executable code against new schema changes to ensure that the required fields and types are still valid for all existing code.  I've used this invaluable feature in other migration tools.  Very useful as a config setting on your CI server.
###### What did you see instead?

Missing feature.

**Comment by tohagan** [comment]
Currently there is also a very real risk that you accidentally script the same object twice in two different `R__` scripts.  You update one script, run `flyway migrate` and only **one** of these scripts runs (looks good & your app works ok on you dev machine so you commit the change). Now someone later performs a migration that runs **both** scripts. The later one happens to overwrite your recent change. Nasty mystery bug!  Safer to rerun all `R__` script to avoid this.

**Comment by maciejmakowski** [comment]
To add to the feature request: Could java / jdbc migrations be configured to run regardless of whether the checksum changed?

What I have done as a workaround for my repeatable java / jdbc migrations, I have implemented MigrationChecksumProvider and am returning a random Integer every time it runs. 

Does anyone have a better workaround for this? I need to make sure that the migration is running every time.

**Comment by instilled** [comment]
+1 we would also like to see this feature. We run a hierarchical set of database migrations targeting the same schema all managed by flyway. We use repeatable migrations to provide defaults for code tables and the like. Clients may override certain values with their own Flyway migration. If we now change something in the root we would like all repeatable migrations to run, including the non-changed client overrides.

**Comment by litriv** [comment]
+1 we would like this feature too for testing that repeatable migrations are idempotent.

**Comment by k0enf0rNL** [comment]
+1 We would also like this feature to be able to separate our tables, grants, default inserts and indices in different migration files especially during development.

**Comment by apexbine** [comment]
+1 Would be great to have this feature for development databases!

**Comment by flo-ryan** [comment]
+1 would be highly useful during developing phases

**Comment by PachowStudios** [comment]
This would be very handy.

My current solution is to have a comment at the top of every repeatable migration with the version of the latest migration. When the repeatable migrations need to be rerun, I just find replace on the whole project for that comment to update it to the new version.

**Comment by juliahayward** [comment]
Rather than a binary option, how would everyone feel about extending the migration naming convention:

`R__repeatableMigration.sql` runs as now, only when the file is changed,
`A__alwaysRunMigration.sql` runs on every migration?

(This also starts to work towards the Flyway Test story, as `A__` migrations would be an ideal place to include integrity checks)

**Comment by PachowStudios** [comment]
I just kinda realized that this can already be somewhat accomplished using Flyway's callbacks: https://flywaydb.org/documentation/callbacks

**Comment by alextercete** [comment]
Another option could be to add some metadata to the top of the repeatable script:

```sql
-- flyway run: always
```

**Comment by cdavid15** [comment]
> I just kinda realized that this can already be somewhat accomplished using Flyway's callbacks: https://flywaydb.org/documentation/callbacks

This is exactly how we do it. We have an afterMigrate.sql script that compiles all our packages which are defined as separate repeatable migrations and this works very well.

The call back option could provide more flexibility around the implementation as some repeatable migrations you may only wish to execute when necessary (ie only target all the package bodies excluding materilized views). The callback could do this and allows for the one off custom script to executed.

**Comment by PachowStudios** [comment]
> We have an afterMigrate.sql script that compiles all our packages which are defined as separate repeatable migrations and this works very well.

@cdavid15 could you please expound on this? How are you compiling stuff from within a SQL file? Sounds interesting.

**Comment by cdavid15** [comment]
Flyway is running against an oracle database so it’s custom plsql block that executes against the USER_OBJECTS view to determine the correct objects (packages, package bodies etc) then we loop through the results and execute the statement to compile. 

When I’m back in at work on Monday I’ll update this with a sample script. I’m sure the exact use case we used it for was when packages were invalid then we would recompile them. May not meet every use case being described above but may be useful to some.

**Comment by apexbine** [comment]
Another use case:
**Conditional Compilation** in PL/SQL

We are using conditional compilation for making some private methods accessible for utPLSQL unit tests in our test environments.
The conditional code is included (or not) _only at compile time_. You can't change the code afterwards by changing the compile flag and compiling the existing code again.

If we could set the compile flag and "force" flyway to repeat the repeatables that would help a lot!

**Comment by MikielAgutu** [comment]
We're not convinced adding this new option is the best approach.

As we understand it, this feature is desired to test all the scripts work when run from scratch. We think this sort of 'start from scratch' test scenario is the responsibility of a CI environment. In CI you can provision a new DB, migrate all Flyway scripts, and see if it works.

For instance, @tohagan says:

>Safer to test rerunning all R__ script to avoid this as this reflects the true database state after a clean & full migrate...you want an option to perform this for your CI testing environment

In this scenario, for instance, we think you should just introduce a CI step that provisions an empty DB and migrates. No new functionality is needed from Flyway in order to do this.

So we think more robust CI is the solution here. However we're open to more discussion if this isn't a desirable option for people.

**Comment by Lyeeedar** [comment]
We wrote a blog post on how to do this with the new timestamp placeholder released in Flyway 6.3.0. https://flywaydb.org/blog/flyway-timestampsAndRepeatables

I will close this issue. If this solution does not work for you please open a new issue with the reasons why.

**Comment by berv63** [comment]
> We wrote a blog post on how to do this with the new timestamp placeholder released in Flyway 6.3.0. https://flywaydb.org/blog/flyway-timestampsAndRepeatables
> 
> I will close this issue. If this solution does not work for you please open a new issue with the reasons why.

Updated link for future reference
https://www.red-gate.com/blog/timestamps-and-repeatable-migrations
