### ISSUE TITLE
Warning messages from an earlier migration re-displayed in later scripts.

### ISSUE THREAD

**Issue by tohagan** [flyway/flyway#1455]
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command line
###### What database are you using (type & version)?

MySQL 5.6
###### What operating system are you using?

Window 7 
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

flyway migrate
###### What did you expect to see?

Error message related to correct scripts.
###### What did you see instead?

I'm repeatedly observing that when a warning occurs for a migration script A, the same warning text is then displayed when a warning occurs for later migrations scripts B or C. In my case, it's impossible for the warning to have occurred for scripts B and C so it appears that there is a bug in the error/warning reporting code that is re-displaying old messages from earlier scripts.  So basically I can't trust the error/warning messages.  

Example from a recent migration ... 

The message `WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)` that first occurred in `20161025.002 - DROP mytable v1` is then repeated multiple times in `repeatable migration 000 base views` migration ... but this error cannot occur from this later script since the table in the message is not referenced by this script.

```
> flyway migrate
Flyway 4.0.3 by Boxfuse

Database: jdbc:mysql://localhost:3306/mydb1 (MySQL 5.6)
Successfully validated 15 migrations (execution time 00:00.024s)
Current version of schema `mydb1`: 1
Migrating schema `mydb1` to version 20161020.001 - kirra tbl ezipayment
Migrating schema `mydb1` to version 20161020.002 - kirra tbl batch job
Migrating schema `mydb1` to version 20161020.003 - kirra tbl svc log
Migrating schema `mydb1` to version 20161020.005 - kirra col drop customer data.submission target date
Migrating schema `mydb1` to version 20161020.006 - kirra drop trg submission target date
Migrating schema `mydb1` to version 20161025.001 - DROP vew kpi stats
Migrating schema `mydb1` to version 20161025.002 - DROP case status v1
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
Migrating schema `mydb1` with repeatable migration 000 base views
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
WARNING: DB: Unknown table 'mydb1.mytable1' (SQL State: 42S02 - Error Code: 1051)
Migrating schema `mydb1` with repeatable migration 100 base sps fns
Migrating schema `mydb1` with repeatable migration 101 base sps remove db refs
Migrating schema `mydb1` with repeatable migration 102 base trg copycomplaint
Migrating schema `mydb1` with repeatable migration 102 base trg copynote
Migrating schema `mydb1` with repeatable migration 102 base trg customerdata
Migrating schema `mydb1` with repeatable migration 103 kirra fn workdaysdiff
Successfully applied 14 migrations to schema `mydb1` (execution time 00:09.310s).
```

**Comment by axelfontaine** [comment]
The warnings are returned verbatim from the database and the JDBC driver. I suggest opening a defect with the MySQL JDBC driver to see if they may be returning stale warnings from previous invokings in their resultsets.

**Comment by idontusenumbers** [comment]
I was getting the same warnings because one of my migrations included "drop table if exists" for tables that didn't exist.
