### ISSUE TITLE
When migrations have been applied by enabling out-of-order Flyway displays the wrong current version

### ISSUE THREAD

**Issue by rousej** [flyway/flyway#1457]
###### What version of Flyway are you using?

4.03
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API
###### What database are you using (type & version)?

Oracle 11g, MS Sql Server 2012, 2014
###### What operating system are you using?

Windows 7
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I applied migrations in-order beginning with a baseline version of 12.3.2.0.0.0.990 and ending with version 17.1.0.0.0.0.990. I then applied migration version 12.4.0.0.0.0.130 by enabling out-of-order. All migrations were successfully applied. The next time I ran flyway migrate I received the following output: 

Flyway 4.0.3 by Boxfuse
Database: <redacted> JDBC Driver; (Microsoft SQL Server 12.0)
Successfully validated 104 migrations (execution time 00:00.211s)
SQLServer does not support setting the schema for the current session. Default schema NOT changed to dbo
Current version of schema [dbo]: 12.4.0.0.0.0.130
outOfOrder mode is active. Migration of schema [dbo] may not be reproducible.
Schema [dbo] is up to date. No migration necessary.
###### What did you expect to see?

I expected to see the highest successfully applied migration version displayed as the Current version.
###### What did you see instead?

The Current version was displayed as 12.4.0.0.0.0.130, which was the last migration applied chronologically, but not the highest migration version applied.

**Comment by axelfontaine** [comment]
Good catch! Thanks for reporting!
