### ISSUE TITLE
filesystem paths in flyway.locations not working if Gradle task is invoked through Buildship

### ISSUE THREAD

**Issue by gkresic** [flyway/flyway#1462]
I'm not sure if this is Flyway's or Buildship's issue (or Gradle'e or just mine misconfiguration), but it seems that Flyway's Gradle plugin has some issues resolving filesystem paths when Gradle task is not invoked from command line, but from [Buildship](https://github.com/eclipse/buildship).

I'm trying to place my migration scripts in folder `src/main/db` and I'm configuring this via `gradle.properties`:

`flyway.locations=filesystem:src/main/db`

Now, if I run flyway task from command line, everything is OK:

```
gkresic@mata:~/Sources/mentor (master)$ ./gradlew flywayInfo
:flywayInfo
+---------+----------------+---------------------+---------+
| Version | Description    | Installed on        | State   |
+---------+----------------+---------------------+---------+
| 1       | Initial schema |                     | Pending |
+---------+----------------+---------------------+---------+


BUILD SUCCESSFUL

Total time: 0.898 secs
```

However, if I run the same task through Eclipse/Buildship, Flyway says it can not find paths specified (notice that working directory, as reported by Buildship at the start of Gradle execution, should be fine):

```
Working Directory: /home/gkresic/Sources/mentor
Gradle User Home: /home/gkresic/.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 3.1
Java Home: /usr/local/j2se-8
JVM Arguments: None
Program Arguments: None
Gradle Tasks: flywayInfo

:flywayInfo
Unable to resolve location filesystem:src/main/db
Unable to resolve location filesystem:src/main/db
Unable to resolve location filesystem:src/main/db
+---------+-------------+---------------------+---------+
| Version | Description | Installed on        | State   |
+---------+-------------+---------------------+---------+
| No migrations found                                   |
+---------+-------------+---------------------+---------+


BUILD SUCCESSFUL

Total time: 0.092 secs
```

I'm using mostly latest versions of every component:

Flyway 4.0.3
Buildship 1.0.21.v20161010-1640
Eclipse 4.6.1.v20160907-1200
Ubuntu 16.04.1
PostgreSQL 9.5 (not that PostgreSQL should have anything to do with this)

**Comment by axelfontaine** [comment]
This is most likely due to the current directory being set to something else. Check with Buildship on how to influence this. Not a Flyway issue.
