### ISSUE TITLE
Flyway-validate behavior on application startup

### ISSUE THREAD

**Issue by phaas** [flyway/flyway#1464]
###### What version of Flyway are you using?
3.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?
Postgres, H2, DB2

###### What operating system are you using?
Windows, Solaris, Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Added a startup step to perform flyway.validate() to my application

###### What did you expect to see?

I expected the validation to (only) fail when required migrations on the classpath had not been applied.

###### What did you see instead?

The validation also failed when future migrations were found in the schema_version table.

Discussion:
All of my migrations are backward compatible at least 1 release, i.e. they can be applied while the 'current' version of the application is still running. The next version of the application is going to depend on new tables, columns, etc.

I want to ensure that the application doesn't start up until after the required migrations have been applied.
The application itself does not have the required access to create/alter the database, so the migrations are applied by a separate 'administrative' script. On startup, the application should verify that all known migrations have been applied.

I also need to ensure that the current/previous version of the application continues to function, to cover rollbacks and app restarts.

I've attempted to insert a 'validate()' call on startup, which passes for the 'new' version but breaks the 'previous' version, since the metadata table now contains pending entries.

Since the 'validate()' method forced the 'pending' parameter to 'false', this causes validation to fail.

```
+----------------+----------------------------+---------------------+---------+
| Version        | Description                | Installed on        | State   |
+----------------+----------------------------+---------------------+---------+
| 1              | Last                       | 2016-11-09 07:35:57 | Success |
| 2              | Next                       | 2016-11-09 07:35:57 | Future  |
+----------------+----------------------------+---------------------+---------+
Found differences between applied migrations and available migrations: Detected applied migration missing on the classpath: 2
```

**Comment by axelfontaine** [comment]
This is fully supported in the latest release by setting `ignoreFutureMigrations` to `true`.
