### ISSUE TITLE
Release Notes Issue for version 4.0.0

### ISSUE THREAD

**Issue by gsaslis** [flyway/flyway#1467]
[Please feel free to advise if I am opening this issue in the wrong place -- I found no other better place to report this, e.g. no `edit` button on the release notes page. ]

When upgrading to 4.x, we were bitten (hard) by a breaking change that was not documented correctly (imho), in the release notes.

In particular, #988, causes a change in the behaviour of `migrate`, now resulting in an error when a file is missing. Previously, this was not a problem and our runs were running with no issues, even though the file was missing.  

###### What version of Flyway are you using?
4.0.3

###### What did you expect to see?
Issue #988 under the `Incompatible Changes` section, since, as described above, the behaviour of the `migrate` run has changed. 

###### What did you see instead?
Issue #988 under the `Bug Fixes` section, therefore leading me to believe this would not have any breaking changes.

**Comment by Catchwa** [comment]
I don't think this is the correct project to be raising an issue against, as the documentation is in the flywaydb.org project. I'd suggest you submit a pull request against https://github.com/flyway/flywaydb.org/blob/gh-pages/documentation/releaseNotes.html

**Comment by axelfontaine** [comment]
@gsaslis You are correct. This should have been marked as an incompatible change. Fixed. Note that @Catchwa is absolutely correct regarding the repo.

**Comment by gsaslis** [comment]
@axelfontaine / @catchwa thanks both & 
sorry for the misplaced issue !
