### ISSUE TITLE
Using flyway.serverId produces WARNING log

### ISSUE THREAD

**Issue by eidottermihi** [flyway/flyway#1468]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven Plugin

###### What database are you using (type & version)?
Oracle 12.1

###### What operating system are you using?
Ubuntu 14.0.4

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I store the credentials of my database server in settings.xml via <servers>.
I invoke flyway like this:
`mvn flyway:info -Dflyway.serverId=my-server -Dflyway.url=jdbc:oracle:thin:@my.server.com:1521:mysid `

###### What did you expect to see?

No [WARNING] logs.

###### What did you see instead?

the maven plugin logs the following line:

`[WARNING] Unknown configuration property: flyway.serverId`

**Comment by axelfontaine** [comment]
Good catch! Thanks!
