### ISSUE TITLE
gh-ost support for MySQL

### ISSUE THREAD

**Issue by stepin** [flyway/flyway#1471]
gh-ost is a triggerless online schema migration solution for MySQL. More info http://githubengineering.com/gh-ost-github-s-online-migration-tool-for-mysql/

gh-ost like tools is critical for no downtime deployments, but it lacks a lot of infrastructure that flyway has.

It will be really usefull to be able to use gh-ost for alter table statements / special migrations.
Is there any plans for such kind of functionality?

**Comment by axelfontaine** [comment]
Thanks for your suggestion. Please explain in detail how you feel such an integration should be implemented.

**Comment by axelfontaine** [comment]
Any news?

**Comment by stepin** [comment]
Hi,

I think that developer should be able to run automatic migrations on the app start.
On other hand in production in some cases (like use of gh-ost or http://vitess.io/user-guide/schema-management.html) in the background some console utility should be used to start query, waiting for end of query, start next query, ...). So, this can be --engine switch to select method to run queries.

**Comment by axelfontaine** [comment]
Well if all you want is a CLI then the Flyway Commandline Tool is already a great solution for this.
