### ISSUE TITLE
Add -n flag to suppress credentials prompt

### ISSUE THREAD

**Issue by zombor** [flyway/flyway#1477]
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

postgres, mysql

###### What operating system are you using?

linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Using a valid jdbc connection uri that includes a username and password to connect to the database, such as:

```
jdbc:mysql://localhost/db?user=xxx&password=xxx
jdbc:postgresql://localhost/db?user=xxx&password=xxx
```

Results in prompt for username/password

###### What did you expect to see?

No prompt for username/password, with the jdbc connection params used for authentication

###### What did you see instead?

Username/password prompts on STDIN

This worked on v3.0 and I'm trying to upgrade to v4 and ran into this issue. It looks like the following commits are relevant:

https://github.com/flyway/flyway/commit/a2d1941adebc6eb2f372c4dff44343085776933a
https://github.com/flyway/flyway/pull/1051/commits/0e1905e9b9d548196662276c76460b6277fe25ef

**Comment by amit-bridg** [comment]
+1
