### ISSUE TITLE
An R prefixed migration is treated as versioned if number is included in the filename immediately after the R

### ISSUE THREAD

**Issue by josephramsay** [flyway/flyway#1478]
###### What version of Flyway are you using?
gradle.plugin.com.boxfuse.client:flyway-release:4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle

###### What database are you using (type & version)?
"PostgreSQL 9.3.14 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit"

###### What operating system are you using?
Linux <host> 4.2.0-42-generic #49~14.04.1-Ubuntu SMP

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Named repeatable migration files RNNN__something.sql

###### What did you expect to see?
Expected to be able to edit repeatable migrations and have them run on successive calls to flywayMigrate

###### What did you see instead?
checksum errors for repeatable migrations as if they were versioned

Problem was resolved by renaming files to R__NNN_something.sql. Just needs to be documented that this is the case

**Comment by khatkar** [comment]
I think documentation makes it pretty clear that repeatable migrations do not have a version. So the file must be named like 'R__description.sql'. If you do decide to include a number like R123__something.sql then you have to use the `setRepeatableSqlMigrationPrefix` method to set a custom prefix to R123.
