### ISSUE TITLE
use druid Datasource failed startup for: sql injection violation, comment not allow 

### ISSUE THREAD

**Issue by zjengjie** [flyway/flyway#1480]
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

mysql

###### What operating system are you using?

ubuntu

###### What did you do?

I use Druid database connection pool, the fault seems to it's default setting don't allow comment in sql execution.

###### What did you see instead?
```
Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Script failed
-------------
SQL State  : null
Error Code : 0
Message    : sql injection violation, comment not allow : CREATE TABLE `db`.`table_version` (
    `installed_rank` INT NOT NULL,
    `version` VARCHAR(50),
    `description` VARCHAR(200) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `script` VARCHAR(1000) NOT NULL,
    `checksum` INT,
    `installed_by` VARCHAR(100) NOT NULL,
    `installed_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `execution_time` INT NOT NULL,
    `success` BOOL NOT NULL,
    -- Add the primary key as part of the CREATE TABLE statement in case `innodb_force_primary_key` is enabled
    CONSTRAINT `table_version_pk`PRIMARY KEY (`installed_rank`)
) ENGINE=InnoDB
```

**Comment by axelfontaine** [comment]
Please raise a defect with them as this is perfectly valid SQL with no risk of SQL injection.
