### ISSUE TITLE
Support for ordering repeatable migrations using imports

### ISSUE THREAD

**Issue by jedvardsson** [flyway/flyway#1481]
From what I can see the only way to order repeatable migrations is using filename (last checked 4.0.3). This gets ugly in a project with a lot of repeatable migrations (e.g. stored procedures). Has there been a consideration around adding some kind of import or depends feature?

```sql
--#import util.sql
--#import time.sql
create or replace function .... begin
    -- use stuff in util.sql and time.sql
end

```

Migrations are applied in the same order as today, except when there are imports, which are applied before if necessary (if changed and if not applied). 

Also, it would be nice if one could drop the R__ prefix on repeatable migrations to make filenames cleaner and treat files with V-prefix as versioned and everything else as repeatable.

I would be happy to help in anyway if this is something that you see fits the goals of Flyway.

**Comment by albertocsm** [comment]
related to #1403

**Comment by axelfontaine** [comment]
Imports is not something I feel would carry it's own conceptual weight. You can work around this by having a prefix (numbers or letters) that guarantees you the order you want.

As for `R` and `__` they are both configurable.
