### ISSUE TITLE
Flyway doesn't recognize Sybase ASE 12.5

### ISSUE THREAD

**Issue by ogerardin** [flyway/flyway#1483]
It seems version 12.5 of Sybase ASE identifies itself as "sql server 12.50", while DbSupportFactory.createDbSupport expects something that starts with "ASE" or "Adaptive.

###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Sybase ASE 12.5

###### What operating system are you using?
Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
flyway -X -url=jdbc:jtds:sybase://<host>:4100/<database> baseline

###### What did you expect to see?
Not an error

###### What did you see instead?
ERROR: Unsupported Database: sql server 12.50

**Comment by ogerardin** [comment]
A simple solution to this would be to provide an option to bypass DbSupport factory, something like
`flyway.dbSupport=org.flywaydb.core.internal.dbsupport.sybase.ase.SybaseASEDbSupport`

**Comment by ogerardin** [comment]
I created a pull request for this issue, the ball is in your court now...

**Comment by axelfontaine** [comment]
Thanks for sharing the exact string. Support has now been added.
