### ISSUE TITLE
Error baselining existing DB

### ISSUE THREAD

**Issue by burm87** [flyway/flyway#1488]
###### What version of Flyway are you using?
`<dependency>`
`      <groupId>org.flywaydb</groupId>`
`                    <artifactId>flyway-core</artifactId>`
 `                   <version>3.0</version>`
`                </dependency>`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

Postgres 9.1

###### What operating system are you using?

Ubuntu 16.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I dumped the production DB schema and placed the sql file into java/main/resources/db/migration/V001__baseline.sql, i run the mvn plugin `<groupId>org.flywaydb</groupId>
                            <artifactId>flyway-maven-plugin</artifactId>
                            <version>4.0.3</version>` to create baseline. The schema version table is created. When I startup my spring application it says version_rank column is not present, and it's right. That column is not created by the plugin by flyway seems to expect it "org.postgresql.util.PSQLException: ERROR: column "version_rank" does not exist". Manually creating the column does not help because flyway tries to apply the baseline migration.

###### What did you expect to see?
I was expecting to start my application without applying the baseline migration.

###### What did you see instead?
`"org.postgresql.util.PSQLException: ERROR: column "version_rank" does not exist".` schema version table seems to be not properly created.

**Comment by burm87** [comment]
Resolved, I don't know why but maven was downloading a wrong version of flyway.

**Comment by naxas** [comment]
it only worked after replacing 
<groupId>org.flywaydb</groupId> <artifactId>flyway-maven-plugin</artifactId> <version>4.0.3</version>, I mean adding <version>4.0.3</version>. thanks a lot. I tried everything else on internet.
