### ISSUE TITLE
Flyway ran version 1 script wiping production database

### ISSUE THREAD

**Issue by Jerbell** [flyway/flyway#1492]
###### What version of Flyway are you using?
3.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
Mysql 5.5.5 / MariaDB 10.0.22

###### What operating system are you using?
Centos

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Started the application, one of 4 instances.  Once instance decided to run version 1 script which wiped the DB.

###### What did you expect to see?
Normal migration.

###### What did you see instead?
A database where all tables were cleared except for schema_version

Obviously this will be near impossible to recreate, but thought you should see the verbatim log file snippet (apart from the company name change).

[DatabaseLogSnip.txt](https://github.com/flyway/flyway/files/649208/DatabaseLogSnip.txt)

**Comment by theothercoreytaylor** [comment]
Did the other instance startup and run at the same time?

**Comment by Jerbell** [comment]
Yes - they started & all tried to run Flyway migration at the same time.  I can get a log file equivalent with the instances tomorrow if you're interested.  I've never experienced this before.

**Comment by othercoreytaylor** [comment]
I would be interested as I will be deploying to a similar production environment.

**Comment by Jerbell** [comment]
OK - will get back to you.

**Comment by Jerbell** [comment]
I've noticed that someone put in a customised MySQLSchema class to work with older versions of MySQL.  This issue might be a dud, so will close it off.
