### ISSUE TITLE
Add support for schema modules

### ISSUE THREAD

**Issue by asaikali** [flyway/flyway#1493]
This is a feature request, scenario below explains what and why I am looking for this feature.

I have a module called outbox.jar which contains some code used to send out emails, this code first writes the emails to a database table called outbox and then a background thread sends picks up the email and actually sends it.  The outbox.jar module can be used in a lot of applications, so I would like to be able to just drop outbok.jar into an application's classpath (especially via a SpringBoot starter) that are using flyway and then have flyway automatically pickup the migrations in db.migration directory inside the outbox.jar. 

The lifecycle of the migrations in outbox.jar is 100% independent of the migrations in the application that outbox.jar is being used from. Creating a separate schema_version table for outbox while possible is undesirable because it will slow down application startup and there are lots of other examples of third party modules that depend on having their's tables present. It would not make sense to have three separate schema_version tables under different names of course for three separate reusable modules. 

Is it possible to add the notion of a module to flyway so that flyway schema_version has an extra column called module which would identify the source of the migration scripts. This would make it possible to have V001_create_tables.sql in the outbox.jar file and a V001_create_tables.sql in the application without having these two migrations conflict with each other and having the result of the migration recorded in the scheam_version table of the application. 

With modules getting added to Java 9 and the move towards microservices based architecture I am finding myself with a lot of common libraries that need their own database tables and the module feature would really make things much easier.

Is a feature like this desirable for the Flyaydb team or is there some reason why such a feature should never be included.

Would a pull request implementing such a feature be accepted assuming it met the coding/testing/style standards for the project?

**Comment by axelfontaine** [comment]
Thanks for the suggestion. Adding another layer into the mix just doesn't seem worth it. I am also not sold on the statement that adding a second schema_version table would somehow slow down the application startup.

My recommendation: one schema per module, with its own Flyway schema_version table.
