### ISSUE TITLE
Own Annotation with Flyway does not work on method level

### ISSUE THREAD

**Issue by jkoorts** [flyway/flyway#1494]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle

###### What database are you using (type & version)?
Postgresql

###### What operating system are you using?
Linux, Win

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@FlywayTest(locationsForMigrate = "classpath:db/migration/activated")
public @interface BaseActivatedSql {
}

public class CustomerChannelTestCase extends BaseIntegrationTest {
@BaseActivatedSql
 public void canChangeCustomer() {
   // BaseActivatedSql does not get run. If I add this annotation at class level it works - runs.
}
}

###### What did you expect to see?
My own annotations with flyway integrated should not only work on class level but also on method level.

###### What did you see instead?
Flyway did not run. Only runs when I add the annotation like this:

@BaseActivatedSql
public class CustomerChannelTestCase extends BaseIntegrationTest {

 public void canChangeCustomer() {
   // Flyway ran.
}
}

**Comment by axelfontaine** [comment]
Those annotations are not part of the core Flyway project. There is not much we can do here.
