### ISSUE TITLE
Ability to detect if no migration files were found

### ISSUE THREAD

**Issue by cowwoc** [flyway/flyway#1496]
Currently, if Flyway is configured to look for migrations in the wrong path the following error is logged:

> Dec 25, 2016 9:27:01 PM org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner getLocationUrlsForPath
WARNING: Unable to resolve location classpath:a/b/c

I'd like to be able to detect this situation from the API in order to fail the build or run that depends on such migration files being found.

Ideally I should be able to get a list of migration locations that were referenced, but not found. Another approach could be to list the migration files found (whether they have already been found or not) so that I can throw an exception if the number is zero.

**Comment by stevenschlansker** [comment]
We just ran into this too.  A test case was failing, and the Flyway error gets logged and then lost in a sea of other messages.  If it could fail fast with a clear error message that would reduce the amount of time to diagnose and fix issues with flyway migration locations.

**Comment by khatkar** [comment]
Flyway reads migrations from multiple locations and then consolidates them together before migration the database. In case migration is not found at a given location, flyway assumes that no migration needs to be applied. Hence it logs a warning, not an error, and proceeds. If you want flyway to acknowledge that all migration locations are valid, you can do so specific to your application you're working on. Check the location exists in your program and if so, call flyway migrate.

For a Spring project, the setting `flyway.check-location` seems to be doing this.

**Comment by cowwoc** [comment]
@khatkar This doesn't really solve my problem. I can process `Flyway.getLocations()` but there is no guarantee that my resolution of classpath resources matches that of Flyway. Meaning, my logic might locate the files, but Flyway will not because it is using a different search algorithm than I am. The fact that Flyway logs this event means that it knows about it occurring. All we're asking you to do is expose an API method that indicates whether this occurred. The only one that knows if Flyway found a resource is Flyway itself.

**Comment by khatkar** [comment]
@cowwoc I created a PR for your requested feature. Please check it out.

**Comment by axelfontaine** [comment]
You can achieve this by inspecting the value of `getState()` for each element returned by `flyway.info().all()`

**Comment by joehorsnell** [comment]
Linking to #2205, which I think is related.
