### ISSUE TITLE
Cannot load migration SQL scripts from the root of the classpath in a jarfile

### ISSUE THREAD

**Issue by albertmatyi** [flyway/flyway#1498]
###### What version of Flyway are you using?

4.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

JAVA API

###### What database are you using (type & version)?

mariadb  10.1.7 
mysql client 5.5

###### What operating system are you using?

linux x64
4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

###### What did you do?

Created a FlywayMigrator class file with `public static main` method ( code in `groovy`)

```
package com.wewash.backend

import org.flywaydb.core.Flyway

class FlywayMigrator {
    static void main(String[] args) {
        Flyway flyway = new Flyway()
        flyway.setLocations(".", "/", "classpath:.", "classpath:/", "classpath:*.sql")
        print(flyway.getLocations())
        flyway.setDataSource(
            "jdbc:mysql://localhost:3310/wewash",
            "root",
            "")
        flyway.migrate()
    }

}
```

and compiled it into a jar with the migration scripts, which can be found at the root of the jar

###### What did you expect to see?

I exepected that `java -jar app.jar` runs the migrations

###### What did you see instead?

Flyway cannot scan the root of the classpath. 

The whole thing only works if i put the scripts in a subfolder.

###### What I've tried

I've tried debugging the code, and it seems that `ClassPathScanner:201/2`  is the culprit 

```
} else { 
            Enumeration<URL> urls = classLoader.getResources(location.getPath()); // 201
            if (!urls.hasMoreElements()) { //202
                LOG.warn("Unable to resolve location " + location); // 203
            }
```
because it evaluates to a failing location interpretation, it treats it as if the root of the classpath could not be resolved.

**Comment by kopax** [comment]
I have this issue. 
I have a root project that configure sub project.
I am trying to run migration command from gradle and it can't find any classpath.
How did you solved it for flyway 4.2.0 and when is flyway 5.0 scheduled?

Also is it possible to run the migration using the java api and how can I do it?

**Comment by axelfontaine** [comment]
The correct syntax is `classpath:`. We'll make changes to fail fast on the other variants.

**Comment by axelfontaine** [comment]
This has now been fixed.
