### ISSUE TITLE
Option to allow for duplicate version numbers for unordered versioned migrations

### ISSUE THREAD

**Issue by benjaminsanborn** [flyway/flyway#1501]
In the spirit of providing an unopinionated versioning solution, flyway could provide an option to allow for duplicate version numbers. When presented with duplicates, it will apply them sequentially (in an order the developer cannot explicitly rely on; let's say, alphabetically).

This would allow the version numbers to also be used as incremental "baselines", so V5__foo.sql and V5__bar.sql, as long as they work on separate schema can be merged without issue. It would be the developers responsibility to ensure they don't conflict.

Since this does present some dangers, it wouldn't be default behavior, but it would allow for more flexible versioning conventions.

**Comment by othercoreytaylor** [comment]
And how would this be applied to the schema table?  Do you really want multiple entries of the same version in a non-deterministic setting?

You are basically asking for a versionless system, right? If a new V5 was added you would want it applied arbitrarily.

**Comment by benjaminsanborn** [comment]
The pain point were trying to avoid is that we have to rename our migrations frequently when migrations are coming from many developers at once. But I agree with you, this way of getting around handling concurrent work gets us into non-deterministic weeds.

A "migration schedule" file (like http://sqitch.org/ implements) that would serialize the migrations would be ideal, as we could configure `git` to handle how we want that document merged.

Would that be a more sensible solution? The migrations are still fully serialized, but we'd have a little more flexibility in how we automate the ordering management.
