### ISSUE TITLE
MigrationChecksumProvider interface returns value of Integer should be BigInteger or byte[]

### ISSUE THREAD

**Issue by binary10** [flyway/flyway#1503]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
SQL Server

###### What operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

###### What did you expect to see?
Standard checksums like MD5 and SHA256 cannot be converted to type Integer. I recommend setting the interface return type of `getChecksum` to `BigInteger`

###### What did you see instead?
Integer cannot store standard checksum values.

**Comment by axelfontaine** [comment]
There is no need for such a longer hash. All this is for is to detect accidental modification and CRC32 handles that just fine.

**Comment by binary10** [comment]
Thanks Axel, I argue this should be implemented for the case when one is detecting *intentional* modification to trigger repeatable migrations.
