### ISSUE TITLE
Don't mix the DBNAME with CREATOR(schema) in DB2ZOS

### ISSUE THREAD

**Issue by adifri** [flyway/flyway#1504]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line, Java API

###### What database are you using (type & version)?
DB2 for z/OS v.11

###### What operating system are you using?
Windows,Linux,AIX,z/OS

###### What did you do?
creating the flyway table (schema_version) on the very first migrate with command-line.

Hi

on creating the tablespace for the flyway table version in createMetaDataTable.sql you are using the "schema" for the database (DBNAME) 

```
CREATE TABLESPACE SFLYWAY
      IN "${schema}"
```
	  
and then on create table you are using the same schema as database(DBNAME).

```
CREATE TABLE "${schema}"."${table}" (
...
)
IN "${schema}".SFLYWAY;
```

This is not going to work because in DB2ZOS the schema(CREATOR) is not the same as database(DBNAME).

They may but don't have to have the same name.

You should define a new flyway parameter for the DBNAME in DB2ZOS.

```
CREATE TABLESPACE SFLYWAY
      IN "${dbname}"
```
	  
and then on create table 

```
CREATE TABLE "${schema}"."${table}" (
...
)
IN "${dbname}".SFLYWAY;
```
 

From DB2 z/OS SQL Ref:
`CREATE TABLESPACE table-space-name IN database-name ...`
where database-name: DBNAME Name of the database that contains the table space.

```
CREATE TABLE table-name
...
IN database-name.table-space-name
```

table-name: The name, including the implicit or explicit qualifier (CREATOR)

Tablespaces
===========
CREATOR Authorization ID of the owner of the table space.
DBNAME Name of the database that contains the table space.

Tables
======
CREATOR The schema of the table, view, or alias.
DBNAME For a table, or a view of tables, the name of the database G that contains the table space           that is named in TSNAME.
       For a created temporary table, an alias, or a view of a view, the value is DSNDB06..

**Comment by axelfontaine** [comment]
@cteig Thoughts?

**Comment by moverkamp** [comment]
I have the same problem als Adrian (adifri): I am trying to use Flyway with a DB2 z/OS installation where database names and schema/creator names are not the same, too.
It would be very helpful if this issue could be fixed.

**Comment by axelfontaine** [comment]
> It would be very helpful if this issue could be fixed.

Then it's time to roll up your sleeves and submit a pull request :-)

**Comment by adifri** [comment]
I didn't have time until now, i'll work on it as soon as I can

**Comment by moverkamp** [comment]
I've looked at adifri's code and why his pull request was not accepted. If his changes in DB2zosSchema.java could be accepted, without any of the other changes, that would fix the most important bug:  the correct detection of the existance of the schema (if contains tables), and if there are no tables Flyway would go on and try to create the tables anyway.
There would still be a problem with the metadata table, but I think I can work around that by creating it myself beforehand.

**Comment by axelfontaine** [comment]
Closing as DB2 z/OS support has been discontinued in Flyway's main distribution.
