### ISSUE TITLE
flyway give up by reporting `Cannot insert the value NULL into column 'installed_on', table 'dbo.schema_version'; column does not allow nulls. INSERT fails.`

### ISSUE THREAD

**Issue by xiaoyifang** [flyway/flyway#1507]
###### What version of Flyway are you using?
3.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
gradle plugin:flyway-gradle-plugin:3.0

###### What database are you using (type & version)?
sqlserver

###### What operating system are you using?
win7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
executing the flywayMigrate command,

###### What did you expect to see?
migration can be success,as it usually does.

###### What did you see instead?
flyway give up by reporting `Cannot insert the value NULL into column 'installed_on', table 'dbo.schema_version'; column does not allow nulls. INSERT fails.`

**Comment by khatkar** [comment]
Is it possible for you to upgrade Flyway to 4.x?

**Comment by xiaoyifang** [comment]
yeah,may be my fault.I changed to table definition according to 3.0  create table script ,seemed work.
