### ISSUE TITLE
Support for cleaning SQL Server Rule and Default objects

### ISSUE THREAD

**Issue by Catchwa** [flyway/flyway#1508]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven plugin

###### What database are you using (type & version)?
SQL Server Developer Edition 2014 in 2008 compatibility mode

###### What operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Ran a flyway:clean after doing a flyway:migrate to create the database structure

###### What did you expect to see?
The database being truly 'clean'

###### What did you see instead?
The following object types still remain:

1. Defaults
2. Rules

I would create a PR, but I can't work out how to get a list of all Defaults and/or Rules from a database. I've posted that question here: http://stackoverflow.com/q/41733344/79450

**Comment by axelfontaine** [comment]
I saw that you got an answer on StackOverflow. Would you like to submit a PR (including a test)?

**Comment by Catchwa** [comment]
Yes, I'd like to but I need to discuss with my employer :-)

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
This is now supported.
