### ISSUE TITLE
Feature Request: Java migration checksum generator

### ISSUE THREAD

**Issue by MichaelBitard** [flyway/flyway#1509]
I released a maven plugin which can allow flyway users to have checksums validation on their java migration files almost as easily as on the sql migrations.

If you are interested I'll gladly make a pull request in order to integrate this into the flyway maven plugin.

It's a maven plugin which generate an Enum containing all the Java migration files name and their corresponding crc32 (on the .java, not the .class)

This way you can use it in your java migration files by implementing `MigrationChecksumProvider`

and by overriding 

```java
    @Override
    public Integer getChecksum() {
        return JavaMigrationChecksums.valueOf(getClass().getSimpleName()).getChecksum();
    }
```

The project is currently here: https://github.com/agileek/java-checksum-flyway-maven-plugin

**Comment by MikielAgutu** [comment]
We don't think there's enough interest in this feature.

**Comment by MichaelBitard** [comment]
No problem ;)

**Comment by mdindoffer** [comment]
This is very nice. Without the script immutability guarantees, Java-based migrations are pretty much a nogo for DB migrations. This should be mainlined.
