### ISSUE TITLE
Make Scanner and/or MigrationResolver extensible

### ISSUE THREAD

**Issue by rodlogic** [flyway/flyway#1511]
I am using Flyway v4.0.3 and would like to be able to resolve migration files using the ServletContext instead of the Classpath and/or the Filesystem. However, it is not possible to, or at least not obvious how to, customize the Scanner since it is directly instantiated within Flyway method calls.

**Comment by axelfontaine** [comment]
Use `Flyway.setResolvers(...)`to pass in your own resolver.
