### ISSUE TITLE
Parameter ignoreMissingMigrations not recognized

### ISSUE THREAD

**Issue by aleblanc39** [flyway/flyway#1521]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command line

###### What database are you using (type & version)?
(Oracle 11.2)

###### What operating system are you using?
Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Ran command 
```
$ flyway validate -ignoreMissingMigrations=false
```

###### What did you expect to see?

Expected not to see the 
    `WARNING: Unknown configuration property: flyway.ignoreMissingMigrations`
line

###### What did you see instead?
```
Flyway 4.0.3 by Boxfuse

WARNING: Unknown configuration property: flyway.ignoreMissingMigrations
Database: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.xxx.xxx.xxx)(PORT = 1521))(CONNECT_DATA =(SERVICE_NAME = XXX))) (Oracle 11.2)
ERROR: Validate failed: Detected resolved migration not applied to database: 16.12.1.4.02
```

Not sure where to put this note: I don't have this issue with `-ignoreMissingMigrations`.

**Comment by axelfontaine** [comment]
You need Flyway 4.1.0 for this. Upgrade and everything should work as expected.

**Comment by aleblanc39** [comment]
That was it. I didn't notice the new version. Thanks.
