### ISSUE TITLE
Error upgrading to schemaversion 4.1.0 from 3.2.1

### ISSUE THREAD

**Issue by hcalsos** [flyway/flyway#1526]
###### What version of Flyway are you using?

3.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Maven plugin

###### What database are you using (type & version)?

MySQL 5.7

###### What operating system are you using?

OSX

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Upgraded my flyway verison to 4.1..0, and ran flyway:migrate to update the schema_versions table

###### What did you expect to see?

A successful build.

###### What did you see instead?

Maven output:
[INFO] Upgrading metadata table `schema_version` to the Flyway 4.0 format ...
[DEBUG] Found statement at line 17: DROP INDEX `schema_version_vr_idx` ON `schema_version`
[DEBUG] Found statement at line 18: DROP INDEX `schema_version_ir_idx` ON `schema_version`
[DEBUG] Found statement at line 19: ALTER TABLE `schema_version` DROP COLUMN `version_rank`
[DEBUG] Found statement at line 21: ALTER TABLE `schema_version` DROP PRIMARY KEY, ADD CONSTRAINT `schema_version_pk` PRIMARY KEY (`installed_rank`)
[DEBUG] Found statement at line 22: ALTER TABLE `schema_version` MODIFY `version` VARCHAR(50)
[DEBUG] Found statement at line 23: UPDATE `schema_version` SET `type`='BASELINE' WHERE `type`='INIT'
[DEBUG] Executing SQL: DROP INDEX `schema_version_vr_idx` ON `schema_version`
[DEBUG] Update Count: 0
[DEBUG] Executing SQL: DROP INDEX `schema_version_ir_idx` ON `schema_version`
[DEBUG] Update Count: 0
[DEBUG] Executing SQL: ALTER TABLE `schema_version` DROP COLUMN `version_rank`
[DEBUG] Update Count: 0
[DEBUG] Executing SQL: ALTER TABLE `schema_version` DROP PRIMARY KEY, ADD CONSTRAINT `schema_version_pk` PRIMARY KEY (`installed_rank`)
[WARNING] DB: Can't DROP 'PRIMARY'; check that column/key exists (SQL State: 42000 - Error Code: 1091)
[DEBUG] Rolling back transaction...
[DEBUG] Transaction rolled back
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.419 s
[INFO] Finished at: 2017-02-13T09:23:54+01:00
[INFO] Final Memory: 23M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:4.1.0:migrate (default-cli) on project app: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
[ERROR] Script failed
[ERROR] -------------
[ERROR] SQL State  : 42000
[ERROR] Error Code : 1091
[ERROR] Message    : Can't DROP 'PRIMARY'; check that column/key exists
[ERROR] Line       : 21
[ERROR] Statement  : ALTER TABLE `schema_version` DROP PRIMARY KEY, ADD CONSTRAINT `schema_version_pk` PRIMARY KEY (`installed_rank`)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.flywaydb:flyway-maven-plugin:4.1.0:migrate (default-cli) on project app: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
Script failed
-------------
SQL State  : 42000
Error Code : 1091
Message    : Can't DROP 'PRIMARY'; check that column/key exists
Line       : 21
Statement  : ALTER TABLE `schema_version` DROP PRIMARY KEY, ADD CONSTRAINT `schema_version_pk` PRIMARY KEY (`installed_rank`)

When inspecting my schema_version table i see that the primary key is missing :

`show create table schema_version` output :
CREATE TABLE schema_version (
  version_rank int(11) NOT NULL,
  installed_rank int(11) NOT NULL,
  version varchar(50) COLLATE utf8_danish_ci NOT NULL,
  description varchar(200) COLLATE utf8_danish_ci NOT NULL,
  type varchar(20) COLLATE utf8_danish_ci NOT NULL,
  script varchar(1000) COLLATE utf8_danish_ci NOT NULL,
  checksum int(11) DEFAULT NULL,
  installed_by varchar(30) COLLATE utf8_danish_ci NOT NULL,
  installed_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  execution_time int(11) NOT NULL,
  success tinyint(1) NOT NULL,
  KEY schema_version_vr_idx (version_rank),
  KEY schema_version_ir_idx (installed_rank),
  KEY schema_version_s_idx (success)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci

adding installed_rank as a primary key, fixed the issue, and i was able to successfully migrate to 
schema_version 4.1.0
`alter table schema_version add PRIMARY key (installed_rank);`

**Comment by axelfontaine** [comment]
The primary key should have been there: https://github.com/flyway/flyway/blob/flyway-3.2.1/flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/mysql/createMetaDataTable.sql#L30

No idea why your metadata table was modified, but I'm glad you found a solution.

**Comment by pacey** [comment]
Sorry to plus 1 this issue but I've just ran into something similar where my schema version table is trying to drop an index that doesn't exist. I'd raised it initially with spring-boot, but they have correctly forwarded me on here.

https://github.com/spring-projects/spring-boot/issues/12506

**Comment by axelfontaine** [comment]
@pacey As I wrote to in my previous comment on this issue:
- The primary key should have been there
- No idea why your metadata table was modified

We do not plan on revisiting these ancient versions of Flyway to fix this.

This means you have 3 options:
1. Manually recreate that index so that migration can proceeed
2. Drop your schema_version table and recreate it using baseline with Flyway 5.0.7
3. Leave your schema_version table as-is for historical reference and baseline using Flyway 5.0.7 and specify a new table name such as `flyway_schema_history` (Flyway's new default, but in this case you must specify it explicitly to avoid our compatibility fallback code)
