### ISSUE TITLE
file flyway-commandline-4.1.0-windows-x64.zip does not contain jre

### ISSUE THREAD

**Issue by tcat2** [flyway/flyway#1528]
###### What version of Flyway are you using?

does not matter

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

does not matter

###### What database are you using (type & version)?

does not matter

###### What operating system are you using?

does not matter

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
try to download 
flyway-commandline-4.1.0-windows-x64.zip
https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/4.1.0/flyway-commandline-4.1.0-windows-x64.zip

###### What did you expect to see?

file with jre

###### What did you see instead?

file without jre

**Comment by axelfontaine** [comment]
Duplicate of #1525
