### ISSUE TITLE
Incosistent Flyway versions (4.0.3, 4.1.0 and 4.1.1)

### ISSUE THREAD

**Issue by aladin2020** [flyway/flyway#1535]
###### What version of Flyway are you using?
Starting with 4.0.3 then 4.1.1 and 4.1.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
I'm using gradle plugin

###### What database are you using (type & version)?
Oracle and MariaDB

###### What operating system are you using?
Win

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
The same sql scripts used to build an environment, they worked each time I called flywaymigrate, all of a sudden I got:
* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
Validate failed: Migration description mismatch for migration 01.02
-> Applied to database : ddl tableNamesChanged MySQL
-> Resolved locally    : ddl OraMariadbCompatiblity MySQL

When I used flywayrepair: it works
I called flywaymigrate the same error still appears

I changed the version from 4.0.3 to 4.1.1
plugins {
    id "org.flywaydb.flyway" version "4.0.3"
}
When I used flywayrepair: it DOESNT works
I called flywaymigrate, I got: 
* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
Unable to instantiate JDBC driver: org.mariadb.jdbc.Driver : org.mariadb.jdbc.Driver
org.mariadb.jdbc.Driver

I changed the versin to 4.1.0 and both flywayrepair and flywaymigrate work.

WHAT'S GOTING ON HERE ??????

###### What did you expect to see?
It must work, since neither the sql scripts nor the gradle build has changed

###### What did you see instead?
The error mentioned above

**Comment by axelfontaine** [comment]
We tightened the behavior of validate on 4.1.0 to catch description mismatch issues in the metadata table and we added the ability to repair those to repair().

This should also work in Flyway 4.1.1, if not it's a bug. Can you share a small test case that reproduces the issue on Flyway 4.1.1?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
