### ISSUE TITLE
no index and no PK on schema_version

### ISSUE THREAD

**Issue by fportillo** [flyway/flyway#1536]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle plugin

###### What database are you using (type & version)?
Postgresql v. 9.5

###### What operating system are you using?
Fedora 25 x64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Looked for primary key in schema_version.

###### What did you expect to see?
I expected schema_version to have one of index or PK

###### What did you see instead?
No indexes, no PK. Although you may argue that everything is controlled by the application, in some situations such as migrating data from one database to another (and keeping migration state), e.g., from Postgresql to Oracle and vice-versa, it's very usefull for DBAs to have this information.

**Comment by axelfontaine** [comment]
This must be an issue with your specific setup as Flyway does create those by default: https://github.com/flyway/flyway/blob/master/flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/postgresql/createMetaDataTable.sql
