### ISSUE TITLE
The default Java API log level (DEBUG) is way too verbose

### ISSUE THREAD

**Issue by who** [flyway/flyway#1538]
###### What version of Flyway are you using?
4.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
mysql 5.7 served from an in-memory docker container

###### What operating system are you using?
Ubuntu 16.04 LTS

###### What did you do?
Performed a flyway clean + migrate in an integration test:
```
Flyway flyway = new Flyway();
flyway.setDataSource("...");
flyway.setLocations("...");
flyway.clean();
flyway.migrate();
```
This is executed with maven:
```
mvn clean verify -P integration-test 
```
The clean+migrate work just fine, but my terminal is spammed with DEBUG messages.

###### What did you expect to see?
INFO level logging

###### What did you see instead?
DEBUG level logging (~1500 lines of noise)

**Comment by axelfontaine** [comment]
This is due to your configuration of your logging framework in your application.

**Comment by who** [comment]
My application (Dropwizard-based) is configured with INFO level for `org.flywaydb`.

**Comment by who** [comment]
I was able to fix this by adding this `logback-test.xml` to my `src/test/resources` folder:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <logger name="org.flywaydb" level="info" />
</configuration>
```
