### ISSUE TITLE
/etc/hosts file not checked for database URLs

### ISSUE THREAD

**Issue by eepstein** [flyway/flyway#1542]
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Gradle Plugin (hence the older version)

###### What database are you using (type & version)?

Postgres 9.5

###### What operating system are you using?

Client: Mac
Server:  Ubuntu (I think)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Changed the connection URL from the full host name to a host alias registered in the local /etc/hosts file.

###### What did you expect to see?

The connection should work (per Postgres JDBC docs this is supported)

###### What did you see instead?

The connection attempt failed.

**Comment by eepstein** [comment]
was trying to use an alias.  changed to ip address and it works.  closing (non-)"issue"

**Comment by yamb00** [comment]
OS: Centos 7
Env: docker-ce
driver: mysql-connector-java-5.1.44
flyway-version: 4.2.0

please fix this behaviour. I want to you use /etc/hosts

**Comment by axelfontaine** [comment]
This is an issue with your system. As the PG JDBC driver uses the JVM, which in turn uses the C library to lookup hosts, there must be something broken at this level on your machine/container.
