### ISSUE TITLE
Raima Rdm support

### ISSUE THREAD

**Issue by stecolet** [flyway/flyway#1543]
###### What version of Flyway are you using?
4.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Raima rdm

###### What operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
In our company we were using flyway to manage db migrations on Postgres database. Now we are migrating to a proprietary db: Raima Rdm http://raima.com/raima-database-manager. It supplies a properly Jdbc driver.
I’ve tried to launch flyway migrate but it can’t support raima rdm database.
 
Because I would like to continue to use flyway for my purpose, could be Raima supported in the future?

###### What did you expect to see?
I expect flyways can support this db

###### What did you see instead?
ERROR: Unsupported Database: Raima Database manager 14.0

**Comment by alextercete** [comment]
Closing due to lack of interest.
