### ISSUE TITLE
Unable to create a function in mysql using flyway

### ISSUE THREAD

**Issue by Lochan08** [flyway/flyway#1544]
###### What version of Flyway are you using?

flyway 4.0 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

commandline

###### What database are you using (type & version)?

mysql 5.1.62-re13.3-log

###### What operating system are you using?

linux x86_64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I can create a function when i run a script manually, however when i run it using flyway it is giving error.
I am using below script to create the function is 'IS_ADGROUP_CAMPAIGN_ACCOUNT_ACTIVE' in schema ampx.
Below is the script for your reference:

CREATE DEFINER=`root`@`localhost` FUNCTION `ampx`.`IS_ADGROUP_CAMPAIGN_ACCOUNT_ACTIVE`(in_adgroup_id INTEGER) RETURNS tinyint(4)
    READS SQL DATA
begin
  declare result tinyint;

  select
  (1 = ag.ADGROUP_STATUS_ID and 1 = c.CAMPAIGN_STATUS_ID and 1 = a.ACCOUNT_STATUS_ID) into result
  from ADGROUP ag inner join CAMPAIGN c on c.ID = ag.CAMPAIGN_ID
  inner join ACCOUNT a on a.ID = c.ACCOUNT_ID
  where ag.ID = in_adgroup_id;

  return result;
end

###### What did you expect to see?

I expect to see the function getting created successfully

###### What did you see instead?
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2

**Comment by axelfontaine** [comment]
Unable to reproduce. This is most likely due to you not setting delimiters correctly before defining the function.

**Comment by Lochan08** [comment]
You are right, its just the delimiters that i was missing.
Thanks
