### ISSUE TITLE
Ensure Java 9 compatibility

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#1545]

**Comment by relgames** [comment]
Flyway gradle plugin does not work with Java 9:
`java.lang.ClassNotFoundException: org.omg.CORBA.Object`

**Comment by masc3d** [comment]
now that java 9 has been finalized, I would see this as a bug, not a feature.
also, `5.0.0` as a milestone with 20% completion seems awfully far away for something that fundamental, so it may be appropriate to also fix this for `4.x`.

**Comment by jillesvangurp** [comment]
I looked through the repository for references to org.omg.CORBA.Object. I found two imports and both look like bugs to me. FlywayValidateTask and FlywayRepairTask both override FlywayRepairTask.run and import this (without actually using it), which returns a java.lang.Object. Both these classes have the import, which IMHO should be safe to remove. Probably these were added by mistake by some IDE? I don't see a reason for flyway to have any CORBA dependencies.

**Comment by dhardtke** [comment]
@axelfontaine can we expect a hotfix release soon?

**Comment by bendem** [comment]
I stumbled upon this when trying to run a migration with java 9.

```
Flyway 4.2.0 by Boxfuse

DEBUG: Java 9 (Oracle Corporation)
DEBUG: Mac OS X 10.12.6 x86_64

DEBUG: Loading config file: /usr/local/Cellar/flyway/4.2.0/libexec/conf/flyway.conf
DEBUG: Unable to load config file: /Users/benjamin/flyway.conf
DEBUG: Loading config file: /Users/benjamin/projects/<x>/server/flyway.conf
Database password:
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /usr/local/Cellar/flyway/4.2.0/libexec/jars
DEBUG: flyway.locations -> filesystem:src/main/resources/migrations
DEBUG: flyway.url -> jdbc:postgresql://<x>/<y>
DEBUG: flyway.user -> <u>
DEBUG: flyway.baselineVersion -> 0
DEBUG: flyway.password -> ****
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/derby-10.12.1.1.jar
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to load /usr/local/Cellar/flyway/4.2.0/libexec/drivers/derby-10.12.1.1.jar
	at org.flywaydb.core.internal.util.ClassUtils.addJarOrDirectoryToClasspath(ClassUtils.java:156)
	at org.flywaydb.commandline.Main.loadJdbcDrivers(Main.java:305)
	at org.flywaydb.commandline.Main.main(Main.java:95)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.flywaydb.core.internal.util.ClassUtils.addJarOrDirectoryToClasspath(ClassUtils.java:151)
	... 2 more
```

**Comment by zlangbert** [comment]
Also hitting this issue, a hotfix release would be awesome

**Comment by chadjaros** [comment]
Same

**Comment by logicbomb421** [comment]
Yeah same boat here.

**Comment by dhardtke** [comment]
ping @axelfontaine

**Comment by iLavryk** [comment]
me the same
An exception occurred applying plugin request [id: 'org.flywaydb.flyway', version: '4.2.0']
> Failed to apply plugin [id 'org.flywaydb.flyway']
   > Could not generate a proxy class for class org.flywaydb.gradle.task.FlywayValidateTask.

if look to stacktrace i found:
Caused by: java.lang.NoClassDefFoundError: org/omg/CORBA/Object

**Comment by axelfontaine** [comment]
Java 9 support is now implemented.

**Comment by jillesvangurp** [comment]
@axelfontaine great! Will there be a backport or do we have to wait for the next major version?

**Comment by axelfontaine** [comment]
@jillesvangurp No backport. Flyway 5.0 is due out by the end of the month and comes with many other enhancements and fixes.

**Comment by dhardtke** [comment]
Excellent!

**Comment by naveensharma18** [comment]
Failed to apply plugin [id 'org.flywaydb.flyway']
Could not generate a proxy class for class org.flywaydb.gradle.task.FlywayValidateTask

Using java 10 + flyway 5.1.4

trying to deploy the code but getting above exception.

Any help ?
