### ISSUE TITLE
Abstraction over org.flywaydb.core.internal.util.scanner.Scanner

### ISSUE THREAD

**Issue by tfij** [flyway/flyway#1547]
###### What version of Flyway are you using?
4.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java with spring boot.

###### What database are you using (type & version)?
Mysql 5.6 and H2 1.4.193

###### What operating system are you using?
Linux Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I'm trying to load migration script depend on spring profile. I'd like to have convection like:
Vnumber_desc_listOfProfiles.sql
eg. V0034_insertUser_local,dev.sql
I found solution for DB specific sql (http://stackoverflow.com/questions/27909642/using-flyway-to-load-data-conditionally-per-environment), unfortunately it is not clear.

###### What did you expect?
I'd like to use custom org.flywaydb.core.internal.util.scanner.Scanner or some kind of custom Resource filter to filter out files with not matching Resource. Then in application.properties configure it:
flyway.custom-filter=com.example.MyResourceFilter
In a MyResourceFilter I'll inject spring profile and write simple regex on file name.

if you give me some hints I can try to implement it and make a PR.

**Comment by axelfontaine** [comment]
No need to implement anything. Simply set `sqlMigrationSuffix` to the value you want based on the active Spring profile.

**Comment by tfij** [comment]
If file is named `V0034_insertUser_local,dev.sql` it should start at `local` and `dev`, if `V0034_insertUser_local.sql` then only on `local`, id `V0034_insertUser.sql` then on all env. I can't simply configure `sqlMigrationSuffix` as `local`.

**Comment by axelfontaine** [comment]
Then a custom `MigrationResolver`is what you need.

**Comment by tfij** [comment]
I need whole functionality of `SqlMigrationResolver` but filter out some script.
`SqlMigrationResolver` is not a bean so I have to create it and aggregate it in my class (or inherit).
To create instance of `SqlMigrationResolver` its required: `DbSupport`, `Scanner`, `Location`, `PlaceholderReplacer`, `FlywayConfiguration`. All that classes are not bean's and I will have to instantiate them manually. And so on. It push me in a terrible coupling.
It is better then simple filter class?

**Comment by tfij** [comment]
Here is one of implementation (override Scanner):

```
public ProfileAwareMigrationResolver() {
    }

    @Override
    public Collection<ResolvedMigration> resolveMigrations() {
        DbSupport dbSupport = null; // can't inject it
        PlaceholderReplacer placeholderReplacer = null;  // can't inject it
        Flyway flywayConfiguration = null; // can't inject it
        Location location = null; // can't inject it
        Environment env = null; // can't inject it
        Scanner scanner = new Scanner(getClass().getClassLoader()); // original scanner, should also be inject
        Scanner profileAwareScanner = new ProfileAwareScanner(scanner.getClassLoader(), env);
        MigrationResolver delegate = new SqlMigrationResolver(dbSupport, scanner, location, placeholderReplacer, flywayConfiguration);
        return delegate.resolveMigrations();
    }

    private static class ProfileAwareScanner extends Scanner {

        private final Environment environment;

        ProfileAwareScanner(ClassLoader classLoader, Environment environment) {
            super(classLoader);
            this.environment = environment;
        }

        @Override
        public Resource[] scanForResources(Location location, String prefix, String suffix) {
            return Arrays.stream(super.scanForResources(location, prefix, suffix))
                    .filter(it -> isScriptApplicableForEnc(it.getFilename()))
                    .toArray(Resource[]::new);
        }

        @Override
        public Class<?>[] scanForClasses(Location location, Class<?> implementedInterface) throws Exception {
            return super.scanForClasses(location, implementedInterface);
        }

        private Set<String> profilesFromFileName(String filename) {
            return Collections.emptySet(); //TODO to implement
        }

        private boolean isScriptApplicableForEnc(String filename) {
            Set<String> scriptProfiles = profilesFromFileName(filename);
            Set<String> activeProfiles = new HashSet<>(Arrays.asList(environment.getActiveProfiles()));
            return scriptProfiles.stream().anyMatch(scriptProfile -> activeProfiles.contains(scriptProfile));
        }
    }
```

There are two problems: 
- class is created by reflection (if I use resolversAsClassNames in `application.properties`).
- There is no way to access instances of class DbSupport, PlaceholderReplacer etc

Alternative implementatim may lock like:
```
return delegate.resolveMigrations()
    .stream();
    .filter(it -> filterByLocationOnDisk(it.getLocationOnDisk()))
    .collect(Collectors.toList());
```

unfortunately, problems do not disappear.

**Comment by axelfontaine** [comment]
Duplicate of #897

**Comment by tfij** [comment]
I'm glad you noticed that you can improve the library in order to solve the problem described by me :)

**Comment by tfij** [comment]
I'm glad you noticed that you can improve the library in order to solve the problem described by me :)
