### ISSUE TITLE
Flyway "(unsupported protocol: war)" with Tomcat 8.0.41 and unpackWARs=false

### ISSUE THREAD

**Issue by thomasmey** [flyway/flyway#1549]
Hi,

this Tomcat commit https://github.com/apache/tomcat80/commit/7e767cc6efe79cdd367213da3c1f88711a29ad7a#diff-a72fb99b0729353084d2c437f749e718 broke Flyway in https://github.com/flyway/flyway/blob/7925112a1041d7763d722a4d36cbbb39277e7b5c/flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/ClassPathScanner.java#L310
with Tomcat config unpackWARs=false.
The returned URL is now war: instead of jar:

**Comment by thomasmey** [comment]
The fix from https://github.com/flyway/flyway/issues/1512 is incomplete as the JarFileClassPathLocationScanner will get used for protocol "war" but the protocol separator is then "*/" and not "!/", so getJarFromUrl() will fail to correctly determine the file name.

This whole code fragment looks very similar to https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java#L578 which has a similar bug reported in https://jira.spring.io/browse/SPR-15332

**Comment by axelfontaine** [comment]
Arrgghh!! OK, we'll have to adjust for this.

**Comment by axelfontaine** [comment]
Thanks for the PR! Merged.
