### ISSUE TITLE
Consider making AbstractFlywayTask public again

### ISSUE THREAD

**Issue by wstrzalka** [flyway/flyway#1551]
Hi

   I had made an own plugin to improve cooperation of Flyway and JOOQ based on AbstractFlywayTask. Since it was made private I can not upgrade to latest version without bulk copy-paste from flyway. 
Would you mind considering making it public again - this will help resolve [#1](https://github.com/wstrzalka/gradle-flyway-jooq-plugin/issues/1)

**Comment by axelfontaine** [comment]
I am not opposed to make this public, however ... keep in mind that we won't be making this a published interface. Therefore: 0 compatibility guarantees for the future.

**Comment by wstrzalka** [comment]
Roger that. Thanks
