### ISSUE TITLE
validate does not respect target

### ISSUE THREAD

**Issue by masc3d** [flyway/flyway#1554]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Verified against command line and gradle plugin

###### What database are you using (type & version)?
mysql

###### What operating system are you using?
macos

###### What did you do?
* `migrate` without target set (applying all migrations)
* `validate` with `flyway.target` set to a lower version and `flyway.ignoreFutureMigrations=false`

###### What did you expect to see?
Validate should fail.

###### What did you see instead?
Validate completes successfully as long as future migrations can be found. `flyway.target` is ignored.

**Comment by axelfontaine** [comment]
This doesn't strictly fall under the current definition of future as future currently means higher than the highest version resolved on the classpath or filesystem.

I am however not opposed to revisit the meaning of feature for 5.0 to mean higher than target.

**Comment by masc3d** [comment]
Then the current definition is flawed, as it doesn't make much sense as soon as `target` is set.

**Comment by axelfontaine** [comment]
The definition of future is actually consistent and correct.

However, we have now changed validate to ignore anything above target, which is more consistent with the definition of target.

**Comment by masc3d** [comment]
> I am however not opposed to revisit the meaning of feature for 5.0 to mean higher than target.

I suppose we missed that one. I still believe it's worth changing this for the better.

anyway as it seems, it's now also broken for future migrations not being on the classpath as of 6.0.8. 

please re-open @axelfontaine
