### ISSUE TITLE
checksum values are negative

### ISSUE THREAD

**Issue by sinall** [flyway/flyway#1560]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
SQLite version 3.15.2 (SQLCipher 3.15.2)

###### What operating system are you using?
Windows 10 X64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

flyway migrate

Script file: V1_2__Create_table_settings.sql
```
DROP TABLE IF EXISTS settings;
CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY
);
```

###### What did you expect to see?
I use [csc32.exe tool](http://esrg.sourceforge.net/utils_win_up/md5sum/) to manually generate checksum.

>crc32.exe sql\V1_2__Create_table_settings.sql
0x5C86DB25 (106)

The corresponding base-10 number is **1552341797**.

###### What did you see instead?
checksum value in schema_version is **-723451720**. I'm not quite familiar with CRC32 checksum algorithm, but this seems not correct.

**Comment by axelfontaine** [comment]
This is fine and it works as designed. Those are just two different ways to represent 32 bit integers: signed and unsigned.
