### ISSUE TITLE
Flyway Maven Plugin fails to recognize Materialized view

### ISSUE THREAD

**Issue by barkhakeni** [flyway/flyway#1561]
###### What version of Flyway are you using?
4.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Flyway Maven Plugin

###### What database are you using (type & version)?
Postgres 9.3

###### What operating system are you using?
Centos 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I was running flyway maven plugin which tries to run the sql scripts. IT says unexpected token materialized

###### What did you expect to see?
Expected it to run

###### What did you see instead?
SQL State  : 42581
[ERROR] Error Code : -5581
[ERROR] Message    : unexpected token: MATERIALIZED

**Comment by axelfontaine** [comment]
Flyway passes statements as is to your database via your JDBC driver. Either of these two is to blame, not Flyway.
