### ISSUE TITLE
Add flyway.configFiles support to Gradle plugin

### ISSUE THREAD

**Issue by rbatllet** [flyway/flyway#1562]
###### What version of Flyway are you using?
4.1.2 version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Gradle plugin

###### What database are you using (type & version)?

Oracle 11.2.0.4

###### What operating system are you using?

Windows 2010

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

The flyway.configFile cannot be found. 

The command is the following:
```
gradle flywayInfo -Dflyway.configFile=flyway.local.properties
```

###### What did you expect to see?

The information about the  pending migrations or added.
`It works with the Maven plugin version, but not with the Gradle plugin version`

###### What did you see instead?
```
Unknown configuration property: flyway.configFile
:myProject:flywayInfo FAILED
:myProject:flywayInfo (Thread[Daemon worker Thread 8,5,main]) completed. Took 1.713 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myProject:flywayInfo'.
> Error occurred while executing flywayInfo
Unable to connect to the database. Configure the url, user and password!

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
```

**Comment by rbatllet** [comment]
It would be nice to do something like this as well:

```
flyway {
    configFile = file("myFlyway.properties")
}
```

**Comment by axelfontaine** [comment]
We have now added support for `flyway.configFiles` which also supports multiple config files.

**Comment by swat2793** [comment]
Trying to use the flyway.configFiles with gradle plugin in intelliJ for a springboot application. The configuration is as shown below 

<img width="561" alt="flyway" src="https://user-images.githubusercontent.com/14159722/65576331-59754900-dfa4-11e9-869d-f0137ed9f818.PNG">

the below error comes on trying to build 

 Executing task 'flywayMigrate -x test -Dflyway.configFiles=flyway.properties'...

> Task :flywayMigrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  Unable to load config file: /home/user/Workspace/sample/flyway.properties

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
