### ISSUE TITLE
SQLCipher support

### ISSUE THREAD

**Issue by sinall** [flyway/flyway#1563]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
SQLCipher-3.15.2 (SQLite-3.15.2)

###### What operating system are you using?
WIndows 10 X64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
flyway -url=jdbc:sqlite:data-template.db -locations=filesystem:.db/migration -password=testkey migrate

###### What did you expect to see?
Migrate successfully.

###### What did you see instead?

> Flyway 4.1.2 by Boxfuse
> 
> Database user:
> 
> Database: jdbc:sqlite:.data-template.db (SQLite 3.0)
> ERROR:
> Unable to check whether table "main"."schema_version" exists
> ------------------------------------------------------------
> SQL State  : null
> Error Code : 26
> Message    : [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)

**Comment by alextercete** [comment]
Closing due to lack of interest.

**Comment by vAdyar** [comment]
Are there any plans for the SqlCipher support in the near future?
