### ISSUE TITLE
Read shell environment variables into pg variables like psql

### ISSUE THREAD

**Issue by bithead2k** [flyway/flyway#1571]
###### What version of Flyway are you using?

4.10

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

command line

###### What database are you using (type & version)?

PostgreSQL 9.6

###### What operating system are you using?

OS/X   and Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I run migrate from a wrapper shell script.   This script populates some shell variables, and exports them to the parent shell.

export DB_HOST=localhost
export DB_NAME=mydb
export FLYWAY_USER=myuser
export FLYWAY_PASSWORD=password
export DB_SCHEMA=account1

flyway migrate -q -locations=filesystem://$PWD/sql

In the sql script, I read the variables like this:

\\set db_host \`echo $DB_HOST\`
\\set db_name \`echo $DB_NAME\`
\\set db_user \`echo $FLYWAY_USER\`
\\set db_pass \`echo $FLYWAY_PASSWORD\`
\\set db_schm \`echo $DB_SCHEMA\`

This works in psql, but not in flyway.

###### What did you expect to see?

Populated variables in the SQL script

###### What did you see instead?

Migration V1__create.sql failed
-------------------------------
SQL State  : 42601
Error Code : 0
Message    : ERROR: syntax error at or near "\\"
  Position: 1

**Comment by bithead2k** [comment]
Extra points for getting \setenv to work also.

**Comment by axelfontaine** [comment]
We have no plans to support arbitrary shell code execution as in your example. You can however use placeholders to accomplish something very similar.

**Comment by bithead2k** [comment]
Ok, so for anybody else running into this problem I ended up with:

#populate a variable in shell
myvar=$(some complex shell script)
#use it to create a config file
echo "MYVAR=$myvar" >> myconfigfile
#merge that into a flyway.conf that has placeholders
j2 flyway.conf.j2 myconfigfile
#migrate using the config file
flyway migrate

This gets the results I was aiming for, but it's a little clunkier than using the backticks.
