### ISSUE TITLE
Migration skips first version with multiple metadata tables per Database

### ISSUE THREAD

**Issue by tburny** [flyway/flyway#1574]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
Postgresql 9.5.6

###### What operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I'm trying to run multiple migrations on the same schema(`public`) and database `test` on Postgresql:
```java
  @Test
  public void testFlywayWithBaseline() {
    for (String _category : new String[]{"catalog", "account"}) {
      Flyway _flyway = new Flyway();
      _flyway.setDataSource("jdbc:postgresql:test", System.getenv("USER"),"xy");
      _flyway.setLocations("classpath:/sql/" + _category);
      _flyway.setCallbacks(new MyFlywayCallback());
      _flyway.setTable(_category + "_schema_version");
      _flyway.setBaselineOnMigrate(true);
      _flyway.migrate();
    }
  }
```
> (MyFlywayCallback() is a callback which just prints the method names of the callbacks and the version of if any (e.g. `beforeEachMigrate`: `System.out.println("beforeEachMigrate: " + info.getVersion());`).

So in the first run, the meta data table will be `catalog_schema_version` and in the second run `account_schema_version`. 
We need the `baselineOnMigrate=true` as there are already data from the first migration. *Note that for the "account" migration no meta data table exists!*

Given the following SQL files:
`/sql/account/V1__baseline.sql`: `create table account (username VARCHAR (50));`
`/sql/account/V2__data.sql`: `insert into account values ('Jon Doe');`

and 
`/sql/catalog/V1__baseline.sql`: `CREATE table PRODUCT (pname VARCHAR (100));`
`/sql/catalog/V2__data.sql`: `insert into product (pname) values ('The Walking Dead');`

Basically I have two migrations, one for "catalog" and one for "account". Both have two versions V1 and V2 in `/sql/$category`. When running the migrations on an empty database, the "catalog" migrations succeed, while for "account" `V1` is skipped.

A more detailed explanation of the scenario can be found at http://stackoverflow.com/questions/43047184/flyway-partial-migration-of-legacy-application.
###### What did you expect to see?
As `catalog` and `account` are seperate migrations, they should not know of each other. Therefor both should successfully migrate to version 2.

###### What did you see instead?
The `account` migration for `V2` fails, as `V1` is never executed, even when repeatedly calling the migration.. This happens although Flyway should consider the table as "there is no meta data table" for each `_category`.
```Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.util.VersionPrinter printVersion
INFORMATION: Flyway 4.1.2 by Boxfuse
Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.dbsupport.DbSupportFactory createDbSupport
INFORMATION: Database: jdbc:postgresql:test (PostgreSQL 9.4)
Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.command.DbValidate validate
INFORMATION: Successfully validated 2 migrations (execution time 00:00.051s)
beforeMigrate
Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.command.DbMigrate migrate
INFORMATION: Current version of schema "public": 2
Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.command.DbMigrate logSummary
INFORMATION: Schema "public" is up to date. No migration necessary.
afterMigrate
Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.command.DbValidate validate
INFORMATION: Successfully validated 2 migrations (execution time 00:00.036s)
beforeMigrate
Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.command.DbMigrate migrate
INFORMATION: Current version of schema "public": 1
Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.command.DbMigrate applyMigration
INFORMATION: Migrating schema "public" to version 2 - insert data
beforeEachMigrate: 2
Mär 27, 2017 4:39:28 PM org.flywaydb.core.internal.command.DbMigrate applyMigration
SCHWERWIEGEND: Migration of schema "public" to version 2 - insert data failed! Changes successfully rolled back.

org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V2__insert_data.sql failed
------------------------------------
SQL State  : 42P01
Error Code : 0
Message    : ERROR: relation "account" does not exist
  Position: 13
Location   : sql/account/V2__insert_data.sql (/home/tobi/workspace/flywaytest/target/classes/sql/account/V2__insert_data.sql)
Line       : 1
Statement  : insert into account values ('Jon Doe')
```
and further below in the stack trace the according `PSQLException` can be seen.

When adding 
```java
     _flyway.setBaselineVersion(MigrationVersion.fromVersion("0"));
```
the test passes, as the baselined version is now "0" and it proceeds to "1".
However this does not allow a `V0` for initialization.

**Comment by axelfontaine** [comment]
Works as designed. The default for `baselineVersion` is `1` and explains this behavior perfectly (see https://flywaydb.org/documentation/commandline/migrate)

**Comment by tburny** [comment]
Thank you for your quick response. I'm sorry, but it seems the log I posted was incomplete. I re-ran the test case on a fresh database and updated the log above.

Looking at the log, it seems there is a distinction between an empty schema (`<< Empty Schema >>`) and a non-empty one: 
* *Empty schema: * The `V1_catalog` migration is applied and the database is baselined *afterwards*
* If there are some pre-existing tables, baselining seems to be done *before* the migration. The form the baseline ("these tables are already version 1").

Maybe I can help to improve the documentation on that part, if you like to? It really wasn't that obvious :smiley:

To wrap it up:
> INFORMATION: Creating Metadata table: "public"."catalog_schema_version"
> INFORMATION: Current version of schema "public": << Empty Schema >>
> INFORMATION: Migrating schema "public" to version 1 - baseline

Note that no baselining is performed here.

> beforeEachMigrate: 1
> afterEachMigrate: 1
> INFORMATION: Migrating schema "public" to version 2 - insert data
> beforeEachMigrate: 2
> afterEachMigrate: 2
> INFORMATION: Successfully applied 2 migrations to schema "public" (execution time 00:00.210s).
> afterMigrate
> beforeBaseline

Now for `account` there are tables and the database gets baselined. Flyway assumes the current state is version 1 and it has to resume with version 2.

> Mär 28, 2017 11:11:00 AM org.flywaydb.core.internal.metadatatable.MetaDataTableImpl createIfNotExists
> INFORMATION: Creating Metadata table: "public"."account_schema_version"
> afterBaseline
> INFORMATION: Successfully baselined schema with version: 1
> beforeMigrate
> INFORMATION: Current version of schema "public": 1
> INFORMATION: Migrating schema "public" to version 2 - insert data
> beforeEachMigrate: 2
> Mär 28, 2017 11:11:00 AM org.flywaydb.core.internal.command.DbMigrate applyMigration
> SCHWERWIEGEND: Migration of schema "public" to version 2 - insert data failed! Changes successfully rolled back.
> 
> org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
> Migration V2__insert_data.sql failed
>
> SQL State  : 42P01
> Error Code : 0
> Message    : ERROR: relation "account" does not exist
>   Position: 13
> Location   : sql/account/V2__insert_data.sql (/home/tobi/workspace/flywaytest/target/classes/sql/account/V2__insert_data.sql)
> Line       : 1
> Statement  : insert into account values ('Jon Doe')
>

**Comment by axelfontaine** [comment]
Thanks for the details. I can confirm this works as designed. Documentation pull requests are always welcome :-)
