### ISSUE TITLE
Command info:  Comparison method violates its general contract!

### ISSUE THREAD

**Issue by aoksys** [flyway/flyway#1575]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

###### What operating system are you using?
Windows 7 Professional Service Pack 1

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

There exist several normal successful migrations in the database, which have been executed with flyway Version 3.2.1.
Now i want to proceed with some new migrations using flyway Version 4.1.2. 
Before doing that I ran the command "flyway.cmd info" and receive the error message:
_ERROR: java.lang.IllegalArgumentException: Comparison method violates its general contract!_

Note: 
To reproduce the error, please find attached a zip-file containing:
- my configuration Settings (directory 'conf')
- the insert-statements to restore my original schema-table-state to reproduce the error in your local database (file named 'inserts_bug.sql', possibly here you have to modify the tablespace-names)
- the sql-migrations (Directory 'sql', the content of the SQL-migration-files is not relevant for the bug, only the names, so you find all files more or less empty.)
- the oracle-jdbc-driver I am using (directory 'drivers')

[flyway_bug.zip](https://github.com/flyway/flyway/files/872906/flyway_bug.zip)

###### What did you expect to see?
The normal info-Output.

###### What did you see instead?
This error message:
_ERROR: java.lang.IllegalArgumentException: Comparison method violates its general contract!_

**Comment by aoksys** [comment]
Hi Axel,

I noticed, that the milestone for this issue has been changed to 5.0.0. 
In my eyes, the bug is quite relevant. It appears only under certain circumstances (i.e. data constellations). The main effect is, when the bug appears, it appears on **all flyway commands** and not only on the command "info" (sorry, I didn't point up that before) and I think, this may have an impact on all flyway users. 

For that reason we are forced to remain with all of our customers on Version 3.2.1, because we are responsible for the reliability of our delivered software (including database).
For that reason I would appreciate, if you could decide to accelerate the problem solution.

Please don't hesitate to contact me here, if you need additional information concerning this issue.

Best regards.

**Comment by junkmanuk** [comment]
This is related to a change in the way Java performs sorting:

http://www.oracle.com/technetwork/java/javase/compatibility-417013.html#source
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6804124

To circumvent this issue in the short term add the following parameter to your flyway java command line:

 -Djava.util.Arrays.useLegacyMergeSort=true

**Comment by ford-thomas-w** [comment]
I am getting this error too, but I don't know how to apply this suggested short term fix.  Sorry, a noob question: where is the "flyway java command line" ?  I have flyway installed on an Ubuntu 14.04 headless server.

**Comment by junkmanuk** [comment]
Edit the file 'flyway'

Add the parameters to the end of the JAVA_ARGS line

**Comment by aoksys** [comment]
Here an extract of the file 'flyway' to clarify:

...
if $linux; then
  JAVA_ARGS=-Djava.security.egd=file:/dev/../dev/urandom **-Djava.util.Arrays.useLegacyMergeSort=true** 
fi
if $cygwin; then
  CP=$(cygpath -pw "$CP")
fi
"$JAVA_CMD" $JAVA_ARGS -cp "$CP" org.flywaydb.commandline.Main "$@"
...

**Comment by aoksys** [comment]
By the way, thanks to junkmanuk.
This seems to be a fine workaround.

@axelfontaine : 
But honestly we would appreciate to receive a stable solution of this issue, which works with all Java versions. We're looking forward to Flyway 5.0.0!

**Comment by junkmanuk** [comment]
Sorry for the brevity of my response - was on mobile - pleased it helps as much as it helped me!

**Comment by ford-thomas-w** [comment]
Worked! Thank you both!
