### ISSUE TITLE
Validate Failed After DB cleanup

### ISSUE THREAD

**Issue by sushil5612** [flyway/flyway#1576]
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Maven

###### What database are you using (type & version)?

Oracle 11g

###### What operating system are you using?

Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I have a list of scripts in order and try to run mvn:migrate  there was some issue with the script hence run the mvn:cleanup to clean the whole database. I have checked the DB is clean now.
While running the mvn:validate it fails saying "Validate failed: Detected resolved migration not applied to database: 1.0.0"

while running mvn:info gets below
+---------+-----------------------------+---------------------+---------+
| Version | Description                 | Installed on        | State   |
+---------+-----------------------------+---------------------+---------+
| 1.0.0   | BaselineSQLs-DDL            |                     | Pending |
| 1.0.1   | Baseline StoredProcs        |                     | Pending |
| 2.0.0   | InitialVersion              |                     | Pending |
| 2.0.1   | InitialVersion              |                     | Pending |
| 2.0.3   | InitialVersionJavaMigration |                     | Pending |
| 2.0.4   | InitialVersionDML           |                     | Pending |
|         | InitialVersion Views        |                     | Pending |
+---------+-----------------------------+---------------------+---------+

version 1.0.0 is the first script and there are no future versions applied in DB, since it is clean. 

My scripts are in order as well.

###### What did you expect to see?

validate should validate my scripts fine and allow migrate to run.

###### What did you see instead?
"Validate failed: Detected resolved migration not applied to database: 1.0.0"

**Comment by axelfontaine** [comment]
Works as designed. Starting with 4.0 validate fails when there are unapplied migrations.
