### ISSUE TITLE
Fail on incorrect parameter instead of showing a warning

### ISSUE THREAD

**Issue by teopost** [flyway/flyway#1577]
###### What version of Flyway are you using?

4.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

Oracle 11r2

###### What operating system are you using?

Mac OSX Sierra

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

```
+---------------------+-------------------------------------+---------------------+---------+
| Version             | Description                         | Installed on        | State   |
+---------------------+-------------------------------------+---------------------+---------+
| 1.0.0.20170327.1108 | new Sequences                       |                     | Pending |
| 1.0.0.20170327.1109 | new Tables                          |                     | Pending |
| 2.0.0.20170327.1130 | new Functions                       |                     | Pending |
| 2.0.0.20170327.1150 | cust view Utenti                    |                     | Pending |
| 2.0.0.20170327.1151 | cust view V TALKS ISCRITTI          |                     | Pending |
| 2.0.0.20170327.1152 | cust view V TALKS ISCR 2017 T0201   |                     | Pending |
| 2.0.0.20170327.1155 | add dataora spedizioni              |                     | Pending |
| 2.0.0.20170327.1200 | drop comunicazioni id on spedizioni |                     | Pending |
+---------------------+-------------------------------------+---------------------+---------+
```

```bash
flyway -configFile=conf/dallas-flyway_test-bocconi.cfg  -taget=2.0.0.20170327.1151  migrate
```

I used a wrong parameter. ```taget``` instead of ```target````

###### What did you expect to see?

Flyway report an error because ```taget``` parameter is unknow and the migration are not applyed

###### What did you see instead?

Flyway apply all migrations !

**Comment by axelfontaine** [comment]
Hmm this should actually be checked...

**Comment by teopost** [comment]
Flyway shows the message `` WARNING: Unknown configuration properties: flyway.target` `` but migrations are applied

https://asciinema.org/a/6q6m84saohacpmq8tadcwfpbn
