### ISSUE TITLE
Easy Flyway test environment setup based on Docker

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#1579]
Currently it is tedious and time-consuming to set up all databases required to fully test Flyway. See https://flywaydb.org/documentation/contribute/code/database

It should be easier both for existing and new contributors to quickly fire up a complete test environment with all databases to be able to run the full set of Flyway tests.

Almost every single database vendor now maintains a set of official Docker images. This should be leveraged in a Docker Compose file. See https://docs.docker.com/compose/compose-file/

Additionally the existing test configuration should be adapted to reference the databases started in the individual containers.

Even if not all databases are included at first, this approach could debut with a subset and expand from there.

Who's up for the challenge and ready to step up and contribute?

**Comment by kiview** [comment]
It might be beneficial to use https://github.com/testcontainers/testcontainers-java for this task. I'll look into the current integration test aproach for Flyway and see if I'll be able to contribute.

**Comment by axelfontaine** [comment]
@kiview Any of these works for us. At the end of the day the most convenient one for our contributors (prio 1) with the fastest run times (prio 2) wins.

**Comment by bsideup** [comment]
Hi all,

I'm a co-maintainer of TestContainers and here to help :)

I checked some tests and can verify that it should be easy to integrate TestContainers.

Let me know if you want me to contribute some basic TC support (like we did with Zipkin)

I'm also open to any questions you have :)

**Comment by axelfontaine** [comment]
@bsideup Thanks! Yes, we're interested! Let's maybe start with a single database in the first PR to get warmed up and expand from there.

**Comment by bsideup** [comment]
@axelfontaine sure :) Just point me at some test where you use a real database so I can play around and replace it with TestContainers' based instance.

**Comment by axelfontaine** [comment]
@bsideup These ones for example: https://github.com/flyway/flyway/tree/master/flyway-core/src/test/java/org/flywaydb/core/internal/dbsupport/db2

**Comment by axelfontaine** [comment]
@bsideup Did you have the chance to look into this yet?

**Comment by bsideup** [comment]
Hi @axelfontaine,

Sorry, didn't have enough time because of job change, but I'll have it soon :)
FYI since db2 integration is mostly about preparing the DB, it will help if you provide a Dockerfile/image for it. Of course, I can do it for you, but it will speed it up :)

**Comment by axelfontaine** [comment]
@bsideup I just pushed our initial testcontainers integration. It works great locally, however TravisCI seems to be having trouble. Could you have a look? I am sure I made a trivial mistake somewhere.

**Comment by bsideup** [comment]
@axelfontaine awesome! Sure, I'll take a look :)

**Comment by axelfontaine** [comment]
@jmahonin Would you be interested in contributing a PR to include Apache Phoenix into our docker-compose.yml setup so that the tests can also be run by default on TravisCI? (This shouldn't be a big thing)

**Comment by jmahonin** [comment]
@axelfontaine I am, and I have some internal tooling that should make this fairly straight-forward. I'm (as per usual) swamped right now, can you ping me in a week or so if I haven't gotten to this? Thanks!
