### ISSUE TITLE
Automatically set the first schema from flyway.schemas as the current one

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#158]
_Original author: anssi.hu...@gmail.com (June 06, 2012 05:19:26)_

We are using flyway with Maven plugin to execute migrations into DB2 database. Our configuration in our pom.xml is similar to this:
&lt;profile&gt;
  &lt;id&gt;flyway-migrate&lt;/id&gt;
  &lt;build&gt;
   &lt;plugins&gt;
    &lt;plugin&gt;
      &lt;groupId&gt;com.googlecode.flyway&lt;/groupId&gt;
      &lt;artifactId&gt;flyway-maven-plugin&lt;/artifactId&gt;
      &lt;executions&gt;
        &lt;execution&gt;
          &lt;phase&gt;process-test-resources&lt;/phase&gt;
          &lt;goals&gt;
           &lt;goal&gt;migrate&lt;/goal&gt;
          &lt;/goals&gt;
        &lt;/execution&gt;
      &lt;/executions&gt;
      &lt;configuration&gt;
        &lt;driver&gt;com.ibm.db2.jcc.DB2Driver&lt;/driver&gt;
        &lt;url&gt;jdbc:db2://host:50000/testdb:currentSchema=TEST_SCHEMA&lt;/url&gt;
       &lt;user&gt;USERNAME&lt;/user&gt;
       &lt;password&gt;PASSWORD&lt;/password&gt;
       &lt;schemas&gt;TEST_SCHEMA&lt;/schemas&gt;
       &lt;table&gt;SCHEMA_VERSION_FLYWAY&lt;/table&gt;
      &lt;/configuration&gt;
    &lt;/plugin&gt;
   &lt;/plugins&gt;
&lt;/build&gt;
&lt;/profile&gt;

It seems that flyway-clean correctly uses the schema given in the flyway-plugins schemas configuration. With flyway-migrate, however, connection defaults to a schema that corresponds the username of the jdbc connection. Workaround for this is to give currentSchema attribute in the jdbc connection url or explicitly specify the schema in SQL-scripts.

**************_V1_0__base.sql**_*****************
set schema TEST_SCHEMA;
CREATE TABLE CUSTOMER;

or

CREATE TABLE TEST_SCHEMA.CUSTOMER;

---

It would be nice if the schema given in the schemas configuration would be the one used when executing migrations.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=273_

**Comment by JasperHorn** [comment]
For those working with SQL Server: you might want to use [placeholders](https://flywaydb.org/documentation/migrations#placeholder-replacement) to work around this feature not working in SQL server.
