### ISSUE TITLE
No logs printed by the Gradle plugin tasks by default

### ISSUE THREAD

**Issue by czyzby** [flyway/flyway#1584]
When running the default Flyway tasks like `flywayMigrate`, relevant task logs are not printed on the default logging level. You have to run Gradle with `-i` (info logging level), which in turn causes the console to be flooded with semi-debug information from other tasks and Gradle itself. It is a bit tedious, since there seem to be no way to change logging level at runtime. Gradle plugins tend to be more "verbose" and informative on the default (lifecycle) logging level.

I'd expect Flyway to output more logs (basically the info level ones) or allow the user to control its logging level through extension parameters.

 > Flyway version 4.1.2, running via Gradle plugin, PostgreSQL 9.6.

**Comment by axelfontaine** [comment]
Works as designed. The log levels align with the Gradle expectations for each one. If other plugins produce too much logs at info they should be fixed to output those at debug instead.

**Comment by gavenkoa** [comment]
Is it possible to add `verbose` option to `flywayMigrate` task?

`-i` produces lots of noise. I miss important information, like:

```
Successfully validated 44 migrations (execution time 00:00.040s)
Current version of schema "DB": 42
Migrating schema "DB" to version 43 - init
```

with normal run. I always want to have, otherwise I feel blind.
