### ISSUE TITLE
tablespace SFLYWAY create fails on DB2 z/OS when BP cannot be used

### ISSUE THREAD

**Issue by rvjansen** [flyway/flyway#1591]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API, Command-line

###### What database are you using (type & version)?
DB2 z/OS V11

###### What operating system are you using?
z/OS

###### What did you do?
tried to run Flyway first time. 

###### What did you expect to see?
a created metadata table

###### What did you see instead?
an access violation on BP0. At this site, BP0 is only for catalog tables, and the buffer pool I needed to use is called differently. I suggest making a parameter out of this, the default can still be BP0.

**Comment by axelfontaine** [comment]
@cteig Can you take a look at this?

**Comment by Muni10** [comment]
@rvjansen @axelfontaine Looking at this issue

**Comment by Muni10** [comment]
@axelfontaine Should I just add a generic parameter that can be used from the API and commandline, like flyway.bufferPool, should I name ut db2BufferPool or should we add it some other way? Have made the changes necessary to parameterize this, but would like your opinion on naming.

**Comment by axelfontaine** [comment]
@Muni10 Ideally I would actually like to resolve this as part of #865 

This would be a nice generic parameter applicable to a broad range of databases.

**Comment by Muni10** [comment]
@axelfontaine We would still need a separate parameter for the buffer pool setting. The problem with this is that a buffer pool on z/OS is something quite different than buffer pools we are familiar with from databases like Oracle and SQLServer, so a parameter "bufferPool" would be confusing I think.

**Comment by axelfontaine** [comment]
Closing as DB2 z/OS support has been discontinued.
