### ISSUE TITLE
Unable to resolve location on Docker Linux system (with ANT)

### ISSUE THREAD

**Issue by gintsgints** [flyway/flyway#1594]
###### What version of Flyway are you using?
4.1.1. 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
ANT tasks

###### What database are you using (type & version)?
Oracle 12c. 
https://github.com/oracle/docker-images/tree/master/OracleDatabase/dockerfiles/12.2.0.1

###### What operating system are you using?
debian:stable
https://hub.docker.com/r/frekele/ant/

###### What did you do?
Any task with flyway, location is not recognised.
Example migrate task:
[flyway:migrate] Flyway 4.1.1 by Boxfuse
[flyway:migrate] Database: jdbc:oracle:thin:@registry.online.lv__ltt__oracle-db-docker:1521:ORCLCDB (Oracle 12.2)
[flyway:migrate] Scanning for SQL callbacks ...
[flyway:migrate] Scanning for classpath resources at 'classpath:migrations/ZV_USER_42' (Prefix: '', Suffix: '.sql')
[flyway:migrate] Determining location urls for classpath:migrations/ZV_USER_42 using ClassLoader AntClassLoader[/builds/ZVAIS/main/src/main/lib/ojdbc6.jar] ...
[flyway:migrate] Unable to resolve location classpath:migrations/ZV_USER_42
[flyway:migrate] Scanning for classpath resources at 'classpath:migrations/ZV_USER_42' (Prefix: 'V', Suffix: '.sql')
[flyway:migrate] Unable to resolve location classpath:migrations/ZV_USER_42
[flyway:migrate] Scanning for classpath resources at 'classpath:migrations/ZV_USER_42' (Prefix: 'R', Suffix: '.sql')
[flyway:migrate] Unable to resolve location classpath:migrations/ZV_USER_42
[flyway:migrate] Scanning for classes at 'classpath:migrations/ZV_USER_42' (Implementing: 'org.flywaydb.core.api.migration.jdbc.JdbcMigration')
[flyway:migrate] Unable to resolve location classpath:migrations/ZV_USER_42

###### What did you expect to see?
On windows locations is resloved.

###### What did you see instead?
It's not.

**Comment by axelfontaine** [comment]
Flyway is able to scan both the classpath and filesystem just fine on Linux. This is an issue with your specific setup.

**Comment by gintsgints** [comment]
Adding filesystem: to location helped in this  case.
