### ISSUE TITLE
Flyway writes to schema_version without lock after upgrade to 4.1.2

### ISSUE THREAD

**Issue by robbertnoordzij** [flyway/flyway#1598]
###### What version of Flyway are you using?

4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

MySQL 5.7

###### What operating system are you using?

Docker on Mac (Ubuntu image)

```
RUN wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/4.1.2/flyway-commandline-4.1.2-linux-x64.tar.gz \
   && tar -xf flyway-commandline-4.1.2-linux-x64.tar.gz

ENV PATH /flyway-4.1.2/:$PATH
```

###### What did you do?

After we upgraded from version 4.1.1 to version 4.1.2 our migrations started failing. Hereby the minimum set of migrations to reproduce the exception:

```sql
-- V1__CreateTable.sql

CREATE TABLE test (
  id  VARCHAR(36)  NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
```

```sql
-- V2__CreateTrigger.sql

LOCK TABLES test WRITE;

DELIMITER //

CREATE TRIGGER test_trigger BEFORE INSERT ON test
FOR EACH ROW
BEGIN
  SET NEW.id := UUID();
END
//
```

Without the lock statement the migration would work in 4.1.2, but we want to lock to the table to prevent other systems to change data when the trigger is manipulated. E.g. we have to drop the old trigger to replace it with the new one.

Adding `UNLOCK TABLES` to the end would solve it, but than we need to change all previous migrations and it would also unlock tables that are locked by Flyway.

###### What did you expect to see?

We expected the migration to complete without exceptions, like it did in 4.1.1.

###### What did you see instead?

The trigger is created and we get the following exception: "Table 'schema_version' was not locked with LOCK TABLES".

```
$ flyway -configFile=flyway.conf migrate
Flyway 4.1.2 by Boxfuse

Database: jdbc:mysql://127.0.0.1:3306/database (MySQL 5.7)
Successfully validated 2 migrations (execution time 00:00.038s)
Current version of schema `database`: 1
Migrating schema `database` to version 2 - AddTriggerToTable
ERROR: Migration of schema `database` to version 2 - AddTriggerToTable failed! Please restore backups and roll back database and code!
ERROR: 
Unable to insert row for version '2' in metadata table `database`.`schema_version`
-----------------------------------------------------------------------------------
SQL State  : HY000
Error Code : 1100
Message    : Table 'schema_version' was not locked with LOCK TABLES
Query is : SELECT MAX(`installed_rank`) FROM `database`.`schema_version`
```

This looks like an undocumented change between the two version.

**Comment by axelfontaine** [comment]
You are correct that the locking technique used was modified. We now use `GET_LOCK` and `RELEASE_LOCK`. See https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/mysql/MySQLNamedLockTemplate.java#L59

The behavior you were relying on was purely an implementation detail as Flyway never made any claims on how it would perform the locking, only that locking is applied to support concurrent migration attempts.

To new behavior is here to stay, so the workaround you suggested is the correct way forward for your case.
