### ISSUE TITLE
Cannot drop projections in Vertica database

### ISSUE THREAD

**Issue by sethm** [flyway/flyway#1599]
###### What version of Flyway are you using?

4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

HPE Vertica 8.0

###### What operating system are you using?

CentOS 6.5, CentOS 7.2, MacOS 10.12

###### What did you do?

Created a SQL migration that runs the following code:

`DROP PROJECTION example_schema.example_projection`

###### What did you expect to see?

The projection should be dropped.

###### What did you see instead?

The migration fails because the AHM (Ancient History Mark) is out of date.

```
15:50:23.133 [db-migration] ERROR com.example.vertica.VerticaSchema - could not apply database migration: 
Migration V3_0_0__Example_Migration.sql failed
-----------------------------------------------
SQL State  : 55006
Error Code : 4470
Message    : [Vertica][VJDBC](4470) ROLLBACK: Projection cannot be dropped because history after AHM would be lost
  [Vertica][VJDBC]Detail: Current AHM epoch = 0
Location   :  [...omitted...]
Line       : 60
Statement  : DROP PROJECTION example_schema.example_projection
```

###### Notes

I think I understand what's going on here. When doing a migration, a lock is held on the Flyway metadata table in another transaction. But the Vertica Tuple Mover cannot advance the AHM Epoch until the lock is released.

Under normal circumstances, the AHM can be advanced by calling Vertica's `MAKE_AHM_NOW()` function. However, with the lock held open, this function simply blocks and does nothing, so it also cannot be used in a migration.

I honestly don't know what the right thing to do is, here. This is probably not a bug, per se, but it does mean that projections cannot be dropped in migrations.

**Comment by axelfontaine** [comment]
What may be necessary here is aligning Vertica support with PostgreSQL support as the latter now runs in single-connection mode using advisory locks. Do you want to submit a pull request?

**Comment by sethm** [comment]
I'll look at what it would take to do this, and hopefully will have a pull request for you shortly.

**Comment by MikielAgutu** [comment]
Vertica is no longer supported, so this is irrelevant. See this issue to track re-introduction of Vertica support https://github.com/flyway/flyway/issues/1855
