### ISSUE TITLE
Provide Maven-like profiles to assist in promoting migrations

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#160]
_Original author: lander...@chariotsolutions.com (July 05, 2012 15:32:23)_

I have prototyped the use of Flyway in applying migrations in a multi-level database environment using the Flyway Maven plugin for a client with a large development staff. In my consulting experience, most companies have a multi-level database environment like development, QA, staging, and production versions of databases. The only thing different in these companies is the number of levels. They all need to promote migrations from one level to the next.

In my prototype I used properties within Maven profiles to specify database-level specifics such as the JDBC driver name, database URL, database user credentials, schemas, etc., and then referenced those properties in the configuration of the plugin in the Maven POM file. Migrations are easily promoted from one level to the next by specifying the Maven profile name on the command line when running the migrations project. 

I have not used Ant for quite a long time so I am not sure if there is an equivalent profile feature that could be employed using the Flyway Ant task that would duplicate my Maven implementation. And other than using system properties, I do not know of a method to duplicate my Maven prototype using the Flyway Command Line tool. I would imagine one could use properties files for the same purpose when using Flyway Java migrations since I have not attempted it. 

Providing the capability to define migration configuration profiles within the Flyway configuration would afford the Flyway user consistency in defining the various levels of databases to which migrations of this set are to be applied regardless of the component being used whether it be the Maven plugin, the Ant task, the command line tool, or Java migrations. The migration configuration profile to be used in a particular execution could be specified in the context of the tool, e.g., a command line argument for the command line tool, a configuration argument specified via a property in either the Maven plugin or Ant task, or as an argument to the invocation of a Flyway task in a Java migration. And in all cases, maybe an &lt;activeProfile&gt; configuration parameter could be specified. 

Alternatively, Flyway could support a Rails-like database definition concept via the use of a database.config file. Although supported in the context of the entire platform, Rails provides 'profile' type support via its RAILS_ENV environment variable setting as well as the RAILS_ENV command line argument. The Rake db tasks act on the database defined in the application's database definition file (config/database.yml) for the  RAILS_ENV setting. Flyway could use a FLYWAY_ENV environment variable or command line argument or configuration parameter to communicate the database to be acted upon.  

_Original issue: http://code.google.com/p/flyway/issues/detail?id=284_

**Comment by shanekenyon87** [comment]
Meh, this is a non-solution.  What is a "flyway.properties" file?  Your docs don't mention it.  I am assuming Brian is using Maven to accomplish this.  But it should be explicit in the Flyway docs that you have to roll your own here.

In any case, as part of our Node app, our solution is to use Javascript to read from .ENV files to rewrite the .conf file before deploying.

Code below (thanks to @benvogler):

```
// This file will fill the flyway.conf file with the authentication string
// from .env and run the flyway migration. 
require('dotenv').config();
const url = require('url');
const fs = require('fs');
const proc = require('child_process');
const flyway_dir = './sql_scripts/flyway-5.0.7';
if (!process.env.DATABASE_URL) {
    console.error('Postgres URL not present, flyway will likely migrate to the wrong database');
    return;
}

function replaceVariable(file, variable, value) {
    variable += '=';
    let startIndex = file.indexOf(variable) + variable.length;
    let variableValue = file.substring(startIndex + variable.length);
    let endIndex = variableValue.indexOf('\n') + file.substring(0, startIndex + variable.length).length;
    return file.replace(file.substring(startIndex, endIndex), value);
}

const host = url.parse(process.env.DATABASE_URL).hostname;
const port = url.parse(process.env.DATABASE_URL).port;
const database = url.parse(process.env.DATABASE_URL).path.replace('/', '');
const user = url.parse(process.env.DATABASE_URL).auth.split(':')[0];
const password = url.parse(process.env.DATABASE_URL).auth.split(':')[1];

let file = fs.readFileSync(`${flyway_dir}/conf/flyway.conf`, 'utf-8');
let variables = [
    {
        value: 'flyway.user',
        replacement: user
    },
    {
        value: 'flyway.url',
        replacement: `jdbc:postgresql://${host}:${port}/${database}?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory`
    },
    {
        value: 'flyway.password',
        replacement: password
    }
];
variables.forEach(variable => file = replaceVariable(file, variable.value, variable.replacement));

fs.writeFileSync(`${flyway_dir}/conf/flyway.conf`, file);
proc.execSync(`${flyway_dir}/flyway migrate`, {stdio: [process.stdin, process.stdout, process.stderr]});
```
