### ISSUE TITLE
Location that only contains repeatable Migrations leads to ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by jbrusis** [flyway/flyway#1600]
###### What version of Flyway are you using?

4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-Line

###### What database are you using (type & version)?

Oracle 12c (12.1.0.2.0 64 Bit)

###### What operating system are you using?

Windows Server 2012 R2

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I configured a folder on the filesystem as location for the flyway migrations that only contained Repeatable Migrations (default prefix and separator: R__). The schema was created by flyway and successfully migrated before with different scripts (both versioned and repeatable) from a different location.

I then tried to run migrate via the flyway command line application with the following command from a batch-script:

`call D:\flyway-4.1.2\flyway.cmd -configFile=flyway.conf -locations=filesystem:d:\path\to\migrations\ migrate 
`
The config file also specifies a location that should be overriden with the command line parameter. url, user, password and schemas are given in the config file.

###### What did you expect to see?

The migrate command executes successfully and all repeatable migrations (none of those scripts were executed before) are being executed against the configured DB

###### What did you see instead?

An ArrayIndexOutOfBoundsException:

`Flyway 4.1.2 by Boxfuse

Database: jdbc:oracle:thin:@//xxx.xxx.xxx.xxx:1521/xxx (Oracle 12.1)
Successfully validated 159 migrations (execution time 00:00.048s)
Current version of schema "<schema>": 0.7.5
ERROR: java.lang.ArrayIndexOutOfBoundsException: -1`

**Comment by axelfontaine** [comment]
Can you also post the full stacktrace? (invoke Flyway with `-X` to get it)

**Comment by jbrusis** [comment]
Of course:

`Flyway 4.1.2 by Boxfuse

DEBUG: Java 1.8.0_74 (Oracle Corporation)
DEBUG: Windows 10 10.0 amd64

DEBUG: Loading config file: ...
DEBUG: Using configuration:
DEBUG: flyway.locations -> filesystem:C:\... <- the path to the folder containing only repeatable migrations
DEBUG: flyway.password -> ************
..
DEBUG: flyway.encoding -> Windows-1252
DEBUG: flyway.url -> jdbc:oracle:thin:@//xxx.xxx.xxx.xxx:1521/xxx
DEBUG: flyway.user -> <schema>
DEBUG: flyway.validateOnMigrate -> false
DEBUG: flyway.configFile -> flyway.conf
DEBUG: flyway.sqlMigrationSuffix -> .sql
DEBUG: flyway.jarDirs -> C:\Programme\flyway-4.1.2\jars
DEBUG: Adding location to classpath: C:\Programme\flyway-4.1.2\drivers\ojdbc7.jar
Database: jdbc:oracle:thin:@//xxx.xxx.xxx.xxx:1521/xxx (Oracle 12.1)
DEBUG: DDL Transactions Supported: false
DEBUG: Schemas: ...
DEBUG: Spring Jdbc available: false
DEBUG: Scanning for SQL callbacks ...
DEBUG: Scanning for filesystem resources at 'C:/path/to/migrations' (Prefix: 'R', Suffix: '.sql')
DEBUG: Scanning for resources in path: [...]
DEBUG: Filtering out resource: [...]
DEBUG: Found filesystem resource: [...]
Current version of schema "<schema>": 0.7.5
ERROR: Unexpected error
java.lang.ArrayIndexOutOfBoundsException: -1
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:169)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:142)
        at org.flywaydb.core.internal.dbsupport.DbSupport$1.call(DbSupport.java:224)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.dbsupport.DbSupport.lock(DbSupport.java:220)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:142)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:969)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:930)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1413)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:930)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:148)
        at org.flywaydb.commandline.Main.main(Main.java:103)`

**Comment by Arun4D** [comment]
Hi...  I am also getting same error. Do you have any workaround for this issue? or which is the stable version to use?

**Comment by jbrusis** [comment]
I think a the easiest workaround would be to simply add a versioned Dummy script that does nothing (e.g. a select 'dummy' from dual).

**Comment by axelfontaine** [comment]
I can't seem to reproduce this this. Can you post a test case or even better a pull request including a test case and a fix?

**Comment by axelfontaine** [comment]
Any news?

**Comment by geoffroya** [comment]
Got the same issue. I confirm it's linked with the fact that the locations only contains repeatable migrations.
Flyway version: 4.2.0

**Comment by axelfontaine** [comment]
Closing due to lack of response from original reporter. Please open a new issue if you still see the problem with Flyway 5.0 after it is out.

**Comment by ripasapa** [comment]
i had the same problem, hope that is fixed then
