### ISSUE TITLE
question: run "sbt flywayMigrate" in project that does not compile

### ISSUE THREAD

**Issue by felixSchl** [flyway/flyway#1604]
I am sure this question is somewhat silly, but is it possible to run the "flywayMigrate" task in a project that does not compile? I am setting up the project in a way that I maintain my migrations in raw SQL, then derive classes / traits using the slick code generator (scala). But if I nuke my generated models in order to re-generate them, it does not compile and sbt's compile task fails. So then the question is why does it even bother to compile my sources when the task has nothing to do with my sources.

###### What version of Flyway are you using?

4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

SBT

###### What database are you using (type & version)?

N/A

###### What operating system are you using?

Mac OSX

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Run "sbt flywayMigrate" in a non-compiling project

###### What did you expect to see?

Migrations should run regardless

###### What did you see instead?

Compile errors

**Comment by axelfontaine** [comment]
Please post your question on StackOverflow under the Flyway tag.
