### ISSUE TITLE
FlywayCLI - Even after adding the snowflake jars in the respective directory failing with unable to detect the driver exception

### ISSUE THREAD

**Issue by shetaksroc** [flyway/flyway#1605]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command Line

###### What database are you using (type & version)?
Snowflake

###### What operating system are you using?
Linux 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Unable to auto-detect the driver class not found exception

###### What did you expect to see?
I need to get the migration done.

###### What did you see instead?
Error

**Comment by axelfontaine** [comment]
Snowflake is not supported.

**Comment by JDFagan** [comment]
Any plans to support Snowflake in the future?
