### ISSUE TITLE
Make MigrationResolvers easier to build by moving some internal APIs to org.flywaydb.core.api

### ISSUE THREAD

**Issue by egil** [flyway/flyway#1608]
Some of the helpers methods and classes in `org.flywaydb.core.internal` are quite useful when building custom migration resolvers. It would be great if they were moved to `org.flywaydb.core.api` and if the built in resolvers were only implemented with using external APIs. Right now, the internal resolvers have a constructors that is passed objects that are likely to be useful for other external resolvers. Switching to `Aware...` injection model could be a solution.

In my case, I wanted to create a `OraclePackageMigrationResolver` that is almost identical to the internal `SqlMigrationResolver`, but only searches for ".pks" and ".pkb" files, and gives then a prefix in their description, to ensure they are applied in a correct order (all _.pks'_ first, then all _.pkb's_). Most of the code I needed is already in `SqlMigrationResolver` and other classes in the `org.flywaydb.core.api` namespace, so I choose to copy/paste as little as possible, and reference the rest.

The biggest obstacle was that the constructor in `SqlMigrationResolver` is passed a reference to objects it needs to its work. These objects I had to recreate again via the flyway configuration object.

Right now I feel a little dirty referencing internal classes and interfaces. Will it continue to work with future versions of Flyway? I guess there is no guarantee for me in this case, but the benefits are to big to not go in this direction. 

Anyway, here is my `OraclePackageMigrationResolver` class for reference:

```java
package database.resolvers;

import org.flywaydb.core.api.FlywayException;
import org.flywaydb.core.api.MigrationType;
import org.flywaydb.core.api.MigrationVersion;
import org.flywaydb.core.api.resolver.BaseMigrationResolver;
import org.flywaydb.core.api.resolver.ResolvedMigration;
import org.flywaydb.core.internal.dbsupport.DbSupport;
import org.flywaydb.core.internal.dbsupport.oracle.OracleDbSupport;
import org.flywaydb.core.internal.resolver.MigrationInfoHelper;
import org.flywaydb.core.internal.resolver.ResolvedMigrationImpl;
import org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor;
import org.flywaydb.core.internal.util.Location;
import org.flywaydb.core.internal.util.Pair;
import org.flywaydb.core.internal.util.PlaceholderReplacer;
import org.flywaydb.core.internal.util.scanner.Resource;
import org.flywaydb.core.internal.util.scanner.filesystem.FileSystemScanner;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.zip.CRC32;

public class OraclePackageMigrationResolver extends BaseMigrationResolver {
    private FileSystemScanner scanner;
    private DbSupport dbSupport;
    private PlaceholderReplacer placeholderReplacer;

    @Override
    public Collection<ResolvedMigration> resolveMigrations() {
        init();
        List<ResolvedMigration> migrations = new ArrayList<>();

        for (String locationDefinition :  flywayConfiguration.getLocations()) {
            Location location = new Location(locationDefinition);
            migrations.addAll(scanForMigrations(location, "def", ".pks"));
            migrations.addAll(scanForMigrations(location, "imp", ".pkb"));
        }

        return migrations;
    }

    private void init() {
        scanner = new FileSystemScanner();
        placeholderReplacer = new PlaceholderReplacer(
                flywayConfiguration.getPlaceholders(),
                flywayConfiguration.getPlaceholderPrefix(),
                flywayConfiguration.getPlaceholderSuffix());

        try {
            dbSupport = new OracleDbSupport(flywayConfiguration.getDataSource().getConnection());
        } catch (SQLException e) {
            throw new FlywayException("Unable to get Oracle database connection", e);
        }
    }

    private List<ResolvedMigration> scanForMigrations(Location location, String descriptionPrefix, String suffix) {
        String separator = flywayConfiguration.getSqlMigrationSeparator();
        String prefix = flywayConfiguration.getRepeatableSqlMigrationPrefix();

        List<ResolvedMigration> migrations = new ArrayList<ResolvedMigration>();

        try {
            for (Resource resource : scanner.scanForResources(location, prefix, suffix)) {
                String filename = resource.getFilename();
                Pair<MigrationVersion, String> info = MigrationInfoHelper.extractVersionAndDescription(filename, prefix, separator, suffix);

                ResolvedMigrationImpl migration = new ResolvedMigrationImpl();
                migration.setVersion(info.getLeft());
                migration.setDescription("(" + descriptionPrefix + ") " + info.getRight());
                migration.setScript(extractScriptName(resource, location));
                migration.setChecksum(calculateChecksum(resource, resource.loadAsString(flywayConfiguration.getEncoding())));
                migration.setType(MigrationType.SQL);
                migration.setPhysicalLocation(resource.getLocationOnDisk());
                migration.setExecutor(new SqlMigrationExecutor(dbSupport, resource, placeholderReplacer, flywayConfiguration));
                migrations.add(migration);
            }
        } catch (IOException e) {
            throw new FlywayException("Unable to scan for SQL migrations in location: " + location, e);
        }

        return migrations;
    }

    // Originally from flyway 4.2: org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver
    String extractScriptName(Resource resource, Location location) {
        if (location.getPath().isEmpty()) {
            return resource.getLocation();
        }

        return resource.getLocation().substring(location.getPath().length() + 1);
    }

    // Originally from flyway 4.2: org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver
    static int calculateChecksum(Resource resource, String str) {
        final CRC32 crc32 = new CRC32();

        BufferedReader bufferedReader = new BufferedReader(new StringReader(str));
        try {
            String line;
            while ((line = bufferedReader.readLine()) != null) {
                crc32.update(line.getBytes("UTF-8"));
            }
        } catch (IOException e) {
            String message = "Unable to calculate checksum";
            if (resource != null) {
                message += " for " + resource.getLocation() + " (" + resource.getLocationOnDisk() + ")";
            }
            throw new FlywayException(message, e);
        }

        return (int) crc32.getValue();
    }
}
```

**Comment by gvanderploeg** [comment]
I'm quite new to Flyway development but stumbled upon this issue by accident. But couldn't you save quite a bit of duplication by extending `SqlMigrationResolver` instead of `BaseMigrationResolver`?

**Comment by egil** [comment]
@gvanderploeg, I cant remember why I chose the BaseMigrationResolver, but pretty sure I had a reason. I might have to revisit this at some point though :)

**Comment by JanecekPetr** [comment]
Exactly this. Things like `Scanner`, `ClassUtils`, `ConfigurationInjectionUtils` etc. are just oh-so useful in implementing new migrations. Ideally they should be outside of the `internal` package. Better yet, I'd hope to ask Flyway for all migrations of type `WhateverMigration` and it would give me back everything it found, properly instantiated and configured. That'd be the bomb.

**Comment by axelfontaine** [comment]
The original case of `OraclePackageMigrationResolver` is now supported out of the box with multiple suffixes. See https://flywaydb.org/documentation/commandline/migrate#sqlMigrationSuffixes

As for exposing the internal constructs, this is harder than it sounds. The moment we expose them, we lose the ability to freely evolve them as people will then start depending on them. This would radically reduce our ability to iterate and innovate and make things a lot more complicated. When we are really certain we found the right abstraction for something we may chose to expose it. But this will take time and will be gradual as any mistake takes years to correct via long deprecation periods and compatibility adapters to ensure a smooth upgrade path across Flyway versions.

**Comment by JanecekPetr** [comment]
Makes sense, thank you for your work.

Our use-case was a Java migration that does not need a `Connection` (as it does not write to the DB - later migrations would), but rather some other references to do its work (move things around, remove excessive files, get some services into their new desired state etc.).

It's just that writing new kinds of Java migrations either requires nasty hacks, or our own classpath scanner, and I'm not even talking about getting DI working. Perhaps we'll go the other way and build a flyway plugin.

**Comment by axelfontaine** [comment]
@JanecekPetr Could you describe your requirements in detail in a new issue? (Or even post source code like @egil did) This would allow us to better understand your scenario and evaluate possibilities to make this easier in the future. Maybe there is a solutions (like for @egil's `OraclePackageMigrationResolver`) that we can provide that doesn't rely on exposing too many internals.

**Comment by arlowhite** [comment]
Flyway does not allow files to have the same description, so `R__foo.pks` and `R__foo.pkb` is not allowed. Renaming them to `R__foo_header.pks` and `R__foo_body.pkb` and with `flyway.sqlMigrationSuffixes=.sql,.pks,.pkb`, bodies are compiled before headers because Flyway just alpha sorts instead of doing all .pks files and then all .pkb files.

So you need to name them so that alphasort puts the pks above the pkb :-1:
