### ISSUE TITLE
Bug in migration order (R script before V script)

### ISSUE THREAD

**Issue by RobBrown500** [flyway/flyway#1609]
###### What version of Flyway are you using?
4.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven

###### What database are you using (type & version)?
SQL Server 2014 R2

###### What operating system are you using?
Windows Server 2012

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
1) Created V scripts and R scripts.
2) Ran migration (worked fine, created DB from scratch)
3) Created new V script
4) Altered single (already existing) R script
5) Ran migration - failed

###### What did you expect to see?
The V script to run before the R script.  This was necessary for the R script to run successfully.

###### What did you see instead?
The R script tried to run before the V script.
By commenting out the code in the R script, I was able to confirm that this did run before the V script.
![r_before_v migration_example](https://cloud.githubusercontent.com/assets/27815722/25233014/40fc9fee-25d5-11e7-8ac6-a70949e5ceb3.PNG)

**Comment by axelfontaine** [comment]
I am afraid I can't reproduce this. Can you try again with the latest version and see if the problem persists?

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
