### ISSUE TITLE
 Change the name of the default constraint

### ISSUE THREAD

**Issue by afraxas** [flyway/flyway#1614]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

Sql Server 2005

###### What operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
      ...
        Flyway flyway = new Flyway();
        flyway.setDataSource(dataSource);
        flyway.baseline();
       ..
###### What did you expect to see?

![image](https://cloud.githubusercontent.com/assets/3926044/25460094/b1a8f016-2b1c-11e7-92ec-ae6e23fe8db9.png)

###### What did you see instead?
![image](https://cloud.githubusercontent.com/assets/3926044/25460060/8e6d470a-2b1c-11e7-8410-14071e8e21e8.png)

**Comment by axelfontaine** [comment]
This is an internal implementation detail. Works as designed.
