### ISSUE TITLE
Flyway logs passwords at INFO level

### ISSUE THREAD

**Issue by chrylis** [flyway/flyway#1620]
I am using Flyway 3.2.1 with the latest release of Spring Boot, but this behavior appears to still be present in the current master.

I was rather surprised to see, on startup, that the username and password for my JDBC connection were printed to the console at INFO level:

```
INFO 7 --- [           main] o.f.c.i.dbsupport.DbSupportFactory       : Database: jdbc:postgresql://host/db?user=admin&password=<password> (PostgreSQL 9.5)
```

This is apparently automatic behavior, invoked automatically once per `Flyway` instance (the private field `dbConnectionInfoPrinted` is used solely to make this happen once), and is not configurable in any way.

I would suggest at a minimum custom-printing diagnostic information rather than dumping the entire connection string.

**Comment by axelfontaine** [comment]
Flyway logs the _connection url_. If you don't include the password in the url, but use the password property of your datasource it will not appear.

Works as designed.

**Comment by chrylis** [comment]
The connection string is what is injected by most cloud systems, and logging it _at INFO_, which is the default output level for most loggers, is something that is surprising behavior. Since it's on by default (and actually not suppressable), it ought to require some overt action, such as setting logs to DEBUG.

**Comment by axelfontaine** [comment]
Which cloud system did you see this on?

**Comment by pvillega** [comment]
This happens when using Heroku too. Logs show the full url with password.

Mind you, I'm using `flyway.setDataSource(config.url, config.user, config.password)` to set the configuration, so this is shown after building the full url.

Please default it to debug/trace level. This is unsafe.

**Comment by axelfontaine** [comment]
OK, so far this only seems to affect Heroku then.

**Comment by pvillega** [comment]
Is it thought? I wonder as I specifically use:

`flyway.setDataSource(config.url, config.user, config.password)`

which is not Heroku specific as far as I know...
