### ISSUE TITLE
Flyway command-line not prompting for password

### ISSUE THREAD

**Issue by marktucks** [flyway/flyway#1622]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

Postgres (PostgreSQL) 9.4.10

###### What operating system are you using?

Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

flyway -user=myuser -url=jdbc:postgresql://localhost:5432/mydb validate

Config file:

&#35; Password to use to connect to the database. Flyway will prompt you to enter it if not specified.
&#35;flyway.password=

###### What did you expect to see?

A prompt for the database password.

###### What did you see instead?

```
Flyway 4.2.0 by Boxfuse

ERROR:
Unable to obtain Jdbc connection from DataSource (jdbc:postgresql://localhost:5432/mydb) for user 'myuser': The server requested password-based authentication, but no password was provided.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08004
Error Code : 0
Message    : The server requested password-based authentication, but no password was provided.
```

**Comment by axelfontaine** [comment]
Right now it's all or nothing. Either you don't supply a user and you don't supply a password and you get a prompt. As soon as you supply either the prompt is disabled.

**Comment by axelfontaine** [comment]
I can't reproduce this. Please check with Flyway 5.0.x if the issue persists for you.
