### ISSUE TITLE
Not able to run "drop materialized view if exist" sql in another schema, if public schema has a table with same name as materialized view

### ISSUE THREAD

**Issue by sreekanthsnair** [flyway/flyway#1623]
###### What version of Flyway are you using?

4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

Postgres 9.4

###### What operating system are you using?

Redhat Linux 6.5

###### What did you do?
try to run migration on two schema one by one, one to **public** and one is to another schema let say **schema-two**, In both of these same set of sql.
eg: following pseudo migration script.
1) create materialized view X
2) drop materialized view if exists X
3) create table X

executed successfully in public schema

trying to execute the same set of migration script in schema **schema-two**
2nd script failed to migrate, its say X is not a materialized view.

###### What did you expect to see?
It should migrate both schema with out any error

###### What did you see instead?
Migration failed due to SQL State : 42809

**Comment by axelfontaine** [comment]
Please provide a small test case that reproduces this.

**Comment by axelfontaine** [comment]
Any news?

**Comment by sreekanthsnair** [comment]
Really sorry @axelfontaine, was fully busy with my regular work and other stuffs. Will try to create test asap and let you know. Thank you

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by sreekanthsnair** [comment]
@axelfontaine Sorry for it, caught up with other priority. Will file issue later once i'm ready with test case
