### ISSUE TITLE
Multiple configuration files

### ISSUE THREAD

**Issue by jappievw** [flyway/flyway#1624]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
MySQL 5.7 and Aurora

###### What operating system are you using?
macOS and Amazon Linux

###### What did you do?
Run `flyway -configFile=secrets.conf -configFile=application.conf migrate`

The `secrets.conf` file contains the database credentials including some placeholders which have to be kept safe. It is generated by our CI solution and only available when flyway runs. The `application.conf` contains the lookup paths for the migrations and some placeholders. It is included in the repository and maintained by our developers.

###### What did you expect to see?
A merge of the two configuration files where the last one takes precedence over the first one.

###### What did you see instead?
I had to provide the database credentials when running flyway.

**Comment by nycjay** [comment]
+1 for this feature. Or the ability to specify placeholders in a separate file
`flyway -configFile=myconfiguration.conf -placeholderFile=placeholdersForThisRelease.conf migrate`

Our configuration file is pretty static - connection information, schema, basic setting, etc. Our placeholders may vary from release to release, and a given placeholder may on my applicable for a single release. Separating them into multiple folders will make it easier to manage.

**Comment by axelfontaine** [comment]
This has now been implemented using a new `-configFiles=...` argument.

**Comment by Roemer** [comment]
Was the original `-configFile` removed entirely from Flyway? If so, in which version? (can't find it in `Incompatible Changes` in the changelog)
