### ISSUE TITLE
Appengine & ClassPathScanner : throw AccessControlException since 4.1.0

### ISSUE THREAD

**Issue by Ctrl-X** [flyway/flyway#1627]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
- Flyway Java API 
- Maven dependencies
- Appengine (latest SDK, 1.9.51) Standard Environment (JAVA 7) . 

###### What database are you using (type & version)?
MySql 5.6.23

###### What operating system are you using?
Mac OSX El Capitan

###### What did you do?
Only append in the Development environment (as appengine libs are in a different classpath on Google Appengine server)

Basic configuration of flyway: 
- appengine Java helloworld project
- resources/db/migration/V1_init.sql
- fresh & clean database (only one table)
- Add java Flyway migration in a simple servlet:
```
  Flyway flyway = new Flyway();
  flyway.setDataSource(url,user,password);
  flyway.migrate();
```

- Result : Throw an exception : 

> org.flywaydb.core.api.FlywayException: Unable to scan for SQL migrations in location: classpath:db/migration

I've hunted the bug down to the location where it occurs : 
In fact, when the [ClassPathScanner](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/ClassPathScanner.java) try to `findResourceNames`, it hits the appengine sdk jar (in my case 'appengine-agentruntime.jar') that triggers a : 
java.security.AccessControlException: access denied ("java.io.FilePermission" "/Users/CtrlX/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/impl/agent/appengine-agentruntime.jar" "read")

Basically, after some research, appengine disallow that type of action (opening appengine jar at runtime) and so it raise that FilePermission exception.

This is due to this [commit](https://github.com/flyway/flyway/commit/0baf57e73beb694e9c34e54ad377aa155c27a392) that change the logic of method `findResourceNames` by adding: 
```
    ...
    try {
       jarFile = new JarFile(url.toURI().getSchemeSpecificPart());
    } catch (URISyntaxException ex) {
       // Fallback for URLs that are not valid URIs (should hardly ever happen).
        jarFile = new JarFile(url.getPath().substring("file:".length()));
    }
    ...
```

It doesn't catch the AccessControlException, and the exception bubble up to [Scanner.scanForResources](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/Scanner.java), eventually transformed into a FlywayException.

For those how have the same issue : 
The bug appear in the release 4.1.0, so as a work around, you can use a previous version of flyway (like 4.0.3)

###### What did you expect to see?
Jar that trigger FilePermission exceptions should be ignored or just warned.

###### What did you see instead?
FlywayException encapsulating an AccessControlException

**Comment by axelfontaine** [comment]
Thanks for the detailed investigation!
