### ISSUE TITLE
Implementing MigrationInfoProvider.getDescription() returning String longer than 200 characters

### ISSUE THREAD

**Issue by gscht** [flyway/flyway#1633]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
MS SQL Server 2014

###### What operating system are you using?
Windows 8.1

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I created a JDBC migration implementing `MigrationInfoProvider`. The `String getDescription()` returns a String longer than 200 characters. When the migration gets applied, it works fine. The description gets abbreviated so it would fit into the metadata table.

But every subsequent call to migrate() throws an exception saying "Validate failed: Migration description mismatch for migration"

###### What did you expect to see?
A JDBC migration with a description longer than 200 characters should not fail after it gets applied successfully.

###### What did you see instead?
Validate failed: Migration description mismatch for migration

**Comment by axelfontaine** [comment]
This has now been fixed. Validate now compares against the abbreviated version as well.
