### ISSUE TITLE
No executable permission on mvnw

### ISSUE THREAD

**Issue by saadshakil** [flyway/flyway#1639]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
command-line

###### What operating system are you using?
Linux

###### What did you do?
Tried to run `mvnw`

###### What did you expect to see?
To see `mvnw` execute successfully out of the box, instead of running it with `sh`, `bash`, or setting executable permission manually.  It appears that this [resolved using `sh` in Flyway scripts](https://github.com/flyway/flyway/commit/edcbceaae8215ab929036159e62d3c0c96d41e94), but any other use of this specific `mvnw` out of the box is broken.

###### What did you see instead?
`bash: ./mvnw: Permission denied`

**Comment by axelfontaine** [comment]
This has now been fixed.
