### ISSUE TITLE
migration locations scanning under WebSphere 

### ISSUE THREAD

**Issue by sbespalov** [flyway/flyway#1640]
###### What version of Flyway are you using?

4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

DB2

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Hi guys. I am using Flyway under WAS 7.x and was very surprised when discovered [this](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/ClassPathScanner.java#L258) feature with `flyway.location`. 
Is it documented any where?

###### What did you expect to see?

Any googlable information about why Flyway can't find migrations under WAS.

###### What did you see instead?

Spend about 3 hours trying to resolve issue with `Scanner` under WAS.

**Comment by axelfontaine** [comment]
Didn't you get the warning in your logs?

**Comment by sbespalov** [comment]
> Didn't you get the warning in your logs?

Yes, that's how I found it. Accidentally noticed this warning in the logs, after 3 hours of pain :)
It seems to me that this should be an Exception and not just a Warning. Because of this issue, migrations simply do not work under WAS, so this is real Error.

**Comment by FrankMeissnerArena** [comment]
Same here. Seems like classpath-based migrations are impossible at the moment when using Websphere.

**Comment by axelfontaine** [comment]
@FrankMeissnerArena Not true. See the note about `flyway.location`

**Comment by axelfontaine** [comment]
@sbespalov If you have a way to achieve this without this file, I'd be open to accept a pull request.

**Comment by FrankMeissnerArena** [comment]
Ok, my bad -- the found location (without flyway.location) is used further on and migration finally gets to class-processing further on.
