### ISSUE TITLE
Java error when running flyway from bash shell of Git for Windows

### ISSUE THREAD

**Issue by tiborbaksa** [flyway/flyway#1642]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

N/A (Irrelevant)

###### What operating system are you using?

Windows 10 + Git for Windows environment from [git-scm.com](https://git-scm.com/)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Executed `./flyway` in a bash shell.

###### What did you expect to see?

I expected to see the usage information.

###### What did you see instead?

I got the following error:
```
Error: Could not find or load main class org.flywaydb.commandline.Main
```

**Comment by axelfontaine** [comment]
Thanks for reporting and submitting the pull request. Merged.

**Comment by abhijitparkhi1983** [comment]
Has this issue been fixed ? 
I get the exact same error in the same environment with the same flyway version mentioned above.
Its kind of blocker for me.

@axelfontaine @tiborbaksa  can you please let me know if there was any fix for this issue or any workaround

**Comment by axelfontaine** [comment]
@abhijitparkhi1983 It was fixed as you can see. Update to the latest version and everything will work as expected.
