### ISSUE TITLE
Was looking for having a separate migration jar

### ISSUE THREAD

**Issue by abdulrahmank** [flyway/flyway#1644]
We use flyway migration along with spring boot and Gradle.

I wanted to have separate jar for migration. As It was required to run migrations manually without being run automatically on app startup and without installing any tool.

The reason being multiple web servers pointing to same database may cause race condition when running migrations. 

I came across this FAQ, [PARALLEL](https://flywaydb.org/documentation/faq.html#parallel) , can I get bit more details, so that I can live with running the migrations on app startup.

**Comment by axelfontaine** [comment]
Please post such questions on StackOverflow under the Flyway tag
