### ISSUE TITLE
Flyway does not log "select" statements

### ISSUE THREAD

**Issue by umapathy08** [flyway/flyway#1645]
###### What version of Flyway are you using?

4.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Flyway Commandline

###### What database are you using (type & version)?

Oracle 11g

###### What operating system are you using?

RHEL5.x

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

In Debug mode, Flyway returns update count for insert/delete/update statements. But it does not log the output of "select" statements. 

DEBUG: Scanning for resources in path: sql (sql)
DEBUG: Filtering out resource: sql/Vx_x_x__sample.inc (filename: Vx_x_x__sample.inc)
Current version of schema "test": 1.8.3
DEBUG: Found statement at line 1: select count(*) from sample
Migrating schema "test" to version 1.8.4 - sample.inc
DEBUG: Executing SQL: select count(*) from sample
DEBUG: Successfully completed migration of schema "test" to version 1.8.4 - sample.inc
DEBUG: MetaData table "test"."schema_version" successfully updated to reflect changes
DEBUG: Locking table "test"."schema_version"...
DEBUG: Lock acquired for table "test"."schema_version"
Successfully applied 1 migration to schema "test" (execution time 00:00.859s).
+ /tmp/flyway-4.1.1/flyway -configFile=flyway/flyway_test.conf info
Flyway 4.1.1 by Boxfuse

###### What did you expect to see?

I was expecting to see the output of the below sql in the logs.

DEBUG: Executing SQL: select count(*) from sample

###### What did you see instead?

I could not see anything in the logs for "select" statements. But flyway logs for insert/update/delete statements in debug mode.

**Comment by axelfontaine** [comment]
Please explain what your use case for this would be.

**Comment by umapathy08** [comment]
Thank you for acknowledging the request. The use case is as below:

1. Development team executes the sequence of sql/prc files in database.
2. At the end of every sql file, team has a validation script to verify whether all the sqls executed properly. 
For eg: if the sql script contains the script to insert 10 rows, at the end of sql, there will be select count(*) with where clause to find whether those rows are inserted.
3. Example query is given below.
select * from sample where user_id='uma';

**Comment by axelfontaine** [comment]
Thanks for clarifications. We won't be implementing this. You can however create and invoke a stored procedure that fails if the self-test doesn't succeed. This should work seamlessly with Flyway as is.

**Comment by umapathy08** [comment]
Thank you again. Just curious to know, was there a security reason for not printing execution results of "select" statements in logs in any log level?

**Comment by axelfontaine** [comment]
It's hardly ever needed in an automated CD process.
