### ISSUE TITLE
Command-line: Improve support for SQL Server integrated security

### ISSUE THREAD

**Issue by Komurugesan** [flyway/flyway#1646]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

command-line

###### What database are you using (type & version)?
Sqlserver 2014

###### What operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I am trying to using flyway. I am not able to connect to the database

In the flyway config file
flyway.url= jdbc:jtds:sqlserver://localhost:1434/databaseName=xxxxxxxxx;integratedSecurity=true;

In the command prompt

I typed as flyway baseline and also tried with flyway info

Prompt for Database user: Pressed enter key ( Because In the url I gave "integratedSecurity=true", so flyway will connect with SQL server using  windows authentication)
Prompt for Database password : Pressed enter key

###### What did you expect to see?
Successful connection to the SQL server and baseline the database

###### What did you see instead?

SQL State : 28000
Error Code : 18456
Message : Login failed for user Mydomainname\MyLoginName

**Comment by Sarado** [comment]
Same problem here!! Any suggestions?

**Comment by reitzmichnicht** [comment]
Did you provide the native sql server libraries for integrated security to the cli?

**Comment by junkmanuk** [comment]
Download and unpack this:
https://www.microsoft.com/en-us/download/details.aspx?id=54629

Create new folder in flyway directory e.g. c:\flyway-4.x.x\native
Copy sqljdbc_auth.dll appropriate for your JVM build into this folder
Copy the sqljdbc4.jar into c:\flyway-4.x.x\drivers folder (if necessary)

Change the flyway URL removing jdts:
flyway.url=jdbc:sqlserver://localhost:1433;database=xxxxxxxxx;integratedSecurity=true;

Change the flyway.cmd to set up the library path to the directory where you copied the DLL:
%JAVA_CMD%  -Djava.library.path="%INSTALLDIR%\native" ...

See here for more info:
https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url

**Comment by esauser** [comment]
@axelfontaine what is changing for this in `6.0.0`?  It works as-is with that download.

**Comment by juliahayward** [comment]
I've followed the documentation through and it appears to be sufficient to make the commandline work. Can we close this now, or are there other issues?

**Comment by MikielAgutu** [comment]
@juliahayward Ideally Flyway should perform the necessary setup so it works out of the box.

**Comment by richardrflores** [comment]
It looks like the work-around provided by @junkmanuk may work. Can someone elaborate on how to change the flyway.cmd as he describes above ^^^?

I've tried setting integrated security to false and used a user name password in the plug-in config and I still get a login failure. I'm curious if it's the result of the same issue.

**Comment by junkmanuk** [comment]
> Can someone elaborate on how to change the flyway.cmd as he describes above ^^^?

Just edit it with a text editor, it's a batch file

**Comment by MikielAgutu** [comment]
Note that a workaround is documented https://flywaydb.org/documentation/database/sqlserver#windows-authentication

**Comment by MikielAgutu** [comment]
As on 6.2.4 flyway no longer prompts for username/password when adding integratedSecurity to the url. See https://github.com/flyway/flyway/issues/2679

Add the dll needed to support it will be done as part of a separate issue. See https://github.com/flyway/flyway/issues/2694
