### ISSUE TITLE
Migration with version prior to baseline version accepted without warning

### ISSUE THREAD

**Issue by vavallo** [flyway/flyway#1648]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line client.

###### What database are you using (type & version)?

Oracle 12c.

###### What operating system are you using?

Linux (ubuntu 16.04)

###### What did you do?

Created a migration with version prior to baseline version by mistake.
Applied the migration.

Some information for replicating the issue:
-----------------------------------------------------------
Baseline version:  1
Migration version: 0.0.3
Migration file: V0.0.3__MIGRACAO_0.0.3.sql
Last Migration Version:  1.2.73 

Result from execution:
--------------------------------
Database: jdbc:oracle:thin:@aaa.bbbb.xxx.br:1529:NAME (Oracle 12.1)
Successfully validated 999 migrations (execution time 00:00.166s)
Current version of schema "xxx_xxxxx": 1.2.73
Schema "xxx_xxxxx" is up to date. No migration necessary.
Flyway 4.1.2 by Boxfuse

Extract from info command:
----------------------------------------
Database: jdbc:oracle:thin:@aaa.bbbb.xxx.br:1529:NAME (Oracle 12.1)

+----------+-----------------------------------+---------------------+---------+
| Version | Description                        | Installed on       | State  |
+----------+-----------------------------------+---------------------+---------+
 | 0.0.3    | MIGRACAO 0.0.3             |                          | <Baseln |           <<<=== Inserted 
 | 1          | << Flyway Baseline >>     | 2017-03-22 11:06:37 | Baselin |
 | 1.2.73  | MIGRACAO 1.2.73           | 2017-04-11 11:36:17 | Success |

###### What did you expect to see?

A Warning/Error about trying to apply a migration that "pre-dates" the baseline.
SCHEMA_VERSION table data remaining the same.

###### What did you see instead?

Normal ending without warning:
-->"Schema "xxx_xxxxx" is up to date. No migration necessary."

SCHEMA_VERSION table was updated and the incorrect version was inserted before baseline.

**Comment by axelfontaine** [comment]
This migration was NOT applied. The info command simply reports it as it was found on the filesystem. This is a normal case as this migration can for example be valid in a DEV environment, but should ignored in the PROD environment. 

Works as designed.
