### ISSUE TITLE
SET ROLE not respected in callbacks or initSqls

### ISSUE THREAD

**Issue by justinsteffy** [flyway/flyway#1657]
###### What version of Flyway are you using?

4.1.2 or later

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

cli and Java

###### What database are you using (type & version)?

PG 9.6.2

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I have a `beforeMigrate.sql` that looks like this:

```sql
SET ROLE migration_user;
```

And then many regular migrations which need to be run as the user `migration_user`.

###### What did you expect to see?

I expect to see the entire migration session run as user `migration_user`, so that this role owns all of the created objects.

###### What did you see instead?

In fixing #1537, this [`RESET ROLE`](https://github.com/flyway/flyway/commit/cfd15b8c6f589fef149333725485a365690bc02e#diff-082a3414ab12680389b61424a632705cR90) was added, which undoes the callback and any `initSqls` which use `SET ROLE`. I think this is unexpected.

**Comment by axelfontaine** [comment]
Place it in `beforeEachMigrate.sql` instead and it should work as expected.

**Comment by ppiastucki** [comment]
beforeEachMigrate.sql does not seem to be executed before schema_version creation. How can I ensure schema_version is created by the given user?
