### ISSUE TITLE
Flyway command line cannot handle special character in password param

### ISSUE THREAD

**Issue by Frantch** [flyway/flyway#1658]
I have a redshift password that contains ( and # and * when using the command line -password param flyway says the credentials are wrong.

when i put the same password in the flyway.password conf it works

**Comment by axelfontaine** [comment]
Make sure to quote the argument in your shell.

**Comment by Frantch** [comment]
have tried this but this does not fix the issue

**Comment by Frantch** [comment]
@axelfontaine please reopen

**Comment by axelfontaine** [comment]
Please share  the exact command-line triggering this as well as the OS you are using. And please use the template for filing issues in the future.
