### ISSUE TITLE
Special characters (diacritics) are not correctly inserted in table

### ISSUE THREAD

**Issue by nibosoft** [flyway/flyway#1659]
###### What version of Flyway are you using?
I am using Flyway version 4.2.0.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
I am using Java API.

###### What database are you using (type & version)?
I am using mysql Server version: 5.6.12 MySQL Community Server (GPL).

###### What operating system are you using?
Windows 7 Enterprise

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I have a .sql file, V3__insert_person.sql, with one insert statement:
INSERT INTO person (id, firstName, lastName) VALUES (1, 'Ă ă Â â Î î Ș ș Ț ț','Ă ă Â â Î î Ș ș Ț ț');
The problem is that after running migration, inserted values are:
id: 1
firstName: ? ? Â â Î î ? ? ? ?
lastName:  ? ? Â â Î î ? ? ? ?

###### What did you expect to see?
I was expecting to see:
id: 1
firstName: Ă ă Â â Î î Ș ș Ț ț
lastName:  Ă ă Â â Î î Ș ș Ț ț

###### What did you see instead?
The problem is that I am unable to insert into table special characters like Ă ă Ș ș Ț ț  using flyway. Flyway inserts correctly only Â â Î î characters from my list. When I run the query on MySQL Workbench, all the characters are correctly inserted.
The code I used is here: [https://github.com/nibosoft/flywaytest](url)
I also checked this issue: [https://github.com/flyway/flyway/issues/814](url) . I created sql files with UTF-8 encoding, and not ANSI. But it didn't work.
What should I do?

**Comment by axelfontaine** [comment]
This is due to inconsistent encoding somewhere on your end (DB, table, driver, Flyway, ...).

**Comment by nkbysani** [comment]
Hi ,

We are also facing the same issue  as mentioned below, can you please suggest .

Script :

CREATE TABLE TEST 
(Name NVarchar(100))

Go

INSERT INTO TEST
SELECT N'Test – Test'

And after script executed through flyway and when we see the data is being like below.

Result :
Test � Test

Please help
