### ISSUE TITLE
setIgnoreRepeatableMigrations is missing

### ISSUE THREAD

**Issue by reitzmichnicht** [flyway/flyway#1662]
###### What version of Flyway are you using?
4.2.0

###### What did you do?
Calling validate() throws an exception if a repeatable script has changed.

###### What did you expect to see?
My setting is to clean the database on validation errors, but for repeatable migrations that would not be necessary as they can be repeated. So another option like setIgnoreRepeatableMigrations would be necessary.

###### What did you see instead?
FlywayException

**Comment by reitzmichnicht** [comment]
Perhaps it makes sense to introduce a separate ValidationConfiguration object to cleanup the FlyWay setters.

**Comment by rmamillapalli** [comment]
Our use case is bit different but the similar error: 
We are using "Validate" for inspection step in Team city and it is failing with error: **"ERROR: Validate failed: Detected outdated resolved repeatable migration that should be re-applied to database"** 
this is happening as the Repeatable migration was changed. 
where as Migrate step runs with no issues and executes the changed Repeatable script. 
impact is that we cannot do Validate as inspection step in the CI/CD.
currently using Flyway Community Edition 5.0.7 by Boxfuse.

**Comment by MikielAgutu** [comment]
Flyway encourages a workflow where your migrations (repeatable and versioned) should match what has been applied to your database. The intention of the validate command is to ensure this is the case. @rmamillapalli @reitzmichnicht can you explain more why you need this? Why not just ensure your migrations match what has been applied by running migrate first?

**Comment by MikielAgutu** [comment]
@rmamillapalli @reitzmichnicht Any news?

**Comment by reitzmichnicht** [comment]
Here is a description of our use case:
In repeatable migrations we have normally statements like:
 create view of not exists
Vacuum db

During development the repeatable and non repeatable migrations change. This means every change to a migration let's the validation fail and as a consequence we clean the database and start from zero with migrations. This would not be needed for repeatable migrations, as they do not change the data structure.

Kind regards
Michael

**Comment by MikielAgutu** [comment]
Thanks for providing more information. So it looks like you'd like to conditionally migrate based on certain validation failures.

I think introducing machine readable output to the CLI (or improving the objects we return from the API) would be a good fit for this. It means you can write the rules of your validation manually based on what Flyway produces.

Does that sound good? Note this is slated for V7, so it'll be a while before we introduce this.

**Comment by reitzmichnicht** [comment]
We do not use the cli, only the java api. But indeed maybe it would be helpful if the validate command would return which migrations fail the validation. Then it could be custom logic how to proceed

**Comment by MikielAgutu** [comment]
In Flyway 7 we've improved the validate API to produce more information. Could you try it and see if it helps?

**Comment by MikielAgutu** [comment]
@reitzmichnicht Any news?

**Comment by reitzmichnicht** [comment]
Will check this when spring boot has updated flyway to version 7

**Comment by DoodleBobBuffPants** [comment]
@reitzmichnicht Any news?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
