### ISSUE TITLE
Ignore common SQL*Plus commands

### ISSUE THREAD

**Issue by edwagner** [flyway/flyway#1671]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Oracle

###### What did you do?
`flyway migrate` using scripts that are also meant to run through SQL*Plus.

###### What did you expect to see?
Flyway process the script without error.

###### What did you see instead?
Flyway passed some of the SQL*Plus commands on to the database which caused an exception.

I realize that it is documented that flyway doesn't honor SQL\*Plus commands, but it would be nice if Flyway didn't blow up when it encounters them. Flyway ignores `set define off;` but not other common SQL\*Plus commands.

**Comment by umapathy08** [comment]
similar case for set serveroutput on, show errors, etc.

**Comment by axelfontaine** [comment]
Duplicate of #1845
