### ISSUE TITLE
SQL Server USE statements within migration cause Flyway to fail

### ISSUE THREAD

**Issue by mahidbdw** [flyway/flyway#1676]
###### What version of Flyway are you using?
4.2.0 (flyway-commandline-4.2.0-windows-x64.zip)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
SQL server 2012 (express edition)

###### What operating system are you using?
Windows 7 professional SP1

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
My scripts were running with flyway 4.0 command-line without issue.
Then I use flywayclean. And dropped DB. Created new DB. And then used flyway 4.2.0 with migrate. 
But the same scripts failing when I am using 4.2.0 version even though there are no rows in that table.

###### What did you expect to see?
Should not raise Violation of PRIMARY KEY error, when there are no rows in that table.

###### What did you see instead?
SQL State  : 23000
Error Code : 2627
Message    : Violation of PRIMARY KEY constraint 'property_PRIMARY_property'. Cannot insert duplicate key in object 'dbo.property'.

**Comment by axelfontaine** [comment]
Please provide the smallest possible SQL file that reproduces the issue.

**Comment by mahidbdw** [comment]
[pk_issue.zip](https://github.com/flyway/flyway/files/1089421/pk_issue.zip)
Plz note: This is sample script, just to reproduce the issue.

1st file uses: 2 databases, it just creates tables. No insert.
2nd file: has only 1 insert.
And this PK error is occuring on 2nd file.
It works fine with 4.0.
But getting error with 4.2.0.

Do let me know.

**Comment by mahidbdw** [comment]
Any update on this.
It would be helpful if you can update on this.

**Comment by axelfontaine** [comment]
We haven't had time to look into this and nobody else seems to be having the issue so far. You are of course welcome subscribe to one of our support plans and we would be happy to investigate immediately or alternatively you could roll up your sleeves and crack open the debugger to find out what is going on.

**Comment by rogatec** [comment]
I've run into this error also today.

I "fixed" this problem temporarily by:
1. removing the table with the primary key violation from the database.
2. then I created a script file which includes schema and data.
3. migrated with flyway without any errors.

**Comment by axelfontaine** [comment]
This is now fixed. Flyway now properly deals with migration scripts changing the current database.
