### ISSUE TITLE
Upgrading to 4.2.0 from 4.1.1 and java migrations are not being picked up

### ISSUE THREAD

**Issue by manojlds** [flyway/flyway#1679]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

Postgres and H2

###### What operating system are you using?

Ubuntu and Mac OS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Upgraded from 4.1.1 to 4.2.0

###### What did you expect to see?

Migrations with sql and java migrations to be picked up

###### What did you see instead?

Only sql migrations were picked up and the java migrations were not found.

**Comment by axelfontaine** [comment]
It works on our end, so this must be specific to your jar file/classpath setup. Can you share a small test case that reproduces the issue?

**Comment by manojlds** [comment]
Ok, will try to get that. For sure though, 4.1.1 works as is and 4.2.0 doesn't.

**Comment by axelfontaine** [comment]
Closing due to lack of response.
