### ISSUE TITLE
outOfOrder default is actually true, contrary to documentation

### ISSUE THREAD

**Issue by codingthat** [flyway/flyway#1680]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

CLI

###### What database are you using (type & version)?

PostgreSQL 9.4

###### What operating system are you using?

Linux Mint 18, 64-bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I ran `flyway migrate` with the `outOfOrder` line left commented (and not defined anywhere else).

###### What did you expect to see?

I expected something like `ERROR: Validate failed: Detected resolved migration not applied to database:...`

###### What did you see instead?

`WARNING: outOfOrder mode is active. ...`

###### more notes

This is the exact behaviour you get if you put `flyway.outOfOrder=true`.

The only way I get the expected behaviour is by explicitly defining `flyway.outOfOrder=false`.

This is unexpected given the comment just above it in the stock config, which claims: `# Allows migrations to be run "out of order" (default: false).`

**Comment by axelfontaine** [comment]
No it's not: https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L265

Please provide exact steps on how to reproduce with a fresh install on a fresh machine.

**Comment by codingthat** [comment]
Interesting...

I've attempted to reproduce it with a fresh install, and I don't seem to be able to.  The config was like this:

```
flyway.url=jdbc:postgresql://...
flyway.user=...
flyway.password=...
flyway.schemas=...
flyway.locations=filesystem:../project/sql
# flyway.outOfOrder=true
flyway.group=true
flyway.installedBy=me
```

Unfortunately the server this happened on was a production instance so I can't test it out on that.  My local PostgreSQL is 9.5.7 but in the original case the production instance was 9.4.7.

Originally too I believe there was first a duplicate version in play, but then the duplicate was renamed, and it was at this point that we hit the error.  But even trying that scenario I'm not able to reproduce it.
