### ISSUE TITLE
Command-line - Linux platform version works on windows platform

### ISSUE THREAD

**Issue by joneyhsiao** [flyway/flyway#1684]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

###### What operating system are you using?
windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I typed command "flyway migrate" sqls by using flyway-commandline-4.2.0-linux-x64 on windows platform.

###### What did you expect to see?
Some erorrs should be prompted, like "wrong platform".

###### What did you see instead?
Seems Linux platform version works on windows platform. Could anyone confirm this? Thanks in advance.

**Comment by axelfontaine** [comment]
Each download ships with both a `flyway` (Linux and macOS) and `flyway.cmd` (Windows) launch script. Only the bundled JVM is different. However the startup scripts do fall back to a system JVM if available. 

Works as designed.
