### ISSUE TITLE
Adding a comment to a migration file changes the checksum, forcing a rerun of the migration scripts

### ISSUE THREAD

**Issue by haarts** [flyway/flyway#1689]
I understand that the issue I'm describing could be interpreted as intended behavior. I also understand that the solution to this issue, if this is something which should be fixed, is not trivial.
Nonetheless, I wanted to bring this to your attention. Feel absolutely free to close!

###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle plugin

###### What database are you using (type & version)?
Postgres 9.6

###### What operating system are you using?
Ubuntu 16.04

###### What did you do?
I've added a comment to a migration file in order to clarify what was going on there. (This file was added some time ago and a Git ammend operation was no longer feasible.)

###### What did you expect to see?
I expected this to have no influence on the functioning of Flyway.

###### What did you see instead?
My application refused to start because the checksum of the file is suddenly different. I understand why this is the case but it seems overly strict.

**Comment by axelfontaine** [comment]
Thanks for reporting. As you probably suspected we have no plans to start evaluating changes in terms of comments vs comment directives (think MySQL version-specific comment directives, DB2 set terminator, optimizer hints, ...), nor do we plan to account for formatting changes (newline added, string concatenation simplified, ...). This would cause a lot of developüment effort for very little benefit.

Works as designed.
