### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by hybaken** [flyway/flyway#1698]
###### What version of Flyway are you using?
3.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle 4.0 with SpringBoot 1.5.4.RELEASE

###### What database are you using (type & version)?
Mysql 5.5.28

###### What operating system are you using?
Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Trying to insert data with diacritic.

###### What did you expect to see?
Characters: č ľ

###### What did you see instead?
I see question marks instead expected symbols: ? ?

##### Few more information: 
When I try input data manually, there is not a problem. I can see correct data.
I know default encoding is UTF-8 so it should work. I set it to UTF-8, but without a change.
Other characters like š ž á are working fine using flyway.
The files are saved as UTF-8 with IntelliJ 2017.1.4
Tables have CHARACTER SET utf8 COLLATE utf8_unicode_ci

**Comment by axelfontaine** [comment]
The issue is your database encoding. See https://stackoverflow.com/a/34889966/350428
