### ISSUE TITLE
Run SQL script multiple times with different placeholder parameters?

### ISSUE THREAD

**Issue by everking** [flyway/flyway#1700]
Not really an issue per se... But I'm wondering if Flyway supports the use-case where a script can be re-run multiple times using different parameter sets through "placeholder" and be treated either as separate versions or repeatable migration (though with different SQL files)?

I have a requirement where we'd want to run the same set of scripts to organize data according to "regions" (US, UK, CA, etc.)

###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Maven plugin

###### What database are you using (type & version)?

10.2.6-MariaDB

###### What operating system are you using?

Mac, Linux, AWS

**Comment by axelfontaine** [comment]
Please use the Flyway StackOverflow tag to ask questions.
