### ISSUE TITLE
Auto Create database if not exist.

### ISSUE THREAD

**Issue by bilalsha** [flyway/flyway#1703]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle plugin

###### What database are you using (type & version)?
PostGreSQL

###### What operating system are you using?
mac

###### What did you do?
I deleted my database now I want to run `gradle flywayMigrate -i` and it gives error

###### What did you expect to see?

I want that if database does not exist it should create a new one else it should continue migration

###### What did you see instead?
 ```
Error occurred while executing flywayMigrate
  Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost:3306/testDb) for user 'root': Unknown database 'testDb'
  Unknown database 'testDb'
```

**Comment by axelfontaine** [comment]
Flyway can creates schemas, not databases. This works as designed.
