### ISSUE TITLE
Dont know how to use java-based migration

### ISSUE THREAD

**Issue by oMinGWo** [flyway/flyway#1704]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-lnie

###### What database are you using (type & version)?
mysql 5.7

###### What operating system are you using?
window10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I'm trying to use java code to migrate some data to a new table
But the document about Java-based migrations are too simple
I don't know how to organize the project structure and how to package the project to a jar without main function.
(Is a main function is necessary for a java-based migration?

**Comment by axelfontaine** [comment]
Please ask questions on StackOverflow under the Flyway tag.
