### ISSUE TITLE
Parser does not support multiple statements per line

### ISSUE THREAD

**Issue by Lochan08** [flyway/flyway#1706]
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

CMD line

###### What database are you using (type & version)?

MYSQL 5.1.65-rel14.0-log

###### What operating system are you using?
Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Ran migrate script to execute script to insert data in db

###### What did you expect to see?

data should be inserted

###### What did you see instead?
migration failing due to sql code 1064: sytax error.
However if i execute the script manually It would insert data sucessfully.
Flyway is unable to execute the script
![flyway_error](https://user-images.githubusercontent.com/25623242/28068339-0f95a346-6613-11e7-8726-92ebedd452dd.png)

**Comment by axelfontaine** [comment]
Fixed. At last!
