### ISSUE TITLE
Flyway 4.2.0 Multiple Nodes In Parallel Failure with Oracle 11g

### ISSUE THREAD

**Issue by crgardner** [flyway/flyway#1712]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

Oracle 11g

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

NB: The following issue was also submitted to stackoverflow:

https://stackoverflow.com/questions/45110617/flyway-4-2-0-multiple-nodes-in-parallel-failure-with-oracle-11g

I have multiple application servers configured to run flyway at startup. Each server attempts to apply the same set of migrations across multiple schemas in the same Oracle 11g database. These servers are started at the same time. This works most of the time. On occasion, however, a server fails during migration because it encounters a unique constraint violation.

Unable to insert row for version '0' in metadata table "FOO"."SCHEMA_VERSION"

SQL State : 23000 Error Code : 1 Message : ORA-00001: unique constraint (FOO.SCHEMA_VERSION_pk) violated

 at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.addAppliedMigration(MetaDataTableImpl.java:242)
    at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.addBaselineMarker(MetaDataTableImpl.java:334)
    at org.flywaydb.core.internal.command.DbBaseline$2.call(DbBaseline.java:135)
    at org.flywaydb.core.internal.command.DbBaseline$2.call(DbBaseline.java:112)
    at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
    at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:112)
    at org.flywaydb.core.Flyway$1.execute(Flyway.java:990)
    at org.flywaydb.core.Flyway$1.execute(Flyway.java:971)
    at org.flywaydb.core.Flyway.execute(Flyway.java:1464)
    at org.flywaydb.core.Flyway.migrate(Flyway.java:971)

###### What did you expect to see?

I expected that the flyway instance that was waiting for the schema_version table to be unlocked would detect that the version 0 had already been added after it was unlocked.

###### What did you see instead?

A unique constraint violation when trying to insert version 0 entry.

**Comment by axelfontaine** [comment]
We are unable to reproduce this with Oracle 10, 11 or 12. Please share a small repro repo so we can analyse this further.

**Comment by axelfontaine** [comment]
Any news?

**Comment by crgardner** [comment]
I've been on holiday, so I haven't had a chance to try to recreate it.  The
issue is that it is random.  It doesn't happen every time.  In your own
experiments, how many schemas and how many flyway instances did you test
with?  In our environments, we have many 10s up to 150 schemas per oracle
server and two to six flyway instances hitting a server.

On Nov 27, 2017 3:52 AM, "Axel Fontaine" <notifications@github.com> wrote:

Any news?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/flyway/flyway/issues/1712#issuecomment-347115501>, or mute
the thread

**Comment by axelfontaine** [comment]
What surprises me is that this would imply the lock Flyway acquires occasionally either doesn't hold or gets released. Yet, we use an absolutely standard `LOCK TABLE ... IN EXCLUSIVE MODE`. See https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/oracle/OracleTable.java#L53

**Comment by crgardner** [comment]
If the lock does work, could another flyway instance wait until the lock is
released and then attempt to migrate anyway?  The error message seems to
indicate that the second instance doesn't check if the migration has
already happened.  So is this possible:

t1. Flyway 1 obtains exclusive lock on the foo.schema_version table.
t2. Flyway 2 discovers the lock is on the foo.schema_version table.
t3. Flyway 1 completes the migrations for the foo schema and updates
foo.schema_version table accordingly.
t4. Flyway 1 releases the lock.
t5. Flyway 2 attempts to migrate the foo schema, but discovers via an
Oracle error that the migrations have taken place.


Oracle locking allows you to specify a NOWAIT option (see below).
https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/oracle/OracleTable.java#L53
doesn't specify NOWAIT.  Based on the documentation excerpt below, I think
Flyway 2 is indeed waiting for the lock.  I don't know, however, if there's
a double check to ensure that the migrations have already happened after
the lock is released.  If that check is not there, that could be the cause
of the problem.

https://docs.oracle.com/cd/B13789_01/server.101/b10759/statements_9015.htm

*NOWAIT *

Specify NOWAIT if you want the database to return control to you
immediately if the specified table, partition, or table subpartition is
already locked by another user. In this case, the database returns a
message indicating that the table, partition, or subpartition is already
locked by another user.

If you omit this clause, then the database waits until the table is
available, locks it, and returns control to you.



On Nov 27, 2017 8:46 AM, "Axel Fontaine" <notifications@github.com> wrote:

What surprises me is that this would imply the lock Flyway acquires
occasionally either doesn't hold or gets released. Yet, we use an
absolutely standard LOCK TABLE ... IN EXCLUSIVE MODE. See
https://github.com/flyway/flyway/blob/master/flyway-core/
src/main/java/org/flywaydb/core/internal/database/oracle/
OracleTable.java#L53

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/flyway/flyway/issues/1712#issuecomment-347185692>, or mute
the thread

**Comment by axelfontaine** [comment]
@crgardner We do all that already.

**Comment by crgardner** [comment]
Given the original error message, what flyway code would encounter that
problem after the lock was released?  Could there be a race condition?

**Comment by axelfontaine** [comment]
OK, I just noticed this is version 0. This means you are attempting to do this against an empty DB. In which case one of the instance won't be able to use a `LOCK TABLE` as there not yet a table to lock.

We do have some retry logic specifically for this case. See https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/schemahistory/JdbcTableSchemaHistory.java#L103

We'll analyse to see if we have a logic flaw somewhere. In the meantime you can safely work around this by first baselining the table to version 0 from a single node. From then on all nodes should be able to migrate in parallel safely.

**Comment by axelfontaine** [comment]
We have adjusted the logic for this in Flyway 5.0 to ensure the table is created before any migrations are applied. This should hopefully fully eliminate this issue. Please try again with the latest sources or with binaries once Flyway 5.0 is out and confirm.

**Comment by axelfontaine** [comment]
Have you been able to retest this with Flyway 5.0.2?

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by MENGKONGSEAN** [comment]
I got that error too 
https://github.com/flyway/flyway/issues/2704
