### ISSUE TITLE
Suppress redundant "SQLite does not support setting the schema..." messages

### ISSUE THREAD

**Issue by J0s3f** [flyway/flyway#1713]
As in issue #1327 for SQLServer, the message should also be shown only once for SQlite because it is annoying and has no purpose.

	Jul 18, 2017 4:17:59 PM org.flywaydb.core.internal.dbsupport.sqlite.SQLiteDbSupport info
	INFORMATION: SQLite does not support setting the schema. Default schema NOT changed to main
	Jul 18, 2017 4:17:59 PM org.flywaydb.core.internal.metadatatable.MetaDataTableImpl info
	INFORMATION: Creating Metadata table: "main"."schema_version"
	Jul 18, 2017 4:18:00 PM org.flywaydb.core.internal.command.DbMigrate info
	INFORMATION: Current version of schema "main": << Empty Schema >>
	Jul 18, 2017 4:18:00 PM org.flywaydb.core.internal.command.DbMigrate info
	INFORMATION: Schema "main" is up to date. No migration necessary.
	Jul 18, 2017 4:18:00 PM org.flywaydb.core.internal.dbsupport.sqlite.SQLiteDbSupport info
	INFORMATION: SQLite does not support setting the schema. Default schema NOT changed to main

**Comment by axelfontaine** [comment]
Thanks for reporting. This has now been fixed.
