### ISSUE TITLE
SSMS Scripts 'migrate' fails due to encoding

### ISSUE THREAD

**Issue by rogatec** [flyway/flyway#1718]
###### What version of Flyway are you using?

```
$ ./flyway.cmd -v
Flyway 4.2.0 by Boxfuse
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

> flyway-commandline-4.2.0-windows-x64

###### What database are you using (type & version)?

> Microsoft SQL Server Developer Edition (64-bit)
> 13.0.4202 SP1
> Short: SQL 2016 Developer Edition

**Additional software**:
* Microsoft SQL Server Management Studio 2017
  * Version: 14.0.17119.0

###### What operating system are you using?

> Windows 10 Pro 64bit OS Build: 15063.483

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

1.  In SSMS go to a database
1.1 Right Click -> Tasks
1.2 Generate scripts
1.3 create script for one table (to simplify problem): e.g. only data (but doesn't matter)
1.4 move generated script to flyway sql folder and take care of correct syntax and version number.
2. Open command line
2.1 execute: ./flyway.cmd migrate to import new migration file from generated script (see 1.3)

###### What did you expect to see?

Sucessfully imported the sql file which was generated by SSMS.

###### What did you see instead?

Error output:
```
Successfully validated 3 migrations (execution time 00:00.915s)
SQLServer does not support setting the schema for the current session. Default schema NOT changed to dbo
Current version of schema [dbo]: 2
Migrating schema [dbo] to version 2.1 - BASE-DATA 2008R2
ERROR: Migration of schema [dbo] to version 2.1 - BASE-DATA 2008R2 failed! Changes successfully rolled back.
ERROR:
Migration V2.1__BASE-DATA_2008R2.sql failed
-------------------------------------------
SQL State  : S0001
Error Code : 102
Message    : Falsche Syntax in der N▒he von "?".
Location   : C:/flyway/flyway-4.2.0/sql/V2.1__BASE-DATA_2008R2.sql (C:\flyway\flyway-4.2.0\sql\V2.1__BASE-DATA_2008R2.sql)
Line       : 1
```

## Workaround

1. Open generated sql file with an editor (eg. VS Code / Sublime)
2. Change encoding from _UTF-16 LE_ to _UTF-8_

## Additional information

Unfortunately Microsoft is still lacking in giving an option for users to set an encoding for generating scripts.
[Open Microsoft Issue](https://connect.microsoft.com/SQLServer/feedback/details/336750/need-a-way-to-set-the-default-encoding-for-query-files-in-smss)

Is this possible for flyway to get around this problem e.g. change encoding on runtime of migrate command or just maybe to inform the user that he has to manually fix the encoding of the file?

Or is it possible to get migrate running with the usage of UTF-16 LE?

**Comment by rogatec** [comment]
Well to solve this problem without changing anything in flyway I can use the flyway configuration.
```
flyway.encoding=UTF-16LE
```

so I need to inform the other developers that they create their migration scripts with `UTF16-LE` encoding.

I leave it to you if you want to close this issue as "not a bug" and maybe just implement a "better" error message when failing due to encoding problems.

**Comment by chucklu** [comment]
Why don't you write a PowerShell script convert the encoding of the file to the target encoding?
I have a sample here for you
https://github.com/chucklu/Scripts/blob/master/Powershell/chuck.psm1
```Powershell
function Convert-EncodingToUTF8NoBOM {
  param(
    [Parameter(Mandatory = $false)]
    [string]
    $targetDir = '.',
    [Parameter(Mandatory = $false)]
    $extension = '*')
  $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
  $files = Get-ChildItem -Path $targetDir -Filter $extension
  foreach ($file in $files)
  {
    #$file.FullName
    $fileContent = Get-Content -Path $file.FullName
    [System.IO.File]::WriteAllLines($file.FullName,$fileContent,$Utf8NoBomEncoding)
  }
}
```
It can be invoked like this
Save the following code as Powershell script file with extension .ps1, you can replace the path by yourself
```Powershell
Import-Module ".\chuck.psm1" 
$extension = "*.sql"
Convert-EncodingToUTF8NoBOM "." "$extension"
```

**Comment by Mtnrunrmidge** [comment]
If the versioning matters amongst a team and you need to change the encoding one may also use a text editor (Notepad++). 
1. Open the file in the text editor. 
2. Select 'Encoding' in the menu and then select the encoding type. 
3. Save the file.
