### ISSUE TITLE
Flyway migrate() very slow with hundred of .sql files

### ISSUE THREAD

**Issue by edpichler** [flyway/flyway#1719]
As the project evolves, the migration files number increases.
Now, after more than a hundred .sql files, it's very slow to start an application. Our application calls migrate() every time starts up.

How can I check if is there anything to migrate?  How can I speed up this migrate() method when there is nothing to migrate?

**Comment by axelfontaine** [comment]
Please fill in the template for issue submission.

**Comment by axelfontaine** [comment]
Closing due to lack of response.
