### ISSUE TITLE
Migrate executing baseline again

### ISSUE THREAD

**Issue by rkukkadapu** [flyway/flyway#1720]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?
Postgres 9.6.2

###### What operating system are you using?
MacOS/Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Performing a simple migration. I have an existing DB and therefore creating a baseline. I have the base line file named 20170719120032048__Base_version.sql. I am using Java APIs for performing my migration.
Here are my configuration settings : 
`
        

- flyway.setBaselineOnMigrate(false)
- flyway.setValidateOnMigrate(false)
- flyway.setIgnoreMissingMigrations(true);
- setLocation("filesystem:" + COMPANY_NAME_DIR + "/" + locations);
- flyway.setSqlMigrationPrefix("");
- flyway.setBaselineVersionAsString(BASE_LINE_VERSION);
- flyway.setBaselineDescription(BASE_LINE_DESCRIPTION);
- flyway.setCleanDisabled(true);`

It executes the Baseline script again while migration and then complains that the tables in the file are already created and exits

###### What did you expect to see?

I am not expecting the baseline script again while migrating.

###### What did you see instead?
I see the baseline script being executed again and failing. The statements in the .sql file are not idempotent though.

**Comment by rkukkadapu** [comment]
Have the question posted here : 
https://stackoverflow.com/questions/44313173/migrate-executing-the-baseline-again/45288663#45288663

**Comment by axelfontaine** [comment]
I can't seem to reproduce this (note that your database must be non-empty for baseline to work). Can you share a small test case?

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by rkukkadapu** [comment]
My DB is not empty.

Sorry, was on a vacation and missed this.
Steps to repro
1. Create a base version file and place it in a directory.
2. Now, create new files which do not have the keyword "base" in it.
3. Run the baseline
4. Run the migrate
While running the migrate, it will try to re-execute the file name ***Base***.sql and fails, unless the baseline file is completely idempotent.
Here is a list of the file names that I have -
20170719120032048__Base_version.sql
20170725103622143__helper_func_for_idempotency.sql
20170728114246728__migration_for_8_5_0.sql
20170808153435742___cs_matchinginfo_migration_for_8_5_0.sql
20170810070050220__cis_benchmark_migration_for_8_5_0.sql
20170811163535123___computersystemidentity_migration_for_8_5_0.sql
20170821085722247__trl_vuln_cve_id_idx_for_8_5_0.sql
20170823105328123__createdbyinquerytable_8_5_0.sql
20170825153541390___data_collection_cycle_info_migration_for_8_5_0.sql
20170901083716128__ncc_cis_check_table_for_cis_benchmark_8_5_0.sql
20170915091856222__isCancelled_in_dataCollectionCycleInfo_8_5_0.sql
20170920112418442__dataCollectionCycleInfo_dataPluginName_8_5_0.sql

**Comment by axelfontaine** [comment]
Please share a minimal test case with actual files we can use to reproduce this.

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
