### ISSUE TITLE
Table creation Warning/Error

### ISSUE THREAD

**Issue by Binnykoul** [flyway/flyway#1721]
###### What version of Flyway are you using?
3.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
JAVA API

###### What database are you using (type & version)?
MySQL

###### What operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I'm using JpaRepository for saving my results to database MySQL. I use Flyway 3.2 to create my table in MySQL.
SAMPLE SCRIPT
drop table if exists `SAMPLE`;
  CREATE TABLE `SAMPLE` (
  `SAMPLE_ID` varchar(50) NOT NULL,
  `SAMPLE NAME` varchar(50) NOT NULL,
  `COMMENTS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SAMPLE`))
  ENGINE = InnoDB;
 
Table is successfully created.

Now if I call save on this table from my java code where I use JpaRepository, I get sql error and the reason is because of the space in column "SAMPLE NAME" and now if I change the column name to "SAMPLE_NAME" it works fine. 
So what I thought was Flyway should not have allowed creating such table on first place because then it becomes difficult to find these kind of errors once the table has been successfully created. Flyway should show an error or warning while creating such tables with such column names.

###### What did you expect to see?
A warning or error while creating the table

###### What did you see instead?
Table was successfully created

**Comment by axelfontaine** [comment]
Flyway executes your SQL as-is. If you instruct your database to create a column with a valid, although unusual, name and you are no longer happy with it, it is up to you to create a follow up migration to fix this.
