### ISSUE TITLE
Command-line: JAVA_ARGS environment variable support

### ISSUE THREAD

**Issue by jbrekelmans** [flyway/flyway#1727]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### Details

The CLI entrypoint script ("flyway") clears JAVA_ARGS by doing:
JAVA_ARGS=

I can't use the CLI entrypoint script because I need to set JVM properties in JAVA_ARGS around SSL settings:
JAVA_ARGS="-Djavax.net.ssl.trustStore=... -Djavax.net.ssl.trustStorePassword=...  -Doracle.net.ssl_server_dn_match=true -Doracle.net.ssl_version=1.0"

NOTE: I tried setting the same properties in flyway.conf by adding lines like "sysprops.javax.net.ssl.trustStore" but this didn't make the database connection work correctly.

The solution for me was to create my own CLI entrypoint script that works exactly the same as the original except for setting JAVA_ARGS to what I need it to be. Essentially doing this:
JAVA_ARGS="..."
java "$JAVA_ARGS" -cp "..." org.flywaydb.commandline.Main -configFile='...' -X info
 
**Could you update the CLI entrypoint script to APPEND to JAVA_ARGS so it's more usable?** For example:
JAVA_ARGS="$JAVA_ARGS -Djava.security.egd=file:/dev/../dev/urandom"

**Interesting question: Why does "syprops..." in flyway.conf not work while JAVA_ARGS="-D..." does?**

Also adding documentation around setting JAVA_ARGS would be helpful, if we go down that path (use-case example: SSL DB configuration).

Kind regards,

Jasper

**Comment by axelfontaine** [comment]
This has now been implemented.
