### ISSUE TITLE
Redshift JDBC 4.2 driver support

### ISSUE THREAD

**Issue by jeffreytli** [flyway/flyway#1733]
###### What version of Flyway are you using?
**4.2.0**

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
**Command-line**

###### What database are you using (type & version)?
**Redshift JDBC 4.2**

###### What operating system are you using?
**Mac OS 10.11.6**

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
**I tried running the following command: `flyway migrate` with the `username`, `password`, and `url` defined in flyway.conf.**

###### What did you expect to see?
I expected it to succeed and output:
```
Creating Metadata table: "PUBLIC"."schema_version"
Current version of schema "PUBLIC": << Empty Schema >>
Migrating schema "PUBLIC" to version 1 - Create person table
Successfully applied 1 migration to schema "PUBLIC" (execution time 00:00.062s).
```

###### What did you see instead?
**After running the above mentioned command, I get the following error: `ERROR: Unable to instantiate JDBC driver: com.amazon.redshift.jdbc42.Driver : com.amazon.redshift.jdbc42.Driver`.** 

###### Other notes
I downloaded the Redshift JDBC driver from [here](http://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html), and moved the 4.2 driver into the `drivers` directory. After digging around, I'm seeing that only 4.1 is currently supported. Are there any plans on supporting 4.2 in the near future? Or is this already supported and I'm just not configuring Flyway properly?

**Comment by axelfontaine** [comment]
What is the output if you add `-X`?

**Comment by axelfontaine** [comment]
This has now been implemented.
