### ISSUE TITLE
Flyway - Oracle SSL Support 

### ISSUE THREAD

**Issue by geethaRam** [flyway/flyway#1734]
###### What version of Flyway are you using?
4.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
Oracle 11.2

###### What operating system are you using?
Linux Centos 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

We are trying to run flyway to an Oracle RDS instance over SSL.
The connection and migration works fine when connecting over non-ssl
Here is the url for non-SSL: jdbc:oracle:thin:@//testd.c9ddfghoerty.us-east-1.rds.amazonaws.com:1521/TESTD

For SSL - we tried couple of options for the URL
URL1 :
 jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=testd.c9ddfghoerty.us-east-1.rds.amazonaws.com)(PORT=2484))(CONNECT_DATA=(SERVICE_NAME=testd)))
Exception:
14:08:41 org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=shrtsd.c9dfyqjobtqf.us-east-1.rds.amazonaws.com)(PORT=2484))(CONNECT_DATA=(SERVICE_NAME=shrtsd)))) for user 'SHRTS_ADMIN': IO Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
14:08:41 	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:407)
14:08:41 	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:365)
14:08:41 	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
14:08:41 	at org.flywaydb.core.Flyway.execute(Flyway.java:1314)
14:08:41 	at org.flywaydb.core.Flyway.clean(Flyway.java:1013)

URL2:
jdbc:oracle:thin:@//testd.c9ddfghoerty.us-east-1.rds.amazonaws.com:2484/TESTD
Exception:
IO Error: Got minus one from a read call
11:19:38 	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:407)
11:19:38 	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:365)
11:19:38 	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
11:19:38 	at org.flywaydb.core.Flyway.execute(Flyway.java:1314)
11:19:38 	at org.flywaydb.core.Flyway.clean(Flyway.java:1013)

Question: How to provide the certs path to flyway or how to connect to Oracle DB over SSL?

In Java code, we were able to set below properties to connect over SSL.

System.setProperty("javax.net.ssl.trustStore", TRUST_STORE_PATH);
System.setProperty("javax.net.ssl.trustStoreType", "JKS");
System.setProperty("javax.net.ssl.trustStorePassword",TRUST_STORE_PASSWORD); 
###### What did you expect to see?
Expected to see flyway make connection and able to execute migrations

###### What did you see instead?
Exceptions as listed above.

**Comment by geethaRam** [comment]
This is fixed.Works like a charm
For future references:

I added below when calling the flyway jar 
-Djavax.net.ssl.trustStore=/path/to/truststore -Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.trustStorePassword=password

**Comment by thehhugg** [comment]
We ran into the same problem. In our case, it was also necessary to specify keystore args like so:

```-Djavax.net.ssl.keyStore=/Users/you/wallet_dir/keystore.jks -Djavax.net.ssl.keyStorePassword=yourpasswordhere```

**Comment by Arunosaur** [comment]
I am following the examples and using gradle. I am new to all these. I am getting Network Adapter Error. Please help.

> Error occurred while executing flywayMigrate

  Unable to obtain connection from database (jdbc:oracle:thin:@ap20191107_tp?TNS_ADMIN=/Users/asrajag/Library/Oracle/Network/Admin) for user 'eorder': IO Error: The Network Adapter could not establish the connection
  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  SQL State  : 08006
  Error Code : 17002
  Message    : IO Error: The Network Adapter could not establish the connection

  IO Error: The Network Adapter could not establish the connection
  The Network Adapter could not establish the connection
  Unable to initialize ssl context.
  Unable to initialize the key store.
  SSO not found
  SSO KeyStore not available

**Comment by MikielAgutu** [comment]
@geethaRam @thehhugg This workaround looks reasonable, thanks for figuring it out.

@Arunosaur Gradle allows you to set JVM properties required for the workaround. [See Gradle docs](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties). Can you try it and see if it works?

Of course, Flyway should ideally have built-in support for this. We'll have a think about how can implement it. In the meantime hopefully this workaround is good enough to unblock people.

**Comment by MikielAgutu** [comment]
@Arunosaur Any news?
