### ISSUE TITLE
when using "group" transaction with "baselineOnMigrate" the schema_version table stays

### ISSUE THREAD

**Issue by y123321** [flyway/flyway#1736]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
SQL Server 2016 developer edition

###### What operating system are you using?
Windows server 2012 R2

###### What did you do?
I tried to run "flyway migrate" on an empty database. I ran the command:

flyway migrate -url=jdbc:sqlserver://MACHINE_NAME:1433;DatabaseName=test;integratedSecurity=true -target=1.2.776095 -locations=\"filesystem:C:/*PATH*" -baselineVersion=0001.0000.000000 -outOfOrder=true -ignoreMissingMigrations=true **-group=true** **-baselineOnMigrate=true**

one of the sql scripts had a syntax error in it.

###### What did you expect to see?
The database should have stayed empty

###### What did you see instead?
The table "schema_version" was there, the creation of it was not rolled back as expected.

**Comment by axelfontaine** [comment]
This is currently the expected behavior. The contents of the table are rolled back down, just not the creation of the table itself. Works as designed.
