### ISSUE TITLE
Re-BaseLine and Initial Script

### ISSUE THREAD

**Issue by fendy3002** [flyway/flyway#1737]
I wonder if there are 2 features that already in planning / existing / similar with those 2 that I need:

# Re-Baseline
No, I don't talk about feature that has been mentioned in #908.

Re-baseline simply add a baseline record in schema version table. For example:

| version | script |
| --- | --- |
| 1.0.0 | << Flyway Baseline >> |
| 1.1.0 | V1.1.0__migrate.sql |
| 1.2.0 | V1.2.0__migrate.sql |
| 1.2.3 | V1.2.3__bugfix.sql |
| 2.0.0 | << Flyway Baseline >> |

The purpose is only to prevent flyway migrate to execute the migration version 2.0.0. Sql script V2.0.0 is a script that construct database from scratch, up to latest migration or V1.2.3 in this case. The script will be similar with what will be produced if issue #470 is delivered, but manually constructed by developer.

# Initial Script
Continuing from previous example, I want the initial flyway migrate to start from script V2.0.0. without executing the artifacts before V2.0.0.

**Comment by reitzmichnicht** [comment]
I'm already doing this with Flyway, no need to add extra functionality:

```
MigrationInfo current = flyway.info().current();
		if (current == null) {
			String dbVersion = "2.0.0":
			flyway.setBaselineVersionAsString(dbVersion);
			flyway.baseline(); // needed because flyway doesn't baseline empty schemas
		}
```

Kind regards,
Michael

**Comment by popojargo** [comment]
@reitzmichnicht flyway.info().current() will return null even on a production database right? Thus, this code wouldn't work.

**Comment by MikielAgutu** [comment]
Related to #1986

**Comment by MikielAgutu** [comment]
This is now possible in V7 with the new `skipExecutingMigrations` config option: https://flywaydb.org/documentation/configuration/skipExecutingMigrations. You can run migrate with `target` set to your new 'baseline', and avoid executing them whilst still creating the record in the schema history.

**Comment by fendy3002** [comment]
> This is now possible in V7 with the new `skipExecutingMigrations` config option: https://flywaydb.org/documentation/configuration/skipExecutingMigrations. You can run migrate with `target` set to your new 'baseline', and avoid executing them whilst still creating the record in the schema history.

Awesome! Haven't tried it yet but I guess it's achievable with cherryPick!

**Comment by MikielAgutu** [comment]
We're going to assume the new features in V7 unblock this problem. Feel free to re-open if more limitations are discovered.
