### ISSUE TITLE
Fail to update checksum if errors happen during the upgrade from v2 to v4

### ISSUE THREAD

**Issue by mecca831** [flyway/flyway#1739]
###### What version of Flyway are you using?
4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
Postgres 9.6

###### What operating system are you using?
OS X

###### What did you do?
I have `schema_version` in v2 format (with `version_rank`, `installed_rank`, `version` columns). The table can be migrated to v4 format, with checksums updated, if no error happens when the application starts. However, if an error occurs during the process, e.g. duplicate migration version, then `schema_version` will be in a weird state. The table will be in v4 format (with `version_rank` removed) but the checksum will be the v2 hash. It won't be recalculated again, resulting checksum error for all subsequent runs.

###### What did you expect to see?
If the v4 migration fails, everything should be rolled back to the previous state, so in this case, the duplicate version error can be fixed and the v4 migration can be applied again.

###### What did you see instead?
v4 `schema_version` with v2 `checksum`

**Comment by axelfontaine** [comment]
I am afraid I am not sure how the table could contain duplicate migration versions in the first place. Can you explain?

**Comment by mecca831** [comment]
The table doesn't contain duplicate versions. Instead the error occurs because 2 migration files have the same version, say `v2__add_column.sql` and `v2__create_table.sql`.

**Comment by mecca831** [comment]
Looking at the code, the checksum repair calls `org.flywaydb.core.internal.resolver.CompositeMigrationResolver#checkForIncompatibilities` indirectly after the v4 schema upgrade. The expected behavior is either reverting the schema upgrade altogether, or simply not validating the new migration when repairing the checksum, IMHO.

See:
https://github.com/flyway/flyway/blob/274212fa5a91b6b82690555ef047ca2902d887f8/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L1459-L1462

https://github.com/flyway/flyway/blob/274212fa5a91b6b82690555ef047ca2902d887f8/flyway-core/src/test/java/org/flywaydb/core/internal/resolver/CompositeMigrationResolverSmallTest.java#L113

**Comment by mecca831** [comment]
@axelfontaine Any update on this?

**Comment by axelfontaine** [comment]
Nope, but you are welcome to contribute a pull request with a fix.

**Comment by axelfontaine** [comment]
We do not plan to fix this anymore. If this is still an issue, please drop your metadata table and rebaseline your schema with the new Flyway version.
