### ISSUE TITLE
support sbt 1.0

### ISSUE THREAD

**Issue by xuwei-k** [flyway/flyway#1741]
sbt 1.0.0 released http://developer.lightbend.com/blog/2017-08-11-sbt-1-0-0/

sbt 1.0.x is not compatible with sbt 0.13.x. need cross build or migrate to 1.0.

**Comment by axelfontaine** [comment]
Thanks for the suggestion. It may still be too early to drop 0.13.x compatibility. What do you think? Would you be willing to contribute a pull request?

**Comment by davidmweber** [comment]
I have migrated the sbt plugin to 1.0.0 to the point where it compiles and has a couple of flyway related deprecation warnings. I have two issues preventing me testing this and making a PR:
- `mvn compile -e -rf :flyway-sbt` results in an error  ( Command execution failed in flyway-sbt)
- How do you plan to support two different versions of the plugin? Perhaps a project in `flyway-sbt-1.0`?

**Comment by davidmweber** [comment]
Fixed maven issues (bad command line option for sbt). Just need to know how you plan to deal with the older version

**Comment by axelfontaine** [comment]
@davidmweber Would you be interested in taking over the maintenance of the official SBT plugin in a separate GitHub repo? (say `flyway/flyway-sbt` for example?)

**Comment by davidmweber** [comment]
That would probably make things easier for everyone. I have a tonne of Scala experience but my knowledge of sbt's plugins is limited. Happy to set up a repo and see what the community thinks.

**Comment by axelfontaine** [comment]
It would be great if you could support both SBT 0.13.x and 1.0.x until we all agree it makes sense to drop 0.13.x. 

Also you would have to keep up with changes in the core in a timely fashion. This is less work than it sounds. It usually revolves around adding new properties and removing deprecated ones for new major or minor releases which happen a few times a year at most.

You would also have to publish the plugin to a central repo after each release to make it easy for people to consume it.

Would this work for you?

Let me know and I'll set up the repo for you under the Flyway GitHub organization and give you the commit rights. You will share them along with @cdedie , the plugin's original contributor.

**Comment by davidmweber** [comment]
Sounds great! I have a couple of small projects that I already release this way. I suggest we start by pulling out the flyway-sbt tree and making that the first commit. We will need to integrate the test (flyway-sbt-largetest) and probably get some CI running. Docs presumably stay with your (rather excellent) docs?

**Comment by davidmweber** [comment]
@axelfontaine Are you still interested in doing this? I can prepare a sample repo and if you like it, we can transfer ownership to flyway.

**Comment by axelfontaine** [comment]
@davidmweber Yes! I have just created the `flyway/flyway-sbt` repo and sent you an invite. It would be ideal indeed if you could start by importing the `flyway-sbt` and `flyway-sbt-largetest` as an initial commit and then take things from there.

Once an initial version is ready for outside consumption, I'll then remove the modules from the main repo and we'll adjust the docs to point at yours.

**Comment by davidmweber** [comment]
Great stuff. I'll prepare something. Can we merge the test cases in `flyway-sbt-largetest` into `flyway-sbt` or do you want to retain this pattern? I am quite busy over the next few days but I will try to have something before the end of the week.

**Comment by axelfontaine** [comment]
Feel free to structure it as you prefer. Either option is fine with me.

**Comment by davidmweber** [comment]
Perfect!

**Comment by axelfontaine** [comment]
@davidmweber Have you been able to make progress on this? Is your access to https://github.com/flyway/flyway-sbt working?

**Comment by davidmweber** [comment]
I have just managed to get SBT's plugin testing running and have a decent migration to sbt 1.0. I cannot push to master (fine by me). I'll push something to another branch in the next hour.

**Comment by axelfontaine** [comment]
@davidmweber Please try again. I just readded you to the team.

**Comment by davidmweber** [comment]
I can edit the README on master so it looks good!

**Comment by davidmweber** [comment]
I have a rough cut of a port on master. It actually migrates a real database. Tests are using sbt's plugin test framework. It needs proper versioning, CI and deployment. Take a look and let me know if something smells wrong.

**Comment by axelfontaine** [comment]
Looks good. As I mentioned, please make sure the plugin supports both SBT 0.13.x and 1.0.x until we all agree it makes sense to drop 0.13.x.

**Comment by jarreds** [comment]
Any ETA when the new plugin might be uploaded?

**Comment by davidmweber** [comment]
The sbt 1.0 version can be uploaded. I will figure out sbt's versioned builds today. I have not worked out how to version this properly as it is hardcoded to a SNAPSHOT for the tests. Not sure how you guys do your CI and maven deployment. We can take this to gitter or some such any time after 9:00 UTC.

**Comment by pettyjamesm** [comment]
Any update on getting this released? SBT 1.0 is now supported by Play 2.6.6, so I imagine people will start trying to upgrade in larger numbers.

**Comment by etspaceman** [comment]
Yep @pettyjamesm; I tried to upgrade today and ran into this roadblock.

**Comment by davidmweber** [comment]
There is a build ready to roll at https://github.com/flyway/flyway-sbt and a pull request to flyway.org at https://github.com/flyway/flywaydb.org/pull/86#issuecomment-333189250 that just needs to be merged. If that is deployed then it should just work  Ideally, we need it to deploy it to Maven  from Travis but I don't have credentials to do that. It is actually a bit of a blocker for me too.

**Comment by etspaceman** [comment]
For those looking for a workaround, I was able to copy the FlywayPlugin file from @davidmweber's referenced repository into my project/ folder and it works great. I also had to add the following line to project/plugins.sbt in order to resolve dependencies at build time:

`libraryDependencies += "org.flywaydb" % "flyway-core" % "4.2.0"`

**Comment by pettyjamesm** [comment]
Any update on a public release being made available?

**Comment by davidmweber** [comment]
I am depended on the Flyway deployment at the moment and personally blocked on several projects. I will follow up on my pull request. If I see nothing then I may deploy it to Maven myself under a different path.

**Comment by etspaceman** [comment]
@davidmweber I say go for it. You'd be helping out a lot of devs in the interim.

**Comment by davidmweber** [comment]
I have put a preview/early release maven style site up on github. Check it out at https://davidmweber.github.io/flyway-sbt.repo/ and let me know if this works for you.

**Comment by emag** [comment]
@davidmweber Great works! it works perfectly on the following environment. Thanks!

* Play 2.6.7
* Scala 2.12.4
* sbt 1.0.3

**Comment by axelfontaine** [comment]
For SBT support going forward, please use @davidmweber 's https://github.com/flyway/flyway-sbt repo.
