### ISSUE TITLE
Allow Multiple Suffixes/File Extensions

### ISSUE THREAD

**Issue by apexbine** [flyway/flyway#1742]
###### What version of Flyway are you using?
4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Oracle 12.x

###### What operating system are you using?
Windows

###### What did you do?
I tried to find a way to make Flyway execute files with different file extensions.
One was to change flyway.conf (see below)

###### What did you expect to see?
When setting
`flyway.sqlMigrationSuffix=.sql,.pkg,.pkb`
in flyway.conf I expected a proper error message when executing `flyway info` or `flyway migrate`
Instead, all pending files where ignored.

###### What do you need?
We need to execute .sql files as well as .pkg and .pkb files. (Containing SQL and/or PL/SQL code)
We can't change the file extensions to be all the same because _Oracle SQL Developer_ and _TOAD_ need them to determine the correct editor to open the file in.
**Please allow multiple suffixes.**

**Comment by apexbine** [comment]
Related to https://github.com/flyway/flyway/issues/1206

**Comment by MSchmidke** [comment]
If it's still open, I would like to take care of it ...

**Comment by axelfontaine** [comment]
Will this alone solve the problem though? How would the ordering be guaranteed between your different pkg and pkb files? Do you give them a different description? Help me understand your scenario better with a few specific examples.

**Comment by apexbine** [comment]
Hi Alex,

we want to apply our delta scripts - as usual - and after that we would like to reinstall all our packages via repeatable migration.
The correct naming with unique version prefixes would still be our responsibility.

**Comment by axelfontaine** [comment]
@MSchmidke No need for a pull request. We will implement this ourselves.

**Comment by axelfontaine** [comment]
`flyway.sqlMigrationSuffix` has now been deprecated in favor of the new `flyway.sqlMigrationSuffixes` which now takes a comma-separated list of suffixes.

**Comment by apexbine** [comment]
Thanks a lot! Looking forward to testing it!
