### ISSUE TITLE
SQL Server - Metadata table in wrong catalog being updated

### ISSUE THREAD

**Issue by NiallWallace** [flyway/flyway#1743]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command Line

###### What database are you using (type & version)?

SQL Server 2008

###### What operating system are you using?
Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
flyway.url=jdbc:jtds:sqlserver://localhost:1433/LOOKUP;instance=SQLSERVER2008
flyway.table=LOOKUPMETADATA

Migration script containing updates to a catalog "Lookup" as well as deployment of a SQL Server Agent Job to the msdb catalog

flyway migrate

###### What did you expect to see?
Migration logged in the metadata table for the "Lookup" catalog

###### What did you see instead?
Migration logged in a metadata table in the "msdb" system catalog rather than in Lookup

The result of this is that migrations do not execute after this due to validation failure because the migration with the SQL Server Agent Job is detected as missing.

I've been able to work around this by finishing the script with a "Use Lookup" to switch back into the catalog with the intended metadata table for the db being deployed.

Although in this case the problem is from switching to a different schema in order to add a db rather than catalog level item; I also have a number of systems with database objects spread across multiple catalogs that would be impacted by this also if I wanted to manage them from a single migration set.

**Comment by axelfontaine** [comment]
Flyway simply passes the connection URL as-is to jTDS. If that doesn't trigger the correct connection setup, it is most likely related to a bug in the driver. Alternatively you can try switching to the official MS driver instead.
