### ISSUE TITLE
This log is too long to be displayed

### ISSUE THREAD

**Issue by dhoer** [flyway/flyway#1749]
Travis build has the following complaint:

```
This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.
```

I don't know if Netty has a log level of DEBUG for troubleshooting. But if not, can Netty log level be set to something higher like WARN?

**Comment by axelfontaine** [comment]
This should be fixed now. I reduced the testcontainers log output dramatically.

**Comment by dhoer** [comment]
Thanks
