### ISSUE TITLE
VoltDB support

### ISSUE THREAD

**Issue by arun0009** [flyway/flyway#1751]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
SBT

###### What database are you using (type & version)?
VoltDB 7.5

###### What operating system are you using?
Mac 10.12.6

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Ran sbt flywayMigrate

###### What did you expect to see?
Migration Successful

###### What did you see instead?
[info] Database: http://voltdb.com/ (VoltDB 7.5)
org.flywaydb.core.api.FlywayException: Unsupported Database: VoltDB 7.5

Can we add support for Volt DB? Just basic support to migrating scripts that are valid for VoltDB sqls with schema versions would be sufficient.

**Comment by alextercete** [comment]
Closing due to lack of interest.
