### ISSUE TITLE
Flyway SQL Server database migration failed using statement delimiter GO

### ISSUE THREAD

**Issue by MateuszSobala** [flyway/flyway#1755]
###### What version of Flyway are you using?
3.2.1 and 4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
ANT tasks

###### What database are you using (type & version)?
SQL Server 2014. My jdbc SQLServer driver version is 6.0.

###### What operating system are you using?
Windows 7 64-bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Put some statements separated with GO delimiter in a single SQL file and wanted to execute it.

###### What did you expect to see?
That the script should be executed successfully.

###### What did you see instead?
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'GO'.
The same problem described also here: https://stackoverflow.com/questions/27107498/flyway-sql-server-database-migration-failed-using-statement-delimiter-go

**Comment by axelfontaine** [comment]
Please include  the smallest possible set of statements that causes this to fail.

**Comment by MateuszSobala** [comment]
e.g.
INSERT INTO TAB_A (A_ID) VALUES (1)
GO
SELECT * FROM TAB_A

But also any other DML or DDL statements (create table, procedure etc.).

The only working case is for instance:
SELECT * FROM TAB_A
GO
SELECT * FROM TAB_B

**Comment by MateuszSobala** [comment]
@axelfontaine 
The reason was, that we had set "@" as a delimiter for the described scripts in an ant task runner. As soon as we used "@" to separate the statements everything started working like a charm. The same happened when we switched to MySQL, so it's just our oversight and it's a platform independent problem.

Sorry for the inconvenience.

Kind regards,
Mateusz
