### ISSUE TITLE
Warn on incompatible class change

### ISSUE THREAD

**Issue by nvartolomei** [flyway/flyway#1757]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

SBT plugin

###### What did you do?

Tried to migrate this

```java
import java.sql.Connection

import org.flywaydb.core.api.migration.jdbc.JdbcMigration
import org.json4s._
import org.json4s.ext.JavaTypesSerializers

class V42__Some_migration extends JdbcMigration {
  implicit val formats = DefaultFormats ++ JavaTypesSerializers.all

  override def migrate(conn: Connection): Unit = {
    // ...
  }
}
```

###### What did you expect to see?

An error at least.

###### What did you see instead?

Using flyway 4.0.3 sbt 0.13.13 and scala 2.11 worked as expected.
After upgrading to sbt 0.13.16 and scala 2.12.3, migrations failed with `java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V` exception somewhere in json4s code. I suspect this is because of some conflicts between sbt's scala 2.10 and scala 2.12. I can accept this to some degree.

The funny thing is that after upgrading to flyway 4.2.0, migrations are run successfully, except that `V42` migration mentioned above is skipped completely.

ps. if I delete `implicit val formats = DefaultFormats ++ JavaTypesSerializers.all` declaration, flyway will see this migration.

**Comment by axelfontaine** [comment]
SBT 0.13.x is only compatible with Scala 2.10.x

Not a Flyway issue.

**Comment by nvartolomei** [comment]
@axelfontaine I perfectly understand that the issue I have is caused by sbt 0.13 and scala 2.12 incompatibility, the issue instead says that flyway behaviour under such conditions changed and now it is swallowing the error, since 0baf57e7.

I tried to find commit that changed the behaviour of flyway in this environment.
Would you mind at least raising logging level, to warn?

https://github.com/flyway/flyway/blob/219ffbd00c9e07693be51ffd2e8ea06694273073/flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/ClassPathScanner.java#L122-L124
