### ISSUE TITLE
Flyway doesn't insert correctly Hindi or Japanese chars on migration

### ISSUE THREAD

**Issue by edpichler** [flyway/flyway#1759]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
MySQL 5.7 with correct encoding. (there are already hindi chars on database inserted by my application, and being read  #correctly).

###### What operating system are you using?
Linux

###### What did you do?
I have a flyway migration UTF8 file, with: 
`INSERT INTO MESSAGES (value)  VALUES ( 'डिडिडिडि');`

###### What did you expect to see?
डिडिडिडि chars inserted on database. 

###### What did you see instead?
On database flyway inserts ??????? chars.
When I insert directly on Mysql from other tools, it works, reading and writing, I got the hindi chars I want. Only when inserted by flyway migration it can't be read correctly.

Obs.: There are German letters like ß and ü on the same flyway script, and it's inserting correctly, just Japanese and hindi chars it doesn't.

My flyway sql file is using UTF-8

**Comment by axelfontaine** [comment]
Flyway deals with encoding just fine. Make sure somewhere down the chain (connection?) you are not using the wrong encoding (`utf8` instead of `utf8mb4` for example).

Not a Flyway issue.

**Comment by edpichler** [comment]
@axelfontaine flyway is using the same database connection as the whole application. Could you point me a jUnit test that inserts similar chars (chinese, hindi, etc)?

**Comment by edpichler** [comment]
The same database connection is inserting and selecting the data correctly, only flyway not.

**Comment by chariothy** [comment]
I have the same problem. My Chinese comments all become '???' after migrating.
My *.sql files are encoded in UTF-8 and my database is utf8mb4_unicode_ci.
Then I execute the sql file directly by IDEA database tool, nothing wrong.
Also I've tried utf8mb4_general_ci and utf8_general_ci, but nothing changed.

**Comment by chariothy** [comment]
I have the same problem, too. After half hour's investigation, I've found the problem is not flyway's.
Just make sure your datasource.url contains characterEncoding=UTF-8:
jdbc:mysql://localhost:3306/mydb?useSSL=false&characterEncoding=UTF-8&autoReconnect=true
