### ISSUE TITLE
MySQL - schema_version table remains LOCKed after Flyway runs

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#176]
_Original author: greg.c...@gmail.com (March 11, 2013 19:00:17)_

Commit ceb4bbb4f49e802fc76e370c1af069bddae3380b to fix issue #439 means the schema_version table will be locked with LOCK TABLES. However, a UNLOCK TABLES; statement is never issued.  Other sessions will hand attempting to query the schema_version table.  But most importantly, in other queries using the same session as the flyway migration will error out with  Table 'XXXX' was not locked with LOCK TABLES.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=450_

**Comment by meilleureVie** [comment]
See this
https://stackoverflow.com/a/36467496
