### ISSUE TITLE
Flyway CLI with Vertica

### ISSUE THREAD

**Issue by pkurra** [flyway/flyway#1761]
###### What version of Flyway are you using?
Ans: 4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Ans: Command-Line

###### What database are you using (type & version)?
Vertica

###### What operating system are you using?
Windows 7 Enterprise

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

C:\Software\flyway-4.2.0>flyway migrate
Flyway 4.2.0 by Boxfuse

Database: jdbc:vertica://XXXXXXXXXX.YYYY.net:5433/XXXXXX (Vertica Database 8.0)
ERROR:
Unable to check whether table "XXXXXXX"."schema_version" exists
----------------------------------------------------------------
SQL State  : 3F000
Error Code : 4650
Message    : [Vertica][VJDBC](4650) ERROR: Schema "information_schema" does not exist

###### What did you expect to see?
The flyway audit tables to be created in the specified schema and the SQL script to be migrated.

###### What did you see instead?
Unable to check whether table "XXXXXXX"."schema_version" exists
Message    : [Vertica][VJDBC](4650) ERROR: Schema "information_schema" does not exist

Please Note that “information_schema” is not a valid schema on Vertica, as it should be “v_catalog” schema in Vertica.

**Comment by cowboygneox** [comment]
Is there a workaround for this?

**Comment by MikielAgutu** [comment]
We've dropped support for Vertica. If we re-add it, we'll check this bug is fixed.
