### ISSUE TITLE
Misleading documentation about command-line configuration files

### ISSUE THREAD

**Issue by brynjulv** [flyway/flyway#1762]
On the webpage https://flywaydb.org/documentation/commandline it says:

"To use an alternative configuration file use -configFile=path/to/myAlternativeConfig.conf"

That is misleading, it should be something like:

"To use an ADDITIONAL configuration file use -configFile=path/to/myAlternativeConfig.conf"

and perhaps mention that this one is read last, and thus its settings override settings in the previous three.

**Comment by cdavid15** [comment]
This might not be valid now since pull request flyway/flywaydb.org/pull/87 was merged

**Comment by axelfontaine** [comment]
Thanks for the feedback. This whole section has now been reworked (flyway-5.0 branch).
