### ISSUE TITLE
Does Flyway really support 'DB2 on zOS'

### ISSUE THREAD

**Issue by riedela** [flyway/flyway#1763]
###### What version of Flyway are you using?
flyway -v: Flyway 4.2.0 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
DB2 11.1 zOS

###### What operating system are you using?
Windows 7

###### What did you do?
Really, I DO NOTHING!

I have start working and testing Flyway on Postgre-Database and everything was fine.

So, the first decision on a 'real world project' fell on a DB2 on zOS.

As we can see in the docmentation:
https://flywaydb.org/documentation/database/db2zos

it will be supported. With some, we have to read carefully, restriction:
  Limitations
    - Create Schema - is not supported in db2 on zOS
    - Drop Schema - is not supported in db2 on zOS

So, some lie to me. I not really complete doing nothing.
- I've even fullfill the nescessary configuration task to flyway.conf
  I insert:
  - JDBC-Connection-String
  - User-Name
  - Password
  - Default-Schema
  Put at this point, really: I do nothing more. I do not even configure a single SQL-Script.

###### What did you expect to see?

That the command: flyway migrate
- Ended up successfully, even doing nothing else than ...
- ... create the schema_version table used by Flyway itself.

That was the only result I expect.

###### What did you see instead?
But the command 'flyway migrate' only show this error:
$ flyway migrate
Flyway 4.2.0 by Boxfuse

Database: jdbc:db2://someip:someport/somedb (DB2 11.1)
Creating schema "someschema" ...
Creating schema "someschema" ...
Creating schema "someschema" ...
Creating schema "someschema" ...
Creating schema "someschema" ...
Creating schema "someschema" ...
Creating schema "someschema" ...
Creating schema "someschema" ...
Creating schema "someschema" ...
Creating schema "someschema" ...
ERROR: java.lang.UnsupportedOperationException: Create Schema - is not supported in db2 on zOS

BTW:
  I think the command: flyway info
  is enougth to test 	whether or not the configuration is correct. And this command succeeded.

  $ flyway info
  Flyway 4.2.0 by Boxfuse
  
  Database: jdbc:db2://someip:someport/somedb (DB2 11.1)
  
  +---------+-------------+---------------------+---------+
  | Version | Description | Installed on        | State   |
  +---------+-------------+---------------------+---------+
  | No migrations found                                   |
  +---------+-------------+---------------------+---------+

###### What is the question?

I've
- test it myself.
- read some old comments releated to 'DB2 zOS' here in this forum:
    https://github.com/flyway/flyway/issues/1344
    https://github.com/flyway/flyway/issues/638

And I ending up in the question:
- Does Flyway really support DB2 on zOS?
- Is this really verfied or is it just a guess?

Afterread the following comment:

--------------
  axelfontaine commented on 8 Nov 2013
  Thanks for your report.
  
  Unfortunately I don't have access to a z/OS environment.
  
  I you wish to add support for DB2 on z/OS and maintain the code, I would gladly accept a pull request.
  
  Cheers
  Axel

--------------

putting together with my own study I came to the result:
- I don't really think so!

But if you are sure, it works, please tell my in a little more detail, what's to do.

I don't think the explanation 'Create Schema - is not supported in db2 on zOS' is enough here.

TIA
   Andreas Riedel

**Comment by Muni10** [comment]
Create the schema in the DB2 z/OS database beforehand, set the schema in the configuration. As you can see, the support for DB2 z/OS is discontinued, and the code will be moved to another artifactId and package. But we are using this in-house at my company, so it does work (with some limitations).

**Comment by riedela** [comment]
Hello Muni10,

first at all many thanks. But, excuse me, some more questionsmarks over my head:
-  Were did you get the information _the support for DB2 z/OS is discontinued_ from? I can't find it. On the homepage of flyway, DB2 on zOS is still supported.
- If you say _Create the schema_ what does this concrete mean? From the connection-string:
_flyway.url=jdbc:db2://<server>:<port>/<db>:currentSchema=<schema>;currentPackageSet=NULLID91;_
must be equals to
_flyway.schemas=<schema>_
This schema exists, so nothing to do here? Or do you mean the schema-version table? Then your  tip means I have to create this table before running Flyway?!
- As I can see, you have developed a solution a fork. This means: Origin Flyway will not support DB2 on zOS? Will your bugfix/workaround come in the origin or does your addition _will be moved to another artifactId and package_ mean, that this will persist as a separate fork.

Many thanks at all,

Andreas Riedel

**Comment by axelfontaine** [comment]
@riedela We, at Boxfuse, took the decision to drop DB2 z/OS from the upcoming Flyway 5.0 release as we simply have no way to test and validate that code ourselves due to the lack of access to a z/OS machine.

The DB2 z/OS code will migrate to the newly created https://github.com/flyway/flyway-db2zos repository and will land in a separate jar, which will act as a plugin for the main distribution of Flyway. This means that when both jars are present on the classpath, Flyway will automatically pick up z/OS support as before.

You are welcome to assist @Muni10 and @cteig in implementing, testing and polishing this.

**Comment by Muni10** [comment]
@riedela 
I see @axelfontaine answered your first question, I will try to answer the second:
In DB2 z/OS the schema must be available when running the first migration as we can't assume to have the permissions for this. We use this schema name to set current schema when running migrations. If your schema has not been created before running the migration you will see the UnsupportedOperationException. A check is done to verify the existence of this schema, if that is not the case, then flyway will try to create the schema, and will return USE in your case. Please make sure "schema" is available in your DB2 instance, and that you can access it. 

You do not have to create the schema_version table, that will be created automatically when flyway can access your schema.

As for your third question: Any new bug fixes will be made available in the new repository flyway-db2zos as soon as I am able to move the code there.

**Comment by dhermanns** [comment]
Anything new on this? The db2zos Repository seems to be empty:
https://github.com/flyway/flyway-db2zos

Is this still under construction?

**Comment by Muni10** [comment]
Have not been able to finish this unfortunately. But will try to get an initial version done over the summer.
