### ISSUE TITLE
ClickHouse support

### ISSUE THREAD

**Issue by peturrun** [flyway/flyway#1772]
We at Activity Stream would like to contribute support for ClickHouse to Flyway.

There are some limitations - because ClickHouse doesn't support UPDATE or DELETE, repair functionality is not available.

This depends on changes to the clickhouse-jdbc driver that have been committed to the github repository, but are not yet part of a release.

**Comment by filimonov** [comment]
any plans to merge #1773 ?

**Comment by axelfontaine** [comment]
@filimonov The biggest impediment is this: https://db-engines.com/en/ranking 

Maintaining ClickHouse support unfortunately currently has a very low power to weight ratio.

**Comment by filimonov** [comment]
Ok, sounds reasonable. (of course I could say that CockroachDB is also not on the top of the list). 

And what about 'community-supported' extra DB engines? For example by plugins? That would allow to use flyway more widely, and after certain community-driven part will become popular / mature / stable you can merge it to the core. That will allow to use flyway in the environments which are not currently covered by flybase core, so flybase will be used wider, so for you it's also win-situation.

**Comment by filimonov** [comment]
That can also unblock a lot of other pull requests, which are waiting while corresponding DBMS will became enough popular to get some support from flyway :)

#1857 #1655 #1495 #1386 #1322 #773

**Comment by axelfontaine** [comment]
@filimonov No immediate plans for this. See https://github.com/flyway/flyway/issues/1608#issuecomment-369514554

That is not to say neither of these DBs can ever be supported. It simply means that until they become much more popular a commercial agreement is needed to make it worth it for us. We would be more than happy to talk to your company or Yandex if this is an option for you in order to get ClickHouse support in sooner.

**Comment by tburch** [comment]
+1 for ClickHouse support!

**Comment by filimonov** [comment]
@tburch i've finished with that: https://github.com/filimonov/ClickHouse/wiki/Clickhouse-database-schema-migrations 

Liquibase extension is also doesn't see like something very sophisticated (especially if not implement all automatic DDL generation logic).

**Comment by tburch** [comment]
Thanks @filimonov! I'll take a look. I was hoping for something that I could use in spring-boot, but maybe I can adapt this.

**Comment by jondeandres** [comment]
Any update on this?

**Comment by eugene-bright** [comment]
The latest related pull request #2981. Unfortunately it stuck

**Comment by filimonov** [comment]
@axelfontaine are there chances to merge a PR with clickhouse support in 2021/2022?

**Comment by anjanroy86** [comment]
Hi,
Is the support for clickhouse available now?

**Comment by waifairer** [comment]
Any chance of clickhouse support please?

**Comment by tianzhou** [comment]
Shameless plug, I am the author of [bytebase](https://github.com/bytebase/bytebase) and it does support ClickHouse. We already have data teams using the GitOps feature branch workflow to apply schema change to ClickHouse. The steps are summarized [here](https://www.bytebase.com/docs/how-to/workflow/gitops-feature-branch)

**Comment by sazonov** [comment]
I made a PR for this #3611. If someone knows who is an active maintainer, please tag. Really want to speed it up a bit.

**Comment by demidov163** [comment]
> I made a PR for this #3611. If someone knows who is an active maintainer, please tag. Really want to speed it up a bit.

We also need this functional, Kindly ask support team pay attention to this PR.

**Comment by jianchengwang** [comment]
Is the support for clickhouse available now?

**Comment by Barry-RG** [comment]
Clickhouse support is now available.
