### ISSUE TITLE
Connection problems with gradle plugin

### ISSUE THREAD

**Issue by naell** [flyway/flyway#1774]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? 
Command-line and Gradle plugin

###### What database are you using (type & version)?
MSSQL 2014

###### What operating system are you using?
Windows 10

###### What did you do?
In the command line:
`flyway info -url=jdbc:jtds:sqlserver://localhost:1433/<dbname> -user=myuser -password=mypassword`

with gradle:
`gradlew flywayInfo -Purl=jdbc:jtds:sqlserver://localhost:1433/<dbname> -Puser=myuser -Ppassword=mypassword`

###### What did you expect to see?
The table with the version, desc, installed on and state column

###### What did you see instead?
The expected for the command line tool, but I got an exception with gradlew 

> Unable to connect to the database. Configure the url, user and password!

**Comment by axelfontaine** [comment]
Gradle properties must be prefixed with `flyway.`. See https://flywaydb.org/documentation/gradle/#gradle-properties
