### ISSUE TITLE
Parallel Migration Issue

### ISSUE THREAD

**Issue by rameezrajas** [flyway/flyway#1778]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven Plugin

###### What database are you using (type & version)?
Microsoft SQL Server 2016

###### What operating system are you using?
Linux 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Flyway is executing same migration when I have two instances of my application startup nearly simultaneously while pointing at an empty database 
First instance of service successfully executes all migration
Second instance of service starts executing the migrations from the middle

Instance 1
{"timeMillis":1506297752742,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.util.VersionPrinter","message":"Flyway 4.2.0 by Boxfuse","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753615,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.callback.SqlScriptFlywayCallback","message":"Executing SQL callback: beforeMigrate","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753643,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.metadatatable.MetaDataTableImpl","message":"Creating Metadata table: [dbo].[schema_version]","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753706,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Current version of schema [dbo]: << Empty Schema >>","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753720,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.1 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753844,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.2 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753884,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.3 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753923,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.4 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753952,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.5 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297753998,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.6 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754026,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.7 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754065,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.8 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754100,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.9 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754134,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.10 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754161,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.11 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754192,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.12 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754219,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.13 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754334,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.15 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754375,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.16 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754403,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.17 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}

Instance 2

{"timeMillis":1506297753350,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.util.VersionPrinter","message":"Flyway 4.2.0 by Boxfuse","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754202,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.callback.SqlScriptFlywayCallback","message":"Executing SQL callback: beforeMigrate","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754305,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Current version of schema [dbo]: 1.13","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754308,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.14 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754351,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migrating schema [dbo] to version 1.15 - XXXXX SCRIPT","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754357,"thread":"main","level":"ERROR","loggerName":"org.flywaydb.core.internal.command.DbMigrate","message":"Migration of schema [dbo] to version 1.15 - XXXXX SCRIPT failed! Changes successfully rolled back.","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754358,"thread":"main","level":"INFO","loggerName":"org.flywaydb.core.internal.dbsupport.sqlserver.SQLServerDbSupport","message":"SQLServer does not support setting the schema for the current session. Default schema NOT changed to dbo","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{"appName":"product"},"threadId":1,"threadPriority":5}
{"timeMillis":1506297754359,"thread":"main","level":"WARN","loggerName":"org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext","message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: \nMigration V1_15__XXXX_SCRIPT.sql failed\n-----------------------------------------------------

###### What did you expect to see?
If one instance of service is process of migrating the schema, the other instance of service should wait for the migration to be finished by first service. Locking is missing

###### What did you see instead?
Two instances of service executing same migration

**Comment by axelfontaine** [comment]
This is very surprising as we actually have code to handle this exact scenario. Can you share a small test to reproduce this?

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
