### ISSUE TITLE
Use java.nio.Path to scan filesystem and read SQL files

### ISSUE THREAD

**Issue by gquintana** [flyway/flyway#1779]
This new feature allows:

* To read file from remote file systems: I want to read SQL files from S3 (using [S3](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2) file system provider ) or from a Zip file not in classpath ( [Zip](http://docs.oracle.com/javase/7/docs/technotes/guides/io/fsp/zipfilesystemprovider.html) file system provider) )
* To read file from classloader as if it was as local file: `Path path=Paths.get(classLoader.getResource(resourceName).toURI());`

However, it's probably not compatible with Android as it requires Java 7.

**Comment by axelfontaine** [comment]
Thanks for the suggestion. While those features are neat, the lack thereof hasn't seemed to be much of a deal breaker for users so far. But it's an interesting idea to consider for the future.

**Comment by gquintana** [comment]
Would you accept a PR?

**Comment by MikielAgutu** [comment]
We don't think this is the right thing. S3 locations are on the roadmap : https://github.com/flyway/flyway/issues/1961.

Feel free to create a particular issue for reading from Zip archives etc.
