### ISSUE TITLE
Add ability to load configuration files directly from Flyway API

### ISSUE THREAD

**Issue by jakaarl** [flyway/flyway#1780]
When constructing a new `Flyway` instance using the Java API and not providing a configuration, Flyway simply fails instead of looking for a configuration using the same rules as the command line. I was expecting not providing a configuration to cause the "normal" lookup.

Please consider using the same lookup as CLI when no configuration is given explicitly. Since people are used to how it works (or, not works for us who expected it to behave similarly to the command line client), it would probably make sense to have a method for enabling automatic lookup?

**Comment by axelfontaine** [comment]
I am not sure the automatic part would be a good addition as this would vastly change the behavior of millions of installations. However, providing an easy method to load configuration files from disk as part of the core could be a nice low hanging fruit.
