### ISSUE TITLE
First character in script column of schema_version table removed if double back slashes in location.

### ISSUE THREAD

**Issue by mehta-m** [flyway/flyway#1782]
###### What version of Flyway are you using?
4.2.0

###### What database are you using (type & version)?
Microsoft SQL Server 2012

###### What operating system are you using?
Windows 10

###### What did you do?

If you have double back slashes `\\` in flyway.locations the script column in schema_version table removed the first character from the script name.

i.e. If flyway.locations = `D:\\Scripts\SQL` and  file name is 
V17.5.0.0062__PROIRL-50.sql - it will appear in the script column as
17.5.0.0062__PROIRL-50.sql (V - removed)

However if flyway.locations = D:\Scripts\SQL the it works fine.

**Comment by axelfontaine** [comment]
I am afraid something went wrong with the formatting of your issue report as I don't see any difference between both locations.

**Comment by mehta-m** [comment]
I've just Updated the issue.
