### ISSUE TITLE
Serious issue when dealing with delimiter changes

### ISSUE THREAD

**Issue by chb0github** [flyway/flyway#1790]
###### What version of Flyway are you using?

```
 flyway -v
Flyway 4.2.0 by Boxfuse
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
cli

###### What database are you using (type & version)?

mysql 5.6

###### What operating system are you using?

```
docker run -it mysql:5.6  /bin/bash -c "uname -a"
Linux 405b2ed3d485 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 GNU/Linux
```

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

We have scripts that are used to create stored procedures and such. In those scripts the delimiter changes in order to delimit the stored proc from the rest of the script. Other tools fail in the case. Flyway silently ignores/skips these and it isn't apparent until later on during migration that warnings occur about reference to non-existent stored procedures. 

Example:

```sql

DROP FUNCTION IF EXISTS format_time;

DELIMITER ||

CREATE FUNCTION format_time( picoseconds BIGINT UNSIGNED )
RETURNS varchar(16) CHARSET utf8
   DETERMINISTIC
BEGIN

  IF picoseconds IS NULL THEN

    RETURN NULL;

  ELSE 

    RETURN CAST(CONCAT(ROUND(picoseconds / 1000000000000, 2)) AS DECIMAL(10,6));

  END IF;

END;
||

DELIMITER ;
```

Here is the relevant ordering of the files:
```
$ grep -n format_time *
V33__DBA_functions.sql:13:DROP FUNCTION IF EXISTS format_time;
V33__DBA_functions.sql:17:CREATE FUNCTION format_time( picoseconds BIGINT UNSIGNED )
V35__DBA_views.sql:25:  DBA.format_time(events_statements.SUM_TIMER_WAIT) AS total_latency,
V35__DBA_views.sql:26:  DBA.format_time(events_statements.MAX_TIMER_WAIT) AS max_latency,
V35__DBA_views.sql:27:  DBA.format_time(events_statements.MIN_TIMER_WAIT) AS min_latency,
V35__DBA_views.sql:28:  DBA.format_time(events_statements.AVG_TIMER_WAIT) AS avg_latency,
V35__DBA_views.sql:29:  DBA.format_time(events_statements.SUM_LOCK_TIME) AS lock_latency,
```

In `V33__DBA_functions.sql:17` it is declared and defined and in `V35__DBA_views.sql:25` it's attempted to be used. So, this should present no issue of ordering

###### What did you expect to see?
> cat formattime.sql

```sql
DROP FUNCTION IF EXISTS format_time;

DELIMITER ||

CREATE FUNCTION format_time( picoseconds BIGINT UNSIGNED )
  RETURNS varchar(16) CHARSET utf8
DETERMINISTIC
  BEGIN

    IF picoseconds IS NULL THEN

      RETURN NULL;

    ELSE

      RETURN CAST(CONCAT(ROUND(picoseconds / 1000000000000, 2)) AS DECIMAL(10,6));

    END IF;

  END;
||

DELIMITER ;

cbongiorno at wa-cbongiorno-mba in /Volumes/dev/sterling/databases/scripts on flyway [!?$]
$ cat formattime.sql | mysql -h 127.0.0.1 -u root -pmy-secret-pw
mysql: [Warning] Using a password on the command line interface can be insecure.

mysql> SELECT count(*)  FROM information_schema.routines where ROUTINE_NAME ='format_time';
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.01 sec)

```

###### What did you see instead?
`WARNING: DB: FUNCTION DBA.format_time does not exist (SQL State: null - Error Code: 1305)`

**Comment by sjkyspa** [comment]
any solution? I have also encountered the same problem.

**Comment by chb0github** [comment]
Use mybatis. It has dedicated support (even though it's kind of hacky). The
problem is at the driver level. The best true fix would be to use the
mariadb driver if you're working with MySQL and submit a fix since it's
oss. The commercial driver is from Oracle

**Comment by axelfontaine** [comment]
Flyway 5.0 will ship with the latest MariaDB driver (2.2). There is unfortunately not much else we can do on our end.

**Comment by chb0github** [comment]
@axelfontaine The only way to handle this is client-side. One other project ([mybatis](https://github.com/mybatis/migrations/issues/95)) handles this in a kinda kludgy way by having their own delimiter-switch syntactic comments: `-- @DELIMITER \\` or whatever. 

Ideally a DB dialect approach is in order.

**Comment by axelfontaine** [comment]
@chb0github Flyway DOES parse this correctly and has done so for a long long time. Again the issue must be somewhere else, either your driver, DB, or your script. Are you sure the objects are actually being created in the DBA schema and not somewhere else?

**Comment by chb0github** [comment]
@axelfontaine I am 100% sure of it. I have tried flyway with our scripts and they fail exactly when stored procedures are created. The DB driver(s) in Java only support 1 delimiter. In the script, the command to change the delimiter is given and the driver ignores it - technically it shouldn't; that's what the mysql native client does correctly. 

To be fair: Flyway fails exactly as other migration tools fail and for the same reason. Unless it's accounted for client side it will always fail like this. The real solution is a fix in the driver itself but this issue has been around for an age.

you can take the script in this ticket and run it - it fails. If it doesn't give me the details and I will attempt to replicate. I didn't cut this ticket without having tried every trick I could think of.

**Comment by axelfontaine** [comment]
@chb0github I did take your script and ran it:

```

DROP FUNCTION IF EXISTS format_time;

DELIMITER ||

CREATE FUNCTION format_time( picoseconds BIGINT UNSIGNED )
RETURNS varchar(16) CHARSET utf8
   DETERMINISTIC
BEGIN

  IF picoseconds IS NULL THEN

    RETURN NULL;

  ELSE

    RETURN CAST(CONCAT(ROUND(picoseconds / 1000000000000, 2)) AS DECIMAL(10,6));

  END IF;

END;
||

DELIMITER ;

select format_time ( NULL );
```

And it completes correctly and without errors, as expected. As I said, did you check your default schema settings? Did you set `flyway.schemas` to `DBA`? If not, you either have to do that or prefix the objects you want to create in that schema with the schema name.

**Comment by chb0github** [comment]
I will dig into this more today. What version of flyway are you using and what mysql driver?
