### ISSUE TITLE
Deploying different migration scripts in different schema as part of a migration

### ISSUE THREAD

**Issue by Rajeswari-31** [flyway/flyway#1791]
###### What version of Flyway are you using?
4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
command-line / Jenkins

###### What database are you using (type & version)?
Oracle

###### What operating system are you using?
linux

###### What did you do?
trying to migrate multiple scripts that has to be deployed in different schema as part of a migration

###### What did you expect to see?
 different migration scripts needs to be deployed/migrated in different schema (Eg: file1 in schema1, file2 in schema2) as part of single migration

###### What did you see instead?
Its possible to deploy same script in different schema using flyway.schema property.

**Comment by axelfontaine** [comment]
This appears to be more a question suited for StackOverflow than an issue. Closing.
