### ISSUE TITLE
Upgrade jTDS to latest version to support SqlLocalDb

### ISSUE THREAD

**Issue by jmartasek** [flyway/flyway#1793]
At the moment flyway is shipped with jTDS 1.3.1 

The latest version as per [here](https://github.com/milesibastos/jTDS/releases) is 1.3.3

Starting from 1.3.2 the driver supports connection to SqlLocalDb with named pipes, which is perfect for local automated tests and / or development. How to do that is described on [StackOverflow](https://stackoverflow.com/questions/11345746/connecting-to-sql-server-localdb-using-jdbc)

I have replaced the jar on my local flyway install and it has been working well so far.

Thanks!

###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
command-line

###### What database are you using (type & version)?
SQL server SqlLocalDb

###### What operating system are you using?
Windows7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Tried to connect to SqlLocalDb using named pipes as described [here](https://stackoverflow.com/a/15176091/80941)

###### What did you expect to see?
Connection passed

###### What did you see instead?
Connection failed

**Comment by axelfontaine** [comment]
Hmm, that doesn't seem to be the official jTDS repo, nor is 1.3.3 available on Maven Central. Delaying until this is fixed upstream.

**Comment by jmartasek** [comment]
Good point. The jTDS development seems a bit stalled. 

So just for anyone having the same need of running against SqlLocalDB, this is the way to go.

**Comment by axelfontaine** [comment]
Flyway 5.0 will ship with the official Microsoft SQL Server JDBC driver, rendering this issue obsolete.
