### ISSUE TITLE
Repair: also correct migration type

### ISSUE THREAD

**Issue by wanglin0413** [flyway/flyway#1804]
###### What version of Flyway are you using?

flyway-4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

Mysql 5.8

###### What operating system are you using?

windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I wrote a V38__Change.sql and executed migrate，but now I want to change V38 to jdbc migrate, because it's difficult to implement new requirement with sql.  With repair I can only change checksum, but cant change type.

###### What did you expect to see?
With a command I can change version type instead of modifying with mysql states handly. and databases which already migrated to version higher than V38, should ignore new Jdbc-type V38 other than fail. 

###### What did you see instead?
There is no such command.

**Comment by wanglin0413** [comment]
I am a freshman in programming, and this is my first time to contribute to an open source project. I'm so excited to see my name in the releaseNotes. This is really a big inspiration for me. Thank u very much!

**Comment by axelfontaine** [comment]
@wanglin0413 No worries. It was an unusual scenario, but it made sense to include it. Thanks for the detailed report explaining your reasoning and situation. To be honest, this is often much more valuable than a pull request. Cheers!
