### ISSUE TITLE
please add rfc3339 to valid versions

### ISSUE THREAD

**Issue by yamb00** [flyway/flyway#1805]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

mysql-5.6.36

###### What operating system are you using?

Centos 7 in docker environment

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

https://tools.ietf.org/html/rfc3339

version file: V2017-10-23T10:10.15Z__test.sql

flyway migrate

###### What did you expect to see?

Successfully migrate

###### What did you see instead?

ERROR: Invalid version containing non-numeric characters. Only 0..9 and . are allowed. Invalid version: 2017-10-23T10:10.15Z

**Comment by axelfontaine** [comment]
Thanks for your suggestion. This is not something we are planning on doing. It is reasonably easy to translate an RFC3339 to a version supported by Flyway using bash or the language of your choice.
