### ISSUE TITLE
Oracle: Automatically enable support TNSNames aliases if TNS_ADMIN is set

### ISSUE THREAD

**Issue by cdavid15** [flyway/flyway#1806]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command Line

###### What database are you using (type & version)?

Oracle XE 11.2
Oracle Enterprise 12c

###### What operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Tried connecting to database using TNSNames within the database connection string url as follows:

jdbc:oracle:thin:@LOCAL_ORCL

Which is a valid connection string as per the Oracle documentation:

http://docs.oracle.com/cd/B19306_01/java.102/b14355/urls.htm#BEIJFHHB

The command I ran was:
```
flyway info -configFile=conf/flyway-dev.conf
```
With the configuration file as follows:

```
flyway.url=jdbc:oracle:thin:@LOCAL_ORCL
flyway.user=TEST
flyway.password=TEST
flyway.locations=filesystem:./sql/common,filesystem:./sql/dev
flyway.installedBy=FlywayDB Migration
flyway.table=__DB_MIGRATIONS
```

###### What did you expect to see?
Successful connection to the Database similar to the following:
```
Flyway 4.2.0 by Boxfuse

Database: jdbc:oracle:thin:@LOCAL_ORCL (Oracle 12.1)
```

###### What did you see instead?
```
Flyway 4.2.0 by Boxfuse

ERROR:
Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:@LOCAL_ORCL) for user 'TEST': IO Error: Unknown host specified
----------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08006
Error Code : 17002
Message    : IO Error: Unknown host specified
```

I have a local fix and have successfully been using it against Oracle Enterprise 12c Database and will submit a pull request in the coming days once I have made the documentation changes.

**Comment by PeeZu** [comment]
Hello,

According to Oracle documentation:

When using TNSNames with the JDBC Thin driver, you must set the oracle.net.tns_admin property to the directory that contains your tnsnames.ora file. 

Try with:
 
`flyway info -configFile=conf/flyway-dev.conf -Doracle.net.tns_admin=/directory/that/contains/tnsnames/file`

**Comment by cdavid15** [comment]
Yeah that's the change I have made although the flyway command line executable automatically picks up the path based on the TNS_ADMIN environmental variable and automatically passes the JVM property in.

https://github.com/flyway/flyway/compare/master...cdavid15:master

**Comment by axelfontaine** [comment]
Thank you very much for the suggestion. I really liked the idea of making it automatic and ending up adding this TNS_ADMIN autodetection to the core to make it available to all clients.

**Comment by cdavid15** [comment]
Excellent - it's definitely better suited at the core library level. Not the biggest of changes but a very useful one to those using Oracle databases.
