### ISSUE TITLE
Memory leak in getVersion()

### ISSUE THREAD

**Issue by Minras** [flyway/flyway#1809]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64)
Aurora DB on AWS

###### What operating system are you using?
Ubuntu 16.04.3 LTS
CentOS Linux 7 (Core)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
We have a heart-beat service on the server, part of it's result is a database migration version.
Here's a call we make (simplified): 
```
@Autowired
private Flyway flyway;
public String getSchemaVersion() {
  return flyway.info().current().getVersion().getVersion();
}
```
The service is called every few seconds (say 720 times per hour) and every hour the response time dropped by ~250ms. The issue was gone after restarting the server, but then it started piling up again.

Unfortunately, I don't have the memory profiling results.

We fixed the issue first by caching the first response from `getVersion()` and later by querying the database for the migration version.

###### What did you expect to see?
Same response, but without affecting the performance.

###### What did you see instead?
Performance decrease (described in `What did you do`)

**Comment by axelfontaine** [comment]
Flyway does not hold on to any static references and cleanly closes all closeable resources. I therefore strongly suspect your memory leak originates in your JDBC driver instead.
