### ISSUE TITLE
Test Flyway migrations without committing them

### ISSUE THREAD

**Issue by cristalp** [flyway/flyway#1812]
###### What version of Flyway are you using?
4.1.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
SQL Server

###### What operating system are you using?
RedHat Linux

###### Feature request
Right now we have four stages: development, integration, staging and production.
Flyway is not used in development, since we think that developers create the Flyway migration manually in a DB environment (e.g. DB Visualizer) and then create the Flyway migration.
However, we sometimes get nasty surprises, for instance several SQL commands that work interactively, but fail as Flyway script. (Then we have to insert GO statements for SQL server)
So it would be really nice if databases that support transactions for DDL could test their Flyway scripts. Ideally, this could be done with the Maven plugin during the build: I write a new Flyway script, which is check checked by our CI build server: The Flyway script is new, so the Maven plugin executes it and any other new scripts agains a configured database. All Flyway scripts are run in **one transaction** which is rolled back after the check.

**Comment by axelfontaine** [comment]
Wouldn't the `group` setting be enough to give you the same assurance? In that case all migration are run against the DB. If any statement fails, they are all rolled back.

**Comment by cristalp** [comment]
The `group` option is already a big step towards the right direction. Basically if there was a `commit` flag (defaulted to `true`), that would be all I need.
The problem is that of course DB and software go together. But I'd like to test the Flyway migrations when they are checked in, without necessarily executing them, because otherwise I would be forced to install the software as well.

**Comment by axelfontaine** [comment]
Can't you simply migrate a test schema for that? This should give you want you want.

**Comment by cristalp** [comment]
In principle that would work, but it would mean yet another DB stage (we alredy have five of them) to manage...

**Comment by axelfontaine** [comment]
Since Flyway can automatically create schemas for you, all this takes is a configuration setting. I have the feeling that even though the idea of the `commit` flag sounds simple, it will be full of edge cases (non-transactional statements come to mind) that will further diminish the usefulness of this. Certainly now that DB instances can be easily and reliably provisioned on-demand using Docker. I therefore see the chances of this being implemented close to 0. Closing for now.
