### ISSUE TITLE
Java-based repeatable migration is only run once

### ISSUE THREAD

**Issue by dhardtke** [flyway/flyway#1814]
###### What version of Flyway are you using?
4.2.0 (latest)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle

###### What database are you using (type & version)?
MariaDB 10.2.8

###### What operating system are you using?
Windows 10 1709

###### What did you do?
Suppose I have the following Java based migration:
```java
public final class R_Migration implements JdbcMigration, MigrationInfoProvider {
    @Override
    public void migrate(final Connection c) throws Exception {
        System.err.println("I am running");
    }
    
    @Override
    public MigrationVersion getVersion() {
        return null;
    }
    
    @Override
    public String getDescription() {
        return "R_Migration";
    }
}
```

###### What did you expect to see?
I would expect the migration to run as repeatable migration, i.e., as a migration that is executed every time I run flywayMigrate.

###### What did you see instead?
The migration is only run once.

**Comment by axelfontaine** [comment]
Change it as follows to get the behavior you want:

```java
public class R_Migration implements JdbcMigration, MigrationInfoProvider, MigrationChecksumProvider {
    private static int count;

    @Override
    public void migrate(final Connection c) throws Exception {
        System.err.println("I am running");
    }

    @Override
    public MigrationVersion getVersion() {
        return null;
    }

    @Override
    public String getDescription() {
        return "R_Migration";
    }

    @Override
    public Integer getChecksum() {
        return ++count;
    }
}
```

**Comment by dhardtke** [comment]
That is not really translating to the functionality I want:

Using a counter, like you propose, would require the counter to be consistent across all migrations, otherwise the schema_migration table would get flooded with the same repeated migrations over and over again. Suppose I could just provide a map somewhere where I store a checksum for each migration I want to execute.

**Comment by axelfontaine** [comment]
Well obviously the counter is only there to illustrate how to force Flyway to rerun the migration. Feel free to use whatever mechanism suits you to achieve the rate of change you desire. You can also simply return a constant and update it every time you want Flyway to rerun the migration.

**Comment by dhardtke** [comment]
Okay, I tested this approach and this is not really what I wanted.

![76955818_2017-11-18_02-18-07](https://user-images.githubusercontent.com/1360135/32975347-bdb0ae22-cc06-11e7-87c1-d97e6c93faf8.png)

Every time I re-execute the migrations, a new row is appended for each migration inside the `schema_version` table.

This is my `getChecksum()` implementation:

```java
@Override
    public Integer getChecksum() {
        return Math.toIntExact(System.currentTimeMillis() / 1000);
    }
```

Is this now a bug or simply the way it's meant to be?

Thanks.

**Comment by axelfontaine** [comment]
Works as designed. Flyway records every execution of a migration in that table in order to keep a clear audit trail of the changes that took place in that schema.

**Comment by dhardtke** [comment]
It doesn't behave like that for repeatable SQL-migrations.

So, there is *no* way to replicate the same behavior of SQL migrations in Java-based migrations I guess.

For a repeatable SQL-based migrations, the `schema_version` table contains only one row, where the checksum column is always `0` and that particular row gets _updated_, rather than a new row getting _added_, each time it is executed.

**Comment by NicoTexas** [comment]
What about generating a random checksum in your MigrationChecksumProvider?

**Comment by axelfontaine** [comment]
@dhardtke Yes it does. Just check it, you'll see.

**Comment by dhardtke** [comment]
Thanks guys. You were right, axelfontaine: For repeatable SQL-based migrations Flyway behaves exactly the same as for Java migrations, if and only if the checksum changes.

I did just implement some sort of CRC generation that calculates the checksum for each actual Java class.
