### ISSUE TITLE
Expose method calculateChecksum for SqlMigrationResolver

### ISSUE THREAD

**Issue by camleb** [flyway/flyway#1816]
###### What version of Flyway are you using?

4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

MySQL

###### What operating system are you using?

Linux

###### What did you do?

We are developing an open source project based on Apache 2.0 Licence. In that licence we have to declare the date of the copyright in the header of each file. As the date is changing (depending on when we declare the source code to the authority) the header is changing as well and thus the checksum of all sql files.
We would like to change the method that calculate the checksum to exclude the first comments lines.
But the method is static in the SqlMigrationResolver class. 
How can we deal with this problem ?
Is it possible to expose the method ?
Thank you for your reply.

**Comment by axelfontaine** [comment]
The entire class is currently part of Flyway's private API. We'll consider this should we make it public in the future.

**Comment by MikielAgutu** [comment]
@camleb The simpler solution is to run an ad-hoc `repair` whenever the license changes. No one else has asked for this in 2+ years, so closing.
