### ISSUE TITLE
Multiline RULE declarations are not parsed correctly

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#183]
_Original author: p.malo...@gmail.com (May 31, 2013 16:03:22)_

Using PostgreSQL 9.2.
Given a migration that creates a multiline rule:
CREATE OR REPLACE RULE my_rule AS
ON DELETE TO some_table
DO ALSO
(
   DELETE FROM some_other_table WHERE some_other_table.id=old.id;
   DELETE FROM some_other_table2 WHERE some_other_table2.id=old.id;
);

This conforms to the syntax as stated here: http://www.postgresql.org/docs/9.2/static/sql-createrule.html

Flyway returns the following error:
ERROR: com.googlecode.flyway.core.api.FlywayException: Error executing statement at line 14: CREATE OR REPLACE RULE my_rule AS
ON DELETE TO some_table
DO INSTEAD
(
   DELETE FROM some_other_table WHERE some_other_table.id=old.id
ERROR: Caused by org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position?: 136
ERROR: FlywayException: Migration of schema &quot;data&quot; to version 4.0.1.1 failed! Changes successfully rolled back.
ERROR: Occured in com.googlecode.flyway.core.command.DbMigrate.applyMigration() at line 275

From what I understand of Flyway's parser, as soon as it detects the ';' delimiter, it ends the statement and tries to run it, but in this case the statement is not completely parsed.
I believe this is a rather rare syntax where nested statements are not surrounded by dollar-quotes in PostgreSQL (like FUNCTIONs).

Thanks,
Patrick Malouin

_Original issue: http://code.google.com/p/flyway/issues/detail?id=507_

**Comment by ShiloHaendler** [comment]
Hi,

any progress on that matter?
I'm running flyway 3.2.1 with PostgreSQL 9.3, and that's still happening.

from our side, his seems to be a blocker from using flyway :(

Thanks,
Shilo

**Comment by axelfontaine** [comment]
@ShiloHaendler You are free to sponsor this fix if you want to have this sooner: http://flywaydb.org/support/

**Comment by kjkrol** [comment]
Workaround: Put a comment after each semicolon and remove semicolon from the last line.
eg.
```
CREATE OR REPLACE RULE my_rule AS
ON DELETE TO some_table
DO ALSO
(
DELETE FROM some_other_table WHERE some_other_table.id=old.id; -- comment
DELETE FROM some_other_table2 WHERE some_other_table2.id=old.id
);
```

**Comment by ShiloHaendler** [comment]
Thanks for the tip :)

**Comment by pmefford** [comment]
Any work on this issue? 
We are getting into flyway and working on our workflow in an agile environment.  Where changes may be applied multiple times during development but once on Production environments.  

I was going to purpose writing anonymous functions to allow you to perform checks before executing scripts but that won't work with this bug.  
```
DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM information_schema.columns WHERE table_schema='public' AND table_name='users' AND column_name='email') THEN
     ALTER TABLE users ADD email VARCHAR(256);
ELSE 
  RAISE NOTICE 'USERS already has email column';
END IF;
END
$$ language plpgsql;
```

Any suggestions?  the "; -- " tip doesn't work in this case.    Maybe my workflow strategy is all wrong.  We were going to do a Migration per ticket and make them "repeatable" after establishing a base version.
