### ISSUE TITLE
Script length issue applying against Azure SQL databases

### ISSUE THREAD

**Issue by helloserve** [flyway/flyway#1830]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? 
Command-Line

###### What database are you using (type & version)?
Microsoft SQL Azure (RTM) - 12.0.2000.8   Sep 19 2017 11:48:47   

###### What operating system are you using?
Windows 10

###### What did you do?
We constructed a rerunable script to maintain data in a template system. Our script was structured as follows, it did not include any GO statements:

```
DECLARE all table variables (4 in total) ~4 lines
INSERT INTO all the table variables the data to maintain. ~70 lines
MERGE statements for all the tables in question using the table variables as sources. ~125 lines

```

The command is
`flyway migrate -url=jdbc:jtds:sqlserver://xxxx.database.windows.net/xxxx -locations=filesystem:.\db -user=xxxx -password=xxxx`

###### What did you expect to see?
I expected the migration to complete flawlessly as tested against local database servers, and manually against Azure using SQL Server Management Studio.

###### What did you see instead?
```
Migration R__ComponentTemplates.sql failed
------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : I/O Error: Connection reset
Location   : ./db/R__ComponentTemplates.sql (D:\Projects\xxx\db\R__ComponentTemplates.sql)
Line       : 1
Statement  : DECLARE @Template TABLE (Id INT, Name NVARCHAR(500), Description NVARCHAR(MAX), IsActive BIT)
```

###### Our workaround to resolve the issue
We altered the structure of the script to the following to reduce the line count between GO statements:

```
DECLARE table variable
INSERT INTO all table variable
MERGE statements for the table in question using the table variable as sources
GO

DECLARE table variable
INSERT INTO table variable
MERGE statements for the table in question using the table variable as sources
GO

DECLARE table variable
INSERT INTO table variable
MERGE statements for the table in question using the table variable as sources
GO

DECLARE table variable
INSERT INTO table variable
MERGE statements for the table in question using the table variable as sources
GO
```

This solved the issue, and proves that FlyWay has a buffer problem streaming long sections of code to a remote server over lower than LAN latency connections. Reducing the sections between GO statements to < 50 lines works. This is not the first script that we have had to do this for. All our scripts worked 100% using SSMS.

**Comment by axelfontaine** [comment]
Flyway only passes these statements to the JDBC driver, which is where the issue must lie. Flyway 5.0 will ship with the official Microsoft SQL Server driver instead of jTDS, so hopefully this should sort itself out automatically, as unfortunately there is not much else we can do on our end.

**Comment by helloserve** [comment]
What is the projected release date of 5.0?

**Comment by axelfontaine** [comment]
End of the month

**Comment by helloserve** [comment]
So I just downloaded 5.0.2, but this issue persists. The documentation (https://flywaydb.org/documentation/database/sqlserver) does not show another URL format other than through JDBC. It is just not up to date yet? What is the native MS SQL Driver format for command line? Thanks.
