### ISSUE TITLE
Whitespace/Formatting and migration checksums.

### ISSUE THREAD

**Issue by DenEwout** [flyway/flyway#1837]
###### What version of Flyway are you using?
3.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API/Spring Boot

###### What database are you using (type & version)?
PostgreSQL 9.5

###### What operating system are you using?
Windows

###### What did you do?
Another developer committed code which accidentally reformatted the flyway migration scripts.

###### What did you expect to see?
If no SQL changes are made, flyway should (in my opinion) work without migration validation errors. 

###### What did you see instead?
A migration validation error (different checksum)

When working on a project with multiple people and multiple code formatting settings, it becomes easy to commit code which makes formatting changes to migration scripts that already have been applied on databases. What exactly is the reason for taking whitespace (spacing, newlines, etc...) into account in the migration checksum? Would it be possible to take a checksum of the content of the scripts without taking formatting into account?

Thanks in advance.

**Comment by axelfontaine** [comment]
Yes it is certainly possible. However this would require (besides being very careful in NOT ignoring whitespace where it matters like string literals etc) every Flyway installation out there to recompute its checksums, for only a small added benefit. We may consider this some day, but for now simply stick to the rule: don't modify a script once it has been applied.

**Comment by DenEwout** [comment]
Thanks for your feedback. Of course my current solution is to stick to that rule! 👍

This behavior could be seen as a separate checksum (so no recomputing would be required) and a feature flag/config parameter that says, if the exact checksum fails, but the other succeeds, don't throw a migration error.

**Comment by adrianmsmith** [comment]
I have a related issue, to do with newlines.

If I check out my project on Linux, create a Docker container and deploy it, everything works fine. If I check out my project on Windows, Git by default "helpfully" changes the newlines on all text files to be Windows newlines (Subversion doesn't do this by default.) So when I create the Docker container and deploy it, the server complains that all checksums are different, understandably.

Of course Git could be taught to not change the newlines. Nevertheless, like the original poster of this issue, I feel if the migration file hasn't fundamentally changed, it should "just work".

I don't really have a proposal for how this could work with existing installations either. I'm just chiming in here that I have a similar problem.

**Comment by axelfontaine** [comment]
@adrianmsmith This has already been addressed in #253

**Comment by adrianmsmith** [comment]
Ah, I searched for such an issue but didn't find it, so I posted here, I'm sorry. Thanks for the link.

**Comment by MikielAgutu** [comment]
This seems to be more trouble than it's worth.
