### ISSUE TITLE
Unable to instantiate a Java callback using CLI

### ISSUE THREAD

**Issue by jocelynduc** [flyway/flyway#1839]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
CLI and Maven 3.3.3

###### What database are you using (type & version)?

Oracle 12

###### What operating system are you using?

Docker container and Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I use flyway command-line in a docker container to apply my migration scripts. I now have to add a Java callback in my implementation. The callback can successfully be detected and launch through the flyway-maven-plugin, with a <callback> definition in the pom.xml. I generate a JAR of this project.

I now want to run it with the command line. The following command works, my SQL migrations are applied

`flyway repair migrate      -locations=path/to/sql/migration     -url=...`

If I add my callback, in this way, it tells me the following error

`flyway repair migrate      -locations=path/to/sql/migration      -callbacks=com.company.MyCallback     -url=...`

_Unable to instantiate class "com.company.MyCallback"_

I also tried the jarDirs option, but same error

`flyway repair migrate      -locations=path/to/sql/migration      -jarDirs=/folder/containing/the/jar/i/generated     -callbacks=com.company.MyCallback     -url=...`

###### What did you expect to see?

My callback to be executed

###### What did you see instead?

Flyway 4.2.0 by Boxfuse
ERROR: Unable to instantiate class: com.company.MyCallback

**Comment by Ramblurr** [comment]
Is this a confirmed bug? Is there no known workaround to execute callbacks with the flyway cli or gradle tasks?

**Comment by axelfontaine** [comment]
I am unable to reproduce this. Please try again with Flyway 5.0.3 and add `-X` to also print debug output.

If the problem persists, please share the *exact* steps you took as well as the full debug output.

**Comment by patrit** [comment]
My 2 cents: make sure that com.company is in your classpath e.g. -locations=com.company

**Comment by axelfontaine** [comment]
Closing due to lack of response.
