### ISSUE TITLE
Problems building on Windows: Class in different directory than declared: sybaseASE

### ISSUE THREAD

**Issue by MSchmidke** [flyway/flyway#1843]
Hi,

I'd like to build flyway from source, but I've a small problem on Windows.

###### What version of Flyway are you using?
Commit 43ee2b

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
./.

###### What database are you using (type & version)?
./.

###### What operating system are you using?
Windows 10

###### What did you do?
mvn clean install

###### What did you expect to see?
SUCCESS

###### What did you see instead?
[ERROR] Manifest org.flywaydb:flyway-core:jar:0-SNAPSHOT : Class in different directory than declared. Path from class name is org/flywaydb/core/internal/dbsupport/sybasease/SybaseASEDbSupport.class but the path in the jar is org/flywaydb/core/internal/dbsupport/sybaseASE/SybaseASEDbSupport.class from 'Jar:classes'

**Comment by axelfontaine** [comment]
No idea about that old commit. The latest commit builds fine on all platforms. Just use that.

**Comment by MSchmidke** [comment]
Oops. Since I cloned I was so busy setting up a Linux development machine (since I thought Windows might be the problem) that I didn't realize that it was just that exact single commit which caused the Windows problem. Sorry!
