### ISSUE TITLE
Pre- / Post-check schema minimal DDL (owner / table / row) against offline dump

### ISSUE THREAD

**Issue by chatelao** [flyway/flyway#1844]
###### What version of Flyway are you using?

None

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

None

###### What database are you using (type & version)?

Oracle

###### What operating system are you using?

Windows / Linux

###### What did you do?
Listen to a nice presentation about flyaway, telling that schema-diff can only be done with online databases.

###### What did you expect to see?

A check before and after migrating if all expected tables & columns a presend.

Establish expected references (during script developement)
======================================
1.) Dump the "Pre-DDL" of the DB to a file=> Add to an "pre-condition" file / folder
2.) Apply the migration from "Pre" to "Post"
3.) Dump the "Post-DDL" of the DB to a file => Add to an "post-condition" file / folder

Verify expected references 
=================
1.) Apply the migration with "Pre" and "Post" checks
a) Check if the current table / rows match the expected post-condition DDL
=> In case of an error, all missing / superfluous table / rows are printed
b) Apply the migration from "Pre" to "Post"
c) Check if the resulting table / rows match the expected post-condition DDL
=> In case of an error, all missing / superfluous table / rows are printed

###### What did you see instead?

No such feature(s) :-)

**Comment by axelfontaine** [comment]
This is actually quite complex to implement and I am not fully convinced it is worth it. Also because Flyway handle more than DDL. Very often it is also used for reference data.

**Comment by MikielAgutu** [comment]
Closing for lack of interest.
