### ISSUE TITLE
Oracle statement fails when it contains DATE'11/29/2017' and no space in between

### ISSUE THREAD

**Issue by Nthalk** [flyway/flyway#1846]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven plugin

###### What database are you using (type & version)?
Oracle 11G

###### What operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
```
CREATE OR REPLACE PACKAGE DEMO_P_FLYWAYBUG
IS
  FUNCTION F_MAGIC_DATE
    RETURN DATE;
END DEMO_P_FLYWAYBUG;
/

CREATE OR REPLACE PACKAGE BODY DEMO_P_FLYWAYBUG
IS
  FUNCTION F_MAGIC_DATE
    RETURN DATE
  IS BEGIN
    RETURN DATE'11/29/2017';
  END F_MAGIC_DATE;

END DEMO_P_FLYWAYBUG;
/
```

###### What did you expect to see?
That the USER_SOURCE for the package body object ends with 'END DEMO_P_FLYWAYBUG'
and that the package compiles.

###### What did you see instead?
That the USER_SOURCE for the package body object ends with '/'
and that the package does not compile.

I traced this bug to https://github.com/flyway/flyway/blob/df9e7560427c3586905cfaa69f54c64cad3fe9eb/flyway-core/src/main/java/org/flywaydb/core/internal/database/SqlStatementBuilder.java#L193 where it thinks it is in a multiline string.

This is because the `DATE` cast keyword is allowed before the strings. This is fixed with a space between `DATE` and the subsequent quote.

This can easily be fixed by adding `DATE` to the following list https://github.com/flyway/flyway/blob/df9e7560427c3586905cfaa69f54c64cad3fe9eb/flyway-core/src/main/java/org/flywaydb/core/internal/database/oracle/OracleSqlStatementBuilder.java#L37

**Comment by axelfontaine** [comment]
Good catch and excellent analysis! That was indeed the issue. Thank you very much. Fixed!
