### ISSUE TITLE
Documentation is not clear about the definition of missing and future migration

### ISSUE THREAD

**Issue by Jidehem** [flyway/flyway#1847]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven

###### What database are you using (type & version)?
(Oracle)

###### What operating system are you using?
(WIndows)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I removed a migration, then ran _migrate_ with `ignoreMissingMigrations=true`.

###### What did you expect to see?
A successful migration that do nothing

###### What did you see instead?
The following error 

> Validate failed: Detected applied migration not resolved locally: _version_x_

###### Analysis
See [this knowledge sharing](https://stackoverflow.com/questions/47568746/why-does-flyway-ignoremissingmigrations-is-not-taken-into-account/47568747#47568747).
The problem comes from the definition of _missing migration_.
- either define (and document !) missing migration as a migration that is not anymore present but there is a newer available migration (=> else it's a future migration)
- either change logic to effectively ignore this case too. However, I feel that this may conflict with the definition of future migration. Thus first solution (improve documentation) is probably the best.

**Comment by axelfontaine** [comment]
Good point! I agree it is a documentation issue. We have now clarified it with:

> Note that if the most recently applied migration is removed, Flyway has no way to know it is missing and will mark it as future instead.
