### ISSUE TITLE
What about soft lock to avoid lock timeout

### ISSUE THREAD

**Issue by kakawait** [flyway/flyway#1856]
I would know if you're interested by creating an alternative `LOCK` than _native_. I mean something different that `SELECT ... ON UPDATE` (for example for `MySQL`)  to avoid 

```
Lock wait timeout exceeded; try restarting transaction
```

Since default `innodb_lock_wait_timeout` is `50` sec.

The main advantage of _soft lock_ is you can control timeout at code level and not database level. But how can _soft lock_ work to get the same requirement than _native lock_?

(Just before starting, _soft lock_ is using _native lock_ but differently)

0. (pre-req) metadata table should be updated to add 3 columns: `lock_id`, `lock_status` & `heartbeat` (heartbeat is used for watchdog mechanism to avoid infinite or really too long lock)
1. Lock metadata table with native lock feature in order to update the lock table
2. Update the metadata table to set locked `lock_id` & `lock_status`
3. Perform operation if you acquired the lock
    Else wait until `lock_status` is equals to _UNLOCK_

It's a bit abstract, just a big picture, but I already prototype something working.

I mainly want to know if you could be interested by such alternative lock that is vendor-less, if yes I could propose a PR to expose you my version of _soft lock_.

**Comment by axelfontaine** [comment]
Thanks for asking. First of all note that we don't use `SELECT ... FOR UPDATE` with MySQL. See https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLNamedLockTemplate.java#L91

Using that approach we can already control the lock timeout in code. I am not sure hand-rolling our own alternative would be the right choice. I will therefore kindly decline your offer.

**Comment by kakawait** [comment]
@axelfontaine Thank for feedback.

Sorry I read wrong code I though it was https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLTable.java#L53

So if it's already possible! No need much so I completely understand. 

I will document me more about code on https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLNamedLockTemplate.java#L91
