### ISSUE TITLE
Custom version computation strategy for Sql migrations

### ISSUE THREAD

**Issue by mdewilde** [flyway/flyway#1858]
As of now, there seems to be no straightforward way to add a custom strategy for creating a version String for a specific SQL migration script.

However, the codebase reveals the interface `org.flywaydb.core.api.migration.MigrationInfoProvider`. That interface seems to meet a similar demand but of course is limited to Java classes that can implement that interface. 

Internally, SQL migrations have their version computed by `org.flywaydb.core.internal.resolver.MigrationInfoHelper`. For this logic, API users can only provide a prefix, separator and suffix, through the methods:

- `org.flywaydb.core.Flyway.setSqlMigrationPrefix(String)` 
- `org.flywaydb.core.Flyway.setSqlMigrationSeparator(String)` 
- `org.flywaydb.core.Flyway.setSqlMigrationSuffixes(String)`

It would be very helpful and provide a lot of flexibility if there was a way to override that version computation strategy. Internally, this could be accomplished without too much trouble by moving the current logic into a default implementation of the interface to be defined. It would then be up to the API user to add their own logic by overriding with their own implementation, if so desired.

The user could choose, for instance, to have the version string not only depend on the filename, but on the hierarchy in which the file resides. Alternatively, the user could implement logic to extract the version string from the file itself. Or the user could implement something else entirely. The point would be to provide the user with the flexibility to accomplish this. 

My question is twofold:
1. would you consider adding this as a feature?
2. is this something you would accept pull requests for?

**Comment by axelfontaine** [comment]
Yes, this is something that can be considered. I must admit that we are usually very conservative about adding interfaces to the public API, as this represents a lot term commitment to our users, which in turn means that we both lose flexibility and have higher maintenance overhead.

So if you do consider sending a pull request, please discuss your design in detail in this issue first to avoid disappointment of not having it merged later.

**Comment by mdewilde** [comment]
I'd work in the following direction:

- add interface `org.flywaydb.core.api.resolver.SqlVersionResolver` with single method `public String extractVersion(LoadableResource resource)`
- add implementation `org.flywaydb.core.api.resolver.BaseSqlVersionResolver`, which would contain (part of) the version extraction logic now in `org.flywaydb.core.internal.resolver.MigrationInfoHelper.extractVersionAndDescription()`
- add field `private final BaseSqlVersionResolver baseSqlVersionResolver` to `org.flywaydb.core.Flyway`
- encapsulate fields `sqlMigrationPrefix`, `sqlMigrationSeparator` and `sqlMigrationSuffixes` in `baseSqlVersionResolver` & channel existing getters and setters to that instance
- add field `private SqlVersionResolver customSqlVersionResolver` to Flyway, along with getter and setter.
- add method `SqlVersionResolver getSqlVersionResolver` to `org.flywaydb.core.api.configuration.FlywayConfiguration` & implementation in `Flyway`. This getter would return `baseSqlVersionResolver` unless  `customSqlVersionResolver` is set
- at the single call to `MigrationInfoHelper.extractVersionAndDescription()`, in `org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver`, use the `SqlVersionResolver` from the available `FlywayConfiguration` to determine the version for a specific script

Additional thoughts:
- choosing `LoadableResource` as implementations are returned for both types of resource (classpath and filesystem)
- `LoadableResource` fully qualified is `org.flywaydb.core.internal.util.scanner.LoadableResource`. The `internal` package part may be a problem, as it was probably not intended to be part of a public API.
- an alternative to returning a `String` could be to return a `org.flywaydb.core.api.MigrationVersion` from `SqlVersionResolver.extractVersion(LoadableVersion)`. Doing this would force the user to ensure their version extraction logic fits with existing Flyway logic.
- the name `SqlVersionResolver` may not be ideal, as the name resolver is already used by a number of classes
- instead of simply relying checking for nullness of `customSqlVersionResolver`, an explicit flag along the lines of `private boolean skipDefaultCallbacks` and `private boolean skipDefaultResolvers` could be added
- it would be necessary to document that `sqlMigrationPrefix`, `sqlMigrationSeparator` and `sqlMigrationSuffixes` are not taken into account when using the `customSqlVersionResolver`

**Comment by DoodleBobBuffPants** [comment]
Duplicate.
