### ISSUE TITLE
Gradle plugin not published successfully

### ISSUE THREAD

**Issue by tpodom** [flyway/flyway#1862]
###### What version of Flyway are you using?
5.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Gradle plugin

###### What database are you using (type & version)?

Postgresql 9.6

###### What operating system are you using?
MacOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Attempted to upgrade to Gradle 5.0.1 but got an error that the plugin could not be located.  Clicking on the link to the jar from https://plugins.gradle.org/m2/gradle/plugin/com/boxfuse/client/flyway-release/5.0.1/ results in an error. 

###### What did you expect to see?

Successful download

###### What did you see instead?
https://plugins-artifacts.gradle.org/gradle.plugin.com.boxfuse.client/flyway-release/5.0.1/e731240c05ef96b2f99f6831c7e3a144c3cba2047c7c0474f9380523f2c9e43f/flyway-release-5.0.1.jar

```<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
gradle.plugin.com.boxfuse.client/flyway-release/5.0.1/e731240c05ef96b2f99f6831c7e3a144c3cba2047c7c0474f9380523f2c9e43f/flyway-release-5.0.1.jar
</Key>
<RequestId>74881D74B12A0F4C</RequestId>
<HostId>
/JPyavxY0r0e3PPDQwcWHrpwFDJ76wP5J/rtUS5jwoU5v1idhat+N/61lcdgaIrfpOfaRfuPyMg=
</HostId>
</Error>```

**Comment by alexanderjohn** [comment]
Had the same issue on both 5.0.0 and 5.0.1

my gradle file snippet:
```
plugins {
    id 'application'
    id 'eclipse'
    id 'java'
    id 'org.flywaydb.flyway' version '5.0.1'
}
// ...
```

response:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'tt'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find gradle.plugin.com.boxfuse.client:flyway-release:5.0.1.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/com/boxfuse/client/flyway-release/5.0.1/flyway-release-5.0.1.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/boxfuse/client/flyway-release/5.0.1/flyway-release-5.0.1.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CONFIGURE FAILED

Total time: 5.361 secs
```

**Comment by axelfontaine** [comment]
Arrghh! You are right! Even though it shows up at https://plugins.gradle.org/m2/gradle/plugin/com/boxfuse/client/flyway-release/5.0.1/ and https://plugins.gradle.org/plugin/org.flywaydb.flyway

Time to investigate what happened...

**Comment by axelfontaine** [comment]
An update to the Gradle plugin publishing plugin fixed the issue. Flyway Gradle Plugin 5.0.2 is now available.

**Comment by tpodom** [comment]
Thank you!  I just confirmed 5.0.2 downloads successfully for me with Gradle.
