### ISSUE TITLE
Box.json to support CommandBox

### ISSUE THREAD

**Issue by mborn319** [flyway/flyway#1864]
Would it be possible to create a box.json file and publish this package on [ForgeBox](https://www.forgebox.io/)? This would support future ColdFusion development through the [CommandBox](https://www.gitbook.com/book/ortus/commandbox-documentation/details) package manager.

To quote the Commandbox [Creating Packages](https://commandbox.ortusbooks.com/content/packages/creating_packages/creating_packages.html) guide: 

```
# Create user (first time only)
CommandBox> forgebox register username password your@email.com firstName lastName
CommandBox> forgebox login username password

# Create package/git repo
CommandBox> mkdir mypackage --cd
CommandBox> !git init
CommandBox> package init slug=my-package type=modules location=gitUser/my-package
CommandBox> bump --minor message="Initial Commit"

# Publish it
CommandBox> !git remote add origin <git url>
CommandBox> !git push
CommandBox> publish

# Viewable and installable by the world!
CommandBox> forgebox show my-package
CommandBox> install my-package
```

**Comment by axelfontaine** [comment]
Can you help me understand a bit better what the exact benefit of doing this would be?

**Comment by mborn319** [comment]
@axelfontaine Sorry, yep! CommandBox is a package manager (like Composer or NPM) written in and for the [Adobe Coldfusion](http://www.adobe.com/products/coldfusion-family.html) programming language.

Adding this one `box.json` file would benefit Flyway in that CommandBox users could name Flyway as a dependency in their projects, and not have to install it manually. In CommandBox, running `install` would run through my package's dependencies and install them all for me by downloading them from the Forgebox package repo.

Something like
```json
{
    "name":"FlywayDB",
    "version":"5.0.2",
    "author":"Axel Fontaine",
    "location":"",
    "directory":"",
    "createPackageDirectory":true,
    "packageDirectory":"",
    "homepage":"https://flywaydb.org",
    "documentation":"",
    "repository":{
        "type":"Git",
        "URL":"https://github.com/flyway/flyway"
    },
    "bugs":"",
    "slug":"flywaydb",
    "shortDescription":"Database Migrations Made Easy",
    "description":"A database migration tool for Linux, Mac and Windows. Evolve your database schema easily and reliably across all your instances.",
    "instructions":"",
    "changelog":"",
    "type":"",
    "keywords":[
        "database",
        "migrations",
        "migrate"
    ],
    "private":false,
    "engines":[
        {
            "type":"",
            "version":""
        }
    ],
    "defaultEngine":"lucee@5.2",
    "projectURL":"",
    "license":[
        {
            "type":"",
            "URL":""
        }
    ],
    "contributors":[
        
    ],
    "devDependencies":{
    },
    "dependencies":{
    },
    "scripts":{
    }
}
```

**Comment by mborn319** [comment]
So, right now, I can't (easily) use Flyway in Bitbucket Pipelines until I figure out some simple way to get it installed in my CI "build" script. Since I'm using CommandBox as a package manager, it would make sense to name Flyway as a dependency, let CommandBox download and install, and my build script will instantly build the database and run tests.

The other option is writing a simple script to download the Flyway commandline executable and save it to my /usr/bin folder somewhere, but this would be easier IMO.

**Comment by mborn319** [comment]
PS. I'd be happy to submit a pull request for this - it's a simple JSON file, not too hard. The more difficult part is making it work on multiple distributions. I don't know if you would need a separate ForgeBox package for each?

**Comment by axelfontaine** [comment]
Thanks for the details. I certainly sounds like this is more work than just "adding a json file", yet the benefits will be tiny at best as the current alternatives are very easy to implement. You can either use a one-liner consisting of curl+tar+ln or Docker (see https://hub.docker.com/r/boxfuse/flyway/).

Won't fix.
