### ISSUE TITLE
New option to allow for 'Ignored' migrations in 'validate' command: 'ignoreIgnoredMigrations'

### ISSUE THREAD

**Issue by bkaminnski** [flyway/flyway#1865]
###### What version of Flyway are you using?

4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

Oracle 12C

###### What operating system are you using?

Windows Server 2012

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
###### What did you see instead?

**I would like to be able to ignore "Ignored" migrations when running "validate" command.**

These are migrations that were added in between already migrated migrations in this version. For example: we have migrations available on the classpath with versions from 1.0 to 3.0. The schema history table indicates that version 1 was finished on 1.0.15, and the next one was 2.0.0. But with the next release a new migration was added to version 1: 1.0.16. Such scenario is ignored by migrate command, but by default is rejected by validate. When ignoreIgnoredMigrations is enabled, such case will not be reported by validate command. This is useful for situations where one must be able to deliver complete set of migrations in a delivery package for multiple versions of the product, and allows for further development of older versions.

**Comment by bkaminnski** [comment]
I just made a pull request for this new feature: [https://github.com/flyway/flyway/pull/1866](https://github.com/flyway/flyway/pull/1866).

**Comment by axelfontaine** [comment]
Fixed with pull request. Thanks!
