### ISSUE TITLE
SqlServer 2012 SP4 is still supported until 2022

### ISSUE THREAD

**Issue by reitzmichnicht** [flyway/flyway#1867]
Please enable SQLServer version 11 in Flyway OpenSource 5.0.2 again.
SQL Server 2012 SP4 has still support by Microsoft until 12.07.2022

This is a major issue for us.

**Comment by axelfontaine** [comment]
As you can see from https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20SQL%20Server%202012%20service%20pack%204

The Mainstream Support End Date for Microsoft SQL Server 2012 Service Pack 4 was 2017-07-11.
The 2022-07-12 date is for extended support.

The easiest way to resolve this is either upgrading SQL Server to 2014 with mainstream support by Microsoft (and Flyway Community Edition) until 2019-07-09 or upgrade to Flyway Enterprise edition which continues to support all SQL Server versions all the way back to 2008.
