### ISSUE TITLE
checksum overflow

### ISSUE THREAD

**Issue by ruruko** [flyway/flyway#1874]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
command-line

###### What database are you using (type & version)?

MySQL 5.6

###### What operating system are you using?

CentOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

try to run migrate
tried several times and this is repeatable.

###### What did you expect to see?
migrate successfully as usually

###### What did you see instead?
SQL State  : 22003
Error Code : 1264
Message    : Out of range value for column 'checksum' : value 3582190037 is not in Integer range

Just wonder why this checksum number so big?

**Comment by axelfontaine** [comment]
Which driver are you using? If you are using the MariaDB driver, can you also try using the official MySQL driver instead?

**Comment by axelfontaine** [comment]
Upon reviewing the code and all relevant specifications I am now 100% convinced this is a driver issue. The INTEGER Flyway sends to the DB is destined for a column of type INTEGER and therefore should be signed all the way. This unsigned value is most certainly the result of the driver not correctly interpreting the column type or the column having been manually modified.

Looking forward to hearing about your findings!

**Comment by ruruko** [comment]
Hi Alex ,
Thanks for your quick response. Actually I found it might be flyway-4.2's issue.  I tried run migrate with flyway-5.0 command-line with both MariaDB and MySQL, and got success for the two cases.

**Comment by axelfontaine** [comment]
Sounds good. This is most likely due to the updated drivers shipped with 5.0.
