### ISSUE TITLE
SAPHANATable.doDrop() should drop with CASCADE

### ISSUE THREAD

**Issue by breglerj** [flyway/flyway#1875]
###### What version of Flyway are you using?
5.0.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
SAP HANA 2 SPS 02

###### What operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Flyway flyway = new Flyway();
flyway.clean()

###### What did you expect to see?
The database schema should have been cleaned

###### What did you see instead?
An SQL error:

------------------------------------
SQL State  : HY000
Error Code : 417
Message    : SAP DBTech JDBC: [417]: can't drop without CASCADE specification: cannot drop table referenced by foreign key:

**Comment by axelfontaine** [comment]
Please post the smallest possible SQL migration file that causes Flyway to fail.

**Comment by breglerj** [comment]
[V1.2__migration.txt](https://github.com/flyway/flyway/files/1575479/V1.2__migration.txt)

**Comment by axelfontaine** [comment]
Thanks. Fixed.
