### ISSUE TITLE
Maven: Add a workingDirectory parameter to support relative filesystem locations in conf files

### ISSUE THREAD

**Issue by lbreuss** [flyway/flyway#1877]
Introduce a parameter `workingDirectory` which shall be interpreted as the base directory of relative filesystem locations.

This will allow to reuse conf files without modifications. They preserve their originally designed relative reference to directories containing migrations, that are packaged together with the conf file.

For my schema unit tests run during maven build, I would really like to use the original bundled `/src/main/resources/util/flyway/conf/flyway_latest.conf`, that references `filesystem:../../database/`. Now if during test phase I direct flyway-maven-plugin to use the config file at `/target/util/flyway/conf/flyway_latest.conf`, the relative path currently does not evaluate to `/target/database/`, but to `/../../database/` (leading "/" denoting the project root), which is an inexistent path and even outside the maven project. Currently, as a workaround, I have to use a manipulated version of flyway_latest.conf, which is not optimal for unit testing what's beeing packaged...

Related to issue [944](https://github.com/flyway/flyway/issues/944#issuecomment-347234618), which implemented a fixed current working directory. 
In reply to @jedvardsson, I'm not a big fan of introducing a not-so-obvious semantics of `./path` vs. `path`.

**Comment by axelfontaine** [comment]
I'm currently leaning towards exposing this in the core, to make it accessible to all clients (API, Maven & Gradle).

**Comment by axelfontaine** [comment]
This has now been implemented for Maven. Opened a new issue for other clients: #2022

**Comment by lbreuss** [comment]
Thanks for implementing. I can't get it to work in maven, so I'll open a Bug with a small testcase. (On the command line, I successfully tested the feature, #2022.)
