### ISSUE TITLE
DB2 Stored procedure scripts which run in 4.1.2 fail to execute in 5.0.2

### ISSUE THREAD

**Issue by Rob34** [flyway/flyway#1878]
###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran) 

Clean followed by a migrate to recreate the environment. 

###### What did you expect to see?

Successful recreation of the test environment as previously done in 4.1.2. 

###### What did you see instead?

Process abended at first script which created stored procedures with the following error;

ERROR: Unexpected error
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException:
Migration V00000279__create_end_of_day_audit_stored_procedures.sql failed
-------------------------------------------------------------------------
SQL State  : 42601
Error Code : -104
Message    : DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=END;

This may be related to recent fixes 1690 and 1691.

**Comment by Rob34** [comment]
Syntax of stored procedure all follow a similar template as below;

CREATE PROCEDURE SP_PROC1(
  IN fromTime TIMESTAMP,
  IN toTime   TIMESTAMP
)
DYNAMIC RESULT SETS 1
  BEGIN
    DECLARE cursor1 CURSOR WITH RETURN FOR
      SELECT  .....
      FROM ....
      WHERE .....
      GROUP BY .....;
    OPEN cursor1;
  END;

**Comment by axelfontaine** [comment]
The devil is often in the details. Could you post the smallest possible SQL file that causes Flyway to fail? Please include actual SQL as we often need the exact input characters to see what trips up the parser.

**Comment by axelfontaine** [comment]
Any news?

**Comment by Rob34** [comment]
Not yet, other than it does seem to be specific to the makeup of the procedures in the failing script. Trying to recreate the problem with anonymous code.

**Comment by axelfontaine** [comment]
Have you been able to recreate it?

**Comment by Rob34** [comment]
Yes. It's a bit messy but it's a couple of the original scripts with various names changed. 
[Flyway.zip](https://github.com/flyway/flyway/files/1634885/Flyway.zip)

**Comment by axelfontaine** [comment]
@Rob34 Thanks! That was very helpful. Fixed.
