### ISSUE TITLE
Add Maven artifact install and deploy scripts

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#1882]
To make it easier to install the artifacts in a local or remote repository

**Comment by axelfontaine** [comment]
This has now been implemented.

**Comment by davidkarlsen** [comment]
in deployToRemoteMavenRepo.sh
the '-f pom.xml' is an error (there is no such file)
Also the 1st echo line needs to use double quotes so the () is not parsed as shell execution

**Comment by axelfontaine** [comment]
@davidkarlsen It appears some earlier version of our scripts we used for internal testing slipped in the final release. This has now been fixed.
