### ISSUE TITLE
Add support for SQL*Plus variable substitution

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#1883]
Including the following SQL*Plus commands:

- `SET DEFINE`
- `SET SCAN`
- `DEFINE`
- `UNDEFINE`  

Additionally to avoid breaking existing installations not relying on SQL\*Plus, SQL*Plus functionality should be disabled by default and activated with a new flag `flyway.oracle.sqlplus`.

**Comment by Sajith1988V** [comment]
Is the flyway.oracle.sqlplus available in Flyway 5.1.1 community version?

**Comment by axelfontaine** [comment]
@Sajith1988V No, it's Pro and Enterprise only. See https://flywaydb.org/documentation/database/oracle#sqlplus-commands
