### ISSUE TITLE
Incorrect WARNING: Ignoring unsupported SQL*Plus statement when "column" text appears on a new line

### ISSUE THREAD

**Issue by dvdtknsn** [flyway/flyway#1886]
###### What version of Flyway are you using?
5.01 Flyway Pro trial

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command line

###### What database are you using (type & version)?
Oracle express 11gR2

###### What operating system are you using?
Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
When this statement is run using flyway migrate (command line)

   COMMENT ON COLUMN "EMPLOYEES"."DEPARTMENT_ID" IS 'Department id where employee works; foreign key to department_id column 
column of the departments table';

it fails with 

WARNING: Ignoring unsupported SQL*Plus statement:    COMMENT ON COLUMN "EMPLOYEES"."DEPARTMENT_ID" IS 'Department id where employee works; foreign key to department_id
column of the departments table'

If I change this to 

   COMMENT ON COLUMN "EMPLOYEES"."DEPARTMENT_ID" IS 'Department id where employee works; foreign key to department_id column 
colum of the departments table';

(ie, I've changed column to colum)

then it works...

So it seems that something in Flyway is special casing new lines that start with the "column"

###### What did you expect to see?
The statement above should work (it works when I run it from SQL Developer)

**Comment by axelfontaine** [comment]
Good catch! This was actually a subtle bug in the Oracle parsing triggered by the multiline string literal. Fixed.
