### ISSUE TITLE
Missing semi colon in the dryrun SQL to insert into the flyway_schema_history table

### ISSUE THREAD

**Issue by dvdtknsn** [flyway/flyway#1894]
###### What version of Flyway are you using?
 flyway pro 5.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Jenkins and the command line

###### What database are you using (type & version)?
Oracle XE 11g

###### What operating system are you using?
Windows

###### What did you do?
When running the following dryrun script using SQLplus I get:
Table created.

ALTER SESSION SET CURRENT_SCHEMA="REDGATE_PRODUCTION"
*
ERROR at line 2:
ORA-00933: SQL command not properly ended

It looks like there's no semi colon after the INSERT statement. Is this a bug?

NSERT INTO "REDGATE_PRODUCTION"."flyway_schema_history" ("installed_rank","version","description","type","script","checksum","installed_by","execution_time","success") VALUES (1, '2', 'migration script', 'SQL', 'V2__migration_script.sql', -1362741165, 'REDGATE_PRODUCTION', 1, 1)

**Comment by axelfontaine** [comment]
Thanks! Fixed.

**Comment by dvdtknsn** [comment]
Great - this is useful as many people I speak to want to use the reviewed
script to execute, rather than trusting running flyway migrate once more.
