### ISSUE TITLE
flyway4.2.0 Unable to acquire MySQL named lock:

### ISSUE THREAD

**Issue by slmouse** [flyway/flyway#1896]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?
mysql 5.0.51b

###### What operating system are you using?
centos 7.2

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
[INFO][2018-01-15T19:27:36.518+0800][org.springframework.web.servlet.handler.SimpleUrlHandlerMapping:362] Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
[INFO][2018-01-15T19:27:37.397+0800][org.flywaydb.core.internal.util.VersionPrinter:44] Flyway 4.2.0 by Boxfuse
[INFO][2018-01-15T19:27:37.760+0800][org.flywaydb.core.internal.dbsupport.DbSupportFactory:44] Database: jdbc:mysql://100.69.238.101:18066/prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=TRUE&useSSL=false (MySQL 5.0)
[INFO][2018-01-15T19:27:37.829+0800][org.flywaydb.core.internal.command.DbValidate:44] Successfully validated 19 migrations (execution time 00:00.023s)

[WARN][2018-01-15T19:30:37.897+0800][org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext:551] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.dbsupport.FlywaySqlException:
Unable to acquire MySQL named lock: Flyway--1880266916
------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

**Comment by axelfontaine** [comment]
Please try again with Flyway 5.0.5 and reopen if the problem persists. It does sound like a network issue on your end though.
