### ISSUE TITLE
Resolver and Executor for specified list of scripts in a specified order

### ISSUE THREAD

**Issue by lgoldstein** [flyway/flyway#1898]
###### What version of Flyway are you using?
5.0.6
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven + Java API
###### What database are you using (type & version)?
PostgreSQL 9.3
###### What operating system are you using?
Fedora 25/26/27/CentOS
###### What did you do?
I had some code that was using the `SqlMigrationExecutor` (version 5.0.5) to run some script(s) which used to be _public_. Since _Flyway_ is such a good useful tool, all its classes/methods/literal constants should be made _public_ or _protected_ so that its functionality can be re-used or extended. This would also encourage contributions from the _Java_ community and further its widespread use.

**Comment by axelfontaine** [comment]
This is an internal implementation detail, with no compatibility guarantees, subject to change at any time.

For this same reason, the following will *never* happen as it would create a maintenance nightmare and absolute ossification:
> all its classes/methods/literal constants should be made public or protected so that its functionality can be re-used or extended

What is your usecase?

**Comment by lgoldstein** [comment]
> This is an internal implementation detail, with no compatibility guarantees, subject to change at any time.

I have no quarrel with that - I will adjust my code accordingly

> What is your usecase?

I have my own code that sometimes needs to invoke one *specific* SQL script or a list of *specific* scripts determined by my code's logic (including the correct order in which they should be executed) rather than _Flyway_'s built-in full scan and ordering

**Comment by stellingsimon** [comment]
I think it is hard for Flyway to provide a resolver and executor for specified lists of scripts and orders without making it awkward and error-prone to configure. As a user of Flyway, what I really need is a more powerful SPI that allows me to take control of the execution order and the migration selection process. Nothing prevents you from providing default implementations for common use cases that build upon this SPI.

I too got bitten by the reduced visibility of `SqlMigrationExecutor` when upgrading to Flyway 5.0.7. Right now we're forcefully invoking the constructor using reflection, well aware of the dangers of this approach. 

Ideally, I'd like to be able to use `SqlMigrationExecutor` as a building block in my own "migration controller" of sorts. Flyway is a great library that does the nitty-gritty right, but I'd like to use it more as a toolbox than a blackbox with some (configurable) buttons.

**Comment by lgoldstein** [comment]
I couldn't have said it better myself - I fully agree with

>> Flyway is a great library that does the nitty-gritty right, but I'd like to use it more as a toolbox than a blackbox with some (configurable) buttons

**Comment by DoodleBobBuffPants** [comment]
You can read about how to [configure your own resource providers and executors here](https://flywaydb.org/blog/Configure-resource-providers).
