### ISSUE TITLE
GSS PostgreSQL Authentication

### ISSUE THREAD

**Issue by bradyclifford** [flyway/flyway#1900]
* What version of Flyway are you using? Latest
* Which client are you using? Command-line
* What database are you using (type & version)? PostgreSQL 9.6
* What operating system are you using? Windows & Mac

# Overview
Utilizing MIT Kerberos and GSS authentication with PostgreSQL, would like to be able to execute Flyway providing a username for Postgres authentication and a different username for GSS authentication.  Flyway does not allow for the use of [User Name Maps](https://www.postgresql.org/docs/9.1/static/auth-username-maps.html) within Postgres due to this restriction.

## What did you do?
When attempting to connect to our Postgres instance using Flyway, I get `GSS Authentication failed` connection error:

    Unable to obtain Jdbc connection from DataSource
    (
      jdbc:postgresql://host/database?
      kerberosServerName=postgres&
      jaasApplicationName=pgjdbc
    ) 
    for user 'username@domain.com': GSS Authentication failed

My Postgres instance is using gss authentication with MIT Kerberos to authenticate with my Active Directory using an uppercase domain name (realm), but on Postgres we are using lowercase domains due to how `pg-ldap-sync` tool creates users.

I am able to connect just fine using `psql` and a lowercase domain name:
```
psql -h postgres.domain.com -U username@domain.com
```

However, when I attempt to run `Flyway` with the same credentials, I receive a `GSS Authentication failed` due to me not providing the correct domain casing matching the realm.

My JAAS Configuration:

    pgjdbc
    {
      com.sun.security.auth.module.Krb5LoginModule required
      doNotPrompt=true
      useTicketCache=true
      debug=true
      client=true;
    };

> Same questions asked on [StackOverflow](https://stackoverflow.com/questions/48235725/flyway-gss-authentication-failed-postgres-connection-error)

## What did you expect to see?
How can I provide a different Postgres user than the principal used for Kerberos authentication?  Similar to what I can do with `psql`.

Allowing for different Postgres and principal users will enable the use of [User Name Maps](https://www.postgresql.org/docs/9.1/static/auth-username-maps.html) within Postgres.

## What did you see instead?
 I am only able to authenticate when I create a Postgres user identical to the principal; i.e. `username@DOMAIN.COM`.

From the look of it, the JDBC driver Flyway is using, when using GSS, can only send the authentication user over, so if the database user doesn't match there is no way to map it. Since there is no ability to send the database user separately through the JDBC driver it falls back to the authentication user and the map fails.

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in V7 using JDBC properties. You can read about it in our blog post [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
