### ISSUE TITLE
All migrations are ignored after Out of Order

### ISSUE THREAD

**Issue by ijoaum** [flyway/flyway#1902]
###### What version of Flyway are you using?
Flyway Community Edition 5.0.2 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
MySQL 5.5

###### What operating system are you using?
Ubuntu 14.04.5 LTS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I ran several migration with ouOfOrder=true

###### What did you expect to see?
The next migrations is suposed to be pending

###### What did you see instead?
All migarions after last Out of Order is showing ignored

![image](https://user-images.githubusercontent.com/1765800/35162547-dfc6670e-fd2a-11e7-9b20-94c684e929f5.png)

**Comment by axelfontaine** [comment]
This could be related to #1890

Please try again with 5.0.6. Does the issue persist?

**Comment by ijoaum** [comment]
No success with 5.0.6.
I could handle to get a migration in Pending state by changing timestamp to a higher value. Maybe this could help.

![image](https://user-images.githubusercontent.com/1765800/35338147-42f995c6-0104-11e8-8ece-83f4931a8126.png)

JFYI: Baseline is set on migration 1.

**Comment by ijoaum** [comment]
Sorry. My mistake. 
One of the migrations timestamp was in the future and I didn't see.
