### ISSUE TITLE
Migration fails with "end-of-copy marker corrupt" error

### ISSUE THREAD

**Issue by rachnaagg** [flyway/flyway#1903]
###### What version of Flyway are you using?
5.0.6

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
PostgreSQL 10

###### What operating system are you using?
Centos 7

###### What did you do?
I am trying to do migration using command line tool. I have a SQL script which is created by the pg_dump command of PostgreSQL database. It has some binary data which includes the end of line marker character "\." and is escaped because this file was automatically created by pg_dump. When I restore the database using psql and this file, the database gets restored correctly. But when I use this file to migrate using Flyway, it gives the following error:
Migration V1__Desc.sql failed
------------------------------------------
SQL State  : 22P04
Error Code : 0
Message    : ERROR: end-of-copy marker corrupt
  Where: COPY table, line 7
Location   : /home/vagrant/flyway-5.0.6/sql/V1__Desc.sql (/home/user/flyway-5.0.6/sql/V1__Desc.sql)
Line       : 8919

The contents of the file include COPY FROM stdin statement containing data for a couple of bytea columns.

###### What did you expect to see?
I expect the migration to be successful and the data to be inserted correctly.

###### What did you see instead?
Migration fails with error.

**Comment by axelfontaine** [comment]
Please post the smallest possible sample SQL file that trips up Flyway so we can reproduce this.

**Comment by rachnaagg** [comment]
We need to examine the data before posting it. Meanwhile, I would also like to give some more information:
Initially our PostgreSQL dump file was one big file with data inserts for other tables after this table in which the issue is occurring. When I ran this file in Flyway DB, the data got inserted in this table but the rest of the data after this table was ignored and none of the later tables were populated. Moreover, no error was thrown. So, to debug the issue, I split the file in 2 files, one till the data for this table (in which the issue is occurring) and the second for the rest of the data. Now, when I ran this first file, I got an error that I mentioned in my previous comment and the data was not inserted in the table and the script rolled back.

**Comment by rachnaagg** [comment]
While I am awaiting approval from my company for posting the data, I did some more analysis and found that:
When I set the data to NULL for the column in the record that contained the end of line marker character "\." and ran the script in one full go, it demonstrated the same behavior and the data was populated in the table but not in the after ones. When I split this script again into 2 and ran both the scripts in one go, the data got populated in all the tables without any issue.

**Comment by axelfontaine** [comment]
Hmm very interesting! Can you construct a minimal example with synthetic data that would allow us to reproduce this?

**Comment by rachnaagg** [comment]
I am unable to upload the data as per my company policy. I have taken a workaround solution using the base64 encoded string rather than bytes. Thanks for your help.

**Comment by axelfontaine** [comment]
Closing as without the ability to reproduce this, I see no chance in assessing what the situation is, let alone fixing something.

**Comment by qpointsystems** [comment]
I think that \. is the PG end-of-copy marker. If you happen to encounter this sequence -- say in a file containing escaped HTML -- PG will end the COPY command prematurely.

Example: C1978266|L6897214|S8022125|A18352124|SCUI|50398-7|AT216211012||LEA|LNC|&#x7C;CASE: PM-06-J00705 \.br\ PATIENT: SANTA CLAUS \.br\ \.br\ |N||

Encountering the first \.br\ will stop the COPY statement
