### ISSUE TITLE
Provide a list-of-migration-objects MigrationResolver

### ISSUE THREAD

**Issue by fabianbergmark** [flyway/flyway#1905]
###### What version of Flyway are you using?

5.0.6

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

Sqlite3

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

###### What did you expect to see?

As our app uses Proguard and some other bytecode transformation tools, it's generally nice to avoid classpath-scanning or resource folders. It would be nice if Flyway provided (public) classes and documentation for migrating a list of ResolvedMigration objects. Right now I have to copy some internal classes from Flyway. Here is my current solution: https://pastebin.com/t3hpTcGn

**Comment by axelfontaine** [comment]
Related to #1898

**Comment by MikielAgutu** [comment]
We think this can be achieved by setting `locations` to empty, and providing a [list of pre-instantiated migrations](https://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/api/configuration/ClassicConfiguration.html#setJavaMigrations(org.flywaydb.core.api.migration.JavaMigration...)).

**Comment by MikielAgutu** [comment]
@fabianbergmark Can you try the above solution?

**Comment by fabianbergmark** [comment]
I no longer work on this project.
