### ISSUE TITLE
CLI flyway specified drivers directory via jarDirs not applied

### ISSUE THREAD

**Issue by buuren** [flyway/flyway#1906]
###### What version of Flyway are you using?

Flyway Community Edition 5.0.6 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

MSSQL 2012

###### What operating system are you using?

GNU/Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

According to:
https://github.com/flyway/flyway/blob/master/flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java#L292

> jarDirs                      : Comma-separated list of dirs for Jdbc drivers & Java migrations

the command line parameter "-jarDirs" should allow to specify directory with JDBC drivers, but this option is only working for Java Migrations and does not apply to JDBC drivers

###### What did you expect to see?

jarDirs should provide a way to specify path to JDBC drivers according to documentation

If we take a look at https://github.com/flyway/flyway/blob/master/flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java#L318 there is no mention of JAR_DIRS and as a result -jarDirs has no effect on finding JDBC Drivers

###### What did you see instead?

ERROR: Directory for Jdbc Drivers not found

**Comment by axelfontaine** [comment]
Don't delete the drivers directory. Then things should work as expected.

We'll loosen the check on our end as well to make this possible in the future.

**Comment by axelfontaine** [comment]
The check for the drivers directory has now been removed.
