### ISSUE TITLE
Initial Schema reported as not empty (view pg_stat_statements exists)

### ISSUE THREAD

**Issue by vitali-esau** [flyway/flyway#1908]
What version of Flyway are you using?
5.0.5

Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

What database are you using (type & version)?
Postgres 9.6

What operating system are you using?
? Linux on AWS

What did you do?
Started a spring boot service with flyway migration scripts on a fresh/ intitial postgresql instance

What did you expect to see?
A successfull flyway migration

What did you see instead?
Migration failed with exception:
https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L1196

Issue:
https://github.com/flyway/flyway/blob/fb9a6ebe3a560553f7a2211a40460532f6154d13/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLSchema.java#L51
Running a postgresql DB on cloud foundry we have a postgres instance which has initially the db view "pg_stat_statements" available. The linked statement in doEmpty() returns "true", but i this case it should be false. In flyway 4.2.0 the doEmpty() is different and issue not occuring.

**Comment by axelfontaine** [comment]
Well, Flyway isn't lying, the schema isn't empty.

That being said, maybe there is a way to detect that such a view comes from an extension. This would also help with #100 

In the meantime you can either use a different schema or baseline this one.

**Comment by vitali-esau** [comment]
We just found out that spring property "baselineOnMigrate" just fits well to our requirements.
So issue can be closed.
