### ISSUE TITLE
Oracle 11.2 support

### ISSUE THREAD

**Issue by vpavic** [flyway/flyway#1913]
After picking up Flyway 5.0.6 via upgrade to Spring Boot 2.0.0.RC1 I've had Oracle 11.2 based integration tests fail due to `FlywayEnterpriseUpgradeRequiredException`.

However, according to [this post](https://blogs.oracle.com/stevenchan/database-112-extended-support-fee-waived-through-december-2018) from Oracle Blog, Extended Support is waived through December 2018.

Please consider bringing back support for Oracle 11.2 to Community Edition.

**Comment by axelfontaine** [comment]
As you can see from http://www.oracle.com/us/support/library/lifetime-support-technology-069183.pdf (page 4) this version of Oracle was released in Sep 2009 and premier support ended on Jan 2015.

You can upgrade to Oracle 12.2 which is supported by Oracle Premier support and Flyway Community Edition until March 2022. Or if you prefer you can upgrade to Flyway Enterprise Edition which continues to support Oracle 11.2 as you would expect.

**Comment by vpavic** [comment]
Thanks for the feedback @axelfontaine.

Upgrading is not an option as this is customer's database that only provides a dedicated schema for our application's purposes.

It's really unfortunate that we're unable to use the current Flyway release with database that's effectively still supported under existing support contracts with no extra costs.

**Comment by remmeier** [comment]
so what is the plan, to fork out the old database integrations into a new project? which are kind of minimal given everything is based on JDBC.
