### ISSUE TITLE
Still "no database selected" error with MySQL and no schema name in flyway.url

### ISSUE THREAD

**Issue by mauromol** [flyway/flyway#1921]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle plugin

###### What database are you using (type & version)?
MySQL 5.5

###### What operating system are you using?
Windows (client) and Ubuntu Linux (server running MySQL)

###### What did you do?
As specified in #598 
I'm still having the "no database selected" problem with Flyway 4.2.0 and running Flyway through Gradle.
The flyway.url is set without the schema name, while flyway.schemas is set to the correct schema name.
This did not happen with Flyway 3.2.1.

I have to workaround this by putting the schema name in the URL.

NOTE 1: I'm using MySQL Connect/J 5.1.45 (latest currently available)
NOTE 2: it seems like Flyway can query the schema_version table correctly (for instance: if I run flywayMigrate twice, the first attempt fails with "no database selected", the second attempt fails because it correctly find the failed migration from the previous run), but fails when trying to actually apply migrations.

###### What did you expect to see?
No error at all, just like it was with Flyway 3.2.1.

###### What did you see instead?
> Error occurred while executing flywayMigrate

```
Migration mymigration.sql failed
-------------------------------------------------------------
SQL State  : 3D000
Error Code : 1046
Message    : No database selected
Location   : path-to/mymigration.sql (D:\absolute\path-to\mymigration.sql)
Line       : 6
Statement  : DELETE FROM MYTABLE [cut]

No database selected
```

**Comment by axelfontaine** [comment]
Please upgrade to 5.0.7 and check if the issue persists.

**Comment by mauromol** [comment]
Not that easy, since 5.0.7 is quite a major upgrade (Java 8, new default schema version table name...).
Unless you did something in this area, I really doubt it will make any difference: I couldn't find anything suspect in the release notes...
Anyway, I will give it a chance.

**Comment by axelfontaine** [comment]
Any news?

**Comment by mauromol** [comment]
Sorry, I did not have time to test yet, I'll let you know as soon as possible.

**Comment by krm1312** [comment]
Just FYI, one can't simply upgrade from 3.2.X to 5.X either since you must go through 4.X to get your schema_version table migrated/repaired.

**Comment by krm1312** [comment]
[flyway_log.txt](https://github.com/flyway/flyway/files/1803364/flyway_log.txt)

Startup log at debug level.

**Comment by krm1312** [comment]
It does work fine w/ 5.0.7, but, the need to go through 4.2 to fix schema_version still makes this problematic for upgrades from 3.2.X.

**Comment by axelfontaine** [comment]
Closing as this is obviously working now.

**Comment by krm1312** [comment]
Yet, you can't simply migrate from 3.2 to 5.  Anyway, I'm pretty sure the change for https://github.com/flyway/flyway/issues/1108 is what broke it.  If I remove the check at the top of MqSQLDbSupport.changeCurrentSchemaTo in 4.2 branch and let the schema change happen every time it works.

**Comment by krm1312** [comment]
The workaround in https://github.com/flyway/flyway/issues/598 of createDatabaseIfNotExist=true on the connect string and specifying the db in the connect string seems to work.

**Comment by mauromol** [comment]
I could finally test this against Flyway 5.0.7 after upgrading Flyway in our build scripts.
I confirm it works correctly with 5.0.7, so the schema name must not be necessarily specified in the JDBC URL.

Anyway, not really "invalid", since it was really broken in 4.2.0 ;-)
