### ISSUE TITLE
Too much memory allocations

### ISSUE THREAD

**Issue by luengnat** [flyway/flyway#1924]
###### What version of Flyway are you using?

4.X

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

maven

###### What database are you using (type & version)?

Oracle 12c

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

We have tons of database to migrate and the migration script is very long. We noticed that the migration spends a lot of time performing GC when we run a lot of data migrations in our integration tests. It turns out that SqlScript class uses a lot of String split, replace, toUpperCase, trim, replaceAll, etc which generates a lot of string garbage. I wonder whether it's possible to stream line them a little bit such as:
1. Use Pattern/Matcher.replace instead of String.replace which creates a Pattern every time.
2. Use Matcher.appendReplacement whenever you can

**Comment by axelfontaine** [comment]
Please try again with 5.0.7 as there have been a number of changes in this area.

The streaming part is related to #615 . I'll look into the 2 other suggestions as well.

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
We have now rewritten a number of string handling functions and profiling indicates that things are much better now.

**Comment by luengnat** [comment]
@axelfontaine  I just tried to upgrade to 5.0.7 from 4.2.0, it seems to break our schema deployment. It looks like some of the scripts seem to run twice. I'm trying to track it down
