### ISSUE TITLE
search_path is not restored after migration if the schema names are quoted

### ISSUE THREAD

**Issue by stellingsimon** [flyway/flyway#1930]
This issue is another manifestation of #737 which has been closed in Flyway 4.0 but still appears in 4.2.

###### What version and edition of Flyway are you using?
4.2.0, Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
I located the error in the source code (see detailed analysis below) and the code in the master branch looks identical, so it's reasonable that yes, this is the case.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### What database are you using (type & version)?
Postgres 9.5

###### What operating system are you using?
Linux

###### What did you do?
I migrate several schemas, one after the other in a separate `Flyway.migrate()` call, but using the same Connection pool. I noticed that statements like `DROP TABLE IF EXISTS xxx` statements would **unexpectedly drop tables with the same name but contained in other schemas**.

I tracked this down to incorrect search path handling in Flyway.

The last schema migration file contains the following code:

```
CREATE TABLE WTF (x TEXT);
INSERT INTO WTF (x)
  SELECT current_setting('search_path');
```
It is run against a schema called `billing`.

Here's the content of `WTF` after Flyway migrated the schemas `public`, `shared` and `billing`:

```
billing, shared, "$user", public
```

I would have expected this instead:

```
billing, "$user", public
```

Stepping through calls of `PostgreSQLDbSupport.changeCurrentSchemaTo` I can see that the same schema is added to the search path multiple times, which shouldn't be. The reason is that the check to prevent this is done on `schema.getName()` while the search path is prepended with `schema.toString()`, which contains additional quoting characters.

![flyway_search_path_bug](https://user-images.githubusercontent.com/7038847/36320922-481b1aba-1348-11e8-8793-df7fcd0c5cf2.png)

This bug can potentially cause data loss. Is there a workaround we can employ without immediately upgrading to a newer FlywayVersion? We are just days away from a rollout to production...

Thanks for your efforts!

**Comment by axelfontaine** [comment]
Thanks for reporting. There is a reason we ask to test with the latest version, as this was fixed in 5.0.0 and the search_path is now backed up as a whole and restored completed afterwards.

Upgrade to 5.0.7 and you should be all set. It should be a drop-in replacement.
