### ISSUE TITLE
Where did all the tests go?

### ISSUE THREAD

**Issue by stellingsimon** [flyway/flyway#1931]
(I am posting this question as an issue because it would not be considered a proper question on StackOverflow. I hope this is okay since it's a question related to the development of Flyway, not its usage.)

[This page](https://flywaydb.org/documentation/contribute/code/setup) in the contributor guide mentions a test suite, but doesn't specify where to find these tests. [`CONTRIBUTING.md`](https://github.com/flyway/flyway/blob/master/CONTRIBUTING.md) states that "Contributions will not be accepted without tests or necessary documentation updates." 

But as part of the initial push for Flyway 5.0 (commit 3387a942a5eab7eb344df7d92b19524ff99c9b29) **all the unit tests were deleted from the git repo.** Why were they removed, and where did they go? How can contributors (or Boxfuse) make sure that their pull requests will not introduce regressions?

**Comment by axelfontaine** [comment]
Thanks for the heads up. That page was indeed out of date. This has now been fixed.

We validate contributions ourselves using a large internal automated test infrastructure.

**Comment by mbode** [comment]
@axelfontaine Is there a way to access said test suite? Otherwise it doesn't seem feasbile to make meaningful contributions to the project imo.
