### ISSUE TITLE
PostgreSQL: clean doesn't unlink referenced LOBs in pg_largeobject

### ISSUE THREAD

**Issue by zinnchen** [flyway/flyway#1934]
###### Which version and edition of Flyway are you using?
5.0.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Don't know. I can't use 5.0.7 because there is another issue where some classes can't be found.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres 9.6

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I have two schemas in postgres database. First the default one 'postgres' and separate schema for application tables ('app_schema'). I store blobs in my application schema which are stored as large object. These large objects are stored in table 'pg_largeobject' in catalog 'pg_catalog'.

I run the following Java code test preparation:
    // prepare database
    Schema schema;
    try (Database database = DatabaseFactory.createDatabase(migrator, false)) {
      schema = database.getMainConnection().getSchema("app_schema");
      if (schema.exists()) {
        schema.clean();
      } else {
        schema.create();
      }
    }

###### What did you expect to see?
I expect that schema.clean() does clean the 'app_schema' AND the referenced entries in 'pg_catalog' catalog.
In my case I expect that the entries in 'pg_largeobject' which are referenced by entries in 'app_schema' will be deleted.

###### What did you see instead?
I see remaining entries in catalog 'pg_catalog'.'pg_largeobject' which not referenced anymore.

**Comment by axelfontaine** [comment]
Hmmm I don't see an easy solution to this. Your table will most likely only contain OIDs. We would have to check whether these belong to large objects and if they do, unlink them. But that's not necessarily safe as these LOBs may still be referenced from a different schema that the user doesn't want cleaned.

Suggestions welcome.

**Comment by zinnchen** [comment]
I updated the error descriptions since the table 'pg_largeobject' isn't located in schema 'postgres'. It is located in catalog 'pg_catalog'

**Comment by axelfontaine** [comment]
Any suggestion on how to resolve this in a safe and generic manner?

**Comment by zinnchen** [comment]
After some research in documentation of postgresql I found the build in utility 'vacuumlo' which removes orphaned large objects. May be it is possible to call this function during clean.

`vacuumlo is a simple utility program that will remove any "orphaned" large objects from a PostgreSQL database. An orphaned large object (LO) is considered to be any LO whose OID does not appear in any oid or lo data column of the database.`

see: https://www.postgresql.org/docs/9.6/static/vacuumlo.html

**Comment by axelfontaine** [comment]
That has a number of issues. First of all we couldn't assume the CLI tool is installed, second it is challenging on RDS: https://dba.stackexchange.com/questions/174663/how-to-vacuumlo-an-rds-postgresql-database#174664

**Comment by MikielAgutu** [comment]
In Flyway 7 we introduced Script migrations: https://flywaydb.org/documentation/migrations#script-migrations. This will allow you to implement the proposed workaround (https://github.com/flyway/flyway/issues/1934#issuecomment-368848005). You could include it in a repeatable script, and use a timestamp placeholder to ensure it's always executed.

**Comment by MikielAgutu** [comment]
We think this is solved by using script migrations to call the 'vacuumlo' tool.
