### ISSUE TITLE
Even after migrate, it shows that ERROR: Validate failed: Detected resolved migration not applied to database: 2

### ISSUE THREAD

**Issue by sarjunkumar** [flyway/flyway#1935]
###### Which version and edition of Flyway are you using?

Flyway Trial Edition 5.0.7 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

Mysql 5.6

###### Which operating system are you using?

RHEL 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

flyway migrate
Flyway Trial Edition 5.0.7 by Boxfuse
WARNING: You are using the 30 day limited Flyway Trial Edition. After 30 days you must remove this version and either upgrade to Flyway Pro Edition or Flyway Enterprise Edition or downgrade to Flyway Community Edition.

WARNING: Overwriting existing dry run out file <folder>/output/output.sql ...
=================================================================================================================================
Dry Run: Database will NOT be modified. The following messages only represent what would happen in a normal Flyway migration run.
=================================================================================================================================
Database: jdbc:mysql://localhost:3306/petclinic (MySQL 5.6)
Current version of schema `petclinic`: 1
Migrating schema `petclinic` to version 2 - 2 addtypes [non-transactional]
Migrating schema `petclinic` to version 3 - 3 addtypes [non-transactional]
Successfully applied 2 migrations to schema `petclinic` (execution time 00:00.009s)

flyway validate
Flyway Trial Edition 5.0.7 by Boxfuse
WARNING: You are using the 30 day limited Flyway Trial Edition. After 30 days you must remove this version and either upgrade to Flyway Pro Edition or Flyway Enterprise Edition or downgrade to Flyway Community Edition.

WARNING: Overwriting existing dry run out file <folder>/output/output.sql ...
=================================================================================================================================
Dry Run: Database will NOT be modified. The following messages only represent what would happen in a normal Flyway migration run.
=================================================================================================================================
Database: jdbc:mysql://localhost:3306/petclinic (MySQL 5.6)
ERROR: Validate failed: Detected resolved migration not applied to database: 2

flyway info
Flyway Trial Edition 5.0.7 by Boxfuse
WARNING: You are using the 30 day limited Flyway Trial Edition. After 30 days you must remove this version and either upgrade to Flyway Pro Edition or Flyway Enterprise Edition or downgrade to Flyway Community Edition.

WARNING: Overwriting existing dry run out file <folder>/output/output.sql ...
=================================================================================================================================
Dry Run: Database will NOT be modified. The following messages only represent what would happen in a normal Flyway migration run.
=================================================================================================================================
Database: jdbc:mysql://localhost:3306/petclinic (MySQL 5.6)
Schema version: 1

+-----------+---------+-------------+----------+---------------------+----------+----------+
| Category  | Version | Description | Type     | Installed On        | State    | Undoable |
+-----------+---------+-------------+----------+---------------------+----------+----------+
| Versioned | 1       | Baseline    | BASELINE | 2018-02-26 09:00:56 | Baseline | No       |
| Versioned | 2       | 2 addtypes  | SQL      |                     | Pending  | No       |
| Versioned | 3       | 3 addtypes  | SQL      |                     | Pending  | No       |
+-----------+---------+-------------+----------+---------------------+----------+----------+

I am new to flyway and we are planning to implement to use this a automated DB deployment and schema versioning for more than 100+ projects.

Even after the migrate why the state is still pending. 

Also the changes were not applied to the database.

Please let me know if I am missing something here

**Comment by axelfontaine** [comment]
Your configuration has the `dryRun` feature active. This is most likely due to one of your configuration files having the [`dryRunOutput` configuration property](https://flywaydb.org/documentation/commandline/migrate#dryRunOutput) set. You can check which settings are currently active using the [`-X` flag](https://flywaydb.org/documentation/commandline/#debug-output)

When `dryRun` is active Flyway uses a read-only database connection and changes are only simulated and not applied against the database. All statements that would have been executed as saved in the file specified by the [`dryRunOutput` configuration property](https://flywaydb.org/documentation/commandline/migrate#dryRunOutput).

If you want the changes to be applied you have to unset this property. The easiest is to comment in out in the config file where it was set. Everything will then work as expected.

Please confirm this is resolved.

**Comment by sarjunkumar** [comment]
Thanks for this. The issue is resolved.
Thanks for the immediate response
