### ISSUE TITLE
chinese character encoding issues

### ISSUE THREAD

**Issue by ttarcher** [flyway/flyway#1937]
###### Which version and edition of Flyway are you using?

`compile('org.flywaydb:flyway-core:5.0.7')`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Spring boot + Gradle plugin

###### Which database are you using (type & version)?

Mariadb: Ver 15.1 Distrib 10.2.12-MariaDB, for Win64 (AMD64)

###### Which operating system are you using?

![image](https://user-images.githubusercontent.com/13407099/36713909-beb1176c-1bca-11e8-8355-12006a913dcf.png)

###### What did you do?

this is my `V0_0_1__base.sql` file : 
```mysql
CREATE TABLE book_publisher
(
  id   BIGINT AUTO_INCREMENT
    PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT book_publisher_uindex
  UNIQUE (name)
)
  ENGINE = InnoDB;

INSERT INTO book_publisher (id, name) VALUES (1, '人民教育出版社');
```
![image](https://user-images.githubusercontent.com/13407099/36714215-2ea2e888-1bcc-11e8-881d-f059f80e0355.png)

and this is my database character :

![image](https://user-images.githubusercontent.com/13407099/36714297-8c6a774c-1bcc-11e8-8db5-09763957b61c.png)

and my `application.properties` :

![image](https://user-images.githubusercontent.com/13407099/36714771-7906c6d6-1bce-11e8-873f-2cfc56fb6bd9.png)

Is there any wrong configration?

###### What did you expect to see?

![image](https://user-images.githubusercontent.com/13407099/36714121-cce11fd4-1bcb-11e8-82a1-7bb8a27ca961.png)

###### What did you see instead?

![image](https://user-images.githubusercontent.com/13407099/36714098-b572c686-1bcb-11e8-9623-66b0712c6dda.png)

**Comment by axelfontaine** [comment]
This is due to your database using `utf8` instead of `utf8mb4` encoding. Not a Flyway issue.

**Comment by ttarcher** [comment]
@axelfontaine Thanks for answer,but I don't think so.
Because I use mybatis to insert the name my database is :

**Comment by ttarcher** [comment]
@axelfontaine Thanks for answer. But I don't think so.
Because I use mybatis to insert the name and my database is normal.
![image](https://user-images.githubusercontent.com/13407099/36718372-7ce217de-1bdc-11e8-810f-869d6c0ca56d.png)
![image](https://user-images.githubusercontent.com/13407099/36718386-86eef800-1bdc-11e8-9230-4e9a7f0f06be.png)
so I think this is not my database encoding issue.

**Comment by axelfontaine** [comment]
Then it must be somewhere else in your config. Ensure Flyway's [`encoding` property](https://flywaydb.org/documentation/commandline/migrate#encoding) is set to `UTF-8` and that your build tool is also properly reading and packing the files using UTF-8. Either way, Flyway *does* handle this correctly, so the issue must be somewhere in your setup.
