### ISSUE TITLE
Automatic rollback in postgress using flyway

### ISSUE THREAD

**Issue by hgakhr** [flyway/flyway#1939]
###### Which version and edition of Flyway are you using?

5.0.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Donn't know , I am using gradle and gradle has only 5.0.2 as the latest version
https://plugins.gradle.org/m2/gradle/plugin/com/boxfuse/client/flyway-release/ 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
I am using gradle to connect to Postgres 9.6

###### Which database are you using (type & version)?
Postgres 9.6

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I am trying to execute my scripts using the gradle and flyway . Now if a migration gets failed , due to some error . Normally flyway will add the entry in the flyway_schema_history table for the failed schema and give its status as (Failed).
But in my case if a sql script has got error , it will rollback the whole migration plus didnot make any entry in the flyway_schema_history; table. I am not using any undo command for it.
It is automatically gets rollback when a migration failed.
Can you please let me know how this is possible 

Ex
Migration of schema "dscvietnam" to version 01.02.03 - DDL 1 RF failed! Changes successfully rolled back.**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate

###### What did you expect to see?

It should make some entry in the flyway_schema_history  and if a migration gets failed , it should add the failed migration entry  in the table. As of know it is not making any entry in the table flyway_schema_history , if a migration get fail. Can you please help on this 

###### What did you see instead?

I also tried with the latest version 5.0.7 but still the same issue . Can you please let me know if its the default behaviour ? . and if its the default behaviour then what is the use for "undo" command.
I am using below command to run the migration.
gradle -Dflyway.url=jdbc:postgresql://xxxxxxxxxxxxxs -Dflyway.user=xxxxxxxxxxxxxx -Dflyway.password=xxxxxxxxxx -Dflyway.locations=filesystem:dbcr/rollforward -Dflyway.schemas=xxxxxxxxxxxxxs -Dflyway.sqlMigrationPrefix=V flywayMigrate.

And one more question I am executing baseline before every migration , so is this correct approach or i need to do t once . Please help

**Comment by axelfontaine** [comment]
Note that 5.0.7 *is* published. See https://plugins.gradle.org/plugin/org.flywaydb.flyway

This is the beauty of PostgreSQL: nice DDL transactions which make it possible to cleanly roll back all changes of a failed migration, removing the need to add a failed entry in the schema history table. Works as designed.

Undo is for undoing successfully applied migrations.

No need to baseline. This is only for existing databases where Flyway is introduced later.
