### ISSUE TITLE
PostgreSQL: Ignore objects created by extensions when checking whether a schema is empty

### ISSUE THREAD

**Issue by wimdeblauwe** [flyway/flyway#1940]
Is it possible to specify a list of expected database tables for the baseline migration?

i am using Flyway with Spring Boot 1.5.10 with PostgreSQL with Postgis extension. The Postgis extension creates a `spatial_ref_sys` table after installation. Because of this, I need to set `flyway.baseline-on-migrate=true`. However, I would like to somehow indicate that the database should only have that one table and nothing else.

Is this possible? If not, are you interested on adding this?

**Comment by axelfontaine** [comment]
We will almost certainly not solve it like this. However ... what we can do is detect whether an object was created by an extensions and automatically ignore it in the empty schema check. This would be a generic way to solve this for all extensions, current and future.

**Comment by wimdeblauwe** [comment]
That would be even better indeed 👍
