### ISSUE TITLE
Reopen: Issue 1149

### ISSUE THREAD

**Issue by philipprawe** [flyway/flyway#1942]
Reproduced with version flyway version 5.0.7

Mysql-DB version is 5.7.1
Flyway is used within an spring boot application.
Tested on Mac and Ubuntu. It does not appear under windows!

Query: "INSERT INTO countries (id, code, english, german) VALUES (13, 'AT', 'Austria', 'Österreich');"

Log: "2018-03-02 11:36:15 - DB: Incorrect string value: '\xD6sterr...' for column 'german' at row 1 (SQL State: HY000 - Error Code: 1366)"

Database character set is set default to utf-8, direct execution of the query works.

**Comment by axelfontaine** [comment]
Please use the template when reporting issues.

The issue is somewhere in your setup (Flyway encoding, source file encoding, table encoding, DB encoding). Double-check everything. Flyway does handle this correctly.
