### ISSUE TITLE
Flyway schema creation issue on Oracle 12.2 DB with password policy enabled

### ISSUE THREAD

**Issue by TimoTHa** [flyway/flyway#1943]
###### Which version and edition of Flyway are you using?

5.0.7, Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

Oracle database 12.2.0.1.0

###### Which operating system are you using?

Oracle Linux 7.3 (database host)

Windows 10 EE (Flyway command line host)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Running "flyway migrate" command on an existing Oracle database instance with the password policy enabled (mininum characters 8), and where target schema does not yet exist.

My Flyway configuration file:
# Sample Flyway configuration file
flyway.url=<my db url>
flyway.user=FLYWAY
flyway.table=FLYWAY_SCHEMA_HISTORY
flyway.locations=filesystem:scripts
flyway.schemas=FOODEV
flyway.cleanDisabled=false

###### What did you expect to see?
Flyway creating the user/schema successfully.

###### What did you see instead?

Unable to create schema "FOODEV"
--------------------------------
SQL State  : 99999
Error Code : 28003
Message    : ORA-28003: password verification for the specified password failed
ORA-20001: Password length less than 8

**Comment by axelfontaine** [comment]
Why exactly do you feel this is a Flyway issue?

**Comment by TimoTHa** [comment]
Thanks Axel.

Two reasons:

1. Oracle database 12.2 version provides a set of functions that you can use to manage the complexity of passwords. 
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/dbseg/configuring-authentication.html#GUID-F09749BF-2881-4EE5-B59D-041E4796BAC4

On enterprise level, it is quite common to use these, or customize them as per the organization security requirements.

2. Not sure if I'm looking at the correct source code file, but I feel it is hardcoded to "flyway". In my opinion, it should be at least configurable parameter.
https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/oracle/OracleSchema.java

**Comment by axelfontaine** [comment]
Thanks for the link. The first step we could do, could be moving from `flyway` to `FFllyywwaayy00!!` which should be compliant with all predefined policies. This doesn't fully handle the case of custom policies, but it should be sufficient for the vast vast majority of the cases. What do you think?

**Comment by TimoTHa** [comment]
Thanks Axel for the reply. Yes, more complex default password (like your proposed one) would be good as a quick fix for the issue.
