### ISSUE TITLE
PostgreSQL: Callback afterClean isn't executed on schema.clean()

### ISSUE THREAD

**Issue by zinnchen** [flyway/flyway#1944]
###### Which version and edition of Flyway are you using?
5.0.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Don't know. I can't use 5.0.7 because there is another issue where some classes can't be found. (I will report this issue later)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres 9.6

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I tried to use SQL callback (afterClean.sql) but it isn't executed on schema.clean(). If I execute  flyway.clean() the SQL-Script will be executed.

I run the following Java code test preparation:
// prepare database
Schema schema;
flyway = new Flyway();
//... some flyway configuration ...
try (Database database = DatabaseFactory.createDatabase(flyway, false)) {
schema = database.getMainConnection().getSchema("app_schema");
if (schema.exists()) {
schema.clean();
//flyway.clean();
} else {
schema.create();
}
}

###### What did you expect to see?
I expect flyway to also run the afterClean.sql script on calling schema.clean()

###### What did you see instead?
afterClean.sql isn't executed on schema.clean()

**Comment by axelfontaine** [comment]
This works for me. Check your configuration, especially the locations. Please reopen with a small test repository that reproduces the problem if the issue persists.

**Comment by zinnchen** [comment]
flyway.clean() does work for me, too. But schema.clean() doesn't. I took a look in the source code and didn't find code for callback execution: https://github.com/flyway/flyway/blob/2ce8df3fcebad51270a4263b12e4a1a3ae341b66/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLSchema.java#L80

**Comment by axelfontaine** [comment]
I hadn't noticed in the subbtle difference in the title. This is private API and not meant to be consumed by you. Use `Flyway.clean()` instead. 

This is a low-level internal class not tied to the callback mechanism.
