### ISSUE TITLE
Flyway with AWS Aurora over SSH tunnel not working

### ISSUE THREAD

**Issue by pikeas** [flyway/flyway#1947]
Related: https://github.com/flyway/flyway/issues/1667. Breaking out as separate issue per @axelfontaine.

###### Software versions

OS X 10.12.6, Flyway 5.0.7 (CLI client), AWS Aurora MySQL 5.6.10a.

###### What did you do?

Tried to connect Flyway to an Aurora database via an SSH tunnel.

Successful direct connection:

```
$ ./flyway -url=jdbc:mysql://<cluster-endpoint>.<region>.rds.amazonaws.com/<db> info
Flyway Community Edition 5.0.7 by Boxfuse

Database user: <user>
Database password:
Database: jdbc:mysql://<cluster-endpoint>.<region>.rds.amazonaws.com/<db> (MySQL 5.6)
Schema version: << Empty Schema >>

+----------+---------+-------------+------+--------------+-------+
| Category | Version | Description | Type | Installed On | State |
+----------+---------+-------------+------+--------------+-------+
| No migrations found                                            |
+----------+---------+-------------+------+--------------+-------+
```

Setting up port forwarding:

```
$ ssh -L 3306:<cluster-endpoint>.<region>.rds.amazonaws.com:3306 -N bastion
```

Using the tunnel, incorrect user/pass is immediately rejected:

```
$ ./flyway -url=jdbc:mysql://localhost/<db> info
Flyway Community Edition 5.0.7 by Boxfuse

Database user: bad-user
Database password:
ERROR:
Unable to obtain connection from database (jdbc:mysql://localhost:3306/<db>) for user 'bad-user': Access denied for user 'bad-user'@'<ip>' (using password: YES)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 28000
Error Code : 1045
Message    : Access denied for user 'bad-user'@'<ip>' (using password: YES)
```

Same tunnel, good user/pass hangs forever:

```
$ ./flyway -url=jdbc:mysql://localhost/<db> info
Flyway Community Edition 5.0.7 by Boxfuse

Database user: user
Database password:
<hangs>
```

Same result with the MariaDB driver, same result using `127.0.0.1` instead of `localhost`. Connections via localhost work fine via other tools (Sequel Pro, mysql CLI). No extra information with debug (-X) enabled.

###### What did you expect to see?

Same output as a direct connection.

**Comment by axelfontaine** [comment]
What makes you think this is a Flyway issue and not a JDBC driver or Aurora issue?

**Comment by pikeas** [comment]
Aurora: other software (as mentioned above, Sequel Pro, mysql CLI) works perfectly over an ssh proxy. There may be an Aurora issue, but it seems less likely.

JDBC: I have no idea, I'm a consumer of Flyway, JDBC is an implementation detail from my perspective. Is there a way for me to generate additional logs and debugging info to help troubleshoot this?

**Comment by axelfontaine** [comment]
Under the hood, Flyway uses the MySQL JDBC driver to connect to Aurora and delegates all network communication to it. I highly suspect the issue lies with the MySQL JDBC driver or Aurora itself. Your best bet is probably to get AWS support to investigate. Not a Flyway issue.

**Comment by pikeas** [comment]
I've been test driving Flyway for my day job, it was the front runner in my research of database migration tools. We would have happily purchased the Enterprise edition, but this issue prevents us from even getting started with the product.

I'll ping AWS support to see if they have any thoughts, but based on this response I'll be test driving your competitors.

**Comment by axelfontaine** [comment]
@pikeas My response is what it is because I sincerely believe there is nothing we can do on our end to fix this. Our code doesn't have any influence on this part of the stack. I look forward to hearing what AWS support has to say on this. Since Flyway with regular MySQL over SSH using JDBC works and the same with Aurora does not, I suspect AWS must implement some slight detail of the wire protocol differently which trips up the MySQL JDBC driver.

**Comment by pikeas** [comment]
Thank you for clarifying, the previous replies were a bit less helpful. I'll update here if and when I hear anything from AWS.

In the interim, I propose keeping this issue remain open if compatibility with Aurora is a goal for Flyway. This may not be Flyway's fault, but it does mean Flyway <-> Aurora is broken until resolved upstream.

If Flyway does not intend to support Aurora, it would be great if a note to that effect could be added to Flyway's docs.

**Comment by axelfontaine** [comment]
Any news from AWS support?

**Comment by axelfontaine** [comment]
Any news?

**Comment by pikeas** [comment]
Thanks for the ping, I'll follow up with my internal contact and start a forum thread as well.

**Comment by axelfontaine** [comment]
Any news?

**Comment by pikeas** [comment]
No replies on my thread: https://forums.aws.amazon.com/thread.jspa?threadID=278945

I'll try to nudge some of my internal AWS connections again.

**Comment by axelfontaine** [comment]
@pikeas I highly recommend you to sign up for AWS support. It's not too expensive at the lower tiers and they'll investigate all the way if needed.

**Comment by pikeas** [comment]
Yes, I'd love to escalate this via support. I'm used to having access to the higher tiers of AWS support when needed. Unfortunately, for internal reasons that's not currently an option at my company.

**Comment by ykoasanto** [comment]
@pikeas I ran into the same issue. I resolved this by downloading the latest driver for mysql: mysql-connector-java-8.0.11.jar and put it inside `drivers` folder. Once I have it there, I was able to connect to Aurora with no issues.

**Comment by axelfontaine** [comment]
@ykoasanto Thanks for confirming my initial suspicion. Closing.
