### ISSUE TITLE
On PostgreSql the alternate quote string literal is not detected if it is not followed by a space.

### ISSUE THREAD

**Issue by jMediaConverter** [flyway/flyway#1948]
###### Which version and edition of Flyway are you using?
Community Edition 5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
java API

###### Which database are you using (type & version)?
PostgreSQL 9.6

###### Which operating system are you using?
Does not matter.

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I am trying to run with flyway a SQL file containing the following function definition:
CREATE OR REPLACE FUNCTION bugTest() RETURNS TEXT AS $$
BEGIN
	return '';
END;
$$LANGUAGE plpgsql;

An ArrayOutOfBoundsException is thrown. The cause appears to be the fact that there is no space after the $$ alternate quote token on the last line. However this is a valid script that I can run in the PG query tool.

###### What did you expect to see?
No errors.

###### What did you see instead?
An exception is thrown.

**Comment by axelfontaine** [comment]
Good catch and thank for the snippet to reproduce! Fixed.
