### ISSUE TITLE
Issue integrating hibernate enver with flyway

### ISSUE THREAD

**Issue by manishgithub1173** [flyway/flyway#1951]
###### Which version and edition of Flyway are you using?
Latest
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle
###### Which database are you using (type & version)?
Mysql 5
###### Which operating system are you using?
Mac

###### What did you do?
Trying to integrate latest version of flyway. I have integrated hibernate enver library for maintaining audit tables for each entity and author table which all are created automatically.  But for flyway, we need to specify the entity table creation sql statements in the sql script. So how can i integrate enver with flyway?

public class AuthorRevisionListener implements RevisionListener {
    public final static String USERNAME = "Suay";
    @Override
    public void newRevision(Object revisionEntity) {
	    	AuthorEntity exampleRevEntity = (AuthorEntity) revisionEntity;
	        exampleRevEntity.setUsername(USERNAME);
    }
}

Author table(Entity is defined but columns are created automatically):
@Entity
@RevisionEntity(AuthorRevisionListener.class)
public class AuthorEntity extends DefaultRevisionEntity {
    private String username;
    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }
}

###### What did you expect to see?
author_entity should have been created.

###### What did you see instead?
Schema-validation: missing table [author_entity]. I cannot define sql statements for author entity as columns are defined by hibernate enver.

Log below:
2018-03-12 18:17:11.307[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.f.c.internal.database.DatabaseFactory [0;39m [2m:[0;39m Database: jdbc:mysql://localhost:3306/db_example (MySQL 5.7)
[2m2018-03-12 18:17:11.340[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.f.core.internal.command.DbValidate    [0;39m [2m:[0;39m Successfully validated 1 migration (execution time 00:00.010s)
[2m2018-03-12 18:17:11.375[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.f.c.i.s.JdbcTableSchemaHistory        [0;39m [2m:[0;39m Creating Schema History table: `db_example`.`flyway_schema_history`
[2m2018-03-12 18:17:11.429[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.f.core.internal.command.DbMigrate     [0;39m [2m:[0;39m Current version of schema `db_example`: << Empty Schema >>
[2m2018-03-12 18:17:11.431[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.f.core.internal.command.DbMigrate     [0;39m [2m:[0;39m Migrating schema `db_example` to version 1 - init
[2m2018-03-12 18:17:11.471[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.f.core.internal.command.DbMigrate     [0;39m [2m:[0;39m Successfully applied 1 migration to schema `db_example` (execution time 00:00.097s)
[2m2018-03-12 18:17:11.590[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mj.LocalContainerEntityManagerFactoryBean[0;39m [2m:[0;39m Building JPA container EntityManagerFactory for persistence unit 'default'
[2m2018-03-12 18:17:11.599[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.hibernate.jpa.internal.util.LogHelper [0;39m [2m:[0;39m HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
[2m2018-03-12 18:17:11.650[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36morg.hibernate.Version                   [0;39m [2m:[0;39m HHH000412: Hibernate Core {5.0.12.Final}
[2m2018-03-12 18:17:11.651[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36morg.hibernate.cfg.Environment           [0;39m [2m:[0;39m HHH000206: hibernate.properties not found
[2m2018-03-12 18:17:11.652[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36morg.hibernate.cfg.Environment           [0;39m [2m:[0;39m HHH000021: Bytecode provider name : javassist
[2m2018-03-12 18:17:11.681[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.hibernate.annotations.common.Version  [0;39m [2m:[0;39m HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
[2m2018-03-12 18:17:11.851[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36morg.hibernate.dialect.Dialect           [0;39m [2m:[0;39m HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
[2m2018-03-12 18:17:11.875[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.h.e.boot.internal.EnversServiceImpl   [0;39m [2m:[0;39m Envers integration enabled? : true
[2m2018-03-12 18:17:12.624[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.h.tool.hbm2ddl.SchemaValidator        [0;39m [2m:[0;39m HHH000229: Running schema validator
[2m2018-03-12 18:17:12.628[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mrmationExtractorJdbcDatabaseMetaDataImpl[0;39m [2m:[0;39m HHH000262: Table not found: author_entity
[2m2018-03-12 18:17:12.629[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mrmationExtractorJdbcDatabaseMetaDataImpl[0;39m [2m:[0;39m HHH000262: Table not found: author_entity
[2m2018-03-12 18:17:12.630[0;39m [33m WARN[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mationConfigEmbeddedWebApplicationContext[0;39m [2m:[0;39m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
[2m2018-03-12 18:17:12.635[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.apache.catalina.core.StandardService  [0;39m [2m:[0;39m Stopping service [Tomcat]
[2m2018-03-12 18:17:12.645[0;39m [32m INFO[0;39m [35m4413[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mutoConfigurationReportLoggingInitializer[0;39m [2m:[0;39m

**Comment by manishgithub1173** [comment]
Styling is not proper in above logs so attaching it in a file.

Adding error file 
[error.zip](https://github.com/flyway/flyway/files/1805672/error.zip)

**Comment by axelfontaine** [comment]
You have to generate the DDL and use that in a Flyway migration. See https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#envers-generateschema

Not a Flyway issue.
