### ISSUE TITLE
Repeatable migrations with identical names in directory per schema

### ISSUE THREAD

**Issue by elvis2** [flyway/flyway#1953]
###### Which version and edition of Flyway are you using?
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I am using the newest release on MacOS

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
SQL Server 2014

###### Which operating system are you using?
MacOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway migrate -X

###### What did you expect to see?
All Repeatable Stored Procedures sql files executed.

###### What did you see instead?
Failed

In our scenario, we have multiple countries represented in schemas that share the same proc name. A quick illustration of schema and proc names.

dbo/R__BusinessReport.sql
  -- This proc servers as a router, routing to the request to the correct country proc, based on logic and it's context.

na/R__BusinessReport.sql
  -- Creates the report just for North America

eu/R__BusinessReport.sql
  -- Create the report for Europe

The reason we have this arrangement is to reduce the logic in the application and to keep the app working for any other company entity outside of North America. Also, the procs generate slightly  different reports.

In this scenario, as Flyway runs through the list of Repeatable migrations, it makes successfully creates dbo/R__BusinessReport.sql but then complains when trying to create eu/R_BusinessReport.sql, saying the proc name is already in use / referenced. I was able to get around this temporarily by using this naming convention:

dbo/R__dbo--BusinessReport.sql
na/R__na--BuesinessReport.sql
eu/R__eu--BusinessReport.sql

Ideally, Flyway should be looking at the schema and file name to determine if it is a duplicate.

Thank you for such a great tool. I look forward to using it in our automation.

**Comment by axelfontaine** [comment]
A workaround for you could also be to run Flyway 3 times, each time pointing it at a different directory.

We currently have no plans to associate a special meaning to directories, but I am happy to leave this open for future consideration.

**Comment by MikielAgutu** [comment]
Changing this would break existing installations. It's also undesirable for most cases.
