### ISSUE TITLE
Support for Semantic Version

### ISSUE THREAD

**Issue by lordofthejars** [flyway/flyway#1956]
###### Which version and edition of Flyway are you using?

5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

H2

###### Which operating system are you using?

Mac OSX

###### What did you do?

Create migration files using semantic version

###### What did you expect to see?

That semantic version are supported for example (1.0.0-alpha.1)

###### What did you see instead?

A Failure`Invalid version containing non-numeric characters. Only 0..9 and . are allowed. Invalid version: 1.0.0-detail`

Notice that in the semantic version you can still specify an order: `1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0`

If interested I can provide a PR.

**Comment by axelfontaine** [comment]
Thanks for the suggestion. What is your exact usecase for this? And why is the current versioning scheme not sufficient for you?

**Comment by lordofthejars** [comment]
My use case is that I have several modules, each of the module contains its Flyway resource, so they are independent in this sense from a root module where all db migration files are stored. So I have module A with all scripts of that module, module B with all of them and so on so forth.

Then one solution is to do something like `V1_0_0_0` (for module A) `V1_0_0_1` for module B and so on so forth, but if we implement semantic version support then:

* we are following one spec, so any user knows exactly what can be done and what's not and link to its versioning process.
* it will allow something like `V1_0_0-moduleA.1`, `V1_0_0-moduleA.2`, `V1_0_0-moduleA.3` and the `.1` is the creation of schemas for module A, the `.2` the creation of tables and so on. Then you can have `V1_1_0-moduleA.1` which is the creation of tables of version 1.1 and so on

**Comment by lordofthejars** [comment]
I can try to contribute on that

**Comment by axelfontaine** [comment]
Thanks for your offer. I'd be happy to consider a pull request for code and docs if it doesn't break any existing installations.

**Comment by MikielAgutu** [comment]
@lordofthejars Have you done any work for this?

**Comment by MikielAgutu** [comment]
Closing for lack of response.

**Comment by grv87** [comment]
@lordofthejars, have you found a solution?

I see that your case
> something like `V1_0_0-moduleA.1`, `V1_0_0-moduleA.2`, `V1_0_0-moduleA.3`

1) is not semantic versioning. Module names are not pre-release labels
2) breaks Flyway migration order if somebody adds a module with a name *lesser* (ordered before) the names of existing modules: `V1_0_0-anotherModuleB.1`

On the issue, I believe SemVer support is still very desirable. But it doesn't solve problem of modules in any way.
