### ISSUE TITLE
Flyway - Redshift - Executing SQL's taking hours sometimes 

### ISSUE THREAD

**Issue by Punnapulusu** [flyway/flyway#1960]
###### Which version and edition of Flyway are you using?
flyway-5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
AWS Redshift RDS

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Taking hours to run below sql 
create group loader;
create group reporter;
create group dba_user;

###### What did you expect to see?

When running for the first time or on a clean environment , it runs like with in 30 s .

and sometimes it takes 2 - 3 hours to run 3 sql commands.

if I run the same sql's from AWS Redshift RDS Sql workbench , It takes 2-3 mins ... along with above mentioned 3 sqls and including DB schema creation and loading test data.

###### What did you see instead?
if I run the same sql's from AWS Redshift RDS Sql workbench , It takes 2-3 mins ... along with above mentioned 3 sqls and including DB schema creation and loading test data.

**Comment by axelfontaine** [comment]
Since Flyway only takes the SQL statement and sends it to the DB via the JDBC driver, I am afraid there is not much we can do here. This sounds like a case for AWS support where they should investigate why these simple group creating commands take so long. Please do add a comment with their response, as I am curious as well.

**Comment by Punnapulusu** [comment]
Thanks for the quick turn around Alex, I will certainly take it up with AWS , but this is happening when using Flyway
