### ISSUE TITLE
Support S3 locations

### ISSUE THREAD

**Issue by krazavet** [flyway/flyway#1961]
Hello,

I am using Flyway 5.0.7 and I am trying to access to SQL migration scripts located on a S3 repository.
I tried to do so using the configuration file:
```
...
flyway.locations=s3://<bucket>/<path to sql scripts>
...
```
But when running a command, I encountered an error: 
```
$ flyway info                                                                                                                                                                         
Flyway Community Edition 5.0.7 by Boxfuse

ERROR: Unknown prefix for location (should be either filesystem: or classpath:): s3://<bucket>/<path to sql scripts>
```
I am missing something ? 
Or SQL locations are reserved to local filesystem only ?

Thanks in advance

**Comment by axelfontaine** [comment]
Related to #1779

**Comment by Lyeeedar** [comment]
Moving this to flyway 7.x as the v2 SDK requires upgrading flyway from java 7. See https://github.com/flyway/flyway/pull/2458#issuecomment-582872908

**Comment by MikielAgutu** [comment]
@miron4dev This is slated for the V7 release, which we aim to get out summer this year.

**Comment by sanketh-shetty-incontact** [comment]
Hi,

Any update as to when this will be released?

**Comment by slsshetty** [comment]
Hi,

Any updated when will this be released?

**Comment by RanjithTom** [comment]
Any updates on supporting S3 location in flyway.url.locations

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
