### ISSUE TITLE
Migrations order

### ISSUE THREAD

**Issue by raderio** [flyway/flyway#1962]
We use Liquibase, and now in new project we must use Flyway. In liquibase migrations order is in xml file, so you specify what migration are first and what are second, it do not depends on names.

So, when some developer add new migration, if before that someone else pushed a new migration he would get a conflict in Git, and it must fix ordering.

How this is done in Flyway? How to control order if migrations are added in parallel?

https://stackoverflow.com/questions/49505899/flyway-migrations-order

**Comment by axelfontaine** [comment]
This is not an issue, but a question. Please don't crosspost from StackOverflow.

Related to #1898

**Comment by raderio** [comment]
The question on StackOverflow https://stackoverflow.com/questions/49505899/flyway-migrations-order

**Comment by raderio** [comment]
SO, is there a way to specify the execution order?
