### ISSUE TITLE
Inconsistent results when trying to download https://plugins.gradle.org/m2/org/flywaydb/flyway-core/4.0.3/flyway-core-4.0.3.jar

### ISSUE THREAD

**Issue by ldm810** [flyway/flyway#1963]
###### Which version and edition of Flyway are you using?

https://plugins.gradle.org/m2/org/flywaydb/flyway-core/4.0.3/flyway-core-4.0.3.jar

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using (type & version)?
N/A

###### Which operating system are you using?
alpine 3.7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

In my CI I try to download https://plugins.gradle.org/m2/org/flywaydb/flyway-core/4.0.3/flyway-core-4.0.3.jar. I specified jcenter and mavenCentral as repositories. 

###### What did you expect to see?

I expect the dependency to be downloaded

###### What did you see instead?
Sometimes the dependency is downloaded and other times it does not download. I get the following error:
```
* What went wrong:
A problem occurred configuring root project 'java'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find flyway-core.jar (org.flywaydb:flyway-core:4.0.3).
     Searched in the following locations:
         https://plugins.gradle.org/m2/org/flywaydb/flyway-core/4.0.3/flyway-core-4.0.3.jar
```

**Comment by axelfontaine** [comment]
Not a Flyway issue. Either an Gradle issue or some issue with your infrastructure.
