### ISSUE TITLE
Unable to migrate schema_version to flyway_schema_history

### ISSUE THREAD

**Issue by zingybrett** [flyway/flyway#1964]
###### Which version and edition of Flyway are you using?
5.0.7, community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Postgresql 9.6.x

###### Which operating system are you using?
Archlinux

###### What did you do?
To prepare for the 6.0 `schema_version` -> `flyway_schema_history` rename, I want to move that table over via a migration as we have earlier migrations that use `schema_version`. I used the following:

```
CREATE TABLE flyway_schema_history AS
    SELECT * from schema_version;
DROP TABLE schema_version;
```

But Flyway still wishes to write the history in the old `schema_version` table.

Is there any advised path forward?

###### What did you expect to see?
Success and flowers?

###### What did you see instead?
`ERROR: relation "master.schema_version" does not exist`

**Comment by axelfontaine** [comment]
No need to rename. As the warning message says you simply need to make an old implicit default explicit for things to keep on working.
