### ISSUE TITLE
Migration path from flyway 4 to flyway 5 (and 6)

### ISSUE THREAD

**Issue by letientai299** [flyway/flyway#1965]
I's surprising me when upgrade to flyway 5 today and see warning regards `schema_version` has been changed to `flyway_schema_history`.

<details>
 <summary> Gradle warning </summary>
   <pre><code>
> Task :flywayMigrate

Could not find schema history table "public"."flyway_schema_history",
but found "public"."schema_version" instead. You are seeing this message
because Flyway changed its default for flyway.table in version 5.0.0
to flyway_schema_history and you are still relying on the old default
(schema_version). Set flyway.table=schema_version in your configuration
to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
   </code></pre>
</details>

For me, set `table = 'schema_version'` in `flyway{...}` in `build.gradle` is not a problem. The migration works as before. But, I've some concerns:

- Are there's any other undocumented changed? I've tried to look up for the reason behind the table name changes. It's not mention in the [announcement blog post](https://flywaydb.org/blog/flyway-5.0.0).  The only place mentioned this is Changes section in the [Release note](https://flywaydb.org/documentation/releaseNotes), which links to #1848, and the issue by itself doesn't justify the reason behind the change. What's wrong with the old name?

- Can we just rename the table (via `ALTER TABLE ...`) to prevent that warning, and keep using flyway 5 and 6? The message states that the fallback mechanism won't be available in version 6. If I understand correctly, my `schema_verion` table won't be usable when upgrade to flyway 6, and I'll stuck with flyway 5 forever. Of course, drop that table which contains all change history is not an option.

This issue is related with #1964, but I believe I'm asking different questions.

**Comment by axelfontaine** [comment]
No need for concern. You already did all that needed to be done.

**Comment by letientai299** [comment]
So we can just `ALTER TABLE ` to rename it, get rid of fallback config for gradle and no need to worry about upgrade to Flyway 6?

**Comment by axelfontaine** [comment]
No alter table. Just keep the new line in your config

`table = 'schema_version'`

No further changes are needed. Exactly as the warning message says.

**Comment by seiyapl** [comment]
Hi,
But wouldn't the ALTER TABLE be the recommended way of update?
I mean, with each new release it's good to check my config files against changes introduced in new versions and it probably be better to have smaller amount of differences from default config.

**Comment by hotzen** [comment]
@axelfontaine i also understood the warnings that `table = 'schema_version'`  is a workaround for the moment and it seems suggesting that an `ALTER TABLE` is actually the recommended way to match the new default?

**Comment by mhaberl** [comment]
@axelfontaine Would you recommend using the ALTER TABLE to match the new default name?
Just out of curiosity, what was the reason for changing the table name?

**Comment by latuszek** [comment]
`ALTER TABLE` works for me.
