### ISSUE TITLE
Unable to undo migration

### ISSUE THREAD

**Issue by boha11oran** [flyway/flyway#1967]
###### Which version and edition of Flyway are you using?

Flyway Trial Edition 5.0.7 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

PostgreSQL 9.6

###### Which operating system are you using?

CentOS Linux 7.3

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

flyway undo -user="denver" -password="" -locations=filesystem:/opt/flyway/sql

###### What did you expect to see?

Successful undo of migration version 21.76.87

###### What did you see instead?

"Unable to undo migration to version 21.76.87 as no corresponding undo migration has been found."

bash-4.2$ pwd
/opt/flyway
bash-4.2$ flyway undo -user="denver" -password="" -locations=filesystem:/opt/flyway/sql
Flyway Trial Edition 5.0.7 by Boxfuse
WARNING: You are using the 30 day limited Flyway Trial Edition. After 30 days you must remove this version and either upgrade to Flyway Pro Edition or Flyway Enterprise Edition or downgrade to Flyway Community Edition.

Database: jdbc:postgresql://127.0.0.1:5432/denver (PostgreSQL 9.6)
Current version of schema "public": 21.76.87
ERROR: Unable to undo migration to version 21.76.87 as no corresponding undo migration has been found.
bash-4.2$ ls /opt/flyway/sql/V21.76.87__chaseUrlUpdate.sql 
/opt/flyway/sql/V21.76.87__chaseUrlUpdate.sql
bash-4.2$ psql -U denver -d denver
psql (9.6.8)
Type "help" for help.

denver=# select * from schema_version order by installed_rank desc limit 1;
 installed_rank | version  |  description   | type |            script             |  checksum   | installed_by |        installed_on        | execution_time | success 
----------------+----------+----------------+------+-------------------------------+-------------+--------------+----------------------------+----------------+---------
             41 | 21.76.87 | chaseUrlUpdate | SQL  | V21.76.87__chaseUrlUpdate.sql | -2026313102 | denver       | 2018-03-30 12:41:31.237087 |              1 | t
(1 row)

denver=# \q
bash-4.2$ cat /opt/flyway/conf/flyway.conf 
flyway.url=jdbc:postgresql://127.0.0.1:5432/denver
flyway.baselineOnMigrate=true
flyway.mixed=true
flyway.table=schema_version
bash-4.2$ ls -altr ./sql/V21.76.87__chaseUrlUpdate.sql 
-rw-r--r-- 1 postgres postgres 242 Mar 30 12:41 ./sql/V21.76.87__chaseUrlUpdate.sql
bash-4.2$

**Comment by axelfontaine** [comment]
@boha11oran As the error message says, you need to supply your own undo script. In your case it would be called `U21.76.87__chaseUrlUpdate.sql` and would contain the statements that would undo the changes of `V21.76.87__chaseUrlUpdate.sql`. See https://flywaydb.org/getstarted/undo
