### ISSUE TITLE
PostgreSQL UTF-8 message problems

### ISSUE THREAD

**Issue by reitzmichnicht** [flyway/flyway#1969]
###### Which version and edition of Flyway are you using?
5.0.7

I'm executing commands on PostgreSQL 9.6.x database and get wrong encoded log messages for locale de

SqlScript migration with this content:
```
analyze verbose schema.table;
```

results in this log messages:
```
2018-04-03 14:18:03,095 INFO  [default task-41] [] org.flywaydb.core.internal.database.ExecutableSqlScript: DB: analysiere �schema.table�
2018-04-03 14:18:03,095 INFO  [default task-41] [] org.flywaydb.core.internal.database.ExecutableSqlScript: DB: �table�: 0 von 0 Seiten gelesen, enthalten 0 lebende Zeilen und 0 tote Zeilen; 0 Zeilen in Stichprobe, sch�tzungsweise 0 Zeilen insgesamt
```

Kind regards,
Michael

**Comment by axelfontaine** [comment]
Please stick to the template when reporting issues, as your current report leaves many questions about what could be causing this unanswered.

This is however most likely due to either your console settings (if you are on Windows) or your encoding configuration of your database. Either way, not a Flyway issue.

**Comment by reitzmichnicht** [comment]
Hi

I'm using Java client with Postgres running on Windows.
Having this DB Setup I'm still seeing encoding issues:
```
CREATE DATABASE "foo"
  WITH OWNER = alice
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'C'
       LC_CTYPE = 'C'
       CONNECTION LIMIT = -1;
```

So I doubt it is anything that can be configured on db side.

Kind regards,
Michael

**Comment by reitzmichnicht** [comment]
You are right, it's an issue of the IntelliJ console. Damn
