### ISSUE TITLE
CockroachDB 2.0 support

### ISSUE THREAD

**Issue by arteniioleg** [flyway/flyway#1970]
https://github.com/cockroachdb/cockroach/releases

I tried to execute `flyway clean` and `flyway baseline` but I kept getting errors about scheme. All attempts to fix it by changing config parameters have failed.

I just want to know if it's officially supported.

**Comment by axelfontaine** [comment]
As [stated in the docs](https://flywaydb.org/documentation/database/cockroachdb#supported-versions), current support is for 1.1 only.

**Comment by cristhiank** [comment]
I'm having the same issues with the 2.0 version. 
I found out that Flyway is looking for existent schemas in the pg_namespace table as seen in the following line. 
https://github.com/flyway/flyway/blob/2e6043074d7920d326cfb66739a3a3b27f8f6cc7/flyway-core/src/main/java/org/flywaydb/core/internal/database/cockroachdb/CockroachDBSchema.java#L45

But it seems that CockroachDB 2.0 doesn't create a record for the user databases in the pg_namespace table. 

This can be fixed if we use pg_database instead of pg_namespace.

**Comment by cristhiank** [comment]
I was digging into the CockroachDB and it seems that they do not support "custom" schemas inside the databases, the 'public' schema is always fixed to the user objects. 
I'm working in a pull-request, I will let you know and reference this issue when it's ready.

**Comment by arteniioleg** [comment]
I don't need custom schemas. Making flyway work only with `public` schema with Cockroach will be an acceptable solution.

**Comment by cristhiank** [comment]
Hello @axelfontaine ,

Is there any "CI" builds we can use as a temporary solution while the next release is out?
I'm really looking forward to the revision of this issue. Thanks!

**Comment by nstewart** [comment]
This should be resolved in Flyway 5.1 cc @axelfontaine

**Comment by axelfontaine** [comment]
@cristhiank We expect this to land on master early next week. From then on you will be able to build Flyway from source to use it until the official 5.1 release.

**Comment by axelfontaine** [comment]
We have just pushed support for CockroachDB 2.0. The current master now supports both CockroachDB 1.1 and 2.0. There are no known issues. You can access it by building from source until the official 5.1 release.

**Comment by tirasmuturi** [comment]
@axelfontaine could you tell us when flyway version 5.1 will be released.

**Comment by arteniioleg** [comment]
I'm also waiting 5.1 because I don't know how to compile it and don't want to waste time learning it.

**Comment by cmakamara** [comment]
You can use this temporarily, basically pulls from the master branch [https://plugins.gradle.org/plugin/com.radioafricagroup.plugins.flyway](https://plugins.gradle.org/plugin/com.radioafricagroup.plugins.flyway). Also make sure to include jitpack.io in your build script repositories

**Comment by arteniioleg** [comment]
Thank you for [the release](https://github.com/flyway/flyway/releases/tag/flyway-5.1.0)!
