### ISSUE TITLE
Improve error handling of jdbc migrations

### ISSUE THREAD

**Issue by reitzmichnicht** [flyway/flyway#1972]
###### Which version and edition of Flyway are you using?
5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
SQL Server

###### Which operating system are you using?
Windows 7

###### What did you do?
Writing a JDBC Migration which might produce a SQLException

###### What did you expect to see?
Detailed logging about the failed migration.

###### What did you see instead?
Migration failed!

The JdbcMigrationExecuter catches anything and wraps it into a FlywayException, the pretty error printing seems to be only activated on a FlywayMigrateSqlException exception.
The doMigrateGroup would convert a SQLException to a FlywayMigrateSqlException, but that doesn't work because the JdbcMigrationExecuter wraps the SQLException into a FlywayException.

**Comment by axelfontaine** [comment]
Thanks for reporting. That improvement is already on master. See https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/resolver/jdbc/JdbcMigrationExecutor.java#L47
