### ISSUE TITLE
Custom name convention

### ISSUE THREAD

**Issue by albfan** [flyway/flyway#1974]
###### Which version and edition of Flyway are you using?

versión 5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

maven plugin

###### Which database are you using (type & version)?

oracle 12

###### Which operating system are you using?

linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We want to use a different name convention to apply scripts, like: To upgrade versión 1.0.0 alpha0:

```
1.0.0/a0/01_create.sql
1.0.0/a0/02_insert.sql
1.0.0/a0/03_update.sql
1.0.0/a0/rollback/01_update.sql
1.0.0/a0/rollback/02_insert.sql
1.0.0/a0/rollback/03_create.sql
```

###### What did you expect to see?

On upgrade, these sqls 

```
1.0.0/a0/01_create.sql
1.0.0/a0/02_insert.sql
1.0.0/a0/03_update.sql 
```

are applied in that order

On rollback

```
1.0.0/a0/rollback/01_update.sql
1.0.0/a0/rollback/02_insert.sql
1.0.0/a0/rollback/03_create.sql
```

this ones

###### What did you see instead?

We can only use

```
1.0.0/a0/V1.0.0_a0_01_create.sql
1.0.0/a0/V1.0.0_a0_02_insert.sql
1.0.0/a0/V1.0.0_a0_03_update.sql
1.0.0/a0/rollback/U1.0.0_a0_01_update.sql
1.0.0/a0/rollback/U1.0.0_a0_02_insert.sql
1.0.0/a0/rollback/U1.0.0_a0_03_create.sql
```

to apply scripts

**Comment by axelfontaine** [comment]
Related to #1858

**Comment by MikielAgutu** [comment]
We don't think Flyway should work this way.
