### ISSUE TITLE
flyway migrated modules causing "Inconsistent Line Endings" popup when Modifying in SSMS

### ISSUE THREAD

**Issue by gitnature** [flyway/flyway#1976]
###### Which version and edition of Flyway are you using?

5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

DOS command line

###### Which database are you using (type & version)?

SQL Server 2016

###### Which operating system are you using?

Windows 7 Professional

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

What is happening is that I scripted code (tables, procedures, etc.) from a SQL Server database storing it with ANSI encoding (SQL Server gives you options for Unicode and ANSI).
Then migrated it to another SQL Server database which was successful.
Then, when I try to Modify a procedure module in the new database, I get a popup error
saying "Inconsistent Line Ending" and "The line endings in the following file are not consistent. Do you want to normalize the line endings?"
I have tried the following flyway encoding options and none of the them fix the issue:
flyway.encoding=ISO-8859-1
flyway.encoding=Windows-1252
flyway.encoding=UTF-8

Examining file with Notepad++ shows all lines in the file have consistent CR+LF endings in the migration file.  It seems like flyway is doing something to the end of lines during migration.  I have examined many of the reported issues and do not see this addressed.

###### What did you expect to see?
No error message.

###### What did you see instead?
The "Inconsistent Line Endings" popup message.

**Comment by axelfontaine** [comment]
Duplicate to #1420 

This has now been fixed. Please try again with the latest code by building from master. Things should now work as expected.
