### ISSUE TITLE
Migration fails when importing mysql dump

### ISSUE THREAD

**Issue by jorgevillaverde** [flyway/flyway#1978]
###### Which version and edition of Flyway are you using?
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
MySQL

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
mvn flyway:migrate

###### What did you expect to see?
BUILD SUCCESS

###### What did you see instead?
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Migracion de base de datos de SIBE 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- flyway-maven-plugin:5.0.7:migrate (default-cli) @ sibe ---
[INFO] Flyway Community Edition 5.0.7 by Boxfuse
[INFO] Database: jdbc:mysql://localhost/dv360_nbch (MySQL 5.7)
[INFO] Successfully validated 2 migrations (execution time 00:00.130s)
[INFO] Creating Schema History table: `dv360_nbch`.`flyway_schema_history`
[INFO] Current version of schema `dv360_nbch`: << Empty Schema >>
[INFO] Migrating schema `dv360_nbch` to version 1.0 - Base version
[WARNING] DB: Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release. (SQL State: HY000 - Error Code: 3090)
[WARNING] DB: Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release. (SQL State: HY000 - Error Code: 3090)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.144 s
[INFO] Finished at: 2018-04-09T09:37:35-03:00
[INFO] Final Memory: 11M/230M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:5.0.7:migrate (default-cli) on project sibe: org.flywaydb.core.api.FlywayException: No value provided for placeholder expressions: ${?d<???\?\?p{n\?s?$\?#I???#\?\?\0EJH?\?/????\?l?M?\"?H???\"\?\?\0E?H??Rg}, ${?d<??6?\?\?psf\?s?$\?#I???#?\?\0E\nH?\?Z\?\??Qm???\"\?H???\"?\?\0E?H???\??J#B?e!?\'TM???R\?\?c\?\?????8???\?;Rp#??9???C\Z??\?c???E~??\???4*P???2$Q@?\0??_\"?\?\??_o?\?V\'??\?\?\????J\???\??-?j?\?@to\"?c???w\n?\????zx8B:2??q?Y~???$\?@`?|PM\?\?\'2?\0N???\???\??uf?\'\?\?F?n?-Z?\?\n\?h?6??M^?F??\?\?cqQ?\?    ?f|\?oii?\?\?\?@v\?H??\?\??N?\?\?u???>x?m\?|??H?????i\?g4E????~dh?(?\?h?\'Kk????+\?      ?\ZB?rPF/(?\\J?\?(Z(E\?h02(?\?_?Q\????\?\?j?qi\?I?VK??\?\?b2u?\??\'??MJ>J.\?gRacJ6%?K?2)f?(?\?[N?h\?5u?\'N\?i%i?O?\?    ?]?I??J2????S?\?z|8??\?g?c??\??\?\?\??`W??v\???\?\?\??\?\?\?\??\?~??s\?x?5???\?v?Z\?\??S}, ${*#?%l????\?T??J\?%]?Mr5\?\?th??#42?CEv?\n7s?T??c\??G?\?\? >?????\?t??\?=\0H?e\?\0B-G\0/\?3W?\?:??0\??Y]? \?w. ??+-\?\n?zW?O\?\?\?;??gm\?\?s???W\?g???^\?\?\?-i\?gi|?\?W?\?IQ+*?E5?(M??\?(C\r7?\?(?=$?!??\?C?\0?E?4D?a? H\?(I`\"*?}, ${/5( ?G??q?\?\Z$??hc\nG?q??(???cGKuw?\??J4(i^i@.$?\?j\?xI78?\\?\?#??j\?t\?6@?     \?\?%r??u?-\?[A\?\?ç??6 \??}, ${/5(   ?G??q???Ib??hc\nG?q??(???cGKuw?\??J4(i^i@,$Gk?i??Qq?pc?G{?i?d Q??hc??\?????\?\?\?S\?]?\?>?>\?\?Cn?nOV3??v?\??!\?Ò\?Sx\?\r\?\??\?&????1@\??\?\?h?+\????!,2????=Y\?z???b\n???=X\?|?\??b???<\?K\?]??#2:??\Z\?!7QkC%?`?G*?\?\??\?\?L\?(?\?\r\?16\?\?u?K?:??r?\?@#4\?\?2\?%C??l??\? ??Cn????d>\? ?CCn??    |?h?\?9/_\?\?Bn?\??\?+?0b?\n?\r??<\?,??b???y?????+?[$?\?Ì?\?\?!?>7\?J0?\r?nOL?!7?7?JH\?pUl\????;????4i\?\'\??Ç??3      Gtw??Q0c?G?tw?QA?8c?Gktg?\?\?\?H???u?5F=?\?*&???\?\?????<E?)B?1???_\?0\\\?L#3B?1??}, ${:2??\??{?<*\?\?9\0}, ${<t??b\?\?????+\?\?        ?4\n1?\???\"i<?e?\?s?k?ag\?w7???\?=\?r\Z\?9}, ${T$?ı1I\??M?\?&\?\nhT\?=??T0???V6D*??q\?*Q?seO\?,\????ih@n?Z?\????!??a?\?r?G?j\?J?\??Fh\0Rw?\??d8\?9??FKq??\?.?\?#???j-????[?~?O?6???jc\?[??8?6?GM??o`\?*_\??m:?\?w?*?\?b\?N?\r\0|\?\0?UÔ\r?\?\?_??\r??\0????F+xI?Z:`?5|\niu\?a=\?\?\?H9|???0%Sb?SbB        ?09V???\Z)O,??D        \?N\?.B??C\'??{??\0\??p?`.?¾?hh???????0U4z\?\???\\???? ?\?G??\0u\?v\? ?\?\?\??\0z???-??^X?_\'mZ??-g?;\? ??%}, ${\"??>yB{t?=#?g$?5?\?\?b????(???Y?$X?^T?k??@1??\?X\nl\?u\?^&\?0??*<;?\?c???\??o\???\?W\?\?\?t\??\?z\?\Z??????????d\??\'C\"\?\?w??f\?Y0\??v\?\?\?+??\?^ec?+;?{???S\????9?z?T?????0?9?[??~Wz\??Z-??Hh?*_?\?\?J@?\????\??Cv??\?T\?E\??\?? \0k?p@\0?\?aOP??\?4H\?xZ!????3?????\'??&?\Zj??\?*w?\?S?y\??\?r;?-?O?o\?>?7J=?L?N}, ${xg\Z???+\"?%B\??d?d\? I?G?Um????WZn\??:??\?Lv\'{C$oC(c#%?|\?$%W4??????B??u?z?MUWL0E.gh???Ul>?\?3M?-%??\?j?<\?O&C]??\?%I?@X?.\'?+QiEVTY?IT??\?I@\?Y<??A8?\?&?hbK&??Q.??%?sB?%??}, ${xo\Z???+\"?%B\??d?d\?    I?G?Um?-?c     \?Tv;}, ${?f?`?C\?h\??66z??\?`???[7P0?\???H!{??x^\?m???? ??\?%y?36?DG????oM\?t???l?$?U?\?$?$SGt\?H{?4A@?V??Fv\?\??\?????\??\??\?0??bd\?\?@?\"????\??O??V?\?\r4?&\"\?\?x\?4W\?4\???;G????&-?    \?T?&\"\?\??|9[Z?\?$W???G\?r{1?e?t??\?u??V??\?F\??\?$pyJ??ve\?kLoI>  g?=?\?\?\?\'c{az?O\?``Qk??0\?X??\?N\?1?}, ${??????\?qr7(?@?}.  Check your configuration! -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by axelfontaine** [comment]
Binary dumps are not supported. You must use a SQL dump instead.
