### ISSUE TITLE
Update FAQ for hibernate integration

### ISSUE THREAD

**Issue by reitzmichnicht** [flyway/flyway#1981]
###### Which version and edition of Flyway are you using?
5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java with Hibernate

The linked Stackoverflow entry is only for Hibernate 4.x
I found this way to include Flyway with Hibernate 5.x for example in Wildfly >= 10
Perhaps it is worth for documentation:

```java
import java.util.Map;
import org.flywaydb.core.Flyway;
import org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl;

public class FlywayConnectionProvider extends DatasourceConnectionProviderImpl {

  @Override
  public void configure(final Map props) {
    super.configure(props);

    Flyway flyway = new Flyway();
    flyway.setDataSource(getDataSource());
    ...
  }

  @Override
  @SuppressWarnings("rawtypes")
  public boolean isUnwrappableAs(final Class unwrapType) {
    return super.isUnwrappableAs(unwrapType) || FlywayConnectionProvider.class.isAssignableFrom(unwrapType);
  }
}
```

With this entry in persistence.xml
```
 <property name="hibernate.connection.provider_class" value="package...FlywayConnectionProvider"/>
```

Kind regards,
Michael

**Comment by MikielAgutu** [comment]
Updated website with a link to this issue https://flywaydb.org/documentation/faq#hibernate-cdi.
