### ISSUE TITLE
Flyway 5.0.7 with SpringBoot 2 cannot work when 'locations' containes prefix 'filesystem:'

### ISSUE THREAD

**Issue by Cepr0** [flyway/flyway#1982]
###### Which version and edition of Flyway are you using?
Flyway 5.0.7 Community Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin 

###### Which database are you using (type & version)?
PostgreSQL

###### Which operating system are you using?
Windows 10

###### What did you do?
I use spring Boot 2.0.1 in my project and set `locations` property with 'filesystem' prefix:

`spring.flyway.locations=filesystem:../migration/common,filesystem:../migration/partner`

But application failed with the exception:

`2018-04-13 14:03:54.457 ERROR 7104 --- [           main] o.s.boot.SpringApplication               : Application run failed`

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed;`

`nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception;`

`nested exception is java.lang.IllegalStateException: Cannot find migrations location in: [filesystem:../migration/common, filesystem:../migration/partner] (please add migrations or check your Flyway configuration)`

Part of stack trace:

`Caused by: java.lang.IllegalStateException: Cannot find migrations location in: [filesystem:../migration/common, filesystem:../migration/partner] (please add migrations or check your Flyway configuration)
	at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.checkLocationExists(FlywayAutoConfiguration.java:168) ~[spring-boot-autoconfigure-2.0.1.RELEASE.jar:2.0.1.RELEASE]`

With previous version of Spring Boot (1.5.x) all worked as expected. 

###### What did you expect to see?
Normal work with Spring Boot 2 when 'locations' property contains prefix 'filesystem'.

###### What did you see instead?
Application failed.

**Comment by axelfontaine** [comment]
This is almost certainly an issue with either your working directory setting. Alternatively it is maybe a Spring Boot issue, but it is certainly not a Flyway one.

**Comment by charanack** [comment]
@Cepr0 Instead filesystem you can use `classpath`

`spring.flyway.locations=classpath:/db/migration
`

**Comment by zwolej** [comment]
I have same problem but problem is that I placed migration files in root of project and there is no way to point to that folder. Anyone knows how to point to root folder?

before spring boot 2 working path was:
``
spring.flyway.locations=filesystem:./in_root_folder
``
now, nothing works
``
spring.flyway.locations=classpath:/../../../in_root_folder
spring.flyway.locations=filesystem:./in_root_folder
spring.flyway.locations=filesystem:/../../../in_root_folder
``

**Comment by iamgbsmith** [comment]
After debugging the code in Spring Boot 2.x, I found that putting the following entry in your configuration file:

`spring.flyway.check-location=false`

Will skip the check which consistently failed when the location is prefixed with `filesystem`. 

It should then work if you specify:

`spring.flyway.locations=filysystem:/path/to/file/anywhere/on/the/filesystem`

Hope this helps.

**Comment by Cepr0** [comment]
@iamgbsmith Thank you very much for this workaround!

**Comment by zirconias** [comment]
> @Cepr0 Instead filesystem you can use `classpath`
> 
> `spring.flyway.locations=classpath:/db/migration `

the problem was : using double quote in `spring.flyway.locations="classpath:..."`
