### ISSUE TITLE
Ignore sqlplus set define off command in Community Edition

### ISSUE THREAD

**Issue by bretthodel** [flyway/flyway#1984]
###### Which version and edition of Flyway are you using?
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
Oracle 12.1

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I have sql*plus commands, such as `SET DEFINE OFF` in a number of my migration files.  In version 4 these were ignored successfully.  

###### What did you expect to see?
I expected that after migrating to version 5, these commands would continue to be ignored as I was on the community edition which doesn't have support for those commands.

###### What did you see instead?
Instead I saw errors saying `ora-00922 missing or invalid option`

My ask is if the community version can restore ignoring the SQL*Plus commands so that existing applications can upgrade to version 5 without issues.

**Comment by axelfontaine** [comment]
SQL*Plus support is a Flyway Pro feature which we do not plan to enable in the community edition.
