### ISSUE TITLE
Clean cannot drop schema with H2 1.4.197 and newer

### ISSUE THREAD

**Issue by ben-manes** [flyway/flyway#1989]
Gradle plugin: 5.0.7
H2: 1.4.197

`gradle flywayClean` will execute the statement `DROP SCHEMA "<name>"` and this works with H2  1.4.196. However, in the latest version it fails with `Cannot drop "<name>" because "..." depends on it`.

The grammar of H2 [DROP SCHEMA](http://www.h2database.com/html/grammar.html#drop_schema) states:
>Drops a schema. The command will fail if objects in this schema exist and the RESTRICT clause is used (the default). All objects in this schema are dropped as well if the CASCADE clause is used. This command commits an open transaction in this connection.

This indicates that the correct SQL statement would be `DROP SCHEMA "<name>" CASCADE`.

**Comment by axelfontaine** [comment]
Thanks for reporting. This was nastier than expected as H2 actually introduced a breaking change in a patch release. The `DROP SCHEMA ... CASCADE` syntax is the only one that works for this from 1.4.197 onward, yet it isn't supported at all in 1.4.196 and earlier. I have now added detection code to handle both versions transparently.
