### ISSUE TITLE
JAVA-API support for SQL Server integrated security

### ISSUE THREAD

**Issue by kusumat** [flyway/flyway#1991]
###### Which version and edition of Flyway are you using?
Flyway 4.0.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Seen in latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

JAVA API 

###### Which database are you using (type & version)?
SQL Server 2016

###### Which operating system are you using?

WINDOWS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?
expected flyway.setDatasource(url)

###### What did you see instead?
No api to provide url and skip username password

**Comment by kusumat** [comment]
This is not duplicate of [](https://github.com/flyway/flyway/issues/1646)

**Comment by axelfontaine** [comment]
Please don't open identical issues. Comment on existing ones instead.
