### ISSUE TITLE
CREATE SUBSCRIPTION PostgreSQL statement not detected as non-transactional

### ISSUE THREAD

**Issue by razvannegrea** [flyway/flyway#1992]
###### Which version and edition of Flyway are you using?
Flyway 5.0.7 community

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Postgresql 10.1

###### Which operating system are you using?
Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We are trying to create a PG logical replication setup. 
As part of this setup, on the server where data is to replicated, we need to run the following statement, after the database model is created:

CREATE SUBSCRIPTION ifdb_subscription CONNECTION 'host=xxx.xxx.xxx.xxx dbname=xxxx user=xxxx password=xxxx port=5432' PUBLICATION ifdb_publication;

###### What did you expect to see?
A successful migration message, just like for other migrations.

###### What did you see instead?

Migration V1.2__Setup_replication.sql failed
--------------------------------------------
SQL State  : 25001
Error Code : 0
Message    : ERROR: CREATE SUBSCRIPTION ... WITH (create_slot = true) cannot run inside a transaction block

**Comment by axelfontaine** [comment]
Good catch! This has now been fixed for both `CREATE SUBSCRIPTION` and `DROP SUBSCRIPTION`.
