### ISSUE TITLE
Getting checksum error when migrating from flyway 3.2.1 to flyway 5.0.x

### ISSUE THREAD

**Issue by tsatya** [flyway/flyway#1994]
###### Which version and edition of Flyway are you using?

Currently using 3.2.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
 
I am seeing this issue when I am updating flyway from 3.2.1 to 5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?
 Postgres 9.6

###### Which operating system are you using?
 Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

With flyway 3.2.1,  I could see in the logs, it was printing the database url with userid and password. I wanted to supress that. I came to know printing of db credentials is fixed in flyway 5. So thought to upgrade with flyway 5. When I upgrade it, it is giving me error checksum mismatch. 

How this can solved?

Or is there any way to stop printing db credentials in the logs?

**Comment by axelfontaine** [comment]
You must upgrade to Flyway 4.2.0 first. See https://flywaydb.org/documentation/releaseNotes#5.0.0 (It's literally the first item)

**Comment by GuruprasadBennur** [comment]
is there any way to avoid checksum issue? i have one senario like i would like to modify same script for multiple times, but definitely it will throw check sum issue, i want to avoid this check sum how to do it?
