### ISSUE TITLE
How to remove dB credentials being printed in logs

### ISSUE THREAD

**Issue by tsatya** [flyway/flyway#1997]
###### Which version and edition of Flyway are you using?

4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java api

###### Which database are you using (type & version)?

Posters 9.6

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

With flyway 4.2.0, I could see in the logs, it was printing the database url with userid and password. I wanted to supress that. 

 is there any way to stop printing db credentials in the logs? Is flyway provides any way to control the log level ?

**Comment by axelfontaine** [comment]
Simply upgrade to Flyway 5.x or use your preferred logging framework to silence the offending logger. 

Please refrain from posting such questions in the issue tracker and post them on StackOverflow under the Flyway tag instead.
