### ISSUE TITLE
Valid MySQL accounts cannot login via Flyway

### ISSUE THREAD

**Issue by gudatcomputers** [flyway/flyway#2000]
###### Which version and edition of Flyway are you using? 
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using (type & version)?
MySQL8.0.11

###### Which operating system are you using?
macOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
`flyway -user=root -password=password -url=jdbc:mysql://localhost:3306/mydb -locations=filesystem:src/db/migrations migrate`
`flyway -user=root url=jdbc:mysql://localhost:3306/mydb -locations=filesystem:src/db/migrations migrate`

###### What did you expect to see?
for the first command, successful migration
for the second command, a password prompt, then successful migration

###### What did you see instead?
first command gives `Access denied for user 'root'@'localhost' (using password: NO)`
second command prompts for password then  `Access denied for user 'root'@'localhost' (using password: NO)`

**Comment by gudatcomputers** [comment]
as a note, this same setup works if I downgrade to MySQL 5.7

**Comment by axelfontaine** [comment]
This is almost 100% an issue with your MySQL configuration. We have been testing Flyway for months with MySQL 8.0.x with no such issues.

**Comment by gudatcomputers** [comment]
an issue with the server config? or my flyway client config?  They are both just standard installs downloaded from the website.

**Comment by axelfontaine** [comment]
MySQL server configuration. Flyway literally passes the url, user and password you supply to the MySQL driver (make sure you are using the MySQL and not the MariaDB one, just to be safe) which in turns passes them to the DB.

**Comment by gudatcomputers** [comment]
hmm ok thanks.. don't know what would be up.. like I said it's a straight up install from the website...I'll try 8.0.x on another machine and verify it's not just machine weirdness.  Thanks for the follow up.

**Comment by HenriquePereiraRosa** [comment]
For now you can reinstall your MySQL Server instance and choose to use 5.x legacy access in instalation.

**Comment by digital-abyss** [comment]
Elaborating on @axelfontaine's answer -- I had the same issue on mac and solved it by downloading the java connector for [mysql](https://dev.mysql.com/downloads/connector/j/).  Selected 'Platform Independent' version and then used the `-jarDirs` option to specify the folder where I extracted the downloaded java connector.

**Comment by helpermethod** [comment]
For anyone wondering:

MySQL 8 requires and additional flyway dependency

```
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-mysql</artifactId>
</dependency>
```
