### ISSUE TITLE
Files with Suffix BASE, LOCAL, REMOTE are being executed

### ISSUE THREAD

**Issue by apexbine** [flyway/flyway#2004]
###### Which version and edition of Flyway are you using?
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
Oracle 12.1 and 12.2

###### Which operating system are you using?
Windows

###### What did you do?
flyway.conf:
flyway.sqlMigrationSuffixes=.sql,.pkg,.pkb,.pks

Windows command line:
flyway migrate 

###### What did you expect to see?
I expected Flyway to execute the first file but ignore the .BASE, .LOCAL and .REMOTE files, as .pkb is in the name but it's not the suffix.

Expected output:
Migrating schema "MY_SCHEMA" with repeatable migration **02 04 045 b pkb my package**

###### What did you see instead?

Actual output:
Migrating schema "MY_SCHEMA" with repeatable migration **02 04 045 b pkb my package**
Migrating schema "MY_SCHEMA" with repeatable migration **02 04 045 b pkb my package.pkb.BASE**
Migrating schema "MY_SCHEMA" with repeatable migration **02 04 045 b pkb my package.pkb.LOCAL**
Migrating schema "MY_SCHEMA" with repeatable migration **02 04 045 b pkb my package.pkb.REMOTE**

**Comment by axelfontaine** [comment]
I am unable to reproduce this. Can you post a small repo that reproduces the issue?

**Comment by apexbine** [comment]
Thanks, Axel, I'll get back to you.

**Comment by apexbine** [comment]
> Can you post a small repo that reproduces the issue?

Is there a manual or example how to do this (properly)?

**Comment by apexbine** [comment]
I can't reproduce it when I 'fake' the file names.
But it happens regularly when git creates the files while merging.

**Comment by axelfontaine** [comment]
I am afraid there must be something strange on your end. Please debug and reopen if you do manage to pinpoint Flyway as being the cause. It would be surprised if it were the case as this code is well tested and I can't reproduce it, but you never know.
