### ISSUE TITLE
SpringFramework FlywayAutoConfigurationBean Issue

### ISSUE THREAD

**Issue by sadhasivam** [flyway/flyway#2005]
###### Which version and edition of Flyway are you using?
Flyway: 5.0.7
SpringFramework 5
SpringBoot 2.0.1.RELEASE

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
GradlePlugin

###### Which database are you using (type & version)?
MySQL &H2

###### Which operating system are you using?
MacOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
we have to two yaml configuration files  
1. application.yml for all  production configuration information
  /src/main/resources/application.yml
    datasource pointing to mysql 

2. application-integration.yml for all testing configuration information
  /src/test/resources/application-integration.yml 
 datasource pointing to h2

###### What did you expect to see?
i expected to see my testing->integration spring profile should get picked up and Flyway work with H2 Database for all testing purposes.

###### What did you see instead?
FlywayAutoConfigurationBean always picks up src/ version of application.yml and looking for a mysql instance. is

**Comment by axelfontaine** [comment]
This is not a Flyway issue. Please check with the Spring Boot team.
