### ISSUE TITLE
Sybase ASE 11 support

### ISSUE THREAD

**Issue by mefernandez** [flyway/flyway#2009]
###### Which version and edition of Flyway are you using?

5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

NA

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

CLI

###### Which database are you using (type & version)?

Sybase ASE 11.0.3

###### Which operating system are you using?

CentOS release 4.9 (Final)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

cmd: `flyway baseline`
Connecting with JDBC driver JTDS 1.3

###### What did you expect to see?

"Successfully baselined schema with version: 1"

###### What did you see instead?

```
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unsupported Database: sql server 1.0
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:179)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1634)
	at org.flywaydb.core.Flyway.baseline(Flyway.java:1341)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:159)
	at org.flywaydb.commandline.Main.main(Main.java:108)
```

##### My comments

I'm not sure why Sybase ASE 11 is not supported, @axelfontaine ¿Is it because of DDL transactions?
I guess there's some limitation I'm not aware of.

Anyway, I forked this repo and made it work.
https://github.com/ondevio/flyway

¿Shall I create a pull request?

Cheers!

**Comment by axelfontaine** [comment]
This version has been released literally 23 years ago, around the same time as Windows 95. There are probably very few remaining users besides yourself if any, so adding support for it certainly wouldn't justify the additionally testing efforts required. Let alone that it is simply impossible to find a legal download of it.

Won't fix.

**Comment by mefernandez** [comment]
Hi @axelfontaine, thanks for your quick reply.
Yes, I agree with all of it.
`<sidenote class="friendly">`
"besides myself if any"? Ouch, that hurt, not my fault having to maintain old software.
`</sidenote>`

Should anyone need a version of Flyway working with Sybase ASE 11, head to my fork.
https://github.com/ondevio/flyway

Cheers!

**Comment by axelfontaine** [comment]
Hi @mefernandez , apologies if that came over a bit harsh, that certainly wasn't my intention. All I tried to say was that the user base is most likely infinitely small at this point.

Cheers!
