### ISSUE TITLE
It can't find flyway_schema_history but the table is there

### ISSUE THREAD

**Issue by fabiofalci** [flyway/flyway#2010]
###### Which version and edition of Flyway are you using?

5.0.7
Trying to migrate from 3.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin of the same version.
Maven version is 3.5.2

###### Which database are you using (type & version)?

Mysql: `Server version: 5.7.14-google-log (Google)`
But reproduced on h2 1.4.197

###### Which operating system are you using?

Linux

###### What did you do?

Migrating flyway from version 3 to 5.
I see that the table name has changed. Also the checksum has changed on version 4 but I skipped v4.

If I `mvn flyway:validate`, I get a checksum exception.

My goal was to copy the existing `schema_version` table to `flyway_schema_history`, keeping both for now, and `repair` the checksum of the new one.

After the copy, when running `validate` again, it outputs this:

```
[WARNING] Could not find schema history table "my_schema"."flyway_schema_history", but found "my_schema"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
```

But the `"my_schema"."flyway_schema_history"` table has been created. Got the same warning if using `flyway.table=flyway_schema_history`.

###### What did you expect to see?

Flyway using the new `flyway_schema_history` and outputing the same checksum exception.

###### What did you see instead?

Flyway still querying old  `schema_version`.

You can check this repo reproducing the issue:
https://github.com/fabiofalci/flyway-from-3-to-5

The first commit uses version 3 to create the database and the second to upgrade to version 5. The database has been commited so you don't need to recreate it.

Just try to run: `mvn flyway:validate`
Also check that the h2 database has the `flyway_schema_history` table.

**Comment by pzygielo** [comment]
How about https://flywaydb.org/documentation/releaseNotes

> Flyway 5.0.0 (2017-12-07)
> Important note for users upgrading from Flyway 3.x: This release no longer supports a schema history table upgrade from Flyway 3.x. You must upgrade to Flyway 4.2.0 first before upgrading to Flyway 5.0.0.

**Comment by fabiofalci** [comment]
I see, so there is no way of skipping v4.

**Comment by fabiofalci** [comment]
Ok, I was just being cautious in keeping `schema_version` around.

Now I deleted `schema_version` and then I was able to repair `flyway_schema_history`.

Maybe on my live database, I'll rename `schema_version` when repairing.

**Comment by fabiofalci** [comment]
Just to add an unlikely scenario.

I renamed the table to `flyway_schema_history` and seems to be working.

However, if I create a table named `schema_version` (who knows why), then flyway doesn't work anymore, even if I use `flyway.table=flyway_schema_history`. Shouldn't flyway forget about `schema_version` if the new name is found?

**Comment by fabiofalci** [comment]
Ok, decided to first migrate to 4 because the format of `schema_version` table has changed, the jump from 3 to 5 didn't work. @panchenko thank you for pointing out the changelog.

Will close this issue as it seems is not relevant.

**Comment by jtlambjr** [comment]
Adding a comment here in case anyone runs into the same issue we did. We have Spring Boot Starter, which is using Flyway 5.2.4. We had to rename the FLYWAY_SCHEMA_HISTORY table to lowercase, along with all of its column names. Then it started working.
