### ISSUE TITLE
SP is not creating through flyway SQL Server.

### ISSUE THREAD

**Issue by nkbysani** [flyway/flyway#2011]
###### Which version and edition of Flyway are you using?
flyway-4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

new versions are not supporting

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-Line

###### Which database are you using (type & version)?

SQL SERVER 2012

###### Which operating system are you using?

windows 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Invoke-Flyway -TargetDatabaseOption 5 -ServerName $serverName -Port $port -UserName $userName -Password $password  -CommandToolPath $sqlCommandpath -ScriptsPath $scriptsPath -Environment $environment

###### What did you expect to see?

Few Stored procedures are not executing with the combination, when i kept the only one SP it is executing properly.

###### What did you see instead?
incorrect syntax near 'end'
incorrect syntax near 'GO'
like the above errors are coming , error coming with last statement mentioned in the script.

for example : if the last statement is ";".
error is coming as 
incorrect syntax near ';'

**Comment by axelfontaine** [comment]
Please post the smallest stored procedure that Flyway has trouble parsing.

**Comment by nkbysani** [comment]
CREATE PROCEDURE [dbo].[uspDeleteGenericImportJournal] 
(
@CLID UNIQUEIDENTIFIER,
@CSID UNIQUEIDENTIFIER,
@sheetImportType nvarchar(50),
@JournalIdTable IdTable READONLY
)
AS
BEGIN

	DECLARE @LedgerID UNIQUEIDENTIFIER,@GLCOAID UNIQUEIDENTIFIER,@CLCOAID UNIQUEIDENTIFIER,@clientId UNIQUEIDENTIFIER,@NEXTGIJOURNALNO INT,
	@CalcCLID UNIQUEIDENTIFIER

	SELECT @LedgerID=ACCCS.CIID,@GLCOAID  = LIM.GLCOAID,@clientId=MT.ClientId,@CLCOAID=LIM.CLCOAID,@CalcCLID=CalcCL.CLID 
	FROM cmscenario CalcCS
	INNER JOIN CMLogical EntityCL ON EntityCL.CLID = @CLID
	INNER JOIN CMlogical CalcCL WITH(NOLOCK) ON CalcCS.CLID= CalcCL.CLID AND CalcCS.CSID=@CSID AND CalcCL.PLID = EntityCL.CLID
	INNER JOIN CMlogical ACCCL WITH(NOLOCK) ON ACCCL.PLID = CalcCL.CLID
	INNER JOIN CMScenario ACCCS WITH(NOLOCK) ON ACCCL.CLID = ACCCS.CLID AND ACCCS.CSID=@CSID
	INNER JOIN LedgerImportTypeMap LIM WITH(NOLOCK) ON LIM.LEDGERID = ACCCS.CIID
	INNER JOIN Maptemplate MT WITH(NOLOCK) ON MT.CID = LIM.GLmapID AND MT.SheetImportType COLLATE Latin1_General_CS_AS = @sheetImportType and IsNewMarkup=1
	
IF EXISTS (SELECT 1 FROM @journalIdTable)
BEGIN
    DELETE FROM JournalLineItem  WHERE JournalID IN (SELECT ID FROM @journalIdTable)
	DELETE FROM Journal WHERE ID IN (SELECT ID FROM @journalIdTable)
END
	
IF EXISTS (SELECT JL.AccountCode as Code,JL.AccountDescription as Description,cast(JL.Amount as varchar(50)) as 'Amount',cast(@CalcCLID as varchar(50)) as 'CLId', JL.LineItemType as Type 
	FROM Journal J	INNER JOIN Journallineitem JL ON J.ID=JL.JournalID
	WHERE J.ledgerid= @LedgerID AND J.SheetImportType COLLATE Latin1_General_CS_AS = @sheetImportType
	AND J.IsHistoric = 0)
	BEGIN
		SELECT JL.AccountCode as Code,JL.AccountDescription as Description,cast(JL.Amount as varchar(50)) as 'Amount',cast(@CalcCLID as varchar(50)) as 'CLId', JL.LineItemType as Type , CAST((CASE WHEN J.Type = 1 THEN 1 ELSE 0 END) AS BIT) IsAdjustment, JL.[SubAccount Code] as 'SubAccount Code', JL.AccountCode as 'Account Code'
		FROM Journal J
		INNER JOIN Journallineitem JL ON J.ID=JL.JournalID
		WHERE J.ledgerid= @LedgerID AND J.SheetImportType COLLATE Latin1_General_CS_AS = @sheetImportType
		AND J.IsHistoric = 0
	END
	ELSE
	BEGIN
		SELECT '' as Code,'' as Description,'0'as 'Amount',cast(@CalcCLID as varchar(50)) as 'CLId', ''as Type ,  CAST(0 AS BIT) IsAdjustment, '' as 'SubAccount Code', '' as 'Account Code'
	END
END

GO

CREATE PROCEDURE [dbo].[usptest]
AS
BEGIN
	SELECT 1
END

**Comment by nkbysani** [comment]
when i kept only first SP uspDeleteGenericImportJournal , executing properly.
but after that SP what ever i mention as above not executing ...don't know why. please help.

**Comment by axelfontaine** [comment]
Thanks for reporting. This was indeed a parsing issue and it has now been fixed.
