### ISSUE TITLE
Next realease ?

### ISSUE THREAD

**Issue by larochef** [flyway/flyway#2012]
Hello, 

I know the cockroachdb has been implemented already, and I'm willing to use it. In comments, you said to build from source or wait for a release. 

I saw in the milestones that a release is planned soon, but there seems to be still alot of work to get it done. 

So:
- Do you have an estimate date for release?
- If not, there are 45 commits since latest release, what is safest if building from source? build from latest commit? go to latest release and cherry-pick the cockroach 2 support? Is there anything to know in migrating from 5.0.7 to latest?

Thx in advance,

François

###### Which version and edition of Flyway are you using?

5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

java api

###### Which database are you using (type & version)?

cockroachdb, wanting to migrate to version 2.x

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by axelfontaine** [comment]
The latest version of the sources is always the best choice. Release is expected this month (some things took longer to polish than anticipated)
