### ISSUE TITLE
Flyway firing all scripts with same DB and different run modes of application

### ISSUE THREAD

**Issue by vir2610** [flyway/flyway#2020]
###### Which version and edition of Flyway are you using?
5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Spring boot Java API

###### Which database are you using (type & version)?
SQL Server 2016 Express

###### Which operating system are you using?
Windows 10 Pro build 1803

###### What did you do?
I am running my spring boot application with flyway configured in application.properties in 2 different modes, one from which I am developing this application, and one from executable WAR to see after packaged the application, flyway still behaves perfectly.
But What I found is, flyway overwrites DB content (i.e. Firing all scripts again) on same DB which I used to run from IDE. Now this issue only happened if I change the run mode (i.e. from IDE to new build WAR or from WAR to IDE). Please note that everything related to DB configuration is same,  I just change the run mode to executable WAR.
Please find my application.properties for flyway configuration

```
#Spring datasource properties
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1501;databaseName=issueDB1
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.dbcp2.max-total=5

#Flyway migration properties
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration/testissue
spring.flyway.out-of-order=true
spring.flyway.baseline-version=1.3
spring.flyway.mixed=true
spring.flyway.cleanOnValidationError=true
```

###### What did you expect to see?
Once flyway schema table is there, it should not fire all scripts again as database is same and just application run mode changes.

###### What did you see instead?
Fired all scripts as described above even though DB is same.

**Comment by axelfontaine** [comment]
This is not a Flyway issue. This is most likely due to your Spring Boot config or active profiles. Debug and open an issue with Spring Boot if the problem persists.
