### ISSUE TITLE
More Repeatable Migrations leads to ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by vladABC** [flyway/flyway#2024]
###### Which version and edition of Flyway are you using?
5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
Postgres 10, Fedora 27

###### Which operating system are you using?
Win 8.1

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I am creating Project and using Flyway for migration.
I configured a folder on resource folder as location for the flyway migrations that contained versioned migration  and  Repeatable Migrations (default prefix and separator: R_) and then migrate. Migrate successfully.
I added more Repeatable Migrations files and perform the migration so far. Migration was successful but at some point I got an exception java.lang.ArrayIndexOutOfBoundsException

###### What did you expect to see?
Success migration

###### What did you see instead?
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:5.0.7:migrate (default-cli) on project xxxxx: java.lang.ArrayIndexOutOfBoundsException -> [Help 1]

**Comment by vladABC** [comment]
600 Repeatable Migrations limit
same on: 5.0.6, 4.2.0, 4.1.2, 4.0.3

**Comment by axelfontaine** [comment]
Thanks for reporting. Please provide a small test repo that reproduces the issue as well as a full stack trace of the error.

**Comment by vladABC** [comment]
Sorry, my wrong. Error message confused me.
FYI  The error was in double comments in one Repeatable Migrations script.
