### ISSUE TITLE
Baseline migration is always updated when repairing

### ISSUE THREAD

**Issue by AndrasJanurik** [flyway/flyway#2025]
###### Which version and edition of Flyway are you using?
Community, 5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MySQL 5.7

###### Which operating system are you using?
Windows

###### What did you do?
called FlyWay.repair()
DbRepair.alignAppliedMigrationsWithResolvedMigrations(): 
when comparing resolved and applied typeUpdateNeeded is checked
(earlier it was not checked, in 4.2.0, where the method was called repairChecksumsAndDescriptions, therefore this behavior did not occur with 4.2.0)
the resolved type for sql migrations is always SQL (SqlMigrationResolver:149)
the applied type for a baseline migration is always BASELINE
therefore schemaHistory.update() is always called for baseline migrations when calling DbRepair.repair() (and FlyWay.repair())

One possible solution I could recommend (without a thorough knowledge of FlyWay so it might be wrong):
the given baseline description (FlyWay.setBaselineDescription()) could be used in the migration resolver to determine if an sql migration is actually a baseline migration and so the resolved type could then be BASELINE
One problem: the current default value "<< Flyway Baseline >>" is not valid for a windows file name

**Comment by axelfontaine** [comment]
Good catch. Fixed.
