### ISSUE TITLE
Regression in 5.1.0 regarding non-transactional migrations including comments

### ISSUE THREAD

**Issue by pakohan** [flyway/flyway#2029]
###### Which version and edition of Flyway are you using?

5.1.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line in alpine docker image

###### Which database are you using (type & version)?
Postgres 9.6

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

`migrate`

```sql
-- Insertion order invoicing state
ALTER TYPE invoicing_state ADD VALUE IF NOT EXISTS 'factored';
ALTER TYPE invoicing_state ADD VALUE IF NOT EXISTS 'partially_factored';
```

###### What did you expect to see?
That the migration succeeds.

###### What did you see instead?
It didn't.

When upgrading from 5.0.7 to 5.1.0 the non-transactional migrations feature breaks for every migration including SQL comments. It seems that flyway recognizes these as transactional-eligible statements and thus does not run migrations with non-transactional statements, when mixed-migrations are not allowed. Since we've already applied these on our prod system, we cannot fix this issue by altering these migrations to not include comments anymore nor do we want to alter the checksums in the schema_version tables.

**Comment by axelfontaine** [comment]
Thanks for reporting and the analysis. Fixed.
