### ISSUE TITLE
PostgreSQL: Restore role to its original value between migrations instead of resetting it

### ISSUE THREAD

**Issue by danieljamesscott** [flyway/flyway#2035]
###### Which version and edition of Flyway are you using?

5.1.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

PostgreSQL 9.6

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I need to be able to run 'set role $rolename' for all flyway migrations, including the initial metadata table creation. This is to ensure that the created objects are owned by the 'correct' user. We are using vault for database credential management, so the user running the migrations is dynamic and will change over time, leading to inconsistent ownership of objects.

###### What did you expect to see?

Possibly a flyway configuration option, or callback support to call 'set role'. I'm not sure if there's a callback which is run before the initial metadata table creation?

###### What did you see instead?

I saw a few issues related to this, including a call to 'RESET ROLE' which appears to be conflicting with my attempts to use connectInitSql on the pool, or the beforeMigration callback.

https://github.com/pradheeps/flyway/commit/5671442ea36fcf595ef8221271ba0622156e0b8f#diff-082a3414ab12680389b61424a632705cR90

**Comment by axelfontaine** [comment]
This should be achievable using a combination of callbacks.

For the initial schema history table creation, use the `beforeMigrate.sql` callback and then for the individual migrations use the `beforeEachMigrate.sql` callback.

**Comment by danieljamesscott** [comment]
Thanks, but would it be possible to add this in a cleaner way? I believe that this will become more of a problem as people start using dynamic users more.

**Comment by axelfontaine** [comment]
I am not sure a dedicated setting would be pulling its conceptual weight at this point, especially considering the easy workaround available.

But the future will tell. If this does prove to be a major pain point down the road, we'll gladly reconsider this decision.

**Comment by danieljamesscott** [comment]
Sure. Thanks.

Can we make it possible to disable the 'RESET ROLE' call? It seems a little strange to do a hard reset. If someone has changed role, then it should be their responsibility to change it back when they're done, right?

**Comment by axelfontaine** [comment]
> Can we make it possible to disable the 'RESET ROLE' call? It seems a little strange to do a hard reset. If someone has changed role, then it should be their responsibility to change it back when they're done, right?

No, as this would potentially produce different results. For example if V1 changes the role and V2 does not then running V1 + V2 together will produce a different result than running V1 and then later V2.

**Comment by danieljamesscott** [comment]
Yes, but if a user is messing with roles in the migration, then they should ensure that they do the reset, no?

By the same argument, if I connect with user1 and run v1 + v2, that produces a different result than when I connect with user1 and run v1 and then connect with user2 and run v2.

**Comment by danieljamesscott** [comment]
Would you accept a PR to make execution of Connection.doRestoreOriginalState configurable with a new configuration option in Configuration?

**Comment by axelfontaine** [comment]
> Would you accept a PR to make execution of Connection.doRestoreOriginalState configurable with a new configuration option in Configuration?

No, for the conceptual weight reasons I outlined above.

**Comment by danieljamesscott** [comment]
I'm not sure what's going on, but setting the role in the 'beforeMigrate' callback does not result in flyway_schema_history being owned by my role. It is owned by the connecting role. This appears to have stopped working around 5.0.7.

**Comment by axelfontaine** [comment]
I saw that you mentioned this in the PR comments. Can you debug and figure out why?

**Comment by danieljamesscott** [comment]
Looks like it's this line:

https://github.com/flyway/flyway/blame/master/flyway-core/src/main/java/org/flywaydb/core/internal/schemahistory/JdbcTableSchemaHistory.java#L111

**Comment by axelfontaine** [comment]
I am starting to think that an even better solution would be to expose the initSqls property of the data source to all clients. This would allow for a generic way to do things like set role before any other Flyway code runs.

This should then be combined with replacing the reset role calls with an initial call to read the current user and individual calls before each migration to reset the current user to the one we read before.

Feedback welcome.

**Comment by danieljamesscott** [comment]
This is exactly what I was asking for in the original issue report! 😃

**Comment by axelfontaine** [comment]
This has now been implemented. It should give you exactly what you need when used in combination with #1324 .
