### ISSUE TITLE
Sybase 15.7 not supported

### ISSUE THREAD

**Issue by seneiran** [flyway/flyway#2040]
###### Which version and edition of Flyway are you using?

5.1.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven Plugin

###### Which database are you using (type & version)?
Sybase 15.7

###### Which operating system are you using?

Jenkins Server : Linux 2.6.32-642.el6.x86_64 x86_64
Database server: HP-UX giotto1 B.11.31 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

i'm using flyway plugin with maven, i have tried several versions and currently the version 5.1 still having this issue. 

My Stack: 
Sybase 15.7
Flyway-maven-plugin v 5.1.0
JTDS 1.3.1

My connection string:

[INFO] Database: jdbc:jtds:sybase://x.x.x.81:17000/database (sql server 12.50)

And the error im getting:

Unsupported Database: sql server 12.50

###### What did you expect to see?

Successful connection

###### What did you see instead?

Unsupported Database: sql server 12.50

**Comment by EdoBarroso** [comment]
I'm getting the same error using Sybase 15.7 and the latest version of Flyway plugin for Maven :(

**Comment by ethervs** [comment]
Hi guys, please take a look at this one, we are also getting problems trying to connect to sybase.

**Comment by axelfontaine** [comment]
The installation you connect to appears to be running Sybase 12.50 and not 15.7.  The message you are seeing is correct. Sybase 15.7 reports as `ASE` with jTDS and `Adaptive Server Enterprise` with jconnect. Only older versions report as `sql server`.

**Comment by seneiran** [comment]
Hi Axel, i'm pretty sure i'm running v15.7 
In Db Client running:  select @@version
i'm getting this output:  Adaptive Server Enterprise/15.7/EBF 21151 SMP SP100
