### ISSUE TITLE
Sybase 15.7:  Incorrect syntax near 'GO'.

### ISSUE THREAD

**Issue by seneiran** [flyway/flyway#2041]
###### Which version and edition of Flyway are you using?

5.1.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven Plugin

###### Which database are you using (type & version)?

Sybase 15.7

###### Which operating system are you using?

Jenkins Server : Linux 2.6.32-642.el6.x86_64 x86_64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Running a SQL script validated previously with DBeaver 5.06, we are getting : 

[ERROR] Migration R__sp_tef.sql failed
[ERROR] ----------------------------------------------
[ERROR] SQL State  : 37000
[ERROR] Error Code : 102
[ERROR] Message    : Incorrect syntax near 'GO'.

###### What did you expect to see?

success SQL script execution

###### What did you see instead?
Error message previously described

**Comment by axelfontaine** [comment]
Please share the contents of the file, so we can check why it fails to parse correctly.

**Comment by seneiran** [comment]
Hey, sorry for the delayed response, i was cleaning the script. 

i have attached the conflictive SP.

Thanks in advance!

[sp_error.txt](https://github.com/flyway/flyway/files/2099985/sp_error.txt)

**Comment by axelfontaine** [comment]
Thanks for the file. That was very helpful. Flyway's parser was being tripped up by `ELSE'somestring'` constructs with no space in between. This has now been fixed.

**Comment by seneiran** [comment]
Thanks for the quick fix!  

@axelfontaine , do you have an estimated to release this to be used with maven plugin ?

**Comment by axelfontaine** [comment]
@seneiran This is currently scheduled for 5.2 which is due out by the end of August/early September. Until then you can easily work around this by adding a space between `ELSE` and the string literal immediately following it.
