### ISSUE TITLE
Unknown database error if schema not created in advance

### ISSUE THREAD

**Issue by barry1cassidy** [flyway/flyway#2050]
###### Which version and edition of Flyway are you using?
5.1.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MySQL

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I run Flyway command line without creating the schema in advance. The schema is included in the flyway.url parameter in the conf file.
flyway.url=jdbc:mysql://localhost:3306/my_db

I get the error when I run >flyway migrate

###### What did you expect to see?
My understanding is that the schema will be created if it doesn't exist. If I create the schema in advance, my migration script works perfectly.

###### What did you see instead?
I get this error when the schema is not created in advance:
ERROR: Unable to obtain connection from database (jdbc:mysql://localhost:3306/my_db) for user 'root': Unknown database 'my_db'

**Comment by axelfontaine** [comment]
Remove the schema from the url and add it to `flyway.schemas` instead and you should be fine.

**Comment by barry1cassidy** [comment]
Thanks. This worked for MySQL. However, we have another migration for a SQL Server database and we are getting the following error.

Unable to create schema [my_db]
SQL State  : S0001
Error Code : 15247
Message    : User does not have permission to perform this action.

I can create the schema with the same user with the following commands:
USE master
GO
CREATE DATABASE my_db
GO

Is there an additional configuration option or another approach required to get DB schema creation working with SQL Server?

Thanks,
Barry
