### ISSUE TITLE
Header comment on stored procedure not migrated to SQL Server

### ISSUE THREAD

**Issue by stevemiller2018** [flyway/flyway#2058]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 5.1.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This seems to be the same as Issue 1362 Header comment on stored procedure, which was to be fixed in release 5.1.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?
SQL Server 2014 SP2 CU11

###### Which operating system are you using?
Windows Server 2008 R2

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.) 
Migrated the following stored procedure source:

USE [CCR_FWTest]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sp_InsertActivityLog]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[sp_InsertActivityLog] AS' 
END
GO

/********************************************************************************************************************** 
** Chg001 07/31/2000 Excluded domain name from agent name - PML	     
** Chg002 06/27/2018 Moving comment block after alter statmenet to test Flyway Migration - SDM	 
*****************************************************************************************************************/

ALTER PROCEDURE [dbo].[sp_InsertActivityLog]

  @Customer_ID           int,
  @Activity_Message      varchar(255),
  @Activity_Message_Type varchar(255)

AS

  DECLARE  @Agent_Name varchar(30)

  SELECT @Agent_Name = User_Name()  /* For Integrated Logins */
	Select @agent_name	

###### What did you expect to see?

Expected to see all lines migrated to DB

###### What did you see instead?
Comment block is missing.  However all comments following the ALTER PROCEDURE statement do appear.   If comment block is moved to below the ALTER statement is shows up.

However, this is not practical as we have hundreds of SPs with the same format for header comments before the ALTER statement

**Comment by axelfontaine** [comment]
The issue is the blank line between the comment and the statement. If you remove it, Flyway will recognize as a header comment instead of a loose comment and will properly associate it with the statement.
