### ISSUE TITLE
Flyway doesn't allow to apply SQL Server 2016 in-memory objects

### ISSUE THREAD

**Issue by okosenko** [flyway/flyway#2062]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 5.1.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
SQL Server 2016

###### Which operating system are you using?
Windows 10, Windows Server

###### What did you do?
I'm trying to create script for SQL Server 2016 in-memory object

USE [MyOwnSchema];

CREATE TYPE dbo.someType  
AS TABLE
 ([Id]  BIGINT   NOT NULL INDEX IX_udt_someType_Id  NONCLUSTERED
 ,[Value]   NVARCHAR(500) NOT NULL
 ,[Type]    BIGINT   NOT NULL
 )
WITH ( MEMORY_OPTIMIZED = ON );

###### What did you expect to see?
Successful migration

###### What did you see instead?
Migrating schema [dbo] to version 1.10031 - create udtt someName
WARNING: DB: Changed database context to 'MyOwnSchema'. (SQL State: S0001 - Error Code: 5701)
ERROR: Migration of schema [dbo] to version 1.10031 - create udtt someName failed! Changes successfully rolled back.
ERROR:
Migration V1_10031__create_udtt_someName.sql failed
---------------------------------------------------
SQL State  : S000110
Error Code : 12331
Message    : DDL statements ALTER, DROP and CREATE inside user transactions are not supported with memory optimized tables.

**Comment by axelfontaine** [comment]
Thanks for reporting. This is actually trickier than it seems. While the `create type as table` and `create table` operations with `memory_optimized=on` are easy to detect, the `alter` and `drop` are not. This means that if we add autodetection for create, that still won't solve the issue for alter and drop. Supporting them would either require deeper introspection of the current DB state or the ability to override the autodetection (default) for the transaction support and allow to force it to be either on or off for a specific migration.

Either way this will need additional work to support properly. Delaying to 6.0 for now.

**Comment by okosenko** [comment]
Thanks for answer, we will wait till 6.0 release

**Comment by robertoandrade** [comment]
Is there a workaround for this? ie: flag a specific migration not to be executed in a transaction?

**Comment by robertoandrade** [comment]
Wonder if at least support for non-transactional `CREATE/DROP TYPE` can be added to https://github.com/flyway/flyway/blob/0c89fc00f8413a8123552391be8554d2940eb9e9/flyway-core/src/main/java/org/flywaydb/core/internal/database/sqlserver/SQLServerParser.java in time for the 6.0 release.

**Comment by tomasjanuskaitis** [comment]
Workaround can be to force specific migration script into non-transactional mode, using supported non-transactional statements aka fulltext index creation+drop.
For example:
create unique index <index name> on <random table>(<primary key column>);
create fulltext catalog <catalog name> as default; --if you don't have it
create fulltext index <random table>(<random column>) key index <index name> with stoplist = system;
drop fulltext index on <random table>;
drop fulltext catalog <catalog name>;
drop index <random table>.<index name>;

**Comment by juliahayward** [comment]
6.1.0 will include the ability to force specific scripts into non-transactional mode.
