### ISSUE TITLE
Schema Creation Fails on SQL Server

### ISSUE THREAD

**Issue by barry1cassidy** [flyway/flyway#2063]
###### Which version and edition of Flyway are you using?
5.1.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
SQL Server 2014 - Note: This is an Amazon RDS Instance

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway.url=jdbc:sqlserver://rds-instance-endpoint
I get the error when I run >flyway migrate

###### What did you expect to see?
If I connect to the RDS instance using a client tool, I can create the database using these commands:

USE master
GO
CREATE DATABASE my_db
GO

It seems like DB creation may not be working for SQL Server using the same technique you gave me for MySQL in this issue (2050)

###### What did you see instead?

Unable to create schema [my_db]
SQL State : S0001
Error Code : 15247
Message : User does not have permission to perform this action.

Is there an additional configuration option or another approach required to get DB schema creation working with SQL Server, particularly when it's an RDS instance?

Thanks,
Barry

**Comment by axelfontaine** [comment]
This is a permissions issue with your setup, not a Flyway issue. Also don't confuse `create database` with `create schema`. They mean the same on MySQL, but are totally different things with SQL Server.

**Comment by tweeks024** [comment]
@barry1cassidy did you ever find a way to make this work with RDS?  Without sa access or access to the master db we cannot figure out how this will work.

**Comment by barry1cassidy** [comment]
@tweeks024 Unfortunately no. Our workaround is 
1. Create the database manually before the initial migration script is run. 
2. Comment out the flyway.schemas parameter in the config file so that flyway doesn't attempt to create a schema.  
3. Add ";databaseName=SCHEMA_NAME"  to the end of the URL we provide for the flyway.url parameter in the config file.

**Comment by tweeks024** [comment]
@barry1cassidy thanks that works using the conf file, thanks for responding.

On a side note I tried what I thought was the equivalent through the cli arguments (not using -schema and putting ";databaseName=SCHEMA_NAME" on the URL) but it did not work through the CLI.
