### ISSUE TITLE
Add system property to provide regex based selection of repeatable file names

### ISSUE THREAD

**Issue by KangoV** [flyway/flyway#2064]
Add system property to allow for the selection of which repeatable files to be included repeatable.
This addition would be very useful in production, but would really come into its own during unit testing.

At the moment we are overriding exposed location system property to tell our service under test where to load the test data from. We are currently using cucumber and have many scenarios in the same feature. We'd like to select a single file by name/regex for each scenario.

I hope I've explained that correctly.

**Comment by axelfontaine** [comment]
What would be the use of this? Repeatable migrations only run if their checksum changed. Please explain why you need this.

**Comment by KangoV** [comment]
My use case is unit testing. Each unit test spins up an instance of Ratpack with a Flyway service in it. We override system properties for the location(s) where flyway should look. But we want to be able to select which repeatable migration to load for which test. I hope this makes sense.

**Comment by axelfontaine** [comment]
After having given this some thought. I currently don't see a chance to have this niche requirement integrated in the core in the near future.
