### ISSUE TITLE
Validate migration encoding

### ISSUE THREAD

**Issue by Ryanman** [flyway/flyway#2069]
###### What did you do?
I work with SQL developers who, somehow, manage to create and add a multitude of variously encoded .sql files. For many these do "Fail Fast" but in particular ANSI-encoded files will still execute... with botched characters. This is particularly dangerous.

###### What do you want to see?
I have loved flyway so far and hope this doesn't come across as entitled. I think an encoding check for the migrations folder would be a great idea especially for these corner cases that can seriously ruin a whole migration. For teams that have automated fully and can't manage to enforce encoding, this will help avoid problems.

Right now my workaround will be to write a powershell script that performs this as part of our Pull Request, Gated Commit process.

**Comment by axelfontaine** [comment]
Thanks for the suggestion. I can see how this could be useful as an additional safeguard as part of the validate step for example.

**Comment by axelfontaine** [comment]
We have now addressed this at least partially. Flyway will now complain when it is configured for `UTF-8` and being fed a `windows-1252` file for example. However when bytes are valid in both encodings like for example `UTF-8` and `ISO-8859-1` it isn't able to reliably report this and I am honestly not sure it is possible to fix this.

**Comment by Ryanman** [comment]
Awesome, thanks for the work and the product!
