### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by Sajith1988V** [flyway/flyway#2070]
###### Which version and edition of Flyway are you using?
Community edition 5.1.4 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
Oracle 12.2

###### Which operating system are you using?

Windows, but docker image is from linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**C:\Apps\flyway>docker run --rm -v c:/apps/flyway/sql:/flyway/sql -v c:/apps/flyway/conf:/flyway/conf -v c:/apps/flyway/drivers:/flyway/drivers boxfuse/flyway migrate
Flyway Community Edition 5.1.4 by Boxfuse

ERROR: Unable to connect to the database. Configure the url, user and password!**

###### What did you expect to see?

It should connect to the db.
###### What did you see instead?
Not connecting to be.

**Comment by axelfontaine** [comment]
What is the debug output (-X)?

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
