### ISSUE TITLE
DROP FULLTEXT INDEX statement cannot be used inside a user transaction.

### ISSUE THREAD

**Issue by mehta-m** [flyway/flyway#2071]
Flyway Version: 4.2.0
Commandline
Microsoft Sql Server 2012
OS: Windows Server 2012 R2

###### What did you do?
I've a migration where I've only 1 statement: `DROP FULLTEXT INDEX on SomeTable Name`
On running the migrate command I get an error:  **Error Message: DROP FULLTEXT INDEX statement cannot be used inside a user transaction.**
Now I understand that for each migration Flyway automatically starts a transaction. So how do i execute this script outside of a transaction.

**Comment by axelfontaine** [comment]
Thanks. Good catch. Fixed.

**Comment by mehta-m** [comment]
Thank you Axel. When can i expect 5.2.0 version to be available ?

**Comment by axelfontaine** [comment]
@mehta-m See https://github.com/flyway/flyway/milestones
