### ISSUE TITLE
SQL Server always encrypted with Azure Key Vault support

### ISSUE THREAD

**Issue by LRomano72** [flyway/flyway#2072]
This is from SO as not sure if I was suppose to post it here.
https://stackoverflow.com/questions/51198706/sql-always-encrypted-and-dump-of-migration-scripts-for-validation

###### Which version and edition of Flyway are you using?
Latest

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Any and all of them

###### Which database are you using (type & version)?
Azure SQL, latest version, cloud

###### Which operating system are you using?
Windows/Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Sql Server Always Encrypted connection: how do we override or inject enough information so that Flyway can setup the database connect to an Always Encrypted database. The connection needs to connect to Azure Key Vault to get a token for use for encryption/decryption but this additional setup that is above the the standard User Name/Password the connection string needs. Also, you can't pass these values on the connections string.

More details here on how this would be done in JDBC as I'm not a Java person
https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=azuresqldb-current

**Comment by axelfontaine** [comment]
(Only one feature request/bug report per issue please. Please file a separate issue for your other one)

This is currently not supported using the command-line tool. It should be easily achievable using the Java API though.

**Comment by LRomano72** [comment]
Can you provide more details on what interface we would need to hook into to get be able to provide the new database connection information to the Flyway context?

**Comment by axelfontaine** [comment]
You will need a properly configured DataSource for this.

**Comment by MikielAgutu** [comment]
Related to #2688

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
