### ISSUE TITLE
How I can runtime define multiples schemas?

### ISSUE THREAD

**Issue by rdgoutiyama** [flyway/flyway#2075]
###### Which version and edition of Flyway are you using?

latest

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

PostgreSQL 9.4

###### Which operating system are you using?

Windows/Linux 

###### What did you do?

I need update multiple schemas, but in runtime. Its work if defined in flyway.properties (flyway.schemas). I dont define the schemas fixed in properties file, because each client have your schema.

**Comment by axelfontaine** [comment]
Not an issue. Question better suited for StackOverflow.
