### ISSUE TITLE
Allow Multiple prefixes for repeatable migrations

### ISSUE THREAD

**Issue by sdchhabaria** [flyway/flyway#2077]
###### Which version and edition of Flyway are you using?
flyway-5-1-4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using (type & version)?

oravle 11.2

###### Which operating system are you using?

Red-Hat Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

For my project, we follow the naming convention as:

packages: pk_<<name>>.sql
functions: ap_<<name>>.sql
views: vw_<<name>>.sql
and so on..

###### What did you expect to see?
Is there anyway, flyway can identify all the above repetable prefixes and migrate the same to database

###### What did you see instead?
Currently multiple prefixes aren't supported

**Comment by awesome-amit** [comment]
We too follow database object naming standards. How we have fixed this issue is that we append `R__` for repeatable migrations at build time so the migration artifacts are created with the suffix that keeps Flyway happy and our source control have objects that follows our naming standards.

**Comment by MikielAgutu** [comment]
You could use sub folders, or just another convention e.g. `R__PK_something.sql`
