### ISSUE TITLE
Undo repeatable migrations

### ISSUE THREAD

**Issue by sdchhabaria** [flyway/flyway#2078]
###### Which version and edition of Flyway are you using?

flyway-5-1-4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command-line

###### Which database are you using (type & version)?

oracle 11gR2

###### Which operating system are you using?

RedHat Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

For a particular build suppose I have 10 versioned migration, and 20 repatable migrations.
I have maintained undo migrations for versioned migrations.
Also repeatable migrations are dependent on versioned migrations.
i.e. suppose a new table created in versioned migration, is referenced in one of the packages of repetable migration

All versioned migrations are successful
Now suppose due to some reason (syntactical, network issue, etc.) buld breaks at repeatable migration 12. I now want to rollback the entire build, both versioned and repeatable.

I have a way to undo versioned migrations.

But is there any other way to undo repeatable migrations.
One way I know is for developer to maintain previous version in SVN.

###### What did you expect to see?

Can this step of undoing repeatable migration being automated, removing an overhead on developer?

###### What did you see instead?

Currently not supported.

**Comment by axelfontaine** [comment]
As indeed for repeatable migrations the history is kept in source control, reverting a change means reverting the contents of that file from source control. We currently have no plans to change this as versioned migrations already provide a viable alternative if you want to make this more explicit.
