### ISSUE TITLE
Migration freeze with CockroachDB and CREATE SEQUENCE

### ISSUE THREAD

**Issue by man4j** [flyway/flyway#2079]
###### Which version and edition of Flyway are you using?
5.1.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
CockroachDB 2.0.3

###### Which operating system are you using?
Ubuntu 16.04

###### What did you do?
CREATE SEQUENCE my_seq START 1 INCREMENT 1;

###### What did you see instead?
Freeze

**Comment by axelfontaine** [comment]
I can't seem to reproduce this. This statement executes just fine on my end. Definitely not a Flyway issue. It is either an issue with your setup or with CockroachDB itself.
