### ISSUE TITLE
Non-transactional RECONFIGURE statement not working in SQL Server

### ISSUE THREAD

**Issue by JLopeDeB** [flyway/flyway#2082]
###### Which version and edition of Flyway are you using?
5.1.4 (but it hasn't worked with previous versions, using it since 5.1.1)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Microsoft SQL Server 2014 (SP2-CU10-GDR) (KB4052725) - 12.0.5571.0 (X64) 

###### Which operating system are you using?
Windows 10 (Flyway), Windows Server 2008 R2 (SQL Server)

###### What did you do?
Tried to migrate scripts containing non transactional commands and DDL and it failed. I tried with FullText Catalogs, Linked Servers, and the last time with sp_configure. I have flyway.mixed=true in my config file, but also tried by adding -mixed=true to the command line. 

Command:
`PS C:\repos\cpp> flyway -n -configFiles="conf/flyway_Desa.conf" -mixed=true migrate`

[V2018.07.16.1036__Migrar_Datos_dbo_Proveedores.txt](https://github.com/flyway/flyway/files/2198146/V2018.07.16.1036__Migrar_Datos_dbo_Proveedores.txt)

###### What did you expect to see?
Successful migration.

###### What did you see instead?
Output (partial)
> Migration V2018.07.16.1036__Migrar_Datos_dbo_Proveedores.sql failed
> SQL State  : S1000
> Error Code : 574
> Message    : No se puede usar la instrucción CONFIG dentro de una transacción de usuario
> Location   : C:\repos\CPP\Datos\V2018.07.16.1036__Migrar_Datos_dbo_Proveedores.sql (C:\repos\CPP\Datos\V2018.07.16.1036__Migrar_Datos_dbo_Proveedores.sql)
> Line       : 22
> Statement  : EXEC sp_configure 'Ad Hoc Distributed Queries', 1
> RECONFIGURE

Worth to mention that I haven't been able to run non-transactional code ever. In this case, the code is mixed with something else but in other cases it wasn't. For everything else, I find Flyway an excellent tool and I'm super happy with it. Thanks for it!

EDIT: I forgot to mention that I ran a trace on it, and I was able to see that Flyway always use `SET IMPLICIT_TRANSACTIONS ON`, no matter if mixed migrations is enabled or not. Setting the option OFF explicitly in the code didn't work either.

**Comment by axelfontaine** [comment]
The issue in this case is the RECONFIGURE statement. This has now been fixed.
