### ISSUE TITLE
flyway.cleanDisabled - Shouldn't the default be TRUE

### ISSUE THREAD

**Issue by mehta-m** [flyway/flyway#2083]
Version; Flyway 4.2.0
Client: Commandline
Database Engine: MS SQL Server
OS: Windows Server 2012 R2

In the Flyway.conf file - we have this section 
```
# Whether to disabled clean. (default: false)
# This is especially useful for production environments where running clean can be quite a career limiting move.
 flyway.cleanDisabled=false

```
###### What did you expect to see?
It's rightly mentioned that this command can be a career limiting move. So shouldn't the default be **true**  ??

**Comment by axelfontaine** [comment]
Thanks for the suggestion. We may reconsider this in the future. For now we are however happy with the current default.
