### ISSUE TITLE
Migrations starting from baselineVersion are applied instead of migrations ABOVE the baselineVersion.

### ISSUE THREAD

**Issue by mehta-m** [flyway/flyway#2084]
Version; Flyway 4.2.0
Client: Commandline
Database Engine: MS SQL Server
OS: Windows Server 2012 R2

###### What did you do?
```
# Whether to automatically call baseline when migrate is executed against a non-empty schema with no metadata table.
# This schema will then be initialized with the baselineVersion before executing the migrations.
# Only migrations above baselineVersion will then be applied.
# This is useful for initial Flyway production deployments on projects with an existing DB.
# Be careful when enabling this as it removes the safety net that ensures
# Flyway does not migrate the wrong database in case of a configuration mistake! (default: false)
flyway.baselineOnMigrate=true
```
After running the baseline command - I am running the migrate command. Now if I've set the flyway.baselineVersion=5 - then as per the above documentation - Only migrations **above** baselineVersion will then be applied.

###### What did you expect to see?
I was expecting migrations to starting from number 6 to be applied. (Above baselineVersion which is 5)

###### What did you see instead?
Migrations starting from number 5 area applied.

Is it a bug in the program or a mistake in the documentation?

Thank you

**Comment by axelfontaine** [comment]
Works as designed. If baselineVersion is 5, then it is perfectly normal that 5.1 will be applied.
