### ISSUE TITLE
dryrun does not set schema on java migration on DB2

### ISSUE THREAD

**Issue by fischey** [flyway/flyway#2086]
Which version and edition of Flyway are you using?
- 5.1.4 Trial Version

Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
- Maven Plugin

Which database are you using (type & version)?
- DB2 10.5 on AIX 64bit

Which operating system are you using?
- Linux x64 for the maven plugin 

What did you do?
- We ran a Java Migration in Jenkins via the maven-plugin in dryrun-Mode. 
We did a migrate with mutiple schemas.

following configurations are in the pom.xml:
```XML                      
<configuration>
  <user>user</user>
  <password>password</password>
  <encoding>ISO-8859-1</encoding>
  <table>SCHEMA_VERSION</table>
  <outOfOrder>true</outOfOrder>

   <placeholders>
        <tempSchema>TMP</tempSchema>
        <targetSchema>${targetSchema}</targetSchema>
    </placeholders>
    <schemas>
       <schema>${targetSchema}</schema>
       <schema>${tempSchema}</schema>
    </schemas>
    <locations>
      <location>db/migration</location>
    </locations>
</configuration>
```
Additionally we use a properties file with the following values
```
flyway.url=jdbc:db2://db2server:50000/DB
flyway.schemas=K110,TMP
flyway.placeholders.targetSchema=K110
```
The log output of non dry run and dry run and a simple reproducible Java Migration are attached
[dryrun.txt](https://github.com/flyway/flyway/files/2201121/dryrun.txt)
[non-dry-run.txt](https://github.com/flyway/flyway/files/2201122/non-dry-run.txt)
[V201807161439__i_am_reproducible.java.txt](https://github.com/flyway/flyway/files/2201123/V201807161439__i_am_reproducible.java.txt)

What did you expect to see?
- We expect in a dry run of a Java Migration also the automatic use of the first schema name from the configuration.

What did you see instead?
- The schema name from the configuration was not used and the Java Migration failed in dry run mode although it worked in the normal (non dry) mode.

We think that there is a bug in the read only wrapper connection for the java migration. Maybe the setting of the schema is not correctly delegated to the underlying DB2-Connection object.

https://github.com/flyway/flyway/blob/f3e7f8f0c603495ae6aa48a1c3d08b84dc734aee/flyway-core/src/main/java/org/flywaydb/core/internal/database/base/Connection.java#L113
and 
https://github.com/flyway/flyway/blob/f3e7f8f0c603495ae6aa48a1c3d08b84dc734aee/flyway-core/src/main/java/org/flywaydb/core/internal/database/db2/DB2Connection.java#L49

**Comment by axelfontaine** [comment]
Thanks for reporting. This indeed appears to be inconsistent. Here is what happens. When Flyway is run in dry-run mode, the first thing it does is set the JDBC connection in read-only mode as follows to prevent any changes being made to the database:

```java
connection.setReadOnly(true);
```

As you correctly found out, before each migration is run Flyway sets the current schema of the connection using the methods you highlighted in your report. 

With the combination of these however it appears the JDBC driver or database silently suppresses the schema change. However the `SET SCHEMA` statement does appear in Flyway's dry-run output. What this means is that indeed during the dry-run you do get the result you described above, however when running the produced dry-run script the result will be correct.

One way to avoid this could be to avoid making the connection read-only. I am however not too keen on this as it would remove an important safety net that prevents accidental changes.

I therefore believe that although not perfect, the current solution is the lesser of both evils.
