### ISSUE TITLE
Support for always running SQL files A__.always_executed.sql. Reason: "SET lock_timeout" or "SET statement_timeout" for postgres before every migration 

### ISSUE THREAD

**Issue by tjerkw** [flyway/flyway#2087]
###### Which version and edition of Flyway are you using?

The latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command line

###### Which database are you using (type & version)?

Postgres 9.3

###### Which operating system are you using?

Ubunutu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

The flyway executer just executes migrations and waits forever to aqcuire a lock. This can cause a deadlock situation for a postgresql database.

A way to solve this is to fail fast, if you cant aqcuire a lock.

You can do this with:

SET lock_timeout = 3s;

However now, i need to add that before EVERY migration .sql file in order to set it.
It would be nice  if i can set it for the JDBC driver, but this is impossible. It only supports connection timeouts.

Currently this brings our website down, if people keep flyway running while it is aqcuiring a lock.

###### My Idea

Have a custom configuration option for the PostgreSQL Statement executor to prepand every migration with a SET lock_timeout.

Or somehow have an .sql file that is execute before every migration.

What do you think?

**Comment by tjerkw** [comment]
For now i'm going to use JDBC socketTimeout in the JDBC connection string, which is a brute-force way to enforce a statement timeout:
https://jdbc.postgresql.org/documentation/head/connect.html

I think this should also work for lock timeouts. 

`
socketTimeout = int

The timeout value used for socket read operations. If reading from the server takes longer than this value, the connection is closed. This can be used as both a brute force global query timeout and a method of detecting network problems. The timeout is specified in seconds and a value of zero means that it is disabled.`

**Comment by tjerkw** [comment]
This doesnt work :-(

After it closes the connection after socketTimeout it cannot release the lock anymore. Keeping the transaction open, and impossible to run another migration because the lock on the schema-history table is still there.

`ostgres=# SELECT pid, usename, application_name, query_start, state, now()- query_start as duration, SUBSTRING(query, 1, 400) FROM pg_stat_activity WHERE  datname = '...' ORDER BY duration DESC;
  pid  | usename  |    application_name    |          query_start          |        state        |    duration     |                              substring
-------+----------+------------------------+-------------------------------+---------------------+-----------------+----------------------------------------------------------------------
 10179 | postgres | psql                   | 2018-07-18 11:12:47.099124+02 | idle in transaction | 00:03:30.058798 | ALTER TABLE a.account ADD COLUMN derp4 VARCHAR DEFAULT 'helo';
 10235 | postgres | PostgreSQL JDBC Driver | 2018-07-18 11:13:42.022829+02 | active              | 00:02:35.135093 | ALTER TABLE a.account ADD COLUMN derp10 VARCHAR DEFAULT 'hello'
 10238 | postgres | PostgreSQL JDBC Driver | 2018-07-18 11:16:17.094319+02 | idle                | 00:00:00.063603 | SELECT pg_try_advisory_lock(77433833903597)`

**Comment by tjerkw** [comment]
What i want: It should stop trying to migration if a migration itself (after it got the schema history table lock) doesnt work due to a lock.

**Comment by tjerkw** [comment]
I know workaround this issue by regenerating a R__set_timeouts.sql just before the migrations.

Which has the following code:

`-- This file is autogenerated to workaround issue https://github.com/flyway/flyway/issues/2087
-- Wed Jul 18 11:41:20 CEST 2018
SET SESSION lock_timeout = 3s;`

The date will be updated, which updates the checksum of the file, so it will be executed every time.

**Comment by tjerkw** [comment]
To bad this doesnt work, the repeatable migration are run AFTER the other migration.
I need a B__ (before) or A__  (always) prefix.

**Comment by axelfontaine** [comment]
The `beforeEachMigration` callback can be you for this very purpose: https://flywaydb.org/documentation/callbacks

**Comment by tjerkw** [comment]
Yes I found the callbacks. I kind a missed this part in the documentation. I thought it was about Java callbacks.

Sorry for not updating the issue.
