### ISSUE TITLE
Derby Embedded DB stays open when using the Gradle wrapper

### ISSUE THREAD

**Issue by timmyhadwen** [flyway/flyway#2088]
###### Which version and edition of Flyway are you using?
flyway 5.1.4, Derby 10.14.2.0, 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using (type & version)?
Derby Embedded Client

###### Which operating system are you using?
MacOS 10.11 but also confirmed happening on Windows using bash.

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Running 'gradle flywayMigrate' twice causes derby database to not be connected due to the lock files still being valid. Running 'pkill java' fixes the issue for another run. 'gradle flywayMigrate --no-daemon' makes the issue go away.

**Comment by axelfontaine** [comment]
Good point. This has now been fixed.
