### ISSUE TITLE
WARN log using MariaDB driver

### ISSUE THREAD

**Issue by VibyJocke** [flyway/flyway#2099]
This is not a major issue or anything, but maybe there's a quick fix for it. Flyway is warning "You are connected to a MySQL database using the MariaDB driver..." when using MariaDB driver with AWS Aurora (based on MySQL), even though it is the recommended driver to use (see [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Aurora.Connecting.html)).

**Comment by axelfontaine** [comment]
The reason we introduced this warning is because the MariaDB driver is unable to connect with MySQL 8.0. In the case of Aurora, which is currently only compatible with MySQL 5.7, this is not *yet* an issue.

**Comment by PredatorVI** [comment]
I've recently upgraded to the latest 5.1.4 and it appears there is an auto detect problem,  All of my config files have the following pattern for flyway.url:

```
flyway.url=jdbc:mysql://<dbhost>/<db_schema>?autoReconnect=true&useOldAliasMetadataBehavior=true&dontTrackOpenResources=true

# Fully qualified classname of the jdbc driver (autodetected by default based on flyway.url)
# flyway.driver=

```
According to the sample flyway.conf file, the driver should be autodetected based on the format of flyway.url and the comment in the flyway.conf file shows the MySQL url format as:

`# MySQL             : jdbc:mysql://<host>:<port>/<database>?<key1>=<value1>&<key2>=<value2>...
`
Yet when I run it I get the warning:

```
C:\Projects\GitLab\dbmigration>flyway -configFiles=conf/acc/flyway_hunters.conf -target=001.0.2 -user=admin -password=lint1234 migrate
Flyway Community Edition 5.1.4 by Boxfuse

Database: jdbc:mysql://mrdb-acc01.wp.bluecoat.com/hunters (MySQL 5.6)
WARNING: You are connected to a MySQL database using the MariaDB driver. This is known to cause issues. An upgrade to Oracle's MySQL JDBC driver is highly recommended.
Successfully validated 3 migrations (execution time 00:01.986s)
Current version of schema `hunters`: 001.0.2
Schema `hunters` is up to date. No migration necessary.
```

**Comment by axelfontaine** [comment]
This has now been fixed automatically as a consequence of #2144

**Comment by GregTurner** [comment]
@axelfontaine doesn't that fix apply to the CLI version only?

**Comment by axelfontaine** [comment]
@GregTurner No.

**Comment by juliahayward** [comment]
> The reason we introduced this warning is because the MariaDB driver is unable to connect with MySQL 8.0. In the case of Aurora, which is currently only compatible with MySQL 5.7, this is not _yet_ an issue.

This is now no longer the case - see #2865 and https://mariadb.com/kb/en/about-mariadb-connector-j/
