### ISSUE TITLE
Concurrent migrations with multiple docker swarm replicas

### ISSUE THREAD

**Issue by jlmc** [flyway/flyway#2102]
###### Which version and edition of Flyway are you using?
Flyway community, 5.1.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
PostgreSQL 10

###### Which operating system are you using?
Ubuntu 16.04.5 LTS or MacOS HighSierra

###### What did you do?
We have a database with multiple similar schemas, all schemas having exactly the same objects (multitenancy with schema). We intend to run the migrate command for all schemas, all schemas should have a flyway_schema_history table.

Those migrations are run in parallel by a Docker service with multiple replicas.

###### What did you expect to see?
When we have only one replica of the application all the schemas are migrated successfully. However, we expected that when we have multiple replicas running the schema migrations, they would be isolated and would run successfully as well.

###### What did you see instead?
When we start the service that runs the migrations with multiple replicas on the same schemas at the same time, we obtain the following exception:

```txt
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException:
Migration V1.0.0_2__initial_migration.sql failed
------------------------------------------------
SQL State  : 42P07
Error Code : 0
Message    : ERROR: relation "organization_unit" already exists
Location   : db/migration/tenant/V1.0.0_2__initial_migration.sql (/content/my-application-1.0.0-SNAPSHOT.war/WEB-INF/classes/db/
Line       : 12
Statement  : CREATE TABLE organization_unit (
  id          UUID         NOT NULL,
  description VARCHAR(500),
  name        VARCHAR(100) NOT NULL,
  parent_id   UUID,

  PRIMARY KEY (id)
)
```

**Comment by axelfontaine** [comment]
This is almost certainly due to a mixup somewhere in your config or environment setup. Please debug and reopen if you can pinpoint that Flyway is at fault.
