### ISSUE TITLE
Incomplete list of Incompatible Changes

### ISSUE THREAD

**Issue by pdkovacs** [flyway/flyway#2109]
###### Which version and edition of Flyway are you using?
5.1.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes, I can!

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
n/a

###### Which operating system are you using?
Linux

###### What did you do?
Upgraded from 4.1.2 to 5.1.1

###### What did you expect to see?
Stating in the *Incompatible Changes* section of the Release Notes that the default name of the metadata table has changed (somewhere between 4.1.2 and 5.1.1)

###### What did you see instead?
Nothing.

**Comment by axelfontaine** [comment]
This wasn't an incompatible change as there is code in place to ensure your old config keeps on working unchanged.

**Comment by pdkovacs** [comment]
This change is forward incompatible. I cannot simply downgrade back to 4.1.2 without having to deal with this change in some way.
