### ISSUE TITLE
Oracle SQL/Plus DEFINE should not be case sensitive.

### ISSUE THREAD

**Issue by fullyinchristswonder** [flyway/flyway#2115]
###### Which version and edition of Flyway are you using?
5.1.4 pro trial

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
OracleXE 11.2g

###### Which operating system are you using?
Windows 7 enterprise

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

```sql
--works case insensitive
set define on

--works case insensitive
set define ~
--doesn't work case sensitive
define random="--"

--works case sensitive when uncommented
--DEFINE random="--"

declare

   --
    --    For service locations with a single extract location, simply assign every client in the service location to that extract location.
    --
    PROCEDURE proc( ) IS
    BEGIN

        dbms_output.put_line('test replacement ~random ');
        
    END;
	
begin
	dbms_output.enable(null);
    
end;
/
```

###### What did you expect to see?

~random be set to "--" and successful migration

###### What did you see instead?
12:33:57,138 ERROR [Main] No value provided for placeholder expressions:  ~random.  Check your configuration!

**Comment by axelfontaine** [comment]
Thank you for reporting and thanks for the detailed analysis. This was a big help in finding and fixing the issue. The fix will be out as part of the next release.
