### ISSUE TITLE
Mismatch between validate's fail-fast and repair's broad-brush

### ISSUE THREAD

**Issue by eepstein** [flyway/flyway#2116]
###### Which version and edition of Flyway are you using?

5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A - this is the latest release

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using (type & version)?

Postgresql 9.6

###### Which operating system are you using?

MacOS and Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

First : we touched two of the .sql migration files, 
Then:
    mvn -Dflyway.configFiles=config/flyway-stage.conf flyway:validate

###### What did you expect to see?

Both validations fail.

###### What did you see instead?

Only the first change was reported as a validation failure.  
This is `validate`'s fail-fast policy, which would be fine,

EXCEPT

the `repair` function does not take a parameter to indicate the specific migration to repair (update the checksum in the db in this case).

instead `repair` happily updated all the checksums, which combined with `validate`'s fail-fast logic means that we had no idea someone had touched one of the other .sql file in the migration folder.

Holy DB mess batman.

**Comment by juliahayward** [comment]
In 6.0.3 and higher, `validate()` will provide all failures. If finer grained control is required, we can add options to both `validate()` and `repair()` to only go up to a specific migration - please kick off a new issue if that's the case.
