### ISSUE TITLE
Flyway behaves differently with MSSQL & MySQL

### ISSUE THREAD

**Issue by MrR0807** [flyway/flyway#2122]
###### Which version and edition of Flyway are you using?
flyway: 5.1.4
spring-boot: 2.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Spring Boot Auto-Config.

###### Which database are you using (type & version)?
MySQL 5.7.17-13
MS SQL Express 14.0.2002

###### Which operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Spring boot application.yaml:

//MS SQL
spring:
  profiles: test_flyway
  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-version: 2
    locations: classpath:db/migration/test
    schemas: flyway_test
  datasource:
    url: jdbc:sqlserver://${SQL_URL}:${SQL_PORT};databaseName=flyway_test
    username: ${SQL_USER}
    password: ${SQL_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: sql_server
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

//MySQL
spring:
  profiles: test_flyway
  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-version: 2
    locations: classpath:db/migration/test
  datasource:
    url: jdbc:mysql://${MySQL_URL}:${MySQL_PORT}/flyway_test
    username: ${MySQL_USER}
    password: ${MySQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

###### What did you expect to see?
**baseline-on-migrate**: Whether to automatically call baseline when migrate is executed against a non-empty schema with no metadata table. This schema will then be baselined with the baselineVersion before executing the migrations. 

For MS SQL I have this database structure:
Database: flyway_test;
Schema: flyway_test;
Tables: [flyway_test.table1]

For MySQL I have this database structure:
Schema: flyway_test;
Tables: [flyway_test.table1]

I run this migration script for MySQL:
USE flyway_test;

CREATE TABLE table2 (
id2 int auto_increment NOT NULL PRIMARY KEY,
user_name2 varchar(255));

I run this migration script for MSSQL:
USE flyway_test;
GO

CREATE TABLE flyway_test.table2 (
id2 int IDENTITY(1,1) NOT NULL,
user_name2 varchar(255),
PRIMARY KEY(id2));

When I run given Spring Boot application with properties above for MS SQL, the property of baseline-on-migrate does not work: Flyway creates flyway_schema_history either way and continues with migration.

When I run given Spring Boot application with properties above for MySQL, the property of baseline-on-migrate **works** and I get **Error:** _Found non-empty schema(s) `flyway_test` without schema history table! Use baseline() or set baselineOnMigrate to true to initialize the schema history table._

**Comment by axelfontaine** [comment]
This is most likely due to an error in your setup somewhere. Could it be that you initialize a different SQL Server database as the one you point Flyway to?

Please share a small test repo that reproduces the issue.

**Comment by axelfontaine** [comment]
Closing due to lack of response.
