### ISSUE TITLE
Introduce connectRetries setting

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#2124]
See https://github.com/flyway/flyway-docker/issues/2#issuecomment-382830510

Currently Flyway automatically tries to connect up to 10 times at a 1 second interval. This should be made configurable to deal with a number of use cases including Docker Compose where both the Flyway and the DB container are started at the same time and Flyway must wait for the DB container to come up before being able to migrate the database..

**Comment by AlexBoothClearswift** [comment]
Is the interval configurable to a value larger than 1 second?

**Comment by axelfontaine** [comment]
@AlexBoothClearswift No. Please file a new feature request detailing your use case in detail and why the current approach doesn't work for you.
