### ISSUE TITLE
Support upgrading from 3.x to 5.x

### ISSUE THREAD

**Issue by wimdeblauwe** [flyway/flyway#2126]
The [Spring Boot migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#flyway) mentions that you first need to upgrade your Spring Boot 1.5.x application to use Flyway 4.x so that the existing `schema_version` table gets updated. After that, you can migrate to Spring Boot 2.x which includes Flyway 5.x.

As a consequence you need to do 2 releases of an application to be able to properly upgrade due to this. This is all great if you have very regular releases, and have easy access to the server to do those upgrades.

Some of my Spring Boot projects are deployed at the customer site with no internet connection, so this 2-step release process is making things harder then it should be.

Is there an option to include the migration code in Flyway 5.x so that Spring Boot users don't have to do 2 releases just for this? Given the adoption rate of Spring Boot, I think it would really help a lot of users that use Flyway through Spring Boot.

**Comment by axelfontaine** [comment]
We have no plans to do this. The Spring Boot situation is really unfortunate. We have always provided automate migration from the previous Flyway major release. Unfortunately, the Spring Boot team stuck with Flyway 3.x for several years, completely skipping 4.x, which lead to this situation.

So yes, the following scenario is still the way to go:
1. Upgrade your Spring Boot 1.X app to Flyway 4.2
2. Upgrade to Spring Boot 2.X and along with it Flyway to 5.X

**Comment by wimdeblauwe** [comment]
Is there a way to run the migration from the [command line tool](https://flywaydb.org/documentation/commandline/)? 

The idea would be that v1 of my app is stopped, then flyway command line tool is started where it just upgrades the schema_version to v4 format of Flyway. Then v2 of my app that uses Flyway 5 is deployed and started. Can the command line tool (probably v4.2.0 of the tool then) be run like that?

**Comment by axelfontaine** [comment]
@wimdeblauwe Yes, that should work.

**Comment by energister** [comment]
Just for the reference: those, who interested in upgrading from 4.x to 6.x should look to the #1965
