### ISSUE TITLE
Migrations are resolved differently with and without packaging

### ISSUE THREAD

**Issue by nigredo-tori** [flyway/flyway#2127]
###### Which version and edition of Flyway are you using?

5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

PostgreSQL 9.6

###### Which operating system are you using?

Ubuntu Linux 18.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I'm in the process of embedding Jetty into a pre-existing web application. For reasons I'd rather not go into here, I ended up with the following structure :

```
/
├── <boot and dependency classes and resources, including code that uses Flyway>
├── WEB-INF/
│   └── classes/
│       └── <web application classes>
└── db/
    └── migration/
        └── <SQL migrations>
```

There are two classloaders:
1. The boot one, which uses the classes and resources in `/`.
2. The webapp classloader, which uses the classes and resources in `/WEB-INF/classes/`. The first classloader is its parent.

In this setup I run Flyway in a thread that uses the second classloader, but the actual code resides in the first (parent) classloader. There are two possible scenarios:
1. Running without packaging (the root of the structure above is a simple directory).
2. Running with WAR packaging (the root of the structure is a `.war` file), running the WAR as a JAR (`java -jar foo.war`).

###### What did you expect to see?

I expected Flyway to find the migrations in both of the scenarios above.

###### What did you see instead?

Flyway successfully finds the migrations when running from a directory. However it can't locate the migrations when running from a WAR archive.

The problem here is [JarFileClassPathLocationScanner](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/JarFileClassPathLocationScanner.java). It *assumes* that the classloader root coincides with the archive root (or `WEB-INF/classes` for WAR archives), which is not always the case. For example, if the classloader resolves `location` resource to `/foo.jar!/bar/location`, then the resulting call `jfcpls.findResourceNames("location", new URL("jar:file:/foo.jar!/bar/location"))` will look for resources in `/foo.jar!/location` instead.

I'd like to see Flyway behave more consistently in cases like this. Since we have both the original `location` and the URL it resolves to, we can remove from the URL only the parts that correspond to the `location`, leaving the prefix intact.

One workaround for my case would be to move the migrations into `WEB-INF/classes`, which is ugly, but not much weirder than what I already have. Another way would be to roll my own `JarFileClassPathLocationScanner` and `ClassPathScanner`. Switching from WAR to JAR would be the best thing to do, but I can't do that at the moment.

**Comment by axelfontaine** [comment]
You should absolutely more your migrations to `WEB-INF/classes` as now they are exposed to clients (!).

The current behavior works fine for the overwhelming majority of war deployments. And your current structure is really not something to recommend, so I'll settle for won't fix on this one.
