### ISSUE TITLE
java.sql.SQLException: sql injection violation, comment not allow 

### ISSUE THREAD

**Issue by stonehiy** [flyway/flyway#2130]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
this the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
java api

###### Which database are you using (type & version)?
mysql 5.7

###### Which operating system are you using?
mac 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?
-- Add the primary key as part of the CREATE TABLE statement in case `innodb_force_primary_key` delete this ?
not

###### What did you see instead?
my exception info :
Caused by: java.sql.SQLException: sql injection violation, comment not allow : CREATE TABLE `im_db`.`flyway_schema_history` (
    `installed_rank` INT NOT NULL,
    `version` VARCHAR(50),
    `description` VARCHAR(200) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `script` VARCHAR(1000) NOT NULL,
    `checksum` INT,
    `installed_by` VARCHAR(100) NOT NULL,
    `installed_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `execution_time` INT NOT NULL,
    `success` BOOL NOT NULL,
    -- Add the primary key as part of the CREATE TABLE statement in case `innodb_force_primary_key` is enabled
    CONSTRAINT `flyway_schema_history_pk`PRIMARY KEY (`installed_rank`)
) ENGINE=InnoDB

**Comment by axelfontaine** [comment]
Please fill in all part of the template, clearly explain what the issue is, how it can be reproduced, what the full stack trace is and what should be happening instead.

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by chenm1xuexi** [comment]
flyway version  => 5.2.4
use druid as  dataSource, when I start a spring-boot application, flyway need to create flyway_schema_history table, so I receive this exception message: " SQL injection violation, comment not allow", please remove comment about createMetaDataTable.sql
