### ISSUE TITLE
Allow url to include the username/password

### ISSUE THREAD

**Issue by AlJohri** [flyway/flyway#2132]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 5.1.4 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Postgres 10.0

###### Which operating system are you using?
macOS

Currently, `FLYWAY_URL` only accepts `jdbc:postgresql://{host}:{port}/{dbname}'`. I tried giving it a full database uri such as: `jdbc:postgresql://{user}:{pass}@{host}:{port}/{dbname}` but that didn't work- it still asked me for the username.

Any chance it can parse out the user and pass right out of the `FLYWAY_URL`?

Thanks!

**Comment by axelfontaine** [comment]
Did it work with `-n`? See https://flywaydb.org/documentation/commandline/#credentials

**Comment by axelfontaine** [comment]
Any news?

**Comment by AlJohri** [comment]
sorry, haven't gotten a chance to test yet. will do!

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by AlJohri** [comment]
@axelfontaine let's re-open this issue. it did not work.

attempt one:

```
FLYWAY_URL=jdbc:postgresql://root:mypass@myhost/mydb flyway -n migrate
```

```
Flyway Community Edition 5.2.1 by Boxfuse
Nov 21, 2018 5:33:47 PM org.postgresql.Driver parseURL
WARNING: JDBC URL invalid port number: mypass@myhost
ERROR: java.lang.NullPointerException
```

attempt two:


```
FLYWAY_URL=jdbc:postgresql://root:mypass@myhost:5432/mydb flyway -n migrate
```

fails with:

```
Flyway Community Edition 5.2.1 by Boxfuse
ERROR:
Unable to obtain connection from database (jdbc:postgresql://root:mypass@myhost:5432/mydb) for user 'null': The connection attempt failed.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : The connection attempt failed.
```

here's my wishlist of ways I wish FLYWAY could smartly parse the database url:
- handle `postgres` or `postgresql` (allows keeping consistent with [libpq](https://www.postgresql.org/docs/9.2/libpq-connect.html#LIBPQ-CONNSTRING)
- allow dropped `jdbc:`. it should be assumed, I'm passing in an environment variable called FLYWAY_URL, it's meant specifically for flyway
- allow defaulting the port 5432 for postgres. it thought everything before the slash until the first colon was the port. for example, in `root:mypass@myhost/mydb` it think the port is `mypass@myhost`. this can be parsed out slightly smarter to prevent this
- and last but not least, take the username and password from the FLYWAY_URL itself

I would be happy to help with any and all of the above. thanks @axelfontaine!

**Comment by AlJohri** [comment]
hey @axelfontaine I just tried using `jdbc:postgresql://localhost/test?user=fred&password=secret` but it still asks for the user and password

```bash
flyway -url="jdbc:postgresql://host-dev-us-east-1.perso.aws.arc.pub:5432/history?user=uzr&password=psswrd" -locations="filesystem:$(pwd)/sql" migrate
```

**Comment by juliahayward** [comment]
V6.3.2 will not prompt if it sees user and password in the URL (in the form the Postgres driver is happy with, such as `?user=foo&password=bar`)

**Comment by kyr0** [comment]
Can confirm that this approach doesn't work with the gradle plugin + JDBC/MySQL, unfortunately
