### ISSUE TITLE
Support new callback before executing repeatable script and after executing versioned script

### ISSUE THREAD

**Issue by jitu1983** [flyway/flyway#2133]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
Oracle 12c

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
We have a requirement in which we want to execute some script after migrating all versioned script but before executing repeatable script. I guess currently we don't have any callback support for this scenario. 

###### What did you expect to see?
It would be great if we have new callback to execute exactly for this scenario.

**Comment by axelfontaine** [comment]
What exactly is your use case for this?

**Comment by jitu1983** [comment]
Hey, i have some scenario to execute some script that should be executed only after migration of all versioned script, but before executing any Repeatable script.
I understand, we have beforeMigrate callback which execute before migration of any versioned/repeatable script. And then we have afterMigrate callback which execute after all migration of all versioned/repeatable script.
But I guess there is no callback to execute any script after versioned script and before repeatable script. 
Please correct me if I am wrong.

**Comment by axelfontaine** [comment]
What exactly does this script do? (Just trying to understand this better)

**Comment by jitu1983** [comment]
We have a requirement where in after migration of all data-model and system configuration through Versioned script, we need to invoke some procedures through Repeatable script which will generate some views, packages and triggers based on configuration data updated through Versioned script. But before execution of repeatable scripts, we need to compile all the invalid objects and synchronize some materialized views. Else Repeatable script may get failed during execution or may generate incorrect views, packages and triggers.  We could have handle this through afterEachMigrate callback, but want to explicitly avoid this since we have many Versioned scripts and do this repeatable operation after each migration will be performance impact.

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
