### ISSUE TITLE
Flyway tries to undo un-applied migration

### ISSUE THREAD

**Issue by pikeas** [flyway/flyway#2137]
Flyway 5.1.4 Pro CLI / Aurora MySQL 5.6 / Debian Jessie

```
$ flyway info
Schema version: 3

+-----------+--------------+-----------------------------------------------+------+--------------+
| Category  | Version      | Description  | Type | Installed On        | State        | Undoable |
+-----------+--------------+-----------------------------------------------+------+--------------+

| Versioned | 3            | foo          | SQL  | 2018-08-28 07:47:15 | Success      | Yes      |
| Versioned | 2            | bar          | SQL  | 2018-08-28 23:10:28 | Out of Order | No       |
+-----------+--------------+-----------------------------------------------+------+--------------+

$ ./flyway undo
Current version of schema `my_schema`: 3
ERROR: Unable to undo migration to version 2 as no corresponding undo migration has been found.
```

Due to the order in which features were handed off, migration 3 was applied before migration 2 was merged in. I expected to resolve this situation by undoing 3 and then running a new `migrate`.

Instead, I'm unable to undo because Flyway expects to find an undo migration for 2.

**Comment by pikeas** [comment]
I can add an undo migration for 2 and then run `undo` twice, which works. However, this doesn't represent reality - Flyway shows two undone migrations but one of them wasn't needed. In fact, I'm not sure why this worked at all, unless Flyway never really ran the migration.

**Comment by axelfontaine** [comment]
The current implementation does indeed act like a stack, where `migrate` add an element on top and `undo` pops it of again. I must say I am not sure about changing this.

I understand your perspective and being able to undo specific migrations in the context of `outOfOrder` is something that I see as making sense. But then again, so does the current behavior.

Leaving this open for now.

**Comment by pikeas** [comment]
@axelfontaine Thanks for your reply. My main argument for a change here is that when `outOfOrder` is enabled, it doesn't make sense to "undo" a migration that was never applied.

**Comment by pikeas** [comment]
@DoodleBobBuffPants Why was this closed?

**Comment by DoodleBobBuffPants** [comment]
We want to maintain the current way undo works which is as a stack. This means that if you apply them out of order they will have to be undone out of order.

In V7 however we have new features that make it easier to work around this problem, such as `cherryPick` and `skipExecutingMigrations` which you can read about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
