### ISSUE TITLE
Maven Plugin Password encryption

### ISSUE THREAD

**Issue by stefanwendelmann** [flyway/flyway#2138]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using (type & version)?

SQL Server

###### Which operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Store my user & password in the settings.xml encrypted with the maven encryption 

###### What did you expect to see?

Use the profile propertie ${local.db.pw} in my pom.xml and the plugin decrypt the encrypted password.

###### What did you see instead?

Worg Password output.

**Comment by stefanwendelmann** [comment]
https://stackoverflow.com/questions/32743636/maven-use-encrypted-passwords-in-pom/32808020#32808020

**Comment by axelfontaine** [comment]
This is already fully supported. See https://flywaydb.org/documentation/maven/#settingsxml

**Comment by stefanwendelmann** [comment]
Thanks for clearing this out @axelfontaine 👍 

But how do i ref the id 

`<id>flyway-db</id>`

in my pom ?

What if i have multiple connections in my pom?

Thanks in advance
