### ISSUE TITLE
After Integrating Flyway with Jenkins, Not able to view DBMS_OUTPUT in console

### ISSUE THREAD

**Issue by vnair3** [flyway/flyway#2139]
###### Which version and edition of Flyway are you using?

FLYWAY 5.1.4 Pro (Trial)
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?

Oracle 12c

###### Which operating system are you using?
Windows 8.x

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
1)Integrated Flyway with Jenkins
2)In flyway.conf file ,set flyway.oracle.sqlplus=true;
3)Ran following Script-
    SET SERVEROUTPUT ON;
    BEGIN
	DBMS_OUTPUT.PUT_LINE('Script executed successfully');  
    END;
    /

###### What did you expect to see?

DB: Script executed successfully

###### What did you see instead?
DB: ???

**Comment by axelfontaine** [comment]
Do you have the same issue when you run Flyway directly using the CLI?

**Comment by vnair3** [comment]
@axelfontaine Even using CLI I'm coming across the issue as I'm not able to see DBMS_OUTPUT
![issue](https://user-images.githubusercontent.com/43199621/45423966-84844780-b684-11e8-9f31-bf2af7875072.png)
Migration goes through successfully but the DBMS_OUTPUT is depicted as DB: ???

**Comment by vnair3** [comment]
Hi @axelfontaine Do you have any updates regarding the above issue. If it's an existing bug with Flyway Pro 5.1.4(Trial version)?

**Comment by axelfontaine** [comment]
@vnair3 We tried to reproduce this, both with 5.1.4 and our latest sources and failed. But my gut feeling tells me this could have something to do with encoding. Is it literally "Script executed successfully" that you are trying to print, or something else containing special characters? Also what is the output when you run the same script in SQL*Plus directly?

**Comment by axelfontaine** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/684824/45814719-bfb2f600-bcd6-11e8-95c9-3c6db0c419bc.png)

Note that the code for the Trial and Enterprise Editions is identical.

**Comment by vnair3** [comment]
Hi @axelfontaine ,did you set/specify any encoding type in the configuration, like
# Encoding of SQL migrations (default: UTF-8)
# flyway.encoding=
Can you share the configurations which you're using?

**Comment by axelfontaine** [comment]
Invoking
```sql
SELECT value FROM NLS_DATABASE_PARAMETERS WHERE parameter = 'NLS_CHARACTERSET';
```
returns `AL32UTF8` and Flyway is using its default encoding (`UTF-8`)

**Comment by vnair3** [comment]
Thanks @axelfontaine for speedy reply. Our database is set at we8iso8859p15 and  Flyway is using its default encoding (UTF-8) .
Does this cause any issue while printing the DBMS_OUTPUT on flyway CLI?

**Comment by vnair3** [comment]
Thanks a lot @axelfontaine  It worked as you said.
