### ISSUE TITLE
How to configure logging for flyway?

### ISSUE THREAD

**Issue by vnair3** [flyway/flyway#2140]
###### Which version and edition of Flyway are you using?

FLYWAY 5.1.4 Pro (Trial)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?

Oracle 12c

###### Which operating system are you using?

Windows 8.x

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by axelfontaine** [comment]
See https://flywaydb.org/documentation/commandline/#output
