### ISSUE TITLE
Occasional DB deadlock causes update to fail

### ISSUE THREAD

**Issue by chriskessel** [flyway/flyway#2141]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 5.1.4 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
PostgreSQL 9.6.3 (Amazon RDS)

###### Which operating system are you using?
I assume it's linux, though I'm not seeing any specific OS listed on the RDS instance info page.

###### What did you do?
Ran the migrate script to upgrade my DB.
docker run --rm -v ./docker/postgres/rules/migration:/flyway/sql boxfuse/flyway:5.1.4-alpine -user=$POSTGRES_USERNAME -password=$POSTGRES_PASSWORD -url=jdbc:postgresql://$POSTGRES_HOSTNAME:$POSTGRES_PORT/rules -mixed=true -installedBy=ds-jenkins migrate

The upgrade failed on the recreation of the view (as noted in the error below).
```
ALTER table rule
  ADD COLUMN is_batch BOOLEAN;

ALTER table rule
  ALTER COLUMN is_batch SET DEFAULT FALSE;

CREATE OR REPLACE VIEW complete_rule_view AS ...big view join related to the rule table that was modified...
```

###### What did you expect to see?
Successful table alter and view recreation. 

The bug isn't easy to reproduce. I've run this script a couple dozen times on the DB as various test runs for a production deploy. I'll test it, then restore a snapshot back before the flyway change. Then do it again, rinse lather, repeat.

It's failed twice in those couple dozen runs.

We've done a bunch of similar flyway migrations in the past without issue. Same table, same view even. I'm not sure what's special about this particular one. Then again, it's erratic, so maybe we just got lucky before and not hit it.

I haven't had to stop the processes using the DB in the past to run the migration, but maybe I need to this time?

###### What did you see instead?
```
SQL State  : 40P01
Error Code : 0
Message    : ERROR: deadlock detected
  Detail: Process 15195 waits for AccessExclusiveLock on relation 37941 of database 16671; blocked by process 12370.
Process 12370 waits for AccessShareLock on relation 37879 of database 16671; blocked by process 15195.
  Hint: See server log for query details.
Location   : /flyway/sql/V3_0__add_is_bulk_to_rule.sql (/flyway/sql/V3_0__add_is_bulk_to_rule.sql)
Line       : 7
Statement  : CREATE OR REPLACE VIEW complete_rule_view .... blah blah
```

**Comment by axelfontaine** [comment]
Flyway executes all these statements sequentially within a single transaction on a single connection. This is most likely a PostgreSQL bug. Try upgrading to PostgreSQL 9.6.10 or 10.5 and see if this fixes the issue. Otherwise file an issue with PostgreSQL.
