### ISSUE TITLE
Flyway uses schema_version table even if I specify the table to be flyway_schema_history

### ISSUE THREAD

**Issue by swanke00** [flyway/flyway#2148]
Duplicate of #1859

_Originally posted by @axelfontaine in https://github.com/flyway/flyway/issues/1860#issuecomment-350040650_

The determineTable(Table table) method of JdbcTableSchemaHistory should FIRST check if the new default table (flyway_schema_history) exists before trying to fallback.  Flyway should only fallback if the specified table name is not found.  
For our app we have both a flyway version 3 and 4 compatible table present because our db is shared by our old and new release of software for zero downtime upgrades.  This worked fine with flyway versions 3 and 4.  Now we are upgrading to Spring Boot 2.0 which includes Flyway 5 the app won't start because flyway 5 is falling back to the schema_version table which is flyway 3 compatible.

**Comment by axelfontaine** [comment]
This is quite an unusual scenario, but you are right that a check is missing there. Done. It has now been added.
