### ISSUE TITLE
Old schema_version default is used instead of new one (flyway_schema_history)

### ISSUE THREAD

**Issue by pazvanti** [flyway/flyway#2152]
###### Which version and edition of Flyway are you using?
5.1.4 with Gradle Plugin:

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
This is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin
```
plugins {
    id "org.flywaydb.flyway" version "5.1.4"
}
```

###### Which database are you using (type & version)?
Postgresql

###### Which operating system are you using?
Debian Linux

###### What did you do?
1. In Patch 01 I have a table named `schema_version` (used for non-flyway schema history)
```
CREATE TABLE IF NOT EXISTS MY_SCHEMA.SCHEMA_VERSION (
    version numeric not null,
    creation_date timestamp not null,
    description TEXT
);
```
In the Flyway configuration from within Gradle I do not specify the schema version table or I specify it as the default one (`flyway_schema_history`)

Full flyway Gradle configuration:
```
flyway {
    url = dbUrl
    user = "test_user"
    password = "test_pass"
    locations = ["filesystem:${buildDir}/../src/main/sql"]
    sqlMigrationSuffixes = ['sql']
    sqlMigrationSeparator = '.'
    sqlMigrationPrefix = 'patch.tables_v01_00-'
    schemas = ['my_schema']
}
```
`gradle flywayMigrate` is called at this point so the table is created.

2. Create a new patch 02 that creates a new table. Call `gradle flywayMigrate` to create the new table defined in patch 02

###### What did you expect to see?
Build is successful and patch 02 is applied 

###### What did you see instead?
The old default value for flyway schema history is used instead of the new one.
Build failed with the following error:
```
Error occurred while executing flywayMigrate
  
  Error while retrieving the list of applied migrations from Schema History table "my_schema"."schema_version"
  ------------------------------------------------------------------------------------------------------------------
  SQL State  : 42703
  Error Code : 0
  Message    : ERROR: column "installed_rank" does not exist
    Position: 8
  
  ERROR: column "installed_rank" does not exist
    Position: 8
```

**Comment by axelfontaine** [comment]
This has been fixed as part of #2148
