### ISSUE TITLE
Feature Request: Enforce Sequential Versioned Migrations

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2153]
Currently, any version number is accepted so long as it is greater than the current version.  While technically it doesn't hurt anything to skip versions, it would be nice to be able to enforce that the next version is the next version.  For example, if the current version is `2` the next version must be `3`.  This might get a little tricky with minor versions since the next one could also be `2.1` or `2.01` etc., but I'm sure it's possible.  Enforcing it only at the major version level would be an easy step forward.

To avoid making it a breaking change this could be configured with something like `enforceSequentialVersions` which defaults to `false`.

**Comment by axelfontaine** [comment]
I have some doubts about whether this is useful, considering we already have features like `outOfOrder` to help us here effectively preventing `2.1` to be added after `3.0` which already covers pretty much this entire feature.

Won't fix.
