### ISSUE TITLE
Add support for transactions

### ISSUE THREAD

**Issue by starrychloe** [flyway/flyway#2159]
Please add support for transactions. I have the following migration:
```
set autocommit=0;
START TRANSACTION;
alter table allurls add column createdAt date;
update allurls set createdAt = str_to_date(promotionStart, '%m/%d/%Y');
...
COMMIT;
```

When I run it with `mvn spring-boot:run`, it gives an error:
```
2018-10-01 20:45:27.719  WARN 80872 --- [  restartedMain] o.f.c.i.database.ExecutableSqlScript     : DB: Incorrect datetime value: 'Not Found' for function str_to_date (SQL State: HY000 - Error Code: 1411)
2018-10-01 20:45:27.722 ERROR 80872 --- [  restartedMain] o.f.core.internal.command.DbMigrate      : Migration of schema `app` to version 11 - modify dates failed! Please restore backups and roll back database and code!
```

Yet the column has been created anyways!
```
> describe allurls;
...
| createdAt               | date         | YES  |     | NULL    |       |
```

I would prefer that Flyway wrap all migrations in a transaction automatically, so they either fully succeed, or fully fail. 

###### Which version and edition of Flyway are you using?
5.1.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven, Spring Boot plugin

###### Which database are you using (type & version)?
mysql Ver 15.1 Distrib 10.1.30-MariaDB, for CYGWIN (i686)

###### Which operating system are you using?
Windows 8.1, Cygwin

###### What did you do?
I tried to start the app to apply the migrations. `mvn spring-boot:run`

###### What did you expect to see?
I expected to see the error, but I expected the transaction to rollback because it never reached the `commit;` statement. I expected to _NOT_ see the new column created within the transaction.

###### What did you see instead?
I saw that it had executed the first line of the transaction and it stayed and was committed even after it failed and crashed.

**Comment by axelfontaine** [comment]
MySQL does not cleanly support DDL transactions. Instead an implicit commit is inserted before and after every DDL statement. This is a MySQL issue, not a Flyway one.
