### ISSUE TITLE
Script with dblink

### ISSUE THREAD

**Issue by DominiqueClaes** [flyway/flyway#2161]
###### Which version and edition of Flyway are you using?
4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I've tried it with version 5.1.3 and the issue remains.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
PostgreSQL 9.3

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I've executed the following script:

`CREATE FUNCTION ${schema}.tmp_migratie_kanaal()
  RETURNS VOID AS
$$
BEGIN
  
PERFORM dblink_connect('connectie', 'dbname=esuite user=esuite password=secret');
  INSERT INTO ${schema}.conf_ref_kanaal (id_kanaal, naam, omschrijving, actief, version)
  SELECT id, naam, omschrijving, actief, version
  FROM dblink('connectie',
              'SELECT id, naam, omschrijving, actief, version
               FROM reference.tbl_kanaal')
           AS oudeKanalen (id bigint, naam character varying(255), omschrijving character varying(255), actief boolean, version integer);

END;
$$
LANGUAGE 'plpgsql';

SELECT ${schema}.tmp_migratie_kanaal();

DROP FUNCTION ${schema}.tmp_migratie_kanaal();`

This script fails, however when I execute the same script by using pgAdmin, it works fine.

###### What did you expect to see?
That the migration was successful.

###### What did you see instead?
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: primary] Unable to build Hibernate SessionFactory
    Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to restore connection to its original state
--------------------------------------------------
SQL State  : null
Error Code : 0
Message    : IJ031040: Connection is not associated with a managed connection: org.jboss.jca.adapters.jdbc.jdk8.WrappedConnectionJDK8@62e31d2d
Caused by: java.sql.SQLException: IJ031040: Connection is not associated with a managed connection: org.jboss.jca.adapters.jdbc.jdk8.WrappedConnectionJDK8@62e31d2d"}

**Comment by axelfontaine** [comment]
This seems to be an issue with your datasource. Not a Flyway issue.
