### ISSUE TITLE
New command: Delete migration

### ISSUE THREAD

**Issue by froudj** [flyway/flyway#2162]
Following this question
https://stackoverflow.com/questions/50173873/delete-migration-in-flyway

A command for removing a migration could be handy:
- no need to meddle with flyway history table
- no need to keep empty files

Seems a safe option to me.

**Comment by MikielAgutu** [comment]
You shouldn't alter migrations once applied https://stackoverflow.com/a/50177381/5437021

Flyway is designed to keep an audit trail of your migrations.

If you really want to do it, delete the migration then run `repair` to remove the `missing` entry.
