### ISSUE TITLE
Non-transactiona Java-based migrations support

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#2164]
Until now `JdbcMigration` and `SpringJdbcMigration` implementations could only execute within a transaction. Flyway 5.2.0 introduces a new `JavaMigration` type which supersedes both existing ones and additionally can be configured to optionally execute without a transaction.

**Comment by geoffreywiseman** [comment]
Is there documentation describing the best upgrade approach for people with `SpringJdbcMigration`s?  I've seen some examples like this, using a `SingleConnectionDataSource`:
https://stackoverflow.com/questions/53722392/flyway-how-to-replace-deprecated-springjdbcmigration-without-getting-flywayexc

From the looks of things that's pretty close to what Flyway does internally.

I'm just trying to understand the upgrade path for people who have some `SpringJdbcMigration` descendants, and what the recommendation is on how to modify those classes. Is it just that Spring JdbcTemplate support is gone, isn't returning, there will be no guidance and people can do whatever they want to bridge that gap? Or is it something else -- something that's coming, or something that I haven't found?

**Comment by knocknarea** [comment]
@axelfontaine I have been using Flyway for over 2 years now and the big issue I have is that I have lots of existing migrations from 5.x. If I switch over to 6.x will it fix up those existing migrations in my database or will I really screw up my production database?

I now find myself urgently needing to upgrade from 5.x to 6.x as a result of this.. https://github.com/flyway/flyway/issues/2326

I need to update a query that is a production issue for me and I am in a bit of a bind, this breaking change from 5.x to 6.x is not what I need right now.

I really do not understand why you got rid of the existing interface SpringJdbcMigration??

You could have kept it for those existing users and ensured that whatever migrations they had would be preserved and handled correctly the *new* way. An interface by definition should never be changed. The other issue is that, given that SpringJdbcMigration was an interface, I (and probably many more people), would have the opportunity to boiler plate their migration code, for example

```
class VX__Migration extends BoilerPlate implements SpringJdbcMigration {
    void migrate(JdbcTemplate template) throws Exception {
         super.someBoilerPlateCode(template);
         ..
         Specific code
    }
}
```
My existing code follows this pattern a lot..

My question is... If I refactor, like this:
```
abstract class BoilerPlate extends BaseJavaMigration {

    abstract void migrate(JdbcTempate template);

   @Override
   public void migrate(Context context) throws Exception {
     JdbcTemplate template = new JdbcTemplate(new SingleConnectionDataSource(context.getConnection(), true));
     this.migrate(template);
   }
}
```
Will this work for all the existing migrations that existing in my database from 5.x. Does 6.x recognize existing 5.x migrations and upgrade their records in the database accordingly...

**Comment by danvalencia** [comment]
@geoffreywiseman do you have any insights on how to go about upgrading from SpringJdbcMigration ?
