### ISSUE TITLE
setCallbacks inconsistent deprecation warning

### ISSUE THREAD

**Issue by snicoll** [flyway/flyway#2169]
###### Which version and edition of Flyway are you using?

5.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

N/A

###### Which operating system are you using?

N/A

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Nothing specific

###### What did you expect to see?

Calling `setCallbacks` is deprecated according to the Javadoc in favour of `Flyway.configure` so the warning message should reference this method rather than a reference to an already deprecated method.

###### What did you see instead?

> Flyway.setCallbacks(FlywayCallback) has been deprecated and will be removed in Flyway 6.0. Use Flyway.setCallbacks(Callback) instead.

**Comment by axelfontaine** [comment]
Good catch! We actually had a number of cases like this, which have now all been fixed.
