### ISSUE TITLE
MySQL Driver 5.1.x support

### ISSUE THREAD

**Issue by gregorko** [flyway/flyway#2171]
###### Which version and edition of Flyway are you using?
5.2.0

###### What did you do?
When running a Gradle task Flyway tries to use the driver com.mysql.cj.jdbc.Driver and fails to find it:
``Unable to instantiate JDBC driver: com.mysql.cj.jdbc.Driver => Check whether the jar file is present``

This is caused because the used 5.1.47 driver (released 2018-08-17, supporting MySQL Server versions 5.5, 5.6, 5.7, and 8.0, JDBC 4.2) does not use this driver class but instead is using ``com.mysql.jdbc.Driver``
This used to work before with Flyway 5.1 and 5.0.

Since the MySQL drivers 6.0 and 8.0 still have some substantial bugs which are fixed in 5.1 it would be nice if the 5.1 driver could still be supported.

**Comment by axelfontaine** [comment]
Good point. Even though you could always manually override the driver class, we have now added the old class as an automatic fallback.
