### ISSUE TITLE
Flyway and schema migrations

### ISSUE THREAD

**Issue by ayedo** [flyway/flyway#2173]
###### Which version and edition of Flyway are you using?
org.flywaydb:flyway-core:5.1.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres 9.5

###### Which operating system are you using?
Mac OS X 10.11.6

###### What did you do?

I have a migration file containing: 
 
`create schema test;`

I create a Flyway object:

```
  private val flyway = Flyway().also {
        with(databaseConfig) {
            it.setDataSource(url, user, password)
        }

        val fileSystemPaths = migrationsPaths.map({ "filesystem:$it" }).toTypedArray()

        it.setLocations(*fileSystemPaths)

        if (schemas.isNotEmpty()) {
            it.setSchemas(*schemas.toTypedArray())
        }
    }
```

schemas contains the schema 'test'.

Then I run:

```
flyway.clean()
flyway.migrate()
```

on an empty database.

The first one logs that it cannot drop 'test' as it does not exist. Fair enough.
But the second one, throws an SQLException 'The schema test already exists'.
How can that be?

###### What did you expect to see?
An empty schema 'test'

###### What did you see instead?
SQLException

**Comment by axelfontaine** [comment]
I am only guessing as you didn't share your exact config, but I assume you configure the `schemas` property with the value `test`. When running for the first time, Flyway will attempt the create its schema history table if it doesn't already exist. As part of this process, Flyway will create the configured schema if it is missing as well. This is the reason why your own `create schema` statement fails, as Flyway has effectively already done the work for you.

Works as designed.
