### ISSUE TITLE
Introduce a dependency mechanism between versioned and repeatable migrations

### ISSUE THREAD

**Issue by bohalloran-chwy** [flyway/flyway#2174]
Please also see "###### Situation:" below

###### Which version and edition of Flyway are you using?
Flyway Pro Edition 5.0.7 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
No

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle, command line

###### Which database are you using (type & version)?

PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit

###### What did you do?
./gradlew :commerce:flywayMigrate

###### What did you expect to see?
A way to call the repeatable migration from inside the numbered migration.

###### What did you see instead?
The new stored procedure does not exist at the time we run the fix for historical partitions, so it will error out. Because each release is downtime, we want to execute this as one deploy and not two.

###### Situation:
 
We keep our stored procedures as repeatable migrations so that we can treat them as code.
 
We have a new stored procedure CheckPartition() which looks at a given partition and adds the required indices. We add partitions on a daily basis, and we encapsulated the logic to create the correct indices into this partition. The partition is normally called from a trigger on the parent table.
 
However, due to changes on the table (new columns, etc), this same function needs to be run against all the historical partitions to bring them into line with the current set of indices. We are doing this in a numbered migration as we only want to execute the function on these partitions once. V120__RunCheckPartition.sql
 
The stored proc and the call to fix historical partitions need to go live in the same deploy, so that all partitions are set correctly.
 
The problem:
The new stored procedure does not exist at the time we run the fix for historical partitions, so it will error out. Because each release is downtime, we want to execute this as one deploy and not two.
 
Secondary problem:
We are working on using Flyway with our AWS ephemeral environment. However, there we will always run into the problem that since the DB is totally clean, all numbered migrations run before our stored procedures, so even if we *did* execute it in two different releases originally, with the AWS environment it will always fail.
 
 
Desired solution:
A way to call the repeatable migration from inside the numbered migration.

**Comment by axelfontaine** [comment]
Thank you for the report. I certainly see your point about the dependency between versioned migrations and repeatable ones and how the order is affected by the time at which they are first run.

For now the easiest workaround is to copy the code from your repeatable migration at the beginning of the versioned one that depends on it. I am however fully aware that this isn't fully satisfactory and a proper way to express dependencies would be much better.

Leave this open for now to consider for 6.0. Suggestions and food for thought welcome.

**Comment by Sroca3** [comment]
@axelfontaine was there a solution to the related problem of a sql script referencing other sql scripts? That solution would also satisfy this requirement since including the repeatable script in the version script would be a one line @ reference. 

One of the things that I do in my project to order my repeatable scripts is to have a number as well. i.e. R__000_Permissions.sql. The number could be considered during the initial running of flyway. This might a bit complicated to remember for the average developer though.

**Comment by jakubek2085** [comment]
Hello, this has been marked as Closed, but what is the solution? In Oracle sqlplus there is "@" to reference other scripts, but has this issue been fixed by some general (DB independent) way?

**Comment by DoodleBobBuffPants** [comment]
See https://github.com/flyway/flyway/issues/3030 for anything related to migration ordering
