### ISSUE TITLE
Repeatable Migration not executed after changing Placeholder Value

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2177]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Haven't attempted, but nothing relavant is listed in the release notes for 5.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MS SQL 2014

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I have a repeatable migration with a placeholder.  I changed the value of the placeholder.

###### What did you expect to see?
I expected the repeatable migration to execute.

###### What did you see instead?
The repeatable migration did not execute.

It seems the checksum is calculated on the raw text of the migration, and not after the placeholder is replaced.  It should be calculated after so that such changes are detected.  As-is, the only way to get it to execute was to change the actual repeatable migration or change the checksum in the table.

**Comment by axelfontaine** [comment]
While this wouldn't be a small change as it would require all checksums in all Flyway installations to be recomputed, I definitely appreciate your argument. Will consider for 6.0.

**Comment by Sroca3** [comment]
@axelfontaine the checksums would the checksum not only change for files with placeholder and remain the same otherwise? Also rerunning repeatable scripts could be a performance issue for some instance I would guess but ultimately not a big deal. So the only real problem to be figured out would be the versioned scripts with placeholders right? (Just wanting to clarify the problem space)

**Comment by juliahayward** [comment]
Just noting this came up on a customer call as well.

**Comment by Sroca3** [comment]
> While this wouldn't be a small change as it would require all checksums in all Flyway installations to be recomputed, I definitely appreciate your argument. Will consider for 6.0.

@axelfontaine The migration could be handled semi-gracefully. Both checksums could be calculated and checked against with the second checksum being updated in the schema_history table without running the script if the first checksum matches. Then in the next major release you'd be able to remove the code to check against the original checksum and only used the resolved script checksum. Does that make sense?

**Comment by jaa2261** [comment]
We are in the process retro fitting flyway to an existing database. We have thousands of procedures, packages, etc generated via TOAD's DDL export under source control and we had planned to use a placeholder in a repeatable migration file that is replaced with the concatenated contents of each file. The plan being that if any of the procedures are changed they will be picked up by the repeatable migration. However we've just hit this issue. 
How do you deal with this scenario at the moment? 
Do you recommend creating a new versioned migration file each time a procedure is changed or do you create a repeatable migration file for every procedure (i.e. rename every generated  file and prefix each with R__)? 
Although the latter would be fairly straight forward source control would flag every file as being changed which would make it difficult to see which procedures have really changed (most have been stable for years)

**Comment by MikielAgutu** [comment]
@jaa2261 The feature is coming in 6.3, so your suggested workflow will be supported soon.

From my perspective it seems a bit awkward to insert a large script into a placeholder. They're designed for small items of data.

However, we've seen other users do similar things. I suspect there's a significant use case for injecting entire scripts. Could you create another issue so we could have a more detailed discussion? If you could provide more details about your scenario that would be helpful.

**Comment by jaa2261** [comment]
Created #2685 with details of our use case
