### ISSUE TITLE
Execute All Migrations Despite Failure, then Rollback

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2179]
When grouping into a single large transaction, it would be nice if all migrations would execute despite a failure instead of stopping as soon as a failure is encountered.  This way we can see all failures at once instead of just once at a time.  Of course, the rollback would still occur, but after all have been attempted.

**Comment by axelfontaine** [comment]
This poses a number of issues as not only would the failures be unreliable as the subsequent failures could be a direct consequence of the first, but certain databases such as PostgreSQL won't even let you proceed within a transaction if an error occurred. Won't fix.
