### ISSUE TITLE
Introduce the possibility to have a log file of the migration from command line

### ISSUE THREAD

**Issue by fcaponi** [flyway/flyway#2180]
###### Which version and edition of Flyway are you using?
5.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle 11G Enterprise

###### Which operating system are you using?
Windows and Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We have config files that doesn't specify username and password, mainly for security reasons but also in order to perform migrations using different accounts.
When the migration is issued without specifying to redirect the output of the console to a file, the command line correctly ask to specify username and password to be used for the migration.
When we redirect the output to a file, the command line cannot ask for user and password anymore.
The only workaround is to specify user and password as parameters on the command line, but in such way the history of the operating system stores the password of the database.

###### What did you expect to see?
We would like an additional parameter on the command line in order to have the log of the migration saved for archiving purposes and the possibility to have user and password asked by the command line

**Comment by juliahayward** [comment]
Implemented in v6.1
