### ISSUE TITLE
Repair works from Java API but not Command Line when upgrading from 3.x to 5.x

### ISSUE THREAD

**Issue by elennick** [flyway/flyway#2184]
###### Which version and edition of Flyway are you using?

3.x Java Dependency (old via Spring Boot 1.5.x)
5.0.7 Java Dependency (new via Spring Boot 2.0.5)
5.2.0 Command Line Installation

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command Line is where I am having the issue

###### Which database are you using (type & version)?

MySQL 5.6 (AWS Aurora)

###### Which operating system are you using?

MacOS X 10.13.6 (High Sierra)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

As part of the process of upgrading from Flyway 3.x to 5.x, I was attempting to use the Flyway 5.2.0 Command Line repair to repair my schema_version table. When running repair like this:

```flyway -user="user" -password='pass' -url="jdbc:mysql://AURORA-AWS-URL:3306/db?useSSL=true&verifyServerCertificate=false" -table='schema_version' repair```

I see this output:

```
Flyway Community Edition 5.2.0 by Boxfuse
Database: jdbc:mysql://AURORA-AWS-URL:3306/db (MySQL 5.6)
Repair of failed migration in Schema History table `db`.`schema_version` not necessary. No failed migration detected.
Successfully repaired schema history table `db`.`schema_version` (execution time 00:00.150s).
```

However none of the migrations checksum's are updated and the application still fails to start up due to checksum failures with Flyway.

If I instead start the application with the following configuration:

```
@Configuration
public class DataConfig {
    @Bean
    public FlywayMigrationStrategy repairMigrateStrategy() {
        return flyway -> {
            flyway.repair();
            flyway.migrate();
        };
    }
}
```

...then it does properly repair the `schema_version` table and I'm able to start up the application successfully now running with Flyway 5.0.7.

###### What did you expect to see?

I expected to be able to repair the version table using the command line tool to support an upgrade from Flyway 3.x to 5.x.

###### What did you see instead?

I saw the command line tool not repairing the table the same way that running code in the application did.

**Comment by pzygielo** [comment]
How do you set `locations` in CLI?

**Comment by elennick** [comment]
You can set locations via command line parameter or by specifying a configuration file that has a locations property. See here:

https://flywaydb.org/documentation/commandline/repair

In this case I did not specify locations at all. Are you suggesting that without specifying the migration locations that it can't modify the checksums because it doesn't have the actual migrations available to generate them off of? That would make sense and in that case this issue would really just be more around providing better documentation or error messaging to indicate that maybe?

**Comment by pzygielo** [comment]
I know how to set locations.

> Are you suggesting that without specifying the migration locations that it can't modify the checksums because it doesn't have the actual migrations available to generate them off of?

Could you check it then?

**Comment by axelfontaine** [comment]
This is indeed almost 100% certain a configuration issue on your side as the command-line tool is just a thin wrapper around the core jar. Double-check your configuration. That's where the error lies somewhere. You can use -X to have Flyway command-line output the exact config it resolved.

**Comment by elennick** [comment]
This conversation did lead me to confirming that it was because I was not specifying the `locations` property and not because anything was broken. I was able to get a CLI repair to do everything I expected once I set it. Thanks for the direction!
