### ISSUE TITLE
Option to Enforce Migrations File Format within Directories

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2186]
A very common mistake in our Flyway projects is that developers do not follow the naming conventions perfectly.  If they are not followed perfectly, the migration is ignored, leading to undesired effects.  It would be nice to have an option that would fail if there are any files in the directories that do not match the naming conventions.

**Comment by juliahayward** [comment]
We don't want to fail on all files (not least because we ship a .txt file in the sql folder) but we could extend `validate` - and therefore implicitly `migrate` - to verify that all files with the relevant suffix match a naming convention.

**Comment by esauser** [comment]
@juliahayward could allow for a way to specify a list of files or regex to allow.

**Comment by juliahayward** [comment]
OK, what I'm going to do is add an option `ignoreInvalidMigrationNames` - if true (default) then we ignore files that don't fit the convention, similar to present behaviour; if set to false then we fail fast and report on *all* badly named files, including repeatable migrations and callbacks. 

There is a small change in behaviour in that at the moment, certain edge cases can provoke an error; in future such files will be ignored by default - this will make Flyway more consistent in that it will treat all badly named files the same way. It will also make Flyway better handle the situation of users setting one of the configurable prefixes to empty-string.
