### ISSUE TITLE
Introduce Dependency Mechanism between Repeatable Migrations

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2187]
Similar to #2174 there needs to be a way to specify dependency order for repeatable migrations.  We are using repeatable migrations for stored procedures, functions, triggers, and views so that we can treat them as code.  All of these can be dependent upon one another (and even dependent on others within the same group) and we want to update them together in a single deployment.  For example, if a stored procedure relies another stored procedure or a function or a view, we need a way to specify this dependency.  Currently they simply execute alphabetical order by name.

Sure, we could resort to using versioned migrations, but there is tremendous value in treating these procedural code objects as code in the version control.

**Comment by axelfontaine** [comment]
There are already multiple ways to solve this. You can add a prefix to the name that will sort alphabetically in the correct dependency order, or you can combine multiple dependent objects within the same migration file. I don't feel an additional mechanism is necessary at this point.
