### ISSUE TITLE
trial version usage

### ISSUE THREAD

**Issue by kamaljoshi123** [flyway/flyway#2192]
In the instruction it says to download zip file and then run installToLocalMavenRepo but the link is re-directing to send licence key page. Any instructions how to use trial version?

Start by downloading and extracting the Flyway Trial Edition zip. Then execute the installToLocalMavenRepo script in the flyway-5.2.1 directory. This installs all necessary artifacts in your local Maven repository, making it possible to use them in Maven builds.

<build>
    <plugins>
        <plugin>
            <groupId>org.flywaydb.trial</groupId>
            <artifactId>flyway-maven-plugin</artifactId>
            <version>5.2.1</version>
        </plugin>
    </plugins>
</build>

**Comment by axelfontaine** [comment]
Thanks for reporting this. We changed the way to use the trial as part of 5.2.0 and it would appear the trial tab on the Maven docs page fell through the cracks while we updated the website. This has now been fixed.
