### ISSUE TITLE
Logging auto-detection fails in Apache Felix OSGi environment with multiple copies of Flyway

### ISSUE THREAD

**Issue by renat-sabitov** [flyway/flyway#2195]
Flyway uses context classloader to instantiate `org.flywaydb.core.internal.logging.slf4j.Slf4jLogCreator`, which doesn't make much sense in OSGi. First of all `org.flywaydb.core.internal` classes are not exported from the flyway bundle and therefore not present in any other classloaders rather than flyway bundle's. Therefore, `Flyway.class.getClassLoader()` should be used in OSGi environment to load `Slf4jLogCreator`.

Workaround: 

In a static context before loading any Flyway classes use 
```
LogFactory.setLogCreator(new FlywayToSlf4jLogAdaptor());
```

where `FlywayToSlf4jLogAdaptor` is a trivial slf4j (or your logging system) wrapper.

###### Which version and edition of Flyway are you using?
5.2.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres 9.5.2

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
We use Flyway as an OSGi bundle. After upgrading from 5.0.7 Flyway stopped working.

###### What did you expect to see?
Logger auto detection works in OSGi.

###### What did you see instead?
 Following error (only relevant part of stack trace):

```
jira_1               | Caused by: java.lang.ExceptionInInitializerError
jira_1               |  at org.flywaydb.core.internal.util.FeatureDetector.isSlf4jAvailable(FeatureDetector.java:96)
jira_1               |  at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:39)
jira_1               |  at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
jira_1               |  at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:25)
jira_1               |  at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:35)
jira_1               |  at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
jira_1               |  at org.flywaydb.core.Flyway.<clinit>(Flyway.java:83)
jira_1               |  at cloud.atlassian.rdbms.schema.flyway.FlywaySchemaMigration.<init>(FlywaySchemaMigration.java:34)
jira_1               |  at cloud.atlassian.rdbms.schema.flyway.FlywaySchemaMigrationProvider.get(FlywaySchemaMigrationProvider.java:21)
jira_1               |  at cloud.atlassian.rdbms.schema.module.AtlassianRdbmsSchemaModuleDescriptor.migrateSchema(AtlassianRdbmsSchemaModuleDescriptor.jav
a:149)
jira_1               |  ... 24 more
jira_1               | Caused by: java.lang.ClassCastException: org.flywaydb.core.internal.logging.slf4j.Slf4jLogCreator cannot be cast to org.flywaydb.co
re.api.logging.LogCreator
jira_1               |  at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:40)
jira_1               |  at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
jira_1               |  at org.flywaydb.core.internal.util.ClassUtils.<clinit>(ClassUtils.java:39)
jira_1               |  ... 34 more
``` 

Note that our setup is complex and we have flyway in the context classloader, only that flyway is separate from the one we use in OSGi. I.e. we have 2 flyways - one in the system bundle, not exporeted to OSGi and one as an OSGi bundle. This leads to instantiation of  `Slf4jLogCreator` from a different classloader and `ClassCastException`

**Comment by renat-sabitov** [comment]
The changes to flyway 5.0 are less than ideal. No tests, broken OSGi, flyway can't find resources in felix 6.0.1 container. Is it the start of the flyway demise or I'm exaggerating?

Really @axelfontaine , by hiding tests you just said "go away" to the contributors.

**Comment by axelfontaine** [comment]
Any news?

**Comment by renat-sabitov** [comment]
Will have a chance to work on it later this week. If only I could’ve
created a test...

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by CMoH** [comment]
I just ran into this issue. I am using the felix container within karaf-4.1.5, and I have the following aries blueprint snippet in my bundle:

```
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:cm="http://aries.apache.org/blueprint/xmlns/blueprint-cm/v1.1.0"
           xmlns:ext="http://aries.apache.org/blueprint/xmlns/blueprint-ext/v1.5.0"
           default-activation="lazy">

    <!-- other beans and services here -->

    <reference id="customerDataSource" interface="javax.sql.DataSource"
               filter="(osgi.jndi.service.name=jdbc/customer)"/>

    <!-- DB migration -->
    <bean id="flywayConfig" class="org.flywaydb.core.api.configuration.ClassicConfiguration">
        <property name="dataSource" ref="customerDataSource"/>
        <property name="locations" value="classpath://db/migration"/>
    </bean>

    <bean id="flyway" class="org.flywaydb.core.Flyway" init-method="migrate">
        <argument index="0" ref="flywayConfig"/>
    </bean>

</blueprint>
```

Can one simply inject a log interface here, so one can avoid the log detection algorithm?
