### ISSUE TITLE
Indicated Successful Rollback Despite Not Rolling Back

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2196]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Have no attempted due to #2191, but nothing relevant is listed in release notes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MSSQL 2014

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Created a new versioned migration containing the following
```
CREATE TABLE test (ID INT NOT NULL)
COMMIT TRANSACTION
COMMIT TRANSACTION
```
and executed `flyway migrate`

###### What did you expect to see?
I expected Flyway to fail and roll back properly

###### What did you see instead?
Flyway failed and indicated it rolled back successfully, but it did not rollback.  The `test` table remains.

To be clear, I am fully aware that this is not a truly valid migration.  I was testing to see if flyway would properly handle and protect us from this scenario.  At a minimum, flyway should not indicate a successful rollback in this scenario.  Maximum, truly rolling back would be fantastic.

**Comment by axelfontaine** [comment]
Flyway begins a transaction, executes all statements of the migration sequentially and then if along the way the database tells it, that one of those statements failed, Flyway tells the database to roll back the transaction. If the database tells Flyway that the transaction was successfully rolled back, Flyway reports this back to the end user.

I am afraid there is not much more we can do here. Works as designed.

In fact in this case I don't even know how we could address this, as you explicitly told SQL Server to decrease [`@@TRANCOUNT`](https://docs.microsoft.com/en-us/sql/t-sql/functions/trancount-transact-sql?view=sql-server-2017) twice even though you never increased it first. And using a transaction name doesn't help either as that is simply ignored by SQL Server as well.

**Comment by esauser** [comment]
The database cannot roll back the transaction since it was already committed by the migration.  Thus, Flyway can't be receiving a successful rollback.  The following query is essentially what I understand Flyway to be doing in this scenario, which results in an error.
```
BEGIN TRANSACTION

BEGIN TRY
	COMMIT TRANSACTION
	COMMIT TRANSACTION
END TRY
BEGIN CATCH

END CATCH

ROLLBACK TRANSACTION
```

It seems to me that Flyway should not be reporting back a successful rollback since a rollback has not occurred.

If you're hung up on the two commits, we can change the part that causes the error to literally anything.  For example, let's say we don't have a table named `tableThatDoesNotExist` and we replace the second `COMMIT TRANSACTION` with `DROP TABLE tableThatDoesNotExist`.  The same result occurs; Flyway indicates successful rollback despite that not occurring.  Since the migration itself is committing the transaction, Flyway is unable to roll it back, and thus, should report a failed rollback.

**Comment by axelfontaine** [comment]
As I mentioned in my previous comment, you are actively circumventing Flyway's transaction by intentionally decreasing `@@TRANCOUNT` to 0 and causing the outer transaction to commit. There is nothing we can do at the point. And yes, SQL Server does report the rollback as successful. If you want nested transactions to work, you must issue a `BEGIN TRANSACTION` statement in the same migration.

Alternatively you can also use Flyway Pro Edition's `beforeEachMigrateStatement` callback to intercept the `COMMIT` statement and for example issue an error indicating that such a statement is not allowed in your migrations.
