### ISSUE TITLE
Flyway fails to find resources in Felix 6.0.1 environment

### ISSUE THREAD

**Issue by renat-sabitov** [flyway/flyway#2198]
###### Which version and edition of Flyway are you using?
5.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres

###### Which operating system are you using?
Linux

###### What did you do?
Upgraded Felix to 6.0.1

###### What did you expect to see?
Flyway worked as before

###### What did you see instead?
Flyway fails to find resources

The reason is felix changes resource URL schemas, they look now like this:

```
"bundle://e3a74e5a-af1f-46f0-bb53-bc5fee1b4a57_145.0:1/db/connect-migrations"
```

The bundle id is 145 in the example above.

**Comment by renat-sabitov** [comment]
see pull request https://github.com/flyway/flyway/pull/2199

**Comment by axelfontaine** [comment]
Fixed by adjusting the bundle URL parser to correctly extract the bundle ID from the host. Please try and confirm the flyway-5.2.x branch it is now working for you.

**Comment by renat-sabitov** [comment]
@axelfontaine , your solution didn't work, try on this one:
`5320885d-5e87-4a47-82eb-7cdac36e6978_120.0`

I'm not going to provide a unit test, however I would encourage you to have one. Your regexps are not working as they are.

**Comment by axelfontaine** [comment]
@renat-sabitov Thanks for letting me know. Fixed.

**Comment by renat-sabitov** [comment]
@axelfontaine any chance releasing a new version?

**Comment by axelfontaine** [comment]
@renat-sabitov It's already out as part of the 6.0.0-beta preview.

**Comment by renat-sabitov** [comment]
@axelfontaine is there any chance of releasing it in 5.2.5?
