### ISSUE TITLE
Started getting warnings like this after upgrading to 5.2.1: WARNING: DB: Incorrect string value

### ISSUE THREAD

**Issue by tskardal** [flyway/flyway#2200]
###### Which version and edition of Flyway are you using?
Flyway 5.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using (type & version)?
mysql 5.7

###### Which operating system are you using?
Windows 10
Linux (at Docker)

###### What did you do?

After upgrading to 5.2.1 I noticed that a lot of these warnings are printed when migrating. Can this in any way be related to flyway? I can't reproduce it in macOS, and I cannot find a reason for it to behave like this under Windows.

Update: I also noticed the same behaviour when running test migrations in CI in a docker container. 

Example of output:

```
WARNING: DB: Incorrect string value: '\xF8te' for column 'tekst' at row 2 (SQL State: HY000 - Error Code: 1366)
WARNING: DB: Incorrect string value: '\xF8nstri...' for column 'tekst' at row 9 (SQL State: HY000 - Error Code: 1366)
WARNING: DB: Invalid utf8 character string: 'F8' (SQL State: HY000 - Error Code: 1300)
WARNING: DB: Invalid utf8 character string: 'E56C20' (SQL State: HY000 - Error Code: 1300)
```

Observation: the resulting table data in 5.1.4 is 'Møte' as expected while it becomes 'M?te' in 5.2.1

**Comment by axelfontaine** [comment]
This is almost certainly due to an encoding misconfiguration somewhere on your end. Double-check both your sql files as well as your Flyway config files and add the `-X` to Flyway to see the effective config being used.

**Comment by tskardal** [comment]
Thanks for answering.

For others maybe arriving here:

I solved this by adding characterEncoding=utf8 to my jdbc connection string. I assume that the mariadb driver (which was used by 5.1.4) used this as a default value, whereas the mysql driver doesn't.

**Comment by axelfontaine** [comment]
Ahh very interesting! Thanks for investigating and glad to hear it is working for you now.
