### ISSUE TITLE
Rollback in Java migration causes wrong schema to be used with postgres

### ISSUE THREAD

**Issue by JoelColledge** [flyway/flyway#2201]
###### Which version and edition of Flyway are you using?

5.1.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

Yes, also occurs with 5.2.1.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

Postgres 10.4 (started with `docker run --name linstor-postgres -P --rm postgres:10.4`)

###### Which operating system are you using?

Ubuntu 18.04

###### What did you do?

* Configure Flyway with an explicit schema name.
* Apply a migration that performs a rollback and then creates a table.

See minimal reproducer at https://github.com/JoelColledge/flyway-rollback-test

###### What did you expect to see?

The table is created in the given schema ("MY_SCHEMA"). This works with Flyway 5.0.7.

###### What did you see instead?

The table is created in the schema "public".

##### Motivation

In order to make our migrations idempotent, we check for the existence of DB objects by simply attempting a select. In order to ensure that these checks do not affect the DB, we perform a rollback afterwards. After upgrading Flyway from 5.0.7, we encountered the above schema issues.

**Comment by axelfontaine** [comment]
The rollback will effectively mess up any set up Flyway does for a connection. You can however use savepoints as an alternative. First create a savepoint, do your select and then rollback to that savepoint.

Think of them as PostgreSQL's alternative to true nested transactions, which it does not support.

Won't fix.
