### ISSUE TITLE
Flyway fails to drop SQL Server assembly in a DB with multiple schemas

### ISSUE THREAD

**Issue by AigleeK** [flyway/flyway#2208]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 5.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-Line

###### Which database are you using (type & version)?

SQL Server 2017

###### Which operating system are you using?

Windows 10

###### What did you do?

We have a DB with several schemas, and an Assembly. When trying to use the clean command, Flyway assumes the assembly is part of a schema and tries to drop it, but because assemblies are not schema-bound, it tries to drop the assembly for whatever first schema is configured in the conf file and fails with dependencies.

###### What did you expect to see?

Assemblies should be dropped as the last thing to be done after cleaning all schemas. That way we can be sure dependencies are dropped. This would also be consistent with the fact that assemblies cannot be schema-bound.

I can provide some code with an assembly and references from a couple of different schemas if needed to reproduce.

**Comment by axelfontaine** [comment]
Thanks for the files. Could you also share a quick SQL file that creates an empty assembly? This would help in resolving both this and the #1715 issue. Many thanks!

**Comment by AigleeK** [comment]
Hi Axel,

I'm attaching the sql file to create an empty assembly (I changed it to txt to upload).

I'm curious, how would you use this assembly?

Thanks

[EmptyAssembly.txt](https://github.com/flyway/flyway/files/2596497/EmptyAssembly.txt)

**Comment by axelfontaine** [comment]
Delaying until 6.0 to investigate the best way to fix this.

**Comment by juliahayward** [comment]
There's some overlap with #2447 which also involves objects that live above the schema level.
