### ISSUE TITLE
Flyway MSSQL connection problem

### ISSUE THREAD

**Issue by stefancvetkovic** [flyway/flyway#2211]
###### Which version and edition of Flyway are you using?
5.2.1 

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I want to use firefly with MSSQL 2017 edition (SQLEXPRESS)
I set up conf file like:
flyway.url= jdbc:sqlserver:////SQLEXPRESS:1433;databaseName=TestDb
flyway.user=admin
flyway.password=admin

All other parameters are not touched.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
SQL Expression Server MSSQL 2017

###### Which operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway.url= jdbc:sqlserver:////SQLEXPRESS:1433;databaseName=TestDb
flyway.user=admin
flyway.password=admin

All other parameters are not touched.

Than when I run comman flyway info, and it prompts me for password. I insert password admin&admin
and then I get the error: 
WARNING: Discarding INCOMPLETE dataSource configuration! flyway.url must be set.
ERROR: Unable to connect to the database. Configure the url, user and password!

###### What did you expect to see?
Successfully connected to SQL...

###### What did you see instead?
WARNING: Discarding INCOMPLETE dataSource configuration! flyway.url must be set.
ERROR: Unable to connect to the database. Configure the url, user and password!

**Comment by axelfontaine** [comment]
Where did those 4 slashes come from? Or better said, what made you think 4 were needed? (serious question, trying to understand how you arrived at this)

Replace with 2 slashes and things should work as expected. See https://flywaydb.org/documentation/database/sqlserver#driver

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
