### ISSUE TITLE
Flyway warns about Postgres 10.5 being unsupported

### ISSUE THREAD

**Issue by arlampin** [flyway/flyway#2213]
###### Which version and edition of Flyway are you using?
5.2.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API, Gradle

###### Which database are you using (type & version)?
Postgres 10.5

###### What did you do?
Running any Flyway command results in the following warning:

    Flyway upgrade recommended: PostgreSQL 10.5 is newer than this version of Flyway and support has not been tested.

###### What did you expect to see?
Flyway shouldn't warn about Postgres minor releases. PG changed their versioning schema with Postgres 10, so that all 10.x releases should be compatible.

**Comment by axelfontaine** [comment]
Thanks for reporting. Fixed!
