### ISSUE TITLE
Command-line on Windows: Locations with spaces fails with `was unexpected at this time` error 

### ISSUE THREAD

**Issue by kgeorge314** [flyway/flyway#2220]
###### Which version and edition of Flyway are you using?
5.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-Line | Powershell via Octopus

###### Which database are you using (type & version)?
SQL Server | Azure & 2017

###### Which operating system are you using?
Windows 10 | 2012R2 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

The `locations` path contains a space i.e. `C:\Work\temp\(US) Test\sql\`. We tried the following 

- **Original:** `.\flyway -user=xx -password=yy -url="jdbc:sqlserver://**;databaseName=**" -locations=filesystem:C:\Work\temp\(US) Test\sql\ migrate`
- **Single-quote:** `.\flyway -user=xx -password=yy -url="jdbc:sqlserver://**;databaseName=**" -locations=filesystem:'C:\Work\temp\(US) Test\sql\' migrate`
- **Double-Quote:** `.\flyway -user=xx -password=yy -url="jdbc:sqlserver://**;databaseName=**" -locations=filesystem:"C:\Work\temp\(US) Test\sql\" migrate`
- **Quote-All:** `.\flyway -user=xx -password=yy -url="jdbc:sqlserver://**;databaseName=**" -locations="filesystem:C:\Work\temp\(US) Test\sql\" migrate`
& `.\flyway -user=xx -password=yy -url="jdbc:sqlserver://**;databaseName=**" -locations='filesystem:C:\Work\temp\(US) Test\sql\' migrate`
- **Linux Style escapce:** `.\flyway -user=xx -password=yy -url="jdbc:sqlserver://**;databaseName=**" -locations='filesystem:C:/Work/temp/(US)\ Test/sql' migrate`

###### What did you expect to see?
Flyway Migration 

###### What did you see instead?
Error: 
`Test/sql""=="" was unexpected at this time.`

**Comment by axelfontaine** [comment]
On Windows, you need to wrap the entire argument in double quotes and it will work:

```
.\flyway -user=xx -password=yy -url=jdbc:sqlserver://**;databaseName=** "-locations=filesystem:C:\Work\temp\(US) Test\sql\ migrate"
```

**Comment by kgeorge314** [comment]
Thanks, @axelfontaine, that fixed it.

**Comment by kgeorge314** [comment]
Hi @axelfontaine - Apologies, I forgot to mention that it works fine in `5.0.7` but not in `5.2.1` / `5.2.3`

✅ Works in `Flyway Community Edition 5.0.7 by Boxfuse`

![image](https://user-images.githubusercontent.com/7089603/49159923-7b1e8900-f31d-11e8-9f18-b1417def0a3d.png)

❌ Doesn't work in `Flyway Community Edition 5.2.1 by Boxfuse`

![image](https://user-images.githubusercontent.com/7089603/49159896-6b06a980-f31d-11e8-80c9-1d7b878469f7.png)

❌ Doesn't work with full quotes either `.\flyway.cmd -user=sa -password=P@ssw0rd -url="jdbc:sqlserver://sqldock;databaseName=OneView" "-locations=filesystem:C:\Work\temp\US Test\sql" migrate`
![image](https://user-images.githubusercontent.com/7089603/49160104-e36d6a80-f31d-11e8-92e2-eee07aa718bb.png)


> The enviroment is a local-docker instance, Server, Passwords etc are all temporary.

**Comment by axelfontaine** [comment]
Thank you very much for digging deeper. We found the bug in our Windows batch argument parsing code that wasn't dealing properly with double quotes and spaces. Fixed.
