### ISSUE TITLE
Apache Ignite Support

### ISSUE THREAD

**Issue by xtron** [flyway/flyway#2227]
###### Which version and edition of Flyway are you using?
5.1.4

##### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API
###### Which database are you using (type & version)?
Apache Ignite 2.6  (thin JDBC Client)

###### Which operating system are you using?
Linux

###### What did you do?
Try to connect:

`
INFO  o.f.c.i.database.DatabaseFactory - Database: jdbc:ignite:thin://localhost:10800/PUBLIC (Apache Ignite 2.6)
org.flywaydb.core.api.FlywayException: Unsupported Database: Apache Ignite 2.6
`

**Comment by DoodleBobBuffPants** [comment]
This is now available in [`flyway-community-db-support`](https://mvnrepository.com/artifact/org.flywaydb/flyway-community-db-support)
