### ISSUE TITLE
command-line call does not uses default FLYWAY_EDITION

### ISSUE THREAD

**Issue by tcat2** [flyway/flyway#2230]
###### Which version and edition of Flyway are you using?
5.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
it's the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using (type & version)?
MAriaDB 10.3

###### Which operating system are you using?
Windows 10, 64bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
C:\hided\flyway -url="jdbc:mariadb://localhost:3306/hided?autoReconnect=true&sessionVariables=character_set_client=utf8mb4,character_set_connection=utf8mb4,character_set_results=utf8mb4,collation_connection=utf8mb4_general_ci" -user=hided -password=hided -locations=filesystem:hided,filesystem:hided -table=hided info

###### What did you expect to see?
info output

###### What did you see instead?
"=true" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

I figured out, that it works fine if there are no url parameters in jdbc url.
The only way to make this work for version 5.2.3 is to add "-communy" parameter in command line call as well. So in this case "-communiy" is not used as default for flyway_edition.

**Comment by axelfontaine** [comment]
This could be a duplicate of #2220 

Please try again with 5.2.4. Does it fix the issue?

**Comment by tcat2** [comment]
Yes. Works fine with version 5.2.4.
