### ISSUE TITLE
Rephrase spring boot section to mention dependency management

### ISSUE THREAD

**Issue by snicoll** [flyway/flyway#2231]
A version is currently hardcoded in the Maven and Gradle example of [the spring boot section](https://flywaydb.org/documentation/plugins/springboot) of the documentation. Spring Boot is using dependency management to avoid specifying any version at all and this includes the Flyway dependency. 

I understand that we can't assume users are using this feature so simply removing the version might not be a good idea. It would be nice to mention that users using [our dependency management](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-dependency-management) do not have to specify the version.

Thanks!

**Comment by MikielAgutu** [comment]
Thanks for the request. The update to the documentation will be released with V6.
