### ISSUE TITLE
Clean tries to drop a table from an extension and fails

### ISSUE THREAD

**Issue by svpace** [flyway/flyway#2232]
As instructed by @axelfontaine in https://github.com/flyway/flyway/issues/100#issuecomment-443624051_

flyway version 5.2.4

V1__init.sql:
```
CREATE EXTENSION IF NOT EXISTS POSTGIS;
```

On clean:
```
ERROR: cannot drop table spatial_ref_sys because extension postgis requires it
         Hint:You can drop extension postgis instead.
```

**Comment by axelfontaine** [comment]
Thanks for reporting. The extension dependency detection has now been extended to also include tables. Fixed.

**Comment by svpace** [comment]
Great work @axelfontaine, that was really fast!! Thanks
