### ISSUE TITLE
Oracle SQL*Plus: WHENEVER SQLERROR CONTINUE parsing fails

### ISSUE THREAD

**Issue by Me1gireesh** [flyway/flyway#2233]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Me1gireesh** [comment]
I am using Command line to call the flyway to migrate for testing. Oracle database version I'm using is Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production.

**Comment by Me1gireesh** [comment]
WARNING: Ignoring unsupported SQL*Plus statement: WHENEVER SQLERROR {CONTINUE}

Successfully validated 1 migration (execution time 00:00.895s)
Current version of schema "PROCESS_CICD": << Empty Schema >>
Migrating schema "PROCESS_CICD" to version 1 - test table create
ERROR: Migration of schema "PROCESS_CICD" to version 1 - test table create failed! Please restore backups and roll back database and code!
ERROR:
Migration V1__test_table_create.sql failed
------------------------------------------
SQL State  : 42000
Error Code : 955
Message    : ORA-00955: name is already used by an existing object
Location   : C:\flyway-5.0.7\flyway-5.2.4\sql\V1__test_table_create.sql (C:\flyway-5.0.7\flyway-5.2.4\sql\V1__test_table_create.sql)
Line       : 2
Statement  : Create table sdr.test1( col1 number, col2 varchar2(10))

**Comment by Me1gireesh** [comment]
WARNING: Ignoring unsupported SQL*Plus statement: WHENEVER SQLERROR {CONTINUE}

Successfully validated 1 migration (execution time 00:00.895s)
Current version of schema "PROCESS_CICD": << Empty Schema >>
Migrating schema "PROCESS_CICD" to version 1 - test table create
ERROR: Migration of schema "PROCESS_CICD" to version 1 - test table create failed! Please restore backups and roll back database and code!
ERROR:
Migration V1__test_table_create.sql failed
------------------------------------------
SQL State  : 42000
Error Code : 955
Message    : ORA-00955: name is already used by an existing object
Location   : C:\flyway-5.0.7\flyway-5.2.4\sql\V1__test_table_create.sql (C:\flyway-5.0.7\flyway-5.2.4\sql\V1__test_table_create.sql)
Line       : 2
Statement  : Create table sdr.test1( col1 number, col2 varchar2(10))

**Comment by Me1gireesh** [comment]
I have installed flyway 5.2.4 enterprise trial version on my Desktop for testing. Windows 10 64 bit OS.

**Comment by axelfontaine** [comment]
It appears your SQL*Plus statement is: `WHENEVER SQLERROR {CONTINUE}`

This is not valid syntax and SQL*Plus rejects it with:
```
SQL> WHENEVER SQLERROR {CONTINUE}
Usage: WHENEVER SQLERROR
     { CONTINUE  [ COMMIT | ROLLBACK | NONE ]
     | EXIT  [ SUCCESS | FAILURE | WARNING | n | <variable> | :<bindvariable> ]
             [ COMMIT | ROLLBACK ] }
```

If you on the other hand remove the curly braces and change it to `WHENEVER SQLERROR CONTINUE` both SQL*Plus and Flyway will accept it.

Please confirm this is now working for you.

**Comment by Me1gireesh** [comment]
I also did try adding a semicolon at the end of WHENEVER SQLERROR CONTINUE; still the same issue persists 
Current version of schema "PROCESS_CICD": << Empty Schema >>
Migrating schema "PROCESS_CICD" to version 1 - test table create
ERROR: Migration of schema "PROCESS_CICD" to version 1 - test table create failed! Please restore backups and roll back database and code!
ERROR:
Migration V1__test_table_create.sql failed
------------------------------------------
SQL State  : 42000
Error Code : 900
Message    : ORA-00900: invalid SQL statement
Location   : C:\flyway-5.0.7\flyway-5.2.4\sql\V1__test_table_create.sql (C:\flyway-5.0.7\flyway-5.2.4\sql\V1__test_table_create.sql)
Line       : 1
Statement  : WHENEVER SQLERROR CONTINUE

**Comment by axelfontaine** [comment]
I can't seem to reproduce this. Did you set `flyway.oracle.sqlplus=true` in your config file?

If that still fails could you share the exact SQL file and the exact conf file you are using?

**Comment by axelfontaine** [comment]
You're welcome!
