### ISSUE TITLE
Suppress Warning Messages during Flyway Migrate

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2234]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Haven't tried, but I'm confident it will reproduce

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
We created a versioned migration (V18) that renames a bunch of objects to match our naming standards via `sp_rename`.

###### What did you expect to see?
When running `flyway migrate` we expected to see only that the versioned migration had executed in the output.

###### What did you see instead?
Instead, we see that it executed but also a `WARNING` for every call to `sp_rename` since it returns said `WARNING`.  This is causing developers to question if that is expected since it looks alarming.  I see in #843 that `WARNING`s were shown intentionally, at least back 2014.  Can we suppress these?
![image](https://user-images.githubusercontent.com/24945592/49596084-1e375a00-f93f-11e8-99f7-76888eec2e74.png)

**Comment by axelfontaine** [comment]
Starting with 5.2, this is possible with `errorOverrides`. See https://flywaydb.org/documentation/erroroverrides

In your case you all you would need to add to your conf file is `flyway.errorOverrides=S0001:15477:D` and Flyway will automatically transform all these warnings into debug messages (only shown with `-X`)

**Comment by esauser** [comment]
@axelfontaine shoot... we're on `community`.  I'm curious how you determine which features are for `community`.
