### ISSUE TITLE
Custom password for newly created Oracle schemas

### ISSUE THREAD

**Issue by tobato** [flyway/flyway#2239]
The feature of auto create oracle database schema is cool , but it has some problem

1. we can not config database password 
2. the database create with default password 'FFllyywwaayy00!!' , but can not connect by client!

```
public class OracleSchema extends Schema<OracleDatabase> {

@Override
    protected void doCreate() throws SQLException {
        jdbcTemplate.execute("CREATE USER " + database.quote(name) + " IDENTIFIED BY "
                + database.quote("FFllyywwaayy00!!"));
        jdbcTemplate.execute("GRANT RESOURCE TO " + database.quote(name));
        // should add grant
        jdbcTemplate.execute("GRANT connect TO " + database.quote(name)); 
        jdbcTemplate.execute("GRANT UNLIMITED TABLESPACE TO " + database.quote(name));
    }
}

```
should add  `jdbcTemplate.execute("GRANT connect TO " + database.quote(name)); `

**Comment by axelfontaine** [comment]
The default password we use conforms to the default Oracle password guidelines in newer versions of the database. See #1943 

Why exactly is this password a problem for you?

**Comment by tobato** [comment]
1. the new schema create by flyway can't coonect by client. 

2. we want to set the password if possible

**Comment by StuporHero** [comment]
Grants can currently be performed in migration scripts. You can add `grant connect, unlimited tablespace to user` to the beginning of your first migration to ensure you have everything you need for the rest of your migrations. Not everyone is going to want `unlimited tablespace` for each of those users, so those grants would either need to be configurable, or a recommendation should be included in the documentation to include grants in your migrations.

You can also issue an `alter user schema_user identified by Pa$$word` in a migration to set the password as you like, however, I would consider this one worth adding as a configurable parameter in flyway itself for the case that `FFllyywwaayy00!!` doesn't conform to a custom password policy which would cause the schema creation to fail.

**Comment by MikielAgutu** [comment]
Related to https://github.com/flyway/flyway/issues/2990
