### ISSUE TITLE
CREATE FULLTEXT CATALOG statement cannot be used inside a user transaction

### ISSUE THREAD

**Issue by AlBa231** [flyway/flyway#2242]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 5.2.4 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

MS SQL Server Express 14.0.3015

###### Which operating system are you using?

Windows 10

###### What did you do?

create script file with content
`CREATE FULLTEXT CATALOG comments_catalog;`

run command 
`flyway migrate`

###### What did you expect to see?

Script executed without errors.

###### What did you see instead?

```
ERROR: 
Migration V11__CommentsIndex.sql failed
-----------------------------------------
SQL State  : S0000
Error Code : 574
Message    : CREATE FULLTEXT CATALOG statement cannot be used inside a user transaction.
Location   : ...\sql\V11__CommentsIndex.sql (...\sql\V11__CommentsIndex.sql)
Line       : 1
Statement  : 
CREATE FULLTEXT CATALOG comments_catalog;
```

**Comment by axelfontaine** [comment]
Thanks for reporting. Fixed.
