### ISSUE TITLE
Gradle plugin doesn't find class based migrations of Kotlin project

### ISSUE THREAD

**Issue by nschlehe** [flyway/flyway#2244]
###### Which version and edition of Flyway are you using?
5.2.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
gradle-plugin

###### Which database are you using (type & version)?
Postgres

###### Which operating system are you using?
Linux

###### What did you do?
I added a sql migration as well as a class based one. I'm using spring boot with Kotlin. When starting the 
application migrations are correctly applied. What's not working is the gradle-plugin, it only applies the sql based migrations. It might be related to [this](https://github.com/flyway/flyway/blob/master/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L450)

**Comment by axelfontaine** [comment]
I am unable to reproduce this with the latest Gradle, Flyway and Kotlin versions while testing with a Jdbc migration written in Kotlin. Please reopen with exact steps how to reproduce if the issue persists.
