### ISSUE TITLE
Connection.close restores some things, should ignore broken connection

### ISSUE THREAD

**Issue by reitzmichnicht** [flyway/flyway#2247]
###### Which version and edition of Flyway are you using?
Flyway 5.1.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
same code in repo

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
SQL Server 2014

###### Which operating system are you using?
Windows

###### What did you do?
Having a migration which sets SINGLE_USER mode

###### What did you expect to see?
Flyway will close all connections, also on SocketException because SQL Server dropped already opened connection due to SINGLE_USER mode.

###### What did you see instead?
SocketException throws. SocketException could be swalled because restoring of any previous connection state is not necessary if socket is already closed.
Please add a try catch for SocketException in close method of connection class.

**Comment by axelfontaine** [comment]
I am not sure I fully understand the issue. With SQL Server, Flyway uses a single database connection anyway. If that connection sets the database to SINGLE_USER mode, it doesn't get closed. So what exactly is the issue here?

**Comment by reitzmichnicht** [comment]
You are right that it should not happen in normal use.

I stumbled upon it when unit testing flyway migration scripts with the following code:

  ```
  try (Database<?> database = DatabaseFactory.createDatabase(migrator.getMigrator(), false)) {
      schema = database.getMainConnection().getSchema(SCHEMA);
      if (schema.exists()) {
        schema.clean();
      } else {
        schema.create();
      }
    // if you call migrate here the try with ressources will try to close the connection after the migration reseted the connection because of single user mode
    }
```

Otherwise I see no disadvantages in fixing this case to make the library more robust

**Comment by axelfontaine** [comment]
We decided to leave things as is as all officially supported scenarios work without any issue.
