### ISSUE TITLE
No Values provided for placeholder

### ISSUE THREAD

**Issue by Barathwaja** [flyway/flyway#2249]
**Flyway 5.1.4 version** while running MySQL Query with ${} it throws No Values provided for placeholder.

Is it fixed or any solutions can you provide??

**Comment by axelfontaine** [comment]
You can either disable placeholders or use a different prefix/suffix to make things work.

Next time, please fill in the full issue template.

**Comment by Barathwaja** [comment]
@axelfontaine can i comment that out from the flyway configuration? 

https://flywaydb.org/documentation/commandline/info

found that in the above link.

**Comment by qiaojiang2** [comment]
[main] ERROR org.apache.maven.cli.MavenCli - Failed to execute goal org.flywaydb:flyway-maven-plugin:5.2.4:migrate (default) on project wallet: org.flywaydb.core.api.FlywayException: No value provided for placeholder expressions: ${spring.datasource.schema}.  Check your configuration! -> [Help 1]
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - To see the full stack trace of the errors, re-run Maven with the -e switch.
[main] ERROR org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
[main] ERROR org.apache.maven.cli.Ma
