### ISSUE TITLE
RFE: Add Flyway.truncate()

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#225]
_Original author: jonas.ki...@gmail.com (April 14, 2011 19:23:31)_

When running junit (integration) tests, one often wants to empty the database upon @Before in order to start the tests with a clean state. It's doable like this, albeit very time consuming:

```
flyway.clean();
flyway.init();
flyway.migrate();
```

Proposal: add flyway.truncate() to just empty the tables instead of re-creating them.

As homework I leave it to you to think about how not to truncate the masterdata insterted as part of flyway.migrate() before, e.g. earlier in the build process where the database was created initally. Because that data is often needed for tests as well and belongs to the database's base resp. initial setup.

Want do you think? Maybe specifying an exclusion pattern for tables not to truncate would work for 90&#37; of the time?

_Original issue: http://code.google.com/p/flyway/issues/detail?id=122_

**Comment by eyalroth** [comment]
Does it matter if I "upvote" now, many months later? :)

**Comment by Kamshak** [comment]
Yeah, i'd like to upvote. too :dancer:

**Comment by pchudzik** [comment]
I think it might be useful feature. I'd use it for sure ;)

**Comment by elnur** [comment]
I want it, too. `flyway clean migrate` before every test is taking too much time. Especially when there are hundreds of migrations.

**Comment by eyalroth** [comment]
@flyway @axelfontaine

**Comment by jigyasu11** [comment]
I would like to use it too +1

**Comment by mystdeim** [comment]
+1

**Comment by eiston14** [comment]
+1

**Comment by jean-amana** [comment]
Same here, +1

**Comment by amitkumariitd** [comment]
Upvote +1

**Comment by the-serious-programmer** [comment]
Upvote almost 10 years later, still relevant!
