### ISSUE TITLE
Flyway 3.2.1 version db migration tool

### ISSUE THREAD

**Issue by arunkoratagere** [flyway/flyway#2250]
I am using flyway 3.2.1 version of db migration tool.flyway supports callbacks. I have a requirement to use that callbacks to evict my application cache. The caching logic is in spring framework. Flyway is not supporting the depedency injection of spring to call that caching logic. Could you please help me how can we inject spring objects in flyway callbacks.

**Comment by arunkoratagere** [comment]
Please help me out of flyway tool with spring depedency injection.

**Comment by axelfontaine** [comment]
This is not a Flyway issue. Please post your question on StackOverflow.
