### ISSUE TITLE
No unit tests for source code

### ISSUE THREAD

**Issue by kennethinsnow** [flyway/flyway#2251]
###### Which version and edition of Flyway are you using?
current github version

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Intellij or just github website

###### Which database are you using (type & version)?
N/A

###### Which operating system are you using?
Mac

###### What did you do?
I was reading the source code and noticed the unit tests are not there, at least i didn't find them in the github repo. Could someone help me finding them? 

###### What did you expect to see?
Unit tests for flyway codes.

###### What did you see instead?
no test folder, and doesn't seem any tests were run when running "mvn test"

**Comment by kennethinsnow** [comment]
I would also like to join the developer's community as well. Is there a slack channel or other forum that the development issues are discussed.

**Comment by axelfontaine** [comment]
Our automated tests and our large test infrastructure are private. We have no plans to change that.

**Comment by kennethinsnow** [comment]
@axelfontaine Hi, Axel, I was thinking about making code contributions, but without the testing, it would be a lot less efficient to do that. Whats the proper way to contribute to the code?

**Comment by dennislloydjr** [comment]
What is the advantage of having private only unit tests and how does that aid contributors in ensuring code quality? Should pull requests include unit tests that will then be made private?
