### ISSUE TITLE
Oracle: Parser fails on VIEW ... WITH not followed by PL/SQL

### ISSUE THREAD

**Issue by apexbine** [flyway/flyway#2252]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 5.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command Line

###### Which database are you using (type & version)?

Oracle 12.2

###### Which operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Ran this statement, which worked perfectly in SQL Developer:

```
create or replace view test_view
as
  with b_soll
       as ( 
           select 'c' eins
                , 'd' zwei
                , 'e' drei               
             from dual )
     , b_ist
       as ( 
           select 'c' vier
                , '1'  fuenf
                , 'd' sechs
             from dual )
  ( select 'SOLL' soll
         , eins
         , zwei
         , drei
      from b_soll
   minus
   select 'SOLL' soll
        , vier
        , fuenf
        , sechs
     from b_ist )
  union all
  ( select 'IST' ist
         , vier
         , fuenf
         , sechs
      from b_ist
   minus
   select 'IST' ist
        , eins
        , zwei
        , drei
     from b_soll );
```

###### What did you expect to see?

Success message

###### What did you see instead?

SQL State  : 42000
Error Code : 933
Message    : ORA-00933: SQL command not properly ended

**Comment by axelfontaine** [comment]
Fixed. It turned out to be a delimiter issue. We wrongly assumed that it was always `/` after `CREATE VIEW ... AS WITH`, but as this case demonstrated, this assumption was too imprecise.
