### ISSUE TITLE
Your project flyway/flyway is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [flyway/flyway#2253]
Hi, there!

We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.

We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.

1. commons-logging commons-logging(pom.xml)
version: 1.1.1

Jira issues:
Unit tests fail on linux with java16
affectsVersions:1.1.1
https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-117?filter=allopenissues
deadlock on re-registration of logger
affectsVersions:1.1.1
https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-119?filter=allopenissues
Potential missing privileged block for class loader
affectsVersions:1.1.1
https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-130?filter=allopenissues
Log4JLogger uses deprecated static members of Priority such as INFO
affectsVersions:1.1.1
https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-142?filter=allopenissues
LogFactory/LogFactoryImpl ingore Throwable
affectsVersions:1.1.1
https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-144?filter=allopenissues
LogFactory.nullClassLoaderFactory is not properly synchronized
affectsVersions:1.1.1
https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-146?filter=allopenissues
SimpleLog.log - unsafe update of shortLogName
affectsVersions:1.1.1
https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-147?filter=allopenissues
BufferedReader is not closed properly
affectsVersions:1.1.1;1.2
https://issues.apache.org/jira/projects/LOGGING/issues/LOGGING-163?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by axelfontaine** [comment]
Please don't spam the issue tracker with this. Not interested.
