### ISSUE TITLE
Machine-readable Flyway Info

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2254]
It would be nice to be able to specify a format for `Flyway Info` (i.e JSON).

**Comment by axelfontaine** [comment]
What exactly is your usecase for this? Please describe in detail.

**Comment by molexx** [comment]
We'd like to find out the currently deployed version in a gradle build, please consider a specific field for that to save looping/parsing.

It might also be useful to know the latest version available, I appreciate we could work this out by listing a directory and applying a regex and sorting but I'd rather defer to flyway's algorithm on that.

**Comment by juliahayward** [comment]
Would you be open to a pull request for JSON-formatting the output of `info` ?

**Comment by axelfontaine** [comment]
@juliahayward Not at this time. This is a feature we want to revisit after the 6.0 release and analyse how it could be generalised to all commands instead of making it specific to info.

**Comment by MikielAgutu** [comment]
At the moment Info doesn't give all the information in the schema history table. As part of this work exposing all the information in the table might be valuable for some users.

**Comment by juliahayward** [comment]
Implemented for `flyway info` in 6.1.0. Please open new issues for any extensions to other commands.

**Comment by esauser** [comment]
@juliahayward can you reference and pull requests, commits, or documentation for how this will be implemented?
