### ISSUE TITLE
ERROR: Validate failed: Migration checksum mismatch for migration

### ISSUE THREAD

**Issue by CayoM** [flyway/flyway#2255]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 5.2.4 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

10.1.37-MariaDB

###### Which operating system are you using?

Im using Docker images only

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?

Successfull or already migrated

###### What did you see instead?

```
Flyway Community Edition 5.2.4 by Boxfuse
Database: jdbc:mysql://mariadb-svc.xxx.xxx:3306/mydb (MySQL 5.5)
ERROR: Validate failed: Migration checksum mismatch for migration version 1.8
-> Applied to database : 2047647734
-> Resolved locally    : -1572553709
```

###### Additional Information
this bug feels like Issue https://github.com/flyway/flyway/issues/2027... maybe is the same error, which came back? At least, when i switch to image boxfuse/flyway:5.1.1 the error doesn't show up... with the latest boxfuse/flyway(:latest) im not successful.

**Comment by axelfontaine** [comment]
Please share a small repo that reproduces this issue.

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by buche2** [comment]
i have fixed this error by write an statement as last in the V1 init script:
delete from flyway_schema_history where installed_rank = 1;

the reason for this is flyway make twice entries for Version 1 migration script and the first entry will produce the exception:
+----------------+---------+-------------+------+-------------------+-----------+--------------+---------------------+----------------+---------+
| installed_rank | version | description | type | script            | checksum  | installed_by | installed_on        | execution_time | success |
+----------------+---------+-------------+------+-------------------+-----------+--------------+---------------------+----------------+---------+
|              1 | 1       | Init        | SQL  | V1__Init.sql      |         0 | root         | 2019-05-11 12:03:44 |              2 |       1 |
|              2 | 1       | Init        | SQL  | V1__Init.sql      | 262691744 | root         | 2019-06-15 11:06:04 |            187 |       1 |

**Comment by ajmerhasan** [comment]
i put this line in my property file and seems to be okay:
spring.flyway.validate-on-migrate=false

**Comment by ajmerhasan** [comment]
i put this line in my property file and seems to be okay:
spring.flyway.validate-on-migrate=false

**Comment by ajmerhasan** [comment]
i put this line in my property file and seems to be okay:
spring.flyway.validate-on-migrate=false
