### ISSUE TITLE
Flyway Test

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2256]
I'm proposing a new command, `Flyway Test`.  In addition to using Flyway for migrations, we are also using it for tests.  As-is, Flyway works great for this, with a one simple caveat: we need the tests to run after all migrations.  Thus we are writing them all as repeatable migrations, prefixed with `z_` to ensure they always go last.  If a new command was created for this, there could simply be another naming convention to always have them go laster.  For example, `T__` instead of `V#__` or `R__`.

A behavior change that would be nice for this command would be that it will continue running migrations even if it encounters an error.  This way all failed tests can be identified instead of just the first one.  This was the crux of #2179.  I agree this wouldn't be good within the existing `Flyway Migrate` command, but if we had a new command, maybe it would be acceptable.

I'm sure there is a lot more that could go into this if we were to start building a test runner/framework, but this would be a start for the way we are currently using it.  Everything else about the current `Flyway Migrate` command works great for us.  For additional context, all of our tests are native SQL queries, generally executing stored procedures and asserting.

**Comment by esauser** [comment]
@axelfontaine apologies on the template... it didn't really seem valid for this kind of issue.  We're using various versions and editions of MSSQL.  The test examples below are from MSSQL 2014 Enterprise.  They vary dramatically.  Here are a few examples.  If you'd like to see a lot of them I can push up a repo.

1. Simply executing a stored procedure.  By having this in our pipeline, we can guarantee the schema upon which the stored procedure depends is not removed.  ```EXEC dbo.DIS_rpt_GetTripStop @TriID = 0```

2. Taking it one step further to validate the schema returned by a stored procedure.  There are also test data migrations that populate data for this test. ```DECLARE @TestTable TABLE
(
    [SumTotalExportQueueID] INT,
    [LastName] VARCHAR(50),
    [FirstName] VARCHAR(50),
    [MiddleInitial] VARCHAR(1),
    [EmployeeID] VARCHAR(6),
    [LocationType] VARCHAR(19),
    [LocationTypeGroupIsDefault] INT,
    [IsRetailLocationType] INT,
    [RegionCode] VARCHAR(10),
    [RegionGroup] VARCHAR(50),
    [RegionGroupIsDefault] INT,
    [DistrictCode] VARCHAR(12),
    [DistrictGroup] VARCHAR(50),
    [DistrictGroupIsDefault] INT,
    [LocationCode] VARCHAR(7),
    [LocationGroup] VARCHAR(58),
    [LocationGroupIsDefault] INT,
    [DepartmentCode] VARCHAR(11),
    [DepartmentGroup] VARCHAR(58),
    [DepartmentGroupIsDefault] INT,
    [LocationName] VARCHAR(50),
    [Region] VARCHAR(50),
    [District] VARCHAR(50),
    [Location] VARCHAR(50),
    [UserLocationCode] INT,
    [Department] VARCHAR(54),
    [Position] VARCHAR(55),
    [WorkStatus] VARCHAR(2),
    [StoreState] VARCHAR(2),
    [AdditionalRole] VARCHAR(10),
    [StatusCode] VARCHAR(8)
);

INSERT INTO @TestTable
(
    SumTotalExportQueueID,
    LastName,
    FirstName,
    MiddleInitial,
    EmployeeID,
    LocationType,
    LocationTypeGroupIsDefault,
    IsRetailLocationType,
    RegionCode,
    RegionGroup,
    RegionGroupIsDefault,
    DistrictCode,
    DistrictGroup,
    DistrictGroupIsDefault,
    LocationCode,
    LocationGroup,
    LocationGroupIsDefault,
    DepartmentCode,
    DepartmentGroup,
    DepartmentGroupIsDefault,
    LocationName,
    Region,
    District,
    Location,
    UserLocationCode,
    Department,
    Position,
    WorkStatus,
    StoreState,
    AdditionalRole,
    StatusCode
)
EXEC dbo.STO_stp_GetUserData;```

3. Validating the schema of a table can accept the expected data.```SET XACT_ABORT ON;
BEGIN TRANSACTION;

INSERT INTO dbo.SEN_ExecutionImagesMap
(
    eim_excID,
    eim_ImageName,
    eim_UploadedDatetime
)
VALUES
(ROUND(RAND() * 2147483647, 0), CONCAT('https://', NEWID(), '.png'), GETDATE());

SELECT eim_eimID,
       eim_excID,
       eim_ImageName,
       eim_UploadedDatetime
FROM dbo.SEN_ExecutionImagesMap;

ROLLBACK TRANSACTION;
SET XACT_ABORT OFF;```

4. Validating a user has `SELECT` permission to tables```EXECUTE AS USER = '${aisles_online_api_accountname}'
GO

select top 1 * from [dbo].[OGS_SpecialDietItemLink]
select top 1 * from [dbo].[OGS_SavingsItemLink]
select top 1 * from [dbo].[OGS_Savings]
select top 1 * from [dbo].[OGS_SizeDetail]
select top 1 * from [dbo].[OGS_Agreement]
select top 1 * from [dbo].[OGS_AgreementType]
select top 1 * from [dbo].[OGS_AgreementTracking]
select top 1 * from [dbo].[OGS_FulfillmentFeeTier]
select top 1 * from [dbo].[OGS_FulfillmentSchedule]
select top 1 * from [dbo].[OGS_FulfillmentScheduleTimeSlotLink]
select top 1 * from [dbo].[OGS_FulfillmentScheduleTimeSlot]
select top 1 * from [dbo].[OGS_CartPromotion]
select top 1 * from [dbo].[OGS_OrderPromoType]
select top 1 * from [dbo].[OGS_OrderPromo]

GO
REVERT
```

**Comment by esauser** [comment]
We'd also want it to run the tests every time instead of checking if they changed like it does currently for repeatable migrations.

**Comment by axelfontaine** [comment]
Please keep the ideas coming. Here is my current understanding/vision for this:

- new prefix: `T`
- new command: `test`
- all scripts are run in potentially random order with every invocation
- scripts completes without error = pass, script throws an error = fail
- each script is run within a transaction which is automatically rolled back when the script finishes, regardless of the result

**Comment by esauser** [comment]
Yes, I'm sure there are also a lot more nuances to it that we'll want.  I think we should also have the errors reported differently.  Currently, the entire migration is displayed.  If 10 lengthy tests failed this would be really difficult to parse.  Just the file that failed and the exception information would probably suffice.

**Comment by SpokeyWheeler** [comment]
Yeah, this sounds good.

**Comment by LowlyDBA** [comment]
One could leverage tSQLt in conjunction with this for more advanced features / pretty results summarizing as well.

**Comment by esauser** [comment]
@LowlyDBA we specifically don't use `tSQLt` because it makes a lot of assumptions on the host environment and only supports MSSQL.

**Comment by MikielAgutu** [comment]
We think this is beyond Flyway's scope.
