### ISSUE TITLE
SqlPlus Set Define off

### ISSUE THREAD

**Issue by pjchester** [flyway/flyway#2257]
###### Which version and edition of Flyway are you using?

5.2.4 Enterprise

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?

Oracle 12.1

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

command: flyway -enterprise migrate 
script being migrated is an Oracle Apex application that is exported as an sql file.
Unable to import as the set define off statement not processed (see also #2210)  

###### What did you expect to see?

That set define off would be processed.  However issue may also relate to "whenever sqlerror" 

###### What did you see instead?
Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration v7.1.0.65__f1000.sql failed
-------------------------------------
SQL State  : 42000
Error Code : 922
Message    : ORA-00922: missing or invalid option
Location   : db/migration/oracle/7.1/v7.1.0.65__f1000.sql (/data/jenkins/jobs/connect-database-deployment/workspace/db2/build/dbdeploy/db2/bin/file:/data/jenkins/jobs/connect-database-deployment/workspace/db2/build/dbdeploy/db2/lib/db2-7.0.0.jar!/db/migration/oracle/7.1/v7.1.0.65__f1000.sql)
Line       : 1
Statement  : set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback

**Comment by axelfontaine** [comment]
Did you set `oracle.sqlplus` to `true` as stated in the [docs](https://flywaydb.org/documentation/database/oracle#sqlplus-commands)?

**Comment by axelfontaine** [comment]
Any news?

**Comment by pjchester** [comment]
Hi Alex

My humble apologies for taking so long to come back to you, especially as you responded so promptly.

We’ve been trying various tests within our Jenkins build set up to try and isolate the problem.  We are definitely going ahead with an order for the Enterprise version (it should come through as Deutsche Post / DHL) but we can not get the Oracle Apex applications to load without the “&” placeholder error.

We have set sqlplus enabled, but it looks like the set define off is still being ignored.  We use placeholders elsewhere, so we can not globally turn placeholders off.   It looks like Flyway is still setting define on – see highlighted line below:-


public String replacePlaceholders(String input)
/*     */   {
/* 130 */     String result = this.placeholderReplacer.replacePlaceholders(input);
/* 131 */     if ((this.oracleSqlplus) && (this.defineOn)) {
/* 132 */       boolean replaced = false;
/*     */
/* 134 */       Map<String, String> placeholders = getPlaceholderReplacements();
/* 135 */       Set<String> unmatchedPlaceHolderExpressions = new TreeSet();
/*     */       for (;;) {
/* 137 */         Matcher matcher = this.anyPlaceholderPattern.matcher(result);
/* 138 */         if (!matcher.find()) break;
/* 139 */         String searchTerm = matcher.group(3).toLowerCase(Locale.ENGLISH);
/* 140 */         if (!placeholders.containsKey(searchTerm)) {
/* 141 */           unmatchedPlaceHolderExpressions.add(matcher.group(1));
/* 142 */           result = StringUtils.replace(result, matcher.group(1), "");
/*     */         } else {
/* 144 */           result = StringUtils.replace(result, matcher.group(2), (String)placeholders.get(searchTerm));
/* 145 */           replaced = true;
/*     */         }
/*     */       }
/*     */
/*     */
/*     */
/*     */
/* 152 */       if (!unmatchedPlaceHolderExpressions.isEmpty())
/*     */       {
/* 154 */         throw new FlywayException("No value provided for placeholder expressions: " + StringUtils.collectionToCommaDelimitedString(unmatchedPlaceHolderExpressions) + ".  Check your configuration!");
/*     */       }
/*     */
/*     */
/* 158 */       if (this.escapeOn) {
/* 159 */         result = StringUtils.replace(result, "" + this.escapeChar + this.defineChar, "" + this.defineChar);
/*     */       }
/*     */
/* 162 */       if ((replaced) && (this.verifyOn)) {
/* 163 */         LOG.info("old   1: " + input.trim());
/* 164 */         LOG.info("new   1: " + result.trim());
/*     */       }
/*     */     }

Tried testing for capital vs lower case:-

       List<String> allTokens = tokenizeToStringCollection("SET DEFINE OFF VERIFY OFF FEEDBACK OFF", ' ', '"');
       System.out.println(allTokens);
       /*  52 */     int pos = 1;
       while (pos < allTokens.size()) {
              /*  59 */       if (tokenMatches(allTokens, pos, "DEF(INE)?")) {
              /*  82 */         pos++;
              /*  83 */         if (tokenEquals(allTokens, pos, "ON")) {
              /*  84 */           System.out.println("sqlPlusPlaceholderReplacer.setDefineOn(true)");
              /*  85 */           System.out.println("sqlPlusPlaceholderReplacer.setDefineChar('&')");
              /*  86 */         } else if (tokenEquals(allTokens, pos, "OFF")) {
                                         System.out.println("sqlPlusPlaceholderReplacer.setDefineOn(false)");
              /*  88 */         } else if (tokenMatches(allTokens, pos, "[^A-Z0-9 ]")) {
                     /*  84 */           System.out.println("sqlPlusPlaceholderReplacer.setDefineOn(true)");
              /*  90 */
              /*     */         } else {
              /*  92 */           throw new Exception("Missing argument for SET DEFINE");
              /*     */         }
              /*  94 */       } else if (tokenMatches(allTokens, pos, "FEED(BACK)?")) {
              /* 106 */         pos++;
              /* 107 */         if (tokenEquals(allTokens, pos, "ON")) {
              /* 108 */           System.out.println("this.feedback = Integer.valueOf(1)");
              /* 109 */         } else if (tokenEquals(allTokens, pos, "OFF")) {
              /* 110 */           System.out.println("this.feedback = Integer.valueOf(0)");
              /* 111 */         } else if (tokenMatches(allTokens, pos, "[0-9]{1-5}")) {
              /* 112 */           System.out.println("this.feedback = Integer.valueOf(Integer.parseInt((String)allTokens.get(pos)))");
              /*     */         } else {
              /* 114 */           throw new Exception("SP2-0267: feedback option " + "" + " out of range (0 through 50000)");
              /*     */         }
              /* 116 */       }
                                                else if (tokenMatches(allTokens, pos, "VER(IFY)?")) {
              /* 153 */         pos++;
              /* 154 */         if (tokenEquals(allTokens, pos, "ON")) {
              /* 155 */           System.out.println("sqlPlusPlaceholderReplacer.setVerifyOn(true);");
              /* 156 */         } else if (tokenEquals(allTokens, pos, "OFF")) {
              /* 157 */           System.out.println("sqlPlusPlaceholderReplacer.setVerifyOn(false);");
              /*     */         } else {
              /* 159 */           throw new Exception("SP2-0265: verify must be set ON or OFF");
              /*     */         }
              /*     */       } else {}
              /* 164 */       pos++;
              /*     */     }

But no joy so far.

Any ideas?

Regards

Paul

**Comment by axelfontaine** [comment]
Could you post a small SQL snippet that triggers this?

**Comment by pjchester** [comment]
The initial lines in the sql file are detailed, followed by a sample of lines that will fail on "&AI_FACILITY_IATA_CODE."

set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- ORACLE Application Express (APEX) export file
--
-- You should run the script connected to SQL*Plus as the Oracle user
-- APEX_050000 or as the owner (parsing schema) of the application.
--
-- NOTE: Calls to apex_application_install override the defaults below.
--
--------------------------------------------------------------------------------
begin
wwv_flow_api.import_begin (
 p_version_yyyy_mm_dd=>'2013.01.01'
,p_release=>'5.0.3.00.03'
,p_default_workspace_id=>2584408971928550
,p_default_application_id=>1000
,p_default_owner=>'CONNECT_RECEIVING_USER'
);
end;
/
prompt --application/set_environment
prompt APPLICATION 1000 - Receiving
--
-- Application Export:
--   Application:     1000
--   Name:            Receiving
--   Date and Time:   10:10 Friday January 25, 2019
--   Exported By:     PAUL
--   Flashback:       0
--   Export Type:     Application Export
--   Version:         5.0.3.00.03
--   Instance ID:     61826445038635
--


prompt --application/create_application
begin
wwv_flow_api.create_flow(
 p_id=>wwv_flow.g_flow_id
,p_display_id=>nvl(wwv_flow_application_install.get_application_id,1000)
,p_owner=>nvl(wwv_flow_application_install.get_schema,'CONNECT_RECEIVING_USER')
,p_name=>nvl(wwv_flow_application_install.get_application_name,'Receiving')
,p_alias=>nvl(wwv_flow_application_install.get_application_alias,'RECEIVING')
,p_page_view_logging=>'YES'
,p_page_protection_enabled_y_n=>'Y'
,p_checksum_salt_last_reset=>'20190124213837'
,p_bookmark_checksum_function=>'MD5'
,p_compatibility_mode=>'4.2'
,p_flow_language=>'en'
,p_flow_language_derived_from=>'ITEM_PREFERENCE'
,p_date_format=>'dd-Mon-yyyy'
,p_date_time_format=>'dd-Mon-yyyy hh24:mi'
,p_timestamp_format=>'dd-Mon-yyyy hh24.mi'
,p_flow_image_prefix => nvl(wwv_flow_application_install.get_image_prefix,'')
,p_authentication=>'PLUGIN'
,p_authentication_id=>wwv_flow_api.id(117991098724436888)
,p_application_tab_set=>0
,p_logo_image=>'#IMAGE_PREFIX#themes/dhlgmtheme/images/dhl_rgb_cr.png'
,p_logo_image_attributes=>'style="width:235px; height:24px;"'
,p_public_user=>'APEX_PUBLIC_USER'
,p_proxy_server=> nvl(wwv_flow_application_install.get_proxy,'')
,p_flow_version=>'2019.025'
,p_flow_status=>'AVAILABLE_W_EDIT_LINK'
,p_flow_unavailable_text=>'This application is currently unavailable at this time.'
,p_exact_substitutions_only=>'Y'
,p_browser_cache=>'N'
,p_browser_frame=>'D'
,p_deep_linking=>'Y'
,p_http_response_headers=>wwv_flow_utilities.join(wwv_flow_t_varchar2(
'Cache-Control: no-cache, no-store, max-age=0, must-revalidate',
'X-XSS-Protection: 1; mode=block',
'X-DNS-Prefetch-Control: off',
'X-Content-Type-Options: nosniff'))
,p_runtime_api_usage=>'T:O:W'
,p_rejoin_existing_sessions=>'P'
,p_csv_encoding=>'Y'
,p_auto_time_zone=>'N'
,p_error_handling_function=>'CONNECT_RECEIVING.CR_ERROR_MSG_LOOKUP.PROC_ERR_MSG_FETCH'
,p_substitution_string_01=>'SUB_APPLICATION_NAME'
,p_substitution_value_01=>'Receiving'
,p_substitution_string_02=>'ITEM_RIGHT_OF_USER_NAME'
,p_substitution_value_02=>'&AI_FACILITY_IATA_CODE.'
,p_substitution_string_03=>'APP_FAVICONS'
,p_substitution_value_03=>'<link rel="icon" sizes="16x16" href="#IMAGE_PREFIX#themes/dhlgmtheme/images/receiving_favicon.png"><link rel="icon" sizes="32x32" href="#IMAGE_PREFIX#themes/dhlgmtheme/images/receiving_favicon.png"> <link rel="shortcut icon" href="#IMAGE_PREFIX#theme'
||'s/dhlgmtheme/images/receiving_favicon.png">'
,p_substitution_string_04=>'DEFAULT_DELETE_CONFIRM_MESSAGE'
,p_substitution_value_04=>'Do you wish to delete the selected item?'
,p_last_updated_by=>'PAUL'
,p_last_upd_yyyymmddhh24miss=>'20190124213837'
,p_file_prefix => nvl(wwv_flow_application_install.get_static_app_file_prefix,'')
,p_files_version=>15
,p_ui_type_name => null
);
end;
/

**Comment by axelfontaine** [comment]
Thanks for the snippet. This has now been fixed thanks to a major parser rewrite for 6.0 in combination with adding support for `SQL.SQLCODE` to `WHENEVER SQLERROR` (#2302).

**Comment by sambekar** [comment]
@axelfontaine When is this targeted to be released?

**Comment by axelfontaine** [comment]
@sambekar It's already out as part of 6.0.0-beta.

**Comment by mrmarathe** [comment]
Is this issue resolved. I am still getting the same error in flyway 6.5.0
