### ISSUE TITLE
Flyway migration fails in MaxScale environment

### ISSUE THREAD

**Issue by jtmuhone** [flyway/flyway#2258]
###### Which version and edition of Flyway are you using?

5.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

MariaDB 10.3.7 + MaxScale  2.1.13

###### Which operating system are you using?

Centos 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Run flyway migration.

###### What did you expect to see?

A successful migration.

###### What did you see instead?

Migration fails, error message is:

    Unable to restore connection to its original state
    SQL State  : 42000
    Error Code : 1142
    Message    : (conn=16427) SELECT command denied to user 
    '*******'@'********' for table 'user_variables_by_thread'

This happens because in MaxScale DatabaseMetaData.getDatabaseProductVersion() returns "10.0.0 2.1.13-maxscale" and does not contain "MariaDB". Thus org.flywaydb.core.internal.database.mysql.MySQLDatabase resolves that the database is MySQL and has org.flywaydb.core.internal.database.mysql.MySQLConnection tries to use performance_schema -table.

**Comment by axelfontaine** [comment]
Hmm interesting. Do you happen to know a more reliable query to distinguish MySQL from MariaDB?

**Comment by jtmuhone** [comment]
> Hmm interesting. Do you happen to know a more reliable query to distinguish MySQL from MariaDB?

At least `SELECT VERSION();` returns "10.3.7-MariaDB-log" in our MariaDB MaxScale environment and something like "5.0.96-standard" in MySQL.

**Comment by axelfontaine** [comment]
The MariaDB JDBC driver 2.4.0 and newer should automatically work now with Flyway 6.0.0-beta2 or newer.
