### ISSUE TITLE
Callback output doesn't match execution order

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2260]
###### Which version and edition of Flyway are you using?
5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Created a `beforeEachMigrate` and `afterEachMigrate` SQL callback and ran `Flyway Migrate` with a pending migration.

###### What did you expect to see?
I expected to see no feedback about the callback or for the `before` to output before the migration and the `after` to output after the migration.

###### What did you see instead?
Both came after the migration.
![image](https://user-images.githubusercontent.com/24945592/51053010-fe2e3280-159d-11e9-8e59-6ccb9ff27287.png)

Despite the display, they _do_ execute in the correct order and perform as expected.

Also, the list for every migration.  As you know from #2256, we are using Flyway to execute tests.  We just added this to wrap each of them in a transaction (per our on-going conversation) and now the output has tripped with all of these entries.  It also would be nice if these were just listed once globally at the top instead of every time.

**Comment by axelfontaine** [comment]
Thanks for reporting. Could you share your `flyway.conf` file (no database url, user or password)?

**Comment by esauser** [comment]
[flyway.txt](https://github.com/flyway/flyway/files/2767037/flyway.txt)

The following environment variables are also set:
- FLYWAY_VALIDATE_ON_MIGRATE: false
- FLYWAY_LOCATIONS: filesystem:test
- FLYWAY_GROUP: true

**Comment by axelfontaine** [comment]
The order was indeed not very logical from an outsider's perspective. We have now adjusted to more closely match the user mental model.
