### ISSUE TITLE
Include RDS certificate by default

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#2261]
Currently connecting to an AWS RDS database securely is more difficult than it should be and requires manually adding AWS' certificate to your truststore. See https://joaorosa.io/2019/01/13/using-flyway-and-gitlab-to-deploy-a-mysql-database-to-aws-rds-securely/

Flyway should detect RDS URLs and automatically use the certificate if necessary.

**Comment by MikielAgutu** [comment]
CLI is an obvious feature to add. For Maven and Gradle we will do more investigation.

**Comment by juliahayward** [comment]
We're going to document the use of SSL for now. It appears to go well beyond the scope of Flyway itself.
