### ISSUE TITLE
DatabaseFactory class opens the jdbc conection when calling createDatabase method but never close it

### ISSUE THREAD

**Issue by dmtran25** [flyway/flyway#2262]
###### Which version and edition of Flyway are you using?
5.1.14

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
It's same issue for 5.2.4, the sources are exactly the same in DatabaseFactory and Database classes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Oracle but it does not matter

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Using DatabaseFactory for creating Database class

###### What did you expect to see?
The mainJdbcConnection opened by DatabaseFactory must be closed by Database when the method close of Database is called

###### What did you see instead?
The connection mainJdbcConnection is not closed
To close it when calling Database.close method, the workaround is to use Database.useSingleConnection() and call the method Database.getMainConnection which assign mainJdbcConnection to mainConnection

**Comment by axelfontaine** [comment]
This works as designed. This internal API is called at the appropriate places and no connections leak. It is not intended for outside consumption.
