### ISSUE TITLE
Oracle: cleaning type fails with object does not exist

### ISSUE THREAD

**Issue by jutoft** [flyway/flyway#2263]
The type is created like this:
CREATE TYPE XXX AS VARRAY(1000) OF VARCHAR2(512)

The issue have started after we did this:
alter type XXX modify limit 100000 cascade

###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
We use oracle 12.1 so i am unable to test on latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
Oracle Enterprise 12.1

###### Which operating system are you using?
Flyway: Windows
Oracle: Unknown

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway clean

###### What did you expect to see?
An empty schema.

###### What did you see instead?
Failing to delete a type, and dropping out with some types left behind.

**Comment by axelfontaine** [comment]
Thanks for reporting. Fixed.
