### ISSUE TITLE
Flyway does not clean sequences in MariaDB

### ISSUE THREAD

**Issue by jankoh** [flyway/flyway#2266]
###### Which version and edition of Flyway are you using?

5.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

gradle client; gradle 4.10.2

###### Which database are you using (type & version)?

MariaDB, version 10.3.12

###### Which operating system are you using?

Linux (Arch; Alpine)

###### What did you do?

- Create empty Database
- Run gradle flywayMigrate (database is filled according to the migration scripts)
- Run gralde flywayClean (database should be cleaned; end empty, as before)

###### What did you expect to see?

After Clean, the datebase should be empty again.

###### What did you see instead?

The datebase is empty, except for all the sequences created. Those remain and so a next run of flywayMigrate produces an error, and e manual clean is required.

**Comment by axelfontaine** [comment]
Please share a small SQL script that triggers this behavior.

**Comment by axelfontaine** [comment]
Thanks for reporting and providing the small sample SQL. Fixed.
