### ISSUE TITLE
Allow Callbacks to be Scoped to Specific Migrations

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2268]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
`flyway migrate` with some `afterEachMigrate` and `beforeEachMigrate` SQL callbacks nested within `locations`.

###### What did you expect to see?
I was hoping the callbacks would only apply to the migrations at and below the location containing the callbacks.

###### What did you see instead?
The callbacks applied to all migrations

As part of #2256 we created a `beforeEachMigrate` callback to
```
SAVE TRANSACTION testWrapper
```
and an `afterEachMigrate` callback to
```
ROLLBACK TRANSACTION testWrapper
```
so that we can automatically rollback all tests.  This works great in the pipeline because we can specify different `locations` for the test job, but when developers are working locally they are required to first `flyway migrate` the migrations and then `flyway migrate` again for the tests.

I am proposing a feature to either only apply callbacks at the directory containing them and below or a way to specify where to run them.

**Comment by axelfontaine** [comment]
You can already achieve this by placing callbacks in locations that are only included selectively.
