### ISSUE TITLE
Add Callback Similar to afterEachMigrate, but after writing to flyway_schema_history

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2269]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
`flyway migrate` with an `afterEachMigrate` that checks the `flyway_schema_history` table to see which migration was just executed and then carries out the appropriate action.

###### What did you expect to see?
I was hoping the migration after which the callback fired would already be in the `flyway_schema_history` table.

###### What did you see instead?
The migration after which the callback fired was not yet in the `flyway_schema_history` table.

This makes it impossible to take action based on the specific migration within the `afterEachMigrate` call back.  I'm proposing another callback we added to fire after that record is added.

**Comment by axelfontaine** [comment]
This table is internal to Flyway and you shouldn't be accessing it directly. You can achieve what you need using Java-based callbacks and the context's `getMigrationInfo()` method. Isn't that sufficient for your needs?

**Comment by esauser** [comment]
@axelfontaine that should work work, I was simply trying to avoid writing Java as I've never done it (but I've been in software development for 10 years, so it really shouldn't be a problem).  Can you confirm exactly where Flyway will load them from?  Is it only the `${FLYWAY_HOME}/jars` as indicated [here](https://stackoverflow.com/questions/47471894/execute-a-flyway-callback-in-command-line)?

Also... since you mentioned not accessing that table directly, I wanted to note that we are also querying it with the output from `Flyway Info` in order to determine the path to the migration.  Would you consider adding that to `Flyway Info` or making a switch to include it?  This somewhat goes long with #2254.

**Comment by esauser** [comment]
@axelfontaine are you able to answer my questions above?

> Can you confirm exactly where Flyway will load [Java-based callbacks] from? Is it only the ${FLYWAY_HOME}/jars as indicated here?

> Would you consider adding [the script path] to Flyway Info or making a switch to include it?

**Comment by axelfontaine** [comment]
> Can you confirm exactly where Flyway will load [Java-based callbacks] from? Is it only the ${FLYWAY_HOME}/jars as indicated here?

Yes

> Would you consider adding [the script path] to Flyway Info or making a switch to include it?

#2254 is definitely an avenue we will be exploring

**Comment by esauser** [comment]
@axelfontaine have you considered allowing to specify the `jars` directory?  Reason being is it's hard to share a repo that contains a custom callback when the directory can't be mapped.  Everyone would have to move it to their `FLYWAY_HOME`.

**Comment by axelfontaine** [comment]
That already exists. See https://flywaydb.org/documentation/commandline/migrate#jarDirs
