### ISSUE TITLE
Flyway clean - add possibility to exclude objects

### ISSUE THREAD

**Issue by johnny-lopez** [flyway/flyway#2271]
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using (type & version)?
Postgres 9.1

###### Which operating system are you using?
linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Tried to clean schema were some objects were created by other user (admin)

###### What did you expect to see?
I would like to have possibility to skip deletion of certain types (e.g. view, routines, etc) and/or specified objects (e.g TABLE_WITH_STATISTICS_1, VIEW_CREATED_BY_ADMIN_123, some_routine_that_can_not_be_deleted)

###### What did you see instead?
I got an error:
Unable to clean schema "my_schema"
-------------------------------
SQL State  : 42501
Error Code : 0
Message    : ERROR: must be owner of function my_schema.some_routine_created_by_admin

        at org.flywaydb.core.internal.database.Schema.clean(Schema.java:151)

**Comment by MikielAgutu** [comment]
You should be able to recreate objects from your migrations. Excluding things from clean is quite inconsistent with the workflow that Flyway encourages.
