### ISSUE TITLE
Flyway integration in Micronaut: clean schema

### ISSUE THREAD

**Issue by ilopmar** [flyway/flyway#2273]
###### Which version and edition of Flyway are you using?

5.2.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

Mysql 8.0.12

###### Which operating system are you using?

Linux

###### What did you do?

I'm working on Micronaut Flyway integration and a user opened an improvement (https://github.com/micronaut-projects/micronaut-configuration-flyway/issues/2) to be able to clean the schema before running the migrations. I worked on adding that option but I'm not sure about `cleanDisabled` property.
I've been debugging the execution of `migrate` method and no matter the value of that flag, the `clean` is never called. 
I've seen that the flag is checked but only when executing `clean`.
Can I assume that if I want to clean the schema before running the migration I need to do?
```java
flyway.clean();
flyway.migrate();
```

Or, in other word, `migrate` will never call `clean`?

If this is the case, then I can define a Micronaut configuration property to explicitly allow the users to clean the schema before running the migration.

Thanks!

**Comment by axelfontaine** [comment]
Feel free to implement as you wish.

Just be aware, that migrate may call clean if:
- `validateOnMigrate` is `true` (this is the default)
- `cleanDisabled` is `false` (this is the default)
- `cleanOnValidationError`has been explicitly set to `true`

and a migration's checksum has changed.

**Comment by ilopmar** [comment]
Now everything makes more sense to me. I just wanted to confirm that clean is not called by default in any case. I've tried setting the properties as you explained and manually modifying a migration and I've seen that clean is called. But, to this happen, as you mentioned, the user need to manually set `cleanOnValidationError` to `true`, so we're good with the defaults.

Thank you very much for the explanation! :+1:
