### ISSUE TITLE
Unable to override error S00011:15404

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2275]
###### Which version and edition of Flyway are you using?
5.2.4 Pro

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
[MSSQL 2017 Linux Docker Container](https://hub.docker.com/r/microsoft/mssql-server-linux):latest

###### Which operating system are you using?
[Linux Alpine](https://hub.docker.com/r/boxfuse/flyway):5.2.4-alpine

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
`flyway migrate` with a migration containing `EXECUTE AS USER = '[SOME DOMAIN USER]'` with the following errorOverrides:
```
 flyway.errorOverrides=S0001:15151:I,S0001:15401:I,S0011:15404:I
# S0001 - 15151: Cannot alter the login '', because it does not exist or you do not have permission.
# S0001 - 15401: Windows NT user or group '' not found. Check the name again.
# S00011 - 15404: Could not obtain information about Windows NT group/user '', error code 0x4bc.
```

###### What did you expect to see?
An informational message in regard to `S0011:15404`.

###### What did you see instead?
`ERROR: Invalid error override (should look like STATE:12345:W ): S00011:15404:I`

If I remove that error override I get that following
```
ERROR: Migration of schema [dbo] with repeatable migration [MIGRATION_NAME] failed! Changes successfully rolled back.
ERROR: 
Migration [MIGRATION_FILE] failed
-----------------------------------------------------------------------
SQL State  : S00011
Error Code : 15404
Message    : Could not obtain information about Windows NT group/user '[USER_NAME]', error code 0x4bc.
Location   : /flyway/sql/test/stored-procedures/R__z_dbo.[MIGRATION_FILE] (/flyway/sql/test/stored-procedures/[MIGRATION_FILE])
Line       : 1
Statement  : EXECUTE AS USER = '[USER_NAME]'
```

Domain users are [not yet supported](https://github.com/Microsoft/mssql-docker/issues/165) on Linux SQL so we are on a trial for PRO only to take advantage of this feature locally to see if it will allow us to ignore these errors locally.  For whatever reason, Flyway doesn't like this one.

**Comment by esauser** [comment]
> It is a 5 character SQL state
This needs to support at least 6 characters.
https://flywaydb.org/documentation/envvars#FLYWAY_ERROR_OVERRIDES

**Comment by axelfontaine** [comment]
Interesting! SQL State is actually [defined as 5 chars in the SQL standard](https://en.wikipedia.org/wiki/SQLSTATE).

Do you have a link to SQL Server docs where these 6 char variants are defined?

**Comment by axelfontaine** [comment]
Could you share a small SQL file that triggers this? I'd like to integrate this in our test suite.

**Comment by esauser** [comment]
@axelfontaine I'm able to reproduce it with any domain-like user.  The following will do it.

```
EXECUTE AS USER = 'DOMAIN/USER`
```

**Comment by esauser** [comment]
I see you added 6.0.0 as the milestone, when do you expect to release that?  I see 1/29 [here](https://github.com/flyway/flyway/milestone/19), but there are still 83 issues to go.  Will it be possible for us to extend our trial?  This is the only feature we were looking for in PRO.

**Comment by axelfontaine** [comment]
@esauser We don't expect 6.0 to be delayed too much, if at all. Whatever isn't ready will be pushed back to 6.1. Simply request a new trial key until then.

**Comment by axelfontaine** [comment]
We have now loosened the rules for this as a workaround. I still believe this is an issue in the Microsoft driver and have filed an issue with them as well to get this issue's root cause resolved eventually.
