### ISSUE TITLE
Suppress Select Output

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2276]
###### Which version and edition of Flyway are you using?
5.2.4 Pro

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
[MSSQL 2017 Linux Docker Container](https://hub.docker.com/r/microsoft/mssql-server-linux):latest

###### Which operating system are you using?
[Linux Alpine](https://hub.docker.com/r/boxfuse/flyway):5.2.4-alpine

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
`flyway migrate` with some migrations that `SELECT` data.

###### What did you expect to see?
No output in the console

###### What did you see instead?
Tons of output.  We upgraded from 5.1.4 Community to 5.2.4 Pro and now we see all this output.  We'd rather not see it.  Is there a way to suppress it?
![image](https://user-images.githubusercontent.com/24945592/51711327-60048880-1ff1-11e9-9425-31a4a46953c9.png)

**Comment by axelfontaine** [comment]
There is currently no way to suppress this (other than removing the SELECT statement). Added as feature request.

**Comment by esauser** [comment]
Ugh... the output from our tests is now massive and un-readable.  I see you added a milestone for 6.0.0.  A way to suppress this would be greatly appreciated.  We'll see if we can get by until this without suppressing all the `SELECT` statements into temporary tables or variables.

In normal migrations I wouldn't expect many, or any `SELECT` statements, but I'm sure you can see how there are lots of them in our tests.  Perhaps this is another aspect of #2256, to not show them by default.

**Comment by esauser** [comment]
@axelfontaine per the release notes, this was added in 5.0.0?  Note that we upgraded from 5.1.4 Community to 5.2.4 Pro (on the trial), so we were already above 5.0.0.  Is it one of the features that comes with Pro that doesn't come with Community?  If so, is that documented anywhere?

**Comment by esauser** [comment]
Ah... `Display query results`, that didn't catch my eye before.

Yes, that would work, might want to be a bit more descriptive with it though.  `outputQueryResults`.

As I've looked at this more, it's actually very problematic in our pipeline.  During PR Verify we execute all the migrations against a copy of production.  This behavior allows someone to view sensitive data simply by opening a PR that they otherwise wouldn't have access to.  I almost wonder if you should change the default to false and make people enable it.

**Comment by MikielAgutu** [comment]
Thanks for the feature request. This will be available in the v6 release.

**Comment by binarycoded** [comment]
Hey @MikielAgutu, is it possible that setting `outputQueryResults` to `false` will be allowed in the CE as well in the near future? For us the additional output is very annoying. Thanks & best regards!
