### ISSUE TITLE
Option to fail if schema does not exist

### ISSUE THREAD

**Issue by olib963** [flyway/flyway#2277]
###### Which version and edition of Flyway are you using?

5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

Postgres 9.6

###### Which operating system are you using?

Linux

### Request

Flyway will always try to create a schema as the current user on migrate. I want to separate the schema & permission control from the migrations of the data inside a schema. This allows for easy rotation of permissions and separation of concerns. There is currently a race condition around the running of flyway and the separate creation of the schema. I would like to:

- Have my flyway step continuously fail because the schema does not yet exist
- Create the schema and grant all permissions on that schema
- Flyway can now run with the passed user.

**Comment by axelfontaine** [comment]
Would passing `CREATE SCHEMA IF NOT EXISTS` to the `initSql` option do the trick for you?

**Comment by MikielAgutu** [comment]
@olib963 Any news?

**Comment by olib963** [comment]
@MikielAgutu Thank you, yes this solution seems to work. I don't think it's the most elegant but it absolutely works :D

**Comment by MikielAgutu** [comment]
@olib963 Yes, not particularity elegant I'm afraid 😅 However the new multi line config option feature can make it slightly less ugly: https://flywaydb.org/documentation/configfiles#structure.
