### ISSUE TITLE
afterMigrate : Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by lunky** [flyway/flyway#2278]
###### Which version and edition of Flyway are you using?
5.1.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I have reproduced in 5.2.4 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
Mysql 5.7.21

###### Which operating system are you using?
Windows / Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I have 12 (spring cloud) services which use the maven plugin to run migrations on startup - they seem to work fine - I frequently get a deadlock when the afterMigrate stage is run.

I started seeing this behavior when I split my afterMigrate.sql out to 10 sql files:
    afterMigrate__1-reference-data.sql
    afterMigrate__2-items.sql
    afterMigrate__3-retailers
.sql 
    ...
There's no loss of data, but when the afterMigrate scripts error out, the service fails to start.

The stacktrace : 

###### What did you expect to see?
no errors. After migrate scripts run, application startup successful

###### What did you see instead?
DB: Deadlock found when trying to get lock; try restarting transaction (SQL State: 40001 - Error Code: 1213) 
[error.txt](https://github.com/flyway/flyway/files/2796693/error.txt)

**Comment by axelfontaine** [comment]
Could you please share a small GitHub repo that clearly reproduces this and demonstrates that Flyway itself and not your SQL is at fault?

**Comment by lunky** [comment]
In my project it's not reliably reproducible - it happens frequently but not every time

**Comment by axelfontaine** [comment]
I am afraid that without any proof that Flyway is actually at fault here, we can't really do much. Please reopen if this changes.
