### ISSUE TITLE
Dry-run file contains statements with invalid syntax

### ISSUE THREAD

**Issue by asamonov** [flyway/flyway#2280]
###### Which version and edition of Flyway are you using?
Pro 5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
PostgeSQL 9.6.8

###### Which operating system are you using?
Linux,Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
1. Enable dry run mode (I use `FlywayConfigurationCustomizer` and call `FluentConfiguration.dryRunOutput`) 
2. Execute migration command

###### What did you expect to see?
 Dry run ready to execute via psql

###### What did you see instead?
See below, note `SELECT set_config('search_path', ?, false);` line - this is not a valid syntax - `?` is not expected.
```
---====================================
-- Flyway Dry Run (2019-01-25 19:57:24)
---====================================

SET ROLE 'postgres';
SET ROLE 'postgres';
SET ROLE 'postgres';

-- Executing: validate (with callbacks)
------------------------------------------------------------------------------------------
SET ROLE 'postgres';

-- Executing: migrate (with callbacks)
------------------------------------------------------------------------------------------
SET ROLE 'postgres';
SELECT set_config('search_path', ?, false);
```

**Comment by axelfontaine** [comment]
Thanks for the detailed report and analysis. This has now been fixed.
