### ISSUE TITLE
Sybase ASE: parsing error with double-quoted string literals

### ISSUE THREAD

**Issue by smrutikanta-cog** [flyway/flyway#2281]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Have not tried with the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command-line

###### Which database are you using (type & version)?

sybase-ase

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Flyway gives a syntax error for the sql where as the same sql works just fine in rabbit sql or any other tool which executes sql.

error msg:
ERROR: 
Migration V2.1__sp_sqlname.sql failed
------------------------------------------------
SQL State  : 42S22
Error Code : 207
Message    : Invalid column 
name'************************************************************************************'.

###### What did you expect to see?

Execute the sql without error

###### What did you see instead?
syntax error

Tried to change the encoding also. But that also does not seem to resolve the issue

**Comment by axelfontaine** [comment]
Please try again with the latest version. If that doesn't help please share the smallest possible SQL file that triggers this.

**Comment by smrutikanta-cog** [comment]
Thanks for getting back to me! sure I will try and let you know soon

**Comment by smrutikanta-cog** [comment]
Ran with the latest available version flyway-5.2.4
Still getting the same error
error msg:
ERROR:
Migration V2.1__sp_sqlname.sql failed
SQL State  : 42S22
Error Code : 207
Message    : Invalid column name '              '.
I commented out the earlier code block to see if the error goes away but it still errors out on another code block
So please help

**Comment by axelfontaine** [comment]
As I said: please share the smallest possible SQL file that triggers this.

**Comment by axelfontaine** [comment]
This has been automatically fixed as part of the big parser rewrite for Flyway 6.0.

**Comment by smrutikanta-cog** [comment]
Thanks for fixing this so quick
When will the image be available on dockerhub to pull?

**Comment by axelfontaine** [comment]
@smrutikanta-cog It's available now as 6.0.0-beta

**Comment by smrutikanta-cog** [comment]
my shop uses 15.7 version of Sybase which is no longer supported by the community version of Flyway and at this time they wont go for the enterprise version. Had they used the community version for sometime then they could have been inclined to use the enterprise version but now that is not an option

Thanks anyways for your response
