### ISSUE TITLE
sap hana flyway:clean global temporary table must be empty to drop

### ISSUE THREAD

**Issue by oj19** [flyway/flyway#2283]
flyway-maven-plugin 5.2.4
SAP HANA 2.0 SPS 3

mvn flyway:clean throwed exception: 
SAP DBTech JDBC: [7]: feature not supported: global temporary table must be empty to drop

should clean the db even if a global temporary table contains data

**Comment by oj19** [comment]
create global temporary table global_test (x decimal);
insert into global_test values(1);

**Comment by axelfontaine** [comment]
Hmmm I can't get this to fail. Can you double-check on your end? Tried with a 2017 version as well as the Docker store/saplabs/hanaexpress:2.00.033.00.20180925.2 image.

**Comment by axelfontaine** [comment]
Hmmm I am starting to think we should refrain from attempting to drop these altogether as they are automatically dropped once no more sessions are using them. What do you think?

**Comment by oj19** [comment]
Global temp tables are not dropped that way. Only local ones.
To tell you the truth, we've chosen not to use them (found other solution), so you may close this issue with "won't fix". I just wanted to have this fixed for others.
Hana's error message is not correct when the table is empty. They should change it. But that's not your problem. If I've known it earlier that hana says this even when the global temp table is empty, I wouldn't open this issue (I thought you write a truncate before drop and everybody is happy).
