### ISSUE TITLE
Flyway with OpenJDK

### ISSUE THREAD

**Issue by nkbysani** [flyway/flyway#2286]
###### Which version and edition of Flyway are you using?

flyway-4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

i Didn't try

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

Microsoft SQL Server 2012

###### Which operating system are you using?

Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I have installed "jre-8u161-windows-x64" and working flyway as expected , and now i have uninstalld jave and tried with OpendJDK . it didnt work.
Can you please guide.

###### What did you expect to see?

In my organization we are not suppose to install Java in PROD , so we are planning to go ahead with OpenJDK.

###### What did you see instead?
Getting unable to load derby-10.12.1.1.jar file error coming whereas i have sqlserver driver in place.

**Comment by axelfontaine** [comment]
There is no need to install Java. The current Flyway distribution ships with a private JRE that works out of the box. You can download it from here: https://flywaydb.org/documentation/commandline/#download-and-installation
