### ISSUE TITLE
DB2: Clean excludes views whose names end with _V

### ISSUE THREAD

**Issue by armondoortega** [flyway/flyway#2287]
When running clean on a DB2 database it was noticed that not all views were being dropped correctly. 

Looking into the code I found the following method and query:
```java
    private List<String> generateDropStatementsForViews() throws SQLException {
        String dropSeqGenQuery = "select TABNAME from SYSCAT.TABLES where TABSCHEMA = '" + name
                + "' and TABNAME NOT LIKE '%_V' and TYPE='V'";
           return buildDropStatements("DROP VIEW", dropSeqGenQuery);
    }
```
After validating with the [DB2 documention](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000751.html) on our the LIKE predicate works, I wanted to validate expected functionality of this query.

Currently this query will exclude any view that ends in 'V', so MY_TEST_V and MY_TEST_IDV will both be excluded.

Is this the intended functionality or was the intention to only exclude names that end in '_V'

We saw this functionality in Flyway 5.2.0 Enterprise Edition and validated the query from the master branch of the project.

**Comment by axelfontaine** [comment]
Thanks for reporting. This restriction used to be there in order to filter out the statistical view for an index with an expression-based key. We have now refined our query in order to avoid the side-effect you reported.
