### ISSUE TITLE
Java API tutorial on home page does not work out of the box due to h2 version

### ISSUE THREAD

**Issue by datacticapertti** [flyway/flyway#2290]
###### Which version and edition of Flyway are you using?

5.2.4 Community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

h2 1.3.170

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Followed the Java API First steps tutorial at https://flywaydb.org/getstarted/firststeps/api

###### What did you expect to see?

Working example.

###### What did you see instead?

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project bar: An exception occured while executing the Java class. Flyway Enterprise Edition or H2 upgrade required: H2 1.3.170 is past regular support by H2 and no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition. -> [Help 1]

Updating to h2 1.4.197 resolves this.

**Comment by axelfontaine** [comment]
Thank you very much for letting us know. Truly appreciated! Fixed.
