### ISSUE TITLE
org/flywaydb/maven/MigrateMojo : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by vkuntal** [flyway/flyway#2291]
###### Which version and edition of Flyway are you using?

flyway 5.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

NA

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

maven Plugin

###### Which database are you using (type & version)?

Oracle 12 C

###### Which operating system are you using?

Windows 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Hi team,

Everything was working fine till I was using flyway version 4.2.0. 
I upgraded the oracle version to 12C and I started using TNS alias for the connection URL. 
Since then I am getting this issue(org/flywaydb/maven/MigrateMojo : Unsupported major.minor version 52.0)

I read online it and to resolve this many had suggested to use a higher version.

My query is : 

What is the exact combination of verions of below would work:

1) Flyway
2) Maven
3) jdbc
4) JDK

currently I am using in the same sequence : 5.2.3, 3.0.0-M1, ojdbc6(12.9.9.9), jdk -8

Please let me know how can I resolve the issue.

@andrewlmurray @komu 

###### What did you expect to see?

Migration succesful

###### What did you see instead?
org/flywaydb/maven/MigrateMojo : Unsupported major.minor version 52.0

**Comment by axelfontaine** [comment]
Make sure that your Maven installation uses Java 8. Then everything will work as expected.

**Comment by vkuntal** [comment]
Hi @axelfontaine , 

Thanks for your input on this. Indeed that was a jdk issue, I improved the JDK version to 8 on both end and it worked fine.

Now I have another question I am pretty sure that is related with flyway version.

The version that I have mentioned above:

5.2.3, 3.0.0-M1, ojdbc6(12.9.9.9), jdk -8  --- it is giving me the error "No Matching Authentication Protocol"

I had to decrease the version of ojdbc6 jar to 1.1.1.1 and it worked with url containing (host:port/SID)

but it didn't work with tns alias name  for any ojdbc6 version.

Could you please let me know if there is anything that I can do to fix this.


I have a pom with above mentioned version and a install machine with ojdbc6 and jdk- 8 maven 3.0.4, oracle 12 where I am running the flyway script.

Thanks

**Comment by axelfontaine** [comment]
This issue tracker is for Flyway issues only and isn't a general support forum. Please post your question on StackOverflow where the community can answer it.
