### ISSUE TITLE
Virtual repositories issues with maven central and jcenter

### ISSUE THREAD

**Issue by rpalcolea** [flyway/flyway#2295]
###### Which version and edition of Flyway are you using?
5.1.4

###### What did you do?
Using range dependencies on gradle, for example:

```
    implementation 'org.flywaydb:flyway-core:[5.1.4,)'
```

Fails when using artifactory remote repositories.

We have a remote repository that mirrors maven central and jcenter. 

I noticed that maven central knows about 4.x and 5.x -> https://search.maven.org/search?q=g:org.flywaydb%20AND%20a:flyway-core&core=gav

But jcenter doesn't -> https://bintray.com/business/maven/org.flywaydb:flyway-core#files/org/flywaydb/flyway-core

Would it be possible to either publish newer versions to bintray or remove the existing ones to avoid conflicts with virtual repositories composed of multiple remote ones?

Example of maven-metadata.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>org.flywaydb</groupId>
  <artifactId>flyway-core</artifactId>
  <version>3.2.1</version>
  <versioning>
    <latest>3.2.1</latest>
    <release>3.2.1</release>
    <versions>
      <version>3.0</version>
      <version>3.1</version>
      <version>3.2</version>
      <version>3.2.1</version>
    </versions>
    <lastUpdated>20150322123103</lastUpdated>
  </versioning>
</metadata>
```

**Comment by rpalcolea** [comment]
Thoughts on this @axelfontaine?

**Comment by axelfontaine** [comment]
We have no plans to do either of these. This is probably an Artifactory issue more than anything else.

**Comment by DanielThomas** [comment]
This isn't an Artifactory issue. These artifacts were published to your bintray account - https://bintray.com/business. They're linked to JCenter which means they're the only versions available on JCenter, the Maven Central mirroring will never occur. 

This prevents any project that uses JCenter from using newer releases as as JCenter is a superset (i.e. Maven Central + Bintray linked artifacts) it isn't often impossible to switch.

**Comment by axelfontaine** [comment]
Considering both options, unpublishing on Bintray seems like the much better choice. How would this work in practice? What must be done after deleting the package on Bintray to reactivate the automatic sync?

**Comment by DanielThomas** [comment]
I _think_ the presence of the JCenter link will prevent the sync no matter what you do with the artifacts. Probably easiest to drop a line to Bintray support and ask them to do whatever they need to get it working.

We have an existing relationship with JFrog so let us know if you have any trouble getting in touch with them.

**Comment by juliahayward** [comment]
I've requested that JCenter remove the old artifacts and reinstate automatic proxying from Maven Central. Hopefully they will arrange that soon.

**Comment by magneticflux-** [comment]
It seems like this is still happening:
```
The following dependencies exceed the version found at the milestone revision level:
 - org.flywaydb:flyway-core [6.4.4 <- 3.2.1]
     http://flywaydb.org
```
I commented on the issue in a similar report here: https://github.com/flyway/flyway/issues/1635#issuecomment-673372156
