### ISSUE TITLE
FileSystemScanner scan for resources API changed docs didn't

### ISSUE THREAD

**Issue by karlroberts** [flyway/flyway#2296]
###### Which version and edition of Flyway are you using?
5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Mysql

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

FileSystemScanner.scanForResources() used to have 3 arguments 
location, prefix, and suffix. However it now just has location, yet the documentation says 

> "Scans the FileSystem for resources under the specified location, starting with the specified prefix and ending with the specified suffix."

Either add back the ability to search with prefix or suffix (which I need) or fix the doco and suggest how I can do the old behaviour

###### What did you expect to see?
compiled code

###### What did you see instead?
cant compile too many arguments.

**Comment by axelfontaine** [comment]
The docs have now been updated. The old behavior isn't coming back. This is internal API, don't depend on it.
