### ISSUE TITLE
Default placeholders

### ISSUE THREAD

**Issue by voronaam** [flyway/flyway#2297]
This is a feature request. We are using the Community version, but I think this is not available in the Pro version as well.

Would it be possible to add a few placeholders into the placeholder map dynamically?

This is similar to a request in https://github.com/flyway/flyway/issues/1082 but is a simpler feature.

I noticed that quite often we are following this pattern:

```
flyway {
    url = "jdbc:postgresql://${JDBC_HOST}:${JDBC_PORT}/${JDBC_DB}"
    user = "${JDBC_USER}"
    placeholders = [dbName: "${JDBC_DB}", dbUser: "${JDBC_USER}"]
}
```

And there was recently a request to have the patch's filename available as a placeholder replacement for SQL migration. This one we can not do with the current code.

Would it make sense to have additional placeholders such as `flyway.user` and `flyway.migration.filename`?

If you think it is a useful feature, I can write a Pull Request implementing it. If not, feel free to close this ticket.

Thank you for the great product.

**Comment by axelfontaine** [comment]
This is definitely an area we'll be looking at. It won't make the cutoff for 6.0, but we'll revisit it after.

**Comment by MikielAgutu** [comment]
We're currently doing the work to add default placeholders. We've started with the current schema name, but can certainly add more in time for the 6.1 release.

@voronaam Can you give us a list of the placeholders you'd like? Thanks.

**Comment by voronaam** [comment]
Thank you for working on it. I think those would be valuable:

```
flyway.user # current user
flyway.dbname # name of the DB
flyway.schema # current DB schema
flyway.operation # which operation is being executed
flyway.migration # name of patch or class (? - I am not sure if placeholders are used there, I have not used Java migrations that much, sorry)
flyway.driver # name of the driver/dialect - we have migrations that detect dialect first and alter the behavior a bit, could just as well base it on the value here
```

This are the ones I could think of. You may want to add more. Like, batch index when batching is used (we are on the community version, so I have not used that feature at all and do not know if it would be ever useful).

Of the list above I have a feeling I only need to explain `flyway.migration` a bit. I think it could be useful to know if the DB being seeded vs migrated. Because a lot of our migrations have logic to lock certain structures and validate they have the lock and retry - all to support on-the-fly migrations. But when DB is seeded, it is not on-the-fly yet and we could easily skip that part. This would make seeding new DBs faster for us.

**Comment by juliahayward** [comment]
Some placeholders added in the 6.1.0 release; I'm bumping this issue to 6.2 as more can be added.

**Comment by alextercete** [comment]
We'll consider the remaining placeholders in 6.2.0.

**Comment by juliahayward** [comment]
We feel the remaining placeholders are going to be more problematic than useful, but please do open new issues for new suggestions or discussion.
