### ISSUE TITLE
Unable to obtain connection from database (...) for user 'null': Access denied for user ''@'<IP>' (using password: YES)

### ISSUE THREAD

**Issue by Strum355** [flyway/flyway#2305]
###### Which version and edition of Flyway are you using?
5.2.4 Community Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using (type & version)?
MySQL 8.0.14 in Docker container

###### Which operating system are you using?
Antergos 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

CONSOLE OUTPUT
```
> Task :flywayMigrate FAILED
:flywayMigrate (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 30.373 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  
  Unable to obtain connection from database (jdbc:mysql://<REDACTED IP>:<PORT>/refund?verifyServerCertificate=false&useSSL=true) for user 'null': Access denied for user ''@'<REDACTED IP>' (using password: YES)
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  SQL State  : 28000
  Error Code : 1045
  Message    : Access denied for user ''@'<REDACTED IP>' (using password: YES)
  
  Access denied for user ''@'<REDACTED IP>' (using password: YES)
```

GRADLE FILE EXCERPT (NOTE both the username and `true` are printed, the values are right)
```groovy
def is_ci = props.getProperty("ssh.user") == "username"
println is_ci
println ((is_ci) ? System.getenv("MYSQL_USER") : mysql_user)

flyway {
    user = ((is_ci) ? System.getenv("MYSQL_USER") : mysql_user)
    url = ((is_ci) ? System.getenv("MYSQL_URL") : mysql_url)
    password = ((is_ci) ? System.getenv("MYSQL_PASS") : mysql_pass)
}
```

###### What did you expect to see?
I wouldve thought that the user wouldnt be null / `''` and that I'd be able to access the db

###### What did you see instead?
Above console output

**Comment by axelfontaine** [comment]
Please share a small repository with `build.gradle` and `docker-compose.yml` files that reproduce this issue.

**Comment by Strum355** [comment]
Issue has been resolved, issue was my lack of groovy knowledge.
I had a previously defined variable called `user` that mustve been messing with the flyway `user` variable. Just had to change the other `user` to something else and it was fine
