### ISSUE TITLE
docker run flyway fails

### ISSUE THREAD

**Issue by tcat2** [flyway/flyway#2306]
###### Which version and edition of Flyway are you using?
latest docker image

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which operating system are you using?
windows 10 pro 64x

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
commandline: docker run --rm boxfuse/flyway

###### What did you expect to see?
download of latest flyway docker image

###### What did you see instead?
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'

**Comment by axelfontaine** [comment]
Not a Flyway issue. Most likely an issue with your environment.
