### ISSUE TITLE
Clean requires flyway.table to be explicitly configured

### ISSUE THREAD

**Issue by sentinalll** [flyway/flyway#2309]
###### Which version and edition of Flyway are you using?

5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

In newer version fallback to old flyway.table is removed

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

Postgres 9.4

###### Which operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

When executing Flyway.clean() with default settings on shema that uses old 

> flyway.table=schema_version

it appears that flyway.table has to be explicitly specified when not default value is used.

###### What did you expect to see?

Clean is agnostic to the table where flyway migrations are stored.

###### What did you see instead?

Warning that
 `[WARNING] Could not find schema history table "public"."flyway_schema_history", but found "public"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.`

**Comment by axelfontaine** [comment]
This warning will automatically be removed when the fallback mechanism is removed as part of 6.0.0.
