### ISSUE TITLE
Error during migrate - MariaDB 10.1 isn't supported in CE

### ISSUE THREAD

**Issue by nitro2010** [flyway/flyway#2311]
###### Which version and edition of Flyway are you using?
6.0 beta

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Maria DB 10.1 from XAMPP Package Server

###### Which operating system are you using?
Windows 10 x64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Migrate tables to clear database.
It show me that migrate for MariaDB 10.1 is allows only for Pro Edition, 
on website: https://flywaydb.org/documentation/database/mariadb I see that 10.1 isn't selected only for Pro migrate ('Flyway Enterprise' sign).

###### What did you expect to see?
![image](https://user-images.githubusercontent.com/950663/53294754-35267380-37ed-11e9-98ca-29d076eaaeaf.png)

###### What did you see instead?
success in migrate

**Comment by axelfontaine** [comment]
The docs are indeed still for Flyway 5.2. Starting with Flyway 6.0, you will need to either upgrade MariaDB to 10.2 or newer or upgrade Flyway to Pro or Enterprise.
