### ISSUE TITLE
Wrong link for libjsig.so

### ISSUE THREAD

**Issue by indreek** [flyway/flyway#2312]
###### Which version and edition of Flyway are you using?
5.2.4
6.0.0 

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which operating system are you using?
Linux (Ubuntu 18)

###### What did you do?
untar downloaded archive

###### What did you expect to see?
/tmp/flyway-5.2.4/jre/lib/amd64/server/libjsig.so -> ../libjsig.so

###### What did you see instead?
/tmp/flyway-5.2.4/jre/lib/amd64/server/libjsig.so -> ..\libjsig.so

**Comment by indreek** [comment]
Example download:  https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.4/flyway-commandline-5.2.4-linux-x64.tar.gz

**Comment by axelfontaine** [comment]
Is that actually causing any issue in practice?

**Comment by indreek** [comment]
Actually I'm using it with npm, it is a submodule there and package faileas
at this file/link. Probably this submodule could be improved also but I
thought to let you know also.

Indrek

E, 25. veebruar 2019 19:10 Axel Fontaine <notifications@github.com>
kirjutas:

**Comment by axelfontaine** [comment]
This has automatically be fixed as part of the [upgrade to OpenJDK 11](#2357 )
