### ISSUE TITLE
DB2 create procedure (Java) fails 

### ISSUE THREAD

**Issue by djcru** [flyway/flyway#2315]
###### Which version and edition of Flyway are you using?
5.2.4, DB2 11.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line from Docker client(DB2 JCC4 driver) to DB2 server  

###### Which database are you using (type & version)?
DB2 v11.1

###### Which operating system are you using?
Linux (CentOS 7.6) 

###### What did you do?
All the the SQLs (~70) ran OK with one exception.  Creating a stored procedure:

```sql
CREATE OR REPLACE PROCEDURE "someschema"."some_sproc" (
IN STEREOTYPE      VARCHAR(50),
IN REFERENCE_KEY        VARCHAR(200),
IN VALUE                VARCHAR(6144),
..
IN DIMENSIONS           VARCHAR(32672),
IN PROPERTIES           VARCHAR(32672) )
LANGUAGE JAVA PARAMETER STYLE JAVA DYNAMIC RESULT SETS 0 EXTERNAL NAME 'somejar:someclass!somemethod';
```

###### What did you expect to see?
I expected a return code 0.  
If I take this file, as-is, move it to the db2 server and run it via the DB2 Command Line Processor, then it is successful.

###### What did you see instead?
1. as-is: sqlcode 20204 (unable to map to method in jar) 
2. made several attempts at 'escaping' characters on the EXTERNAL NAME specification (the single quote, the '!', doubling quotes, wrapping with " chars, etc.) - no luck. 

I found no DB2 documentation that precludes this statement from using via the JDBC type 4 driver. 

.. so is it possible that, somehow, the contents of the EXTERNAL NAME clause is getting mangled ?  Or perhaps there is magic way of recoding the command/instruction for Flyway (.. because we know the 'native' method works OK).  Thanks.

**Comment by axelfontaine** [comment]
Revisiting this now. Somehow I don't see how Flyway could be at fault here after all. It simply takes your statement and runs it. You can actually verify which statements it found by passing `-X` to produce debug output. Can you see the statement appear correctly?

**Comment by djcru** [comment]
Hi Axel,

Thanks for the reply.  It's been so long, I don't recall if I tried the -X.  

Our 'workaround', since our solution is Docker-based,  is to mount the directory with the SQL that creates the SP onto the database server and then run it locally.  Again, the identical SQL.  Curious...

I've got some other things to attend to, so it may be a couple of days before I can recreate/retry.

**Comment by axelfontaine** [comment]
Any news?

**Comment by MikielAgutu** [comment]
Closing due to lack of response.
