### ISSUE TITLE
Source code is oddly formatted

### ISSUE THREAD

**Issue by yissachar** [flyway/flyway#2316]
This is not a Flyway bug, but I noticed while browsing the source code that it is oddly formatted, with lots of extra white space inserted. Two examples out of many: [Example 1](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/resolver/sql/SqlMigrationResolver.java), [Example 2](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java).

Is there any reason for this? It makes the code difficult to read.

**Comment by axelfontaine** [comment]
This repository is being generated from our private master and doesn't contain the pro and enterprise edition code. Works as designed.
