### ISSUE TITLE
Invalid target version should stop execution

### ISSUE THREAD

**Issue by Me1gireesh** [flyway/flyway#2324]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Me1gireesh** [comment]
Hi, I'm using flyway 5.2.4 version and when an invalid target version ( a version which is not in the Flyway source path) , the validation doesn't tells you that, rather it executes the callback statements and also the ignored patches( since the outoforder is set as TRUE) . Shouldn't the execution stop, if there is an invalid Input Target passed in the miigrate command.

Eg: flyway -url="my_database_url" -user='PROCESS_CICD' -password='my_db_password' -target='20.0602.201903041324' migrate  -locations=filesystem:/my_file_location -enterprise 

The output says : 
flyway-5.2.4]$ flyway -url="my_database_url" -user='PROCESS_CICD' -password='my_db_password' -target='20.0602.201903041324' migrate  -locations=filesystem:/my_file_location -enterprise 
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
WARNING: You are using a 30 day limited Flyway trial license. After 30 days you must either upgrade to a full Flyway Enterprise Edition license or downgrade to Flyway Community Edition.
Database: jdbc:oracle:thin:@my_database_url (Oracle 12.1)
Successfully validated 7 migrations (execution time 00:00.193s)
Executing SQL callback: beforeMigrate
Current version of schema "PROCESS_CICD": 20.0502.201903041324
Schema "PROCESS_CICD" is up to date. No migration necessary.

**Comment by axelfontaine** [comment]
This actually works as designed. I am however not opposed to leave this open for further enhancement in the future.

**Comment by Me1gireesh** [comment]
This is becoming an issue as if we try to give an invalid version , the validation doesn't identify that , as well as it deploys all the versions before the invalid version automatically. :( 

Eg: if I have version 1,2,3 in the flyway patch and gives a version input as 2.1( which is an invalid version) , It deploys 1 and 2 and marks the database as Version 2. This issue needs to be addressed soon.

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
