### ISSUE TITLE
MariaDB Cluster

### ISSUE THREAD

**Issue by rcbensley** [flyway/flyway#2327]
###### Which version and edition of Flyway are you using?
4.1 and 5.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
Yes.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line.

###### Which database are you using (type & version)?
MariaDB Cluster 10.2, 10.3, 10.4.

###### Which operating system are you using?
CentOS 7.5

###### What did you do?
Simple migration from test.

###### What did you expect to see?
No locks.

###### What did you see instead?
This is a similar issue to #1556. MariaDB is not the same as MariaDB cluster, in that functions like GET_LOCK() are not supported, and bring a cluster to it's knees and blocks all writes.

Could we please have a configuration similar to Percona XtraDB cluster which uses the MariaDB Connector/J?

**Comment by axelfontaine** [comment]
Please fill in the full issue template. We have it for a reason.

Which version of Flyway are you using? Which version of MariaDB, exact error message, steps to reproduce, ...

**Comment by axelfontaine** [comment]
Thanks for updating the issue and sorry for not responding sooner. Somehow I didn't get a notification. Since you work for MariaDB, what Docker image would you recommend for testing a minimal Galera cluster?

**Comment by rcbensley** [comment]
Hi, no worries.

I recommend the officially maintained docker images, version 10.3. The 'latest' tag is currently 10.3, so that's just a 'docker pull mariadb'.

10.3 introduced a PLSQL parser, which I have noticed has had some small influences on schema design.

10.4 is going to be pretty wild and interesting with more online DDL operations, and more JSON functionality.

**Comment by axelfontaine** [comment]
@rcbensley How can they be configured to create a minimal 1 node Galera cluster?

**Comment by rcbensley** [comment]
Hi sorry for my delay this time, I shall get some dockerfile examples together. I haven't tried a single node yet.

**Comment by axelfontaine** [comment]
Any news?

**Comment by rcbensley** [comment]
Hi, yes, just trying to get a proper test working on a single node. Sorry for the delay.

**Comment by axelfontaine** [comment]
Perfect. Looking forward to it! (And to be honest this is probably something MariaDB should offer officially to make it easier to test this locally)

**Comment by rcbensley** [comment]
Hi, yes it is strange we don't provide docker recipes for Galera.

I came up with a simple single node cluster.

https://github.com/rcbensley/labs/tree/master/single

Some notes of limitations exist here:

https://mariadb.com/kb/en/library/mariadb-galera-cluster-known-limitations/

**Comment by rcbensley** [comment]
Hi, yes it is strange we don't provide docker recipes for Galera.

I came up with a simple single node cluster.

https://github.com/rcbensley/labs/tree/master/single

Some notes of limitations exist here:

https://mariadb.com/kb/en/library/mariadb-galera-cluster-known-limitations/

From Galera docs:

http://galeracluster.com/documentation-webpages/documentation/differences.html?highlight=get_lock#table-locking

**Comment by axelfontaine** [comment]
@rcbensley Thanks for the config provided. I tried it out and the current release of Flyway works perfectly with it. Could you ensure it actually comes with the limitations you highlighted?

**Comment by rcbensley** [comment]
Hi @axelfontaine yes I can't seem to get this to fail on 5.2.4.
This is quite frustrating, but also fantastic.
I will close for now and instead see if I can get some upgrades moving.

Sorry for being a pain, and thank you for your patience.
