### ISSUE TITLE
Cannot execute PostgreSQL migration that contains "?" operator for jsonb

### ISSUE THREAD

**Issue by alexander-semenets-dev** [flyway/flyway#2329]
###### Which version and edition of Flyway are you using?
6.0.0-beta

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
PostgreSQL 11

###### Which operating system are you using?
Windows 10

###### What did you do?
My migration contains script similar to this simplified code:
```sql
SELECT 1
WHERE '{ "field": 1 }'::jsonb ? 'field';
```

###### What did you expect to see?
Executed migration

###### What did you see instead?
Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unable to parse statement in V20190318193024__test.sql at line 1 col 1: Unknown char ? encountered on line 2 at column 31

I investigated and debugged code of Parser java class and didn't found any logic for handling this operator.

If I am wrong in something please correct me. Thanks!

**Comment by alexander-semenets-dev** [comment]
Part of stack trace:
Caused by: org.flywaydb.core.api.FlywayException: Unknown char ? encountered on line 2 at column 31
	at org.flywaydb.core.internal.parser.Parser.readToken(Parser.java:453)
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:149)

**Comment by axelfontaine** [comment]
Good catch and many thanks for the clear steps how to reproduce. We did indeed miss this case. Fixed.
