### ISSUE TITLE
MySQL 0.1 is outdated and no longer supported by Flyway

### ISSUE THREAD

**Issue by muarachmann** [flyway/flyway#2332]
###### Which version and edition of Flyway are you using?
org.flywaydb:flyway-gradle-plugin:5.2.4

###### Which client are you using? 
 Gradle plugin

###### Which database are you using (type & version)?
MySQL  Ver 14.14 Distrib 5.7.25,

###### Which operating system are you using?
Linux - Ubuntu 16.04 xenial

###### What did you do?
I am trying to run some sql files using the flyway latest plugin gotten from here https://flywaydb.org/documentation/gradle/ in my project by running the command `./gradlew flywayMigrate`

###### What did you expect to see?
I expect to see it run the migrations and populate my database

###### What did you see instead?
For some unknown reasons i keep getting this error 

`Caused by: org.flywaydb.core.internal.exception.FlywayDbUpgradeRequiredException: MySQL upgrade required: MySQL 0.1 is outdated and no longer supported by Flyway. Flyway currently supports MySQL 5.1 and newer.at` `org.flywaydb.core.internal.database.base.Database.ensureDatabaseIsRecentEnough(Database.java:156)`
       `at` `org.flywaydb.core.internal.database.mysql.MySQLDatabase.ensureSupported(MySQLDatabase.java:114)`
       `at` `org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:97)`
       `at org.flywaydb.core.Flyway.execute(Flyway.java:1670)`
      `at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)`
       `at org.flywaydb.gradle.task.FlywayMigrateTask.run(FlywayMigrateTask.java:28)`
       `at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:489`)
       ... 167 more

I wish get a possible fix for this cause please. i am having mysql 5.7 yet it is  throwing this error

**Comment by axelfontaine** [comment]
You must be using some strange patched version of MySQL as the official binaries do not have this issue. Where did you obtain it from and how did you install it?

**Comment by muarachmann** [comment]
Hi @axelfontaine thanks for reaching out. I installed mysql using the command `sudo apt-get install mysql-server` which pulled the 5.7 version. Even with mysql 8 it does the same thing. I installed using this - https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/

**Comment by muarachmann** [comment]
Moreover @axelfontaine this happens only with the drizzle driver drizzle driver version `org.drizzle.jdbc:drizzle-jdbc:1.3` when i use mysql-connector i don't get this. It works perfectly fine with flyway `org.flywaydb:flyway-gradle-plugin:3.0` but when i upgrade to `org.flywaydb:flyway-gradle-plugin:5.2.4` and drizzle plugin, i get that error. Could there be a fix for this. i would be volunteering to work on this if guided on what to do thanks

**Comment by axelfontaine** [comment]
Well then it would appear we have identified the issue. Please stick to the official MySQL driver (which is the only one we support officially) or contact the Drizzle team to get their driver fixed.

**Comment by vorburger** [comment]
https://github.com/krummas/DrizzleJDBC/issues/46

https://issues.apache.org/jira/browse/FINERACT-761

https://issues.apache.org/jira/browse/LEGAL-462
