### ISSUE TITLE
H2: clean does not remove function alias

### ISSUE THREAD

**Issue by SomMeri** [flyway/flyway#2335]
###### Which version and edition of Flyway are you using?
2018.5.0 (same issue is with 3.2.1)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes. It is the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven dependency.

###### Which database are you using (type & version)?
H2 1.4.197 through maven

###### Which operating system are you using?
Tested with windows and linux.

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

1.) I created an alias in migration:
````sql
CREATE ALIAS MY_FUNCTION AS $$
Integer diffSeconds(java.util.Date date1, java.util.Date date2) {
	if (date1 == null || date2 == null) {
		return null;
	}
	return (int) (date1.getTime() / 1000 - date2.getTime() / 1000);
}
$$;;
````

2.) I run the migration `flyway.migrate()` and then verified that alias exists in database `SELECT * FROM INFORMATION_SCHEMA.FUNCTION_ALIASES;` statement.

3.) I run clean command: `flyway.clean()`

###### What did you expect to see?
The `MY_FUNCTION` function alias should disappear from database. The `SELECT * FROM INFORMATION_SCHEMA.FUNCTION_ALIASES;` statement should return no rows.

###### What did you see instead?
Function alias remained in the database.

**Comment by axelfontaine** [comment]
Thank you very much for the detailed report and analysis. This was very helpful and the issue has now been fixed.
