### ISSUE TITLE
"set serveroutput on" not working in 5.2.4 trial in command line for oracle 12.1

### ISSUE THREAD

**Issue by coredigitalmedia** [flyway/flyway#2336]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by coredigitalmedia** [comment]
/dbwork/git_workspace/DBA/ORACLE/flyway/flyway-5.2.4/flyway -enterprise -licenseKey=FL01963E9370AB97521xxxxxxxxxx  -user=system -password=xxxx -url=jdbc:oracle:thin:@//host.example.com:1521/orcl.example.com -baselineOnMigrate=true -locations=filesystem:/tmp migrate
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Coredigital Media until 2019-04-21
WARNING: You are using a 30 day limited Flyway trial license. After 30 days you must either upgrade to a full Flyway Enterprise Edition license or downgrade to Flyway Community Edition.
Database: jdbc:oracle:thin:@//host.example.com:1521/orcl.example.com (Oracle 12.1)
Successfully validated 2 migrations (execution time 00:00.022s)
Current version of schema "SYSTEM": 1
Migrating schema "SYSTEM" to version 2 - test
ERROR: Migration of schema "SYSTEM" to version 2 - test failed! Please restore backups and roll back database and code!
ERROR:
Migration V2__test.sql failed
-----------------------------
SQL State  : 42000
Error Code : 922
Message    : ORA-00922: missing or invalid option
Location   : /tmp/V2__test.sql (/tmp/V2__test.sql)
Line       : 1
Statement  : SET SERVEROUTPUT ON

**Comment by coredigitalmedia** [comment]
Here is a script.
cat /tmp/V2__test.sql
SET SERVEROUTPUT ON;
SET DEFINE OFF;
BEGIN
DBMS_OUTPUT.PUT_LINE('TEST');
END;
/

**Comment by axelfontaine** [comment]
Did you set `oracle.sqlplus`to `true` (see https://flywaydb.org/documentation/commandline/migrate#oracle.sqlplus) to enable SQL\*Plus support?

**Comment by coredigitalmedia** [comment]
Thanks Axel, it worked.

Now how to get “Display query results” in command line for oracle 12.1?
