### ISSUE TITLE
Flyway history schema lock timeout cannot be overrided

### ISSUE THREAD

**Issue by haithkris** [flyway/flyway#2337]
###### What did you do?
We had a migration done on a large table. An alter table to be precise. And the lock of flyway history schema table did timeout after 30 seconds. 

Is there a possiblity to add an option where we can override this timeout value? Because right now, we are obliged to run manually the migration that takes too long on the side, then re-run flyway which breaks the continuity  of our build.

**Comment by haithkris** [comment]
Sorry for bringing this up now but the solution was to set the `net_read_timeout` and socketTimeout to more than 30 seconds. Now it works.

**Comment by axelfontaine** [comment]
Thanks for the update. Good to know!

**Comment by pbeaumontQc** [comment]
Some precision: we found that the net_read_timeout did not need to be changed, but just the socketTimeout in our connection string.
