### ISSUE TITLE
Create stored procedure for MySql and MariaDB fails

### ISSUE THREAD

**Issue by tcat2** [flyway/flyway#2338]
###### Which version and edition of Flyway are you using?
6.0.0-beta

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using (type & version)?
MySql 5,7

###### Which operating system are you using?
Win10 Pro 64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway migrate

###### What did you expect to see?
no errors

###### What did you see instead?
migration file where stored procedure is created and executed afterwards fails. Error: PROCEDURE xyz does not exist. Works fine with Flyway 5.2.4

**Comment by axelfontaine** [comment]
Please share the smallest possible SQL file that reproduces this issue.

**Comment by tcat2** [comment]
`DROP PROCEDURE IF EXISTS reproduceError;
DELIMITER $$
 CREATE PROCEDURE reproduceError()
BEGIN
    SELECT 1;
 END$$
DELIMITER ;
CALL reproduceError();
DROP PROCEDURE IF EXISTS reproduceError;`

**Comment by axelfontaine** [comment]
Thank you very much for the clear test case. That was incredibly helpful in identifying the issue. It turned out we weren't handling custom delimiters correctly when they followed a keyword without a space. In your example it was `END$$` that tripped up the parser. Fixed.

**Comment by andrew-shamin** [comment]
Please, fix this bug in macOS CLT 
https://flywaydb.org/download/thankyou?dl=https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.2.3/flyway-commandline-6.2.3-macosx-x64.tar.gz
