### ISSUE TITLE
MySQL: Reset SQL_SAFE_UPDATES and FOREIGN_KEY_CHECKS after each migration

### ISSUE THREAD

**Issue by jfly** [flyway/flyway#2341]
(Sorry if this isn't the right place for feature requests.)

We use Flyway 3.0 for running migrations against our MySQL database. Sometimes our migrations leave the database connection/session in a weird state (such as turning on safe mode). We have noticed that if flyway runs multiple migrations, it runs them all in the same connection/session, and weird state from a past migration can cause future migrations to fail. However, if we run those migrations in separate invocations of flyway, then everything is fine, because flyway creates a fresh connection to the database.

https://github.com/flyway/flyway/issues/1250 is a very similar issue, which was fixed in https://github.com/flyway/flyway/commit/7aec65654197592e1b3385bcd059e4fd1af853b7 by having flyway track the original value of `ANSI_NULLS` and then to restore the value after each migration. That fix feels pretty specific to me. If it were instead possible to run each migration in its own fresh connection, then every session specific setting would get reset.

**Comment by axelfontaine** [comment]
What is your exact use case? Is it just `SQL_SAFE_UPDATES` or are there more? And if yes what are they?

**Regarding having a separate connection per migration:**

Short story: it's not as trivial as it seems

Long story: For certain databases like SQL Server this wouldn't be possible as certain commands expect no other connection to be active. That being said I am not aware of any similar restrictions for MySQL. But even if we could manage that, we would still have to deal with connection pools intercepting the `Connection.close()` method...

**Comment by jfly** [comment]
`SQL_SAFE_UPDATES` is one setting I know we've been bit by before. I'm not sure if there are others. I will reach out to the team and report back if there are others.

Re: SQL Server, I don't think I see why creating a new connection for each migration would cause simultaneous connections?

**Comment by jfly** [comment]
Update: Other settings we have played with include `FOREIGN_KEY_CHECKS` and `AUTOCOMMIT`

**Comment by axelfontaine** [comment]
Autocommit was already being reset. Flyway now also resets `SQL_SAFE_UPDATES` and `FOREIGN_KEY_CHECKS`. Fixed.

**Comment by HiJackXD** [comment]
This feature would couse user who has no server privillege failed to boot .
