### ISSUE TITLE
Feature 'Display query results' doesn't give output in 5.2.4 Pro for Oracle

### ISSUE THREAD

**Issue by pvhors** [flyway/flyway#2347]
###### Which version and edition of Flyway are you using?
Flyway Pro 5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
Same problem in Flyway 6.0.0 beta
In version Flyway Pro 5.1.4 it works fine without any problem!

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle Database 18c Standard Edition 2 Release 18.0.0.0.0 - Production

###### Which operating system are you using?
Windows

###### What did you do?
Run sql script "V0001__Test.sql" with 1 statement:
SELECT USER, SUBSTR(GLOBAL_NAME,1,25) GLOBAL_NAME, SYSTIMESTAMP FROM GLOBAL_NAME;

Use flyway.conf file with the settings:
flyway.url=jdbc:oracle:thin:@//xxxxxxx:nnnn/DB_NAME
flyway.user=SCHEMA_NAME
flyway.password=********
flyway.baselineOnMigrate=true
flyway.oracle.sqlplus=true
flyway.mixed=true
flyway.licenseKey=FL……….

###### What did you expect to see?
Flyway Pro Edition (50 schemas) 5.2.4 by Boxfuse licensed to …….
Database: jdbc:oracle:thin:@//xxxxxxx:nnnn/DB_NAME
Successfully validated 1 migration (execution time 00:00.014s)
Creating Schema History table: "SCHEMA_NAME"."flyway_schema_history"
Current version of schema "SCHEMA_NAME": << Empty Schema >>
Migrating schema "SCHEMA_NAME" to version 0001 - Test
+-------------+-------------+-------------------------------+
| USER        | GLOBAL_NAME | SYSTIMESTAMP                  |
+-------------+-------------+-------------------------------+
| SCHEMA_NAME | DB_NAME     | 2019-04-04 15:01:15.245 +2:00 |
+-------------+-------------+-------------------------------+
Successfully applied 1 migration to schema "SCHEMA_NAME" (execution time 00:00.088s)

###### What did you see instead?
Flyway Pro Edition (50 schemas) 5.2.4 by Boxfuse licensed to …….
Database: jdbc:oracle:thin:@//xxxxxxx:nnnn/DB_NAME
Successfully validated 1 migration (execution time 00:00.014s)
Creating Schema History table: "SCHEMA_NAME"."flyway_schema_history"
Current version of schema "SCHEMA_NAME": << Empty Schema >>
Migrating schema "SCHEMA_NAME" to version 0001 - Test
Successfully applied 1 migration to schema "SCHEMA_NAME" (execution time 00:00.088s)
-----------------------------
So there is no output from the select statement.
When we run the same script with the same config settings with Flyway version 5.1.4 Pro it works fine!!

**Comment by axelfontaine** [comment]
Arghh! Good catch! This did indeed break for Oracle (all other DBs work fine). This has now been fixed and the fix will ship as part of 6.0.0.
