### ISSUE TITLE
FluentConfig locations do not works as expected

### ISSUE THREAD

**Issue by sebastienvermeille** [flyway/flyway#2348]
###### Which version and edition of Flyway are you using?
5.2.4 (community)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
it's the latest stable release -> yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API we have our own tool  which embed flyway for convenience.

###### Which database are you using (type & version)?
PostgreSQL 10

###### Which operating system are you using?
Linux Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We upgraded flyway version to flyway 5.2.4 and since there I had to use Fluentconfig in order to avoid using deprecated methods.

I used it like that:
```java
new Flyway(Flyway.configure()//
          .locations("classpath:database/migrations", "classpath:com/project/migration/script/java")//
          .dataSource(getDataSource())//
          .connectRetries(1)//
          .baselineDescription(BASELINE_DESCRIPTION)//
          .table(TABLE_SCHEMA_VERSION)//
          .validateOnMigrate(true));
```

Then I run the flyway.migrate();
###### What did you expect to see?

Flyway execute my migrations scripts placed in **resources/database/migrations**

###### What did you see instead?
Flyway execute (at least it tries) to execute scripts at location **db/migration**

###### My comments
If I move all my sql migrations scripts into resources/db/migration -> it works
if I move them inside of the declared location -> it failed

I had a look at the documentation of course but it seems I am using it correctly right ?
`It search my sql migrations file inside of db/migration which is the default path. Not the one I defined in locations.

Regarding the documentation:
```
    /**
     * Sets the locations to scan recursively for migrations.
     * <p>The location type is determined by its prefix.
     * Unprefixed locations or locations starting with {@code classpath:} point to a package on the classpath and may
     * contain both SQL and Java-based migrations.
     * Locations starting with {@code filesystem:} point to a directory on the filesystem, may only
     * contain SQL migrations and are only scanned recursively down non-hidden directories.</p>
     *
     * @param locations Locations to scan recursively for migrations. (default: db/migration)
     */
    public FluentConfiguration locations(String... locations) {
        config.setLocationsAsStrings(locations);
        return this;
    }
```
I guess it should be okay to use it the way I did right ?`

**Comment by axelfontaine** [comment]
Hmm I can't seem to reproduce this. Can you share a small JUnit test that clearly demonstrates this?

Also note that

```java
new Flyway(Flyway.configure()//
          .locations("classpath:database/migrations", "classpath:com/project/migration/script/java")//
          .dataSource(getDataSource())//
          .connectRetries(1)//
          .baselineDescription(BASELINE_DESCRIPTION)//
          .table(TABLE_SCHEMA_VERSION)//
          .validateOnMigrate(true));
```

can be simplified to:

```java
Flyway.configure()
          .locations("classpath:database/migrations", "classpath:com/project/migration/script/java")
          .dataSource(getDataSource())
          .connectRetries(1)
          .baselineDescription(BASELINE_DESCRIPTION)
          .table(TABLE_SCHEMA_VERSION)
          .validateOnMigrate(true)
          .load();
```

**Comment by sebastienvermeille** [comment]
I'll try to reproduce it in a github project indeed give me a few days more please :) 

Thx for the info regarding the simplification ! :+1:

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by Zougi** [comment]
I get the same issue since we upgraded to spring-boot 2.1.6
I get the issue starting the spring servers with intelliJ. My colleagues who uses Eclipse do not have this issue :(

the code snippet

```
             private static final String BASE_SCRIPT_LOCATION = "classpath:db.migration.";
```

```
            Flyway.configure()
            .dataSource(executionContext.getDataSource())
            .schemas(executionContext.getSchema())
            .locations(BASE_SCRIPT_LOCATION + executionContext.getModule())
            .load();
```
