### ISSUE TITLE
Set a property(flag) to disable automatic schema creation feature

### ISSUE THREAD

**Issue by XhstormR** [flyway/flyway#2350]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 6.0.0-beta
flyway-commandline-6.0.0-beta-windows-x64.zip

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I use latest version 6.0.0-beta

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

```
SELECT VERSION();
----
PostgreSQL 11.1, compiled by Visual C++ build 1914, 64-bit
```

###### Which operating system are you using?

```
C:\Users\Leo>ver
Microsoft Windows [Version 10.0.14393]
```

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I have a SQL script name `V1__init.sql` in flyway-6.0.0-beta\sql folder, this is script content:

```sql
create schema erp;
create sequence erp.account_seq start 1 increment 1;
create table erp.account (id int8 not null);
```

I have an empty database, then I executed the following command:

```
D:\Download\flyway-6.0.0-beta>flyway -user=123 -password=123456 -url=jdbc:postgresql://127.0.0.1:5432/postgres -schemas=erp migrate

Flyway Community Edition 6.0.0-beta by Boxfuse
Database: jdbc:postgresql://127.0.0.1:5432/postgres (PostgreSQL 11.1)
Creating schema "erp" ...
Creating Schema History table: "erp"."flyway_schema_history"
Current version of schema "erp": null
Migrating schema "erp" to version 1 - init
ERROR: Migration of schema "erp" to version 1 - init failed! Changes successfully rolled back.
ERROR:
Migration V1__init.sql failed
-----------------------------
SQL State  : 42P06
Error Code : 0
Message    : Error: schema "erp" already exists
Location   : D:\Download\flyway-6.0.0-beta\sql\V1__init.sql (D:\Download\flyway-6.0.0-beta\sql\V1__init.sql)
Line       : 1
Statement  : create schema erp
```

###### What did you expect to see?

If the schema does not exist, the flyway will report an error directly.

In some cases I don't want this feature because my SQL initialization script already includes schema creation. Since flyway will automatically create the mode, when executing my SQL initialization script, the database will get an error and the program will fail.

###### What did you see instead?

If the schema does not exist, the flyway will automatically create for me.

I found [this link](https://dzone.com/articles/flyway-21-released-automatic), so I want to know if there is a way to disable this feature, or you can add some flag to disable this feature, thank you.

**Comment by axelfontaine** [comment]
Related to #2277

**Comment by MikielAgutu** [comment]
Can you try placing your schema creation script in the [`initSql` config option](https://flywaydb.org/documentation/configfiles)? Note it has to be on one line.

**Comment by MikielAgutu** [comment]
@XhstormR Any news?

**Comment by XhstormR** [comment]
Because the database script is exported by some program, and sine this function cannot be turned off, I need to modify the exported database script every time I export.

**Comment by MikielAgutu** [comment]
@XhstormR So either way you'd need to do some sort of manual config - either deleting a line or toggling a possible new config option. To me it seems reasonable just to delete the create schema code in your script. Thoughts?

**Comment by MikielAgutu** [comment]
@XhstormR Any news?

**Comment by XhstormR** [comment]
I think adding a new option is better, because I need to delete the create statement every time I export the script, and I may forget to delete it. If it is an option, I can use the exported script directly.

**Comment by exst-esolis** [comment]
I also believe that adding a new option to turn off automatic schema creation is the way to go. 

Modifying the existing script causes verification error on database which has already executed the old script. On the other hand, not changing the script would cause problems when running on a clean install of the database.

**Comment by MikielAgutu** [comment]
@exst-esolis @XhstormR This is now possible in Flyway 6.5.0. Note this somewhat interferes with how Flyway's schema history table is created. The details of that are explained in the documentation: https://flywaydb.org/documentation/migrations#toggle-schema-creation.
