### ISSUE TITLE
flyway_commandline: no_jre version

### ISSUE THREAD

**Issue by BercziSandor** [flyway/flyway#2351]
Feature request/suggestion:
the flyway_commandline should be available as no_jre: it should work with the JRE found in the path. The package could be much smaller.
Both versions should be available to download.

###### Which version and edition of Flyway are you using?
Does not matter

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Does not matter

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Does not matter

###### Which database are you using (type & version)?
Does not matter

###### Which operating system are you using?
Does not matter

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Does not matter

###### What did you expect to see?
Does not matter

###### What did you see instead?
Does not matter

**Comment by axelfontaine** [comment]
As stated on https://flywaydb.org/documentation/commandline/#download-and-installation

> Older versions, packages without JRE and sources are available from [Maven Central](https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline)
