### ISSUE TITLE
Typo in MigrationType Javadoc

### ISSUE THREAD

**Issue by JohnEgan91** [flyway/flyway#2352]
There is a simple typo in the Javadoc for MigrationType.java. For the BASELINE enum the Javadoc says 'Bsline' instead of 'Baseline'. 

Here is the link: https://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/api/MigrationType.html

I want to make my first open source contribution so I can go ahead and fix it with a pull request.

**Comment by JohnEgan91** [comment]
I created PR #2353 to fix the typo

**Comment by axelfontaine** [comment]
Good catch! Merged.
