### ISSUE TITLE
Regarding API support for Sql Migration only

### ISSUE THREAD

**Issue by sidhartha1987** [flyway/flyway#2356]
###### Which version and edition of Flyway are you using?

5.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which database are you using (type & version)?

Mysql

###### Which operating system are you using?

Centos 7.0

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?

Actually, I want to perform only sql migration ie. plain sql scripts and not with Maven and all.
Can it be done via API mode ? Please let us know.

**Comment by axelfontaine** [comment]
Please ask questions on StackOverflow. This issue tracker is for issues and pull requests only.
