### ISSUE TITLE
Log Transaction ID for migrations

### ISSUE THREAD

**Issue by henricook** [flyway/flyway#2359]
Running flyway-latest-stable within a JDBC application on Linux...

Is there a way to log or retrieve the transaction ID of each migration?

**Comment by MikielAgutu** [comment]
@henricook Can you explain a bit more about your use case? What DB are you using, how would you like to retrieve the transaction ID, etc

**Comment by henricook** [comment]
Thanks for following this up @MikielAgutu. A now departed member of my infrastructure team asked for this and I cannot remember its benefit. I've not thought 'i really need that' in the last year - so I think it's time to close the ticket!

Thanks again
