### ISSUE TITLE
Parser as an independent module?

### ISSUE THREAD

**Issue by rnorth** [flyway/flyway#2360]
Apologies that this is a question, and a repeat as well (#916 asked the same thing but is dated 2015, so I thought it worth asking again).

For Testcontainers we're thinking about replacing the (growing) ball of mud that is our SQL script splitting class. We literally only need this for running DB init scripts, and I'd consider SQL parsing well outside our area of core competency.

Flyway's parser, particularly the 6.0.0 version, seems quite appealing as a replacement - I'd trust your implementation a lot more than ours!

Have you given any more thought to the question of releasing this separately? 

Or would your suggestion still be to use the internal API? (We'd shade Flyway to guard against breaking changes if we do this).

**Comment by axelfontaine** [comment]
Let me turn this around: Why not integrate Flyway directly as a way to initialize the database?

**Comment by axelfontaine** [comment]
Any news?

**Comment by rnorth** [comment]
Argh, I had written a long reply and I think I forgot to send. I'm sorry. I'll try and rewrite (maybe more concisely).

I do think that's a very interesting suggestion indeed.

We need to run a single specific SQL script, and if the user has Flyway migration files present we *do not* want to run those, nor create a schema history table.

It's essentially a very dumbed-down subset of the `migrate` operation that we're after. Any more than this would be a substantial behaviour change that might contradict what our users expect.

I'm not sure if there's an elegant way to configure Flyway to do this - is there?

**Comment by MikielAgutu** [comment]
@rnorth you could migrate, then use a callback to delete the schema history table. https://flywaydb.org/documentation/callbacks

**Comment by DoodleBobBuffPants** [comment]
For executing the SQL, you could use [initSql](https://flywaydb.org/documentation/configuration/parameters/initSql).

As for not executing migrations, you could use [dry run](https://flywaydb.org/documentation/concepts/dryruns).

This would parse and execute the specific SQL you wish to execute, and not execute any migrations or create a schema history table. Would this suffice?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
