### ISSUE TITLE
Null Pointer exception when no migration patches found

### ISSUE THREAD

**Issue by Me1gireesh** [flyway/flyway#2361]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Me1gireesh** [comment]
Error while no migrations are found on the file path. I am using Flyway 5.2.4 

Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
ERROR: java.lang.NullPointerException

**Comment by axelfontaine** [comment]
Please share the debug output of the command you ran by adding `-X`. Also please fill in the issue template. We have it for a reason as it avoids unnecessary back and forth for essential questions.

**Comment by Me1gireesh** [comment]
You may discard this as I am getting no migrations found message now.

DEBUG: Loading config file: /sbil/ci/bin/flyway-5.2.4/conf/flyway.conf
DEBUG: Unable to load config file: /home/********/flyway.conf
DEBUG: Unable to load config file: /sbil/ci/bin/flyway-5.2.4/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.baselineOnMigrate -> true
DEBUG: flyway.locations -> filesystem:/sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source
DEBUG: flyway.password -> ****************
DEBUG: flyway.oracle.sqlplus -> true
DEBUG: flyway.table -> FLYWAY_SCHEMA_HISTORY
DEBUG: flyway.schemas -> my_user
DEBUG: flyway.url -> jdbc:oracle:thin:@ldap://oudsit.us.dell.com:389/my-db,cn=ORACLECONTEXT,OU=TNSNAMES,O=APPS,dc=dell,dc=com
DEBUG: flyway.user -> my_user
DEBUG: flyway.licenseKey -> FL01651DD2B9088E523126E738D02D5B0A2B594CDE40D0F0A842309E3EAA75F219B212A1D8F1D322A8BCF830AD02AFA4CB9116C9774949079C756EB57BB6D3CCC87A733C9A09A98CC85C9868314AFF75E23570A6B429F2FFFC7AE88824555190379531BD0D7256031AE5BDABBB173719CBD404450F8547EAFD89DDCB3FFF965B5E017019A23418C927537002AAAA4BBBF60297D90C028E6371F7B62A76DD90643C58A918B681A00DBDAAA0F535CA0CE29781A34BCF535C10C9C4C58DCF8052733F7A5F8FF618DA45A6ABF14D33699057C3091ED00C23772EE092912265E14C50390600E8E7B5392B075DDDAF0823E3A4C464DB6FDDABB262393FD5677763118DD879
DEBUG: flyway.jarDirs -> /sbil/ci/bin/flyway-5.2.4/jars
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/derby-10.14.2.0.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/derbyclient-10.14.2.0.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/h2-1.4.197.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/hsqldb-2.4.1.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/mssql-jdbc-7.0.0.jre8.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/mysql-connector-java-8.0.12.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/mariadb-java-client-2.3.0.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/postgresql-42.2.5.jre6.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/sqlite-jdbc-3.23.1.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/ojdbc7_g.jar
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
Database: jdbc:oracle:thin:@ldap://oudsit.us.dell.com:389/my_user,cn=ORACLECONTEXT,OU=TNSNAMES,O=APPS,dc=dell,dc=com (Oracle 12.1)
DEBUG: Driver  : Oracle JDBC driver 12.1.0.1.0
DEBUG: DDL Transactions Supported: false
DEBUG: Schema: PROCESS_CICD
DEBUG: Scanning for filesystem resources at '/sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source'
DEBUG: Scanning for resources in path: /sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source (/sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source)
DEBUG: Found filesystem resource: /sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source/README.md
DEBUG: Scanning for SQL callbacks ...
DEBUG: Filtering out resource: /sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source/README.md (filename: README.md)
DEBUG: Spring Jdbc available: false
DEBUG: Filtering out resource: /sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source/README.md (filename: README.md)
DEBUG: Filtering out resource: /sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source/README.md (filename: README.md)
DEBUG: Filtering out resource: /sbil/ci/jenkins-slave/workspace/utilities-db/database-migration/repo/source/README.md (filename: README.md)
DEBUG: Memory usage: 33 of 117M
Schema version: << Empty Schema >>

+----------+---------+-------------+------+--------------+-------+----------+
| Category | Version | Description | Type | Installed On | State | Undoable |
+----------+---------+-------------+------+--------------+-------+----------+
| No migrations found                                                       |
+----------+---------+-------------+------+--------------+-------+----------+
