### ISSUE TITLE
how to display query when apply

### ISSUE THREAD

**Issue by coredigitalmedia** [flyway/flyway#2362]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by coredigitalmedia** [comment]
it doesn't display query when being applied, how to print which query is being applied at the time?

**Comment by axelfontaine** [comment]
The statement being executed can be displayed by enabling the debug output by adding `-X` to the Flyway CLI's list of arguments.

**Comment by coredigitalmedia** [comment]
Hi Axel,

-X (debug) option list bunch of unnecessary information, how to display just query being executed and output result, not all debug information?

Thanks.
