### ISSUE TITLE
SqlScript Parser takes several minutes

### ISSUE THREAD

**Issue by leonborko** [flyway/flyway#2364]
###### Which version and edition of Flyway are you using?
5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
SQL Server 2017 (linux)

###### Which operating system are you using?
MacOSX

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Every time I start spring boot application flyway takes several minutes to validate attached script. I have do some research and come to SqlScript parser class which is cause of the problem
[V1_0_46__Import_dll.txt](https://github.com/flyway/flyway/files/3108498/V1_0_46__Import_dll.txt)

###### What did you expect to see?
Faster SqlScript Parser

###### What did you see instead?

**Comment by axelfontaine** [comment]
Upgrade to 6.0.0-beta and you will see a dramatic increase in speed. That particular file parses in under 200 ms on my machine.
