### ISSUE TITLE
org.flywaydb.core.api.FlywayException: No value provided for placeholder expressions: ${spring.datasource.schema}.  Check your configuration! 

### ISSUE THREAD

**Issue by qiaojiang2** [flyway/flyway#2365]
###### Which version and edition of Flyway are you using?
 <artifactId>flyway-maven-plugin</artifactId>
 <version>5.2.4</version>

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by axelfontaine** [comment]
Not a Flyway issue. As the message says, you haven't provided Flyway with a value for that placeholder. You need to copy this Spring Boot value into Spring Boot's Flyway config. Check out the Spring Boot documentation for Flyway placeholders when in doubt.

**Comment by qiaojiang2** [comment]
spring:
  messages:
    basename: i18n/messages
  redis:
    host: 127.0.0.1
    port: 6379
    password: Jetpad2019
  datasource:
    url: jdbc:mysql://mysql-test.xx3306/jets
    username: jes
    password: xxx
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    schema: jes

I added the configuration of Spring Boot, but I still reported an error in maven build. Can you give me an example of flyway maven configuration? Thank you very much

**Comment by qiaojiang2** [comment]
<properties>
        <spring.datasource.schema>jes</spring.datasource.schema>
    </properties>

I solved this problem, but I don't understand why we have to set in the property field.

<schemas>
        <schema>schema1</schema>
        <schema>schema2</schema>
        <schema>schema3</schema>
    </schemas>

What does this configuration do?
