### ISSUE TITLE
SQL*Plus SET/SHOW ECHO/TERMOUT/TIME/TIMING support

### ISSUE THREAD

**Issue by Me1gireesh** [flyway/flyway#2371]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Me1gireesh** [comment]
Please add the below command support for Oracle. 
SET TERMOUT ON
SET ECHO ON
SET TIMING ON
SET TIME ON

I am getting the error as the commands are unsupported on 5.2.4
[main] WARN org.flywaydb.core.internal.database.oracle.pro.SQLPlusSetSqlStatement - SP2-0158: unknown SET option "ON"
[main] WARN org.flywaydb.core.internal.database.oracle.pro.SQLPlusSetSqlStatement - SP2-0158: unknown SET option "ON"

**Comment by axelfontaine** [comment]
These have now been implemented.
