### ISSUE TITLE
Wrong path to sqlite database with gradle 4.8+

### ISSUE THREAD

**Issue by FilenkovMaxim** [flyway/flyway#2377]
###### Which version and edition of Flyway are you using?
5.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle 5.2.1

###### Which database are you using (type & version)?
Sqlite 3

###### Which operating system are you using?
Linux (Ubuntu)

###### What did you do?
Start `./gradlew FlywayMigrate `

###### What did you expect to see?
Successful build 

###### What did you see instead?
`Unable to obtain connection from database (jdbc:sqlite:src/db.sqlite) for user 'null': path to 'src/db.sqlite': '/home/maxf/.gradle/daemon/5.2.1/src' does not exist`

I have 
```
flyway {
    url = 'jdbc:sqlite:src/db.sqlite'
}
```
in my build.gradle
With gradle 4.2 it works fine. But with 4.8+ it failed, because searches database into gradle folder.
P.S. if I move database into gradle folder build finishes correctly.

**Comment by axelfontaine** [comment]
Hmmm the more I think yout this the more I feel this is actually a Gradle regression as Flyway simply takes the URL as-is. Gradle appears to have changed its current working directory and should probably change it back.

**Comment by FilenkovMaxim** [comment]
Did you reported this issue to Gradle team?

**Comment by FilenkovMaxim** [comment]
I solved the issue with the variable project.projectDir
```
flyway {
    url = "jdbc:sqlite:/${project.projectDir}/src/main/resources/db/dubs.sqlite"
}
```
It works for gradle 5.5.1
