### ISSUE TITLE
Docker container: add configuration to point at a script which returns the password

### ISSUE THREAD

**Issue by voronaam** [flyway/flyway#2378]
We are using FlywayDB Community Edition in its Docker container.

To configure the connection we supply arguments `-url`, `-user` and `-password`
The latter is a bit of a problem, because it is visible in kubernetes manifest via `kubectl` command. It is visible only while the job is running, but it is still not nice from the security point of view.

Would it be possible to have a `-password-supplier` parameter? (The name can be different)

The idea is to point at some script or a program that retrieves the password (in our case from Vault https://www.vaultproject.io/) and prints to stdout. FlywayDB will execute the script/program and use the captured output as the password.

This would also solve some other use cases, such as one outlined in issue #960 for example. In that user's case she would need to have a simple `echo $PGPASSWORD` in the script.

I believe that this would not make FLywayDB code too convoluted, while providing a great deal of flexibility for the use cases like ours.

**Comment by axelfontaine** [comment]
Can't you assign the result of this script to the `FLYWAY_PASSWORD` environment variable when launching the container?

**Comment by voronaam** [comment]
We could not do this without changing the entrypoint. But I could not remember the reasons behind us not willing to change it.

It is defined as simple `ENTRYPOINT ["/flyway/flyway"]` in https://github.com/flyway/flyway-docker/blob/master/Dockerfile

I think we can change it and call flyway later on after setting the environment variable.

Thank you.
