### ISSUE TITLE
Flyway fails to parse `COMMENT ON ...` statements

### ISSUE THREAD

**Issue by troosan** [flyway/flyway#2382]
###### Which version and edition of Flyway are you using?
Version 5.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
maven plugin

###### Which database are you using (type & version)?
Oracle 12.2

###### Which operating system are you using?
Unix

###### What did you do?
execute script containing `COMMENT ON ...` (for instance, same for comment on view, mview, ...)
```sql
COMMENT ON TABLE Employee IS 'This is a table for Employee.';
```

###### What did you expect to see?
No error

###### What did you see instead?
Error

**Comment by axelfontaine** [comment]
What is the error you are getting? Please post the exact output.

**Comment by troosan** [comment]
I'll have to test it a bit more, the error is probably something else.
I actually have a statement which is not ended by a `;`, but which is followed by `/`.
This is valid when running with plsql, but not with flyway.
