### ISSUE TITLE
Flyway licensing for oracle

### ISSUE THREAD

**Issue by coredigitalmedia** [flyway/flyway#2385]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by coredigitalmedia** [comment]
Hello:
I've a question about licensing for oracle.

"Number of schemas in production managed by Flyway" what does it mean?

**Comment by axelfontaine** [comment]
For Oracle it is a user whose objects are managed by Flyway. See https://flywaydb.org/download/faq#what-exactly-is-a-schema

Let's continue this discussion by email as it is a better place for this than the issue tracker which is for the technical aspects of the product. Please send us an email at sales@flywaydb.org and we can talk there.

**Comment by coredigitalmedia** [comment]
Hi Alex,

Thanks. What does mean of "schemas managed by flyway"?



Thanks,
Pragnesh

On May 13, 2019 10:48 PM, Axel Fontaine <notifications@github.com> wrote:

For Oracle it is a user whose objects are managed by Flyway. See https://flywaydb.org/download/faq#what-exactly-is-a-schema

Let's continue this discussion by email as it is a better place for this than the issue tracker which is for the technical aspects of the product. Please send us an email at sales@flywaydb.org<mailto:sales@flywaydb.org> and we can talk there.

**Comment by axelfontaine** [comment]
> What does mean of "schemas managed by flyway"?

As I wrote, for Oracle it is a user whose objects (tables, views, procedures, ...) are managed (create, alter, drop, ...) by Flyway. See https://flywaydb.org/download/faq#what-exactly-is-a-schema

**Comment by coredigitalmedia** [comment]
So basically there are 100 users in the database with objects, needs license for 100 schemas?

Thanks,
Pragnesh

On May 14, 2019 1:53 AM, Axel Fontaine <notifications@github.com> wrote:

What does mean of "schemas managed by flyway"?

As I wrote, for Oracle it is a user whose objects (tables, views, procedures, ...) are managed (create, alter, drop, ...) by Flyway. See https://flywaydb.org/download/faq#what-exactly-is-a-schema

**Comment by axelfontaine** [comment]
Assuming, all are managed by Flyway, then yes.
