### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by sidhartha1987** [flyway/flyway#2386]
###### Which version and edition of Flyway are you using?
Flyway 5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Latest Version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command Line

###### Which database are you using (type & version)?

Mysql 5.7.17 and onwards

###### Which operating system are you using?

Centos 7.3

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?

Can i get an API for deploying sql through fly way ? Pure DB deployment 
Currently i don't see any option for it.

**Comment by axelfontaine** [comment]
How would this differ from our current Java API? Please lay out your proposal in more detail.

**Comment by axelfontaine** [comment]
Well, can't you simply call the CLI from your golang app?

Or how exactly do you envision this API to be? Please describe in detail so I can be sure I understand what you mean exactly.

**Comment by sidhartha1987** [comment]
See , We (Dtabase Engineers ) don't own the Go lang app , So integration couldn't be possible.  I want there should be an API , which take migration name and DB details as input and after passing it just perform the deployment. Currently i am using CLI option for same.

**Comment by axelfontaine** [comment]
And with API you mean a remotely deployed REST service accessible over HTTP(S) using cURL for example that is then able to perform a migration up to certain version based on SQL migration files stored in a predefined object store (directory, S3, ...)? Or what exactly do you mean? Can you please disambiguate?

**Comment by sidhartha1987** [comment]
yes, exactly. will deploy this on some central server and hit it via curl with all details. Will keep sql files on host not on s3.

**Comment by pyrocks** [comment]
Perhaps an Integration/CI-CD tool is better suited for your requirement, i.e have a parameterized jenkins job which will run the migration based on parameter values.

**Comment by sidhartha1987** [comment]
@axelfontaine  Any idea by when we'll get the above requested feature..

**Comment by sidhartha1987** [comment]
@pyrocks :- Can you please elaborate this in depth and will require more support here.

**Comment by sidhartha1987** [comment]
@pyrocks @axelfontaine  Please update here.

**Comment by axelfontaine** [comment]
@sidhartha1987 We have acknowledged your feature request. It has been placed on our long term roadmap where it may be revisited some day in the future.

**Comment by sidhartha1987** [comment]
@pyrocks :- I need your help in understanding the implementation of Jenkins job in depth. Kindly help here.

**Comment by pyrocks** [comment]
You have many resources online or recruit a devops guy.

**Comment by fazeem84** [comment]
> @sidhartha1987 We have acknowledged your feature request. It has been placed on our long term roadmap where it may be revisited some day in the future.

@axelfontaine  to build REST API,I feel we should build a centralised  console page  and server first ,which itself a separate project .but it will open new opportunities for  flyway
when you are planning to start it?,I would like to contribute to it during the implementation

**Comment by feaster83** [comment]
@fazeem84 @sidhartha1987 couldn't be so hard to build this in a separate or your own project.  Build a REST interface and call Flyway from that or update the database directly (if you don't use Flyway).  

I'm not sure if this kind of functionality should be part of Flyway. Maybe as an extension but it should be designed very well. It's not a quick win.

**Comment by fazeem84** [comment]
@feaster83 you are correct, it should not be the part of flyway.what I was thinking of Building  centralised application to manage multiple database.As you mentioned it should be carefully designed.I will see what I can do for starting my own project on this

**Comment by MikielAgutu** [comment]
This is way beyond the scope of Flyway. You can create something like this yourself by running Flyway on your own server.
