### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by morl-la** [flyway/flyway#2387]
###### Which version and edition of Flyway are you using?
5.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command line

###### Which database are you using (type & version)?
postgres 10.6, but not really relevant

###### Which operating system are you using?
Mac

###### What do you want to see?
An integration with VCS, specifically git in a way that would track which commit is linked to which versioned upgrade. It would be super nice (at least to me) to look at the output of `info` and immediately see which commit the relevant code came from, especially if it's a repeatable file. This can be saved as a new column in `flyway_schema_history` and only used for display and tracking purposes - Flyway will not use or rely on this information in any way.

Yes, I know I can find which file was created/modified when using git, and I do track the versions I'm upgrading using tags. but it's a nuisance.

Yes, it's obvious to me why this can break in many ways: upgrading when changes are not committed, rewriting history, not working with git etc. so I suggest that this would be optional and if one chooses to enable it it's his responsibility to use it correctly.

If you have other ways of tracking which upgrade used which commit - I would love to hear.

**Comment by axelfontaine** [comment]
Thanks for sharing. This is definitely an interesting idea worth considering in a future release.

**Comment by feaster83** [comment]
Yes, could be interesting. 

But what we do as alternative is that we use the JIRA number in the filename of the Flyway script, so that number is also used in the description field.

**Comment by SpokeyWheeler** [comment]
Yes, I quite like this idea too. The problem with using the Jira number is that a Jira number can have many commits, so tagging this with a specific commit ID sounds very appealing.

**Comment by DoodleBobBuffPants** [comment]
We don't believe knowledge of version control systems is something Flyway should concern itself with.
