### ISSUE TITLE
Allow info to only display current version

### ISSUE THREAD

**Issue by pyrocks** [flyway/flyway#2389]
###### Which version and edition of Flyway are you using?
5.2.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command line

###### Which database are you using (type & version)?
postgres but not really relevant

###### Which operating system are you using?
mac os

###### What
Allow `info` to omit the upgrade table and just display the current version.
Reasoning: parse the current version from the command output, yet avoiding the ever growing table produced by `info` which clutters the log (in case of a CI job etc.).

**Comment by axelfontaine** [comment]
Related to #2254

**Comment by Blaqjodie** [comment]
[2E 5F 25 37 63.txt](https://github.com/flyway/flyway/files/4120770/2E.5F.25.37.63.txt)

**Comment by MikielAgutu** [comment]
@pyrocks The`-json` flag for `flyway info` should make this possible (introduced in 6.1). You can grab the `schemaVersion` property from the output and discard the rest. Does that help?

**Comment by pyrocks** [comment]
I played around with the json flag - It would work - but the json response is huge when having >1000 migration records.
I still think my original suggestion to allow displaying partial data would have been helpful - all the more so when it can be parsed as a json.

**Comment by MikielAgutu** [comment]
@pyrocks Yes the JSON output will be large. The motivation behind the feature was to enable users to easily extract the information they need. This means we don't have to support various levels of granularity and detail in the output.

If you [parse it using a library like jq](https://stedolan.github.io/jq/), you can suppress the output from your build log and only see the relevant information.

Something like: `flyway info | jq '.schemaVersion'`.

Does that help?

**Comment by pyrocks** [comment]
I don't like the fact that the response from the command is huge - but it would definitely work. A fair solution to the requirement. Closing.
