### ISSUE TITLE
Using flyway with no jarDirs specified means flyway uses the default path and when the default path doesn't exist, it fails

### ISSUE THREAD

**Issue by CMCDragonkai** [flyway/flyway#2390]
I'm using the 5.2.4 community edition.

When running flyway. I noticed that even though nothing is specifying the `jarDirs` option, it has by default been set to: `/nix/store/kg3pqmrbm11a7z268p3kblr3wz2038cr-flyway-5.2.4/share/jars`.

However this directory does not exist on NixOS. So when I try to run flyway, I always get this error:

```
ERROR: Directory for Java Migrations not found: /nix/store/kg3pqmrbm11a7z268p3kblr3wz2038cr-flyway-5.2.4/share/jars
```

Now I have to set it to an empty directory to make it work. Is there a way to make flyway not automatically by default set the `jarDirs` option, and if it does, if the directory path doesn't actually exist assume that there's no migrations in `jarDirs` anyway so we get a graceful skip instead of a hardline error.

Alternatively since I am a contributor on NixOS, I can PR to configure flyway to point to an empty directory by default. However I'm not sure how to do this with flyway in such a way that it can be easily overridden.

**Comment by axelfontaine** [comment]
By default, the Flyway jar directory is set to `<install-dir>/jars`. Since the installation you have has obviously be customized, it is the responsibility of whoever customized it to ensure that either the default jar directory still exists or the default value for jarDirs is set to something that makes sense. The best option is of course not to mess with the default installation structure.

Works as designed.

**Comment by CMCDragonkai** [comment]
How do you the default value of jarDirs?

On 21 May 2019 01:26:07 GMT+10:00, Axel Fontaine <notifications@github.com> wrote:
>By default, the Flyway jar directory is set to `<install-dir>/jars`.
>Since the installation you have has obviously be customized, it is the
>responsibility of whoever customized it to ensure that either the
>default jar directory still exists or the default value for jarDirs is
>set to something that makes sense. The best option is of course not to
>mess with the default installation structure.
>
>Works as designed.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/flyway/flyway/issues/2390#issuecomment-494035146

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by michael-pe** [comment]
Remove the below line from flyway.conf file. It would work post that. 
flyway.jarDirs=None
