### ISSUE TITLE
Support for TimescaleDB hypertables

### ISSUE THREAD

**Issue by joaocc** [flyway/flyway#2391]
Hi,
Do you support (or are planning to support) PostgreSQL databases which use hypertables (from TimescaleDB extension)?
Thanks

**Comment by axelfontaine** [comment]
We haven't tested this. Are you hitting any specific issues?

**Comment by joaocc** [comment]
No, only assessing Flyway for our next project. But I know that backups/restores for TimescaleDB require a flag to be set, and that a number of schemas are created automatically when you install the extension. This is both a technical (flag and schemas) and licensing (schemas) impact.

**Comment by axelfontaine** [comment]
We have no short terms plans to officially support this. That being said, it is highly probable the Community Edition will work just fine as it is.

**Comment by AtulPundir1** [comment]
Hi @joaocc , 
Have you tried updating postgres with timescaleDB extension?
Is there anything that needs to be taken care for proper implementation.

@alextercete , is the support for timescaleDB added by now?

Thanks

**Comment by MikielAgutu** [comment]
@AtulPundir1 Timescale DB support is not in the product yet. As you can see it's in our 'On the radar' milestone. We review the issues here regularly. Popular issues that fit with Flyway's direction as a product are likely to be bumped up to a version milestone at some point.

**Comment by chrls3rd-github** [comment]
Hello @MikielAgutu - I am new to TimescaleDB but have used PostgreSQL and Flyway before. From the questions about TimescaleDB support, the nature of the request is not completely clear.
Would it be fair to say that, given the TimescaleDB extension had installed in a PostgreSQL instance, a database and extensions schema had been created, and the timescaledb extension had been created in the extensions schema - Flyway would be able to apply subsequent migration steps that create and alter tables, including hyper tables?
And, if not, has there been an update (since Apr 2020) to its status in your "On the radar" milestone? - - Thanks!

**Comment by DoodleBobBuffPants** [comment]
This isn't something we have tested against, however it might still work. Would you be able to try this out and let us know?

**Comment by chrls3rd-github** [comment]
I did try this out, and it does work. 
What I tried:
- Used local PostgreSQL in the form of Postgres.app (including PostGIS), on MacOS 10.14.6, Postgres 12, with TimescaleDB 2.0.0-rc4 built from source, and installed, according to [this writeup](https://prathamesh.tech/2020/07/23/installing-timescaledb-on-mac-os-x-with-postgres-app/)
- Used "Hello Timescale" [tutorial](https://docs.timescale.com/latest/tutorials/tutorial-hello-timescale)
- Created database; created separate schema "extensions"; created schema for tutorial data.
- In schema "extensions", executed CREATE EXTENSION IF NOT EXISTS timescaledb;
- In Spring Boot app (Spring Boot version 2.4.1, default flyway-core dependency is 7.1.1), created two Flyway migrations:
- V1__create-hypertable.sql: creates main data table, hypertable, and some indices
- V2__create-and-load.sql: creates other PostgreSQL tables and inserts data

That worked fine.

- Copied main data file into main data table
- Worked with tutorial instructions, until section using PostGIS feature; then added third Flyway migration:
- V3__geo_upgrade.sql: creates postgis extension in extensions schema, alters main data table, calculates geo column values.

When application restarted, third migration applied (took >20 minutes to update large number of rows), worked fine.

- Completed tutorial's instructions using time_bucket and PostGIS functions.

Also note:

- For tutorial, set search path to tutorial and extensions schemas.
- Migrations executed upon instantiation of DataSource Bean, invoked via (Flyway.configure()).migrate() including aforementioned schemas (so as to avoid use of public schema).

**Comment by DoodleBobBuffPants** [comment]
Thanks for trying it out and letting us know!
