### ISSUE TITLE
DB2: Clean excludes user-defined functions based on new classifications

### ISSUE THREAD

**Issue by armondoortega** [flyway/flyway#2395]
When running clean on a DB2 database it was noticed that not all user-defined functions are being dropped.

The following query is using an older deprecated catalog view and function classification. 
```java
 @Override
    protected Function[] doAllFunctions() throws SQLException {
        List<Map<String, String>> rows = jdbcTemplate.queryForList(
                "select p.SPECIFICNAME, p.FUNCNAME," +
                        " substr( xmlserialize( xmlagg( xmltext( concat( ', ', TYPENAME ) ) ) as varchar( 1024 ) ), 3 ) as PARAMS" +
                        " from SYSCAT.FUNCTIONS f inner join SYSCAT.FUNCPARMS p on f.SPECIFICNAME = p.SPECIFICNAME" +
                        " where f.ORIGIN = 'Q' and p.FUNCSCHEMA = ? and p.ROWTYPE = 'P'" +
                        " group by p.SPECIFICNAME, p.FUNCNAME" +
                        " order by p.SPECIFICNAME", name
        );
```

The ORIGIN filter appears to need to include 'E' and 'U' to include all user-defined functions. 
based on the [DB2 Documentation](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0001045.html) 

Which version and edition of Flyway are you using? 5.2.0 Enterprise Edition
Which client are you using? Command-line
Which database are you using (type & version)? Db2 10.5+
Which operating system are you using? RHEL 6/7

**Comment by axelfontaine** [comment]
Thanks for the report. Please share the smallest possible SQL snippet that we could use to reproduce this issue.

**Comment by axelfontaine** [comment]
Thanks again for reporting. We went ahead and rewrote the relevant code to use the new `ROUTINES` view instead and this was fixed as part of that process.

**Comment by armondoortega** [comment]
Thanks a lot! Appreciate the quick turn around. If you end up still wanting me to send over some SQL just let me know.
