### ISSUE TITLE
Q: migrate execute order

### ISSUE THREAD

**Issue by pocelka** [flyway/flyway#2396]
Hi, 

I'm in a process of researching various tools for DB deployment and flyway came in a way. I did not find this in the documentation. Is there a way how you can specify execution order for repeatable tasks? 

I will try to explain on example (Oracle DB).
- At day1 developer creates package1. Package will be marked as repeatable.
- At day2 developer creates package2 and modified package1 so package 1 would not compile properly unless package2 exists. Package 2 will be marked as repeatable.

My understaing was that repeatable tasks don't have to be versioned (indication in file name), so developer did not include version in the file name. However there might be cases when it is needed.

Is there a way how to specify correct order? Or how you usually deal with this kind of situation?

**Comment by axelfontaine** [comment]
As stated in the [docs](https://flywaydb.org/documentation/migrations#repeatable-migrations):

> Repeatable migrations are applied in the order of their description.
