### ISSUE TITLE
SQL Server: clean doesn't work for system-versioned temporal tables

### ISSUE THREAD

**Issue by kwood612** [flyway/flyway#2397]
###### Which version and edition of Flyway are you using?
5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
SQL Server 2016

###### Which operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway clean

###### What did you expect to see?
No errors and a clean schema

###### What did you see instead?
ERROR:
Unable to drop 'mytableHistory'
-------------------------------------------------
SQL State  : S0001
Error Code : 13552
Message    : Drop table operation failed on table 'mytableHistory' because it is not supported operation on system-versioned temporal tables.

**Comment by axelfontaine** [comment]
Please share the smallest possible SQL file that can be used to reproduce the issue.

**Comment by kwood612** [comment]
CREATE TABLE [dbo].[TestTable](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [Name] [varchar](50) NOT NULL,
    [SysStartTime] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
    [SysEndTime] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
    CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	),
    PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
)
WITH (SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [dbo].[TestTableHistory] ))

**Comment by axelfontaine** [comment]
Thanks for the example. This has now been fixed.
