### ISSUE TITLE
PostgreSQL 12 support

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#2398]
PostgreSQL 12 Beta 1 announcement: https://www.postgresql.org/about/news/1943/

**Comment by severn-everett** [comment]
Is it possible to just focus on getting Flyway 6 and the promised PostgreSQL 11 compatibility out the door before looking at PostgreSQL 12? Flyway 5's lack of compatibility with PostgreSQL 11 is directly blocking our migration to the latter, and I'm worried that continually tacking on new issues to the Flyway 6 initial release is only going to delay its release even further. If we fall behind by two PostgreSQL releases, we might have to drop Flyway and look for another DB schema migration tool.

**Comment by ameenhere** [comment]
@axelfontaine  I still get a warning when I use flyway v6.0.7 with postgresql 12. The commit above indicates 

> recommendFlywayUpgradeForMajorVersion("12"):

Is pg12 supported?
