### ISSUE TITLE
Issue with aurora sql

### ISSUE THREAD

**Issue by vignesh17** [flyway/flyway#2400]
###### Which version and edition of Flyway are you using?

5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command-line as a part of code pipeline build.

###### Which database are you using (type & version)?

aurora sql 5.6

###### Which operating system are you using?

linux docker provided by aws code build

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I am trying to migrate tables to aurora sql as a part of the code pipeline. After giving the details, when I tried to migrate, i am getting error stating communication link failure. 

###### What did you expect to see?
I was expecting my set of create instructions to create tables in my database

###### What did you see instead?
A error stating communication link failure.

**Comment by axelfontaine** [comment]
This issue tracker is for Flyway issues only. This is almost certainly an issue in your setup. Please contact AWS support or post your question on StackOverflow instead.
