### ISSUE TITLE
Flyway Migrate

### ISSUE THREAD

**Issue by vignesh17** [flyway/flyway#2401]
<img width="968" alt="Screen Shot 2019-05-23 at 2 20 33 PM" src="https://user-images.githubusercontent.com/10937830/58280333-f5c4e000-7d65-11e9-869f-84424aa7dbb2.png">
What does the instance in the URL mean?
Where do I look it up in my aurora mysql?

**Comment by axelfontaine** [comment]
That's a standard AWS term. Just use your hostname as shown in the AWS Console.
