### ISSUE TITLE
PLS-00103 when using Oracle TIMESTAMP Literal with forward slash escapes

### ISSUE THREAD

**Issue by NikoSperat** [flyway/flyway#2402]
###### Which version and edition of Flyway are you using?

4.2.0, 5.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
Can't try latest version since the community edition does no longer support Oracle 12.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

Oracle 12.1

###### Which operating system are you using?

Windows 10

###### What did you do?
Tried running a migrationscript containing [Oracle Literal TIMESTAMP](https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements003.htm#BABGIGCJ) in combination with `/` escape sequences. A broken (or should I say a reproducable) example is the following script

```
CREATE TABLE test(id NUMBER NOT NULL CONSTRAINT test_pk PRIMARY KEY);

/
BEGIN
  dbms_output.put_line(TIMESTAMP'2017-08-09 03:00:00');
END;

/
BEGIN
  dbms_output.put_line(TIMESTAMP'2017-08-09 03:00:00');
END;
```

###### What did you expect to see?

A work script, Table creation and timestamp output.

###### What did you see instead?

```
-------------------------------------------
SQL State  : 65000
Error Code : 6550
Message    : ORA-06550: Zeile 5, Spalte 1:
PLS-00103: Encountered the symbol "/"
Location   : 
Line       : 4
Statement  : BEGIN
  dbms_output.put_line(TIMESTAMP'2017-08-09 03:00:00');
END;

/
BEGIN
  dbms_output.put_line(TIMESTAMP'2017-08-09 03:00:00');
END;
```

The workaround for now is using TO_TIMESTAMP instead. I tried a single PL/SQL block without `/` escapes which does work

**Comment by axelfontaine** [comment]
Thanks for reporting. Flyway's parser has been rewritten from the ground up for 6.0.0 and this issue has already been fixed as part of that process.
