### ISSUE TITLE
Add Majestic Modular Monolith Support

### ISSUE THREAD

**Issue by asaikali** [flyway/flyway#2404]
This is a new feature request to make it easy to support the notion of modules in Flyway. It is inspired by [Majestic Modular Monoliths](https://www.youtube.com/watch?v=BOvxJaklcr0) talk and a few specific use cases that I have run into over the years using Flyway. Below is an example of a use case that illustrates why this feature would be useful. 

**Email outbox  module use case** 

I have a small library about 500 lines of code that is used to send emails as part of the current database transaction it has a very simple interface.

```java
@Service
public class EmailOutboxService {
    @Transactional(propagation = Propagation.REQUIRED)
    void add(Email email) throws InvalidEmailAdressException { }
}
```
The `add` method writes emails into database table as part of the current transaction.
```sql
CREATE TABLE evc.email (
	pkey 	     SERIAL PRIMARY KEY,
	version      evc.version_domain,
	insert_ts    evc.insert_ts_domain,
	update_ts    evc.update_ts_domain,
	sent         BOOLEAN DEFAULT FALSE NOT NULL,
	to_address   evc.email_domain NOT NULL,
	from_address evc.email_domain NOT NULL,
	subject      VARCHAR(1024) NOT NULL,
	body         TEXT         NOT NULL	
);
CREATE index unsent_emails_index ON evc.email(pkey) WHERE sent=false;
```
A background thread checks for unset emails and delivers them to email server. It knows how to handle timeouts / outages / reporting ... etc. 

I have used this library a few times as part of various projects that I have worked on.  To use the library I have to. 

1. Add email-outbox to my maven or gradle 
2. go into my db.migration folder and the database table for the library 

I would like eliminate step 2 above. Just add my email-outbox.jar to my app and then have flyway automatically pickup the migrations that are part of the email-outbox library and apply them. 

Another issues  occurs when I add a new feature to the library that requires a new database table or change to the existing table I would like to package those migrations in the email-outbox.jar which would the library users life easier just bump up the version number of the email-outbox and everything should just work.

When composing an app out of modules some of the modules need to have their own self contained tables that no other part of the app accesses. These modules effectively have their own line of database migrations that is independent of the app they are in. I would like to able to somehow represent this concept in Flyway. 

Having the notion of modules built into flyway so that a single flyway instance for the app can handle all the modules that flyway discovers on the classpath would make it easier to deliver on the idea of the Majestic Modular Monolith.

**Comment by axelfontaine** [comment]
This is already possible today.

Simply ask Flyway to scan `db/migration` and 
- put your migrations for module1 in the module1 jar under `db/migration/module1`
- put your migrations for module2 in the module2 jar under `db/migration/module2`
- ...

Flyway will find them all, and apply them in order.

**Comment by asaikali** [comment]
How do I give the scripts different version numbers so Flyway knows the right order to apply them in without previous co-ordination between the module to pick version ranges.

For example module 1 picks `V1__module1_migration.sql` and module 2 picks `V1__module2_migration.sql`

How does Flyway figure out which versions to pick? 

If I publish the module dot a maven central how do I co-ordinate my versioning number with unknown users?

**Comment by feoktant** [comment]
@asaikali I think you could name as `V1.module1__migration.sql`, `V1.module2__migration.sql`.
This will not resolve issue with developers outside company, but could be used inside org
