### ISSUE TITLE
flyway modifying sql_mode instead of using the default sql_mode of mysql server

### ISSUE THREAD

**Issue by salmanasiddiqui** [flyway/flyway#2408]
###### Which version and edition of Flyway are you using?
5.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes I can

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MySQL v5.6

###### Which operating system are you using?
Mojave 10.14.5

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Im running `migrate`, the issue is that when flywaydb runs migration it changes the sql_mode. The global sql_mode of mysql server is NO_ENGINE_SUBSTITUTION, but when flywaydb executes migrations the session sql_mode is STRICT_TRANS_TABLE, NO_ENGINE_SUBSTITUTION. This causes some of our migrations to fail.

###### What did you expect to see?
I expect the `migrate` command to finish successfully as the migration works fine if sql_mode is NO_ENGINE_SUBSTITUTION

###### What did you see instead?
failure on one migration where we insert some data but don't pass values for all the columns.

**Comment by axelfontaine** [comment]
No, we don't ask you can see from this class: https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLConnection.java

What makes you believe so? Please share a small GitHub repo that reproduces the issue, including a `docker-compose.yml` to fire up the server.

**Comment by salmanasiddiqui** [comment]
I will do that when I will get some time.

A bit more to add, I found that jdbc now uses `jdbcCompliantTruncation=true` for which `sql_mode=STRICT_TRANS_TABLE` is required. So setting `sql_mode=NO_ENGINE_SUBSTITUTION` doesn't work unless we set `jdbcCompliantTruncation=false`.

So I tried the following things in flyway:
First, 
`flyway.url=jdbc:mysql://localhost:3306?serverTimezone=America/New_York&jdbcCompliantTruncation=false&sessionVariables=sql_mode=NO_ENGINE_SUBSTITUTION`
but this fails with incorrect connection string format error.

Then I tried:
`flyway.url=jdbc:mysql://localhost:3306?serverTimezone=America/New_York&jdbcCompliantTruncation=false`
and having `beforeEachMigrate.sql`
```
SET @@sql_mode='NO_ENGINE_SUBSTITUTION'
```
but the sql_mode still included STRING_TRANS_TABLE.

**Comment by axelfontaine** [comment]
Hmmm placing `SET @@sql_mode='NO_ENGINE_SUBSTITUTION'` in `beforeEachMigrate.sql` should actually work. Are you certain it doesn't? Also did you try to configure it as [initSql](https://flywaydb.org/documentation/commandline/migrate#initSql)?

**Comment by salmanasiddiqui** [comment]
Indeed. I started getting another failure and didn't notice it and responded here.

Actually I don't need `beforeEachMigrate.sql` once I add `jdbcCompliantTruncation=false` to my connection string. Cause then mysql connection starts to use on the global sql_mode.

To sum this up, jdbc now uses `jdbcCompliantTruncation` which requires `STRICT_TRANS_TABLE`. To turn this sql_mode off, we need to set `jdbcCompliantTruncation=false` in connection string. After this sql_mode will not be modified by your connection and the global sql_mode will be used.
