### ISSUE TITLE
Dollar-quoted section fails when attempting to use hex literal

### ISSUE THREAD

**Issue by dbrennan** [flyway/flyway#2411]
###### Which version and edition of Flyway are you using?
5.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
Postgres 9.5

###### Which operating system are you using?
Linux

###### What did you do?
```sql
create table foo (
  id bigint primary key not null,
  value bigint not null
);
do
$$
begin
  declare foreignKey bigint;
  -- full code gets foreign key from another table for insert, removed for brevity
  insert into foo (id, value) values (1, x'1ff'::bigint);
end
$$ language plpgsql;
```

###### What did you expect to see?

successfully applied, works in pgadmin, dbeaver

###### What did you see instead?

SQL State  : 42601
[ERROR] Error Code : 0
[ERROR] Message    : ERROR: unterminated dollar-quoted string at or near "$$

This works if the x'1ff'::bigint is replaced with a literal value like 10.

**Comment by axelfontaine** [comment]
This has been fixed as part of the parser rewrite in 6.0.0-beta2.
