### ISSUE TITLE
Enforce ignoreFutureMigrations=false for migrate when validateOnMigrate=false

### ISSUE THREAD

**Issue by IgnasD** [flyway/flyway#2412]
###### Which version and edition of Flyway are you using?

5.2.4 community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

Latest stable

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

10.2.24-MariaDB-1:10.2.24+maria~bionic

###### Which operating system are you using?

Ubuntu 18.04

###### What did you do?

1. Created two simple SQL migrations, V1 and V2.
2. Perfomed migration.
3. Removed V2 migration SQL file.
4. Performed migration again.

Migration was called with default configuration except:
- validateOnMigrate(false)
- ignoreFutureMigrations(false)

###### What did you expect to see?

Exception during migrate.

###### What did you see instead?

Warning was logged, migration succeded:
> WARNING: Schema `sandbox2` has a version (2) that is newer than the latest available migration (1) !
> INFO: Schema `sandbox2` is up to date. No migration necessary.

###### Comment

It looks like currently there is no way to do both, ignore changed checksum of SQL file, and also fail on missing future migration.

**Comment by axelfontaine** [comment]
Hmmm... I can see your point. However the ignore* settings have been strictly tied to validate for now. I am unsure this should be changed. Leaving this open for future consideration.

**Comment by IgnasD** [comment]
If `validateOnMigrate` is sort of a master switch for `ignore*` settings, then maybe the best course of action is to introduce `ignoreChecksum` setting with default value of false? This way backwards compatibility will be preserved, and users could choose to ignore checksum without losing ability to validate other aspects.

Also, I'd say that documentation is not entirely accurate. Description for validateOnMigrate says:

> Whether to automatically call validate or not when running migrate.
> For each sql migration a CRC32 checksum is calculated when the sql script is executed. The validate mechanism checks if the sql migration in the classpath still has the same checksum as the sql migration already executed in the database.

From this description it seems like validateOnMigrate setting is responsible for checksum only.

**Comment by MikielAgutu** [comment]
@IgnasD, what would you like to achieve with this behavior? What problem would it solve?

**Comment by IgnasD** [comment]
My goal is to disable checksum validation without disabling other types of validation (future migrations, in my specific case). Currently, there is no way to achieve this, afaik.

As in use-case. Goal is to prevent older versions of services from using databases with newer schemas, which might happen due to some misconfiguration. And I need to turn off checksum validation because tiny amount of my migrations tend to change a tiny bit during time (e.g. having to rewrite some non-standard optimized SQL for a more generic SQL to support different RDBMS). I know this is a problem in itself, but it is what it is, and I don't think it invalidates this issue.

Anyway, I've worked around this issue by implementing custom validation logic that meets my needs by utilising `MigrationInfoService`.

**Comment by MikielAgutu** [comment]
@IgnasD With Flyway 7 we've improved the API for validate, and also introduced JSON output for validate also. We think this should give you to flexibility to write your own validation rules.

Does that help? I don't think we can commit to doing this within Flyway itself as it's quite a niche problem.

**Comment by IgnasD** [comment]
Unfortunately, it'll probably be quite some time till we upgrade to Flyway 7, so I cannot give any immediate feedback.

However, as I stated in the previous post, I have found a viable solution even in pre-7 versions. `MigrationInfoService` returned by `Flyway.info()` had enough information so I could implement my own additional validation logic before calling `migrate()`.

**Comment by MikielAgutu** [comment]
Given there's a viable workaround I'll close this one.
