### ISSUE TITLE
Incorrect detection of GO keyword inside identifiers

### ISSUE THREAD

**Issue by rglidden** [flyway/flyway#2414]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 6.0.0-beta2 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Issue only occurs on Flyway 6.0.0-beta2. Issue does not occur on Flyway 5.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command Line

###### Which database are you using (type & version)?

SQL Server 2017 Developer Edition

###### Which operating system are you using?

Windows 10, 1903

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Create a migration with the following SQL statements, which are valid in SQL Server. Run "flyway migrate":

```sql
CREATE OR ALTER PROCEDURE [dbo].[Test]
AS
BEGIN
	DECLARE @DoNotGO INT;
	RETURN 0;
END;
```

###### What did you expect to see?

Migrations successfully applied.

###### What did you see instead?

```
ERROR: Migration of schema [dbo] to version 0.0.0.3 - FlywayTest failed! Changes successfully rolled back.
ERROR:
Migration V0.0.0_3__FlywayTest.sql failed
-----------------------------------------
SQL State  : S0001
Error Code : 102
Message    : Incorrect syntax near '@DoNot'.
Location   : Operational\baseline\10.10.0\Framework\V0.0.0_3__FlywayTest.sql (C:\git\SmartSuite\Database\Flyway\Operational\baseline\10.10.0\Framework\V0.0.0_3__FlywayTest.sql)
Line       : 1
Statement  : CREATE OR ALTER PROCEDURE [dbo].[Test]
AS
BEGIN
        DECLARE @DoNot
```

It looks like Flyway is interpreting the `GO` inside the variable `@DoNoGO` as a keyword, when it should not be.  Interestingly, changing the case on `GO` allows it to work:
```sql
CREATE OR ALTER PROCEDURE [dbo].[Test]
AS
BEGIN
	DECLARE @DoNotgo INT;
	RETURN 0;
END;
```

**Comment by axelfontaine** [comment]
Thanks again for another excellent and well researched bug report. This was incredibly valuable in tracking down the root cause for this. Fixed.
