### ISSUE TITLE
Organize migrations by database objects (a preprocessor)

### ISSUE THREAD

**Issue by agentgt** [flyway/flyway#2416]
The following is an idea for discussion. I can make separate preprocessor and feed it into flyway but I wanted to run it by you first (@axelfontaine).
 
We have gotten to the point where SQL migration scripts are really making it confusing what actually is in the database.

Ideally we would like the SQL scripts to be organized by object and not migration version just like you would organize code.

There are project(s) that are doing this but are exceedingly complicated and/or lack the maturity that flyway does (e.g. [Obevo](https://github.com/goldmansachs/obevo) by GS).

So here is my idea that doesn't require a change to Flyway.

A directory with a list of migrations e.g.:
 * V_001
 * V_002

Those migration files are just  plain text files with list of file names to SQL object files in order of dependency.

And a directory of SQL objects (e.g.):
 * CUSTOMER_TABLE.sql
 * ORDER_TABLE.sql

The SQL objects files have some meta data comments which will be described below.

Now Lets say 

* V_001 points CUSTOMER_TABLE.sql
* V_002 points to CUSTOMER_TABLE.sql, ORDER_TABLE.sql

The above order is important (ie order table before customer table).

CUSTOMER_TABLE.sql contents would look like:

```
---- CHANGE=V_001
CREATE TABLE CUSTOMER();
---- CHANGE=V_002
ALTER TABLE CUSTOMER ADD COLUMN SOME_ID;
```

ORDER_TABLE.sql

```
---- CHANGE=V_002
CREATE TABLE ORDER();
-- ADD a FKEY to CUSTOMER some id
```

Anyway hopefully the above you get the gist of how it works.

Now you just run it through preprocessor which will generate

```
V_001.sql
V_002.sql
```

If V_001.sql is changed in your source control you know you have messed up and touched something within `---- CHANGE=V_001`.

Curious what your thoughts are?

We aren't Boxfuse customers but this might be a feature that would turn us into ones!

**Comment by axelfontaine** [comment]
Thank you for your suggestion. We already support some form of organising SQL scripts by object with repeatable migrations. See https://flywaydb.org/documentation/migrations#repeatable-migrations

This works great for many kinds of objects, except unfortunately for tables.

While I can see your suggested solution being useful in specific scenarios, it is too niche a requirement and it wouldn't carry its conceptual weight for the product at this time.

**Comment by agentgt** [comment]
As a owner of a software company I always like to hear others use cases and or how I can gain customers. Thus I appreciate the quick response time and consideration.

> Thank you for your suggestion. We already support some form of organising SQL scripts by object with repeatable migrations. See https://flywaydb.org/documentation/migrations#repeatable-migrations

About that....
Repeatable Migrations in my opinion are broken for us as I reported here: https://github.com/flyway/flyway/issues/1999

Flyway really needs a hook to understand about app versions.

We have workaround in testing where we have a special table that has the version of the app currently deployed. We don't let flyway run if the app booting up has a lesser version.

> While I can see your suggested solution being useful in specific scenarios, it is too niche a requirement and it wouldn't carry its conceptual weight for the product at this time.

Well I disagree. And so do several folks. Please see when you have a chance Obevo and or read this article: https://www.infoq.com/articles/Obevo-Introduction/ .

At this point it is really painful to use Flyway from a developers perspective once you have 100s - 1000s of migrations.

Just the naming of SQL files is ripe with potential conflicts and or errors (e.g. merge). Currently we follow a date naming paradigm (because of merge issues) instead of just monotonically incrementing but its still arduous and annoying to name the SQL file with the date. 

And then there is just trying to figure out what a current table is and or its history. Sure you can go look directly in the database and then compare with previous code but this is painful.

And going back to repeatable migrations... you have to create an arbitrary prefix to get the correct sort order (think unix init config scripts) so that Flyway will load the repeatables in the correct dependency order (for stored procedures). At this point developers are giving up and just putting it all in one gigantic repeatable migration script.

If I could we would move to Obevo but it doesn't support clustering yet. I honestly think its design is the future. Life is too short writing 1000s of V_[0-9]+ .

Anyway hopefully the above wasn't too much of a rant and it doesn't matter much anyway as I can just write our own preprocessor just like I had to write our own version checker for the repeatable migrations.  

In the mid-early 2000s I wrote a SQL migration tool in Python . It didn't have cluster support but it did have md5 checksums... I had plans to implement something like the above but never got around to it.... so maybe it is niche.
