### ISSUE TITLE
Integrate Oracle SQL*Loader for faster data import

### ISSUE THREAD

**Issue by apexbine** [flyway/flyway#2428]
Inserting reference data (Stammdaten, Lookup-Werte) via single SQL statements is relatively slow. For small amounts of data this is not a problem, but it get's annoying when it comes to larger data sets.

Oracle has a tool calles SQL*Loader which is FAST. 
It needs a control file which describes the source data file, its structure, where to put the data, and what to do with 'bad' records.

It would be great if we could call it from Flyway like we can all SQL and PL/SQL scripts, because it would save a lot of time.

Documentation:
https://docs.oracle.com/en/database/oracle/oracle-database/18/sutil/oracle-sql-loader.html#GUID-8D037494-07FA-4226-B507-E1B2ED10C144

**Comment by Prathamesh-Joshi** [comment]
This feature is highly recommended for enterprise level database setup where millions of records can be loaded in few seconds via customized Control (.CTL) files and logs,BAD file,DISCARD file can give exact idea of records loaded/discarded with errors in log file. I hope we get facility to use SQLLDR.exe to use this beast.
Generally this can be grouped with sqlplus or customized batch files to leverage this as per the need of huge migration.

**Comment by DoodleBobBuffPants** [comment]
This can now be performed with arbitrary script migrations. You can read more about this and other V7 features [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
