### ISSUE TITLE
Using flyway to create indexes only

### ISSUE THREAD

**Issue by krismorte** [flyway/flyway#2430]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 5.2.4 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MSSQL 2014

###### Which operating system are you using?
Linux arch

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I'm trying to control just the indexes scripts I've already tried V_, R_ and NTV_ script types

###### What did you expect to see?
I'm trying to createa index

###### What did you see instead?
The migrations run with no error or warning message. The script containing the index is totally ignore

Successfully validated 120 migrations (execution time 00:01.478s)
Current version of schema [dbo]: 1
Schema [dbo] is up to date. No migration necessary.

**Comment by axelfontaine** [comment]
This issue tracker is for Flyway issues and feature requests only. Please post general questions on StackOverflow under the Flyway tag where the community can answer them.
