### ISSUE TITLE
Undo-Repair feature

### ISSUE THREAD

**Issue by KiruthikaSS** [flyway/flyway#2444]
###### Which version and edition of Flyway are you using?
flywaydb.pro-6.0.0-beta2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

JAVA API

###### Which database are you using (type & version)?

Oracle 12c

###### Which operating system are you using?

Windows10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?

Wouldn't it be nice, if we have repair command/new undo-repair command this way, 
Say if **V11__Desc.sql** **fails** and **U11__Desc.sql is available**. Repair command will,

- Execute undo file U11__Desc.sql. Yes, I understand, it will throw error since some of the objects in V11 is not created yet - can we just log it and proceed further.

- Now delete the failed record from flyway_schema_history table.

- This way, we avoid manual clean up of left behind objects.

###### What did you see instead?
Say if **V11__Desc.sql** **fails** and **U11__Desc.sql is available**. Repair command will,
- Now delete the failed record from flyway_schema_history table.

- Here, manual cleanup of left behind objects is required.

Please let me know your thoughts on this.

Thanks.

**Comment by MikielAgutu** [comment]
We're not convinced Flyway should work this way. The best approach for failed migrations is to manually clean up after the failure, repair, and try again. In the best of times undo scripts aren't 100% reliable. Trying to use a 'full' undo script to revert a partially applied migration seems like it's inviting trouble.
