### ISSUE TITLE
Cockroach 19.x support

### ISSUE THREAD

**Issue by rkettelerij** [flyway/flyway#2445]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 5.2.4 by Boxfuse 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Via Spring Boot, so the Java API

###### Which database are you using (type & version)?
CockroachDB 19.1

###### Which operating system are you using?
macOS

###### What did you do?
Start a flyway migration against CockroachDB 19.1

###### What did you expect to see?
No warning.

###### What did you see instead?
A warning saying: `Flyway upgrade recommended: CockroachDB 19.1 is newer than this version of Flyway and support has not been tested.`

Note that the migration ran fine. No issues at all. So this ticket is purely about the warning message.

Update: https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/cockroachdb/CockroachDBDatabase.java#L66

**Comment by juliahayward** [comment]
We've run all our existing tests against 19.1 and all pass. We're currently talking to Cockroach about issues around retries that exist in older versions of Flyway; if you see any problems in that regard, please do raise a new issue.

**Comment by juliahayward** [comment]
Fixed in 6.0.5.

**Comment by juliahayward** [comment]
Just to add to this, we've pulled the 19.2 Docker image and tested against that as well.
