### ISSUE TITLE
Migration files with hard spaces don't work anymore

### ISSUE THREAD

**Issue by AigleeK** [flyway/flyway#2446]
###### Which version and edition of Flyway are you using?
Flyway 6 Beta Nightly Snapshot

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-Line

###### Which database are you using (type & version)?
SQL Server 2017

###### Which operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Any SQL statement using a hard space instead of a regular space causes the issue

###### What did you expect to see?
Migration should have worked. It works in Flyway 5

###### What did you see instead?
ERROR: Unable to parse statement in ...\Migrations\V10.12.0_201906211538__File_Name.sql at line 1 col 1: Unknown char   encountered on line 1 at column 3

**Comment by juliahayward** [comment]
Can you share the exact migration .sql file please? Or failing that, a minimal reproduction?

**Comment by AigleeK** [comment]
Attaching one of the failing files :)
[V10.12.0_201905012014__AddConfigurationTypeToScenarioComposer.sql.zip](https://github.com/flyway/flyway/files/3432360/V10.12.0_201905012014__AddConfigurationTypeToScenarioComposer.sql.zip)

**Comment by juliahayward** [comment]
Great, thankyou!

**Comment by juliahayward** [comment]
Thankyou very much for the report! A fix is now pushed and will be rolled up into the v6.0 release.
