### ISSUE TITLE
Flyway clean does not remove postgres extensions

### ISSUE THREAD

**Issue by will-sargent-eero** [flyway/flyway#2448]
###### Which version and edition of Flyway are you using?

6.0.0-beta2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

[info] Flyway Community Edition 6.0.0-beta2 by Boxfuse
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

flyway-sbt with beta2 override:

```
// Needed for running "flywayClean" with postgresql 11 client
libraryDependencies += "org.flywaydb" % "flyway-core" % "6.0.0-beta2"
addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "5.2.0")
```

###### Which database are you using (type & version)?

PostgreSQL 11.4

"org.postgresql" % "postgresql" % "42.2.5" jdbc driver

###### Which operating system are you using?

MacOS

❱ uname -a
Darwin 38f9d32cde81.ant.amazon.com 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

```
sbt flywayMigrate
sbt flywayClean
sbt flywayMigrate
```

###### What did you expect to see?

A clean upgrade

###### What did you see instead?

There is a bug in the way that Flyway handles PostgreSQL extensions: if you create an extension, clean doesn't drop it.  Instead, you have to run the DROP explicitly:

```sql
DROP EXTENSION pgstattuple;
```

**Comment by juliahayward** [comment]
We will defer this for now as we're investigating the option for introducing `clean` at the database level as an alternative to the schema level. We will revisit it for the 6.1 release.
