### ISSUE TITLE
Oracle CREATE VIEW ... as WITH <CTE> ...

### ISSUE THREAD

**Issue by jakubek2085** [flyway/flyway#2453]
###### Which version and edition of Flyway are you using?

5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using (type & version)?

Oracle 12c (12.2)

###### Which operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

migrated script containing "CREATE VIEW ... as WITH <CTE> ..." (common table expression)

###### What did you expect to see?

BUILD SUCCESS

###### What did you see instead?

Java version: 1.8.0_131, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_131\jre    
[DEBUG]    com.oracle:ojdbc8:jar:12.2.0.1.0:provided    
[INFO] Flyway Community Edition 5.2.4 by Boxfuse
[INFO] Database: jdbc:oracle:thin:@bdlg3400.na.pg.com:1525:ioptd101 (Oracle 12.2)
[DEBUG] Driver  : Oracle JDBC driver 12.2.0.1.0

[ERROR] Migration R__SOME_VIEW_VW.sql failed
[ERROR] --------------------------------------
[ERROR] SQL State  : 42000
[ERROR] Error Code : 933
[ERROR] Message    : ORA-00933: (non-english description)
[ERROR] Location   : sql\Views\R__SOME_VIEW_VW.sql (...\sql\Views\R__SOME_VIEW_VW.sql)
[ERROR] Line       : 7
[ERROR] Statement  : CREATE OR REPLACE VIEW some_view_vw as
[ERROR] WITH
[ERROR] lokd_gate AS
[ERROR] (
[ERROR]     SELECT
[ERROR]         iglp.p_skid,
[ERROR]         LISTAGG(g.g_code, ',') WITHIN GROUP (ORDER BY g.g_code) AS lokd_gate_lst
[ERROR]     FROM ig_l_prod iglp
[ERROR]     JOIN ig_prc ig ON ig.ig_skid = iglp.ig_skid
[ERROR]     JOIN g g ON g.g_skid = ig.g_skid
[ERROR]     WHERE iglp.lock_ind = 'Y'
[ERROR]     GROUP BY
[ERROR]         iglp.p_skid
[ERROR] )
[ERROR] SELECT
[ERROR]     pr.p_skid AS scr_prod_skid,
[ERROR]     lg.lokd_gate_lst,
[ERROR]     pr.*
[ERROR] FROM p pr
[ERROR] LEFT JOIN lokd_gate lg ON lg.p_skid = pr.p_skid
[ERROR] where exists(select 1 from PP_PRC pipo WHERE pipo.PI_P_SKID = pr.P_SKID);
[ERROR]
[ERROR] -> [Help 1]

https://stackoverflow.com/questions/57291663/flyway-create-view-as-with-common-table-expression-cte

**Comment by juliahayward** [comment]
The parser has been significantly changed in v6.0. Can you try with the beta version 6.0.0-beta2 and let us know if this resolves your issue?

**Comment by jakubek2085** [comment]
@juliahayward , Thanks for quick reply. I tested the migration with Flyway 6.0.0-beta2. Script was migrated successfully. Thank You :-)

**Comment by juliahayward** [comment]
We are intending to release 6.0.0 on 14th August. We hope that all issues in the 6.0.0 milestone will be fixed by then but we won't delay the release unduly if not all are done.
