### ISSUE TITLE
Regexp in #2048 is to broad

### ISSUE THREAD

**Issue by pauxus** [flyway/flyway#2455]
###### Which version and edition of Flyway are you using?
5.2.4 Enterprise

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven

###### Which database are you using (type & version)?
Oracle 12.2

###### Which operating system are you using?
Linux (windows on developer machines)

###### What did you do?
Create View statement fails if using "AS WITH" but not followed by an PL/SQL statement:

```sql
CREATE OR REPLACE VIEW V_TEST_1
AS
WITH data_list AS (
    SELECT 1 AS ID FROM DUAL
)
SELECT ID
  FROM data_list;

CREATE OR REPLACE VIEW V_TEST_2
AS
SELECT 1 AS ID FROM DUAL;

-- another statement
```

###### What did you expect to see?
Successful migration

###### What did you see instead?
ORA-00933: SQL command not properly ended

## Analysis

The fix for #2048 is incomplete, the Regexp is too broad:

It should only apply to WITH followed by PROCEDURE or FUNCTION, not a regular SQL statement.

Instead the syntax should be:

```java
"^CREATE(\\s+OR\\s+REPLACE)?(\\s+(NON)?EDITIONABLE)?\\s+(VIEW)\\s+.*\\s+AS\\s+WITH\\s+(FUNCTION|PROCEDURE).*");
```

## Workaround: 

use 5.1.1

**Comment by juliahayward** [comment]
The parser has been completely rewritten for v6.0 and we are unable to reproduce this error. Could you try with 6.0.0-beta2 and see if that resolves the issue?

**Comment by pauxus** [comment]
This migration works in 6.0.0-beta2, however, we get errors there with valid code, and beta versions are no option for production code.

**Comment by juliahayward** [comment]
Thankyou for verifying the beta; we're intending that the final v6.0.0 release should be available on 14th August.

**Comment by pauxus** [comment]
Ok, will try to create a bug report for the new problem
