### ISSUE TITLE
how to config flyway.schemas,how to config multiple schemas?example?

### ISSUE THREAD

**Issue by NaturAlex** [flyway/flyway#2460]
###### Which version and edition of Flyway are you using?
5.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
i don't know how to use schemas,i read all of github and stackOverFlow,just tell me to 
read the faq. so i read,but i think it's too simple to understand!i hope someone can give a example, i used flyway with commandline,not maven.thanks

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using (type & version)?
mysql

###### Which operating system are you using?
windows,linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
i try i config one schemas and sql file do something with other schemas,like 
flyway.schema=schema1
insert into schema2.test ..... 
and it works,that is not i wanted

###### What did you expect to see?
i want 
flyway.schemas=schema1,schema2
flyway.locations=filesystem:sql/schema1/dev/,filesystem:sql/schema2/dev/
and sql/schema1/dev/ sql will be used in schema1 
sql/schema2/dev/ sql will be used in schema2

**Comment by NaturAlex** [comment]
please don't tell me to read faq,that is not enough detailed,i have read that for 1000 times,thanks!

**Comment by NaturAlex** [comment]
i think schemas only can work with command clean ,and migrate can't work unless you write the schema in sql sentence.

**Comment by juliahayward** [comment]
What you're describing is currently not supported. You would need to run Flyway twice with different configuration files to achieve what you want.

This is related to #1308, although it's rather an edge case for most users we will reconsider it at some future point.
