### ISSUE TITLE
Database Provisioning in Flyway

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2464]
We explored ideas around database provisioning in flywaydb.org/blog/flyway-provisioning . Would this be a useful feature for you? How would you like to see it working? Please feel free to submit ideas, comments or just give us a thumbs-up.

**Comment by asaikali** [comment]
Simplifying integration testing scenarios with Flyway out of the box would be very good. I like to able to have various of types of data stets in different dirs and then run tests and have fly apply the data sets as part of the execution of the tests but not have the test data be part of the migration scripts that get shipped.

**Comment by dvdtknsn** [comment]
> Simplifying integration testing scenarios with Flyway out of the box would be very good. I like to able to have various of types of data stets in different dirs and then run tests and have fly apply the data sets as part of the execution of the tests but not have the test data be part of the migration scripts that get shipped.

@asaikali This should already be possible by specifying multiple entries in flyway.locations. It's a similar concept to the ["database-specific sql" FAQ answer](https://flywaydb.org/documentation/faq#db-specific-sql). This use case is also describe in this [blog post](https://medium.com/@jonashavers/how-to-create-database-test-data-for-spring-boot-applications-with-flyway-db-294a436db7ee) and also in [this GitHub question](https://github.com/spring-projects/spring-boot/issues/2753)
