### ISSUE TITLE
Database versions due to drop out of Community/Pro support in Flyway 7

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2466]
The following database releases will be more than 5 years old at the release of 7.0, assuming a date in summer 2020, and support for them will be reviewed:

Derby 10.11
Postgres 9.4
Sybase ASE 16
HSQLDB 2.3

**Comment by mark-raymond** [comment]
Will any database drop out of Enterprise support in Flyway 7?

**Comment by juliahayward** [comment]
No, there's no intention to drop anything from Enterprise.
