### ISSUE TITLE
Flyway fails to execute `CALL` to a procedure containing `COMMIT` on PostgreSQL 11

### ISSUE THREAD

**Issue by stellingsimon** [flyway/flyway#2469]
###### Which version and edition of Flyway are you using?
Community Edition 6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
It is the latest.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API, Command-line

###### Which database are you using (type & version)?
`PostgreSQL 11.3 (Debian 11.3-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit`

###### Which operating system are you using?
Linux 4.15.0-58-generic #64-Ubuntu SMP x86_64

###### What did you do?
(Here is a [complete minimal reproduction setup](https://github.com/stellingsimon/flyway-issue-2469-reproducer).) 

Write a SQL migration `V01__Procedure_with_commit.sql` with the following content:

```
CREATE OR REPLACE PROCEDURE waste_xid(cnt int)
AS $$
DECLARE
    i INT;
    x BIGINT;
BEGIN
    FOR i in 1..cnt LOOP
        x := txid_current();
        COMMIT;
    END LOOP;
END;
$$
    LANGUAGE plpgsql;

CALL waste_xid(10);
```

As of PostgreSQL 11, stored procedures with `COMMIT`s are supported: https://www.postgresql.org/docs/11/plpgsql-transactions.html

###### What did you expect to see?
Successful execution.

###### What did you see instead?

```
[main] ERROR org.flywaydb.core.internal.command.DbMigrate - Migration of schema "shared" to version 01 - Procedure with commit failed! Changes successfully rolled back.
Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 

Migration V01_Procedure_with_commit.sql failed
----------------------------------------------------------
SQL State  : 2D000
Error Code : 0
Message    : ERROR: invalid transaction termination
  Where: PL/pgSQL function waste_xid(integer) line 8 at COMMIT
Location   : db/migration/global/V01_Procedure_with_commit.sql (/.../db/migration/global/V01_Procedure_with_commit.sql)
Line       : 15
Statement  : call waste_xid(10)

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:267)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:214)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:121)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:70)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:365)
        ... 22 more
Caused by: org.postgresql.util.PSQLException: ERROR: invalid transaction termination
  Where: PL/pgSQL function waste_xid(integer) line 8 at COMMIT
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:244)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:202)
        ... 25 more
```
Note:

 * The same problem occurs when transforming the `CALL` into a `DO`-block.
 * The same statement called manually executes without problems:

```
psql -U postgres
psql (11.5 (Debian 11.5-1.pgdg90+1))
Type "help" for help.

postgres=# CREATE OR REPLACE PROCEDURE waste_xid(cnt int)
postgres-# AS $$
postgres$# DECLARE
postgres$#     i INT;
postgres$#     x BIGINT;
postgres$# BEGIN
postgres$#     FOR i in 1..cnt LOOP
postgres$#         x := txid_current();
postgres$#         COMMIT;
postgres$#     END LOOP;
postgres$# END;
postgres$# $$
postgres-#     LANGUAGE plpgsql;
CREATE PROCEDURE
postgres=# CALL waste_xid(10);
CALL
```

**Comment by MikielAgutu** [comment]
By default, Flyway will run most migrations inside a transaction. By using `BEGIN` and `COMMIT` inside your sproc, you're actually creating a nested transaction.

I see this is an example pulled from the Postgres docs. Do you have a real use case for this behavior?

Also note this is only failing becasue you're calling the sproc from within the migration script. Remove the `CALL` and this will work, since Flyway's transaction handling will no longer be interfered with.

**Comment by stellingsimon** [comment]
@MikielAgutu: Thanks for the quick reply.

> By using BEGIN and COMMIT inside your sproc, you're actually creating a nested transaction.
Yes, this is intended. As far as I understand, this should not be a problem though? Is there any way to disable Flyway's transaction handling for a particular SQL migration?

> Do you have a real use case for this behavior?
Yes, sorry for not mentioning the original context: my actual procedure loops over a large number of tables and reflectively inserts their data into a snapshot table. Due to the large number of tables, it is quite likely that by using only one transaction I will overflow the in-memory WAL log, causing major stress on the DB and needlessly slowing down the migration. To avoid this, I wanted to `COMMIT` every source table separately.

 > Also note this is only failing becasue you're calling the sproc from within the migration script.
I'm aware of that, but I would need to actually make the `CALL` from within the Flyway migration. For the time being, I worked around this issue by issuing the reflective `INSERT` statements from a `JdbcMigration` instead (without a `PROCEDURE`, implementing the statement-generating logic in Java).

**Comment by MikielAgutu** [comment]
Ok, those are all fair points! There is currently no way to turn off transactions for specific migrations. We prefer for Flyway to automatically detect such scenarios, so as to remove the burden of configuration from users (see #655 for more context).

Normally we turn off transactions for migrations that contain specific keywords that we know are incompatible. However, your case is more complex since it depends on the contents of a stored procedure when it's called.

Flyway currently does not consider the contents of called stored procedures when deciding if a migration can be run inside of a transaction. If you call a stored procedure that happens to contain non-transactional statements, the migration will fail. Therefore this problem isn't just related to `COMMIT`, but is a more general limitation of Flyway's transaction handling.

I'll open a GitHub issue for the more general case. Thanks for the feedback.
