### ISSUE TITLE
Upgrade to Derby 10.15

### ISSUE THREAD

**Issue by pzygielo** [flyway/flyway#2470]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.0.0 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
Apache Derby 10.15

###### Which operating system are you using?
linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
```
4.98s$ ./mvnw flyway:info
```

###### What did you expect to see?
I didn't expect warning for derby 10.15 that was published few months ago.

###### What did you see instead?
```
[INFO] --- flyway-maven-plugin:6.0.0:info (default-cli) @  ---
[INFO] Flyway Community Edition 6.0.0 by Boxfuse
[INFO] Database: jdbc:derby:x (Apache Derby 10.15)
[WARNING] Flyway upgrade recommended: Derby 10.15 is newer than this version of Flyway and support has not been tested. The latest supported version of Derby is 10.14.
```

**Comment by juliahayward** [comment]
The warning should be harmless; it just reflects that we haven't completed formal testing on Derby 10.15 yet. Could you confirm if you're using the 10.15.1.3 driver (now three jar files)? Do you see any problematic behaviour other than the warning?

**Comment by pzygielo** [comment]
> Could you confirm if you're using the 10.15.1.3 driver (now three jar files)? 

Confirmed. My project depends on -- from group `org.apache.derby`:
  * `derby` itself
  * `derbytools` (where `Embedded/ClientDriver` were moved)
  * and `derbyshared` (where some classes from `...derby...security` package were moved).

> Do you see any problematic behaviour other than the warning?

`flyway`:`migrate` that I use works perfectly fine.

> The warning should be harmless; it just reflects that we haven't completed formal testing on Derby 10.15 yet.

Understood, thank you for your reply. I raised this issue mainly, as there is #2013, for previous upgrade, but I didn't see one for tracking 10.15.

**Comment by juliahayward** [comment]
That's great, thanks. With the new driver all our Derby-specific tests pass on Java 9+, but we can't ship the driver by default right now as it would break our promise to support Java 8.

**Comment by pzygielo** [comment]
> we can't ship the driver by default right now as it would break our promise to support Java 8

That's clear for CLI, as 10.15 requires at least java 9, true.
But in case of non-CLI - like with plugin or project depending on sole flyway-core, as driver dependencies have to be provided by developer - will flyway stop issuing warning?

And - as for rule to support only the one latest version for community - will 10.14 stay as supported? (I hope so.)

**Comment by juliahayward** [comment]
We should be able to bump up the version warning, with some careful documentation. 

We're moving to a policy of 5 years database support for the community - which means 10.14 has a good long time left!

**Comment by pzygielo** [comment]
Only confirming - flyway 6.0.1 is (non-warning-)happy with derby 10.15 .
**Thank you**.

**Comment by juliahayward** [comment]
Many thanks - always good to hear that we've done something helpful!
