### ISSUE TITLE
Add extensible DatabaseType and Database support

### ISSUE THREAD

**Issue by bobtiernay-okta** [flyway/flyway#2472]
Currently, it is not possible to extend Flyway to support additional databases outside of what exists in the `flyway/flyway` without forking the repo. This limits the shared extensibility of the core library and causes maintenance issues for consumers. A good example of this can be seen in the request to add Snowflake database support.  In order to support:

- [Flyway PR #2274](https://github.com/flyway/flyway/pull/2274)
- [Flyway PR #1914](https://github.com/flyway/flyway/pull/1914)
- [Flyway PR #1776](https://github.com/flyway/flyway/pull/1776)
- [Flyway issue #1735](https://github.com/flyway/flyway/issues/1735)

Resulting in forks such as the following:

- [brianrepko/flyway](https://github.com/brianrepko/flyway)

By making the following changes to the core library, new databases may be added without requiring a fork:

- Change `DatabaseType` from an enum to a class
- Allow registering `DatabaseType` and `Database` objects via [service loader](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html).
- Update `DriverDataSource` to add support for querying all registered `DatabaseTypes` for required metadata instead of hardcoding.

**Comment by DoodleBobBuffPants** [comment]
Closing as this is quite old and a similar refactor has since been done, so some of these changes don't apply to the current codebase
