### ISSUE TITLE
flyway checksum wrong for unchanged sql script

### ISSUE THREAD

**Issue by valpa** [flyway/flyway#2474]
###### Which version and edition of Flyway are you using?
6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line in Linux and windows

###### Which database are you using (type & version)?
Postgresql

###### Which operating system are you using?
Linux/Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?
flyway migrate

###### What did you see instead?

```
ERROR: Validate failed: Migration checksum mismatch for migration version 1.1
-> Applied to database : -1340212107
-> Resolved locally    : -1039259818
```

I got following error when run flyway (flyway-6.0.0) migrate:

```
ERROR: Validate failed: Migration checksum mismatch for migration version 1.1
-> Applied to database : -1340212107
-> Resolved locally    : -1039259818
```

The SQL script is: V1_1__add_column_location_history_valid_until.sql

`alter table location_history add column valid_until timestamp with time zone;`

I run the crc32 check on this file and covert it into signed integer:

```
root@jerry:~# crc32 V1_1__add_column_location_history_valid_until.sql
b01dfc75
root@jerry:~# echo $(( 16#b01dfc75 -2**32 ))
-1340212107
```

I found the checksum is exact same as what have been applied to database.

Now I am very confused why flyway calculate the checksum result -1039259818, which is clearly wrong.

**Comment by juliahayward** [comment]
Could you attach an exact copy of the migration file please?

**Comment by valpa** [comment]
Attached. 

.sql changed to .log because github doesn't support .sql extention

[V1_1__add_column_location_history_valid_until.log](https://github.com/flyway/flyway/files/3520083/V1_1__add_column_location_history_valid_until.log)

**Comment by juliahayward** [comment]
Many thanks. The -1039259818 checksum is produced by both Flyway 5.2.4 and Flyway 6.0. These are both stripping off line endings from the migration. -1340212107 is the checksum of the file with a LF at the end of the single line. A `flyway repair` should correct everything for you.

Versions of Flyway prior to 4.0 included line endings in the checksum; this was changed as a result of #253. Was your original v1.1 migration carried out with a much older version of Flyway?

**Comment by valpa** [comment]
Thanks Julia, `flyway repair` solved my problem.
I was recently assigned to manage the DB but have no idea about the previous version flyway applied to DB. Is there a way to find out?

`flyway repair` will re-calculate the checksum. But it will not able to do validation during the repair so there will be a chance that script change not be able to be detected.
