### ISSUE TITLE
Postgres - custom tablespace for schema history table not working

### ISSUE THREAD

**Issue by sbelan** [flyway/flyway#2477]
###### Which version and edition of Flyway are you using?

6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle Plugin

###### Which database are you using (type & version)?

Postgres 10.x and Postgres 11.x

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Not taking provided custom tablespace, picking up the default one.

###### What did you expect to see?

It should use the provided tablespace in flyway config file. flyway.tablespace=abc

###### What did you see instead?

Migration  failed
 -----------------
 SQL State  : 42501
 Error Code : 0
  Message    : ERROR: permission denied for tablespace xyz
  Location   :  ()
   Line       : 14
  Statement  : ALTER TABLE "postgres"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank")
  
  **ERROR: permission denied for tablespace xyz**

**Comment by MikielAgutu** [comment]
Can you verify that your permissions are set up correctly for using your `abc` tablespace? You could do this by manually running a script against the DB with the credentials you're using with Flyway. e.g:

```sql
CREATE TABLE foo(i int) TABLESPACE abc;
```

**Comment by sbelan** [comment]
@MikielAgutu Thank you for quick response. My bad, the issue is I provided **flyway.tablespace=abc** but it is still taking default tablespace **xyz** and throwing exception for that default tablespace. I have updated the issue description

**Comment by MikielAgutu** [comment]
I'm having trouble reproducing this. Can you check the [environment variable](https://flywaydb.org/documentation/envvars) (`FLYWAY_TABLESPACE`) is not set?

Can you also clarify what you mean by 'default tablespace', particularly how `xyz` has become the default. Are you setting the default via `SET default_tablespace`, or do you mean the built in `pg_default`? Could you also send me your config file? Thanks :)

**Comment by sbelan** [comment]
I have the existing database having 4 tablespace xyz, abc, lmn, qwe and I want to execute flyway on tablespace abc but its picking xyz. Yes you can say xyz is default like pg_default.

Could you please let me know how to print environment variable? I am using gradle and didn't get much at above link.

My flyway.conf file
-----------
flyway.url=jdbc:postgresql://127.0.0.1:5432/postgres
flyway.schemas=postgres
flyway.baselineOnMigrate=true
flyway.tablespace=abc

**Comment by MikielAgutu** [comment]
Can you review your entire configuration and ensure the tablespace option isn't set anywhere other than your `flyway.conf` file? You can read how to configure Gradle [on this docs page](https://flywaydb.org/documentation/gradle/#gradle-properties).

In particular note at the end of the document the overriding order:

> Settings are loaded in the following order (higher items in the list take precedence over lower ones):
> 1. System properties
> 1. Environment variables
> 1. Custom config files
> 1. Gradle properties
> 1. Flyway configuration section in build.gradle
> 1. `<user-home>/flyway.conf`
> 1. Flyway Gradle plugin defaults

It could be that you have specified it in one of those places and it's overriding your `flyway.conf`. 

If you've set your `flyway.conf` using the `-Dflyway.configFiles` system property, then the first two items on the list could be overriding it. If your `flyway.conf` lives in `<user-home>/flyway.conf` then the first 5 items on the list could be overriding it.

> Could you please let me know how to print environment variable?

These are just normal system level environment variables, acesses to them is OS dependent. You're using Linux so I assume [`printenv | grep FLYWAY`](https://www.cyberciti.biz/faq/linux-list-all-environment-variables-env-command/) is what you need.

**Comment by MikielAgutu** [comment]
Can you review your entire configuration and ensure the tablespace option isn't set anywhere other than your `flyway.conf` file? You can read how to configure Gradle [on this docs page](https://flywaydb.org/documentation/gradle/#gradle-properties).

In particular note at the end of the document the overriding order:

> Settings are loaded in the following order (higher items in the list take precedence over lower ones):
> 1. System properties
> 1. Environment variables
> 1. Custom config files
> 1. Gradle properties
> 1. Flyway configuration section in build.gradle
> 1. `<user-home>/flyway.conf`
> 1. Flyway Gradle plugin defaults

It could be that you have specified it in one of those places and it's overriding your `flyway.conf`. 

If you've set your `flyway.conf` using the `-Dflyway.configFiles` system property, then the first two items on the list could be overriding it. If your `flyway.conf` lives in `<user-home>/flyway.conf` then the first 5 items on the list could be overriding it.

> Could you please let me know how to print environment variable?

These are just normal system level environment variables, acesses to them is OS dependent. You're using Linux so I assume [`printenv | grep FLYWAY`](https://www.cyberciti.biz/faq/linux-list-all-environment-variables-env-command/) is what you need.

**Comment by sbelan** [comment]
Thank you, let me try this.

**Comment by alextercete** [comment]
Any news?

**Comment by sbelan** [comment]
@alextercete not tried above solution yet.. will try over the weekend and let you know.

**Comment by sbelan** [comment]
@MikielAgutu I checked with printenv from my jenkin and didn't find any flyway environment variable. I proceeded with the workaround by executing history table manually. On local I created new tablespace and provided in config and worked for me. Now Checking with access issue with my infra team for higher environments. @MikielAgutu @alextercete Thank you for you help and follow up
