### ISSUE TITLE
Consider contents of called stored procedures to decide if migration can be run inside a transaction

### ISSUE THREAD

**Issue by MikielAgutu** [flyway/flyway#2478]
###### Which version and edition of Flyway are you using?
6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

n/a

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using (type & version)?
PostgreSQL 11

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

See #2469 for original context.

Reproduced with PostgreSQL specifically, but will probably occur for other DBs also.

- Create a stored procedure inside a repeatable migration
- In the stored procedure, introduce a non-transactional statement
- `CALL` the stored procedure inside the migration

**Example script**
```sql
CREATE OR REPLACE PROCEDURE some_sproc()
AS $$
BEGIN
    VACUUM;
END;
$$
    LANGUAGE plpgsql;

CALL some_sproc();
```

###### What did you expect to see?
Flyway should detect this migration cannot be run inside a transaction because the stored procedure that is called is using non-transactional statements (`VACUUM`).

###### What did you see instead?
Flyway attempts to run the migration inside a transaction and produces an error;

```
ERROR: Migration of schema "flyway_schema" with repeatable migration sproc failed! Changes successfully rolled back.
ERROR: 
Migration R__sproc.sql failed
-----------------------------
SQL State  : 25001
Error Code : 0
Message    : ERROR: VACUUM cannot run inside a transaction block
  Where: SQL statement "VACUUM"
PL/pgSQL function some_sproc() line 3 at SQL statement
Location   : sql\R__sproc.sql (C:\flyway_project\sql\R__sproc.sql)
Line       : 9
Statement  : CALL some_sproc()
```

This is going to fail for any non-transactional statements that are present in stored procedures called from migration scripts.

**Comment by juliahayward** [comment]
This is solved by allowing the transactional nature of the script to be specified per-script - see #2478.
