### ISSUE TITLE
extend API for tests, adding migration steps

### ISSUE THREAD

**Issue by grexe** [flyway/flyway#2485]
using Flyway 5.2.4 and also checking latest docs, it seems to be impossible to do selective migrations only to a specific step from the API.
My usage scenario is to test if a certain migration in the middle of the process works by inspecting the database after migration step X, without performing the whole migration, from within a Unit test.
I've not found any API methods to perform migration steps, only a full `migrate()`.

When using Flyway in a Spring context, this is usually done automatically (can be configured though), so it's too late then, there is only all or nothing.

So I'd like to:
1. startup my Spring context and DB without any migration (can be configured iirc)
1. perform migration from baseline up to step N so I have my well-known setup
1. load some data
1. perform migration steps N+1, N+2
1. check if everything worked and structure+data has been changed as expected
1. perform the remaining migration steps if needed.

Am I missing something or how could I achieve that?

**Comment by MikielAgutu** [comment]
This should be possible using the [`flyway.target` config option](https://flywaydb.org/documentation/configfiles).

- Set `flyway.target` to migration version N for your baseline migration
- Run migrate
- Prepare your DB for manual testing
- Update `flyway.target` to N+1, N+2 etc as you require
- Run migrate again

[Flyway Spring Boot docs for reference](https://flywaydb.org/documentation/plugins/springboot).

**Comment by grexe** [comment]
Ah the target was it, thanks now I remember. That should work, will try it out and report back.

**Comment by MikielAgutu** [comment]
[It should be a case of using `configure` on the `Flyway` class](https://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/Flyway#configure()):

```Java
Flyway.configure().target("2");
```

[API Docs](https://flywaydb.org/documentation/api/)

**Comment by grexe** [comment]
Ok thanks I must have totally overlooked that in the docs, sorry. Will try that...

**Comment by alextercete** [comment]
@grexe Any news?

**Comment by grexe** [comment]
WIth the info from @MikielAgutu I discovered everything needed to implement this test, please feel free to close this issue @alextercete and thanks for asking!

**Comment by alextercete** [comment]
@grexe That's good to hear!
