### ISSUE TITLE
Using flyway to do continuos integration with mysql.

### ISSUE THREAD

**Issue by joseagt1994** [flyway/flyway#2488]
###### Which version and edition of Flyway are you using?
I am using Flyway 6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
I am using Jenkins with Flyway plugin.

###### Which database are you using (type & version)?
I am using Mysql 5.7 currently.

###### Which operating system are you using?
Ubuntu server 18.04

###### What did you do?
I might be wondering is there is a way that flyway can handle this or not. I am doing a backup of my database always in any migration, this way I wont lose any data. After that I am doing changes to my database, like changing the name of the table or the name of an attribute itself. I would like to restore that data into the new database but I dont know if this is possible or not.

###### What did you expect to see?
I will expect to see my data in the new database after the restore without losing any data. 

###### What did you see instead?
Got error because the table doesnt exist currently. Does flyway can keep track of this or not really?

**Comment by alextercete** [comment]
@joseagt1994 I'm not sure I understand your request. Would you like to create a backup of your database before each migration is run? If that's the case, could you explain why do you need this?

**Comment by alextercete** [comment]
@joseagt1994 Would you mind clarifying your request?

**Comment by alextercete** [comment]
Closing due to lack of response.
