### ISSUE TITLE
SQL Server integrated security - This driver is not configured for integrated authentication

### ISSUE THREAD

**Issue by lamjwe** [flyway/flyway#2489]
###### Which version and edition of Flyway are you using?

Gradle plugin

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which database are you using (type & version)?

Sql Server 2014

###### Which operating system are you using?

Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I am trying to use flyway. I am not able to connect to the database using windows auth.
I need to add my new directory in my project that includes the sqljdbc_auth.dll to java.library.path.

I've tried setting 

System.properties.setProperty "java.library.path", System.getProperty("java.library.path") + ";$rootDir\\lib"

in my flyway object in build.gradle.

also tried 
./gradlew flywayMigrate -Djava.library.path="C:\(mypath)\lib;" 

Both of these does change the java.library.path (i've added print statements to verify), but I am still getting the error :
SQL State  : 08S01
  Error Code : 0
  Message    : This driver is not configured for integrated authentication. ClientConnectionId:xxx

  This driver is not configured for integrated authentication. ClientConnectionId:xxx
  no sqljdbc_auth in java.library.path: [ ...] <-- without my path

I've tried copying sqljdbc_auth.dll to my java bin file and it works. But I hope to leave the sqljdbc_auth.dll in my project and have flyway java.lib.path points to it. 

###### What did you expect to see?

Successful connection to the SQL server and baseline the database

###### What did you see instead?

SQL State  : 08S01
  Error Code : 0
  Message    : This driver is not configured for integrated authentication. ClientConnectionId:xxx

  This driver is not configured for integrated authentication. ClientConnectionId:xxx
  no sqljdbc_auth in java.library.path: [ ...]

**Comment by alextercete** [comment]
Related to #1646.

**Comment by MikielAgutu** [comment]
This is documented here: https://flywaydb.org/documentation/database/sqlserver#windows-authentication--azure-active-directory
