### ISSUE TITLE
NoClassDefFoundError in maven plugin

### ISSUE THREAD

**Issue by JustAPhrog** [flyway/flyway#2490]
###### Which version and edition of Flyway are you using?

6.0.1 (tested also on 5.2.4)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin on IntelliJ IDEA 2019.2.1 (Community Edition)
Build #IC-192.6262.58, built on August 20, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
JAVA:
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
###### Which database are you using (type & version)?

H2 1.4.199

###### Which operating system are you using?

Windows 7 x64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I run info, clean and migrate in Intellij

###### What did you expect to see?

Success without error. In H2 db for:
- clean: clean db
- info: no change
- migrate: new table with 3 rows

###### What did you see instead?
Success but with error
![flyway-error](https://user-images.githubusercontent.com/36739202/64000393-ef34ca00-cb05-11e9-9185-6a2d693cc8cf.jpg)
For info and migrate is same situation: success and flowing error.

**Comment by JustAPhrog** [comment]
In H2 database there is no changes when I `clean` it. Clean should remove one table defined in migration.

**Comment by alextercete** [comment]
@JustAPhrog Thanks for the report.

Could you please share the relevant parts of your `pom.xml` and `flyway.conf` files?

**Comment by JustAPhrog** [comment]
Sory for that delay: I finally repair that :smile: because some migration with lunched app could broke db. After **delete** of H2 db file - all commands **worked**.
