### ISSUE TITLE
Extend flyway info to include all data in the flyway_schema_history table

### ISSUE THREAD

**Issue by DoodleBobBuffPants** [flyway/flyway#2491]
###### Which version and edition of Flyway are you using?
Enterprise 6.0.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
This is a feature request, not a bug.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle 18c

###### Which operating system are you using?
Windows 10 x64

###### What did you do?
Run flyway info in the command line.

###### What did you expect to see?
Data from all columns in the `flyway_schema_history` table for each migration.

###### What did you see instead?
The current info implementation doesn't return all the columns, for example `execution_time` and `installed_by` aren't returned.

**Comment by alextercete** [comment]
@DoodleBobBuffPants Out of interest, why do you need the data from the columns that aren't currently exposed by `flyway info`?

**Comment by DoodleBobBuffPants** [comment]
The `execution_time` would be useful because some of our customers want to be able to plan how/when to apply their migrations against production environments.  This information can help them work out where bottlenecks are, and improve how migration scripts are generated to avoid massive files that take ages to run.

`installed_by` would be helpful for audit purposes - e.g. monitoring who is responsible for applying migrations

**Comment by alextercete** [comment]
It's now possible to get `executionTime` and `installedBy` when the `-json` option is specified.
