### ISSUE TITLE
REPAIR / UNDO-REPAIR command

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2492]
(Feature request received by email)

Wouldn't it be nice, if we have repair command/new undo-repair command this way, 

Say if V11__Desc.sql fails and U11__Desc.sql is available. Repair command will,

- Execute undo file U11__Desc.sql. Yes, I understand, it will throw error since some of the objects - in V11 is not created yet - can we just log it and proceed further.
- Now delete the failed record from flyway_schema_history table.

This way, we avoid manual clean up of left behind objects.

**Comment by alextercete** [comment]
Closing as a duplicate of #2444.
