### ISSUE TITLE
Dry Run Always Returns Zero

### ISSUE THREAD

**Issue by jwheeler31** [flyway/flyway#2494]
###### Which version and edition of Flyway are you using?
6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Feature Request

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line/Java API

###### Which database are you using (type & version)?
MariaDB 10.2.6

###### Which operating system are you using?
macOS Mojave 10.14.6/CentOS 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
`PreparedStatement.executeUpdate()`

###### What did you expect to see?
Non-zero result for a successful update

###### What did you see instead?
Zero

---

In `DryRunJdbcProxies.createPreparedStatementProxy(final ClassLoader, final PreparedStatement, final String, final DryRunStatementInterceptor)`, the code that always returns zero is:
```
String methodName = method.getName();
if ("execute".equals(methodName)
        || ("executeQuery".equals(methodName) && !QUERY_REGEX.matcher(sql).matches())
        || "executeUpdate".equals(methodName)
        || "executeLargeUpdate".equals(methodName)) {
    if (args == null) {
        dryRunStatementInterceptor.interceptPreparedStatement(sql, params);
    } else {
        dryRunStatementInterceptor.interceptStatement((String) args[0]);
    }
    if ("execute".equals(methodName)) {
        return false;
    }
    if ("executeQuery".equals(methodName)) {
        return createDummyResultSet(classLoader);
    }
    return 0;
}
```
I don't know if it's possible to return a valid value or if a dummy value must be returned.

**Comment by juliahayward** [comment]
What would a valid value be (other than, perhaps, a hard-coded non-zero value)? https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#executeUpdate indicates that the normal result of `PreparedStatement.executeUpdate` is the rowcount of any DML in your migration; the dry-run proxy can't give you the count that would have happened had it been an actual migration.

**Comment by alextercete** [comment]
Closing due to lack of response.
