### ISSUE TITLE
Feature: Add `isDryRun()` to Java API

### ISSUE THREAD

**Issue by jwheeler31** [flyway/flyway#2495]
###### Which version and edition of Flyway are you using?
6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MariaDB 10.2.6

###### Which operating system are you using?
macOS Mojave 10.14.6/CentOS 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Standard Java migration (implement `BaseJavaMigration.migrate()`

###### What did you expect to see?
Feature Request - an API to check if currently in a dry-run state.

###### What did you see instead?
Current workaround is `context.getConfiguration().getDryRunOutput() != null`

**Comment by juliahayward** [comment]
IWhich class would you like the method added to?

**Comment by alextercete** [comment]
We probably wouldn't add this to the `Configuration` interface because that is meant to reflect the options in the config files (and `dryRun` isn't one of them), so I'm going to close this because the workaround seems reasonable.
