### ISSUE TITLE
Fall back to Community edition when license check fails

### ISSUE THREAD

**Issue by alextercete** [flyway/flyway#2497]
In the event of the licensing service being down, Flyway Pro/Enterprise should behave like Flyway Community to minimise the impact of such outage.

This would allow scenarios such as applying migrations in CI, although this would still fail if other Pro/Enterprise features are being used (for example, SQL*Plus syntax).

**Comment by MikielAgutu** [comment]
https://github.com/flyway/flyway/issues/2515#issuecomment-601214975
