### ISSUE TITLE
Flyway gradle task cannot open file within custom location (windows)

### ISSUE THREAD

**Issue by gintsgints** [flyway/flyway#2504]
###### Which version and edition of Flyway are you using?
6.0.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using (type & version)?
Oracle 11.g.

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Start gradle build with custom location:

gradle flywayMigrate -i -Pflyway.locations=filesystem:"./src/main/resources/db/seed"

###### What did you expect to see?

Executed scripts in seed directory.

###### What did you see instead?

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  Unable to load filesystem resource: .\src\main\resources\db\seed\V10__AGC_CUSTOM_TABLE_TYPE.sql (encoding: UTF-8)
  .\src\main\resources\db\seed\V10__AGC_CUSTOM_TABLE_TYPE.sql

**Comment by MikielAgutu** [comment]
Thanks for the report. I've been able to reproduce and develop a fix for this. It should be available in the next release.
