### ISSUE TITLE
Flyway migration hangs on clustered postgres

### ISSUE THREAD

**Issue by wayne-o** [flyway/flyway#2506]
###### Which version and edition of Flyway are you using?

flyway community 6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Basically using the CLI via this configuration; https://github.com/nelvadas/ocp-flyway-db-migration/blob/master/beosbank-flyway-job.yaml

###### Which database are you using (type & version)?

Postgres 11

###### Which operating system are you using?

Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I have installed postgres into my cluster using the helm chart found here: https://github.com/helm/charts/tree/master/stable/postgresql

If I run the migration against a single node postgres (i.e. not using the production values settings from here https://github.com/helm/charts/tree/master/stable/postgresql#production-configuration) - it works imediately - if I run it with replication.enabled: true and the other relevant settings found there it just hangs

###### What did you expect to see?

The migrrations should run

###### What did you see instead?

It just hangs.

Also these commands run fine if I exec into the flyway migration job pod:

flyway -url=jdbc:postgresql://postgresql.default.svc.cluster.local:5432/sonaticket -user=****-password=**** clean

flyway -url=jdbc:postgresql://postgresql.default.svc.cluster.local:5432/sonaticket -user=**** -password=**** info

however this also just hangs:

flyway -url=jdbc:postgresql://postgresql.default.svc.cluster.local:5432/sonaticket -user=**** -password=**** migrate -locations=filesystem:/var/flyway/data/

**Comment by juliahayward** [comment]
This is possibly related to #2634 - could you take a copy of v6.2 when we release it (tomorrow) and try with that?

**Comment by MikielAgutu** [comment]
Closed for lack of response
