### ISSUE TITLE
Machine readable output for commands

### ISSUE THREAD

**Issue by MikielAgutu** [flyway/flyway#2507]
We propose introducing machine readable output for the Flyway commands.

[We'd like every command to produce machine readable output,](https://github.com/flyway/flyway/issues/2254#issuecomment-504131983) although the Info command wants the most attention. Info has this has already been requested (#2254), and we'd also like Info to output more information while we're at it (#2491). 

JSON is the obvious format, although we may consider others if people want them.

We're thinking the following:
- Introduce a `-json` or `-format:json`, or something to that effect to the CLI
- Output a success or error object after execution of a command
- Produce a JSON version of the ASCII table that Info currently produces
  - Including metadata; schema version etc
- Add extra data to Info, comprising of the entire `schema_history` table, e.g:
  - Execution time
  - Filename
  - Checksum
  - Installed by
- Progress messages on stderr (perhaps only for Migrate)
- Output nested or multiple errors
- Output currently deployed version
- Support all clients ([Gradle specifically has been requested](https://github.com/flyway/flyway/issues/2254#issuecomment-483782549))

Please share any thoughts, or just thumb up this post if you'd like to see this feature 😄

**Comment by juliahayward** [comment]
Some notes from today's meeting:
- all commands to return success/(failure+reason)
- would be helpful for `validate` to return a list of validation failures
- would be helpful for `migrate` to include a list of which migrations happened

**Comment by MikielAgutu** [comment]
Another important consideration is that the API could produce more information about the commands. For instance, Validate currently throws exceptions on validation errors. We could make it produce an object instead, so users can decide what to do based on the result of certain validation failures. One case that could help is https://github.com/flyway/flyway/issues/1662.

**Comment by MikielAgutu** [comment]
Related https://github.com/flyway/flyway/issues/2662
