### ISSUE TITLE
flyway command line does not migrate Db which is used on Bamboo agents

### ISSUE THREAD

**Issue by sameera464** [flyway/flyway#2508]
###### Which version and edition of Flyway are you using?
Verified with Flyway 4.0.1, 5.2.4, 6.0.0 and 6.0.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
aurora-mysql

###### Which operating system are you using?
amazon linux 1 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

command that I used: 

flyway -url=url -user=user -password=password -validateOnMigrate=true -baselineOnMigrate=true migrate

it always says no migration necessary where there are new files to be migrated.

###### What did you expect to see?

Migrations to happen

###### What did you see instead?

No migration necessary or Empty schema in latest version.

**Comment by MikielAgutu** [comment]
It could be an issue with your configuration. How have you specified the [`locations` config option](https://flywaydb.org/documentation/commandline/migrate#locations)? If it isn't specified the default is to look for migrations in a `sql` folder in the Flyway install directory.

**Comment by alextercete** [comment]
@sameera464 Any news?

**Comment by alextercete** [comment]
Closing due to lack of response.
