### ISSUE TITLE
Allow Flyway Edition Specification in Config File

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2515]
We are in the process of upgrading from Community to Pro edition.  It would be nice if this could be specified within the configuration file instead of on every command.

**Comment by alextercete** [comment]
There's a technical limitation at the moment which would make loading the edition from the config file challenging (basically, by the time it gets to that step, it has already loaded the relevant libraries). 

In addition to using the command-line flag, you can set this information using the [`FLYWAY_EDITION` environment variable](https://flywaydb.org/documentation/commandline/#environment-variable). Would that work for you?

**Comment by esauser** [comment]
@alextercete either _can_ work, but it would be much easier to do through the config file since it's so easily shared.  Hopefully this can be added some time in the future.

**Comment by MikielAgutu** [comment]
The technical limitations are round this are significant. We don't think it's valuable enough to pursue.
