### ISSUE TITLE
Feature: Support Azure Database Explorer

### ISSUE THREAD

**Issue by brycefisher** [flyway/flyway#2516]
I've found myself needing something exactly like flywaydb for Azure Data Explorer -- a way to manage migrations and track their state. Azure Data Explorer is not a pure SQL product however, so I'm not sure if trying to extend flywaydb makes sense for my use case. Would the maintainers see benefit to extending support for Azure Data Explorer?

Azure Data Explorer is a columnar, relational database only available on Azure with managed servers. It excels at handling ad-hoc querying quickly while ingesting terabytes of data per day. It's also used internally by Azure...to monitor Azure.

Here's the overview:
https://docs.microsoft.com/en-us/azure/data-explorer/data-explorer-overview

**Comment by MikielAgutu** [comment]
This is beyond the scope of Flyway. We're tied to relational DBs compatible with JDBC drivers.
