### ISSUE TITLE
Data API for Aurora Serverless

### ISSUE THREAD

**Issue by lielran** [flyway/flyway#2517]
I wonder what you think about supporting a none JDBC connection like Data API for amazon-aurora-serverless
https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/

it can be very handy and more secure to run migration like that. 
What do you think? doable?

**Comment by MikielAgutu** [comment]
It may be possible. However, a lot of Flyway's functionality depends on JDBC so this would require a fair bit of work most likely.

We're aware of the desire of some users to use alternatives to JDBC. For instance we've had a request for R2DBC (#2502). However JDBC still seems to be perfectly fine for most use cases, so we won't commit to providing alternatives at this time.

**Comment by lielran** [comment]
working with data API enables serverless workload. I found it very useful and secure working with this interface and would love to see that flyway will be the first to support this kind of integration. 

from the technical side, working with data API meaning to translate the SQL to http call using the aws-sdk in order the execute statement or commit/rollback transaction(that has the SQL in the body in some json format). 

what is the effort to creating this kind of driver?

**Comment by lielran** [comment]
from what I read in a few minutes I saw what @MikielAgutu means by refactoring. especially around  `Connection` class where `jdbcTemplate` is final and in this case need to be overridden with something that calls aws-sdk  functions

**Comment by MikielAgutu** [comment]
We don't think this is the right thing for Flyway.

**Comment by lielran** [comment]
Thanks, @MikielAgutu . 
after playing with aurora serverless. I figure that I can run Flyway as JDBC regular connection if I connected via ssh proxy to the VPC.

**Comment by mbklaene** [comment]
@lielran 
I am trying to do the same thing with Aurora Serverless. Would you mind sharing how you were able to connect via Flyway? Thanks.

**Comment by lielran** [comment]
> @lielran 
> I am trying to do the same thing with Aurora Serverless. Would you mind sharing how you were able to connect via Flyway? Thanks.

@mbklaene sure. If you run Flyway from outside your VPC(e.g. circeci/github actions) you will need a ec2 instance inside the vpc that can connect to the DB within the vpc. Then create JDBC connection with ssh configuration via the ec2 instance.

**Comment by mbklaene** [comment]
@lielran Great. Thanks.  I am thinking of using AWS CodeBuild to trigger flyway migration. CodeBuild will have a VPC Endpoint Interface so maybe I can get by with just a standard JDBC connection after all.

**Comment by jeffster23** [comment]
I'm gearing up to use Aurora Serverless for the first time. I'll be using AWS Data API for all interactions except deployment, where I'll use socket-based connections in order to leverage Flyway.

In the past I've used an AWS CodeBuild stage to run Flyway, where that stage is bound to the private subnets of my VPC (where the databases reside). CodeBuild makes the following properties available toward this end:

VpcConfig.VpcId
VpcConfig.SecurityGroupIds
VpcConfig.Subnets

CodeBuild then has access to the database endpoint. Hope this is pertinent.
