### ISSUE TITLE
flyway.configFiles upable to load files : Gradle plugin

### ISSUE THREAD

**Issue by swat2793** [flyway/flyway#2518]
###### Which version and edition of Flyway are you using?
6.0.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using (type & version)?
H2

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Trying to use the flyway.configFiles with gradle plugin in intelliJ for a springboot application. The configuration is as shown below
<img width="561" alt="flyway" src="https://user-images.githubusercontent.com/14159722/65576695-05b72f80-dfa5-11e9-9aa4-e3200c13aad1.PNG">

###### What did you expect to see?
Expected flyway to pick the configuration for the mentioned property file

###### What did you see instead?
Looks like the plugin is unable to load the file 

the below error comes on trying to build

Executing task 'flywayMigrate -x test -Dflyway.configFiles=flyway.properties'...

Task :flywayMigrate FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':flywayMigrate'.
Error occurred while executing flywayMigrate
Unable to load config file: /home/user/Workspace/sample/flyway.properties

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

**Comment by MikielAgutu** [comment]
I've been unable to reproduce this. Can you ensure that your config file is in the expected location (apparently `/home/user/Workspace/sample/`). Can you also try running with `--stacktrace` and `--debug` options and attach the logs? Thanks.

**Comment by alextercete** [comment]
Closing due to lack of response.
