### ISSUE TITLE
Ran migrate instead of baseline, got error; now can't run baseline because of history table

### ISSUE THREAD

**Issue by kippm** [flyway/flyway#2527]
###### Which version and edition of Flyway are you using?
6.0.4, community edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
SQL Server 2016

###### Which operating system are you using?
Windows 10

###### What did you do?
First I tried a migration, which failed, because I didn't create a baseline before. After that I ran the baseline command.

###### What did you expect to see?
The baseline should be stored. This worked like that in version 5.2.4

###### What did you see instead?
Baseline not stored in the table.

**Comment by kippm** [comment]
The problem is not related to the migration. To reproduce what I meant, then just take an empty database and run a baseline. Then delete the only row from the flyway table and run the same baseline again.

I would expect that the baseline would add one row to the flyway table, but it doesn't. The flyway table stays empty.

**Comment by juliahayward** [comment]
OK, thankyou. So the specific problem is that *because* the migration failed, it left an empty schema history table which could then not be baselined? If that's so then I understand the problem now. We will need to carefully consider a behaviour change, as a migration could potentially fail part way through and a subsequent baseline might be misleading.

**Comment by kippm** [comment]
Yes, you are correct. And as stated, this behavior was different (and according to me correct) in 5.2.4.

**Comment by MikielAgutu** [comment]
@kippm You say:

> The problem is not related to the migration. To reproduce what I meant, then just take an empty database and run a baseline. Then delete the only row from the flyway table and run the same baseline again. I would expect that the baseline would add one row to the flyway table, but it doesn't.

Manually altering the schema history table is likely to cause Flyway to enter an inconsistent state. Therefore we can't really support workflows that involve such manual alterations.

In this scenario, you've manually altered the schema history such that it's empty. In this case the Baseline command doesn't do anything. I think this is the correct behavior. All you need to do is run clean, or manually delete the schema history table, and run baseline again.

As much as it is a behavior change between Flyway versions it doesn't seem particularly significant to me.

**Comment by MikielAgutu** [comment]
Actually we'll make baseline produce an exception in this case to make it more clear that baselining an empty schema table is invalid.
