### ISSUE TITLE
flyway-maven-plugin fails after upgrade to 6.0.5

### ISSUE THREAD

**Issue by pzygielo** [flyway/flyway#2528]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.0.5 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
maven plugin

###### Which database are you using (type & version)?
mysql, sqlite, postgres, derby, firebird, hsqldb

###### Which operating system are you using?
linux

###### What did you do?
Upgraded maven plugin and core from 6.0.4 to 6.0.5.

###### What did you expect to see?
As before
```
[INFO] --- flyway-maven-plugin:6.0.4:migrate ---
[INFO] Flyway Community Edition 6.0.4 by Redgate
[INFO] Database: ---
[INFO] Successfully validated 3 migrations (execution time 00:00.020s)
```
but with 6.0.4 bumped to 6.0.5.

###### What did you see instead?
```
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:6.0.5:migrate: org.flywaydb.core.internal.license.FlywayProUpgradeRequiredException: Flyway Pro Edition or Flyway Enterprise Edition upgrade required: batch is not supported by Flyway Community Edition. -> [Help 1]
```

I don't see anything relevant in [Release Notes](https://flywaydb.org/documentation/releaseNotes#6.0.5).

**Comment by kedar-joshi** [comment]
In community edition `isBatch()` and `configuration.getErrorOverrides()` both methods from `ClassicConfiguration` immediately throw `FlywayProUpgradeRequiredException` without `batch` property being set. Calling `if (configuration.isBatch() && configuration.getErrorOverrides().length > 0)` can only result in `FlywayProUpgradeRequiredException`.

```java
public class ClassicConfiguration implements Configuration
{
	// ...

	@Override
	public boolean isBatch()
	{
		throw new org.flywaydb.core.internal.license.FlywayProUpgradeRequiredException("batch");
	}

	@Override
	public String[] getErrorOverrides()
	{
		throw new org.flywaydb.core.internal.license.FlywayProUpgradeRequiredException("errorOverrides");
	}

	// ..
}
```

```java
public class ConfigurationValidator
{
	public void validate(Configuration configuration)
	{
		if (configuration.isBatch() && configuration.getErrorOverrides().length > 0)
		{
			throw new FlywayException("flyway.batch configuration option is incompatible with flyway.errorOverrides.\n" +
											  "It is impossible to intercept the errors in a batch process.\n" +
											  "Set flyway.batch to false, or remove the error overrides.");
		}
	}
} 
```

**Comment by pzygielo** [comment]
> without `batch` property being set

Happens the same even with `-Dflyway.batch=false`.
(With this definition ie. `batch=`**false**, `o.f.c.i.l.FlywayProUpgradeRequiredException` is also thrown in 6.0.4 as well).

**Comment by amadensor** [comment]
Same issue on the command line version:

:flyway-6.0.5 gjohnson$ ./flyway migrate 
ERROR: Flyway Pro Edition or Flyway Enterprise Edition upgrade required: batch is not supported by Flyway Community Edition.
:flyway-6.0.5 gjohnson$

**Comment by kedar-joshi** [comment]
You are right. Anything that touches `batch` property seems to throw `FlywayProUpgradeRequiredException`.

```java
public class ClassicConfiguration implements Configuration
{
	// ...

	@Override
	public boolean isBatch()
	{
		throw new org.flywaydb.core.internal.license.FlywayProUpgradeRequiredException("batch");
	}

	public void setBatch(boolean batch)
	{
		throw new org.flywaydb.core.internal.license.FlywayProUpgradeRequiredException("batch");
	}

	// ..
}
```

**Comment by kedar-joshi** [comment]
Seems that the fix 5557da6 is already committed.

**Comment by alextercete** [comment]
We're already aware of the problem and in the process of releasing 6.0.6 with a fix. Sadly, Maven [isn't having the best day either](https://status.maven.org/incidents/k4zssj3356bs), so the process is taking a bit longer than anticipated.

Sorry for the inconvenience!

**Comment by alextercete** [comment]
Flyway 6.0.6 has now been released. Thanks for bearing with us!

**Comment by kedar-joshi** [comment]
Thank you for quick fix 👍
