### ISSUE TITLE
Previously valid migration now requires paid edition

### ISSUE THREAD

**Issue by Pinwheeler** [flyway/flyway#2529]
###### Which version and edition of Flyway are you using?

"6.0.5"

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle Plugin

###### Which database are you using (type & version)?

Postgresql 12

###### Which operating system are you using?

Mac OSX

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Running `gradle flywayMigrate`

I have 10 versioned flyway migration files that I can upload, but they are all just SQL

###### What did you expect to see?

Just like in the previous versions of Flyway, I expected to see a successful migration on this same migration set. Failing that, I expect to see some documentation somewhere about what is a batch migration and what is not.

###### What did you see instead?

> Task :flywayMigrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  Flyway Pro Edition or Flyway Enterprise Edition upgrade required: batch is not supported by Flyway Community Edition.

**Comment by alextercete** [comment]
Duplicate of #2528.
