### ISSUE TITLE
Should be able to delete repeatable migration scripts

### ISSUE THREAD

**Issue by yarhamjohn** [flyway/flyway#2533]
###### Which version and edition of Flyway are you using?
6.0.6

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
n/a

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle 18.3

###### Which operating system are you using?
Windows 10

###### What did you do?
I created a repeatable migration containing a single stored procedure. At a later date I wanted to delete the stored procedure and the associated repeatable migration.

I tried deleting the repeatable migration script, but this resulted in Flyway considering the repeatable migration to be `Missing` with no way to indicate that it was deliberately removed.
The only other option I could see was to empty the repeatable migration script but keep the file.

Neither of these two options are great solutions because either I have to maintain an empty, redundant repeatable migration script or I constantly get `Missing` entries in my Flyway info queries. 

###### What did you expect to see?
I would expect to be able to delete repeatable migration scripts completely from my Flyway project. The `flyway_schema_history` table could either have all entries for that repeatable migration removed, or a new entry could be created marked as something other than `Missing` (e.g. `Deleted`) so that history is maintained.

**Comment by seb-urbaniak** [comment]
+1

**Comment by cdavid15** [comment]
This has bugged me for a while and would prevent the need to run multiple "repeatable scripts". The first to drop the database object, then another run where the migration only contains a comment indicating the object is removed to ensure the migration doesn't show as missing.

**Comment by MikielAgutu** [comment]
We're thought about this, and our proposal is:
- Scripts that are deleted should rightfully marked as 'missing'
  - To alert users of scripts that no longer exist
- Amend the repair command to mark 'missing' scripts as 'deleted'
- 'deleted' scripts that subsequently re-appear are considered pending

Unfortunately, to implement this feature properly we probably need to update the schema history table. This is a significant change which can only really be made in a major version bump (i.e V7). So it'll have to wait until then.

**Comment by yarhamjohn** [comment]
Sounds like a sensible solution, thanks

**Comment by fipsingdale** [comment]
You could also just write a migration script that deletes the entry for the repeatable you deleted from the schema history table:
`DELETE FROM flyway_schema_history WHERE script = 'R__repeatable_description.sql';`

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).

**Comment by mike-ayres** [comment]
Not sure when redgate took over, but the v7 beta info is now at https://www.red-gate.com/blog/flyway-7-0-0-beta
