### ISSUE TITLE
SQLite: Running PRAGMA foreign_keys=OFF inside a migration does not have any effect

### ISSUE THREAD

**Issue by Regulareveryday** [flyway/flyway#2536]
###### Which version and edition of Flyway are you using?
Flyway 5.2.4 (with Spring)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
The latest version 6.0.7 seems not to be compatible with Spring 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using (type & version)?
SQLite JDBC 3.25.2

###### Which operating system are you using?
Windows 10

###### What did you do?
I created a migration in which I am changing the schema in a way that requires the foreign keys constraint to be turned off. However, foreign keys constraint must be on while the application is running, and it is done by adding "spring.datasource.tomcat.connection-properties=foreign_keys=ON" to the application.properties file. I've tried many ways to it turn off for the time of migration, including running "PRAGMA foreign_keys=OFF" and "PRAGMA foreign_keys=ON" in separate migrations before and after the problematic migration, and also placing these commands at the beginning and at the end of the migration with mixed transactions enabled by adding "spring.flyway.mixed=true" to the application.properties file.

###### What did you expect to see?
Foreign keys constraint turned off for the time of migration

###### What did you see instead?
Foreign keys are still on during migration, and the migration fails when it operates on a non-empty database because of foreign key violation.

**Comment by MikielAgutu** [comment]
I've been unable to reproduce this myself. I've actually encountered the opposite problem - I'm unable to enforce foreign key constraints.

Looks like Flyway isn't able to honor `PRAGMA foreign_keys` settings at all. I've tried amending our JDBC usage to pass relevant properties ([like the solution suggested here](https://stackoverflow.com/a/13377015/5437021)), but it hasn't worked so far. We'll keep investigating.

**Comment by MikielAgutu** [comment]
I've found that you can set the `foreign_keys` parameter to `on` or `off` in the JDBC url to enable and disable foreign key constraints. ([Answer on SO](https://stackoverflow.com/a/41273749/5437021)) For example:

`flyway.url=jdbc:sqlite:db?foreign_keys=on;`

This seems to work in my manual testing. It seems to be a limitation of the JDBC drivers that this is the only way to turn the option on.

@Regulareveryday does that help?

**Comment by MikielAgutu** [comment]
Closed for lack of response.
