### ISSUE TITLE
SQL State: 42000 - Error Code: 1305

### ISSUE THREAD

**Issue by Tauri28** [flyway/flyway#2538]
###### Which version and edition of Flyway are you using?
6.0.0 Community Edition
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI
###### Which database are you using (type & version)?
DBMS: MySQL (ver. 5.5.5-10.3.13-MariaDB-1:10.3.13+maria~bionic)
###### Which operating system are you using?
Windows 10 Pro 1809
###### What did you do?
flyway migrate -url=jdbc:mysql://127.0.0.1/xxx?serverTimezone=UTC -user=xxx -password=xxx -table=xxx -locations=xxx -sqlMigrationSeparator=- -baselineOnMigrate=true -baselineVersion=000 -sqlMigrationPrefix='.
###### What did you expect to see?
Successfully applied 1 migration to schema `xxx`
###### What did you see instead?
WARNING: DB: PROCEDURE xxx.my_procedure_name does not exist (SQL State: 42000 - Error Code: 1305)
Successfully applied 1 migration to schema `xxx` (execution time 00:00.089s)
###### Simplified migration script content:
DROP PROCEDURE IF EXISTS my_procedure_name;

**Comment by juliahayward** [comment]
This is not a bug in Flyway, it is an intentional behaviour of MariaDB (and MySQL). The `IF EXISTS` clause downgrades the 1305 (object doesn't exist) code from an error to a warning, but it is still sent back to the client, and in Flyway's case it is logged in case it is significant.
