### ISSUE TITLE
Questions on if Flyway has any support for integrating with Data Catalogues tools ?

### ISSUE THREAD

**Issue by kishorekkota** [flyway/flyway#2540]
This is a question.

Were there any prior integration between Flyway and Data Catalogue tools ? We are being asked to find a mechanism to have tables created report into Data Catalogue tools like Alation so that Enterprise has insight into Data managed across all the data stores.

I am trying to see if anyone has solved this puzzle before and want to learn from them.

**Comment by alextercete** [comment]
I'm closing this as I think [StackOverflow](https://stackoverflow.com/questions/ask?tags=flyway) might be more suitable for this kind of question (it will probably have more visibility as well).
