### ISSUE TITLE
Ability to have Flyway apply scripts from "locations" list in order that is specified.

### ISSUE THREAD

**Issue by seb-urbaniak** [flyway/flyway#2541]
###### Which version and edition of Flyway are you using?
v6.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MSSQL 14.0.x

###### Which operating system are you using?
Win10 x64

###### What did you do?
Just doing meat-and-potatoes migration.

###### What did you expect to see?
IT WOULD BE GREAT:   if   there existed a new switch  that when turned to ON,  would  force FLYWAY to execute scripts from the "locations" list   in the order that they were specified in, and not in the 'default'/current/alpha order.   (ie.  include the path names in the sort, but honour the individual  folder order specified).
https://flywaydb.org/documentation/commandline/migrate#locations

###### What did you see instead?
From what we understand  the  "locations"  list is consumed,  and   execution commences in alphabetical order.

-The above feature would give us an additional amount of control over things, that we currently don't have-
_Danke Sehr._
BrockSolutions Inc.

**Comment by MikielAgutu** [comment]
Thanks for the request

> The above feature would give us an additional amount of control over things, that we currently don't have

Can you explain a bit more what you mean by this? What additional control do you need over migration execution?

**Comment by seb-urbaniak** [comment]
@MikielAgutu practical example:     i would want my  **scripts/Functions**  subfolder to be always executed/iterated-through ,  before our  **scripts/StoredProcedures**  subfolder is executed.    This has to do with object dependencies,  and warnings MSSQL likes to throw up.
Does that make sense ?

Side Note: In an ideal world,  if i introduce a new (or modify existing) repeatable FN,  and i try to use it in a new V script   i would like Flyway to be smart enough and realize it needs to Create or Alter the FN first before running the V,   but while a related issue;  it would be a much more complex problem - i do realize.

**Comment by MikielAgutu** [comment]
Thanks for the extra information. We've had lots of people report issues which ultimately come down to dependency management, script execution order etc. We're currently thinking about how we can solve this problem to unlock alot of users.

We won't commit to adding this feature in particular, since we'd rather add something that fixes the underlying problem. I'll keep the issue open for reference however.

**Comment by MikielAgutu** [comment]
General problem captured here https://github.com/flyway/flyway/issues/2698
