### ISSUE TITLE
Nested calls to routines containing non-tran operations don't get detected in mixed mode.

### ISSUE THREAD

**Issue by seb-urbaniak** [flyway/flyway#2546]
###### Which version and edition of Flyway are you using?

v6.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command-line

###### Which database are you using (type & version)?

MSSQL 14.0.x

###### Which operating system are you using?

Win10 x64

###### What did you do?
Added new script  sql\Migrations\V11.0__SomethingSomething.sql
which contains a stored procedure call to:   MyLittleSPthatTouchesReplication
That SP has this statement in it :   **EXEC sp_addarticle** ...blah...
Tried to Migrate with Mixed mode = TRUE.

###### What did you expect to see?
Flyway  (if it were able to traverse nested calls)  would detect that in Mixed mode  that V script  should be marked as  [non-transactional].

###### What did you see instead?
V script was not marked as  [non-transactional],   and it errors out    because  sp_addarticle   is not allowed  to   be called within  TRAN  wrapper  that  Flyway creates.

---------------------
I realize this is a very complex problem,     and  it will probably take you quite some  hoop jumping to resolve.      As a temporary workaround   we   fake  inject a NON-TRAN    operation into the V script   just to   get things to run.  Not ideal   -   unless you have a better idea for us.

**Comment by alextercete** [comment]
This is related to #2478.

As you suggested, this is a very complex problem full of edge cases, so we intend to provide a mechanism to force a script [not] to run within a transaction. We haven't settled on anything specific, but it's likely to involve adding a comment to the top of the script, for example:

```sql
-- flyway transactional: true
```

**Comment by alextercete** [comment]
For the record, we decided to go with slightly different approach: you'll need to create a migration configuration file such as:

`V1__My_migration.sql.conf`:
```properties
executeInTransaction=true
```

**Comment by seb-urbaniak** [comment]
@alextercete  Let me make sure I understand your/new approach right,  for  every V script that I want executed in this mode,  one has to make a   conf file,  with the same name ?  and in the usual conf folder ?  and  Flyway will automatically know to  use that conf ?  ....   and now the possible deal breaker:   What if it is one of the callback scripts that currently explodes in my collection ?  (do i just make a conf file with the matching  callback script name ?)

**Comment by alextercete** [comment]
@seb-urbaniak That's very close to how it's been implemented, except that `.conf` files live next to the script they're modifying (and not inside the `conf` folder). For example:

```text
sql
├── beforeMigrate.sql
├── beforeMigrate.sql.conf
├── beforeMigrate__No_configuration.sql
├── V1__My_migration.sql
├── V1__My_migration.sql.conf
└── V2__Migration_with_no_configuration.sql

```

As the example suggests, this approach would work for callbacks as well: just create a `.conf` for the script in question and it will override `executeInTransaction` to the value you set.
