### ISSUE TITLE
Java API debug logging at DbMigrate not working

### ISSUE THREAD

**Issue by KiruthikaSS** [flyway/flyway#2547]
###### Which version and edition of Flyway are you using?

flyway-pro & 6.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

JAVA API

###### Which database are you using (type & version)?

Oracle 12c & RDS

###### Which operating system are you using?

Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

logging.level.org.flywaydb.core.internal.command.DbMigrate=DEBUG

###### What did you expect to see?

Result of each statement, as it get displayed in plsql. At Least the debug messages from DbMigrate.

###### What did you see instead?
With logging.level.org.flywaydb.core=DEBUG -> all the statements are getting displayed from all the version files
With logging.level.org.flywaydb.core.internal.command.DbMigrate=DEBUG, just able to see only the info message. This config does not seems effective.

**Comment by MikielAgutu** [comment]
@KiruthikaSS What information are you trying to get out of the logs?

**Comment by KiruthikaSS** [comment]
I would like to see each statement execution.

Thanks

**Comment by MikielAgutu** [comment]
@KiruthikaSS  Could you try setting log levels on `OracleSqlScriptExecutor` or `DefaultScriptExecutor` instead of `DbMigrate`?

**Comment by MikielAgutu** [comment]
@KiruthikaSS Any news?

**Comment by MikielAgutu** [comment]
Closing for lack of response.
