### ISSUE TITLE
Flyway can't calculate the checksum of a large SQL script 

### ISSUE THREAD

**Issue by yarhamjohn** [flyway/flyway#2549]
###### Which version and edition of Flyway are you using?
6.0.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle 12.1

###### Which operating system are you using?
Windows

###### What did you do?
I exported my database using SQL Developer, creating a SQL file ~32MB in size which I used as an effective baseline. When I tried to run flyway info, I got the following error:

```
Unable to calculate checksum for V001.001__BaselineScript.sql: Input length = 1
: Running flyway info failed: "C:\Program Files\flyway\flyway.cmd" exited with code 1
Flyway Enterprise Edition (unlimited schemas) 6.0.2 by Redgate
Database: jdbc:oracle:thin:@//localhost:1521/db (Oracle 12.1)

ERROR: Unable to calculate checksum for V001.001__BaselineScript.sql: Input length = 1
```

###### What did you expect to see?
I expected to see a standard `flyway info` response. The SQL script is valid and can be run in SQL Developer. When I tried to do something similar but on a much smaller database it all worked which suggests the size of the file is causing the problem.

###### What did you see instead?
See error as described above

**Comment by juliahayward** [comment]
The problem isn't the size - I can get the checksum of a 150MB file happily. I suspect it is an encoding issue. If you can forward us the file (have Slacked you privately) then I'll try to reproduce...

**Comment by juliahayward** [comment]
It would be helpful to know what `flyway.encoding` is set to in config, if anything, and what encoding the offending file is before we proceed?

**Comment by juliahayward** [comment]
OK, having gone down a bit of a rabbit hole the solution is to validate the file encoding and then `flyway repair` if necessary.  Flyway 5.2.4 was much more forgiving but that brings other problems into play.

**Comment by rscero** [comment]
Wanted to add a bit to this discussion. Had this exact problem yesterday, ERROR: Unable to calculate checksum of <script file> Input Length=1.  Looked through many discussions, went down the rabbit hole testing them, none of them worked.  Script was not large at all, ran the repair command, even tried converting the encoding between UTF-8 and ANSI.  Nothing worked.  To make it more confusing, the procedure being changed hadn't been update in probably 4-5 years (prior to us using flyway), the change was minor, and the change script code, when run in SQL, ran fine.  After a LOT of testing, found the issue. Our procedures have a comment header that maintains information on history of changes and other info.  Part of that header is a copyright statement.   Example: 
--COPYRIGHT 2011 ....     Well, in this particular procedure, that had been set at:  © 2011...   Yep, it was the ©  character that was causing the issue.   Removed that, added COPYRIGHT statement, problem solved.

**Comment by hdiass** [comment]
@rscero  saved hours of my life, Cheers to you!

**Comment by Phil-Factor** [comment]
The problem seems to be that by default, flyway is expecting a UTF-8  text encoding. I hit this problem using files generated by SCA that used UTF-16 little-endian. You can specify the encoding in the config file ...

# Encoding of SQL migrations (default: UTF-8). Caution: changing the encoding after migrations have been run
# will invalidate the calculated checksums and require a `flyway repair`.
# flyway.encoding=

... or you can specify the encoding of your migration files using the -encoding parameter.

I chose the 'cowards way out' and  converted the existing files to UTF-8!

**Comment by EnGoPy** [comment]
@rscero  saved my time. The same issue here. Was caused by specific polish chars like "ł, ó" etc. which somehow (perhaps through someones changing file encoding) changed into "�" marks. After moving them into original polish characters - migration went smoothly.
