### ISSUE TITLE
Invalid placeholders substitution character &

### ISSUE THREAD

**Issue by sladis** [flyway/flyway#2552]
###### Which version and edition of Flyway are you using?
6.0.8

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Commandline

###### Which database are you using (type & version)?
Microsoft sql

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

ERROR: Unable to parse statement in V222__banks.sql at line 281 col 2: No value provided for placeholder: &P. Check your configuration!

<code>insert into T2013 (T2013PK_____, T2013STREET_, T2013NO_____, T2013TOWN___, T2013ZIPCODE, T2013T0111_1,T2013ICO____,T2013T0111_2,T2013TECHACC,T2013NOTE___,T2013BNKNAME) values (s2013.nextval,'Ulice','123','string','123456',(select T0111PK_____ from T0111 where T0111CODE___ = 'LST035_0222'),'741852963',(select T0111PK_____ from T0111 where T0111CODE___ = 'LST010_0001'),'','','P&P');</code>

In our Flyway config we are not using placeholders, so we should be using defaults (  ${  )  but somehow flyway is trying to substitute string "&string" in our sql scripts.

**Comment by alextercete** [comment]
@sladis I can't reproduce your issue with SQL Server, but I can see how it might be trying to replace an Oracle SQL*Plus placeholder when it finds the string `P&P`.

Would you mind sharing your `flyway.conf`?

**Comment by sladis** [comment]
Have new info from application admin, DB is oracle 12.5 . I'll paste config soon, but it's pretty much default with customized script extensions and sqlplus syntax on.

**Comment by alextercete** [comment]
@sladis Thanks for the additional information, I've managed a reproduction in Oracle.

As a workaround, you could change the script to disable [placeholder replacement](https://flywaydb.org/documentation/database/oracle#placeholders) using `SET DEFINE OFF`.

**Comment by sladis** [comment]
I recieved config and it is pretty much default except:
flyway.table,flyway.sqlMigrationsSuffixes,flyway.oracle.sqlplus=true . 


DB is really oracle 12.5 .

**Comment by MikielAgutu** [comment]
After further investigation we think this isn't actually a bug.

The variable substitution is working as intended. If you wish to toggle substitution certain scripts then, as Alex set, use the `SET DEFINE` command.

The original report says this occurred on SQL Server. If that is true, then it is a bug only in our SQL Server support since, of course, it doesn't support Oracle SQL*Plus. However we haven't been able to reproduce this so far.

@sladis can you confirm you encountered this on SQL Server?

**Comment by MikielAgutu** [comment]
For more context, in Oracle SQL Developer's SQL*Plus client we tested this script:
```
SET DEFINE ON;
DEFINE P = 'from-var';
CREATE TABLE my_table (text VARCHAR(64));
INSERT INTO my_table (text) VALUES ('P&P');
SELECT * FROM my_table;
```

We found it substituted the value. This is what confirms to us that Flyway's behavior is correct. So it should be a matter of toggling using `SET DEFINE` `ON`/`OFF` when needed.

**Comment by sladis** [comment]
Db is oracle 12.5. Right now we are using newest Flyway for that particular application with placeholderReplacement=false and since we are using this setup error have not occured once.
