### ISSUE TITLE
Can Flyway create the database if it doesn't exist?

### ISSUE THREAD

**Issue by fy-kenny** [flyway/flyway#2556]
5.2.4

Can Flyway create database if not exited?
Database Migration 
but can not create database auto can it?

or could someone tell me which property can active this feature
why it can not support?

or tell me the best practice

Thx

**Comment by fy-kenny** [comment]
I think it is the first thing that will be considering.
to make sure it can manage all lifecycle of database or database.

could someone help me? 

Thx

**Comment by alextercete** [comment]
@fy-kenny Flyway doesn't automatically create the database for you if it doesn't exist. Would you mind explaining why you need this?

**Comment by fy-kenny** [comment]
@alextercete Thank you very much, I have been found this schema autocreation feature,
```yaml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306
  flyway:
    schemas: db1
```

Then, console received msg:
o.f.c.internal.database.DatabaseFactory  : Database: jdbc:mysql://localhost:3306 (MySQL 5.5)
o.f.core.internal.command.DbSchemas      : Creating schema `db1` 

But, I should still thank you :D

I recommend: flyway community should provide some classic usage and cases

**Comment by alextercete** [comment]
@fy-kenny I'm glad you found a way to solve your issue. 👍

**Comment by NervousOrange** [comment]
@fy-kenny 
you could use parameter `createDatabaseIfNotExist` in the  mysql url configuration of flyway
~~~
        <groupId>org.flywaydb</groupId>
	<artifactId>flyway-maven-plugin</artifactId>
	<version>6.4.1</version>
	<configuration>
		<url>jdbc:mysql://localhost:3306/<databaseName>?createDatabaseIfNotExist=true</url>
		<user>root</user>
		<password>123456</password>
	</configuration>
~~~

**Comment by fy-kenny** [comment]
谢谢你回复，很久以前的问题了，有好几种实现方式，最后JDBC URL里添加参数比较方便和合适。

> @fy-kenny
> you could use parameter `createDatabaseIfNotExist` in the mysql url configuration of flyway
> 
> ```
>         <groupId>org.flywaydb</groupId>
> 	<artifactId>flyway-maven-plugin</artifactId>
> 	<version>6.4.1</version>
> 	<configuration>
> 		<url>jdbc:mysql://localhost:3306/<databaseName>?createDatabaseIfNotExist=true</url>
> 		<user>root</user>
> 		<password>123456</password>
> 	</configuration>
> ```

**Comment by dkthezero** [comment]
yeah, thank you. This is very useful for us when create unit test or local test

**Comment by leandross-picpay** [comment]
Has a form to pass that arg in command line ? Because dont work to me :(
