### ISSUE TITLE
Whitespace after "/" delimiter causes migration to fail.

### ISSUE THREAD

**Issue by jeroenroosen** [flyway/flyway#2560]
###### Which version and edition of Flyway are you using?
6.0.8 community

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Works in 4.2, 6.0.7)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle 12

###### Which operating system are you using?
RHEL7

###### What did you do?
SQL file that ends with `"/ "`: a space followed by a whitespace, then migrate.

###### What did you expect to see?
In 4.2 this did not cause any issues, migrate would succeed.

###### What did you see instead?
```
SQL State  : 65000
Error Code : 6550
Message    : ORA-06550: line 6, column 1:
PLS-00103: Encountered the symbol "/" The symbol "/" was ignored.
```

I could find https://github.com/flyway/flyway/issues/2530 and https://github.com/flyway/flyway/issues/2493, it seems that our problem is somewhere in between because we have a trailing whitespace after the `/` which didn't cause any trouble in Flyway 4 and before.

**Comment by alextercete** [comment]
@jeroenroosen Thanks for reporting this.

As you have noticed, we've been chasing `/` issues in Flyway 6 and Oracle for a little while. Hopefully, there aren't many more edge cases to consider after this one.
