### ISSUE TITLE
Custom delimiter

### ISSUE THREAD

**Issue by JFNGO** [flyway/flyway#2563]
###### Which version and edition of Flyway are you using?
6.0.8

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
OracleDB

###### Which operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Using an other delimiter than ";" or "/" for PL/SQL.

###### What did you expect to see?
Statements executed successfully

###### What did you see instead?
Error about the delimiter I'm using, unexpected "..."

So I would like to allow to choose and set a custom delimiter

**Comment by juliahayward** [comment]
What delimiter are you trying to use? How do you indicate to Oracle that it should be interpreted that way?

**Comment by JFNGO** [comment]
I would like to use '/' for standard SQL, the idea is to have new parameters in the conf file that will overwrite the default delimiter by the value set in the conf file?

**Comment by intacctvaler** [comment]
Hi @juliahayward . Could you please let me and Jean know if you need more information on this feature request? Jean has done the code changes to support custom delimiters. Should we go ahead and create a pull request?

**Comment by juliahayward** [comment]
@intacctvaler We'd be happy to take a look at a PR, though you might want to hang on a couple of days and base it on 6.1.1 as we're shipping a fix to #2560 that might affect you. Also, do let us know what test cases you're using, and we can work them into our test suite.

**Comment by alextercete** [comment]
@JFNGO Is this something supported by Oracle at the moment? Why do you need to use a custom delimiter? If you could share an example scenario, that would be very useful.

**Comment by alextercete** [comment]
Closing due to lack of response.

**Comment by JFNGO** [comment]
Hi @alextercete, sorry for the late answer.
Yes custom delimiters are supported by Oracle at the moment. We need to have only one distinct delimiter for both PL/SQL statements and standard statements, we would like to use '/' as delimiter for both.
Can we reopen the issue and submit a pull request?
Thank you

**Comment by juliahayward** [comment]
Yes, a pull request would be welcome, especially if you have an example script (that fails on the current Flyway and passes afterwards) that we can add to our test suite.

**Comment by MikielAgutu** [comment]
Waiting for follow up from https://github.com/flyway/flyway/pull/2670#issuecomment-585977302

**Comment by MikielAgutu** [comment]
@JFNGO Any news?

**Comment by JFNGO** [comment]
@MikielAgutu haven't got the time to work on it yet, will try this week, will keep you update.

**Comment by JFNGO** [comment]
Please refer to [2701](https://github.com/flyway/flyway/issues/2701)
