### ISSUE TITLE
Percona XtraDB 5.7.23-23 Issue

### ISSUE THREAD

**Issue by milannankov** [flyway/flyway#2566]
Version: Flyway Community Edition 6.0.8 by Redgate
Using command line
Database: Percona XtraDB 5.7.23-23
OS: CentOS Linux release 7.5.1804 (Core) 

###### What did you do?
I ran the info command with a config file:
flyway -configFiles=./flyway.test.conf info

###### What did you expect to see?
I expected that the command will succeed.

###### What did you see instead?
I got the following error "ERROR: Flyway Enterprise Edition or MySQL upgrade required: MySQL 5.5 is no longer supported by Flyway Community Edition". I believe that the version of Percona that I am using is not based on Mysql 5.5 but rather Mysql 5.7.

**Comment by juliahayward** [comment]
If you run `SELECT VERSION()` against the database, what result do you get? Do you know which version of the MySQL JDBC driver you are using?

**Comment by milannankov** [comment]
The result is 5.7.23-23-57-log. 
The Mysql driver is mysql-connector-java-8.0.17.jar

**Comment by juliahayward** [comment]
Ah - I see the issue; it's related to previous ones where the JDBC metadata doesn't accurately reflect the database version. I'll have a fix ready for 6.1 which we will release next week.
