### ISSUE TITLE
When SQL with comment and line breaking character CR, it does not work as expected

### ISSUE THREAD

**Issue by kenchan0130** [flyway/flyway#2570]
###### Which version and edition of Flyway are you using?

6.0.8

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

MariaDB 10.4.10

###### Which operating system are you using?

Ubuntu 18.04.3 LTS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

`V1__init.sql` exits file in `/tmp/db/migration`:

```sql
CRATE TABLE `user`(`id` int(10) unsigned NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL', PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
```

And `V2__insert.sql` exits file in `/tmp/db/migration` with comment and line breaking character as `CR` :

```sql
-- insert
INSERT INTO `user`(`name`) VALUES ('name1');
```

Finlay, I executed command: 

```
$ /flyway/flyway -locations=filesystem:/tmp/db/migration -user=root -password=pass -url="jdbc:mysql://localhost:3306/test" clean migrate

Flyway Community Edition 6.0.8 by Redgate
Database: jdbc:mysql://mariadb:3306/test (MySQL 5.5)
Successfully cleaned schema `test` (execution time 00:00.007s)
Successfully validated 3 migrations (execution time 00:00.035s)
Creating Schema History table `test`.`flyway_schema_history` ...
WARNING: DB: Name 'flyway_schema_history_pk' ignored for PRIMARY key. (SQL State: 42000 - Error Code: 1280)
Current version of schema `test`: << Empty Schema >>
Migrating schema `test` to version 1 - init
Migrating schema `test` to version 2 - insert
Successfully applied 2 migrations to schema `test` (execution time 00:00.127s)
```

###### What did you expect to see?

```sql
> select * from `user`;

+-------+------------+
| id    |       name | 
+-------+------------+
| 1     |      name1 |
+-------+------------+
```

###### What did you see instead?

```sql
> select * from `user`;

+-------+----------------+
| id    |           name | 
+-------+----------------+
```

It seems that the table was empty.

**Comment by juliahayward** [comment]
Hi! We've tried to reproduce but appears that Flyway is correctly parsing the script. 

The problem appears to be in the MySQL driver which interprets the V2 script as just a comment - because it doesn't recognise CR-only as a line break.
