### ISSUE TITLE
Delimiter # not supported

### ISSUE THREAD

**Issue by BartBM** [flyway/flyway#2571]
###### Which version and edition of Flyway are you using?
6.0.8

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
It is the latest (stable) version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API.

###### Which database are you using (type & version)?
Mariadb 10.4.2

###### Which operating system are you using?
MacOS

###### What did you do?
The delimiter # does not work. It did with flyway 5.x
Workaround: use delimiter //
```
delimiter #
create procedure someProcedure() BEGIN
END #
delimiter ;
call someProcedure();
```

###### What did you expect to see?
Successful migrations.

###### What did you see instead?
SQL State  : 42000
Error Code : 1305
Message    : (conn=150) PROCEDURE someProcedure does not exist

**Comment by juliahayward** [comment]
The error is that # was still being seen as an alternative single line comment - which is overridden temporarily by `DELIMITER #`. A fix will be included in 6.1.1.
