### ISSUE TITLE
Very slow Flyway.migrate() after upgrade from 4.2.0 to 5.2.4

### ISSUE THREAD

**Issue by LukeLaz** [flyway/flyway#2572]
###### Which version and edition of Flyway are you using?
5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
I can't use any other version since it's managed dependency of Spring Boot 2.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres 9.6, but it doesn't matter

###### Which operating system are you using?
Linux

###### What did you do?
Little background here - we have Spring boot app with more than 1k Flyway scripts. Some of them are huge since we abused Flyway also for inserts of Base64 encoded PDF files to BLOB. Shame on us. 

I work on upgrade of this app to Spring Boot 2 and therefore upgrade of Flyway from 4.2.0 to 5.2.4

What happened after the upgrade was that our test set became really really slow - before it took ~ 25 minutes, after it wasn't able to finish in 90 minutes limit. For each test we run `Flyway.migrate()` on database image that has majority of migrations already applied and we have hundreds (maybe thousands) tests in the set.

The cause is the way Flyway changed the mechanism of reading scripts between the two versions - in version 5.2.4 Flyway parses SQL statements in each migration right when it is read. It does so for each migration on classpath or filesystem regardless of it's already applied or not. The parsing takes in our case approximately 8 seconds for one run of `Flyway.migrate()`.

I was able to verify that if Flyway is changed so that it parses the statements lazily - only when `SqlScript.getSqlStatements()` is called then running time of Flyway.migrate() and therefore our test set is back where it was with Flyway 4.

It's quite hard to make a minimal working example, since high number of migrations is needed for the effect to be observable. How can I help you reproduce it?

**Comment by Lyeeedar** [comment]
Fixed in version 6
