### ISSUE TITLE
Flyway 6.0.3 By Redgate：Soft link path format error

### ISSUE THREAD

**Issue by mangococo** [flyway/flyway#2573]
###### Which version and edition of Flyway are you using?

Flyway 6.0.8 By Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I am using the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command-line

###### Which database are you using (type & version)?

postgresql 10.6

###### Which operating system are you using?

cent-os 7.4

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I am moving the flyway from one directory to another and calculating md5 information for each file.

###### What did you expect to see?

I want to be able to calculate md5 for every file under flyway.

###### What did you see instead?

When traversing to 'flyway/jre/legal/java.compiler/ADDITIONAL_LICENSE_INFO', the system prompts that the file does not exist. After viewing, the directory pointed to by all the soft connections under a does not exist, but in fact only the path separator format used in the soft connection is wrong.

expect:  ADDITIONAL_LICENSE_INFO -> ../java.base/ADDITIONAL_LICENSE_INFO
actual: ADDITIONAL_LICENSE_INFO -> ..\java.base\ADDITIONAL_LICENSE_INFO

**Comment by juliahayward** [comment]
`flyway/jre` is an embedded copy of OpenJDK... this isn't a bug in Flyway per se as far as I can see.
