### ISSUE TITLE
Flyway + Spring boot  + DbMigrate debug log does not work

### ISSUE THREAD

**Issue by KiruthikaSS** [flyway/flyway#2574]
###### Which version and edition of Flyway are you using?
Flyway Pro 6.0.8 

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

NA

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?

Oracle 12C

###### Which operating system are you using?

Windows 10 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I am using Flyway + SpringBoot and trying to enable debug level logging for Migrate command alone. Configured below in application.properties file, but this is not printing the debug logs
logging.level.org.flywaydb.core.internal.command.DbMigrate=DEBUG

**This WORKS**, but am just interested in Migrate and undo logs->logging.level.org.flywaydb.core.internal=DEBUG

**NOT working**->logging.level.org.flywaydb.core.internal.command.DbMigrate=DEBUG

**NOT working**-> logging.level.org.flywaydb.core.internal.command=DEBUG

###### What did you expect to see?
DbMigrate debug level log messages. 

###### What did you see instead?
Just seeing only Info level log messages.

**Comment by alextercete** [comment]
The Spring Boot Flyway integration is developed by the Spring Boot team, so it's best to report this directly [to them](https://github.com/spring-projects/spring-boot/issues/new). It might be that Flyway needs to change in some way to support this change, in which case feel free to reopen this with more details.
