### ISSUE TITLE
Flyway 6.0.8 parser stumbles over `–` (emdash), unknown char encountered

### ISSUE THREAD

**Issue by marthjod** [flyway/flyway#2581]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 6.0.8 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Tried flyway/flyway:6.1.0-alpine, but this seems to contain 6.0.8 as well [sic].

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line (Docker flyway/flyway:6.0.8-alpine)

###### Which database are you using (type & version)?

PostgreSQL 11.1

###### Which operating system are you using?

Alpine Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

```sql
-- ...
INSERT INTO "template"("object_type","locale_id","field","template")
VALUES
(E'foo',16,E'bar',E'foo – bar'),
-- ...
```

###### What did you expect to see?

Successful migration.

###### What did you see instead?

```
ERROR: Unable to parse statement in /flyway/fixtures/afterMigrate.sql at line 7963 col 1: Unknown char – encountered on line 7981 at column 75
```

(Column number doesn't match anymore due to sanitization, of course.)

**Comment by juliahayward** [comment]
As an aside - when you say "Tried flyway/flyway:6.1.0-alpine, but this seems to contain 6.0.8 as well [sic]." could you elaborate?

**Comment by juliahayward** [comment]
Could you confirm the encoding of the migration script, and whether you've set `flyway.encoding` in config / command line parameters?

**Comment by juliahayward** [comment]
Also, are you able to provide more of the script (privately, if necessary) for context? The parser should be recognising that it is processing a string literal and ignore the actual contents, including the em-dash, and it does so for me locally.

**Comment by marthjod** [comment]
> As an aside - when you say "Tried flyway/flyway:6.1.0-alpine, but this seems to contain 6.0.8 as well [sic]." could you elaborate?

Running the Docker image tagged 6.1.0, the binary contained in it announces its version with 6.0.8.
```
docker run -it flyway/flyway:6.1.0-alpine -v
Flyway Community Edition 6.0.8 by Redgate
```

**Comment by juliahayward** [comment]
Thanks - I'll split that off as a separate issue.

**Comment by marthjod** [comment]
> Could you confirm the encoding of the migration script, and whether you've set `flyway.encoding` in config / command line parameters?

The encoding is UTF-8, and none is configured when calling `migrate` (default is UTF-8 according to docs). Setting it explicitly to "UTF-8" gives the same error. There are UTF-8 characters (letters) in preceding lines which are no problem for the parser.

**Comment by marthjod** [comment]
> Also, are you able to provide more of the script (privately, if necessary) for context? The parser should be recognising that it is processing a string literal and ignore the actual contents, including the em-dash, and it does so for me locally if I have a script with just this one line.

The error message stems from here https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/parser/Parser.java#L496, and afaics the parser is not ignoring the input at this point yet, but rather emdash (and potentially more chars) as valid input.

**Comment by juliahayward** [comment]
That's true - but it should have seen the opening single quote prior to the emdash, and gone into `handleStringLiteral()` which ignores everything up to the closing single quote. The fact that it didn't suggests it believes it's no longer in a string literal - but I can't see why just yet.

**Comment by juliahayward** [comment]
If you're able to produce a redacted script file that produces the error that would be really helpful! (The Docker issue is #2585 and is now resolved)

**Comment by marthjod** [comment]
(Thanks for resolving #2585.)

Your remark about quotes pointed me in the right direction: We apparently have wrongly escaped single quotes in preceding lines (which I left out unfortunately) that are the actual cause for the parser's behavior.

```sql
INSERT INTO "template"("object_type","locale_id","field","template")
VALUES
(E'foo',331,E'heading_1',E'What\'s new...?'),
(E'foo',16,E'bar',E'foo – bar'),
```

Escaping using `''` works (the table will have `'`):

```sql
INSERT INTO "template"("object_type","locale_id","field","template")
VALUES
(E'foo',331,E'heading_1',E'What''s new...?'),
(E'foo',16,E'bar',E'foo – bar'),
```

Thank you very much for your swift support!

**Comment by juliahayward** [comment]
Many thanks for letting us know - glad we could help!
