### ISSUE TITLE
-json and -logFile not supported in config files or environment variables

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#2583]
###### Which version and edition of Flyway are you using?
6.1.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MSSQL 2017 CU17 in Docker

###### Which operating system are you using?
MacOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Added the following to config files
```
flyway.json=true
flyway.logFile=test
```
and included the following environment variables (in separate executions)
```
FLYWAY_JSON=true
FLYWAY_LOG_FILE=test
```
and ran `flyway info`.

###### What did you expect to see?
JSON formatting and a log file created.

###### What did you see instead?
Normal formatting and no log file.  Since all other configuration can be done via the command line, config files, and environment variables, I expected these to function the same way.

**Comment by MikielAgutu** [comment]
This was an intentional decision. We're planning to revisit the accessibility of these options, but can't commit to anything yet. Thanks for sharing your thoughts, we'll keep this issue open for our reference.

**Comment by esauser** [comment]
@MikielAgutu it might be worth specifically documenting this to avoid others wasting the time that I did.  I know it isn't documented as working, but I assumed that was the miss (since everything else functions this way) as opposed to it actually not being implemented.

**Comment by esauser** [comment]
Somewhat related to https://github.com/flyway/flyway/issues/2515.

**Comment by alextercete** [comment]
We've moved these two options to the _[Command-line > Output](https://flywaydb.org/documentation/commandline/#output)_ section of the documentation, which hopefully makes it clearer that they are only applicable to the command-line.
