### ISSUE TITLE
Consider option for more output on data-altering migration results, that's less verbose than `DEBUG / -X`

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2587]
Related to #2559 but for cases where you don't have an explicit option like Oracle's `SET FEEDBACK ON`

"When we run SELECT queries we get output
When do we run INSERT or UPDATE or CREATE we do not see output but we see SUCCESS message or ERROR message.

It would be good to see the output with SUCCESS message as many developers want to know how many rows were inserted or updated or a package was created and many objects like that."

**Comment by MikielAgutu** [comment]
It's possible to see this by setting the log level to debug (e.g. with `-X` from the CLI). You get something like:
```
DEBUG: Executing SQL: INSERT INTO tasks (title) VALUES ('Do something')
Update Count: 1
```

Though of course it might be nicer to have a separate option to avoid seeing all the debug information.

**Comment by juliahayward** [comment]
Leaving this case open to consider whether we should allow output without going as far as DEBUG.

**Comment by juliahayward** [comment]
More information:

Hi,
I used the -X debug flag and this is the output I got
DEBUG: Executing SQL: grant execute on  martin_welcome_msg  to schema1
DEBUG: Update Count: 0
DEBUG: Sending batch of 0 statements to database ...
DEBUG: Executing SQL: create or replace synonym martin_welcome_msg for schema1.martin_welcome_msg
DEBUG: Update Count: 0

What we really want is a output as 
Grant Success
Synonym created and so on

Please see if you can include a support for it

**Comment by MikielAgutu** [comment]
This is a big feature that we can't really commit to doing. I agree that -X can be too verbose sometimes - but that's a slightly different issue.
