### ISSUE TITLE
Flyway output not colored in jenkins when using ansiColors plugin

### ISSUE THREAD

**Issue by morl-la** [flyway/flyway#2590]
###### Which version and edition of Flyway are you using?
6.1.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Jenkins Flyway Runner plugin

###### Which database are you using (type & version)?
postgres 11.4 but doesn't really matter

###### Which operating system are you using?
linux

###### What did you do?
Running a jenkins build containing a call to flyway wrapped with the ansiColor('xterm') step.

###### What did you expect to see?
The flyway output colored the same as in a standard terminal

###### What did you see instead?
Everything in black

From the documentation I quote: "Colors are suppressed if stdout is not associated with a terminal."
Perhaps there should be a configuration parameter to force color encodings.

**Comment by alextercete** [comment]
@morl-la We're thinking about adding a new CLI-only option `-color=` which would accept `always`, `never` or `auto` (the current behaviour, which would be the default if the option is omitted). What do you think?

**Comment by morl-la** [comment]
Sounds like it would allow what I need. Thanks.

**Comment by morl-la** [comment]
Great Success!
![image](https://user-images.githubusercontent.com/44611568/73185720-3cee4680-4127-11ea-8247-55ae819ac140.png)
