### ISSUE TITLE
aloneOnLine has no effect

### ISSUE THREAD

**Issue by JFNGO** [flyway/flyway#2591]
###### Which version and edition of Flyway are you using?
6.1.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
OracleDB

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
![image](https://user-images.githubusercontent.com/56840868/70277162-b04a8c00-1766-11ea-9608-725e89a7a4c1.png)
Tried to run this statement using "flyway migrate".

###### What did you expect to see?
The migration should have failed because for PL/SQL the delimiter '/' is supposed to be on a line by itself.
![image](https://user-images.githubusercontent.com/56840868/70277947-27cceb00-1768-11ea-84e3-da42f9328266.png)

###### What did you see instead?
This migration succeeded.

**Comment by juliahayward** [comment]
Fixed in v6.1.2
