### ISSUE TITLE
Postgre SCRAM Authentication not possible because .jre driver

### ISSUE THREAD

**Issue by fkoehler** [flyway/flyway#2594]
###### Which version and edition of Flyway are you using?

6.0.8 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes, with the latest as well

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line (via the docker image, but that is not relevant)

###### Which database are you using (type & version)?

Postgresql 12.0

###### Which operating system are you using?

Ubuntu 18.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Cofigured postgres server with 

postgresql.conf:
```
password_encryption = 'scram-sha-256'
```

###### What did you expect to see?

A normal execution of migrations like

```
Database: jdbc:postgresql://host/db (PostgreSQL 12.0)
Successfully validated 11 migrations (execution time 00:00.022s)
```

###### What did you see instead?

```
Flyway Community Edition 6.0.8 by Redgate
ERROR: 
Unable to obtain connection from database (jdbc:postgresql://host/db) for user 'my-user': SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08004
Error Code : 0
Message    : SCRAM authentication is not supported by this driver. You need JDK >= 8 and pgjdbc >= 42.2.0 (not ".jre" versions)
```

The reason for the bug is because the postgres driver in the flyway package is the "jre6" (`postgresql-42.2.8.jre6.jar`) version of the driver which does not support SCRAM authentication.

It works when I change the `postgresql-42.2.8.jre6.jar` to the "normal" version of the driver: `postgresql-42.2.8.jar`

**Comment by juliahayward** [comment]
I'm having difficulty reproducing this: both FLyway and SQuirreL seem to connect correctly with the 42.2.8.jre6 driver - the only difference apparently being that I've set SCRAM up in a createDatabase script: 

`ALTER SYSTEM SET password_encryption = 'scram-sha-256';
CREATE ROLE julia LOGIN ENCRYPTED PASSWORD 'redacted';
CREATE DATABASE flyway_db WITH OWNER = julia ENCODING = 'UTF8' TABLESPACE = pg_default;`

**Comment by fkoehler** [comment]
Did you reload the server after changing the setting? Maybe it did not come into effect?
Can you reproduce it via setting it in the config file (Probably you don't want to in order to set up an automated test) ?

**Comment by juliahayward** [comment]
Running `SHOW password_encryption` via Squirrel returns `scram-sha-256`, so I think the setting has taken effect. Strange, will keep on looking!

**Comment by juliahayward** [comment]
Putting in 7.x for now as changing the driver shipped with the command line may cause problems for Java 7 users, which we're committed to supporting in 6.x. I'll update the documentation site to indicate the workaround.

**Comment by TomRed97** [comment]
Hello. Any news from that issue? I also have an issue with postgres driver  now.

**Comment by juliahayward** [comment]
You should be able to drop the newer Postgres driver in manually (into the `drivers` folder in Flyway) and it will just work; alternatively Flyway 7 will ship with the latest driver this week.

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).

**Comment by TomRed97** [comment]
I like to say thank you and all your team, thank you very much for your support.
