### ISSUE TITLE
Snowflake stored procedure issues in 'Migarte' and 'Clean' commands

### ISSUE THREAD

**Issue by zjwu2000** [flyway/flyway#2596]
###### Which version and edition of Flyway are you using?
6.1.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Snowflake 3.52

###### Which operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Issue 1:**
if a stored procedure migration has the semicolon ";" put in a separate line at the end of the script file, the "Migrate" command reports "Unable to parse statement" error

Here is the sample migration code:

```
CREATE OR REPLACE PROCEDURE MDM.SP_ARRAY_GET_INF_SCHEMA_TABLES () RETURNS VARIANT LANGUAGE JAVASCRIPT
AS $$ 
var results_array = []; 
var rs = snowflake.createStatement( 
            { sqlText: 'SELECT TABLE_SCHEMA,TABLE_NAME FROM INFORMATION_SCHEMA.TABLES;' }).execute(); 
    while (rs.next()) 
    {    var schema_name = rs.getColumnValue(1);    
        var table_name = rs.getColumnValue(2);  
        results_array.push([schema_name, table_name]); 
    }  
return results_array; 
$$
;
```
Here is the error message:
`ERROR: Unable to parse statement in C:\flyway-6.1.1\sql\Procedures\R__Procedure_mdm_nossn_MatchRecursion.sql at line 1 col 1: Index 256 out of bounds for length 256`

Issue 2:
The "Clean" command failed in dropping stored procedure(s) from the Snowflake database.
For example, I successfully migrated two functions and two stored procedures into the Snowflake database, then I run "Flyway clean" command to clean the database. The "clean" command completed without error, when I check the database, the two functions were dropped, but the two stored procedures are still in the database.

Here are the sample statements I use to check the functions and procedures in Snowflake database:

```
SHOW USER FUNCTIONS IN SCHEMA MDM;
SHOW PROCEDURES IN SCHEMA MDM;

```

###### What did you expect to see?
No error

###### What did you see instead?
For issue 1:  the "Migrate" command returns the error.
For issue 2: the "Clean" command doesn't drop the procedures.

**Comment by MikielAgutu** [comment]
Thanks for reporting these bugs. We've got a fix which will be shipped in Flyway 6.1.2.
