### ISSUE TITLE
Is there any documentation on how to use this with the Exposed library?

### ISSUE THREAD

**Issue by AdityaAnand1** [flyway/flyway#2616]
https://github.com/JetBrains/Exposed

**Comment by MikielAgutu** [comment]
We aren't aware of any way to integrate Flyway with Exposed. That isn't to say it's impossible, just that we don't know enough about Exposed to advise.

From [this issue on the Exposed GitHub repo](https://github.com/JetBrains/Exposed/issues/165), it looks like migrations support is a long standing request for this tool.

We'll keep this open to see if it gets more responses.

**Comment by MikielAgutu** [comment]
Closing for lack of response.

**Comment by AdityaAnand1** [comment]
That is unfortunate. This is still a real unsolved issue.
