### ISSUE TITLE
Target dedicated artifacts

### ISSUE THREAD

**Issue by Koriit** [flyway/flyway#2622]
###### Which version and edition of Flyway are you using?
6.1.4 CE but it probably applies to all releases.
###### Which client are you using?
N/A
###### Which database are you using (type & version)?
N/A
###### Which operating system are you using?
N/A

Hi,
I have been wondering if it would be possible to add dedicated flyway artifacts per DB. Flyway isn't quite featherweight and as I checked roughly 40% of the size is just luggage of the other targets in the `org.flyway.core.internal.database` package, which is never gonna by used in my specific deployment(flyway integrated into application startup). I could bet that holds true for at least 80% of similar deployments.

In my opinion the ideal solution would be providing:
1. One uber artifact containing everything - just like currently - for CLI, backwards-compatibility and people who don't care or actually need it
2. One flyway-core artifact
3. One artifact for each DB target

Motivation?
Well, there isn't any "hard" reasoning for this apart for striving for excellence. Size does matter... ;)

Thanks!

**Comment by MikielAgutu** [comment]
We think Flyway's footprint is fairly small already. This would be a lot of extra work for only a minimal gain. It would also introduce more scope for failure due to more artifacts to test.

**Comment by Koriit** [comment]
That's fine too.
