### ISSUE TITLE
Print statements in dry run output

### ISSUE THREAD

**Issue by nyctef** [flyway/flyway#2623]
###### Which version and edition of Flyway are you using?

6.1.4 Enterprise

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

cli/docker

###### Which database are you using (type & version)?

Oracle 18c express (although this probably applies to most db types?)

###### Which operating system are you using?

Windows

###### What did you do?

`docker run -e ... -v ... flyway/flyway6.1.4 migrate "-dryRunOutput=/flyway/conf/output.sql"`

Currently flyway generates dry run output that looks like this:

```sql
-- Executing: migrate -> v6 (with callbacks)
------------------------------------------------------------------------------------------

-- Source: ./sql/V6__generated.sql
----------------------------------
ALTER TABLE talkr_cust.person DROP ("NAME");
-- ...
INSERT INTO "SCHEMA"."flyway_schema_history" ("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "execution_time", "success") VALUES (6, '6', 'generated', 'SQL', 'V6__generated.sql', 1683464225, 'SYSTEM', 3, 1);
```

It'd be handy for us if lines like `-- Executing` could be print statements rather than comments - that way the script would generate progress messages as it executes. I'd be happy to help work on this.

**Comment by Lyeeedar** [comment]
On further investigation, this may not be something we want flyway to think about. Only a small subset of databases support any sort of writing to output, and as such this change would introduce inconsistencies to how flyway behaves across databases.

We will move this to On The Radar just incase theres a swell of interest for this feature, but for now we won't be looking to implement this.

**Comment by MikielAgutu** [comment]
This looks very difficult to do, and probably not particularly valuable.
