### ISSUE TITLE
"Flyway parsing bug" error when processing SAP HANA view

### ISSUE THREAD

**Issue by stesix** [flyway/flyway#2624]
###### Which version and edition of Flyway are you using?
6.1.4 community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
cli

###### Which database are you using (type & version)?
sap hana 2

###### What did you do?
I tried to create a sap hana view

###### What did you expect to see?
the view in the db

###### What did you see instead?
Flyway parsing bug: unable to decrease block depth below 0
[...]

It's possible to reproduce the issue by adding a view using CASE. e.g.
```sql
create view my_test_case as
  select 
    case when table_name = 'testing' then 'testing' else table_name end
  from tables;
```

The issue is in flyway-core/src/main/java/org/flywaydb/core/internal/database/saphana/SAPHANAParser.java. The CASE portion ends with END but the parser considers the END to be used only with BEGIN, DO or IF (that are normally not used in views afaik).

EDIT: fixed the statement...

**Comment by alextercete** [comment]
@stesix Thanks for the bug report.

We've identified a fix and we expect to include it in the next release.
