### ISSUE TITLE
Migration not happening and no log output

### ISSUE THREAD

**Issue by stoffel2107** [flyway/flyway#2628]
###### Which version and edition of Flyway are you using?
```xml
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-core</artifactId>
    <version>6.1.3</version>
</dependency>
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
It is used inside a Java Spring Boot application. Imported through maven.

###### Which database are you using (type & version)?
The problematic database is an mssql server 2017 (as far as I know)

###### Which operating system are you using?
I am using Linux, but the application is also running on Windows and throwing the error there too.

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I started to use flyway to migrate all persistent databases to a newer Camunda version.

I've written a code snippet which determines the current database version and then baselines and migrates if necessary, using Flyway. On PostgreSQL and h2 the migration works fine.. Using the mssql server is the only problem:

On start, My code realizes the database still uses an older camunda version and configures flyway and prepares for a migration. Logging get's up to 1 or 2 lines before the baseline and migrate but then just stops without any notice...

```java
log.info("Version table wasn't found.. Baselining version 1 and using flyway to migrate to the current version");
flyway = flywayConfiguration.baselineVersion("1").load();
flyway.baseline();
flyway.migrate();
log.info("Database migration done");
```
This is the code.. And the configuration is correct (loaded from the camunda process engine which has a working connection) the first line is shown in the logs.. And the log file is also showing that Flyway has been initialized. After the first info log flyway just stops..  baseline doesn't even happen

###### What did you expect to see?

I expected to see flyway attempting a migration and either throw an error or logging a successful migration/writing the flyway_schema_log table

###### What did you see instead?
Nothing.

**Comment by alextercete** [comment]
@stoffel2107 Thanks for reporting this.

My suspicion is that it's hanging when trying to connect to the database. Could you share the format of the URL you're using?

Also, out of curiosity, is there any reason why are you checking the schema history table yourself? Flyway will check for an existing schema history table and baseline if necessary when you run `migrate` with [`baselineOnMigrate`](http://localhost:4000/documentation/commandline/migrate#baselineOnMigrate) set to `true`.

**Comment by stoffel2107** [comment]
# Why I check for myself:
I'm checking for an existing `act_ge_schema_log`, It's very crappy rn. the table `act_ge_schema_log` is a camunda specific table which holds information of the camunda version deployed in the database rn. Problem is that table was first introduced in 7.11.0 so the only way it'll work is if I check if that table exists.. If not -> I just assume it's 7.9.0 because thats the only camunda version I ever used and then start to migrate. The check for the flyway_schema_history is done by flyway as it should be.

# URL
`jdbc:sqlserver://mssql-srv-2\\mssql2012:1433;databaseName=<DB_NAME>`

**Comment by stoffel2107** [comment]
Okey. I got the error of the server...

It seems like the logger is misconfigured, because if I try the smelly version of testing with my machine against the SQL Server the following log output appears:
`Flyway Enterprise Edition or SQL Server upgrade required: SQL Server 2012 is no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.`

**Comment by alextercete** [comment]
@stoffel2107 Thanks for the update. I'm glad you got to the bottom of the issue!

**Comment by stoffel2107** [comment]
Thanks for your quick help ;)
