### ISSUE TITLE
Feature request: Custom placeholder defaults

### ISSUE THREAD

**Issue by scottsteen** [flyway/flyway#2629]
###### Which version and edition of Flyway are you using?
6.1.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line. This would apply to all, though.

###### What feature would you like?
I'd like to see a feature which allows me to provide custom defaults for any placeholder not provided. These would be written inline or via a defaults file alongside the migrations. Given that issue #2297 introduced a couple of static placeholder defaults, the `:` syntax could be re-used. The bash style `:-` syntax would also be reasonable if you wished to keep the use-cases separated.

This would be great for helping with the dev story at my company. Locally, we want the flyway command to be as simple as possible. Having the invocation grow as more placeholders are added is not ideal. The placeholders come in to play during CI/env deployment where we need to parameterise the invocation. 

For example, sensitive information such as passwords should be fed into environments & not kept in source control. For local dev, we'd want a known value.

Example (Postgres):
V0__custom_placeholder_defaults.sql
```
CREATE USER x WITH PASSWORD ${usr_pass:-BadPassword123};
```
Executing `flyway migrate` would create user `x` with password `BadPassword123`.
Executing `flyway migrate -placeholders.usr_pass=StrongPass456` would create user `x` with password `StrongPass456`.

I'm happy to submit a PR if you think this would be a useful feature.

**Comment by alextercete** [comment]
@scottsteen Couldn't this be solved using [multiple config files](https://flywaydb.org/documentation/commandline/#config-files)?

For example:

`flyway.conf`
```properties
flyway.placeholders.usr_pass=BadPassword123
```

`flyway.Production.conf`
```properties
flyway.placeholders.usr_pass=StrongPass456
```

In Development, you'd run `flyway migrate`. In Production, you'd run `flyway migrate -configFiles=flyway.Production.conf`.

**Comment by scottsteen** [comment]
Ah, yes! I was unaware of config files. This fits the bill perfectly. Thanks for the pointer. Next time I'll be sure to read the manual first!
