### ISSUE TITLE
"initSql" as a callback

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2630]
At the moment any SQL that needs to be executed on a new connection is passed in the `initSql` parameter. There are some potential issues:
- the SQL required is too large and cumbersome to pass on a command line easily
- the SQL is difficult to escape correctly for use in a command line
- the SQL isn't source-controlled in the same way as migrations and callbacks are

In those cases, would the ability to use a callback-like `initSql.sql` file instead be valuable to anyone?

**Comment by MikielAgutu** [comment]
Note that multi-line config options are [coming in Flyway 6.3](https://github.com/flyway/flyway/issues/2555). This'll make it easier to define longer scripts in the config file, albeit with visible newline delimiters (unsightly, but still better than a single line...).

This could be a reasonable compromise for those that need longer scripts in `initSql` for the time being, although a new callback still seems ideal.

**Comment by juliahayward** [comment]
A further suggestion - call it `init` and allow a Java callback as well as a SQL one

**Comment by DoodleBobBuffPants** [comment]
Closing until further interest
