### ISSUE TITLE
Getting reference to FlywayCallback that does not exist in project

### ISSUE THREAD

**Issue by jtlambjr** [flyway/flyway#2632]
###### Which version and edition of Flyway are you using?

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-maven-plugin</artifactId>
            <version>6.1.3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.flywaydb</groupId>
                    <artifactId>flyway-core</artifactId> <-- mvn dependency:tree was showing 5.2.4 being referenced
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>6.1.3</version>
        </dependency>

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I believe this is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using (type & version)?

Oracle 12

###### Which operating system are you using?

Mac 10.15.2

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I deployed the jar, triggering Flyway to execute

###### What did you expect to see?

Logging that I added for the afterValidate event

###### What did you see instead?

   2020-01-16T16:14:33.83-0500 [APP/PROC/WEB/0] OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration': Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type org.flywaydb.core.api.callback.FlywayCallback not present

I am implementing the Callback interface and do not see FlywayCallback referenced anywhere in my code or in the flyway-core classes in the classpath.

These are the classes that I see in the callback package:
org.flywaydb.core.api.callback.BaseCallback
org.flywaydb.core.api.callback.Callback
org.flywaydb.core.api.callback.Context
org.flywaydb.core.api.callback.Error
org.flywaydb.core.api.callback.Event
org.flywaydb.core.api.callback.Statement
org.flywaydb.core.api.callback.Warning

**Comment by juliahayward** [comment]
The `FlywayCallback` class was replaced after 5.2.4 by `BaseCallback` -  so it looks like your version of Spring Boot was built against an out-of-date version of flyway-core.jar. What version of Spring Boot are you using?

**Comment by jtlambjr** [comment]
We are using Spring Boot Starter 2.2.2.RELEASE

**Comment by jtlambjr** [comment]
I checked the effective POM file that is generated and I see that Spring Boot Starter is bringing in version 5.2.4. I didn't realize that it was bringing in Flyway at all, and, since it is the newest version of Starter, I thought it would at least have a newer version of Flyway if it did bring it in. Sorry for the bother.

I'll just need to look at the older version of the documentation to see how to use the callbacks until Starter brings in a newer version.  Thanks!

**Comment by juliahayward** [comment]
Not a problem - it's good for us to know and perhaps we can nudge them to move on!
