### ISSUE TITLE
Instructions for usage via Maven are wrong or don't work

### ISSUE THREAD

**Issue by richardrflores** [flyway/flyway#2636]
###### Which version and edition of Flyway are you using?
6.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven

###### Which database are you using (type & version)?
SQL Server

###### Which operating system are you using?
Windows

###### What did you do?
I'm trying to run a migration using the instructions on the Maven website under the Enterprise Edition tab: https://flywaydb.org/documentation/maven/

Driver was installed using the following instructions: https://flywaydb.org/documentation/database/sqlserver

###### What did you expect to see?
Migrations to work as documented using Maven.

###### What did you see instead?
After updating the pom file and the settings config I get the following error:

` No plugin found for prefix 'flyway' in the current project and in the plugin groups [com.oracle.weblogic, org.sonarsource.scanner.maven, org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (P:\Users\riflores\.m2\repository), nexus (http://jfrog.aws.wfscorp.com/artifactory/maven-mirror)] -> [Help 1]`

![image](https://user-images.githubusercontent.com/1383703/72764210-bb3d6c80-3bac-11ea-81d0-161c09310c22.png)

**Comment by juliahayward** [comment]
Would you be able to share your pom file? In the screenshot it seems incorrect that it's looking for anything in the `org.flywaydb.enterprise` namespace.

**Comment by alextercete** [comment]
@richardrflores You might be missing your license key in `<user-home>/.m2/settings.xml`:

```xml
<settings>
    <servers>
        <server>
            <id>flyway-repo</id>
            <username>your-flyway-license-key</username>
            <password>flyway</password>
        </server>
    </servers>
    ...
</settings>
```

**Comment by richardrflores** [comment]
@alextercete I updated the settings.xml file with my license. Below is my pom file.

`<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.mycompany.my_migrations</groupId>
  <artifactId>my-migrations</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>my-migrations</name>
  
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>7.4.1.jre11</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <pluginRepositories>
    <pluginRepository>
      <id>flyway-repo</id>
      <url>https://repo.flywaydb.org/repo</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <pluginManagement>
      <plugins>

        <plugin>
          <groupId>org.flywaydb.enterprise</groupId>
          <artifactId>flyway-maven-plugin</artifactId>
          <version>6.1.4</version>
          <configuration>
            <user>flywayUser</user>
            <password>*******</password>
            <schemas>dbo</schemas>
            <url>jdbc:sqlserver://myserver;databaseName=mydb;integratedSecurity=false</url>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>com.microsoft.sqlserver</groupId>
              <artifactId>mssql-jdbc</artifactId>
              <version>7.4.1.jre11</version>
            </dependency>
          </dependencies>
        </plugin>

        
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
`

**Comment by richardrflores** [comment]
Hi @alextercete, yes, I have done that already. As I mentioned in my original post, I'm following the instructions for setting up flyway for enterprise edition. 

It might be worth mentioning, using `<groupId>org.flywaydb</groupId>` isntead of `<groupId>org.flywaydb.enterprise</groupId>` seems to work, but I get an error message telling me to use the enterprise edition. The groupId with "org.flywaydb.enterprise" does not seem to work.   

Below is my pom file for reference. 

    <?xml version="1.0" encoding="UTF-8"?>
    
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
      <modelVersion>4.0.0</modelVersion>
    
      <groupId>com.mycompany.my_migrations</groupId>
      <artifactId>my-migrations</artifactId>
      <version>1.0-SNAPSHOT</version>
    
      <name>my-migrations</name>
      
      <url>http://www.example.com</url>
    
      <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
      </properties>
    
      <dependencies>
        <dependency>
          <groupId>com.microsoft.sqlserver</groupId>
          <artifactId>mssql-jdbc</artifactId>
          <version>7.4.1.jre11</version>
        </dependency>
    
        <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
          <version>4.11</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
    
      <pluginRepositories>
        <pluginRepository>
          <id>flyway-repo</id>
          <url>https://repo.flywaydb.org/repo</url>
        </pluginRepository>
      </pluginRepositories>
    
      <build>
        <pluginManagement>
          <plugins>
    
            <plugin>
              <groupId>org.flywaydb.enterprise</groupId>
              <artifactId>flyway-maven-plugin</artifactId>
              <version>6.1.4</version>
              <configuration>
                <user>flywayUser</user>
                <password>*******</password>
                <schemas>dbo</schemas>
                <url>jdbc:sqlserver://myserver;databaseName=mydb;integratedSecurity=false</url>
              </configuration>
              <dependencies>
                <dependency>
                  <groupId>com.microsoft.sqlserver</groupId>
                  <artifactId>mssql-jdbc</artifactId>
                  <version>7.4.1.jre11</version>
                </dependency>
              </dependencies>
            </plugin>
    
            
            <plugin>
              <artifactId>maven-clean-plugin</artifactId>
              <version>3.1.0</version>
            </plugin>
            
            <plugin>
              <artifactId>maven-resources-plugin</artifactId>
              <version>3.0.2</version>
            </plugin>
            <plugin>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>3.8.0</version>
            </plugin>
            <plugin>
              <artifactId>maven-surefire-plugin</artifactId>
              <version>2.22.1</version>
            </plugin>
            <plugin>
              <artifactId>maven-jar-plugin</artifactId>
              <version>3.0.2</version>
            </plugin>
            <plugin>
              <artifactId>maven-install-plugin</artifactId>
              <version>2.5.2</version>
            </plugin>
            <plugin>
              <artifactId>maven-deploy-plugin</artifactId>
              <version>2.8.2</version>
            </plugin>
            
            <plugin>
              <artifactId>maven-site-plugin</artifactId>
              <version>3.7.1</version>
            </plugin>
            <plugin>
              <artifactId>maven-project-info-reports-plugin</artifactId>
              <version>3.0.0</version>
            </plugin>
          </plugins>
        </pluginManagement>
      </build>
    </project>

**Comment by richardrflores** [comment]
Hi @juliahayward, see my response to @alextercete
<https://github.com/alextercete>.

**Comment by richardrflores** [comment]
@alextercete 

    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    
        <localRepository/>
        <interactiveMode/>
        <usePluginRegistry/>
        <offline/>
        <pluginGroups>
            <pluginGroup>com.oracle.weblogic</pluginGroup>
            <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
        </pluginGroups>
    	<servers>
            <server>
                <id>flyway-repo</id>
                <username>**********</username>
                <password>flyway</password>
            </server>
        </servers>
    	
        <mirrors>
            <mirror>
                <id>nexus</id>
                <mirrorOf>external:*</mirrorOf>
                
                <url>http://jfrog.aws.company.com/artifactory/maven-mirror</url>
            </mirror>
        </mirrors>
    
        <proxies/>
    
    
        <profiles>
            
    
    
            <profile>
                <id>local</id>
                <properties>
                    <weblogic.adminurl>http://localhost:8000</weblogic.adminurl>
                    <weblogic.username>weblogic</weblogic.username>
                    <weblogic.password>weblogic1</weblogic.password>
                    <weblogic.targets>DefaultServer</weblogic.targets>
                </properties>
            </profile>
    
            <profile>
                <id>local3</id>
                <properties>
                    <weblogic.adminurl>http://localhost:8000</weblogic.adminurl>
                    <weblogic.username>weblogic</weblogic.username>
                    <weblogic.password>weblogic1</weblogic.password>
                    <weblogic.targets>AdminServer</weblogic.targets>
                </properties>
            </profile>
    
            <profile>
                <id>local2</id>
                <properties>
                    <weblogic.adminurl>http://someserver:8000/</weblogic.adminurl>
                    <weblogic.username>weblogic</weblogic.username>
                    <weblogic.password>weblogic1</weblogic.password>
                    <weblogic.targets>AdminServer</weblogic.targets>
                </properties>
            </profile>
    
            <profile>
                <id>dev</id>
                <properties>
                    <weblogic.adminurl>wldev.company.com:8005</weblogic.adminurl>
                    <weblogic.username>sgaddom</weblogic.username>
                    <weblogic.password>Welcome01</weblogic.password>
                    <weblogic.targets>wldev_ms1</weblogic.targets>
                </properties>
            </profile>
    
            <profile>
                <id>sonar</id>
                <activation>
                    <activeByDefault>true</activeByDefault>
                </activation>
                <properties>
                    
                    <sonar.host.url>
                        http://localhost:9000
                    </sonar.host.url>
                </properties>
            </profile>
    
        </profiles>
    
    </settings>

**Comment by richardrflores** [comment]
@alextercete 

     <mirrors>
            <mirror>
                <id>nexus</id>
                <mirrorOf>external:*,!flyway-repo</mirrorOf>
                
                <url>http://jfrog.aws.wfscorp.com/artifactory/maven-mirror</url>
            </mirror>
        </mirrors>

Adding `!flyway-repo` to mirroOf works, but I get the following exception: `org.flywaydb.core.api.FlywayException: Missing license key. Ensure flyway.licenseKey is set to a valid Flyway license key ("FL01" followed by 512 hex chars) -> [Help 1]`

Instead, I have to pass the licenseKey as a system property works: `mvn -Dflyway.licenseKey=FL01.... flyway:migrate`. Not sure why it's not reading it from the settings.xml file though. Not sure how much that matters as we will probably be using another configuration option to integrate into our CI/CD pipeline. Thoughts?

**Comment by alextercete** [comment]
@richardrflores I'm glad you got it working -- I didn't know you could exclude `flyway-repo` like that, that's pretty neat!

At the moment, you have to set the license key "twice" if you're using Maven: a) in the `settings.xml`, to download the Pro/Enterprise version of the artifacts; b) in the Flyway config (in your case, through a system property), to enable Pro/Enterprise features in Flyway.

I'll close this issue as I think we've reached a natural conclusion, but feel free to reopen it if you have any outstanding issues.
