### ISSUE TITLE
no console output when using command line 

### ISSUE THREAD

**Issue by romaindup** [flyway/flyway#2641]
###### Which version and edition of Flyway are you using?

version 6.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

AWS Redshift

###### Which operating system are you using?

RedHat 8, openjdk version "1.8.0_242"

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I configured flyway with the minimum parameters: flyway.url, flyway.user and flyway.password.
Flyway can connect to the database as the migration scripts get executed, but none of the commands (migrate, info, status) are outputting anything on the console. The only way to get some information back is with `flyway info -json`. All the other commands only output this:
```
log4j:WARN No appenders could be found for logger (org.flywaydb.core.internal.configuration.ConfigUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info
```
If I pass an invalid parameter (`flyway validate -json`, for example), I get an error message:
```
{
  "error": {
    "errorCode": "ERROR",
    "message": "The -json flag is only supported by the info command."
  }
}
```

###### What did you expect to see?
Details of the commands executed or information on the migration scripts already executed.

###### What did you see instead?
log4j warning message (see above)

**Comment by juliahayward** [comment]
OK, so you're using log4j to do the logging, but we're unable to find your configuration file log4j.xml (or alternatively log4j.properties). If you haven't got such a config file, here's an example which will log to the console:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration>
    <appender name="CA" class="org.apache.log4j.ConsoleAppender">
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="%-p - %m%n"/>
        </layout>
        <filter class="org.apache.log4j.varia.LevelRangeFilter">
            <param name="levelMin" value="INFO"/>
            <param name="levelMax" value="ERROR"/>
        </filter>
    </appender>

    <root>
        <priority value="all"/>
        <appender-ref ref="CA"/>
    </root>
</log4j:configuration>
```

You can put this file in the top level of the flyway installation, or edit flyway's bash script to add `-Dlog4j.configuration=file:///your/path/here/log4j.xml` if you want to have it somewhere else.

**Comment by romaindup** [comment]
Thanks. That fixes the problem. Is that documented anywhere? Seems like a basic requirement

**Comment by juliahayward** [comment]
Excellent, thanks for the confirmation! I'll raise an issue against the website now and we'll get it sorted asap.
