### ISSUE TITLE
Package the oracle drivers

### ISSUE THREAD

**Issue by Lyeeedar** [flyway/flyway#2642]
Package the oracle db drivers into flyway so they do not need to be downloaded and copied in manually by the user.

**Comment by Lyeeedar** [comment]
https://github.com/utPLSQL/utPLSQL-cli/commit/6b38976adf989d3a17cae77debb9f803388b8b5c

**Comment by juliahayward** [comment]
Fixed in 6.2.1

**Comment by MikielAgutu** [comment]
Waiting for Oracle to confirm we can legally do this

**Comment by MikielAgutu** [comment]
Related to https://github.com/flyway/flyway/issues/2513

**Comment by juliahayward** [comment]
The concern about ending up with multiple drivers is not a problem - just tried, and if you have both `odbc8-x.y.z.jar` and `odbc8-a.b.c.jar` (or odbc10-a.b.c.jar for that matter) then the class loader is quite happy, it takes the first one it comes to. In the absence of us trying to be clever, that means taking the jars in alphabetical order.

**Comment by juliahayward** [comment]
Done in 6.2.3

**Comment by davidkarlsen** [comment]
Is this for the docker image, the maven plugin or the cli?
