### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Anna273839** [flyway/flyway#2644]
Hi,
Eagerly waiting for this feature. Also I hope we will get output like
Procedure Created
Package Body Created and so on for PL/SQL DB Objects

_Originally posted by @martinmlouis in https://github.com/flyway/flyway/issues/2559#issuecomment-561668120_

**Comment by MikielAgutu** [comment]
Duplicate/ +1 of https://github.com/flyway/flyway/issues/2559
