### ISSUE TITLE
Snowflake 4.1.1 support

### ISSUE THREAD

**Issue by filiprichtarik** [flyway/flyway#2645]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
Snowflake 4.1.1

###### Which operating system are you using?
Linux

###### What did you do?

Last week Snowflake updated our databases and we are getting warning to upgrade flyway to support latest Snowflake. But there is no newer version to use than 6.2.0,

major version has changed so it triggers following recommendation:
 
   recommendFlywayUpgradeIfNecessaryForMajorVersion("3.50");

**Comment by juliahayward** [comment]
The recommendation is (or at least should be) just a warning; do you see any failure running against Snowflake 4? We will run our tests against the latest Snowflake asap and change the recommendation accordingly.

**Comment by filiprichtarik** [comment]
no issue so far, meanwhile jumped to Snowflake 4.2 and still everything ok (at least our use cases)

**Comment by juliahayward** [comment]
All the tests are green with 4.2 so fine to go ahead and ignore the warning. Flyway 6.2.2 will have the check updated.
