### ISSUE TITLE
Snowflake Key Pair Authentication support

### ISSUE THREAD

**Issue by kulmam92** [flyway/flyway#2661]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 0-SNAPSHOT by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Snowflake 

###### Which operating system are you using?
Mac

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Authenticate using key pair
https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#using-key-pair-authentication

```
flyway.ur=jdbc:snowflake://MYFLAKE.east-us-2.azure.snowflakecomputing.com/?db=DEMO_DB&warehouse=DEMO_WH&role=PUBLIC&schema=FLYWAY&authenticator=snowflake_jwt&private_key_file=/Users/myuser/.ssh/rsa_key.pem
flyway.user=myuser@test.com
```

###### What did you expect to see?
connection success

###### What did you see instead?
```
ERROR:
Unable to obtain connection from database (jdbc:snowflake://MYFLAKE.east-us-2.azure.snowflakecomputing.com/?db=DEMO_DB&warehouse=DEMO_WH&role=PUBLIC&schema=FLYWAY&authenticator=snowflake_jwt&private_key_file=/Users/myuser/.ssh/rsa_key.pem) for user 'myuser@test.com': Private key provided is invalid or not supported: Please use java.security.interfaces.RSAPrivateCrtKey.class
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 42601
Error Code : 200045
Message    : Private key provided is invalid or not supported: Please use java.security.interfaces.RSAPrivateCrtKey.class
```

**Comment by juliahayward** [comment]
Which version of the Snowflake driver are you using? We are testing with 3.11.1 and it appears fine; however, we see the same message as you (`Private key provided is invalid or not supported`) if we don't have an absolute path to the .pem file.

**Comment by kulmam92** [comment]
@juliahayward 
Snowflake JDBC driver version was the issue. After replacing snowflake driver in the flyway drivers folder(/usr/local/Cellar/flyway/6.1.4/libexec/drivers) to the latest version(snowflake-jdbc-3.12.0.jar), it worked.

**Comment by Igor-Kuzenkov** [comment]
Hey @kulmam92,
Sorry for the late message to the closed ticket, anyway, I have a question related to this.
**Q:** Did you use _**encrypted**_ (some _passphrase_ is used to decrypt it) RSA Key pair?
Asking this because I have the same problem with the _encrypted_ key and there is still no closed issue - https://github.com/snowflakedb/snowflake-jdbc/issues/327

Thanks.
