### ISSUE TITLE
Logging frameworks

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2664]
At the moment, we auto-detect some logging frameworks that are present on the Flyway classpath, and if one is found then Flyway uses it; otherwise a sensible fallback option is taken. Specifically, we look for instances of:

- the Android Java runtime
- `org.apache.commons.logging.Log`
- `org.slf4j.Logger`

This has the disadvantage that we can't then pull in packages like the Amazon SDK which has an embedded SLF4J logger (see #1961 and #2458) without potentially disturbing users who are happy with their current logging behaviour. Is this a big issue for you? Would having to configure logging, other than the current fallback option, be a significant imposition?

**Comment by juliahayward** [comment]
The immediate concern is how it affects users using Flyway in Maven and/or Gradle, as it provides a convenient way to delegate to their loggers.

**Comment by JonLally** [comment]
Hi Julia, let me take a look over the weekend and get back to you. I just need to get back up to speed on this.
