### ISSUE TITLE
Trigger Delimiter Problem

### ISSUE THREAD

**Issue by marcobehler** [flyway/flyway#2666]
Hi guys,
I do not know if there is a simple way around it, but I am running into a bug when using MySQL and Flyway. Version doesn't really matter, but I tried it with MySQL5-8 as well as Flyway 6.2.1.

`CREATE TRIGGER before_insert_users BEFORE INSERT ON USERS FOR EACH ROW IF new.api_key IS NULL THEN SET new.api_key = uuid(); END IF;`

The issue is that Flyway parses in the statement but thinks the ";" after uuid() is the end of the statement, hence cutting of the END IF and hence you cannot apply that migration succesfully.

Is there an easy way to change delimiters in these cases or is this a bug?

Thanks
Marco

**Comment by MikielAgutu** [comment]
Looks like this is a bug. There's no way to change the delimiters, it's something we need to fix on our end.

**Comment by MikielAgutu** [comment]
After more investigation we've actually found a workaround using the [MySql `DELIMITER` option](https://flywaydb.org/documentation/database/mysql#sql-script-syntax). Our parser seems to be happy with things like:

```
DELIMITER #
CREATE TRIGGER before_insert_users BEFORE INSERT ON USERS FOR EACH ROW IF new.api_key IS NULL THEN SET new.api_key = uuid(); END IF#
DELIMITER ;
```

Nonetheless we should still fix it.

**Comment by peterhalicky** [comment]
@Lyeeedar this is still broken on MariaDB
