### ISSUE TITLE
Would it be possible to use flyway to compare two database schemas and upgrade one's schema to match the other?

### ISSUE THREAD

**Issue by AdityaAnand1** [flyway/flyway#2667]
I'm using a pretty niche ORM, Kotlin based Exposed library.

https://github.com/JetBrains/Exposed

To my knowledge, there exists no official way to do database migrations using this library, or the Kotlin backend stack.

Clearly, to put this stack into production (ktor + exposed), we need to figure out a way to do migrations.

So back to raw SQL. Here's an idea I have:

1. There's the prod server with old schema
2. There's the dev server with new schema

I want to say

> Hey prod server, get ready to update. I want prod DB schema to look exactly like dev DB schema. Do some auto-magic migration script generation and make it so.

Would it be possible to extend flyway to become something like this?

Or can you recommend any other directions that you think I should explore to accomplish this?

**Comment by MikielAgutu** [comment]
We've had [another issue asking about JetBrains' Exposed](https://github.com/flyway/flyway/issues/2616). We don't support it, and aren't aware of any third party integrations either.

As for your idea, Flyway would certainly enable the workflow you described. You can run the baseline command on your production DB to get it ready for Flyway migrations. However the main limitation is that [Flyway doesn't automagically generate migrations](https://github.com/flyway/flyway/issues/648).

Migration generation is something you'd have to solve yourself. There are numerous comparison engines available for different databases ([SQL Compare](https://www.red-gate.com/products/sql-development/sql-compare/), [PostgresCompare](https://www.postgrescompare.com/), etc). These can generate a SQL script representing the diff of dev to production. You can use that diff script as a Flyway migration.

So the deployment workflow would be:
- Compare dev and production using the comparison engine
- Save the diff script as a Flyway migration
- Run `flyway migrate` on production

This can probably be achieved with a script (PowerShell, Bash, etc) that calls into the various APIs. If you want something built in, Flyway is open source, so you can fork the repo and build this yourself.

**Comment by MikielAgutu** [comment]
SQL generation is beyond the scope of Flyway.

**Comment by jamesdh** [comment]
@Aditya94A This might sound crazy, but I'm pretty certain IntelliJ's JPA Explorer (formerly JPA Buddy) uses liquibase under the covers to do exactly this. So while the tool allows you to generate a Flyway migration based on the diff between two databases, the actual SQL generation for the migration is done via liquibase tooling under the covers.

**Comment by LvargaDS** [comment]
I am not sure, but according [this article](https://www.red-gate.com/hub/product-learning/flyway/creating-flyway-migration-files-using-redgate-schema-comparison-tools), and according features described in paid version (enterprise and also teams) of flyway, comparison and migration generation is possible.
Through, free version of flyway does not know how o generate migration.

PS: There is bytebase project which claims to do migration for you. There are also other projects which does that (visual studio for example). Beware of difference between various products. Sometimes renaming column (or changing its type) can be done in various approaches and some of them is not feasible on tables with many data. Some generators are so clever, that they are able to do "magic" migrations using tricks for safety/performance.
