### ISSUE TITLE
I would like to have DEBUG levels to hide files' listing

### ISSUE THREAD

**Issue by jakubek2085** [flyway/flyway#2668]
###### Which version and edition of Flyway are you using?

6.0.6

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?

I would like to see DEBUG mode, but hide the files' listing. I raised a question for this here:
https://stackoverflow.com/questions/60006223/flyway-are-there-debug-levels

**Comment by Lyeeedar** [comment]
Related to https://github.com/flyway/flyway/issues/2587

**Comment by juliahayward** [comment]
The problem with implementing this is that we're constrained by the need for compatibility with standard logging interfaces such as SLF4J and Apache COmmons Logging; these only offer a fixed set of log levels. So no, we can't easily add in more granularity. 

As you mention the -X option I assume you're using the command line. If so, then you can pipe the output through a filter to remove everything you don't want to see. For example, to hide any line with the word "resource" in:

**Linux / macOS** 

`flyway migrate -X | grep -v 'resource'`

**Powershell**

`./flyway migrate -Z | sls -Pattern "resource" -NotMatch

**Windows CMD**

`flyway migrate -X | findstr /v /c:"resource"`
