### ISSUE TITLE
baselineOnMigrate seems to be ignored when calling migrate when used on an empty database

### ISSUE THREAD

**Issue by cjheppell** [flyway/flyway#2671]
###### Which version and edition of Flyway are you using?

Flyway Community 6.2.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

This is the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line in Docker

###### Which database are you using (type & version)?
PostgreSQL 10

###### Which operating system are you using?
MacOS
(But also repro's in Docker)

###### What did you do?

Create a docker PostgreSQL container which already has an empty database called "foo".

Within my Flyway scripts, V1.0 includes `CREATE DATABASE foo`.

I want to migrate my `foo` database, but ignore the first script so I use `-baselineOnMigrate=true -baselineVersion=1.0`, but Flyway still tries to run the first script and the baseline operation is never completed.

Reproduction:

```bash
mkdir -p baselineOnMigrateRepro/sql
cd baselineOnMigrateRepro

echo "CREATE DATABASE foo" > create-db.sql

pushd sql
echo "CREATE DATABASE foo" > V1_0__create-database.sql
echo "CREATE TABLE mytable (id int);" > V1_1__create-table.sql
popd

docker run --name flywaypg -e POSTGRES_PASSWORD=MySecretPassword -v $PWD/create-db.sql:/docker-entrypoint-initdb.d/1-create-db.sql -p 5432:5432 -d postgres:10-alpine
```

Wait for the PostgreSQL docker container to be accepting connections... Then run:

```bash
flyway migrate -url=jdbc:postgresql://localhost:5432/foo -user=postgres -password=MySecretPassword -baselineVersion=1 -baselineOnMigrate=true -locations=filesystem:./sql

### The following error is printed:

Flyway Community Edition 6.2.2 by Redgate
Database: jdbc:postgresql://localhost:5432/foo (PostgreSQL 10.11)
Successfully validated 2 migrations (execution time 00:00.035s)
Creating Schema History table "public"."flyway_schema_history" ...
Current version of schema "public": << Empty Schema >>
Migrating schema "public" to version 1.0 - create-database [non-transactional]
ERROR: Migration of schema "public" to version 1.0 - create-database [non-transactional] failed! Please restore backups and roll back database and code!
ERROR: 
Migration V1_0__create-database.sql failed
------------------------------------------
SQL State  : 42P04
Error Code : 0
Message    : ERROR: database "foo" already exists
Location   : ./sql/V1_0__create-database.sql (/Users/chris.heppell/go/src/github.com/red-gate/foundry-labs/server.estate/baselineOnMigrateRepro/./sql/V1_0__create-database.sql)
Line       : 1
Statement  : CREATE DATABASE foo
```

###### What did you expect to see?

The first migration script ignored, and all subsequent migrations run successfully.

###### What did you see instead?

An error when migrating

###### Additional info

Admittedly, we probably shouldn’t include the CREATE DATABASE statement in our flyway scripts anyway, since AFAIK there’s no way to say “After you created that database, run all the subsequent scripts on it” (and it seems like that's a bad idea anyway!)

**Comment by MikielAgutu** [comment]
[From the docs](https://flywaydb.org/documentation/configfiles):

> Whether to automatically call baseline when migrate is executed against a non-empty schema with no schema history

This is expected. It only works if your schema is non-empty.

You can however just run the `baseline` command to ignore your initial migration. I admit this is not intuitive.

Flyway works on the assumption that your DB already exists. [From Axel himself](https://stackoverflow.com/a/22973660/5437021):

> And remember, you have to create the database first using the tool of your choice. You can do this with this SQL statement: CREATE DATABASE test;. Flyway handles only the schema creation, not database creation.

This is possibly a case for a [new `skip` command](https://github.com/flyway/flyway/issues/1986).

I'll keep this open for reference as it demonstrates a lack of clarity in Flyway's initial set up experience.
