### ISSUE TITLE
unsupported SQL*Plus statement: SPOOL

### ISSUE THREAD

**Issue by emarcellus** [flyway/flyway#2674]
###### Which version and edition of Flyway are you using?
 /opt/flyway/flyway -v -pro
Flyway Pro Edition 6.2.1 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
6.2.1 is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle 12.2

###### Which operating system are you using?
Red Hat Enterprise Linux 6
Linux 2.6.32-754.25.1.el6.x86_64 #1 SMP Wed Nov 20 15:07:26 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway -pro -outputFile=outfile.txt -configFiles=file.conf info

The issues happens with info, migrate & baseline. I suspect others as well but these are the 3 command options I am using currently.

###### What did you expect to see?
No warnings for unsupported SQL*Plus statements

###### What did you see instead?
WARNING: Detected unsupported SQL*Plus statement: SPOOL OFF
-> Please file an issue requesting support at https://github.com/flyway/flyway/issues
WARNING: Detected unsupported SQL*Plus statement: SPOOL /spoolfile.log
-> Please file an issue requesting support at https://github.com/flyway/flyway/issues

**Comment by MikielAgutu** [comment]
To clarify, we don't necessarily claim to support all SQL*Plus commands. [See the docs](https://flywaydb.org/documentation/database/oracle#sqlplus-commands):

> All other SQL*Plus commands are gracefully ignored with a warning message.

Of course we'll consider adding support for more commands in future releases.

**Comment by juliahayward** [comment]
I have a fix, hopefully going in 6.2.4
