### ISSUE TITLE
Snowflake jdbc requires password mandatorily despite opting for Auth-key mechanism

### ISSUE THREAD

**Issue by srjonemed** [flyway/flyway#2677]
###### Which version and edition of Flyway are you using?
flyway 6.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Snowflake

###### Which operating system are you using?
MacOs, Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
attempting to make connection using Auth-key connection mechanism of snowflake, like so:
flyway.url=jdbc:snowflake://<myaccount>.snowflakecomputing.com/?private_key_file=<abs_path_to>/.ssh/rsa_key_fdb_user.pem&db=mydb&warehouse=etl_dev_wh&role=etl_dev_role&user=etl_dev_user

###### What did you expect to see?
I was hoping that the user's Auth would get done based on the private key provided in the uri

###### What did you see instead?
being prompted for password.. 
more info - 
https://stackoverflow.com/questions/60232554/does-flyway-support-auth-key-based-credentials-for-snowflake

**Comment by juliahayward** [comment]
Will be fixed for 6.2.4
