### ISSUE TITLE
Parameters in JDBC URL

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2678]
Arising from #2677 - it is possible to put `user` in the JDBC URL in which case the command line should not prompt for it. The fix for #2677 was Snowflake-specific, but it is worth a wider consideration that parameters may be passed in the JDBC URL (rather than the various config methods) and we can parse them out.

**Comment by MikielAgutu** [comment]
See https://flywaydb.org/documentation/commandline/#credentials.

Also https://github.com/flyway/flyway/issues/2132

**Comment by juliahayward** [comment]
This is going to be a case-by-case exercise as Oracle does it differently - see https://community.oracle.com/thread/221883

I'll have a look at genericising the code in the command line to make it easy to add new cases.

**Comment by MikielAgutu** [comment]
We can do this for Azure auth too (MSI, Integrated, etc)

**Comment by juliahayward** [comment]
https://github.com/flyway/flyway-master/pull/230 moves the logic to the core, adds the Oracle credentials-in-URL case, and adds unit tests. It's too much of a case-by-case problem to have a truly generic solution.
