### ISSUE TITLE
Create stored procedure for MySql and MariaDB fails for macOS

### ISSUE THREAD

**Issue by andrew-shamin** [flyway/flyway#2680]
Please, fix it in macOS CLT
https://flywaydb.org/download/thankyou?dl=https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.2.3/flyway-commandline-6.2.3-macosx-x64.tar.gz

_Originally posted by @axelfontaine in https://github.com/flyway/flyway/issues/2338#issuecomment-481185568_

**Comment by juliahayward** [comment]
Hi - I'm unable to reproduce with Flyway 6.2.3 and the script provided in the original case #2338 . I'm using MySQL 8.0, JRE 13.0 and macOS Mojave 10.14.6. Could you provide your problematic script (redacted as necessary)?

**Comment by MikielAgutu** [comment]
Closing for lack of response
