### ISSUE TITLE
multi location or path for migration

### ISSUE THREAD

**Issue by MENGKONGSEAN** [flyway/flyway#2683]
###### Which version and edition of Flyway are you using?
6.2.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
No error it just question

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
`mysql` and `postgresql`

###### Which operating system are you using?
Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
No error but I just want to use deference location for migration.

Example: 
I have two deference local for migation `./src/a` and `./src/b`
First I would like to migration on `./src/a` after finish continue migration on `./src/b`

###### What did you expect to see?
How to migration deference localtion
`./src/a` and `./src/b` 

###### What did you see instead?
NO error

**Comment by Lyeeedar** [comment]
Do you mean for it work work as requested in https://github.com/flyway/flyway/issues/2541? If not, would you mind explaining a bit more about what behaviour you would like?

**Comment by MikielAgutu** [comment]
General problem captured here https://github.com/flyway/flyway/issues/2698
