### ISSUE TITLE
Redshift: clean schema fails if there is a procedure present

### ISSUE THREAD

**Issue by jaiseban** [flyway/flyway#2684]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 6.2.4 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

AWS Redshift

###### Which operating system are you using?

Executes through flyway/flyway docker image

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Our migration script includes a stored procedure. During DB migration, we don't face any issues and procedure gets created. But during flyway clean command execution, we get below error

> Message    : [Amazon](500310) Invalid operation: function <schema>.<procedure name>(character varying, character varying) does not exist

After looking into the flyway code, observed that the clean action does not differentiate the "procedure" and "function". ie org.flywaydb.core.internal.database.redshift.RedshiftSchema->generateDropStatementsForRoutines() does not differentiate procedure. The procedure also treated like function and execute with command "drop function" instead of "drop procedure".

Instead, we should use PG_PROC_INFO-> prokind to differentiate procedure and function to generate a respective drop statement.

###### What did you expect to see?

The clean command should handle the procedure clean

###### What did you see instead?

The clean command fails with below error in Redshift DB  if the stored procedure exists
[Amazon](500310) Invalid operation: function <schema>.<procedure name>(character varying, character varying) does not exist

**Comment by jaiseban** [comment]
Note that this issue happens only if schemaHistory.hasSchemasMarker() return false

**Comment by juliahayward** [comment]
I have a reproduction, fix will be in 6.3
