### ISSUE TITLE
Improve support for injecting entire scripts

### ISSUE THREAD

**Issue by jaa2261** [flyway/flyway#2685]
###### Which version and edition of Flyway are you using?

6.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle

###### Which database are you using (type & version)?

Oracle 19c

###### Which operating system are you using?

RHEL 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We are in the process retro fitting flyway to an existing Oracle 11 database to help us migrate to 19c. The DDL to generate the database has been held in git for many years and has ~100 schemas, thousands of tables, and thousands of procs, packages, functions and triggers. The DDL scripts are generated via export DDL feature in TOAD which generates individual sql files that are in separate directories for each object type grouped by schema.

We use gradle to build test instances for CI purposes from scratch for each build. Most of the schemas are independent of each other so gradle's parallel build helps us keep the build time to a few minutes which is fine given that the tests take hours to run (this is a major enterprise system).

We use placeholders extensively so we don't need to change the existing source DDL files or structure. So for each object type we use something like this:

flyway {
    placeholders = [
            'procedures_DDL' : fileTree(dir: "${projectDir}").include('**/Procedures/*.prc').collect { it.getText() }.join(System.getProperty("line.separator"))
    ]
}

which means that rather than having a repeatable migration file for each procedure we just have a single file for each type e.g. R__procedures.sql just contains:

${procedures_DDL}

For the databases that we create from scratch this works fine but for the baselined DEV,QA, PRE-PROD and PROD instances procedures changed after the first migration aren't being applied.

###### What did you expect to see?

We expected that the checksum for the file would be calculated after the placeholder had been replaced and thus the repeatable migration would be re-run if an underlying DDL file has changed

###### What did you see instead?

Due to issue #2177 this isn't happening

**Comment by jaa2261** [comment]
One of the comments on #2177 mentioned that there may be a performance hit if the checksums are calculated post the placeholder replacement. Given the scale of the migration we are doing I doubt it will be significant. To back up that assertion I'll alter our gradle scripts so that gradle does the inserts the concatenated files into the repeatable migration files before flyway runs, i.e. do the placeholder replacement for flyway. I assume this means the checksums should change if an underlying DDL file is changed. I'll report back with the results

**Comment by MikielAgutu** [comment]
Thanks for providing more detail for https://github.com/flyway/flyway/issues/2177#issuecomment-589271352.

It still looks like this will be solved in the Flyway 6.3 release, when we will implement post-placeholder checksum calculation. (We think the performance will be largely equivalent)

As I understand, you've introduced a mechanism to convert your existing source control structure into something Flyway understands.

I have a couple of questions:
- Do you plan to keep the existing structure (one produced by TOAD export DDL) for the forseeable future?
- Have you encountered any limitations by using placeholders in this way (except the checksum calculation)?
- How does this system work with versioned scripts?

Essentially, I'd like see if we should do anything to improve Flyway's support for this sort of workflow, or if it's good enough as is.

**Comment by jaa2261** [comment]
That's good to hear :-) When is the 6.3 release scheduled for?

We've use the TOAD structure (a directory per schema, sub-directories for each object type, and then individual files for each object) for many years to store the DDL I source control. We've used hand crafted CI scripts up to now to build test DBs. I can't see us moving to a different structure as it makes it easy to navigate.

Once the checksum issue is fixed everything seems to be fine. The combination of placeholders and gradle has given us enough control to allow us to build the database from scratch and to maintain existing databases one they've been baselined. The creation scripts are pretty much all using place holders which has allowed us to template the process and it ensures the objects are created in the correct order.

Running in parallel building 2 databases with ~40 schemas and thousands of objects from scratch takes around 12 minutes and running subsequent migrations (or checking there are no changes) takes ~ 1 minute.

The versioned scripts work fine. I'll zip up a sample set of scripts so you can see what we've done. They should be fairly generic at least for Oracle DBs.

**Comment by MikielAgutu** [comment]
6.3 should be coming in the next week or so.

**Comment by jaa2261** [comment]
[flyway.zip](https://github.com/flyway/flyway/files/4245991/flyway.zip) is a sample of how we've done it

**Comment by MikielAgutu** [comment]
Thanks for providing this. As I said, https://github.com/flyway/flyway/issues/2177 should fix your problem when 6.3 is released. I'll rename this issue to capture the wider feature of 'script injection' which others might be interested in.
