### ISSUE TITLE
Can FlyWay support the flyway_histroy_table created in different database

### ISSUE THREAD

**Issue by lxwhappy** [flyway/flyway#2686]
I am using the flyway command tools.I  know By default the flyway create the flyway_history_table in the business database, the flyway only can config one jdbc datasource .But I want the flyway_history_table exist in other database,i dont want ther developer to see and modify the history_table, dose flyway support this or give me some suggest.
I hope for your answer,Thanks!

**Comment by MikielAgutu** [comment]
Flyway doesn't support schema history tables external to the deployment database. The closest you can get is to use the [`schemas` and `table` option](https://flywaydb.org/documentation/commandline/migrate#table) to put the schema history table in its own schema:

> When the `flyway.schemas` property is set (multi-schema mode), the schema history table is placed in the first schema of the list.

I should also clarify something - some database engines have no concept of 'schemas', only 'databases' ([like MySQL](https://stackoverflow.com/a/11618350/5437021)). In that case the `schemas` property maps to individual databases. In this way Flyway tries to make the concept of a schema generic across multiple database engines.

Anyway, as for this use case, it isn't supported. You say you don't want other developers to see or modify the schema history. Probably the only way is to put the schema history table into a schema that these developers don't have write permissions for.

@lxwhappy Does that help? I'll also mark this as a feature request.

**Comment by MikielAgutu** [comment]
After more thought, we don't think this is the right thing for Flyway.
