### ISSUE TITLE
Azure Active Directory with MFA support

### ISSUE THREAD

**Issue by MikielAgutu** [flyway/flyway#2688]
Turns out Flyway doesn't support Azure Active Directory with MFA (Multi Factor Authentication), as it is [not supported by the Microsoft JDBC drivers](https://github.com/microsoft/mssql-jdbc/issues/1053).

A crazy workaround is suggested which involves sort of partially re-implementing AD MFA https://github.com/microsoft/mssql-jdbc/issues/1053#issuecomment-490594780. However we should probably wait for built-in support.

Edit: Now support is improved in the JDBC driver - perhaps we should investigate it again.

**Comment by MikielAgutu** [comment]
Related to https://github.com/flyway/flyway/issues/2072

**Comment by lotsahelp** [comment]
It appears official [support for MFA](https://github.com/microsoft/mssql-jdbc/pull/1464) has been added.

**Comment by DoodleBobBuffPants** [comment]
Closing until there is (more) interest or a known incompatibility
