### ISSUE TITLE
Question about support time

### ISSUE THREAD

**Issue by vadim-hleif** [flyway/flyway#2690]
Hi,

In docs i see that this tool will support database version for 5 or 10 years after database GA release date. [link](https://flywaydb.org/download/faq#how-long-are-database-releases-supported-in-each-edition-of-flyway)

 Is it depend on flyway version? E.g. i have the old postgresql database X.X and static version of flyway Y.Y. After 5 years (Community Edition) it wouldn't be work even i wouldn't do update of flyway?

If it's true, could you explain why?

**Comment by MikielAgutu** [comment]
Flyway versions won't suddenly break for certain DBs after a given period of time. As in, there's no 'time bomb' aspect to our DB support.

Support for old DBs is only removed between versions. e.g:

- Flyway 6 supports DB X
- Flyway 7 drops support for DB X
- Nonetheless, Flyway 6 will continue to support DB X

Does that answer the question?

**Comment by vadim-hleif** [comment]
Yes, thank you so much !
