### ISSUE TITLE
Using '/' as delimiter on a new line

### ISSUE THREAD

**Issue by JFNGO** [flyway/flyway#2701]
###### Which version and edition of Flyway are you using?
6.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle DB

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I tried to make some migrations using the '/' on a line alone as delimiter.
For example, just a "CREATE TABLE" statement, that works on Oracle SQL Developer but not using flyway command line

###### What did you expect to see?
I expected that the migration would be successful and the table would be created

###### What did you see instead?
The migration failed with an error "ORA-00922: missing or invalid option"

**Comment by Lyeeedar** [comment]
Could you please provide an example script that flyway fails to execute?

**Comment by JFNGO** [comment]
`UPDATE company SET name = 'COOL' WHERE record# = 1234567
/`

**Comment by Lyeeedar** [comment]
I made a script containing only that line and it parsed fine. Is there maybe other stuff in the file that could be causing the actual failure?

**Comment by JFNGO** [comment]
That is weird, there is nothing else. I tried with an other statement:
![image](https://user-images.githubusercontent.com/56840868/75906767-0b3e5e80-5dfc-11ea-82e6-95335387c087.png)
It didn't work as well.

**Comment by Lyeeedar** [comment]
So on investigation the sql as written is invalid, as it has to end with a semicolon to be 'properly ended'. Im guessing that sql developer is adding the semicolons onto the end of statements without one before it executes the sql.

**Comment by JFNGO** [comment]
I am not sure about Oracle SQL Developer adding semicolons.
According to Oracle documentation:
![image](https://user-images.githubusercontent.com/56840868/76577311-222b2380-6482-11ea-90dc-eeed6e295c77.png)

Link of the documentation: 
https://docs.oracle.com/cd/E11882_01/server.112/e16604/ch_four.htm#SQPUG014

I also tried the following statement on Oracle SQL Developer:
`SELECT record# from company
/`
According to the SQL history:
![image](https://user-images.githubusercontent.com/56840868/76577508-df1d8000-6482-11ea-8daa-7f3dad8e7083.png)
It has been executed without adding a semicolon.

**Comment by intacctvaler** [comment]
Here is another example. This script works fine in sqlplus and SQL developer against my Oracle 18c database. But it fails in flyway.

create table temp_migr(c1 number)
/
insert into temp_migr values(1)
/
insert into temp_migr values(2);
insert into temp_migr values(3);
commit;
drop table temp_migr
/

The flyway migrate output is:

Flyway Community Edition 6.0.7 by Redgate
Database: jdbc:oracle:thin:@//dev08.intacct.com:1521/dbacct (Oracle 18.0)
Successfully validated 3 migrations (execution time 00:00.179s)
Current version of schema "MIGR_OWNER_01": 0.2
WARNING: outOfOrder mode is active. Migration of schema "MIGR_OWNER_01" may not be reproducible.
Migrating schema "MIGR_OWNER_01" to version 0.3 - delimiter test
ERROR: Migration of schema "MIGR_OWNER_01" to version 0.3 - delimiter test failed! Please restore backups and roll back database and code!
ERROR: 
Migration V0.3__delimiter_test.sql failed
-----------------------------------------
SQL State  : 42000
Error Code : 922
Message    : ORA-00922: missing or invalid option
Location   : ./V0.3__delimiter_test.sql (/u02/home/vcrisan/projects/db/app/migr_simple/./V0.3__delimiter_test.sql)
Line       : 1
Statement  : create table temp_migr(c1 number)
/
insert into temp_migr values(1)
/
insert into temp_migr values(2)
