### ISSUE TITLE
Alter table add new column in MYSQL

### ISSUE THREAD

**Issue by MENGKONGSEAN** [flyway/flyway#2704]
###### Which version and edition of Flyway are you using?
flyway java 

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

flyway java 4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Mysql

###### Which operating system are you using?
Ubuntu 18.4

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I have one scrip for alter table add new column but it error duplication column already exist

###### What did you expect to see?
I just expect it alter table and add new column.

###### What did you see instead?
I error because it run two time first time create already and second time to try to add new one creat so it will error duplicate column.

**Noted**
 - Error my production because I use cluster [many node] so I think it have many application try to migration as parallel so i think because of it.

Thank you advance .

**Comment by MENGKONGSEAN** [comment]
How to disable multi migration in `java-api`

**Comment by MENGKONGSEAN** [comment]
@Lyeeedar 
Sorry could you help me please ?

**Comment by Lyeeedar** [comment]
Could you please try this with flyway 6.2.4 to see if its still an issue?

**Comment by MENGKONGSEAN** [comment]
HI @Lyeeedar  I can't upgrade to 6.2.4 because my currently version is 2.2.0 so I need update to version 4.2.0 first.
Do you have any solution ?

**Comment by MENGKONGSEAN** [comment]
HI @axelfontaine do you any idea ??? 
Thank you.

**Comment by MENGKONGSEAN** [comment]
I would like to disable this feature because it have some problem.
>Can multiple nodes migrate in parallel?
Yes! Flyway uses the locking technology of your database to coordinate multiple nodes. This ensures that even if even multiple instances of your application attempt to migrate the database at the same time, it still works. Cluster configurations are fully supported.

**Comment by MENGKONGSEAN** [comment]
this issue not relate to flyway migration or cluster because of development environment and real product not the same.
