### ISSUE TITLE
Flyway issue with Oracle 12.2.0.1 Charset (AL32UTF8)

### ISSUE THREAD

**Issue by chinababu** [flyway/flyway#2708]
Charset issue when using Flyway Java API 6.2.4 (flyway-core:6.2.4) with Oracle database 12.2.0.1 with Charset "AL32UTF8" on RHEL 7.5. There is no problem when script is executed with sqlcmd.

I also tried https://github.com/flyway/flyway/issues/2139 (with orai18n.jar) and no luck.

Any suggestions please?

**Comment by juliahayward** [comment]
Are you able to provide a copy of the script which caused you problems?

**Comment by chinababu** [comment]
Here is the sample update query that I was having issue with. Obviously following query is meaningless as I removed most part of it to isolate the issue.

We are getting the issue at "Sign":"ʻ". that single quote in double quotes ("ʻ") is not actually single quote, but the driver is treating it as single quote and ending the value so getting the following error.

Sample Query:
update <table> set value=value||
'some text","unicode":["U+002E"], "Sign":"ʻ", "ResultingSign":"."}}]'

Error:
SQL State  : 42000
Error Code : 933
Message    : ORA-00933: SQL command not properly ended

Thanks,
Chinna

**Comment by juliahayward** [comment]
OK, so I suspect the charset isn't the problem, it's that a single-quote is being interpreted as the end of a string literal when in fact it's escaped and in the middle of a JSON object?

**Comment by juliahayward** [comment]
Actually after I said that it occurred to me: is that single-quote an 0x27 or something else? (https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html)

**Comment by chinababu** [comment]
Thanks Julia for the information. Unfortunately I cannot share the script as it's licensed.
But, as I mentioned earlier, the character that looks like single quote is not really a single quote. I am copying below couple of such characters that are causing same issue. I am not sure how this editor interpret it.

"ˊ"  ,  "˚"

Our script contains roughly 100 or more such special characters and I isolated the issue by running script by changing these above characters to other well known one like (":" and ","). So because of these observation I thought this is issue with charset support.
Can I request you to try your script by coping exactly the above two characters?
Please let me know if you need more details.

**Comment by juliahayward** [comment]
Aha - so the first is U+02CA : MODIFIER LETTER ACUTE ACCENT and the second U+02DA : RING ABOVE - I'll try those and see. Thankyou!

**Comment by juliahayward** [comment]
OK, I'm puzzled - the script succeeds if I use a 0x02CA in the string rather than a single quote 0x27. Is it possible that a single-quote has slipped through somewhere? Do you set `flyway.encoding` in your configuration?

**Comment by chinababu** [comment]
Not really, we are using the default value ie. "UTF-8". 
When we attempted to use "AL32UTF8" for encoding, we got following error.
[We used java api for everything.]

2020-03-06/13:01:23.003   [main] ERROR c.f.f.<OurClass>: Flyway Migration Failed in Migrate.   
<location of the file>
java.nio.charset.UnsupportedCharsetException:   AL32UTF8           at java.nio.charset.Charset.forName(Charset.java:531)           at   org.flywaydb.core.api.configuration.ClassicConfiguration.setEncodingAsString(ClassicConfiguration.java:1039)           at   org.flywaydb.core.api.configuration.FluentConfiguration.encoding
<removed>
 java.nio.charset.UnsupportedCharsetException:   AL32UTF8           at   java.nio.charset.Charset.forName(Charset.java:531)           at   org.flywaydb.core.api.configuration.ClassicConfiguration.setEncodingAsString(ClassicConfiguration.java:1039)           at   org.flywaydb.core.api.configuration.FluentConfiguration.encoding
<removed>
--

Also please note the version of driver:
compile group: 'com.oracle.ojdbc', name: 'ojdbc8', version: '19.3.0.0'
compile group: 'com.oracle.ojdbc', name: 'orai18n', version: '19.3.0.0'

**Comment by chinababu** [comment]
Actually it is not U+02CA : MODIFIER LETTER ACUTE ACCENT.

I reproduced issue with your script. I added both character and Unicode below.

-- A row to manipulate
INSERT INTO putjsoninme VALUES (1, '');

-- will error, not correctly escaped 
UPDATE putjsoninme SET contents=contents ||
'"Data":{"Denotation":"MODIFIER LETTER PRIME", "Sign":"ʹ","Unicode":"U+02B9"}';

Any thoughts?

**Comment by juliahayward** [comment]
I've attached the file that I was using that seems OK - with both 18.3 and 19.3 Oracle driver (against an Oracle 18.3 database). This was copied and pasted form the above - I'm not sure whether my script differs subtly from yours, or there's something in the environment?

[V1__2708.txt](https://github.com/flyway/flyway/files/4324427/V1__2708.txt)

**Comment by chinababu** [comment]
Did you use encoding in java file? If so, what is it?

**Comment by chinababu** [comment]
Sorry It was prehit and could not edit my post.
Did you use encoding in java file? If so, what is it? 
What environment are you testing? 
I had this issue even with flyway-core:6.3.0 community edition. Does community edition matter here?

**Comment by juliahayward** [comment]
It should be UTF-8. I was testing on macOS Mojave (10.14.6) against an Oracle 18.3 instance in Docker. I'll try on Windows as well.

Are you able to attach your script that reproduces the bug as a text file to this issue, just in case the Github UI is doing something strange to the text?

**Comment by chinababu** [comment]
I could not attach file here as attachment button is not responding for me. I sent you an email with file attached.
This may also be issue with environment, by any chance is flyway tested on environment similar to mine?

**Comment by juliahayward** [comment]
We can't reproduce this.
