### ISSUE TITLE
flyway.url must be set when running command but already set in flyway.conf

### ISSUE THREAD

**Issue by nickeeromo** [flyway/flyway#2709]
First of all there are other similar issues that were closed, but wanted to post this here bc I have a solution.

###### Which version and edition of Flyway are you using?

flyway-commandline-6.3.0-macosx-x64

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command-line

###### Which database are you using (type & version)?

MS SQL Server (though not relevant in this case)

###### Which operating system are you using?

MacOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

opened conf/flyway.conf
There are a LOT of notes that I don't care to look over, so added conf entries at the very top just to get started.

Put in the following entries at the top:
flyway.url=jdbc:sqlserver://WCNCMAADBD01:54433
flyway.user=MAA_CUM_SQD
flyway.password=password

tried the command:
flyway info

just to see if connection working.

###### What did you expect to see?

Anything besides a message saying a property I set was not set :)

###### What did you see instead?

WARNING: Discarding INCOMPLETE dataSource configuration! flyway.url must be set.
Flyway Community Edition 6.3.0 by Redgate
ERROR: Unable to connect to the database. Configure the url, user and password!

###### Solution

So I'm about 99% sure it was due to this line:

https://github.com/flyway/flyway/blob/master/flyway-commandline/src/main/assembly/flyway.conf

line 43:
flyway.url=

The ONLY line that is not commented-out in the whole document.

I cut all the original contents from flyway.conf out and pasted them somewhere else for safe-keeping, leaving my settings in, ran the command again and it worked fine. After inspecting the different supported url formats, saw that uncommented line at the end of that section.

Thank you!

**Comment by nickeeromo** [comment]
Forked and submitted a PR.

**Comment by nickeeromo** [comment]
#2710 
#2211

**Comment by MikielAgutu** [comment]
Thanks for the contribution
