### ISSUE TITLE
Multiple ALTER SESSIONs in dry run

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2712]
![image](https://user-images.githubusercontent.com/454881/76201773-b3cd3380-61eb-11ea-9519-02d8f1a5d389.png)

The above dry run script contains a number of ALTER SESSIONs, two of which are redundant. In particular, it's not at all clear why the first of these is generated at all as there's no comment explaining it.

**Comment by juliahayward** [comment]
t's not as obvious as it seems - it's being done prior to handling each callback event (so there's a beforeValidate, beforeMigrate, beforeEachMigrate) and they are inserted into the dry run prior to determining that the relevant event is a no-op. We are being as cautious as possible. It doesn't cause any bugs in the script, it just looks over-verbose.

**Comment by MikielAgutu** [comment]
This doesn't seem worth fixing.
