### ISSUE TITLE
Gradle plugin: Flyway dependencies

### ISSUE THREAD

**Issue by VedavyasBhat** [flyway/flyway#2714]
This is a suggestion for the gradle plugin

It would be nice to generate/maintain the flyway dependencies, i.e., the dependencies a project's flyway task has on another project's flyway task. (By dependency. I mean the tables can have a dependency)

I find that I often have a complex gradle subproject hierarchy with flyway migrations in each. For instance,
```
A
- B
  - C
  - D
- E
```

and let's say `D` and `E` depend on project `C`'s `flywayMigrate`. When I run `flywayMigrate` on the base project, it runs it for all subprojects with the plugin enabled, but when I run it from within one project (let's say `E`), it does not run it for its "dependencies". 

The current solution I have is to manually add `dependsOn` on the flywayMigrate task to related subproject flywayMigrate tasks. I'd rather define it in the plugin configuration itself instead of adding a dependency per subtask (flywayMigrate, flywayClean, etc.).

In addition, a good to have would be if the dependencies were not just created in gradle configurations but maintained in generated source files. Because I also run flyway clean/migrate tasks from my junit tests, so if I could build a config from the dependencies and then supply it to `Flyway`, that would make things a lot easier.

Any thoughts/feedback?

Also, would this repo be the right place to contribute this feature? I am currently working on a gradle plugin to do the same, but it would of course be nice coming from the official plugin itself.

**Comment by MikielAgutu** [comment]
>  would this repo be the right place to contribute this feature

Feel free to submit a PR :)

**Comment by DoodleBobBuffPants** [comment]
Any news on the PR?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
