### ISSUE TITLE
Flyway shouldn't suppress comments after "prompt" with Oracle (SQLPlus)

### ISSUE THREAD

**Issue by rafael-trevisan** [flyway/flyway#2716]
###### Which version and edition of Flyway are you using?
6.2.0 but the same issue is reproducible in newer versions

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
If the SQL migration contains something like `prompt --application/set_environment` Flyway will show nothing while in SQLPlus is shown "--application/set_environment"

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
Oracle 18

###### Which operating system are you using?
MacOS

###### What did you do?
Oracle APEX source files contain lots of `prompt --<some message>` that are useful when importing the app in other environments. However, Flyway seems to ignore the message as it may think it's a comment.

**Comment by Lyeeedar** [comment]
Support for many SQLPlus commands (including PROMPT) is a flyway Pro or Enterprise only feature. Do you have a pro or enterprise license? If so can you confirm whether or not it works when running in pro or enterprise mode?

**Comment by rafael-trevisan** [comment]
I have a pro license and can confirm that suppressing the "--" after the "prompt" command is a real issue.

**Comment by Lyeeedar** [comment]
This will be fixed in the next flyway release
