### ISSUE TITLE
Script Config Files - Placeholder replacements not working

### ISSUE THREAD

**Issue by KevMurph** [flyway/flyway#2721]
###### Which version and edition of Flyway are you using?

6.3.1 - Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

PostgreSQL 10.x

###### Which operating system are you using?

MacOS, CentOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I created a script config file as per this [documentation](https://flywaydb.org/documentation/scriptconfigfiles). This file contains a placeholder replacement. 

**FILES**
V1__my_description.sql
-- CONTENT --
CREATE TABLE ${my_placeholder}();
-- END CONTENT --

V1__my_description.sql.conf
-- CONTENT --
placeholders.my_placeholder="test_table_name"
-- END CONTENT --
**Note:** I have also tried flyway.placeholders.my_placeholder

###### What did you expect to see?

I expected to see the migration performed as if

`flyway.placeholders.my_placeholder="test_table_name"` were in the flyway.conf file.

Perhaps the "Reference" section of the documentation implies that ONLY the executeInTransaction configuration can be set from this file, but if this is the case, it would be nice to update the documentation to call that out more clearly.

###### What did you see instead?

org.flywaydb.core.api.FlywayException: Unknown configuration property: placeholders.my_placeholder

P.S. I can't seem to find when the script config file feature was added to flyway in the release notes. I see the page was added about 3 months ago according to the flywaydb.org github commit history. I also poked around for a few minutes in the codebase, but it's not readily apparent where the code to handle script config files is. I assume that it's done somewhere near the Migration Resolvers. Could you also point me to the entry point for handling these script config files?

**Comment by MikielAgutu** [comment]
> I expected to see the migration performed as if flyway.placeholders.my_placeholder="test_table_name" were in the flyway.conf file

Fair point, this is a bit inconsistent. We'll update the docs to make it clearer that 'normal' config options aren't supported in script config files. We'll also keep this open as we may possibly make code changes to make this clearer also.

It was added in 6.1.0, see the 'Option to force migration to (or not to) run in a transaction' entry in the release notes: https://flywaydb.org/documentation/releaseNotes#6.1.0.

The class you want is `SqlScriptMetadata`, here https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/sqlscript/SqlScriptMetadata.java
