### ISSUE TITLE
Create a database that does not exist

### ISSUE THREAD

**Issue by chelegen** [flyway/flyway#2723]
May I ask if  can add a feature. 
In **mvn flyway: migrate**, you can create a **database** that does **not exist**.

**Comment by MikielAgutu** [comment]
This is possible using the `initSql` configuration option. You can write a script which does this, e.g. in flyway.conf:

`flyway.initSql=CREATE DATABASE IF NOT EXISTS myDatabase;`

Does that help?

Also, this is possibly a duplicate, as we've had users ask about this before. However I can't quite find the duplicate issue so I'll leave it for now.

**Comment by MikielAgutu** [comment]
@chelegen any news?
