### ISSUE TITLE
Flyway using config file over env variable

### ISSUE THREAD

**Issue by PachowStudios** [flyway/flyway#2725]
###### Which version and edition of Flyway are you using?
`Community 6.3.1`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CMD

###### Which database are you using (type & version)?
`PostgreSQL 10.7`

###### Which operating system are you using?
`Windows 10`

###### What did you do?
I have the following set in my `flyway.conf`:
```
flyway.url=jdbc:postgresql://localhost:5432/DatabaseA
```

I then do the following on the command line:
```
set FLYWAY_URL=jdbc:postgresql://localhost:5432/DatabaseB

flyway info
```

###### What did you expect to see?
Flyway connects to `DatabaseB`.

###### What did you see instead?
Flyway connects to `DatabaseA`.

This worked on Flyway `6.0.6`

**Comment by MikielAgutu** [comment]
I'm unable to reproduce this. According to the [overriding order on the docs](https://flywaydb.org/documentation/commandline/#overriding-order), the highest priority is given to command line arguments.

Could you try specifying a command line argument for the url to `DatabaseB` to check the overriding order isn't completely broken? Also, is it possible there is some other configuration present in your workflow?

**Comment by PachowStudios** [comment]
Passing the url in the cli works fine. Nothing else has changed in my configuration.

**Comment by MikielAgutu** [comment]
Still unable to reproduce this. Is it happening in other contexts too? Could you try PowerShell for instance?

**Comment by PachowStudios** [comment]
Just tested in PowerShell and it worked properly. So just not working in CMD.

**Comment by MikielAgutu** [comment]
@PachowStudios Still can't reproduce...Unless you can give any further information this will just have to go on our long term backlong.

**Comment by PachowStudios** [comment]
It's working properly for me again now. No clue what changed. Must've been a weird fluke.
