### ISSUE TITLE
Unable to download artefacts for Enterprise flyway-maven-plugin

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2729]
Follow the documentation for referring to the Flyway maven plugin in your pom file (update the pom and settings.xml), for v6.3.1. You appear to get an error rather than the artefact being downloaded.

**Comment by MikielAgutu** [comment]
FYI, you can manually hit the endpoint to ensure the server is working: https://repo.flywaydb.org/repo/org/flywaydb/pro/flyway-maven-plugin/6.3.1/flyway-maven-plugin-6.3.1.jar
