### ISSUE TITLE
Problem with running fly migrate from Command-line

### ISSUE THREAD

**Issue by alehodro** [flyway/flyway#2741]
###### Which version and edition of Flyway are you using?

6.3.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

PostgreSQL 12.1

###### Which operating system are you using?

MacOs Mojave
10.14.6

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

1. Dowloaded tar archive with a client, moved it to Flyway folder in user catalog and unarchived it;
2. Set up parameters for connection with a DB in flyway.conf
flyway.url=jdbc:postgresql://localhost:5432/postgres
flyway.user=postgres
flyway.password=postgres
(db runs in docker locally, parameters are valid and double-checked)
3. created V1__create_database.sql file in sql folder of client
"  create table PERSON (
    ID int not null,
    NAME varchar(100) not null
);
"
4. started clean DB
5. returned to root directory of client (flyway-6.3.2) and run command "flyway migrate"

###### What did you expect to see?

Creating schema history table: "PUBLIC"."flyway_schema_history"
Current version of schema "PUBLIC": << Empty Schema >>
Migrating schema "PUBLIC" to version 1 - Create person table
Successfully applied 1 migration to schema "PUBLIC" (execution time 00:00.062s).

###### What did you see instead?

ERROR: Unable to connect to the database. Configure the url, user and password!

###### Hint

If I enter conf directory of client and run command from there it partially works, because client touches DB and even creates "flyway_schema_history" table, but sees no migration file. I register another issue for that.

**Comment by Lyeeedar** [comment]
If you run flyway with the -X argument you will see more information about what config files it is loading, and where it is searching for migrations. Could you please post the log from running that here.

**Comment by alehodro** [comment]
> If you run flyway with the -X argument you will see more information about what config files it is loading, and where it is searching for migrations. Could you please post the log from running that here.

iMac-Saul:Flyway bettercallsaul$ flyway migrate -X
DEBUG: Loading config file: /usr/local/Cellar/flyway/6.3.1/libexec/conf/flyway.conf
DEBUG: Unable to load config file: /Users/bettercallsaul/flyway.conf
DEBUG: Unable to load config file: /Users/bettercallsaul/Flyway/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /usr/local/Cellar/flyway/6.3.1/libexec/jars
DEBUG: flyway.locations -> filesystem:/usr/local/Cellar/flyway/6.3.1/libexec/sql
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/derby-10.15.1.3.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/jaybird-jdk18-3.0.6.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/derbytools-10.15.1.3.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/mariadb-java-client-2.4.0.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/postgresql-42.2.8.jre6.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/mssql-jdbc-7.2.0.jre8.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/hsqldb-2.5.0.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/derbyshared-10.15.1.3.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/h2-1.4.200.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/mysql-connector-java-8.0.17.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/derbyclient-10.15.1.3.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/snowflake-jdbc-3.11.1.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/sqlite-jdbc-3.23.1.jar
Flyway Community Edition 6.3.1 by Redgate
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
	at org.flywaydb.core.internal.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:34)
	at org.flywaydb.core.Flyway.execute(Flyway.java:410)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:153)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:192)
	at org.flywaydb.commandline.Main.main(Main.java:128)

**Comment by alehodro** [comment]
iMac-Saul:Flyway bettercallsaul$ cd conf/
iMac-Saul:conf bettercallsaul$ flyway migrate -X
DEBUG: Loading config file: /usr/local/Cellar/flyway/6.3.1/libexec/conf/flyway.conf
DEBUG: Unable to load config file: /Users/bettercallsaul/flyway.conf
DEBUG: Loading config file: /Users/bettercallsaul/Flyway/conf/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /usr/local/Cellar/flyway/6.3.1/libexec/jars
DEBUG: flyway.locations -> filesystem:/Users/bettercallsaul/Flyway/sql
DEBUG: flyway.password -> ********
DEBUG: flyway.url -> jdbc:postgresql://localhost:5432/postgres
DEBUG: flyway.user -> postgres
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/derby-10.15.1.3.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/jaybird-jdk18-3.0.6.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/derbytools-10.15.1.3.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/mariadb-java-client-2.4.0.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/postgresql-42.2.8.jre6.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/mssql-jdbc-7.2.0.jre8.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/hsqldb-2.5.0.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/derbyshared-10.15.1.3.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/h2-1.4.200.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/mysql-connector-java-8.0.17.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/derbyclient-10.15.1.3.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/snowflake-jdbc-3.11.1.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/6.3.1/libexec/drivers/sqlite-jdbc-3.23.1.jar
Flyway Community Edition 6.3.1 by Redgate
DEBUG: Scanning for filesystem resources at '/Users/bettercallsaul/Flyway/sql'
DEBUG: Scanning for resources in path: /Users/bettercallsaul/Flyway/sql (/Users/bettercallsaul/Flyway/sql)
DEBUG: Found filesystem resource: /Users/bettercallsaul/Flyway/sql/V1__Create_person_table.sql
Database: jdbc:postgresql://localhost:5432/postgres (PostgreSQL 12.1)
DEBUG: Driver  : PostgreSQL JDBC Driver 42.2.8.jre6
DEBUG: DDL Transactions Supported: true
DEBUG: Schemas: 
DEBUG: Default schema: null
DEBUG: Scanning for SQL callbacks ...
DEBUG: Validating migrations ...
DEBUG: Filtering out resource: /Users/bettercallsaul/Flyway/sql/V1__Create_person_table.sql (filename: V1__Create_person_table.sql)
Successfully validated 1 migration (execution time 00:00.041s)
Current version of schema "public": 1
Schema "public" is up to date. No migration necessary.
DEBUG: Memory usage: 15 of 258M
iMac-Saul:conf bettercallsaul$

**Comment by Lyeeedar** [comment]
In the second call it seems to be running correctly, finding the migration (V1__Create_person_table), and seeing that this has already been applied to the database.

`Flyway info` should show you this information.

The first run was from the wrong directory, as you can see from the places flyway searched:
DEBUG: Loading config file: /usr/local/Cellar/flyway/6.3.1/libexec/conf/flyway.conf
DEBUG: Unable to load config file: /Users/bettercallsaul/flyway.conf
DEBUG: Unable to load config file: /Users/bettercallsaul/Flyway/flyway.conf

If you want flyway to run a config file from a different directory, you can pass it in via the -configFiles="" argument. See https://flywaydb.org/documentation/commandline/#config-files
