### ISSUE TITLE
FlywayException: Unable to parse statement

### ISSUE THREAD

**Issue by dcheng45** [flyway/flyway#2746]
###### Which version and edition of Flyway are you using?
6.3.2 Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MySQL 5.7.12

###### Which operating system are you using?
Mac OS X (Mysql DB in Linux Docker container)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Script:
ALTER TABLE `traveler_personal_info` ADD COLUMN `birthdate_tmp` DATE AFTER `birthdate`;
UPDATE traveler_personal_info SET birthdate_tmp =
CASE
 WHEN birthdate = unix_timestamp('1960-01-01') THEN DATE('1970-01-01')
 ELSE cast(birthdate as date)
END;

###### What did you expect to see?
migrate successfully. Works successfully in version 6.3.1

###### What did you see instead?
Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/V26__traveler_birthdate_to_date.sql at line 2 col 1: Incomplete statement at line 2 col 1: UPDATE traveler_personal_info SET birthdate_tmp =
CASE
 WHEN birthdate = unix_timestamp('1960-01-01') THEN DATE('1970-01-01')
 ELSE cast(birthdate as date)
END;

**Comment by Lyeeedar** [comment]
This should be fixed by commit https://github.com/flyway/flyway/commit/706099bcae648d5c9c51f0847e9f58c880ab117b, and be in flyway 6.3.3
