### ISSUE TITLE
Update Gradle Maven packages

### ISSUE THREAD

**Issue by MikielAgutu** [flyway/flyway#2747]
We have two Gradle packages, gradle-core and gradle-plugins, both on version 3.0.

gradle-plugins 3.0 isn't available on official sources anymore. It's a magic version that we host here: https://github.com/flyway/flywaydb.org/tree/gh-pages/repo/org/gradle

We should upgrade to the latest version of both of these, hosted on the official Gradle repo:
https://repo.gradle.org/gradle/libs-releases-local/org/gradle/

**Comment by devkonarev** [comment]
Hi, will you accept a PR?

**Comment by MikielAgutu** [comment]
@devkonarev Yes we'd be happy to receive a PR. Note we pushed this to V7 because from what we could see this update introduces many breaking changes.
