### ISSUE TITLE
How to fix flyway migration mismatch type?

### ISSUE THREAD

**Issue by diedino** [flyway/flyway#2752]
###### Which version and edition of Flyway are you using?
6.0.4
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin
###### Which database are you using (type & version)?
 Postres, postgresqlVersion = '42.2.1'
###### Which operating system are you using?
Win10
###### What did you do?
 When try to run have error:

```
Migration type mismatch for migration version 2.2
-> Applied to database : JDBC
-> Resolved locally    : SQL
```
How to fix this prombem? 
If i tried to comment line `FLYWAY_ENABLE: "false"` in application.yml nothing happend too.

**Comment by MikielAgutu** [comment]
This is warning you that the applied migrations differ to the migrations you have in your project. In this case, v2.2 was applied as a Java migration, but your project has a SQL script.

If this is expected, then run a repair https://flywaydb.org/documentation/command/repair. This will re-align the types in schema history with available migrations.

**Comment by diedino** [comment]
But if it is not expected?

**Comment by diedino** [comment]
alse main trouble is i can not use it. But don't know how to switch off flyway.

**Comment by MikielAgutu** [comment]
This isn't really an issue with Flyway. The real problem is that your build tool is broken, or you aren't clear on the build tool's/your team's process.

I assume you're using the Spring Boot plugin? You should ask them https://github.com/spring-projects/spring-boot/issues
