### ISSUE TITLE
Mixed java and sql callbacks executed out of order

### ISSUE THREAD

**Issue by jaa2261** [flyway/flyway#2753]
###### Which version and edition of Flyway are you using?

6.3.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle

###### Which database are you using (type & version)?

Oracle 19

###### Which operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I have 3 afterMigrate callbacks: 2 sql ones and 1 java. When I extract the jar file I have the following in the db/migration folder:
afterMigrate__1-drop-Create_DB_Link.sql
afterMigrate__2-recompile-objects.sql
afterMigrate__3CheckForInvalidObjectsCallback.class

When I run the migration I see them executed in the logs in this order:

afterMigrate__3CheckForInvalidObjectsCallback.handle() called
Executing SQL callback: afterMigrate - 1-drop-Create DB Link
Executing SQL callback: afterMigrate - 2-recompile-objects

###### What did you expect to see?
I would have expected them to be executed in alphabetic order as they are in the same directory and that seems to be the convention for the other scripts

###### What did you see instead?
For some reason the java callback is called first.

**Comment by juliahayward** [comment]
The current behaviour is:
- Java callbacks, in the order specified in the config file
- SQL callbacks, in alphabetic order of description

There are a couple of issues with changing this:
- it's potentially a breaking change for some people who rely on the above: having both types of callback and where the ordering is significant
- Java callbacks aren't bound by a `{eventName}__{description}.class` naming convention - indeed, they *can't* be because one class can handle multiple event types.

Are your callbacks significant in terms of ordering (and therefore you can't do what you want) or is it just that the behaviour was a surprise?

**Comment by jaa2261** [comment]
Yes - if that's the order then that's fine - documentation around java callbacks is fairly sparse. e.g. It took a while to find out that I needed to specify the callback names in the config file - documented in the file but it would have been good if there had been a pointer in the main docs to look in the config file. An example of a plain java callback handling multiple events would be very useful.

Is there a reason why you need to specify the callback names in the config file? Couldn't you just run all the classes found in the jar using a naming convention to specify the order they are run in?

**Comment by juliahayward** [comment]
I suspect two reasons:
- lack of demand for change, as Java callbacks do not appear to be widely used
- the risks around introducing breaking changes.

It's not difficult to use reflection to identify callbacks and interleave them with SQL ones as we already do that for migrations. I'll add it as a feature request for v7.

**Comment by jaa2261** [comment]
Being able to interleave the java and sql callbacks would certainly be useful for us
