### ISSUE TITLE
Baseline doesn't work if flyway_schema_history table exists

### ISSUE THREAD

**Issue by Jacquers** [flyway/flyway#2754]
###### Which version and edition of Flyway are you using?

Community Edition 6.2.4 (PostgreSQL)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command line

###### Which database are you using (type & version)?

PostgreSQL 10.1

###### Which operating system are you using?

Docker (CentOS)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Baseline the database with a specific version. If the flyway_schema_history does not exist, then it's created and the baseline works. If the table exists (but it's empty) then the output shows that the baseline was successful, but no entry is actually written to the table, so the baseline doesn't work as expected.

###### What did you expect to see?

An entry in the flyway_schema_history table.

###### What did you see instead?

No entries in the flyway_schema_history table.

**Comment by MikielAgutu** [comment]
This is actually expected behavior. However I agree it's misleading. The answer is to delete the schema history table and try again.

Also, how did you get into a state where the schema history is empty?

**Comment by Jacquers** [comment]
Thanks, it works as expected once the table is deleted.

How I got there: I scripted an existing database which had the flyway table in it and was then playing around with various steps in baseline and migrate.

Perhaps a more informative message could be displayed if the table exists, but is empty? Or could it just not apply the baseline as I had expected?

**Comment by MikielAgutu** [comment]
> Perhaps a more informative message could be displayed if the table exists, but is empty? Or could it just not apply the baseline as I had expected?

Yes, I 100% agree. It's an unusual case that is rarely encountered in a normal workflow, which is why we haven't given it much attention. We will schedule some work to make the messaging clearer.
