### ISSUE TITLE
Flyway support SAP Hana .hdbview files

### ISSUE THREAD

**Issue by Rnagaraj1** [flyway/flyway#2755]
###### Which version and edition of Flyway are you using?
flyway-6.3.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I believe above mentioned version latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?
HDB2.0

###### Which operating system are you using?

Mac Os

###### What did you do?

schema = "CORE_P08";
query = "
select * \"CORE_P08\".\"CORE_P08.SCRIPT::TDF_TEMPLATE()\"
"
;

###### What did you expect to see?
After migration repository object should be shown as Sql Scripted View .Hdbview ext  in SAP HANA

###### What did you see instead?
Not a regular Sql Standard

**Comment by Lyeeedar** [comment]
Would you be able to provide the script you tried to run that failed, as well as the error message you got?

**Comment by Rnagaraj1** [comment]
Hi @Lyeeedar  ,
Here is the similar script I'm trying Run 
schema="your schema";
query = "SELECT
     SCENARIO,
       REGION,
       DIST_PT,
       MATERIAL,
       TIME_PERIOD,
       BEGIN_DATE,
       STO_OUT,
       STO_IN,
       FORCAST,
       PRODUCTION,
       FROZEN_PRODUCTION,
       OPEN_ORDERS,
       CYTD_SALES,
       CMTD_SALES,
       FROZEN_STO_IN,
       FROZEN_STO_OUT,
       STARTING_INVEN,
       ENDING_INVEN,
       FORWARD_COVERAGE_PERIODS,
       SPECIE,
       UNSCHEDULE_FROZEN,
       REMAIN_TO_SCHEDULE,
       PROD_PLAN
      from \"your schema\".\"table name\"
"
;
 or more example:
schema="SXSLTP08";
query ="
  SELECT
    \"OPSYS\"
    ,\"MANDT\"
    ,\"CUOBJ\"
    ,\"KLART\"
    ,\"OBTAB\"
    ,\"OBJEK\"
    ,\"ROBTAB\"
    ,\"ROBJEK\"
    ,\"CLINT\"
    ,\"STATU\"
    ,\"CUCOZHL\"
    ,\"PARENT\"
    ,\"ROOT\"
    ,\"EXPERTE\"
    ,\"MATNR\"
    ,\"DATUV\"
    ,\"TECHS\"
    ,\"OPTIME\"
    ,\"OPTYPE\"
  FROM
    \"SXSLTP08\".\"INOB\"
    ";

Please let me know if you have any way we can promote , these scripts .

**Comment by pavanbigfort** [comment]
@Lyeeedar

**Comment by Lyeeedar** [comment]
Currently flyway only support executing sql or java migrations. As such we don't currently support executing .hdbview files.

I'll leave this issue open to gauge interest in support for this.

**Comment by MikielAgutu** [comment]
In Flyway 7 you can now call an external tool to execute these files: https://flywaydb.org/documentation/migrations#script-migrations

**Comment by pavanbigfort** [comment]
@MikielAgutu can you point me to the specific sections can this support ?
