### ISSUE TITLE
Fix performance issue with the MySQLSchema doEmpty() call

### ISSUE THREAD

**Issue by AlexisDeschamps** [flyway/flyway#2756]
Hello, I am creating a new issue to report the problem described in #2123. As specified by @golbi's comment on the issue, the PR merged for the original issue did not really solve the problem of filtering by `TRIGGER_SCHEMA` instead of `EVENT_OBJECT_SCHEMA`. As explained in #2123, `EVENT_OBJECT_SCHEMA` will provide significantly better performance.

I have implemented the fix in #2750 (it's a one-line change). Please let me know if there's anything I could to do help merge the PR and for a new Flyway version to be released. Thanks!

###### Which version and edition of Flyway are you using?
Flyway 6.3.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MySQL 5.7

###### Which operating system are you using?
Linux containers.

###### What did you do?
Execute `flyway.migrate()` with `baselineOnMigrate = true` on a database that had not been migrated by Flyway before.

###### What did you expect to see?
A relatively fast first migration/baseline (e.g. a few hundreds of milliseconds).

###### What did you see instead?
An extremely slow first migration/baseline (e.g. a few tens of minutes - we have a lot of logical databases).

**Comment by Lyeeedar** [comment]
Relates to https://github.com/flyway/flyway/pull/2750

**Comment by AlexisDeschamps** [comment]
Closing this since the fix was merged in https://github.com/flyway/flyway/pull/2750.
