### ISSUE TITLE
Can "flyway_schema_history" table creation be skipped?

### ISSUE THREAD

**Issue by adivardhan** [flyway/flyway#2757]
###### Which version and edition of Flyway are you using?
Flyway 5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Spring Boot Flyway (uses Java API)

###### Which database are you using (type & version)?
Oracle SQL 12.2

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I have two database users:
1. DBX_ADMIN (has **all DDL's** permissions)
2. DBX_USER (has **only DML** permissions)

User DBX_ADMIN creates all tables, which includes the "flyway_schema_history" table.
Now, the client application code will only be allowed to use DBX_USER group to connect to database.

But when the client application boots up, flyway being enabled, will try to create "flyway_schema_history" table as DBX_USER. 
The doExists() check will fire a query but get no rows as result set, hence exists() check return "false".  Since, this user is not the owner of table, it is expected to get false.

But, I don't want it to fail here. The client must be able to work without any issue.
The DBX_USER only wants to migrate some data to database (No DDL's)

Is this not possible?

###### What did you expect to see?
I am hoping that I can skip the creation of "flyway_schema_history" table, even if user which connected to database is different.
As my DDL is migrated from ADMIN but the USER also using flyway only migrates data.

###### What did you see instead?
Application boot up fails, as the DBX_USER is trying to create a "flyway_schema_history" table but does not have the permissions.

**Comment by juliahayward** [comment]
In FLyway 6, your DBX_USER account must have permissions to check the existence of the history table as well as being able to write to it. Can you give us a use case as for why you wouldn't give your DBX_USER those permissions on that one specific table, even if you don't grant it that permission on anything else?

**Comment by adivardhan** [comment]
> In FLyway 6, your DBX_USER account must have permissions to check the existence of the history table as well as being able to write to it. Can you give us a use case as for why you wouldn't give your DBX_USER those permissions on that one specific table, even if you don't grant it that permission on anything else?

I think its true for Flyway 5 as well. (do correct if wrong)

Use case:

NOTE: 
We use Oracle 12 as our RDBMS

1. We have an Infrastructure team which creates tables for us in production environment.
2. These tables are created as user: DBX_ADMIN  (admin access who later grants access to DBX_USER)
3. We only get access to Synonyms of those tables and as user: DBX_USER. **(& not admin)**
4. This means for any table (including flyway's) DBX_USER is NOT the owner of table.
5. We launch our Java App, and **make database connection using DBX_USER** credentials.
6. At this point we already have all tables (including flyway's) on our RDBMS.
7. Now, flyway boots up.
8. It **checks for existence** of "flyway_schema_history" table.
9. Flyway calls: 
`org.flywaydb.core.internal.database.base.Table
protected boolean exists(Schema catalog, Schema schema, String table, String... tableTypes)`
10. The above methods executes a **table existence query but as DBX_USER** (as we connected that way from Java App)
11. This query, hence, **returns NO row** as the table was not created by this user. (Owner is DBX_ADMIN)
12. So Java app boot up fails.

_PS: I cannot use DBX_ADMIN from Java App._

**Comment by juliahayward** [comment]
OK - I believe one way to work around this is the following: 
- DBX_ADMIN creates a synonym for the history table.
- ensure that DBX_USER has the rights to both check the existence of this synonym and insert rows
- alter the Flyway configuration parameter `flyway.table` (in the configuration file, or your Java code) to refer to the synonym, not the actual table

Could you see if that resolves your problem?

**Comment by adivardhan** [comment]
@juliahayward 

This most certainly would, with only catch, to have a special grant permission on this table.
Anyway for now since I may not able to get DBX_ADMIN to grant such privilege to this table, I have decided to disable flyway.
I'll keep looking into getting this resolved one way or another.

Thanks for your help!
