### ISSUE TITLE
v7: Identify Java callbacks by reflection and interleave with SQL ones

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2760]
in v6, Java callbacks are identified by being specified in configuration, and their ordering is also taken from the config. This is inconsisent with Java migrations which are identified by reflection and run in order based on naming. We're also constrained to run all Java callbacks for an event first, followed by all SQL ones.

Consider for v7 picking up callbacks by reflection and running them in alphabetical order interleaved with SQL callbacks.

**Comment by juliahayward** [comment]
(arose as a result of #2753 )

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
