### ISSUE TITLE
Snowflake - support QUOTED-IDENTIFIERS-IGNORE-CASE option TRUE

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2761]
Split from #2731  Two things to improve: 

when QUOTED-IDENTIFIERS-IGNORE-CASE is true we get errors on the history table as the table name and column names are lower case but quoted. They need to be upper case and existing tables migrated.

When it's false, the implicit quoting of `flyway.schemas` and `flyway.defaultSchema` means that schema names have to be uppercased in the config - ugly but workable for now in v6

**Comment by juliahayward** [comment]
A script that will do the migration:

```USE DATABASE DEMO_DB;

SHOW TABLES;

ALTER TABLE IF EXISTS "flyway_schema_history" RENAME TO FLYWAY_SCHEMA_HISTORY;

ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "installed_rank" TO INSTALLED_RANK;
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "version" TO VERSION;
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "description" TO DESCRIPTION;
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "type" TO TYPE;
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "script" TO SCRIPT;
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "checksum" TO "CHECKSUM";
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "installed_by" TO INSTALLED_BY;
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "installed_on" TO INSTALLED_ON;
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "execution_time" TO EXECUTION_TIME;
ALTER TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY RENAME COLUMN "success" TO SUCCESS;```

**Comment by juliahayward** [comment]
I had a closer look. If the column names are uppercased then we either need an overrideable `mapRow()` in `JdbcTableSchemaHistory`, or to construct a mapping of column names to ordinals that understands the casing. The latter fails because of what I think is a bug in the Snowflake JDBC driver https://github.com/snowflakedb/snowflake-jdbc/issues/355.

The less nice solution is to flip `QUOTED-IDENTIIERS-IGNORE-CASE` to false for the session immediately before we do anything involving the history table, and back again immediately afterwards.

**Comment by MikielAgutu** [comment]
Hopefully Snowflake will fix + ship their driver, so I'll mark as blocked for now. Although if it takes too long we'll reassess.

**Comment by davidyang99** [comment]
Could we reassess it or is there any workaround?

**Comment by juliahayward** [comment]
Yes, I'll pick it up again now. Will let you know how far we get.
