### ISSUE TITLE
DROP always references public schema even during migration to other schemas

### ISSUE THREAD

**Issue by jkenefick** [flyway/flyway#2764]
###### Which version and edition of Flyway are you using?
6.0.8

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes - also verified to occur with 6.3.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin
```Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T08:58:13+01:00)```
```Default locale: en_IE, platform encoding: UTF-8```
```OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"```

Java API
Java Version:
```openjdk 11.0.6 2020-01-14 LTS```
```OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)```
```OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)```

###### Which database are you using (type & version)?
PostgreSQL 11.2 (Debian 11.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

###### Which operating system are you using?
Mac OS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
1. Download and run postgres docker image
```docker run --name some-postgis -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d mdillon/postgis```  This runs a postgres database with public schema available by default.
2. Unzip attached zip and run
```mvn clean install```
```mvn spring-boot:run```
[flyway-test.zip](https://github.com/flyway/flyway/files/4446098/flyway-test.zip)

###### What did you expect to see?
Table "building", "asset" and view "building_view"  are migrated to public schema (by default) and to t1 and t2 schemas (via FlywayMigration.java)

###### What did you see instead?

Schema public:
Only has building table and building view

Schema t1:
Only has asset table

Schema t2:
Nothing.

Explanation:
When the initial public migration was run, building, asset and building_view were created in schema public.

When migration of t1 was run:
1. The drop of asset table actually dropped **public**.asset
2. The create of asset table created **t1**.asset
3. The drop of building during t1 migration actually tried to drop **public**.building (**not** t1.building) and because public.building has a dependent view, the drop failed.
4. Therefore the entire migration stopped, leaving public with a missing asset table, and t1 migration failed when dropping the building table if exists because it tried to drop the public table building instead of verifying that t1.building didn't exist.

**Comment by jkenefick** [comment]
May be related to
https://github.com/flyway/flyway/issues/1959

regression?

**Comment by jkenefick** [comment]
still occurs with recommended workaround in #1959 to set spring.datasource.hikari.auto-commit to true.  I used the modified application.yml
```spring:
  application:
    name: flyway-test

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

    hikari:
      auto-commit: true

server:
  port: 8080
  servlet:
    context-path: /
```

**Comment by jkenefick** [comment]
Anyone interested in this issue at all at flyway?

**Comment by MikielAgutu** [comment]
Thanks for providing reproduction steps, and sorry for the lack of responsiveness.

I'm finding it difficult to cut through the boilerplate provided by Spring Boot to understand the issue. Also, Spring Boot isn't an officially supported integration FYI.

It would be helpful if you could provide a reproduction that didn't rely on it - perhaps a simple Maven project that depends on flwyay core?

**Comment by matthjes** [comment]
We're experiencing a similar problem with Flyway 5.2.4, Payara 4.x, EclipseLink 2.6.4. The schema ist set to some value other than `public`, but views are getting dropped fom `public`. I have to think about how to come up with a minimal project for this...

**Comment by jkenefick** [comment]
@MikielAgutu thanks for the response and the info.  I'll see what I can do.

**Comment by MikielAgutu** [comment]
@jkenefick Any news?

**Comment by srikanthAnuguAmount** [comment]
It seems like issue is not fixed yet but I see it is closed, Any reason?

**Comment by mtzagkarakis** [comment]
Hi everyone. We stumble this issue ourselves today. The problem arises in class org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection. There in method changeCurrentSchemaTo it checks for the value of originalSchemaNameOrSearchPath string. The variable is defined in superclass and it gets its value from method getCurrentSchemaNameOrSearchPath(). This method implementation in PostgreSQLConnection class is: "SHOW search_path" which returns 'public' in postgres. 

So in the end changeCurrentSchemaTo calls doChangeCurrentSchemaOrSearchPathTo(schema + "," + originalSchemaNameOrSearchPath); so search path value in postgres end up being '"some_schema_name",public'

so any drop table sql command, given this search path, will delete any public schema table that is happened to match if there is no table with the same name on 'some_schema_name' schema. 

I think this should get re-opened

**Comment by ErisoHV** [comment]
Hi! I'm having the same ploblem with this library and version:

```
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-database-postgresql</artifactId>
      <version>10.10.0</version>
      <scope>runtime</scope>
    </dependency>
```

**Comment by mtzagkarakis** [comment]
This is how we overcome it => 

properties.setInitSqls(List.of("SELECT set_config('search_path', '', false)"));

You need to 'reset' postgres search path basically (so it can got to the default value again - which is the 'public' schema)

**Comment by ErisoHV** [comment]
> This is how we overcome it =>
> 
> properties.setInitSqls(List.of("SELECT set_config('search_path', '', false)"));
> 
> You need to 'reset' postgres search path basically (so it can got to the default value again - which is the 'public' schema)

@mtzagkarakis Thank you, 
How do you use this configuration? Where can I include it?

**Comment by mtzagkarakis** [comment]
In general in Flyway you take this rg.springframework.boot.autoconfigure.flyway.FlywayProperties.class to create the Flyway.class

The Flyway properties class you can change it either programmatically or by binging with some property/yml file 

initSqls is a property of FlywayProperties.class
