### ISSUE TITLE
Allow to ignore repeatable migrations (for test)

### ISSUE THREAD

**Issue by flozano** [flyway/flyway#2765]
###### Which version and edition of Flyway are you using?
6.2.4

##### Scenario
Given the following hypothetical scenario:
 - V1__create_initial_model.sql
 - V2__add_some_fields.sql
 - V3__add_more_fields_and_migrate_some_data.sql
 - V4__add_some_other_fields.sql
 - R__create_some_views.sql

"R__create_some_views" re-creates all views based on latest state (uses DB objects created in V4).

Now, imagine V3 adds some transformations which __I would like to have test for__. 

To do that, I'm doing in Java code:
```java
  myFlywayConfiguration().target("2").migrate();
  insertSomeTrickyDataThatWillBeTransformedByV3();
  myFlywayConfiguration().target("3").migrate();
  assertDataIsCorrect();
```

However, "R__create_some_views" is executed, so the test fails.

##### Feature request
It would be great to have `ignoreRepeatable()` in `FluentConfiguration`, so that I can isolate what is executed and what is not. I understand this flag would make little sense in normal production migrations, but it'd be great for making migrations more testable.

##### Mitigation
I'm trying to mitigate this by changing `repeatableSqlMigrationPrefix` during test execution, but it's a little obscure.

**Comment by MikielAgutu** [comment]
Could you place the repeatable migrations in a separate folder, then exclude them by not including that folder in `flyway.locations`?

**Comment by flozano** [comment]
Yes, that's possible, thank you, but I guess I can't move existing migrations to different location without them being considered a different migration?

 It's similar to changing repeatable prefix to something like "XXX" so that the real ones that start with "R" are not used.

**Comment by MikielAgutu** [comment]
You should be able to move migrations without Flyway thinking the migration is different. They will show up as missing if they've already been applied however.
