### ISSUE TITLE
Give a way to overwrite flyway .sql migration file within a jar from my project?

### ISSUE THREAD

**Issue by kopax** [flyway/flyway#2767]
###### Which version and edition of Flyway are you using?

latest

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

It's a feature request

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

Postgresql 11

###### Which operating system are you using?

Docker/Debian

###### Feature proposal

I am working on a Java application that is modular.

Some of my flyway `.SQL` migration files are within installed `.jar`s.

I am able to override java class from those jars, but there is no way I can **overwrite** one of those `.sql` **migration file from within my project** so mine get executed for the migration instead of the one provided by the `jar`.

This is a feature request to allow `.sql` to be overridden.

**Comment by MikielAgutu** [comment]
I'm not sure if this is the right thing for Flyway. Overriding Java migrations is a given since Flyway is leaning on Java's systems for everything - class definition, inheritance, and so on. For SQL we would have to build in something entirely new.

How would you propose this should work?

Also, have you tried setting the `locations` configuration property to look somewhere else for SQL migrations?

**Comment by kopax** [comment]
Thanks yes I am already using the `locations`.

I rather keep the migrations files so I do not have to duplicate them, and will be able to still receive the updates.

Is there a way to filter the list of `.sql` files within the `location` and add a second `location` programmatically?

**Comment by MikielAgutu** [comment]
> Is there a way to filter the list of .sql files within the location and add a second location programmatically?

I can't think of a way to do this.

I'm not sure I can think of a workaround for you. I'll mark this as a feature request.
