### ISSUE TITLE
Parser issue for Sybase ASE for keyword GOTO

### ISSUE THREAD

**Issue by ltwesley** [flyway/flyway#2774]
###### Which version and edition of Flyway are you using?
6.3.3 (community and pro edition)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes the issue can be reproduced in the latest. (v6.3.3)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command Line 

###### Which database are you using (type & version)?
Sybase ASE 16.2

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
SQL with GOTO keywords results in a 'column not found' error when running migrate command. The parser is splitting the GOTO into two keywords (GO, TO)
```
declare @count smallint
select @count = 1
restart:
  print 'yes'
select @count = @count + 1
while @count <= 4
  goto restart
```

###### What did you expect to see?
No errors when running migrate command. In the code snippet above 'yes' should be printed 3x

###### What did you see instead?
```
Migration R__wes.sql failed
---------------------------
SQL State  : 37000
Error Code : 102
Message    : Incorrect syntax near '4'.
Line       : 1
Statement  : declare @count smallint
select @count = 1
restart:
  print 'yes'
select @count = @count + 1
while @count <= 4
```

**Comment by Lyeeedar** [comment]
This will be in flyway 6.4.1
