### ISSUE TITLE
Flyway 6.3.3 hangs when processing DROP VIEW IF EXISTS

### ISSUE THREAD

**Issue by elieabichar-wk** [flyway/flyway#2778]
###### Which version and edition of Flyway are you using?
6.3.3 (latest release)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java

###### Which database are you using (type & version)?
Mysql 5.7

###### Which operating system are you using?
Mac OS

###### What did you do?
We were upgrading from 6.3.2 to 6.3.3. Flyway migration worked well with the older 6.3.2 version but hangs with 6.3.3 with the statement below

```
DROP VIEW IF EXISTS `view-1`, `view-2`;
```

###### What did you expect to see?
Migration to complete successfully 

###### What did you see instead?
Hanging due to a loop likely because of processing the wrong code path for ```IF``` in [MySqlParser.adjustBlockDepth](https://github.com/flyway/flyway/blob/flyway-6.3.3/flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLParser.java#L118-L129)

**Comment by Lyeeedar** [comment]
I could not reproduce this in flyway 6.4. When this releases (today or tomorrow), would you mind testing it to see if you can also confirm it is fixed?

**Comment by elieabichar-wk** [comment]
i can test and confirm. thank you

**Comment by elieabichar-wk** [comment]
I tested the latest 6.4.0 and migration worked as expected. thanks
