### ISSUE TITLE
Website mistakes

### ISSUE THREAD

**Issue by vazhnov** [flyway/flyway#2779]
[Here](https://flywaydb.org/documentation/faq#parallel) is a double "even":

> that even if even multiple instances

And [here](https://flywaydb.org/documentation/faq#downgrade), I think, it is better to use "How about …":

> What about undo/downgrade/downward migrations?

**Comment by MikielAgutu** [comment]
Thanks for pointing these out. For reference there is a GitHub repository for the website too https://github.com/flyway/flywaydb.org
