### ISSUE TITLE
Hi ,I am using flyway 6.3.3 version and I am using svn. My question is that Is there any way to automate the process of naming the versioned files. I don't want to rely on developers to add version numbers.Please suggest

### ISSUE THREAD

**Issue by Kirannnnn** [flyway/flyway#2784]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Lyeeedar** [comment]
Flyway does not do anything for generating the version numbers, as that is how the users of flyway control what it does. The version numbers control in what order the migrations get applied, and therefore require your developers to decide the valid order. Why do you not want to rely on your developers to assign them?

You could look into svn pre-commit hooks to enforce a naming scheme for the files, which maybe help enforce some consistency.
Another alternative could be using a timestamp in the version so you do not get version number conflicts.

**Comment by Kirannnnn** [comment]
Thank you for response
