### ISSUE TITLE
SSL to MySQL from CLI: need to add extra arguments

### ISSUE THREAD

**Issue by vazhnov** [flyway/flyway#2788]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 6.4.0 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line.

###### Which database are you using (type & version)?

AWS RDS MySQL 5.7.22.

###### Which operating system are you using?

```
 $ cat /etc/os-release 
PRETTY_NAME="Devuan GNU/Linux 3 (beowulf)"
NAME="Devuan GNU/Linux"
VERSION_ID="3"
VERSION="3 (beowulf)"
VERSION_CODENAME=beowulf
ID=debian
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"
```

###### What did you see instead?

I've successfully established SSL connection to AWS RDS with Flyway CLI, but I had to edit shell-script https://github.com/flyway/flyway/blob/master/flyway-commandline/src/main/assembly/flyway to add extra arguments:
```shell
EXTRA_ARGS=
if $linux; then
  EXTRA_ARGS=-Djava.security.egd=file:/dev/../dev/urandom
fi
EXTRA_ARGS="$EXTRA_ARGS -Djavax.net.ssl.trustStore=~/aws_rds_truststore.jks -Djavax.net.ssl.trustStorePassword=changeit"

if `command -v cygpath > /dev/null`; then CP=`cygpath -pw "$CP"`; fi
"$JAVA_CMD" $JAVA_ARGS $EXTRA_ARGS -cp "$CP" org.flywaydb.commandline.Main "$@"
```

Could you please add possibility to add arguments without patching your shell script?

For example, by `FLYWAY_EXTRA_ARGS`:

```shell
EXTRA_ARGS=${FLYWAY_EXTRA_ARGS:=}
if $linux; then
  EXTRA_ARGS="$EXTRA_ARGS -Djava.security.egd=file:/dev/../dev/urandom"
fi
```

Then I will create documentation how to connect Flyway to MySQL with SSL.

**Comment by vazhnov** [comment]
Pull request: #2789.

**Comment by MikielAgutu** [comment]
Thanks for reporting this. Ideally we'd like to add built in support for things like this, instead of allowing arbitrary extra arguments, properties, etc. Is this the only reason you'd like the 'extra arg' feature?

**Comment by vazhnov** [comment]
@MikielAgutu , yes, right now I need to add SSL support to Flyway CLI only, I see no other reason for this patch.

**Comment by MikielAgutu** [comment]
Have you seen https://github.com/flyway/flyway/issues/1727? Apparently this has come up before a while ago. You can use the `JAVA_ARGS` environment variable.

**Comment by vazhnov** [comment]
@MikielAgutu , `JAVA_ARGS` looks good! Let me check…

**Comment by vazhnov** [comment]
```shell
export JAVA_ARGS="-Djavax.net.ssl.trustStore=~/aws_rds_truststore.jks -Djavax.net.ssl.trustStorePassword=changeit"
```
works fine. Thank you very much!
