### ISSUE TITLE
Hi,I am using flyway 6.3.3 version and I have environment specific scripts but in one of my script I have $BASE which is part of that script and not meant for replacement with placeholder values ..How to handle this? Please Advice...Thanks in advance 

### ISSUE THREAD

**Issue by Kirannnnn** [flyway/flyway#2792]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by MikielAgutu** [comment]
You can configure the placeholder prefix and suffix: https://flywaydb.org/documentation/commandline/migrate#placeholderPrefix.

**Comment by Kirannnnn** [comment]
Thanks , It works
