### ISSUE TITLE
Improve error/debug messaging when Flyway Can't Calculate Checksum

### ISSUE THREAD

**Issue by rscero** [flyway/flyway#2799]
Which version and edition of Flyway are you using? 6.4.0

Which client are you using? Command-line

Which database are you using SQL Server 2016

Which operating system are you using? Windows 

What did you do?

Had this exact problem yesterday, ERROR: Unable to calculate checksum of <script file> Input Length=1. Looked through many discussions, went down the rabbit hole testing them, none of them worked. Script was not large at all, ran the repair command, even tried converting the encoding between UTF-8 and ANSI. Nothing worked. To make it more confusing, the procedure being changed hadn't been updated in probably 4-5 years (prior to us using flyway), the change was minor, and the change script code, when run in SQL, ran fine. After a LOT of testing, found the issue. Our procedures have a comment header that maintains information on history of changes and other info. Part of that header is a copyright statement. Example:
--COPYRIGHT 2011 .... Well, in this particular procedure, that had been set to: © 2011... Yep, it was the © character that was causing the issue. Removed that, added COPYRIGHT statement, problem solved.

What did you expect to see? message on bad character would help in debugging, may be an enhancement to warn or handle these type of characters.

What did you see instead?  Misleading error message.

**Comment by MikielAgutu** [comment]
I'm unable to reproduce this just by copying the '©' character into a migration script. Can you share the script file itself (or a file with the bad comment in)?

**Comment by rscero** [comment]
Attached.



[cid:image001.png@01D62380.BE475420]

**Comment by MikielAgutu** [comment]
@rscero Unfortunately email attachments don't work! You'll have to share the file directly on GitHub on this issue page.

**Comment by MikielAgutu** [comment]
@rscero Any news?

**Comment by MikielAgutu** [comment]
Closing for lack of response.
