### ISSUE TITLE
Documentation for "mixed" config setting is misleading

### ISSUE THREAD

**Issue by LHCGreg** [flyway/flyway#2801]
The documentation for the "mixed" config setting is misleading. It says:

> Whether to allow mixing transactional and non-transactional statements within the same migration. **Enabling this automatically causes the entire affected migration to be run without a transaction.**
>
> Note that this is only applicable for PostgreSQL, Aurora PostgreSQL, SQL Server and SQLite which all have statements that do not run at all within a transaction.
>
> This is not to be confused with implicit transaction, as they occur in MySQL or Oracle, where even though a DDL statement was run within within a transaction, the database will issue an implicit commit before and after its execution.

[emphasis mine]

To me that says that if I turn on the "mixed" setting, flyway will never run a migration in a transaction. But testing that out, it still ran a simple migration in a transaction. Doing on a search on github issues, it seems this setting turns on a mode where flyway tries to guess whether the migration script should not automatically be wrapped in a transaction based on the presence of certain statements in the script. Is this correct? I didn't see that in the docs.

I don't want flyway to guess whether a script should be wrapped in a transaction or not. I would like to disable automatic transactions for all migration scripts and leave it up to the scripts to use transactions. I see that you can disable the automatic transaction on a script-by-script basis with a `<script_name>.conf` file that contains `executeInTransaction=false`. But that has to be done for *every* script. Is there any way to disable automatic transactions for *all* migrations without having to create a .conf file for every migration script?

###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This is the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
PostgreSQL 12.2

###### Which operating system are you using?
Flyway is running on Windows, PostgreSQL is running on the postgres:12.2 docker image.

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

flyway.conf:
```
flyway.locations=filesystem:.
flyway.mixed=true
flyway.cleanDisabled=true
```

V1__initial_schema.sql:
```
BEGIN TRANSACTION;

CREATE TABLE thing
(
  thing_id int NOT NULL PRIMARY KEY, -- trailing comma after last column is a syntax error
);

COMMIT TRANSACTION;
```

I ran
```
C:\projects\flyway_test_2>flyway -url="jdbc:postgresql://localhost:6543/flyway_test_2" -user=postgres -password=postgres_pw migrate
```

###### What did you expect to see?
I expected to see an error about the syntax error, but no warning about a transaction being already in progress.

###### What did you see instead?
```
C:\projects\flyway_test_2>flyway -url="jdbc:postgresql://localhost:6543/flyway_test_2" -user=postgres -password=postgres_pw migrate
Flyway Community Edition 6.4.1 by Redgate
Database: jdbc:postgresql://localhost:6543/flyway_test_2 (PostgreSQL 12.2)
Successfully validated 1 migration (execution time 00:00.017s)
Creating Schema History table "public"."flyway_schema_history" ...
Current version of schema "public": << Empty Schema >>
Migrating schema "public" to version 1 - initial schema
WARNING: DB: there is already a transaction in progress (SQL State: 25001 - Error Code: 0)
ERROR: Migration of schema "public" to version 1 - initial schema failed! Changes successfully rolled back.
ERROR:
Migration V1__initial_schema.sql failed
---------------------------------------
SQL State  : 42601
Error Code : 0
Message    : ERROR: syntax error at or near ")"
  Position: 116
Location   : .\V1__initial_schema.sql (C:\projects\flyway_test_2\.\V1__initial_schema.sql)
Line       : 3
Statement  : CREATE TABLE thing
(
  thing_id int NOT NULL PRIMARY KEY, -- trailing comma after last column is a syntax error
)
```

**Comment by MikielAgutu** [comment]
This is something we've thought alot about. The ultimate aim is to make deployments straightforward, and to retain an accurate audit trail.

To achieve this, Flyway defaults to running scripts in transactions. This means we can easily recover from failed migrations. Rolling back a transaction gives significant confidence that the schema history is accurate, because there should be nothing 'left over' from the bad script.

Of course some statements can't be run inside transactions. Flyway detects such statements and runs those scripts outside of a transaction. Of course this means such scripts are more difficult to recover from if they fail, because the clean-up has to be manual.

As it says [in the docs](https://flywaydb.org/documentation/migrations#transactions):

> By default transactional and non-transactional statements cannot be mixed within a migration run. You can however allow this by setting the mixed property to true

So we attempt to funnel users into creating smaller non-transactional scripts. The mixed mode is really a concession to the fact in the real world things aren't so cut-and-dry.

We require per-script configuration to disable transactions as part of Flyway's opinionated design. We would prefer that you use transactions where possible. However again, in 'real life' things aren't so simple.

Does that clarify things? I appreciate you may want to run most or all scripts non-transactionally. May I ask for more details as to why?

**Comment by LHCGreg** [comment]
It is not that I want to run most scripts non-transactionally, it is that I want explicit control over when a script is run transactionally by putting BEGIN TRANSACTION/COMMIT TRANSACTION inside the script itself, even though it is most of the time. Part of the appeal of SQL-based migration tools like flyway is that the scripts are portable between any tool that can run SQL. When you put "should this script run in a transaction?" outside of the script itself, you lose that. With that said, that's more of a philosophical concern, and letting the migration tool control the transaction does have the benefit that its housekeeping to track what scripts have been run is part of the transaction as well.

The more important topic here is, as the title says, the documentation for the "mixed" config setting is misleading. I am actually more confused than before after reading the documentation you linked to.

Before searching github issues, my (incorrect) understanding was:

No special configuration: All scripts are automatically wrapped in a transaction.
.sql.conf file with executeInTransaction=false: Disables automatic transaction for one script.
flyway.mixed=true: Disables automatic transaction for all scripts.

After searching github issues, my (incorrect?) understanding became:

No special configuration: All scripts are automatically wrapped in a transaction.
.sql.conf file with executeInTransaction=false: Disables automatic transaction for one script.
flyway.mixed=true: flyway attempts to determine whether script contains statements that cannot be executed in a transaction, and if so, disables the automatic transaction.

After a more careful reading of the docs you linked to:

> If Flyway detects that a specific statement cannot be run within a transaction due to technical limitations of your database, it won’t run that migration within a transaction. Instead it will be marked as non-transactional.
> 
> By default transactional and non-transactional statements cannot be mixed within a migration run. You can however allow this by setting the mixed property to true. 

that seems be saying:

No special configuration: flyway attempts to determine whether scripts contain statements that cannot be executed in a transaction, and if so, refuses to run the migration.
.sql.conf file with executeInTransaction=false: Disables automatic transaction for one script.
flyway.mixed=true: flyway attempts to determine whether script contains statements that cannot be executed in a transaction, and if so, disables the automatic transaction.

Is this correct?

**Comment by MikielAgutu** [comment]
Not quite correct. Paraphrasing from the docs:

- By default, Flyway runs each migration within its own transaction
- If Flyway detects that a specific statement cannot be run within a transaction, it won’t run that migration within a transaction
- Transactional and non-transactional statements cannot be mixed within a migration run

So, by default Flyway will refuse to run a migration if it contains both transactional and non-transactional statements. To allow transactional and non-transactional statements inside a single migration run, you can set `mixed` to `true`.

`executeInTransaction` will override Flyway's auto-detection process. It forces the migration to run as specified.

From your first post:

> To me that says that if I turn on the "mixed" setting, flyway will never run a migration in a transaction.

The `mixed` setting doesn't do this. Flyway will still try and put things in transactions if possible.

Does that help?

**Comment by LHCGreg** [comment]
Yes, that is clear.

**Comment by MikielAgutu** [comment]
Excellent! I'll note that we should make our docs clearer.

**Comment by MikielAgutu** [comment]
See https://github.com/flyway/flyway/commit/33b274a3f19065c4a04a447f7a528c4c80a31721
