### ISSUE TITLE
Pass env variables using cli

### ISSUE THREAD

**Issue by gauravluckme** [flyway/flyway#2803]
###### Which version and edition of Flyway are you using?
6.4.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle

###### Which database are you using (type & version)?
MySQL

###### Which operating system are you using?
Windows

###### What did you expect to see?
I have a property set like this:

url=localhost:3206
Is there a way to specifiy this like below instead:

url=${hostname}:3206

**Comment by MikielAgutu** [comment]
Flyway already accepts [environment variables for configuration](https://flywaydb.org/documentation/envvars).

If you really need to do what you've described, it should already be possible by relying on the built-in capabilities of your terminal. For instance, in PowerShell you can do something like this:

```powershell
$url= Get-Variable URL -valueOnly
flyway info -url=$url
```

Does that help?

**Comment by gauravluckme** [comment]
May the issue got misunderstood, I am using below flyway.conf for gradle build:-

flyway.url=jdbc:mysql://localhost:3206/database

But I trying to make it as below by passing the "dbenv" value by gradle cli :-

flyway.url=jdbc:mysql://${dbenv}:3206/database

**Comment by MikielAgutu** [comment]
It's possible to [substitute environment variables in configuration files](https://flywaydb.org/documentation/configfiles#environment-variable-substitution).

[Flyway's Gradle plugin documentation](https://flywaydb.org/documentation/gradle/) also explains more about configuration methods. Does that help?

**Comment by gauravluckme** [comment]
I am passing the below command:-

**gradle -Pflyway.user=myUsr -Pflyway.password=mypass -Pflyway.placeholders.dbenv=locahost**

And trying to get it inside flyway.conf:-

flyway.url=jdbc:mysql://${dbenv}:3206/database

But it throwing error, the variable is not replaced with the value passed as an argument.

**Comment by MikielAgutu** [comment]
The `placeholders` option is only for migration scripts. To replace things in the config file you'll have to set an environment variable.

**Comment by gauravluckme** [comment]
Tried the below:-

**gradle -Pflyway.user=myUsr -Pflyway.password=mypass -Pdbenv=locahost**

Its also not working, please let me know if I assigning it correctly.

**Comment by MikielAgutu** [comment]
The `-P` sets a Gradle property, not a system environment variable. You'll need to depend on other mechanisms to set the environment variable (like the PowerShell example above).

**Comment by gauravluckme** [comment]
Closing the issue, as I am able to perform it by using Gradle project environmental variables.
