### ISSUE TITLE
Command-line add default location 'filesystem:sql'

### ISSUE THREAD

**Issue by qoomon** [flyway/flyway#2805]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.4.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which operating system are you using?
macOs

###### What did you do?
I've installed `flyway` by homebrew `brew install flyway`
Then I execute `flyway migrate -url=... -user=... -password=...` within my project directory.
**project structure**
* project-name
  * sql
  * ...
However I got the error message `WARNING: No migrations found. Are your locations set up correctly?`
This is because the default location `sql` is relative to `flyway` executable.
I need to add following parameter to make it work ` -locations='filesystem:sql'`

###### What did you expect to see?
I would expect that the default lookup location is relative to execution path as basically ever other cli does like maven or gradle.
My suggestion is to add `filesystem:sql` as a default location
or maybe even better `filesystem:migrations`

**Comment by MikielAgutu** [comment]
Fair point, although FYI the [Homebrew package is a third party integration.](https://flywaydb.org/documentation/plugins/) We haven't thought about the setup experience for Homebrew users.

**Comment by qoomon** [comment]
I think in general it is quite common to install executables in some bin directories. And even when in install it manually I'd like to be able to move it to a global directory `/bin` or `/usr/local/bin` or `/usr/bin`. I'd like to use the `flyway` command for every project with its own `sql` or `migrations` folder.

**Comment by qoomon** [comment]
So I would looking forward to have this feature. maybe 3 default locations
* `classpath:sql`(for backward compatibility)
* `filesystem:sql`(for support current folder name)
* `filesystem:migrations`(for a more descriptive folder name)

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
