### ISSUE TITLE
Hi Flyway team , if there is a way we can have flyway output a script instead of executing the commands -  

### ISSUE THREAD

**Issue by Kirannnnn** [flyway/flyway#2809]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Lyeeedar** [comment]
This is a Flyway pro feature, called Dry Run. See more details here: https://flywaydb.org/documentation/dryruns

**Comment by Kirannnnn** [comment]
yes I know that I want for the community edition
