### ISSUE TITLE
DRYRUN output could/should be more verbose.

### ISSUE THREAD

**Issue by seb-urbaniak** [flyway/flyway#2811]
###### Which version and edition of Flyway are you using?
6.4.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
i think so.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CMDline

###### Which database are you using (type & version)?
MSSQL 2017

###### Which operating system are you using?
Win10 x64

###### What did you do?
We had to add PRINT&GO lines everywhere to your DRYRUN output file  (based on the "Source" comment line).
ex:
```
-- Executing: migrate -> dbo.Replicator DYN FLIGHTCODESHARE Put [repeatable] (with callbacks)
-- ---------------------------------------------------------------------------------------
-- Source: sql\StoredProcedures\R__dbo.Replicator_DYN_FLIGHTCODESHARE_Put.sql
```
**PRINT '-- Source: sql\StoredProcedures\R__dbo.Replicator_DYN_FLIGHTCODESHARE_Put.sql';
GO**
```
-- ---------------------------------------------------------------------------
SET ANSI_NULLS ON
```

###### What did you expect to see?
Would be nice if the DRYRUN output was more verbose to begin with.  Perhaps as a config switch ,  you could add those exact PRINTs that we did by hand ?

###### What did you see instead?
As described above.
The motivation behind all this is,  that when executing the DRYRUN output in PROD ENV,  where we can't just run Flyway from CMDline,  it is  next to impossible to tell what the  multi megabyte script is doing and where it's at (at any given time).

**Comment by MikielAgutu** [comment]
Could you give more examples of the sort of output you'd like to see?

**Comment by seb-urbaniak** [comment]
The PRINT that i put in bold above would be all that is needed.   Just to  give the user indication what currently is being executed  ,  particularly for those long-running V scripts.

**Comment by MikielAgutu** [comment]
We think this isn't the right thing. It would involve making the dry run script different to your migrations, which isn't the way we want this feature to work.
