### ISSUE TITLE
ORA-32794: cannot drop a system-generated sequence when running as other user.

### ISSUE THREAD

**Issue by lwasylow** [flyway/flyway#2816]
###### Which version and edition of Flyway are you using?
Flyway Enterprise Edition (unlimited schemas) 6.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Redgate Change Automation

###### Which database are you using (type & version)?
Oracle 19.6 , pluggable

###### Which operating system are you using?
NAME="Oracle Linux Server"
VERSION="7.6"
ID="ol"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
CPE_NAME="cpe:/o:oracle:linux:7:6:server"
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Oracle Linux Server release 7.6

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Created a super user bg_deploy , granted to it connect and dba role that will be deployment user.
My deploy schemas are defined as follow:
flyway.schemas=OPS_DATA,OPS_DATA_API,OPS_DATA_ETL
flyway.table=DB_OPS_SCHEMA_HISTORY

I've created a table with identity column
e.g.
CREATE TABLE ops_data.test_table(
  build_number NUMBER,
  release_code NUMBER,
  run_date DATE,
  file_content BLOB,
  content_type VARCHAR2(50 BYTE),
  file_name VARCHAR2(250 BYTE),
  build_type VARCHAR2(100 BYTE),
  "ID" NUMBER GENERATED AS IDENTITY,
  log_seen VARCHAR2(1 BYTE) DEFAULT 0 NOT NULL
);

run `clean`

###### What did you expect to see?
I expected to task `clean` run succesfully.

###### What did you see instead?
when running a `clean` on database I got an error:
```bash
[flyway] Flyway Enterprise Edition (unlimited schemas) 6.4.1 by Redgate licensed to Redgate until 2020-07-01
[flyway] Database: jdbc:oracle:thin:@//ora-d-vmdb01.ad.bailliegifford.com:1521/DEV100_REL_CD.WORLD (Oracle 19.0)
[flyway] Successfully dropped pre-schema database level objects (execution time 00:00.002s)
[flyway] ERROR: 
[flyway] Unable to clean schema "OPS_DATA"
[flyway] ---------------------------------
[flyway] SQL State  : 99999
[flyway] Error Code : 32794
[flyway] Message    : ORA-32794: cannot drop a system-generated sequence
[flyway] 
[flyway] flyway exited with code 1
```

This is possible due to fact that deploy user cant see the object in its recycle bin for sequence.
Running a 
```sql
purge recyclebin
```
doesnt help however when run 
```sql
PURGE DBA_RECYCLEBIN
```
this solves the issue until next deployment.

**Comment by juliahayward** [comment]
I'm not currently able to reproduce - would you be able to script out the creation of the relevant users and permissions?

**Comment by lwasylow** [comment]
Hi Please see also steps to create db.

```sql
create pluggable database DBXX admin user admin identified by "Password" CREATE_FILE_DEST='LOCATION';
alter pluggable database DBXX open;
alter pluggable database DBXX save_state;
alter session set container=DBXX;
create bigfile tablespace data;
create user deploy_user identified by "Password" default tablespace data;
grant dba to deploy_user;
grant unlimited tablespace to deploy_user;
grant create session to deploy_user;
grant connect to deploy_user;
CREATE USER ops_data NO AUTHENTICATION DEFAULT TABLESPACE DATA;
CREATE USER ops_data_api Identified by "Password" DEFAULT TABLESPACE DATA;
CREATE USER ops_data_etl identified by "Password" DEFAULT TABLESPACE DATA;
ALTER USER ops_data QUOTA UNLIMITED ON DATA;
ALTER USER ops_data_api QUOTA UNLIMITED ON DATA;
ALTER USER ops_data_etl QUOTA UNLIMITED ON DATA;
grant create session,connect to ops_data_api;
grant create session,connect to ops_data_etl;
```

with config of flyway:

```
flyway.schemas=OPS_DATA,OPS_DATA_API,OPS_DATA_ETL
flyway.table=DB_OPS_SCHEMA_HISTORY
```

**Comment by DoodleBobBuffPants** [comment]
Closing as possibly no longer relevant
