### ISSUE TITLE
Improve Exception and Error Handling in the Java API

### ISSUE THREAD

**Issue by JeanRev** [flyway/flyway#2820]
On current master (Flyway 6.4.2)

Currently, the [FlywayException](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/api/FlywayException.java) has a few Subclasses, which are only partly documented, and it's not always clear which exception relates to which problem. For example: what if I'm only interested in schema validation failures, but I don't want to catch connectivity issues? 

Moreover, [ErrorCode](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/api/ErrorCode.java)s should be documented with Javadoc in the Java API. A user can right now only try to guess what the codes mean according to their name, which isn't always straightforward. For example, what's the difference between FAULT and ERROR?

**Comment by MikielAgutu** [comment]
Related to https://github.com/flyway/flyway/issues/2948

**Comment by Lyeeedar** [comment]
We did a revamp of the exception handling and error codes in https://github.com/flyway/flyway/commit/39197c36943fc11390fe8036d35438d1bd5c5561
