### ISSUE TITLE
Provide a way to use a custom ResourceProvider

### ISSUE THREAD

**Issue by geoand** [flyway/flyway#2822]
Hey folks,

In [Quarkus](https://quarkus.io/) we have a Flyway [extension](https://quarkus.io/guides/flyway) that is configured with the locations to the migration scripts at **build** time. 
The locations **cannot** be changed at runtime, meaning that the locations are always known to us at build time thus, making runtime classpath scanning for them redundant (at best).

I looked at the code in order to see if we could configure Flyway to use a custom `ResourceProvider` (which Quarkus would setup with the proper locations), but short of sub-classing `Flyway` and overriding `execute`, I didn't see any way of doing so.

It would be great for us if such a configuration point were possible.
WDYT? If you like the idea, I can provide a PR using whatever design you think it best.

Thanks!

**Comment by gastaldi** [comment]
One possible solution is to add `ResourceProvider` and `ClassProvider<JavaMigration>` to the `Configuration` that is passed to the `Flyway` constructor then it can be injected here:

https://github.com/flyway/flyway/blob/744f85d3585adc90bc5d55c730b122fc93074145/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L429-L449

**Comment by geoand** [comment]
That's what I had in mind as well

**Comment by gastaldi** [comment]
Or maybe not, since they belong to the internal API(`org.flywaydb.core.internal.resource` and `org.flywaydb.core.internal.clazz` respectively)

**Comment by Lyeeedar** [comment]
Thank you for suggesting this, we will be considering this when we decide what we want to do in Flyway 7 and beyond. In the mean time we would welcome a pull request.

**Comment by geoand** [comment]
Thanks @Lyeeedar.

I'll come up with something this week hopefully

**Comment by geoand** [comment]
Took a quick look, but like @gastaldi said above the interfaces of interest are in the `internal` package which I pressume we wan't to keep out of the `Configuration` class and / or `Flyway` method signatures.

I could make something like `doExecute` which takes a `Scanner` and does all the work. In our integration we would subclass Flyway, override `execute` and call `doExecute` with our own `Scanner`. 
I am a little reluctant to do that because `execute` is supposed to be private according to the comments. WDYT?

**Comment by Lyeeedar** [comment]
We aren't against modifying the classes in internal to expose things like this, and often community submissions that do modify them reveal improvements to the internals we can perform. So please feel free to do the changes you need to do to make it work, whatever changes those might be. It is just that the more internal things you touch, the more care we will take before deciding if we want to merge it in.

**Comment by geoand** [comment]
Understood, thanks!

I'll work on a PR soon and let you know.

**Comment by KPhi** [comment]
We're trying to get a `ResourceProvider` running in an OSGi environment. However, we are encountering issues with implementing the interface, as the class `org.flywaydb.core.internal.resource.LoadableResource` referenced in the public signature is not exported via the library's MANIFEST.MF file.
```
Access restriction: The type 'LoadableResource' is not API (restriction on required library 'org.flywaydb.core_6.5.1.jar')
```

In theory, we could implement the interface in the `org.flywaydb.core`, put it into a dedicated bundle and attach it as a fragment to the library. Then we would need to have the ability to reference the class as a string, which is possible for the `FluentConfiguration.resolvers()` method but not implemented for `FluentConfiguration.resourceProvider()`.
Does someone have an example on how we can get this to work in OSGi?
