### ISSUE TITLE
Flyway repair command updates wrong migration row's description in the FLYWAY_SCHEMA_HISTORY table

### ISSUE THREAD

**Issue by zjwu2000** [flyway/flyway#2823]
###### Which version and edition of Flyway are you using?
Version 6.3.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Snowflake 4.16

###### Which operating system are you using?
Windows 10 Enterprise

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Run "flyway repair" after run migration

###### What did you expect to see?

After run the Flyway migration successfully, the Flyway repair command should not repair anything.

###### What did you see instead?
The Flyway repair command try to repair the repeatable migration rows in the FLYWAY_SCHEMA_HISTORY table because they has NULL value in ‘Version’ column, which it should not do that because repeatable migration rows always have NULL value in ‘Version’ column. This issue I already reported in issue #2821.

Here I want to report a second issue: the repair command updates wrong migration row's description column in the FLYWAY_SCHEMA_HISTORY table.
Please see the attached document to see the detail steps I did to trigger this issue.
[Flyway_6.3.0_repair_issue.docx](https://github.com/flyway/flyway/files/4660076/Flyway_6.3.0_repair_issue.docx)

**Comment by juliahayward** [comment]
This is indeed a bug in Repair - it's not that the descriptions of the versioned/repeatable match, but the checksums. Obviously not often reproducible as checksum clashes are intentionally unusual (unless V/R scripts are identical). Will be fixed in the next patch release.

**Comment by Lyeeedar** [comment]
Fixed by https://github.com/flyway/flyway/commit/95dbab86728e4d0532a5e0705ba69734463e01c9
