### ISSUE TITLE
Plugin to Preresolve Migrations

### ISSUE THREAD

**Issue by RyanHoldren** [flyway/flyway#2824]
I run `Flyway.migrate()` time my application starts. During development, my application is restarting all the time. Because I have so many migrations at this point, Flyway takes around 10 seconds to do it's thing. I am assuming that most of the work is scanning for SQL files and computing checksums, since 99% of the time the database is already up to date. It would nice nice if there was a Gradle and/or Maven plugin that I could add to my project to resolve my migrations at compile time so that Flyway could migrate faster.

**Comment by MikielAgutu** [comment]
Related to https://github.com/flyway/flyway/issues/2822

**Comment by Lyeeedar** [comment]
As of https://flywaydb.org/documentation/releaseNotes#6.5.0 you can now provide your own ResourceProvider, so you can implement this yourself when using the api.
