### ISSUE TITLE
Can't log in 'as sysdba' for any sysdba user other than SYS 

### ISSUE THREAD

**Issue by jaa2261** [flyway/flyway#2825]
###### Which version and edition of Flyway are you using?
6.4.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle

###### Which database are you using (type & version)?
Oracle 19c 19.2

###### Which operating system are you using?
Linux OEL 7.8

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
We don't want to use the default SYS user so we cloned it and created FLYWAY_USER with exactly the same roles and privileges as SYS. The intention is to reduce the privileges to the bare minimum in the future.

Gradle plugin works fine when user is SYS e.g.
flyway {
       user = 'SYS as SYSDBA'
}

but when we set

flyway {
       user = FLYWAY_USER as SYSDBA'
}

it fails to connect. We can connect as FLYWAY_USER as SYSDBA via sqlplus and sqldeveloper with no issues.
Does Flyway only support using the SYS user?

###### What did you expect to see?
 We would expect the FLYWAY_USER to connect and perform the migration just like the SYS user. 

###### What did you see instead?
Flyway fails to connect to the database to start the migration. We get the following error:

Error occurred while executing flywayClean
 
Unable to obtain connection from database (jdbc:oracle:thin:@//xxx.com:1521/service.com) for user 'FLYWAY_USER as SYSDBA': ORA-01017: invalid username/password; logon denied

**Comment by juliahayward** [comment]
There's nothing special in Flyway about the SYS user. It appears to be a property of the Oracle JDBC driver: see https://stackoverflow.com/questions/10101517/how-to-connect-in-java-as-sys-to-oracle

```
"If you want to connect your database with user other than "sys" as "sysdba" then you have to change the driver from "thin" to "oci" to make the successful connection."
```

**Comment by jaa2261** [comment]
That would explain it. 
We've worked around it by creating the non sysdba user with a role that has all the required grants with admin options set.
