### ISSUE TITLE
Cannot create "concurrent" index on TimescaleDB

### ISSUE THREAD

**Issue by cloudpaul** [flyway/flyway#2826]
###### Which version and edition of Flyway are you using?

6.4.2 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I believe that this is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

TimescaleDB extension to PostgreSQL 12
TimescaleDB version is 1.7

###### Which operating system are you using?
Windows 10 Pro

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I have an SQL migration (the only migration) where I create tables, hypertables and indexes.
TimescaleDB does not support CREATE INDEX CONCURRENTLY and we must use this form as an alternative

    CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
    
    CREATE TABLE BEAM_SAMPLED_DATA(
        ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
        CREATION_TIME TIMESTAMPTZ NOT NULL,
    
        DATA_START_TIME BIGINT NOT NULL,
        NUMBER_OF_DATA_POINTS INTEGER  NOT NULL,
        NUMBER_OF_DATA_SAMPLES INTEGER  NOT NULL,
        SENSOR_SOURCE VARCHAR(32)  NOT NULL,
        SENSOR_POSITION INTEGER  NOT NULL,
    
        DATA_SAMPLE_POINTS REAL[] NOT NULL,  
        DATA_POINT_OFFSET REAL[] NOT NULL);
    
    SELECT create_hypertable('BEAM_SAMPLED_DATA', 'creation_time');
    SELECT set_chunk_time_interval('BEAM_SAMPLED_DATA', 60000000);
     
    CREATE INDEX IDX_BEAM_SAMPLED_DATA ON BEAM_SAMPLED_DATA(CREATION_TIME ASC, DATA_START_TIME) WITH (timescaledb.transaction_per_chunk);

See https://docs.timescale.com/latest/api#create_index

I run Flyway like this

            MigrationVersion baselineVersion = MigrationVersion.fromVersion(BASELINE_VERSION);          
            Flyway flyway = Flyway.configure()
                                    .baselineVersion(baselineVersion)
                                    .baselineOnMigrate(true)
                                    .dataSource(dataSource)
                                    .outOfOrder(true)
                                    .locations("classpath:postgres/migration")
                                    .mixed(true)
                                    .load();
            flyway.migrate();

###### What did you expect to see?

The migration should have completed successfully

###### What did you see instead?
When this is run by Flyway the following exception is logged

Caused by: org.postgresql.util.PSQLException: ERROR: CREATE INDEX ... WITH (timescaledb.transaction_per_chunk) cannot run inside a transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:244)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:208)

It's worth noting that CREATE INDEX WITH is not included in the non-transactional statement checks
(I noticed on https://stackoverflow.com/questions/20350501/how-do-i-create-indexes-concurrently-with-flyway-in-postgres)

    if (statementStart.matches("(CREATE|DROP) (DATABASE|TABLESPACE) .*")
        || statementStart.matches("ALTER SYSTEM .*")
        || statementStart.matches("(CREATE|DROP)( UNIQUE)? INDEX CONCURRENTLY .*")
        || statementStart.matches("REINDEX( VERBOSE)? (SCHEMA|DATABASE|SYSTEM) .*")
        || statementStart.matches("VACUUM .*")
        || statementStart.matches("DISCARD ALL .*")
        || statementStart.matches("ALTER TYPE .* ADD VALUE .*")
        ) {
        executeInTransaction = false;
    }

**Comment by Lyeeedar** [comment]
You can actually control whether a migration can execute in a transaction on a migration by migration basis, using a [script config file](https://flywaydb.org/documentation/scriptconfigfiles). Could you try that and see if it works?

If you are using Java migrations you can instead override canExecuteInTransaction. See [java migrations](https://flywaydb.org/documentation/migrations#manual-override).

**Comment by cloudpaul** [comment]
The script config file works, thank you

**Comment by Jolley71717** [comment]
@Lyeeedar, Since you provided a workaround instead of an actual fix, shouldn't this gitlab issue still be open?

Wouldn't a fix include the addition of the necessary filter in the non-transactional statement checks?
