### ISSUE TITLE
I have 20 migration files in sql folder but without removing any file I want to start migration from 11th file.Can we mention the start version of file in flyway

### ISSUE THREAD

**Issue by Kirannnnn** [flyway/flyway#2830]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by MikielAgutu** [comment]
The Baseline command could help you here. [From the docs](https://flywaydb.org/documentation/command/baseline):

> Baselines an existing database, excluding all migrations up to and including baselineVersion.

You can set the `baselineVersion` configuration option to `10`, and then run Baseline. This will tell Flyway to exclude all migrations up to and including version 10 on that database. Then you can run migrate as normal, and only migrations above version 10 will be executed.

Note Baseline only works on databases without a schema history table. Does that help?

**Comment by MikielAgutu** [comment]
@Kirannnnn Any news? Did it work?

**Comment by MikielAgutu** [comment]
Closing for lack of response.
