### ISSUE TITLE
flyway validate with the flyway timestamp in a repeatable file

### ISSUE THREAD

**Issue by asollberger** [flyway/flyway#2836]
###### Which version and edition of Flyway are you using?
6.4.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command line and maven plugin

###### Which database are you using (type & version)?
Oracle 18c

###### Which operating system are you using?
macOS, Linux and Windows 10

###### What did you do?
I tried to use the the new feature of the timestamps:
https://flywaydb.org/blog/flyway-timestampsAndRepeatables

R__create_error_tables.sql
`
-- ${flyway:timestamp}
begin
   dbms_errlog.create_error_log('MY_TABLE');
end;
/
`

We have a jenkins job that runs the whole deployment:
- flyway info
- flyway migrate
- flyway validate

The validate now throws an error because there is always a new timestamp that it sees.

###### What did you expect to see?

I was hoping that the validation would at most give a warning about pending changes because of a new timestamp, but not an error. This way validate will never succeed.

I wouldn't have a problem with setting a flag to ignore flyway timestamp, but I'd need something to not get an error from the validate

###### What did you see instead?
I got an error from the validate.

**Comment by Lyeeedar** [comment]
What purpose does the validate after calling migrate serve? If migrate succeeded without errors, then that means its applied all the local migrations to the database exactly as they exist on disk, which is the same thing that validate is checking.

Validate mainly has a use when being run before, or seperately from, migrate. As such I'm wondering if it would be best to simply remove the flyway validate from the jenkins job?

**Comment by asollberger** [comment]
I see your point concerning our jenkins job, we could remove the validate in the end and it would be just fine (I'd have to convince our devOps team of it).

But that does not solve the issue that with the flyway timestamp in a file, validate basically is unusable from that point forward. It never returns anything valid anymore. There's always an error.

❱ mvn flyway:validate
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< com.rj.cob.database:flyway-oracledb >-----------------
[INFO] Building Flyway Oracle Database SQL 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- flyway-maven-plugin:6.4.2:validate (default-cli) @ flyway-oracledb ---
[INFO] Flyway Community Edition 6.4.2 by Redgate
[INFO] Database: jdbc:oracle:thin:@//localhost:1521/XEPDB1 (Oracle 18.0)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.495 s
[INFO] Finished at: 2020-05-29T09:31:27-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:6.4.2:validate (default-cli) on project flyway-oracledb: org.flywaydb.core.api.FlywayException: Validate failed:
[ERROR] Detected outdated resolved repeatable migration that should be re-applied to database: create error tables
[ERROR] Detected resolved repeatable migration not applied to database: create error tables
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Lyeeedar** [comment]
I can see the issue, but at the same time it is working exactly as intended. Flyway validate is used to check if the migrations you have on disk match whats been applied to the database. If you use the timestamp migration this will never be the case, so we want validate to fail every time.

Yes this is not ideal in this case, but adding some special handling to ignore certain placeholder changes depending on if the checksum is being calculated by validate vs by info/migrate/repair would require reworking how validate is designed internally.

The interaction between timestamp and validate will need some thought, and I will leave this issue open so people can comment and provide feedback on what they would want from it.

**Comment by asollberger** [comment]
> Flyway validate is used to check if the migrations you have on disk match what's been applied to the database

I agree with that, I just don't really agree that the validation of a file with the timestamp always fails.

I'm assuming you're comparing the resolved state of the template with either a new resolved state or just the template code:
```sql
-- ${flyway:timestamp}
```
vs
```sql
-- 2020-03-21T12:31:45
```
or vs an new resolved timestamp
```sql
-- 2020-03-21T12:31:48
```

In the mean time I'm using your afterMigration scripts to do the same, which in my opinion works better than the timestamp possibility.

I have several of them with different names:
```sql
afterMigrate__create_error_tables.sql
afterMigrate__create_audit_tables.sql
afterMigrate__grants.sql
```
That seems to work just fine. The downside of this approach is that I have no possibility to order them ... just like the repeatable files. Unless you know of a way to establish an order of the after migrate scripts (I understand I can put it all into the same file).

If validate does not raise an error anymore I might switch again.

**Comment by Lyeeedar** [comment]
Ordering of Callbacks (such as afterMigration) is defined according to [documentation](https://flywaydb.org/documentation/callbacks#callback-ordering) this way:

> When multiple callbacks for the same event are found, they are executed in the following order:
> 
> Java callbacks, in the order in which they are specified in the callbacks configuration property
> SQL callbacks, in alphabetic order of their description.

**Comment by Lyeeedar** [comment]
Just an update. In Flyway v7 we will be executing callbacks in alphabetical order (interleaving java and sql ones). This will allow you to configure the callback execution order by constructing their names so they sort into the order you desire 

e.g. 
```
afterMigrate__001_create_error_tables.sql
afterMigrate__002_create_audit_tables.sql
afterMigrate__003_grants.sql
```

**Comment by MikielAgutu** [comment]
This is working as intended.
