### ISSUE TITLE
Unable to specify config property using standard input

### ISSUE THREAD

**Issue by intacctvaler** [flyway/flyway#2837]
###### Which version and edition of Flyway are you using?
I'm using version 6.4.3 community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
It is the latest version as of now

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Any

###### Which operating system are you using?
CentOS 6, linux-64bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I am trying to pass the config options to flyway using the standard input as documented here:
https://flywaydb.org/documentation/commandline/#configuration-from-standard-input

###### What did you expect to see?

I expected to see that flyway attempted to use the given configuration options. - see the output below when I use the same options in a configuration file.

###### What did you see instead?

$ echo $'flyway.url=jdbc:h2:mem:mydb\nflyway.user=sa\nflyway.password=blah' | ~/flyway/flyway info
Flyway Community Edition 6.4.3 by Redgate
ERROR: Unable to connect to the database. Configure the url, user and password!

If I pipe those options to a temp config file and invoke flyway with that config file, the options are working:

$ echo $'flyway.url=jdbc:h2:mem:mydb\nflyway.user=sa\nflyway.password=blah' > /tmp/flyway.conf
$ ~/flyway/flyway -configFiles=/tmp/flyway.conf info
Flyway Community Edition 6.4.3 by Redgate
Database: jdbc:h2:mem:mydb (H2 1.4)
Schema version: << Empty Schema >>

+----------+---------+-------------+------+--------------+-------+
| Category | Version | Description | Type | Installed On | State |
+----------+---------+-------------+------+--------------+-------+
| No migrations found                                            |
+----------+---------+-------------+------+--------------+-------+

**Comment by juliahayward** [comment]
Fixed in 6.4.4
