### ISSUE TITLE
flyway: SQL SERVER: Unable to USE DDL and DML in same migration

### ISSUE THREAD

**Issue by brightlord108** [flyway/flyway#2839]
###### Which version and edition of Flyway are you using?
Flyway 6.4.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
even with flyway 6.4.3 I am unable to use ddl and dml in same migration for sql server

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
SQL SERVER 2016

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway: SQL SERVER: Unable to USE DDL and DML (create table) in same migration, the dml insert statement always shows Invalid column name, 
DDL - Create table
DML - Insert statement 
Both in same migration sql file
Even when I use Begin Transaction and Commit Transaction for creating a table, the insert statement fails saying Invalid column name.

###### What did you expect to see?
DDL and DML should execute successfully in the same migration

###### What did you see instead?
SQL State  : S0001
Error Code : 207
Message    : Invalid column name 'column name'

**Comment by juliahayward** [comment]
There's no reason why you can't mix DDL and DML. Could you share the script you're running? (If not, you could mail to support@flywaydb.org)

**Comment by brightlord108** [comment]
Hi Juliahayward, 

Please find the below script which i am trying to run from fylway

USE [TEST_DB]
GO


delete from tablea where columna= 15 

CREATE TABLE [dbo].test_type(
	TYPE_ID [int] NOT NULL,
	DESCRIPTION [varchar](32) NULL,	
 CONSTRAINT [T_TYPE_PK] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

Insert into test_type
   (TYPE_ID, DESCRIPTION)
Values
   (1, 'FUNCATIONAL');
Insert into test_type
   (TYPE_ID, DESCRIPTION)
Values
   (2, 'REGRESSION');
   
ALTER TABLE COLUMN_B
        ADD TYPE_ID VARCHAR(16) NULL --Or NOT NULL. 
    DEFAULT (1)--Optional Default-Constraint.
WITH VALUES;

UPDATE COLUMN_B set TYPE_ID=TYPE_ID+','+'2' Where column_id=3;
GO

**Comment by brightlord108** [comment]
Closing the issue, there seems to be something else going on. Sorry.
