### ISSUE TITLE
Not respecting jdbc args?

### ISSUE THREAD

**Issue by psylinse** [flyway/flyway#2840]
###### Which version and edition of Flyway are you using?
Flyway gradle plugin: 6.4.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using (type & version)?
Postgres 12

###### Which operating system are you using?
MacOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I ran `./gradlew -Dflyway.configFiles=config.flyway flywayMigrate`

with a config file that looks like :

```
flyway.url=jdbc:postgresql://127.0.0.1:5432/db_name?ssl=true&sslmode=verify-ca&sslrootcert=/path/to/server-ca.pem&sslkey=/path/to/client-key.pem&sslcert=/path/to/client-cert.pem
flyway.user=postgres
flyway.password=redacted

```

###### What did you expect to see?
A successful migration

###### What did you see instead?
```
 SQL State  : 28000
  Error Code : 0
  Message    : FATAL: connection requires a valid client certificate
  
  FATAL: connection requires a valid client certificate
```

I have confirmed that I can connect via psql or DataGrip with these files. With DataGrip I can copy paste that jdbc url and it works great. I'm not entirely convinced this is due to something in flyway, but I can't seem to reproduce this outside of flyway. Any ideas is flyway messes with/doesn't understand jdbc URLs?

Is there a better way to configure SSL with custom certs?

**Comment by MikielAgutu** [comment]
You may need to set some JVM properties, as [detailed on this page](https://jdbc.postgresql.org/documentation/head/ssl-client.html). Like `javax.net.ssl.trustStore`, and `javax.net.ssl.trustStorePassword`.

**Comment by psylinse** [comment]
I did try that and it made no difference. I also attempted converting the .pem key to .der per this article: https://jdbc.postgresql.org/documentation/head/connect.html.

I also tried a custom keystore and `-cacerts` via gradle.properties:

```
org.gradle.jvmargs=-Djavax.net.ssl.trustStore=/path/to/mystore -Djavax.net.ssl.trustStorePassword=changeit
```

It's strange that it works with the exact same URL through DataGrip. I'm not sure if they're doing anything different IRT how it connects via JDBC. 

For more info, I'm using a google cloud sql postgres database and turning on SSL required. I'm pretty stumped.

**Comment by MikielAgutu** [comment]
Could you run Flyway with debug logging? You'll need to put a logger on the classpath that derives from `org.apache.commons.logging.Log` or `org.slf4j.Logger`. [See the docs ](https://flywaydb.org/documentation/commandline/#output)(docs page is for command line but the principle is the same). Or you could try the CLI and run using `-X` flag,

Any extra information is helpful. We'll continue to investigate.

**Comment by psylinse** [comment]
Sorry, haven't been able to look at this and we found a work around for now. Will be able to look at this in a few weeks.

**Comment by Lyeeedar** [comment]
Have you had time to look at this yet?

**Comment by psylinse** [comment]
No, I probably won't at this point. We moved on to using https://cloud.google.com/sql/docs/postgres/sql-proxy. Sorry I can't help further, feel free to close this if it's clutter at this point.

**Comment by cyrbil** [comment]
Just as information for the wanderers that could stumble on this issue:

To succesfully use `JDBC` arguments:
- Certificates (`root` and `client`) should be in `X509+PEM` format
- Certificates can have _any_ extension (tested with `pem` and `crt`) 
- Certificates should be readable (duh!)
- Private key should be in `pk8` format
- Private key should end with extension `.pk8`
- Private key should be owner read only (`chmod 600 # or 400`)
- The default should not exist (ie: for `postgresql`, `$HOME/.postgresql/{postgresql.crt,postgresql.pk8,root.crt}` should not exist)

**Comment by nat-ser** [comment]
For anyone struggling with this, @cyrbil is on point. I want to add a specific example of what worked for me applying his comment.

On Mac, `jdbc` driver. My original client key is `.pem` and the certs are `.crt`
```
chmod 0600 $PGSSL_SERVER_CERT_PATH

# convert key to PK8+DER format
openssl pkcs8 -topk8 -inform PEM -outform DER -in $PGSSL_CLIENT_KEY_PATH -out client_key.pk8 -nocrypt
FORMATTED_KEY=client_key.pk8

flyway -locations="filesystem:/seismic/webhook/sql/flyway_revisions/webhook" -url="jdbc:postgresql://${PGHOST}/${PGDATABASE}?sslmode=verify-ca" -jdbcProperties.sslcert=${PGSSL_CLIENT_CERT_PATH} -jdbcProperties.sslrootcert=${PGSSL_SERVER_CERT_PATH} -jdbcProperties.sslkey=client_key.pk8 -user=$PGUSER -password=$PGPASSWORD info
```
Above also works with the jdbc properties passed as params in the url, like @bit-void was doing
