### ISSUE TITLE
Writing multiple procedure/udfs for a Snowflake is throwing errors during migrate

### ISSUE THREAD

**Issue by srjonemed** [flyway/flyway#2843]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.2.0 by Redgate
snowflake-jdbc-3.12.0.jar

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Snowflake 4.18.1

###### Which operating system are you using?
macOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Created a new repeatable migration file, to create a set of related procedures and UDFs. However, when I run the command line migrate command, it fails with error.
If I edit the file to contain only ONE procedure or UDF then the migrate works.
 
###### What did you expect to see?
Expecting to be able to run the migrate successfully with multiple procedures and udfs in a single file.

###### What did you see instead? 
Error Message - 

```
Migration R__auth_view_procs.sql failed
-----------------------------------------------------------
SQL State  : 0A000
Error Code : 8
Message    : Actual statement count 2 did not match the desired statement count 1.
```

Also, tried the same using a Versioned sql file but results in same error message.

**Comment by juliahayward** [comment]
Would you be able to share the script with us? If not in public then by email to support@flywaydb.org .

**Comment by srjonemed** [comment]
You could use the following test content as the content of the script:

/* script begins */
create or replace procedure tst_exec_owner_proc()
  returns VARCHAR
  language javascript
  as
  $$
  // Set the second session variable
  var stmt = snowflake.createStatement(
      {sqlText: "select CURRENT_ROLE();"}
      );
  var rs = stmt.execute();
  rs.next();

  return rs.getColumnValue(1);
  $$
  ;

create or replace function tst_exec_owner_func()
  returns VARCHAR
  as
  $$
  select current_role()
  $$;

/* script ends */

**Comment by juliahayward** [comment]
That's great, thankyou. I will investigate and get back to you!

**Comment by juliahayward** [comment]
Many thanks; I can reproduce and a fix will be in the next patch version.

**Comment by srjonemed** [comment]
Thats great! appreciate the quick response on this..

**Comment by srjonemed** [comment]
@juliahayward thanks again for putting in the fix. could you please let me know when 6.4.4 would be available for downloads?

**Comment by juliahayward** [comment]
It should be in the next couple of days, all being well.

**Comment by srjonemed** [comment]
Thanks!

**Comment by smsdatabase** [comment]
One workaround is to substitute $$ with ' (singe quote)
