### ISSUE TITLE
the value NULL into column 'installed_on' After migrate from mysql to mssql 

### ISSUE THREAD

**Issue by azizkhani** [flyway/flyway#2857]
###### Which version and edition of Flyway are you using?
5.24

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
spring boot

###### Which database are you using (type & version)?
ms sqlserver

###### Which operating system are you using?
mac 

###### What did you do?
`Cannot insert the value NULL into column 'installed_on', table 'dbo.schema_version'; column does not allow nulls. INSERT fails.`

**Comment by MikielAgutu** [comment]
That's a fairly old version of Flyway. Could you try with the latest version?

**Comment by Lyeeedar** [comment]
Have you had a chance to try this with the latest version?
