### ISSUE TITLE
Migrations in sqlite returns no error but it doesn't do anything

### ISSUE THREAD

**Issue by po5i** [flyway/flyway#2858]
###### Which version and edition of Flyway are you using?
6.4.4 (latest as today)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle Plugin

###### Which database are you using (type & version)?
Sqlite 3.28.0 
org.xerial:sqlite-jdbc:3.28.0

###### Which operating system are you using?
macOS Catalina 10.15.4 (19E287)
Java info:
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

###### What did you do?
I replaced postgres with sqlite on a legacy Spark project with Gradle. Everything works well (app and tests) if I create the database and run [SQL](https://github.com/TwilioDevEd/browser-calls-spark/blob/next/src/main/resources/db/migration/V1__Create_ticket_table.sql) from migrations manually using a 3rd. party db client. The issue here is `flywayMigrate` command is not returning errors as if it ran correctly. But no database was created anywhere. Even if I created an empty file with the same name, it doesn't apply migrations on it.

Repo: https://github.com/TwilioDevEd/browser-calls-spark/tree/next
Note: Make sure you are on the `next` branch.

Easy to reproduce: 
1. Just clone, check out that branch
1. `source .env.example` you don't need the rest of the variables.
1. Execute the migration command `./gradle flywayMigrate`.

As a workaround, I had to create the DB [manually](https://github.com/TwilioDevEd/browser-calls-spark/blob/next/.github/workflows/gradle.yml#L35) using sqlite3 CLI so CI can pass.

###### What did you expect to see?
- Creating of the mydb.db file
- Migrations run on that file

###### What did you see instead?
```
❱ ./gradlew flywayMigrate -i
.
.
.
> Task :flywayMigrate
Caching disabled for task ':flywayMigrate' because:
  Build cache is disabled
Task ':flywayMigrate' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Database: jdbc:sqlite:mydb.db (SQLite 3.28)
Successfully validated 1 migration (execution time 00:00.000s)
Creating Schema History table "main"."flyway_schema_history" ...
Current version of schema "main": << Empty Schema >>
Migrating schema "main" to version 1 - Create ticket table
Successfully applied 1 migration to schema "main" (execution time 00:00.004s)
:flywayMigrate (Thread[Execution worker for ':',5,main]) completed. Took 0.246 secs.

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

But no `mydb.db` file is created anywhere on the project.

```
❱ ./gradlew flywayInfo      

> Task :flywayInfo
Schema version: 1
+-----------+---------+---------------------+------+---------------------+---------+
| Category  | Version | Description         | Type | Installed On        | State   |
+-----------+---------+---------------------+------+---------------------+---------+
| Versioned | 1       | Create ticket table | SQL  | 2020-06-17 21:04:22 | Success |
+-----------+---------+---------------------+------+---------------------+---------+


BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

**Comment by MikielAgutu** [comment]
Given the output you've provided it looks as if the database is being created. Perhaps it hasn't been created in the place you expected?

Could you try using an absolute path in your SQLite JDBC driver to confirm?

**Comment by po5i** [comment]
```
> Task :flywayInfo
Caching disabled for task ':flywayInfo' because:
  Build cache is disabled
Task ':flywayInfo' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Database: jdbc:sqlite:/Users/cvillavicencio/Code/TwilioDevEd/browser-calls-spark/mydb.db (SQLite 3.30)
Schema version: << Empty Schema >>
+-----------+---------+---------------------+------+--------------+---------+
| Category  | Version | Description         | Type | Installed On | State   |
+-----------+---------+---------------------+------+--------------+---------+
| Versioned | 1       | Create ticket table | SQL  |              | Pending |
+-----------+---------+---------------------+------+--------------+---------+

:flywayInfo (Thread[Execution worker for ':',5,main]) completed. Took 0.541 secs.
```

Then

```
> Task :flywayMigrate
Caching disabled for task ':flywayMigrate' because:
  Build cache is disabled
Task ':flywayMigrate' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Database: jdbc:sqlite:/Users/cvillavicencio/Code/TwilioDevEd/browser-calls-spark/mydb.db (SQLite 3.30)
Successfully validated 1 migration (execution time 00:00.000s)
Creating Schema History table "main"."flyway_schema_history" ...
Current version of schema "main": << Empty Schema >>
Migrating schema "main" to version 1 - Create ticket table
Successfully applied 1 migration to schema "main" (execution time 00:00.008s)
:flywayMigrate (Thread[Execution worker for ':',5,main]) completed. Took 0.336 secs.
```

And everything is successful now. The mydb.db file is created at the root of my directory with migrations executed.

I wonder why I can't set a relative path such as `jdbc:sqlite:./mydb.db` or `jdbc:sqlite:mydb.db`. Am I missing something? (just to confirm that none of those jdbc creates any mydb.db file anywhere on my project's directory).

**Comment by MikielAgutu** [comment]
I suppose it's a question of how the JDBC driver works. Relative paths will be resolved from the working directory, not necessarily where the configuration lives.

**Comment by sinkcup** [comment]
@po5i if you use `jdbc:h2:file:./mydb`, gradle flyway will create db file at `~/.gradle/`

```
$ find ~/.gradle/ -name '*.db'
/Users/sinkcup/.gradle/daemon/6.4.1/mydb.mv.db
```

if you want db file be created to current dir, you should use this config:

```
flyway {
    url = "jdbc:h2:file:${System.getProperty('user.dir')}/database"
    user = 'sa'
}
```

**Comment by DoodleBobBuffPants** [comment]
We have now documented how gradle relative paths work and this work around. Thank you.
