### ISSUE TITLE
ERROR: Unable to parse statement

### ISSUE THREAD

**Issue by lwasylow** [flyway/flyway#2860]
###### Which version and edition of Flyway are you using?
Flyway Enterprise Edition (unlimited schemas) 6.4.3 by Redgate licensed to Redgate until 2020-07-01

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Redgate Change Control\flyway\flyway.cmd

###### Which database are you using (type & version)?
Oracle 19.6

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Added a package body to a migration folder and tried to deploy.

###### What did you expect to see?
Success

###### What did you see instead?
Unable to parse statement in migrations\PackageBodies\R__ws_dba_apex.oos_util_crypto_PackageBody.sql at line 1 col 1. See https://flywaydb.org/documentation/knownparserlimitations for more information: Flyway parsing bug: unable to decrease block depth below 0
: Running Flyway failed. "C:\Program Files\Red Gate\Redgate Change Control\flyway\flyway.cmd" exited with code 1
Flyway Enterprise Edition (unlimited schemas) 6.4.3 by Redgate licensed to Redgate until 2020-07-01
Database: jdbc:oracle:thin:@//ora-d-vmdb01:1521/dev100_rel_shdw.world (Oracle 19.0)
Successfully validated 41 migrations (execution time 00:00.400s)
Current version of schema "OPS_DATA": 2.0
ERROR: Unable to parse statement in migrations\PackageBodies\R__ws_dba_apex.oos_util_crypto_PackageBody.sql at line 1 col 1. See https://flywaydb.org/documentation/knownparserlimitations for more information: Flyway parsing bug: unable to decrease block depth below 0
Caused by: Flyway parsing bug: unable to decrease block depth below 0
[R__ws_dba_apex.oos_util_crypto_PackageBody.txt](https://github.com/flyway/flyway/files/4799582/R__ws_dba_apex.oos_util_crypto_PackageBody.txt)
[Redgate Change Control-2020_06_15_12_12.log](https://github.com/flyway/flyway/files/4799584/Redgate.Change.Control-2020_06_15_12_12.log)

**Comment by juliahayward** [comment]
Will be fixed in v6.5
