### ISSUE TITLE
Document (or at least reference) known issues with MariaDB driver and MySQL server

### ISSUE THREAD

**Issue by mauromol** [flyway/flyway#2865]
###### Which version and edition of Flyway are you using?

6.4.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

MySQL 5.7

###### Which operating system are you using?

Linux

###### What did you do?

Starting Spring Boot application, having MariaDB 2.6.0 driver on the classpath.

###### What did you expect to see?

No errors/warnings since MariaDB Connector/J 2.6.0 supports MySQL Server 5.7.0

###### What did you see instead?

On startup I get this warning:

    2020-06-22 12:32:24.242  WARN 19434 --- [  restartedMain] o.f.c.i.d.m.MySQLDatabase                : You are connected to a MySQL 5.7 database using the MariaDB driver. This is known to cause issues. An upgrade to Oracle's MySQL JDBC driver is highly recommended.

Since MariaDB and MySQL drivers are not equivalent w.r.t. licensing, and being MariaDB 2.6.0 officially supporting MySQL 5.7, which are these known issues that I should be warned against?

I tried to look at Flyway source code where this warning is produced (`org.flywaydb.core.internal.database.mysql.MySQLDatabase.ensureSupported()`), but I found no mention of them. I tried to search here on GitHub and just found an old issue mentioning problems with MariaDB drivers and MySQL Server 8.0 (https://github.com/flyway/flyway/issues/2099#issuecomment-409869502).
Also tried a broader search with Google but was not able to figure it out.

Thanks in advance.

**Comment by juliahayward** [comment]
It appears these issues are out of date in any case : https://mariadb.com/kb/en/about-mariadb-connector-j/ claims the Maria driver that we now ship supports all versions of MySQL higher than 5.5.3 now.

**Comment by juliahayward** [comment]
Warning will be removed in the next release.
