### ISSUE TITLE
Enabling flyway.oracle.sqlplus=true is causing parsing placeholder error

### ISSUE THREAD

**Issue by lwasylow** [flyway/flyway#2870]
###### Which version and edition of Flyway are you using?
Flyway  6.4.4 by Redgate
we run Flyway from RCC, we run it with the enterprise flag and a license key.

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Redgate Change Control

###### Which database are you using (type & version)?
Oracle 19.6

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
enabled option flyway.oracle.sqlplus=true

###### What did you expect to see?
The package to be parsed with no errors.

###### What did you see instead?
```
Running flyway info failed: Unable to parse statement in migrations\PackageBodies\R__ws_dba_apex.apex_otp_utils_PackageBody.sql at line 1 col 1. See https://flywaydb.org/documentation/knownparserlimitations for more information: No value provided for placeholder: &issuer.  Check your configuration!: Error
    at stackTrace (file:///C:/Program%20Files/Red%20Gate/Redgate%20Change%20Control/rcc-author/resources/app/out/website/index.js:280743:30)
    at fallbackMakeErrorReadable (file:///C:/Program%20Files/Red%20Gate/Redgate%20Change%20Control/rcc-author/resources/app/out/website/index.js:280760:30)
    at Object.makeErrorReadable (file:///C:/Program%20Files/Red%20Gate/Redgate%20Change%20Control/rcc-author/resources/app/out/website/index.js:280647:16)
    at compare (file:///C:/Program%20Files/Red%20Gate/Redgate%20Change%20Control/rcc-author/resources/app/out/website/index.js:278302:75)
```

###### Workaround
I have modifed a string from:
`l_url := 'otpauth://#TYPE#/#LABEL#?secret=#SECRET#&issuer=#ISSUER#';`
 to intsead be 
`l_url := 'otpauth://#TYPE#/#LABEL#?secret=#SECRET#'||chr(38)||'issuer=#ISSUER#';`

Sounds like an error message is confusing , if its running in sqlplus mode then would probably failed as SET DEFINE is not properly set, but error indicates placeholder.

**Comment by Lyeeedar** [comment]
In this situation 'placeholder' is referring to the sql plus variable substitution, not to the flyway placeholders. I admit this terminology can be easily confused with the flyway placeholders, but at this point changing how they are named may cause more confusion with the people who have become used to this naming.

To confirm, correctly defining the placeholder value with does fix the parsing error?

**Comment by juliahayward** [comment]
I suspect `&issue` is part of a string literal which both SQL*Plus and Flyway will interpret as needing variable substitution. In this case SET DEFINE OFF is needed, and I'll update the Flyway message to indicate that.

**Comment by juliahayward** [comment]
SQL*Plus treats `&issue` as a string to be substituted, even though the intent is that it's part of a string literal. SET DEFINE OFF won't save us here because Flyway is doing the substitution itself.

**Comment by lwasylow** [comment]
Hi 
This was not a placeholder but part of the string variable in the package.
Normally would ask for substitution from SQLPLUS if set define off not enabled.

**Comment by juliahayward** [comment]
Yes, that's what I expected - in the absence of `SET DEFINE OFF` both Flyway and SQL*Plus expect to substitute it (Flyway doesn't prompt, it just expects the parameter to be there.) I think the `chr(38)` solution is good in that it's completely unambiguous that it's part of the literal string.
