### ISSUE TITLE
Batch Sql doesn't error out

### ISSUE THREAD

**Issue by sdchhabaria** [flyway/flyway#2872]
###### Which version and edition of Flyway are you using?

6.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
MVN

###### Which database are you using (type & version)?
Oracle 11g

###### Which operating system are you using?
Unix

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I have a versioned patch with lots of DML's.
So I first delete the data and then Insert the data to make the patch re runnable.

For eg:

DELETE FROM TABLE1 where col1 between 110 and 500;

DELETE FROM TABLE2 where col1 between 110 and 500;

DELETE FROM TABLE3 where col1 between 110 and 500;

COMMIT;

INSERT INTO TABLE3 (col1,col2) VALUES (110,'ABC');

The insert statement fails due to unique constraint violation. On further debugging the issue I found that col1 in TABLE2 didn't exists, but since the 3 delete's were executed in batch first one was executed, second one gave error but not halted flyway migration and third delete was skipped.

Now when insert is executed, since  3rd delete was skipped it gives unique constraint violation.  

###### What did you expect to see?

Build should be halted if any of batch execution is unsuccessful.

###### What did you see instead?
Build skipped rest of sql statements in batch.

**Comment by MikielAgutu** [comment]
Can you provide a minimal reproduction script?

**Comment by sdchhabaria** [comment]
[V570004_script.zip](https://github.com/flyway/flyway/files/4932167/V570004_script.zip)
PFA a sample script. 

If migration done wth flyway.batch=true, it is success
but flyway.batch=false, fails the patch which should be done also when flyway.batch=true

**Comment by sdchhabaria** [comment]
Hi.. any update on the issue?

**Comment by MikielAgutu** [comment]
Hello, sorry for our unresponsiveness. I've put this on our team's backlog to look at now.
