### ISSUE TITLE
Set location in Java 

### ISSUE THREAD

**Issue by politrons** [flyway/flyway#2873]
Hi,

I'm just using the latest version, and reading the documentation I cannot find a way programmatically to specify a flyway where are my migration v*_description.sql files that I have in the file-system.  I cannot use location since I would like to use the Java API to do It.

There's an DSL to do that in your API or command-line is the only way?.

Regards

**Comment by MikielAgutu** [comment]
It can be configured with the Flyway api, see the Javadoc https://flywaydb.org/documentation/api/javadoc.html

![image](https://user-images.githubusercontent.com/20282448/87015949-fb79c100-c1c5-11ea-9457-14c5ab20599c.png)

**Comment by politrons** [comment]
sounds promising, thanks!.

Still I cannot make it works. I set an absolute path of location to avoid external issues and still have some problems



  ```
     Flyway flyway = Flyway.configure()
            .dataSource("jdbc:h2:file:./target/customDatabase", flywayUser, null)
            .schemas(flyWayConfig.getString("schemas"))
            .encoding(flyWayConfig.getString("encoding"))
            .validateOnMigrate(flyWayConfig.getBoolean("validateOnMigrate"))
            .cleanDisabled(flyWayConfig.getBoolean("cleanDisabled"))
            .baselineOnMigrate(flyWayConfig.getBoolean("validateOnMigrate"))
            .table(flyWayConfig.getString("table"))
            .outOfOrder(flyWayConfig.getBoolean("outOfOrder"))
            .placeholderReplacement(true)
//            .placeholders(ORA_PLACEHOLDERS)
            .locations("/Users/XXX/Developer/projects/maggie-flyway/maggie-flyway-infrastructure/src/test/resources/db/releases/release-es")
            .load();
```

But after migrate         `flyway.migrate();`

I still have the error

`ADVERTENCIA: Unable to resolve location classpath:Users/XXX/Developer/projects/maggie-flyway/maggie-flyway-infrastructure/src/test/resources/db/releases/release-es. Note this warning will become an error in Flyway 7.`

Any idea?

**Comment by MikielAgutu** [comment]
Try prefixing with `filesystem:`, e.g. `filesystem:/Users/XXX/Developer/projects/flyway/flyway-infrastructure/src/test/resources/db/releases/release-es`

**Comment by politrons** [comment]
yep that works thanks
