### ISSUE TITLE
flyway-core -  single statement SQL migrations  requiring ending semicolon

### ISSUE THREAD

**Issue by gsbtech** [flyway/flyway#2878]
###### Which version and edition of Flyway are you using?
For Java, 
org.flywaydb:flyway-core:6.4.1. Previous version that was used that did not show this error was 6.0.8.

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes, I can reproduce it on 6.5.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java  using flyway-core 6.4.1
mysql:mysql-connector-java 8.0.20

###### Which database are you using (type & version)?
mysql 5.7.24-27

###### Which operating system are you using?
macOS mojave 10.14.6

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Just ran the mysql migrations in a resource directory.  Files are xxx.sql
Most of the files have a single SQL command.
Among these, the ones that do not have an ending ";"  have failed with a misleading message.

###### What did you expect to see?
An ending semicolon is not part of a SQL command definition, at least not of MySQL.
By default, an ending  semicolon is used when there are multiple SQL statements. So it is used as a separator.
A migration file with one statement, which does not end in a semicolon should NOT have failed.

###### What did you see instead?
E.g. a misleading error message:

`Caused by: org.flywaydb.core.api.FlywayException: Unable to parse statement in com/company/app/migration/mysql/V001_1__create_table_coupons.sql at line 2 col 1: Incomplete statement at line 2 col 1: CREATE TABLE IF NOT EXISTS pricing.coupons (
  id                                   INT(11) NOT NULL AUTO_INCREMENT,
`

**Comment by Lyeeedar** [comment]
Could you please share an example script that failed to parse?

**Comment by gsbtech** [comment]
Any  SQL statement that does not end in semicolon.

**Comment by gsbtech** [comment]
[V001_1__create_table_fee_profile.sql.zip](https://github.com/flyway/flyway/files/4927366/V001_1__create_table_fee_profile.sql.zip)

**Comment by gsbtech** [comment]
By the way, using Java 11

**Comment by Lyeeedar** [comment]
This issue should have been fixed by Flyway 6.5.1, could you please test with that version to confirm?

**Comment by Lyeeedar** [comment]
Have you had a chance to test with Flyway 6.5.1 yet?
