### ISSUE TITLE
ALTER EVENT SESSION statement cannot be used inside a user transaction

### ISSUE THREAD

**Issue by anake1** [flyway/flyway#2879]
###### Which version and edition of Flyway are you using?
flyway-commandline-6.5.1-windows-x64

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Latest.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
flyway.cmd

###### Which database are you using (type & version)?
Microsoft SQL Server 2019  15.0.4023.6 (X64)

###### Which operating system are you using?
Windows Server 2016 Standard 10.0

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

ALTER EVENT SESSION [AlwaysOn_health] ON SERVER  ADD EVENT sqlserver.alwayson_ddl_executed(SET collect_statement=(1) ACTION(sqlserver.nt_username));

###### What did you expect to see?
Clean execution.

###### What did you see instead?
SQL State  : S0000
Error Code : 574
Message    : ALTER EVENT SESSION statement cannot be used inside a user transaction.
Line       : 1
Statement  : ALTER EVENT SESSION [AlwaysOn_health] ON SERVER  ADD EVENT sqlserver.alwayson_ddl_executed(SET collect_statement=(1) ACTION(sqlserver.nt_username));

**Comment by MikielAgutu** [comment]
This may be a bug as Flyway should detect non-transacitonal statements. In the meantime you can force this migraiton to run outside of a transaciton with [the `executeInTransaction` script config file option](https://flywaydb.org/documentation/scriptconfigfiles#reference).

**Comment by anake1** [comment]
I understand that parameter executeInTransaction=false should be added and that is all. If yes I still get the same error.

**Comment by MikielAgutu** [comment]
Ok, we'll have to investigate further. We'll aim to get a fix in the next release.

**Comment by juliahayward** [comment]
I'm not able to reproduce the problem - would you be able to send me the script `.sql` file and associated `.sql.conf` file? You can mail to support@flywaydb.org or julia.hayward@red-gate.com if you prefer not to post here.

**Comment by juliahayward** [comment]
Ok, it seems to be a weakness in the documentation telling you how to use this feature. I'll update it.
