### ISSUE TITLE
Default value of placeholder. command line 

### ISSUE THREAD

**Issue by MENGKONGSEAN** [flyway/flyway#2880]
###### Which version and edition of Flyway are you using?
4.2.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Not issues 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
Mysql ad postgres

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
`-placeholders.KYC_VALIDATION=${KYC_VALIDATION}:false`

###### What did you expect to see?
I would expect it will have defalut value for placeholder when `KYC_VALIDATION` not exist I expect it will get `false` 

###### What did you see instead?
I would expect it have default value.

**Comment by MikielAgutu** [comment]
We don't think this is the right thing for Flyway.
