### ISSUE TITLE
Percona XtraDB CREATE TABLES AS SELECT prohibited

### ISSUE THREAD

**Issue by ampersand8** [flyway/flyway#2883]
We're using Flyway 6.4.4

We are using Percona XtraDB Cluster 5.7. The pxc_strict_mode is set to MASTER, which in our case is hard coded in the bosh-release we are using (https://github.com/cloudfoundry-incubator/pxc-release).

When trying to 'migrate' we see the following error:
```
Migration  failed
-----------------
SQL State  : HY000
Error Code : 1105
Message    : Percona-XtraDB-Cluster prohibits use of CREATE TABLE AS SELECT with pxc_strict_mode = ENFORCING or MASTER
Location   :  ()
Line       : 1
```

Flyway already has [a check for the pxc_strict_mode](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLDatabase.java#L95), which is then also used to [decide whether "create table as select" is allowed](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLDatabase.java#L142). However, the pxc_strict_mode check only checks for "ENFORCING" and ignores "MASTER". Therefore, in our case the migration is still done by "create table as select", which is also not supported with pxc_strict_mode = MASTER (see error message above).

I think the pxc_strict_mode check, could also look for MASTER.

**Comment by juliahayward** [comment]
Will be fixed in 6.5.2 - thankyou!
