### ISSUE TITLE
Flyway parsing bug: unable to decrease block depth below 0 in version 6.4.2

### ISSUE THREAD

**Issue by t-kwasniewski** [flyway/flyway#2884]
###### Which version and edition of Flyway are you using?

6.4.2 

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I have checked also version 6.5.1 and there still was this error

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?

Oracle 19

###### Which operating system are you using?
Linux and Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

In v6.2.4 i was having an error "unable to decrease block depth below 0" when i try to execute script which contains create package, procedure and dbms_scheluder.create_job.
Example code:
```sql
CREATE OR REPLACE PACKAGE some_jobs AS
    PROCEDURE some_procedure;
END some_jobs;

CREATE OR REPLACE PACKAGE BODY some_jobs AS

    PROCEDURE some_procedure IS
      CURSOR C_TO_CLOSE
      IS
        --some select

    BEGIN
      FOR row IN C_TO_CLOSE
      LOOP
       --update
      END LOOP;
    END;
END;

BEGIN
 DBMS_SCHEDULER.create_job (
    job_name        => 'some_procedure_job',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'some_jobs.some_procedure',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=DAILY; BYHOUR=1',
    end_date        => NULL,
    enabled         => TRUE,
    comments        => 'some job');
END;

```

Workaround from issue https://github.com/flyway/flyway/issues/2715 (downgrade to v6.2.0) works.
But same issue exists in version 6.5.2.

**Comment by Lyeeedar** [comment]
If you add a / after the end of the package and the package body, Flyway will parse them correctly again. 

In Flyway 6.2.0 this parsed by accident, as packages were not being correctly separated out which would in some cases mean that the sql was invalid when executed.
Fixing that bug has meant that packages need to explicitly be deliminated by a / to be detected properly. If I'm not mistaken this is the same behaviour that SQL*Plus exhibits isnt it?

**Comment by t-kwasniewski** [comment]
Thank you for very fast answer. Adding / helped. Now it works corretly.
