### ISSUE TITLE
Unable to perform any Flyway Gradle task

### ISSUE THREAD

**Issue by gregorsintic** [flyway/flyway#2888]
###### Which version and edition of Flyway are you using?
Using gradle plugin:
id "org.flywaydb.flyway" version "6.5.2"

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Using latest as specified on official page https://flywaydb.org/documentation/gradle/#installation

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle Plugin

###### Which database are you using (type & version)?

Oracle 12c2 EE

###### Which operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Created new empty Gradle project and wrote the following build.gradle script:

`plugins {
    id "org.flywaydb.flyway" version "6.5.2"
}

repositories {
    mavenCentral()
}

apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'org.flywaydb.flyway'

group 'flyway-test'
version '1.0-SNAPSHOT'

compileJava{
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}

dependencies {
    //flywayMigration
    compile files("C:/tools/flyway-6.5.0/drivers/ojdbc8-19.6.0.0.jar")
}

flyway {
    driver='oracle.jdbc.OracleDriver'
    url = 'jdbc:oracle:thin:<username>/<password>@//<correct_address>:1521:orcl'
    user = '<username>'
    password = '<password>'
}
// also tried without user and password parameters as its already in url. 
// also tried without user and password in url and added them as parameters in flyway
`
I provided the same ojdbc8.jar as dependency found in Flyway downloaded as zip. 

Tried Java 8 & Java 11
Tried both in CMD and IntelliJ getting same result
I am using IntelliJ IDEA 2019.2.4. Ultimate Edition. 

###### What did you expect to see?
I expected to see contents of table _flyway_schema_history_.
I was able to use Flyway normally when using Flyway downloaded as .zip. 

After using binary/"full installation" Flyway i decieded to use Gradle plugin. So i executed flywayInfo task on same DB schema as the one I worked with with binary Flyway.

###### What did you see instead?
FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':flywayInfo'.
> Error occurred while executing flywayInfo
  Unable to obtain field value oracle.jdbc.OracleConnection.CONNECTION_PROPERTY_THIN_NET_DISABLE_OUT_OF_BAND_BREAK : oracle.jdbc.OracleConnection
  oracle.jdbc.OracleConnection

The result is same in CMD or IDEA

Looking for ideas how to resolve this problem? 
Thanks in advance,

Gregor

**Comment by Lyeeedar** [comment]
Could you please try any version of Flyway before 6.4.3 and see if it works?

**Comment by juliahayward** [comment]
I've seen this happen when the Oracle JDBC driver is not present (it masks a `ClassDefNotFound` exception). Could that be related to the problem?

**Comment by gregorsintic** [comment]
> Could you please try any version of Flyway before 6.4.3 and see if it works?

I tried with 6.4.2 and 6.3.2. Now I get a different more clear error: 

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':flywayInfo'.
> Error occurred while executing flywayInfo
  Unable to instantiate JDBC driver: oracle.jdbc.OracleDriver => Check whether the jar file is present
  Unable to instantiate class oracle.jdbc.OracleDriver : oracle.jdbc.OracleDriver
  oracle.jdbc.OracleDriver

But how is this possible if I added the "C:/tools/flyway-6.5.0/drivers/ojdbc8-19.6.0.0.jar" as dependency. I also tried a different path: "C:\\tools\\flyway-6.5.0\\drivers\\ojdbc8-19.6.0.0.jar" for possible errors in path since I am using Windows but I think Gradle can handle both paths. 

I also see the added JAR in IDEA under External Libraries. I dont see why it would not get detected by flyway plugin...


> I've seen this happen when the Oracle JDBC driver is not present (it masks a `ClassDefNotFound` exception). Could that be related to the problem?

Yes as you can see above this is exactly what is going on. But I don't know why...

**Comment by gregorsintic** [comment]
I apologise for this.... My insfufficient knowledge of Gradle caused this.
Till now I have been adding dependencies like odjbc8.jar to projects normally like in my case above via dependencies block. Using an external plugin like Flyway means that the plugin itself needs ojdbc.jar inside build.gradle to work. To add this dependency to _the classpath_ you need to use `buildscript{}` block where you add ojdbc.jar as dependency. After this Flyway starts working as expected. 

Gradle documentation on this: [https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:build_script_external_dependencies](url)

Thanks again!

Best regards,

Gregor

**Comment by juliahayward** [comment]
Thanks for letting us know - we'll also have a look at our documentation and see if we can make it better.
