### ISSUE TITLE
Undo dry don't generate report

### ISSUE THREAD

**Issue by politrons** [flyway/flyway#2890]
Good Morining,

We are using flyway with a Java API. flyway version: 6.5.0 Enterprise. database: h2 (version 1.4.197).

We are trying to apply undo operation programmatically setting a number of a version and applying undo until the current version would be equal. For example undoVersion from 03 to 02.

    private void undoVersion(String lastVersion, Flyway flyway, int limit) {
        MigrationInfoService info = flyway.info();
        String currentVersion = info.current()!=null && info.current().getVersion()!=null ?
            info.current().getVersion().getVersion() : null;

        if (limit > 0 && !lastVersion.equals(currentVersion)) {
            flyway.undo();
            
            undoVersion(lastVersion, flyway, limit - 1);
        }
    }
If we create the flyway instance using dryRunOutput this way the undo operation is not truly executed but I was expecting to see the report with the `UNDO` actions that I have in my `UNDO` files

```
   Flyway.configure()
            .dataSource(countryConfig.getString("url"), flywayUser, countryConfig.getString("password"))
            .licenseKey(FLYWAY_LICENSE)
            .schemas(flyWayConfig.getString("schemas"))
            .encoding(flyWayConfig.getString("encoding"))
            .validateOnMigrate(flyWayConfig.getBoolean("validateOnMigrate"))
            .cleanDisabled(flyWayConfig.getBoolean("cleanDisabled"))
            .baselineOnMigrate(flyWayConfig.getBoolean("validateOnMigrate"))
            .table(flyWayConfig.getString("table"))
            .outOfOrder(flyWayConfig.getBoolean("outOfOrder"))
            .placeholderReplacement(true)
            .locations("filesystem:" + countryConfig.getString("flywayLocation"))
            .dryRunOutput(outputFileName)
            .load();

```
But after execute the undo the report is generated but without all the steps that I define in my `UNDO` files

**Comment by Lyeeedar** [comment]
Related to https://github.com/flyway/flyway/issues/2893

**Comment by juliahayward** [comment]
I'm not able to reproduce locally. Can you turn the logger in your application up to the highest level, and send us the output? (By email to julia.hayward@red-gate.com is fine rather than publishing here)

**Comment by politrons** [comment]
Before we can provide an example that work for you (It's part of a large library), maybe you can share some code showing us how the undo works with DryRun generating the report.sql?

**Comment by juliahayward** [comment]
This was sufficient for me:
```
flyway = Flyway.configure().configuration(flyway.getConfiguration())
                .locations("filesystem:c:\\flyway-conf\\sql")
                .baselineOnMigrate(false)
                .licenseKey("FL01...")
                .load();
// Empty the database
        flyway.clean();
// Do the V1 migration
        flyway.migrate();
        flyway = Flyway.configure().configuration(flyway.getConfiguration())
                .locations("filesystem:c:\\flyway-conf\\sql")
                .baselineOnMigrate(false)
                .licenseKey("FL01...")
                .dryRunOutput("c:\\temp\\dryRunUndoOutput.txt")
                .load();
// Undo the v1 migration - dry run only
        flyway.undo();
```

If you're getting dry run output but there's no actual migrations there, then the problems are likely that Flyway is unable to find a migration to undo - either because the `U1__migration.sql` file is missing, incorrectly named, the locations path is wrong, or the history table doesn't contain what you expect.

**Comment by politrons** [comment]
Thanks a lot!.  I'm trying to run your code, can you also please provide your config file?, just in case we have a property wrong set

Regards

**Comment by politrons** [comment]
@juliahayward with your code we manage to make it works, thanks a lot, we will investigate what problem we have in our side.

Regards

**Comment by juliahayward** [comment]
That's great - thanks! I wasn't using a config file except to set the database url, by the way.
