### ISSUE TITLE
InMemory File System path for Flyway

### ISSUE THREAD

**Issue by slsshetty** [flyway/flyway#2891]
###### Which version and edition of Flyway are you using?
3.2.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MySql

###### Which operating system are you using?
Windows/UNIX

###### What did you do?
I am using JIMFS which is an InMemory File System for java. When I provide this path to Flyway locations it says Unable to resolve filesystem:path.

###### What did you expect to see?
It should have picked the path

###### What did you see instead?
It is not able to resolve the path for in memory directory

**Comment by Lyeeedar** [comment]
You can specify your own migration providers as of Flyway 6.5. See blog post detailing how to do so here: https://flywaydb.org/blog/Configure-resource-providers

Using this you can develop support for this new location.
