### ISSUE TITLE
Support for PgBouncer transaction pooling

### ISSUE THREAD

**Issue by matmannion** [flyway/flyway#2895]
###### Which version and edition of Flyway are you using?

6.5.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

postgres (PostgreSQL) 10.13
PgBouncer 1.14.0

###### Which operating system are you using?

CentOS Linux release 7.8.2003

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Connected to the PostgreSQL database via PgBouncer, using transaction pooling. Flyway.migrate() is called as part of startup.

This is part of a multi-node environment where multiple nodes start simultaneously, meaning there are multiple nodes starting Flyway from the same code-base at the same time.

###### What did you expect to see?

Validation of the existing migrations and performing any missing ones.

###### What did you see instead?

Multiple nodes appear to "lock", waiting for a time-out and then dying with an error "Number of retries exceeded while attempting to acquire PostgreSQL advisory lock".

Looking at the way the code works, this is expected; Flyway grabs a _session_ lock as part of its work (https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLAdvisoryLockTemplate.java#L106-L116) but PgBouncer is set up to do transaction pooling, so multiple nodes may (and do, in this case) receive the same database session for separate transactions. This then means that the session lock can't be obtained and the node fails with the above error.

In this situation (and with group=true in settings) it _may_ be more appropriate to get a transaction-level advisory lock rather than a session-level advisory lock by using `pg_try_advisory_xact_lock` instead of `pg_try_advisory_lock`, which may be sufficient to get this working with PgBouncer transaction pooling.

**Comment by fml2** [comment]
> multiple nodes may (and do, in this case) receive the same database session for separate transactions. This then means that the session lock can't be obtained and the node fails with the above error.

Shouldn't it rather lead to the situation that ALL nodes successfully aquire the lock (since they work within same session as seen by the DB)? Hence, effectively, no sync would take place.

According to the docs (see [here](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS)),

> If a session already holds a given advisory lock, additional requests by it will always succeed

So, if multiple nodes share the session, there will be no concurrency protection at all.

**Comment by fml2** [comment]
For the reference: #3086 describes a similar but not identical case. There, the migration went OK until the advisory lock was to be released, which failed.

**Comment by fml2** [comment]
Another relevant info:

If PgBouncer is configured to work in transaction pooling mode, the error described in #3086 arises (can't release advisory lock).

If PgBouncer is configured to work in session pooling mode, everything works correctly, i.e. the advisory lock can be released at the end of the flyway migration.

**Comment by hacst** [comment]
Could someone with more knowledge on flyway internals elaborate on why session locks are required here? https://flywaydb.org/documentation/learnmore/faq#parallel mentions it for coordinating multiple nodes. However wouldn't they coordinate themselves even with just per migration transaction level locking as each migration is done separately? Would something fundamental break if it was optionally allowed to work this way?

I also tried to check how other tools handle this and it seems like liquibase uses a more manual approach to locking using a table https://docs.liquibase.com/concepts/basic/databasechangeloglock-table.html . That should not be a problem with pgbouncer however it might leave itself locked accidentally if something goes wrong.

**Comment by jmotex** [comment]
After investigating and considering this, I switched it to transaction scoped advisory locks and tested locally with pgBouncer transaction pooling, session pooling and direct backend.  All three work the same and it works nicely with both per-migration lock and entire migration group lock.  The reported error could not be reproduced.  If somebody could take a look at the PR, it would be appreciated.

**Comment by jmotex** [comment]
I've created a PR that adds support for pgBouncer.  Please see #3394

**Comment by hacst** [comment]
@DoodleBobBuffPants in a linked bugreport you commented that there has not yet been a decision on whether to support pgbouncer. Would the pending PR by jmotex be a valid implementation of the feature? Is there other work required? Not being able to use flyway with pgbouncer is definitely still is a pain point. pgbouncer is quite common in postgresql setups.

**Comment by gmcquillan** [comment]
PgBouncer is very, very common in large Postgresql deployments.

I think this is less about supporting PgBouncer for migrations and more about reducing the transactional scope that those migrations need. 

This is a very popular migration tool, but also the only one that I'm aware of that has this issue. Please, let's see what we can do to support this feature.

**Comment by sharkymcdongles** [comment]
I am also bit by this. It would be amazing if someone would look at the PR.

**Comment by PatrickHaas** [comment]
Any ideas on when u guys fix this issue?

**Comment by fml2** [comment]
In our company, we abandoned flyway and switched to liquibase -- exactly because of this issue.

**Comment by FoKas90** [comment]
We are extend flyway by org.flywaydb.core.extensibility.Plugin file, which tell use our impl of PostgreSQLDatabaseType. That class use our impl of PostgreSQLConnection, which override lock method. For locking we create special table in another database schema.
