### ISSUE TITLE
timestamp differences in flyway_schema_history.installed_on column. 5 hr offset

### ISSUE THREAD

**Issue by bugnvl** [flyway/flyway#2897]
###### Which version and edition of Flyway are you using?
5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
not tested on new version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
maven

###### Which database are you using (type & version)?

oracle and 12.2.0.1 and plan to use on 18c, 19c 

###### Which operating system are you using?

Linux 7

###### What did you do?
select * from ARUNGSOX."flyway_schema_history";
1	1	sql selectas	SQL	V1__sql_selectas.sql	157908673	ARUNGSOX	30-JUL-20 09.24.06.528007000 PM	2965	1
2	2	sql createtable	SQL	V2__sql_createtable.sql	-1845933317	ARUNGSOX	30-JUL-20 09.24.07.025477000 PM	272	1
5	7	demosql	SQL	V7__demosql.sql	-733124648	ARUNGSOX	31-JUL-20 03.03.13.504589000 PM	473	1
4	6	create1 5GBtable	SQL	V6__create1_5GBtable.sql	-1861372367	ARUNGSOX	31-JUL-20 07.09.35.614333000 AM	323	1
3	5	insertintoasselect	SQL	V5__insertintoasselect.sql	320881898	ARUNGSOX	30-JUL-20 10.10.58.042814000 PM	442	1

V7_demosql.sql was triggered on 31-JUL-20 but in the morning 10 AM or so.. not 3 PM.. 

database is in CST. 
Select dbtimezone from dual; 
+00:00
select to_char(current_date, 'DD-MON-YYYY HH:MM:SS'), to_char(sysdate, 'DD-MON-YYYY HH:MM:SS') from dual;
02-AUG-2020 02:08:16	02-AUG-2020 02:08:16

###### What did you expect to see?
I was hoping to see 10.13* AM.. not 3 PM.

###### What did you see instead?
31-JUL-20 03.03.13.504589000 PM

**Comment by Lyeeedar** [comment]
Flyway uses (CURRENT_TIMESTAMP)[https://docs.oracle.com/database/121/SQLRF/functions052.htm#SQLRF00629] for the installedOn value. From looking at the docs, this can be modified by any changes to the session timezone. Do any of the migrations or callbacks in your project do this?
