### ISSUE TITLE
Add Additional Logging for Loading Backup Driver

### ISSUE THREAD

**Issue by belugabehr** [flyway/flyway#2902]
https://github.com/flyway/flyway/blob/a9402ccde08f25c3b606bb940e387f2e70e84208/flyway-core/src/main/java/org/flywaydb/core/internal/jdbc/DriverDataSource.java#L175-L192

This code caused a bit of confusion for me.  I had incorrectly installed the MySQL JDBC Driver and when Flyway started up, it failed with a message about `com.mysql.cj.jdbc.Driver`, this was confusing since I was expected it to look for `com.mysql.jdbc.Driver` which is the legacy Driver I was providing.

Based on the code, it looks like it *does* try to load `com.mysql.jdbc.Driver` but first it tries `com.mysql.cj.jdbc.Driver` since it wasn't able to, it has a fall-back option to a fallback to the legacy MySQL JDBC driver.  However, this happens transparently and the resulting Exception only covers the details of trying to the primary driver.  Please add some additional logging here that says something like:

> Unable to load driver com.mysql.cj.jdbc.Driver, trying backup driver com.mysql.jdbc.Driver instead

**Comment by belugabehr** [comment]
That is all to say that the second exception message should include both of the driver classes it attempted.

**Comment by Lyeeedar** [comment]
We will be updating the message in Flyway v7

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
