### ISSUE TITLE
Flyway 6.5.3 is really slow in resolving resources

### ISSUE THREAD

**Issue by leoherbie** [flyway/flyway#2903]
###### Which version and edition of Flyway are you using?

6.5.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes 6.5.4 also fails.  6.5.2 worked just fine.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java api

###### Which database are you using (type & version)?

mysql  Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)

###### Which operating system are you using?

macosx 10.15.6
circleci docker images:           
- image: circleci/openjdk:11-jdk-browsers
- image: circleci/mysql:8-ram

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

When calling the info command or the migrate command via the java api the this.migrationResolver.resolveMigrations(this.context); never completes.  I believe this is related to the change.https://github.com/flyway/flyway/commit/ecfebd2e99f9ac507c3af3627dad6d149dc89335#diff-ef3cebb1d725c91fdb9dbd22d7163eab

Our locations look like the following and are all located on the classpath.  They are mostly sql files but we do have some jdbc migrations.

co/kuali/coeus/data/migration/sql/mysql/kc/bootstrap,co/kuali/coeus/data/migration/sql/mysql/kc/staging,co/kuali/coeus/data/migration/sql/mysql/kc/demo,co/kuali/coeus/data/migration/sql/mysql/rice_server/bootstrap,co/kuali/coeus/data/migration/sql/mysql/rice/bootstrap,co/kuali/coeus/data/migration/sql/mysql/rice/staging,co/kuali/coeus/data/migration/sql/mysql/rice/demo,co/kuali/coeus/data/migration/custom/coeus

Note: adding classpath:/ to each path seems to help performance on macosx but not on circleci.  I'm not sure if this is just a coincidence or if it really does make a difference. 

###### What did you expect to see?

I expect to see output related to the command.

###### What did you see instead?

No output. It just pauses when attempting to find file resources

**Comment by kalejami** [comment]
Yes, same problem with Windows 10 too.

I described the cause of the problem already here:

https://github.com/flyway/flyway/pull/2901

**Comment by leoherbie** [comment]
Perfect!  Thank you for fixing this @kalejami

**Comment by kalejami** [comment]
@leoherbie No you got me wrong, I didn't fix anything. Just described the problem. #2901 won't fix the problem!

**Comment by Lyeeedar** [comment]
In Flyway 6.5.5 we pushed a fix that should solve the slowdown, could you try that and if it doesnt work make a new issue?

**Comment by kalejami** [comment]
@Lyeeedar 6.5.5 works like a charm. Thank you for fixing the problem
