### ISSUE TITLE
Defining multiple schemas only migrates the first schema

### ISSUE THREAD

**Issue by runarhk** [flyway/flyway#2905]
When defining multiple schemas only the first one is migrated. This could be due to the fact that only the first Schema in the schemas array is used in the mentioned code line. Not sure about the implications of looping over all schemas and running the migrations, but that could be a possible quick-fix. 

https://github.com/flyway/flyway/blob/e281909e1158481f25b2f3cbd201016054594260/flyway-core/src/main/java/org/flywaydb/core/Flyway.java#L205

**Comment by Lyeeedar** [comment]
The schemas property is just the list of schemas flyway will manage. [See documentation](https://flywaydb.org/documentation/commandline/migrate#schemas)

This means Flyway will create them if they don't exist, and clean them when you run Flyway clean.

If you want to run Flyway on multiple schemas, executing the same migrations on each (and presumably with a schema history in each), you need to run Flyway multiple times, which time with the schema list pointing to one of the schemas.
