### ISSUE TITLE
Cleanup unused imports, formatting and codesmells

### ISSUE THREAD

**Issue by Jolley71717** [flyway/flyway#2908]
###### Which version and edition of Flyway are you using?
current master version

Reading through some of the code and there was tons of blank space, unused imports and a few code-smells.

I use flyway and would like to leave it a little cleaner than I found it.
Following the guidelines for submitting new code and adding an issue was the first step

**Comment by Lyeeedar** [comment]
The blank lines and unused imports are for code found only in the pro and enterprise editions of flyway. Sadly there is no way to easily remove these for the community edition, so the code will have some oddities as a result.

Thank you for your interest though! Guidelines for how to contribute can be found here: https://flywaydb.org/documentation/contribute/
