### ISSUE TITLE
TiDB support

### ISSUE THREAD

**Issue by bb7133** [flyway/flyway#2910]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.5.3

###### Which database are you using (type & version)?
TiDB Community Edition 4.0.0(https://docs.pingcap.com/tidb/stable)

I've proposed an issue with some possible solutions in TiDB repo: https://github.com/pingcap/tidb/issues/19449

**Comment by DoodleBobBuffPants** [comment]
TiDB is now available as part of our community database package, which is [here](https://mvnrepository.com/artifact/org.flywaydb/flyway-community-db-support) on Maven
