### ISSUE TITLE
Flyway locking is unsafe in MySQL 5.6 and below

### ISSUE THREAD

**Issue by morgo** [flyway/flyway#2911]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 6.5.5 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

It is the latest.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command Line

###### Which database are you using (type & version)?

MySQL

###### Which operating system are you using?

Linux

###### What did you do?

I inspected the code to see how it ensures one migration is performed at a time in MySQL, and noticed an issue:

Flyway uses `GET_LOCK` in a way that relies on the [MySQL 5.7+ behavior](https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html#function_get-lock). In MySQL 5.6 and earlier, subsequent calls to `GET_LOCK` in the same session will release all previous locks acquired. I confirmed via a trace (see
[mysql.log](https://github.com/flyway/flyway/files/5131246/mysql.log) attached) that this issue exists, and that there is no reserved connection logic to mitigate this.

It looks like MySQL 5.6 is now enterprise only support, but I can only assume it uses the same code base.

~I think there is also an issue in the PXC implementation, but I will investigate and file separately.~ **Edit:** The PXC implementation is safe! It uses `SELECT FOR UPDATE` in one session, and a second sesion to do the work to avoid the implicit commit from a CREATE TABLE releasing the lock. May I suggest just using the PXC implementation everywhere? See 
[pxclog.log](https://github.com/flyway/flyway/files/5131600/pxclog.log).

###### What did you expect to see?

 I expect it to work, or error.

**Comment by DoodleBobBuffPants** [comment]
MySQL 5.6 is fairly old and support is due to end in early 2021 so it isn't worth changing the behavior. Also we only use `GET_LOCK` when creating the schema history table so there isn't a table to use the PXC implementation. Thanks though!
