### ISSUE TITLE
ERROR: Failed to execute operation in non-transactional context. Please restore backups and roll back database and code!

### ISSUE THREAD

**Issue by sukhdevkhade** [flyway/flyway#2912]
Hi,

Currently i am using Flyway (flyway-6.5.3) on local window machine . Using flyway it is successfully created table , db etc in Sybase ASE 16.0...
But  it gives below error during backup and restore..

ERROR: Migration of schema dbo to version 1.6.0.2 - Crete Dump failed! Please restore backups and roll back database and code!
ERROR: Failed to execute operation in non-transactional context. Please restore backups and roll back database and code! 

I have already make mixed=true in conf file.
please give solution.

thanks in advanced.

**Comment by sukhdevkhade** [comment]
@Axel Fontaine can u check this error..?

**Comment by MikielAgutu** [comment]
Can you share the script which is causing the problem?

**Comment by sukhdevkhade** [comment]
hi  @MikielAgutu  

dump database DBname to '/home/ec2-user/DBname.dump'
go

**Comment by DoodleBobBuffPants** [comment]
Can you send us the full output of migrate in debug mode? (run with `-X`)

**Comment by sukhdevkhade** [comment]
[Flyway_output.txt](https://github.com/flyway/flyway/files/5136789/Flyway_output.txt)


hi @DoodleBobBuffPants

Please find attachment.  Currently i am using Sybase 16.0 version for backup 
please let me know if anything else.

thanks..

**Comment by DoodleBobBuffPants** [comment]
Out of curiosity is the dump file actually created even when it fails?

**Comment by sukhdevkhade** [comment]
Hi @DoodleBobBuffPants

It failed during backup but successfully created the dump file ..

during backup , flyway throws error . I don't know what is problem.

Another curiosity is that this dump file was not corrupted because this load manually to other Sybase db it's recovers all databases tables, store-processes etc.

give below error during backup.

ERROR: Failed to execute operation in non-transactional context. Please restore backups and roll back database and code!

ERROR: Migration of schema dbo to version 1.6.0.2 - Crete Dump failed! Please restore backups and roll back database and code!

ERROR: Failed to execute operation in non-transactional context. Please restore backups and roll back database and code! 

I attached some snip , please find.

![Flyway1](https://user-images.githubusercontent.com/49577440/91472223-c3812700-e8b4-11ea-8750-f63b192151f6.PNG)

![Flyway2](https://user-images.githubusercontent.com/49577440/91472263-d0057f80-e8b4-11ea-8003-3f38691136df.PNG)

**Comment by DoodleBobBuffPants** [comment]
This is due to [Sybase throwing an exception](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc00729.1500/html/errMessageAdvRes/BGBCJDHC.htm). You could try looking into [error handling your SQL](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1510/html/iqrefbb/Tseh.htm).
