### ISSUE TITLE
Support for GCP BigQuery

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2913]
Received by email: Can we add support for Google Cloud BigQuery?

**Comment by sann3** [comment]
It will help lot of people if add support Google Cloud BigQuery, since no other tools are supporting currently.

**Comment by lidalei** [comment]
Hi guys, I have made an implementation https://github.com/flyway/flyway/compare/master...lidalei:master. You need to follow the [getting-started](https://flywaydb.org/documentation/contribute/contributingDatabaseSupport#getting-started) to play with it. Your configuration file should look like this

```
# Long properties can be split over multiple lines by ending each line with a backslash
flyway.locations=filesystem:<path_to_sql_folder>

flyway.url=jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=<gcp_project_id>;Location=EU;OAuthType=0;OAuthServiceAcctEmail=<sa_name>@<gcp_project_id>.iam.gserviceaccount.com;OAuthPvtKeyPath=<path_to_service_account_key_file.json>;
flyway.user='hello'
flyway.password='world'

flyway.driver=com.simba.googlebigquery.jdbc42.Driver
flyway.jarDirs=<path_enclosing_simba_driver>/SimbaJDBCDriverforGoogleBigQuery42_1.2.14.1017/

flyway.schemas=flyway
# The simba JDBC driver always creates schema in the US multi-region (doesn't respect the BigQuery Location configuration).
# So we have to manually create the schema and tell flyway to not create schema.
# Please ignore the warning flyway outputs if you have created the schema in the Location.
flyway.createSchemas=false
```

Note you need to manually create the flyway schema in the desired region (EU in the example) before running migrations. Enjoy flyway and BigQuery!

**Comment by sharadjain21** [comment]
@DoodleBobBuffPants any timeline how soon we can expect it to get added pls.?

**Comment by juliahayward** [comment]
It is on our roadmap for v8, although there will be some significant refactoring of the database support mechanism (which I'm working on right now).

**Comment by juliahayward** [comment]
@lidalei Have you tried running a repeatable migration? I'm seeing errors along the lines that the Simba driver does not support inserting nulls into the history table?

**Comment by lidalei** [comment]
> @lidalei Have you tried running a repeatable migration? I'm seeing errors along the lines that the Simba driver does not support inserting nulls into the history table?

Not really. I will try to reproduce it later today. Could you share the stack trace?

**Comment by juliahayward** [comment]
`[Simba][BigQueryJDBCDriver](100064) The specified column type is currently unsupported by the driver for column {0}.` at 
JDBCTableSchemaHistory.java line 169

- that is jdbcTemplate.update(...) in case line numbers have changed

**Comment by juliahayward** [comment]
I *think* I have a fix in that I can update the JDBC template to use `statement.setNull(i + 1, Types.VARCHAR);` for the null version field for the repeatable migration, but I haven't yet found documentation to confirm this is the right thing to do?

**Comment by lidalei** [comment]
> I _think_ I have a fix in that I can update the JDBC template to use `statement.setNull(i + 1, Types.VARCHAR);` for the null version field for the repeatable migration, but I haven't yet found documentation to confirm this is the right thing to do?

I remember using VARCHAR leads to another issue.

So I turned on the driver's trace mode, I got this
```
May 21 23:38:19.539 ERROR 1 com.simba.googlebigquery.exceptions.ExceptionConverter.toSQLException: [Simba][BigQueryJDBCDriver](100064) The specified column type is currently unsupported by the driver for column {0}.
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100064) The specified column type is currently unsupported by the driver for column {0}.
	at com.simba.googlebigquery.googlebigquery.utils.BQCoreUtils.convertSqlTypeToBigQueryType(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeAnyUpdate(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeUpdate(Unknown Source)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.update(JdbcTemplate.java:328)
```

and errored function convertSqlTypeToBigQueryType does not accept Types.NULL (aka 0).
```
    public static String convertSqlTypeToBigQueryType(int var0) throws ErrorException {
        switch(var0) {
        case -16:
        case -15:
        case -9:
        case -1:
        case 1:
        case 12:
            return "STRING";
        case -7:
        case 16:
            return "BOOL";
        case -6:
        case -5:
        case 4:
        case 5:
            return "INT64";
        case -4:
        case -3:
        case -2:
            return "BYTES";
        case 2:
        case 3:
            return "NUMERIC";
        case 6:
        case 7:
        case 8:
            return "FLOAT64";
        case 91:
            return "DATE";
        case 92:
            return "TIME";
        case 93:
        case 2014:
            return "STRING";
        default:
            throw BQDriver.s_BQMessages.createGeneralException(BQMessageKey.METADATA_INCORRECT_TYPE_ERR.name());
        }
    }
```

I have  no idea to solve it without changing org.flywaydb.core.internal.jdbc.JdbcTemplate.java to distinguish STRING, INTEGER and BOOL Nulls.

```
    protected PreparedStatement prepareStatement(String sql, Object[] params) throws SQLException {
        PreparedStatement statement = connection.prepareStatement(sql);

        //Spanner requires specific types for null but most others e.g. postgres don't work that way
        for (int i = 0; i < params.length; i++) {
            if (params[i] == null) {
                statement.setNull(i + 1, nullType);
            } else if (params[i] instanceof Integer) {
                statement.setInt(i + 1, (Integer) params[i]);
            } else if (params[i] instanceof Boolean) {
                statement.setBoolean(i + 1, (Boolean) params[i]);
            } else if (params[i] instanceof String){
                statement.setString(i + 1, params[i].toString());
            } else if (params[i] == JdbcNullTypes.StringNull) {
                statement.setNull(i + 1, nullType);
            } else if (params[i] == JdbcNullTypes.IntegerNull) {
                statement.setNull(i + 1, nullType);
            } else if (params[i] == JdbcNullTypes.BooleanNull) {
                statement.setNull(i + 1, nullType);
            } else {
                throw new FlywayException("Unhandled object of type '" + params[i].getClass().getName() + "'. " +
                        "Please contact support or leave an issue on GitHub.");
            }
        }
        return statement;
    }
```

But it is doable. Will try tomorrow!

**Comment by lidalei** [comment]
@juliahayward It works now with the new commit [distinguish String, Integer, Boolean NULL for BigQuery
](https://github.com/flyway/flyway/commit/92f2bfc13cb2d62adbe6d3a8639cba80b4a2c6b1). Note I tested it with the latest JDBC driver [1.2.16.1020](https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers#current_jdbc_driver_release_12161020) and it works in the following cases:
* `validate` failed if a repeatable migration changes (expected)
* `validate` failed if a versioned migration changes (expected)
* `migrate` succeeded if a new repeatable migration is added
* `migrate` succeeded if a repeatable migration changes.

**Comment by sann3** [comment]
This issue is closed, that means it is implemented ?

**Comment by lidalei** [comment]
> This issue is closed, that means it is implemented ?

https://flywaydb.org/documentation/database/big-query
