### ISSUE TITLE
Could you please clarify the community edition of flyway support dates for 12.2.0.1, 18c and 19c??

### ISSUE THREAD

**Issue by bugnvl** [flyway/flyway#2915]
Five years after the initial release of Oracle 12, we now have a brand new Oracle major release: 18c. It was initially available exclusively for Oracle Cloud. And now since August 2018 it is also available for download and Flyway 5.2. 0 comes with full support for it.Oct 4, 2018

>> Could you please clarify the dates for 12.2.0.1, 18c and 19c??

**Comment by MikielAgutu** [comment]
Refer to https://flywaydb.org/download/faq#how-long-are-database-releases-supported-in-each-edition-of-flyway.

Community edition support is guaranteed for 5 years since the general availability release of a database.
