### ISSUE TITLE
Parsing bug: unable to decrease block depth below 0

### ISSUE THREAD

**Issue by goranpaues-tradedoubler** [flyway/flyway#2916]
###### Which version and edition of Flyway are you using?
6.4.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
Yes, reproduced in 6.5.5

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Oracle 19c

###### Which operating system are you using?
Windows

###### What did you do?
Ran "flyway migrate" with repeatable migration 
[R___DB_ADM_PKG_BODY.zip](https://github.com/flyway/flyway/files/5160787/R___DB_ADM_PKG_BODY.zip)
The package includes conditional compilation.

###### What did you expect to see?
That repeatable migration succeeded.

###### What did you see instead?
Flyway Community Edition 6.4.0 by Redgate
Database: jdbc:oracle:thin:@localhost:5513/dev2 (Oracle 19.0)
Successfully validated 1202 migrations (execution time 00:01.303s)
Executing SQL callback: beforeMigrate -
Current version of schema "TDSYS": 2020.929.4
WARNING: outOfOrder mode is active. Migration of schema "TDSYS" may not be reproducible.
WARNING: Schema "TDSYS" has a version (2020.929.4) that is newer than the latest available migration (2020.910.132) !
ERROR: Unable to parse statement in .\Source\admin\packages\R___DB_ADM_PKG_BODY.sql at line 1 col 1: Flyway parsing bug:
 unable to decrease block depth below 0

**Comment by DoodleBobBuffPants** [comment]
Hi. We couldn't reproduce this error. Could you remove the conditional compilation to see if that is the issue?

**Comment by goranpaues-tradedoubler** [comment]
I tried again now with Flyway 6.5.5 and it works. It must have been an issue in 6.4.0 only, I think I forgot to switch path before when trying to reproduce with latest version. Thank you and sorry!
