### ISSUE TITLE
Allow for injectable S3 Client

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [flyway/flyway#2919]
###### Which version and edition of Flyway are you using?

`7.0.0-beta1`

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

This is on (and only relevant to) latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

Postgres

###### Which operating system are you using?

OSX

##### Suggestion

I think this feature is amazing, and one thing I think would make it even more amazing is allowing the user to inject the S3Client, freeing them to use tools such as LocalStack. 

Was browsing thru this [commit](https://github.com/flyway/flyway/commit/b3fd2f95221cea844e88eb1502640a90fa242649) and I don't think this is currently feasible in the existing implementation.  Looks like it just sets up a default `S3Client s3 = S3Client.create();` on read and goes on its merry way.  
 
Furthermore, this would allow the user to *not have to do the following from the blogpost 

> To use AWS S3, the AWS environment variables AWS_REGION, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY need to be set to the appropriate values for your S3 account

Though, to be fair, I looked thru the code a tad and this may not even be true, I believe the way you guys have it setup should follow the standard AWS cred model, which would look thru a host of places, include env, cred file, etc.  

Anyway, cheers, this feature is awesome just wanna help make it more awesome :>

**Comment by DoodleBobBuffPants** [comment]
Closed by https://github.com/flyway/flyway/commit/d17dac86a93da0709b0a42e6ef57bb8d46dcc2a2

**Comment by juliahayward** [comment]
Will be shipped in v7.0.1.

**Comment by juliahayward** [comment]
As a result of #2969 #2970 we can't do the fluent interface - sorry, my fault! 7.0.2 will have to back that part out. So the API will be the much less elegant `S3ClientFactory.setClient(customClient)`, which is already in 7.0.1
