### ISSUE TITLE
Log4J2 Support Without Requiring Bridge

### ISSUE THREAD

**Issue by TheSench** [flyway/flyway#2921]
I would like to be able to use Log4J2 loggers without needing to also include API JARs and a bridge for Apache Commons Logging or SLF4J.

###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.5.5

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I dropped the required logging JARs into the `/lib` folder of my Flyway deployment and verified that logs worked properly.

###### What did you expect to see?
I expected to be able to drop in the Log4J2 jars to enable logging.

###### What did you see instead?
I was required to also the `slf4j-api` and `log4j-slf4j-impl` jars.

**Comment by DoodleBobBuffPants** [comment]
Closed by c9e301a844985d82e1986da672500263e5fa4145

**Comment by juliahayward** [comment]
This will be shipped in v7.0.1.
