### ISSUE TITLE
Migrate all sql files when outOfOrder=true

### ISSUE THREAD

**Issue by jpgr79** [flyway/flyway#2923]
###### Which version and edition of Flyway are you using?
Latest version (free)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
DB2 v11.1.4.5

###### Which operating system are you using?
Windows 10

###### What did you do?
flyway migrate
In file flyway.conf i have flyway.outOfOrder=true

###### What did you expect to see?
I tried to migrate three sql files as an example: V2, V3 and V4. Migrate V2 was successful, but i had an error in migrate V3. I was expecting that with outOfOrder=true, flyway would mark V3 as pending and continue to V4. Later I would fix V3 and then flyway would migrate it out of order.

###### What did you see instead?
Following the previous example, Flyway stopped on V3 and did not migrate V4. I think this shouldn't happen if outOfOrder=true.

**Comment by Lyeeedar** [comment]
If a migration fails, it isn't safe for Flyway to continue migrating, as the migration may have had sideeffects that need to be cleanup up. If Flyway just continued migrating, it would be very difficult to identify and fix these failed migrations.

**Comment by jpgr79** [comment]
When outOfOrder = true you are already vulnerable to side effects. So why not let Flyway move on to the next migrations? It could ultimately be a configurable parameter.

In my particular project, we went through dozens of migrations to Quality and Production, with business configurations that rarely depend on each other.

We send the migrations to the DBAs and they respond with the errors to be corrected. We would need this feature to decrease the number of interactions with DBAs.

**Comment by MikielAgutu** [comment]
We don't think this is the right thing for Flyway.
