### ISSUE TITLE
Is the flyway supported for cross database migration?

### ISSUE THREAD

**Issue by sukhdevkhade** [flyway/flyway#2925]
###### Which version and edition of Flyway are you using?
 flyway-6.5.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which operating system are you using?

Windows as well as Linux 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?

Cross database Migration.

**Comment by DoodleBobBuffPants** [comment]
Hi. Flyway is indeed cross database. A list of supported databases can be found in our [documentation](https://flywaydb.org/documentation/).
