### ISSUE TITLE
Migrate fails leaving database in a bad state

### ISSUE THREAD

**Issue by yarhamjohn** [flyway/flyway#2935]
###### Which version and edition of Flyway are you using?
6.5.6

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
n/a

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command Line

###### Which database are you using (type & version)?
Oracle 18.3

###### Which operating system are you using?
Windows 10

###### What did you do?
Created a new user:
`CREATE USER test_user IDENTIFIED BY test_password;`

Did not then execute:
`GRANT UNLIMITED TABLESPACE TO test_user`, meaning I cannot insert data into tables.

Then ran `flyway migrate` with two simple scripts:
`V1__CreateTable.sql` - `CREATE TABLE test_user.Table1 (col NUMBER);`
`V2__CreateTable.sql` - `CREATE TABLE test_user.Table2 (col NUMBER);`

###### What did you expect to see?
I expected flyway to report an `ORA-01950: no privileges on tablespace 'USERS'` error and not make any changes to the database.

###### What did you see instead?
Flyway reported the `ORA-01950: no privileges on tablespace 'USERS'` error fine, but successfully migrated the first script (`V1__CreateTable.sql`), creating `Table1` and also added an empty `flyway_schema_history` table.

This has left the database/flyway history in a bad state - it would be nice if this could be prevented (maybe some sort of permission validation?).

**Comment by DoodleBobBuffPants** [comment]
There are many different ways of doing user permissions in Oracle and to do this work we would have to understand every oracle configuration. Instead you could attempt to create, insert, and delete into a table in a `beforeMigrate` callback to catch this error.

**Comment by yarhamjohn** [comment]
> There are many different ways of doing user permissions in Oracle and to do this work we would have to understand every oracle configuration.
That is fair enough.

Is there some way that flyway could at least ensure that the `flyway_schema_history` table reflects what has happened though? In my case, it successfully ran my first script but that is not listed in the table. It might well be fair to say that flyway thinks the script execution actually failed due to the grant issue, and the fact the object appears to have been created is an oracle peculiarity - if so I would still expect the schema history table to list a failed migration (V1) and for `flyway info` to return a failed migration and a pending one.

**Comment by DoodleBobBuffPants** [comment]
> Is there some way that flyway could at least ensure that the `flyway_schema_history` table reflects what has happened though?

In this case it can't. The schema under which it exists doesn't have the ability to insert into tables, so inserting a failed entry wouldn't be possible.

**Comment by yarhamjohn** [comment]
Ha thats true...

Darn this looks unsolvable

**Comment by nyctef** [comment]
> Instead you could attempt to create, insert, and delete into a table in a `beforeMigrate` callback to catch this error.

Isn't this something flyway could also do? Maybe insert a test row into the schema history table before starting migrations?

**Comment by DoodleBobBuffPants** [comment]
> Isn't this something flyway could also do? Maybe insert a test row into the schema history table before starting migrations?

While this would work for your case, it wouldn't work for everyone. If a user doesn't have delete privileges we end up polluting the schema history table with these test rows. Therefore this isn't something that should be in Flyway if it won't work ubiquitously, so closing this for now.
