### ISSUE TITLE
re-run failed sql scripts after a failed migration?

### ISSUE THREAD

**Issue by zhouwenyang** [flyway/flyway#2937]
I got a problem when sql scripts failed.
I cannot run the fixed sql scripts directly. 
what I have to do now is I have to run repair command first. and then migrate.

but what  I want is that when i fix the scripts it can automatically run failed scrips without "repair command"
because the repair command will update all checksum value. if somebody update other sql scripts in the same time.
some bad thing will happen in production.

**Comment by MikielAgutu** [comment]
You could run validate to see if the expected scripts have a checksum mismatch. If everything looks as expected, then you can run repair without concern of incorrectly overwriting script checksums.

Does that help?

**Comment by zhouwenyang** [comment]
You could run validate to see if the expected scripts have a checksum mismatch.
the problem is if i check it manually it will lose the meaning of CI\CD
so I just think a  trick, i'm not sure if it work.
can i just add a callback before validate and use the callback to delete the failed record from flyway_sheme_history.
then everything i do fly migrate it will delelte the failed record and run the sql scripts without flyway repair

**Comment by MikielAgutu** [comment]
We've shipped a paid feature called [cherry pick](https://flywaydb.org/blog/flyway-7.0.0-beta#cherry-pick-migrations) in Flyway 7 beta. It allows you to specify exact scripts to operate on. Currently it only supports migrate, but in light of this issue we've scheduled some work to add repair also. Keep an eye out for future releases.

In the meantime I think your workaround is a good option.
