### ISSUE TITLE
Configuring flyaway to look for migration scripts in build folder?

### ISSUE THREAD

**Issue by mikezliu** [flyway/flyway#2938]
I'm trying to figure out how to configure flyaway to look in the build folder instead of src folder for migration scripts.

My project structure:

```
Project
-- build
----resources
------main
--------migrations
----------v1__migration.sql
```

I have tried the following with no success:

```
spring.flyway.locations=classpath:main/migrations

Variations of:
spring.flyway.locations=classpath:../build/main/migrations
```

```
Flyway failed to initialize: none of the following migration scripts locations could be found:

	- classpath:main/migrations
```

**Comment by DoodleBobBuffPants** [comment]
Hi. The locations property looks on the classpath for the supplied locations, but you actually have to add the path to that location to the classpath in your project for non-default locations. In your case, you want to add the `build/resources` folder to the classpath in your project. Could you try that and let me know if it works?

**Comment by mikezliu** [comment]
That works, thanks!
