### ISSUE TITLE
No migrations found:  filtering out perfectly valid sql file?????

### ISSUE THREAD

**Issue by ZackingIt** [flyway/flyway#2943]
###### Which version and edition of Flyway are you using?
6.5.6

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using (type & version)?
postgresql

###### Which operating system are you using?
Linux 81a0390bd254 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

###### What did you do?
running `flyway migrate -X` with flyway.locations set to `filesystem:./../flyway/sql`

###### What did you expect to see?
Migration to be detected and running

###### What did you see instead?
```
DEBUG: Filtering out resource: ./../flyway/sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
DEBUG: Validating migrations ...
DEBUG: Filtering out resource: ./../flyway/sql/V0__Initial.sql (filename: V0__Initial.sql)
DEBUG: Filtering out resource: ./../flyway/sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
DEBUG: Filtering out resource: ./../flyway/sql/V0__Initial.sql (filename: V0__Initial.sql)
DEBUG: Filtering out resource: ./../flyway/sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
```

I believe this is due to having an empty schema --

```
Successfully validated 0 migrations (execution time 00:00.012s)
WARNING: No migrations found. Are your locations set up correctly?
Current version of schema "public": << Empty Schema >>
Schema "public" is up to date. No migration necessary.
```?  Must I define a schema for migrations to be picked up?

**Comment by ZackingIt** [comment]
I want to reconfirm -- the files are definitely found:

```
DEBUG: Scanning for filesystem resources at './../flyway/sql'
DEBUG: Scanning for resources in path: ./../flyway/sql (./../flyway/sql)
DEBUG: Found filesystem resource: ./../flyway/sql/V0__Initial.sql
DEBUG: Found filesystem resource: ./../flyway/sql/put-your-sql-migrations-here.txt
```

**Comment by ZackingIt** [comment]
CONFIRMED -- Need to add a schema to avoid having migrations skipped.  Please perhaps put this in an error message, aka, "NO SCHEMA DEFINED, SKIPPING MIGRATIONS" ?

**Comment by DoodleBobBuffPants** [comment]
Hi. I am unable to reproduce this, could you provide a minimal reproduction project?

**Comment by Lyeeedar** [comment]
If you look at the output, when it says its filtering out resources it is `DEBUG: Scanning for SQL callbacks ...`. When it ` DEBUG: Scanning for resources in path: ./../flyway/sql (./../flyway/sql)` it finds your sql, and parses it `Found statement at line 1: CREATE TABLE "supply"."ssp_logz" `

**Comment by ZackingIt** [comment]
Hi everyone -- was able to resolve this issue by correctly specifying the right db name.  However, I immediately came across a very similar issue which I've described in the following issue:
https://github.com/flyway/flyway/issues/2944
