### ISSUE TITLE
how to switch user/schema during the migrate?

### ISSUE THREAD

**Issue by zhouwenyang** [flyway/flyway#2945]
hi guys, I'm a DevOps consultant and one of our client using Oracle 11.2
they have multiple schemas in a database aka multiple projects and project teams.
and they also have one common schema which all teams may touch on. 
what they current do now is they can switch user during do the migration with their own BAT/Shell scripts. things like below.
1.user01_create_view.sql
2.user02_create_table.sql
they can identify which user they should use during the migrate within sql file name.

so I suggest the flyway tool for them and we are doing tools validations now. everything working perfect. except this req.

Q1:what is the best practise with flyway switch user/schema during the migrate? 
Q2:and another question I wonder is it possible to buy your tool with unlimited schema and time.
because the client cant apply for budget every year

**Comment by Lyeeedar** [comment]
For question 2 you want to email sales@flywaydb.org

**Comment by zhouwenyang** [comment]
@Lyeeedar thanks, what about Q1?

**Comment by Lyeeedar** [comment]
As for Q1, You can do this by putting an `ALTER SESSION SET CURRENT_SCHEMA=schema1` at the top of each migration file, or prefixing all your statements like `CREATE TABLE schema1.mytable`.

**Comment by zhouwenyang** [comment]
@Lyeeedar so it means i have to use a user that have permission for multiple schema. right?

**Comment by Lyeeedar** [comment]
That is correct. If you want to have different users, then you need to invoke flyway multiple times, and structure your migrations into seperate locations that can be independently executed.
