### ISSUE TITLE
Feature: Add possibility to configure wait timeout between flyway.connectRetries

### ISSUE THREAD

**Issue by holgerstolzenberg** [flyway/flyway#2953]
Which version and edition of Flyway are you using?
6.4.4

If this is not the latest version, can you reproduce the issue with the latest one as well?
Yes.

Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
- Java API via Spring Boot Integration

Which database are you using (type & version)?
- Postgres 12.3

Which operating system are you using?
- Podman based adoptopenjdk14 image

We are running a micro services stack based on Spring Boot apps and postgres databases. From time to time, the Flyway migrations integrated into the apps via Spring Boot fail due to a non finished startup of the postgres database. Of course there are solutions out there that try to address these issues deployment wise, still none of them is really straight forward, overcomplicating deployment.

Flyway overs a native solution to that. We managed to overcome the issue by using `flyway.connectRetries=10`. This is working for us, but configuring a higher number of retries will flood the logs on startup with errors. Configuring them away might hide other exception you wanna see.

In general this is a small problem, but being able to configure a `flyway.connectRetryWaitPeriodMs=5000` would be a cool thing instead of having to use the default hardcoded 1s period.

**Comment by Lyeeedar** [comment]
Related to https://github.com/flyway/flyway/issues/2847

**Comment by DoodleBobBuffPants** [comment]
Flyway V7 allows you to set [JDBC Properties](https://flywaydb.org/documentation/configuration/jdbcProperties). One such property for PostgreSQL is [connectionTimeout](https://jdbc.postgresql.org/documentation/head/connect.html). Would this allow you to achieve the same result?

**Comment by juliahayward** [comment]
I suspect not; this isn't about how long you wait before giving up on trying to get a connection and try again, it's how long you wait after a failure before you have another go. If the database is known to be very slow to spin up, Flyway could get quite spammy.

**Comment by holgerstolzenberg** [comment]
This is correct. If the database needs 10s to spin up with 10 retries configured, you´ll have 10 full stacktrace in the log.
If you know your DB takes some time, youll rather have 2 or 3 retries with a 10s timeout in between.

**Comment by mukul-atomicwork** [comment]
This is still not completed. Although it is marked as completed. The commit currently linked to this issue is for the backoff strategy of the connection failure. Connection failure doesn't mean there is no lock on the database and migration failed due to lock.
