### ISSUE TITLE
Can Flyway 7.0.0 be used without AWS SDK and related dependencies?

### ISSUE THREAD

**Issue by fstokke** [flyway/flyway#2957]
Flyway 7.0.0  includes the AWS S3 SDK as a dependency. The AWS S3 SDK includes a large number of other dependencies making the footprint of Flyway 7.0.0 significantly larger than the previous release.

Having a dependency on AWS S3 SDK seems uncessary if you are not using AWS. Can Flyway 7.0.0 be used without this dependency?

**Comment by MikielAgutu** [comment]
If you're not using AWS Flyway should be fine without this dependency. We'll investigate making this optional to reduce the footprint.

**Comment by vorburger** [comment]
We've run into this as well in https://github.com/apache/fineract/pull/1355, for https://issues.apache.org/jira/browse/FINERACT-1172, and had to work around it in https://github.com/apache/fineract/pull/1367/files. I'm not familiar with Flyway internals (and as a user wishing to upgrade probably shouldn't have to be), but why don't you simply do #2964 ?

**Comment by DoodleBobBuffPants** [comment]
Fixed in https://github.com/flyway/flyway/commit/d17dac86a93da0709b0a42e6ef57bb8d46dcc2a2
