### ISSUE TITLE
 Spanner support removed?

### ISSUE THREAD

**Issue by CarthageKing** [flyway/flyway#2958]
Hi,

We've been eagerly waiting for Flyway to support GCP Spanner. We saw some weeks back that this PR got merged: https://github.com/flyway/flyway/pull/2776

I pulled the following into a test project to see the Spanner support, but I couldn't find any of the Spanner classes inside:

```xml
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
		</dependency>
```

I tried this with both version 7.0.0-beta1 and 7.0.0.

Are we missing something?

**Comment by MikielAgutu** [comment]
Spanner support has been removed between the beta and the full V7 release. The beta was an experimental release designed to gather feedback, and we reserved the right to make significant/breaking changes. Unfortunately Spanner support wasn't up to our standards so we held it back from the full V7 release. It's likely to make it into a later release however.

**Comment by CarthageKing** [comment]
Does this mean we'll see it supported in a 7.x release or it's more of a 'Flyway version 8' kind of thing?

**Comment by MikielAgutu** [comment]
I can't give a definite timeframe, but we intend for Spanner support to be released as a V7 feature.

**Comment by CarthageKing** [comment]
Ok thank you for the update. I'll be closing this.

**Comment by thecloudgeek** [comment]
sorry for opening this back up..but is there an update on Spanner support in V7?
