### ISSUE TITLE
Unable to parse statement - CREATE OR REPLACE package body

### ISSUE THREAD

**Issue by mLarsenAlkaDk** [flyway/flyway#2959]
###### Which version and edition of Flyway are you using?

Flyway Enterprise Edition 6.5.7 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Not sure because it's part of Redgate Change Control

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Redgate Change Control 3.15.11152
Witch client it uses i don't know, but i have tried Flyway Command-line(migrate) in the the RCC folder and it gives the same error

###### Which database are you using (type & version)?

Oracle Database 12.2.0.1.0

###### Which operating system are you using?

Flyway: Windows 10 1909
Database: Oracle Linux Server 7.8

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Trying to create a change script with RCC
It also happens when i try to do "flyway migrate"

###### What did you expect to see?

The completion of a change script

###### What did you see instead?

[rcc-output.log](https://github.com/flyway/flyway/files/5307070/rcc-output.log)

**Comment by DoodleBobBuffPants** [comment]
Could you provide the original script? The attached log isn't readable

**Comment by mLarsenAlkaDk** [comment]
The script looks like that, because it's compiled PL SQL code

**Comment by mLarsenAlkaDk** [comment]
One extra information is that the log dumps the rest of the baseline script in the log and i had not uploaded that because it is +110 MB, so i have only attached the script at witch point it failed.

**Comment by DoodleBobBuffPants** [comment]
Without the script before it was compiled/wrapped it won't be possible to identify what Flyway failed to parse. Would you be able to provide the script before it was compiled?

**Comment by mLarsenAlkaDk** [comment]
As it's not our own i'm not sure i can give you that code.
Is it not possible to identify the problem without?

**Comment by DoodleBobBuffPants** [comment]
Currently the error points us to a line that doesn't exist in the compiled version which means it isn't possible to identify what the parser is failing on.

Firstly I'd like to verify if the contents of the log is the entire compiled SQL?

Secondly, would you be able to attempt the migration in flyway with debug output enabled (run `flyway migrate -X`)? The debug output might give more insight.

**Comment by mLarsenAlkaDk** [comment]
That line(388982) exists in my baseline sql and it's what you se in the log:

V001_20200928230958__baseline.sql
![image](https://user-images.githubusercontent.com/56872312/94808976-391b6e00-03f2-11eb-9021-1d7a92b4b5a9.png)

No it's not the whole log as i stated before, the rest of the log is the rest of the baseline SQL and +500000 lines, so i did not include that but this is the next part in the log:

Redgate Change Control-2020_09_28_20_34.log
![image](https://user-images.githubusercontent.com/56872312/94810236-0d00ec80-03f4-11eb-801f-0e94e36e3022.png)

I will try to run `flyway migrate -X`
