### ISSUE TITLE
AWS SDK not found on 7.0.0 command line

### ISSUE THREAD

**Issue by caterpaula** [flyway/flyway#2960]
###### Which version and edition of Flyway are you using?
7.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
MySQL 5.7

###### Which operating system are you using?
macOS Catalina 10.15.6

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Run Flyway 7 docker image with following env vars set:
`AWS_REGION`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `FLYWAY_USER`, `FLYWAY_PASSWORD`

`flyway -schemas=test_schema -locations=s3:<bucketname>/<folders> migrate`
(with bucketname and folders pointing to a valid S3 bucket)

I also ran:
`flyway -schemas=test_schema -locations=filesystem:<path-to-folder> migrate`

###### What did you expect to see?
I expected migrations from the S3 bucket to be run, and migrations from the filesystem to be run

###### What did you see instead?
Migrations from the file system were successfully run.

Migrations from S3 resulted in this error message:
`ERROR: Can't read location s3:<bucketname>/<folders>; AWS SDK not found`

**Comment by vorburger** [comment]
#2957 is perhaps related to this?

**Comment by DoodleBobBuffPants** [comment]
Closing as this is somewhat fixed in https://github.com/flyway/flyway/commit/d17dac86a93da0709b0a42e6ef57bb8d46dcc2a2.

You now have to provide the AWS SDK and dependencies manually as we won't be shipping with it
