### ISSUE TITLE
Flyway 7 fails to migrate SPs with transactions

### ISSUE THREAD

**Issue by AigleeK** [flyway/flyway#2961]
###### Which version and edition of Flyway are you using?
Flyway 7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
SQL Server 2017

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Migrate an R file of an SP that has a BEGIN TRAN and COMMIT TRAN

###### What did you expect to see?
It should create the SP

###### What did you see instead?
ERROR: Unable to parse statement in Operational\sql\Enterprise\SmartDrop\Stored Procedures\R__SmartDrop.CFG_CARRIER_Insert.sql at line 5 col 1. See https://flywaydb.org/documentation/knownparserlimitations for more information: Incomplete statement at line 5 col 1: CREATE OR ALTER PROCEDURE [SmartDrop].[CFG_CARRIER_Insert]

**Comment by DoodleBobBuffPants** [comment]
Hi. Could you provide a reproduction script?

**Comment by AigleeK** [comment]
`CREATE OR ALTER PROCEDURE [Test]
AS
BEGIN
    BEGIN TRAN
        SELECT 1;
    COMMIT TRAN;
END;`

**Comment by AigleeK** [comment]
[R__Test.zip](https://github.com/flyway/flyway/files/5319138/R__Test.zip)
