### ISSUE TITLE
Spring Boot fails to start after upgrading to Flyway 7.0.0

### ISSUE THREAD

**Issue by donalmurtagh** [flyway/flyway#2962]
###### Which version and edition of Flyway are you using?
7.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Spring Boot 2.3.4 built with Gradle

###### Which database are you using (type & version)?
Postgres

###### Which operating system are you using?
OS X

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I upgraded from Flyway 6.5.6 to 7.0.0. The relevant entries in `build.gradle` are shown below.
```groovy
buildscript {
  ext {
    flywayVersion = "7.0.0" // changed from 6.5.6
  }
}

plugins {
  id "org.flywaydb.flyway" version "${flywayVersion}"
}

dependencies {
  implementation "org.flywaydb:flyway-core:${flywayVersion}"
}

flyway {
  url = "jdbc:postgresql://0.0.0.0:5432/postgres"
  user = "postgres"
  password = "secret"
}
```

###### What did you expect to see?
The application starting up without errors

###### What did you see instead?
The following error occurs when I start the app e.g. with `./gradlew bootRun`

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65)

The following method did not exist:

    'int org.flywaydb.core.Flyway.migrate()'

The method's class, org.flywaydb.core.Flyway, is available from the following locations:

    jar:file:/Users/donal/.gradle/caches/modules-2/files-2.1/org.flywaydb/flyway-core/7.0.0/623494c303c62080ca1bc5886098ee65d1a5528a/flyway-core-7.0.0.jar!/org/flywaydb/core/Flyway.class

The class hierarchy was loaded from the following locations:

    org.flywaydb.core.Flyway: file:/Users/donal/.gradle/caches/modules-2/files-2.1/org.flywaydb/flyway-core/7.0.0/623494c303c62080ca1bc5886098ee65d1a5528a/flyway-core-7.0.0.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.flywaydb.core.Flyway
```

**Comment by DoodleBobBuffPants** [comment]
This is due to Spring Boot not yet being compatible with a breaking change made in Flyway 7. You can read more [here](https://github.com/spring-projects/spring-boot/issues/23514).
