### ISSUE TITLE
Password masking when using FLYWAY_URL

### ISSUE THREAD

**Issue by dcarley** [flyway/flyway#2966]
###### Which version and edition of Flyway are you using?

```
$ docker run --rm -ti flyway/flyway:7 -v
Flyway Community Edition 7.0.0 by Redgate
```

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

CLI

###### Which database are you using (type & version)?

```
$ docker run --rm -ti postgres:9.6 -V
postgres (PostgreSQL) 9.6.19
$ docker run --rm -ti -e POSTGRES_USER=test_user -e POSTGRES_PASSWORD=test_pass -e POSTGRES_DB=test_db -p 5432:5432 --network flyway --name postgres postgres:9.6
```

###### Which operating system are you using?

Linux (via Docker on Mac, in this reproduction case)

###### What did you do?

1. Ran a migration with a password in `FLYWAY_URL` and debug mode enabled:
    ```
    $ docker run --network flyway --rm -ti -v "$(pwd)/fixtures:/flyway/sql" -e FLYWAY_URL='jdbc:postgresql://postgres:5432/test_db?user=test_user&password=test_pass' flyway/flyway:7 migrate -X
    ```
1. Ran a migration with an incorrect password in `FLYWAY_URL`:
    ```
    $ docker run --network flyway --rm -ti -v "$(pwd)/fixtures:/flyway/sql" -e FLYWAY_URL='jdbc:postgresql://postgres:5432/test_db?user=test_user&password=wrong_pass' flyway/flyway:7 migrate
    ```

###### What did you expect to see?

The password to be masked out in the debug output and connection errors, in the same way as it is when using `FLYWAY_PASSWORD`:
```
DEBUG: flyway.password -> *********
```

###### What did you see instead?

1. Debug mode:
    ```
    DEBUG: Multiple databases found that handle url 'jdbc:postgresql://postgres:5432/test_db?user=test_user&password=test_pass'. CockroachDB, PostgreSQL
    DEBUG: Multiple databases found that handle url 'jdbc:postgresql://postgres:5432/test_db?user=test_user&password=test_pass'. CockroachDB, PostgreSQL
    DEBUG: Using configuration:
    DEBUG: flyway.jarDirs -> /flyway/jars
    DEBUG: flyway.locations -> filesystem:sql
    DEBUG: flyway.url -> jdbc:postgresql://postgres:5432/test_db?user=test_user&password=test_pass
    DEBUG: Multiple databases found that handle url 'jdbc:postgresql://postgres:5432/test_db?user=test_user&password=test_pass'. CockroachDB, PostgreSQL
    ```
1. Incorrect password:
    ```
    ERROR:
    Unable to obtain connection from database (jdbc:postgresql://postgres:5432/test_db?user=test_user&password=wrong_pass) for user 'null': FATAL: password authentication failed for user "test_user"
    ```

**Comment by MikielAgutu** [comment]
I don't think this is essential. As you've observed, you can explicitly supply a password to Flyway outside of the url, and in that case the password is masked. However I suppose it's nice to have as a feature.

**Comment by dcarley** [comment]
Thanks for the prompt triage. I think it's important because the inconsistency, depending on which method you use to pass credentials, makes it easy to leak sensitive values to places like centralised logging systems without realising it.
