### ISSUE TITLE
Placeholder documentation is broken

### ISSUE THREAD

**Issue by cheppsn** [flyway/flyway#2967]
The [placeholder documentation](https://flywaydb.org/documentation/configuration/placeholder.html) on the Flyway homepage is broken in parts.

###### What did you expect to see?
- After the "Flyway also provides default placeholders, whose values are automatically populated:" I would expect to see a list of supported placeholders. Portion of the documentation seems to be missing, that is probably also the reason why the section header size below "Default Placeholders" are off (those are not supposed to be subsections).

![image](https://user-images.githubusercontent.com/5145827/95236703-8c812800-0807-11eb-90c4-6acad47f608b.png)

- At the bottom of the page there is a Maven section and above it should be a Gradle section. However, the Gradle section is merged with the API code: 

![image](https://user-images.githubusercontent.com/5145827/95236737-9c007100-0807-11eb-9370-ac89166977c6.png)

###### What did you see instead?
- List of flyway default placeholders
- Example of placeholder configuration with Gradle

**Comment by DoodleBobBuffPants** [comment]
Thanks for spotting this. The page has now been fixed
