### ISSUE TITLE
Flyway removed from jcenter

### ISSUE THREAD

**Issue by jeggy** [flyway/flyway#2975]
It seems like a lot of flyway versions have been removed from jcenter.

This issue is blocking us from doing any new builds as are CI pipelines are not able to download anything.

###### Which version and edition of Flyway are you using?
6.5.5

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle & JCenter

###### What did you expect to see?
I expect to have all versions available at this location: https://bintray.com/redgate/Flyway/org.flywaydb%3Aflyway-core

###### What did you see instead?
```
 Could not resolve org.flywaydb:flyway-core:6.5.5.
     Required by:
         project : > org.flywaydb.flyway:org.flywaydb.flyway.gradle.plugin:6.5.5 > gradle.plugin.org.flywaydb:gradle-plugin-publishing:6.5.5
      > Could not resolve org.flywaydb:flyway-core:6.5.5.
         > Could not get resource 'https://plugins.gradle.org/m2/org/flywaydb/flyway-core/6.5.5/flyway-core-6.5.5.pom'.
            > Could not GET 'https://repo.jfrog.org/artifactory/libs-release-bintray/org/flywaydb/flyway-core/6.5.5/flyway-core-6.5.5.pom?referrer'.
               > Read timed out
```

**Comment by jeggy** [comment]
I can see it's still available on [MavenCentral](https://search.maven.org/artifact/org.flywaydb/flyway-core/6.5.5/jar), so for my projects that needs to be released now I have just added mavenCentral to my repositories within build.gradle.

But I would love to see these packages back at JCenter as we are using flyway at multiple different projects.

**Comment by juliahayward** [comment]
They weren't removed; Flyway stopped shipping to JCenter at v3. We've deleted the repo at JCenter now so that it will simply proxy through to Maven Central; https://jcenter.bintray.com/org/flywaydb/flyway-core/maven-metadata.xml is now showing versions up to and including 7.0.2.
