### ISSUE TITLE
Enterprise Gradle plugin throwing "Missing license key" first time it executes per version

### ISSUE THREAD

**Issue by friscoMad** [flyway/flyway#2978]
###### Which version and edition of Flyway are you using?
7.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle Plugin

###### Which database are you using (type & version)?
Reproducible in Mysql 5.7 and PG 10.14

###### Which operating system are you using?
MacOs 10.15

###### What did you do?

Trace:
```
$ ../gradlew flywayInfo

> Configure project :

> Task :1-returnly_prod_v3:flywayInfo FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':XXXXX:flywayInfo'.
> Error occurred while executing flywayInfo
  Missing license key. Ensure flyway.licenseKey is set to a valid Flyway license key ("FL01" followed by 512 hex chars)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

gradle config:

```
apply plugin: 'org.flywaydb.enterprise.flyway'

ext {
    flyway_db_user = 'root'
    db_host = project.findProperty('db_host') ?: 'localhost'
    db_port = 3306
    flyway_locations.addAll((project.findProperty('flyway_extra_locations') ?: '').toString().split(',')
            .collect {it == '' || it.contains(':') ? it : "filesystem:$it"})
    logger.lifecycle("flyway: $flyway_db_user@$db_host:$db_port/$db_schema ; looking for migrations in: $flyway_locations")
}

flyway {
    url = "jdbc:mysql://${db_host}:${db_port}?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8"
    user = flyway_db_user
    password = ''
    schemas = [ db_schema ]
    locations = flyway_locations
    if (placeholders == null) 
        placeholders = new LinkedHashMap()
    placeholders.put('current-schema', db_schema)
    outOfOrder = true
}

tasks.matching { it.name.startsWith('flyway') }.forEach { it.logging.level = LogLevel.INFO }
```
build.gradle 

```
buildscript {
    apply from: "$sharedScripts/plugin-repos.gradle", to: buildscript

    dependencies {
        classpath "org.flywaydb.enterprise:flyway-gradle-plugin:$flyway_version"
    }
}
```

###### What did you expect to see?

I would expect no issues as Info is a non restricted operation, but always failing is also consistent.

###### What did you see instead?

To work or fail every time.

**Comment by friscoMad** [comment]
This is the same issue reported in #2248
I can reproduce it easily just changing the version I want to use and running any flyway task (for example switching back and forward between 7.0.2 and 7.0.3)

**Comment by DoodleBobBuffPants** [comment]
How are you supplying the license key?

**Comment by friscoMad** [comment]
That's the interesting thing I am not passing the license by any means that I know. We are migrating several projects from 5.1.4 to 7.0.X while also moving to the maven central repo.
Previously it was working without a license (just the one to get the plugin from your old repo) so when I saw the error I added the license and worked, but in another project, I did not add the license and found out that it works after the first error.
Tried with several commands (info, migrate, undo, clean) and after the first error in any command all work without issues.

I have checked env vars and there is nothing there worth noting.
Tested with gradle 6.6.1 and 5.4.1 without any major difference.
From time to time I get the same error again, but doing a `gradle clean` or deleting project `.gradle` folder does not trigger the error.
The only consistent way I have found to reproduce the issue is changing flyway version.

**Comment by DoodleBobBuffPants** [comment]
Thank you very much for spotting this! This will be fixed for 7.0.4

**Comment by friscoMad** [comment]
Just to confirm, in 7.0.4 license key will be required to be configured for flyway to work regardless of the type of operation we are performing, right?

**Comment by DoodleBobBuffPants** [comment]
That is correct
