### ISSUE TITLE
CockroachDB migrations not run within a transaction. Is there a way to force transaction on for certain migration??

### ISSUE THREAD

**Issue by noobgramming** [flyway/flyway#2979]
###### Which version and edition of Flyway are you using?
7.0.3 community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
CockroachDB 20.1.7

###### Which operating system are you using?
Linux

###### What did you do?
trying to change primary key type

###### What did you expect to see?
migration success

###### What did you see instead?
failure because Flyway doesn't run CockroachDB migrations within a transaction. CockroachDB does not allow removing a primary key without adding another in the same transaction. Since Flyway isn't running CockroachDB migrations in a transaction, you can't modify the PK's at all :( 

```sql 
ALTER TABLE blah ADD COLUMN IF NOT EXISTS new_id UUID NULL;
UPDATE blah SET new_id = CAST(LPAD(TO_HEX(id), 32, '0') AS UUID); -- convert existing int keys to UUID
ALTER TABLE blah ALTER COLUMN new_id SET NOT NULL;
ALTER TABLE blah DROP CONSTRAINT IF EXISTS blah_pkey; -- for Postgres backwards compat
ALTER TABLE blah DROP CONSTRAINT IF EXISTS "primary"; -- CRDB uses diffrent default PK names, annoying
ALTER TABLE blah DROP COLUMN IF EXISTS id;
ALTER TABLE blah RENAME COLUMN new_id TO id;
ALTER TABLE blah ADD PRIMARY KEY (id);
```

result:

```Migration V20201014220621__CRDB_UUID_PK.sql failed
------------------------------------------------------------------
SQL State  : XXUUU
Error Code : 0
Message    : ERROR: primary key of table blah dropped without subsequent addition of new primary key
Location   : db/migration/V20201014220621__UUID_PK.sql (~removed~)
Line       : 11
Statement  : ALTER TABLE blah DROP CONSTRAINT IF EXISTS "primary"
```

transactions appear to be disabled here: 
https://github.com/flyway/flyway/blob/e0d17cf987f6bcbfb466202931ffb2e82d1de948/flyway-core/src/main/java/org/flywaydb/core/internal/database/cockroachdb/CockroachDBParser.java#L45

**Comment by DoodleBobBuffPants** [comment]
Hi. I'm unable to reproduce this, could you provide a minimal reproduction script/project? Also you can tell Flyway to execute migrations in a transaction on a per script basis with [script config files](https://flywaydb.org/documentation/configuration/scriptconfigfiles#reference). Could you try that too?

**Comment by noobgramming** [comment]
I'm trying to reproduce with Postgres since its CockroachDB compatible. I will try using config files to force transactions on these migrations... I'm starting to think this is a CockroachDB bug

**Comment by noobgramming** [comment]
I used the per-migration configuration to narrow this down, its a bug in CockroachDB. Closing this
