### ISSUE TITLE
Unable To Run Flyway With AWS Secrets Manager Driver

### ISSUE THREAD

**Issue by rmoyersrfd** [flyway/flyway#2982]
###### If this is not the latest version, can you reproduce the issue with the latest one as well? Didn't try
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

We purchased the Pro edition recently, and aren't prepared to buy another license quite yet - so no upgrade to v7 yet.

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Followed the instructions for using Secrets Manager with a RDS Postgres database
See attached ZIP containing:
run_flyway.cmd - Windows command file for running Flyway
RunConsole.log - output from the run
flyway_secman_postgres.conf - configuration file tried removing the flyway.driver line. Fails with or without it the same way.

###### What did you expect to see?
I expected it to run my migrate

###### What did you see instead?
Oct 20, 2020 6:24:08 PM org.flywaydb.core.internal.logging.apachecommons.ApacheCommonsLog error
SEVERE: Invalid JDBC URL (should start with jdbc:) : jdbc-secretsmanager:postgresql://localhost:24850/mi_espoperational

[FlywayProblem.zip](https://github.com/flyway/flyway/files/5412255/FlywayProblem.zip)

**Comment by DoodleBobBuffPants** [comment]
Hi. Secrets Manager is only available from Flyway V7. Your existing license should work with all versions of Flyway too.

**Comment by rmoyersrfd** [comment]
I was able to make Flyway 6.4.3 work with Secrets Manager. I had to make a few small changes to the Secrets Manager Driver though. Will try Flyway V7 also
