### ISSUE TITLE
[Minor] Slf4j Detection with Slf4j 1.8/2.0

### ISSUE THREAD

**Issue by A248** [flyway/flyway#2984]
I just thought I would let you know that Slf4j 1.8.0/2.0.0 no longer uses `org.slf4j.impl.StaticLoggerBinder`, therefore [this line](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/FeatureDetector.java#L121) in FeatureDetector will fail to detect these versions of Slf4j.

Instead, slf4j will rely on the ServiceLoader mechanism to find the logger factory:

> More specifically, when initializing the LoggerFactory class will no longer search for the StaticLoggerBinder class on the class path. – http://www.slf4j.org/faq.html#changesInVersion18

As a result Flyway will not detect slf4j although this is the intention of LogCreatorFactory.

----------------------------
Bug template:
###### Which version and edition of Flyway are you using?
Flyway 7.0.4 community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
7.0.4 is the latest as of writing this

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
HSQLDB 2.5.1

###### Which operating system are you using?
Mac OS X

###### What did you do?
Run this:
```java
package flywaydb.slf4j2;

import org.flywaydb.core.internal.util.FeatureDetector;

public class FlywaySlf4j2Main {

	public static void main(String[] args) {
		boolean slf4j = new FeatureDetector(FlywaySlf4j2Main.class.getClassLoader()).isSlf4jAvailable();
		System.out.println("Has slf4j: " + slf4j);
	}
	
}
```

###### What did you expect to see?
"Has slf4j: true" using slf4j 1.8.0/2.0.0

###### What did you see instead?
"Has slf4j: false" using slf4j 1.8.0/2.0.0

When using slf4j 1.7.30, it is correctly detected.

**Comment by juliahayward** [comment]
This isn't as easy as it might seem. When using the AWS SDK for S3 storage, that embeds a version of the SLF4J API (at 1.7, natch) which gets picked up by the feature detector. Looking for the `StaticLoggerBinder` made sure there was a concrete implementation underlying the `Logger`, and taking out that check results in 

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

when trying to use S3, with log output going to the console. We'll carry on looking, but there may be wider ramifications.
