### ISSUE TITLE
Cassandra db migration by using Flyway

### ISSUE THREAD

**Issue by anandey** [flyway/flyway#2985]
###### Which version and edition of Flyway are you using?

Hello Team,

I want to implement Cassandra Db Migration by using Flyway, Could you help on the steps please?

Regards,
Anand.

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by DoodleBobBuffPants** [comment]
Hi. Flyway doesn't currently support Cassandra, so closing this issue (and because it is already mentioned in https://github.com/flyway/flyway/issues/823)
