### ISSUE TITLE
Getting a MariaDB warning when the flyway_schema_history is first created

### ISSUE THREAD

**Issue by willy0275** [flyway/flyway#2988]
###### Which version and edition of Flyway are you using?

7.0.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

MariaDB 10.3.18

###### Which operating system are you using?

CentOS 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I'm runnin 'flyway baseline' on an existing database without Flyway

###### What did you expect to see?

No error or warning

###### What did you see instead?

When it creates the flyway_schema_history I'm getting the warning "WARNING: DB: Name 'flyway_schema_history_pk' ignored for PRIMARY key. (SQL State:  - Error Code: 1280)". I did some research and it's because MySQL/MariaDB (at least more recent versions, an older version of MariaDB didn't give the warning) don't allow a custom index name for the PRIMARY KEY. It will give a warning and use "PRIMARY" as the name. This is really not obvious and if it's ever possible I think "PRIMARY" should be used for the primary key name for MySQL/MariaDB or at least no name provided, which will then use the default one.

**Comment by jjanczur** [comment]
Hi I got the same error

`[WARNING] DB: Name 'PK_REPORTS' ignored for PRIMARY key. (SQL State:  - Error Code: 1280)`

Flyway version
7.11.0
