### ISSUE TITLE
Migration with version 7.0.4 on Oracle hangs for several minutes

### ISSUE THREAD

**Issue by kasgilpofi** [flyway/flyway#2989]
###### Which version and edition of Flyway are you using?
7.0.4 Teams Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven Plugin

###### Which database are you using (type & version)?
Oracle Database 19c Enterprise Edition

###### Which operating system are you using?
Windows

###### What did you do?
Created a maven project (https://flywaydb.org/documentation/getstarted/firststeps/maven).
Added 200 CREATE TABLE Files ("create table TABLE1 (ID int not null,  NAME varchar(100) not null);", ...)
Called `mvn flyway:migrate`

###### What did you expect to see?
A similar performance as with version 6.5.5

###### What did you see instead?
It hangs for ~2 minutes, migrates the 200 files, hangs again for ~2 minutes, then finishes.

Version 7.0.4 Teams Edition: `Total time: 05:50 min`

Version 7.0.4 Community Edition: `Total time: 01:25 min`

Version 6.5.5 Pro Edition: `Total time: 58.528 s`

Version 6.5.5 Community Edition: `Total time: 57.870 s`

**Comment by MikielAgutu** [comment]
I'm unable to reproduce this. I've created 200 migrations with create table statements, and it doesn't hang.

I can't think of anything that Teams would be doing compared with Community that would produce such a long wait. Could you share the debug log for a run with Teams, and a log for a run with Community in 7.0.4? I'd like to compare what's different between the editions.

**Comment by kasgilpofi** [comment]
I ran it with the profiler.
The 2 minutes at the start and end are used in OracleDatabaseType.createParser(), because in the Teams Edition, it opens a new connection to determine the oracleUser, oracleConnectIdentifier, oracleOVersion and oracleORelease.

OracleDatabaseType.createParser() is called for every migration file, once in Flyway.migrate() and once in Flyway.info().
So it opens 400 connections and calls 1200x JdbcTemplate.queryForString() for getting information about the Database, that could be cached.


![grafik](https://user-images.githubusercontent.com/73525807/97316029-9d9ee100-1869-11eb-998a-889d3aa76a80.png)

![grafik](https://user-images.githubusercontent.com/73525807/97316096-aa233980-1869-11eb-85d5-c0c7d9675e26.png)
