### ISSUE TITLE
Oracle: Insufficient privileges creating objects under Flyway-created schemas

### ISSUE THREAD

**Issue by Sam-Redgate** [flyway/flyway#2990]
###### Which version and edition of Flyway are you using?

7.0.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

Oracle 18.0

###### Which operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

When running `flyway migrate` to migrate a script containing a `CREATE MATERIALIZED VIEW` statement, it failed because of insufficient privileges.

![image](https://user-images.githubusercontent.com/55439156/97466374-effc0280-193a-11eb-8c6e-77479d2fa17b.png)

Since the schema didn't exist beforehand, Flyway created it prior to the migrate, but without the necessary `GRANT CREATE TABLE` and `GRANT CREATE MATERIALIZED VIEW` privileges for the new schema.

These two permissions are required for creating materialized views in Oracle.

![image](https://user-images.githubusercontent.com/55439156/97466433-01dda580-193b-11eb-8c0b-e6bfba434b03.png)

Manually creating a schema with these two privileges and the migration succeeds. Our tool uses Flyway to create schemas if they don't exist, so this is problematic for us for any migrations that include a materialized view.

###### What did you expect to see?

Migrations containing `CREATE MATERIALIZED VIEW` statements succeed with Flyway-provisioned schemas.

###### What did you see instead?

Migrations containing `CREATE MATERIALIZED VIEW` statements failed with Flyway-provisioned schemas.

**Comment by MikielAgutu** [comment]
Currently I think it's better for users to manually deal with schema creation if Flyway isn't able to do it correctly due to permissions. I suppose it's a trade off between convivence and security - [applying permissions because you *might* one day need them feels wrong](https://en.wikipedia.org/wiki/Principle_of_least_privilege).

In this case, you can apply the `GRANT`s you need in your versioned migrations.

I'm happy to revisit in case other users come across similar problems, so I'll keep this open for now.

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
