### ISSUE TITLE
Dry Run output - can it write to S3?

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2992]
From Grant Fritchey:

> No errors from this, but no .SQL file either:
> `docker run --rm -v <redacted> -enterprise  -url=<redacted> -dryRunOutput="https://s3.us-east-1.amazonaws.com/<redacted>/output.sql" migrate`

The dry run output currently only recognises local file system paths. It seems reasonable that as we can read from S3 when the relevant sdk is present, we could also write (perhaps using an `s3:<bucket>/<file>` syntax like the locations parameter)? This would allow us to run more cleanly in AWS CodePipelines.

**Comment by Lyeeedar** [comment]
If we are going to do this, we should support gcs too
