### ISSUE TITLE
MSSQL stored proc call from beforeEachMigrate script

### ISSUE THREAD

**Issue by esagardia** [flyway/flyway#2994]
###### Which version and edition of Flyway are you using?
Flyway 7.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line via docker

###### Which database are you using (type & version)?
MSSQL 14.0.3294.2

###### Which operating system are you using?
Running from docker image 

###### What did you do?
This is the script I want to run in beforeMigrate.sql script and this is working when executed from MSSQL client 2017 :
DECLARE @return_value int
DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
DECLARE @db_name VARCHAR(50)
DECLARE @snapshot_name VARCHAR(100)

SET @db_name = '${database}'
SET @snapshot_name = CONCAT(@db_name, @date)

EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name

SELECT @db_name, @return_value
where usp_create_snapshot is creating a snapshot of my DB

###### What did you expect to see?
This stored proc should create a snapshot of my DB

###### What did you see instead?
I see this error :

Migration beforeMigrate.sql failed
--
  | ----------------------------------
  | SQL State  : S0005
  | Error Code : 226
  | Message    : CREATE DATABASE statement not allowed within multi-statement transaction.
  | Location   : sql/beforeMigrate.sql (/flyway/sql/beforeMigrate.sql)
  | Line       : 1
  | Statement  : DECLARE @return_value int
  | DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
  | DECLARE @db_name VARCHAR(50)
  | DECLARE @snapshot_name VARCHAR(100)
  |  
  | SET @db_name = '5434.FTM2.TU'
  | SET @snapshot_name = CONCAT(@db_name, @date)
  |  
  | EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name
  |  
  | SELECT @db_name, @return_value
  |  
  | Caused by:
  | Migration beforeMigrate.sql failed
  | ----------------------------------
  | SQL State  : S0005
  | Error Code : 226
  | Message    : CREATE DATABASE statement not allowed within multi-statement transaction.
  | Location   : sql/beforeMigrate.sql (/flyway/sql/beforeMigrate.sql)
  | Line       : 1
  | Statement  : DECLARE @return_value int
  | DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
  | DECLARE @db_name VARCHAR(50)
  | DECLARE @snapshot_name VARCHAR(100)
  |  
  | SET @db_name = '5434.FTM2.TU'
  | SET @snapshot_name = CONCAT(@db_name, @date)
  |  
  | EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name
  |  
  | SELECT @db_name, @return_value
  |  
  | Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: CREATE DATABASE statement not allowed within multi-statement transaction.

**Comment by DoodleBobBuffPants** [comment]
Hi, I am unable to reproduce this. Could you provide a minimal reproduction script / project

**Comment by esagardia** [comment]
Hello,

Here is the content of usp_create_snapshot :

CREATE procedure [dbo].[usp_create_snapshot] @db_name sysname, @snapshot_name sysname as 
begin
	declare @data_path nvarchar(260) = cast(serverproperty('InstanceDefaultDataPath') as nvarchar(260))
	declare @name sysname
	declare @physical_name nvarchar(260)
	declare @sql nvarchar(max) = N''
	set nocount on
	set @snapshot_name = N'snapshot_' + @snapshot_name 
	if not exists(select * from sys.databases where name = @db_name)
		return 1
	if exists(select * from sys.databases where name = @db_name and state > 0)
		return 1
	if exists(select * from sys.databases where name = @db_name) and 
		exists(select * from sys.databases where name = @snapshot_name and source_database_id = db_id(@db_name))
			return 1
	set @sql = N'create database ' + quotename(@snapshot_name) + N' on '
	declare curFile cursor for  
		select name from master.sys.master_files where type <> 1 and state = 0 and database_id = db_id(@db_name)
	open curFile 
	fetch next from curFile into @name
	while @@FETCH_STATUS = 0
	begin
		set @sql += N'(name = ''' + @name + N''', filename = ''' + @data_path + @snapshot_name + N'.ss''), '
		fetch next from curFile into @name
	end
	close curFile
	deallocate curFile
	set @sql = left(@sql, len(@sql) - 1)
	set @sql += N' as snapshot of ' + quotename(@db_name)
	exec sp_executesql @sql
end
GO

**Comment by esagardia** [comment]
In my beforeMigrate I call it : 
DECLARE @return_value int
DECLARE @Date VARCHAR(20) set @Date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
DECLARE @db_name VARCHAR(50)
DECLARE @snapshot_name VARCHAR(100)

SET @db_name = '${database}'
SET @snapshot_name = CONCAT(@db_name, @Date)

EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name

SELECT @db_name, @return_value


**And this is the error I get :
 Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: CREATE DATABASE statement not allowed within multi-statement transaction.**

**Comment by DoodleBobBuffPants** [comment]
I'm still unable to reproduce this. Running your scripts as they are works successfully, although I had to remove `[master]` from the line `EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name`. Could you also try this? If not, could you provide your full debug output? (run the Flyway command with `-X`)

**Comment by esagardia** [comment]
Did you use beforeMigrate ? In callback to test it ? 
Still not working.
With -X : 


DEBUG: Loading config file: /flyway/conf/flyway.conf
--
  | DEBUG: Unable to load config file: /flyway/?/flyway.conf
  | DEBUG: Unable to load config file: /flyway/flyway.conf
  | DEBUG: Adding location to classpath: /flyway/drivers/aws-secretsmanager-jdbc-1.0.5.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/derby-10.15.2.0.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/derbyclient-10.15.2.0.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/derbyshared-10.15.2.0.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/derbytools-10.15.2.0.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/google-cloud-spanner-jdbc-1.16.0.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/google-cloud-storage-1.111.2.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/h2-1.4.200.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/hsqldb-2.5.0.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/jaybird-jdk18-3.0.8.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/jna-4.5.2.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/jna-platform-4.5.2.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/jtds-1.3.1.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/mariadb-java-client-2.6.0.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/mssql-jdbc-7.2.0.jre8.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/mysql-connector-java-8.0.20.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/ojdbc8-19.6.0.0.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/postgresql-42.2.14.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/snowflake-jdbc-3.11.1.jar
  | DEBUG: Adding location to classpath: /flyway/drivers/sqlite-jdbc-3.30.1.jar
  | DEBUG: Using configuration:
  | DEBUG: flyway.jarDirs -> /flyway/jars
  | DEBUG: flyway.locations -> filesystem:sql
  | DEBUG: flyway.password -> ***********
  | DEBUG: flyway.placeholders.database -> 5434.FTM2.TU
  | DEBUG: flyway.schemas -> financial_transaction
  | DEBUG: flyway.url -> jdbc:sqlserver://WSIDADBMSQ01.res.bngf.local;databaseName=5434.FTM2.TU
  | DEBUG: flyway.user -> svc5434FTM2TU
  | DEBUG: Multiple databases found that handle url 'jdbc:sqlserver://WSIDADBMSQ01.res.bngf.local;databaseName=5434.FTM2.TU'. Azure Synapse, SQL Server
  | DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
  | DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@1698c449 ...
  | DEBUG: Unable to resolve location classpath:db/callback.
  | Flyway Community Edition 7.1.1 by Redgate
  | DEBUG: AWS SDK available: false
  | DEBUG: Google Cloud Storage available: false
  | DEBUG: Scanning for filesystem resources at 'sql'
  | DEBUG: Scanning for resources in path: sql (sql)
  | DEBUG: Found filesystem resource: sql/V1.0__Initial_version_mssql.sql
  | DEBUG: Found filesystem resource: sql/_V1.0__Initial_version_aurora.sql
  | DEBUG: Found filesystem resource: sql/beforeMigrate.sql
  | DEBUG: Found filesystem resource: sql/put-your-sql-migrations-here.txt
  | Database: jdbc:sqlserver://WSIDADBMSQ01.res.bngf.local:1433;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=5434.FTM2.TU;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 14.0)
  | DEBUG: Driver  : Microsoft JDBC Driver 7.2 for SQL Server 7.2.0.0
  | DEBUG: DDL Transactions Supported: true
  | DEBUG: Schemas: financial_transaction
  | DEBUG: Default schema: null
  | DEBUG: Scanning for SQL callbacks ...
  | DEBUG: Filtering out resource: sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
  | DEBUG: Validating migrations ...
  | DEBUG: Filtering out resource: sql/_V1.0__Initial_version_aurora.sql (filename: _V1.0__Initial_version_aurora.sql)
  | DEBUG: Filtering out resource: sql/beforeMigrate.sql (filename: beforeMigrate.sql)
  | DEBUG: Filtering out resource: sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
  | DEBUG: Filtering out resource: sql/V1.0__Initial_version_mssql.sql (filename: V1.0__Initial_version_mssql.sql)
  | DEBUG: Filtering out resource: sql/_V1.0__Initial_version_aurora.sql (filename: _V1.0__Initial_version_aurora.sql)
  | DEBUG: Filtering out resource: sql/beforeMigrate.sql (filename: beforeMigrate.sql)
  | DEBUG: Filtering out resource: sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
  | Successfully validated 2 migrations (execution time 00:00.800s)
  | DEBUG: Parsing beforeMigrate.sql ...
  | DEBUG: Found statement at line 1: DECLARE @return_value int
  | DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
  | DECLARE @db_name VARCHAR(50)
  | DECLARE @snapshot_name VARCHAR(100)
  |  
  | SET @db_name = '5434.FTM2.TU'
  | SET @snapshot_name = CONCAT(@db_name, @date)
  |  
  | EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name
  |  
  | SELECT @db_name, @return_value
  | Executing SQL callback: beforeMigrate -
  | DEBUG: Executing SQL: DECLARE @return_value int
  | DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
  | DECLARE @db_name VARCHAR(50)
  | DECLARE @snapshot_name VARCHAR(100)
  |  
  | SET @db_name = '5434.FTM2.TU'
  | SET @snapshot_name = CONCAT(@db_name, @date)
  |  
  | EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name
  |  
  | SELECT @db_name, @return_value
  | DEBUG: Rolling back transaction...
  | DEBUG: Transaction rolled back
  | ERROR: Unexpected error
  | org.flywaydb.core.api.FlywayException: Error while executing beforeMigrate callback:
  | Migration beforeMigrate.sql failed
  | ----------------------------------
  | SQL State  : S0005
  | Error Code : 226
  | Message    : CREATE DATABASE statement not allowed within multi-statement transaction.
  | Location   : sql/beforeMigrate.sql (/flyway/sql/beforeMigrate.sql)
  | Line       : 1
  | Statement  : DECLARE @return_value int
  | DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
  | DECLARE @db_name VARCHAR(50)
  | DECLARE @snapshot_name VARCHAR(100)
  |  
  | SET @db_name = '5434.FTM2.TU'
  | SET @snapshot_name = CONCAT(@db_name, @date)
  |  
  | EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name
  |  
  | SELECT @db_name, @return_value
  |  
  | at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.handleEvent(DefaultCallbackExecutor.java:139)
  | at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.execute(DefaultCallbackExecutor.java:132)
  | at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.access$000(DefaultCallbackExecutor.java:39)
  | at org.flywaydb.core.internal.callback.DefaultCallbackExecutor$2.call(DefaultCallbackExecutor.java:118)
  | at org.flywaydb.core.internal.callback.DefaultCallbackExecutor$2.call(DefaultCallbackExecutor.java:115)
  | at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
  | at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.execute(DefaultCallbackExecutor.java:115)
  | at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.onMigrateOrUndoEvent(DefaultCallbackExecutor.java:77)
  | at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:146)
  | at org.flywaydb.core.Flyway$1.execute(Flyway.java:215)
  | at org.flywaydb.core.Flyway$1.execute(Flyway.java:164)
  | at org.flywaydb.core.Flyway.execute(Flyway.java:538)
  | at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
  | at org.flywaydb.commandline.Main.executeOperation(Main.java:238)
  | at org.flywaydb.commandline.Main.main(Main.java:151)
  | Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException:
  | Migration beforeMigrate.sql failed
  | ----------------------------------
  | SQL State  : S0005
  | Error Code : 226
  | Message    : CREATE DATABASE statement not allowed within multi-statement transaction.
  | Location   : sql/beforeMigrate.sql (/flyway/sql/beforeMigrate.sql)
  | Line       : 1
  | Statement  : DECLARE @return_value int
  | DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
  | DECLARE @db_name VARCHAR(50)
  | DECLARE @snapshot_name VARCHAR(100)
  |  
  | SET @db_name = '5434.FTM2.TU'
  | SET @snapshot_name = CONCAT(@db_name, @date)
  |  
  | EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name
  |  
  | SELECT @db_name, @return_value
  |  
  | at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:273)
  | at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:218)
  | at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
  | at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory$SqlScriptCallback.handle(SqlScriptCallbackFactory.java:135)
  | at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.handleEvent(DefaultCallbackExecutor.java:137)
  | ... 14 more
  | DEBUG: Memory usage: 8 of 13M
  | Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: CREATE DATABASE statement not allowed within multi-statement transaction.
  | at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
  | at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
  | at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:868)
  | at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768)
  | at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
  | at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2930)
  | at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
  | at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
  | at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:744)
  | at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
  | at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
  | at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
  | ... 17 more

**Comment by DoodleBobBuffPants** [comment]
Thanks for sharing the output, I have now reproduced this. The underlying issue is transactions - to make this work you need to create a [script config file](https://flywaydb.org/documentation/configuration/scriptconfigfiles) `beforeMigrate.sql.conf` and add the line `executeInTransaction=false`

**Comment by esagardia** [comment]
Hi ! works well with beforeMigrate. Thanks!
I also tried it with **beforeEachMigrate** and it's not working. Is it something wanted ? 

DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /flyway/?/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Adding location to classpath: /flyway/drivers/aws-secretsmanager-jdbc-1.0.5.jar
DEBUG: Adding location to classpath: /flyway/drivers/derby-10.15.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbyclient-10.15.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbyshared-10.15.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbytools-10.15.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/google-cloud-spanner-jdbc-1.16.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/google-cloud-storage-1.111.2.jar
DEBUG: Adding location to classpath: /flyway/drivers/h2-1.4.200.jar
DEBUG: Adding location to classpath: /flyway/drivers/hsqldb-2.5.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/jaybird-jdk18-3.0.8.jar
DEBUG: Adding location to classpath: /flyway/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /flyway/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /flyway/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /flyway/drivers/mariadb-java-client-2.6.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/mssql-jdbc-7.2.0.jre8.jar
DEBUG: Adding location to classpath: /flyway/drivers/mysql-connector-java-8.0.20.jar
DEBUG: Adding location to classpath: /flyway/drivers/ojdbc8-19.6.0.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/postgresql-42.2.14.jar
DEBUG: Adding location to classpath: /flyway/drivers/snowflake-jdbc-3.11.1.jar
DEBUG: Adding location to classpath: /flyway/drivers/sqlite-jdbc-3.30.1.jar
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /flyway/jars
DEBUG: flyway.locations -> filesystem:sql
DEBUG: flyway.password -> ***********
DEBUG: flyway.placeholders.database -> 5434.FTM2.TU
DEBUG: flyway.schemas -> financial_transaction
DEBUG: flyway.url -> jdbc:sqlserver://WSIDADBMSQ01.res.bngf.local;databaseName=5434.FTM2.TU
DEBUG: flyway.user -> svc5434FTM2TU
DEBUG: Multiple databases found that handle url 'jdbc:sqlserver://WSIDADBMSQ01.res.bngf.local;databaseName=5434.FTM2.TU'. Azure Synapse, SQL Server
DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@1698c449 ...
DEBUG: Unable to resolve location classpath:db/callback.
Flyway Community Edition 7.1.1 by Redgate
DEBUG: AWS SDK available: false
DEBUG: Google Cloud Storage available: false
DEBUG: Scanning for filesystem resources at 'sql'
DEBUG: Scanning for resources in path: sql (sql)
DEBUG: Found filesystem resource: sql/V1.0__Initial_version_mssql.sql
DEBUG: Found filesystem resource: sql/_V1.0__Initial_version_aurora.sql
DEBUG: Found script configuration: beforeEachMigrate.sql.conf
DEBUG: Found filesystem resource: sql/beforeEachMigrate.sql
DEBUG: Found filesystem resource: sql/beforeEachMigrate.sql.conf
DEBUG: Found filesystem resource: sql/put-your-sql-migrations-here.txt
Database: jdbc:sqlserver://WSIDADBMSQ01.res.bngf.local:1433;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=5434.FTM2.TU;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 14.0)
DEBUG: Driver  : Microsoft JDBC Driver 7.2 for SQL Server 7.2.0.0
DEBUG: DDL Transactions Supported: true
DEBUG: Schemas: financial_transaction
DEBUG: Default schema: null
DEBUG: Scanning for SQL callbacks ...
DEBUG: Filtering out resource: sql/beforeEachMigrate.sql.conf (filename: beforeEachMigrate.sql.conf)
DEBUG: Filtering out resource: sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
DEBUG: Found script configuration: beforeEachMigrate.sql.conf
DEBUG: Validating migrations ...
DEBUG: Filtering out resource: sql/_V1.0__Initial_version_aurora.sql (filename: _V1.0__Initial_version_aurora.sql)
DEBUG: Filtering out resource: sql/beforeEachMigrate.sql (filename: beforeEachMigrate.sql)
DEBUG: Filtering out resource: sql/beforeEachMigrate.sql.conf (filename: beforeEachMigrate.sql.conf)
DEBUG: Filtering out resource: sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
DEBUG: Filtering out resource: sql/V1.0__Initial_version_mssql.sql (filename: V1.0__Initial_version_mssql.sql)
DEBUG: Filtering out resource: sql/_V1.0__Initial_version_aurora.sql (filename: _V1.0__Initial_version_aurora.sql)
DEBUG: Filtering out resource: sql/beforeEachMigrate.sql (filename: beforeEachMigrate.sql)
DEBUG: Filtering out resource: sql/beforeEachMigrate.sql.conf (filename: beforeEachMigrate.sql.conf)
DEBUG: Filtering out resource: sql/put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
Successfully validated 2 migrations (execution time 00:00.625s)
Current version of schema [financial_transaction]: null
DEBUG: Parsing V1.0__Initial_version_mssql.sql ...
DEBUG: Found statement at line 1: CREATE TABLE financial_transaction.monetary_transaction (id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
correlation_id VARCHAR(100) NOT NULL,business_id VARCHAR(100) NOT NULL,reply_to VARCHAR(60) NOT NULL,created_date DATETIME NOT NULL,
request_payload TEXT NOT NULL, response_payload TEXT, status VARCHAR(50) NOT NULL,
type VARCHAR(50) NOT NULL,updated_date DATETIME NOT NULL, version VARCHAR(20) NOT NULL);

create unique index UK_monetary_transaction on financial_transaction.monetary_transaction(correlation_id);

DEBUG: Starting migration of schema [financial_transaction] to version "1.0 - Initial version mssql" ...
DEBUG: **Using executeInTransaction=false from script configuration**
Executing SQL callback: beforeEachMigrate -  [non-transactional]
DEBUG: Parsing beforeEachMigrate.sql ...
DEBUG: Found statement at line 1: DECLARE @return_value int
DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
DECLARE @db_name VARCHAR(50)
DECLARE @snapshot_name VARCHAR(100)

SET @db_name = '5434.FTM2.TU'
SET @snapshot_name = CONCAT(@db_name, @date)

EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name

SELECT @db_name, @return_value
DEBUG: Executing SQL: DECLARE @return_value int
DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
DECLARE @db_name VARCHAR(50)
DECLARE @snapshot_name VARCHAR(100)

SET @db_name = '5434.FTM2.TU'
SET @snapshot_name = CONCAT(@db_name, @date)

EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name

SELECT @db_name, @return_value
DEBUG: Rolling back transaction...
DEBUG: Transaction rolled back
ERROR: Unexpected error
org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration beforeEachMigrate.sql failed
--------------------------------------
SQL State  : S0005
Error Code : 226
Message    : CREATE DATABASE statement not allowed within multi-statement transaction.
Location   : sql/beforeEachMigrate.sql (/flyway/sql/beforeEachMigrate.sql)
Line       : 1
Statement  : DECLARE @return_value int
DECLARE @date VARCHAR(20) set @date = FORMAT(GETDATE(),'dd_MM_yy_hh_mm_ss')
DECLARE @db_name VARCHAR(50)
DECLARE @snapshot_name VARCHAR(100)

SET @db_name = '5434.FTM2.TU'
SET @snapshot_name = CONCAT(@db_name, @date)

EXEC @return_value = [master].[dbo].[usp_create_snapshot] @db_name, @snapshot_name

SELECT @db_name, @return_value

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:273)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:218)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory$SqlScriptCallback.handle(SqlScriptCallbackFactory.java:135)
	at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.onEachMigrateOrUndoEvent(DefaultCallbackExecutor.java:90)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:431)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:341)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:338)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:303)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:207)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:204)
	at org.flywaydb.core.internal.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:62)
	at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:96)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:204)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:165)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:215)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:164)
	at org.flywaydb.core.Flyway.execute(Flyway.java:538)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:238)
	at org.flywaydb.commandline.Main.main(Main.java:151)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: CREATE DATABASE statement not allowed within multi-statement transaction.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:868)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2930)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:744)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
DEBUG: Memory usage: 8 of 13M
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
	... 23 more

**Comment by DoodleBobBuffPants** [comment]
The `Each` variant of a callback runs inside the same transaction as the migration. In this case, adding a script config file for the migration itself (in your case it may be `V1.0__Initial_version_mssql.sql.conf` with `executeInTransaction=false`) would work

**Comment by esagardia** [comment]
Thanks :)
