### ISSUE TITLE
FLYWAY_IGNORE_INVALID_MIGRATION_NAMES=false does not abort on invalid names

### ISSUE THREAD

**Issue by rpdelaney** [flyway/flyway#2996]
###### Which version and edition of Flyway are you using?

`flyway/flyway:6.3` via docker.

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

N/A -- this may be a documentation error in v6. 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

cli

###### Which database are you using (type & version)?

postgres 11

###### Which operating system are you using?

N/A

###### What did you do?

Dockerfile for running migrations:

```
FROM flyway/flyway:6.3

COPY migrations/ /flyway/sql

ENV FLYWAY_CONNECT_RETRIES=10
ENV FLYWAY_IGNORE_INVALID_MIGRATION_NAMES="false"
ENV FLYWAY_CLEAN_DISABLED="true"

ENTRYPOINT ["flyway", "migrate"]
```

A migration was added with the filename `V40_Issue_LCID_Action_Type.sql`. 

###### What did you expect to see?

flyway should fail fast with an exception, as described in the [docs for this option in v6](https://flywaydb.org/documentation/v6/envvars#FLYWAY_IGNORE_INVALID_MIGRATION_NAMES).

###### What did you see instead?

flyway ignored the migration with the invalid name and applied the others without error.

**Comment by DoodleBobBuffPants** [comment]
Thanks for spotting this, this is indeed a documentation error. Environment variable support for this parameter wasn't added until Flyway V7, and it was renamed to [validateMigrationNaming](https://flywaydb.org/documentation/configuration/parameters/validateMigrationNaming#environment-variable).
