### ISSUE TITLE
Execute SQL migrations and Java based ones in separate sequences

### ISSUE THREAD

**Issue by diddowill** [flyway/flyway#2998]
The scenario is:
We use SQL to migrate our database schema and Java to migrate some existing meta data.
Our DAO model must be consistent with the latest db schema. The problem is, an upgrade may consists of tens of migrations, and the earlier Java-based ones may be inconsistent with db schema which has not been upgraded yet, and that leads to an upgrade exception.

So my idea is execute all SQL migrations first and then Java-based ones. It seems Flyway does not support the separation of different execution types. Is this a proper scenario and reasonable feature requirement? 

Example:
migrations to be performed:
/sql/1.sql
/sql/3.sql
/sql/5.sql

/java/2.java
/java/4.java
/java/6.java

For a common case, the migrations will be executed according to their version numbers, i.e., 1 -> 6.
But I want to run SQL first, i.e., 1, 3, 5, and then java based ones, i.e., 2, 4, 6

**Comment by DoodleBobBuffPants** [comment]
The way to achieve this is by executing `migrate` twice. For the first time you want to point the `locations` configuration parameter to just your `sql` folder. The second time around you want to change `locations` to point to just your `java` folder. You would also need to enable `outOfOrder`
