### ISSUE TITLE
Support opensource Redshift JDBC driver

### ISSUE THREAD

**Issue by bjaglin** [flyway/flyway#3000]
###### Which version and edition of Flyway are you using?

5.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

https://github.com/flyway/flyway-play

###### Which database are you using (type & version)?

AWS Redshift 1.0.21053 

###### What did you do?

Switched from the closed-source `"com.amazon.redshift" % "redshift-jdbc42" % "1.2.50.1077"` driver to the [recently-released](https://aws.amazon.com/fr/about-aws/whats-new/2020/11/amazon-redshift-announces-open-source-jdbc-python-drivers/) [open source](https://github.com/aws/amazon-redshift-jdbc-driver) `"com.amazon.redshift" % "redshift-jdbc42" % " 2.0.0.0"` one.
 
###### What did you expect to see?

Migrations being applied.

###### What did you see instead?

Exception `Migration(s) failed for finance-redshift[Unsupported Database: Redshift 8.0]`.

**Comment by MikielAgutu** [comment]
Have you tried setting the [`driver`](https://flywaydb.org/documentation/configuration/parameters/driver) configuration option?

**Comment by bjaglin** [comment]
I believe [the product name changed](https://github.com/aws/amazon-redshift-jdbc-driver/blob/1d0e79c6a9d21e09930808f654fcf8124b8aefe0/src/main/java/com/amazon/redshift/jdbc/RedshiftDatabaseMetaData.java#L155), so https://github.com/flyway/flyway/blob/d525f6e4cd20ab3344ca8b11356537d93a228e07/flyway-core/src/main/java/org/flywaydb/core/internal/database/redshift/RedshiftDatabaseType.java#L64-L74 should be updated.

**Comment by bjaglin** [comment]
> Have you tried setting the [`driver`](https://flywaydb.org/documentation/configuration/parameters/driver) configuration option?

it's set to `com.amazon.redshift.jdbc.Driver`

**Comment by juliahayward** [comment]
The new driver appears to have rather different behaviour around transactions (it errors in situations where the older driver is fine) so it's not simply a matter of swapping one out and adding the other.

**Comment by juliahayward** [comment]
I've raised the issue with the driver team, will await further news. https://github.com/aws/amazon-redshift-jdbc-driver/issues/4

**Comment by juliahayward** [comment]
@bjaglin We've found a fix but it requires `;enableFetchRingBuffer=false` in the URL. Is this an acceptable limitation?

**Comment by bjaglin** [comment]
@juliahayward thanks for the follow-up. Yes, for our usage, it's acceptable!

**Comment by juliahayward** [comment]
Great! So this will go into the next patch release.
