### ISSUE TITLE
pgpass support does not seem to work under Windows

### ISSUE THREAD

**Issue by cowwoc** [flyway/flyway#3004]
###### Which version and edition of Flyway are you using?
7.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
PostgreSQL 13.0

###### Which operating system are you using?
Microsoft Windows [Version 10.0.19042.630]

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Attempted to run "migrate" goal omitting the password parameter

###### What did you expect to see?
I was expecting Flyway to use %APPDATA%\postgresql\pgpass.conf for authentication as https://flywaydb.org/documentation/learnmore/releaseNotes#7.1.0 indicates that you now support pgpass.

###### What did you see instead?
Maven goal failed with:

```
Failed to execute goal org.flywaydb:flyway-maven-plugin:7.2.0:migrate (create-db) on project database: org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:postgresql://localhost/) for user 'postgres': Something unusual has occurred to cause the driver to fail. Please report this exception.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 99999
Error Code : 0
Message    : Something unusual has occurred to cause the driver to fail. Please report this exception.
```

**Comment by cowwoc** [comment]
For clarification, if I explicitly provide a `<password>` parameter, the connection works fine. Omitting the parameter triggers the above error. If I use the psql command-line tool it uses pgpass just fine (meaning that the credentials contained therein are fine).

**Comment by cowwoc** [comment]
I just noticed that this feature is not supported by community edition (which I am using). I expect to get a clearer error message from Flyway in this case, instead of letting the postgresql driver fail this way.

**Comment by DoodleBobBuffPants** [comment]
Flyway reports the same error message returned by the driver. In the normal case this is:

```
SQL State  : 08004
Error Code : 0
Message    : The server requested password-based authentication, but no password was provided.
```

This was the message I received when attempting to reproduce this. Your message suggests some other kind of driver failure which you can inspect by running maven in debug

**Comment by cowwoc** [comment]
@DoodleBobBuffPants Are you saying that Flyway pgpass is implemented in the community edition?
