### ISSUE TITLE
Clean command tries to drop extensions that are installed by superuser

### ISSUE THREAD

**Issue by scranen** [flyway/flyway#3005]
###### Which version and edition of Flyway are you using?
Flyway 7.2.0 CE

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
Reproduces in 7.0.0 CE, 7.1.0 CE, 7.2.0 CE

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
Postgres 11.3

###### Which operating system are you using?
MacOS

###### What did you do?
We have a docker environment with a Postgres 11.3 instance that is initialised with a couple of extensions in the databases it hosts. We use one of these databases to perform a Flyway migration during our Maven build:

```plpgsql
\c template1
CREATE SCHEMA debug;
CREATE EXTENSION IF NOT EXISTS intarray;
CREATE EXTENSION IF NOT EXISTS btree_gist;

\c postgres
CREATE USER a WITH PASSWORD 'a';
CREATE USER flyway_build WITH PASSWORD 'flyway_build';

CREATE DATABASE a WITH OWNER a;
CREATE DATABASE b WITH OWNER flyway_build;
```

The Maven build is configured to run Flyway as the `flyway_build` user. With Flyway 6.5.7, this all worked fine.

When Flyway 7.x.x tries to perform a `clean` during the build, it fails because it tries to drop the `intarray` extension, which is owned by `postgres`. 

**Workarounds**
- Make the Flyway user a superuser and move the `CREATE EXTENSION` to the migration scripts.
- Upgrade to Postgres 13 where these extensions can be installed by regular users.

###### What did you expect to see?
Flyway not requiring superuser rights for a `clean`, and Flyway not to drop extensions that it cannot install itself (or better: that are not created by the migrations that it runs itself, since extensions may affect more than just the schemas that the Flyway user can access).

###### What did you see instead?
Flyway requires superuser rights for a `clean`, or fails to drop extensions that were installed by another user.

I would rather not give Flyway superuser rights, because migrations during build are then allowed to do more (like installing extensions) than migrations in production.

**Comment by scranen** [comment]
⚡ lightning fast, many thanks!

**Comment by dbrennan** [comment]
Did flyway not used to drop extensions? We recently started using 7.2.1 upgrading from 6.4.0 and noticed that extensions that were installed before clean are being removed now and breaking scripts that did not expect that.

**Comment by DoodleBobBuffPants** [comment]
In Flyway V7 we added several breaking changes, and dropping extensions is one of them

You can read about the changes in the [V7 blog post](https://flywaydb.org/blog/flyway-7.0.0) and in the [release notes](https://flywaydb.org/documentation/learnmore/releaseNotes)

**Comment by sivelli** [comment]
I'm facing a similar issue. My cloud provider creates some functions in the schema and because of that Flyway fails to clean up the database. Is it possible to delete only entities that the current user is the owner of?
