### ISSUE TITLE
Change directory structure of Flyway CLI archive to make it compatible with SDKMAN!

### ISSUE THREAD

**Issue by helpermethod** [flyway/flyway#3006]
###### Which version and edition of Flyway are you using?
Flyway 7.2.0 Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
PostgreSQL 13

###### Which operating system are you using?
MacOSX Catalina

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
The SDKMAN! team received a PR (sdkman/sdkman-db-migrations#414) to add `Flyway CLI` to `SDKMAN!`.
While SDKMAN! would gladly add `Flyway` to the list of available candidates, there is one problem:

SDKMAN! expects the archive to contain a `bin` folder with the executable binaries (in your case `flyway` and `flyway.cmd`) under the root folder, which is then added to the `PATH`.

Something like this:

```
flyway-7.2.0 3/
  bin/
    flyway
    flyway.cmd
```

But looking at the `Flyway CLI` archive, it seems the binaries (`flyway` and `flyway.cmd`) are directly placed in the root folder.

```
flyway-7.2.0 3/
  flyway
  flyway.cmd
```

Would it be possible for `Flyway` to package the `CLI` differently, i.e. move the binaries to a `bin` subfolder?

We think that `Flyway` would be a great addition to `SDKMAN!`. If you have any questions or suggestions, feel free to ask!

**Comment by DoodleBobBuffPants** [comment]
Changing the directory structure in this way isn't something we want to do. One reason is because `flyway` and `flyway.cmd` aren't actually binaries, but scripts that call into a `JAR`.

Is this something you could handle on your end? It doesn't feel right to require every software package to contain a `bin` folder

**Comment by helpermethod** [comment]
Agreed, we will think about options to handle that differently. Thank you for your quick answer!
