### ISSUE TITLE
7.2.0 Command-Line Bash Script fails on local JRE 

### ISSUE THREAD

**Issue by dwelch2344** [flyway/flyway#3009]
###### Which version and edition of Flyway are you using?
7.2.0, installed via the wget command on the getting started section: 
```wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.2.0/flyway-commandline-7.2.0-linux-x64.tar.gz | tar xvz && ln -s `pwd`/flyway-7.2.0/flyway /usr/local/bin``` (sudo omitted, as inside `alpine:3.11`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Postgres, but irrelevant 

###### Which operating system are you using?
`alpine:3.11` inside a container

###### What did you do?
Just attempting to install and run a migration with the bundled JRE

###### What did you expect to see?
Flyway migrate :) 

###### What did you see instead?
```/usr/local/bin/flyway: line 83: //flyway-7.2.0/jre/bin/java: No such file or directory```

###### My notes

Setting up a new docker container and wanted to bundle in Flyway (love it, thanks to all!) but the run script doesn't work, at least on `alpine:3.11` (with Bash added).

Error is the following: 
```/usr/local/bin/flyway: line 83: //flyway-7.2.0/jre/bin/java: No such file or directory```

Looks simple enough - the bash script just has a leading `/` from interpolation. Submitted https://github.com/flyway/flyway/pull/3008 to address it. *Should* be straight forward enough across Linux distros, but not sure how else it's used. Happy to take feedback - just want it to work ;)

**Comment by DoodleBobBuffPants** [comment]
The issue may be in your custom docker image

We recommend using [the official Flyway docker images](https://hub.docker.com/r/flyway/flyway) as these are the ones we support

Does this container work for you? Perhaps the dockerfile can help you figure out where yours is going wrong?

**Comment by DoodleBobBuffPants** [comment]
The leading double slash comes from installing Flyway in the root directory, however this should be harmless (see [this post](https://superuser.com/questions/314102/what-causes-double-slashes-in-linux/314103#314103))

The real issue is that Java cannot be executed in your container due to missing libraries. Running `ldd /flyway-7.2.0/jre/bin/java` in your container will show what is missing
