### ISSUE TITLE
Move the Resource class into the API package

### ISSUE THREAD

**Issue by ericparton** [flyway/flyway#3013]
Sort of as a follow on to #2822, I'd like to suggest that the ResourceProvider class that was recently moved into the public API package be refactored to return a kind of Resource object that also exists in the public API package. It currently returns LoadableResource, which is in the org.flywaydb.core.internal package.

Just to add some context, my organization has some custom Flyway code that has used classes out of this internal package for quite some time, and we're making an effort to refactor our code to only use classes in the API package so that fewer things will break when we upgrade Flyway.

The LoadableResource class itself doesn't look particularly useful, since all classes that implement the Resource interface also extend from this threadbare abstract class. It shouldn't be too difficult or disruptive to absorb the LoadableResource class into the Resource interface, and move that interface to the public API package.

That would require a non-backwards compatible change to the public facing ResourceProvider class, but it would theoretically prevent more breaking changes in the future.

I have a PR that I'm happy to submit if it would be welcome.

Thanks!

**Comment by DoodleBobBuffPants** [comment]
Could you expand on what value moving Resource into the API would give you? It would help to understand your use case before making any changes

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity

**Comment by ericparton** [comment]
Sorry for the delay in responding, I just found out this morning that all of my github emails have been going to spam for awhile. 

So to offer some context around this issue, my organization created a custom migration resolver a few years ago that generates custom migrations from yaml configuration files instead of java or sql. We want this migration resolver to behave the same was as the default migration resolvers in terms of locating migrations on the filesystem and converting the file names into migration metadata. 

Unfortunately, the only way that we found of doing that was to use the Scanner, Resource, and MigrationInfoHelper classes from the org.flywaydb.core.internal package. Since these are internal classes, there's obviously no guarantee or expectation of backwards compatibility, and we've seen these classes change frequently across major versions of Flyway. We'd like to stop using internal classes completely to make upgrading Flyway require less effort on our part in the future.

When we upgraded to Flyway 6 a few months ago, someone noticed the new getResourceProvider method on the Configuration class, and we were hopeful that we might be able to replace our usage of the internal Scanner class with a call to that method. We did also notice that the new method was returning a class from the org.flywaydb.core.internal package, which we would like to completely avoid going forward.

Also, if it would be helpful to see our custom migration resolver class, I should be able to provide the code, since it doesn't contain any business logic or anything like that.

**Comment by DoodleBobBuffPants** [comment]
Thanks for the response. I think it makes sense for `LoadableResource` and `Resource` to be in the API, since a `ResourceProvider` asks you to implement these. Since, as you said, combining these would be a breaking change, and we only make breaking changes at major versions, it makes more sense for these classes to be moved to the API without any modification
