### ISSUE TITLE
Is there a way to migrate parquet data and Rocks DB using flyway?

### ISSUE THREAD

**Issue by apoorva-dave** [flyway/flyway#3016]
My data is stored in the form of parquet files and in rocks db. Is there any way to use flyway for their migration?

**Comment by DoodleBobBuffPants** [comment]
Hi. Flyway doesn't support RocksDB and since RocksDB doesn't currently have a JDBC driver it may be a while before we can. You can find a list of databases we do support under the _Supported Databases_ section of our [documentation](https://flywaydb.org/documentation/).
