### ISSUE TITLE
Password keep printed in the stdout

### ISSUE THREAD

**Issue by harisalatas** [flyway/flyway#3018]
###### Which version and edition of Flyway are you using?

6.5.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I believe someone didn't think of that passwords will be logged to an external logging service like kibana or datadog

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

gradle

###### Which database are you using (type & version)?

postgres

###### Which operating system are you using?

debian/docker

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Whenever flyway fails to connect it prints out in the stdout among the other credentials, the password as well. And then the password is logged by kibana!

###### What did you expect to see?

No password!

###### What did you see instead?

Password printed in stdout.

If you could accept a pull request I could probably fix the problem and send you a pull request.

**Comment by DoodleBobBuffPants** [comment]
Is this password in the URL? If so, this was fixed in [Flyway 7.0.3](https://flywaydb.org/documentation/learnmore/releaseNotes#7.0.3)

If not, could you share the debug output? (Run Flyway with `-X`, removing your credentials of course!)

**Comment by harisalatas** [comment]
Yes it was because of the url finally. Thank very much! I will update asap!
