### ISSUE TITLE
SAP HANA Cloud (4.0) Support

### ISSUE THREAD

**Issue by iggycoder** [flyway/flyway#3022]
Version: `7.3.0`

HANA Cloud uses internally version `4.0`. Flyway will print a warning:

`[WARNING] Flyway upgrade recommended: org.flywaydb.core.internal.database.saphana.SAPHANADatabaseType@1835dc92 4.0 is newer than this version of Flyway and support has not been tested. The latest supported version of org.flywaydb.core.internal.database.saphana.SAPHANADatabaseType@1835dc92 is 2.`

As far as I can tell, HANA Cloud is using a subset of features of HANA 2 and should be fully compatible.

[SAP HANA Cloud SQL Reference Guide](https://help.sap.com/viewer/c1d3f60099654ecfb3fe36ac93c121bb/2020_03_QRC/en-US)

It would be nice to know if Flyway will eventually have full support for HANA Cloud.

Thank you.

**Comment by juliahayward** [comment]
I've worked through all the test suite with a HANA Cloud instance and all appears good (except for our tests which exercise HANA 2 features that aren't implemented in HANA Cloud). The message you get at the moment is only a warning; you should be good to continue and I'll remove that warning message from the next version.
