### ISSUE TITLE
Use with GitHub Actions and NodeJS

### ISSUE THREAD

**Issue by dschinkel** [flyway/flyway#3023]
I want to use the command-line for my GitHub Actions pipelines for a NodeJS service.   My NodeJS service is going to be tested against a postgres DB which locally I plan on running the DB in a docker container.

Is there a way to install flyaway so that I can run commands in GitHub Actions, Travis, and other build tools with a NodeJS app?  How would I actually install flyaway in this situation for GitHub Actions for example so that npm scripts could run flyaway cli?  I don't want to install flyaway _in_ my container.  I want to apply migrations from my NodeJS app itself during CI/CD from scripts run from my build.yaml

**Comment by DoodleBobBuffPants** [comment]
In your GitHub Actions workflow, you'd first want a step that downloads Flyway. You can achieve that with the following script:

```
FLYWAY_VERSION=7.3.1

curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}.tar.gz -o flyway-commandline-${FLYWAY_VERSION}.tar.gz \
  && tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz --strip-components=1 \
  && rm flyway-commandline-${FLYWAY_VERSION}.tar.gz
```

Then you can add Flyway to the `PATH` with:

```
PATH=/flyway:$PATH
```

You should then be able to call Flyway inside your GitHub Actions workflow as normal i.e. `flyway migrate`

This isn't the only solution of course, you could also:
- Keep a copy of the Flyway CLI inside your repo if you felt inclined
- Pull the [Flyway docker image](https://hub.docker.com/r/flyway/flyway/)

Does this work for you?

**Comment by dschinkel** [comment]
thanks much!

**Comment by dschinkel** [comment]
I tried running this

- run: ./flyway -url=jdbc:postgresql://${{secrets.DB_HOST}}:${{secrets.DB_PORT}}/${{secrets.DB_NAME}}?user=${{secrets.DB_USER}}&password=${{secrets.DB_PASS}}

I tried running this in OS X and it doesn't even work there

 ./flyway -url=jdbc:postgresql://******:******/******?user=******&password=******

I get `zsh: no matches found:`

**Comment by dschinkel** [comment]
**I tried running this in github actions:**
```
- run: ./flyway -url=jdbc:postgresql://${{secrets.DB_HOST}}:${{secrets.DB_PORT}}/${{secrets.DB_NAME}}?user=${{secrets.DB_USER}}&password=${{secrets.DB_PASS}}
```

and get `Unable to connect to the database. Configure the url, user and password!`. 

I know the values are valid there for the secrets so not sure if I just malformed this somehow still or what.

**I even tried running this in OS X with. hard coded values, and it doesn't even work there:**

./flyway -url=jdbc:postgresql://******:******/******?user=******&password=******

I get `zsh: no matches found`

**Comment by dschinkel** [comment]
In my GitHub actions, not sure why I'm getting command not found for this:
```
Run flyway -locations="filesystem:src/graphql/DB/pgMem/migrations" info
/home/runner/work/_temp/0fadf1dd-2b28-4fb5-91a4-b05169e3b40b.sh: line 1: flyway: command not found
```

but not this:
```
Run flyway -url=jdbc:***ql://***:***/***?user=***&***
```
I don't anything in the first example that should cause a command not found unless you see it?

**Comment by dschinkel** [comment]
Having issues running this command from github actions.  I thought this syntax was right for linux but apparently not yet:

- run: ./flyway -url="jdbc:postgresql://${{secrets.DB_HOST}}:${{secrets.DB_PORT}}/${{secrets.DB_NAME}}?user=${{secrets.DB_USER}}&password=${{secrets.DB_PASS}}"
![Screen Shot 2020-12-27 at 12 03 29 AM](https://user-images.githubusercontent.com/338798/103164939-0c9ba600-47d7-11eb-91d8-7946971cd1ca.jpg)

**Comment by dschinkel** [comment]
I think I needed to combine it into one call.  This time however, it's not able to find my path.  I know that path is there on the VM for github actions because I ls'd it prior to this command:

```
- run: ./flyway -q -url=jdbc:postgresql://${{secrets.DB_HOST}}:${{secrets.DB_PORT}}/${{secrets.DB_NAME}}?user=${{secrets.DB_USER}}&password=${{secrets.DB_PASS}} -locations="filesystem:/src/graphql/DB/pgMem/migrations" info
- ```
But I still get `/home/runner/work/_temp/a77fac76-e24d-4a05-8b08-6c550f51e225.sh: line 1: -locations=filesystem:/src/graphql/DB/pgMem/migrations: No such file or directory`

also tried `./src/graphql/DB/pgMem/migrations: No such file or directory`
and `src/graphql/DB/pgMem/migrations: No such file or directory`

**Comment by DoodleBobBuffPants** [comment]
I notice that you've deleted the comments now, so presumably you have it working?

The issues I noticed:

- The value of each argument needs to be wrapped in quotes in bash
- You were trying to run Flyway without issuing a command such as `info` or `migrate`

A correct command would look like `./flyway -url="<your_url>" -locations="<your_locations>" info`

**Comment by dschinkel** [comment]
Almost there, you were on the right track.  The problem is I wonder if I need to escape something:

```
- run: ./flyway -q -url="jdbc:postgresql://00.00.00.00:5432/postgres?user=postgres&password=fakePassword*&ssl=false" -locations="filesystem:src/graphql/DB/pgMem/migrations" info
```

I replaced some of the real stuff above, but this gets across what I'm running.  The problem I have now is I don't know if I need to escape something because it seems to cut off some of the command when github actions runs it:

![Screen Shot 2020-12-29 at 3 15 16 AM](https://user-images.githubusercontent.com/338798/103274792-29c3a680-4988-11eb-84d4-f8945f76c21d.jpg)

**Comment by DoodleBobBuffPants** [comment]
You could try passing the user and password in separately with `-user` and `-password`, and this will let you figure out which bit is causing the URL to cut off

**Comment by dschinkel** [comment]
Thanks yea so it's the password.  The password has a * in it, wonder if that's the problem.

**Comment by DoodleBobBuffPants** [comment]
Does it successfully connect when you pass the username and password in as separate arguments? You shouldn't have to escape anything, and if the password is incorrect the driver should throw an authentication error

Since your database is running in a container, it's also possible that the container isn't ready yet

**Comment by dschinkel** [comment]
My database isn't running in a container.  It's trying to connect to my Google Cloud DB instance which I thought this could do?

**Comment by dschinkel** [comment]
It's so odd, I don't know why I see `-***`,  even tried without the ^ and just characters and numbers for the password.

**Comment by DoodleBobBuffPants** [comment]
It appears as asterisks due to masking, it won't be using `***` as the password internally. Could you share the output of running the above command?

You could also try downloading the Flyway CLI and running the above command. If it runs then we know there's something specific to running it as a GitHub Action

**Comment by dschinkel** [comment]
Sure, yea it might be something with the -password flag, because no matter how I format that, Actions is replacing it with -***.

How do I download the cli?

**Comment by DoodleBobBuffPants** [comment]
You can download it for your platform from the following link: https://flywaydb.org/download/community

**Comment by DoodleBobBuffPants** [comment]
After having a look around, it seems that you may need to manually start the postgres service if you aren't already. You can do this by running `sudo service postgresql start` first in your Actions workflow

**Comment by DoodleBobBuffPants** [comment]
The error indicates that the URL is incorrect - there's no database there to connect to. Since you're trying to connect to a Google Cloud database instance, the URL is formatted differently - see [their documentation](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#instructions-for-jdbc) on how to set up your JDBC URL.

**Comment by dschinkel** [comment]
The problem is the statement is malformed, the same problem I've had from the beginning but yes, thanks for the find on the google version of the jdbc.  

I still have the same problems even when running this

- run: ./flyway -q -url="jdbc:postgresql:///${{secrets.DB_NAME}}?cloudSqlInstance=${{secrets.CLOUD_SQL_CONNECTION_NAME}}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${{secrets.DB_USER}}&password=${{secrets.DB_PASS}}" -locations="filesystem:src/graphql/DB/pgMem/migrations" info
- 
![Screen Shot 2020-12-30 at 12 33 48 AM](https://user-images.githubusercontent.com/338798/103334493-220f0b00-4a37-11eb-9f34-1fbe882e8fc5.jpg)

**Comment by DoodleBobBuffPants** [comment]
Flyway however is Java based and uses JDBC to connect to the database. You need to download the socket factory JAR in your Actions workflow and make it available on the classpath so that it can be used

One way would be by running a similar `curl` command on `https://repo1.maven.org/maven2/com/google/cloud/sql/postgres-socket-factory/1.2.0/postgres-socket-factory-1.2.0.jar` and then copying the downloaded JAR into `flyway/drivers`

Closing for now as this is no longer a Flyway issue

**Comment by dschinkel** [comment]
This issue is about trying to get flyway working in node and github actions.  It's fine to close it but this thread is all about getting flyway working via command-line which is proving to be painful.

tried your suggestion on downloading the google cloud jar, but got this:

![Uploading Screen Shot 2020-12-30 at 3.12.38 AM.jpg…]()

**Comment by DoodleBobBuffPants** [comment]
You also need to download dependencies yourself too. You can find what you need in the `Compile Dependencies` section on Maven for this artifact [here](https://mvnrepository.com/artifact/com.google.cloud.sql/postgres-socket-factory/1.2.0)

**Comment by dschinkel** [comment]
I assume those should all be downloaded to the `drivers` folder

**Comment by DoodleBobBuffPants** [comment]
They all need to be available on the classpath, and Flyway ensures everything in the `drivers` folder is added to the classpath so it is the safest option, and recommended for dependencies related to your database connectivity

**Comment by dschinkel** [comment]
As I ventured down this path to resolving the compiled dependencies, am finding I'm chasing a rabbit hole now of dependencies which is tough because I'm manually having to find, download, and hope for the best since I'm not in an actual Java Project.

```
- run: chmod 744 drivers
- run: wget -P drivers https://repo1.maven.org/maven2/com/google/cloud/sql/postgres-socket-factory/1.2.0/postgres-socket-factory-1.2.0.jar
- run: wget -P drivers https://repo1.maven.org/maven2/com/google/cloud/sql/jdbc-socket-factory-core/1.2.0/jdbc-socket-factory-core-1.2.0.jar
- run: wget -P drivers https://repo1.maven.org/maven2/com/google/api-client/google-api-client/1.20.0/google-api-client-1.20.0.jar
```

The latest one, which I thought I solved by downloading `google-api-client-1.20.0.jar` but nope, and this is not very fun:
![Screen Shot 2020-12-30 at 8 51 01 PM](https://user-images.githubusercontent.com/338798/103391953-42939f80-4ae1-11eb-9eeb-e56fe325fb62.jpg)

**Comment by dschinkel** [comment]
We have lift-off.  Thanks much @DoodleBobBuffPants 
![Screen Shot 2020-12-31 at 12 17 48 AM](https://user-images.githubusercontent.com/338798/103397394-d3787400-4afd-11eb-93a1-b6ce989ef17b.jpg)

**Comment by dschinkel** [comment]
Blog post about it https://t.co/34zFN3kopx

**Comment by DoodleBobBuffPants** [comment]
Glad to hear it works:)

I appreciate that manually downloading dependencies is a pain. Would it be feasible to create a Java project with Maven for the sole purpose of grabbing dependencies automatically? You could then follow [this post](https://technology.amis.nl/languages/java-languages/download-all-directly-and-indirectly-required-jar-files-using-maven-install-dependencycopy-dependencies/) to grab the dependencies
