### ISSUE TITLE
Consider support  for conditional compilation statements/block  

### ISSUE THREAD

**Issue by BaburaoLad** [flyway/flyway#3025]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.3.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
this is latest as of now 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
JAVA API

###### Which database are you using (type & version)?
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

###### Which operating system are you using?
Linux 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
trying to migrate package body which has below code for conditional compilation ,

  $IF dbms_db_version.version >= 11 $THEN
             execute IMMEDIATE v_stmt_clob;
            $ELSE
              log('The PL/SQL block is larger than 32K - cannot execute in 10g DB');
              execute IMMEDIATE dbms_lob.substr(v_stmt_clob, 32000, 1) || dbms_lob.substr(v_stmt_clob, 32000, 32001);
            $END

###### What did you expect to see?
Successfully  able to migrate 

###### What did you see instead?
Unable to parse statement in R__o2hm.pkb at line 1 col 1. See https://flywaydb.org/documentation/knownparserlimitations for more information

**Comment by BaburaoLad** [comment]
@DoodleBobBuffPants  based  on this   https://flywaydb.org/documentation/knownparserlimitations documentation , this seems to be parsing **bug** for conditional compilation statements .

**Comment by DoodleBobBuffPants** [comment]
I'm unable to reproduce this with the code provided above - it parses just fine for me. Could you provide the exact script that was failing?

**Comment by BaburaoLad** [comment]
@DoodleBobBuffPants  Please find below package which i tested and having same issue ,
If we remove line 381 to 387 from R__flyway_test.pkb file then flyway is able to compile it else not .
[R__flyway_test.zip](https://github.com/flyway/flyway/files/5672546/R__flyway_test.zip)
