### ISSUE TITLE
add jdk13,14,14 support for flyway-maven-plugin

### ISSUE THREAD

**Issue by damingerdai** [flyway/flyway#3027]
###### Which version and edition of Flyway are you using?
flyway-maven-plugin:7.3.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
flyway-maven-plugin

###### Which operating system are you using?
macos 10.14.6 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by DoodleBobBuffPants** [comment]
Could you provide more information about what you're trying and what is failing?

**Comment by damingerdai** [comment]
i use IDEA to develop a spring boot project. when i use jdk14, i can not install flyway-maven-plugin. but i use jdk11, flyway-maven-plugin can be installed.
this is my code: https://github.com/damingerdai/hoteler

**Comment by DoodleBobBuffPants** [comment]
This works fine for me, and isn't a Flyway issue. Using your code I can still execute the Flyway plugin on all JDK versions >= 11.

If the Flyway plugin appears red in your POM, you can still try executing it, and if it works you'll know something is wrong on your end. You can try:

- purging your local maven cache
- invalidating your IDEA cache
- checking your maven settings in IDEA and ensuring they point to use the desired JDK and repositories
