### ISSUE TITLE
Flyway migrate output always reports the same schema

### ISSUE THREAD

**Issue by robertsosinski** [flyway/flyway#3033]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 7.3.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

###### Which operating system are you using?

Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Ran `flyway migrate`

I have multiple schemas setup in the `flyway.conf` file, which looks like this:

```
flyway.defaultSchema=public
flyway.schemas=public,schema_1,schema_2,schema_3
```

###### What did you expect to see?

Expected to see output like this:

```
Migrating schema "public" to version "1.0.4 - create hstore ext"
Migrating schema "public" to version "1.0.5 - create pgcrypt ext"
Migrating schema "public" to version "1.0.6 - create pgjwt ext"
Migrating schema "schema_1" to version "1.1.1 - create users table"
Migrating schema "schema_2" to version "1.1.2 - create tasks table"
Migrating schema "schema_3" to version "1.1.3 - create open_tasks view"
```

In this case, the `users` table is in `schema_1`,  the `tasks` table is in `schema_2`,  the `open_tasks` table is in `schema_3`, 

###### What did you see instead?

```
Migrating schema "public" to version "1.0.4 - create hstore ext"
Migrating schema "public" to version "1.0.5 - create pgcrypt ext"
Migrating schema "public" to version "1.0.6 - create pgjwt ext"
Migrating schema "public" to version "1.1.1 - create users table"
Migrating schema "public" to version "1.1.2 - create tasks table"
Migrating schema "public" to version "1.1.3 - create open_tasks view"
```

Here, flyway is incorrectly reporting that all schemas were `public`.  The migration works just fine (everything is in the correct schema), but the output is incorrect.

Thanks!

**Comment by DoodleBobBuffPants** [comment]
Flyway is working as expected. The schema history table is stored in the `defaultSchema` so that is the schema that appears as 'Migrating' as that is where the version information is stored. The list of `schemas` tells Flyway what to manage, and while only the default schema is tracking version information, all of these schemas would be cleaned when you run `clean`. If you wish to track version information per schema, you can ready about how you could achieve this in our [FAQs](https://flywaydb.org/documentation/learnmore/faq#multiple-schemas)
