### ISSUE TITLE
Feature request: Is there a table grouping function? There was no interaction between different groups.

### ISSUE THREAD

**Issue by wangliang181230** [flyway/flyway#3035]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by DoodleBobBuffPants** [comment]
It seems like you're asking for the same thing as https://github.com/flyway/flyway/issues/439. Do leave a comment on there explaining what you're after so that we can track interest
