### ISSUE TITLE
Feature proposal: Baselining repeatable migrations

### ISSUE THREAD

**Issue by peterdevaal** [flyway/flyway#3036]
When implementing Flyway for existing systems we have the baseline command to mark schemas that already contain database objects for having all versioned scripts below the baseline version. This is great functionality. However,  any repeatable migration is still considered to be executed as long as the checksum of each script has not been determined yet.

With an existing system with a large amount of repeatable scripts, such as for creating stored procedures, database views, jobs etc. it is not desirable that all these scripts are executed on the next migration run, especially not in a production environment. When it is known that the objects in the database are really the same as those created by the repeatable script (and that can be verified by using a schema comparison tool) then we should have the possibility that the baselining also records the checksum of the existing scripts without executing them. This can be done now by doing a dry-run and only execute the update of the flyway history table data from the resulting script, but that is a work around rather than intended functionality.

So, an extra option e.g. checksum_on_baseline=yes should be great to have this feature added.

**Comment by DoodleBobBuffPants** [comment]
The intended way to achieve this is by using [`skipExecutingMigrations`](https://flywaydb.org/documentation/configuration/parameters/skipExecutingMigrations). Enabling this parameter will not execute the migration, but still updates the schema history table as desired. Then you can either [`cherryPick`](https://flywaydb.org/documentation/configuration/parameters/cherryPick) all of the repeatable migrations to skip executing, or if your repeatables are stored in a separate location you can change the `locations` parameter

**Comment by peterdevaal** [comment]
Thanks very much for this explanation! I overlooked it, but that indeed exactly serves the purpose.
