### ISSUE TITLE
Java Heap Space - Out of Memory

### ISSUE THREAD

**Issue by tanguanpeng1234** [flyway/flyway#3037]
###### Which version and edition of Flyway are you using?

7.3.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is already the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line - Linux

###### Which database are you using? (Type & version)

MySQL 8.0

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

flyway -teams -licenseKey=xxx info    (xx is just a placeholder of the license key)

###### What did you expect to see?

Proper display of the information similar to the below
flyway info
Detected a MySQL option file. Upgrade to Flyway Teams Edition to use this for database authentication by visiting https://flywaydb.org/upgrade.
Flyway Community Edition 7.3.2 by Redgate
Database: jdbc:mysql://vm1:3306/user1db (MySQL 8.0)
Schema version: << Empty Schema >>

+-----------+---------+-------------+------+--------------+---------+
| Category  | Version | Description | Type | Installed On | State   |
+-----------+---------+-------------+------+--------------+---------+
| Versioned | 1.1     | cr table1   | SQL  |              | Pending |
+-----------+---------+-------------+------+--------------+---------+

###### What did you see instead?

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at org.flywaydb.core.internal.authentication.mysql.MySQLOptionFileReader.decryptFileContents(MySQLOptionFileReader.java:482)
        at org.flywaydb.core.internal.authentication.mysql.MySQLOptionFileReader.getAllContents(MySQLOptionFileReader.java:440)
        at org.flywaydb.core.internal.authentication.mysql.enterprise.MySQLPropertiesProvider.get(MySQLPropertiesProvider.java:427)
        at org.flywaydb.core.internal.database.mysql.MySQLDatabaseType.getExternalAuthProperties(MySQLDatabaseType.java:530)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:574)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:512)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:2626)
        at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:1610)
        at org.flywaydb.commandline.Main.main(Main.java:533)

**Comment by DoodleBobBuffPants** [comment]
Are you limiting your maximum heap space, and if so to how much?
Also how large is your `.mylogin.cnf` option file?

**Comment by DoodleBobBuffPants** [comment]
We can optimize the memory performance to a certain extent, but Flyway needs to hold the 'obfuscated' option file in memory which cannot be avoided

Closing for now

**Comment by tanguanpeng1234** [comment]
The Java memory issue was flagged out when I include the switch "-teams". Hence, it didn't quite explain if issue is on .mylogin.cnf.

**Comment by DoodleBobBuffPants** [comment]
The option file should only be read if no other form of authentication is used, so we will fix it to do that instead, then it should work as it did before

**Comment by tanguanpeng1234** [comment]
Can elaborate which and why the option file could give rise to this issue?

On Linux:
flyway -teams -licenseKey=xxx info (xx is just a placeholder of the license key) migrate  -- this will encounter memory error
flyway migrate  -- this will run successfully

On window:
Both commands run successfullly

**Comment by DoodleBobBuffPants** [comment]
We added the ability to [authenticate via MySQL Option Files](https://flywaydb.org/documentation/database/mysql#option-files) in Flyway Teams only. The stack trace indicates that while decrypting the obfuscated option file which is `.mylogin.cnf` on Linux, Java ran out of memory. Unfortunately this can't be avoided since we want to hold the decrypted file in memory only. In your case however, it should still work with and without `-teams` as we only want to consider option files as a last resort, so that is something we will fix

**Comment by tanguanpeng1234** [comment]
Yes, issue has been resolved after i remove the .my.cnf.

Contents of my .my.cnf as below:

[mysql]
prompt=\\u@\\h [\\d]>\\_

Is there a tentative timeline whereby the fix will be made available?

**Comment by tanguanpeng1234** [comment]
when you said decrypted file in memory, will it cache the decrypted file in memory? if yes, when will it age out the cache? any command i can use to age this out?
