### ISSUE TITLE
Compare against List for shouldExecute

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3039]
###### Which version and edition of Flyway are you using?
7.3.1 Teams

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We're trying to find a way to use the [shouldExecute](https://github.com/flyway/flyway/issues/2997) migration precondition in our multi-tenant environment.  We have about 300 copies of the database and occasionally need to roll out changes to the database selectively.  For example, we may to go 1, then 5, then 10, then 25, etc.  Today we're accomplishing this with very unconventional SQL scripts.  If we're able to do some kind of _contains_ or list comparison in `shouldExecute`, it would make this much better.  Is that possible or is it only `==`?

Each of our 300 databases are associated with a store code.  What we'd like to do is have a store code placeholder that we then use in the `shouldExecute`.  In the example above, the first time would look something like
```
shouldExecute={StoreCode}==1
```
where it would only run for StoreCode 1.  Then
```
shouldExecute={StoreCode}==1,2
```
where it would only run for StoreCodes 1 and 2.  Of course `==` wouldn't work in this case, but is there something that would?

**Comment by esauser** [comment]
Are `AND` and `OR` supported within there?  If they are, an option could be
```
shouldExecute={StoreCode}==1 OR {StoreCode}==2
```

**Comment by DoodleBobBuffPants** [comment]
At the moment none of these are supported, but adding support for a list of values which is effectively shorthand for `OR` seems like a nice addition

**Comment by esauser** [comment]
How long would you estimate until we'll see this?  Trying to determine if we should come up with our own work around or not.

**Comment by DoodleBobBuffPants** [comment]
Support for more extensive boolean expressions in `shouldExecute` will be available from the next release:)

**Comment by esauser** [comment]
When do you expect the next release?

**Comment by DoodleBobBuffPants** [comment]
While we make no guarantees, we aim to release every week or so
