### ISSUE TITLE
Vault Integration

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3040]
###### Which version and edition of Flyway are you using?
7.4.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I noticed Vault integration listed in the release notes.  Went to find documentation.

###### What did you expect to see?
Documentation

###### What did you see instead?
Nothing

I found the commit and see that it's listed as experimental.  I couldn't tell from the commit how exactly it works.  I see it takes a URL, Token, and Secret name.  What is the expected value of the Secret?

**Comment by DoodleBobBuffPants** [comment]
The secret needs to be structured like the contents of a Flyway configuration file e.g.

```
flyway.password=...
flyway.licenseKey=...
```

**Comment by esauser** [comment]
Will it simply append to existing configuration?  If so, where will if fall in order or precedence?

Have you considered implementing it in such a way that it could be multiple secrets instead of a single?  For example, in vault a secret can have multiple key value pairs.  We could give it a path to a secret, then each key be the part after `flyway.` and the value the part after the `=`.

**Comment by DoodleBobBuffPants** [comment]
> Will it simply append to existing configuration? If so, where will if fall in order or precedence?

It will append to existing configuration and overwrite with the highest precedence


 >Have you considered implementing it in such a way that it could be multiple secrets instead of a single? For example, in vault a secret can have multiple key value pairs. We could give it a path to a secret, then each key be the part after `flyway.` and the value the part after the `=`.

The approach of specifying a path to multiple key-value pairs is nice for Vault, as you can specify configuration properties at a more granular level. However this doesn't necessarily apply to all secrets managers so wouldn't be consistent, hence the approach of treating a single secret as another entire configuration

Will leave this open to gather more feedback and interest for now

**Comment by esauser** [comment]
Just to be clear, will it actually work if we configure those values right now?  I know it's experimental, but I didn't see in the commit where it did more than just set the values internally.

**Comment by DoodleBobBuffPants** [comment]
It should work in 7.4.0 yes

**Comment by esauser** [comment]
If you're looking for general feedback, in our case, the best possible configuration would allow for multiple secrets to be specified.  In our Vault we have a path per team.  With just one secret, either one team has to manage it or all teams have access to it.  To be clear, we'd like to be able to specify something like this
```
/team1/flyway
/team2/flyway
/team3/flyway
```

**Comment by esauser** [comment]
No, they are shared.  It's kind of a mess, we have very large shared cross-team databases.

**Comment by DoodleBobBuffPants** [comment]
Multiple secrets still poses a precedence problem. Is there anything in particular that prevents `teamX` from having their own secret at `/teamX/flyway` and only providing that?

**Comment by esauser** [comment]
Sure, you could easily say the last one wins or something like that.  Ideally they wouldn't be duplicating each other.

The problem is that `team1`, `team2`, and `team3` all contribute to the `shared-database`.  None of them have access to the secrets for the `shared-database` (like the flyway account credentials, etc.).  They only have access to their own, under a path for their team.

Let's say `team1` wants to create an account.  They would put the password in `/team1/flyway`.  No other teams would have access to it here.  If `team2` wants to create an account, they would put it in `team2/flyway`, again where only they have access.

By allowing multiple paths to be specified, it will allow us to enable each team to manage their own secrets.  As-is, our only options are to put them all in `/shared` which are secrets for everyone, allowing every team to see every teams, or `shared-databases`, which none of the teams have access to, thus someone else having to manage it for them.

**Comment by DoodleBobBuffPants** [comment]
When you mention account credentials, are you referring to the username and password you would supply to Flyway? If each team's secret just stores the password configuration parameter, then specifying secrets for multiple teams has no effect as only one such parameter would win

Flyway uses Vault as another source of Flyway configuration parameters. Each of your teams likely already has a way of configuring Flyway and this allows them to move that into Vault. Is your existing approach to configuration also doing something similar by loading in configuration parameters from locations specific to different teams?

It's not clear why Flyway needs to load in configuration parameters from multiple secrets, unless there are different configuration parameters from each team's path that would combine to make a complete Flyway configuration?

**Comment by esauser** [comment]
> When you mention account credentials, are you referring to the username and password you would supply to Flyway? If each team's secret just stores the password configuration parameter, then specifying secrets for multiple teams has no effect as only one such parameter would win

I am not referring to the username and password supplied to flyway (references as the flyway account credentials in my previous post).  Rather, the usernames and passwords for accounts that are created by flyway.  For example, if `team1` wants to create a user for `application1`, they would have a username and password used in the `CREATE LOGIN` migration.  If `team1` wanted to do the same for `application2`, there would be a separate set.  Finally, `team2` for `application3`, another.  So on and so forth.

> Flyway uses Vault as another source of Flyway configuration parameters. Each of your teams likely already has a way of configuring Flyway and this allows them to move that into Vault. Is your existing approach to configuration also doing something similar by loading in configuration parameters from locations specific to different teams?

Since these are shared across many teams, they do not have a way to provide their own configuration.  Instead, there is a single .conf file shared by all teams.  The passwords technically could go here, but then they are committed to source control and viewable to everyone.  We do not currently have team specific configuration.

Since we don't currently have a secure way to pass the passwords to flyway, all accounts are created with the same hard-coded password and disabled.  The DBAs then go into the database, change the password, enable the account, and send the password to the team.

> It's not clear why Flyway needs to load in configuration parameters from multiple secrets, unless there are different configuration parameters from each team's path that would combine to make a complete Flyway configuration?

Yes, that is correct.  In the example above, I'd like to be able to pull the credentials from `application1` and `application2` from `/team1/flyway` and the credentials for `application3` from `/team2/flyway`.  Now, Flyway wouldn't know where they are coming from, but it wouldn't care.  It would only care that it comes from somewhere and all of it together has all of them that it needs.

**Comment by DoodleBobBuffPants** [comment]
Thanks for explaining

To make sure we're clear on your process, are these team-specific account credentials being loaded in as placeholders or some other configuration parameter?

**Comment by DoodleBobBuffPants** [comment]
Would you be willing to send an email to support to arrange a call for a more in-depth discussion? (You should have access to support as a Teams customer)

**Comment by esauser** [comment]
>To make sure we're clear on your process, are these team-specific account credentials being loaded in as placeholders or some other configuration parameter?

Yes, I'm planning to use placeholders.

>Would you be willing to send an email to support to arrange a call for a more in-depth discussion? (You should have access to support as a Teams customer)

Sure.  What's the email address for support?  I'm not seeing it on the website.

**Comment by DoodleBobBuffPants** [comment]
The email is  support@flywaydb.org

**Comment by esauser** [comment]
Thanks for the call today.  I'll be standing by to hear your plans.

**Comment by esauser** [comment]
@DoodleBobBuffPants is this implemented in such a way that it will silently ignore secrets that don't yet exist?  In our environment, ideally we'd configure it for every team, but it wouldn't actually exist until they needed it.

**Comment by DoodleBobBuffPants** [comment]
The current implementation will throw an exception if the secret doesn't exist

**Comment by esauser** [comment]
Thoughts on silently ignoring, or allowing for that option?

**Comment by DoodleBobBuffPants** [comment]
I think it makes sense to throw an exception, since we're treating secrets as a source of configuration parameters, and the existing behavior for configuration files that are provided and do not exist is to also throw an exception

**Comment by esauser** [comment]
I can't find the actual source code that communicates to vault.  Can you share a link to it?  

I'm trying to determine which [secret engine](https://www.vaultproject.io/docs/secrets) is expected.  I'm guessing it's [KV](https://www.vaultproject.io/docs/secrets/kv).  Does it happen to be [KV1](https://www.vaultproject.io/docs/secrets/kv/kv-v1) or [KV2](https://www.vaultproject.io/docs/secrets/kv/kv-v2)?

Assuming it is KV, what `key` is expected?  My understanding is the value is the config contents.
![image](https://user-images.githubusercontent.com/24945592/104736194-370ebe00-5708-11eb-95dd-b0bace515ae0.png)

As you know, our structure is built around the assumptions that Concourse makes with it's [Vault integration](https://concourse-ci.org/vault-credential-manager.html).  It only supports KV1.

**Comment by DoodleBobBuffPants** [comment]
Since this is a Flyway Teams-only feature, the source code is hidden

The changes that support multiple secrets have only been merged and not yet released so that won't work yet

We expect the secret engine to be KV2 (this is what was tested against, but if the JSON response of KV1 and KV2 is equivalent then both should work)

In the current implementation:
- The key can be anything, you just need to specify it in `flyway.vault.secret`
- The URL (put in `flyway.vault.url`) must contain the full path to the secret i.e. `http://localhost:8200/v1/secret/data/...`
- The token goes in `flyway.vault.token`

In the new implementation (will be available from next release):
- Multiple paths can be specified in a list to `flyway.vault.secrets`
- The paths must be the full path to the secret, and include both the engine name and secret name i.e. `secret/data/flyway/flywayConfig` where `secret` is the engine, `data` is required by the KV2 api, `flyway` is the path, and `flywayConfig` is the secret name
- The URL only needs to contain the domain and version i.e. `http://localhost:8200/v1`

**Comment by esauser** [comment]
Would it be possible to allow Teams customers to view the code?  I'd be able to answer all these questions on my own if that was the case.

While both KV1 and KV2 return JSON, they are different, the access methods, parameters, etc.  Would it be possible for you to setup and KV1 engine and test against it on your side?  If the implementation only works with KV2 and KV1 isn't added we'll have to create a dedicated secret engine for this.  Not insurmountable, but certainly a lot more work.

One of the differences in KV1 and KV2 is that `data` part of the path.  Since you have that configurable, this just might support both.

**Comment by DoodleBobBuffPants** [comment]
The code isn't available to view, but we're happy to answer any questions

The current version doesn't support KV1 it seems. This is because the response object is structured differently, however it shouldn't be much work to add support for both KV1 and KV2:)

**Comment by esauser** [comment]
Does your :) imply you're going to support it?

**Comment by esauser** [comment]
@DoodleBobBuffPants unfortunately we still cannot use the vault integration as-is.  You may recall we have a bit of an odd scenario with our shared databases where many teams contribute.  Once we add the team specific locations in vault, the teams are able to change any `flyway` settings, not just `flyway.placeholders`.  We are not comfortable opening ourselves up to this.

Would you consider adding a whitelist or the kinds of config that are allowed?  We only want to allow `placeholders` through, that way everything else can still be controlled by us.

**Comment by DoodleBobBuffPants** [comment]
I imagine this would need to be another configuration parameter where you specify the whitelisted parameters which we can use as a filter. Is this what you expect too? Could you also open a new feature request issue for this? Thanks

**Comment by esauser** [comment]
Yes, it would have to be another parameter.  I can certainly open a feature request.
