### ISSUE TITLE
I can not build flyway 6.5.5 with maven besause gradle-plugins-3.0.pom and gradle-plugins-3.0.jar can not be found in all the maven repository

### ISSUE THREAD

**Issue by lihaocaojingnv** [flyway/flyway#3046]
I want to build flyway 6.5.5 source code. However, I can not find the dependency gradle-plugins-3.0 for the module flyway-gradle-plugin in all the maven repository listed in the root pom, like https://repo1.maven.org/maven2,https://repo.gradle.org/gradle/libs-releases-local/,https://nexus.flywaydb.org/repository/flyway/ and https://maven.oracle.com. Where can I get this dependency gradle-plugins-3.0?

![image](https://user-images.githubusercontent.com/20627755/104172656-94241e80-543f-11eb-9518-266669fc22cf.png)
![image](https://user-images.githubusercontent.com/20627755/104172694-9f774a00-543f-11eb-84e6-908212c2d947.png)

**Comment by DoodleBobBuffPants** [comment]
It seems that version 3.0 of the JAR is no longer available. You could try updating to the next available version which is 3.4, or building from the latest sources which are guaranteed to work
