### ISSUE TITLE
Sl4fj logs incorrect class / method

### ISSUE THREAD

**Issue by hc-codersatlas** [flyway/flyway#3047]
###### Which version and edition of Flyway are you using?

7.4.0 / latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API, Gradle plugin

###### Which database are you using? (Type & version)

PostgreSQL, H2

###### Which operating system are you using?

Windows, Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Run Flyway with Slf4j

###### What did you expect to see?

Flyway reports org.flywaydb.core.internal.logging.slf4j.Slf4jLog.info() as the class that is getting logged as per below, i.e. not the real class but the wrapped 1.

Flyway should be using Slf4j's location aware logger so that the real calling class / method can be shown in logs.

###### What did you see instead?

2021-01-01 15:33:23 [io-executor-thread-1] org.flywaydb.core.internal.logging.slf4j.Slf4jLog.info()
INFO: Flyway Community Edition 7.3.1 by Redgate
2021-01-01 15:33:23 [io-executor-thread-1] org.flywaydb.core.internal.logging.slf4j.Slf4jLog.info()
INFO: Database: jdbc:postgresql://127.0.0.1:6432/test (PostgreSQL 13.1)
2021-01-01 15:33:23 [io-executor-thread-1] org.flywaydb.core.internal.logging.slf4j.Slf4jLog.info()
INFO: Current version of schema "public": 1.1

**Comment by DoodleBobBuffPants** [comment]
Could you provide a sample Flyway project with your logging set up that reproduces this?

**Comment by hc-codersatlas** [comment]
Any flyway project with Slf4j (which is the default on top without a way to override the ordering) produces this. A default logback config might look right because it's logging the category and not the classname / method.

https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java/org/slf4j/spi/LocationAwareLogger.java indicates clearly why it's required i.e. for wrappers to get to the correct location information.

**Comment by DoodleBobBuffPants** [comment]
All typical logging set-ups work correctly for us. We use SLF4J's `LoggerFactory` to get a logger, which also handles `LocationAwareLogger`'s. Without knowing which logging JARs you're using (or missing) or your logging configuration we won't be able to proceed

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
