### ISSUE TITLE
Option to provide a list of migrations to be skipped & mark as success

### ISSUE THREAD

**Issue by garvbhandari** [flyway/flyway#3055]
###### Which version and edition of Flyway are you using?
Version 7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
Amazon auroraa postgres db - version 10

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Have a one time operation requirement to migrate data from multiple db tables to another db table.
The above flyway migration will create an issue when applied on a fresh instance of a database, therefore, require an option where one can supply a list of migrations to be skipped and marked as success.

###### What did you see instead?
Cherry-pick provides an option to add a list of migrations to apply but this gets cumbersome to maintain in the long run as one has to keep updating this list on every new addition of a migration version.

**Comment by DoodleBobBuffPants** [comment]
This can be achieved with [`skipExecutingMigrations`](https://flywaydb.org/documentation/configuration/parameters/skipExecutingMigrations). This will skip the execution of migrations during a migrate, and mark them as having applied successfully. With `cherryPick` this will enable what you're after. If `cherryPick` is too cumbersome then alternatively you can put the migrations to skip executing in their own folder, and change the `locations` parameter accordingly
