### ISSUE TITLE
flyway.locations 7.5.0 not working

### ISSUE THREAD

**Issue by sprocketholer** [flyway/flyway#3056]
###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

This is my config:

flyway.url=jdbc:postgresql://localhost:5432/AgencyPOC
flyway.user=postgres
flyway.password=password
flyway.locations=filesystem:C:\repos\sentinel\sentinel-agency\Database\Scripts

I have 2 migration scripts in the folder "C:\repos\sentinel\sentinel-agency\Database\Scripts" (I copied that path from Windows Explorer)

If  I copy the scripts into the flyway/sql folder it runs fine. If the flyway/sql is empty Flyway is not finding the scripts in the path.

###### What did you expect to see?
The database should be moved to version 2 and the two scripts should have executed.

###### What did you see instead?

WARNING: No migrations found. Are your locations set up correctly.

**Comment by DoodleBobBuffPants** [comment]
Can you share your full debug output? (run flyway with `-X` as an argument)

**Comment by sprocketholer** [comment]
![image](https://user-images.githubusercontent.com/5629141/105057774-697f2a80-5a2a-11eb-9e6c-3b3fbfa25134.png)

Here's the output from a -X run.

**Comment by DoodleBobBuffPants** [comment]
From the output, you haven't actually set the locations parameter to your folder. Set locations to `filesystem:C:\repos\sentinel\sentinel-agency\Database\Scripts` and run it again.

If you are setting locations in your conf file, make sure it's not being overriden (such as by environment variables)

**Comment by sprocketholer** [comment]
So the new config had this line "flyway.locations=filesystem:sql" uncommented about 110 lines into the documentation.

I commented this out and it finds the file location, now. 

Thank you for your help!
