### ISSUE TITLE
-schemas causing schema version `null`

### ISSUE THREAD

**Issue by jorgecarleitao** [flyway/flyway#3057]
###### Which version and edition of Flyway are you using?

`docker flyway/flyway 7.5.0`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

CLI

###### Which database are you using? (Type & version)

`postgres 9.5`

###### Which operating system are you using?

docker on Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

There is not configuration file present and no jars, this is a plain usage of the docker image together with a postgres database.

command (inside the docker container): `flyway -user=... -password=... -schemas=my_schema -url=jdbc:postgresql://db:5432/postgres migrate`

SQL on `/flyway/sql/V1__Initial.sql` (mounted):

```
CREATE TABLE my_schema.table (
    my_test INTEGER NOT NULL,
    ... 
)
```

###### What did you expect to see?

The migration be applied.

###### What did you see instead?

```
Creating schema "my_schema" ...
Creating Schema History table "my_schema"."flyway_schema_history" ...
Current version of schema "my_schema": null
Schema "my_schema" is up to data. No migration necessary.
```

When `-schema=my_schema` is not passed (and `CREATE TABLE` does not include it) the migration is applied correctly.

**Comment by DoodleBobBuffPants** [comment]
Can you provide information about your configuration?
Where is `schema1` coming from?
The message indicates that no migrations were found, are you mapping the migrations folder?
I assume by `-schema` you mean `-schemas`? There is no `-schema` parameter

**Comment by jorgecarleitao** [comment]
Hi @DoodleBobBuffPants. Thanks for the quick response.

I am sorry: I have to redact names before presenting them here, and misredated one. `schema1` should have been `my_schema`. `-schema` should have been `-schemas`, as is in the command provided.

I changed the description and title to reflect these changes.

**Comment by DoodleBobBuffPants** [comment]
Can you provide the full debug output? (Pass `-X` as an argument to flyway)

**Comment by teotwaki** [comment]
Hi @jorgecarleitao,

Did you extract the DDL from the existing database? As far as I understand, Flyway can't apply new changes if it doesn't have a starting point.

https://flywaydb.org/documentation/learnmore/existing

**Comment by jorgecarleitao** [comment]
Thanks a lot for your help, "-X" really helped solving the problem. The sql directory was incorrectly mounted, which caused the sql files to be empty. Funny that it did not said that there were no files, but that is beyond the point.

Thanks a lot both for your help.
