### ISSUE TITLE
Vault Token File

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3059]
###### Which version and edition of Flyway are you using?
7.5.0 Teams

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you expect to see?
We'd like to be able to set an environment variable with a path to a file containing the Vault token.  Thus, in addition to the current `vault_token` parameter, the proposal is to add a `vault_token_file` parameter.

**Comment by DoodleBobBuffPants** [comment]
Could you tell us a bit more about why this would be useful, as opposed to putting the token directly in the existing parameter?

**Comment by esauser** [comment]
As you know, we use Concourse for our pipelines.  In Concourse enforces isolation by requiring every task to run within a Docker image.  Going along with isolation, nothing can be passed directly from one Docker image to another, it must go through a file or some other external source.  Thus, we have two options:

1. We create a single docker image that contains both `flyway` and `vault`, where we have a custom script that calls to vault, gets the token, and then calls flyway passing the token to it.

2. We use the supplied vault docker container to get the token without a custom script (just using the environment variables they support), save it to a file, pass it to the supplied flyway container, and call it using your environment variables.  The key there is that we need to be able to set an environment variable with the path to the token.

We currently use the supplied flyway container without a custom script, only a config file and environment variables.  Without this option, at a minimum, we'd have to use a custom script.

Many tools support files as inputs, generally for this reason, and many do not.

**Comment by DoodleBobBuffPants** [comment]
Thanks for the explanation

In general we'd recommend using [`configFiles`](https://flywaydb.org/documentation/configuration/parameters/configFiles) when needing to pass parameters in via a file. This means we don't have to create a file alternative for every parameter, and there doesn't seem to be anything immediate in your workflow that would prevent this from working

In particular, you would have to specify a configuration file such as `flyway-vault.conf` and in it you would provide the token as a complete parameter i.e. `flyway.vaultToken=<your token>`

Would this work?

**Comment by esauser** [comment]
The vault token is a dynamic secret, so it can't be a static value in a `configFile`.  We technically could have a script that injected it, but that's another less ideal flavor.

**Comment by esauser** [comment]
Ah, that's an interesting approach.  Have it be a unique config file just for this and generate it.  Thanks for the idea.

You are correct, that effectively means any value can be passed by file.  It might be worth making that more clear in the docs.
