### ISSUE TITLE
Snowflake 5.0 is not supported. Warning in the logs.

### ISSUE THREAD

**Issue by jsyrjala** [flyway/flyway#3061]
###### Which version and edition of Flyway are you using?

7.5.0 which is the latest version when writing this issue

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Snowflake 5.0

###### Which operating system are you using?

MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Running migrations against Snowflake.

Using Snowflake JDBC driver net.snowflake/snowflake-jdbc "3.12.15"

###### What did you expect to see?

No warnings

###### What did you see instead?

I see warning about Snowflake 5.0 beeing newer than tested & supported version.

```
21-01-21 14:36:22 MacBook-Pro-92.local INFO [org.flywaydb.core.internal.license.VersionPrinter:49] - Flyway Community Edition 7.5.0 by Redgate
21-01-21 14:36:22 MacBook-Pro-92.local INFO [org.flywaydb.core.internal.database.base.DatabaseType:49] - Database: jdbc:snowflake://xxx.xxx.snowflakecomputing.com:443/ (Snowflake 5.0)
21-01-21 14:36:22 MacBook-Pro-92.local WARN [org.flywaydb.core.internal.database.base.Database:53] - Flyway upgrade recommended: org.flywaydb.core.internal.database.snowflake.SnowflakeDatabaseType@2168ed92 5.0 is newer than this version of Flyway and support has not been tested. The latest supported version of org.flywaydb.core.internal.database.snowflake.SnowflakeDatabaseType@2168ed92 is 4.2.
```

Everything has worked as expected with Snowflake and Flyway. The only thing "wrong" is the warning in the logs.

Seems to be similar to this issue https://github.com/flyway/flyway/issues/2645

**Comment by juliahayward** [comment]
This is just a warning and indicates that we last tested against a previous version of Snowflake. I've verified all the tests pass with 7.5.0, and the warning will disappear in Flyway 7.5.2

**Comment by DoodleBobBuffPants** [comment]
This has been merged and will be available from the next release
