### ISSUE TITLE
AWS IAM database authentication support

### ISSUE THREAD

**Issue by jonnyrobots** [flyway/flyway#3062]
Add support for AWS IAM to Flyway to enable organisations to use this authentication method when connecting databases (eg. [Postgres and MySQL](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html)), and other AWS resources (eg. [S3](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_rw-bucket.html))

**Comment by DoodleBobBuffPants** [comment]
Could you explain how you expect this to work? It may just work as is - You'd configure your JDBC URL to point to a database instance like so:

`flyway.url=jdbc:mysql://<RDS_INSTANCE_HOSTNAME>:<RDS_INSTANCE_PORT>`

You then need to set the following properties:

```
flyway.jdbcProperties.verifyServerCertificate=true
flyway.jdbcProperties.useSSL=true
```

Set your `flyway.user` to be the database user and `flyway.password` to be the authentication token:

`flyway.password=<AuthToken>`

These steps were adapted from [this](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Java.html) post, so the SSL properties may not be required depending on your set up

**Comment by DoodleBobBuffPants** [comment]
We will document this instead :)

**Comment by musab** [comment]
@DoodleBobBuffPants sorry for bumping an old issue, was this ever documented?

**Comment by DoodleBobBuffPants** [comment]
There's documentation [here](https://documentation.red-gate.com/fd/authentication-184127471.html)

If you have any questions, feel free to raise a new issue :)

**Comment by Alina-Valea-Forter** [comment]
@DoodleBobBuffPants The link no longer works.

**Comment by matthewgreenwaldagility** [comment]
I _think_ the new URL is: https://documentation.red-gate.com/monitor14/enabling-aws-iam-postgresql-authentication-246972466.html
