### ISSUE TITLE
"Flyway Clean" action causes error when database contains user-defined types.

### ISSUE THREAD

**Issue by TonytheEditor** [flyway/flyway#3063]
###### Which version and edition of Flyway are you using?
Flyway Community 7.3.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Commadline (PowerShell)

###### Which database are you using? (Type & version)
SQL Server 2019

###### Which operating system are you using?
Windows 10 Enterprise

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Ran "Flyway Clean" command with a target database that contained user defined datatypes (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-type-transact-sql?view=sql-server-ver15)

###### What did you expect to see?
All schema objects removed, as described in the documentation for this command.

###### What did you see instead?
An error. The 'clean' action gets the dependency order wrong - it tries to delete the user defined types _before_ the table that references it and SQL Server won't allow you to do this so it causes an error:
Flyway : ERROR:
At line:1 char:1
+ Flyway clean
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Unable to clean schema [dbo]
----------------------------
SQL State  : S0001
Error Code : 3732
Message    : Cannot drop type 'dbo.Dollars' because it is being referenced by object 'titles'. There may be other objects that reference this type.
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot drop type 'dbo.Dollars' because it is being referenced by object 'titles'. There may be other objects that reference this
type.

**Comment by DoodleBobBuffPants** [comment]
Could you provide the SQL scripts you ran that produced this exception?

**Comment by TonytheEditor** [comment]
1. Create a project directory with a "Scripts" sub directory containing this build script (it builds a 'modernized' version of the old pubs database and fills it with some data):
[R__V1-1-2_PubWithTags.zip](https://github.com/flyway/flyway/files/5872985/R__V1-1-2_PubWithTags.zip)
2. Create an empty target database called PubsTest or whatever
3. from the project directory run "flyway migrate" using PubsTest as the target
4. then try to run "flyway clean"
