### ISSUE TITLE
Special characters in passwords not supported using command line

### ISSUE THREAD

**Issue by davemurp** [flyway/flyway#3064]
###### Which version and edition of Flyway are you using?
Found on 7.0.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Verified same exists on 7.5.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using? (Type & version)
Postgres 11.6 but can also be experienced on mysql and mssql

###### Which operating system are you using?
Windows 8

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
1. `flyway -url="jdbc:postgresql://<instance>:<port>/<database>" -user=username -password=&flyway migrate`

2. `flyway -url="jdbc:postgresql://<instance>:<port>/<database>" -user=username "-password=&flyway" migrate`

3. `flyway -url="jdbc:postgresql://<instance>:<port>/<database>" -user=username -password="&flyway" migrate`

###### What did you expect to see?
A successful migration

###### What did you see instead?
1. `The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.`
2 & 3. `ERROR: Unable to connect to the database. Configure the url, user and password!`

###### Extra Information
Editing the flyway.conf will allow for special characters but this is not a viable alternative. 
`flyway.password=&flyway`

This submission is focused only on the & character but the scope of the problem is not limited to that character.

**Comment by DoodleBobBuffPants** [comment]
This is a Powershell problem (it works fine in CMD). You need to pass the password parameter wrapped in single quotes, and the ampersand in double quotes as so:

`'-password="&"flyway'`
