### ISSUE TITLE
Support multi-line in script config files

### ISSUE THREAD

**Issue by scottsauber** [flyway/flyway#3071]
###### Which version and edition of Flyway are you using?
7.5.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
SQL Server 2014

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
In a script config file we tried the following:
```
shouldExecute=${placeHolderName} == 1234 || \
              ${placeHolderName} == 5678
```

###### What did you expect to see?
We expected to see it work since the global Config Files support multiple lines

###### What did you see instead?
`Unable to parse expression \`

It would be nice to support multiple lines in script config files like the normal config files do.  That way it doesn't show up as one big line if you have a more complex expression with lots of ||'s.  It would also be nice if there was an `IN` operator but that's a separate issue. :) 

Relevant commit for multi-line support is [here](https://github.com/flyway/flyway/commit/1ea14b7faf4eb2e668122fa389b8f0e5c7b430a0).

**Comment by DoodleBobBuffPants** [comment]
Multi-line values in script config files should work, could you provide a small script that reproduces this error?

**Comment by scottsauber** [comment]
> Multi-line values in script config files should work, could you provide a small script that reproduces this error?

I can, but it's pretty much just this inside a script config file.

```
shouldExecute=${placeHolderName} == 1234 || \
              ${placeHolderName} == 5678
```

If you need a full repro, I can do that but it will take some time.

**Comment by DoodleBobBuffPants** [comment]
Copy+pasting the example into a test works as expected. Would you be able to attach a script config file that reproduces this error?
