### ISSUE TITLE
shouldExecute causes issues on subsequent migrations for at least the Docker images

### ISSUE THREAD

**Issue by scottsauber** [flyway/flyway#3072]
###### Which version and edition of Flyway are you using?
7.5.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command Line

###### Which database are you using? (Type & version)
SQL Server 2014

###### Which operating system are you using?
Both Docker images, the base 7.5.2 version and the 7.5.2-alpine

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We used `shouldExecute` which worked perfect.  It ignored the migration when it should have and executed when it should have.  However, the subsequent migrations that did not contain `shouldExecute` failed with the following error:
```
ERROR: java.lang.IllegalArgumentException: Comparison method violates its general contract
```
Note: we have tried both the 7.5.2 Docker image and 7.5.2-alpine.

###### What did you expect to see?
It to execute subsequent migrations successfully

###### What did you see instead?
```
ERROR: java.lang.IllegalArgumentException: Comparison method violates its general contract
```

**Comment by esauser** [comment]
Note that this error only occurs if the previous migration was not applied.  For example, if migration 1 `shouldExecute` at server 1 but not server 2, when migration 2 comes along and does not have `shouldExecute`, it will succeed at server 1 and fail with this error at server 2.

**Comment by DoodleBobBuffPants** [comment]
Could you attach sample scripts and script config files that reproduces this? I haven't been able to reproduce this, so there might be subtle differences in the script or environmental differences that are causing this (and possibly https://github.com/flyway/flyway/issues/3071 too)

**Comment by scottsauber** [comment]
I'm trying to do a minimal repro but struggling.  I have a suspicion this could be because our placeholder name is "serverName" and that appears to be a reserved placeholder.  Because locally if I have a Docker container running SQL Server and I plugin a URL pointed at localhost and set a placeholder serverName of "test123" then Flyway tried to connect to "test123" instead of `localhost`.

I will try using a different placeholder tomorrow and report back.

**Comment by DoodleBobBuffPants** [comment]
Any update on this?

**Comment by esauser** [comment]
@DoodleBobBuffPants we haven't had time to circle back to it yet.  It's on our list.  It definitely broke for us, and when we tried it completely new it did not break.  So now we're trying to figure out why it broke.  Clearly something with our setup.

**Comment by DoodleBobBuffPants** [comment]
Thanks for letting us know, will be closing until further activity
