### ISSUE TITLE
Flyway Gradle Plugin in combination with Gradle Eclipse plugin adds source folder that does not exist.

### ISSUE THREAD

**Issue by twwwt** [flyway/flyway#3075]
###### Which version and edition of Flyway are you using?
7.5.2; issue has been observed with 6.5.7 as well

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin in combination with Eclipse.

###### Which database are you using? (Type & version)
irrelevant

###### Which operating system are you using?
Mac OS 10.15.7, Java 11.0.8

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
run `gradle cleanEclipse eclipse` in a shell

###### What did you expect to see?
We apply Flyway's Gradle plugin to one of our builds, just to get the corresponding Flyway Gradle tasks. The project neither configures the flyway plugin in any way (i.e., there is no `flyway { /*...*/ }` section in the `build.gradle` file) nor does the project contains any Java migration implementations; i.e., there is no dedicated Java source folder `main-java`. We do, however, have standard Java code in the project; i.e., there exists a non-empty Java source folder `src/main/java` that contains "normal" Java code.

###### What did you see instead?
A source folder `main-java` is added to the Eclipse configurations, see screenshot below. This source folder is correctly marked as missing by Eclipse as it does not exist. This causes Eclipse not to build the project unless the source folder is removed manually.

Is this a bug? If not, what can be done to prevent the Flyway Gradle plugin (or the Eclipse Gradle plugin?) to add this folder?

<img width="813" alt="missing_source_folder" src="https://user-images.githubusercontent.com/143208/107025893-50a4a200-67aa-11eb-8804-a9ea64abd93e.png">

**Comment by DoodleBobBuffPants** [comment]
This is a known 'feature' of the eclipse gradle plugin. See this forum post: https://discuss.gradle.org/t/non-existing-directories-added-to-eclipse-classpath/1652
As such, there isn't anything Flyway can do about it

**Comment by twwwt** [comment]
I don't understand why a non-existing directory is _configured_ anyway. I would, if it was existing while empty.

Anyway, I'm working around this issue now in the following way:

```groovy
eclipse
{
	classpath
	{
		file
		{
			whenMerged { classpath ->
				classpath.getEntries().removeAll { it.path == 'main-java' }
			}
		}
	}
}
```
