### ISSUE TITLE
PLS-00172: string literal too long

### ISSUE THREAD

**Issue by BaburaoLad** [flyway/flyway#3076]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.3.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

###### Which operating system are you using?

linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Trying to compile packages body which has CLOB variable declared with length more than 500 lines which is not supported by flyway and shows above error.

###### What did you expect to see?
Package body should compile successfully .

###### What did you see instead?

 line 72/31    PLS-00172: string literal too long

**Comment by DoodleBobBuffPants** [comment]
This error code is indicative of an issue with your SQL and not Flyway's ability to handle large statements. Flyway already uses prepared statements which is the recommended approach for handling large statements, but in this case the error code means your own string literal is too long. See [this](http://nimishgarg.blogspot.com/2014/10/pls-00172-string-literal-too-long.html) post or [this](https://asktom.oracle.com/pls/apex/f?p=100:11:0::::P11_QUESTION_ID:1202548400346932817) post for actions you can take
