### ISSUE TITLE
Make the default ResourceProvider available via the Configuration interface

### ISSUE THREAD

**Issue by ericparton** [flyway/flyway#3077]
Hello,

My organization has a custom migration resolver that needs to search for migration files in the same way that the rest of Flyway does. Unfortunately, the only way this appears to be possible is through the use of the internal Scanner class. We've been using this for a number of years, but we'd like to move away from using internal classes, since they often change and make upgrading more difficult.

With the recent addition of the getResourceProvider() method to the Configuration interface, we were optimistic that we would finally be able to end our reliance on the internal Scanner class. However, we discovered that this method deliberately returns null when no custom ResourceProvider has been set.

Would it be possible to have the getResourceProvider() method return the default ResourceProvider, instead of null, when no custom ResourceProvider is set?

If the change were implemented, it would allow us to replace code that looks like this:

```
import org.flywaydb.core.internal.scanner.LocationScannerCache;
import org.flywaydb.core.internal.scanner.ResourceNameCache;
import org.flywaydb.core.internal.scanner.Scanner;

@Override
public Collection<ResolvedMigration> resolveMigrations( Context context )
{
	Configuration config = context.getConfiguration();

	Scanner<JavaMigration> scanner = new Scanner<>(
	        JavaMigration.class,
	        Arrays.asList(config.getLocations()),
	        config.getClassLoader(),
	        config.getEncoding(),
	        false,
	        new ResourceNameCache(),
	        new LocationScannerCache()
	);

	for ( Resource resource : scanner.getResources( config.getSqlMigrationPrefix(), CSV_SUFFIXES ) )
	{
		//do something
	}
}
```
...with code that does not rely on internal classes and is also simpler and more maintainable:

```
@Override
public Collection<ResolvedMigration> resolveMigrations( Context context )
{
        Configuration    config           = context.getConfiguration();
        ResourceProvider resourceProvider = config.getResourceProvider();

        for ( Resource resource : resourceProvider.getResources( config.getSqlMigrationPrefix(), CSV_SUFFIXES ) )
        {
    	         //do something
        }
}
```

**Comment by madninjaskillz** [comment]
`getResourceProvider` is designed to only be interested in custom implementations as our own scanner is already fully configurable. We wish to keep this approach as it allows us to ascertain if the implementation is custom.

There are a multitude of other reasons to avoid changing this, the primary being that it is a niche request and a breaking change. As such, we cannot commit to making this change at this current time. 

That said, Flyway already has support for setting [custom suffixes](https://flywaydb.org/documentation/configuration/parameters/sqlMigrationSuffixes) which is what your example seems to be focused on.
