### ISSUE TITLE
Error setting current schema to "FLYWAY_ACCOUNT_STATE" on Snowflake

### ISSUE THREAD

**Issue by damianslee** [flyway/flyway#3079]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.5.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line with Snowflake JDBC driver 3.12.17.  
Own docker image rebuilt from flyway DockerFile with latest snowflake driver.

###### Which database are you using? (Type & version)
Snowflake

###### Which operating system are you using?
Ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I am using flyway to manage database creation, account administration of snowflake. 
This flyway state is stored in a database called Management.   The migration scripts Create other databases, roles, warehouse.  This flyway instance isn't used to manage these other databases.

Looking through the Snowflake SQL history for the user, it shows that there are two snowflake sessions from flyway.  one that created the database, and one which is issuing some of the flyway state commands.   Quite often some of the flyway state command are executed on the session that created the database, which then fail as the current database is incorrect.

###### What did you expect to see?
successful flyway state change.

###### What did you see instead?
SHOW SCHEMAS LIKE 'FLYWAY_ACCOUNT_STATE'  [Snowflake SessionID: 88257283035190]
success

USE SCHEMA "FLYWAY_ACCOUNT_STATE"   [Snowflake SessionID: 88257283035194]
SQL compilation error:
Object does not exist, or operation cannot be performed.

**Comment by DoodleBobBuffPants** [comment]
Flyway is designed to manage a schema or schemas within a database. Managing other databases using one history table is typically an unsupported scenario, in that Flyway needs to be able to reset the default schema in between migrations, such as for callbacks. We won't be committing to making any changes that enable this, although you can make it work for your scenario by ensuring that your migrations set the current database to the one containing the history table
