### ISSUE TITLE
Gradle plugin without java plugin ignores configurations classpath

### ISSUE THREAD

**Issue by TarodBOFH** [flyway/flyway#3084]
###### Which version and edition of Flyway are you using?

Community, 7.5.3 :
```
plugins {
    id("org.flywaydb.flyway") version "7.5.3"
}
``` 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using? (Type & version)

It doesn't matter, but the example in the attached git repo is with MySQL 8.0.23

###### Which operating system are you using?

It doesn't matter. It is a Gradle-plugin bug... anyway, it happens on official Gradle docker images, windows, MacOS... 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I added just flyway to an empty project and added mysql driver to a configurations block. The driver is not loaded during flyway tasks inside gradle-plugin

###### What did you expect to see?
A connection timeout instead of a missing driver.
```
Executing task 'flywayInfo'...

> Task :flywayInfo FAILED
1 actionable task: 1 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayInfo'.
> Error occurred while executing flywayInfo
  
  Unable to obtain connection from database (jdbc:mysql://localhost?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8) for user 'root': Could not create connection to database server. Attempted reconnect 3 times. Giving up.
...
```

###### What did you see instead?
A missing driver error:

```
Executing task 'flywayInfo'...

> Task :flywayInfo FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayInfo'.
> Error occurred while executing flywayInfo
  Unable to instantiate JDBC driver: com.mysql.cj.jdbc.Driver => Check whether the jar file is present
  Unable to instantiate class com.mysql.cj.jdbc.Driver : com.mysql.cj.jdbc.Driver
  com.mysql.cj.jdbc.Driver
```

I've created a minimal gradle project that reproduces both behaviors in two git branches at https://github.com/TarodBOFH/flyway-without-java-bug

I'll be submitting a pull request with the fix as soon as I finish writing the issue.

**Comment by DoodleBobBuffPants** [comment]
Closing this to continue on the PR instead
