### ISSUE TITLE
Document Magic Placeholders

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3087]
###### Which version and edition of Flyway are you using?
7.5.3 Teams

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Executed `flyway migrate` with a placeholder named `serverName`.

###### What did you expect to see?
Successful connection

###### What did you see instead?
Unsuccessful connection.

It appears to have failed because `serverName` is a reserved placeholder for the connection.  In our case, the placeholder was not fully qualified, but the connection string was.  But this placeholder overrode the connection string, and thus, failed to connect.

We didn't see any documentation about this magic placeholder.  What others are there?  Can they all be documented?

**Comment by DoodleBobBuffPants** [comment]
Flyway passes its placeholders as additional properties to the data source, and `serverName` is a placeholder in MSSQL which is why this occurs. We will document this on the placeholders page
