### ISSUE TITLE
flyway info fails on subsequent migrations after shouldExecute

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3088]
###### Which version and edition of Flyway are you using?
7.5.3 Teams

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We deployed a versioned migration that was toggled via a `shouldExecute` script config.  We're deploying to a multi-tenant environment and used the `hostName` placeholder to control it.  Each tenant has a storeCode.  So our `shouldExecute` contained some stores but not others.  Thus, store A got the migration, but store B did not.  This worked correctly.

We then came back with a subsequent versioned migration.  This one was not toggled with a `shouldExecute` scrip config.  We ran `flyway info` for this migration.

###### What did you expect to see?
`flyway info` output

###### What did you see instead?
For store A (the one that got the previous migration) we saw the output.

For store B (the one the didn't get it), however, we saw the following error
```
{
  "error": {
    "errorCode": "FAULT",
    "message": "Comparison method violates its general contract!",
    "stackTrace": "java.lang.IllegalArgumentException: Comparison method violates its general contract! 
at java.base/java.util.ComparableTimSort.mergeHi(Unknown Source) 
at java.base/java.util.ComparableTimSort.mergeAt(Unknown Source)
at java.base/java.util.ComparableTimSort.mergeForceCollapse(Unknown Source)
at java.base/java.util.ComparableTimSort.sort(Unknown Source)
at java.base/java.util.Arrays.sort(Unknown Source)
at java.base/java.util.Arrays.sort(Unknown Source)
at java.base/java.util.ArrayList.sort(Unknown Source)
at java.base/java.util.Collections.sort(Unknown Source)
at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:744)
at org.flywaydb.core.internal.command.DbInfo.info(DbInfo.java:446)
at org.flywaydb.core.Flyway$6.execute(Flyway.java:772)
at org.flywaydb.core.Flyway$6.execute(Flyway.java:767)
at org.flywaydb.core.Flyway.execute(Flyway.java:957)
at org.flywaydb.core.Flyway.info(Flyway.java:767)
at org.flywaydb.commandline.Main.executeOperation(Main.java:620)
at org.flywaydb.commandline.Main.main(Main.java:531)
"
  }
}
```

This is a continuation of https://github.com/flyway/flyway/issues/3072 and almost the exact behavior that we saw there.  The only difference is this time we used a different placeholder name (it was `serverName` before which is where https://github.com/flyway/flyway/issues/3087 came from) and this time `flyway migrate` actually worked at both.  Only `flyway info` failed at the one.

We are using the 7.5.3-alpine docker image to reproduce this.

_edit: added newlines to stack trace - JH_

**Comment by juliahayward** [comment]
To clarify: each tenant has a separate history table? Would you be able to send us the contents of the offending one?

**Comment by esauser** [comment]
Yes, each tenant has its own history table.  They are completely separate SQL servers. 

The offending store doesn't contain anything at all for the previous migration that wasn't toggle to it.  Let's say V1 was toggled to store A but not store B.  Store B is the one that will fail when V2 comes around, and it will have no trace of V1 in the history table.

If you still desire the contents, what format works?  Insert script?

**Comment by juliahayward** [comment]
Insert script would be great. You can mail it to julia.hayward@red-gate.com rather than post it here.

**Comment by esauser** [comment]
Script sent via email.

**Comment by juliahayward** [comment]
Many thanks - we'll get to work on it!
