### ISSUE TITLE
flyway info fails on subsequent migrations after shouldExecute

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3091]
###### Which version and edition of Flyway are you using?
7.5.4 Teams

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Upgraded to 7.5.4.  See #3088 

###### What did you expect to see?
Success

###### What did you see instead?
Same failure as #3088

**Comment by scottsauber** [comment]
Thank you!
