### ISSUE TITLE
modification of migrated file name not subsequently detected by validate action

### ISSUE THREAD

**Issue by sikarazj** [flyway/flyway#3094]
###### Which version and edition of Flyway are you using?
 7.3.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command line 

###### Which database are you using? (Type & version)
Redshift

###### Which operating system are you using?
linux redhat

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
After after a successful migration of a number of files, rename by removal prefix char from last file e.g. V3__insert.sql to 3_insert.sql then run validation.

###### What did you expect to see?
I expected the modification of migrated file(s) including its name to be detected on validation

###### What did you see instead?
The alteration of filename(s) already migrated was not detected e.g. validation did not fail.

Note: if migrate is run subsequently in same scenario it does correctly fail

**Comment by Rixium** [comment]
Hey @sikarazj,

This is the default behaviour in Flyway.
There's some documentation [here](https://flywaydb.org/documentation/configuration/parameters/ignoreFutureMigrations) about this.

In particular you can force Flyway to fail, by setting `-ignoreFutureMigrations="false"`

**Comment by sikarazj** [comment]
Hi Rixium, 
Thank you for the feedback and analysis.
I guess the bit that is at odds in my mind (that is similar but diiferent) is that the defaults are:
-ignoreFutureMigrations="true"
-ignoreMissingMigrations="false"
(In upgrading from flyway version 6.5.7 to 7+ latest)
So the second config item must be explicitly added to maintain the previous 6+ behaviour
