### ISSUE TITLE
Validate existing indexes as part of the validation process

### ISSUE THREAD

**Issue by arbuz55555** [flyway/flyway#3095]
###### Which version and edition of Flyway are you using?

The latest 

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

---

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle

###### Which database are you using? (Type & version)

Cockroach/MySQL/PostgreSQL

###### Which operating system are you using?

Linux/MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I would like to have an option (new settings) in flyway to  validate indexes as part of the migration validation process (not part as afterMigrate callback)

###### What did you expect to see?

I would like to have an option to validate the indexes (not only columns) and if that fail then generate the report or 
terminate the microservice bootstrap (terminate could be the option as well not default behaviour!)

###### What did you see instead?

----

**Comment by DoodleBobBuffPants** [comment]
This isn't the direction we want to take Flyway in at the moment - Validate is for validating the Flyway state. It also seems you already have a solution using callbacks so you aren't blocked

We will reconsider this should it garner more interest
