### ISSUE TITLE
[Question] How to debug and test flyway in IDEA with this source code

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [flyway/flyway#3096]
###### Which version and edition of Flyway are you using?
master

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Mysql 8.0

###### Which operating system are you using?
Windows10  x64

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Sorry to ask such a question. But I really want to learn how to become a contributor of flyway.

After finished migration in my springboot application with flyway. I decided to get a deeper learning of using flyway.

I have forked the source code and trying to run it in debug mode by IDEA. Hoping that someday I could be able to contribute something.

So far I didn't figure out how to run this source code according to [contributor ducuments.](https://flywaydb.org/documentation/contribute/code/setup)

Here is the replaced jre in my customized maven repository:
![image](https://user-images.githubusercontent.com/58684828/109489428-d1ad3b80-7ac1-11eb-9311-650608d5f239.png)

And by running command :
mvn install:install-file -DgroupId=net.adoptopenjdk -DartifactId=jre -Dclassifier=windows-x64 -Dtype=zip -Dversion=11.0.2 -Dpackaging=zip -Dfile=jre-11.0.2-windows-x64.zip -e

Here comes the Maven exception screenshot:
![image](https://user-images.githubusercontent.com/58684828/109489326-a3c7f700-7ac1-11eb-96a6-b1f7dae55b24.png)
![image](https://user-images.githubusercontent.com/58684828/109489339-a9bdd800-7ac1-11eb-8e9a-aba4331ed5a4.png)

Not very familiar with setting maven manually. 

If convenient, please tell me how to test flyway-core if I have the source code modified.
or
How to install my new modification of flyway-core into maven and then use it in my springboot application for test.

Thank a lot for helping me aboud this situation.

**Comment by DoodleBobBuffPants** [comment]
Following the instructions [here](https://flywaydb.org/documentation/contribute/code/setup) should suffice

Some things I've noticed:
- When invoking Maven you have modified the `-Dfile` parameter from what is on the docs page. It should be `-Dfile=OpenJDK11U-jre_x64_windows_hotspot_11.0.2_9.zip`
- The JDK zip needs to be in your Maven repository folder. This is the `.m2\repository` folder that Maven will create in your user folder i.e. `C:\Users\<user>\.m2`

For your last question, you will want your application to be dependent on your local Flyway project. You can read about how to do that [here](https://stackoverflow.com/questions/15383322/how-do-i-add-a-project-as-a-dependency-of-another-project)

**Comment by WilliamChen-luckbob** [comment]
> Following the instructions [here](https://flywaydb.org/documentation/contribute/code/setup) should suffice
> 
> Some things I've noticed:
> 
> * When invoking Maven you have modified the `-Dfile` parameter from what is on the docs page. It should be `-Dfile=OpenJDK11U-jre_x64_windows_hotspot_11.0.2_9.zip`
> * The JDK zip needs to be in your Maven repository folder. This is the `.m2\repository` folder that Maven will create in your user folder i.e. `C:\Users\<user>\.m2`
> 
> For your last question, you will want your application to be dependent on your local Flyway project. You can read about how to do that [here](https://stackoverflow.com/questions/15383322/how-do-i-add-a-project-as-a-dependency-of-another-project)

@DoodleBobBuffPants 
Thanks a lot for your help!

But that 2 questions still remains:

Maybe I have some misunderstandings about the doc you just gave me.

Doc told me to put that downloaded zip as ~/.m2/repository/net/adoptopenjdk/jre/11.0.2/jre-11.0.2-windows-x64.zip.

But my maven repository was already set to D://mavenrepository for not enough . So I decided to create directories and put that zip into my customized maven repository.

Afterwards I also tried to rename the zip as jre-11.0.2-windows-x64.zip, but no matter I set the zip file as jre-11.0.2-windows-x64.zip or OpenJDK11U-jre_x64_windows_hotspot_11.0.2_9.zip , 
by using command:
mvn install:install-file -DgroupId=net.adoptopenjdk -DartifactId=jre -Dclassifier=windows-x64 -Dtype=zip -Dversion=11.0.2 -Dpackaging=zip -Dfile=OpenJDK11U-jre_x64_windows_hotspot_11.0.2_9.zip

there comes the same exception and I can't pass the compile.

The maven I used is IDEA bundled maven v3.6.3

![image](https://user-images.githubusercontent.com/58684828/109587970-eed61e80-7b42-11eb-9f30-68688535a25e.png)

I wonder if the maven repository is required to be set as default  C:\Users\<user>\.m2\repository. Or should I download independent maven to build the source code?

Thank you again for your help!

**Comment by DoodleBobBuffPants** [comment]
Thanks for sharing

You shouldn't manually move the downloaded JRE zip into your maven repository. Once you have downloaded it, you should run the `mvn` command from the root of the Flyway repository (`flyway-parent`) and this will automatically unzip the JRE into your local Maven repository. The downloaded JRE zip should be placed into the root of the Flyway repository before running the `mvn` command, or you can set `-Dfile` to have the full path to the JRE zip i.e. `-Dfile=C:\users\<user>\Downloads\...`

When running `mvn` from the command-line in this case you need to ensure that it is the Maven that is bundled with IDEA that you are running, which can be done by adding its directories to your `PATH` as stated [here](https://flywaydb.org/documentation/contribute/code/setup#maven). If you are unsure, then download Maven independently
