### ISSUE TITLE
Caused by: java.lang.TypeNotPresentException: Type org.flywaydb.core.api.callback.FlywayCallback not present -->community edition 7.5.4 i am using java version any one pls help for the same

### ISSUE THREAD

**Issue by mohammad-sk** [flyway/flyway#3097]

**Comment by DoodleBobBuffPants** [comment]
Please use the issue template

This sounds like you are trying to use something from an older version of Flyway in the newest version. For information about how to use callbacks in Flyway V7 see [this](https://flywaydb.org/documentation/concepts/callbacks#java-callbacks)

**Comment by mohammad-sk** [comment]
Hi Team ,

i am trying to use 6.0.8 version which is compatible with spring boot 2.2.5
version and i am trying to execute migration using java api
flyway.migrate().
Please help me and i am facing issue of


org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'flywayInitializer' defined in class path resource
[org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]:
Invocation of init method failed; nested exception is
org.flywaydb.core.api.FlywayException: Unable to parse statement in
db/migration/V1_1__Identity_Service_dml.sql at line 1 col 1: No value
provided for placeholder: ${USER_NAME}.  Check your configuration!
        at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)
~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at
org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at
org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at
com.bkgaming.bkpoker.service.identity.BKPokerIdentityServiceApplication.main(BKPokerIdentityServiceApplication.java:28)
~[classes!/:sp09-SNAPSHOT]
        at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method) ~[na:na]
        at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
~[na:na]
        at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
~[na:na]
        at
org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
~[identity-service-sp09-SNAPSHOT.jar:sp09-SNAPSHOT]

Caused by: org.flywaydb.core.api.FlywayException: Unable to parse statement
in db/migration/V1_1__Identity_Service_dml.sql at line 1 col 1: No value
provided for placeholder: ${USER_NAME}.  Check your configuration!

**Comment by DoodleBobBuffPants** [comment]
The error indicates that you are attempting to use a placeholder for which you haven't provided a value. There is documentation about placeholders in V6 [here](https://flywaydb.org/documentation/v6/placeholders). If that doesn't solve your issue then we ask if you're able to reproduce the issue in the latest version. V7 documentation is [here](https://flywaydb.org/documentation/configuration/placeholder)

**Comment by mohammad-sk** [comment]
Thank you for your response.
