### ISSUE TITLE
Check Flyway Migration Filename Prefix for Uniqueness at Build Time

### ISSUE THREAD

**Issue by zwbetz-gh** [flyway/flyway#3101]
Hi Flyway team, thank you for this useful tool. Please see request details below.

**Is your feature request related to a problem? Please describe.**
A Flyway migration filename prefix must be unique. If it is not unique, then Flyway will fail at **run-time**. This means that duplicate prefixes could be merged, and it would not be discovered until the app was deployed.

**Describe the solution you'd like**
Allow Flyway to check prefixes for uniqueness at **build-time**, when using the Java API.

**Describe alternatives you've considered**
Originally written about [here](https://zwbetz.com/check-flyway-migration-filename-prefix-for-uniqueness-at-build-time/), I'm using a Gradle task to accomplish this. It works just fine, but it would be even cooler if Flyway had this functionality built-in.

```groovy
task checkFlywayMigrationFilenamePrefixForUniqueness() {

  // Document the task
  group = 'Verification'
  description = 'Check Flyway migration filename prefix for uniqueness'

  // Provide the Action block
  doLast {

    // The default Flyway locations dir is src/main/resources/db/migration
    // So, go one level up, in case custom dirs are used
    def dir = "src/main/resources/db"

    // Get a list of filenames
    def filenames = fileTree(dir).files.name

    // Get a list of prefixes
    def prefixes = filenames.collect { it.split("__")[0] }

    // Check each prefix
    prefixes.each {

      // Get how many times the prefix appears in the list
      def count = prefixes.count(it)

      // If the prefix is not unique, throw an exception
      if (count > 1) {
        throw new GradleException("Flyway migration filename prefix is not unique: $it")
      }
    }
  }
}

// Tell it to run after the build task
build.finalizedBy(checkFlywayMigrationFilenamePrefixForUniqueness)
```

**Comment by DoodleBobBuffPants** [comment]
Running [`validate`](https://flywaydb.org/documentation/command/validate) will also validate migration filenames, so you can call this at build. We won't be doing this automatically, as this approach is more flexible and doesn't force everyone into a build-time validation. If this functionality gets more interest we will come back to it, but closing for now
