### ISSUE TITLE
Add support for arm32v7 (RPi)

### ISSUE THREAD

**Issue by fagnercarvalho** [flyway/flyway#3102]
###### Which version and edition of Flyway are you using?
latest-alpine

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI from Docker

###### Which database are you using? (Type & version)
PostgreSQL

###### Which operating system are you using?
RPi OS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Tried to run the container and got this:

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

This normally happens when there is a discrepancy between the architecture of the executable and the target OS.

Would it be possible to make it available a container or an executable for ARM?

**Comment by DoodleBobBuffPants** [comment]
There is an open issue in our docker repo [here](https://github.com/flyway/flyway-docker/issues/37), so this is on our radar

Closing this one as a duplicate
