### ISSUE TITLE
Introducing a MigratedDataSource interface for easier integration

### ISSUE THREAD

**Issue by alanfranz** [flyway/flyway#3108]
###### Which version and edition of Flyway are you using?
7.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
PostgreSQL

###### Which operating system are you using?
Ubuntu Linux 20.04

**This is a feature request**. I'll be happy to provide a PR if it seems interesting to the development team

The currently recommended way to use Flyway in a Spring context is to rely on dependsOn (https://flywaydb.org/documentation/usage/api/#spring-configuration):

Example from doc:
```<bean id="sessionFactory" class="..." depends-on="flyway">```

While it works, it's sometimes a bit cumbersome and error-prone, especially when doing some config overrides for testing or other purposes. Sometimes a dependsOn just slips out of the way, and everything breaks without an apparent reason, since it tries to work with an non-migrated database.

My idea would be to introduce a marker interface, e.g. ```MigratedDataSource``` which just extends Java's DataSource interface, along with a default implementation which just delegates to the original datasource. Then, all beans depending on flyway being run before them can just rely on such type. The idea would be something like this (pseudojava) for a Spring java-based context:

```
@Bean
public MigratedDataSource flyway(DataSource ds) {
          ...
          Flyway.configure().datasource(ds)
          ...
          flyway.migrate()
          return new DelegatingDataSource(ds)
}

```

let me know if you think the idea interesting and useful. I know this can be done entirely outside Flyway (and I have done something similar already in some projects), but I think it would be useful to have it within the library.

**Comment by Rixium** [comment]
Hey @alanfranz ,

We don't maintain integrations in this project, but instead aim to make our API as interoperable as possible,
however if this gains more traction then we'll consider it, but we'll close it for now.
