### ISSUE TITLE
Characters `GO ` incorrectly parsed as a GO statement

### ISSUE THREAD

**Issue by rchurchley** [flyway/flyway#3110]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 7.7.0 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

MSSQL 2019 (Docker)

###### Which operating system are you using?

Docker container based on RHEL.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Run the following migrations against a fresh empty database.

V1__table.sql
```sql
CREATE TABLE Customer (ID BIGINT, LOGO NVARCHAR(50))
```

R__sproc.sql
```sql
CREATE OR ALTER PROCEDURE GetCustomers AS SELECT c.ID, c.LOGO FROM Customer c
```

###### What did you expect to see?

The repeatable migration should run and create the stored procedure.

###### What did you see instead?

```
Migration R__sproc.sql failed
-----------------------------
SQL State  : S1000
Error Code : 4104
Message    : The multi-part identifier "c.LO" could not be bound.
Location   : ./Tables/R__sproc.sql (/concur/./Tables/R__sproc.sql)
Line       : 1
Statement  : CREATE OR ALTER PROCEDURE GetCustomers AS SELECT c.ID, c.LO

Caused by: java.sql.SQLException: The multi-part identifier "c.ID" could not be bound.
```

###### Further details

The migration succeeds if you don't capitalize the non-GO "go":

```sql
CREATE OR ALTER PROCEDURE GetCustomers AS SELECT c.id, c.logo FROM Customer c
```

It also succeeds when GO is found elsewhere in the line:

```sql
CREATE OR ALTER PROCEDURE GetCustomers AS SELECT c.LOGO, c.id FROM Customer c
```

```sql
CREATE OR ALTER PROCEDURE GetCustomers AS SELECT c.id, c.[LOGO] FROM Customer c
```

The distinguishing factor appears to be when the characters GO is immediately followed by whitespace, which comes into play before or during the parsing. The following migration succeeds:

```sql
CREATE OR ALTER PROCEDURE GetCustomers AS SELECT c.id, c.LOGO--
FROM Customer c
```

but the following fails:
```sql
CREATE OR ALTER PROCEDURE GetCustomers AS SELECT c.id, c.LOGO --
FROM Customer c
```

**Comment by Rixium** [comment]
Hey @rchurchley ,

Thanks for spotting the bug!
We've been looking at this today, and a fix should be released soon,

Thanks a lot 😃
