### ISSUE TITLE
Flyway 6.5.4 migrate error com.microsoft.sqlserver.jdbc.TDSTokenHandler onColMetaData

### ISSUE THREAD

**Issue by sagardsouza** [flyway/flyway#3113]
###### Which version and edition of Flyway are you using?
Flyway 6.5.4 Enterprise

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
It will take to reproduce the issue in latest version as it needs to be upgraded from existing running DB

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-Line

###### Which database are you using? (Type & version)
MS SQL Server 2012

###### Which operating system are you using?
Windows OS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
There is nothing wrong with the SQL script (contians only INSERT, UPDATE commands) as App Team able to execute in locally also able to deploy to SIT server manually. I have also executed the SQL script locally with the help of Flyway 6.5.4 however, we are running Flyway cmd using Jenkins Pipeline, with below flyway commands:
Command:
We first run this command below after the println but it was not executed
"----------------------Database Migrate----------------------------"
call %flyway_ver%\flyway.cmd -enterprise -url=%dbConnectionString%;databaseName=%database% -user=%database_user% -password=%database_pwd% -locations=filesystem:%CurrentWorkingDirectory%/db_execute/%database% -table=%FLYWAY_TABLE% info | findstr /v /c:"DEBUG" >> flyway.log

Then, the subsequent command below is throwing the error
call %flyway_ver%\flyway.cmd -enterprise -outOfOrder=%outOfOrder% -url=%dbConnectionString%;databaseName=%database% -user=%database_user% -password=%database_pwd% -baselineVersion=%baseline% -locations=filesystem:%CurrentWorkingDirectory%/db_execute/%database% -target=%target% -table=%FLYWAY_TABLE% migrate | findstr /v /c:"DEBUG" >> flyway.log
Command:
We first run this command below after the println but it was not executed
"----------------------Database Migrate----------------------------"
call %flyway_ver%\flyway.cmd -enterprise -url=%dbConnectionString%;databaseName=%database% -user=%database_user% -password=%database_pwd% -locations=filesystem:%CurrentWorkingDirectory%/db_execute/%database% -table=%FLYWAY_TABLE% info | findstr /v /c:"DEBUG" >> flyway.log

Then, the subsequent command below is throwing the error
call %flyway_ver%\flyway.cmd -enterprise -outOfOrder=%outOfOrder% -url=%dbConnectionString%;databaseName=%database% -user=%database_user% -password=%database_pwd% -baselineVersion=%baseline% -locations=filesystem:%CurrentWorkingDirectory%/db_execute/%database% -target=%target% -table=%FLYWAY_TABLE% migrate | findstr /v /c:"DEBUG" >> flyway.log

###### What did you expect to see?
Flyway Migration should be success

###### What did you see instead?
Error:
Mar 16, 2021 12:27:56 PM com.microsoft.sqlserver.jdbc.TDSTokenHandler onColMetaData
10:00:07  SEVERE: ConnectionID:1 ClientConnectionId: 7bf6b91b-a3c3-4bdf-a6ef-13e4579251c5: batch completion: Encountered TDS_COLMETADATA (0x81). SHOWPLAN is ON, ignoring.

**Comment by Rixium** [comment]
Closing as being handled via customer support 😊
