### ISSUE TITLE
Missing information in documentation

### ISSUE THREAD

**Issue by KalleJohansson** [flyway/flyway#3114]
###### Which version and edition of Flyway are you using?
7.7.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle

###### Which database are you using? (Type & version)
Postgresql 13.2-1

###### Which operating system are you using?
Debian/Ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
gradle flywayClean flywayMigrate

###### What did you expect to see?
The following warning:
"Flyway upgrade recommended: PostgreSQL 13.2 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 12."

###### What did you see instead?
No warning.

After upgrading from using Flyway 6.4.1 to Flyway 7.7.0, running commands, warnings about unsupported Postgresql version disappeared.

If indeed Postgresql 13 is supported, my feeling is that it would be more clarifying if the documentation is updated.
(i belive the documentation around supported versions of postgresql may have been brought up in this issue to, https://github.com/flyway/flyway/issues/2952).

**Comment by Rixium** [comment]
Hey @KalleJohansson ,

Thanks for this, I'll update the documentation 😊

**Comment by KalleJohansson** [comment]
Thanks 👍

Den tors 18 mars 2021 14:59Daniel Pottenger ***@***.***>
skrev:
