### ISSUE TITLE
Java API: Flyway.schemas() usage

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#3117]
From a support ticket: it's not 100% obvious that these two situations are **not** the same and that Flyway will error on one of them. Can we either spot comma-separated lists (as you'd use that form for a config file) and split them, or improve the documentation?

Good:
```
Flyway f = Flyway.configure().defaultSchema("bar").schemas("foo,bar").load();
```

Bad:
```
Flyway f = Flyway.configure().defaultSchema("bar").schemas("foo", "bar").load();
```

**Comment by DoodleBobBuffPants** [comment]
The latter is actually the correct case, and there's a pending fix in the documentation [here](https://github.com/flyway/flywaydb.org/pull/299)

It's also how we handle all list properties in the API, and we can't reliably change it since schema names can themselves contain commas

**Comment by juliahayward** [comment]
Doh! I'd put the wrong "good" and "bad" labels!
