### ISSUE TITLE
Support for a `ignoreRepeatableMigrations` parameter

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3121]
###### Which version and edition of Flyway are you using?
7.7.0 Teams

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Upgraded from `6.1.2` and ran `flyway migrate`.

###### What did you expect to see?
Successful validation and no migrations executed (since we didn't change anything).

###### What did you see instead?
```
ERROR: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: MIGRATION_NAME If you removed this migration intentionally, run repair to mark the migration as deleted.
```
For each `repeatable` migration that we've deleted.

We pinpointed the issue to the `7.0.0` release.  We're actually seeing the exact opposite behavior described [here](https://flywaydb.org/blog/flyway-7.0.0-beta#delete-repeatable-migrations).  That scenario worked for us before, but no longer does after the upgrade.

While the suggestion to run `flyway repair` works, this isn't sustainable for us since everything is done through a pipeline.  How can we get `flyway` to succeed as before and allow for deleted repeatable migrations?

**Comment by MikielAgutu** [comment]
So to confirm, in Flyway 6.1.2 deleted repeatable migrations didn't cause validation errors for being missing - but in 7.7.0 they do?

If that's the case, it sounds like perhaps that was a bug in an earlier version. If an applied migration is deleted, Flyway should produce a validation error. So that behavior is more correct in the latest versions. I think the right thing is to run `repair`, or re-introduce the scripts.

> While the suggestion to run flyway repair works, this isn't sustainable for us since everything is done through a pipeline. How can we get flyway to succeed as before and allow for deleted repeatable migrations?

Can you not amend your pipelines to always run repair before migrating in all your environments?

**Comment by madninjaskillz** [comment]
In versions previous to 7.0.0, `ignoreMissingMigrations` was defaulted to `true`, in 7.0.0 that is now defaulted to `false`. You should be able to set this back to `true` in config to replicate 6.x behavior. This will need to be enabled during `migrate` as this runs validation (which would fail without `ignoreMissingMigrations` set to true)

**Comment by esauser** [comment]
@MikielAgutu 

> So to confirm, in Flyway 6.1.2 deleted repeatable migrations didn't cause validation errors for being missing - but in 7.7.0 they do?

Confirmed.

> Can you not amend your pipelines to always run repair before migrating in all your environments?

We certainly _can_ do that, but it would essentially render all the protections provided by the checksums and the stateful schema history table worthless.

@madninjaskillz 

Can you provide a link to the code change and/or documentation indicating this change was made?  I'm unable to find one.  Additionally, our configuration files from 6.1.2 indicate that it was defaulted to `false` at that time.

**Comment by esauser** [comment]
@MikielAgutu @madninjaskillz 

We have confirmed that in `6.1.2` if a repeatable migration is applied and then removed, validate does not fail.  It does not matter if `ignoreMissingMigrations` is set to true of false.  The same, however, is not true for a versioned migration.

We have relied on this behavior (potentially taking advantage of a bug) for over 3 years now and have many pipelines that rely upon it.  How can we make it so that we can upgrade?

If you're set on it being a bug that has since been resolved, are you open to adding a new configuration that would allow it to ignore just repeatables, bringing back the behavior from before?  As-is, we are not able to upgrade.

**Comment by DoodleBobBuffPants** [comment]
Setting `ignoreMissingMigrations` to true should achieve the same effect in V7. Validate will then continue to succeed for missing migrations

**Comment by esauser** [comment]
That will allow both `versioned` and `repeatable` to be removed.  The behavior prior to V7 was just `repeatable` and that's what we'd like back if we can.  We don't want to allow `versioned` to be removed.

**Comment by DoodleBobBuffPants** [comment]
In this case we'd recommend running `validate` separately from `migrate` and validating `versioned` and `repeatable` migrations separately. You can store `versioned` and `repeatable` migrations in separate directories and change `locations` to validate them, and utilize `ignoreMissingMigrations` to achieve your desired behavior. You could also achieve this with `cherryPick` as `validate` respects what you specify to `cherryPick`, but that process is more manual as it requires updating the contents of `cherryPick`

We can't commit to adding this specific behavior, but if it gets more interest we will revisit it

**Comment by esauser** [comment]
If we try to `validate` just the `repeatable` or just the `versioned` wouldn't it have the same problem since all of the other would be missing?  I don't have any problem running them separately if there is a way to do that.

**Comment by DoodleBobBuffPants** [comment]
If you use the `cherryPick` approach then you won't encounter this problem. Everything not being `cherryPick`-ed is marked as `ignored`, so together with `ignoreIgnoredMigrations` you will get the desired behavior

If you use the `locations` approach then you'd be able to `validate` the `repeatable` migrations as all `versioned` migrations will be marked as `future`, but when it comes to validating `versioned` migrations, they will still have this same problem. In this case, it seems something like `ignoreRepeatableMigrations` is required, as opposed to something too specific such as `ignoreMissingRepeatableMigrations`

I'll rename the issue to reflect the former of the above features and reopen while we investigate

**Comment by esauser** [comment]
@DoodleBobBuffPants just to confirm, whereas we currently only run `migrate`, with the proposed `ignoreRepeatableMigrations` we'd:
1. `validate` with `locations` for only the `versioned` migrations with `ignoreRepeatableMigrations` set to `true`
2. `validate` with `locations` for only the `repeatable` migrations with `ignoreMissingMigrations` set to `true`
3. `migrate` with `validateOnMigrate` set to `false`

**Comment by esauser** [comment]
@DoodleBobBuffPants please explain why deleting migrations is discouraged, particularly `repeatable` migrations.  This is a very common and expected use case for us, so I'm wondering if we're fundamentally doing something wrong.

We utilize repeatable migrations for things like stored procedures, views, functions, and triggers.  Any time one of the objects is dropped, we delete the corresponding repeatable migration.

**Comment by DoodleBobBuffPants** [comment]
I should have said that deleting migrations and not running `repair` to mark them as `DELETED` is discouraged

In the workflow you have described, you end up in a state where the object is no longer in the database but Flyway's schema history table would suggest that it is as the corresponding `repeatable` migration is still considered to have been successfully applied, but it is just `missing`. This state is all that was possible before V7 but it is an incorrect state to be in

Running `repair` to mark the migration as `DELETED` might be what you need in this workflow instead

I understand you don't want to always run `repair` as it could cover up changes to checksums, so perhaps you could utilize the JSON output of `validate` to determine the kinds of validation failures that occurred?

**Comment by jangolano** [comment]
@DoodleBobBuffPants 
Having the ability to delete a repeatable is a big help.  We unfortunately have a lot of stored procedures we are trying to replace with application code.  

Is there some way to adjust the history when this occurs to have the best of both worlds?

**Comment by DoodleBobBuffPants** [comment]
@jangolano 

With Flyway we recommend making all database changes with a migration. If your aim is to make changes to the database in the application instead of with migrations, then you could use dummy (blank) migrations to track the history, but note that your migrations themselves lose reproducibility 

If your application won't be making changes to the database and you will be deleting those stored procedures, then deleting those migrations on disk and running `repair` to mark them as `DELETED` is the way forward
