### ISSUE TITLE
Lock row never removed causing failures

### ISSUE THREAD

**Issue by senthil-yolabs** [flyway/flyway#3124]
###### Which version and edition of Flyway are you using?
7.4.0 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Haven't tried

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
CockroachDB 20.2.6

###### Which operating system are you using?
Amazon Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I have situation that is similar to #2932. 
I see logs that say:
`Waiting for lock on Flyway schema history table. Application may be deadlocked. Lock row may require manual removal from the schema history table.`

In my schema table it looks like:
```
select * from flyway_schema_history;
  installed_rank |             version              | description  | type |         script         | checksum  |   installed_by    |           installed_on           | execution_time | success
-----------------+----------------------------------+--------------+------+------------------------+-----------+-------------------+----------------------------------+----------------+----------
            -100 | 5f995812f7cf53c59ba74f742898730a | flyway-lock  |      |                        |         0 |                   | 2021-03-25 21:07:22.840323+00:00 |              0 |  true
               1 | 1.0                              | create-table | SQL  | V1.0__create-table.sql | 588152650 | serv_int_svc_user | 2021-03-25 00:01:25.349565+00:00 |           7154 |  true
(2 rows)
```

I had to manually delete the `flyway-lock` row to make that error go away. Based on reading the referenced issue, it seems that the process that sets up the lock will delete it after the 10 minute timeout for Cockroachdb. However, if that process got killed, wouldn't that leave that row around causing this issue to happen at any time?

###### What did you expect to see?
Maybe at startup if the time is longer than the timeout, it should delete the row lock and proceed with migration?

###### What did you see instead?
Stuck indefinitely.

**Comment by DoodleBobBuffPants** [comment]
Flyway already deletes locks older than the timeout

If you run Flyway with debug level logging, you should see messages from a task running every 5 minutes indicating that the lock's timer is being updated. In this case it means your application hasn't fully shut down

If not, then you probably have entered a deadlock state and deleting the lock manually as per the message is the correct way to go as Flyway can't reasonably detect every user's case, unless you are able to provide a reproduction for this?

That being said, we will consider switching from Timer to Executor as it is generally considered better
