### ISSUE TITLE
clean fails for H2 databases with domains used in a non-default schema

### ISSUE THREAD

**Issue by muued** [flyway/flyway#3128]
###### Which version and edition of Flyway are you using?
7.7.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
It is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven and Gradle plugin, Java API

###### Which database are you using? (Type & version)
H2 1.4.200

###### Which operating system are you using?
macOS 10.15.7

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
minimal SQL statements
```
DROP SCHEMA IF EXISTS mcve CASCADE;
CREATE DOMAIN enumdomain AS ENUM ('x', 'y');
CREATE SCHEMA mcve;
CREATE TABLE mcve.test (
  problemcolumn enumdomain
);
```
call `flyway:migrate`
call `flyway:clean`

can also be seen here (was discovered while tracking down an issue in jooq)
https://github.com/muued/jOOQ-mcve/tree/issue11722

###### What did you expect to see?
no problems, expected to end up with a clean database

###### What did you see instead?
migrate works, clean fails

[ERROR] Unable to clean schema "PUBLIC"
[ERROR] -------------------------------
[ERROR] SQL State  : 90107
[ERROR] Error Code : 90107
[ERROR] Message    : Cannot drop "ENUMDOMAIN" because "CREATE CACHED TABLE ""MCVE"".""TEST""(
[ERROR]     ""PROBLEMCOLUMN"" ""ENUMDOMAIN""
[ERROR] )" depends on it; SQL statement:
[ERROR] DROP DOMAIN"ENUMDOMAIN" [90107-200]

**Comment by madninjaskillz** [comment]
The foreign schema needs to be configured in flyway for clean to be able to process it. Details on configuring that can be found [here](https://flywaydb.org/documentation/configuration/parameters/schemas), but with the minimal SQL, 
```-schemas="main,mcve"``` resolved the issue.
