### ISSUE TITLE
Parse error with `BEGIN DISTRIBUTED TRANSACTION`

### ISSUE THREAD

**Issue by rchurchley** [flyway/flyway#3130]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 7.7.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command line

###### Which database are you using? (Type & version)

Microsoft SQL Server 15.0 (2019) on Docker

###### Which operating system are you using?

Docker container based on RHEL.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Run the following script through flyway

```sql
CREATE OR ALTER PROCEDURE [dbo].[Foo] AS BEGIN

  BEGIN DISTRIBUTED TRANSACTION  
    SELECT 1
  COMMIT TRANSACTION

END
```

###### What did you expect to see?

The script should successfully be run, with the procedure generated

###### What did you see instead?

```
ERROR: Unable to parse statement in ./Stored Procedures/R__A_TEST.sql at line 1 col 1. See https://flywaydb.org/documentation/knownparserlimitations for more information: null
Caused by: java.lang.NullPointerException
```

The [parser](https://github.com/flyway/flyway/blob/e39053d2e52294945d2a313d05e656b099e5ee70/flyway-core/src/main/java/org/flywaydb/core/internal/database/sqlserver/SQLServerParser.java#L111) covers `BEGIN TRAN(SACTION)?` as a special case but not [`BEGIN DISTRIBUTED TRANSACTION`](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/begin-distributed-transaction-transact-sql?view=sql-server-ver15), so it sees an imbalance of `BEGIN ` and `END`s in the migration.

**Comment by Rixium** [comment]
Hey @rchurchley ,

Thanks for the bug report.
I can confirm we've managed to reproduce the issue, and will be working on it,

Thanks!
