### ISSUE TITLE
MariaDB 10.5 support

### ISSUE THREAD

**Issue by nicregez** [flyway/flyway#3131]
###### Which version and edition of Flyway are you using?
7.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle and SpringBoot 2.4.4

###### Which database are you using? (Type & version)
MariaDB 10.5

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I start my SpringBoot application which validates and applies Flyway migrations.
Furthermore, I check the output of WARN/ERROR logs.

###### What did you expect to see?
No WARN message from Flyway in my logs saying I need to upgrade Flyway. Because I cannot upgrade as I am using the newest version of Flyway.

###### What did you see instead?
A WARN message saying "Flyway upgrade recommended: org.flywaydb.core.internal.database.mysql.mariadb.MariaDBDatabaseType@2afdf6b7 10.5 is newer than this version of Flyway and support has not been tested. The latest supported version of org.flywaydb.core.internal.database.mysql.mariadb.MariaDBDatabaseType@2afdf6b7 is 10.4."

**Comment by nicregez** [comment]
Is there a way I can contribute to the resolution of this issue?

**Comment by DoodleBobBuffPants** [comment]
The warning shouldn't block you unless MariaDB 10.5 includes breaking changes to 10.4

There is no way to contribute unfortunately, we will have to test our support against 10.5 before we can update our support

**Comment by guidomedina** [comment]
Not sure if I should comment on this issue but Flyway 8.1.0 is the latest that is support MariaDB, starting with version 8.2.0 I get this error:
```
nested exception is org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 10.5
```
With both MariaDB JDBC driver 2.7.5 and 3.0.3, I'm running my application on Debian 11 (Bullseye)
