### ISSUE TITLE
Flyway ignoreIgnoredMigrations not working

### ISSUE THREAD

**Issue by laxman1411** [flyway/flyway#3138]
###### Which version and edition of Flyway are you using?
Flyway 5.1.4 community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I have not tried that

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
SQL SERVER 2017

###### Which operating system are you using?

WINDOWS 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I have already migrated a versioned migration say V114 and when I am trying to migrate V114.1 to the same database, the flyway command-line tool is ignoring it. I have tried using ignoreIgnoredMigration but it is not working.

**Comment by DoodleBobBuffPants** [comment]
Could you provide reproduction steps and try on the latest version? Also could you include debug output (run flyway with `-X`)

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
