### ISSUE TITLE
Support `--help` as a command-line alias to show the help text

### ISSUE THREAD

**Issue by angusholder** [flyway/flyway#3139]
###### Which version and edition of Flyway are you using?
7.7.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Ran `flyway --help`

###### What did you expect to see?
Display the standard usage message you get when invoking Flyway with `-?` or no arguments.

I understand that Flyway doesn't follow the GNU command-line arg convention, but it would be nice if it at least accepted `--help` - it's nice to be able to reflexively type `--help` without having to think about which program you're using, since the majority of programs support it.

###### What did you see instead?
`ERROR: Invalid argument: --help`

**Comment by juliahayward** [comment]
We will add GNU-standard `--version`, `--help`, `-h` in the next version. We won't remove anything without announcing its deprecation well in advance, but becoming more compliant with standards is on our radar.
