### ISSUE TITLE
Problem while inserting placeholder as a string in db.

### ISSUE THREAD

**Issue by harsh0581** [flyway/flyway#3140]
###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

SET DEFINE OFF UPDATE ALERTS_EVENTS SET ALERT_EMAIL_ = 'Dear Customer,  ${INVOICE_REF_NO}, Invoice Amount ${CURRENCY} ${AMOUNT} is raised on ${INVOICE_DATE} ' where EVENT='ABC'

###### What did you expect to see?

I want to enter a message in one column as Dear Customer,  ${INVOICE_REF_NO}, Invoice Amount ${CURRENCY} ${AMOUNT} is raised on ${INVOICE_DATE}.

###### What did you see instead?
error

**Comment by DoodleBobBuffPants** [comment]
Documentation for placeholders is [here](https://flywaydb.org/documentation/configuration/placeholder)

If you are encountering a specific error, please share the full output and steps to reproduce
