### ISSUE TITLE
application jre

### ISSUE THREAD

**Issue by crizzs** [flyway/flyway#3141]
###### Which version and edition of Flyway are you using?

7.7.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

MSSQL

###### Which operating system are you using?

Redhat

###### What did you expect to see?
There is security risk for the current version of JAVA_VERSION="11.0.2". Are there plan to upgrade the jre version??

**Comment by DoodleBobBuffPants** [comment]
We have our own mechanism for detecting and upgrading vulnerabilities and will do so when we are able to test the upgrade
