### ISSUE TITLE
Fix #3105 Is Not a good idea: It prints too many logs while I have many insert-scripts

### ISSUE THREAD

**Issue by yaumi123** [flyway/flyway#3142]
###### Which version and edition of Flyway are you using?
7.7.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
not fix or change in 7.7.3 (newest as for now)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
maven plugin

###### Which database are you using? (Type & version)
postgresql V13 (v11 in another workspace)

###### Which operating system are you using?
mac and ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I have many Insert-sql-scripts (since I use flyway5). And in this new version, the log code in SqlExecutor changed. It prints all the affect row count msg (it's debug level before and info now) like `X rows affected`. 
When I start a new database and do the migrate (it's quite often when I do local dev),  there are tons of `affected` msg on my log screen.

###### What did you expect to see?
I expected that I can configure when I want to see these msg. I tried Override `createSqlScriptExecutor` method but have no idea how to inject the class I create.

###### What did you see instead?
tons of `x rows affected` msg

**Comment by yaumi123** [comment]
[Fix #3105 ](https://github.com/flyway/flyway/commit/c3776f47cf95b8feb27921ea750048ba24236c2d) this is the pull request I'm talking while the issue it fixed is [#3105 ](https://github.com/flyway/flyway/issues/3105)

**Comment by tristanwqy** [comment]
+1 really annoying

**Comment by DoodleBobBuffPants** [comment]
See https://github.com/flyway/flyway/issues/3132 for a proposed solution we will try, as we need to balance not hiding information people find useful vs spam

**Comment by esauser** [comment]
@DoodleBobBuffPants what is the proposed solution?  I'm not seeing it on #3132 .

**Comment by Lucas3oo** [comment]
+1 really annoying

**Comment by esauser** [comment]
FWIW a poor workaround I found is to add a `beforeMigration` script that to `SET NOCOUNT ON`.
