### ISSUE TITLE
Flyway fails to migration migration containing loopback linked server

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3156]
###### Which version and edition of Flyway are you using?
6.1.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
We are not able to upgrade to the latest version due to another issue that is actively being worked on by the flyway team.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
In an environment where linked servers are setup to the same server (loopback, meaning there are multiple databases on a single instance with linked servers to eachother on the same instance) we executed `flyway migrate` with a repeatable migration containing a stored procedure that interacted with the the linked server.

###### What did you expect to see?
The migration to successfully apply

###### What did you see instead?
![image](https://user-images.githubusercontent.com/24945592/115787496-e56d7380-a387-11eb-89fe-2764271a7a2c.png)

Note that logged-in as any user with permission to alter the stored procedure, including the user flyway executes as, we were able to alter the stored procedure without issue.  It is only when flyway does it that the issue manifests.

We dug deeper and found the following error in SQL Profiler
```
Cannot obtain the schema rowset “DBSCHEMA_TABLES_INFO” for OLE DB provider “SQLNCLI11" for linked server “[REDACTED]”. 
The provider supports the interface, but returns a failure code when it is used.
```

**Comment by DoodleBobBuffPants** [comment]
- Does this only occur for the repeatable migration in question?
- Do the contents of this repeatable migration execute successfully through SSMS?
- Do the contents of this repeatable migration execute successfully through JDBC outside of Flyway? (This will help identify if the issue is JDBC or Flyway related)

Could you try the first solution in [this post](https://stackoverflow.com/questions/32974092/transaction-with-loopback-linked-server-locking-issues) which suggests copying the contents of the stored procedure into the end of the script

See also [this post](https://dba.stackexchange.com/questions/62580/loopback-linked-server) which mentions that distributed transactions don't work with loopback linked servers, so if your scripts contain these then that might be the cause

Could you also provide a script that reproduces this, along with the exact setup of your linked server?

**Comment by esauser** [comment]
> Does this only occur for the repeatable migration in question?

No.  It occurred with every migration interacting with the linked servers.

> Do the contents of this repeatable migration execute successfully through SSMS?

Yes

> Do the contents of this repeatable migration execute successfully through JDBC outside of Flyway? (This will help identify if the issue is JDBC or Flyway related)

How does one go about testing this?

**Comment by DoodleBobBuffPants** [comment]
> How does one go about testing this?

If you've used Java migrations, then that might be the quickest way. Java migrations give you access to the underlying JDBC connection, meaning you can execute statements directly over that connection. There is a sample Java migration in our documentation [here](https://flywaydb.org/documentation/concepts/migrations#sample-class). This will let you see which statements execute successfully and their exceptions when they fail

If you don't want to use a Java migration then you'll need a Java project that will achieve the same result as the Java migration. [Here's](https://www.codejava.net/java-se/jdbc/connect-to-microsoft-sql-server-via-jdbc) a quick tutorial on setting one up. It will give you access to a `Connection` object, and then you can proceed as described in the Java migration case

**Comment by esauser** [comment]
> See also this post which mentions that distributed transactions don't work with loopback linked servers, so if your scripts contain these then that might be the cause
Wrapping in a transaction appears to be the issue.  If we wrap it in a transaction through SSMS we get
```
Msg 3910, Level 16, State 2, Line 3
Transaction context in use by another session.
```
which highlights another flavor of flyway not really showing the _actual_ error as mentioned in #3157.

Adding a script configuration file to run this outside of a transaction allows it to succeed.  So that aspect appears to be a SQL limitation and not flyway.
