### ISSUE TITLE
Flyway hides error information

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3157]
###### Which version and edition of Flyway are you using?
7.6.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
We are not able to upgrade to the latest version due to another issue that is actively being worked on by the flyway team.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Executed `flyway migrate` with a migration that resulted in a trigger firing and returning an exception.

###### What did you expect to see?
Full exception details

###### What did you see instead?
Only the message.

We didn't know the exception was coming from a trigger because flyway only showed the message `String or binary data would be truncated`.  When we ran the migration through SSMS it was very clear that there was a trigger involved because the error included the relevant object name.  Could we get that included in the error output?

Separater, but related we've also seen many times where the actual error, or part of the error information, is missing from the flyway output.  #3156 is an example.

**Comment by DoodleBobBuffPants** [comment]
Could you provide a script that reproduces this behavior?

**Comment by esauser** [comment]
Setup with the following:
```
CREATE TABLE testA (number INT)

CREATE TABLE testB (string VARCHAR(10)

CREATE TRIGGER testC ON testA
AFTER INSERT
AS
     INSERT INTO testB (string) VALUES ('12345678901234567890')
```

Create a migration:
```
INSERT INTO testA (number) VALUES (1)
```

Execute `flyway migrate` and observe only `String or binary data would be truncated` returned, which is a bit confusing since our migration had nothing to do with strings.  Run the same in SSMS and you will see the relavant object (`testC`) returned.

**Comment by DoodleBobBuffPants** [comment]
We appreciate that SSMS gives a different and more helpful error message. However, I have confirmed that we are displaying everything returned by the JDBC driver - there isn't any more information for us to display
