### ISSUE TITLE
Support for aurora postgres 12.4

### ISSUE THREAD

**Issue by karunagoyal** [flyway/flyway#3159]
###### Which version and edition of Flyway are you using?
11.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

NA

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
postgres 12.4

###### Which operating system are you using?
Mac

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Currently flyway support aurora postgres version 11.4 . However because of my project needs , I have to use 12.4 aurora postgres. When are you planning to support this version of postgres?

###### What did you expect to see?

NA

###### What did you see instead?
NA

**Comment by juliahayward** [comment]
Flyway should work fine, other than the warnings, although we haven't formally verified it yet. We'll run through the tests on Aurora and update the warning trigger in the next version.

**Comment by karunagoyal** [comment]
Thanks @juliahayward

**Comment by juliahayward** [comment]
Hi - I can confirm Flyway should be fine with Aurora Postgres up to and including 13.2, and I'll update the documentation to reflect that.

**Comment by karunagoyal** [comment]
Thanks again @juliahayward !!
