### ISSUE TITLE
MySQL 8.0 WARNING UTF8MB3

### ISSUE THREAD

**Issue by xiagw** [flyway/flyway#3162]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.8.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
use flyway docker 

###### Which database are you using? (Type & version)
MySQL 8.0

###### Which operating system are you using?
Ubuntu 20.04

###### What did you see instead?

Flyway Community Edition 7.8.1 by Redgate
Database: jdbc:mysql://192.168.20.153:3306/dev_api (MySQL 8.0)
Successfully validated 6 migrations (execution time 00:00.037s)
Current version of schema `dev_api`: 0.0.4
Migrating schema `dev_api` to version "0.0.5 - web open client"
WARNING: DB: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous. (SQL State: HY000 - Error Code: 3719)
WARNING: DB: Integer display width is deprecated and will be removed in a future release. (SQL State: HY000 - Error Code: 1681)
WARNING: DB: Integer display width is deprecated and will be removed in a future release. (SQL State: HY000 - Error Code: 1681)
WARNING: DB: Integer display width is deprecated and will be removed in a future release. (SQL State: HY000 - Error Code: 1681)
WARNING: DB: Integer display width is deprecated and will be removed in a future release. (SQL State: HY000 - Error Code: 1681)
WARNING: DB: Integer display width is deprecated and will be removed in a future release. (SQL State: HY000 - Error Code: 1681)
2 rows affected
WARNING: DB: 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release. (SQL State: HY000 - Error Code: 3135)

**Comment by xiagw** [comment]
可否升级一下 jdbc 链接库的版本？

**Comment by juliahayward** [comment]
Yes, you can update the JDBC driver library - Flyway currently ships with 8.0.23, and we'll bump this to 8.0.24 in the next Flyway release. Do you get these warnings with specific scripts or on every migration? Does the migration complete successully despite the warnings?

**Comment by xiagw** [comment]
yes, on every migration,
migration is ok,
