### ISSUE TITLE
failOnMissingTarget is not exposed via FluentConfiguration

### ISSUE THREAD

**Issue by kedar-joshi** [flyway/flyway#3171]
Commit e7416a99 added support for property `failOnMissingTarget` in v7.9.0 but this configuration is not currently exposed via `FluentConfiguration`.

I am trying to add support for Flyway v7.9.0 to Spring Boot (https://github.com/spring-projects/spring-boot/pull/26456) and it will be helpful to know if this is an intended behavior.

**Comment by DoodleBobBuffPants** [comment]
This is indeed intended

This property should be set by appending a `?` to the version specified to `target` instead
