### ISSUE TITLE
Flyway unable to drop schema during cleanup when a user defined type is used

### ISSUE THREAD

**Issue by AigleeK** [flyway/flyway#3174]
###### Which version and edition of Flyway are you using?

Flyway 7.9.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-Line

###### Which database are you using? (Type & version)

SQL Server 2017

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Execute migrate
It works successfully
Execute clean
It fails to drop Utility schema

Use the following configuration file:
flyway.url=jdbc:sqlserver://localhost;database=Test;integratedSecurity=true
flyway.locations=filesystem:Test
flyway.table=VER_FLYWAY_MIGRATION_HISTORY
flyway.defaultSchema=dbo
flyway.schemas=dbo,Framework,Utility

Test folder is below:
[Test.zip](https://github.com/flyway/flyway/files/6493850/Test.zip)

###### What did you expect to see?

It should drop the schemas but it fails to clean types

###### What did you see instead?

![image](https://user-images.githubusercontent.com/45078281/118488509-cdb8af00-b6e9-11eb-8b99-30951902534b.png)

**Comment by DoodleBobBuffPants** [comment]
This is expected behavior - the schema cannot be dropped due to the type, so we clean the schema instead. We will consider attempting to drop the schema again after this clean, as the type shouldn't be a problem at this point

**Comment by AigleeK** [comment]
It makes no sense that's expected behavior because if you do that, run the clean, it doesn't drop the schema, it cleans it, and then you run a migrate, it FAILS. It tells you the schema already exists because is trying to create it. So either the clean needs to drop it or the migrate needs to not fail if it already exists.
