### ISSUE TITLE
Consider i18n migrate  support?

### ISSUE THREAD

**Issue by wangyongxu** [flyway/flyway#3176]
Consider sql script i18n support?
I found no issues with i18n, how to migrate sql for i18n project?
Such as `first_migrate_en.sql` for english

**Comment by DoodleBobBuffPants** [comment]
Could you explain more about what it is you're trying to do, and what behavior you're seeing at the moment, and what changes you'd like to see?

**Comment by wangyongxu** [comment]
In i18n projects, when init or upgrading sql scripts, the content depends on the language
for example table `alarm` column `desc`, 
 init  content  `CPU {0} Bus Error` for `en`, 
but `处理器 {0}总线错误` for `zh_CN`,

hence, when upgrade,  sql scripts depends on locality or environment language:

`V10_alarm_en.sql` for english environment :
`insert into 'alarm' ('desc') values ('CPU {0} Bus Error for 'en')`
`V10_alarm_zh_CN.sql` for chinese environment:
`insert into 'alarm' ('desc') values ('处理器 {0}总线错误' for 'zh_CN')`

for not i18n sql scripts, keep it as it was.

**Comment by wangyongxu** [comment]
Now, i implement the function by`I18nSqlMigrationResolver` impl `MigrationResolver`
Others have this need?

**Comment by DoodleBobBuffPants** [comment]
If my understanding is correct, you want to choose which migration to execute depending on the locality of the environment?

You can achieve this now using [script configuration files](https://flywaydb.org/documentation/configuration/scriptconfigfiles) that use `shouldExecute`. You would then have to populate a placeholder which you can use to determine which environment you are in, and this will let you enable/disable migrations. You could also do this with `locations`, storing migrations per environment in a different location, and changing the locations based on the environment

Closing unless this gets more traction

**Comment by wangyongxu** [comment]
I mean, similar to spring's i18n, define a default message file for the English language called **messages.properties**:
```
greeting=Hello! Welcome to our website!
lang.change=Change the language
lang.eng=English
lang.fr=French
```
and  create **messages_fr.properties** for the French language with the same keys:
```
greeting=Bonjour! Bienvenue sur notre site!
lang.change=Changez la langue
lang.eng=Anglais
lang.fr=Francais
```
create **messages_XX.properties** for the XX language with the same keys.

`shouldExecute` and `locations`should not meet this i18n scene.
