### ISSUE TITLE
OSGi ServiceLoader still not working

### ISSUE THREAD

**Issue by alexgast** [flyway/flyway#3177]
### Problem

When using "Flyway" (7.9.1) in some (OSGi-) Bundle X, the classloader of Bundle X is responsible for loading classes of the Bundle `org.flywaydb.core`, incl. the static parts of `org.flywaydb.core.internal.database.DatabaseTypeRegister`, i.e.

```java
public static ClassLoader classLoader = DatabaseTypeRegister.class.getClassLoader()
```

equals the classloader of Bundle X. 

But in OSGi Classloader X has no access to any resource of bundle `org.flywaydb.core`, i.e. the ServiceLoader folder is not
visible for this classloader and we end up with: https://github.com/flyway/flyway/issues/3173.

### Solution

We need a classloader explicitly tied to bundle `org.flywaydb.core`, for instance `<...>.getClass().getClassloader` of a some internal instanciated class of `org.flywaydb.core`:

```java
ServiceLoader<DatabaseType> loader = ServiceLoader.load(DatabaseType.class, new DatabaseTypeRegister().getClass().getClassLoader());

```

or equivalently

```java
public class Clazz {

    public static final ClassLoader LOADER = new Clazz().getClass().getClassLoader();

}

```

and then 

```java
ServiceLoader<DatabaseType> loader = ServiceLoader.load(DatabaseType.class, Clazz.LOADER);
```

**Comment by jamiecounsell** [comment]
@alexgast this is still not working for me as of 7.11.13. Are you able to explain anything you did besides wrap the JAR in an OSGI Plugin to get this working?

**Comment by alexgast** [comment]
OSGi a has strict concept of classloader visibility/isolation. In general a classloader of some OSGi Bundle A (for instance a client bundle containg migration files: *.sql etc.) has no access to resources of a different Bundle B (for instance the flyway core bundle 'org.flywaydb.core'). As a consequence the last two lines of the `Flyway` constructor are not correct

 ```java
    public Flyway(Configuration configuration) {
        this.configuration = new ClassicConfiguration(configuration);

        // Load callbacks from default package
        this.configuration.loadCallbackLocation("db/callback", false);

        // Set ClassLoader for ServiceLoader
        DatabaseTypeRegister.classLoader = configuration.getClassLoader();
        VersionPrinter.classLoader = configuration.getClassLoader();
    }
 ```

because "configuration.getClassLoader()" holds a classloader of Bundle A by `Flyway.configure(getClass().getClassLoader()) ...`, but this classloader only has access to Bundle A (which is good to load migration files from Bundle A, but not sufficient to load Servicloader resources from Bundle B).

Solution/Workaround:

remove the followng lines from `Flyway` constructor

```java
        // Set ClassLoader for ServiceLoader
        DatabaseTypeRegister.classLoader = configuration.getClassLoader();
        VersionPrinter.classLoader = configuration.getClassLoader();
```

and optionally make `ClassLoader classLoader` private to prevent overriding, i.e.:

for class `org.flywaydb.core.internal.database.DatabaseTypeRegister`

```java
private static ClassLoader classLoader = new DatabaseTypeRegister().getClass().getClassLoader();
```

and for `org.flywaydb.core.internal.license.VersionPrinter`:

```java
private static ClassLoader classLoader = new VersionPrinter().getClass().getClassLoader();

```

A deeper discussion of Serviceloader and OSGi issues (maybe needed to get flyway extensions working) you can find here: https://aries.apache.org/documentation/modules/spi-fly.html.

**Comment by jamiecounsell** [comment]
Thanks @alexgast! For my fellow OSGI devs that end up here, 7.11.4 fixed the issue Alex is describing. However, I was still having an issue causing Flyway to not recognize my migrations. This is because the `bundle://` protocol is only supported when the system detects an OSGI environment. It does this by attempting to load the class `org.osgi.framework.Bundle`.

```
ClassUtils.isPresent("org.osgi.framework.Bundle", classLoader);
```

However, of course when Flyway does this with its own classLoader, this isn't available. The solution is to ensure there is an Import-Package line in your Flyway bundle's MANIFEST.MF for the OSGI Framework.

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Flyway
Bundle-SymbolicName: org.flywaydb.flyway-core
Bundle-Version: 7.11.4
Automatic-Module-Name: org.flywaydb.flyway-core
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Import-Package: javax.sql, org.osgi.framework
```

With 7.11.4 and this Import-Package line, it works!
