### ISSUE TITLE
Flyway:Repair Deletes History of Java Migrations

### ISSUE THREAD

**Issue by ClancyDamon** [flyway/flyway#3180]
###### Which version and edition of Flyway are you using?
7.9.1 Community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven Plugin

###### Which database are you using? (Type & version)
Oracle 19c and Postgresql 12

Happens for both databases.

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

During recent development, we've upgraded Flyway from 6 to 7. As part of some recent updates, changes were made to existing SQL migration files. Normally, this isn't a problem, as we just run Flyway:Repair through the Maven plugin. What I've noticed is that in Flyway 7, all of my Java Based Migrations are being deleted from the schema history table. I see the following output in my console:

Flyway Community Edition 7.9.1 by Redgate
Database: jdbc:oracle:thin:@localhost:1521/ORCLPDB1 (Oracle 19.0)
Repair of failed migration in Schema History table "MY_SCHEMA"."MY_SCHEMA_VERSION" not necessary. No failed migration detected.
Repairing Schema History table for version "8.6.1" (Marking as DELETED)  ...
Repairing Schema History table for version "8.7.0.1" (Marking as DELETED)  ...
Successfully repaired schema history table "MY_SCHEMA"."MY_SCHEMA_VERSION" (execution time 00:00.473s).
Please ensure the previous contents of the deleted migrations are removed from the database, or moved into an existing migration.

###### What did you expect to see?

No instance of 'Repairing Schema History table for version "x.x.x" (Marking as DELETED) '. I have made no changes to my Java Migrations. They are part of the locationsAsStrings property for my org.flywaydb.core.api.configuration.ClassicConfiguration bean, so they shouldn't be considered missing. These migrations are found and they run successfully if I just do Flyway:Migrate.

###### What did you see instead?

The records for my java based migrations are deleted in my schema history table. This means that future deployments of the application will attempt to re-apply these migrations, and everything will fail. Fortunately, this is being done by apparently creating a duplicate record with the same version, description, script, etc, but with the type column listing "DELETE". At the moment, my only solution is to immediately execute the following statement after running repair - DELETE FROM MY_SCHEMA_VERSION WHERE "type" = 'DELETE';

I'm assuming there is some property introduced in Flyway 7 that I need to use. I have confirmed that if I run repair with Flyway 6, there are no problems, and repair doesn't affect my Java Migrations at all, in terms of history. I'm reading through the documentation, but I'm not seeing anything that would appear to be related to this.

I have attempted to add an implementation of getChecksum in my migration classes, but the results are still the same.

**Comment by juliahayward** [comment]
Is it possible for you to get the output from `flyway:info` when in a situation just before some migrations would be deleted incorrectly?

A `repair` should remove migrations in four states from the history table; MISSING_SUCCESS / MISSING_FAILED, where Flyway cannot find the source for the migration any more, and FUTURE_SUCCESS / FUTURE_FAILED, where Flyway cannot find the source and in addition it's a higher migration version than all those whose source is available. This should not include Java migrations that have been successfully applied, unless they are no longer on the classpath at the time `repair` is run?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity

**Comment by ClancyDamon** [comment]
I apologize for the delay, it's been extremely busy.

I ran Flyway:Info and this is my output:

```
+-----------+--------------+-------------------------------+------+---------------------+---------+
| Category  | Version      | Description                   | Type | Installed On        | State   |
+-----------+--------------+-------------------------------+------+---------------------+---------+
| Versioned | 9.5.1.11     | Init Db DDL                   | SQL  | 2021-05-20 10:16:21 | Success |
| Versioned | 9.5.1.12     | LocalizationTextTablePopulate | JDBC | 2021-05-20 10:17:42 | Missing |
| Versioned | 9.5.3.6      | ComplianceReviewEnableDisable | SQL  | 2021-05-26 09:49:18 | Success |
| Versioned | 9.3.14.24.26 | SmtpSettingsConversion        | JDBC | 2021-06-11 14:29:56 | Missing |
| Versioned | 9.5.5.2      | CustomFieldCrosstabFix        | SQL  | 2021-06-11 15:05:19 | Success |
| Versioned | 9.5.5.12     | CustomFieldCrosstabFix2       | SQL  | 2021-06-15 17:47:13 | Future  |
| Versioned | 9.5.5.13     | IntegerBooleanCastCorrection  | SQL  | 2021-06-15 18:00:17 | Future  |
+-----------+--------------+-------------------------------+------+---------------------+---------+
```

Both of my java migrations (JDBC) are listed as Missing. What's extremely odd is that sql based migrations are found and accurately listed as either success or future. I have three directories for my classpath that are being set to the "locationsAsStrings" parameter of my flyway bean. Our application is using XML based Spring configuration. Here's the bean:

```
<bean id="flywayConfig" class="org.flywaydb.core.api.configuration.ClassicConfiguration" depends-on="SpringUtility">
    	<property name="dataSource" ref="dataSource"/>
    	<property name="table" value="MY_SCHEMA_VERSION" />
    	<property name="baselineVersionAsString" value="9.5.1.11" />
    	<property name="baselineOnMigrate" value="true" />
    	<property name="baselineDescription" value="The baseline of the database." />
    	<property name="locationsAsStrings" value="classpath:db/migration/postgresql,classpath:com/mycompany/webapp/util/migration/javafiles/postgresql,classpath:com/mycompany/webapp/util/migration/javafiles/common" />
    	<property name="placeholderReplacement" value="false" />
    	<property name="outOfOrder" value="false" />
    	<property name="callbacksAsClassNames" value="com.mycompany.webapp.util.migration.FlywayCallbackHandler" />
    </bean>
    <bean id="flyway" class="org.flywaydb.core.Flyway" init-method="migrate">
    	<constructor-arg ref="flywayConfig"/>
    </bean>
```

**Comment by ClancyDamon** [comment]
Nevermind. Very stupid mistake on my part. Migrations are done as part of application deployment, so migrations utilize the bean I showed previously. However, when running repair or info, these are invoked directly with the Maven Flyway plugin, and are utilizing solely the Pom.xml. <flyway.locations></flyway.locations> was misconfigured and did not include the java migration directories seen in the bean. So my assumption is that in Flyway 6.x, if the migrations were not found they were just ignored. However, Flyway 7.x has stronger validation and marks things as deleted if the migrations are not found. It must be that because my Pom.xml has been incorrectly configured for quite some time, but only after the update did I notice any problem.

So, no issues with Flyway at all, actually. Just user error on my part. Thank you, and I apologize.

**Comment by juliahayward** [comment]
That's not a problem - many thanks for taking the time to let us know! If there are changes you think we can make so that it's easier to avoid such situations, do let us know.
