### ISSUE TITLE
Re-opened - Repeatable Migration not executed after changing Placeholder value

### ISSUE THREAD

**Issue by polaskj** [flyway/flyway#3181]
The expected behavior is to detect and apply differences to repeatable migrations when placeholder values change.

This issue was also described in https://github.com/flyway/flyway/issues/2177 and https://github.com/flyway/flyway/issues/2685 but does not seem to be working as described in the 6.3 release notes.

###### Which version and edition of Flyway are you using?

Tested with 6.3 as well as latest (at the time of submission) 7.9.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

MySQL 5.7

###### Which operating system are you using?

Flyway runtime: MacOs; Database: AWS Aurora

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

```
...
Map<String, String> flyWayPlaceholders = flyway.getConfiguration().getPlaceholders();
flyWayPlaceholders.put("mykey", "myupdatedvalue");
...
```

R_spTest.sql:
```
DROP PROCEDURE IF EXISTS `spTest`;
DELIMITER $$
CREATE PROCEDURE `spTest`
BEGIN
    SELECT '${mykey}';
END
$$
DELIMITER 
```

###### What did you expect to see?

The expected placeholder substitution of `mykey` in the body of the `spTest` procedure should be `myupdatedvalue`.

###### What did you see instead?

`myoldvalue` which is the old value evaluated at the time of creation.

There does seems to be a differences between 6.2.2 and 6.3.0 (and above) where files whose checksum does not match the flyway_schema checksum forces placeholder will be recomputed, but ideally the placeholder substitution alone should be enough to trigger a re-run of the repeatable migration. Eg:

```
echo "[INFO] Touching files with property substitutions"
for f in $(find . -name "R__*.sql" | xargs grep -l "\${"); do
  echo "/** touch **/" >> $f
done
# Run Flyway
...
# Reset touched files
...
```
The above is the current workaround, using 6.3.0+ applied before Flyway as part of our CI/CD pipeline.

**Comment by juliahayward** [comment]
I'm not able to reproduce this. Since 6.3 the checksum of a file has been calculated *after* placeholder value substitution, so the following code in our current version does what we expect:
```
// Run with first value of placeholder
Map<String, String> placeholders = flyway.getConfiguration().getPlaceholders();
placeholders.put("abc", "foo");
MigrateResult firstResult = flyway.migrate();
assertEquals(2, firstResult.migrationsExecuted); // V1 to create table, R to insert a row into it

// Change the placeholder - repeatable should rerun on second migration
placeholders.put("abc", "bar");
MigrateResult secondResult = flyway.migrate();
assertEquals(1, secondResult.migrationsExecuted); // R inserts a second row

// Don't change the placeholder's value - repeatable should not rerun
placeholders.put("abc", "bar");
MigrateResult thirdResult = flyway.migrate();
assertEquals(0, thirdResult.migrationsExecuted);
```

Are you able to share a larger sample of your code?

**Comment by polaskj** [comment]
@juliahayward thanks for taking a look. Upon further investigation it looks like I had a transitive dependency making the effective flyway-core dependency v6.2.2. Once I got that resolved, the same assertions in your test above & expected behavior are working properly for me. Thanks again.

**Comment by klint** [comment]
Hello
I don't want to reopen this ticket, but I just have a question.
For repeatable migrations, the checksum is computed AFTER replacing the placeholders.
But what about VERSIONED migrations? It seems to be the other way around (checksum being computed BEFORE replacing the placeholders). 
Can anyone confirm?
Thank you

**Comment by tjs145** [comment]
> Hello I don't want to reopen this ticket, but I just have a question. For repeatable migrations, the checksum is computed AFTER replacing the placeholders. But what about VERSIONED migrations? It seems to be the other way around (checksum being computed BEFORE replacing the placeholders). Can anyone confirm? Thank you

Correct, placeholders are replaced before calculating checksums for repeatable migrations, but not for versioned migrations. 

For example `${flyway:timestamp}` can be used to constantly change a repeatable checksum so that it's applied in every run, but it wont cause checksum mismatch problems if used in versioned migrations.
