### ISSUE TITLE
flyway:validate fails to detect duplicate files with identical names in different classpaths

### ISSUE THREAD

**Issue by magicwerk** [flyway/flyway#3182]
###### Which version and edition of Flyway are you using?

7.9.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

is newest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

No database (dummy jdbc:hsqldb:mem:myDB)

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

See attached test case
[ShowBugFlywayValidate.zip](https://github.com/flyway/flyway/files/6555035/ShowBugFlywayValidate.zip)

Run test with "gradle test"

There are 4 test cases with duplicate files.
testCp1: classpath:cp1/dir1/V1__file1.sql vs classpath:cp1/dir1/V1__file2.sql
testCp2: classpath:cp2/dir1/V1__file1.sql vs classpath:cp2/dir2/V1__file1.sql
testCp3: classpath:cp3a/dir1/V1__file1.sql vs classpath:cp3b/dir1/V1__file1.sql
testCp4: classpath:cp4a/dir1/V1__file1.sql vs classpath:cp4b/dir1/V1__file2.sql

###### What did you expect to see?

Flyway should detect duplicates in all 4 test cases and throw an exception.
As the test expect an error, all tests should pass

###### What did you see instead?

testCp3 fails, i.e. Flyway does not detect duplicate files with identical names in different classpaths.

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising this issue. While we work on a fix, you can work around this issue by ensuring that the paths to your migrations are unique under each location e.g. `CP3a/dir1/V1__file1.sql` and `CP3b/dir2/V1__file1.sql`

**Comment by magicwerk** [comment]
As you can imagine we're using validate exactly to detect situatios where something has gone wrong to guarantee stable and reproducible builds. Unfortunately with this bug, duplicate files have sneaked in. Regarding work arounds:
- when do you think this bug will be fixed so we could wait for this release?
- do you know when it has been introduced so we could downgrade to get back stability?

**Comment by DoodleBobBuffPants** [comment]
After investigating further, we've determined that this is expected and desired behavior (for now)

We determine if two migrations are the same based on their path _relative to the classpath location_, their version and description, and their checksum. We then use this to remove duplicates, so that specifying the same location twice or a parent/child location doesn't cause validation errors. We'll be happy to revisit this should it get more interest, but closing for now

**Comment by magicwerk** [comment]
So if you're saying that you verify the checksum, validate would reject two files with same path but different content?

I'm also not completely convinced by your argumentation: why don't you use the full path to the classpath location to check for duplicates? We now had duplicate files in different compoents without being detected - and I had hoped validate to detect this as this for other inconsistencies.

**Comment by DoodleBobBuffPants** [comment]
For your first question - yes

For the second - not all migrations have a full path, and this depends on which location they come from (filesystem, classpath, gcs or s3). Making this change would be a breaking change for existing validate workflows

**Comment by magicwerk** [comment]
After doing some test, I still think this is not working as expected and it a bug.
I therefore opened a new issue containing a new test case.

https://github.com/flyway/flyway/issues/3197
flyway:validate still fails to detect duplicate files with identical names in different classpaths
