### ISSUE TITLE
"placeholders.password" overrides "password" as flyway password

### ISSUE THREAD

**Issue by brynjulv** [flyway/flyway#3187]
###### Which version and edition of Flyway are you using?
7.9.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This was not a problem in version 5 and 6

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)
oracle 19

###### Which operating system are you using?
windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
conf/x.conf contains:
flyway.user=fish
flyway.password=fruit
flyway.placeholders.password=bean
fish is the flyway user, fruit is the valid password for that user.
Command 1) $ flyway -configFiles=conf/x.conf info
Command 2) $ flyway -configFiles=conf/x.conf info -password=fruit
Command 3) $ flyway -configFiles=conf/x.conf info -placeholders.password=fruit

###### What did you expect to see?
All three command successful

###### What did you see instead?
The first two commands fail:

SQL State  : 72000
Error Code : 1017
Message    : ORA-01017: ugyldig brukernavn/passord, nektet pålogging
(That's norwegian for invalid username/password)

The last one succeeds.

It looks like "placeholders.password", if set, overrides "password" and is used as the flyway password.
It did not work that way in flyway 5/6.
This looks like a bug (if it is a feature I don't like it).

**Comment by DoodleBobBuffPants** [comment]
This is one of the breaking changes made in Flyway V7. Flyway now has a `jdbcProperties` parameter and this, combined with the placeholders, are passed to the JDBC driver when the datasource is instantiated. This means that if you set a placeholder to a reserved keyword for your database (`password` in this case) then it will override that value. We'll be happy to revisit this should more people have the same issue, but the recommended approach is to rename your placeholder
