### ISSUE TITLE
flyway.jarDirs config property unknown

### ISSUE THREAD

**Issue by twwwt** [flyway/flyway#3189]
###### Which version and edition of Flyway are you using?
7.9.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle Plugin.

###### Which database are you using? (Type & version)
not relevant

###### Which operating system are you using?
not relevant

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
run `gradle :my_gradle_project:flywayInfo`

###### What did you expect to see?
The output that's supposed to be produced when running the task `flywayInfo`.

###### What did you see instead?
The following error:
```
> Error occurred while executing flywayInfo
  Unknown configuration property: flyway.jarDirs
```

It seems that since version 6, the property `flyway.jarDirs` cannot be used anymore in the `flyway.conf` file. However, the example configuration file distributed as part of the standard release still mentions/documents it, even the [current version in master branch](https://github.com/flyway/flyway/blob/master/flyway-commandline/src/main/assembly/flyway.conf). If this property is indeed no longer supported, please remove it from the example config ~~and better explain how we can add extra JARs to the classpath, especially for the Gradle plugin as this is a rather vital use case~~ or add an info where/when it can be used.

**Comment by DoodleBobBuffPants** [comment]
As per our [documentation](https://flywaydb.org/documentation/configuration/parameters/jarDirs), this feature isn't available in Gradle
