### ISSUE TITLE
Broken Alias in jre/legal directory in MacOS version

### ISSUE THREAD

**Issue by ekuntzHautelook** [flyway/flyway#3192]
###### Which version and edition of Flyway are you using?
7.9.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MySQL

###### Which operating system are you using?
MacOS 11.3.1

###### What did you do?
I found that the alias, in the `flyway-7.9.1/jre/legal/ADDITIONAL_LICENSE_INFO`, along with all of the aliases in the `flyway-7.9.1/jre/legal` directory, are all referencing themselves. 

###### What did you expect to see?
I believe they are all suppose to be referencing the directory `flyway-7.9.1/jre/legal/java.base`.  If those alias files are not meant to show some legal information, then I would not expect to see the legal folder.

###### What did you see instead?
When attempting to open those files via Finder, there is an error stating that the alias is broken.  I generally am not concerned with the legal information that is suppose to be provided, outside of abiding to the licenses, but the alias files were causing an error when I had installed the CLI in my javascript repo. After I fixed a couple alias files to verify what was causing the issue, and finally removed the `legal` folder, the error went away.

<img width="1299" alt="flyway-legal-bug" src="https://user-images.githubusercontent.com/49455702/120578345-806f5980-c3da-11eb-8b57-78bae8c5cac5.png">

**Comment by DoodleBobBuffPants** [comment]
Flyway ships with a JRE for your OS, and these files aren't controlled by us as we simply copy over the artifact from Maven

You can delete this folder, in which case Flyway will use the JRE specified by the `JAVA_HOME` environment variable
