### ISSUE TITLE
Config to change existing Sql files 

### ISSUE THREAD

**Issue by azharakbar** [flyway/flyway#3194]
Hi Team,
How can I change existing sql files for flyway?

When i change and run, the following error is thrown
`Caused by: org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration version 2`

Is there a config to change this behaviour?

Thanks

**Comment by DoodleBobBuffPants** [comment]
This isn't possible for versioned migrations. Flyway enforces a forward-only approach, so you will need a new versioned migration to apply the new changes. Repeatable migrations do allow you to change the contents and reapply the migration, so you can use them too. More information about migrations in general is available on our [website](https://flywaydb.org/documentation/getstarted/how)
