### ISSUE TITLE
COPY FROM stdin "missing data for column" error

### ISSUE THREAD

**Issue by GiannisDimitriou** [flyway/flyway#3195]
###### Which version and edition of Flyway are you using?
5.1.1
5.1.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)
PostgreSQL 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Upgrade flyway to 5.1.1 after experiencing the following issue #1945

Note: The issue maybe caused due to both trailing columns are empty

```
CREATE TABLE test_table (
	id SERIAL PRIMARY KEY,
	some_column TEXT,
        some_column2 TEXT
);

COPY test_table (id, some_column,some_column2) FROM stdin;
1	test
2	
3	test
\.
```

`Message    : ERROR: missing data for column "some_column"
  Where: COPY test_table, line 2: "2"`

###### What did you expect to see?

A "migration success" message.

**Comment by DoodleBobBuffPants** [comment]
You need to input the correct number of tabs even if there is no data

If you want the last column to be empty, you need to end in a tab, similarly if you want the middle column to be empty you need two tabs in the middle
