### ISSUE TITLE
flyway:validate still fails to detect duplicate files with identical names in different classpaths

### ISSUE THREAD

**Issue by magicwerk** [flyway/flyway#3197]
###### Which version and edition of Flyway are you using?

7.9.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

newest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

java

###### Which database are you using? (Type & version)

No database (dummy jdbc:hsqldb:mem:myDB)

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

See attached test case
[EvalFlywayBugValidate2.zip](https://github.com/flyway/flyway/files/6609566/EvalFlywayBugValidate2.zip)

I opened last week issue

https://github.com/flyway/flyway/issues/3182
flyway:validate fails to detect duplicate files with identical names in different classpaths

The issue was closed as you stated that this is expected behavior.
You also stated that you would reject two files with same path but different content.

The test case shows that this does not work as expected and I still think this is a bug.

We have 2 projects, EvalFlywayBugValidateMain and EvalFlywayBugValidateLib.
Both containt Flyway migration scripts in src/main/resources.

Tests in EvalFlyway now check whether Flyway detects duplicate files.
testOtherName: main:otherName/V1__file.sql lib:otherName/V1__fileLib.sql: raised as error -> CORRECT
testSameNameSameContent: main:sameNameSameContent/V1__file.sql lib:otherName/sameNameSameContent.sql: same content, accepted -> CORRECT
testSameNameOtherContent: main:sameNameOtherContent/V1__file.sql lib:otherName/sameNameSameContent.sql: other content, still accepted -> WRONG

###### What did you expect to see?

Flyway should detect duplicates as described in issue 3182 but fails to do.

###### What did you see instead?

eval.flyway.EvalFlyway > testSameNameOtherContent FAILED
    java.lang.AssertionError at ExpectException.java:34

**Comment by DoodleBobBuffPants** [comment]
Given your example, I've not been able to reproduce the issue. The last case fails for me as expected. Could you provide a trimmed down reproduction with the just case you're expecting to fail?

**Comment by magicwerk** [comment]
If you run "gradle test", I would expect all tests to be sucessfull if Flyway would detect duplicates correctly.
However testSameNameOtherContent fails.

My output:
>gradle test

> Task :EvalFlywayBugValidateMain:test FAILED

eval.flyway.EvalFlyway > testSameNameOtherContent FAILED
    java.lang.AssertionError at ExpectException.java:34

3 tests completed, 1 failed

FAILURE: Build failed with an exception.

What do you get?

**Comment by magicwerk** [comment]
If you just want to run the test showing the issue, simply execute

gradle test --tests eval.flyway.EvalFlyway.testSameNameOtherContent

**Comment by DoodleBobBuffPants** [comment]
It seems your test set up only finds one migration, hence why it doesn't fail. Copying your set up into another project then works as expected

**Comment by magicwerk** [comment]
I don't think it's the problem of the test that the migration is not found, but probably the root cause of the isssue we encounter.

I attach a new test case showing the issue again.
[EvalFlywayBugValidate3.zip](https://github.com/flyway/flyway/files/6615632/EvalFlywayBugValidate3.zip)

I added logging to see what's happening.

The test contains 2 files with different names and different content:
EvalFlywayBugValidate3\EvalFlywayBugValidateLib\src\main\resources\migration\V1__fileLib.sql
EvalFlywayBugValidate3\EvalFlywayBugValidateMain\src\main\resources\migration\V1__file.sql

Run the test to see Flyway detecing the duplicate.

> gradle test --info

> Task :EvalFlywayBugValidateMain:test FAILED

eval.flyway.EvalFlyway > test STANDARD_OUT
    12:07:21.419 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:db/callback' ...
    12:07:21.423 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Determining location urls for classpath:db/callback using ClassLoader sun.misc.Launcher$AppClassLoader@73d16e93 ...
    12:07:21.437 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Unable to resolve location classpath:db/callback.
    12:07:21.441 [Test worker] INFO org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 7.9.2 by Redgate
    12:07:21.445 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - AWS SDK available: false
    12:07:21.445 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - Google Cloud Storage available: false
    12:07:21.445 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:migration' ...
    12:07:21.446 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Determining location urls for classpath:migration using ClassLoader sun.misc.Launcher$AppClassLoader@73d16e93 ...
    12:07:21.447 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning URL: file:/C:/dev/Temp/bug3/EvalFlywayBugValidate3/EvalFlywayBugValidateMain/build/resources/main/migration
    12:07:21.447 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - JBoss VFS v2 available: false
    12:07:21.450 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.FileSystemClassPathLocationScanner - Scanning starting at classpath root in filesystem: C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\build\resources\main\
    12:07:21.450 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.FileSystemClassPathLocationScanner - Scanning for resources in path: C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\build\resources\main\migration (migration)
    12:07:21.451 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning URL: jar:file:/C:/dev/Temp/bug3/EvalFlywayBugValidate3/EvalFlywayBugValidateLib/build/libs/EvalFlywayBugValidateLib.jar!/migration    12:07:21.451 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - JBoss VFS v2 available: false
    12:07:21.453 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/
    12:07:21.453 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/V1__file.sql
    12:07:21.453 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/V1__fileLib.sql
    12:07:21.453 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classes at classpath:migration
    12:07:21.747 [Test worker] INFO org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:hsqldb:mem:myDB (HSQL Database Engine 2.5)
    12:07:21.747 [Test worker] DEBUG org.flywaydb.core.internal.database.base.BaseDatabaseType - Driver  : HSQL Database Engine Driver 2.5.1
    12:07:21.750 [Test worker] DEBUG org.flywaydb.core.Flyway - DDL Transactions Supported: false
    12:07:21.750 [Test worker] DEBUG org.flywaydb.core.Flyway - Schemas:
    12:07:21.751 [Test worker] DEBUG org.flywaydb.core.Flyway - Default schema: null
    12:07:21.759 [Test worker] DEBUG org.flywaydb.core.internal.callback.SqlScriptCallbackFactory - Scanning for SQL callbacks ...
    12:07:21.760 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:07:21.774 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:07:21.786 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:07:21.787 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/V1__file.sql (filename: V1__file.sql)
    12:07:21.787 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/V1__fileLib.sql (filename: V1__fileLib.sql)
    12:07:21.794 [Test worker] DEBUG org.flywaydb.core.Flyway - Memory usage: 50 of 481M

eval.flyway.EvalFlyway > test FAILED
    org.flywaydb.core.api.FlywayException: Found more than one migration with version 1
    Offenders:
    -> C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\file:\C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateLib\build\libs\EvalFlywayBugValidateLib.jar!\migration\V1__fileLib.sql (SQL)
    -> C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\build\resources\main\migration\V1__file.sql (SQL)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.checkForIncompatibilities(CompositeMigrationResolver.java:152)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:117)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:100)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:47)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:92)
        at org.flywaydb.core.internal.command.DbInfo.info(DbInfo.java:59)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:388)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:383)
        at org.flywaydb.core.Flyway.execute(Flyway.java:574)
        at org.flywaydb.core.Flyway.info(Flyway.java:383)
        at eval.flyway.EvalFlyway.checkDuplicateVersion(EvalFlyway.java:33)
        at eval.flyway.EvalFlyway.test(EvalFlyway.java:17)

1 test completed, 1 failed

This means that Flyway checks the classpath correctly, as it finds the 2 files at the two different locations.
You can also see this as debug output by the ClassPathScanner
    12:07:21.453 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/V1__file.sql
    12:07:21.453 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/V1__fileLib.sql

Now rename 
EvalFlywayBugValidate3\EvalFlywayBugValidateLib\src\main\resources\migration\V1__fileLib.sql
to 
EvalFlywayBugValidate3\EvalFlywayBugValidateLib\src\main\resources\migration\V1__file.sql

The file has now the same name as 
EvalFlywayBugValidate3\EvalFlywayBugValidateMain\src\main\resources\migration\V1__file.sql
but still different content.
Flyways should now detect that there are files with the same name, but different content.

Run test again:

>gradle test --info 

eval.flyway.EvalFlyway > test STANDARD_OUT
    12:09:04.265 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:db/callback' ...
    12:09:04.265 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Determining location urls for classpath:db/callback using ClassLoader sun.misc.Launcher$AppClassLoader@73d16e93 ...
    12:09:04.275 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Unable to resolve location classpath:db/callback.
    12:09:04.285 [Test worker] INFO org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 7.9.2 by Redgate
    12:09:04.285 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - AWS SDK available: false
    12:09:04.285 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - Google Cloud Storage available: false
    12:09:04.285 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:migration' ...
    12:09:04.285 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Determining location urls for classpath:migration using ClassLoader sun.misc.Launcher$AppClassLoader@73d16e93 ...
    12:09:04.285 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning URL: file:/C:/dev/Temp/bug3/EvalFlywayBugValidate3/EvalFlywayBugValidateMain/build/resources/main/migration
    12:09:04.285 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - JBoss VFS v2 available: false
    12:09:04.295 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.FileSystemClassPathLocationScanner - Scanning starting at classpath root in filesystem: C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\build\resources\main\
    12:09:04.295 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.FileSystemClassPathLocationScanner - Scanning for resources in path: C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\build\resources\main\migration (migration)
    12:09:04.295 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning URL: jar:file:/C:/dev/Temp/bug3/EvalFlywayBugValidate3/EvalFlywayBugValidateLib/build/libs/EvalFlywayBugValidateLib.jar!/migration
    12:09:04.295 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - JBoss VFS v2 available: false
    12:09:04.300 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/
    12:09:04.300 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/V1__file.sql
    12:09:04.300 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classes at classpath:migration
    12:09:04.575 [Test worker] INFO org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:hsqldb:mem:myDB (HSQL Database Engine 2.5)
    12:09:04.575 [Test worker] DEBUG org.flywaydb.core.internal.database.base.BaseDatabaseType - Driver  : HSQL Database Engine Driver 2.5.1
    12:09:04.575 [Test worker] DEBUG org.flywaydb.core.Flyway - DDL Transactions Supported: false
    12:09:04.575 [Test worker] DEBUG org.flywaydb.core.Flyway - Schemas:
    12:09:04.575 [Test worker] DEBUG org.flywaydb.core.Flyway - Default schema: null
    12:09:04.585 [Test worker] DEBUG org.flywaydb.core.internal.callback.SqlScriptCallbackFactory - Scanning for SQL callbacks ...
    12:09:04.585 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:09:04.605 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:09:04.615 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:09:04.615 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/V1__file.sql (filename: V1__file.sql)
    12:09:04.635 [Test worker] DEBUG org.flywaydb.core.Flyway - Memory usage: 50 of 481M
    C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\build\resources\main\migration\V1__file.sql
    12:09:04.645 [Test worker] INFO org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 7.9.2 by Redgate
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - AWS SDK available: false
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - Google Cloud Storage available: false
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:migration' ...
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Determining location urls for classpath:migration using ClassLoader sun.misc.Launcher$AppClassLoader@73d16e93 ...
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning URL: file:/C:/dev/Temp/bug3/EvalFlywayBugValidate3/EvalFlywayBugValidateMain/build/resources/main/migration
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - JBoss VFS v2 available: false
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning URL: jar:file:/C:/dev/Temp/bug3/EvalFlywayBugValidate3/EvalFlywayBugValidateLib/build/libs/EvalFlywayBugValidateLib.jar!/migration
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.util.FeatureDetector - JBoss VFS v2 available: false
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Found resource: migration/V1__file.sql
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.classpath.ClassPathScanner - Scanning for classes at classpath:migration
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.Flyway - DDL Transactions Supported: false
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.Flyway - Schemas:
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.Flyway - Default schema: null
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.callback.SqlScriptCallbackFactory - Scanning for SQL callbacks ...
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.command.DbValidate - Validating migrations ...
    12:09:04.645 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:09:04.654 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/ (filename: )
    12:09:04.655 [Test worker] DEBUG org.flywaydb.core.internal.scanner.Scanner - Filtering out resource: migration/V1__file.sql (filename: V1__file.sql)
    12:09:04.657 [Test worker] INFO org.flywaydb.core.internal.command.DbValidate - Successfully validated 1 migration (execution time 00:00.005s)
    12:09:04.657 [Test worker] DEBUG org.flywaydb.core.Flyway - Memory usage: 50 of 481M
Finished generating test XML results (0.001 secs) into: C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\build\test-results\test
Generating HTML test report...
Finished generating test html results (0.005 secs) into: C:\dev\Temp\bug3\EvalFlywayBugValidate3\EvalFlywayBugValidateMain\build\reports\tests\test
:EvalFlywayBugValidateMain:test (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 1.623 secs.

BUILD SUCCESSFUL in 3s

Now Flyway happily accepts the migration, even if the there are files with same name, but different content.

It seems that Flyway fails to scan the classpath properly if there are mutliple files with identical paths in the classpath.
This is however a common use case, think about all the information placed at a predefined location in META-INF, e.g. beans.xml or other configuration files.

So I still think this is a bug which should be addressed.

Otherwise I would ask you to provide the project showing how this works for you.

**Comment by magicwerk** [comment]
Any news on this issue?

**Comment by magicwerk** [comment]
May I ask again whether there are news on this issue?
