### ISSUE TITLE
Many projects report the same exception.

### ISSUE THREAD

**Issue by zolian11** [flyway/flyway#3198]
###### Which version and edition of Flyway are you using?
5.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I have userd the latest version to instead.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin.

###### Which database are you using? (Type & version)
MySQL,5.7.2.

###### Which operating system are you using?
Develop is Windows 10, and servers are Linux CentOS 7.5.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I did nothing.It's happened on the AM of yesterday.

###### What did you expect to see?
Of course,the projects are running successfully.

###### What did you see instead?
The flywaydb of many projects report the same exception,but the sql file is not exsits.
The error message:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 1.0.202105311400
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: Detected applied migration not resolved locally: 1.0.202105311400

**Comment by Barry-RG** [comment]
This was an intentional change for version 7.
Please see documentation on [ignoreMissingMigrations](https://flywaydb.org/documentation/configuration/parameters/ignoreMissingMigrations) to correct this issue.
Closing for now.
