### ISSUE TITLE
Flyway 7.x should accept classpath locations separated by '.', just like 6.x did

### ISSUE THREAD

**Issue by MartinHaeusler** [flyway/flyway#3199]
I've just spent over two hours upgrading Flyway 6.x to 7.x (latest). The 6.x version worked like a charm, the 7.x version refused to find my Java migrations. After debugging the migration resolution in each version side-by-side (in an otherwise identical codebase) I've finally found the issue.

In Flyway 6.x, the following API configuration line works:

```java
 Flyway.configure()
    ....
    .locations("classpath:com.example.myapp.db.migration.scripts")
    ...
    .load()
```

However, this produces nothing (i.e. 0 migration scripts) in 7.x. After a lot of debugging, I've found the solution. The equivalent for 7.x is:

```java
 Flyway.configure()
    ....
    .locations("classpath:com/example/myapp/db/migration/scripts")
    ...
    .load()
```

The new separator has to be `/`, whereas before also `.` was accepted (which is the more natural way to write a Java package name). I haven't found any documentation on this change in particular.

I don't know why this has been done this way, I just hope that this issue will save someone the hours I've wasted on this.

**Comment by Barry-RG** [comment]
This was an intentional change for version 7.
Unless there is further interest we will not be reopening this at this time.
Closing for now.
