### ISSUE TITLE
"Flyway Community database support extension" output is confusing

### ISSUE THREAD

**Issue by dvdtknsn** [flyway/flyway#3200]
When running flyway info I get a confusing message "Flyway Community database support extension 7.9.0 by Redgate"

- Should I get this message at all?
- If so, what is it telling me? I don't know what a database support extension is.
- I have Flyway Teams, so it's confusing that it's referring to "Flyway Community".

flyway info

WARNING: You are on an older version of Flyway. Please download latest at https://www.flywaydb.org/download/community
Flyway Teams Edition (unlimited schemas) 7.9.0 by Redgate licensed to David Ong until 2021-07-06
>       Flyway Community database support extension 7.9.0 by Redgate

**Comment by DoodleBobBuffPants** [comment]
This output is expected

It refers to the Community database support extension - database types supported by the community - as opposed to Flyway Community edition. This message reports the version of this extension as well as verifies it is available. The relevant extension can be located within the `lib/[community|enterprise]` folder

**Comment by esauser** [comment]
I agree this is confusing since there is a `Community` and `Teams` edition.  We are also on `Teams` and seeing this output.  What is the purpose of the output?

**Comment by madninjaskillz** [comment]
This is by design. To clarify: "Flyway Community database support extension 7.9.0 by Redgate" is specifying the version of the (new) plugin that allows the community to create database support. More details can be found [here](https://flywaydb.org/documentation/contribute/contributingDatabaseSupport) and [here](https://flywaydb.org/documentation/learnmore/database-support).

When community supported database jars are added to flyway, their version numbers will also be reported here.
This is an artifact of Flyway becoming more modular and extensible.

That said, we understand the confusion and are discussing approaches to reduce this.

**Comment by dvdtknsn** [comment]
What surprised me is seeing these appear. I know they're new capabilities, but I was unaware that they'd been included.

If the "Community" in "Flyway Community" is referring to "community database support" it should be lower case "c", otherwise people will naturally read this as "Flyway Community" (the edition of Flyway). Also, maybe it would help to remove "Flyway", as this is a given. So, this could read something like "Community-contributed database support 7.9.0" or similar.

C:\WINDOWS\system32>flyway info
Flyway Teams Edition (unlimited schemas) 7.10.0 by Redgate licensed to Redgate until 2020-07-01
>       Flyway Community database support extension 7.10.0 by Redgate
>       GCP Spanner/BigQuery database support (beta) 7.10.0 by Redgate

**Comment by LitKnd** [comment]
Hi,

I saw the message "Flyway Community database support extension 7.10.0 Redgate" when executing Flyway teams in a Docker container this week. 

I see that a commit has been made to change this to "Community-contributed database support extension", but this message is still quite confusing to me, even after reading the links above. 

The message implies to me that there's only community support for this database and that I don't get Redgate support for this even though I'm using Teams. 

If the goal is to encourage the community to contribute more plugins then I think we should take a different approach.


![image](https://user-images.githubusercontent.com/1623675/122371981-3482ef80-cf58-11eb-84e4-0cb4b4f66a8d.png)
