### ISSUE TITLE
Suppress Old Version Warning

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3201]
###### Which version and edition of Flyway are you using?
7.9.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Well it doesn't happen on the latest, but the more recent non-latest.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Ran `flyway migrate`

###### What did you expect to see?
No warning

###### What did you see instead?
`WARNING: You are on an older version of Flyway. Please download latest at https://www.flywaydb.org/download/community`

Is there a way to suppress this?  We do not want it showing on all of our pipeline steps.  We also don't want to be running the bleeding edge version.

**Comment by madninjaskillz** [comment]
`-skipCheckForUpdate` should achieve what you require

**Comment by esauser** [comment]
@madninjaskillz is this documented?
