### ISSUE TITLE
SELECT command denied to user 'user'@'xx.xx.xx.xx' for table 'user_variables_by_thread'

### ISSUE THREAD

**Issue by loongshaw** [flyway/flyway#3202]
**error info :**
execute error. SELECT variable_name FROM performance_schema.user_variables_by_thread WHERE variable_value IS NOT NULL
java.sql.SQLSyntaxErrorException: SELECT command denied to user  'user'@'xx.xx.xx.xx' for table 'user_variables_by_thread'

**flywaydb version:**
<dependency>
	<groupId>org.flywaydb</groupId>
	<artifactId>flyway-core</artifactId>
	<version>7.7.3</version>
</dependency>

**Comment by madninjaskillz** [comment]
It seems like the user that flyway is using (or its IP Address) has not been granted permissions within your DB. Can you give further details on which DB you are using so we can give more specific assistance?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity

**Comment by loongshaw** [comment]
granted permissions to our db use following sql, it's okay, thanks. @DoodleBobBuffPants @madninjaskillz 
`GRANT SELECT ON performance_scheme.user_variables_by_thread TO 'username'@'%'
`

**Comment by jdkcn** [comment]
> granted permissions to our db use following sql, it's okay, thanks. @DoodleBobBuffPants @madninjaskillz `GRANT SELECT ON performance_scheme.user_variables_by_thread TO 'username'@'%' `

fix the typo.

`GRANT SELECT ON performance_schema.user_variables_by_thread TO 'username'@'%'`
