### ISSUE TITLE
H2 database compatibility broken on current H2 HEAD with incorrect column names

### ISSUE THREAD

**Issue by craigraw** [flyway/flyway#3204]
###### Which version and edition of Flyway are you using?
7.9.1-community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
H2 1.4.201 (latest HEAD)

###### Which operating system are you using?
OSX

###### What did you do?
In Flyway's `H2Database.java`, there is an SQL command to read the database compatibility type from Flyway's internal configuration: https://github.com/flyway/flyway/blob/5f89e02a3ce76ebd91fce784063acf2976c6c8d5/flyway-core/src/main/java/org/flywaydb/core/internal/database/h2/H2Database.java#L98

This SQL selects from `VALUE` on the column `NAME` - however the columns are actually called `SETTING_NAME` and `SETTING_VALUE`. I notice that when using the H2 1.4.200 release, the column names are `NAME` and `VALUE`.

On performing a migration to setup a new database, H2 throws the error
```
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT VALUE[*] FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE'"; expected "TOP, DISTINCT, ALL, ,, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
```

This error causes a terminal `FlywayException` to end the migration process.

If I run the following modified SQL in the database however, it works as expected, returning `REGULAR`:
```
SELECT SETTING_VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE SETTING_NAME = 'MODE'
```

While I realise supporting a non-stable release may not be a priority, I believe H2 is planning on another release soon.

Any workarounds appreciated!

**Comment by juliahayward** [comment]
Thankyou! The next release will have both H2 1.x and 2.0 support (with autodetection, so no need to configure Flyway itself).
