### ISSUE TITLE
2 simultaneously running Flyway migrations will run forever if contains a repeatable migration with ${flyway:timestamp}

### ISSUE THREAD

**Issue by johnlinp** [flyway/flyway#3207]
###### Which version and edition of Flyway are you using?
Flyway version: 7.9.1
Flyway edition: Community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
MySQL 5.7.32

###### Which operating system are you using?
macOS 11.2.3

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
1. Create a repeatable migration `R__always_run_once.sql` with the following content (following the suggestion provided [here](https://flywaydb.org/blog/flyway-timestampsandrepeatables)):
```sql
-- ${flyway:timestamp}
OPTIMIZE TABLE user; -- some sql that takes a long time
```
2. Open up 2 terminals and start running the migration simultaneously

###### What did you expect to see?
The 2 migrations will run `R__always_run_once.sql` once each and then finish successfully.

###### What did you see instead?
The 2 migrations is running `R__always_run_once.sql` again and again, forever.

**Comment by DoodleBobBuffPants** [comment]
I'm unable to reproduce this, however this may be indicative of a subtle concurrency issue. Are you able to provide a consistent reproduction?

**Comment by johnlinp** [comment]
Yes. Here's a consistent reproduction: https://github.com/johnlinp/misc-demo/tree/master/flyway-two-migrations-running-forever
Please let me know if you have further questions. Thanks.
