### ISSUE TITLE
Flyway create multiple schema history table and I get exception when I am using fresh database with no schema

### ISSUE THREAD

**Issue by guptapavan31** [flyway/flyway#3210]
###### Which version and edition of Flyway are you using?

7.10.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I am using the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)

Postgres 13

###### Which operating system are you using?

Window

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I have a completely empty data base with no schema.

```
    flyway =
        Flyway.configure()
            .dataSource(<Hikari data source>)
            .schemas("XYZ")
            .defaultSchema("XYZ")
            .table("My_H_table")
            .locations(
                "classpath:db/migration", "classpath:com/pavan/schmea/db/migration")
            .baselineVersion("1.0.0")
            .target(MigrationVersion.LATEST)
            .load().migrate;
 ```
 
###### What did you expect to see?

Schema XYZ created. It have only one My_H_table in it with just 1 entry 

###### What did you see instead?

1) When I run this I get below error
org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "XYZ" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.

2) If I set baselineOnMigrate=true then I end up have 2 tables in my "XYZ" schema
this is `My_H_table` table
![image](https://user-images.githubusercontent.com/80312918/122388814-8a639180-cf70-11eb-9fb2-7c2fb9b59c23.png)

and this is `flyway_schema_history` table
![image](https://user-images.githubusercontent.com/80312918/122388952-aff09b00-cf70-11eb-8d63-80195aa59f14.png)

**Comment by DoodleBobBuffPants** [comment]
I am unable to reproduce this with the information provided

Could you provide a minimal reproduction project?

**Comment by guptapavan31** [comment]
I doing the additional research and will try to get back to you asap. It seems my `HikariCP` datasource is creating this problem.
This specific problem happens when I create the `com.zaxxer.hikari.HikariDataSource` and call `hikariDataSource.setSchema("XYZ")`

When I do not set schema then I end up having 
My SQL execute on "public" as well as "XYZ" schema. so I end up having duplicate schema's 

Public with my tables + `flyway_schema_history` and "XYZ" having My tables + `My_H_table`

**Comment by guptapavan31** [comment]
Please accept my apologies. 

I forget to set 
```
spring:
    flyway:
        enabled: false
```

Which resulted in calling flyway twice.  Once when I define HikariCP datasource and once when actually calling through spring boot in `afterPropertiesSet` method. 

Now after having this specifically disabled I am having my expected database.
