### ISSUE TITLE
Add string concatenation around all LOG.debug() calls with string concatenation

### ISSUE THREAD

**Issue by keesvandieren** [flyway/flyway#3211]
###### Which version and edition of Flyway are you using?

7.3.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Not relevant

###### Which operating system are you using?

N/A

###### What did you expect to see?

I see that many strings concatenations are done in LOG.debug calls without isDebugEnabled() condiation around it

###### What did you see instead?

isDebugEnabled() statement around all LOG.debug statements that do string concatenation

**Comment by DoodleBobBuffPants** [comment]
Closing as per https://github.com/flyway/flyway/pull/3212
