### ISSUE TITLE
Flyway execution time is way longer with newer version of flyway

### ISSUE THREAD

**Issue by cmodiano** [flyway/flyway#3213]
###### Which version and edition of Flyway are you using?
Flyway 7.10.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Oracle 12.2

###### Which operating system are you using?
AIX and Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL 
Just doing an info on a database

###### What did you expect to see?
I get the expected output but it takes much more time than with flyway 7.3.1 that we use currently

**FLYWAY 7.3.1**

BEGINNING: Tue Jun 22 09:31:01 EDT 2021

Flyway Teams Edition (unlimited schemas) 7.3.1 by Redgate licensed to ********* until 2023-10-01
Database: jdbc:oracle:thin:@//*********:1521/OLTP_HISTP (Oracle 12.2)
Schema version: 1

+-----------+-----------+-----------------------------------------------+----------+---------------------+----------+----------+
| Category  | Version   | Description                                   | Type     | Installed On        | State    | Undoable |
+-----------+-----------+-----------------------------------------------+----------+---------------------+----------+----------+
|           | 1         | << Flyway Baseline >>                         | BASELINE | 2021-06-21 10:51:04 | Baseline | No       |
| Versioned | 02.001.00 | modification structure table MVT              | SQL      |                     | Pending  | Yes      |
| Versioned | 02.002.01 | ajout de donnees table CTL UD TO UDE MAPPING  | SQL      |                     | Pending  | Yes      |
| Versioned | 02.003.00 | drop des vues inutiles                        | SQL      |                     | Pending  | Yes      |
| Versioned | 02.004.00 | drop des tables inutiles                      | SQL      |                     | Pending  | Yes      |
| Versioned | 02.005.00 | modification index table MVT USER DATA DIM 11 | SQL      |                     | Pending  | Yes      |
| Versioned | 02.006.01 | suppression de donnees tables MAPPING         | SQL      |                     | Pending  | No       |
+-----------+-----------+-----------------------------------------------+----------+---------------------+----------+----------+

END: Tue Jun 22 09:31:08 EDT 2021

**FLYWAY 7.10.0**

BEGINNING: Tue Jun 22 09:54:16 EDT 2021

Flyway Teams Edition (unlimited schemas) 7.10.0 by Redgate licensed to ***************** until 2023-10-01
>	Flyway Community database support extension 7.10.0 by Redgate
>	GCP Spanner/BigQuery database support (beta) 7.10.0 by Redgate
Database: jdbc:oracle:thin:@//**********:1521/OLTP_HISTP (Oracle 12.2)
Schema version: 1

+-----------+-----------+-----------------------------------------------+----------+---------------------+----------+----------+
| Category  | Version   | Description                                   | Type     | Installed On        | State    | Undoable |
+-----------+-----------+-----------------------------------------------+----------+---------------------+----------+----------+
|           | 1         | << Flyway Baseline >>                         | BASELINE | 2021-06-21 10:51:04 | Baseline | No       |
| Versioned | 02.001.00 | modification structure table MVT              | SQL      |                     | Pending  | Yes      |
| Versioned | 02.002.01 | ajout de donnees table CTL UD TO UDE MAPPING  | SQL      |                     | Pending  | Yes      |
| Versioned | 02.003.00 | drop des vues inutiles                        | SQL      |                     | Pending  | Yes      |
| Versioned | 02.004.00 | drop des tables inutiles                      | SQL      |                     | Pending  | Yes      |
| Versioned | 02.005.00 | modification index table MVT USER DATA DIM 11 | SQL      |                     | Pending  | Yes      |
| Versioned | 02.006.01 | suppression de donnees tables MAPPING         | SQL      |                     | Pending  | No       |
+-----------+-----------+-----------------------------------------------+----------+---------------------+----------+----------+

END: Tue Jun 22 09:56:29 EDT 2021

**Comment by DoodleBobBuffPants** [comment]
Closing as this is being dealt by official support, however feel free to leave comments here for others

**Comment by cmodiano** [comment]
After testing several versions between 7.3.1 and 7.10.0 we found that the issue is introduced in 7.9.0.
Adding the -skipCheckForUpdate option solved the performance issue
