### ISSUE TITLE
No log output when there is "Invalid versioned migration name format"

### ISSUE THREAD

**Issue by sandynz** [flyway/flyway#3219]
###### Which version and edition of Flyway are you using?
7.10.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
MySQL 5.7

###### Which operating system are you using?
Win10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
1. Put `db/migration/V1_Init.sql` in classpath
2. Set `.baselineOnMigrate(true).baselineVersion("0")`, and then run `flyway.migrate();`

###### What did you expect to see?
1. Tables in sql file could be created
2. There is related record in `flyway_schema_history`

###### What did you see instead?
1. Tables not created
2. There is only "Flyway Baseline" in `flyway_schema_history`
3. In log
```
[main] (ApacheCommonsLog.java:44) - Validating migrations ...
[DEBUG] [main] (ApacheCommonsLog.java:44) - Filtering out resource: db/migration/V1_Init.sql (filename: V1_Init.sql)
[INFO ] [main] (ApacheCommonsLog.java:48) - Successfully validated 1 migration (execution time 00:00.016s)
[INFO ] [main] (ApacheCommonsLog.java:48) - Current version of schema `testdb`: 0
[INFO ] [main] (ApacheCommonsLog.java:48) - Schema `testdb` is up to date. No migration necessary.
```

During debugging, I found `SqlScriptCallbackFactory.java`
```
            ResourceName parsedName = resourceNameParser.parse(resource.getFilename());
            if (!parsedName.isValid()) {
                continue;
            }
```
`parsedName.isValid()` returned `false`.
There was `validityMessage: Invalid versioned migration name format: V2_Init.sql (could not recognise version number 2_Init)` when evaluating `parsedName`.

In fact, I made a mistake: sql file name format is wrong (one underscore missed), but I can't find it in log.
It might be better to print it in log if migration name format is invalid.

**Comment by DoodleBobBuffPants** [comment]
You can achieve this by enabling [`validateMigrationNaming`](https://flywaydb.org/documentation/configuration/parameters/validateMigrationNaming)

**Comment by sandynz** [comment]
OK, thanks
