### ISSUE TITLE
HSQLDB 2.6 Support

### ISSUE THREAD

**Issue by A248** [flyway/flyway#3221]
Flyway states it does not support HSQLDB 2.6 and outputs a console message to say so.

###### Which version and edition of Flyway are you using?
7.9.2, community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
7.10.0 has the same message about not supporting HSQLDB 2.6.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
HSQLDB 2.6

###### Which operating system are you using?
Mac OS X (developer's personal machine)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run Flyway with HSQLDB 2.6 Console output follows:

> [main] WARN org.flywaydb.core.internal.database.base.Database - Flyway upgrade recommended: HSQLDB 2.6 is newer than this version of Flyway and support has not been tested. The latest supported version of HSQLDB is 2.5.

###### What did you expect to see?
The version is supported (I didn't actually expect this since 2.6 is relatively new)

###### What did you see instead?
HSQLDB 2.6 is not supported

**Comment by ctoabidmaqbool** [comment]
I am not 100% sure, but I think in the same way HSQLDB 2.5.2 is too un-supported. Please note that's HSQLDb 2.5.2 & 2.6.0 is too biased on module system e.g. implemented using module-info.java yet Flyway is not so if using main module-info.java it's it's too causing of un-sportiness.

**Comment by juliahayward** [comment]
This is only a warning and indicates that we haven't formally tested with 2.6 yet - Flyway *should* work as expected (although we would be keen to hear about any ways in which it does not). That should be done in time for the next release.

**Comment by juliahayward** [comment]
Indeed, it has passed all the tests with 2.6. Do carry on using FLyway, and the warning/documentation will be updated asap.
