### ISSUE TITLE
location config

### ISSUE THREAD

**Issue by woaidaodao** [flyway/flyway#3223]
###### Which version and edition of Flyway are you using?
7.10.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using? (Type & version)

mysql 8.0

###### Which operating system are you using?
windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

my project (based on springboot  2.3.0)  has multiple modules, that means multiple resouces  location exist. when i use  all the default config in yml,  then when i start the project, it  throws exception  as below:

============================
Description:

Flyway failed to initialize: none of the following migration scripts locations could be found:

	- classpath:db/migration

Action:

Review the locations above or check your Flyway configuration

###### What did you see instead?

***************************
APPLICATION FAILED TO START
***************************

Description:

Flyway failed to initialize: none of the following migration scripts locations could be found:

	- classpath:db/migration

Action:

Review the locations above or check your Flyway configuration

2021-06-29 15:44:20.315 [WARN ] org.springframework.boot.SpringApplication - Unable to close _ApplicationContext_

**Comment by Barry-RG** [comment]
`db/migration` is a default location. You will need to change the `locations` property to a valid location.
