### ISSUE TITLE
[support] [javers-5.2.4] :: Defer execution of flyway

### ISSUE THREAD

**Issue by azharakbar** [flyway/flyway#3224]
###### Which version and edition of Flyway are you using?
``5.2.4``

###### Question
Is there a way to delay the execution of flyway scripts in spring-boot app ?

My scenario is as follows:
I have javers configured in my application for auditing purpose
Javers creates some tables and sequences in the DB for their purpose

I want flyway to run after the initialization of javers so that I can write some migration scripts to insert data into javers

Currently, flyway runs first and then javers

I want the other way round.

Is there any way ?

Thanks for the help :-)

**Comment by Barry-RG** [comment]
This is an issue with how Spring Boot orders services as they are initialized. You will need to contact them as this is not something we are able to control.
