### ISSUE TITLE
Support for SOCKS5 proxy

### ISSUE THREAD

**Issue by michaelbv** [flyway/flyway#3226]
How can I get flyway running locally to send the traffic for mydb on desthost:5432 via (say) localhost:7777 (the local end of an SSH tunnel)? 

###### Which version and edition of Flyway are you using?
7.10.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
postgres 13.3

###### Which operating system are you using?
Windows, Ubuntu

**Comment by DoodleBobBuffPants** [comment]
This is something you will have to configure on your machine outside of Flyway to redirect the traffic

If you're expecting a solution in Flyway, could you describe how you're expecting it to work? We likely won't make any changes however unless this gets further interest, so closing for now
