### ISSUE TITLE
[support] [javers-5.2.4] :: Manually trigger execution of flyway

### ISSUE THREAD

**Issue by fantazkool** [flyway/flyway#3228]
Hi, 

I have plugged in flyway to my spring-boot application and works like a charm

Kudos to the team !!

I am assigned with a requirement for which I am not able to get clear documentation on how to do it

The requirement is as follows:
Currently, the flyway is kicking in automatically without the user having to write any code

But, I want this behaviour to stop, and I want it to be triggered only after I manually invoke

How can I do this?

Please give me the code also, to do it

Thanks

**Comment by DoodleBobBuffPants** [comment]
You will need to ask Spring Boot as they maintain the integration with Flyway

However it looks like you may need to use the Maven plugin or use the Java API directly. There is documentation on our website on how to use these [here](https://flywaydb.org/documentation/usage/maven/) and [here](https://flywaydb.org/documentation/usage/api/)
