### ISSUE TITLE
Support to globally disable Update Check

### ISSUE THREAD

**Issue by odin568** [flyway/flyway#3229]
###### Which version and edition of Flyway are you using?
7.11.0 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
-- Feature Request --

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Oracle 19c

###### Which operating system are you using?
Ubuntu based docker container with Flyway manually installed in. This whole in GitLab as CI/CD tool.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
`flyway [baseline|migrate|clean] -url=$DB_URL -password=$DB_PASSWORD  -baselineVersion='$FLYWAY_BASELINE_VERSION_UPSTREAM' -skipCheckForUpdate`
(The Dollar variables are GitLab syntax and will be replaced during run - just ignore)

If I ommit the -skipCheckForUpdate, Flyway will take approx. 20sec until it starts doing the migration or whatever. The reason is that from my build enviornment, I cannot access directly to the Internet, so I assume it's a waiting for timeout.

Adding -skipCheckForUpdate did the trick, yes, but I have this now on every command in my pipeline.yml file. So 7 occurences repeatingly.

###### What did you expect to see?

I want to centrally want to set an Environment Variable and/or set this in the flyway.conf to get a consistent user experience like with all other parameters (... I know about :) )

###### What did you see instead?

Much boilerplate in Pipeline

Commit for reference: https://github.com/flyway/flyway/commit/b0f6073c8be8f7edef09b16f75a6813a29951310

**Comment by odin568** [comment]
That's also an option - thanks!

**Comment by odin568** [comment]
As integrated in 7.11.1:
I can confirm this fixes my issue. Thanks a lot!

**Comment by alexandru-lazarev** [comment]
So what is doing "skipCheckForUpdate" parameter? Is it somewhere documented?

**Comment by odin568** [comment]
No, does not seem to be documented.
If set via command line, will bypass the update check. My issue was that in my pipeline, internet access is blocked, thereby the update check lasted a minute to time out. This gets bypassed with this parameter.
