### ISSUE TITLE
Gradle tasks that inherit from FlywayMigrateTask cannot override 'locations'

### ISSUE THREAD

**Issue by pw-aowen** [flyway/flyway#3232]
###### Which version and edition of Flyway are you using?
7.11.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
At time of writing, 7.11.2 is the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using? (Type & version)
PostgreSQL 12

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I have a custom Gradle task to run flyway migrate. It overrides the 'locations' variable, so that it grabs from a test directory.
```
// normal flyway plugin settings
flyway {
    url = "jdbc:postgresql://mydatabase:6379/mytable"
    user = "username"
    password = "password"
    locations = [
        'filesystem:D:/src/main/resources/db/migration'
    ]
}

// test flyway task
task testDbSetup(type: FlywayMigrateTask) {
    url = "jdbc:postgresql://mydatabase:6379/mytable"
    user = "username"
    password = "password"
    locations = [
        'filesystem:D:/src/main/resources/db/migration',
        'filesystem:D:/src/main/resources/db/test'
    ]
}
```

###### What did you expect to see?
When I execute testDbSetup, I expected the R files in the 'test' directory to be applied to the database.

###### What did you see instead?
The R files from the 'test' directory were not retrieved. 

###### Other Notes
Overriding 'locations' from the FlywayMigrateTask used to behave correctly in v6.0.0

**Comment by tjs145** [comment]
The arguments to `testDbSetup` need to be in a flyway block e.g. 

```groovy
flyway {
    url = "jdbc:postgresql://mydatabase:6379/mytable"
    user = "username"
    password = "password"
    locations = [
        'filesystem:D:/src/main/resources/db/migration',
        'filesystem:D:/src/main/resources/db/test'
    ]
}
```

**Comment by pw-aowen** [comment]
> 
> 
> The arguments to `testDbSetup` need to be in a flyway block e.g.
> 
> ```groovy
> flyway {
>     url = "jdbc:postgresql://mydatabase:6379/mytable"
>     user = "username"
>     password = "password"
>     locations = [
>         'filesystem:D:/src/main/resources/db/migration',
>         'filesystem:D:/src/main/resources/db/test'
>     ]
> }
> ```

That worked, thanks!

**Comment by pw-aowen** [comment]
@tjs145 I might have misunderstood, can you clarify this:

I updated my testDbSetup task to look like this

```
task testDbSetup(type: FlywayMigrateTask) {
    flyway {
        url = "jdbc:postgresql://mydatabase:6379/mytable"
        user = "username"
        password = "password"
        locations = [
            'filesystem:D:/src/main/resources/db/migration',
            'filesystem:D:/src/main/resources/db/test'
        ]
    }
}
```

testDbSetup is working as expected, but the flywayMigrate gradle task is now using this config now as well. Basically, now when I run flywayMigrate, it's grabbing the test R files as well.

**Comment by DoodleBobBuffPants** [comment]
Thanks for letting us know

This seems to be a change introduced in V7 where any configured `flyway` block takes priority - we will investigate trying to retain the old behavior
