### ISSUE TITLE
Erroneous error "Found non-empty schema(s)"

### ISSUE THREAD

**Issue by codemonstur** [flyway/flyway#3236]
###### Which version and edition of Flyway are you using?

7.11.3 (latest)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java app

###### Which operating system are you using?

PostgreSQL 13.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
Running in a kubernetes cluster

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

1. Create an empty database
2. Run app in kubernetes that connects to db
3. Have flyway create the schema from the migration scripts
4. App runs fine at this point; DB is in proper state, a `flyway_schema_history` table exists in the `public` schema
4. Delete the pod from kubernetes and have it be recreated
5. App fails to start claiming the DB is not empty:

        Exception in thread "main" org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "custom" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
            at org.flywaydb.core.Flyway$1.execute(Flyway.java:202)
            at org.flywaydb.core.Flyway$1.execute(Flyway.java:172)
            at org.flywaydb.core.Flyway.execute(Flyway.java:588)
            at org.flywaydb.core.Flyway.migrate(Flyway.java:172)
            at app.util.app.Factory.migrateRelationalDB(Factory.java:64)
            at app.Main.main(Main.java:40)

My app has a main function that calls Flyway somewhere in the beginning. The code that runs flyway is this:

    Flyway.configure().initSql("").locations("/db/migration").dataSource(url, user, pass).load().migrate();

Since Flyway starts successfully the first time I see no error in configuration.

###### What did you expect to see?

Flyway should find it's own history table and realize there is nothing to do and not throw an error.

###### What did you see instead?

The error.

**Comment by DoodleBobBuffPants** [comment]
Could you provide a minimal reproduction project, including migration scripts

**Comment by codemonstur** [comment]
I found a workaround; If I move all my tables out of the custom schema and into the public schema then I no longer get the error. 

I'll see if I can create a test project with the error. I doubt kubernetes is relevant. Maybe just start Postgres through docker.

**Comment by codemonstur** [comment]
That was a lot more painful than I had hoped. But I got it: https://github.com/codemonstur/flyway-bug.

Bug appears to happen when the schema name is the same as the username.

**Comment by DoodleBobBuffPants** [comment]
Thanks for sharing

This is actually an implementation detail of PostgreSQL - it defaults to the schema of the current user's name, and Flyway uses the current schema as its default

You can work around this by setting the `schemas` property on Flyway as you need, where the first item becomes the default schema i.e. something like `.schemas("public", "username")`

**Comment by codemonstur** [comment]
I don't want to explicitly list schema names in the code. If I add a schema in the migration scripts the code is likely to fail for not having it listed.

If I understand you correctly this is what happens:
1. In the first run I have an empty DB so Postgres makes the default schema 'public'
2. Flyway uses the default schema 'public'.
3. The migration scripts make a schema with the same name as the user
4. The second run Postgres makes the schema with my username the default
5. Flyway uses the default schema. This time it is 'username'
6. Flyway throws error because the history table is not in default schema

I'd say there are two bugs here then. Postgres has a bug because it changes the default schema based on content of the DB, and Flyway has a bug for not working around the Postgres bug and trusting the default schema.

Seems like the code that tries to find the history table should look first in the default schema, then in 'public' and finally in 'username'.

**Comment by DoodleBobBuffPants** [comment]
As this is the expected behavior for PostgreSQL, we won't be changing it unless there is further interest as more people are likely to depend on this behavior

**Comment by codemonstur** [comment]
Did some searching. It is possible to configure the default search path in the postgres conf: https://mkyong.com/database/postgresql-how-to-change-default-schema/.

That would work but I don't want to make changes to our postgres database. So instead I'm changing the default search path using some initialization SQL:

    Flyway.configure().initSql("SET search_path = public").dataSource(url, user, pass).load().migrate();

This removes the $user setting from the search path and makes Flyway find the history table correctly. And I don't have to list all the schema names with a `.schemas()` call.
