### ISSUE TITLE
Flyway.info() requires two open db connections in parallel

### ISSUE THREAD

**Issue by uwolfer** [flyway/flyway#3237]
###### Which version and edition of Flyway are you using?
7.11.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Postgress 11.1

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Call `Flyway.info()` from our apps health check.

###### What did you expect to see?
Calls to `Flyway.info()` should never lead in a deadlock.

###### What did you see instead?
Call `Flyway.info()` causes a deadlook sometimes.

###### Additional information
Change which introduces this issue: https://github.com/flyway/flyway/commit/47485cef154061332bfca31ef1050f1e40bb1ea2

Change added a new call to `migrationInfoService.getInfoResult() -> CommandResultFactory#createInfoResult() -> CommandResultFactory#getDatabaseName()`
This method open an addition connection from the data source (while the "main connection" is still open).

Would be nice if this method call would not use db connections in parallel in order to reduce the chance of an exhausted connection pool / deadlocks.

**Comment by DoodleBobBuffPants** [comment]
You should use `Flyway#info()` as that will ensure the connection is closed, so that using the resulting `MigrationInfoService` won't use an additional parallel connection, however we will look into using an existing connection before trying a new one

**Comment by uwolfer** [comment]
@DoodleBobBuffPants: Thanks for your feedback.

Sorry, there was a mistake in my description. I'm indeed using `Flyway.info()`, and this causes the issue as described above.

Can you please reopen this issue?

**Comment by DoodleBobBuffPants** [comment]
Even with that I was unable to reproduce the issue, as all existing connections are closed when I attempt to use them

Are you able to provide a reproduction?

**Comment by uwolfer** [comment]
> Even with that I was unable to reproduce the issue, as all existing connections are closed when I attempt to use them

All connections are properly closed after `Flyway#info()`. But it opens two connections in parallel while running it.

> Are you able to provide a reproduction?

I'll try to describe how we can reproduce this issue:
* configure your connection pool to have at max. 2 active connections
* call `Flyway.info()` from two different threads at the same time
* 1st call to `Flyway.info()` will open a connection in `Flyway#execute()` (`new JdbcConnectionFactory`...)
* 2nd call to `Flyway.info()` will open a connection in `Flyway#execute()` (`new JdbcConnectionFactory`...)
* 1st call tries to open another connection as described in the initial post above, but is not able to get one from the datasource because both available connections are still in use by the 2 calls from above -> locked, and call will fail after connection acquisition timeout reached

**Comment by DoodleBobBuffPants** [comment]
Could you provide a sample project which can reproduce this?

By the time the first thread tries to 'open another connection' the previous connection is closed

As a workaround until then, would [`connectRetries`](https://flywaydb.org/documentation/configuration/parameters/connectRetries) be able to help with the deadlock

**Comment by uwolfer** [comment]
> Could you provide a sample project which can reproduce this?

I'm not able to share my current project unfortunately. Setting up a sample project takes some time.

> By the time the first thread tries to 'open another connection' the previous connection is closed

I don't think this is true. The call to `migrationInfoService.getInfoResult()` from `callbackExecutor.onOperationFinishEvent` happens before the wrapping #execute has finished (and thus finally is not called at that point).

**Comment by DoodleBobBuffPants** [comment]
Ah, so you're using `MigrationInfoService` from within the callback?

**Comment by uwolfer** [comment]
> Ah, so you're using `MigrationInfoService` from within the callback?

No, I'm not using any custom callbacks. I can reproduce this issue with the standard code. The standard code already calls `migrationInfoService.getInfoResult()` independent of any registered callbacks.

In my opinion, it would help if you could pass (reuse) the "main connection" into `CommandResultFactory#createInfoResult()`.

**Comment by uwolfer** [comment]
Probably the following change would fix this issue - but keep in mind that it is untested.

```java
    private static String getDatabaseName(Configuration configuration, Database database) {
        try {
-            Connection connection = configuration.getDataSource().getConnection();
-            String catalog = connection.getCatalog();
+            String catalog = database.getMainConnection().getJdbcConnection().getCatalog();
-            connection.close();
            return catalog != null ? catalog : database.getCatalog();
        } catch (Exception e) {
            return "";
        }
    }
```
