### ISSUE TITLE
flyway_schema_history is cached before beforeValidate.sql is called

### ISSUE THREAD

**Issue by jamesdcockayne** [flyway/flyway#3240]
###### Which version and edition of Flyway are you using?

7.11.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Recreated in latest (7.11.4 at the moment)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command line

###### Which database are you using? (Type & version)

SQL Server 2017

###### Which operating system are you using?

Windows 10 version 2004 build 19041.1110

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I'm trying to force Flyway to apply all repeatables without having to remember to add the timestamp placeholder workaround to each repeatable.

In version 7.10.0 I would have a `beforeValidate.sql` script that would drop entries for my repeatables from the flyway_schema_history table. It looks like this 

```
if object_id ('[dbo].[flyway_schema_history]') is not null
begin

	delete [dbo].[flyway_schema_history]
	where version is null;

end
```

I would use this script to trick Flyway into thinking all my repeatables are new, so that it would be applied in the current migration rather the skipped because the checksum has not changed. I also make use of `beforeMigrate` to drop all stored procedures, functions and views, leaving the database with just tables and user defined table types.

However, since the next release (7.11.0) I can see that the flyway_schema_history table is cached before `beforeValidate.sql` is run. This causes flyway to think that that repeatable does not need to be run, even though there was not an entry in `flyway_schema_history` for the repeatable by the time the validation started.

![image](https://user-images.githubusercontent.com/24731453/127142225-c9e38d58-5d83-4eae-bcf5-fcbef6a9bdb2.png)

###### What did you expect to see?

`beforeValidate.sql` to be executed before any of the validation begins.

###### What did you see instead?

`flyway_schema_history` being cached before `beforeValidate.sql` was executed.

##### Note

I know I'm mucking around in Flyway's internal tables, so a will not fix would be fair enough, but no harm in asking, right?

My general ambition when patching databases is to make sure the repeatables are exactly the same as what we have in source control, even if this means reapplying allegedly not unchanged repeatables again and dropping all existing stored procedures, functions etc.

James

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising awareness of this issue, however we will not be fixing it as this isn't a supported scenario

As you've pointed out, we recommend using the timestamp placeholder to achieve this
