### ISSUE TITLE
Warning message to upgrade flyway because PostgreSQL is newer than Flyway current version.

### ISSUE THREAD

**Issue by kleyton-ohare** [flyway/flyway#3242]
###### Which version and edition of Flyway are you using?
7.11.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This is the latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
PostgreSQL 11.12

###### Which operating system are you using?
Windows 10 Enterprise version 20H2  OS Build 19042.1110 & openSUSE Leap 15.2.139.0

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
mvn clean install

###### What did you expect to see?
I expected to see no warning message since Flyway 7.11.4 was released 4 days ago thus making it newer than PostgreSQL 11.12

###### What did you see instead?
o.f.c.i.database.base.Database: Flyway upgrade recommended: PostgreSQL 11.12 is newer than this version of Flyway and support has not been tested.

Further obs: I have upgraded PostgreSQL to 12.7 and 13.3 and still see the warning message. Also, I have downgraded Flyway to 7.11.3, 7.8.2 and 7.0.1 and still see the warning message.

This issue I am creating now is, in fact, a duplicate of  #2238 which was closed on 11 Dec 2018 because it was thought to be another duplicate (which wasn't, https://github.com/flyway/flyway/issues/2238#issuecomment-455909162). I hope someone can get rid of this warning message when Flyway is newer than a database and this database has been tested.

**Comment by DoodleBobBuffPants** [comment]
I am unable to reproduce this issue, could you provide a minimal reproduction project?

**Comment by kleyton-ohare** [comment]
While trying to create a simple application to reproduce the issue, I noticed my project was still using an old version of Flyway in one of its components.
When I upgraded that, this warning message disappeared as expected.
