### ISSUE TITLE
Newb - How to access (and clear) flyway_schema_history

### ISSUE THREAD

**Issue by LordDarkneo** [flyway/flyway#3243]
###### Which version and edition of Flyway are you using?

7.9.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

didnt try (not my binaries...)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven Plugin

###### Which database are you using? (Type & version)

MariaDB 10.5.11

###### Which operating system are you using?

Docker

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I am trying to build SteVe app, using 2 containers. The first one, to create the MariaDB instance, seems to be fine. For hte second one (the app), it uses the flyway-maven-plugin:7.9.1:migrate during the build. The point is, I had an issue regarding SUPER privileges (because of the new MariaDB behavior):
`Error: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)`

Thus, I sshed the container to run: `mysql> SET GLOBAL log_bin_trust_function_creators = 1;`

I restarted the DB and now, on flyway, I am stuck with the error :
```
app_1  | [ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:7.9.1:migrate (default) on project steve: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
app_1  | [ERROR] Detected failed migration to version 0.6.6 (inital). Please remove any half-completed changes then run repair to fix the schema history.
app_1  | [ERROR] Need more flexibility with validation rules? Learn more: https://flywaydb.org/custom-validate-rules
```
I looked over the internet, and found that I should clear the flyway_schema_history. But how to do this? I am really a noob on SQL commands.... Thanks for the help

###### What did you expect to see?
Somehow, the table flyway_schema_history in a DB, but that's not the case:

###### What did you see instead?

```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 10.5.11-MariaDB-log MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| stevedb            |
+--------------------+
4 rows in set (0.005 sec)

MariaDB [(none)]> select * from mysql.flyway_schema_history;
ERROR 1146 (42S02): Table 'mysql.flyway_schema_history' doesn't exist
MariaDB [(none)]> select * from information_schema.flyway_schema_history;
ERROR 1109 (42S02): Unknown table 'flyway_schema_history' in information_schema
MariaDB [(none)]> select * from stevedb.flyway_schema_history;
ERROR 1146 (42S02): Table 'stevedb.flyway_schema_history' doesn't exist
MariaDB [(none)]> select * from performance_schema.flyway_schema_history;
ERROR 1146 (42S02): Table 'performance_schema.flyway_schema_history' doesn't exist
MariaDB [(none)]>



```

**Comment by DoodleBobBuffPants** [comment]
If you run [`flyway info`](https://flywaydb.org/documentation/command/info) you should see an overview of the schema history table, and in your case the output should contain one row saying that a migration has failed

In this case you will need to manually rollback any changes the migration may have made before failing (by inspecting your database) and then run [`flyway repair`](https://flywaydb.org/documentation/command/repair) to remove the failed entry, which will let you proceed. We don't recommend manually modifying the table

**Comment by LordDarkneo** [comment]
Hi and thanks for you feedback but unfortunately, as I am using containers, I cannot execute the flyway repair (as the container is crashing and I cannot connect to it).
Any idea how to fix this problem? Regards

**Comment by klarajanstova** [comment]
Hi, I had a similar problem, just on Linux and Oracle db, but maybe it will help. Flyway saved flyway_schema_history including quotes, so you have to use it like: select * from mysql."flyway_schema_history";

**Comment by LordDarkneo** [comment]
> Hi, I had a similar problem, just on Linux and Oracle db, but maybe it will help. Flyway saved flyway_schema_history including quotes, so you have to use it like: select * from mysql."flyway_schema_history";

Thanks for your feedback, but as said previously, and what is driving me crazy, is that I do not have any table called flyway_schema_history in mysql (nor other) database!

And in the container of the database, flyway info returns:
`root@28c5558f1fe7:/# flyway info
bash: flyway: command not found
`
