### ISSUE TITLE
flyway.conf doesnt connect / sqlplus is OK

### ISSUE THREAD

**Issue by klarajanstova** [flyway/flyway#3246]
###### Which version and edition of Flyway are you using?
7.8.0
Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
there shouldnt be issue i hope its just conf. problem

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line (linux)

###### Which database are you using? (Type & version)
Oracle 19.9

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I cant setup correctly jdbc:oracle:thin:@<tns_entry>
I have sqlplus command: $ sqlplus /@WALLET_NAME - it will connect me correctly 
In flyway.conf - flyway.url=jdbc:oracle:thin:/@WALLET_NAME or flyway.url=jdbc:oracle:thin:@WALLET_NAME or many others....
it will always want to fill USER and PASSWORD
(i am trying command $ flyway info)
connect via jdbc:oracle:thin:@//host:port/service works fine

###### What did you expect to see?
it will connect as the same as sqlplus 

###### What did you see instead?
i have to fill USER / PASSWORD manually

**Comment by DoodleBobBuffPants** [comment]
There's some documentation on connecting with Wallet [here](https://flywaydb.org/documentation/database/oracle#oracle-wallet). Note that you may need to leave `flyway.user` and `flyway.password` empty too

**Comment by klarajanstova** [comment]
Hi thanks for reply. When I left user/password empty, i have this error: 

ERROR: 
Unable to obtain connection from database (jdbc:oracle:thin:@DB_NAME?TNS_ADMIN=PATH_TO_WALLET/oracle) **for user ' ':** ORA-01017: invalid username/password; logon denied

**Comment by DoodleBobBuffPants** [comment]
It seems the Oracle documentation is quite dated - we'll be updating our support for Oracle wallet soon and updating the documentation [here](https://flywaydb.org/documentation/database/oracle#oracle-wallet) when it is released

**Comment by klarajanstova** [comment]
ok thanks,

**Comment by DoodleBobBuffPants** [comment]
This is now fixed in release 7.13.0 and the updated documentation is [here](https://flywaydb.org/documentation/database/oracle#oracle-wallet)
