### ISSUE TITLE
Announcement: Changes to Flyway for the V8 release

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#3247]
This issue explains the changes we intend to make to Flyway for the V8 release.

The jump from V7 to V8 will be a major version change, as per [Semantic Versioning](https://semver.org/#summary). Users should expect breaking and non-backward compatible changes to be introduced.

We're sharing this early so you can anticipate if the breaking changes will affect you. Any feedback on these proposals are welcome.

We intend to release Flyway V8 at the end of Q3 2021. Some work may be released before then under feature flags, undocumented features, etc.

For those following the [roadmap](https://flywaydb.org/documentation/learnmore/roadmap), V8 won't necessarily include everything in there. Some features slated for 'V8' may end up in later V8 releases (e.g. 8.1.0).

### API Changes

These things have been marked as deprecated for a long time, and will be removed.

- `-json` flag (replaced with `-outputType=json`)
  - Command line will produce `invalid argument` error
- `SPRING_JDBC` and `UNDO_SPRING_JDBC` migration types 
- `installedOn` field in `InfoOutput`
  - To be replaced with `installedOnUTC`
  - To be marked with a `@Deprecated` annotation
- `validationError` field in `ValidateResult`
  - To be replaced with `errorDetails`
  - To be marked with a `@Deprecated` annotation
- `validateResult` constructor
  - To be replaced with a different constructor
  - To be marked with a `@Deprecated` annotation

### Architecture changes

We're introducing an extension mechanism that will allow optional functionality to loaded at runtime. Extensions can be optionally dropped in to any Flyway installation to enable new capabilities.
 
We're moving [HashiCorp Vault](https://flywaydb.org/documentation/configuration/secretsManagement#hashicorp-vault) from Flyway's core to an extension.

In the course of time we intend to open this up to allow the Flyway community to write their own plugins for new capabilities.

One aim of this is to enable the community to create their own extensions for the [wide range of requested databases](https://github.com/flyway/flyway/issues?q=is%3Aopen+is%3Aissue+label%3A%22t%3A+database+support%22) that Flyway doesn't yet support. This means it'll be unnecessary to have a pull request accepted to the main Flyway codebase to make Flyway compatible with new databases.

Instead, users will be free to create and use their own extensions, which will be compatible with a mainline release of Flyway. You therefore won't need to depend on a community owned fork of the whole codebase.  In this way, we hope to nurture an ecosystem of ['Community Supported'](https://flywaydb.org/documentation/learnmore/database-support) database extensions.

### New functionality

- [Google Cloud Spanner](https://flywaydb.org/documentation/database/cloud-spanner) & [Big Query](https://flywaydb.org/documentation/database/big-query) support will be promoted from beta to general availability
- New secrets managers: Dapr, and Google Secret Manager
- A way to configure the logger that Flyway will use (current behavior is that Flyway picks up any logger it finds on the classpath in a pre-defined order of precedence)

### Drop Android support

We aren't convinced that Flyway is used very much on Android,

Furthermore, it looks like Android support has been broken for a while. See https://github.com/flyway/flyway/issues/970.

We're intending to remove the guarantee of support for Android for V8.

### To mark as deprecated on the V8 release

These features will continue to work in V8, but will be dropped at some future release.

- `defaultSchema` and `schemas` parameters will be re-worked to be less confusing

### Database support timeline

[As per our database support policy](https://flywaydb.org/download/faq#how-long-are-database-releases-supported-in-each-edition-of-flyway), the following database versions are no longer supported in Community edition. They are however still supported in Flyway Teams edition:

- SQL Server 2016
- MariaDB 10.2
- MySQL 5.7
- Sybase ASE 16.2
- Postgres 9.5/9.6
- DB2 11.1 
- Apache Derby 10.13

**Comment by eipi** [comment]
> We're introducing an extension mechanism that will allow optional functionality to loaded at runtime. Extensions can be optionally dropped in to any Flyway installation to enable new capabilities.
@juliahayward This sounds great, I can't wait to see what kind of extensibility is possible here.  We sometimes have some strange problems as a result of rigid organizational procedures that wouldn't make sense to build in to the public release main branch, but would be great to be able to account for them systematically instead of with convoluted manual process.  Great idea!
