### ISSUE TITLE
Percona XtraDB Cluster 8.0 support

### ISSUE THREAD

**Issue by s-apanasionak** [flyway/flyway#3248]
According to this [https://flywaydb.org/documentation/database/xtradb](https://flywaydb.org/documentation/database/xtradb) supported version of Percona XtraDB Cluster is 5.7.
Do you plan to support Percona XtraDB Cluster 8.0?

**Comment by juliahayward** [comment]
Yes; if you run Flyway against an 8.0 instance then you'll get a warning but this simply means that our test setup has (up to now) worked on 5.7. We'll test on 8.0 very soon and clear the warning. In the meantime, if you spot any problems on 8.0  do let us know.

**Comment by juliahayward** [comment]
... to add to this, all tests pass on our first try, so I'll update the documentation now.
