### ISSUE TITLE
Checksum is done too soon 

### ISSUE THREAD

**Issue by guillaumBrisard** [flyway/flyway#3250]
###### Which version and edition of Flyway are you using?
7.10

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Oracle 19c

###### Which operating system are you using?
Your Flyway Docker

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We now use flyway placeholders to change values inside the sql file.
We used to use our own method before executing flyway.
For an existing schema, migrate doesn't work anymore.
Even if in the end it's the same sql code that should be validate,
it's not, because checksum is done before the placeholders replacement.

If we go further, if we have V1 sql file, with the placeholders foo=one, we apply 'migrate' on the database A.
After we add a V2 file and we change the value of foo=two, we apply 'migrate' on database A, it will work, and it doesn't seem right.
If we apply the files on new database B, the result will not be comparable to database A.

###### What did you expect to see?
Checksum computed after placeholders replacement 

###### What did you see instead?
Checksum computed before placeholders replacement

**Comment by guillaumBrisard** [comment]
One solution would be to add a new column to flyway.table with the version of flyway.
If it's greater than the version that will change the way to compute checksum, we use the new way, 
otherwise we use the old way.

To migrate the whole flyway.table, we could use a new option like 'repair_with_new_checksum'.
And it's handle with the command 'repair'

**Comment by juliahayward** [comment]
This is by design - if the checksum is computed after replacement, then changing a placeholder value will invalidate **all** past migrations that use that placeholder. The point of checksumming is simply to determine if a migration file has been manually changed by a user, to catch retrospective changes which may indicate the development process is not working as Flyway expects. Also, when you say:

> If we apply the files on new database B, the result will not be comparable to database A. 

This is one of the major use cases for placeholders, where you want a single set of migrations but a different naming convention between two databases, or two schema.  

> For an existing schema, migrate doesn't work anymore.

Can you give us a reproducible set of steps to verify how Flyway is not working?

**Comment by guillaumBrisard** [comment]
> This is by design - if the checksum is computed after replacement, then changing a placeholder value will invalidate **all** past migrations that use that placeholder.
It's was what I expected, if I had to change the placeholder value, I would create a new one

If I not misunderstood, it's the design for Repeatable since 6.3
https://github.com/flyway/flyway/issues/2177
So in the flyway table, there is 2 ways to compute checksum.

> This is one of the major use cases for placeholders, where you want a single set of migrations but a different naming convention between two databases, or two schema.
Yes for naming convention. 

If I change a little bit my previous example :
We have V1 sql file, with a placeholder foo=one, we apply 'migrate' on the database.
After we add a V2 file and we change the value of foo=two, we apply 'migrate' on database, 
it will work, and it doesn't seem right.
If we clean the database, and and execute flyway with the 2 files, the schema will not be in the same state like before.
And it's what I expect of flyway to always have the same result.

> Can you give us a reproducible set of steps to verify how Flyway is not working?
We used our own tool to replace the placeholders, so before executing flyway, the replacement was already done.
Now we want to use flyway to replace the placeholders, and not our tool.
It's not possible, even if we want to apply the exact same sql.

With a sql file with one placeholder, replace it manually and execute flyway migrate.
Now try to use the placeholders replacement of flyway instead, and try to validate. 
It will fail even if we want to apply the exact same sql in the end.

**Comment by Barry-RG** [comment]
This issue shall be closed until further interest in this feature arises

**Comment by guillaumBrisard** [comment]
It had just been there for less than a week
It was really short for closing this issue and I didn't have an answer of my last post

**Comment by juliahayward** [comment]
Can you give a specific use case for a situation where you would change the value of a placeholder in a single environment? I'm trying to understand why that would be valid, as if you do so then your scripts are not a faithful representation of the database schema unless you also keep a history of how the placeholder values changed over time (which Flyway doesn't do, and will not do without major work)

**Comment by guillaumBrisard** [comment]
For a single environment, it depends if you consider that a placeholder can change over time.
If a placeholder is to handle different environment, in a single environment I can't see why it would change, 
so if it change I expect that the 'validate' will fail before the 'migrate', to protect against misuse.

I already posted all my use cases with this one or the previous ones.
But I understand those uses cases are not enough to start a major work.

Thanks.
