### ISSUE TITLE
JDBC timeout with BigQuery 

### ISSUE THREAD

**Issue by ferrisnorth** [flyway/flyway#3252]
Current JRE version ...................... openjdk-14_windows-x64
  Current Flyway version ................... 7.11.3
  Platform ................................. GCP
  Database ................................. BigQuery
  Required Drivers ......................... GoogleBigQueryJDBC42.jar
  Other JDBC Stuff ......................... SimbaJDBCDriverforGoogleBigQuery42_1.2.18.1022.zip

-- timeouts on larger queries after 10 - 20 seconds

Caused by: java.sql.SQLException: [Simba][BigQueryJDBCDriver](100034) The job has timed out on the server. Try increasing the timeout value.
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](100034) The job has timed out on the server. Try increasing the timeout value.
QL State  : HY000
Error Code : 100034
Message    : [Simba][BigQueryJDBCDriver](100034) The job has timed out on the server. Try increasing the timeout value.
Location   : .\sql\prism\versioned\V1_00_05__tbl_create_product_dim.sql ***
Line       : 3
Statement  : #standardSQL

" CREATE TABLE AS SELECT ***"

It appears as though the default is 10 seconds?
https://simba.wpengine.com/products/BigQuery/doc/JDBC_InstallGuide/content/jdbc/bq/options/timeout.htm

Is it possible to set the JDBC timeout parameter?

**Comment by juliahayward** [comment]
Yes, just add `Timeout=120;` to the end of your JDBC URL. This will configure the driver without Flyway needing to know about it.
