### ISSUE TITLE
Flyway shell runs "forever" when running against unreachable DB with FLYWAY_CONNECT_RETRIES defined

### ISSUE THREAD

**Issue by dimw** [flyway/flyway#3257]
###### Which version and edition of Flyway are you using?
7.14.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
The related code causing the issue [seems to be still present on _master_](https://github.com/flyway/flyway/blob/master/flyway-commandline/src/main/assembly/flyway#L65).

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line (via Docker). Issue also reported in [flyway/flyway-docker#57](https://github.com/flyway/flyway-docker/issues/57).

###### Which database are you using? (Type & version)
MySQL, most likely other DBMS are effected too.

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Running the `flyway` (aka `flyway --help`) bash script while having the [`FLYWAY_CONNECT_RETRIES`](https://flywaydb.org/documentation/configuration/parameters/connectRetries) property set to a large number cause the script running "forever" if the DB is not reachable:
```
$ FLYWAY_URL="jdbc:mysql://nodb/somedb" 
$ FLYWAY_CONNECT_RETRIES=50
$ flyway
... <no output, runs forever> ...
```

The script is hanging in the [license checking line of the bash script](https://github.com/flyway/flyway/blob/master/flyway-commandline/src/main/assembly/flyway#L65):
```bash
"$JAVA_CMD" $JAVA_ARGS $EXTRA_ARGS -cp "$CP" org.flywaydb.commandline.Main "$@" -checkLicence -n >/dev/null 2>/dev/null
```
Obviously, the license checking command tries connecting to the DB (respecting the _connectRetry_ property) and fails. However, both _stdout_ and _stderr_ are redirected to `/dev/null` which causes the warnings to vanish without any trace. The following output is visible when the std redirection is removed:
```
$ flyway
WARNING: Connection error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. (Caused by nodb: System error) Retrying in 1 sec...
WARNING: Connection error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. (Caused by nodb) Retrying in 2 sec...
WARNING: Connection error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. (Caused by nodb) Retrying in 4 sec...
WARNING: Connection error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. (Caused by nodb) Retrying in 8 sec...
WARNING: Connection error: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. (Caused by nodb: System error) Retrying in 16 sec...
...
```

###### What did you expect to see?
Some error message about the fact that the DB is not reachable. Retry messages.

###### What did you see instead?
Nothing, the scripts just runs "forever".

**Comment by Barry-RG** [comment]
Closing as we have a fix for this in the pipeline

However, it should also be noted that current flyway functionality in regards to connection retries, the delay between each retry increases by the power of 2. This means that even with log output, at 50 retires, you would get periods of hang "forever".

**Comment by dimw** [comment]
Hey @Barry-RG, glad hearing that the fix is already in the pipeline!

Just to clarify on the expectations: According to the [documentation of `connectRetries`](https://flywaydb.org/documentation/configuration/parameters/connectRetries), it is not obvious that the delay will be growing exponentially:
> After each failed attempt, Flyway will wait 1 second before attempting to connect again, up to the maximum number of times specified by connectRetries.

Besides, `50` is the value which is "suggested" by the example.

With the current implementation, when running Flyway for the 1st time using the bash script or the containerized version, what the user sees is just a "freezed" program which does not produce any output. This behaviour is confusing.
