### ISSUE TITLE
Flyway upgraded from 7.4.0 to 7.14.0 - failing for HSQLDB on "DROP FUNCTION XXX IF EXISTS" 

### ISSUE THREAD

**Issue by JaspreetSinghJassal** [flyway/flyway#3258]
###### Which version and edition of Flyway are you using?
Flyway community edition 7.14.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven-plugin

###### Which database are you using? (Type & version)
HSQLDB --> org.hsqldb:hsqldb:2.4.1

###### Which operating system are you using?
Windows and Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Updated flyway from 7.4.0 to 7.14.0

The following script which worked fine before, started failing:

``` 
drop function to_valid_date if exists;
create function to_valid_date(d varchar(8)) returns date
BEGIN atomic
  declare continue handler for sqlexception return null;
  return to_date(d, 'YYYYMMDD');
END;
```

###### What did you expect to see?
Successful migration

###### What did you see instead?

Seems like the `if exists` part is causing the problem as it works fine without - but I can of course not skip that part in my particular sql-migration

```
org.flywaydb.core.api.FlywayException: Unable to parse statement in V500_000__helper_functions.sql at line 1 col 1. 
See https://rd.gt/3ipi7Pm for more information: Incomplete statement at line 1 col 1: drop function to_valid_date if exists;
[ERROR] BEGIN atomic
[ERROR]   declare continue handler for sqlexception return null;
[ERROR]   return to_date(d, 'YYYYMMDD');
[ERROR] END;
[ERROR]
```

**Comment by JaspreetSinghJassal** [comment]
Any tentative ETA, @MikielAgutu?

**Comment by DoodleBobBuffPants** [comment]
Closing as we have a fix in our pipeline to be merged some time today
