### ISSUE TITLE
BigQuery procedures using 'WHILE DO' statement fail

### ISSUE THREAD

**Issue by ferrisnorth** [flyway/flyway#3260]
It appears as though 'WHILE' statements in procedures may not be parsed correctly.
  
  Current JRE version ...................... openjdk-14_windows-x64
  Current Flyway version ................... 7.14.0
  Platform ................................. GCP
  Database ................................. BigQuery
  Required Drivers ......................... GoogleBigQueryJDBC42.jar
  Other JDBC Stuff ......................... SimbaJDBCDriverforGoogleBigQuery42_1.2.18.1022.zip

**SQL Migration Text :**
"
CREATE OR REPLACE PROCEDURE tst.tst_proc_while()
    BEGIN
        DECLARE _i INT64 DEFAULT 0;
        DECLARE _iterTo INT64 DEFAULT 3;
        WHILE _i < _iterTo DO
            SET _i = _i + 1;
        END WHILE;
    END;
"

**ERROR :** 
"
...
Aug. 23, 2021 3:53:20 P.M. org.flywaydb.core.internal.jdbc.PlainExecutionTemplate error
SEVERE: Failed to execute operation in non-transactional context. Please restore backups and roll back database and code!
Aug. 23, 2021 3:53:20 P.M. org.flywaydb.commandline.Main error
SEVERE: Migration R__01_00_tst_proc_while.sql failed
--------------------------------------------
SQL State  : HY000
Error Code : 100032
Message    : [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Expected ";" but got end of script at [9:18]  ...
... Caused by: Migration R__01_00_tst_proc_while.sql failed
--------------------------------------------
SQL State  : HY000
Error Code : 100032
Message    : [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Expected ";" but got end of script at [9:18]
Location   : .\repeatable\R__01_00_tst_proc_while.sql (repeatable\R__01_00_tst_proc_while.sql)
Line       : 2
Statement  : CREATE OR REPLACE PROCEDURE tst.tst_proc_while()
    BEGIN
        DECLARE _i INT64 DEFAULT 0;
        DECLARE _iterTo INT64 DEFAULT 3;
        WHILE _i < _iterTo DO
            SET _i = _i + 1;
        END WHILE

Caused by: java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Expected ";" but got end of script at [9:18]
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Expected ";" but got end of script at [9:18]   
"

**Comment by DoodleBobBuffPants** [comment]
Closing as we have a fix for this in the pipeline
