### ISSUE TITLE
Environment Variables PLACEHOLDER Not working in MacOS

### ISSUE THREAD

**Issue by KarthikRajashekaran** [flyway/flyway#3262]
###### Which version and edition of Flyway are you using?
flyway-7.14.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Snowflake

###### Which operating system are you using?
Mac OS BigSur

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Have downloaded the flyway version flyway-7.14.0 command-line tar file in MAC

Unable to read the value from the FLYWAY_PLACEHOLDERS_RETSCHEMA, tried with both $ and @

I have given in the  shell script as below

```
export FLYWAY_PLACEHOLDERS_RETSCHEMA=DEV_RET
/path/flyway/flyway-7.14.0/flyway migrate -configFiles=config/flyway_dev.conf -password='****'
```
The V1.0.0__init.sql file is as below

```
CREATE SCHEMA IF NOT EXISTS @{RETSSCHEMA};
USE SCHEMA @{RETSCHEMA};
```
But it threw an error
```

Successfully validated 51 migrations (execution time 00:19.616s)
Current version of schema "DEV_RET": << Empty Schema >>
Migrating schema "DEV_RET" to version "1.0.0 - init"
ERROR: Migration of schema "DEV_RET" to version "1.0.0 - init" failed! Please restore backups and roll back database and code!
ERROR: Migration V1.0.0__init.sql failed
---------------------------------
SQL State  : 42000
Error Code : 1003
Message    : SQL compilation error:
syntax error line 1 at position 28 unexpected '@{RETSCHEMA}'.
Location   : sql/flyway/versions/V1.0.0__init.sql (/Users/work/sql/flyway/versions/V1.0.0__init.sql)
Line       : 1
Statement  : CREATE SCHEMA IF NOT EXISTS @{RETSCHEMA}

```
###### What did you expect to see?
Except to see value for variable @{RETSCHEMA}

###### What did you see instead?
No value and failed

**Comment by KarthikRajashekaran** [comment]
Any tentative time on this bug ?As We are in critical deployment

**Comment by MikielAgutu** [comment]
We're looking into it. Has it worked in previous versions of Flyway?

**Comment by madninjaskillz** [comment]
I notice that in your v1.0.0__init.sql there is an inconsistency in the spelling of the env var:

```CREATE SCHEMA IF NOT EXISTS @{RETSSCHEMA};
USE SCHEMA @{RETSCHEMA};```

`RETSSCHEMA` vs `RETSCHEMA`

Can you please confirm if this is just a fault in the report above and if not, is intentional?

**Comment by madninjaskillz** [comment]
I have been unable reproduce this issue; that said, some differences with my script:

* as I do not have your config, I have used the default placeholder notation in the sql script: `SET SCHEMA ${RETSCHEMA}
* on the assumption that `RETSSCHEMA` is a typo, I have replaced it with `RETSCHEMA`

If you have changed the placeholder config and you expect @ to work in place of $ I would appreciate a (redacted where sensible) copy of said config.
