### ISSUE TITLE
Password not redacted in debug output if migration fails

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#3263]
###### Which version and edition of Flyway are you using?

7.3.1 (nb: reported by Tony Davis)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

CLI

###### Which database are you using? (Type & version)

MariaDB, latest (though not relevant)

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Running a migration with -X debug output on, if the migration succeeds then the password is redacted in the debug output. However, if the migration fails (due to bad config, for example) it is displayed.

###### What did you expect to see?

Password always redacted

**Comment by DoodleBobBuffPants** [comment]
Could you provide a reproduction?

**Comment by juliahayward** [comment]
Actually, this case is invalid - the password was in the config file as `-password=OpenSesame` so Flyway didn't recognise what it actually was.
