### ISSUE TITLE
Flyway repair command repeatedly fixes the repeatable migration rows in the FLYWAY_SCHEMA_HISTORY table (flyway 7.9.1.)

### ISSUE THREAD

**Issue by DanDau** [flyway/flyway#3264]
###### Which version and edition of Flyway are you using?
Version 7.9.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This bug was fixed in 6.3.0 however, we still experience it in 7.9.1.
URL to previous issue: https://github.com/flyway/flyway/issues/2821 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Snowflake 5.31.4

###### Which operating system are you using?
Windows 10 Enterprise

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
run flyway repair command

###### What did you expect to see?
After run the Flyway migration successfully, the Flyway repair command should not repair anything.

###### What did you see instead?
The Flyway repair command repeatedly repairs the rows in the FLYWAY_SCHEMA_HISTORY table that have NULL value in ‘Version’ column; since the repeatable migration scripts don’t have version, the version column is always NULL, which will make the "repair" command always repair the repeatable migration script rows in each run.

**Comment by madninjaskillz** [comment]
We are currently unable to reproduce this issue (in 7.9.1 or above) so would require further details to proceed.
If you can supply us with a minimal repro case, it would be appreciated (preferably an example repeatable migration that suffers from the issue)

**Comment by DanDau** [comment]
Sure. Will this be sufficient? @madninjaskillz 

**Example**

[Pipeline] sh (hide)
+ set +x
WARNING: You are on an older version of Flyway. Please download latest at https://www.flywaydb.org/download/community
Flyway Community Edition 7.9.1 by Redgate
Database: jdbc:snowflake://XXXXXX/ (Snowflake 5.31)
QUOTED_IDENTIFIERS_IGNORE_CASE option is false
Repair of failed migration in Schema History table "UTILITY"."flyway_schema_history" not necessary. No failed migration detected.
Repairing Schema History table for description "MARKETING COVERAGE LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "MARKETING  COVERAGE LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "MARKETING POLICY LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "MARKETING POLICY LINE LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "200 MARKETING POLICY LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "500 MARKETING POLICY LINE LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "800 MARKETING  COVERAGE LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "800 MARKETING POLICY LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "900 MARKETING POLICY LINE LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "999 MARKETING COVERAGE LEVEL" (Marking as DELETED)  ...
Repairing Schema History table for description "EDW EDW POL PER X GROUP POLICY FULL" (Marking as DELETED)  ...
Repairing Schema History table for description "KDW EDW COVERABLE LOCATION FULL" (Marking as DELETED)  ...
Repairing Schema History table for description "KDW EDW POL PER X GROUP POLICY FULL" (Marking as DELETED)  ...
Repairing Schema History table for description "KDW EDW POL PER X PRODUCER FULL" (Marking as DELETED)  ...
Repairing Schema History table for description "KDW EDW POLICY COVERAGE FULL" (Marking as DELETED)  ...
Repairing Schema History table for description "KDW EDW POLICY EVENT FULL" (Marking as DELETED)  ...
Repairing Schema History table for description "KDW EDW POLICY FULL" (Marking as DELETED)  ...
Successfully repaired schema history table "UTILITY"."flyway_schema_history" (execution time 00:29.296s).
Please ensure the previous contents of the deleted migrations are removed from the database, or moved into an existing migration.


**Example of migration R__KDW_EDW_POLICY_FULL.sql being repaired:**
CREATE OR REPLACE VIEW KDW.EDW_POLICY_FULL comment = '2021-05-25 DAD: Oprettet' AS
SELECT
POLICY_SK,
POLICY_RK,
VALID_FROM_DTTM,
CASE WHEN VALID_TO_DTTM <= '5999-01-01' THEN DATEADD(NANOSECOND, 1, VALID_TO_DTTM ) ELSE '5999-01-01' END AS VALID_TO_DTTM,
POLICY_ID,
POLICY_NO,
POLICY_FIRST_EFFECTIVE_FROM_DTTM,
PAYMENT_MODE_CD,
PAYMENT_METHOD_CD,
FIRST_POLICY_OFFER_NO,
POLICY_PERIODS_CNT,
PAYOR_CD,
POLICY_NM,
ISSUE_BRANCH_CD,
CHANGE_USER_RK,
CAST(CHANGE_USER_ID AS VARCHAR(50)) AS CHANGE_USER_ID,
CHANGE_USER_CD,
CHANGE_DTTM,
CREATE_USER_RK,
CAST(CREATE_USER_ID AS VARCHAR(50)) AS CREATE_USER_ID,
CREATE_USER_CD,
CREATE_DTTM,
MTG_JOB_SK,
SOURCE_SYSTEM_CD,
CREATE_USER_INITIAL,
CHANGE_USER_INITIAL,
FLOW_HISTORY_ID
FROM
	**${dbEDWName}."POLICY".POLICY_FULL;**

**Comment by madninjaskillz** [comment]
From this log it looks like Flyway is failing to find the local versions of the scripts that are within the schema history table. Specifying the [locations](https://flywaydb.org/documentation/configuration/parameters/locations) parameter to point to where they are on disk should resolve this issue.
