### ISSUE TITLE
BigQuery ADC (Application Default Credentials) with Simba JDBC

### ISSUE THREAD

**Issue by ferrisnorth** [flyway/flyway#3265]
It appears as though Flyway is only supporting OauthType=0? When executing Cloud Deploy on GCP, storing or even saving the key.json on disk is not the ideal solution. It would be great to be able to just use the existing environment variables to authenticate the connection.

ERROR:
FLYWAY INFO PRISM API :
Aug. 27, 2021 12:40:15 P.M. org.flywaydb.commandline.Main error
SEVERE: Invalid argument: jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=MyProject;

EXPECTED BEHAVIOUR:
As defined in on page 17 of the Simba doc this URL should accept 'ADC' to connect to BQ jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=MyProject;

<https://simba.wpengine.com/products/BigQuery/doc/Simba_BigQuery_JDBC_InstallGuide.pdf> (page 17)

**Comment by DoodleBobBuffPants** [comment]
Could you share the full error output? By setting `OAuthType` to `3`, the driver should just pick up the environment variables

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
