### ISSUE TITLE
Fix vitess regression

### ISSUE THREAD

**Issue by spadger** [flyway/flyway#3269]
Vitess is `thing` that sits in front of mysql, which allows for clustering and sharding of data.  Unfortunately, it parses some queries and is unable to parse one of flyway's startup queries due to the (technically valid) nesting

```
SELECT (SELECT 1 FROM information_schema.schemata WHERE schema_name=? LIMIT 1)
```

It looks like this was introduced in 20/09/2018 in SHA [bc2263e](https://github.com/flyway/flyway/commit/bc2263eb5fd04cb03b2da64d540e95c523e2c93f) as part of issue #2123 

###### Which version and edition of Flyway are you using?
7.14.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Vitess 11 [docker image](https://hub.docker.com/r/vitess/vttestserver).  It is updated multiple times per day, but the docker image broke on Mon 30 Aug 2021

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Launching a db migration in JVM

```
Flyway
    .configure()
    .dataSource(dataSources.getValue(datasourceName))
    .locations("classpath:db.migration")
    .load()
    .migrate()
```

###### What did you expect to see?
The app to load up

###### What did you see instead?
Vitess rejects the query with message
```
"select (select :vtg1 from information_schema.schemata where schema_name = :__vtschemaname limit :vtg1) from dual", BindVars: {#maxLimit: "type:INT64 value:\"10001\""vtg1: "type:INT64 value:\"1\""vtg2: "type:VARBINARY value:\"SomeDatabase\""}
```

**Comment by DoodleBobBuffPants** [comment]
We likely won't make any changes unless there is further interest. Instead the way the query is parsed should be fixed

**Comment by spadger** [comment]
I have the fix here https://github.com/spadger/flyway/commit/8897fd911be53993c41ccdcf4db29ef665a4545c

**Comment by DoodleBobBuffPants** [comment]
While making the change might work around this issue, it's not a permanent solution and the issue should be fixed in Vitess

**Comment by DoodleBobBuffPants** [comment]
However, we will run the change through our tests in order to unblock people in the mean time

**Comment by spadger** [comment]
Thank you.  We have raised an [issue](https://github.com/vitessio/vitess/issues/8729) with the Vitess team in the mean time but agreed, this is not ideal
