### ISSUE TITLE
Repeatable Script Execution Order

### ISSUE THREAD

**Issue by KarthikRajashekaran** [flyway/flyway#3271]
###### Which version and edition of Flyway are you using?

flyway-7.14.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Snowflake

###### Which operating system are you using?
macOS and Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Requirement: Need Flyway to execute R scripts in sequence

Issue: As we are migrating all the functions and procedures to new DB, Some of the function internally calls another function as the example below

```
CREATE OR REPLACE FUNCTION ABC_SCHEMA.FN_ABC() RETURNS TABLE (
       COLUMNS
    ) LANGUAGE SQL AS '
      SELECT ID from TABLE(ABC_SCHEMA.FN_ID()) AS c
```

So here both the functions FN_ABC and FN_ID are new functions that need to be created in the new DB

So the issue is when executed via Flyway it creates FN_ABC as First and it fails as the FN_ID doesn't exist

How I can resolve this issue so I can get the function FN_ID created first and then FN_ABC

###### What did you see instead?

Not Executed in Order

**Comment by DoodleBobBuffPants** [comment]
You can use [`cherryPick`](https://flywaydb.org/documentation/configuration/parameters/cherryPick) to specify the repeatable migrations in the order you would like them to be executed
