### ISSUE TITLE
Is it possible to add a free extra column in FLYWAY_SCHEMA_TABLE so we can add some comment, commit number, ...

### ISSUE THREAD

**Issue by delobel** [flyway/flyway#3274]
It's important to track the commit number off each executed script or other uses case...
So if you add an extra column in the FW table, and an extra option on the CLI to fill the field it could be great :-)

###### Which version and edition of Flyway are you using?
7.5.0 community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
PostGreSQL and Oracle

###### Which operating system are you using?
Linux

**Comment by DoodleBobBuffPants** [comment]
As this is a big and breaking change, we likely won't be implementing this unless there is further interest, so closing for now
