### ISSUE TITLE
Missing version output @latest

### ISSUE THREAD

**Issue by iilei** [flyway/flyway#3276]
[latest; flyway-7.15.0](https://github.com/flyway/flyway/releases/tag/flyway-7.15.0)

Command line / Docker

database : *n/a*

OS: *linux/amd64* [docker hub deep link](https://hub.docker.com/layers/flyway/flyway/7.15.0/images/sha256-aeb735b0fc384e10247faac2808792bc358856ed92c1dffdd28b58a03fc1ce48?context=explore)

```shell
export SHA=@sha256:aeb735b0fc384e10247faac2808792bc358856ed92c1dffdd28b58a03fc1ce48
docker run --entrypoint /usr/bin/env flyway/flyway:7.15.0$SHA  flyway -v
# same situation:
# docker run --entrypoint /usr/bin/env flyway/flyway:7.15.0$SHA  flyway --version
``` 

Expected to see some kind of output among the lines of `Flyway Community Edition 7.15.0 by Redgate`, instead saw no output at all (neither stdout nor stderr) – in other words a blank string and zero exit code 

#### Additional Info:

When I run the following to verify the correct utilisation of docker cli: 

```shell
docker run --entrypoint /usr/bin/env flyway/flyway:7.14.1@sha256:cb29805338c3cd594ba15db7f3bd2f6590ae43e068770a62c95ad9c638713387  flyway -v
```
It yields as expected: `Flyway Community Edition 7.14.1 by Redgate`

**Comment by DoodleBobBuffPants** [comment]
Fixed by https://github.com/flyway/flyway/commit/86c285e5a707e19700f1c53841af02397323e844
