### ISSUE TITLE
The flyway default placeholders really ought to be available for script-based callbacks.

### ISSUE THREAD

**Issue by Phil-Factor** [flyway/flyway#3277]
###### Which version and edition of Flyway are you using?
7.15.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
SQL Server, MariaDB, PostgreSQL and sqlite

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Creating PowerShell and DOS Batch callback scripts to run with TEAMS

###### What did you expect to see?
the default placeholders as environment variables, just like the SQL and Java scripts. 

###### What did you see instead?
just the user-defined placeholders, FLYWAY_USER and FLYWAY_URL, but no default placeholders.
The problem is in determining the name of the file that caused the callback, and in working out where the flyway schema table is. To find out the current version number, you either need it passed to you by Flyway, or you need to be able to read the flyway_schema_history table which may be renamed or in a different schema.

**Comment by DoodleBobBuffPants** [comment]
Closing as we have fixed this and it will be available in the next release

Do note that the colon in the default placeholders must be replaced with an underscore when accessed through scripts
