### ISSUE TITLE
Performance issues with flyway 7.9 and above

### ISSUE THREAD

**Issue by tychokamphuis-accommodatiehuur** [flyway/flyway#3278]
###### Which version and edition of Flyway are you using?
7.15.0 Community version

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes (Reproduced in every version after 7.9.0, even 8.0.0-beta)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MySQL 8.0.26

###### Which operating system are you using?
Windows (Hyper-V docker)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We upgraded to 7.15.0 from 5.2.4 and ran migrations on our production server. We noticed a migration time of 30 minutes in 7.15.0 compared to the 16 minutes it took in 5.2.4.

When running the script below, we see that running migrations for **5** dbs, the time doubles.
Running the script below, it takes 4 seconds in 5.2.4 to iterate through 5 db's to see that no migration is necessary.
Running the same script in 7.9 and above results in a time of minimal 9 seconds.

```
DATABASES="
test1
test2
test3
test4
test5
"

EXCLUDED_DBS="
Database
default
sys
"

echo "All dbs"
SECONDS=0
for singledatabase in $DATABASES; do
  # filter dbs
  match=0
  for excl in $EXCLUDED_DBS; do
    if [[ "$excl" == "$singledatabase" ]]; then
      match=1
      break
    fi
  done

  if [[ $match == 0 ]]; then
    echo "DB: $singledatabase"
    if [[ $singledatabase ]]; then
      (flyway -user="root" -url="jdbc:mysql://localhost:3307/${singledatabase}" -locations="filesystem:./_documents/flyway-sql/" migrate) >/dev/null
      # increment counter
      ((counter = counter + 1))
    fi
  fi
done

wait

duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed for db."
echo "Done"

```

###### What did you expect to see?
Equal or better results than 4 seconds.

###### What did you see instead?
9 seconds.

**Comment by madninjaskillz** [comment]
It is a possibility that the update check is adding some latency, especially if you are airgapped or behind a proxy. Could you please try adding the flag `-skipCheckForUpdate` to the Flyway call to see if this improves performance.

**Comment by tychokamphuis-accommodatiehuur** [comment]
First of all, thank you for responding @madninjaskillz.
Unfortunately, this did not improve the performance. It is particularly slower within making the connection to the database, as the line "Database: jdbc:mysql://localhost:3307/crs_test5 (MySQL 8.0)" is coming up later than before. (Measured visually).

I'm unsure if this will be of any importance, but the console is also showing "<-[90m"
![image](https://user-images.githubusercontent.com/40304728/133285997-178da88c-fa78-43ca-81e9-85cea29ed38e.png)

**Comment by madninjaskillz** [comment]
Newer drivers and Flyway doing more in 7.x than it did in 5.0 will mean that it is entirely possible for connections to be fractionally slower. That said, with the current licensing checks, there will be a double connection that can be avoided, simply by specifying the edition of Flyway you wish to run, `-community` for community edition or `-teams` for teams edition. Doing this will skip the auto detection and should half the time spent. 

Obviously, in a real world example, the connection is only made once per migration and the vast majority of the time spent working is unaffected by this start up latency.

**Comment by tychokamphuis-accommodatiehuur** [comment]
@madninjaskillz I'll take a look into the community flag.
About the real world example, we actually make 386 connections, as we migrate 386 databases seperately.

First we list all the databases by using "show databases" query, then we loop through each database and do the flyway migrate command.

Perhaps you have a better strategy to migrate multiple databases?
