### ISSUE TITLE
schema name has "inpact" on `migrate -> clean -> migrate` scenario

### ISSUE THREAD

**Issue by xoac** [flyway/flyway#3281]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.14.0 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I was tried to reproduce on last docker version (with latest tag - 7.15.0)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
PostgreSQL 12.4 (docker image `timescale/timescaledb:1.7.4-pg12`)

###### Which operating system are you using?
Linux x86

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I tried to  create schema on fresh instance and domain in this schema. I made migration, then clean and, then migration again (with both error and working example). In first case I got error

**Minimal error example (on new database):**
```sql
CREATE SCHEMA IF NOT EXISTS bug_bug;

CREATE DOMAIN bug_bug.slot AS INTEGER; 
```

migrate -> ok
clean -> ok (`bug_bug.slot` still in schema)
migrate -> error
```
Flyway Community Edition 7.14.0 by Redgate
Database: jdbc:postgresql://127.0.0.1:5432/bug (PostgreSQL 12.4)
Successfully validated 1 migration (execution time 00:00.018s)
Creating Schema History table "public"."flyway_schema_history" ...
Current version of schema "public": << Empty Schema >>
Migrating schema "public" to version "1 - bug"
WARNING: DB: schema "bug_bug" already exists, skipping (SQL State: 42P06 - Error Code: 0)
ERROR: Migration of schema "public" to version "1 - bug" failed! Changes successfully rolled back.
ERROR: Migration V1__bug.sql failed
----------------------------
SQL State  : 42710
Error Code : 0
Message    : ERROR: type "slot" already exists
Location   : /home/sr/projects/tmp/postgresql-domain-clean-bug/V1__bug.sql (/home/sr/projects/tmp/postgresql-domain-clean-bug/V1__bug.sql)
Line       : 3
Statement  : CREATE DOMAIN bug_bug.slot AS INTEGER

Caused by: Migration V1__bug.sql failed
----------------------------
SQL State  : 42710
Error Code : 0
Message    : ERROR: type "slot" already exists
Location   : /home/sr/projects/tmp/postgresql-domain-clean-bug/V1__bug.sql (/home/sr/projects/tmp/postgresql-domain-clean-bug/V1__bug.sql)
Line       : 3
Statement  : CREATE DOMAIN bug_bug.slot AS INTEGER

Caused by: org.postgresql.util.PSQLException: ERROR: type "slot" already exists
```

- - - -

**Minimal working example (on new database):**
```sql
CREATE SCHEMA IF NOT EXISTS bug;

CREATE DOMAIN bug.slot AS INTEGER; 
```
migrate -> ok
clean -> ok (`bug.slot` domain was removed from schema)
migrate -> ok

**It is worth mention that the user name is `bug` and the database is also called `bug` (with `bug` user as owner).**

###### What did you expect to see?
expected to remove `bug_bug.slot` exactly the same in `bug.slot`. 

###### What did you see instead?
`bug_bug.slot` persist but should be removed in clean

**Comment by Barry-RG** [comment]
Flyway does not remove any schema details, such as domain, which is not created by itself. This is expected Flyway behavior. 

Your example with the bug schema is due to a PostgreSQL quick when a schema and a user share a name when no default schema is set. This should not be viewed as intended usage.
