### ISSUE TITLE
How to use flyway without datasource / database connection?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [flyway/flyway#3283]
I am unsure if Flyway can be used **without any data source (.dataSource())**.

The problem is that I am using HakariCP pooling manager for database connection & HSQLdb database on Android App.

At startup Flyway make it connection to embedded HSQLdb database first & It's close it's connection. Then HakariCP makes it's connection. Hence times double for both connections sources, and if database is large then it much affects performance at startup of App.

Somehow I want that Flyway do not make any connection to database directly rather get connection form other sources e.g. HakariCP. Is it somehow possible???

**Comment by DoodleBobBuffPants** [comment]
You will need to create a Hikari DataSource and provide that to Flyway so that the same underlying connection pool can be used. A tutorial on doing this can be found [here](https://www.baeldung.com/hikaricp)
