### ISSUE TITLE
DB2 connection error

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#3285]
https://stackoverflow.com/questions/69292371/getting-connection-error-from-flyway-command-line-with-db2-drivers

There's an error in the way we handle JDBC connections with DB2 when `retrieveMessagesFromServerOnGetMessage=true` is set in the URL; see the above post for full details.

**Comment by DoodleBobBuffPants** [comment]
This seems to be a limitation of the DB2 JDBC driver

It errors when the URL contains properties and when we pass properties to the driver directly at the same time, even when the two sets of properties are distinct.
It also errors when the set of properties we pass to the driver is null/empty.

The correct solution for the time being is to pass all properties through the `jdbcProperties` parameter
