### ISSUE TITLE
Current version of Azure SQL Database is triggering 'unsupported' errors because it's > 5 years old.

### ISSUE THREAD

**Issue by jitterbox** [flyway/flyway#3286]
###### Which version and edition of Flyway are you using?
6.3.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Azure SQL Database

###### Which operating system are you using?
Windows Server

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Executed any migration.

###### What did you expect to see?
Successful migration.

###### What did you see instead?
`ERROR: Flyway Teams Edition or SQL Server upgrade required: SQL Server Azure v12 is no longer supported by Flyway Community Edition, but still supported by Flyway Teams Edition.`

V12 is the _current_ version of Azure SQL Database, despite it being deployed in 2015. If your error logic is checking only for the age of a database version being targeted, a condition needs to be added to confirm it's not also the current version.

If this is resolved in a newer version, can you confirm which one?

**Comment by DoodleBobBuffPants** [comment]
This was fixed in 8.0.0-beta1

**Comment by jitterbox** [comment]
So to be clear, per the v8.0.0-beta1 release notes, has this been changed from an error to a deprecation warning?

**Comment by DoodleBobBuffPants** [comment]
In this case, it should be supported in Community

**Comment by jitterbox** [comment]
![2021-09-23_16-42-17](https://user-images.githubusercontent.com/6708273/134581397-0fe8fbf6-61bc-4956-a91e-7295016d446e.png)

Should this not be happening then, or is there another factor here?

**Comment by DoodleBobBuffPants** [comment]
Could you try 7.15.0?

**Comment by jitterbox** [comment]
Seems like it works with 7.15.0.

![2021-09-23_17-34-44](https://user-images.githubusercontent.com/6708273/134588031-1b072d74-22de-4e54-aed9-a7820200a6cc.png)
0
