### ISSUE TITLE
Log4j2 cannot be applied in OSGi environment

### ISSUE THREAD

**Issue by AlexIvchenko** [flyway/flyway#3288]
###### Which version and edition of Flyway are you using?
7.15.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
PostgreSQL 9.4

###### Which operating system are you using?
CentOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I run Flyway in OSGi environment using the following:
```java
Flyway flyway = Flyway.configure()
    .configuration(properties)
    .loggers("log4j2")
    .dataSource(dataSource)
    .load();
```

###### What did you expect to see?
Flyway logs in log file.

###### What did you see instead?
Error in log:
```
java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager not found by org.flywaydb.core
```

**Comment by AlexIvchenko** [comment]
I assume that we problem happens due to incorrect import package version in pom.xml
```
org.apache.commons.logging;version="[1.1,2)";resolution:=optional
```
Log4j2 has 2.x versions:
```
<version.log4net2>2.14.1</version.log4net2>
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api</artifactId>
    <version>${version.log4net2}</version>
    <optional>true</optional>
</dependency>
```
I assume that import should be:
```
org.apache.commons.logging;version="[2.14,3)";resolution:=optional
```

**Comment by Barry-RG** [comment]
`org.apache.commons.logging;version="[1.1,2)";resolution:=optional` is a bundled version of Apache Commons Logging, not Log4j2 by Apache. 
We may bundle Log4J2 in a future release, however in the mean while have you included log4j2-api and core as dependencies in your application?

**Comment by Barry-RG** [comment]
Sadly Log4J2 is not able to be bundled in to Flyway for usage due to issues with OSGI. Please add Log4J2 as a dependency in your Java application and add it to your classpath.

**Comment by AlexIvchenko** [comment]
@Barry-RG Yes, I have mistaken. The above imports is for logj4, not for log4j2. log4j2 packages are not imported.

I have log4j2-api and log4j2-core in classpath and I also have related packages imported in MANIFEST.mf:
```
org.apache.logging.log4j;version="[2.6,3)",
org.apache.logging.log4j.util;version="[2.6,3)"
```
This allows me to use log4j2 from my OSGi bundles. Flyway bundle doesn't have such imports. Because of that OSGi classloader cannot find log4j2 classes for Flyway bundle.

I built Flyway locally with the following log4j2 imports in core module:
```
org.apache.logging.log4j;version="[2.6,3)";resolution:=optional,
org.apache.logging.log4j.util;version="[2.6,3)";resolution:=optional,
```
 It works. I see logs in my log4j2 log file.

**Comment by can4ec** [comment]
I have faced with same issue.
@Barry-RG should I raise another issue since this had been closed?

**Comment by DoodleBobBuffPants** [comment]
Closed by https://github.com/flyway/flyway/commit/7d8d53697614f76f8e6716d9ec743eee8bde56c4
