### ISSUE TITLE
There seems to be an error on the site.

### ISSUE THREAD

**Issue by ShkolnikGithub** [flyway/flyway#3293]
![IMG_20211004_165358_331.jpg](https://user-images.githubusercontent.com/67905577/135864774-1fc95bb8-6de2-4d52-8634-20ad3d7562dc.jpg)
When I prescribe:
plugins {
    id "org.flywaydb.flyway.enterprise" version "8.0.0-beta3"
}
, I get the following error:
"* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.flywaydb.flyway.enterprise', version: '8.0.0-beta3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.flywaydb.flyway.enterprise:org.flywaydb.flyway.enterprise.gradle.plugin:8.0.0-beta3')
  Searched in the following repositories:
    Gradle Central Plugin Repository".

If corrected to:
plugins {
    id "org.flywaydb.enterprise.flyway" version "8.0.0-beta3"
}

Then there is no mistake. The word "enterprise" in your example is indicated in the wrong place.

**Comment by DoodleBobBuffPants** [comment]
Thanks for letting us know. This should be fixed now
