### ISSUE TITLE
Flyway gradle plugin incompatible with Gradle 7+

### ISSUE THREAD

**Issue by Synesso** [flyway/flyway#3294]
###### Which version and edition of Flyway are you using?

  id("org.flywaydb.flyway") version "8.0.0-beta3"

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using? (Type & version)

MySQL v5.7

###### Which operating system are you using?

MacOS 11.6

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Upgraded Gradle from v6.8.2 to v7.2

Executed the `generateJooq` Gradle task, which was known to work prior to upgrading Gradle.

`./gradlew -p service generateJooq`

###### What did you expect to see?

New generated classes

###### What did you see instead?

Gradle error:

```
> Task :service:flywayMigrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':service:flywayMigrate'.
> Error occurred while executing flywayMigrate
  Configuration with name 'compile' not found.
```

Gradle removed the compile configuration from version 7.0 (I believe it may have been deprecated since Gradle 3.4)

**Comment by MikielAgutu** [comment]
I'm not seeing where `compile` is used in the Gradle plugin code. We do have some defaults for older versions:
- [From the docs](https://flywaydb.org/documentation/usage/gradle/#extending-the-default-classpath)
- [And the actual code](https://github.com/flyway/flyway/blob/master/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L54-L56)

We also read tasks from the `configurations` Gradle plugin variable, or env var. Is it possible that you've got `compile` set there?

**Comment by Synesso** [comment]
My bad. I changed the plugin version but didn't also change the classpath. Latest release is good. TY

**Comment by Synesso** [comment]
info on fix for anyone stumbling here...

```
 buildscript {
   dependencies {
-    classpath("gradle.plugin.com.boxfuse.client:flyway-release:5.0.2")
+    classpath("org.flywaydb:flyway-gradle-plugin:7.15.0")
```

```
plugins {
-  id("org.flywaydb.flyway") version "5.2.4"
+  id("org.flywaydb.flyway") version "7.15.0"
```
