### ISSUE TITLE
Altering `schemas` doesn't re-run the "create schema if required" check

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#3296]
https://stackoverflow.com/questions/69460752/flyway-doesnt-create-schema-after-initial-schemas-creations

To reproduce: run a migration on an empty database with `flyway.schemas=foo,bar`. Two schemas are created. Then migrate again with `flyway.schemas=foo,bar,baz`. Schema `baz` is **not** created.

This isn't _necessarily_ the wrong behaviour, but we should consider whether it's desirable and review the documentation to make sure it's clear what Flyway does.

**Comment by DanHartman** [comment]
I would like to vote for this issue.  I've run into the exact same scenario as described in the `To reproduce` section above.

From my perspective, it appears that flyway is unable to increase the number of schemas it manages in a database that persists.  My expectation was that appending to `FLYWAY_SCHEMAS` would create the new schema in any circumstance

**Comment by DoodleBobBuffPants** [comment]
This should now be fixed in 9.2.2
