### ISSUE TITLE
Flyway V8 Community Edition and `ignoreMissingMigrations`

### ISSUE THREAD

**Issue by psttf** [flyway/flyway#3297]
Hello and thank you for this wonderful project! Sorry for not following the issue template, but my question is pretty short.

The `ignoreMissingMigrations` configuration is deprecated in 8.0.0 and will be removed in the next major version. It is recommended to switch to `ignoreMigrationPatterns`. But doing so results in runtime errors stating that `ignoreMigrationPatterns` config requires the Teams subscription! I would like to clarify if it is really planned that a paid subscription will soon be required just to have the ability to skip missing migrations?

This functionality is pretty basic and it is required in order to have an opportunity to quickly rollback application deployments (if migrations are backward-compatible).

**Comment by psttf** [comment]
> 
> 
> Hi,
> 
> Thanks for raising this issue! We plan on making parts of `ignoreMigrationPatterns` available in the Community Edition before removing the existing `ignore` parameters in order to retain compatibility

Thank you! That is really nice!

**Comment by johnou** [comment]
@DoodleBobBuffPants our DBA would like historic data of the applied migrations to our database, would you please reconsider marking ignoreMissingMigrations as deprecated?

**Comment by johnou** [comment]
my bad looks like we might be able to achieve this with ignoreMigrationPatterns afterall?

```
How can I validate specific migrations?
ignoreMigrationPatterns let’s you specify classes of migration type and migration status to ignore during validate
```

so retain the existing behaviour we should be able to set ignoreMigrationPatterns to `sql:missing`?

**Comment by DoodleBobBuffPants** [comment]
To retain the existing behaviour, the pattern would be `*:missing`

**Comment by johnou** [comment]
@DoodleBobBuffPants will it also be applied to the repair command? I've been digging through the documentation but I haven't spotted a way to fix checksums without deleting all missing migrations.

**Comment by DoodleBobBuffPants** [comment]
It won't apply to `repair`

Is there any reason running `repair` to update checksums doesn't work?

**Comment by johnou** [comment]
it does however repair now invokes deleteMissingMigrations which I'd like to avoid, we've had a few situations where we'd have to correct a migration that has already been applied to test / staging environment but at the same time retain missing migrations in the history table.

**Comment by johnou** [comment]
@DoodleBobBuffPants quick question wrt the functionality of `*:missing`, after repair is run, the history rows for those files are marked DELETE, but if they are restored and repair is run again the migration is applied a second time.. shouldn't that be skipped if success for the row is 1?

**Comment by DoodleBobBuffPants** [comment]
@johnou 
When migrations are marked `DELETE` their success value is kept the same, however we treat deleted migrations as if the change they were making was also removed from the DB, which is why they appear as `PENDING` when they are restored, and is why they are applied again

**Comment by tomtranc** [comment]
Hi @cleliofs I had the same issue too with Flyway Community Edition.  Apparently Flyway Teams Edition is needed to ignore specific migration types like `repeatable` or `versioned`.  

![image](https://github.com/flyway/flyway/assets/9016600/00e011c8-da59-4be6-a320-c2a5ea1721c5)

Only wildcard `*` is supported in Flyway CE.  

So doing the following should work for your case: `-ignoreMigrationPatterns=*:missing`.  
Or for spring boot: `spring.flyway.ignore-migration-patterns=*:missing`
