### ISSUE TITLE
Schema-name in jdbc_uri not being used with Snowflake

### ISSUE THREAD

**Issue by srjonemed** [flyway/flyway#3308]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.4.4 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Snowflake 5.38.0

###### Which operating system are you using?
Amazon Linux within Docker

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Using commands like below to run the migraitons - 
`/usr/local/flyway//flyway -url="jdbc:snowflake://xxx.snowflakecomputing.com/?private_key_file=/opt/airflow/keys/rsa_key_etl_user_user.pem&db=dev_db&warehouse=etl_dev_wh&user=etl_user_user&schema=final_schema&role=etl_user_user_role&authenticator=snowflake_jwt" -configFiles=/tmp/tmpad0bbtt2 -locations=filesystem:/opt/airflow/utils/migrations/sql/final_schema/ migrate

###### What did you expect to see?

The jdbc_url has `schema=final_schema`. However the migrate doesn't seem to be recognizing this param. Instead the individual sql files have to have the `USE final_schema;` stmt for it to take effect.

###### What did you see instead?
-

**Comment by srjonemed** [comment]
apologies for the late response. 
Yes, i have the flyway.schemas populated with two schema names:
flyway.schemas=protected_schema,{{ SCHEMA_NAME }}
The first one is `protected_schema` - this is where the flyway migration tables are created and managed. Second one is a template field populated by a wrapper tool which is the intended target schema for migration. The value of {{ SCHEM_NAME }} is determined by the wrapper tool at runtime and this same value is also used in the jdbc_uri as well.

**Comment by srjonemed** [comment]
For instance the config looks like:
`flyway.schemas=protected_schema,final_schema`
However the connection seems to be happening on `protected_schema` even though the jdbc_uri is set with `schema=final_schema`

**Comment by Barry-RG** [comment]
@srjonemed it seems like you want to set a default schema for the migration tables and a second one for the migration script executions. This is not possible as flyway will take in the schema list as the default schema, in this case proteced_schema, as a default schema is not specified in its own config. This is overriding the jdbc_url property in your URL. 
The way round this is to add snowflakes use schema statement to your migration scripts or in a before each migrate call back.
https://docs.snowflake.com/en/sql-reference/sql/use-schema.html
