### ISSUE TITLE
Flyway cannot run on a newly created AWS RDS PostgreSQL

### ISSUE THREAD

**Issue by AdamZeng1** [flyway/flyway#3318]
###### Which version and edition of Flyway are you using?
7.12.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin.

###### Which database are you using? (Type & version)

PostgreSQL on Amazon RDS.
Engine version 12.

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

run Flyway migration when the application starts up. 

###### What did you expect to see?

Flyway migration finished successfully.

###### What did you see instead?

Caused by: org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "public" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table

There is a function called db_session_replication_role(text) created by Amazon RDS, which causes Flyway to regard the public schema as non-empty.

```
SELECT EXISTS (
SELECT c.oid FROM pg_catalog.pg_class c
                    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                    LEFT JOIN pg_catalog.pg_depend d ON d.objid = c.oid AND d.deptype = 'e'
                    WHERE  n.nspname = 'public' AND d.objid IS NULL AND c.relkind IN ('r', 'v', 'S', 't')
                  UNION ALL
                    SELECT t.oid FROM pg_catalog.pg_type t
                    JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
                    LEFT JOIN pg_catalog.pg_depend d ON d.objid = t.oid AND d.deptype = 'e'
                    WHERE n.nspname = 'public' AND d.objid IS NULL AND t.typcategory NOT IN ('A', 'C')
                  UNION ALL
                    SELECT p.oid FROM pg_catalog.pg_proc p
                    JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
                    LEFT JOIN pg_catalog.pg_depend d ON d.objid = p.oid AND d.deptype = 'e'
                    WHERE n.nspname = 'public' AND d.objid IS NULL
                )
```
![image](https://user-images.githubusercontent.com/31460118/139640188-1171c039-3647-4e39-bcef-f342ff9c5057.png)

**Comment by AdamZeng1** [comment]
Flyway Github issue: https://github.com/flyway/flyway/issues/3318

**Comment by angellaa** [comment]
If the schema is not completely empty, you need to run the `flyway baseline` command before running migrate. https://flywaydb.org/documentation/command/baseline

This will create the schema history table and later runs of migrate will work as expected.

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
