### ISSUE TITLE
Percona XtraDB 5.7 support is marked as available in the website(https://flywaydb.org/documentation/database/xtradb) but not supported by 8.0.2

### ISSUE THREAD

**Issue by retorres87** [flyway/flyway#3319]
###### Which version and edition of Flyway are you using?

8.0.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using? (Type & version)

Percona-XtraDB-Cluster-57-5.7.23-31.31.2.el7

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

```
> Task flywayMigrate FAILED
5 actionable tasks: 2 executed, 3 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task 'flywayMigrate'.
> Error occurred while executing flywayMigrate
  Flyway Teams Edition or MySQL upgrade required: MySQL 5.7 is no longer supported by Flyway Community Edition, but still supported by Flyway Teams Edition.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
```

###### What did you expect to see?

Since the documentation here says that it has support for percona 5.7 expected to see that the build was successful: https://flywaydb.org/documentation/database/xtradb

###### What did you see instead?
> Error occurred while executing flywayMigrate
  Flyway Teams Edition or MySQL upgrade required: MySQL 5.7 is no longer supported by Flyway Community Edition, but still supported by Flyway Teams Edition.

Please let me know if I am misunderstanding the support or if its a mistake in the website.

**Comment by angellaa** [comment]
Hi!

Starting from version 8 support for MySQL version 5.7 is only available in Flyway Teams according to our database support policy. https://flywaydb.org/documentation/database/mysql

You are right this is a mistake on our part, we haven't correctly updated the documentation page for Percona XtraDB. We apology for the confusion.

You can [request a trial license for Teams](https://flywaydb.org/download/teams) or downgrade to Flyway version 7.15 for the time being.
