### ISSUE TITLE
OutOfOrder migration detection options

### ISSUE THREAD

**Issue by winterspan** [flyway/flyway#3320]
Is there a mechanism for hooking into the out-of-order migration detection? instead of ignoring OoO migrations or executing them (with the outOfOrder=true flag) I'd like to have an exception thrown / halt the application at startup. Alternatively, I'd like to execute an arbitrary callback.

**Comment by angellaa** [comment]
I don't think we have a mechanism for hooking into that.

If `outOfOrder `is set to false (which is the default), Flyway will fail when running a `migrate`.

What's your need for the failure to happen at startup? Could you tell us more about your requirements?

**Comment by DoodleBobBuffPants** [comment]
For the time being you can use Java-based callbacks by extending `BaseCallback` and hooking into `beforeEachMigrate`

This gives you access to the `MigrationInfo` for the next migration. You can use the version from this compared against the current version of your DB to determine if a migration is being executed out of order

For now we will be closing until further interest

**Comment by winterspan** [comment]
Sorry, I had some issues with my Github account. 

I should have mentioned the project is still using Flyway 4.2.  As of that version, if OutOfOrder is disabled, and I introduce an out-of-order migration, it just seems to be ignored. No exceptions are thrown and the app starts up normally. 
(note: I have ValidateOnMigrate disabled, but as I understand it, that just compares the checksums of available/executed migrations)
 
I tried adding a **beforeEachMigrate** Java callback, but that doesn't seem to get called in the context of out-of-order migrations assuming OutOfOrder is disabled. It is only called for normal, in-order migrations, or out-of-order migrations when OutOfOrder is enabled.

Ultimately, the goal is just to detect out-of-order migrations being introduced while OutOfOrder mode is disabled and throw an exception.

**Comment by winterspan** [comment]
created new issue here so this one can remain closed:
https://github.com/flyway/flyway/issues/3353
