### ISSUE TITLE
Migrations executed after the application startup

### ISSUE THREAD

**Issue by a13a** [flyway/flyway#3326]
###### Which version and edition of Flyway are you using?
8.0.3

### Feature proposal

Very often it is necessary to populate the database with initial data, however in some cases it is better to populate the data using the existing ORM instead of SQL scripts, since the SQL scripts are database specific and the ORM has additional functionality which is hard to replicate in SQL scripts.

Flyway has very important features like 

- being able to be run in a cluster (so that if there are identical nodes only one node will execute the scripts) 
- remembering which scripts are ran and not running them again

Flyway has the possibility to execute Java migrations with logic, however those migrations obviously are executed before the ORM is initialized.

It would be nice if another type of migration would be added, that will be executed after the application finished the startup.
For example in Spring after the application finished startup it would be possible to execute a migration that would use injected dependencies and use the ORM to populate data in the database.

**Comment by MikielAgutu** [comment]
Can you give more detail as to how you'd expect this to work? For instance, how would Flyway know that your application has finished starting up?

**Comment by DoodleBobBuffPants** [comment]
This is an issue related to Spring running Flyway at startup

If you use the Flyway API directly, you can invoke it any point in your application's lifecycle
