### ISSUE TITLE
Ignore warnings for SQL*Plus `SET SQLBLANKLINES`

### ISSUE THREAD

**Issue by MikielAgutu** [flyway/flyway#3327]
(From a user report)

The [`SET SQLBLANKLINES`](https://www.oreilly.com/library/view/oracle-sqlplus-the/0596007469/re89.html) SQL*Plus option produces a warning in Flyway. The user has requested for this warning not to appear.

They want this as they like to develop their scripts in a 'real' SQL*Plus environment where this option is necessary, then copy those scripts directly into Flyway migrations.

Possible approaches:
- Support the `SET SQLBLANKLINES` option (questionable as Flyway already supports blank lines in statements, and allowing users to toggle this would be a bit crazy)
- Silently ignore this option (might confuse users who expect it to do something)
- Have an option to turn off all SQL*Plus warnings
- Have an option to ignore warnings for specific SQL*Plus commands

**Comment by madninjaskillz** [comment]
Warning will be replaced with a debug message.
