### ISSUE TITLE
When using ignoreMigrationPatterns, future migrations are always ignored, unless deprecated functionality is used.

### ISSUE THREAD

**Issue by MichalHB** [flyway/flyway#3338]
###### Which version and edition of Flyway are you using?
8.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle 7.3

###### Which database are you using? (Type & version)
PostgreSQL 13

###### Which operating system are you using?
Ubuntu 20.04

###### What did you do?
To avoid using deprecated functionality, we are replacing ignoreFutureMigrations and ignorePendingMigrations calls with ignoreMigrationPatterns.

Our intent is to have Pending migrations ignored. And the opposite when it comes to future migrations (we expect an exception on failure).
The original code:

```
Flyway.configure()
            .dataSource(dataSource)
            .schemas(DatabaseConfiguration.SCHEMA)
            .defaultSchema(DatabaseConfiguration.SCHEMA)
            .table(TABLE_NAME)
            .locations(SQL_MIGRATION_SCRIPT_LOCATION, JAVA_MIGRATION_PACKAGE_LOCATION)
            .ignoreFutureMigrations(false)  // depracated, to be replaced
            .ignorePendingMigrations(true) // depracated, to be replaced
            .load();
```

To achieve the same while using ignoreMigrationPatterns we replaced the code with following:
```
Flyway.configure()
            .dataSource(dataSource)
            .schemas(DatabaseConfiguration.SCHEMA)
            .defaultSchema(DatabaseConfiguration.SCHEMA)
            .table(TABLE_NAME)
            .locations(SQL_MIGRATION_SCRIPT_LOCATION, JAVA_MIGRATION_PACKAGE_LOCATION)
            .ignoreMigrationPatterns("*:pending") // new code
            .load();
```
However this code results in both pending and future migrations being ignored (exception is no longer thrown on the future migration).

To address this we had to add back the deprecated a call to ignoreFutureMigrations. With this we achieve the same functionality as with the original code
```
Flyway.configure()
            .dataSource(dataSource)
            .schemas(DatabaseConfiguration.SCHEMA)
            .defaultSchema(DatabaseConfiguration.SCHEMA)
            .table(TABLE_NAME)
            .locations(SQL_MIGRATION_SCRIPT_LOCATION, JAVA_MIGRATION_PACKAGE_LOCATION)
            .ignoreMigrationPatterns("*:pending") // new code
            .ignoreFutureMigrations(false) // added back the deprecated call
            .load();
```

When using ignoreMigarationPatterns, it shouldn't be needed to use the deprecated call to ignoreFutureMigrations(false), to achieve the future migration NOT being ignored. I would expect that patterns left out of .ignoreMigrationPatterns would NOT be ignored.

**Comment by Barry-RG** [comment]
Unfortunately this is a limitation in the deprecation process. For this functionality, until deprecation is complete, you will have to use the deprecated methods for this. However, afterwards the ignoreMigrationPatterns method will work as expected for future migrations.
