### ISSUE TITLE
Vulnerability in com.h2database:h2@1.4.200

### ISSUE THREAD

**Issue by zenpaul** [flyway/flyway#3339]
###### Which version and edition of Flyway are you using?

Latest (8.2.0)

Snyk has mentioned a vulnerability in the H2 database driver, which is resolved by upgrading the driver to version 2.0.202 or higher: https://security.snyk.io/vuln/SNYK-JAVA-COMH2DATABASE-1769238

**Comment by Barry-RG** [comment]
Looking at upgrading

**Comment by Barry-RG** [comment]
Related to https://github.com/flyway/flyway/issues/3336 and https://github.com/flyway/flyway/issues/3334
