### ISSUE TITLE
Unsupported Database: MySQL 8.0

### ISSUE THREAD

**Issue by nbt-leejaewon** [flyway/flyway#3340]
###### Which version and edition of Flyway are you using?

org.flywaydb:flyway-core:8.2.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

The following error occurs when executing migration. 
```
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 8.0 	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:106) 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75) 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:143) 	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle

###### Which database are you using? (Type & version)

Mysql 8.0.27

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Changed flyway version from 8.2.0 to 8.2.1

**Comment by Barry-RG** [comment]
Flyway compatibility with MySQl is now an additional dependency which needs to be added to your project.
Please see the [Flyway 8.2.1 Release notes](https://flywaydb.org/documentation/learnmore/releaseNotes#8.2.1) and the MySQL Database page within the [documentation](https://flywaydb.org/documentation/database/mysql)

**Comment by nbt-leejaewon** [comment]
Thanks, I solved the problem as below.
```
implementation("org.flywaydb:flyway-mysql:8.2.1")
```

**Comment by abhirammkaushik** [comment]
@nbt-leejaewon 
If possible, could you let me know how you've constructed the datasource object that gets passed? 
( Flyway.configure().dataSource(<dataSource>) )
I'm getting a similar error when I pass (URL, user, pass) into the _.datasource_ method.

**Comment by martinmatovcik** [comment]
The only way that worked for me was to add these dependencies to build.gradle:

```
implementation 'org.flywaydb:flyway-core:8.4.4'
implementation 'org.flywaydb:flyway-mysql:8.4.4'
```
As shown [here.](https://www.code4copy.com/java/spring-boot-flyway-db-migration-integration-example/)

**Comment by Naylor55** [comment]
oh,god!
