### ISSUE TITLE
Obsolete warning about MariaDB connector and MySQL 8.0

### ISSUE THREAD

**Issue by hemberger** [flyway/flyway#3341]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 8.2.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Database: jdbc:mysql://smr-mysql/smr_live (MySQL 8.0)

###### Which operating system are you using?
Ubuntu 20.04

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Here's my docker-compose.yml configuration:
```
    flyway:
        image: flyway/flyway:latest-alpine
        command: -connectRetries=20 -url=jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false -user=${MYSQL_USER} -password=${MYSQL_PASSWORD} migrate 
```
And I am running `docker-compose run --rm flyway`

###### What did you expect to see?
According to https://github.com/flyway/flyway/issues/2865, the MariaDB driver supports all versions of MySQL higher than 5.5.3, and it was stated that the warning would be removed. Therefore, I do not expect to see this warning anymore.

###### What did you see instead?
WARNING: You are attempting to connect to a MySQL database using the MariaDB driver. This is known to cause issues. An upgrade to Oracle's MySQL JDBC driver is highly recommended.

Thanks for your time!

**Comment by Barry-RG** [comment]
This warning will be corrected

**Comment by hemberger** [comment]
Thank you for the quick fix! Really appreciate all the hard work on this great tool.
