### ISSUE TITLE
Support (and auto-detect) for encoding CP1252

### ISSUE THREAD

**Issue by tomtsui88** [flyway/flyway#3346]
###### Which version and edition of Flyway are you using?
8.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
Oracle 19

###### Which operating system are you using?
Both Windows and Linux

###### What did you expect to see?
Currently, the Flyway only officially supports the following encoding format:  US-ASCII, ISO-8859-1, UTF-8, UTF-16BE, UTF-16LE, and UTF-16.  Would like to see if it can support and be able to auto-detect CP1252 as well.

**Comment by Barry-RG** [comment]
As CP1252 and the already supported ISP-8859-1 are identical (With the exception of for the code points 128-159) they are considered the same by many systems. 
As a result, we are awaiting further interest in the feature.

**Comment by tomtsui88** [comment]
Thanks for your answer.  As you said, they are just similar, but not identical.  We have some SQL scripts where they inserted data with special characters using CP1252. but it shows as junk in the database after executing by Flyway (with the encoding set to ISP-8859-1).

**Comment by tomtsui88** [comment]
In addition, it seems Flyway UNOFFICIALLY supports CP1252, as I saw another thread where the Flyway support mentioned to the users to set the property flyway.encoding=cp1252 (found in https://github.com/flyway/flyway/issues/2558).  I am wondering if Flyway can OFFICIALLY support cp1252 and more importantly be able to auto-detect it as well?

Thanks.
