### ISSUE TITLE
how to config flyway log without springboot

### ISSUE THREAD

**Issue by ivanmissu** [flyway/flyway#3351]
###### Which version and edition of Flyway are you using?
5.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Mysql 5.7

###### Which operating system are you using?
Mac / Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
i used LogFactory.setLogCreator(new Slf4jLogCreator()) before initialize flyway,  but log level is always debug。

###### What did you expect to see?
using flyway, config logback without springboot

**Comment by DoodleBobBuffPants** [comment]
You have to configure the logger itself as opposed to through Flyway
