### ISSUE TITLE
OutOfOrder migration detection options/callback

### ISSUE THREAD

**Issue by winterspan** [flyway/flyway#3353]
_(Apologies for the duplication, I was unable to respond on a previous version of this issue (https://github.com/flyway/flyway/issues/3320) which was subsequently closed)._

The project I'm working on is using Flyway 4.2. As of that version, if OutOfOrder mode is disabled, and I introduce an out-of-order migration, it just seems to be ignored. No exceptions are thrown. (note: I have ValidateOnMigrate disabled, but as I understand it, that just looks at migration checksums)

Instead of having OoO migrations ignored when outOfOrder isdisabled, I'd like to have an exception thrown or execute a callback. 

I tried adding a beforeEachMigrate Java callback as suggested in the previous ticket, but that doesn't seem to get called in the context of out-of-order migrations assuming OutOfOrder is disabled. It is only called for normal, in-order migrations, or out-of-order migrations when OutOfOrder is explicitly enabled and they execute. 

Ultimately, the goal is just to detect out-of-order migrations being introduced while OutOfOrder mode is disabled and raise visibility during application startup.

###### Which version and edition of Flyway are you using?
4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
MySQL 5.7

**Comment by DoodleBobBuffPants** [comment]
You can run `info` and check for any unapplied out of order migrations to detect this scenario

We likely won't be making any changes unless this gets further interest, so closing for now
