### ISSUE TITLE
Huge impact of Flyway GCP BigQuery on application launch time

### ISSUE THREAD

**Issue by A-Bag** [flyway/flyway#3354]
###### Which version and edition of Flyway are you using?
Flyway version: 8.2.2
Flyway GCP BigQuery version: 8.2.2-beta

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Database: GCP BigQuery 
Driver: SimbaJDBCDriverforGoogleBigQuery42_1.2.21.1025

###### Which operating system are you using?
Ubuntu 18.04

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Configured Flyway GCP BigQuery with Maven and started Spring Boot application.

###### What did you expect to see?
Successful connection to GCP BigQuery. Application launch time increased not more than a few seconds. 

###### What did you see instead?
Connection was successful but the application started in 45 seconds (even though there was no migration executed because the schema was up to date) while it starts in 7 seconds without Flyway GCP BigQuery configured. Is it supposed to have such a huge impact on the launch time?

**Comment by DoodleBobBuffPants** [comment]
BigQuery is known to be in general slower, and this is likely due to queries we execute on startup, so this is expected
