### ISSUE TITLE
Flyway does not work when installed on Alpine 3.15.0 docker image

### ISSUE THREAD

**Issue by RCCSilva** [flyway/flyway#3356]
###### Which version and edition of Flyway are you using?

Flyway 8.2.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line inside a Dockerfile.

###### Which operating system are you using?

Alpine 3.15.0

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I'm trying to build this Dockerfile with ` docker build -t flyway-alpine:latest . `.

```
FROM alpine:3.15.0

WORKDIR /app

RUN apk add bash
RUN wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.2.2/flyway-commandline-8.2.2-linux-x64.tar.gz | tar xvz && ln -s `pwd`/flyway-8.2.2/flyway /usr/local/bin

CMD ["flyway"]
```

###### What did you expect to see?

The build looks to work well, but when executing the image with `docker run flyway-alpine:latest` I'd expect the flyway CLI to show up.

###### What did you see instead?

Instead, I see this error

```
/usr/local/bin/flyway: line 105: /app/flyway-8.2.2/jre/bin/java: No such file or directory
```

![image](https://user-images.githubusercontent.com/25212811/146584948-f2531394-9ebc-4954-a34e-c6ec1249af4e.png)

Looks to be related with this command on the flyway script.

```
/app/flyway-8.2.2/jre/bin/java -Djava.security.egd=file:/dev/../dev/urandom -cp :/app/flyway-8.2.2/lib/*:/app/flyway-8.2.2/lib/aad/*:/app/flyway-8.2.2/lib/oracle_wallet/*:/app/flyway-8.2.2/lib/community/*:/app/flyway-8.2.2/drivers/*:/app/flyway-8.2.2/drivers/gcp/* org.flywaydb.commandline.Main
```

I have reasons to be believe that this is related with the Alpine OS. When I tried to do the same thing on a Debian based image, it worked fine.

Thank you ahead for your time!

**Comment by DoodleBobBuffPants** [comment]
We recommend using our own provided Alpine image (found [here](https://hub.docker.com/r/flyway/flyway)) as custom images are unsupported
