### ISSUE TITLE
Error while running flyway (after updating flyway and h2)

### ISSUE THREAD

**Issue by alahaouas** [flyway/flyway#3359]
###### Which version and edition of Flyway are you using?
flyway-maven-plugin version 8.2.2 (latest)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
h2 database version 2.0.202

###### Which operating system are you using?
Ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I upgraded Maven dependencies for h2 and flyway to answer security issues with older versions.

Since then, I get errors on my Junit tests that fail the Maven build.
The unit tests are the sames.

###### What did you expect to see?
Junit Tests passing as it used to with old flyway and h2 versions.

###### What did you see instead?
```
Error while running flyway-migrations for src/test/resources/flyway-dptechnical.properties : 
Unable to determine H2 compatibility mode
-----------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "SELECT VALUE[*] FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE'"; expected "TOP, DISTINCT, ALL, ,, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
SELECT VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE' [42001-202]

17:40:01.240 [main] ERROR be.healthdata.hdconnect.persistence.DatabaseWriter - Error while running flyway-migrations for src/test/resources/flyway-localdwh.properties : 
Unable to determine H2 compatibility mode
-----------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "SELECT VALUE[*] FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE'"; expected "TOP, DISTINCT, ALL, ,, NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
SELECT VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE' [42001-202]
```

**Comment by DoodleBobBuffPants** [comment]
Please ensure that the updated version of Flyway is being used as this issue has already been fixed, otherwise please provide a minimal reproduction project

**Comment by alahaouas** [comment]
@DoodleBobBuffPants 
How is this helping ? You are very quick on the closing button, on a real blocker. 
I am using flyway-maven-plugin version 8.2.2 (the latest)

And on the other tickets, you don't explain how this is fixed.

So, what to do now, I can't send you my project, it takes 2 days to setup and it is not open-source code.

**Comment by alahaouas** [comment]
I believe the ticket should be investigated for a fix : flyway with h2 on the versions that are mentioned above.
 
As for the proof, I ran Maven on debug :
![image](https://user-images.githubusercontent.com/77787476/146806869-f9f6773a-75a2-4301-9ab0-49517e8751f8.png)

![image](https://user-images.githubusercontent.com/77787476/146807130-c64c8d28-63d0-4cd6-abe5-f52fa199267e.png)

**Comment by DoodleBobBuffPants** [comment]
The logs show that Flyway 7.9.1 is being used

Please ensure that the updated version of Flyway is being used (you may need to clean and rebuild your project)

**Comment by alahaouas** [comment]
My bad, I did try that older version as an experiment in case the issue appeared on v8.
I came back again on v8.2.2 and I do have the error described above.
I share the screenshot in 2'

**Comment by alahaouas** [comment]
Is there a way I can ignore or override old scripts ?
I get : 
```
Error while running flyway-migrations for src/test/resources/flyway-dptechnical.properties : Found more than one migration with version 1
Offenders:
-> /..../data-collection/target/classes/db/migration/dptechnical/V1__create-formsubmission-table.sql (SQL)
-> /..../data-collection/target/test-classes/db/migration/dptechnical/V1__create-formsubmission-table.sql (SQL)
```

**Comment by DoodleBobBuffPants** [comment]
This is due to a change in 7.12.0 that requires a resource to only appear on the classpath once (this deals with issues where it could appear multiple times, such as in this case, where each script's contents could be different)

You will need to configure the [locations](https://flywaydb.org/documentation/configuration/parameters/locations) to point at just one of them (i.e. under `classes` or `test-classes`)

**Comment by alahaouas** [comment]
@DoodleBobBuffPants is there a way with locations to exclude 1 specific migration file ?

**Comment by DoodleBobBuffPants** [comment]
Not directly, instead you configure `locations` to only include the migrations you want

**Comment by stephane-dereppe** [comment]
Hi @DoodleBobBuffPants 

Does it mean that we have to explicitly list all migrations (I have more than 100 migrations.. One must be excluded for tests).

**Comment by puce77** [comment]
So again, what is the proposed solution to replace 5 scripts out of 100 for H2 unit tests? I don't even see a "not" opeartor in the location wildcards.
This used to work and to list all scripts explicitly is not a good option.

**Comment by MKaciuba** [comment]
Hi, same problem here. Previously I could override a single migration for tests. Is there a convenient alternative to achieve the same result in newer versions of flyway?

**Comment by EricDitp** [comment]
Most scripts in my case are generic, but some are specific for the non-test database. Therefore only a few script should be overriden for test with the same script with the same working but than for the h2 test database
