### ISSUE TITLE
Java based migrations not supporting specific DB

### ISSUE THREAD

**Issue by zoffoliluca** [flyway/flyway#3363]
- I'm using Flyway 8.0.4.

I have a java based migration class but unfortunately SQL scripts differ in Postgres (production) an H2 (junit).

I've tried to put two different migration with this structure :

```
> -> src/main/java/db/migration
>    ->specific
>       -> h2
>          -> V01__CREATE_TABLE.java
>       -> postgres
>          -> V01__CREATE_TABLE.java
```

With usual SQL-Flyway migration scripts this package structure works as expected.

With java-based-migrations not.

I got : **Caused by: org.flywaydb.core.api.FlywayException: Found more than one migration with version 032**

Can you help me? Thanks

[java-based-migrations documentation](https://flywaydb.org/documentation/concepts/migrations.html#java-based-migrations)

**Comment by DoodleBobBuffPants** [comment]
This is something you will need to configure by changing the [locations](https://flywaydb.org/documentation/configuration/parameters/locations) parameter

With this, you want the location set to `db/migration/specific/h2` for test and `db/migration/specific/postgres` for production

Closing as this is a question as opposed to an issue
