### ISSUE TITLE
Conflict between placeholder replacement and JS template literal interpolation in Snowflake

### ISSUE THREAD

**Issue by md5** [flyway/flyway#3365]
###### Which version and edition of Flyway are you using?

8.0.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Based on the docs and source code, yes.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Docker image

###### Which database are you using? (Type & version)

Snowflake

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Tried to create a Snowflake stored procedure written in JavaScript that included `${variable}` substitutions in template literal.

###### What did you expect to see?

My procedure created.

###### What did you see instead?

Got an error from Flyway about a placeholder not being defined.

**Comment by md5** [comment]
To add a bit of context here, we are also using Flyway placeholder replacement, so I can't just turn it off. I could consider using an alternate prefix and suffix for Flyway interpolation, but it seems like that would be confusing to anyone who needs to work on this repository. Alternatively, attempting to adjust my `CREATE PROCEDURE` migration to break up the `${` also seems like it would be a huge pain.

During my investigation, I found that Flyway supports [Script Config Files](https://flywaydb.org/documentation/configuration/scriptconfigfiles) by placing a file with the `.conf` extension that corresponds to the `.sql` file. I was hoping that I could set `placeholderReplacement=false` in that file to override the global value, but it appears that these config files support only a very limited range of configuration settings.

At this point, it feels like my best workaround is probably to change the Flyway placeholder prefix to something other than `${`.

**Comment by DoodleBobBuffPants** [comment]
We would recommend using a different prefix and suffix for Flyway, as this will also differentiate between what's done through JS and Flyway

We likely won't work on this until it gets further interest, so closing for now

**Comment by md5** [comment]
Thanks for the quick fix!
