### ISSUE TITLE
Messages and warnings are only printed after a file is done, and not during the execution

### ISSUE THREAD

**Issue by tussosedan** [flyway/flyway#3370]
###### Which version and edition of Flyway are you using?
8.3.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line and Azure DevOps plugin

###### Which database are you using? (Type & version)
SQL Server 2017

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Running PRINT and RAISERROR warning messages in a loop in a large script

###### What did you expect to see?
Expected to see the output shown in real time, as we use the messages to monitor the progress rate of the script

###### What did you see instead?
No messages shown at all, and after the script was done all were printed at once.

Please make it so the messages/warnings are shown in real time, it's important to see them during the execution for critical scripts. Thank you.

**Comment by DoodleBobBuffPants** [comment]
This is a limitation of JDBC

JDBC executes statements in a blocking manner, so we cannot print any results until a statement has completed, and loops are treated as a single statement
