### ISSUE TITLE
There may be a problem with the callback logic

### ISSUE THREAD

**Issue by vichbb** [flyway/flyway#3371]
###### Which version and edition of Flyway are you using?

7.5.2
8.3.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
8.3.0 is latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line,

###### Which database are you using? (Type & version)
postgresql13

###### Which operating system are you using?

Mac

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

migrate with afterMigrate

###### What did you expect to see?

It is called only when the migrate is successful (the version number has changed).

###### What did you see instead?

It will be called every time you migrate, even if the version number has not changed

**Comment by tjs145** [comment]
This is expected behavior, so closing this issue for now.

Depending on what you're doing, you might want to look into using both afterMigrate and afterMigrateError, or use repeatable migrations.
