### ISSUE TITLE
H2 vulnerability

### ISSUE THREAD

**Issue by dblackstock** [flyway/flyway#3372]
###### Which version and edition of Flyway are you using?

Latest, via [flyway/flyway Docker image](https://github.com/flyway/flyway-docker).

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command line with Docker.

###### Which database are you using? (Type & version)

PostgreSQL 14.1 (latest)

###### Which operating system are you using?

Windows with WSL

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

[Trivy](https://github.com/aquasecurity/trivy) is run against our Docker images before they're deployed.

###### What did you expect to see?

The Flyway image usually runs without any issues raised by Trivy.

###### What did you see instead?

Flyway is flagged with [an H2 vulnerability](https://github.com/advisories/GHSA-h376-j262-vhq6) affecting versions below `2.0.206`. Flyway is on version `2.0.202`.

I'm not familiar with H2 so this may not be an issue directly affecting Flyway, incorrectly flagged by Trivy.

**Comment by Barry-RG** [comment]
Thank you for bringing this to our attention. We will investigate further and get back to you as soon as possible.
