### ISSUE TITLE
Missing 8.4.0 release notes

### ISSUE THREAD

**Issue by jeanremacle** [flyway/flyway#3373]
Hello,

For some odd reason Release 8.4.0's release notes were not published anywhere.  
If I am mistaken or if they can be derived from some references, please advise.
I have to inspect them before any upgrade on our side.

Thanks and regards,
Jean Remacle

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising the issue

This has now been resolved: https://flywaydb.org/documentation/learnmore/releaseNotes#8.4.0
