### ISSUE TITLE
placeholder can not be work correctly.

### ISSUE THREAD

**Issue by fr-yokurah** [flyway/flyway#3384]
###### Which version and edition of Flyway are you using?
7.9.0 later

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
We faced the same problem at latest version (8.4.2)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Comamnd-line

###### Which database are you using? (Type & version)
Postgres 12.3

###### Which operating system are you using?
Linux/MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We customized placeholder prefix and suffix, and try to migrate, placeholder seems not to be work correctly.

conf/placeholder.conf
```
flyway.schemas=god
flyway.placeholderPrefix={{
flyway.placeholderSuffix=}}

flyway.placeholders.meta.startwith=${tYmdHMS}_takagir_is_god
flyway.placeholders.meta.endwith=takagir_is_god_${tYmdHMS}
flyway.placeholders.meta.centered=takagir_is_${tYmdHMS}_god
```

sql/V1.2.0__insert_metadata_with_placeholder.sql
```
insert into t_god_meta values (4, '{{meta.startwith}}');
insert into t_god_meta values (5, '{{meta.endwith}}');
insert into t_god_meta values (6, '{{meta.centered}}');
```

migration result
```
$./flyway -configFiles=./conf/flyway.conf,./conf/placeholder.conf -placeholderReplacement=false migrate

WARNING: You are on an older version of Flyway. Please download latest at https://www.flywaydb.org/download/community
Flyway Community Edition 7.9.0 by Redgate
Database: jdbc:postgresql://192.168.11.3:5432/goddb (PostgreSQL 12.3)
Creating schema "god" ...
Creating Schema History table "god"."flyway_schema_history" ...
Current version of schema "god": null
Migrating schema "god" to version "1.0.0 - create table t god meta"
Migrating schema "god" to version "1.1.0 - insert metadata"
Migrating schema "god" to version "1.2.0 - insert metadata with placeholder"
Successfully applied 3 migrations to schema "god", now at version v1.2.0 (execution time 00:00.053s)

goddb=> select * from t_god_meta;
 meta_id |   meta_value
---------+-----------------
       1 | takagir
       2 | is
       3 | god
       4 | _takagir_is_god
       5 | takagir_is_god_
       6 | takagir_is__god
(6 rows)
```

###### What did you expect to see?
We expected string `${tYmdHMS}` was inserted, but it seemed to be replaced as empty.
This expectation was available at version `5.2.1`.

version 5.2.1 result
```
goddb=> select * from t_god_meta;
 meta_id |        meta_value
---------+---------------------------
       1 | takagir
       2 | is
       3 | god
       4 | ${tYmdHMS}_takagir_is_god
       5 | takagir_is_god_${tYmdHMS}
       6 | takagir_is_${tYmdHMS}_god
(6 rows)
```

###### What did you see instead?
What we have to do to get our expected result ? We have to set escape to `${}`, right ?

**Comment by tjs145** [comment]
Values in the config surrounded by `${` - `}` are treated as environment variables. In this case, Flyway has tried to replace `${tYmdHMS}` with an environment variable called `tYmdHMS`. If the environment variable doesn't exist then it is replaced with nothing, which is what happened here.

What function do the values in `${` - `}` serve? If possible, you might need to use a different prefix/suffix for `${tYmdHMS}`, as there's no way to prevent Flyway from expanding environment variables and we probably won't be adding this functionality unless there's further interest from users.

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
