### ISSUE TITLE
Populated baseline description blocks migration and gives a misleading message about SQL syntax

### ISSUE THREAD

**Issue by fiagaj** [flyway/flyway#3385]
I'm using this is Maven:
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
			<version>7.7.3</version>
		</dependency>
but I also tried with 8.1.0

Client: Maven Plugin in Springboot

Db: PostgreSQL 10.4

OS: Windows 10

I run the springboot application with:
spring.flyway.enabled=true
spring.flyway.create-schemas=false
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true
spring.flyway.baseline-description=Flyway Migration start
.... other project specific data

I expected to see he flyway history table on db, and also a first test script

Instead of that, the application shut down and gave a SQL Exception in trying to insert the first row:

INSERT INTO "my_schema"."flyway_schema_history" ("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "execution_time", "success") VALUES (1, '100', ''Flyway Migration start'', 'BASELINE', ''Flyway Migration start'', NULL, 'null', 0, TRUE)

It was a generic SQL exception but I checked on the db and the table wasn't there.

After I left the baseline-description field unpopulated, thus putting in the default message, the table was created as expected and migrations were handled accordingly.

**Comment by DoodleBobBuffPants** [comment]
Closing till further activity
