### ISSUE TITLE
Unable to have just /* within existing multi-line comment block.

### ISSUE THREAD

**Issue by MikeNeilson** [flyway/flyway#3387]
###### Which version and edition of Flyway are you using?
Community 8.4.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
gradle plugin

###### Which database are you using? (Type & version)
oracle 19c

###### Which operating system are you using?
linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Attempted to run migration with the following:

```
create or replace package  test_pkg
as
    /**
     * @param id 'image/*'
    */
    function a_test(id varchar(255)) returns integer;
end test_pkg;
/
```

The comment is suppose to indicate an example of a type of "glob" one could put in the the parameter. 

###### What did you expect to see?
The migration succeeded.

###### What did you see instead?
`Unable to parse statement in db/migration/V0000/V0000.0000__test.sql at line 4 col 1. See https://rd.gt/3ipi7Pm for more information: Incomplete statement at line 4 col 1: `

I removed the `/*` after image and the migration works. Or if I add a `*/` somewhere after the `image/*` it also works.

Looking at https://github.com/flyway/flyway/blob/6e707f7d9ca462fe72aa5bbd1bcdfb90693448e0/flyway-core/src/main/java/org/flywaydb/core/internal/parser/Parser.java#L514 this appears to be expected behavior but it does limit what text I one could put in a comment. Unless I'm just going something wrong.

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising this issue

While this is a limitation of our current parsing, we likely won't be making any changes here unless others experience the same issue, so we will label and close this

One workaround however would be to make each line a single line comment which would allow you to keep `/*` in the comment
