### ISSUE TITLE
Package request: flyway-commandline for linux-aarch64

### ISSUE THREAD

**Issue by am11** [flyway/flyway#3398]
###### Which version and edition of Flyway are you using?
8.5.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

MySQL

###### Which operating system are you using?

Debian Buster aarch64

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Tried to find flyway-commandline for linux-aarch64 from https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.0/.

###### What did you expect to see?

that there is a package available for linux-aarch64.

###### What did you see instead?

no package was available for the desired architecture.

**Comment by Barry-RG** [comment]
The architecture specified in the releases are mostly around architecture of the JRE which is bundled with Flyway for that release.
https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.0/flyway-commandline-8.5.0.tar.gz is a JRE free command line package which should use the JRE installed in your environment.

**Comment by agorina** [comment]
I am running into a similar issue on the new Mac with Apple M1 Pro chip. Since jre is bundled with the CLI, it fails with this error message due to incompatible version of jre: `.../flyway-8.4.2/jre/bin/java: Bad CPU type in executable` . 

I see that this is closed, could you please explain why and how to solve it?
