### ISSUE TITLE
Parallel migrations broken with Google Cloud Spanner

### ISSUE THREAD

**Issue by scjody** [flyway/flyway#3400]
###### Which version and edition of Flyway are you using?

Community edition, 8.5.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Spanner, as running on GCP on February 15, 2022 (no public version information is shown).

###### Which operating system are you using?

OS X (Darwin NXHX4K9QTM 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64 arm64 MacBookPro18,3 Darwin)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

1. Created and configured 5 `Flyway` instances, all using the same empty Spanner database (and the same set of migrations).
2. Ran `flyway.migrate()` on each instance from a separate thread.

###### What did you expect to see?

I expect one instance to perform the migration and the others to wait for the migration to complete, as [suggested by the FAQ](https://flywaydb.org/documentation/learnmore/faq#parallel).

###### What did you see instead?

All 5 instances attempted to perform migrations. 4 failed with errors such as `Migration of schema "" to version "001 - create entries table" [non-transactional] failed! Please restore backups and roll back database and code!`

**Comment by scjody** [comment]
For what it's worth, we've worked around the issue using ZooKeeper and the [LeaderLatch algorithm in the Curator Framework](https://curator.apache.org/curator-recipes/leader-latch.html).

**Comment by JasonLuo-Redgate** [comment]
This issue is fixed in the latest version of Flyway.
