### ISSUE TITLE
No database found to handle jdbc:sqlserver://localhost

### ISSUE THREAD

**Issue by medwards8** [flyway/flyway#3402]
###### Which version and edition of Flyway are you using?

Currently using 7.9, attempting to upgrade to 8.5(both community editions)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

SQL Server 2019

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Error I'm currently getting:

![2022-02-23_10-53-21](https://user-images.githubusercontent.com/100300381/155355932-29974e01-2044-4293-ae51-19d3a85b41e6.jpg)

Contents of the config file it is referencing:

![2022-02-23_10-57-29](https://user-images.githubusercontent.com/100300381/155356733-a398c254-ced8-47d8-8707-63d1df75242b.jpg)

Doing this same process on 7.9 it runs perfectly fine, only get this error on 8.5 (also tried 8.1 and 8.2, same error)

Also tried the suggestions here, https://github.com/flyway/flyway/issues/3355, but am not using Gradle, and I'm using sqlserver not mysql

###### What did you expect to see?

I expected the database to migrate to my local instance as before in 7.9

**Comment by DoodleBobBuffPants** [comment]
I'm unable to reproduce this issue, the latest version of the CLI should have the `flyway-sqlserver` module included

Could you provide a minimal reproduction project?

**Comment by medwards8** [comment]
Hello Doodle thanks for responding.  Unfortunately I can't share anything outside of the company since it's all protected.
Is there any testing you could recommend or anything else I could try?

Here is the driver for sql I am using:
![2022-02-23_15-13-51](https://user-images.githubusercontent.com/100300381/155400615-2abc52d0-086e-4b6f-a525-a11599dd60f4.jpg)

And these are the flyway commandline/core jar files.  If I swap these back to 7.9 the migrate is successful
![2022-02-23_15-14-05](https://user-images.githubusercontent.com/100300381/155400699-dddc2896-c17c-4a88-91e2-54fbf849ecb5.jpg)

**Comment by DoodleBobBuffPants** [comment]
A couple of things to try/check:

- If you download the latest version of flyway and use that (without moving the JAR files, but instead configuring the new download) does it work?
- In the `lib/community` folder there should be a JAR file that starts with `flyway-sqlserver`. Is this present? If not, you should be able to get one by downloading flyway again
