### ISSUE TITLE
Add one-liner info log for "X migrations were detected but were not run."

### ISSUE THREAD

**Issue by sesgoe** [flyway/flyway#3403]
Hi Flyway Team,

This feature request is created in response to https://github.com/flyway/flyway/pull/3401, as requested.

### The issue
When you run `flyway migrate`, if specific migrations in a folder don't follow the naming convention, those migrations do not get run. I was debugging why specific migrations were not running in our CI environment. The reason was that the files in question were named like this:

```
V1234_some_migration.sql
```

instead of the correct

```
V1234__some_migration.sql
     ^ 
```

I happened to notice that these files lacked an underscore by chance. My knowledge of Flyway before this moment was "it runs DB migrations," and I had no idea that it had any filename conventions or rules. I assumed the structure in our team's `migrations` folder was because they thought it kept it orderly/neat. We're 300+ migrations in, so this system has been there for a lot longer than me 😅. 

### The request
Please see my above PR for further intricate details, but I'd love to add a single `WARN` log line that says something like the following, directly after migrations run:
```
[WARN] X migrations were detected but were not run because they did not follow the filename convention.
```

It could also include something like:
```
Please see https://www.red-gate.com/blog/database-devops/flyway-naming-patterns-matter for more details.
```

```
If this is in error, use the -X flag to enable debug logging to see which files were not run.
```

```
If this is in error, use the `validateMigrationNaming` flag to fail when invalid file names are detected.
```

The point of a change like this is to make the issue discoverable by only running `flyway migrate`. It's a helpful nudge in the right direction to people who may have limited knowledge or understanding of the intricacies of Flyway.

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising this issue!

This is definitely something we're keen on adding

We're interested in what the need is for this as a warn-level log. By default, flyway puts a `.txt` file in the default migrations location, and people often put non-migration files in these locations on purpose, and a warning seems a bit extreme to force upon people in this scenario. Would an info-level log suffice?
