### ISSUE TITLE
Command-line interface does not read config from standard input

### ISSUE THREAD

**Issue by davidvandusen** [flyway/flyway#3404]
###### Which version and edition of Flyway are you using?

Community edition, 8.5.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

Any. Example shown using H2 2.1.

###### Which operating system are you using?

Ubuntu 20.04.3 LTS running interactively in the official Flyway Docker image, `flyway/flyway:8.5.1`.

Encountered the same running on macOS 12.2.1.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Ran the example command on the "Configuration from standard input" section from the "Command-line tool" documentation: https://flywaydb.org/documentation/usage/commandline/#configuration-from-standard-input

The examples are run interactively with the official Docker image using the following command:

```
$ docker run -it --rm --entrypoint=sh flyway/flyway:8.5.1
```

###### What did you expect to see?

The output should be the same as if the `url` was passed in as an argument:

```
$ flyway info -url=jdbc:h2:mem:mydb
Flyway is up to date
Flyway Community Edition 8.5.1 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.1

Database: jdbc:h2:mem:mydb (H2 2.1)
Schema version: << Empty Schema >>

+----------+---------+-------------+------+--------------+-------+
| Category | Version | Description | Type | Installed On | State |
+----------+---------+-------------+------+--------------+-------+
| No migrations found                                            |
+----------+---------+-------------+------+--------------+-------+
```

###### What did you see instead?

The output behaves as if no `url` option was given.

```
$ echo $'flyway.url=jdbc:h2:mem:mydb' | flyway info -configFiles=-             
ERROR: Unable to connect to the database. Configure the url, user and password!
```

With debug option:

```
$ echo $'flyway.url=jdbc:h2:mem:mydb' | flyway info -configFiles=- -X
DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.configFiles -> -
DEBUG: flyway.jarDirs -> /flyway/jars
DEBUG: flyway.locations -> filesystem:sql
DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@134593bf ...
DEBUG: Unable to resolve location classpath:db/callback.
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
	at org.flywaydb.core.internal.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:36)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:112)
	at org.flywaydb.core.Flyway.info(Flyway.java:190)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:284)
	at org.flywaydb.commandline.Main.main(Main.java:182)
```

**Comment by Barry-RG** [comment]
To use this functionality you must specify the edition of Flyway you wish to invoke. For example:
`echo $'flyway.url=jdbc:h2:mem:mydb' | flyway -community info -configFiles=-`
This requirement will be removed in version 9.
