### ISSUE TITLE
Flyway V9 Breaking Changes

### ISSUE THREAD

**Issue by Barry-RG** [flyway/flyway#3407]
### Repackaging of Flyway
As we are moving forward to a 2 package command line system to better allow contributions from our open source community. These packages will be Flyway Command-Line Community, purely open source, and Redgate Flyway Command-Line, closed source, for paid options. Paid users, or those wishing to upgrade to paid features, will specifically need to download the Redgate Flyway Command-Line from the Flyway website.

### Clean disabled by default
Clean will be disabled by default and will need enabling using the [`flyway.cleanDisabled`](https://flywaydb.org/documentation/configuration/parameters/cleanDisabled).

#### MigrationType
- `MigrationType` enum replaced with `CoreMigrationType`
- `SQl__BASELINE` and `JDBC__BASELINE` types removed from `flyway-core`
- `SCRIPT__BASELINE` deprecated
- `baselineMigration` now called `baseline` 
- `BASELINE` enum returns true for `isBaseline`
- `MigrationType` changed to interface which is in the `extensibility` package

#### Configuration
- `BaselineMigrationPrefix` configuration via API removed from core/gradle/maven into `flyway-proprietary`

#### JavaMigration
- `BaseJavaMigration` can no longer be used for B scripts - use `BaselineJavaMigration` from the `flyway-proprietary` package
- Removed `isUndo` and `isBaselineMigration` methods - these are inferred from the migration type

#### MigrationResolver
- `Context` in `resolveMigrations` on a `MigrationResolver` is now a class which also has `ResourceProvider`, `SqlScriptFactory` and `SqlScriptExecutorFactory`
- `getPrefix` is used to determine if a resolver should also have script variants (`ps1`, `bash` etc.) resolved by Flyway. Defaults to null

#### ResolvedMigration
- Adds ability to return its own state with `getState` method with default implementation
- Adds `canCompareWith` to decide if two `ResolvedMigration`s are comparable when checking their version and description for a match

**Comment by allenatdecisiv** [comment]
@Barry-RG,

What does this mean for folks who go to the Maven site to download Flyway Command-line? I haven't found a simple way to get Flyway Command-line from the Flway website without doing a "28 day free trial" dance? I already have my key/token, I just need the binaries.

Because it's not as easy as just clicking a link to download, I go to the Maven artifact site.

What am I missing?

**Comment by Barry-RG** [comment]
Currently, the Community Flyway Command-Line package contains both the Community edition and the Teams edition in one package, with teams functionality only being usable with a license. This means that the downloads are the same from the Flyway website. 

From version 9, there will be two download links, one for the Open Source Community and the other for the Paid Redgate Flyway edition. The community link will be provided on the website. The paid download link will be given with more information nearer the time.

**Comment by esauser** [comment]
Will docker images be provided for the paid version?

**Comment by madninjaskillz** [comment]
> 

Separate Docker Images for licensed editions will be provided (most likely on DockerHub)

**Comment by jeanremacle** [comment]
Will it be possible to toggle community / teams edition with the paid download ? Not all our deployments require the teams edition.

**Comment by Barry-RG** [comment]
@jeanremacle No. This is how things are currently but moving forward community and teams editions will be completely separate packages.
