### ISSUE TITLE
Unable to find driver for postgresql when using P6Spy

### ISSUE THREAD

**Issue by RB14** [flyway/flyway#3409]
This is a follow up ticket to https://github.com/flyway/flyway/issues/3028.

This is the first time I'm trying to actually use `P6Spy` after that feature request you implemented upon my request a year ago.
When I'm using the JDBC URL:
```
jdbc:p6spy:postgresql://host:port/db
```

And running:
```
./gradlew flywayMigrate
```

I'm getting:
```
> Error occurred while executing flywayMigrate
  Unable to obtain connection from database (jdbc:p6spy:postgresql://host:port/db) for user '<user>': Unable to find a driver that accepts jdbc:postgresql://host:port/db
  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  SQL State  : null
  Error Code : 0
  Message    : Unable to find a driver that accepts jdbc:postgresql://host:port/db
  
  Unable to find a driver that accepts jdbc:postgresql://host:port/db
```

I have both the Postgres driver and P6Spy in my classpath:
```
implementation("org.postgresql:postgresql:42.2.18")
implementation("p6spy:p6spy:3.9.1")
```

When omitting the `p6spy` from the jdbc URL, it works fine. 

Could be a problem with P6Spy itself, but not sure.

Thanks!

**Comment by DoodleBobBuffPants** [comment]
The inner exception is coming from P6Spy and isn't a Flyway exception

It works when you manually specify the driver (`org.postgresql.Driver`) in the `driverlist` property in your `spy.properties`
