### ISSUE TITLE
CLI flags `-v` and `--version` not working

### ISSUE THREAD

**Issue by cies** [flyway/flyway#3418]
###### Which version and edition of Flyway are you using?

7.15.0

(I did not have this problem on 5.2.4)

###### Which operating system are you using?

Linux, Ubuntu. Installed from tarbal.

###### What did you expect to see?

The version string.

###### What did you see instead?

Nothing. It does take a while to complete.

**Comment by DoodleBobBuffPants** [comment]
I wasn't able to reproduce this. Could you

- Try the latest version
- Failing that, provide a minimal reproduction project

**Comment by abscondment** [comment]
I see something similar in the docker containers produced since 8.5.6. I still get output, but the command prints an error message and gives a nonzero exit code.

```
bribera@mapple:~/code/rcom/zeke 👻 $ docker run --rm -it --entrypoint /bin/bash flyway/flyway:latest
flyway@35fc030fe2e4:~$ flyway -v
Flyway Community Edition 8.5.7 by Redgate

ERROR: No command extension found to handle command: version
flyway@35fc030fe2e4:~$ echo $?
1
```

**Comment by abscondment** [comment]
And I see the exact thing @cies described in the 7.15.0 docker container:

```
bribera@mapple:~/code/rcom/zeke 👻 $ docker run --rm -it --entrypoint /bin/bash flyway/flyway:7.15.0
flyway@4f0715842c78:~$ flyway --version
flyway@4f0715842c78:~$ time flyway --version

real	0m4.480s
user	0m7.082s
sys	0m0.581s
flyway@4f0715842c78:~$
```

**Comment by cies** [comment]
Cheers.

**Comment by hans2520** [comment]
So we're not able to use the latest version of 7.x without a major bug? It's too bad because there's a lot of older versions of RDBMS that are not supported on 8.x
