### ISSUE TITLE
Spooling via flyway can't be used for code generation because it is pretty printed

### ISSUE THREAD

**Issue by alf** [flyway/flyway#3419]
###### Which version and edition of Flyway are you using?

Enterprise edition 8.5.5

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using? (Type & version)

Oracle XE 18c

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We use the SQL*Plus `Spool`-command to generate some code that is later meant to be migrated:

```
Set ServerOutput On Size 1000000
Set Linesize 105
Set Echo Off
Set Heading Off
Set Feedback Off
Set Verify Off

Spool "db-grant-all.sql"

Select 'Grant Select, Insert, Delete, Update On '||
       Object_Name||' To '||'some_user''||';'
From   User_Objects
Where  Object_Type = 'TABLE';

Spool off
```

Configuration is:

```
                        <configuration>
                            <driver>oracle.jdbc.OracleDriver</driver>
                            <url>${env.FLYWAY_URL}</url>
                            <user>DBADM</user>
                            <password>${env.FLYWAY_PASSWORD}</password>
                            <locations>
                                <location>filesystem:2_DBADM</location>
                            </locations>
                            <validateMigrationNaming>false</validateMigrationNaming>
                            <connectRetries>5</connectRetries>
                            <oracleSqlplus>true</oracleSqlplus>
                        </configuration>
```

###### What did you expect to see?

```
  Grant Select, Insert, Delete, Update On flyway_schema_history To some_user;
```

###### What did you see instead?

```
+-----------------------------------------------------------------------------+
| Grant Select, Insert, Delete, Update On flyway_schema_history To some_user; |
+-----------------------------------------------------------------------------+

+-----------------------------------------------+
| No rows returned                              |
+-----------------------------------------------+

+------------------------------------------------+
| No rows returned                               |
+------------------------------------------------+

```

Edit: Added the boxes with `No rows returned`. I originally attributed those to the SQL script but realize that this is also added by flyway and should not have been part of the output.

**Comment by alf** [comment]
From looking at the decompiled code, it seems that the problem is in `org.flywaydb.core.internal.database.oracle.OracleSqlScriptExecutor.outputQueryResult(Result result)`. Here the result is wrapped in an `org.flywaydb.core.internal.util.AsciiTable` before it's passed on to `org.flywaydb.core.internal.database.oracle.log(String output)` which writes the actual spooling data.

Unfortunately I see no way to disable the AsciiTable-functionality, so this is a blocker for us.

**Comment by alf** [comment]
I just realized that the current implementation also adds feedback info at the end of the spool file, even though we've disabled this using the `set feedback off` command in our script. I updated the initial description to include this output as well. I initially left that part out since I assumed this was our fault. After looking closer, I believe this is also a bug in Flyway.

**Comment by DoodleBobBuffPants** [comment]
The last two rows are a result of `SELECT` statements returning empty results, as opposed to being feedback rows

**Comment by alf** [comment]
I agree with your last assessment. There are a elects returning empty results in our scripts.

**Comment by alf** [comment]
Thanks for being honest. I guess we’re back to running SQL*Plus directly.
