### ISSUE TITLE
Flyway is unable to decrypt the teams license in AIX machine

### ISSUE THREAD

**Issue by indubryt23** [flyway/flyway#3421]
###### Which version and edition of Flyway are you using?

8.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)

Oracle-19c

###### Which operating system are you using?

AIX

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I am using community version of flyway on my AIX machine. Recently I have upgraded to the teams version of flyway and I tried executing my flyway using the license, but I get **"unble to decrypt the license error".**
Later I asked the redgate support an they asked me to use the jre provided within the flyway package instead of the one that is available in the server. After using the jre in the flyway I got **"/jre/bin/java: cannot execute binary file: Exec format error"**
###### What did you expect to see?

Flyway successfully migrated the sql scripts

###### What did you see instead?

License error.

**Comment by Barry-RG** [comment]
Could you please check that you have downloaded the Linux tar.gz for Flyway?
Additionally, could you please check and let us know which architect your system is using? I.E. is it an AMD x64 system?

**Comment by indubryt23** [comment]
Hi Barry,

Yes, I have downloaded flyway linux tar.gz.
Below is my system configuration:

System Model : IBM 8284-22A
Processor Type : PowerPC_POWER8
Processor Implementation Mode : POWER 8
CPU Type : 64 bit
Kernel Type : 64 bit

**Comment by Barry-RG** [comment]
It looks like the version of Java shipped with Flyway does not support POWER8.

Would you be able to try using the [Flyway Docker image](https://hub.docker.com/r/flyway/flyway)? This should hopefully run Flyway in the Java environment it requires.

**Comment by DoodleBobBuffPants** [comment]
Hi,

We will be closing this issue as official Customer Support is handling it

Thanks
