### ISSUE TITLE
Execute multiple sql script into flyway with same version sql file

### ISSUE THREAD

**Issue by nikhilpatiltest** [flyway/flyway#3423]
###### Which version and edition of Flyway are you using?
I am using flyway version 7.2.2 as the maven dependency in java spring MVC 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven Plugin

###### Which database are you using? (Type & version)
MYSQL 8.0.26

###### Which operating system are you using?
Windows 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I want to execute multiple SQL queries using flyway with the same version file.

###### What did you expect to see?
 My requirement is that I only execute one single SQL file and my database is going to update always. so I want to update in the same version SQL file 
 I want only one SQL file and when I migrate then it successfully migrate the SQL file as well as when I again migrate a new script then it successfully migrates it but all of these processes do in a single script.

Any leads will be appreciated.
Thanks in Advance.
@axelfontaine @Barry-RG

**Comment by Barry-RG** [comment]
Apologies, we are having difficulties understanding your problem.
Would you be able to produce a reproduction project and step by step instructions as to how to create the issue you wish to resolve?

**Comment by emmadavis16** [comment]
> Apologies, we are having difficulties understanding your problem. Would you be able to produce a reproduction project and step-by-step instructions as to how to create the issue you wish to resolve?

Thanks for the reply.
Steps for reproduction:-
1) **V1_1__add_user.sql** when I add the queries in this file and use the flyway migrate through maven.
it works
2) but when I add more queries in the same **V1_1__add_user.sql**  file and use flyway migrate through maven it's not working
so can we use the same **V1_1__add_user.sql**   file always for updating and add queries in same file and doing flyway migrate 

##Which version and edition of Flyway are you using?
I am using flyway version 7.2.2 as the maven dependency in java spring MVC

##Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven Plugin

##Which database are you using? (Type & version)
MYSQL 8.0.26

##Which operating system are you using?
Windows 11
