### ISSUE TITLE
Spaces in path to jar end in "Unable to obtain inputstream for resource" error 

### ISSUE THREAD

**Issue by StevenPohl-Uhe** [flyway/flyway#3424]
###### Which version and edition of Flyway are you using?
8.5.5 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
it is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
MySQL Community 8.0.28

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
try to run a migration within a path that contains spaces

###### What did you expect to see?
a working migration

###### What did you see instead?
`org.flywaydb.core.api.FlywayException: Unable to obtain inputstream for resource`

As far as I have seen, in `ClassPathResource.read()`, the comparison between the enumeration element and `this.parentURL` fails, because the parentURL keeps the space in its string while the enumeration element replaces the space with "%20".

Best regards,
Steven Pohl-Uhe

**Comment by tjs145** [comment]
We're closing this issue until further activity
