### ISSUE TITLE
Flyway seems to be skipping my version files

### ISSUE THREAD

**Issue by Octacon100** [flyway/flyway#3426]
###### Which version and edition of Flyway are you using?

6.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I'm not able to connect to Sql Server 2016 with the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command Line.

###### Which database are you using? (Type & version)

Sql Server 2016

###### Which operating system are you using?

Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I'm trying to run a flyway validate, but my files are being skipped. Attached is a basic debug log. I've tried using files that have worked in the past as well, but they are not getting picked up.

###### What did you expect to see?

Some validation happen.

###### What did you see instead?

Here's my debug log:

.\flyway "-url=jdbc:sqlserver://[servername]:1433;databaseName=[databasename];integratedSecurity=true;encrypt=false" validate -X
DEBUG: Loading config file: C:\Agent\_work\_tool\flyway\6.2.4\x64\conf\flyway.conf
DEBUG: Unable to load config file: C:\Users\nlow\flyway.conf
DEBUG: Unable to load config file: C:\Agent\_work\_tool\flyway\6.2.4\x64\flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> C:\Agent\_work\_tool\flyway\6.2.4\x64\jars
DEBUG: flyway.locations -> filesystem:C:\Agent\_work\_tool\flyway\6.2.4\x64\sql
DEBUG: flyway.repeatableSqlMigrationPrefix -> R
DEBUG: flyway.sqlMigrationPrefix -> V
DEBUG: flyway.url -> jdbc:sqlserver://[servername]:1433;databaseName=[databasename];integratedSecurity=true;encrypt=false
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\derby-10.15.1.3.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\derbyclient-10.15.1.3.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\derbyshared-10.15.1.3.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\derbytools-10.15.1.3.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\h2-1.4.200.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\hsqldb-2.5.0.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\jaybird-jdk18-3.0.6.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\jna-4.5.2.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\jtds-1.3.1.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\mariadb-java-client-2.4.0.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\mssql-jdbc-7.2.2.jre8.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\mysql-connector-java-8.0.17.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\ojdbc8-18.3.0.0.0.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\postgresql-42.2.8.jre6.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\snowflake-jdbc-3.11.1.jar
DEBUG: Adding location to classpath: C:\Agent\_work\_tool\flyway\6.2.4\x64\drivers\sqlite-jdbc-3.23.1.jar
Flyway Community Edition 6.2.4 by Redgate
DEBUG: Scanning for filesystem resources at 'C:\Agent\_work\_tool\flyway\6.2.4\x64\sql'
DEBUG: Scanning for resources in path: C:\Agent\_work\_tool\flyway\6.2.4\x64\sql (C:\Agent\_work\_tool\flyway\6.2.4\x64\sql)
DEBUG: Found filesystem resource: C:\Agent\_work\_tool\flyway\6.2.4\x64\sql\V1_1__test.sql
Database: jdbc:sqlserver://[servername]:1433;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=[databasename];columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 13.0)
DEBUG: Driver  : Microsoft JDBC Driver 7.2 for SQL Server 7.2.2.0
DEBUG: DDL Transactions Supported: true
DEBUG: Schemas:
DEBUG: Default schema: null
DEBUG: Scanning for SQL callbacks ...
DEBUG: Filtering out resource: C:\Agent\_work\_tool\flyway\6.2.4\x64\sql\V1_1__test.sql (filename: V1_1__test.sql)
DEBUG: Memory usage: 15 of 256M
ERROR: Unexpected error
java.lang.NullPointerException
        at org.flywaydb.core.internal.util.StringUtils.replaceAll(StringUtils.java:154)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerDatabase.escapeIdentifier(SQLServerDatabase.java:165)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerDatabase.doQuote(SQLServerDatabase.java:170)
        at org.flywaydb.core.internal.database.base.Database.quote(Database.java:280)
        at org.flywaydb.core.internal.database.base.Schema.toString(Schema.java:267)
        at java.base/java.lang.String.valueOf(Unknown Source)
        at java.base/java.lang.StringBuilder.append(Unknown Source)
        at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:115)
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:273)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:73)
        at org.flywaydb.core.Flyway$2.execute(Flyway.java:252)
        at org.flywaydb.core.Flyway$2.execute(Flyway.java:245)
        at org.flywaydb.core.Flyway.execute(Flyway.java:521)
        at org.flywaydb.core.Flyway.validate(Flyway.java:245)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:178)
        at org.flywaydb.commandline.Main.main(Main.java:126)

**Comment by DoodleBobBuffPants** [comment]
Could you try the latest version of Flyway? The logs show you are using 6.2.4 and this is similar to a bug that we have already fixed

**Comment by DoodleBobBuffPants** [comment]
Closing till further activity
