### ISSUE TITLE
Only "flyway_schema_history" table and I don't find my tables in the DB - Flyway | pgadmin | Quarkus

### ISSUE THREAD

**Issue by Bilel-NEJI** [flyway/flyway#3429]
Hi everybody, Hi @axelfontaine ,
I'm using Flyway and pgadmin for the 1st time. I don't get my tables inside the created DB (PostgreSQL docker container pgadmin4) with Quarkus.
The only table that I had is the "flyway_schema_history" !!!

how can I fix those errors and get my asked tables ? thanks

###### Which version and edition of Flyway are you using?

        implementation group: 'io.quarkus', name: 'quarkus-flyway', version: '2.8.0.Final'
        implementation group: 'io.quarkus', name: 'quarkus-jdbc-postgresql', version: '2.8.0.Final'
        implementation group: 'org.postgresql', name: 'postgresql', version: '42.3.3'
        implementation("io.quarkus:quarkus-flyway")
        implementation("org.flywaydb:flyway-sqlserver")
        implementation("io.quarkus:quarkus-jdbc-postgresql")

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

-> I'm using Gradle
-> I'm using PostgreSQL -> docker container pgadmin4
-> I'm using Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
in the "V1__CREATE_DATABASE.sql" file

       CREATE TABLE DomesticDeviceInfoOutMiTO
       (
           miDeviceId INT NOT NULL PRIMARY KEY,
           deviceName VARCHAR(30) NOT NULL,
           deviceState INT,
           deviceSType INT,
           deviceTemperature INT,
       );

       CREATE TABLE issue
       (
           requestId   INT NOT NULL PRIMARY KEY,
           subject     VARCHAR(30) NOT NULL,
           description VARCHAR(200),
           timestamp   TIMESTAMP,
           status      VARCHAR DEFAULT 'OPEN',
           lastUpdate  TIMESTAMP,
       );

in the "docker-compose.yml" file:

       quarkus.datasource.db-kind= postgresql
       quarkus.datasource.username= username
       quarkus.datasource.password= password
       quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/db-mcs-thirdparty
       quarkus.flyway.migrate-at-start=true
       quarkus.flyway.baseline-on-migrate=true
       quarkus.flyway.out-of-order=true
       quarkus.flyway.baseline-version=1

###### What did you expect to see?
-> I expect to see the tables writen in my script file: two tables & a running application in DevMode without errors
-> I see instead:
--------> a "flyway_schema_history" table created in the DB
![pgadmin-01](https://user-images.githubusercontent.com/84474060/162746731-491bc91c-d261-4936-8b6b-ac215b104e79.jpg)

--------> errors in my git-bash
![issue pgadmin](https://user-images.githubusercontent.com/84474060/162749128-2870184d-325c-4adc-9340-d3eb3bb66de8.gif)

**Comment by tjs145** [comment]
Looks like a  SQL problem. 

It seems to work if you remove the trailing commas.
