### ISSUE TITLE
The Chocolatey Distribution for Flyway  is very sporadic- Flyway (at the time of writing this)  is now on version 8.5.8 rather than 8.3.0

### ISSUE THREAD

**Issue by Phil-Factor** [flyway/flyway#3434]
###### Which version and edition of Flyway are you using? 
8.3.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Wish I could, via Chocolatey

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
PostgreSQL, MySQL, SQL Server, sqlITE

###### Which operating system are you using?
Win dows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Cup  flyway.commandline #in PowerShell

###### What did you expect to see?
Flyway upgraded to the latest version

###### What did you see instead?
it reports nothing to upgrade
Chocolatey is currently the best way of installing apps and keeping them up to date on Windows. It means that you can update everything in one PowerShell command.  C'mon- every DevOps person knows this!  Each distribution is managed by Volunteers and occasionally a package gets out of date because of life events for that particular volunteer. The trouble is that we end-users aren't aware of getting out-of-date. Even if we did,  Flyway doesn't have its own Windows install that adds or modifies the path command and so on.   It would increase Flyway's popularity and attractiveness on the windows platform if we  could keep the Chocolatey distribution current.  I've contacted the current volunteers but without much hope. The number of people using the Chocolatey distribution of Flyway has declined since its maintenance has become sporadic.

**Comment by Barry-RG** [comment]
Chocolaty is not an officially supported distribution method for Flyway. 

As Flyway supports multiple operating systems, not just Windows, and a Java application we do not supply a Windows only installer at this time or use unofficial 3rd party package managers. It supplies scripts that can be executed on multiple operating systems in a similar way for consistency.

As the package in question is published by a volunteer unaffiliated with Flyway, I suggest you either wait for their response or build upon their scripts for your own distribution.

**Comment by madninjaskillz** [comment]
You should be able to submit a pull request to the following file:
https://github.com/Roemer/chocolatey-packages/blob/master/build.cake
I believe only the version number on line 37 needs altering to bring it up to date.

**Comment by Phil-Factor** [comment]
I'm a bit puzzled by your response. The chocolatey distribution is actually listed on the redgate Flyway  site as being supported. I've just re-checked.  How can you say it is not officially supported?  I must have misunderstood your other point. I cannot imagine that any other  Flyway Teams Licensee would like the idea that 'we do not supply a Windows only installer at this time'.  Flyway Teams is supported by Redgate for use on Windows, surely? The general distribution is a manual process. That  might be OK for once-a-year releases but not for a professional licensed product advertised for Windows, with the release rate Flyway does.  It would be so simple for you to assist the Chocolatey distribution.

**Comment by Barry-RG** [comment]
Please see our [Community Plugins and Integrations](https://flywaydb.org/documentation/usage/plugins/) in regards to our relationship with Chocolatey. This is maintained by the broader Flyway community and is primarily for the community edition of Flyway. This is not the same as official support but simply highlighting community members work.  As a result, I suggest you either raise an issue or a PR on the community members repository who maintains that Chocolatey package.

**Comment by Phil-Factor** [comment]
Just giving my advice here. A busy Windows Devops professional doing commercial work hasn't the time to do a manual upgrade of all the packages they use, especially with a tool like Flyway that changes so often.  There are just too many required tools.  They use Chocolatey, type CUP ALL in PowerShell and everything is upgraded in one go.
