### ISSUE TITLE
Preserve underscores in flyway_schema_history description

### ISSUE THREAD

**Issue by savinov** [flyway/flyway#3435]
###### Which version and edition of Flyway are you using?
8.5.8

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
It's the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)
PostgreSQL

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run migration with filename: V1__Create_customer_profile_table.sql

###### What did you expect to see?
I expect to get in description column of flyway_schema_history table: 'Create customer_profile table'
So I want to preserve customer_profile table name with underscore in it somehow.
Maybe escape character should be used or some naming convention to seperate words and table names with spaces.

###### What did you see instead?
Description column of flyway_schema_history table: 'Create customer profile table'

#############################
This issue relates to the feature request: https://github.com/flyway/flyway/issues/757
Providing description in SQL comment would be a nice feature which solves this problem.
That's current implementation which replaces all the underscores with spaces: https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/resolver/MigrationInfoHelper.java#L58

**Comment by tjs145** [comment]
What's the importance of preserving the underscores?

We're closing this issue until it has further interest.

**Comment by savinov** [comment]
> What's the importance of preserving the underscores?
Table names with underscores are incorrect in description of flyway_schema_history.
Expected: 'Create customer_profile table'
Actual: 'Create customer profile table'
I think that's important.

**Comment by faelin** [comment]
I have the same need, I would like to include underscores in my descriptions in order to refer to SQL elements such as tables. Perhaps a solution would be to swap all `-` for `_`? (e.g. `Create_customer-profile_table` becomes `Create customer_profile table`)
