### ISSUE TITLE
Create, Use, Drop 52-char UUID schema at end of migration

### ISSUE THREAD

**Issue by mcstafford-git** [flyway/flyway#3436]
###### Which version and edition of Flyway are you using?
8.0.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Haven't tried.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MySQL 5.6

###### Which operating system are you using?
Ubuntu 16.04/xenial

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Run misc. migrations, notice an addition that seems potentially unnecessary.

###### What did you expect to see?
I expected the process to end with `SELECT RELEASE_LOCK('Flyway--1739861824')`.

###### What did you see instead?
CREATE SCHEMA `97ddeaba-e41e-4558-808a-d21130857eac`;
USE `97ddeaba-e41e-4558-808a-d21130857eac`;
DROP SCHEMA `97ddeaba-e41e-4558-808a-d21130857eac`;

I'd like to know what purpose this serves and whether it's configurable.

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising this issue

This is SQL we execute internally to unset the current schema ([code](https://github.com/flyway/flyway/blob/master/flyway-mysql/src/main/java/org/flywaydb/database/mysql/MySQLConnection.java#L125))

We likely won't make any changes unless others have issues with this too, or there's a sensible alternative now (see [this](https://stackoverflow.com/questions/27895328/how-do-you-deselect-mysql-database))

**Comment by the-rockkk** [comment]
This is an issue when a user has CREATE SCHEMA permission but not DROP SCHEMA. It leave dangling schemas hanging around.
