### ISSUE TITLE
Unused boolean in flyway-core FileSystemResource

### ISSUE THREAD

**Issue by CelPyn** [flyway/flyway#3447]
###### Which version and edition of Flyway are you using?
8.5.11

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
N/A

###### Which operating system are you using?
N/A

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
N/A

###### What did you expect to see?
Backwards compatible constructor for [FileSystemResource](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/resource/filesystem/FileSystemResource.java).

###### What did you see instead?
FileSystemResource has a required boolean argument which is not used in the class.
When bumping from an older version, where this argument was not present, you'll encounter a compilation failure.

Instantiating this class requires you to set a boolean flag, which does nothing.
Either documentation on what the boolean flag does or might do in the future, or removal of the argument seems desirable.

**Comment by DoodleBobBuffPants** [comment]
This class is in the `internal` package which doesn't make any API guarantees, and instead we ask you to only use what's in the `api` package
