### ISSUE TITLE
Expect beforeConnect callback to be included in dryRun output

### ISSUE THREAD

**Issue by ben-peacock-uk** [flyway/flyway#3450]
###### Which version and edition of Flyway are you using?
8.4.2 Teams (trial)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven

###### Which database are you using? (Type & version)
Oracle 19

###### Which operating system are you using?
MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Trying to create an SQL Script with dry run that can be run via SQL*Plus and connect to database

Create beforeConnect.sql callback file to include an Oracle SQL*Plus Connect statement
Run mvn flyway:migrate with dryRunOutput set

###### What did you expect to see?
Content of beforeConnect.sql included at top of dry run output file

###### What did you see instead?
Content of beforeConnect.sql not present in dry run output

Workaround is to include connect in beforeValidate.sql, but this results in error when file is run due to preceding ALTER SESSION. Error can be ignored but we don't want errors.

Other workaround is to connect to db outside of script.

**Comment by tjs145** [comment]
Unfortunately the `beforeConnect` callback can't be used for `.sql` migrations as no connection has been made to the database at that point, so it can only be used for script migrations. It's possible that your current workarounds might be the  best option.
