### ISSUE TITLE
insufficient memory for the Java Runtime issue 

### ISSUE THREAD

**Issue by yinyi-fan-zocdoc** [flyway/flyway#3457]
###### Which version and edition of Flyway are you using?
The latest version which is updated 8 hours ago, when we used TeamCity Build, in artifacts log, we can see this error:
```
[0.002s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /flyway/hs_err_pid12.log
```
We use docker command - `docker run -m 4g...` so we have to point to the previous version and we don't see the above error ^^ anymore. But it could be only a temporary solution for us please help investigate into that. The task we were building is just a simple SQL script for creating views in our snowflake database

**Comment by yinyi-fan-zocdoc** [comment]
we use previous version 8.5.11 and it worked. The latest version 8.5.12 (correct me if I am wrong) which is updated 8 hours ago is not working

**Comment by vsobic** [comment]
We have the same issue that started to occur yesterday by using https://github.com/marketplace/actions/flyway-migration GitHub Action **Flyway Migration**. Can you please, take a look and resolve this issue?

**Comment by crablab** [comment]
We're also seeing this breaking pipelines, as we pull `latest` starting 

Downgrading to 8.5.11.

**Comment by Barry-RG** [comment]
Would you be able to give us the RAM size Docker has access to so we can compare it to our benchmarks?

**Comment by vsobic** [comment]
In our case we tried with 2GB, 4GB and 8GB with no luck. Docker image is : flyway/flyway:8

FYI [Barry-RG](https://github.com/Barry-RG)

**Comment by Barry-RG** [comment]
Do you have any large [repeatable](eclipse-temurin:11-jre) scripts in your migrations?

**Comment by vsobic** [comment]
We don't use repeatable migrations. Our biggest script is 156kb huge(create db structure and set some initial data). 

FYI [Barry-RG](https://github.com/Barry-RG)

**Comment by Barry-RG** [comment]
It does look like the underline base image has changed so we will investigate. 
Can you also check if you get the same issue then with flyway/flyway:8-alpine?

**Comment by vsobic** [comment]
With Docker image `flyway/flyway:8-alpine` it's working...no issue then...to conclude Docker image `flyway/flyway:8` is broken.

FYI [Barry-RG](https://github.com/Barry-RG)

**Comment by BernhardPosselt** [comment]
We've encountered the same issue with another docker build on BitBucket Pipelines btw. Unrelated to flyway, we were also able to fix it by downgrading the jre/jdk

**Comment by vsobic** [comment]
We are using Github Action for Flyway and currently it's not so easy to try this with Dockerfile. Maybe some other people with more power/freedom in their hands in terms of pipeline like [Pierozi](https://github.com/Pierozi) or [yinyi-fan-zocdoc](https://github.com/yinyi-fan-zocdoc) ?

FYI [Barry-RG](https://github.com/Barry-RG)

**Comment by DoodleBobBuffPants** [comment]
The issue seemed to be in the base image which we use for the JRE
We've downgraded the version to what it was in the last release

**Comment by alexbde** [comment]
Hi! Just leaving a quick note: I saw you fixed this by switching from `eclipse-temurin:11-jre` to `eclipse-temurin:11.0.14.1_1-jre`. The root cause of the issue seems to be the upgrade from `ubuntu:focal` to `ubuntu:jammy` under the hood. Switching to `eclipse-temurin:11-jre-focal` fixed the issue for us without pinning a patch version.

**Comment by DoodleBobBuffPants** [comment]
@alexbde Thanks for letting us know! I've made a corresponding [issue](https://github.com/flyway/flyway-docker/issues/88) in [flyway/flyway-docker](https://github.com/flyway/flyway-docker) to track this

**Comment by holgerstolzenberg** [comment]
Same for us in another context but the key info here is that we switched our Temurin based JDK `eclipse-temurin:17.0.3_7-jre` to a focal based image `eclipse-temurin:17.0.3_7-jre-focal`.
