### ISSUE TITLE
Flyway Spring Boot Integration - Pod Hanging Issue

### ISSUE THREAD

**Issue by BulandMalik** [flyway/flyway#3458]
###### Which version and edition of Flyway are you using? 
Flyway Community Edition 5.2.4 by Boxfuse.

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
We are using Spring boot version that uses BOM and bring Flyway 5.2.4 version and though we tested it out with more latest/older flyway version but app start up fails due to class mismatch etc.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin). 
We are using Spring Boot + Flyway integration pattern (Spring Boot: 2.1.6 Flyway DB: 5.2.4 Postgress: 42.2.5)

###### Which database are you using? (Type & version)
Postgress: **42.2.5**

###### Which operating system are you using?
Our application runs in K8s so its Linux based.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We are trying to integrate Flyway with our Spring Boot apps. Its working fine for bunch of services but for one service it always brings up all pods except one (we have 3 replica pods for K8s). Weird thing is that in the logs nothing is available, even we enabled DEBUG for our app but application logs only shows Flyway Community Edition 5.2.4 by Boxfuse. We have been trying to trouble shoot this issue but without any logs its almost impossible to do the root cause analysis. There are no errors/exceptions in the logs and logs just hangs after logging above Flyway version log. Also for most of the time, some pods comes up fine while other (mostly 1 out of 3) just hangs and once noticed it becomes healthy after 40 mins or so. Not sure what is going on as went through lot of documentation without any luck.

We are using following versions.

Spring Boot: 2.1.6 Flyway DB: 5.2.4 Postgress: 42.2.5

Any pointers are appreciated.

###### What did you expect to see?
We want deployment to go fine and pod comes up without issue but we do not see that happening.

###### What did you see instead?
We are seeing that POD hangs out and no logs happens. We even enabled DEBUG and after logging Flyway version, it just hangs and hangs there till we kill it. It seems like that after  that flyway version log statement is where the Hikari datasource starts so we do not see any logs in the hung up pod. so seems like some locking or something related to that an issue. We are using JDBC Spring configs to be reused for flyway url/user/pass as we are not setting them specifically

**Comment by DoodleBobBuffPants** [comment]
In older versions of Flyway, there have been known issues with using multiple instances of Flyway targeted at PostgreSQL

We would first recommend upgrading to the latest version of Flyway to see if your issue hasn't already been resolved

**Comment by BulandMalik** [comment]
Thanks @DoodleBobBuffPants. Our problem is that we have 10+ microscopes using Spring boot version that brings flyway 5.2.4. As its a managed dependency so if we only try to bring latest flyway version, we are getting lot of errors and changing spring boot version is a tedious task as we have to change lot of libraries and dependencies as well as in few places code base within services.

Anyway we can still use latest flyway latest version with older spring boot version?

**Comment by DoodleBobBuffPants** [comment]
I don't think you'll be able to use the latest version of Flyway with older versions of Spring Boot

You can alternatively use Flyway directly and not through Spring Boot, if this makes updating easier

As there's nothing we can look into at the minute, I'll be closing this issue until further activity
