### ISSUE TITLE
not able to get secrets from vault by using vault plugins

### ISSUE THREAD

**Issue by parellark** [flyway/flyway#3459]
fallowed as per the documentation from vault integration , but still flyway is not getting the flywayconfigs from vault

**Comment by DoodleBobBuffPants** [comment]
Could you provide more information?
What was your configuration? Can you provide a reproduction?

**Comment by parellark** [comment]
these are configs i have added in flyway.conf
flyway.plugins.vault.url=xxxxxx
flyway.plugins.vault.token=xxxxx
flyway.plugins.vault.secrets=flyway/flyway/configerationTest

these are i have placed in vault under secret name "configerationTest", 
flyway.url=xxxxxx
flyway.user=xxxxx
flyway.password=xxxx

flyway/flyway/  these are the secret engine and path in vault.

now iam able to run the command ./flyway migrate but getting error 
" ERROR: Unable to connect to the database. Configure the url, user and password! "

but all of the credentials are true.

**Comment by DoodleBobBuffPants** [comment]
Can you confirm that you are using Flyway Teams Edition?
Could you also confirm your Flyway version?
Could you run Flyway with `-X` to get debug output and share that too?

**Comment by parellark** [comment]
NO, i am not using teams edition
DEBUG: Loading config file: /home/ec2-user/flyway/flyway-8.5.12/conf/flyway.conf
DEBUG: Unable to load config file: /home/ec2-user/flyway.conf
DEBUG: Unable to load config file: /home/ec2-user/flyway/flyway-8.5.12/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.baselineOnMigrate -> true
DEBUG: flyway.baselineVersion -> 1.0.0
DEBUG: flyway.jarDirs -> /home/ec2-user/flyway/flyway-8.5.12/jars
DEBUG: flyway.locations -> filesystem:sql
DEBUG: flyway.plugins.vault.secrets -> flyway/flyway/credentialsTest
DEBUG: flyway.plugins.vault.token -> xxxxx
DEBUG: flyway.plugins.vault.url -> xxxxxx
DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@5a4041cc ...
DEBUG: Unable to resolve location classpath:db/callback
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
        at org.flywaydb.core.internal.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:36)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:112)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:272)
        at org.flywaydb.commandline.Main.main(Main.java:181)


iam using flyway VERSION    " flyway-8.5.12"

**Comment by DoodleBobBuffPants** [comment]
The Vault integration is only available in the Teams Edition

If you're interested in trying it, you can get a trial key from [here](https://flywaydb.org/download/teams)

If you choose to use it, do let us know how you get on and leave any feedback here
