### ISSUE TITLE
Header comment on stored procedure removed

### ISSUE THREAD

**Issue by bujocek** [flyway/flyway#3460]
###### Which version and edition of Flyway are you using?
6.5.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
testing in progress (v8.5.12) 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command line

###### Which database are you using? (Type & version)
Microsoft SQL Server 15.0.4123.1

###### Which operating system are you using?
Windows Server 2019 Standard (10.0)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

create/alter procedure with a header comment
```
/**
<commitmessage>Documentation</commitmessage>
<summary>Adds shipmentpackage to test case</summary>
<param name="@DropshipTestCase_ID">Related test case</param>

<author>Abc Def</author>
<lang code="EN" doc="EN" msg="EN"/>

<test><![CDATA[

  EXEC k2.Dropship_TestCasePackage_INSERT

]]></test>
*/

CREATE OR ALTER PROCEDURE k2.Dropship_TestCasePackage_INSERT
  @DropshipTestCase_ID INT
AS
BEGIN
...procedure body...
END
```

###### What did you expect to see?

Procedure including header comment on the SQL server. As discussed here: https://github.com/flyway/flyway/issues/1362 the unwanted comment removal should be fixed. But in our case the comments are still removed.

###### What did you see instead?

Procedure without the comment section.

**Comment by bujocek** [comment]
I am still gathering information for the issue description and I will fill them in shortly.

**Comment by bujocek** [comment]
Thank you for the reproduction attempt. We will be testing it in our system in the next sprint so please give us up to two weeks for the feedback. I'll get back to you as soon as I know the test results.

**Comment by DoodleBobBuffPants** [comment]
We'll be closing this till further activity, but happy to reopen once we have a reproduction
