### ISSUE TITLE
Pre and post deploy migrations

### ISSUE THREAD

**Issue by Francismb** [flyway/flyway#3463]
Hi all, I have been looking into how we can run some migrations before a service deployment and a few others after a deployment. For example, if you are adding a new column which your service relies on, it makes sense to run this before deploying your service which utilises this column. The same is true for removal of columns, it makes more sense to run that migration once your service has stopped using the column, post deploy.

Not sure where the best place was to post a feature request/ask if this exists? Thanks anyway!

###### Which version and edition of Flyway are you using?
v8.5.11

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Docker

###### Which database are you using? (Type & version)
Postgres

**Comment by DoodleBobBuffPants** [comment]
Would [`callbacks`](https://flywaydb.org/documentation/concepts/callbacks) (`beforeMigrate` for example) work?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
