### ISSUE TITLE
JDBC Url not interpreted as expected Oracle 19c

### ISSUE THREAD

**Issue by jeanremacle** [flyway/flyway#3465]
###### Which version and edition of Flyway are you using?

Version 8.5.11 edition Community

 

 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

 

 

###### Which database are you using? (Type & version)

Oracle EE 19.14 ExaCC (Engineered System)

 

 

###### Which operating system are you using?

Linux 7.9

 

 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We are using the following as the jdbc url:

flyway.url=jdbc:oracle:oci:[RAS_MGT]/@PDBD_BDWH_TESTUPGRAD

 

 

###### What did you expect to see?

We expect to use impersonation with a user stored in a wallet and be connected as RAS_MGT. In the Oracle realm this is also known as proxy user

 

 

###### What did you see instead?

We are connected as the wallet user

In the log, it says connected as [RAS_MGT]

 

I have the impression that in previous versions of Flyway it was working as expected. This is a base functionality of Oracle

**Comment by DoodleBobBuffPants** [comment]
I believe this is being handled by product support now, so closing the ticket here
