### ISSUE TITLE
Support h2 2.1.214

### ISSUE THREAD

**Issue by hackyoMa** [flyway/flyway#3467]
###### Which version and edition of Flyway are you using?
8.5.12

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
h2 2.1.214

###### Which operating system are you using?
macos 12.4

###### What did you expect to see?
support h2 2.1.214

###### What did you see instead?
Flyway upgrade recommended: H2 2.1.214 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.1.210.

**Comment by DoodleBobBuffPants** [comment]
Closed by https://github.com/flyway/flyway/commit/8ff341eaddb18e6adcd0c6922c0978225dccda15
