### ISSUE TITLE
Upgrading Flyway-core to above versions 8.2 not supporting MariaDB

### ISSUE THREAD

**Issue by kappaj2** [flyway/flyway#3470]
###### Which version and edition of Flyway are you using?

Was using 8.0.5 - upgrading to 8.5.13

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

The latest version 8.5.13 is broken. Downgraded to 8.5.10 - still broken

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java Client from Maven plugin - version 3.0.3
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>

###### Which database are you using? (Type & version)
MariaDB 10.6

###### Which operating system are you using?
MacOS Monterey 12.4

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Upgrading Flyway from 8.0.5 to the latest so we can upgrde SpringBoot to 2.7.0

Now getting the following exception:

Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: MariaDB 10.6
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:106)

Debugging the following class:
package org.flywaydb.core.internal.database;
DatabaseTypeRegister and method getDatabaseTypeForConnection(Connection connection):
    SORTED_DATABASE_TYPES.iterator();
List's only the following supported DB types:

result = {ArrayList@9541}  size = 15
 0 = {CockroachDBDatabaseType@9603} 
 1 = {RedshiftDatabaseType@9604} 
 2 = {DB2DatabaseType@9605} 
 3 = {DerbyDatabaseType@9606} 
 4 = {H2DatabaseType@9607} 
 5 = {HSQLDBDatabaseType@9608} 
 6 = {InformixDatabaseType@9609} 
 7 = {OracleDatabaseType@9610} 
 8 = {PostgreSQLDatabaseType@9611} 
 9 = {SAPHANADatabaseType@9612} 
 10 = {SnowflakeDatabaseType@9613} 
 11 = {SQLiteDatabaseType@9614} 
 12 = {SybaseASEJConnectDatabaseType@9615} 
 13 = {SybaseASEJTDSDatabaseType@9616} 
 14 = {TestContainersDatabaseType@9617}

This is the supported list in 8.4.0 - also broken
result = {ArrayList@9512}  size = 16
 0 = {CockroachDBDatabaseType@9574} 
 1 = {RedshiftDatabaseType@9575} 
 2 = {DB2DatabaseType@9576} 
 3 = {DerbyDatabaseType@9577} 
 4 = {FirebirdDatabaseType@9578} 
 5 = {H2DatabaseType@9579} 
 6 = {HSQLDBDatabaseType@9580} 
 7 = {InformixDatabaseType@9581} 
 8 = {OracleDatabaseType@9582} 
 9 = {PostgreSQLDatabaseType@9583} 
 10 = {SAPHANADatabaseType@9584} 
 11 = {SnowflakeDatabaseType@9585} 
 12 = {SQLiteDatabaseType@9586} 
 13 = {SybaseASEJConnectDatabaseType@9587} 
 14 = {SybaseASEJTDSDatabaseType@9588} 
 15 = {TestContainersDatabaseType@9589} 
 
 Version 8.2.0 is correct:
 
 result = {ArrayList@9513}  size = 18
 0 = {CockroachDBDatabaseType@9575} 
 1 = {RedshiftDatabaseType@9576} 
 2 = {MariaDBDatabaseType@9577} 
 3 = {DB2DatabaseType@9578} 
 4 = {DerbyDatabaseType@9579} 
 5 = {FirebirdDatabaseType@9580} 
 6 = {H2DatabaseType@9581} 
 7 = {HSQLDBDatabaseType@9582} 
 8 = {InformixDatabaseType@9583} 
 9 = {MySQLDatabaseType@9584} 
 10 = {OracleDatabaseType@9585} 
 11 = {PostgreSQLDatabaseType@9586} 
 12 = {SAPHANADatabaseType@9587} 
 13 = {SnowflakeDatabaseType@9588} 
 14 = {SQLiteDatabaseType@9589} 
 15 = {SybaseASEJConnectDatabaseType@9590} 
 16 = {SybaseASEJTDSDatabaseType@9591} 
 17 = {TestContainersDatabaseType@9592} 
###### What did you expect to see?
Expected to see MariaDB in the list of databases.

This is the list of supported DB's in version 8.0.5 - debugging the above mentioned class

result = {ArrayList@9518}  size = 20
 0 = {CockroachDBDatabaseType@9580} 
 1 = {RedshiftDatabaseType@9581} 
 2 = {MariaDBDatabaseType@9517} 
 3 = {SynapseDatabaseType@9582} 
 4 = {DB2DatabaseType@9583} 
 5 = {DerbyDatabaseType@9584} 
 6 = {FirebirdDatabaseType@9585} 
 7 = {H2DatabaseType@9586} 
 8 = {HSQLDBDatabaseType@9587} 
 9 = {InformixDatabaseType@9588} 
 10 = {MySQLDatabaseType@9589} 
 11 = {OracleDatabaseType@9590} 
 12 = {PostgreSQLDatabaseType@9591} 
 13 = {SAPHANADatabaseType@9592} 
 14 = {SnowflakeDatabaseType@9593} 
 15 = {SQLiteDatabaseType@9594} 
 16 = {SQLServerDatabaseType@9595} 
 17 = {SybaseASEJConnectDatabaseType@9596} 
 18 = {SybaseASEJTDSDatabaseType@9597} 
 19 = {TestContainersDatabaseType@9598} 

###### What did you see instead?
Unsupported database type error.
Seems like MariaDB is dropped in totality.

**Comment by tjs145** [comment]
Since [version 8.2.1](https://flywaydb.org/documentation/learnmore/releaseNotes#8.2.1), the [`flyway-mysql` package](https://mvnrepository.com/artifact/org.flywaydb/flyway-mysql) has to be added separately as well as `flyway-core`. This includes the relevant `DatabaseType` for MariaDB, so it should then appear in the list.

**Comment by kappaj2** [comment]
Wow - missed that one! Thank you very much. Working like a dream when adding that. Appreciate!
