### ISSUE TITLE
"no rows updated" reported for DDL statements with Oracle SQL*Plus

### ISSUE THREAD

**Issue by ben-peacock-uk** [flyway/flyway#3473]
###### Which version and edition of Flyway are you using?
Flyway Teams Edition 8.5.13 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven

###### Which database are you using? (Type & version)
Oracle 19

###### Which operating system are you using?
Mac OS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
login.sql:
SET ECHO ON

V1_change.sql:
INSERT INTO my_table (col, my_row) VALUES ('COL', 'ROW');
GRANT SELECT ON my_table TO my_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON my_other_table  TO my_user;

R_my_view.sql:
CREATE OR REPLACE VIEW my_view AS
SELECT col FROM my_table WHERE my_row = 'UPDATE';

Ran mvn flyway:migrate -Dflyway.oracleSqlPlus=true

###### What did you expect to see?
[INFO] Migrating schema "my_schema" to version "1 - change"
[INFO] SQL> INSERT INTO my_table (col, my_row) VALUES ('COL', 'ROW');
[INFO] 1 row updated
[INFO] SQL> GRANT SELECT ON my_table TO my_user;
[INFO] SQL> GRANT SELECT, INSERT, UPDATE, DELETE ON my_other_table  TO my_user;
[INFO] Migrating schema "my_schema" with repeatable migration "my_view"
[INFO] SQL> CREATE OR REPLACE VIEW my_view AS
[INFO] SQL> SELECT col FROM my_table WHERE my_row = 'UPDATE';

###### What did you see instead?
[INFO] Migrating schema "my_schema" to version "1 - change"
[INFO] SQL> INSERT INTO my_table (col, my_row) VALUES ('COL', 'ROW');
[INFO] 1 row updated
[INFO] SQL> GRANT SELECT ON my_table TO my_user;
[INFO] SQL> GRANT SELECT, INSERT, UPDATE, DELETE ON my_other_table  TO my_user;
[INFO] no rows updated
[INFO] Migrating schema "my_schema" with repeatable migration "my_view"
[INFO] SQL> CREATE OR REPLACE VIEW my_view AS
[INFO] SQL> SELECT col FROM my_table WHERE my_row = 'UPDATE';
[INFO] no rows updated

It appears the presence of INSERT, UPDATE and/or DELETE in the SQL is causing the report of "no rows updated". This is confusing for DDL statements.

**Comment by DoodleBobBuffPants** [comment]
This is an unfortunate limitation of our parsing
We likely won't make any changes here unless it's a problem for multiple users, at which point we can revisit this issue, however it shouldn't be a blocker so closing for now
