### ISSUE TITLE
Flyway doesn't clean roles

### ISSUE THREAD

**Issue by rastancu** [flyway/flyway#3474]
###### Which version and edition of Flyway are you using?
8.5.12

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
gradle plugin

###### Which database are you using? (Type & version)
oracle 19c 

###### Which operating system are you using?
windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
flywayMigrate -> create a role
eg: `CREATE ROLE SOME_READ_RL`

then flywayClean

then flywayMigrate again

###### What did you expect to see?
migrate success.

###### What did you see instead?
 'SOME_READ_RL' already exists

I thought flywayClean will clean the schemas and drop anything else. Is this intended behaviour ? edit: forgot to mention I couldn't exactly find if roles are considered db objects, nor how flyway treats them

**Comment by Barry-RG** [comment]
Flyway's clean function cleans the schemas and drops the database objects inside. However, this only applies to the schemas Flyway has awareness of, either through it's configuration or the JDBC url. 

Looking at Oracle, this also applies to a lot of other DB types as well, the roles and users are either not stored as conventional DB object or, more commonly, stored in a schema Flyway does not have scope to change. 

As a result, and considering Oracle 19c's limited access to query roles, we would not advise on using migration scripts to create roles or on Clean to remove roles from your DB.

**Comment by Barry-RG** [comment]
Closing till further interest

**Comment by rastancu** [comment]
A simple workaround is using callbacks like beforeClean (and a simple drop query). But I wasn't sure if about Flyway's behaviour. Thanks a lot for clarifying :)
