### ISSUE TITLE
Error Code: 1267. Illegal mix of collations (utf8mb4_bin,NONE) and (utf8mb4_bin,NONE) for operation ‘max’.

### ISSUE THREAD

**Issue by kanthianna** [flyway/flyway#3475]
###### Which version and edition of Flyway are you using?

flyway:8.5.10

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

RDS mysql 8.0.28

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We are facing a issue with a view in mysql db. View is successfully created using flyway db migration. But, when we execute the view like select * from view_<name>; it throws below error.
Error Code: 1267. Illegal mix of collations (utf8mb4_bin,NONE) and (utf8mb4_bin,NONE) for operation ‘max’.

To fix above issue, we just need to open the view in mysql workbench and save it again and run. With out any code cahnges, it works after recreating in mysql work bench. Need to check why by using flyway it fails and the same code works using mysql workbench.

Its happening with few procedures as well.

**Comment by kanthianna** [comment]
Able to fix the issue by adding 
SET character_set_connection = 'utf8mb4'; to the script. Is there a way to set this variable globally while using flyway?

**Comment by kanthianna** [comment]
how to set "SET character_set_connection = 'utf8mb4'" as env variable so that flyway uses this for every script

**Comment by DoodleBobBuffPants** [comment]
There are a few methods you could try:

- You could try setting it in the JDBC URL using `sessionVariables` as described on [this page](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-connp-props-miscellaneous.html) to set [`character_set_connection`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_character_set_connection)
- You could use Flyway's [`initSql`](https://flywaydb.org/documentation/configuration/parameters/initSql) parameter and provide the SQL to set the variable
- You could use a [callback](https://flywaydb.org/documentation/concepts/callbacks) such as `beforeMigrate`

Any of these approaches ought to work. I'll be closing this issue unless further problems arise
