### ISSUE TITLE
Redshift migration fails with "current transaction is aborted"

### ISSUE THREAD

**Issue by anilmandava** [flyway/flyway#3478]
###### Which version and edition of Flyway are you using?
flyway-8.5.11

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
AWS redshift
JDBC driver 2.1.0.3

###### Which operating system are you using?
Linux,Mac

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
```
   CREATE TABLE "mydb"."public"."atable" (
	tenantId varchar(30) not null,
	id bigint not null,
	program varchar(64),
	primary key(tenantId, id)); 
```

###### What did you expect to see?
Table created

###### What did you see instead?
`com.amazon.redshift.util.RedshiftException: ERROR: current transaction is aborted, commands ignored until end of transaction block`

We had a working setup of redshift db and flyway migration. It has been working well for a while.
Suddenly, about 2 months ago, the simplest of new migrations started failing.

If we use following **workaround**, append `enableFetchRingBuffer=false` to connection string, all is well again.
We reached out to AWS support for help and they feel the problem is with flyway.
Showing below response from them:

"Flyway ran a query `SELECT set_config('search_path', $1, false)` in a transaction block (auto-commit disabled), RingBufferThread activated, it spins up a separate thread, which is efficient for result processing. Then Flyway sent a cancel to the query and close statement attempted, which returned the error Query cancelled on user's request.

Why Flyway sent a cancel to query and then close statement is not known; this is a Flyway/client side initiated action and this need clarification from Flyway side."

JDBC log file:
[10101322351_flyway_debuglogs.txt](https://github.com/flyway/flyway/files/9053631/10101322351_flyway_debuglogs.txt)

**Comment by DoodleBobBuffPants** [comment]
Needing to set `enableFetchRingBuffer=false` is a limitation for the V2 driver documented [here](https://flywaydb.org/documentation/database/redshift#limitations) which we likely won't look into until further interest, so closing till further interest
