### ISSUE TITLE
BigQuery procedures using 'CASE' statement fails

### ISSUE THREAD

**Issue by arshaknorsoyan** [flyway/flyway#3479]
###### Which version and edition of Flyway are you using?
flyway:8.5.13   , community edition 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.21.1025.zip

###### Which database are you using? (Type & version)
BigQuery

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

CREATE OR REPLACE PROCEDURE myschema.usp_myProcedure() BEGIN
	SELECT
	column1,
	CASE WHEN column2 = 'A' THEN 'value for A' WHEN column2 = 'B' THEN 'Value for B' ELSE  'NULL' END AS column3
	FROM myschema.myTable;
END;

###### What did you expect to see?
Procedure created successfully 

###### What did you see instead?
Error occurred during SQL script execution

Reason:
SQL Error [100032] [HY000]: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Syntax error: Expected ";" but got end of script at [5:43]

**Comment by WeServeU** [comment]
Ctrl+A (All select) and run script, please
