### ISSUE TITLE
Failed to upgrade Spring Boot app from Flyway 8.5.13 to 9.0.1

### ISSUE THREAD

**Issue by donalmurtagh** [flyway/flyway#3486]
###### Which version and edition of Flyway are you using?
9.0.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle

###### Which database are you using? (Type & version)
Postgres 11

###### Which operating system are you using?
MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I attempted to upgrade a Spring Boot app (2.7.2) built with Gradle from Flyway 8.5.13 to 9.0.1. I made the following changes in `build.xml`

```
plugins {
    id "org.flywaydb.flyway" version "9.0.1"
}

dependencies {
    implementation "org.flywaydb:flyway-core:9.0.1"
}
```

###### What did you expect to see?
I expect the Spring Boot app to start without errors

###### What did you see instead?
I get the following error, which prevents the app from starting. In the app's configuration, I don't specify any particular value for the "ignore missing migrations" setting, so the default should be used

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureIgnoredMigrations(FlywayAutoConfiguration.java:264)

The following method did not exist:

    'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.ignoreMissingMigrations(boolean)'

The calling method's class, org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration, was loaded from the following location:

    jar:file:/Users/donal/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.7.2/f358e3f8ce01d3a26605fa23f9d3fd408726b033/spring-boot-autoconfigure-2.7.2.jar!/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class

The called method's class, org.flywaydb.core.api.configuration.FluentConfiguration, is available from the following locations:

    jar:file:/Users/donal/.gradle/caches/modules-2/files-2.1/org.flywaydb/flyway-core/9.0.1/b3c2b2ec888a69d2a759552c4678c6f1a12a037c/flyway-core-9.0.1.jar!/org/flywaydb/core/api/configuration/FluentConfiguration.class

The called method's class hierarchy was loaded from the following locations:

    org.flywaydb.core.api.configuration.FluentConfiguration: file:/Users/donal/.gradle/caches/modules-2/files-2.1/org.flywaydb/flyway-core/9.0.1/b3c2b2ec888a69d2a759552c4678c6f1a12a037c/flyway-core-9.0.1.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration and org.flywaydb.core.api.configuration.FluentConfiguration
```

**Comment by DoodleBobBuffPants** [comment]
Flyway V9 introduced breaking changes that you can read about [here](https://flywaydb.org/documentation/learnmore/releaseNotes#9.0.0)

You will likely need to ask the Spring Boot maintainers to update to support the latest version of Flyway

**Comment by donalmurtagh** [comment]
It appears that Flyway 9.2.1 is compatible with the current version of Spring Boot, i.e. 2.7.3
