### ISSUE TITLE
Option 'validateMigrationNaming' isn't working with multiple Flyway instances

### ISSUE THREAD

**Issue by dreis2211** [flyway/flyway#3488]
###### Which version and edition of Flyway are you using?

8.5.13

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes, the code hasn't changed in that regards

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Postgres 14

###### Which operating system are you using?

Doesn't matter - happens on all

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We're having multiple Flyway instances in our application that target different DBs or come from different modules. Each of those Flyway instances might have different prefixes and come with their own set of migrations.

E.g simplified like the following (not complete - just to get the idea)
```
Flyway.configure()
	.sqlMigrationPrefix("Module1_V")
	.repeatableSqlMigrationPrefix("Module1_R")
	.table("flyway_schema_module1")
	.load();

Flyway.configure()
	.sqlMigrationPrefix("Module2_V")
	.repeatableSqlMigrationPrefix("Module2_R")
	.table("flyway_schema_module2")
	.load();
```

This unfortunately has two problems for us with the facilities in `ResourceNameValidator`.

1. `ResourceNameValidator` is getting basically all resources in the classpath (so in our case from all modules) regardless of prefix and validates them just against the current configuration (which is then again validating based on the prefix and fails). Thus we can't enable the option `validateMigrationNaming` at all at the moment.
```
    private Collection<LoadableResource> getAllSqlResources(ResourceProvider provider, Configuration configuration) {
        return provider.getResources("", configuration.getSqlMigrationSuffixes());
        // Maybe better?
        // return provider.getResources(configuration.getSqlMigrationPrefix(), configuration.getSqlMigrationSuffixes());
    }
```

**NOTE**: The caveats of that might be that migrations not matching any prefix & suffix are ignored. But that is actually already happening since the suffixes were used previously. Therefore a migration with a wrong suffix wouldn't have been found already before.

2. Since #3403 there is an info logged that migrations were found that didn't run. I would have expected that `validateMigrationNaming` - when set to `false` - doesn't run any validation. But in fact it runs the validation and prints this misleading messages for every Flyway execution. 

```
... o.f.c.i.resource.ResourceNameValidator   : 34 SQL migrations were detected but not run because they did not follow the filename convention.
... o.f.c.i.resource.ResourceNameValidator   : If this is in error, enable debug logging or 'validateMigrationNaming' to fail fast and see a list of the invalid file names.
```
 
The validation isn't the same as running the migrations. So in reality they ran - just in different Flyway executions. Just the validation of that particular Flyway execution didn't like all of them.
Moreover, this can be an additional performance overhead when you have many migrations.

Imho it would have been better to have introduced a new option `logInvalidMigrations` that you can turn on specifically to enable these logs.

###### What did you expect to see?
- Resource validation can handle multiple Flyway instances (or aka runs with the configuration of the current flyway execution)
- Validation is not run unless otherwise stated.
- Optional logging can be turned on with new config flag.

Let me know if this makes sense.

Cheers,
Christoph

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising this issue

We're unlikely to tackle the last two bullet points unless there's more interest

As for being able to use `validateMigrationNaming`, the current solution would be to store migrations with a common prefix in their own location, and set the `locations` parameter for each instance of Flyway. This would ensure each instance only validates the migrations it needs to access. For example, something like:

```java
Flyway.configure()
	.sqlMigrationPrefix("Module1_V")
	.repeatableSqlMigrationPrefix("Module1_R")
	.table("flyway_schema_module1")
        .locations("Module1")
	.load();

Flyway.configure()
	.sqlMigrationPrefix("Module2_V")
	.repeatableSqlMigrationPrefix("Module2_R")
	.table("flyway_schema_module2")
        .locations("Module2")
	.load();
```

As there is this workaround, we won't be making any changes unless more people encounter an issue here too
