### ISSUE TITLE
Build warning from example in pom.xml

### ISSUE THREAD

**Issue by keranem1** [flyway/flyway#3490]
###### Which version and edition of Flyway are you using?

Tag 9.0.4

###### Which operating system are you using?

Windows 10
java version "17.0.2" 2022-01-18 LTS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

As per https://github.com/flyway/flyway/blob/232283dd2bf1ad3dcb62b6e81011620c58c423d7/pom.xml#L27

`mvn clean install -PCommandlinePlatformAssemblies`

###### What did you expect to see?

`BUILD SUCCESS`

###### What did you see instead?

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.707 s
[INFO] Finished at: 2022-08-01T21:40:21-04:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "CommandlinePlatformAssemblies" could not be activated because it does not exist.
```

Does the WARNING after BUILD SUCCESS indicate an incomplete build?

**Comment by tjs145** [comment]
It looks like that comment is out of date. The current commands are:
```
    mvn clean install -Pbuild-assemblies-windows
    mvn clean install -Pbuild-assemblies-linux
    mvn clean install -Pbuild-assemblies-mac
    mvn clean install -Pbuild-assemblies-no-jre
```
depending on your OS. The comment in the `pom.xml` will be updated.
