### ISSUE TITLE
Migrations don't run on 9.1.0 (possible too many connections required issue?)

### ISSUE THREAD

**Issue by henricook** [flyway/flyway#3491]
###### Which version and edition of Flyway are you using?

My dependency updating program automatically opened an upgrade from 9.0.4 to 9.1.0 for me

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java library

###### Which database are you using? (Type & version)

Postgres 14.4

###### Which operating system are you using?

Java on Ubuntu Focal (Azure Zulu JDK docker images)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Usually during application startup migrations are applied, this is a new application on a blank database

###### What did you expect to see?

Successful migrations

###### What did you see instead?

`[2022-08-03T09:23:45,240] [INFO] o.f.c.i.c.DbValidate - Successfully validated 333 migrations (execution time 00:00.110s)
`

`[2022-08-03T09:23:55,125] [WARN] c.z.h.p.ProxyLeakTask - Connection leak detection triggered for org.postgresql.jdbc.PgConnection@55a2f995 on thread hc-io-28, stack trace follows
`

```
[2022-08-03T09:24:08,568] [DEBUG] c.z.h.p.HikariPool - hc-cp - Pool stats (total=1, active=1, idle=0, waiting=1)
[2022-08-03T09:24:08,568] [DEBUG] c.z.h.p.HikariPool - hc-cp - Fill pool skipped, pool is at sufficient level.
[2022-08-03T09:24:15,242] [DEBUG] c.z.h.p.HikariPool - hc-cp - Timeout failure stats (total=1, active=1, idle=0, waiting=0)
```

It's worth noting that all of our test environments like this are limited to one database connection to ensure that we're never accidentally nesting transactions.

Could Flyway have made a change in this release that now requires 2 connections active at the same time to complete migrations? (Just a guess)

On my local machine, capped at 3 connections, migrations start running before a connection leak occurs, and I have two active connections stuck in active indefinitely

```
[2022-08-03T10:31:32,783] [debug] c.z.h.p.HikariPool - hc-cp - Fill pool skipped, pool is at sufficient level.
[2022-08-03T10:32:02,783] [debug] c.z.h.p.HikariPool - hc-cp - Before cleanup stats (total=3, active=2, idle=1, waiting=0)
[2022-08-03T10:32:02,784] [debug] c.z.h.p.HikariPool - hc-cp - After cleanup  stats (total=3, active=2, idle=1, waiting=0)
[2022-08-03T10:32:02,784] [debug] c.z.h.p.HikariPool - hc-cp - Fill pool skipped, pool is at sufficient level.
```

**Comment by DoodleBobBuffPants** [comment]
That's correct - for PostgreSQL we now have two active connections in order to support [this](https://github.com/flyway/flyway/pull/3394) request, the underlying reason being that we use transactional locks instead of session-level locks

You can revert to the old behaviour by setting `flyway.postgresql.transactional.lock=false`

**Comment by henricook** [comment]
Thanks @DoodleBobBuffPants - I added a further note to the ticket about how it's timing out on my local machine, with 3 max connections, after about half the migrations. I can poke that a bit to see if anything's clear. The migration it seems to 'freeze' on is nothing special, just making an index concurrently.

**Comment by DoodleBobBuffPants** [comment]
Concurrent indexes are unfortunately the primary use case for using session-level locks 😅 They hang when there is an ongoing transaction, so they don't work with transactional locks, and we changed the default to transactional locks as concurrent indexes felt more like the outlier than the norm

**Comment by henricook** [comment]
aha! Guess I need to use the old behaviour then. When adding an index on a large, in-use database we almost always specify `CONCURRENTLY` to prevent disruption to users while the new index is built.

I guess so we're not always using this 'keep old behaviour' flag some kind of selective drop to session level locks when Flyway sees something like a concurrent index might be cool? Just a thought - i'll try this flag now

**Comment by henricook** [comment]
I'm having trouble applying this with in-code config - does this look right to you?

```
                        Flyway.configure
                          .dataSource(ds)
                          .locations("sql/migrations")
                          .configuration(Map("flyway.postgresql.transactional.lock" -> "false").asJava)
                          .load()
```

The Map(...).asJava is because we're in Scala, it becomes a Java Map / compiles fine

the .configuration section is my attempt to specify this flag

**Comment by DoodleBobBuffPants** [comment]
The documentation on how to configure this has just gone live [here](https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock)

This approach isn't working because we implement it as 'extension' config as opposed to 'core' config - could you try the approach(es) in the documentation and let us know if they work?

**Comment by henricook** [comment]
@DoodleBobBuffPants I really appreciate your responsiveness here thank you.

If I define this, how do I then 'apply' it to Flyway config? Some extra method on Flyway.configure? Or is it like a global mutable thing?

```
PostgreSQLConfigurationExtension configurationExtension = configuration.getPluginRegister().getPlugin(PostgreSQLConfigurationExtension.class)
configurationExtension.setTransactionalLock(false);
```

**Comment by DoodleBobBuffPants** [comment]
Configuration extensions are mutable, and they belong to a plugin register, and each configuration object has its own plugin register - hope that answers your question :)

**Comment by henricook** [comment]
Hmmm so based on that what I'm trying in my (inserted in a later edit) code block above is right... weird. I'll keep playing with it

**Comment by DoodleBobBuffPants** [comment]
you may need to call it before the call to `Flyway...load()`

**Comment by DoodleBobBuffPants** [comment]
Something like

```scala
val config =  Flyway.configure
                    .dataSource(ds)
                    .locations("sql/migrations")
                          
val configExtension = config.getPluginRegister.getPlugin(classOf[PostgreSQLConfigurationExtension])          
configExtension.setTransactionalLock(false)

val flyway = config.load()
```

**Comment by henricook** [comment]
Thanks, we'd converged on the same solution.

```scala
                        val config = Flyway.configure
                          .dataSource(ds)
                          .locations("sql/migrations")

                        // Concurrent indexing is not supported by Flyway's default transactional locks
                        // Info: https://github.com/flyway/flyway/issues/3491
                        val configExtension =
                          config.getPluginRegister.getPlugin(classOf[PostgreSQLConfigurationExtension])
                        configExtension.setTransactionalLock(false)

                        config.load()
                        ```
                        
**Unfortunately**, still no dice!

Commencing head scratching

**Comment by henricook** [comment]
Adding a log:

```
unsafeLogger.warn("=== Flyway debug: Is transactional = " + configExtension.isTransactionalLock)
```

prints the following before freeze up:

```
22-08-03T12:19:19,379] [warn] a.n.c.c.p.DatabaseMigrator - === Flyway debug: Is transactional = false
[2022-08-03T12:19:19,387] [info] a.n.c.c.p.DatabaseMigrator - Running database migrations (if any)... [ReqId:00000000000000000000000000000000]
[2022-08-03T12:19:19,429] [info] o.f.c.i.d.b.BaseDatabaseType - Database: jdbc:postgresql://localhost:5432/hc (PostgreSQL 14.4)
[2022-08-03T12:19:19,429] [debug] o.f.c.FlywayExecutor - DDL Transactions Supported: true
[2022-08-03T12:19:19,535] [info] o.f.c.i.c.DbValidate - Successfully validated 333 migrations (execution time 00:00.099s)

```

**Comment by henricook** [comment]
I'm telling lies, it works great. Thanks @DoodleBobBuffPants

**Comment by DoodleBobBuffPants** [comment]
Glad it works!

**Comment by henricook** [comment]
A note for readers: Even with this flag to false Flyway appears to require two connections now instead of one - we've had to up connection maxes from 1 to 2 in our test environments.

**Comment by DoodleBobBuffPants** [comment]
How problematic is it to up the maximum number of connections? It should be easy enough to fix on our side but it would be nice to understand the problem

**Comment by henricook** [comment]
Thanks for asking. It's technically very easy for us to change our max allowed connections. We keep our local and dev (CI) environments at 1 max connection so that we can easily see if any of us accidentally nest transactions (i.e. one API call ends up requiring two connections if our transactions are accidentally nested). So it's very specific I guess to our use of JDBC and the Doobie library for Scala. So the negative for us is that at two connections we're less likely to see those if they happen. That said, the last one we noticed was probably over a year ago so they're not exactly common.

**Comment by huima** [comment]
Looking at @DoodleBobBuffPants commit done 6 days ago, should this already work in the latest version 9.1.2? I just tested in a Clojure project and was not able to get it work.

Snip from the code:

```
   (let   [flyway (-> (. Flyway configure)
                     (.schemas (into-array String ["public"]))
                     (.dataSource (:datasource @@db-con)))
          extConfig (-> flyway
                        (.getPluginRegister)
                        (.getPlugin PostgreSQLConfigurationExtension))
          _ (.setTransactionalLock extConfig false)
          _  (info "It is now: " (.isTransactionalLock extConfig))
          flyway (.load flyway)]
      (.migrate flyway))
```

So I create first the basic configuration, then take the extension from the register - and set the transactional lock status. And even check that it reports the right value. But still the migration wants to use 2 connection.

**Comment by DoodleBobBuffPants** [comment]
The change has not yet been released, it will be in the next release due some time this week

**Comment by avihoo** [comment]
Version `9.1.2` should be treated as a breaking change version. I spent 4 hours figuring out why my migrations do not run anymore, after updating from `9.0.4` only to come here, go through all the comments and realizing I have to increase the pool size from 1 to 2.

**Comment by dsvensson** [comment]
@DoodleBobBuffPants Tried setting `flyway.postgresql.transactional.lock=false` in a `V1_666_00__DoomedMigration.sql.conf` and it's rejected. Tried a number of different permutations. Is it possible to deal with this per migration?

**Comment by DoodleBobBuffPants** [comment]
Hey @dsvensson 

I no longer actively contribute to this project. Last I checked it wasn't available per migration, but it'd be best to raise a feature request :)

**Comment by andyczerwonka** [comment]
> Something like
> 
> val config =  Flyway.configure
>                     .dataSource(ds)
>                     .locations("sql/migrations")
>                           
> val configExtension = config.getPluginRegister.getPlugin(classOf[PostgreSQLConfigurationExtension])          
> configExtension.setTransactionalLock(false)
> 
> val flyway = config.load()

I ended up writing an extension method to do this:

```scala
import org.flywaydb.database.postgresql.PostgreSQLConfigurationExtension
import org.flywaydb.core.api.configuration.FluentConfiguration

package object flyway {

  implicit class FlywayOps(config: FluentConfiguration) {
    // The default session-level lock changed in 9.1.0. Turning off this advisory lock puts you back to the old session-lock behavior.
    // See https://documentation.red-gate.com/fd/flyway-postgresql-transactional-lock-setting-277579114.html
    def useTransactionalAdvisoryLock(lock: Boolean): FluentConfiguration = {
      val configurationExtension = config.getPluginRegister().getPlugin(classOf[PostgreSQLConfigurationExtension])
      configurationExtension.setTransactionalLock(lock)
      config
    }
  }

}
```

This allowed a more fluent and explicit change to the Flyway configuration code, e.g.

```scala
Flyway
  .configure()
  .useTransactionalAdvisoryLock(false)
  .locations(...)
  .load()
  .migrate()

```
