### ISSUE TITLE
Migration to MySQL with grant select action failed as Access Denied when MySQL upgrades to v5.7.33

### ISSUE THREAD

**Issue by Ranger-118** [flyway/flyway#3496]
###### Which version and edition of Flyway are you using?
7.15.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Maybe I could try, but I insist to check with the dev team for a direct answer as well. Since 7.15.0 command line is an tar.gz, could you please guide how to run with the latest version (.jar file) as docker command?

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MySQL v5.7.33, it is no problem with v5.7.26

###### Which operating system are you using?
Linux:tomcat:9.0.65-jdk17-corretto

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
This is the preset:
![image](https://user-images.githubusercontent.com/66778902/183691359-51197c36-5602-43fc-976a-c21364d06c4f.png)

The flyway migration runs well until the script came to:
![image](https://user-images.githubusercontent.com/66778902/183687026-bae4c32a-ab46-4f58-932a-414a14e13988.png)

###### What did you expect to see?
The migration could run just like previous with the MySQL v5.7.33.

###### What did you see instead?
When I upgrade MySQL from v5.7.26 to v5.7.33 and run the Integration Test, the above mentioned SQL script cannot be proceed further, below is the error in IDE terminal:
`java.sql.SQLSyntaxErrorException: Access denied for user 'qsr_webapp'@'%' to database 'qsr_webapp'`
`WARNING: Unable to restore connection to having no default schema: Access denied for user '${user#1}'@'%' to database '${uuid_as_db_for_test}'`

The error message in the MySQL container:
`2022-08-09T15:14:42.919972Z 2 [Note] Got an error reading communication packets`
`2022-08-09T15:14:44.756439Z 3 [Note] Aborted connection 3 to db: 'unconnected' user: '${user#1}' host: '${internal_IP}' (Got an error reading communication packets)`

**Comment by DoodleBobBuffPants** [comment]
MySQL 5.7 is no longer supported in Community so we won't be investigating this issue

If you post the stack trace however, we may be able to point you to other sources

We would recommend updating to newer versions of Flyway and MySQL too as an initial step

As for Docker, you can find usage details [here](https://github.com/flyway/flyway-docker#official-flyway-community-docker-images)

We'll be closing this until further activity
