### ISSUE TITLE
ConnectRetriesInterval default not working in Maven plugin

### ISSUE THREAD

**Issue by mihalyr** [flyway/flyway#3499]
###### Which version and edition of Flyway are you using?

`>=7.15.0`

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

The issue is present in all versions starting from `7.15.0` up to `9.1.3`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using? (Type & version)

`PostgreSQL 11.11`

###### Which operating system are you using?

`Linux 5.17.12`

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

```
          <driver>org.postgresql.Driver</driver>
          <url>jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}</url>
          <user>${postgres.user}</user>
          <password>${postgres.password}</password>
          <mixed>true</mixed>
          <connectRetries>30</connectRetries>
          <locations>
            <location>classpath:db/migrations</location>
          </locations>
```

Then run maven to start my DB in the docker container and apply flyway migrations:

```
mvn docker:start flyway:migrate
```

###### What did you expect to see?

With Flyway versions `< 7.15.0` Flyway will retry connections with exponential delay: 1, 2, 4, 8, 16 sec... and it gives time for the DB to initialize and connect when it becomes ready. I expected to see the same with Flyway versions `> 7.15.0`

###### What did you see instead?

Flyway flew through all 30 retries in 1-2 seconds as there was no retry interval configured at all.

I fixed this by adding the retry interval explicitly:

```
          <connectRetriesInterval>120</connectRetriesInterval>
```

This fixed the problem and now Flyway works as before. However, this is unexpected, because the [documentation](https://github.com/flyway/flyway/blob/flyway-7.15.0/flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java#L110) says the default is 120 already, but for some reason, this is not the case.

**Comment by mihalyr** [comment]
An easy reproducer is to run flyway against a non-existent database without defining `connectionRetriesInterval` in `pom.xml` and just run `mvn flyway:migrate`

**Comment by maguro** [comment]
fyi, I think the Gradle plugin suffers from this same problem.

**Comment by mihalyr** [comment]
Guys, I just upgraded from 9.1.6 where this issue was fixed to the latest 9.16.0 and I can see some issues again. Did the fix get reverted or the default interval changed recently?

**Comment by mihalyr** [comment]
I can see that the connect retries interval default supposed to be 120, but I can tell that is definitely not working, there is a very visible difference if I set the interval explicitly to 120 (I can see only 3 retries) and when I leave the default (I can see my terminal scrolling from the retries).

https://documentation.red-gate.com/fd/connect-retries-interval-184127491.html

**Comment by mihalyr** [comment]
I've opened a new issue for the regression https://github.com/flyway/flyway/issues/3636
