### ISSUE TITLE
PSQLException: ERROR: ALTER TYPE ... ADD cannot run inside a transaction block

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#350]
_Original author: gkislin13@gmail.com (September 11, 2012 12:14:58)_

Script for postgresql
ALTER TYPE ou.rights_object_type ADD VALUE 'saleplan4' AFTER 'saleplan3'

lead to exceptions.
This is special case.

I workaround it by shift new TransactionTemplate.execute from
DbMigrator.applyMigration to SqlMigrationExecutor and compare to &quot;ALTER TYPE&quot; (aplicable only as path, not regular solution)

_Original issue: http://code.google.com/p/flyway/issues/detail?id=327_

**Comment by wontheone1** [comment]
new url that points to this problem is 
https://flywaydb.org/documentation/database/postgresql

**Comment by Hubbitus** [comment]
Sorry, but mentioned workaround is just … workaround.

If your type used in multiple tables it will be mush of scripting handle it properly.

May be you could introduce something like "non-transactional annotation" for statement (or at least script)?

**Comment by Hubbitus** [comment]
There exists better workaround http://stackoverflow.com/questions/1771543/postgresql-updating-an-enum-type/41696273#41696273 but it still some sort of hack…

**Comment by Rehman-Akram** [comment]
This is much better approach

https://stackoverflow.com/a/77283100/22730967
