### ISSUE TITLE
Default Non transactional queries now running inside a transaction

### ISSUE THREAD

**Issue by wolverinrox** [flyway/flyway#3500]
###### Which version and edition of Flyway are you using?

- org.flywaydb.flyway:9.1.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

- It is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

- Gradle Plugin

###### Which database are you using? (Type & version)

- Postgres 12.4

###### Which operating system are you using?

- MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

- Upgraded flyway plugin to 9.1.3
- Non-transactional  migrations like`CREATE INDEX CONCURRENTLY index_name ON table_name(column_name)`  hand indefinite.
- Of course setting `flyway.postgresql.transactional.lock=false` will solve the issue.

###### What did you expect to see?

- Switch between session lock and transactional lock should make sense since it only required for the users who use pgBouncer. 
- No breaking changes in a patch release.
- No super configurations to override all existing configurations and disregard the current behaviour.
- In light of the new configuration if a migrations are running inside a transaction it should log correctly,

###### What did you see instead?

- New config to switch between session lock and transactional lock doesn't make any sense. Since already available script config `executeInTransaction=false` and the new config behaviour contradicts each other.
- Flyway automatic detection of the technical limitation  for running a query in a transaction has no use in the face of the new config.
- It still log that migration like `CREATE INDEX CONCURRENTLY index_name ON table_name(column_name)` will run in a `non-transactional` statement even though it running inside a transaction due to the new change

**Comment by DoodleBobBuffPants** [comment]
Regarding the transaction behaviour - migrations still adhere to `executeInTransaction`. it's that updates to the history table run in a separate connection which is in a transaction, which create `CREATE INDEX CONCURRENTLY` doesn't like

I'm going to merge this into https://github.com/flyway/flyway/issues/3497 so we can track the demand, as currently there is more demand for the current behaviour than the old one
