### ISSUE TITLE
ignoreMigrationPattern not working

### ISSUE THREAD

**Issue by Rob-Gemen** [flyway/flyway#3502]
###### Which version and edition of Flyway are you using?
I tried 8.5.13 and 9.1.4. Both have the same issue

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
The latest version still has the bug

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
I am starting a spring-boot application with flyway. But also if I use the maven plugin, I get the same Issue

###### Which database are you using? (Type & version)
Oracle version 19

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
The feature ignore-migration-pattern is not working. I am following the specs. But valid values are being disapproved

my application.yaml
spring:
  flyway: 
    ignore-migration-patterns: versioned:missing
does NOT work. I get an exception in the log

spring:
  flyway: 
    ignore-migration-patterns: "*:missing* 
Does work

###### What did you expect to see?
missing versioned migrations to be ignored

###### What did you see instead?
FlywayTeamsUpgradeRequiredException

##### my humble opinion
I think this coding is wrong:
ValidatePattern.java (line 57-59)
        if (migrationType.equals("repeatable") || migrationType.equals("versioned")) {
            throw new FlywayTeamsUpgradeRequiredException("ignoreMigrationPattern with type '" + migrationType + "'");
        }
valid values (versioned and repeatable) are being disapproved

I am completely new to open source development and I don't know how to fix this myself

**Comment by DoodleBobBuffPants** [comment]
In Community, only the wildcard is supported as a `MigrationType` - being able to specify `versioned` or `repeatable` is a Teams feature

**Comment by hasakilol** [comment]
I'm using Teams Edition 9.2.1 command line tool with -ignoreMigrationPatterns="versioned:missing", but it still gives me 
```
Detected applied migration not resolved locally: xxx.
If you removed this migration intentionally, run repair to mark the migration as deleted. 
```
