### ISSUE TITLE
BUG: flyway migration of index keeps running on v9.1.6

### ISSUE THREAD

**Issue by pvstaden** [flyway/flyway#3506]
###### Which version and edition of Flyway are you using?
Flyway community edition v9.1.6

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
PostgreSQL v13.4 (AWS aurora cluster)

###### Which operating system are you using?
Ubuntu (Docker)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We tried adding multiple indexes to our database and the migration kept running. (Below is the queries in the script file) When we run the queries to add the indexes manually to the database it succeeds in a few milliseconds. We then downgraded to v8.5.13 and it worked as expected. Unfortunately, we do not get any error messages to be able to supply this for you.

```
create index concurrently if not exists orders_rate_request_id_index
    on orders (rate_request_id);

create index concurrently if not exists orders_status_index
    on orders (status);

create index concurrently if not exists orders_time_archived_index
    on orders (time_archived);
```
This is the command we run:
`flyway migrate -url=jdbc:postgresql://<DB_URL>/<DB_NAME> -user=<DB_USERNAME> -password=<DB_PASSWORD> -locations=filesystem:sql/<DB_NAME>/`

I just want to mention that we successfully added a column with v9.1.6 but as soon as we try to add an index the migration just keeps running.

###### What did you expect to see?
The migration to be successful as with v8.5.13

###### What did you see instead?
The migration process just kept on running with v9.1.6

**Comment by DoodleBobBuffPants** [comment]
See [this related issue](https://github.com/flyway/flyway/issues/3497)

Flyway now uses a transactional lock instead of a session level lock, which concurrent indexes don't like. You can use a session level lock by setting `flyway.postgresql.transactional.lock=false` in config
