### ISSUE TITLE
Flyway Version Upgrade

### ISSUE THREAD

**Issue by sanketh-shetty-incontact** [flyway/flyway#3507]
###### Which version and edition of Flyway are you using?

3.2.1

We want to migrate to latest version now.

Just need to understand if there is a reference document on how do we proceed with the changes for same.

What all things will need to be updated and taken care, can you please assist with same

**Comment by DoodleBobBuffPants** [comment]
Flyway 3 is unfortunately a rather old version of Flyway where direct upgrades are not supported

There is some advice available [here](https://stackoverflow.com/questions/49945098/how-to-upgrade-from-flyway-3-directly-to-flyway-5) for doing this manually. Once you've moved from Flyway 3 to Flyway 4, you can then upgrade one major version at a time and run `repair`

However, we would recommend starting again from the latest version of Flyway. You should be able to delete the old history table, and the latest version of Flyway will recreate it during a `baseline` or `migrate`. You could choose to `baseline` with the latest version of Flyway, but if you're interested in keeping the history of migrations, we would recommend using [`skipExecutingMigrations`](https://flywaydb.org/documentation/configuration/parameters/skipExecutingMigrations) during a `migrate` to update the history table without applying migrations

**Comment by sanketh-shetty-incontact** [comment]
From what I understood the major breaking change after Flyway 5 has been the change in schema_version table.

So if I upgrade to any version above 5 , and add below property in my config 
spring.flyway.table: schema_version

Then it should still work fine right?
