### ISSUE TITLE
Snowflake scripting/queries with semicolon

### ISSUE THREAD

**Issue by pachu** [flyway/flyway#3512]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 9.1.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I cannot see any release notes about Snowflake in 9.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line via docker.

###### Which database are you using? (Type & version)

Snowflake 6.29.0

###### Which operating system are you using?

alpine docker image

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I am using Flyway to execute repeatable migration containing Snowflake scripting (introduced with version 6. Example:

```
DECLARE 
    number_proj := 10;
    env_que := 'TEST';
BEGIN 
    EXECUTE IMMEDIATE ('
    INSERT INTO TEST_FLYWAY_SYS_2."${table_pro}" 
        VALUES
        (' || :number_proj || '}, ''https://${url_pro}/blank''),(11,''${cert_pro}''),(12,''${serial_pro}'')
END;

```
It is just the simple one, where it is easy to get rid off the DECLARE block, but we want, for example, to use it as well for procedurs to declare variables with thert types.

###### What did you expect to see?

Successful query execution. 

###### What did you see instead?

It fails after finding first semicolon character. 
```
DECLARE 
    number_proj := 10
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line 2 at position 21 unexpected '<EOF>'.
```

Do you know, when v6 and SF scripting will be supported or you have any trick to solve this issue/force Flyway to treat it as a single SF query?

**Comment by pachu** [comment]
Ok, I was able so far to make it working with below workaround, but if you will have something more elegant, please let me know.

```
ALTER SESSION SET AUTOCOMMIT = TRUE;

EXECUTE IMMEDIATE $$
DECLARE 
    number_proj := 10;
    env_que := 'TEST';
BEGIN 
    EXECUTE IMMEDIATE ('
    INSERT INTO TEST_FLYWAY_SYS_2."${table_pro}" 
        VALUES
        (' || :number_proj || '}, ''https://${url_pro}/blank''),(11,''${cert_pro}''),(12,''${serial_pro}'')
END;
$$
;
```

**Comment by DoodleBobBuffPants** [comment]
Closed by https://github.com/flyway/flyway/commit/ca90c2edeb523119415e187ac46f6a1e2f5248a8

**Comment by pachu** [comment]
many thanks!
