### ISSUE TITLE
Memory exception when migrating many files

### ISSUE THREAD

**Issue by Warfist** [flyway/flyway#3514]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 9.2.0 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This is the latest version (at the time of creating this bug report)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
[Docker image](https://hub.docker.com/r/flyway/flyway)

###### Which database are you using? (Type & version)
Sql Server 15.0.4178.1

###### Which operating system are you using?
Linux Mint 20.2

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Stacktrace
```
flyway    | Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
flyway    |     at java.base/java.util.Arrays.copyOfRange(Unknown Source)
flyway    |     at java.base/java.lang.StringLatin1.newString(Unknown Source)
flyway    |     at java.base/java.lang.String.substring(Unknown Source)
flyway    |     at org.flywaydb.core.internal.parser.PlaceholderReplacingReader.read(PlaceholderReplacingReader.java:123)
flyway    |     at java.base/java.io.FilterReader.read(Unknown Source)
flyway    |     at org.flywaydb.core.internal.parser.PositionTrackingReader.read(PositionTrackingReader.java:33)
flyway    |     at java.base/java.io.FilterReader.read(Unknown Source)
flyway    |     at org.flywaydb.core.internal.parser.RecordingReader.read(RecordingReader.java:33)
flyway    |     at java.base/java.io.FilterReader.read(Unknown Source)
flyway    |     at org.flywaydb.core.internal.parser.PeekingReader.refillPeekBuffer(PeekingReader.java:73)
flyway    |     at org.flywaydb.core.internal.parser.PeekingReader.peek(PeekingReader.java:62)
flyway    |     at org.flywaydb.core.internal.parser.PeekingReader.peekKeywordPart(PeekingReader.java:140)
flyway    |     at org.flywaydb.core.internal.parser.PeekingReader.readKeywordPart(PeekingReader.java:421)
flyway    |     at org.flywaydb.database.sqlserver.SQLServerParser.readKeyword(SQLServerParser.java:62)
flyway    |     at org.flywaydb.core.internal.parser.Parser.readToken(Parser.java:551)
flyway    |     at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:173)
flyway    |     at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:731)
flyway    |     at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:697)
flyway    |     at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:75)
flyway    |     at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:120)
flyway    |     at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:187)
flyway    |     at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.canExecuteInTransaction(SqlMigrationExecutor.java:73)
flyway    |     at org.flywaydb.core.internal.command.DbMigrate.isExecuteGroupInTransaction(DbMigrate.java:304)
flyway    |     at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:269)
flyway    |     at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
flyway    |     at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
flyway    |     at org.flywaydb.core.internal.command.DbMigrate$$Lambda$122/0x0000000800237840.call(Unknown Source)
flyway    |     at org.flywaydb.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:61)
flyway    |     at org.flywaydb.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:93)
flyway    |     at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
flyway    |     at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
flyway    |     at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
flyway exited with code 1
```

**My analysis:**
This seems to be related with [this list](https://github.com/flyway/flyway/blob/f5d0bfac462bfaa6b70f41e3a740cdc22dcd27e3/flyway-core/src/main/java/org/flywaydb/core/internal/command/DbMigrate.java#L224). The `MigrationInfoImpl` object has references to `ResolvedMigrationImpl` which references `SqlMigrationExecutor` and then `ParserSqlScript` which contains a `protected final List<SqlStatement> sqlStatements`. 

This causes the memory overflow because the sql statements from the previous files are kept in the initial list (`LinkedHashMap<MigrationInfoImpl, Boolean> group`).

**How to reproduce:**
Check your heap size, then have enough files where the sum of the file size is bigger than the heap size.
In my case, I have ~3GB heap allocated and a total of 30GB of files to migrate (each file has 17MB of sql commands).

###### What did you expect to see?
All files should be executed. After successfully migrating a file, the loaded sql commands should be flushed from memory.

###### What did you see instead?
Flyway threw an out of memory exception mid-execution.

**Comment by wbosley** [comment]
Hi there,

Try using the [`stream`](https://flywaydb.org/documentation/configuration/parameters/stream) parameter, it might help you avoid this issue. When `stream` is set to true, Flyway loads each statement within a migration to memory individually. This dramatically reduces Flyway's memory consumption. 

Hopefully this helps :)
