### ISSUE TITLE
Cannot connect to MySQL with JDBC in v9.2.1

### ISSUE THREAD

**Issue by hemberger** [flyway/flyway#3515]
###### Which version and edition of Flyway are you using?
Community Edition 9.2.1 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MySQL 8.0

###### Which operating system are you using?
`flyway:9.2.1-alpine` Docker image 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
```
flyway -connectRetries=20 -url=jdbc:mysql://<host>/<db>?allowPublicKeyRetrieval=true&useSSL=false -user=<user> -password=<password> migrate
```

###### What did you expect to see?
```
Database: jdbc:mysql://<host>/<db> (MySQL 8.0)
Successfully validated 128 migrations (execution time 00:00.126s)
Current version of schema `<db>`: 1.6.68.05
Schema `<db>` is up to date. No migration necessary.
```
(Note: This is what I see when I use the `flyway:9.2.0-alpine` Docker image)

###### What did you see instead?
```
ERROR: Unable to connect to jdbc:mysql://smr-mysql/smr_live?allowPublicKeyRetrieval=true&useSSL=false
ERROR: 1
```

**Comment by calteran** [comment]
I'm seeing the same issue using both the homebrew installed v9.2.1 on a local copy of mysql as well as with between flyway & mysql docker containers.  Downgrading to 9.2.0 works in both cases.

**Comment by SullyJHF** [comment]
Also seeing the same issue here, only saw it because of a docker system prune and then re-pulling flyway broke the database connection.

**Comment by DoodleBobBuffPants** [comment]
This should now be fixed in 9.2.2

**Comment by hemberger** [comment]
I can confirm this is working again with version 9.2.2. Thanks for the quick fix!

**Comment by jobcase-plebedev** [comment]
Looks like this got broken again in 10.7.1, and works in 10.6:
```
initialize-db-1          | Flyway OSS Edition 10.7.1 by Redgate
initialize-db-1          | 
initialize-db-1          | See release notes here: https://rd.gt/416ObMi
initialize-db-1          | ERROR: Unable to connect to jdbc:mysql://db?allowPublicKeyRetrieval=true&useSSL=false
initialize-db-1 exited with code 1
```

while with 10.6.0 it works:
```
initialize-db-1          | WARNING: This version of Flyway is out of date. Upgrade to Flyway 10.7.1: https://rd.gt/3rXiSlV
initialize-db-1          | 
initialize-db-1          | Flyway OSS Edition 10.6.0 by Redgate
initialize-db-1          | 
initialize-db-1          | See release notes here: https://rd.gt/416ObMi
initialize-db-1          | Database: jdbc:mysql://db (MySQL 8.0)
initialize-db-1          | Successfully validated 2 migrations (execution time 00:00.068s)
initialize-db-1          | Current version of schema `local_application`: 20230601000000
initialize-db-1          | Schema `local_application` is up to date. No migration necessary.
```

Not sure it it is related to this breaking change in 7.0.1 
```
The 'flyway-dev' command-line now requires a license to be set in order to use it. If you are licensed with a Flyway license key, you will need to set this in an environment variable called 'FLYWAY_LICENSE_KEY'. If not, you can follow this documentation on how to set an offline license as an environment variable - https://documentation.red-gate.com/fd/licensing-164167730.html
``` 

but I'm not using it to deploy to production environment, it's for local development.

**Comment by tjs145** [comment]
> Looks like this got broken again in 10.7.1, and works in 10.6:
> 
> ```
> initialize-db-1          | Flyway OSS Edition 10.7.1 by Redgate
> initialize-db-1          | 
> initialize-db-1          | See release notes here: https://rd.gt/416ObMi
> initialize-db-1          | ERROR: Unable to connect to jdbc:mysql://db?allowPublicKeyRetrieval=true&useSSL=false
> initialize-db-1 exited with code 1
> ```
> 
> while with 10.6.0 it works:
> 
> ```
> initialize-db-1          | WARNING: This version of Flyway is out of date. Upgrade to Flyway 10.7.1: https://rd.gt/3rXiSlV
> initialize-db-1          | 
> initialize-db-1          | Flyway OSS Edition 10.6.0 by Redgate
> initialize-db-1          | 
> initialize-db-1          | See release notes here: https://rd.gt/416ObMi
> initialize-db-1          | Database: jdbc:mysql://db (MySQL 8.0)
> initialize-db-1          | Successfully validated 2 migrations (execution time 00:00.068s)
> initialize-db-1          | Current version of schema `local_application`: 20230601000000
> initialize-db-1          | Schema `local_application` is up to date. No migration necessary.
> ```
> 
> Not sure it it is related to this breaking change in 7.0.1
> 
> ```
> The 'flyway-dev' command-line now requires a license to be set in order to use it. If you are licensed with a Flyway license key, you will need to set this in an environment variable called 'FLYWAY_LICENSE_KEY'. If not, you can follow this documentation on how to set an offline license as an environment variable - https://documentation.red-gate.com/fd/licensing-164167730.html
> ```
> 
> but I'm not using it to deploy to production environment, it's for local development.

This is a compatibility issue in the latest version of the MariaDB driver, which the Flyway CLI uses for both MariaDB and MySQL connections (the issue being that it no longer supports MySQL URLs by default). While we investigate a proper solution, here are some possible workarounds:

 - Add `&permitMysqlScheme=true` onto the end of your URL.
 - Download the [MySQL driver](https://mvnrepository.com/artifact/com.mysql/mysql-connector-j) and add it to the `drivers` folder in the docker container.

**Comment by jobcase-plebedev** [comment]
@tjs145 - Thanks, adding `&permitMysqlScheme=true` worked
```
initialize-db-1          | Flyway OSS Edition 10.7.1 by Redgate
initialize-db-1          | 
initialize-db-1          | See release notes here: https://rd.gt/416ObMi
initialize-db-1          | Database: jdbc:mariadb://db/ (MySQL 8.0)
initialize-db-1          | Successfully validated 2 migrations (execution time 00:00.023s)
initialize-db-1          | Current version of schema `local_application`: 20230601000000
initialize-db-1          | Schema `local_application` is up to date. No migration necessary.
initialize-db-1 exited with code 0
```
