### ISSUE TITLE
Support for Aurora Postgres 14.3

### ISSUE THREAD

**Issue by henry-kr** [flyway/flyway#3517]
###### Which version and edition of Flyway are you using?
9.2.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
docker

###### Which database are you using? (Type & version)
Aurora Postgres 14.3

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
As Flyway does not support Aurora Postgres 14.3, I'm writing to request if you could please consider supporting it? Thank you for your consideration.

**Comment by DoodleBobBuffPants** [comment]
Do you encounter any particular issues when using it?

**Comment by DoodleBobBuffPants** [comment]
Did you upgrade your version of Flyway at the same time? This sounds similar to https://github.com/flyway/flyway/issues/3544#issuecomment-1285505230 - does the solution there help here?

If the above solution also fails then anything you can provide to help reproduce this, SQL included, would help

**Comment by DoodleBobBuffPants** [comment]
Closing till further activity
