### ISSUE TITLE
Unable to convert uid/gid chown string to host mapping: can't find uid for user flyway: no such user: flyway

### ISSUE THREAD

**Issue by GanesanChandran** [flyway/flyway#3521]
###### Which version and edition of Flyway are you using?
9.3.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This is latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
[Docker file](https://hub.docker.com/r/flyway/flyway)

###### Which database are you using? (Type & version)
Postgres SQL

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I using "flyway/flyway:latest-alpine" image for db script migration. I am trying to copy the DB scripts from our source folder to flyway default folder using below command. 

`COPY --chown=flyway:flyway ./src/DBScripts /flyway/sql`

While running the above command, i am facing the below issue.

**_unable to convert uid/gid chown string to host mapping: can't find uid for user flyway: no such user: flyway_**

My Dockerfile is,

```
FROM flyway/flyway:latest-alpine

COPY --chown=flyway:flyway ./src/DBScripts  /flyway/sql
COPY --chown=flyway:flyway ./dockerfiles/flyway/flyway.conf /flyway/conf/flyway.conf
```

But , the same above Dockerfile is worked last week. From this week, I am facing the above issue.

**Note:** I tried with above same docker commands using "flyway/flyway:9.2.1-alpine" image. It is worked fine. But it is not working after 9.2.1 version (9.2.2 and latest)

**Comment by Barry-RG** [comment]
As of 9.3.0 the Docker images no longer specify a user. The content of our the Flyway Docker files can be found [here](https://github.com/flyway/flyway-docker/), For the Alpine image, [here](https://github.com/flyway/flyway-docker/blob/main/alpine/Dockerfile).

As a result, you wouldnt need the `--chown` in your `COPY` statements anymore.

**Comment by TheRealChssAddct** [comment]
arg. this got me last night.  You broke us!

Serves me right for basing my image off `latest` tag, I guess.

Leaving this comment as it might help others find this issue and resolution:

Using Azure AKS, pod start failed to start with CreateContainerError after deploying a new version built on flyway/flyway:latest-alpine.  

Warning  Failed                  37s               kubelet                  Error: failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount872724113: no users found
