### ISSUE TITLE
SQLCipher support

### ISSUE THREAD

**Issue by benthecarman** [flyway/flyway#3522]
Is there support for SQLCipher, I tried setting the jdbc url with an encryption key to database and it does not seem to work. Is it possible that flyway is using a different sql driver so it is unable to do it. I am using https://github.com/Willena/sqlite-jdbc-crypt

**Comment by DoodleBobBuffPants** [comment]
Flyway does use a different driver by default yes, however you can [define the driver](https://flywaydb.org/documentation/configuration/parameters/driver) you wish to use with `flyway.driver` parameter though you will need to ensure the driver is on the classpath - if you're using the CLI then you need to place the JAR in the `drivers` folder

Closing until further activity
