### ISSUE TITLE
Flyway Community edition not supporting AWS Secrets manager JDBC driver

### ISSUE THREAD

**Issue by srisudarsan** [flyway/flyway#3523]
###### Which version and edition of Flyway are you using?
Flyway Community 8.5.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes, still exists in the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
JAVA API

###### Which database are you using? (Type & version)
Postgresql 14

###### Which operating system are you using?
MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
As per the documentation from https://github.com/aws/aws-secretsmanager-jdbc#usage-example, I am trying to use the AWS Secret JDBC driver to get the passwords from AWS Secrets Manager, when using this in the JDBC URL as "jdbc-secretsmanager:postgresql:...", I am getting an error "Flyway Teams Edition upgrade required: jdbc-secretsmanager is not supported by Flyway Community Edition"

Though, the exception is clear on that it needs a teams edition, the documentation from https://flywaydb.org/documentation/configuration/secretsManagement does not have a mention of the need of teams edition to use this feature. 

https://github.com/flyway/flyway/blob/main/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLDatabaseType.java#L58

###### What did you expect to see?
Application to get the secrets from AWS Secrets manager and the migrations to be run

###### What did you see instead?
Error, Flyway Teams Edition upgrade required: jdbc-secretsmanager is not supported by Flyway Community Edition

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising this

The page has a CTA under the heading that initiates contact, and we will look into making this clearer, so closing for now
