### ISSUE TITLE
Flyway CLI, Migrate Cmd, Not recognize new SQL script

### ISSUE THREAD

**Issue by wg21908** [flyway/flyway#3525]
- Flyway is 7.3.0
- Command-line is being used.
- Database type is PostgreSQL, version is 11.13
- Operating System version is CentOS 7
- I ran the flyway command against a directory full of SQL scripts with the migrate option
- I was expecting to see 1 single SQL script get applied to the database because all others were already applied to the database.
- The result was nothing was applied to the database, flyway gave feedback indicating that there was nothing to run.  If I list the files in the current directory, there is clearly a file that had not been run, it’s filename includes the next higher version number.  If I run the flyway info command, it shows that 109 scripts were applied to the database.  Script 110 is not being recognized.

How can I diagnose this?  I like to get a better understanding on why flyway doesn’t see or recognize this SQL script.

**Comment by Barry-RG** [comment]
Can you provide us with information for a reproduction? For example, what your command looks like

**Comment by wg21908** [comment]
This issue is resolved.  After adding the locations argument with the path to the SQL scripts it worked as expected.  I was under the impression initially, that the fact that I was located in the directory with my SQL scripts that it would just recognize that the scripts were right in the current directory
