### ISSUE TITLE
Feature request: cleanOnValidationError only of last migration

### ISSUE THREAD

**Issue by fabrii** [flyway/flyway#3528]
In our current project, we have Flyway migrations aligned to our backends versions.
For example, if we are releasing backend 0.5.0, then the Flyway script is named V0.5.0.
We have an integration environment where all developers evolve the V0.5.0 script while the version is not released. In this environment we are using the "cleanOnValidationError" parameter. (https://flywaydb.org/documentation/configuration/parameters/cleanOnValidationError).

It would be nice to have a way to only clean the database if the validation error originated in the last script (V0.5.0) and not in a previous script (for example V0.4.0). In the latter case, it would be ideal to get a validation error. This can help to prevent accidental changes in scripts of already released versions. 

Is there any way of implementing this with the current version of Flyway?
Thanks

**Comment by JasonLuo-Redgate** [comment]
Hi @fabrii ,

Just to update that We intend to remove `cleanOnValidationError ` as it is likely to cause more harm than good these days.
From the release notes here https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine, this parameter has been marked as `deprecated`.

**Comment by fabrii** [comment]
Hi @JasonLuo-Redgate.

We are not using it anymore. We decided to have a dev environment with migrations disabled, and an integration environment with small migrations per functionality.

Thanks for the heads up!
