### ISSUE TITLE
Docker hub 9.2.0 arm image is absent

### ISSUE THREAD

**Issue by aliusmiles** [flyway/flyway#3529]
Version 9.2.0 somehow got an arm version of image deleted: https://hub.docker.com/layers/flyway/flyway/9.2.0/images/sha256-f3a2aee4c210a9fc5444f7ca39de0bce723eef00e0b292353d806fa920eadcc1?context=explore

At first I've thought it was some sort of cleanup keeping arm image for only latest version, but both 9.3.x and 9.1.x versions still have arm available.

9.2.0 definitely used to have an arm version as I had successfully built from it.

Decided to report this just in case it's a sign of some build pipeline issue.

**Comment by Barry-RG** [comment]
Hi @aliusmiles 
Thank you for bringing this to our attention, we will investigate.
