### ISSUE TITLE
Introduction of `com.electronwill.night-config` causes license issues

### ISSUE THREAD

**Issue by adamstrawson** [flyway/flyway#3530]
###### Which version and edition of Flyway are you using?
`flyway-core` `v9.3.1` 

 In `9.3.1` `com.electronwill.night-config` was introduced, however this library uses `LGPL-3.0` which means those using flyway  are conditioned on making available complete source code under the same license. (https://choosealicense.com/licenses/lgpl-3.0/) 

I wanted to understand if this change was intentional, or if the license was an oversight when including night-config. 

We can downgrade to `9.3.0` in the mean time, but will be useful to know if we need to re-evaluate our use of flyway.

**Comment by tjs145** [comment]
We don't modify `com.electronwill.night-config`, so do not need to ship Flyway under an LGPL license and nor do Flyway users, so you should be able to use Flyway without having to disclose source code. Hope this helps
