### ISSUE TITLE
Non-transactional migration blocks by `SELECT COUNT(*) FROM pg_namespace WHERE nspname=$1`

### ISSUE THREAD

**Issue by radeklos** [flyway/flyway#3531]
###### Which version and edition of Flyway are you using?
Tested on 9.3.1 and 9.3.0 but got the same results.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
- gradle: 7.5.1
- org.postgresql:postgresql:42.5.0
- com.zaxxer:HikariCP:4.0.3

###### Which database are you using? (Type & version)
PostgreSQL 11.6

###### Which operating system are you using?
- Mac os but failing also on Linux. 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Running migration only with non-transacional statement ([mixed mode](https://flywaydb.org/documentation/configuration/parameters/mixed) isn't set and it's not needed)
```sql
create index concurrently if not exists ...
    on ... (...)
    where (...);
```

###### What did you see instead?
Flyway uses an auto-detect non transactional migration with regular expression: - https://github.com/flyway/flyway/blob/d5ccaf3c5506ae3c910b9aace5b88869c30641cd/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLParser.java#L102

And it seems that there is no extra configuration to execute non-transactional queries. The migration was detected correctly as non-transactional, but it freezes on finishing the migration because it waits on the client to close the migration. The migrations execution freezes and is never finished because of the blocking query described above. 

```sql
SELECT
     activity.pid,
     activity.usename,
     activity.query,
     blocking.pid AS blocking_id,
     blocking.query AS blocking_query
FROM pg_stat_activity AS activity
JOIN pg_stat_activity AS blocking ON blocking.pid = ANY(pg_blocking_pids(activity.pid));

 pid | usename  |                        query                        | blocking_id |                   blocking_query                   
-----+----------+-----------------------------------------------------+-------------+----------------------------------------------------
  72 | sentinel | create index concurrently if not exists ...        +|          71 | SELECT COUNT(*) FROM pg_namespace WHERE nspname=$1
     |          |     on ... (...)                                   +|             | 
     |          |     where (...)                                     |             | 
(1 row)
```

Is there any option on how to successfully run a non-transactional migration with a flyway?

**Comment by DoodleBobBuffPants** [comment]
See [this comment](https://github.com/flyway/flyway/issues/3506#issuecomment-1222246349)

In particular, you will need to set `flyway.postgresql.transactional.lock=false`

Closing as duplicate
