### ISSUE TITLE
flyway version：7.15.0 ，How do I set the field “isSynthetic”=true

### ISSUE THREAD

**Issue by Jasonyouzhe** [flyway/flyway#3537]
issue：flyway version：7.15.0 ，How do I set the field “isSynthetic”=true

When the project is downgraded, the flyway_schema_history table sql records will be deleted（type=delete）, and the script will be executed again during the upgrade, and the error will be reported, so how should we set isSynthetic = true

**Comment by DoodleBobBuffPants** [comment]
Please can you provide a minimal working example of the issue you are seeing

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
