### ISSUE TITLE
`org.flywaydb.core.api.FlywayException: Number of retries exceeded while attempting to acquire PostgreSQL advisory lock. Configure the number of retries with the 'lockRetryCount'

### ISSUE THREAD

**Issue by rajeshhereforyou** [flyway/flyway#3545]
###### Which version and edition of Flyway are you using?
Hi,
I'm using flyway 7.7.3 and using it in my Spring boot java app to execute the SQL scripts against Auorora Postgres 12.4. It was running fine. Then we added a new ALTER script to

ALTER multiple tables to  change the data type of two existing columns in the existing tables with some good amount data.

Now, it started giving below exception. The above alter script is taking more than 10  mins to execute. 

`org.flywaydb.core.api.FlywayException: Number of retries exceeded while attempting to acquire PostgreSQL advisory lock. Configure the number of retries with the 'lockRetryCount' configuration option: https://flywaydb.org/documentation/configuration/parameters/lockRetryCount`

Note:- We tried to monitor the DB during the script run time and observed the advisory lock was there for almost 2 mins and then got released. After couple of mins, it was trying to acquire the lock again, not sure why

Now the question is 

1. I'm not sure if this long running script is causing the above exception ?
2. If yes, how is that causing the lock issue ?

**Comment by DoodleBobBuffPants** [comment]
Could you try this on the latest version of Flyway, as many issues related to this have been fixed over time already

**Comment by rajeshhereforyou** [comment]
The issue is fixed when I set 'lockRetryCount' to 180 the  as mentioned in here 
https://flywaydb.org/documentation/configuration/parameters/lockRetryCount
