### ISSUE TITLE
Possible to make flywayMigrate work with gradle configuration cache?

### ISSUE THREAD

**Issue by danielstravito** [flyway/flyway#3550]
Using latest version of the gradle plugin with configuration cache enabled yields the following warning:

```
- Task `:my-schema:flywayMigrate` of type `org.flywaydb.gradle.task.FlywayMigrateTask`: invocation of 'Task.project' at execution time is unsupported.
```

Which is caused by for example:
```
	at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
	at org.flywaydb.gradle.task.AbstractFlywayTask.addClassesAndResourcesDirs(AbstractFlywayTask.java:683)
```

Is it possible for the flyway plugin to tie into gradle some other way to gather the dependencies in a way that's compatible with the configuration cache? 

This should be reproducible with any version of gradle since configuration cache was added, and by setting the `org.gradle.unsafe.configuration-cache` to `true` in `gradle.properties`.

**Comment by NicklasWallgren** [comment]
@DoodleBobBuffPants I think you should reconsider, or at least leave this open.

**Comment by eskatos** [comment]
The Gradle configuration cache will be declared a stable feature, probably in Gradle 8.1 next month. At this stage you can expect more community interest.
Eventually it will become the default, maybe in Gradle 9.0 next year.
Please reconsider adding support in the flyway plugin.

**Comment by danielstravito** [comment]
From [8.1 rc1 release notes](https://docs.gradle.org/8.1-rc-1/release-notes.html):
> You'll be happy to know that the configuration cache is now stable and ready for general use. The configuration cache was introduced in Gradle 6.6 to help speed up builds by caching the result of the [configuration phase](https://docs.gradle.org/8.1-rc-1/userguide/build_lifecycle.html) and reusing it for subsequent builds. Plus, there are [several other improvements](https://docs.gradle.org/8.1-rc-1/release-notes.html#configuration-cache-improvements) that enhance its usability and compatibility that pave the way for further performance boosts.

**Comment by strindberg** [comment]
Gradle 8.1 is now released, and with it the configuration cache is considered stable. We see considerable performance gains in our project using the cache, but the lack of support in flyway is now a problem for us.

**Comment by davinkevin** [comment]
Please reopen this issue, configuration cache is a killer feature to make everything fast, and flyway not supporting it is a pain…

**Comment by dsvensson** [comment]
As a workaround, or perhaps atrocity, to tap into the stunning performance improvement from gradle configuration cache I added a wrapper task that tests can depend on that tracks changes to the migrations, and if anything has changed, it spaws a new gradle process with `--no-configuration-cache --no-daemon` that runs the real `flywayMigrate`. Really hope @DoodleBobBuffPants changes his mind so I can retire this horrible hack. :joy:

**Comment by dsvensson** [comment]
@DoodleBobBuffPants This issue, if it was open, would currently be at position 10 ranked by :+1: in the issue tracker, and configuration cache is by now something gradle plugins are expected to support. Perhaps time to reconsider?

**Comment by sebek64** [comment]
Any chance this will be implemented?

**Comment by sebek64** [comment]
To add one more hack to the list of hacks, we created a custom task invoking flyway in docker. The task itself is slower, but the overall benefit of increased parallelism is worth it. I really hope we wouldn't have to live with this hack for a long time.

**Comment by strindberg** [comment]
Gradle keeps adding nice features to the configuration cache: https://docs.gradle.org/8.6/release-notes.html

**Comment by autonomousapps** [comment]
@DoodleBobBuffPants does this repo accept community PRs? We might be willing to take this one, although I haven't looked to see how challenging that is yet in this case.

**Comment by autonomousapps** [comment]
just FYI, the configuration cache will be the default in Gradle 9, to be released later this year.
https://blog.gradle.org/road-to-gradle-9

**Comment by autonomousapps** [comment]
I don't think they're interested. I pushed a small PR over two months ago to test the waters, and it hasn't been looked at
https://github.com/flyway/flyway/pull/3898

Internally, we're planning to migrate away from this plugin and use a custom solution that adheres to best practices.

**Comment by mrclrchtr** [comment]
Yes the plugin here doesn't seem to get much love... there are other open tickets like this one for example: https://github.com/flyway/flyway/issues/3798

That sounds interesting. I've also been thinking about moving away. Would the internal solution also be with gradel or something completely different?

**Comment by autonomousapps** [comment]
> Would the internal solution also be with gradel or something completely different?

The internal solution still uses Gradle, but it is heavily coupled to a mostly-internal framework. Luckily, it is OSS, so you can see it [here](https://github.com/cashapp/misk/tree/master/misk-schema-migrator-gradle-plugin).

**Comment by dsvensson** [comment]
@DoodleBobBuffPants Disabling of configuration cache will be deprecated with gradle 9.0.

https://blog.gradle.org/road-to-gradle-9#configuration-cache-improvements

**Comment by hjed** [comment]
Does this mean that flyway does not plan to support future version of gradle? I imagine we'd also move away from flyway if that's the case.

**Comment by rkrisztian** [comment]
@tbcrawford said:

*(Sorry for the edits, I was wrong.)*

> \# Do NOT set this
> org.gradle.configuration-cache.problems=warn

This flag doesn't change anything anymore in Gradle 9.0.0 for tasks already marked as incompatible (see also the confusion about it in https://github.com/gradle/gradle/issues/34356). According to the [release notes](https://docs.gradle.org/9.0.0-rc-3/userguide/upgrading_major_version_9.html), marking a task incompatible should be a temporary solution.
