### ISSUE TITLE
Release notes missing for 9.5.0+

### ISSUE THREAD

**Issue by hemberger** [flyway/flyway#3551]
I'm not sure if this is the appropriate place to report this, but the GitHub release references release notes that do not yet exist, e.g. https://flywaydb.org/documentation/learnmore/releaseNotes#9.5.0. Just reporting in case there's something in the release pipeline that isn't working properly.

Thanks!

**Comment by pzygielo** [comment]
- https://github.com/flyway/flyway/issues/3547

**Comment by hemberger** [comment]
My apologies! Closing as a duplicate of #3547.
