### ISSUE TITLE
Support for MySQL mode of OceanBase database

### ISSUE THREAD

**Issue by whhe** [flyway/flyway#3553]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 8.5.11

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin.

###### Which database are you using? (Type & version)

OceanBase MySQL mode of versions:
- Enterprise Edition 2.2.x
- Community Edition 3.1.x

**Comment by whhe** [comment]
I'd like to try this task and submit a PR for it. Please let me know if someone has any ideas.

**Comment by gakkiyomi** [comment]
@DoodleBobBuffPants @Barry-RG  have any plan to merge this pr for support Oceanbase Mysql mode ?  Oceanbase community's people expectation join the flyway famliy Instead of build it from this pr source code.

**Comment by Barry-RG** [comment]
Oceanbase will be coming soon thanks to a PR from @whhe
