### ISSUE TITLE
Unsupported Database: MariaDB 10.9

### ISSUE THREAD

**Issue by hackyoMa** [flyway/flyway#3557]
###### Which version and edition of Flyway are you using?
9.6.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
no

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
MariaDB 10.9

###### Which operating system are you using?
MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
quickstart

###### What did you expect to see?
Support MariaDB 10.9

###### What did you see instead?
Unsupported Database: MariaDB 10.9

**Comment by OskarZyg** [comment]
Are you relocating flyaway or your mysql/mariadb driver?
