### ISSUE TITLE
Flyway 4.2.0 to 5.0.0

### ISSUE THREAD

**Issue by sanketh-shetty-incontact** [flyway/flyway#3558]
###### Which version and edition of Flyway are you using?

4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
NA

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
MySQL

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We are upgrading from 4.2.0 to 5.0.0 and we have provided property spring.flyway.table=schema_version.
We also have a multi tenant DB schema

###### What did you expect to see?

Newly created schemas after 5.0.0 upgrade should use old table name i.e. schema_version since we have provided that property

###### What did you see instead?
For newly created schema the metadata table name is flyway_schema_history

**Comment by DoodleBobBuffPants** [comment]
As you're relying on Spring's integration you may need to ask the people over at Spring if their integration supports `flyway.table` for your version

Another thing to try for now is setting `flyway.table` instead of `spring.flyway.table`

Closing for now

**Comment by sanketh-shetty-incontact** [comment]
We tried with flyway.table as well but its same.

So lets assume we are not using spring integratoin. Now  if I am migrating to flyway 5.0.0 and have set flyway.table=schema_version.

Now if I create any new schema via flyway, the metadata table will be created as schema_version or flyway_schema_history?

**Comment by DoodleBobBuffPants** [comment]
> Now if I create any new schema via flyway, the metadata table will be created as schema_version or flyway_schema_history?

schema_version

**Comment by sanketh-shetty-incontact** [comment]
@DoodleBobBuffPants 
Ok thanks for the reply. So for us for new schemas its creating the metadata table as flyway_schema_history even though we have provided the property in our config file(tried both flyway.table and spring.flyway.table).

So say if we have few old schemas with metadata table as schema_version and the newly created schemas after flyway 5.0.0 upgrade have metadata table as flyway_schema_history and we have also set the flyway.table property to schema_version. Will it now create any issue when we move to Flyway version 6.0.0?

**Comment by DoodleBobBuffPants** [comment]
Yes, the fallback mechanism is only available in version 5

To complete the upgrade you need to set `table=schema_version` then run `repair` to update the schema of the history table, and then you would need to keep `table=schema_version` going forwards

It's worth noting that this is only for existing schemas, new schemas will work fine without this
