### ISSUE TITLE
Release notes - missing  versions (9.5.0 and more current)

### ISSUE THREAD

**Issue by frichtarik** [flyway/flyway#3561]
release notes do not contain any input since 9.4.0 

https://flywaydb.org/documentation/learnmore/releaseNotes

however they are present at 

https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html

even flyway cli stdout points to flywaydb.org where that particular version is not present
`Upgrade to Flyway 9.7.0: https://rd.gt/2X0gakb`

**Comment by DoodleBobBuffPants** [comment]
The links should now point to `documentation.red-gate.com` - `flywaydb.org` has been deprecated so version numbers on that site won't be kept up to date
