### ISSUE TITLE
Callbacks information in Flyway History table

### ISSUE THREAD

**Issue by tejaspan** [flyway/flyway#3566]
There is no issue. We are requesting new feature where Flyway will insert details for Callbacks execution in history table.

###### Which version and edition of Flyway are you using?
Flyway Community Edition 8.5.13 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I don't think this feature is available in new version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
SQL server and Azure SQL database

###### Which operating system are you using?
Windows

###### What did you expect to see?
Callbacks information in Flyway History table. 

###### What did you see instead?
Flyway doesn't track data for Callbacks file.

**Comment by tjs145** [comment]
Thanks for the suggestion. We probably won't be implementing this feature so closing for now, however we will consider it if there is further interest.
