### ISSUE TITLE
Add option to disregard the flyway_schema_history table

### ISSUE THREAD

**Issue by cies** [flyway/flyway#3567]
I perform the following tasks from Gradle in this order:

* flywayClean
* flywayLoadSchemaAndSeed -- this is a migrate-like task that loads our baseline schema (`db/init/V0-schema.sql`) and seed (`db/init/V1-seed.sql`)

```kotlin
task<FlywayMigrateTask>("flywayLoadSchemaAndSeed") {
  locations = arrayOf("filesystem:${project.projectDir}/db/init")
}
```

* runsqlFixSchemaHistory -- this drops, creates and fills the `flyway_schema_history` table so it lines up with the schema loaded in by previous task
* flywayMigrate -- this runs our migrations from the last time we baselined (the `flyway_schema_history` table contains the right info so flyway knows what to do, and what not to do)

Flyway is smarter than Runsql which does not properly handle `DELIMITER` setting for instance (making it impossible to use Runsql for loading e.g. triggers from a dump).

I'd like to exclusively use Flyway to accomplish this, but I cannot get it to totally disregard the `flyway_schema_history` table. An option to have it disregard it would make, IMHO, flyway more flexible: it can then also be used as a simple script runner.

Say I could do this:

```kotlin
task<FlywayMigrateTask>("flywayLoadSchemaAndSeed") {
  locations = arrayOf("filesystem:${project.projectDir}/db/init")
  disregardSchemaHistory = true
}
```

Then the `flyway_schema_history` table dropping/creating/filling can be part of our `db/init/V0-schema.sql` file, after which the task sequence becomes like this:

* flywayClean
* flywayLoadSchemaAndSeed
* flywayMigrate

And I do not need an additional plugin.

Thanks for considering. If you think this feature is something you'd like to add to the project, I can look into preparing a PR. Maybe such an option already exists, and I just did not discover it.

**Comment by tjs145** [comment]
Thanks for the suggestion. We probably won't be implementing this feature so closing for now, however we will consider it in the future if there is sufficient further interest.

**Comment by cies** [comment]
Ok, fair enough.
