### ISSUE TITLE
Gradle plugin: "No database found to handle"

### ISSUE THREAD

**Issue by sargue** [flyway/flyway#3574]
###### Which version and edition of Flyway are you using?

9.8.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using? (Type & version)

MariaDB 10.5

###### Which operating system are you using?

Windows 10 (for building)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Upgraded my gradle setup from Flyway 7.14.1 to 9.8.3 and now all Flyway gradle tasks fail with the above message. I'm aware there are similar closed issues like #3448 and #3355 so I've tried different changes without success.

Migration on app start using pure Java libraries works as expected (it detects database and validates current migrations).

Here are the relevant parts of the `build.gradle` file.

```
buildscript {
    //...
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.mariadb.jdbc:mariadb-java-client:3.0.6'
    }
}

plugins {
    id "org.flywaydb.flyway" version "9.8.3"
    // ...
}

configurations {
    flywayMigration
    //...
}

dependencies {
    flywayMigration 'org.mariadb.jdbc:mariadb-java-client:3.0.6'

    implementation "org.flywaydb:flyway-mysql:9.8.3"
    //...
}

flyway {
    url = DB_URL
    user = DB_USER
    password = DB_PASS
    table = 'schema_version'
    schemas = [DB_SCHEMA]
}
```

I'm using Java 17 and Gradle 7.4.

###### What did you expect to see?

Flyway gradle tasks working fine.

###### What did you see instead?

> Error occurred while executing flywayInfo
  No database found to handle jdbc:mariadb://vm-mariadb-dev.sargue.net/kprin

**Comment by jschnall** [comment]
I'm having a similar issue with a local mysql db. It opens fine with TablePlus.

> No database found to handle DB_URL=jdbc:mysql://localhost:3306/my_db

**Comment by DoodleBobBuffPants** [comment]
Have you tried adding `org.flywaydb:flyway-mysql:9.8.3` as a `buildscript` dependency as in [this](https://github.com/flyway/flyway/issues/3355#issuecomment-1000585918) comment?

If it still doesn't work, could you provide a minimal reproduction project, including a `build.gradle` and anything particular about how you ran it?

**Comment by sargue** [comment]
My fault. You are totally right I missed adding the flywaydb dependency to the buildscript as well as the JDBC driver I was already adding. It's actually on your documentation, but I somehow misread that about the JDBC driver.

With this buildscript it works now:

```
buildscript {
    dependencies {
        classpath 'org.flywaydb:flyway-mysql:9.8.3'
        classpath 'org.mariadb.jdbc:mariadb-java-client:3.0.6'
    }
}
```
