### ISSUE TITLE
Support for AWS RDS Blue/Green

### ISSUE THREAD

**Issue by Fraserhardy** [flyway/flyway#3575]
Will support for AWS Blue/Green deployments be added to Flyway? Or is this best managed manually from outside of Flyway. The new AWS feature seems like it would work well for changes to be applied to the green instance before being promoted at the end of the migration. 

https://aws.amazon.com/blogs/aws/new-fully-managed-blue-green-deployments-in-amazon-aurora-and-amazon-rds/

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising this issue

It looks fairly easy to manage outside of Flyway for now - you can make changes to the green environment, and promote them when you're ready, which fits into how Flyway already works with staging/production environments

We can take a look at adding built-in support for this promotion if there's further interest in this, so putting it On the Radar and closing for now
