### ISSUE TITLE
Microsoft SQL Server 15.0 - Not Supported With 8.5.13 Version

### ISSUE THREAD

**Issue by vineshraja** [flyway/flyway#3579]
###### Which version and edition of Flyway are you using?
Have upgraded from 8.0.5 to 8.5.13 as part of Spring Boot 2.7.5 Upgrade

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
8.5.13 is the latest version in 8 Series

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Spring Boot - Java

###### Which database are you using? (Type & version)
Microsoft SQL Server 15.0

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Post upgrading Spring Boot 2.7.5, flyway dependency upgraded to 8.5.13 facing below error, in 8.0.5 i didn't see this errro.
19:43:34.109 DataBase Server: MS SQLSERVER
19:43:34.109 Driver Name = microsoft jdbc driver 10.2 for sql server
19:43:34.109 Script Location = classpath:/db/migration/sqlserver/
19:43:34.171 Flyway Community Edition 8.5.13 by Redgate
19:43:34.171 See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13
19:43:34.171 
19:43:34.183 [version] Exception: org.flywaydb.core.api.FlywayException: Unsupported Database: Microsoft SQL Server 15.0

###### What did you expect to see?
Should support MS SQL Server 15 with flyway 8.5.13 version

###### What did you see instead?
 [version] Exception: org.flywaydb.core.api.FlywayException: Unsupported Database: Microsoft SQL Server 15.0

**Comment by Barry-RG** [comment]
Between the releases you specify above, Flyway SQL Server support was extracted int its own module. As a result you must include it in your project. Please see [Flyway SQL Server documentation](https://documentation.red-gate.com/fd/sql-server-184127608.html).
