### ISSUE TITLE
Upgrade JNA to version 5.x

### ISSUE THREAD

**Issue by jippeholwerda** [flyway/flyway#3580]
We use the argon2-jvm library for password-hashing in our Flyway migrations. Argon2-jvm uses JNA 5.8.0. However, since flyway-commandline uses JNA 4.5.2 we have both JNA versions on the classpath at runtime.

This leads to errors like:

```
Exception in thread "main" java.lang.NoSuchMethodError: "com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class)"
	at de.mkammerer.argon2.jna.Argon2Library.<clinit>(Argon2Library.java:13)
	at de.mkammerer.argon2.BaseArgon2.hashBytes(BaseArgon2.java:367)
	at de.mkammerer.argon2.BaseArgon2.hashBytes(BaseArgon2.java:359)
	at de.mkammerer.argon2.BaseArgon2.hash(BaseArgon2.java:77)
	at db.e2e_testdata.V1_3_0__std_users.migrate(V1_3_0__std_users.kt:31)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:62)
```

Would it be possible for Flyway to upgrade the JNA dependency to something more recent in the 5.x range?

**Comment by jippeholwerda** [comment]
I noticed that https://github.com/flyway/flyway/issues/2136 adds the dependency, but the release notes of Flyway 9.2.1 mentions: "Remove JNA dependency as no longer needed by MariaDB". Can the dependency perhaps be removed completely?

**Comment by DoodleBobBuffPants** [comment]
The dependency is required for MariaDB

Could you exclude the JNA dependency from Flyway and depend on the version you need?

**Comment by jippeholwerda** [comment]
Unfortunately not. We use the flyway-commandline.tar.gz in a Dockerfile. I've tried creating a Dockerfile where we remove the jna jar from the lib directory. However, that results in some nasty crashes when running flyway:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000eb6, pid=10, tid=11
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.1+12 (17.0.1+12) (build 17.0.1+12)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (17.0.1+12, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:

# C  0x0000000000000eb6
#
# Core dump will be written. Default location: /flyway/core.10
#
# An error report file with more information is saved as:
# /flyway/hs_err_pid10.log
#
# If you would like to submit a bug report, please visit:
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

/flyway/flyway: line 51:    10 Aborted                 (core dumped) "$JAVA_CMD" $JAVA_ARGS "$EXTRA_ARGS" -cp "$CP" org.flywaydb.commandline.Main "$@"
```

**Comment by DoodleBobBuffPants** [comment]
Are you using MariaDB? If so, then it's best solved by us updating JNA and testing that it works

If not, the following Dockerfile seemed to work with a H2 database to test it

```
FROM flyway/flyway:latest

RUN rm ./drivers/jna-*.jar
```

**Comment by DoodleBobBuffPants** [comment]
Closing till further activity

**Comment by jippeholwerda** [comment]
No, we are not using MariaDB.

As I said, removing the JNA jar from the Docker image resulted in a severe crash.

We've worked around the issue by removing the argon2-jvm dependency so that there are no 2 versions of JNA on the classpath.

I guess that won't help other people running into the same issue, so it probably would be best to upgrade Flyway's JNA dependency to a more recent version in the future...
