### ISSUE TITLE
Subtle ABI Break on "ClassicConfiguration"

### ISSUE THREAD

**Issue by bmarcaur** [flyway/flyway#3582]
###### Which version and edition of Flyway are you using?
Previously using `9.8.3`, trying to upgrade to `9.10.0`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java `Configuration` API

###### Which database are you using? (Type & version)
Postgres ~42

###### Which operating system are you using?
Development is done on a Mac, prod is Unix

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Upgraded the Java library.

###### What did you expect to see?
No compile time breaks on a minor version.

###### What did you see instead?
There is a subtle ABI break on the `ClassicConfiguration` object where the argument signature of [`setBaselineVersion(MigrationVersion version)`](https://github.com/flyway/flyway/blame/main/flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java#L1729) was changed from `MigrationVersion` to `String`. The fix seems trivial enough to stop wrapping the configured `String` in a `MigrationVersion`, but that also seems to be the point of `setBaselineVersionAsString(String version)`. The newly added override seems to prevent Lombok from generating the appropriate setter. This type change broke some of our library upgrade automation due to failing compilation. Not sure if this is an intentional usability "break", but it was introduced in a minor version so it was a surprise.

Thanks!

**Comment by Barry-RG** [comment]
This is currently in our pipeline to fix

**Comment by bmarcaur** [comment]
Hey! Thanks a lot for the quick fix. Appreciate the tool!
