### ISSUE TITLE
Failed migration - Table \"customer\" must be qualified with a dataset

### ISSUE THREAD

**Issue by celiajmd** [flyway/flyway#3586]
###### Which version and edition of Flyway are you using?

Flyway 9.8.1. Community version

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the latest version or very close to the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

BigQuery

###### Which operating system are you using?

Mac & Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

This is the SQL:
```
CREATE TABLE customer (
CUSTOMER_ID INTEGER,
FIRST_NAME STRING,
LAST_NAME STRING
)
```

I wanted to do migrate, however, it gives this error: Table \"customer\" must be qualified with a dataset 

But the schema is given in the config file.
```
flyway.defaultSchema=flyway_demo_dev
flyway.schemas=flyway_demo_dev
```

###### What did you expect to see?

Table is created successfully even thought the dataset is not mentioned in the SQL file, since it is already mentioned in the Config file.

###### What did you see instead?

 Table \"customer\" must be qualified with a dataset

**Comment by DoodleBobBuffPants** [comment]
For BigQuery, you'll have to provide `DefaultDataset` in the JDBC URL for your SQL to use it - does setting that URL parameter work for you?

**Comment by celiajmd** [comment]
It works. Thanks!
