### ISSUE TITLE
Flyway metadata table Rename to match Flyway 6 

### ISSUE THREAD

**Issue by sanketh-shetty-incontact** [flyway/flyway#3589]
###### Which version and edition of Flyway are you using?

5.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

NA

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven

###### Which database are you using? (Type & version)

MySql 5.7

###### Which operating system are you using?
Unix

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

So we are currently on flyway version 5.0.0 with Spring. We have multitenant schemas. We added a property spring.flyway.table=schema_version in config. But still we see that when any new schema is created it names the metadata table as flyway_schema_history instead of schema_version(even tried with property flyway.table=schema_version )

So now to avoid any discrepancy we want to rename all our existing tenant schemas metadata table to flyway_schema_history.

So for this we are planning to add a script for rename table and use flyway only to execute this script for all tenant schemas.

Just wanted to check if we are fine doing that or will using flyway to do any changes to one of its own table may cause any issues?

###### What did you expect to see?
NA

###### What did you see instead?
NA

**Comment by DoodleBobBuffPants** [comment]
In general, no, you shouldn't be modifying the schema history table both within or without of Flyway as its hard to guarantee you've done so safely and it could cause you issues down the line

In this case, setting `flyway.table` should work

A version of Flyway as old as 5 isn't actively supported anymore, so could you provide a reproduction showing Flyway isn't respecting the `flyway.table` property on a more recent version, and could you reproduce this in just Flyway i.e. without Spring

At the same time, it could be an issue with the Spring integration so you may need to raise this with Spring instead

**Comment by sanketh-shetty-incontact** [comment]
Without spring I am not sure as ours is integrated with Spring. But we tried both flyway.table and spring.flyway.table but new schemas still got created with flyway_schema_history as metadata table name.

Now the problem is that if we want to move to flyway 6. But since these properties are not working and since fall back has also been removed in version 6,it will give error I believe. Can you please let us know what will happen once we migrate to flyway 6 now and if these properties are not picked? Will it create flyway_schema_history table in each of the existing schemas and copy data from old schema_version table?

**Comment by DoodleBobBuffPants** [comment]
If you were to upgrade to 6, new schemas would use `flyway_schema_history` however existing schemas will likely say you need to baseline as they are not empty, and data will not be copied from the old `schema_version` table

If you try running Flyway with debug level logging, you should see the configuration it is using being logged, which should also show the value for `flyway.table` which should let you know if the property is being read by Flyway or not

**Comment by DoodleBobBuffPants** [comment]
Closing till further activity

**Comment by sanketh-shetty-incontact** [comment]
@DoodleBobBuffPants I started the service with Debug level for logging but dont see any config being printed. Its ignoring both flyway.table and spring.flyway.table

**Comment by DoodleBobBuffPants** [comment]
Could you:
- share the logs
- try connecting to the database using the Flyway CLI and see if you still get this issue
- provide a minimal reproduction project

**Comment by sanketh-shetty-incontact** [comment]
Actually our use case is that we have a multi tenant schema(4k+ schemas), so we have not gone with default behavior of flyway which happens on service start up. We have written custom code to trigger flyway seperately.

I observed that when I set the flyway table in code(as below) then it worked

Flyway flyway = new Flyway();
flyway.setTable("schema_version")

**Comment by DoodleBobBuffPants** [comment]
As you're creating a new ~Flyway object here and configuring it, the config in the properties file won't be used as the properties file is for configuring that default behaviour of the Spring integration when it runs on start-up

**Comment by sanketh-shetty-incontact** [comment]
This I just added in code to test if it works like this and it worked. But when we are not adding this in code but keeping in properties file(tried both flyway.table=schema_version and spring.flyway.table=schema_version) then new schemas that we create are getting created with metadata table name as flyway_schema_history
