### ISSUE TITLE
Is there a way to build binary for linux arm64?

### ISSUE THREAD

**Issue by daniel-vizai** [flyway/flyway#3590]
###### Which version and edition of Flyway are you using?

community 

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command line

###### Which database are you using? (Type & version)

mysql 11

###### Which operating system are you using?

MacOS Montarey 12..6.1

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

trying to use flyway with docker on mac m1, I need the binary to be built for linux/arm64 and not macosx/arm64 as I'm running flyway inside an arm64 linux container, but I couldn't get it to work as no binary for linux arm64 exist.

###### What did you expect to see?

another build target for linux/arm64 architecture

###### What did you see instead?

no binary

**Comment by DoodleBobBuffPants** [comment]
Our `flyway/flyway` images already have a `linux/arm64` [image](https://hub.docker.com/layers/flyway/flyway/latest/images/sha256-fcf1a6c8458c9c6548ed7ff861628f3db0bd5a6dedf24c4a6f69506ef2dd6f2c?context=explore)

You can also use our [artifacts](https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.10.2/) that doesn't bundle a JRE, and provide your own platform-specific JRE (they're the `zip`/`tar.gz` files without an OS in the name)
