### ISSUE TITLE
Downloads of all versions of Flyway are broken from the website

### ISSUE THREAD

**Issue by jmanus** [flyway/flyway#3595]
###### Which version and edition of Flyway are you using?

Tried to download anything from https://documentation.red-gate.com/fd/command-line-184127404.html, and I get a 404:

https://download.red-gate.com/maven/release/org/flywaydb/enterprise/flyway-commandline/flyway-commandline-9.11.0-macosx-x64.tar.gz gives a 404

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Chrome

###### Which database are you using? (Type & version)

Postgres

###### Which operating system are you using?

Mac

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I think that this is some kind of issue with Maven, and I _think_ that it is causing a broader Flyway outage when versions check maven for packages.

**Comment by DoodleBobBuffPants** [comment]
Thanks for raising this with us, the links on the page should be fixed now
