### ISSUE TITLE
Flyway doesn't work when password starts with $

### ISSUE THREAD

**Issue by jayceebernardino** [flyway/flyway#3596]
###### Which version and edition of Flyway are you using?
docker image > `flyway/flyway:9.8`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
docker command line

###### Which database are you using? (Type & version)
Postgres

###### Which operating system are you using?
Ubuntu with docker 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
```
root@193bc3e6e5de:/flyway# flyway migrate
Database password:
```

###### What did you expect to see?
When wrong password is used
```
ERROR: Unable to obtain connection from database (jdbc:postgresql://database:5432/databasename) for user 'random': FATAL: password authentication failed for user "random"
```

###### What did you see instead?
```
root@193bc3e6e5de:/flyway# flyway migrate
Database password:
ERROR: Unknown resolver: sdfds
```

**Comment by pauljohe-dnb** [comment]
I'm facing this issue as well. I have downgraded flyway to version 9.8 until fixed.

```
root@44807434a68b:/flyway# flyway -url='jdbc:db2://db2database/db2' -user='test' -password='$password123' -connectRetries=5 -validateMigrationNaming=true -baselineOnMigrate=true migrate info
ERROR: Unknown resolver: password123
```

The problem appears to be in https://github.com/flyway/flyway/blob/a0d26ea8530494386503207b093f19ff2e08758b/flyway-core/src/main/java/org/flywaydb/core/internal/configuration/resolvers/PropertyResolverContextImpl.java

**Comment by Barry-RG** [comment]
Thank you for your issue. Due to new configuration management changes in Flyway, there is a new resolver concept that needs to be managed. Please read the latest [Configuration Documentation](https://documentation.red-gate.com/fd/configuration-184127448.html). 
As pointed out above, prefixing any field that starts with `$` with `$$` escapes the resolver and will use the field as a plain text field rather than a field to be resolved. However, to clarify, this is not a work around but the correct documented way to manage fields starting with `$`.

**Comment by TheRealChssAddct** [comment]
Thanks for this official response

**Comment by ludwiggj** [comment]
Strikes me that adding special functionality to the password in this way is a **really bad idea**, and an easy way to cause lots of unintentional problems.

This broke my development environment on an upgrade from 9.8.3 to 9.14.0, and doesn't work with the $$ solution either when using the Java API via scala - in this case I get a "FATAL: password authentication failed: instead.

I guess I'll have to get the password updated in order for me to be able to upgrade.

**Comment by steers** [comment]
I don't see any mention of the `new resolver concept that needs to be managed` on [the Flyway release notes](https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html), but as other commenters have pointed out, [the property resolver functionality was added in flyway 9.90](https://github.com/flyway/flyway/commit/a0d26ea8530494386503207b093f19ff2e08758b)

From the documentation linked by @Barry-RG it seems like the new Secrets Management options are only available in Flyway Enterprise, but not community edition, which is also impacted by this change.

I can't actually see any documented examples of when a value beginning with `$` should be defined to make use of this resolver concept, am I missing something? Examples for AWS, GCP and Vault all involve removing `flyway.password` from the main configuration file, and instead defining it in an external secret store.

So if the new resolver concept effectively cannot be used in flyway community edition, could this new resolver functionality be disabled through some means (e.g. a parameter or environment variable) to preserve prior behaviour?

**Comment by abscondment** [comment]
This is an incredibly frustrating and dangerous sharp edge. Migrations worked great in most of our environments, but then broke inscrutably. The solution is to... at runtime, examine our (randomly generated) passwords, test for whether they start with a magic value, and prepend `$` if they do?

+1 on allowing folks to control this feature via configuration. I would urge you to leave it off by default. Who wants a magic string possibly breaking their migrations?

**Comment by vsabella** [comment]
@Barry-RG   

This is a very frustrating and dangerous breaking change for a variety of reasons. We were about to consider licensing Flyway Enterprise for some of the functionality but this is a serious blocker for us unfortunately.

I'm not sure we've learned from the lessons of the Apache Log4j fiasco. 

Having magic strings, which are sometimes user-entered, resulting in having the code take an unintended code path through other modules seems exceptionally short-sighted. There are a lot better approaches to achieve this goal.

**Comment by maxventu** [comment]
@Barry-RG this issue took few man-hours to debug.
You mentioned latest configuration documentation, but there's no notion of any exceptions for `$` in [`password` configuration documentation](https://documentation.red-gate.com/fd/password-184127524.html).
It would be very beneficial if the lib will use `password` as is, w/o any hidden features.
And if templating feature is required for clients of the lib, let's add a configuration flag.

**Comment by Barry-RG** [comment]
Thank you all for your responses, I appreciate that the communication on the new Placeholder format has not been as good as we would have liked. 
In regards to the concern over adding new functionality to passwords, this has been done to add refurbish and extend the methods to inject passwords and other fields into flyway configuration from other secure sources. This is similar to our existing placeholder mechanic with scripts but now also applies to a new extent to our Configuration.
We will take your comments on board and update both our documentation and implementation in due course.

**Comment by pvarga88** [comment]
Prefixing an extra $ does not seem to work. It seems Flyway keeps it with $$ in DriverDataSource and passes it as such to the database, which obviously rejects it due to the wrong password.
So, the title of this issue is valid - it is now impossible to use Flyway with a password that starts with $.
