### ISSUE TITLE
Does Flyway support filtered migration by label or version number?

### ISSUE THREAD

**Issue by celiajmd** [flyway/flyway#3597]
###### Which version and edition of Flyway are you using?

9.8.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

BigQuery

###### Which operating system are you using?

GCP CloudBuild

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I have multiple SQL files. Each of them has a certain version number. Can I filter some of the SQL scripts and only migrate those? 
For example, I have files:
V01.01__sql1.sql
V01.02__sql2.sql

Is there a command to only migrate V01.02, not V01.01? As the '01', '02' here is referring to different teams, or datasets.
If not, is there any workaround such as label the scripts? And filtering by the labels? 

###### What did you expect to see?

I have multiple folders and multiple sql files. I want to deploy only some of them to a upper environment.

###### What did you see instead?

I don't find such feature.

**Comment by nycjay** [comment]
One possible solution, not necessarily best, is to use a different prefix 

so, some scripts are All…sql, and some are ProdOnly….sql

then, in dev or test environments you include both prefixes, and only include one in prod.

**Comment by tjs145** [comment]
Similarly, you could store them in different folders and select which folders to migrate by configuring `locations`

**Comment by celiajmd** [comment]
> One possible solution, not necessarily best, is to use a different prefix
> 
> so, some scripts are All…sql, and some are ProdOnly….sql
> 
> then, in dev or test environments you include both prefixes, and only include one in prod.


Thanks! I tried with prefix 'R01' to represent release 01.  The sql file name is R0101.01.sql.  I have put the following in the cloud build yaml file: 

```
 '-sqlMigrationPrefix=${_RELEASE_PREFIX}',
```
It turns out this error:
```
`unknown shorthand flag: 's' in -sqlMigrationPrefix=R01`
```

Can you please help?

**Comment by nycjay** [comment]
Not at my computer to look, but I use a separate folder per release, but keep the prefix the same, so I don’t have the numbers as part of it.

**Comment by celiajmd** [comment]
> Not at my computer to look, but I use a separate folder per release, but keep the prefix the same, so I don’t have the numbers as part of it.

Could you provide an example of your sql file name, and sqlMigrationPrefix value in this case?

**Comment by tjs145** [comment]
Closing until further activity
