### ISSUE TITLE
ERROR: Unable to release PostgreSQL advisory lock ERROR: Number of retries exceeded while attempting to acquire PostgreSQL advisory lock

### ISSUE THREAD

**Issue by fjiang-aamc** [flyway/flyway#3600]
###### Which version and edition of Flyway are you using?
flyway-7.5.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Bitbucket flyway- command-lin

###### Which database are you using? (Type & version)

Aurora PostgreSQL 12.8

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

**using flyway in Bitbucket to migrate SQL script to AWS RDS instance, then manually stopping the pipeline since the migration took too long. started a new pipeline to migrate again **  

###### What did you expect to see?
**the migration should be success as usual**

###### What did you see instead?

**flyway info logs:** 
sh -x /home/ec2-user/flyway-7.5.4/script/$BITBUCKET_REPO_SLUG.sh
+ for schema in "${schemas[@]}"
+ flyway migrate -configFiles=/home/ec2-user/flyway-7.5.4/conf/xxxxx.conf
Flyway Community Edition 7.5.4 by Redgate
Database: jdbc:postgresql://staging-amcas.cluster-xxxxx.us-east-1.rds.amazonaws.com/xxxx(PostgreSQL 12.8)
Successfully validated 65 migrations (execution time 00:00.102s)
ERROR: Unable to release PostgreSQL advisory lock
ERROR: Number of retries exceeded while attempting to acquire PostgreSQL advisory lock
+ flyway info -configFiles=/home/ec2-user/flyway-7.5.4/conf/xxxxx.conf
Flyway Community Edition 7.5.4 by Redgate
Database: jdbc:postgresql://staging-amcas.cluster-xxxxx.us-east-1.rds.amazonaws.com/xxxx(PostgreSQL 12.8)
Schema version: 2301060800

**Comment by DoodleBobBuffPants** [comment]
Could you try this on the latest version of Flyway as many issues with locking in PostgreSQL have been fixed since then

**Comment by DoodleBobBuffPants** [comment]
Closing till further activity
