### ISSUE TITLE
official support of snowflake v7

### ISSUE THREAD

**Issue by frichtarik** [flyway/flyway#3602]
###### Which version and edition of Flyway are you using?
latest 9.x

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line (standalone and docker)

###### Which database are you using? (Type & version)
Snowflake 7.0.0

###### Which operating system are you using?
linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

with every run i'm getting warning

`Flyway upgrade recommended: Snowflake 7.0 is newer than this version of Flyway and support has not been tested. The latest supported version of Snowflake is 6.29.`

###### What did you expect to see?
nothing

###### What did you see instead?
warning

this is basically a reiteration of #3386

**Comment by tjs145** [comment]
Thanks for letting us known. The next release of Flyway will officially support up to version 7.1.
