### ISSUE TITLE
Flyway Clean fails with ORA-32794 on Oracle

### ISSUE THREAD

**Issue by rbroth** [flyway/flyway#3603]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 9.11.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line via bash in VSCode on windows. 

###### Which database are you using? (Type & version)
Oracle 19.1

###### Which operating system are you using?
Windows 10 enterprise 64 bit

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

When creating a table with an identity primary key outside of flyway (using DBeaver 22.3.2) and then dropping it, I cannot clean the schema anymore without first purging the recycling bin.

in DBeaver:
```
CREATE TABLE tbl (
    col1              NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)        NOT NULL, CONSTRAINT tblpk PRIMARY KEY (col1)
)
;
DROP TABLE tbl;
```

Running `flyway clean` at this point errors out (see below).

Running ```PURGE RECYCLEBIN;``` in DBeaver makes `flyway clean` work fine again.

`SELECT * FROM user_recyclebin` shows the following:

|OBJECT_NAME|ORIGINAL_NAME|OPERATION|TYPE|TS_NAME|CREATETIME|DROPTIME|DROPSCN|PARTITION_NAME|CAN_UNDROP|CAN_PURGE|RELATED|BASE_OBJECT|PURGE_OBJECT|SPACE|
|-----------|-------------|---------|----|-------|----------|--------|-------|--------------|----------|---------|-------|-----------|------------|-----|
|BIN$8oqBnAOiaBbgUwg3lAouEg==$0|TBLPK|DROP|INDEX|TS3A|2023-01-18:13:59:09|2023-01-18:13:59:10|6033340405379||NO|YES|902771|902771|902773|0|
|BIN$8oqBnAOjaBbgUwg3lAouEg==$0|TBL|DROP|TABLE|TS3A|2023-01-18:13:59:09|2023-01-18:13:59:10|6033340405379||YES|YES|902771|902771|902771|0|

###### What did you expect to see?
```
$ flyway clean
Flyway is up to date
Flyway Community Edition 9.11.0 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.11.0

Database: jdbc:[redacted] (Oracle 19.1)
Successfully dropped pre-schema database level objects (execution time 00:00.001s)
Successfully cleaned schema "[redacted]" (execution time 00:00.109s)
Successfully cleaned schema "[redacted]" (execution time 00:00.039s)
Successfully dropped post-schema database level objects (execution time 00:00.000s)
```

###### What did you see instead?

When running `flyway clean` after dropping the table, I get the following error:

```
$ flyway clean
Flyway is up to date
Flyway Community Edition 9.11.0 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.11.0

Database: jdbc:[redacted] (Oracle 19.1)
Successfully dropped pre-schema database level objects (execution time 00:00.001s)
ERROR: Unable to clean schema "[redacted]"
------------------------------
SQL State  : 99999
Error Code : 32794
Message    : ORA-32794: cannot drop a system-generated sequence

Caused by: java.sql.SQLException: ORA-32794: cannot drop a system-generated sequence

Caused by: Error : 32794, Position : 22, Sql = DROP SEQUENCE "[redacted]"."ISEQ$$_902762", OriginalSql = DROP SEQUENCE "[redacted]"."ISEQ$$_902762", Error Msg = ORA-32794: cannot drop a system-generated sequence
```

**Comment by rbroth** [comment]
Related issue: https://github.com/flyway/flyway/issues/3112

**Comment by rbroth** [comment]
Also related: https://github.com/flyway/flyway/issues/1049

Apparently this was fixed previously

**Comment by DoodleBobBuffPants** [comment]
The issue here is to do with the `RECYCLEBIN`

We're unlikely to add purging the `RECYCLEBIN` to Flyway unless there's more interest/need, so you could `PURGE RECYCLEBIN` in a `beforeClean` [callback](https://documentation.red-gate.com/fd/callback-concept-184127466.html) to work around this, or disable the `RECYCLEBIN` as in https://github.com/flyway/flyway/issues/3112#issuecomment-801012756
