### ISSUE TITLE
New documentation page noticeably less developer-friendly

### ISSUE THREAD

**Issue by cowwoc** [flyway/flyway#3607]
I just wanted to provide you with some feedback. I find the new documentation page at https://documentation.red-gate.com/fd/welcome-to-flyway-184127914.html much harder to understand, browser, read than the old documentation at https://flywaydb.org/documentation/usage/maven/

As a developer, the old documentation allows me to jump in and get up-and-running within 2 minutes. The new documentation buries this information under tons of Enterprisey sales material I have no care for.

Please restore the usability of the documentation page. In its current form, it becomes very hard for me to convince fellow developers to use it instead of alternative technologies.

**Comment by JasonLuo-Redgate** [comment]
Hi Gili, thanks for bring this up. 
The corresponding Maven plugin page in flywaydb.org can now be found here https://documentation.red-gate.com/fd/maven-goal-184127408.html.
