### ISSUE TITLE
Script Config Files does not work for scripts in classpath

### ISSUE THREAD

**Issue by DenisKusakin** [flyway/flyway#3608]
###### Which version and edition of Flyway are you using?
9.12.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
postgresql

###### Which operating system are you using?
linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We need to upgrade flyway from **5.2.4** to the **latest version** but there are some scripts that contain non **UTF-8** symbols. Scripts located in the classpath. [Similar issues](https://github.com/flyway/flyway/issues/2766) was posted before and it seems that we could utilize [Script Config Files](https://documentation.red-gate.com/fd/script-config-files-184127476.html) to change encoding for particular files

###### What did you expect to see?
I expect that [Script Config Files](https://documentation.red-gate.com/fd/script-config-files-184127476.html) works for **classpath files**(in particular, to change encoding)

###### What did you see instead?
According to logs, flyway did not apply encoding specified in script config file

The same works well if migrations located in filesystem instead of classpath

**Comment by tomdcc** [comment]
We also just hit this, was surprised that this doesn't work since it's the only documented way to get a script migration to be non-transactional.

**Comment by joschi** [comment]
@JasonLuo-Redgate Would you be open for community-driven contributions for this feature request?

There are a lot of open PRs in https://github.com/flyway/flyway/pulls, so I'd rather ask before.

**Comment by JasonLuo-Redgate** [comment]
Hi @DenisKusakin , could you confirm by referring `classpath files`, you mean non-sql files, like `bash` or `powershell` file?

**Comment by joschi** [comment]
@JasonLuo-Redgate We store the SQL-based migration files in our JAR artifacts which then will be executed on application startup.
These end up on the class path and are not actual files on the filesystem where the application is being executed.

When adding a script config file which is also baked into the JAR artifact, it doesn't have any effect while having all of them on the filesystem works as expected.

**Comment by DenisKusakin** [comment]
> Hi @DenisKusakin , could you confirm by referring `classpath files`, you mean non-sql files, like `bash` or `powershell` file? Or `.java `migration file?

Hi, I mean sql files

**Comment by robrez** [comment]
Anyone have a workaround?

**Comment by JasonLuo-Redgate** [comment]
Hi @DenisKusakin @joschi ,

I locally explored this scenario, and it looks like both the `sql file` and the `sql.conf` file were picked up by Flyway.
My setting: `locations = ["classpath:flyway-sample"]`

![image](https://github.com/flyway/flyway/assets/130552403/a6a4f5cc-6b82-4d7a-9cb2-b112c351b929)

**Comment by robrez** [comment]
Thanks for looking Jason, I should mentioned I was testing on an older version of flyway at work for tech-debt reasons (IIRC, because we have some pg9.6 deployments).  I want to say we're using v7.x.x.

I will try again (tomorrow). Now that you've provided the screenshot above... I'm almost positive that my setup was (incorrect) as follows:

```bash
V0__zero.sql
V0__zero.conf
```

**Comment by robrez** [comment]
Flyway version - `7.15.0`

I hopped back online and confirmed that my particular problem was my own and that when I corrected my configuration, everything worked correctly:

```patch
  V0__zero.sql
- V0__zero.conf
+ V0__zero.sql.conf
```

FWIW, I am _not_ the OP. Thanks again
