### ISSUE TITLE
Add migration location

### ISSUE THREAD

**Issue by clansing33** [flyway/flyway#3612]
###### Which version and edition of Flyway are you using?
Flyway Desktop V 6.0.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Flyway Desktop

###### Which database are you using? (Type & version)
Postgres

###### Which operating system are you using?
Windows 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Created a New Project using the New Project button.  After I changed the config file to point to a different directory for the migration files using "flyway.locations=filesystem:new location".  Flyway desktop recognizes this path and the files via the Manage migrations screen.

I used the Add migration button to add a new migration file

###### What did you expect to see?
I wanted to see the new file added to the location I have configured in the conf file
"flyway.locations=filesystem:new location"

###### What did you see instead?
 The new migration file was added to the default location ("migration") where the project files are stored.

**Comment by JasonLuo-Redgate** [comment]
Hi @clansing33 ,I locally tried Desktop version  6.3.8, the migration files were successfully added into the new folder when a new location was set through "flyway.locations", would you check the new version to see whether this is the case?

**Comment by clansing33** [comment]
Looks good.  Just tested with 6.3.14.  Now that I went through it again, I wonder if after I changed the conf file, that I didn't reload the project and that's why it acted the way it did when I created the issue.

All is well and works like I need it to - thank you!
