### ISSUE TITLE
Caused by: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mysql://localhost:55604

### ISSUE THREAD

**Issue by JobetSamuel** [flyway/flyway#3615]
###### Which version and edition of Flyway are you using?

Using Flyway version 9.5.1 

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Using recommended Springboot compatible version for flyway 9.5.1.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle Plugin 

###### Which database are you using? (Type & version)
mysql 8

###### Which operating system are you using?
mac os

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Running the integration tests using MysqlContainer which works fine breaks now after the migration. Tried downgrading flyway to older versions doesn't work.

Migration from Sprinboot 2.7.5 to Springboot 3.0.2

###### What did you expect to see?
To work without the below error.

###### What did you see instead?

After upgrading to Springboot 3 and with flyway version from 7.15.0 to 9.5.1  and mysql-connector version 8.0.32

 Caused by: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mysql://localhost:55604/

**Comment by tjs145** [comment]
You'll need to make sure that the [`flyway-mysql`](https://repo1.maven.org/maven2/org/flywaydb/flyway-mysql/) artefact is on the classpath

**Comment by JobetSamuel** [comment]
@tjs145 Thanks for your reply! It fixes the above issue. But starts complaining when i run integration tests:

Caused by: org.flywaydb.core.api.FlywayException: Unable to execute clean as it has been disabled with the 'flyway.cleanDisabled' property

**Comment by tjs145** [comment]
In more recent versions, the `clean` command has to be manually enabled by setting `flyway.cleanDisabled` to `false`. More info [here.](https://documentation.red-gate.com/fd/clean-disabled-184127486.html)

**Comment by PyruzJanbaaz** [comment]
@tjs145 Not Found
