### ISSUE TITLE
Migration fails as Flyway detects missing files as future files

### ISSUE THREAD

**Issue by tejaspan** [flyway/flyway#3617]
###### Which version and edition of Flyway are you using?
Community 9.14.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This is latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
SQL Server 2019

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Migration fails and when we do Info it shows the migrations state is Future despite the Installed_On date is in past and migration file is not present in given location. This is for versioned files.
![image](https://user-images.githubusercontent.com/49127166/217666582-fe4e40af-52a8-42cb-91d3-c259486969ab.png)

###### What did you expect to see?
Info state should show missing.

###### What did you see instead?
Future

**Comment by JasonLuo-Redgate** [comment]
Hi @tejaspan , "Future" indicates that This migration's version is higher than the schema history table’s current version, more info can be found here https://flywaydb.org/documentation/concepts/migrations#migration-states
