### ISSUE TITLE
PostgreSQL warning 13.10 not supported

### ISSUE THREAD

**Issue by AndreVelde** [flyway/flyway#3623]
###### Which version and edition of Flyway are you using?
9.14.1 (org.flywaydb:flyway-core)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API (org.flywaydb:flyway-core)

###### Which database are you using? (Type & version)
PostgresSQL 13.10

###### Which operating system are you using?
Windows 10

###### What did you expect to see?
No warnings to appear when the server starts

###### What did you see instead?
`Flyway upgrade recommended: PostgreSQL 13.10 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 12.`

**Comment by tjs145** [comment]
I can't reproduce this on the latest version, which should support up to PostgreSQL 15. 

https://github.com/flyway/flyway/blob/main/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLDatabase.java#L64

Are you sure you're on Flyway 9.14.1?

**Comment by AndreVelde** [comment]
Seems like I put the version number on the wrong spot (thought it would take the same version number as with the gradle plugin)
