### ISSUE TITLE
A schema contains a horizontal bar, such as "test-db1"

### ISSUE THREAD

**Issue by lushengBrother** [flyway/flyway#3627]
###### Which version and edition of Flyway are you using?
4.0.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I can not use the latest one.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java

###### Which database are you using? (Type & version)
PostgreSQL 9.2

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
In the PostgreSQL database I use, a schema contains a horizontal bar, such as "test-db1". When I start the flyway project, the console reports the following error:

Caused by: org.flywaydb.core.api.FlywayException: Error restoring current schema to its original setting

My configuration is as follows:
Datasource config:
```
@Bean("testDataSource")
public DataSource getSnapshotDataSource() {
        DataSourceBuilder dataSource = DataSourceBuilder.create();
        dataSource.driverClassName(driverClassName);
        dataSource.url("jdbc:postgresql:/host:port/test?currentSchema=test-db1");
        dataSource.username(userName);
        dataSource.password(password);
        return dataSource.build();
```
Flyway config:
```
@Bean(name = "testFlyway", initMethod = "migrate")
public Flyway testFlyway(@Qualifier("testDataSource") DataSource dataSource) {
        Flyway configuration = new Flyway();
        configuration.setBaselineOnMigrate(true);
        configuration.setOutOfOrder(true);
        configuration.setPlaceholderReplacement(false);
        configuration.setPlaceholderPrefix("#[");
        configuration.setPlaceholderSuffix("]");
        configuration.setDataSource(dataSource);
        configuration.setLocations("classpath:/db/testdb");
        configuration.setTable("test_db_flyway_schema_history");
        return configuration;
    }
```

Is my configuration incorrect or does Flyway not support this type of schema?

**Comment by JasonLuo-Redgate** [comment]
Hi @lushengBrother , to narrow down the issue, have your tried changing the name of your schema, removing the hyphen, to see whether it works?

**Comment by JasonLuo-Redgate** [comment]
Hi @lushengBrother , I can reproduce this error you mentioned with Flyway API version 4, but I also tried Flyway API version 9+, it works fine with a schema contains a "-" in it. 
So this issue was fixed in latest version.

**Comment by JasonLuo-Redgate** [comment]
Local test result as below with Flyway API version 9.0.1

![image](https://github.com/flyway/flyway/assets/130552403/42773abc-6a32-47a2-aa9a-fd6921bc2ad0)
