### ISSUE TITLE
FluentConfiguration#loggers outdated Javadoc

### ISSUE THREAD

**Issue by Djaytan** [flyway/flyway#3629]
###### Which version and edition of Flyway are you using?

v9.15.1 (latest one)

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

SQLite during my tests

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I read the Javadoc for `FluentConfiguration#loggers` directly from my IDE (so the impacted Javadoc is the one retrieved bundled with the artifact into Maven Central) and I found that for using SLF4J, I need to put `slf4j2`. Then, I just put this value.

But in fact, I read the same from the Javadoc official website: https://flywaydb.org/documentation/usage/api/javadoc/org/flywaydb/core/api/configuration/FluentConfiguration.html#loggers(java.lang.String...)

###### What did you expect to see?

Flyway using SLF4J for logging

###### What did you see instead?

An error: class not found or something like that. And this is obvious when looking at the code why the problem occurs (into LogFactory):
![image](https://user-images.githubusercontent.com/26904516/221432507-6a4eca5f-9cbf-4973-8179-b415359f5a1a.png)

So... When I put `slf4j` it works as expected.

Another thing maybe related: sources are not sync with the bytecode it seems:
![image](https://user-images.githubusercontent.com/26904516/221432373-c5bd86f5-37e5-4f41-81a8-a64ca621e327.png)

**Comment by Barry-RG** [comment]
[https://flywaydb.org/documentation](https://flywaydb.org/documentation)) and its children pages is now deprecated and moved to https://documentation.red-gate.com/fd/flyway-cli-and-api-183306238.html. For Javadocs please see https://documentation.red-gate.com/fd/api-javadoc-184127636.html
