### ISSUE TITLE
Placeholders leaked as options on exception

### ISSUE THREAD

**Issue by Hubbitus** [flyway/flyway#3633]
###### Which version and edition of Flyway are you using?

9.15.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Clickhouse (with https://github.com/flyway/flyway/pull/3611)

###### Which operating system are you using?
Fedora Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

```
$ ./flyway -user=default -password='qwerty' -url=jdbc:clickhouse://default@127.0.0.1:8123/datamart -placeholders.pass=value2 -placeholders.my_remote_db_password=password_value migrate 2>&1
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Flyway Community Edition 9.15.2 by Redgate
See release notes here: https://rd.gt/416ObMi

ERROR: Unable to obtain connection from database (jdbc:clickhouse://default@127.0.0.1:8123/datamart) for user 'default': Connection refused, server ClickHouseNode [uri=http://127.0.0.1:8123/datamart, options={my_remote_db_password=password_value,pass=value2}]@-562309298
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08000
Error Code : 210
Message    : Connection refused, server ClickHouseNode [uri=http://127.0.0.1:8123/datamart, options={my_remote_db_password=password_value,pass=value2}]@-562309298

Caused by: java.sql.SQLException: Connection refused, server ClickHouseNode [uri=http://127.0.0.1:8123/datamart, options={my_remote_db_password=password_value,pass=value2}]@-562309298
Caused by: java.net.ConnectException: Connection refused
```

###### What did you expect to see?
There is no present sensitive information like passwords in options={} block.

###### What did you see instead?
I run similar code on CI/CD and see in logs passwords to the remote database:
`server ClickHouseNode [uri=http://127.0.0.1:8123/datamart, options={my_remote_db_password=password_value,pass=value2}]`

What also interesting, placeholder with name `password` omitted. But it does not allow providing such in different name (several values).

It would be helpful to have an option with comma-separated placeholder names, which should not be dumped to an error message.

**Comment by Barry-RG** [comment]
Since Clickhouse is not supported by Flyway at this time and it looks like a server log being returned in this instance, we will not be looking at this issue at this time.
