### ISSUE TITLE
Artifact flyway-parent is missing starting from 9.15.2 version

### ISSUE THREAD

**Issue by oleg-sukhov** [flyway/flyway#3639]
###### Which version and edition of Flyway are you using?
9.15.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API, Maven plugin

###### Which database are you using? (Type & version)

MySQL

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

After upgrading to version 9.15.2 the build is failed due to not able to download dependencies from https://download.red-gate.com/maven/release repository.

###### What did you expect to see?

The dependencies is downloaded successfully

###### What did you see instead?

Dependencies not found error.

![failed-build](https://user-images.githubusercontent.com/8500133/227506405-7cca23d3-f4d9-4e26-82c7-24d893e28cba.png)

**Comment by Barry-RG** [comment]
Thank you for bring this to our attention. This will be investigated

**Comment by oleg-sukhov** [comment]
Thank you, @Barry-RG
