### ISSUE TITLE
On MySQL engine parameter is hard-coded to InnoDB, this brakes replication to a diffrent storage engine

### ISSUE THREAD

**Issue by kantselovich** [flyway/flyway#3641]
###### Which version and edition of Flyway are you using?

8.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes, I can 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command line 

###### Which database are you using? (Type & version)

MySQL 5.6, 5.7 

###### Which operating system are you using?

Ubuntu 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Applying flyway migration to a new schema, to a database server that has a replica running a different storage engine. 
Ref https://dev.mysql.com/doc/refman/5.7/en/replication-solutions-diffengines.html

###### What did you expect to see?

Flyway migration applied successfully. 
Database changes from migration applied successfully to the replica server, running a different storage engine.

###### What did you see instead?

Flyway migration applied successfully. 
Replication stops with the error "cannot create table 'migrations'"

###### Additional info:

On MySQL engine parameter is hard-coded to InnoDB, this brakes replication to a diffrent engine, when flyway runs against a schema for the first time. 

https://github.com/flyway/flyway/blob/75c3b9027ad86861f93977c176ac4b451806723b/flyway-mysql/src/main/java/org/flywaydb/database/mysql/MySQLDatabase.java#L160-L174

**Comment by kantselovich** [comment]
Any updates here?  Let me know if you need any details ?

**Comment by kantselovich** [comment]
@PabloThiele thank you for  the reminder about support timeline for MySQL 5.7

However, the problem raised in this issue  is not specific to MySQL 5.7 and it is not really addressed by your comment. 
It has to do that in flyway storage engine definition  is hard-coded to be  InnoDB.  

MySQL supports [various storage engines ](https://dev.mysql.com/doc/refman/8.0/en/storage-engines.html), and there are cases when setting replication with different storage engines on master & replicas are beneficial.    That 'cross storage engine' replication will be broken by flyway creating migrations history table with ENGINE=InnoDB -- create table statement with ENGINE=InnoDB will be pushed to binlog on the primary (master) database and then this statement can cause failure in SQL Slave applying binlog changes on the replica if InnoDB storage engine is not available.

I think this problem can simply be solved removing specific storage engine from table definition and using the default. I do not see any benefits of hard-coding storage engine to be InnoDB.  Or possibly storage engine specification can be made as configurable option, but that will add complications and more code to maintain, so  I would consider this option if there are benefits to it.

I would like to get some feedback on https://github.com/flyway/flyway/pull/3642

Thanks you,
-Konstantin 



If 
See  https://github.com/flyway/flyway/pull/3642

**Comment by kantselovich** [comment]
UP.

**Comment by piers-williams** [comment]
Thank you for your contribution, this has been incorporated into Flyway 10.22.0 released yesterday
