### ISSUE TITLE
Postgres create function as SQL language block (rather than string constant) results in syntax error.

### ISSUE THREAD

**Issue by mackler** [flyway/flyway#3643]
###### Which version and edition of Flyway are you using?

9.16.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command line

###### Which database are you using? (Type & version)

Postgres 14.6 as distributed in the [citusdata/citus:11.1.5-pg14](https://hub.docker.com/layers/citusdata/citus/11.1.5-pg14/images/sha256-faf7cfb210c16cc5256c03d1f376f5287e7236a2cf6dd505c5f6778c5414edb8?context=explore) docker image.

###### Which operating system are you using?

Flyway is running in the docker container for citusdata/citus:11.1.5-pg14 as referenced above.

Docker is running on:
Devuan GNU/Linux 4
Kernel Version 5.10.0-20-amd64

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I made a migration file containing both this first statement:
```
CREATE FUNCTION myFuncWorks(OUT rval int) RETURNS int
LANGUAGE sql
AS 'SELECT 1;';
```
and also this second one:
```
CREATE FUNCTION myFunc(OUT rval int) RETURNS int
LANGUAGE sql
BEGIN ATOMIC
  SELECT 1;
END;
```
I also tried pasting them into an interactive `psql` session.

###### What did you expect to see?

If I'm reading [the Postgres 14 manual](https://www.postgresql.org/docs/14/sql-createfunction.html) correctly, both statements should succeed when run from a migration file.

###### What did you see instead?

The first statement succeeds when in a migration file.
The second statement fails when in a migration file but succeeds when pasted into a `psql` interaction session.
The Error looks like this:
```
SQL State  : 42601
Error Code : 0
Message    : ERROR: syntax error at end of input
  Position: 86
Location   : /migrate/V101__examplefile.sql (/migrate/V101__examplefile.sql)
Line       : 6
Statement  : CREATE FUNCTION myFunc(OUT rval int) RETURNS int
LANGUAGE sql
BEGIN ATOMIC
  SELECT 1
```

_N.B._ I am aware this failing statement can also be expressed using the `RETURN expression` form of function body.  This example is reduced from a body with with multiple statements.

**Comment by JasonLuo-Redgate** [comment]
Hi @mackler , as a follow up of above discussion. The` BEGIN ATOMIC` support was just added, which will be included in the next release.
