### ISSUE TITLE
Flyway is using deprecated Oracle view ALL_SCHEDULER_CREDENTIALS 

### ISSUE THREAD

**Issue by lm-net** [flyway/flyway#3648]
While checking Oracle schema existing object types, Flyway is using deprecated data dictionary view ALL_SCHEDULER_CREDENTIALS. It is deprecated from version 12.1 as described here https://docs.oracle.com/database/121/REFRN/GUID-DCC268E4-14BB-48A6-9679-CEEAB1ADA1F1.htm#REFRN20580 

Best solution in my opinion is limit usage of ALL_SCHEDULER_CREDENTIALS for version 11gR2 and older and for newer versions use  view ALL_CREDENTIALS.

Problematic source code is located here
org.flywaydb.core.internal.database.oracle.OracleSchema.getObjectTypeNames

https://github.com/flyway/flyway/blob/08ff5b0c6ecf2a87e32e41d72904b7ec92a522de/flyway-core/src/main/java/org/flywaydb/core/internal/database/oracle/OracleSchema.java#L818

**Comment by Barry-RG** [comment]
Thank you for your research, will will look into this

**Comment by Barry-RG** [comment]
This has been put in our pipeline and will be resolved in our next release
