### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ankit31365** [flyway/flyway#3653]
flyway 9.16 teams
command line 
oracle 19.3 c 
Windows 11 citrix VDI
python 3.10

below is error 
./specdbCreateSchemas.sh
+ ./grantEmrAccessToOtherSchemas.pl specdb emrtiny -noPrompt
+ ./runFlyway.py specdb emrtiny repair --noPrompt
Traceback (most recent call last):
  File "C:\prod\g\g-admin\src\main\resources\dbsetup\bin\runFlyway.py", line 189, in <module>
    sys.exit(Util.runDbCommand(cmdList, dbContext.schemaPasswd, debug))
  File "C:\prod\g\g-admin\src\main\resources\dbsetup\lib\Util.py", line 65, in runDbCommand
    return subprocess.call(cmdList)
  File "C:\python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
++ exit_report FAILED
++ echo 'specdbMigrate.sh - FAILED'
specdbMigrate.sh - FAILED
++ echo

this setup is working fine in linux and mac , however i am trying to do in windows system

**Comment by Barry-RG** [comment]
Would you be able to give us a minimum reproduction for us to debug this issue? 
For example, there is no indication from your output what Flyway command is being run.

**Comment by Barry-RG** [comment]
Is there any update on my question?

**Comment by ankit31365** [comment]
how can i pass multiple sql file folder in windows platform through cmd terminal?

**Comment by Barry-RG** [comment]
the `locations` parameter accepts a list of folders.
See documentation [here](https://documentation.red-gate.com/fd/locations-184127514.html).

**Comment by ankit31365** [comment]
['flyway', '-enterprise', '-configFiles=../lib/flyway.conf', '-url=jdbc:oracle:thin:@localhost:1521/orcl', '-user=mukesh', '-password=mukesh', '-locations=filesystem:../sql/migration,filesystem:../sql/db-targeted/specdb/mukesh', 'repair'], are multiple location will work ??? in flyway 5.2.4 this command is working in mac and linux but not working in windows , i am passing this command through python script. please guide me
