### ISSUE TITLE
Updating from 9.15.2 to 9.16.x introduces breaking change

### ISSUE THREAD

**Issue by jeremy-brooks** [flyway/flyway#3657]
# Version 9.16.2
Community
Command-line
PostgreSQL 14.5
Linux

# What you did
I updated the version we used from 9.15.2 to 9.16.2, nothing else changed.

# What did you expect to see?
Database: jdbc:postgresql://################.cluster-############.rds.amazonaws.com:####/################ (PostgreSQL 14.5)
Successfully validated ## migrations (execution time 00:00.513s)
Current version of schema \"schema_name\": x.x.x
Schema \"schema_name\" is up to date. No migration necessary.

# What did you see instead?
991 | /home/sbx_user1051/.config/Redgate/feature_usage_data (No such file or directory)
992 | ERROR: Unable to write JSON to file: report.html.json (Read-only file system)

_NOTE: I am parsing the response and only logging out the failure message when the migration fails._

**Comment by jeremy-brooks** [comment]
Is there any update on this one?

**Comment by jeremy-brooks** [comment]
Oh that sounds very interesting, good spot!

Lets see what the devs come back with, I'm leaning on it being an unintentional introduction to keep things positive right now.
Or at least something we can turn off.

**Comment by dev-trilobyte** [comment]
Looking further into it there seems to be an env var `REDGATE_DISABLE_TELEMETRY` to disable (docs here https://documentation.red-gate.com/fd/redgate-disable-telemetry-191562045.html). This skips initialization of the telemetry plugin in the command line client and does not read/write some telemetry files. It was added with 9.16.0 too.

The problem with the write permission denied seems to be another commit with 9.16.2 where the cli client tries to write the migration report without further checks onto disk:
https://github.com/flyway/flyway/blob/8e3af28e9c99c3da2da484f6f7051d589ae716c2/flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java#L204-L208

Method call `HtmlUtils.toHtmlFile()` writing the file cannot be disabled it seems. Here a fix from RedGate is needed to either disable writing reports or do not exit with error on problems...

**Comment by jeremy-brooks** [comment]
Still no updates from the developers on this one?

**Comment by jeremy-brooks** [comment]
That's great, the latest version at time of writing 9.17.0 is working fine for cli community edition.
No need to set any new env vars either.
