### ISSUE TITLE
Flyway core update to 9.4.0 is not updating flyway jar version and it is still pointing to 7.7.3

### ISSUE THREAD

**Issue by kumarsenior5** [flyway/flyway#3663]
###### Which version and edition of Flyway are you using?

9.4.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven

###### Which database are you using? (Type & version)

Postgres 15.2

###### Which operating system are you using?

Unix

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I have upgraded flyway core version from 8.0.5 to 9.4.0

###### What did you expect to see?

I was expecting that flyway core jar after successful maven build should be updated to flyway core 9.4.0

###### What did you see instead?

I see that flyway core 7.7.3 is generated after maven build which is not right in case of 8.0.5 flyway core also in case of flyway core 9.4.0

**Comment by Barry-RG** [comment]
Can you please give us a minimum reproduction? It would be useful to better understand what this issue is?

**Comment by kumarsenior5** [comment]
Hi,

I have a project for r2dbc connect pooling where I have given below
dependency for postgressql, r2dbc, spring boot and flyway version:-

<postgresql.version>42.5.0</postgresql.version>
<r2dbc.postgres.version>0.8.13.RELEASE</r2dbc.postgres.version>
<springboot.version>2.5.12</springboot.version>
<flyway.version>9.4.0</flyway.version>

I have another project XYZ where I have added dependency for r2dbc
project and r2dbc postgres version as per below maven dependency.

<r2dbc.lib.version>0.0.2</r2dbc.lib.version>
<r2dbc.postgres.version>0.8.13.RELEASE</r2dbc.postgres.version>

When I am running XYZ project, I see flyway-core 7.7.3 jar in the
generated sources of XYZ project inside snapshot jar, although
expected jar version is

flyway core 7.7.3.jar

In the application console I see this log message:-


"message":"Flyway Community Edition 7.7.3 by Redgate" }

 (PostgreSQL 14.3)" }

 "message":"Flyway upgrade recommended:
***@***.***
14.3 is newer than this version of Flyway and support has not been
tested. The latest supported version of
***@***.***
is 13." }

Can you help me with this?

Issue:- Why I am getting a message for upgrade although I am already at 15.2.

Why Flyway version is 7.7.3 although it should be 9.4.0


Thanks

Prashant

**Comment by kumarsenior5** [comment]
Hi, 

I am waiting for support on this. Please respond.
