### ISSUE TITLE
is there a version 9.17.0 of the Flyway Gradle plugin?

### ISSUE THREAD

**Issue by donalmurtagh** [flyway/flyway#3666]
###### Which version and edition of Flyway are you using?

Community edition, v. 9.17.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I am using the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using? (Type & version)

Postgres 11

###### Which operating system are you using?

macOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Upgraded from 9.16.3 to 9.17.0

###### What did you expect to see?

Version 9.17.0 of Gradle plugin should be installed. Further details are available in [this stackoverflow post](https://stackoverflow.com/questions/76155058/is-there-a-version-9-17-0-of-the-flyway-gradle-plugin).

###### What did you see instead?

Version 9.17.0 of Gradle plugin failed to download. Further details are available in [this stackoverflow post](https://stackoverflow.com/questions/76155058/is-there-a-version-9-17-0-of-the-flyway-gradle-plugin).

**Comment by Barry-RG** [comment]
Thanks for bringing this up. We have repushed 9.17.0 and is now appearing on the Gradle plugin repo.

**Comment by donalmurtagh** [comment]
It works now, thanks for your prompt response
