### ISSUE TITLE
AWS SDK dependency installation

### ISSUE THREAD

**Issue by ebonharme** [flyway/flyway#3668]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 9.17.0 using flyway/flyway:9-alpine

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

It is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command line

###### Which database are you using? (Type & version)

SnowFlake 7.15

###### Which operating system are you using?

Mac OS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

FLYWAY_LOCATIONS=s3:mybucket/myfolder flyway migrate

###### What did you expect to see?

Successful migration

###### What did you see instead?

SEVERE: Can't read location s3:mybucket/subfolder; AWS SDK not found

###### Additional notes

I am aware that the documentation reads "To use AWS S3, the [AWS SDK v2](https://mvnrepository.com/artifact/software.amazon.awssdk/services) and dependencies must be included, and [configured](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) for your S3 account." but the AWS documentation related to AWs SDK v2 is geared towards fresh maven projects, whereas I'm just interested in using the CLI tool.  I've tried downloading various jars using wget and saving them in /flyway/lib/ which appears to be in the CLASSPATH but to no avail.

Can you provide more detailed instructions on how to install all the necessary dependencies?

**Comment by JasonLuo-Redgate** [comment]
Hi @ebonharme , would you try whether this would help https://documentation.red-gate.com/fd/adding-to-the-classpath-184127216.html ?

**Comment by elijahyoon** [comment]
hey @ebonharme, just curious, were you able to get this to work eventually?
