### ISSUE TITLE
Unsupported Database: MariaDB 10.11

### ISSUE THREAD

**Issue by xGregor** [flyway/flyway#3683]
###### Which version and edition of Flyway are you using?

9.19.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

no

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API & Gradle plugin

###### Which database are you using? (Type & version)

MariaDB 10.11 with Galera Cluster

###### Which operating system are you using?

Ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Started my Spring Boot Application

###### What did you expect to see?

Support MariaDB 10.11

###### What did you see instead?

`FlywayException: Unsupported Database: MariaDB 10.11`
MariaDB 10.11 is published since Feb 2023.

**Comment by JasonLuo-Redgate** [comment]
Hi @xGregor , MariaDB latest support for now is 10.10. 
https://documentation.red-gate.com/fd/mariadb-184127600.html

**Comment by tjs145** [comment]
This should just show up as a warning. When I run against MariaDB 10.11 I get:
```
...
Database: jdbc:mariadb://localhost/test (MariaDB 10.11)
WARNING: Flyway upgrade recommended: MariaDB 10.11 is newer than this version of Flyway and support has not been tested. The latest supported version of MariaDB is 10.10.
...
```

Not sure why it would be triggering the exception at that point

**Comment by xGregor** [comment]
Thanks for you invastigation! The missing `flyway-mysql` dependency fixed my issue.

**Comment by alculete** [comment]
Worked for me also. Thank you @tjs145
