### ISSUE TITLE
Flyway cannot find migration scripts

### ISSUE THREAD

**Issue by MatthisVanHoecke2** [flyway/flyway#3688]
###### Which version and edition of Flyway are you using?
9.8.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
SQLite

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I tried packaging the jar file with the flyway migrations

###### What did you expect to see?
A log of Flyway executing 2 migration files.

###### What did you see instead?
Flyway executing 0 migration files.

![FlywayError1](https://github.com/flyway/flyway/assets/101056688/d19fe1c9-5fac-4d12-a2f9-f751921729b2)
![FlywayError2](https://github.com/flyway/flyway/assets/101056688/1db43fad-09a5-406e-b708-d46798ca03e2)
![image](https://github.com/flyway/flyway/assets/101056688/95ebbbef-71a6-4f82-9eba-86216505e104)
![image](https://github.com/flyway/flyway/assets/101056688/9ffd0441-aaea-440c-9161-5fdb264294ee)

**Comment by JasonLuo-Redgate** [comment]
Hi @MatthisVanHoecke2 , I see question marks marked at the `db/migration` folders, can you confirm the location of the folder is actually OK?

**Comment by ResurrectAjax** [comment]
When I add classpath:db/migration to the locations in the java code, it doesn't give me an error or anything like that when I run it. The scripts just don't get recognized. From what I understood from the flyway documentation, when using a maven project, I am supposed to put the db/migration folder inside the resource folder. Is there a better way to check whether the location is ok?

**Comment by Izocel** [comment]
From the documentation im not even sure the java API will check `.sql` files have you tried running it with the maven cmd ?
On my side the maven plugin works but i'm not able to initiate a connecter wit hthe Java API.

repos:
https://github.com/Izocel/Minecraft-Whitelist-Discord-Bot

**Comment by JasonLuo-Redgate** [comment]
Hi @MatthisVanHoecke2 , did you run Maven clear/install for your project?
I locally verified that, one you run Maven clear/install, any migration files will be automatically copied from `src\main\resources\db\migration`
to
`target\classes\db\migration`

**Comment by ResurrectAjax** [comment]
I run the clean install command when generating the sources, I checked the generated .jar file as well and it has all the required files

**Comment by ResurrectAjax** [comment]
> 

I'll try this and get back to you if it works or not.
