### ISSUE TITLE
A way of switching off the generation of report.html and report.json in Flyway Commandline

### ISSUE THREAD

**Issue by Phil-Factor** [flyway/flyway#3699]
###### Which version and edition of Flyway are you using?
9.19.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
RDBMS? SQL Server

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Flyway Info  -outputType=json 

###### What did you expect to see?
Just my nice JSON Output

###### What did you see instead? (as well)
Report.HTML and Report.json

I'm getting a report.html and report .json. I really don't want them. They take a lot of space (The HTML one takes 4.5 Mb and if you get an error the report.json can get huge too.  Is there a way of using config to turn them both off as they are a nuicance, and make info even longer to execute.  If not, please can you put something in there to allow us to switch it off.

**Comment by JasonLuo-Redgate** [comment]
Hi @Phil-Factor , we already had a similar ticket https://github.com/flyway/flyway/issues/3685 here, so probably may I close this one as duplication?

**Comment by Phil-Factor** [comment]
Yes, that is fine as long as the issue doesn't get forgotten
