### ISSUE TITLE
Flyway version 9 having issue to connect to Mysql SSL enabled User

### ISSUE THREAD

**Issue by Abhishek010397** [flyway/flyway#3708]
###### Which version and edition of Flyway are you using?
Flyway version 9.19.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

All flyway version above 8.0 throwing the same issue

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command-line

###### Which database are you using? (Type & version)

Amazon Aurora 

###### Which operating system are you using?
Mac and Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Tried executing flyway info on the Amazon Aurora Database which has mysql user with tis_option set as SSL.

flyway info -url="jdbc:mysql://amazon-rds-url/db_name?useSSL=true&requireSSL=true" -user=Abhishek -password=xxxxxxx

Error:-

SQL State  : 08000

Error Code : -1

Message    : Could not connect to address=(host=dbs-aurora-msf-gpls-perfizdb-dm-tf-test.cluster-couctixqsm8e.ap-southeast-1.rds.amazonaws.com)(port=3306)(type=master) : Could not connect to dbs-aurora-msf-gpls-perfizdb-dm-tf-test.cluster-couctixqsm8e.ap-southeast-1.rds.amazonaws.com:3306 : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

When removing the SSL flag:-

flyway info -url="jdbc:mysql://amazon-rds-url/db_name" -user=Abhishek -password=xxxxxxx
Error:-

SQL State  : 28000

Error Code : 1045

Message    : Could not connect to address=(host=dbs-aurora-msf-gpls-perfizdb-dm-tf-test.cluster-couctixqsm8e.ap-southeast-1.rds.amazonaws.com)(port=3306)(type=master) : (conn=2123) Access denied for user 'Abhishek'@'10.130.5.137' (using password: YES)

Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'

Also to bring into the conversation when MYSQL user's don't have the tis_option set to SSL flyway version 9 works smoothly.

Can someone help me out with the solution of the above issue, Thanks.

**Comment by JasonLuo-Redgate** [comment]
HI @Abhishek010397 , for SSL support, you might need to refer to guidance at https://documentation.red-gate.com/fd/ssl-support-184127478.html
