### ISSUE TITLE
getCallbacks on configuration does not retrieve SQL callbacks

### ISSUE THREAD

**Issue by SBylemans** [flyway/flyway#3719]
###### Which version and edition of Flyway are you using?
8.5.13

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Postgres 14.1

###### Which operating system are you using?
Mac OS for application, docker container for DB

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I'm trying to access the callbacks.

Only way I see how is through
```java
 Flyway flyway = Flyway.configure()
        .dataSource(datasource(databaseMigrationManagerProperties, product))
        .locations(databaseMigrationManagerProperties.locations(product).toArray(Location[]::new))
        .createSchemas(true)
        .table(flywayProperties.getTable())
        .schemas(trimmedSchemas)
        .defaultSchema(databaseMigrationManagerProperties.getDefaultSchema(product))
        .load();
flyway.getConfiguration().getCallbacks(); // is empty array
```

###### What did you expect to see?
I would expect this to resolve the callbacks present in the locations, but it only does this at runtime of the migration itself (when calling `.migrate()`)

Another possibility is to include the callbacks executed in MigrationInfo.

###### What did you see instead?
An empty array.

**Comment by JasonLuo-Redgate** [comment]
Can you add a `.callbacks()` call before the` .locations()` call and re-try?

**Comment by SBylemans** [comment]
@JasonLuo-Redgate The `.callbacks()` method expects arguments and as I can see, it will scan for classes that implement the Callback class.

However, I want to see the callback scripts that I defined, as SQL scripts.

**Comment by JasonLuo-Redgate** [comment]
Hi @SBylemans , sorry for the confusion, I mean if you add a `.callbacks()` call in your code, you might get the expected result in `getCallbacks() `rather than an empty array.

**Comment by SBylemans** [comment]
@JasonLuo-Redgate , yeah, so I tried that and still nothing. 

As I said, I went to see in the code, and found that this method calls for scanning of classes that implement the `Callback` class. But doesn't scan for possible SQL scripts...

**Comment by JasonLuo-Redgate** [comment]
Hi @SBylemans ,
Sorry for the confusion. The `getCallbacks()` method call returns Java-based Callbacks (https://documentation.red-gate.com/fd/api-hooks-184127635.html#callsbacks) after a proper `.callbacks()` call which scans for classes that implement the Callback `interface`.

This method call doesn't work on SQL scripts.
