### ISSUE TITLE
Update Check waits for timeout if it cannot connect to maven

### ISSUE THREAD

**Issue by odin568** [flyway/flyway#3720]
###### Which version and edition of Flyway are you using?

Flyway up to 9.20.0 works fine. Issue was introduced with 9.20.1 and following.

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Same issue still with latest version 9.21.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

CLI

###### Which database are you using? (Type & version)

Oracle 19.1

###### Which operating system are you using?

Ubuntu Jammy (Docker)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Regardless if I run `flyway info`, `flyway clean`, `flyway migrate`, ... with 9.20.1 it takes ~3min until the first logs appear. Then it works fine but I don't know what it does within those 3mins.

Until 9.20.0 those jobs succeed within seconds.

###### What did you expect to see?

I expect a runtime of some seconds.

###### What did you see instead?

With 9.20.1, job takes almost 3minutes until it prints first logs

I reported this issue already in the past with #3229 and it was fixed with https://github.com/flyway/flyway/commit/428011abb38805b90dc04af2ac9ac4381f2081d2 .
Seems that following change removed that check again:  
https://github.com/flyway/flyway/commit/9abeef6dfceb7de626175a2e9584cacd9fbd723f#diff-d00b1316af97253c8b5e6318c8c503cea3d134b06d14a5d4c37548b968183367

**Comment by Barry-RG** [comment]
Thank you for rising this. This will be addressed in the next release.

**Comment by odin568** [comment]
Hi, 
Any news/plan for this?
Thanks!

**Comment by JasonLuo-Redgate** [comment]
Hi @odin568 , is this still an issue with the latest version of Flyway ?

**Comment by odin568** [comment]
Okay, I watched the release notes but did not find anything. Was then already introduced and I can confirm it works now (again). Thanks a lot!
