### ISSUE TITLE
如何在nacos配置加载完成后，插入节点执行代码

### ISSUE THREAD

**Issue by zengshuimu** [flyway/flyway#3721]
原本我的逻辑是在数据库连接前自动初始数据库（创建库、创建表），
加入nacos后，执行顺序发现了改变。
在Application的@PostConstruct的实例化执行顺序变在mybatisplus之后了，这个如何解决呢，在nacos配置加载完成后，插入节点第一时间执行我的执行代码，或者等效的方法，求指点

**Comment by JasonLuo-Redgate** [comment]
Hi @zengshuimu , your question might not be related to Flyway. 
I would suggest raise this question to the right product.
