### ISSUE TITLE
Flyway gives `No database found to handle jdbc:postgresql://localhost/access_point` when deployed as Jar

### ISSUE THREAD

**Issue by boroicamarius** [flyway/flyway#3722]
###### Which version and edition of Flyway are you using?
flyway-core:9.21.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Running SBT `assembly` to create the final jar file, with SBT `run` the project works fine

###### Which database are you using? (Type & version)
PostgreSQL 15.3

###### Which operating system are you using?
Windows 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Trying to run the tutorial on my machine, seems that running sbt run to run my main.scala file all works fine but when i run sbt assembly and then I run the jar, the error `No database found to handle jdbc:postgresql://localhost/access_point` appears

###### What did you expect to see?
I expected it to run normally and give another error related to the permissions of the user it is trying to login, but I didnt expect for it to not even make it possible to connect to the database

###### What did you see instead?
this:

```cmd
❯ java -jar scala-instance.jar
DRIVER: org.postgresql.Driver
PG_URL: jdbc:postgresql://localhost/access_point
PG_USERNAME: scala
PG_PASSWORD: passwordforscala
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgresql://localhost/access_point
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1075)
        at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:631)
        at com.scaladocker.Main$.main(Main.scala:43)
        at com.scaladocker.Main.main(Main.scala)
```

###### Repository:
https://github.com/boroicamarius/scala-instance

**Comment by IRus** [comment]
Apparently, they changed the way flyway is distributed. 
If you want Postgres support for example, add this dependency:

```kotlin
dependencies {
    implementation("org.flywaydb:flyway-database-postgresql:10.4.1")
}
```

Databases supported in flyway-core:

```
H2DatabaseType
SQLiteDatabaseType
TestContainersDatabaseType
```

**Comment by 9Rain** [comment]
> Apparently, they changed the way flyway is distributed. If you want Postgres support for example, add this dependency:
> 
> ```kotlin
> dependencies {
>     implementation("org.flywaydb:flyway-database-postgresql:10.4.1")
> }
> ```
> 
> Databases supported in flyway-core:
> 
> ```
> H2DatabaseType
> SQLiteDatabaseType
> TestContainersDatabaseType
> ```

Many thanks, buddy! You've helped a lot!

**Comment by dilunika** [comment]
Thanks @IRus  Following configuration helped me to solve the issue. (if you are using gradle plugin)

`buildscript {
    dependencies {
        classpath("org.postgresql:postgresql:42.7.1")
        classpath("org.flywaydb:flyway-database-postgresql:10.4.1")
    }
}

plugins {
    kotlin("jvm") version "1.9.21"
    id("org.flywaydb.flyway") version "10.0.0"
}`

**Comment by epomatti** [comment]
"No database found" does not immediately explain what's going on.

Team got this issue and thought it was network related.

No only did this break existing behavior but also does not convey any meaningful information.

**Comment by abdullatheeftk-gulf** [comment]
> Thanks @IRus Following configuration helped me to solve the issue. (if you are using gradle plugin)
> 
> ```
> buildscript {
>     dependencies {
>         classpath("org.postgresql:postgresql:42.7.1")
>         classpath("org.flywaydb:flyway-database-postgresql:10.4.1")
>     }
> }
> 
> plugins {
>     kotlin("jvm") version "1.9.21"
>     id("org.flywaydb.flyway") version "10.0.0"
> }
> ```

Thank you. This helped me

**Comment by Sedose** [comment]
> "No database found" does not immediately explain what's going on.
> 
> Team got this issue and thought it was network related.
> 
> Not only did this break existing behavior but also does not convey any meaningful information.

Fair point

**Comment by olaf-otto** [comment]
For completeness, if you are using SBT, you need to add the respective plugin dependencies, including the DB driver, to the _plugins.sbt_, not just the build.sbt!

```
addSbtPlugin("com.github.sbt" % "flyway-sbt" % "11.11.0")

/* These dependencies are required in plugin scope to generate code during plugin execution */
libraryDependencies ++= Seq(
  "org.flywaydb" % "flyway-core" % "11.20.2",
  "org.flywaydb" % "flyway-database-postgresql" % "11.20.2",
  "org.postgresql" % "postgresql" % "42.7.4"
)
```
