### ISSUE TITLE
Docker image fails PrismaScan due to jackson 2.14.0 CVE

### ISSUE THREAD

**Issue by iamniche-too** [flyway/flyway#3723]
###### Which version and edition of Flyway are you using?
9.21.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)
postgres

###### Which operating system are you using?
linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

we build flyway docker image and run PrismaScan to check for any vulnerabilities

###### What did you expect to see?
flyway passes PrismaScan

###### What did you see instead?
PrismaScan fails due to critical vulnerability (CVE)
com.fasterxml.jackson.core_jackson-core package versions before 2.15.0 are vulnerable to Denial of Service (DoS)

jackson version 2.14.0 fails PrismaScan with a critical vulnerability

PRISMA-2023-0067 | New | 7.5 | high | com.fasterxml.jackson.core_jackson-core | 2.11.1 | fixed in 2.15.0

**Comment by WilliamL-RG** [comment]
Thank you for bring this up. This will be fixed in the next release.

**Comment by asvitkine** [comment]
It seems that as of this change, flyway is shipping with a version of jackon compiled with Java 19.
So this causes failures for projects that are on earlier Java versions.

Is it this intended?

For reference, this is blocking us from moving from 9.21.1.

**Comment by asvitkine** [comment]
> It seems that as of this change, flyway is shipping with a version of jackon compiled with Java 19. So this causes failures for projects that are on earlier Java versions.
> 
> Is it this intended?
> 
> For reference, this is blocking us from moving from 9.21.1. See my notes on [triplea-game/triplea#12032](https://github.com/triplea-game/triplea/pull/12032)

Looks like we just needed to update gradle and that resolved the issue.
