### ISSUE TITLE
How do I use default/implicit credentials with the jdbc Big Query driver?

### ISSUE THREAD

**Issue by red8888** [flyway/flyway#3725]
Currently it looks like I must generate a json key for a service account: https://documentation.red-gate.com/fd/google-bigquery-186679473.html

I run flyway containerized in environments that have creds injected with workload id and also locally on users machines that use default app creds.

Does the JDBC driver support not specifying creds and having it just use the default credential loading mechanism the GCP SDK uses? Ie it just finds the creds based on the environment (workload id, GCE instance with service account attached, the GOOGLE_APPLICATION_CREDENTIALS environment variable, etc)

 I can't find docs for the driver with examples of this if its possible.

I don't generate service account keys I use workload id which does not require any static keys

**Comment by matthijsdewit111** [comment]
@red8888 since this question is almost a year old, did you find a solution or workaround?

**Comment by matthijsdewit111** [comment]
Just wanted to say that I found that the Simba driver comes with a PDF containing documentation (you can download it here https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers), one of them is the option OAuthType which has 4 options, option 4 allows you to authenticate using workload or workforce identity federation.
