### ISSUE TITLE
SLF4J Autodetection doesn't work with SLF4J 2.0

### ISSUE THREAD

**Issue by hho** [flyway/flyway#3730]
###### Which version and edition of Flyway are you using?

9.21.0 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

PostgreSQL 15.3

###### Which operating system are you using?

Kubuntu 22.04

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I ran Flyway in an integration test project with logback-classic 1.4.8 and slf4j-api 2.0.7 on the classpath.

###### What did you expect to see?

Flyway logging via SLF4J

###### What did you see instead?

Flyway logging to stderr

#### Cause

I debugged through the issue and found that the error seems to be [here](https://github.com/flyway/flyway/blame/84b4dfbf03156561d632164eb3d77c2ed2154380/flyway-core/src/main/java/org/flywaydb/core/internal/util/FeatureDetector.java#L64-L67) – while the detection of the newer SLF4J version works fine (L.63), the result is afterwards set back to `false`, because the new implementation isn't returned by the `ServiceLoader` mechanism (empty stream -> `allMatch` is trivially true -> slf4j is marked as not available).

As Flyway uses the old SLF4J 1.7 API, and the check introduced in 9.16.2 only seems to be to exclude the slf4j-nop binding added to flyway-commandline, I'd suggest doing the check only for the old API as well.

**Comment by Barry-RG** [comment]
Thank you for the information @hho. I will bring this up with our team

**Comment by JasonLuo-Redgate** [comment]
Hi @Barry-RG , we already have a ticket for known issue here https://github.com/red-gate/flyway-main/issues/2712
