### ISSUE TITLE
Database migration vs Schema Evolution

### ISSUE THREAD

**Issue by sreejeshraj** [flyway/flyway#3742]
This is not technical, but probably related to marketing. I know there are many Database migration tools out there. When I talk to people, they get confused between Data migration (moving data from one DB to another) and Database Migration (Evolving the DB Schema along with the project).

If the tools like Flyway have marketed themselves as "Database Schema Evolution Tool", it makes probably more sense than just saying that it is a "Database Migration Tool".

I actually wanted to send this suggestion to Flyway team, but their "Contact Us" page is not working. It is just a static page with no functionality I think.

**Comment by Phil-Factor** [comment]
Thanks for making that helpful point
