### ISSUE TITLE
Postgres 16.0

### ISSUE THREAD

**Issue by yashh** [flyway/flyway#3743]
###### Which version and edition of Flyway are you using?
"org.flywaydb:flyway-core:9.22.1"

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes this is the latest version in the maven repository

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
val flyway = Flyway.configure().dataSource(pool).load()
flyway.info()
flyway.migrate()

###### Which database are you using? (Type & version)
Postgres 16.0

###### Which operating system are you using?
I am using a mac but postgres is hosted on https://neon.tech

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
trying to run my migrations using flyway.migrate.

###### What did you expect to see?
The migrations runs fine on postgres 15.4

###### What did you see instead?

```
INFO: Schema history table "public"."flyway_schema_history" does not exist yet
Exception in thread "main" org.flywaydb.core.internal.exception.FlywaySqlException: Unable to turn on auto-commit for the connection
------------------------------------------------
SQL State  : 26000
Error Code : 0
Message    : ERROR: prepared statement "S_1" does not exist

        at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:43)

```

**Update:**
Actually just realized I am pointed to the pgbouncer pooler. Running migrate against the database works. So we cant run migrations against the pooler?

**Comment by JasonLuo-Redgate** [comment]
Hi @yashh , may I know more about what do you mean by "run migrations against the pooler"?

**Comment by yashh** [comment]
@JasonLuo-Redgate  I meant my database url is pointed to the postgres connection pooler rather than pointing to the database directly.  

https://github.com/blitz-js/legacy-framework/issues/107

Looks like migrations have to be run directly on the database.

**Comment by nafg** [comment]
Well I'm not using the connection pool URL and it's not working for me. It says explicitly

```
jvm[ERROR] org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.0
jvm[ERROR]      at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105)
jvm[ERROR]      at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1089)
jvm[ERROR]      at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:590)
jvm[ERROR]      at maasertracker.server.PlaidHttp4sServer$.$anonfun$run$1(PlaidHttp4sServer.scala:135)
jvm[ERROR]      at apply @ maasertracker.server.PlaidHttp4sServer$.run(PlaidHttp4sServer.scala:141)
jvm[ERROR]      at >> @ maasertracker.server.PlaidHttp4sServer$.run(PlaidHttp4sServer.scala:143)
jvm[ERROR]      at main$ @ maasertracker.server.PlaidHttp4sServer$.main(PlaidHttp4sServer.scala:29)
jvm[ERROR]      at main$ @ maasertracker.server.PlaidHttp4sServer$.main(PlaidHttp4sServer.scala:29)
jvm[ERROR]      at main$ @ maasertracker.server.PlaidHttp4sServer$.main(PlaidHttp4sServer.scala:29)
```

and [Flyway docs themselves](https://documentation.red-gate.com/fd/postgresql-184127604.html) say

> Verified Versions: 9.0, 15

Although it's true that only says "verified," not "supported." But then it says

> For information regarding the supported version and support levels available, please see [Supported Databases for Flyway](https://documentation.red-gate.com/flyway/learn-more-about-flyway/system-requirements/supported-databases-for-flyway)

Except that link returns a 404.

**Comment by nafg** [comment]
I am also using Neon, and I'm using the server name `ep-calm-heart-XXXXXXXXX.us-east-1.aws.neon.tech`.

I found the page the docs should be linking to: https://documentation.red-gate.com/fd/supported-databases-and-versions-143754067.html

It also only has up to 15.

**Comment by nafg** [comment]
So I recreated my Neon project with postgres 15 and now I get

```
jvm[ERROR] org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 15.4
jvm[ERROR]      at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105)
jvm[ERROR]      at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1089)
jvm[ERROR]      at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:590)
jvm[ERROR]      at maasertracker.server.PlaidHttp4sServer$.$anonfun$run$1(PlaidHttp4sServer.scala:135)
jvm[ERROR]      at apply @ maasertracker.server.PlaidHttp4sServer$.run(PlaidHttp4sServer.scala:141)
jvm[ERROR]      at >> @ maasertracker.server.PlaidHttp4sServer$.run(PlaidHttp4sServer.scala:143)
jvm[ERROR]      at main$ @ maasertracker.server.PlaidHttp4sServer$.main(PlaidHttp4sServer.scala:29)
jvm[ERROR]      at main$ @ maasertracker.server.PlaidHttp4sServer$.main(PlaidHttp4sServer.scala:29)
jvm[ERROR]      at main$ @ maasertracker.server.PlaidHttp4sServer$.main(PlaidHttp4sServer.scala:29)
```

I have my flyway version set to 10.0.1.

**Comment by nafg** [comment]
14 doesn't work either. Something else weird is going on.

**Comment by yashh** [comment]
Same here. I downgraded to the old flyway version which is working

**Comment by nafg** [comment]
Problem solved. The problem that remains is the discoverability of the documentation.

I had seen, and forgotten, that in the hard-to-find release notes (please add them to GitHub releases) at https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html, it says

> Modularized database support in Flyway to allow greater flexibility. This includes; DB2, Derby, HSQLDB, Informix, PostgreSQL, CockroachDB, Redshift, SAP HANA, Snowflake and Sybase ASE. See Database Support page for your database for module dependency. If you are including Flyway in your project, either as a dependency or via the maven and gradle plugins please include the respective database module in your project configuration.

Which means I had to update the dependency artifact ID as specified on https://documentation.red-gate.com/fd/postgresql-184127604.html from `flyway-core` to `flyway-database-postgresql`.

**Comment by nafg** [comment]
Another thing that could be improved, is that the error message is confusing. If support for the database is not on the classpath altogether, the error shouldn't mention the version number.

**Comment by yashh** [comment]
Thank you @nafg. It worked. Still seeing the old warning though.

```
2023-11-19 17:30:58.681 [main] WARN  o.f.c.i.database.base.Database - Flyway upgrade recommended: PostgreSQL 16.0 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
```

**Comment by nafg** [comment]
Then IMO the issue should be reopened
