### ISSUE TITLE
Add DB2 drivers to command line package

### ISSUE THREAD

**Issue by davidkarlsen** [flyway/flyway#3749]
It would be good if you could add DB2 drivers to the default set of pre-packaged drivers.
https://repo1.maven.org/maven2/com/ibm/db2/jcc/11.5.8.0/

###### Which version and edition of Flyway are you using?
latest, community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)

DB2 11.5.8.0

###### Which operating system are you using?
N/A

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Use the docker image which is missing drivers, see https://github.com/flyway/flyway-docker/issues/124

###### What did you expect to see?
DB2-drivers pre-packaged with cmdline.

###### What did you see instead?
missing drivers

**Comment by davidkarlsen** [comment]
?

**Comment by JasonLuo-Redgate** [comment]
Hi @davidkarlsen , many thanks for the PR. I will raise this requirement to the team.

**Comment by JasonLuo-Redgate** [comment]
Hi @davidkarlsen , we won't be able to do that due to the driver is under `International Program License Agreement (IPLA)`.
