### ISSUE TITLE
Password starting with '$' cannot be set using dataSource() method

### ISSUE THREAD

**Issue by honzabazant** [flyway/flyway#3751]
###### Which version and edition of Flyway are you using?
9.22.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Postgres 12

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We changed password of one of our database schemas and the password (generated by a random string generator) now starts with `$`.
We are configuring connection parameters using `dataSource()` method:
```
Flyway
  .configure()
  // other non-important stuff
  .dataSource("url", "username", "password")
  .load()
```

Password starting with `$` causes "Unknown resolver" exception to be thrown from `PropertyResolverContextImpl.resolveValue`. I noticed that the `$` can be escaped by another `$` to skip that resolving.
So in case the password starts with `$`, I prepend it with another `$` before passing it to Flyway configuration.

But this does not help, because the call to `flyway.migrate()` throws `FlywaySqlException: Unable to obtain connection from database` because of `FATAL: password authentication failed for user`.

I looked into the code and found the following:
- `FluentConfiguration.dataSource` calls `ClassicConfiguration.setDataSource` and passes the password as-is
- `ClassicConfiguration.setDataSource` does this:
  - creates an instance of `DriverDataSource` with the password it receives, and stores this instance into `dataSource` field
  - calls `getCurrentUnresolvedEnvironment().setPassword(password)`
- when `Flyway.load()` is finally called, it calls `ClassicConfiguration.getCurrentResolvedEnvironment` which then does the variable resolving.

So the problem is that when the password starting with unescaped `$` is used, resolving is attempted and fails. When the starting `$` is escaped, resolving is skipped, but the escaping is not removed when storing the password in `ClassicConfiguration.dataSource` field and authentication fails when trying to establish the database connection.

However there is a workaround which consists of using `FluentConfiguration.configuration()`:
```
Flyway
  .configure()
  .configuration(
    Map(
      "flyway.url" -> "url",
      "flyway.user" -> "username",
      "flyway.password" -> "password"
    )
  )
  .load()
```

This way, `ClassicConfiguration.configure(Map<String, String> props)` is called and here is the following:
```
if (StringUtils.hasText(getCurrentResolvedEnvironment().getUrl()) && (dataSource == null || StringUtils.hasText(urlProp) || StringUtils.hasText(driverProp) || StringUtils.hasText(userProp) || StringUtils.hasText(passwordProp))) {
    Map<String, String> jdbcPropertiesFromProps = getPropertiesUnderNamespace(props, getPlaceholders(), ConfigUtils.JDBC_PROPERTIES_PREFIX);
    setDataSource(new DriverDataSource(classLoader, getCurrentResolvedEnvironment().getDriver(), getCurrentResolvedEnvironment().getUrl(), getCurrentResolvedEnvironment().getUser(), getCurrentResolvedEnvironment().getPassword(), this, jdbcPropertiesFromProps));
}
```

so the password passed into `ClassicConfiguration.dataSource` is un-escaped first and everything works.

**Comment by steers** [comment]
To note, version 9.8 was the last release that still supports passwords beginning with `$` but obviously there are drawbacks to being locked down to an old version just to avoid this behaviour https://github.com/flyway/flyway/issues/3596

**Comment by JasonLuo-Redgate** [comment]
Hi @steers @honzabazant , many thanks for raising this issue. Escaping `$` by `$$` will be included in the next major release.
