### ISSUE TITLE
Flyway 6.0.0 Gives Unsupported Database: H2

### ISSUE THREAD

**Issue by sanketh-shetty-incontact** [flyway/flyway#3761]
###### Which version and edition of Flyway are you using?

6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Not checked

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
h2

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We upgraded from Flyway 5.2.4 to Flyway 6.0.0

###### What did you expect to see?
Migration should have Worked

###### What did you see instead?

 Got error Unsupported Database: H2

**Comment by JasonLuo-Redgate** [comment]
Hi @sanketh-shetty-incontact , could you post the error messages to give us more clues?
