### ISSUE TITLE
Single-line comment without space breaks migration after 7.7.0 version

### ISSUE THREAD

**Issue by Tsyklop** [flyway/flyway#3766]
###### Which version and edition of Flyway are you using?
7.6.0. Free

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
From 7.7.0 to 9.22.3 bug reproduces. 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Mysql 8

###### Which operating system are you using?
Windows 10, Ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I have old migrations. And single line comment: `--COMMENT`. Before 7.7.0 version all fine, but after 7.7.0 I got exception:

```
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V118__migration.sql failed
-----------------------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--COMMENT
``` 
Why?
###### What did you expect to see?
Successfull migration.

###### What did you see instead?
Exception.

**Comment by tjs145** [comment]
Could you provide some minimal SQL code to reproduce the issue

**Comment by Phil-Factor** [comment]
In MySQL and MariaDB, a single-line comment is indicated by '--' followed by a space and then the comment text. This behavior is specific to these database systems and is not part of the SQL standard. If you use it in a comment it will cause an error. 

In standard SQL, single-line comments are represented by '--' followed by the comment text without requiring  a space after the second '-'. This standard syntax is more widely used in other database systems like PostgreSQL, Oracle, and SQL Server.

The fault is surely in MySQL and MariaDB, not Flyway

**Comment by JasonLuo-Redgate** [comment]
HI @Tsyklop , I locally verified both `--COMMENT` and `-- COMMENT` but I can't reproduce that issue, could you share your sql script?

**Comment by JasonLuo-Redgate** [comment]
Hi @Tsyklop , I locally tested the exact sql script you posted, it's working fine. No parsing exception.  Could you double confirm the script?

**Comment by ryanrupp** [comment]
Stumbled upon this while hitting something similar. Likely this is due to the MySQL JDBC driver being updated (and not an issue with Flyway itself), apparently the JDBC driver validates this instead of just sending it to the DB? And in MySQL backend 5.7.x at least the DB would allow comments like this despite the documentation saying it doesn't, not sure about 8.x. Sort of confusing that the driver is validating this instead of letting the DB do this but see [here](https://bugs.mysql.com/bug.php?id=71929)

> Added the following entry to the Connector/J 8.0.30 changelog: 
> 
> "Contrary to the the MySQL requirement for comments, Connector/J did not require a whitespace (or a control character such as a newline) after "--" to mark the         beginning of a comment within a SQL statement. This fix aligns Connector/J with the MySQL requirement."
