### ISSUE TITLE
Flyway version check fails.

### ISSUE THREAD

**Issue by DxsSucuk** [flyway/flyway#3769]
###### Which version and edition of Flyway are you using?
Community 9.22.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
MariaDB 1.0.11

###### Which operating system are you using?
Debian 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run Migration via Java API

###### What did you expect to see?
Successful migration

###### What did you see instead?
Unsupported  Database error

**Comment by JasonLuo-Redgate** [comment]
Hi @DxsSucuk , could you provide detailed info about the error message you encountered and the operation you ran?

**Comment by DxsSucuk** [comment]
Sure!
The Issue is quite weird, since I adding the library to another project that I use as library in my main project. It happends sometimes that it does not work on my main application but secondary, which uses springboot.

I am running both of them on Debain 11 with Java 17.
When running the Springboot Application, it works fine. But when trying to run it within the normal Java application this error occures?

Sadly its not only on my machine, as of report from users that use the open source project it also happends to them on Pterodactyl?

**Comment by DxsSucuk** [comment]
The Project I am talking about is here:

Normal Application, where it fails -> https://github.com/Ree6-Applications/Ree6
Springboot Application, where it works? -> https://github.com/Ree6-Applications/Webinterface

**Comment by DxsSucuk** [comment]
Anything new @JasonLuo-Redgate ?

**Comment by tjs145** [comment]
Have you included a dependency on the `flyway-mysql` module?

**Comment by DxsSucuk** [comment]
> Have you included a dependency on the `flyway-mysql` module?

Unsure what you mean with included a dependency on the module?
If the question is if I added the mysql module as dependency yes I have.
![image](https://github.com/flyway/flyway/assets/53257574/74d38ef8-9bf5-47cb-b2f3-738406169ff1)

**Comment by tjs145** [comment]
What specific error message did you get?

**Comment by DxsSucuk** [comment]
![image](https://github.com/flyway/flyway/assets/53257574/8f2af0c9-b18e-49c2-aa6c-cff0c0e48c85)
I receive the error message that the current Database is not supported, even thou it is stated that it is being supported by the Website. And when trying to do the same with another project, that uses the exact same thing it works fine.

**Comment by DxsSucuk** [comment]
Even after checking the dependencies via InteliJ, there is no dependency that overwrites the version that is being used.
![image](https://github.com/flyway/flyway/assets/53257574/24b308a5-e7d5-401c-9f74-19b84cd5ee53)
So it should work, but doesnt.

**Comment by tjs145** [comment]
You'll need to make sure the `flyway-mysql` jar is on the classpath at runtime
