### ISSUE TITLE
`ClassicConfiguration.setDataSource(Datasource)` closes datasource

### ISSUE THREAD

**Issue by gusega** [flyway/flyway#3773]
###### Which version and edition of Flyway are you using?
9.22.3

[ClassicConfiguration.setDataSource(Datasource)](https://github.com/flyway/flyway/blob/4888d9c06425c3e63b7f36fd49cb29ec45db71f4/flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java#L1092)

closes connection.

It should not.
```
    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
        try (Connection connection = dataSource.getConnection()){
            this.databaseType = dataSource != null ? DatabaseTypeRegister.getDatabaseTypeForConnection(connection) : null;
        } catch (SQLException e) {
            this.databaseType = null;
        }
    }
```
The connection variable is declared in the try-with-resource block. So `connection.close()` is called on exit from the block.

Last time it was working correctly was in [9.19.4](https://github.com/flyway/flyway/blob/6edf1d5de3cb7edafc06865cef420673e2c2ff45/flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java#L78)

**Comment by JasonLuo-Redgate** [comment]
Hi @gusega , in 9.19.4, the only `setDataSource` is `setDataSource(String url, String user, String password)`, which is still usable in the new version. If you mean you want to use that?

**Comment by gusega** [comment]
@JasonLuo-Redgate it has setter in [lombok annotation](https://github.com/flyway/flyway/blob/6edf1d5de3cb7edafc06865cef420673e2c2ff45/flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java#L78).
My point is that [ClassicConfiguration.setDataSource(Datasource)](https://github.com/flyway/flyway/blob/4888d9c06425c3e63b7f36fd49cb29ec45db71f4/flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java#L1092) should not close the connection.

**Comment by gusega** [comment]
@JasonLuo-Redgate it gets connection from data source. It does not create it. So it should not close it.

But I may be wrong. Let me check.
