### ISSUE TITLE
Flyway 10 Gradle Plugin: No database found to handle jdbc:postgresql://...

### ISSUE THREAD

**Issue by josephearl** [flyway/flyway#3774]
###### Which version and edition of Flyway are you using?

Gradle plugin version 10.0.0
Upgraded from 9.22.3

I read the upgrade notes - https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html - but did not see any changes relating to PostgreSQL or clean.

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin
Gradle version 8.4
JVM 17.0.9

###### Which database are you using? (Type & version)

PostgreSQL

###### Which operating system are you using?

Tested on both Linux x64 (RHEL8) and ARM x64 (M2)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We have a custom flyway clean task:

```
tasks.register('flywayCleanTest', FlywayCleanTask) {
  url = System.getenv('TEST_JDBC_URL') ?: 'jdbc:postgresql://localhost/testdb?currentSchema=test'
  user = System.getenv('TEST_DATABASE_USERNAME') ?: 'admin'
  password = System.getenv('TEST_DATABASE_PASSWORD') ?: 'admin'
  defaultSchema = 'test'
  cleanDisabled = false
}
```

###### What did you expect to see?

The clean succeeds without error, as it did for 9.22.3

###### What did you see instead?

Running `./gradlew flywayCleanTest` gives an error:

```
No database found to handle jdbc:postgresql://localhost/testdb?currentSchema=test
```

**Comment by tjs145** [comment]
As of version 10, you'll need to add a dependency on `flyway-database-postgresql`

https://documentation.red-gate.com/fd/postgresql-184127604.html

**Comment by Barry-RG** [comment]
Just for clarification, this is what was meant in the [release notes](https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html) as:

> Java compatibility
* Deprecated Java 8. Java 17 is now required for development
* Modularized database support in Flyway to allow greater flexibility. This includes; DB2, Derby, HSQLDB, Informix, PostgreSQL, CockroachDB, Redshift, SAP HANA, Snowflake and Sybase ASE. See Database Support page for your database for module dependency.

Unfortunately I cannot link to that section directly. The Database Support page for PostgreSQL is [here](https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/postgresql)

**Comment by josephearl** [comment]
Perhaps that should be moved to the breaking changes section and clarified?

Anyway happy to close this - I have the info I need to upgrade, thanks all

**Comment by Barry-RG** [comment]
@josephearl thank you for your comment. I have actually moved that up into the breaking changes to make it more noticeable.

**Comment by donalmurtagh** [comment]
I still can't see any mention of this change in the [breaking changes section for v10](https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html)

**Comment by jankoh** [comment]
We, too, have this issue even after applying the extra dependency. Unfortunately, the error message isn't really helpful, since it doesn't specify if there is a dependency, configuration, connection, authentication, or whatever else error; only stateing the message above. 

At least I don't see a connection attempt logged in my postgres instance.

Best regards Jan

**Comment by jankoh** [comment]
Got it solved by adding the additional dep to the buildscripts dependency declaration, too:

```kotlin
plugins {
    ...
    id("org.flywaydb.flyway") version "10.1.0" apply false
    ...
}
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        ...
        classpath("org.flywaydb:flyway-database-postgresql:10.1.0")
        ...
    }
}
```

I guess, this is needed in our case, since we declare the plugin dependency in our main gradle file; and each subproject using flyway the uses the plugin definition from main and adds flyway-core and flyway-database--postgres itself for SpringBoot/Tests.

Just in case someone else stumbles over this; maybe this helps. :smiley:

**Comment by Mahendra-gowdru-k** [comment]
> Got it solved by adding the additional dep to the buildscripts dependency declaration, too:
> 
> ```kotlin
> plugins {
>     ...
>     id("org.flywaydb.flyway") version "10.1.0" apply false
>     ...
> }
> buildscript {
>     repositories {
>         mavenCentral()
>     }
>     dependencies {
>         ...
>         classpath("org.flywaydb:flyway-database-postgresql:10.1.0")
>         ...
>     }
> }
> ```
> 
> I guess, this is needed in our case, since we declare the plugin dependency in our main gradle file; and each subproject using flyway the uses the plugin definition from main and adds flyway-core and flyway-database--postgres itself for SpringBoot/Tests.
> 
> Just in case someone else stumbles over this; maybe this helps. 😃

This Solved my issue, Thanks.

**Comment by xfiodembo** [comment]
This is still broken for maven projects. Reverted back to 9.23. 
`    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
      <version>10.7.2</version>
    </dependency>
    
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-database-postgresql</artifactId>
      <version>10.7.2</version>
      <scope>runtime</scope>
    </dependency>`

still gets us the error No database found to handle jdbc:postgresql://...

**Comment by plusmobileapps** [comment]
I still got this build error after adding to the class path, reverting to 9.22.3 works for me. 

```
* What went wrong:
A problem occurred configuring project ':backend'.
> Could not resolve all files for configuration ':backend:classpath'.
   > Could not find org.flywaydb:flyway-database-postgresql:flyway.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/flywaydb/flyway-database-postgresql/flyway/flyway-database-postgresql-flyway.pom
       - https://plugins.gradle.org/m2/org/flywaydb/flyway-database-postgresql/flyway/flyway-database-postgresql-flyway.pom
     Required by:
         project :backend

```

**Comment by decoursin** [comment]
I think it's important to mention that you have to substitute the `flyway-database-postgresql` dependency in place of `flyway-core`, otherwise it doesn't work (at least for me).

**Comment by jamesdh** [comment]
This is vaguely alluded to in the [Flyway Gradle Task documentation](https://documentation.red-gate.com/fd/gradle-task-184127407.html) under the header "Adding dependencies on Flyway Database Types": 

> For some Flyway database types, like [Cloud Spanner](https://documentation.red-gate.com/fd/flyway-cli-and-api/supported-databases/google-cloud-spanner) and [SQL Server](https://documentation.red-gate.com/fd/flyway-cli-and-api/supported-databases/sql-server-database), you'll need to add a dependency to the database type in a buildscript closure to get your Gradle commands to work properly. This puts the database type on the build classpath, and not the project classpath.
> 
> Here is an example build.gradle:

Since the 10.x change, it appears this is now the case for all databases. This is very poorly documented, and we stumbled upon this today as well when trying to upgrade Spring Boot from 3.2.8 to 3.3.3, whose BOM includes an update of Flyway from 9.x to 10.10.0.

**Comment by dpointeck** [comment]
I came across this poblem today where I use flyway in a ktor project. I had to put this to the top of my `build.gradle.kts` file.

```kotlin
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.flywaydb:flyway-database-postgresql:10.19.0")
    }
}

apply(plugin = "org.flywaydb.flyway")

plugins {
    kotlin("jvm") version "2.0.20"
    // add flyway plugin
    id("org.flywaydb.flyway") version "10.19.0"
    // project specific plugins
    id("io.ktor.plugin") version "3.0.0"
    id("org.jetbrains.kotlin.plugin.serialization") version "2.0.20"
}
```
