### ISSUE TITLE
Migrations are not found after upgrading to version 10

### ISSUE THREAD

**Issue by plmarcelo** [flyway/flyway#3785]
###### Which version and edition of Flyway are you using?

10

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line + Docker

###### Which database are you using? (Type & version)
Posgres 13.2

###### Which operating system are you using?
Arch linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
When I run the migrations (flyway -locations="filesystem:/flyway/sql" migrate). The username, password & url are already configured as ENV variables. This works perfectly on the version 9.22.3

###### What did you expect to see?
The migration to be ran

###### What did you see instead?
I get this error: ERROR: Skipping filesystem location: /flyway/sql (not a directory)

**Comment by JasonLuo-Redgate** [comment]
Hi @plmarcelo ,

In V10 release, the `sql`  folder won't be shipped by default. More info can be found in the release notes. 

https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html

**Comment by plmarcelo** [comment]
Yes, I saw this on the release notes. That's why I was specifying the locations as an argument of the command. Or should we set it only on the config file?

**Comment by JasonLuo-Redgate** [comment]
Hi @plmarcelo , there is no default `sql` folder shipped, so even you specified it through `locations` parameter, Flyway won't be able to find it.
