### ISSUE TITLE
Flyway CLI migration deployment fails when using m7a EC2 instance and not m6a EC2 instance 

### ISSUE THREAD

**Issue by tdwaf** [flyway/flyway#3789]
###### Which version and edition of Flyway are you using?

9.22.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes, same issue happens when on version 10

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

MySQL using the Microsoft JDBC Driver for SQL Server 

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Used the same process as we normally do with a different type of EC2 instance

###### What did you expect to see?

Flyway CLI deploys migrations successfully

###### What did you see instead?

Using the CLI within a docker container hosted on an `m6a` EC2 instance works fine and as expected. When upgrading the instance to `m7a`, we start seeing the error:

```
SQL State  : 08S01
Error Code : 0
Message    : The TCP/IP connection to the host <host>, port <port> has failed. Error: "<host>. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host <host>, port <port> has failed. Error: "<host>. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
```

**Comment by JasonLuo-Redgate** [comment]
Hi @tdwaf , based on the error message posted, it's more like a connection issue rather than a functional issue to me. Could you check whether there is any additional configuration needed when running on m7a EC2?

**Comment by tdwaf** [comment]
> Hi @tdwaf , just to confirm the content you posted `MySQL using the Microsoft JDBC Driver for SQL Server`, by `MySQL` you mean `Microsoft SQL Server`?

Yes, that's correct. I've been looking into it a bit more, and I can't for the life of me see any additional configuration that would be needed in this case
