### ISSUE TITLE
Flyway 10 does not support anymore the newest version of HSQLDB 2.7.x but only older version

### ISSUE THREAD

**Issue by marcelbaumann** [flyway/flyway#3790]
I upgraded to Flyway 10.

Using the Java API, Flyway states that HSQLDB 2.7.x is not supported. In the official documentation, it is stated that older versions up to 2.4.x are supported.

The same code works without error when using FlyWay 9.22.3 or earlier.

Could you again support the actual version of HSQLDB in the community edition?

**Comment by JasonLuo-Redgate** [comment]
Hi @marcelbaumann , could you take a look at the proposed action in https://github.com/flyway/flyway/issues/3780 to see whether it's the actual root cause?

**Comment by marcelbaumann** [comment]
Hello @JasonLuo-Redgate 

You are right. It solved the problem easily. I was wrong. Thank You. 

As a suggestion, I went the wrong way due to the error message and the official statement on flywaydb page under
[docu HSQLDB](https://documentation.red-gate.com/fd/hsqldb-184127598.html). 

You could perhaps update the information on the page or add a link to the specific package for HSQLDB.

Enjoy the day
