### ISSUE TITLE
Flyway 10 migration doesn't succeed but neither fail - it stays in idle state (V10.0.0 and V10.0.1)

### ISSUE THREAD

**Issue by simoSgua** [flyway/flyway#3792]
###### Which version and edition of Flyway are you using?
I tried to update to 10.0.0 but without success.
I've started to experiment the problem after the flyway:9.20.0-alpine (last version stable without the problem).

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Unfortunately yes, I tried the other versions after the 9.20.0, but still the problem is present. I run the migration, but it never ends.
When I check the logs, I don't see anything.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Postgres, v13, dockerized

###### Which operating system are you using?
Window 10, but the system runs on docker desktop. For Mac user the problem has not been detected.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I simply run the migration as always, but it seems that the pods stay in an idle state without doing anything.
the kubectl logs <pod name> says nothing.
I tried to explicitly set the logger to console (https://www.red-gate.com/hub/product-learning/flyway/the-flyway-configuration-files#migrationfiles -> flyway.loggers=console) as well, but without change in the final outcome.
-> I simply ask to the system to perform "migrate" task

###### What did you expect to see?
I expect to see some logs of the migration, with the version 9.20.0 I see the logs (details on the next question) and the pods completes in short time.
After that version the pods seem to enter in a idle state.
The problem is only present on window 10 environment, with Mac user no problem detected.

###### What did you see instead?

Curently, with v10.0.0 I have:

$> kubectl get all

.NAME                             READY   STATUS    RESTARTS   AGE
pod/flyway-migration-job-rwncz   1/1     Running   0          2m20s
pod/postgres-sts-0               1/1     Running   0          5h15m

NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/kubernetes         ClusterIP   <class-A-local-ip#1>       <none>        443/TCP          7d4h
service/postgres-service   NodePort    <class-A-local-ip#2>   <none>        5432:30432/TCP   5h15m

NAME                            READY   AGE
statefulset.apps/postgres-sts   1/1     5h15m

NAME                             COMPLETIONS   DURATION   AGE
job.batch/flyway-migration-job   0/1           2m20s      2m20s

$> kubectl logs pod/flyway-migration-job-rwncz
$> kubectl logs job.batch/flyway-migration-job
--> No logs, no idea of what is happening

When I use the 9.20.0 the flow runs smoothly:

$> kubectl get all
NAME                             READY   STATUS      RESTARTS   AGE
pod/flyway-migration-job-f8lxq   0/1     Completed   0          14s
pod/postgres-sts-0               1/1     Running     0          90s

NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/kubernetes         ClusterIP   <class-A-local-ip#1>       <none>        443/TCP          7d4h
service/postgres-service   NodePort     <class-A-local-ip#2>  <none>        5432:30432/TCP   90s

NAME                            READY   AGE
statefulset.apps/postgres-sts   1/1     90s

NAME                             COMPLETIONS   DURATION   AGE
job.batch/flyway-migration-job   1/1           10s        14s

$> kubectl logs job.batch/flyway-migration-job
Flyway Community Edition 9.20.0 by Redgate
See release notes here: https://rd.gt/416ObMi

Database: jdbc:postgresql://--connection-details-- (PostgreSQL 13.10)
Successfully validated 156 migrations (execution time 00:00.416s)
Current version of schema "<user_name>": 1.106.0
Migrating schema "<user_name>" with repeatable migration "10 address views"
Migrating schema "<user_name>" with repeatable migration "15 bill functions"
Migrating schema "<user_name>" with repeatable migration "20 bill and bill profile views"
...
Migrating schema "<user_name>" with repeatable migration "40 customer views"
Migrating schema "<user_name>" with repeatable migration "50 bill profile functions"
Successfully applied 5 migrations to schema "<user_name>" (execution time 00:00.360s)
A Flyway report has been generated here: /tmp/flyway/report.html

**Comment by JasonLuo-Redgate** [comment]
Hi @simoSgua , could you run it again with `-X` flag to get more output?

**Comment by simoSgua** [comment]
I tested the -X option, unfortunately it works only on the 9.20.0-apline version.
On the 10.0.0 and 10.0.1, with and without -alpine the result is always the pod that stay in an "idle" status without says anything in the logs.
The -X work only in the 9.20.0 version; it follows an example:

<Example with 9.20.0>
DEBUG: Schema History table "ba_etl"."flyway_schema_history" successfully updated to reflect changes
Successfully applied 5 migrations to schema "ba_etl" (execution time 00:00.322s)
DEBUG: Memory usage: 16 of 20M
A Flyway report has been generated here: /tmp/flyway/report.html

The example with 10.0.0 or 10.0.1 is an empty logs, with the that is running a migration that should be fast.

**Comment by simoSgua** [comment]
Hi @JasonLuo-Redgate, I provided the feedback.
Do you have some idea?

**Comment by simoSgua** [comment]
@JasonLuo-Redgate are there any updates?

**Comment by simoSgua** [comment]
@JasonLuo-Redgate the problem was related to the fact that flyway tend to call an external server for updates, which causes the "DEBUG: Unable to check for updates: Remote host terminated the handshake".
The problem has been fixed adding the parameter "-skipCheckForUpdate".

The main problem was that the pod showed no error message, but stay in the idle state.
Maybe something in the start up procedure.

**Comment by JasonLuo-Redgate** [comment]
Hi @simoSgua , many thanks for the update. 

The confusing part is that I checked the code [here ](https://github.com/flyway/flyway/blob/43b4a835cd0472a4c7ecd5116280d6a3a9ad3804/flyway-commandline/src/main/java/org/flywaydb/commandline/MavenVersionChecker.java#L92), if the `EBUG: Unable to check for updates` message gets printed out, it indicates that the `while` loop in above lines has ended, so Flyway should continue rather than hanging there.

**Comment by OlegZavrazhin** [comment]
Why is has been closed? What is the solution?
