### ISSUE TITLE
Invalid SQL filenames found - Invalid versioned migration name format

### ISSUE THREAD

**Issue by ClaraPaiva** [flyway/flyway#3796]
Hello,
**Technical context**:
- Java 17
- Spring Boot 3.1.2
- Flyway Community Edition 9.16.3 by Redgate
- I'm trying to use Flyway on a small in-memory database of type H2. I want Flyway to run for creating a table and data-fill it based on 2 .sql files I prepared (for subsequent automatic end-to-end testing with Cypress).

**Error message:** on Spring Boot application launch on my 'e2e' spring profile
`11:00:03.521 ERROR [o.springframework.boot.SpringApplication] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invalid SQL filenames found:
Invalid versioned migration name format: V1__qualification_data_insertion.sql (could not recognise version number V1)
Invalid versioned migration name format: V1__qualification_table_creation.sql (could not recognise version number V1)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	(...)
	Caused by: org.flywaydb.core.api.FlywayException: Invalid SQL filenames found:
Invalid versioned migration name format: V1__qualification_data_insertion.sql (could not recognise version number V1)
Invalid versioned migration name format: V1__qualification_table_creation.sql (could not recognise version number V1)
	at org.flywaydb.core.internal.resource.ResourceNameValidator.validateSQLMigrationNaming(ResourceNameValidator.java:59)`

If of any use: here are my properties for the given e2e profile (e2e.properties):
```
spring.datasource.url=jdbc:h2:mem:grj
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.url=jdbc:h2:mem:grj
spring.flyway.user=sa
spring.flyway.password=password
spring.flyway.validateMigrationNaming=true
spring.flyway.locations=classpath:db/migration/e2e
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

logging.level.ch.ge.pj.grj=DEBUG


```
If I turn `spring.flyway.validateMigrationNaming` to false, it fails silently (i.e it does not complain; the app launches but no SQL script seems to have been executed)

I think the files I have are named as expected?

- V1__qualification_data_insertion.sql
- V1__qualification_table_creation.sql
and they are placed in a folder: back-end\src\main\resources\db\migration\e2e  as stated on the properties file.

What I am doing wrong?  I think I'm following the guidelines concerning the file naming.

---

###### Which version and edition of Flyway are you using?
Flyway Community Edition 9.16.3 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes but I cannot do that, because for TEST and PROD we use another database (PostgreSQL) and I'm not allowed to upgrade the Flyway version. As I tried, I get an error ( "_Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception with message: Unsupported Database: PostgreSQL 15.4_" )

(and anyway, that upgrade would be inconvenient /out of scope for my task right now)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java Spring Boot project, maven

###### Which database are you using? (Type & version)
      <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        
        <profile>
            <id>e2e</id>
            <dependencies>
                <dependency>
                    <groupId>com.h2database</groupId>
                    <artifactId>h2</artifactId>
                    <scope>runtime</scope>
                </dependency>
            </dependencies>
        </profile>

###### Which operating system are you using?
Windows 10 enterprise

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I added 2 small SQL scripts for creating a table and inserting 2 records in that table, for a temporary H2 database (local and DEV end-to-end tests)
Execute my Spring Boot with the specified profile, as usual.

###### What did you expect to see?
Table created, with 2 records inserted inside. 

###### What did you see instead?

- No tables under "PUBLIC"
- no data
- The error message already shared here

![image](https://github.com/flyway/flyway/assets/6685137/b3dd4ab2-c1e9-4c66-947e-67f6fc325a52)
and one error message on how Flyway finds the files but doesn't agree on the naming (as above)

**Comment by JasonLuo-Redgate** [comment]
Hi @ClaraPaiva , you won't be able to have the two file both versioned as V1. You need to have a different version number of your 2nd sql file.
