### ISSUE TITLE
Warnings for unsupported version with most recent SAP HANA Cloud due to broken `isCloud` detection

### ISSUE THREAD

**Issue by LukasHeimann** [flyway/flyway#3801]
###### Which version and edition of Flyway are you using?
9.16.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
SAP HANA Cloud 2023.28.12 (QRC 3/2023)

###### Which operating system are you using?
Linux

#### What did you do? 
I'm using Flyway to manage a schema on HANA Cloud. Since a couple of weeks, after an update of HANA Cloud, Flyway emits a warning that the version is not supported. I managed to trace the problem down to the HANA Version detection. If on Cloud, HANA version must (at most) be 4, on premise it must only be HANA v2: https://github.com/flyway/flyway/blob/main/flyway-database/flyway-database-saphana/src/main/java/org/flywaydb/database/saphana/SAPHANADatabase.java#L53

However, the detection for cloud or not seems to be broken as of the most recent update: https://github.com/flyway/flyway/blob/ef097b742647402b531ed6c1e1b5dd3cc2370154/flyway-database/flyway-database-saphana/src/main/java/org/flywaydb/database/saphana/SAPHANAConnection.java#L30
It usually checks for `SELECT VALUE FROM M_HOST_INFORMATION WHERE KEY='build_branch'`, which used to start with `fa/CE` for HANA Cloud. However, with recent versions of HANA Cloud, the field seems to be empty, causing flyway to think its running on-premise and emitting the warning.

#### What would you expect?

I've contacted HANA CLoud support to get information how to distinguish Cloud from On-Premise, and they responded with the following:

> As a result of the discussion we added the key 'build_qrc_version' to the SQL Reference Guide:
> https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/m-host-information-system-view
>
> If ‘build_qrc_version’ has a quarterly date, it is cloud software, for example: 4/2023. 
>
> For on-premise software, for the ‘build_version’, you would see the build number, for example, 2.00.74.00 = HANA 2.0 SPS 07 Revision 74. 
> For on-premise, ‘build_qrc_version’ would presumably be empty. 
> 
> You could compare the pages for the Cloud and On-Prem SQL Reference Guide: 
> Cloud: https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/m-host-information-system-view
> On-Prem: https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20b10028751910148c1c9de602d771de.html

**Comment by JasonLuo-Redgate** [comment]
Hi @LukasHeimann , do we have a confirmation from HANA that `build_branch` was depreciated and removed? 
Because this seems to be a breaking change, so does HANA have a release note to post this officially?

**Comment by LukasHeimann** [comment]
I've asked support, and the `build_branch` was never documented for HANA Cloud anyways (would have been here: https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/m-host-information-system-view).

They clarified internally that `build_qrc_version` is to be used for this use case and is now officially documented (see the quote above)

**Comment by JasonLuo-Redgate** [comment]
Hi @LukasHeimann,
Based on the reply you posted from HANA Cloud support, the new detecting logic could be something like below:
```

            String buildQrcVersion = 
                      jdbcTemplate.queryForString("SELECT VALUE FROM M_HOST_INFORMATION WHERE KEY='build_qrc_version'");
            if (StringUtils.hasText(buildQrcVersion)) {
                isCloud = true;
            } else {  
                String buildBranch = 
                          jdbcTemplate.queryForString("SELECT VALUE FROM M_HOST_INFORMATION WHERE KEY='build_branch'");
                isCloud = buildBranch.startsWith("fa/CE");
            }
```
Could you confirm this works for you?

**Comment by JasonLuo-Redgate** [comment]
This fix will be included in the next release of Flyway.

**Comment by LukasHeimann** [comment]
Thank you for this fix!
