### ISSUE TITLE
Flyway 10.X doesn't work with HSQLDB 2.7.2 (works fine with 9.X)

### ISSUE THREAD

**Issue by JaspreetSinghJassal** [flyway/flyway#3804]
###### Which version and edition of Flyway are you using?
Flyway 9.22.3 was working fine with HSQLDB 2.7.2, but when bumping flyway to 10.0.0 I'm getting the following error exception:

```
org.flywaydb.core.api.FlywayException: Unsupported Database: HSQL Database Engine 2.7
```

**Comment by Barry-RG** [comment]
@JaspreetSinghJassal are you using Flyway CLI or including it in a project via the API?

**Comment by jaspreetjassal** [comment]
@Barry-RG: 

I'm using the API. This is exactly what I do (for my integration tests):

```
        var flyway = Flyway.configure()
            .dataSource(dataSource)
            .cleanDisabled(false)
            .sqlMigrationSuffixes(".sql")
            .locations("..path1..", "...path2...")
            .load();
        flyway.clean();
        flyway.migrate();
    }
```

**Comment by Barry-RG** [comment]
Thank you. In which case, please see the following pinned issue. https://github.com/flyway/flyway/issues/3780

From Flyway V10 there was a move to a modulised approach which requires you to include the database module for certain databases. Please see the issue linked above for more information.

**Comment by ctoabidmaqbool** [comment]
Simply, add both dependencies e.g. core and database e.g. hsqldb

Gradle way:
```
implementation 'org.flywaydb:flyway-core:10.12.0'
runtimeOnly 'org.flywaydb:flyway-database-hsqldb:10.12.0'
```

Maven way:
```
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-core</artifactId>
    <version>10.12.0</version>
</dependency>
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-database-hsqldb</artifactId>
    <version>10.12.0</version>
    <scope>runtime</scope>
</dependency>

```
