### ISSUE TITLE
Could not find org.flywaydb:flyway-core:10.2.0

### ISSUE THREAD

**Issue by CasaSky** [flyway/flyway#3805]
###### Which version and edition of Flyway are you using?
10.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
no

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
org.flywaydb.flyway

###### Which database are you using? (Type & version)
not necessary

###### Which operating system are you using?
not necessary

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
./gradlew build

###### What did you expect to see?
successful build

###### What did you see instead?
build fails with:
`
>What went wrong:
A problem occurred configuring project 'xxx'.
 Could not resolve all files for configuration ':xxx:classpath'.
   > Could not find org.flywaydb:flyway-core:10.2.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/flywaydb/flyway-core/10.2.0/flyway-core-10.2.0.pom
       - https://plugins.gradle.org/m2/org/flywaydb/flyway-core/10.2.0/flyway-core-10.2.0.pom
     Required by:
         project :xxx > org.flywaydb.flyway:org.flywaydb.flyway.gradle.plugin:10.2.0 > gradle.plugin.org.flywaydb:gradle-plugin-publishing:10.2.0
`

**Comment by CasaSky** [comment]
it seems that gradle detects automatically that there is a new version and picks the latest version of flyway but this is not yet available in maven repo. Seems to be conflict in version resolving.

**Comment by Barry-RG** [comment]
Yes, there was an issue with our release pipeline, please bare with us

**Comment by Barry-RG** [comment]
This should now be resolved

**Comment by CasaSky** [comment]
@Barry-RG can you explain why gradle plugin 10.+ detects a new version which is not in maven central yet?
