### ISSUE TITLE
Flyway 10.1.0 doesn't support HSQLDB 2.7, recommends upgrading Flyway

### ISSUE THREAD

**Issue by ashtonbatty** [flyway/flyway#3806]
###### Which version and edition of Flyway are you using?
10.1.0 (Community edition)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
HSQLDB 2.7.2

###### Which operating system are you using?
Windows, Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Start a Spring Boot app with flyway-core 10.1.0 and flyway-database-hsqldb 10.1.0

###### What did you expect to see?
No upgrade recommendation/support warning, because HSQLDB 2.7.2 was released long before Flyway 10.1

###### What did you see instead?
The following message in logs:
`Flyway upgrade recommended: HSQLDB 2.7 is newer than this version of Flyway and support has not been tested. The latest supported version of HSQLDB is 2.6`

**Comment by Barry-RG** [comment]
This will be updated
