### ISSUE TITLE
mysql 8.2 used to work fine with flyway 10.4.1 and now suddenly its not 

### ISSUE THREAD

**Issue by omrija1** [flyway/flyway#3817]
###### Which version and edition of Flyway are you using?
Flyway 10.4.1 version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)

mysql version 8.2

###### Which operating system are you using?
windows 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I'm trying to keep flyway docker container running but it keeps shutting down. 

###### What did you expect to see?
for the container to stay running

###### What did you see instead?
shuts down every 3 seconds 

(023-12-26 19:51:09 See release notes here: https://rd.gt/416ObMi
2023-12-26 19:51:09 Database: jdbc:mysql://db (MySQL 8.2)
2023-12-26 19:51:09 WARNING: Flyway upgrade recommended: MySQL 8.2 is newer than this version of Flyway and support has not been tested. The latest supported version of MySQL is 8.1.
2023-12-26 19:51:09 Successfully validated 1 migration (execution time 00:00.089s)
2023-12-26 19:51:09 Current version of schema `user_profiles`: null
2023-12-26 19:51:09 Schema `user_profiles` is up to date. No migration necessary.)

**Comment by tjs145** [comment]
What command are you using to run the docker container?

**Comment by omrija1** [comment]
> What command are you using to run the docker container?

what do you mean what command? i'm using docker compose
`version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:5002"
    develop:
      watch:
      - action: sync
        path: ./ 
        target: /app
        ignore:
          - .git
          - .gitignore
          - .vscode
          - .gitattributes
          - .env
          - .venv
          - .github
      - action: rebuild
        path: ./Dockerfile

  flyway:
    image: flyway/flyway:10.4.1
    command: -url=jdbc:mysql://db -schemas=user_profiles -user=root -password=root!!! -connectRetries=60 migrate
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2m
    volumes:
      - .:/flyway/sql
    depends_on:
      - db

  db:
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root!!!
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3310:3309"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
`

i even went down mysql version just in case it was the issue, still same issue
2023-12-29 14:44:21 Flyway OSS Edition 10.4.1 by Redgate
2023-12-29 14:44:21 
2023-12-29 14:44:21 See release notes here: https://rd.gt/416ObMi
2023-12-29 14:44:21 Database: jdbc:mysql://db (MySQL 8.0)
2023-12-29 14:44:22 Successfully validated 1 migration (execution time 00:00.091s)
2023-12-29 14:44:22 Current version of schema `user_profiles`: null
2023-12-29 14:44:22 Schema `user_profiles` is up to date. No migration necessary.

**Comment by tjs145** [comment]
The flyway docker image normally shuts down once it has executed the command as it then has no reason to stay running. In this case it finishes running the migrate command and then shuts down. I don't know why its repeating that since it should only be restarting on failure and there aren't any errors in the logs you posted. Does it still constantly reboot if the flyway restart policy condition is changed to `none`?

**Comment by omrija1** [comment]
its none, thats why im shocked, cuz u didnt put it in restart, but it got fixed somehow when i downgraded
