### ISSUE TITLE
When the sql file has been executed,somebody changed it,then the project goes wrong

### ISSUE THREAD

**Issue by JokerSora** [flyway/flyway#3818]
why don't we do such things that after reading and executing the sql file,then change it into a pdf file or other file which is read only.
cause we can't make everyone to avoid to change the executed sql files.
since the sql files which have executed just realized their aim,so they should be just read only to avoid being changed by mistake.

**Comment by JokerSora** [comment]
However, we can make everyone who use flyway to execute their own maked sql files,if the executed sql files changed into other read only files,then other people in project can't change these executed sql files by mistake.

**Comment by Barry-RG** [comment]
This does not seem an appropriate process for Flyway to perform. 
However, if you are having issues with changed SQL scripts getting into your deployment I would recommend integrating the command [`validate`](https://documentation.red-gate.com/flyway/flyway-cli-and-api/commands/validate) which would fail ahead of deployment if changes have been made to previously deployed Flyway version scripts.

Additionally, you may want to look at [Flyway Desktop](https://documentation.red-gate.com/flyway/flyway-desktop) as a way of managing your Flyway development environment if you wish to have more restrictions.
