### ISSUE TITLE
official support of snowflake v8

### ISSUE THREAD

**Issue by frichtarik** [flyway/flyway#3821]
###### Which version and edition of Flyway are you using?

10.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

CLI

###### Which database are you using? (Type & version)

Snowflake 8.0

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

with every run i'm getting warning

Flyway upgrade recommended: Snowflake 8.0 is newer than this version of Flyway and support has not been tested. The latest supported version of Snowflake is 7.33.

###### What did you expect to see?

nothing

###### What did you see instead?

warning 
reiteration of #3602 and #3386

**Comment by frichtarik** [comment]
this was fun, let's do it again 
SF already jumped to 8.5 :D

**Comment by sfc-gh-kadams** [comment]
Hello, Snowflake has a weekly release cycle. Not all release are major. Not all releases impact current functionality. A monthly behavior change bundle is deployed that has platform code changes that may (or may not) impact a customer's data processing environment. Information on the release process and change management can be found on the [Snowflake Release](https://docs.snowflake.com/en/user-guide/intro-releases) page of the documentation. As of today the current version is 8.5.1, but the last behavior change release (BCR) was issued January 15 in version 8.2.0. A list of the releases with the related BCR releases can be found on The [Whats New in Snowflake](https://docs.snowflake.com/en/release-notes/new-features) documentation.

Checking only the Snowflake version is not really a good indicator of whether something was altered on the Snowflake Platform that would potentially break compatibility with Flyway.
