### ISSUE TITLE
FR: Any plans or schedule on the Mariadb 11.2 support

### ISSUE THREAD

**Issue by EugenMayer** [flyway/flyway#3822]
Are there any plans to support MariaDB 11.x and if, is there any rough timeline?

Thank you for all your great work!

PS:
Is there any way to supress `Flyway upgrade recommended: MariaDB 11.2 is newer than this version of Flyway and support has not been tested. The latest supported version of MariaDB is 10.11.` for the time being? (via errorOverrides i assume, but there is no errorCode here)

**Comment by Barry-RG** [comment]
Thank you for your issue. Because this is a warning not an error, we do not have a way to suppress it at the moment. However, support for MariaDB up to version 11.2 will be coming in the next release.
