### ISSUE TITLE
jdk8 no supported for 10.6.0

### ISSUE THREAD

**Issue by fffguo** [flyway/flyway#3824]
###### Which version and edition of Flyway are you using?

10.6.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

java api

###### Which database are you using? (Type & version)

mysql

###### Which operating system are you using?

windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

jdk8 no supported

The [ERROR] class file has the incorrect version 61.0, which should be 52.0. [ERROR] Please delete the file or make sure that the file is in the correct classpath subdirectory.

###### What did you expect to see?

jdk8  supported

###### What did you see instead?

jdk8 no supported

**Comment by Barry-RG** [comment]
As of version 10.0.0, Flyway has moved to supporting Java 17. This move has been made due to the dwindling official support for Java 8 and the many subsequent LTS versions that have been released since.  We are not looking at going back to supporting Java 8 in the foreseeable future.
