### ISSUE TITLE
oracleSqlPlus config parameter not working since version 9.20.0

### ISSUE THREAD

**Issue by ghorio** [flyway/flyway#3827]
###### Which version and edition of Flyway are you using?

org.flywaydb.enterprise:flyway-gradle-plugin:9.20.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin  org.flywaydb.enterprise:flyway-gradle-plugin:9.20.0

###### Which database are you using? (Type & version)

Oracle 11.2

###### Which operating system are you using?

Oracle Linux Server 8.7

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I have been successfully using org.flywaydb.enterprise:flyway-gradle-plugin:9.19.4 gradle plugin with below config
```
flyway {
    url = 'jdbc:oracle:thin:@//localhost:1521/xe'
    driver = 'oracle.jdbc.driver.OracleDriver'
    user = 'user'
    password = 'pass'
    table = 'schema_version'
    baselineOnMigrate=true
    outOfOrder=true
    placeholderReplacement=false
    locations=allLocations
    licenseKey = 'FL01****'
    ignoreMigrationPatterns = ['repeatable:missing']
    oracleSqlplus = true
}
```

But on version org.flywaydb.enterprise:flyway-gradle-plugin:9.20.0 suddenly I am getting errors like ORA-00900: invalid SQL statement, I suppose this is because oracleSqlPlus and some other methods have been removed on version 9.20.0 as I could find per this issue https://github.com/flyway/flyway/issues/3694, but on documentation it says that this config parameter is available on Flyway Teams as per this https://documentation.red-gate.com/fd/oracle-sqlplus-225608697.html
I am confused, because I do have teams license, but its not working. Or do I need to use a different plugin instead of flyway-gradle-plugin ?

###### What did you expect to see?

SQLPlus scripts to execute successfully 

###### What did you see instead?

```
  Migration beforeMigrate.sql failed
  ----------------------------------
  SQL State  : 42000
  Error Code : 900
  Message    : ORA-00900: invalid SQL statement
  Location   : /db/migration/beforeMigrate.sql (/db/migration/beforeMigrate.sql)
  Line       : 1
  Statement  : prompt **************************************************************
  PROMPT CHECK FOR ANY ACTIVE CONNECTIONS FROM TOMCAT SERVERS
  EXEC proc_safe_upgrade

  ORA-00900: invalid SQL statement

  ORA-00900: invalid SQL statement
  ```
This runs fine on 9.19.4 version

**Comment by Barry-RG** [comment]
Can you confirm if you have also imported the `flyway-database-oracle` as a dependency along side the `flyway-gradle-plugin`?

**Comment by ghorio** [comment]
Actually after creating `gradle.properties` file and adding `flyway.oracle.sqlplus=true` inside it, it worked as expected. Not sure why wouldnt it work in `build.gradle` under
```
flyway {
    oracleSqlplus = true
}
```

Also using latest version `com.redgate.flyway:flyway-gradle-plugin:10.7.1` and moving licenseKey from build.gradle to gradle.properties flyway.licenseKey, everything seems to work just fine.

I will close this.
