### ISSUE TITLE
Flyway-core.jar not compatible with Microsoft SQL Server 2014

### ISSUE THREAD

**Issue by 2016272041** [flyway/flyway#3829]
###### Which version and edition of Flyway are you using?
Flyway-core-7.1.1.jar file Currently I'm using my POM.XML file after building the war file I tried to execute migration but "Flyway teams edition or SQL server upgrade required. SQL server 2014 no longer supported community edition but still supported by teams edition"

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I've tried newer versions this is issue not resolved. Sometimes newer version display unsupported database warning messages

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
In my project directory I' using the JAVA ##### Which database are you using? (Type & version)
Microsoft SQL Server 2014

###### Which operating system are you using?
Client Client-sideows 11, Server Side -Windows Server 2008 Server OS

**Comment by Barry-RG** [comment]
Can you please confirm that when you are upgrading to a new version of Flyway you are also importing the appropriate Database JAR as well? In this case you would also need `flyway-sqlserver`.

Please see the following [pinned issue](https://github.com/flyway/flyway/issues/3780#issue-1972137095) for more background information if this is the source of the problem.

**Comment by Barry-RG** [comment]
I am closing this issue, if this persists please reopen the issue
