### ISSUE TITLE
Issues with flyway and Snowflake | Unable to determine the original schema for the connection

### ISSUE THREAD

**Issue by merkle-jtobey** [flyway/flyway#3831]
###### Which version and edition of Flyway are you using? 
Flyway Community Edition 10.7.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin): 
openjdk-17-jdk | Java Version: 17.0.9+9-Ubuntu-122.04

###### Which database are you using? (Type & version) 
Snowflake 8.4
Driver: Snowflake 3.13.30

###### Which operating system are you using? 
Bitbucket

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Executed Pipeline from Bitbucket

###### What did you expect to see?
Successful Push

###### What did you see instead?
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to determine the original schema for the connection

**Comment by Barry-RG** [comment]
This could be the same issue as https://github.com/flyway/flyway/issues/3604

Could you please read the limitations section on the [Snowflake support page](https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/snowflake) and confirm if this resolves your issue.

**Comment by merkle-jtobey** [comment]
Thank you, I saw [#3604](https://github.com/flyway/flyway/issues/3604) was a year old, so I wasn't sure it that was resolved yet.  This gives me what I need.
