### ISSUE TITLE
Flyway 8.5.13 db schema migration issue while repairing

### ISSUE THREAD

**Issue by FatimaBZ** [flyway/flyway#3834]
###### Which version and edition of Flyway are you using?
8.5.13 (Spring 2.7.10)

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
No, application is in production and can't upgrade at the moment. Also this behaviour is not regular, it markes the already ran scripts with DELETE in flyway_schema_history table

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using? (Type & version)
HANA

###### Which operating system are you using?
Mac 14.3

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
server startup with a db migration

###### What did you expect to see?
If script is ok, it should execute successfully and mark migrated script in row with type = 'SQL' in flyway_schema_history table instead of 'DELETE'. 
I don't want to manually change the script status(success = 1) in the flway_schema_history table for it to execute without fail.

###### What did you see instead?
Migration script is marked as 'DELETE' in flway_schema_history. 
It picks up the sql scripts in the order present in the IntelliJ dbMigration location and executes the already executed scripts from the flyway_schema_history table and update those rows as type='DELETE'(success column value=0).

Then, tries to rerun the script as type='SQL' resulting into failed migration due to present of duplicate actions (because the change has been done in the first successful script). Once the success column of flway_schema_history table is set to 1, the migration runs successfully for that table. 

However, repeats the same behavior for the next script. This means there is no issue with the script but buggy behaviour of flyway.

<img width="1191" alt="Screenshot 2024-02-02 at 6 33 34 PM" src="https://github.com/flyway/flyway/assets/85351414/085c836c-ccb3-4952-bc2a-32938cb19159">

**Comment by FatimaBZ** [comment]
For reference, my flyway configuration looks like this: 
<img width="715" alt="Screenshot 2024-02-02 at 6 54 28 PM" src="https://github.com/flyway/flyway/assets/85351414/66f4ab36-efc6-4e7f-b550-d236b859f5a2">

**Comment by FatimaBZ** [comment]
Can anyone from the team please take a look into this issue?

**Comment by JasonLuo-Redgate** [comment]
Hi @FatimaBZ , based on the doc here https://documentation.red-gate.com/fd/repair-184127461.html, it mentioned that `repair must be given the same locations as migrate`.
