### ISSUE TITLE
Flyway latest docker image unable to connect to MySQL database

### ISSUE THREAD

**Issue by bhavneshpateloptum** [flyway/flyway#3835]
###### Which version and edition of Flyway are you using?
Flyway OSS Edition 10.7.1 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Able to produce issue with docker.repo1.uhc.com/flyway/flyway:latest-alpine (as of 02/04/2024) when trying to connect to docker.repo1.uhc.com/mysql:latest

The same files works fine with Dec 20 2023 image docker.repo1.uhc.com/flyway/flyway:10.4.0-alpine

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Docker image

###### Which database are you using? (Type & version)
Version: '8.3.0'

###### Which operating system are you using?
Running on Docker running images of alpine

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Running with Docker compose

  database:
    container_name: database
    image: docker.repo1.uhc.com/mysql:latest

  flyway:
    container_name: flyway
    image: docker.repo1.uhc.com/flyway/flyway:latest-alpine
    command: -configFiles=/flyway/conf/flyway.conf -X -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql_versions:/flyway/sql
      - ./flyway-local.conf:/flyway/conf/flyway.conf

###### What did you expect to see?

With docker.repo1.uhc.com/flyway/flyway:10.4.0-alpine Dec 20 2023 image, the flyway connects to MySQL db and works fine.

flyway                     | DEBUG: Validating V001__test.sql
flyway                     | DEBUG: Multiple databases found that handle url 'jdbc:mysql://database:3306/demo?allowPublicKeyRetrieval=true&useSSL=false': TiDB, MySQL
flyway                     | Database: jdbc:mysql://database:3306/demo (MySQL 8.3)
flyway                     | DEBUG: Driver: MariaDB Connector/J 2.7.10
flyway                     | DEBUG: DDL Transactions Supported: false
flyway                     | DEBUG: Schemas: demo
flyway                     | DEBUG: Default schema: null
flyway                     | DEBUG: Disabled user variable reset as performance_schema.user_variables_by_thread cannot be queried (SQL State: 42000, Error Code: 1142)
flyway                     | WARNING: Flyway upgrade recommended: MySQL 8.3 is newer than this version of Flyway and support has not been tested. The latest supported version of MySQL is 8.1.
flyway                     | DEBUG: Scanning for SQL callbacks ...
flyway                     | DEBUG: Validating migrations ...
flyway                     | DEBUG: CherryPickConfigurationExtension not found
flyway                     | DEBUG: Filtering out resource: /flyway/sql/V001__test.sql (filename: V001__test.sql)

###### What did you see instead?

lyway                     | DEBUG: Validating V001__test.sql
flyway                     | DEBUG: Multiple databases found that handle url 'jdbc:mysql://database:3306/demo?allowPublicKeyRetrieval=true&useSSL=false': TiDB, MySQL
flyway                     | ERROR: Unexpected error
flyway                     | org.flywaydb.core.api.FlywayException: Unable to connect to jdbc:mysql://database:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
flyway                     |    at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:260)
flyway                     |    at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
flyway                     |    at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
flyway                     |    at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:72)
flyway                     |    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:133)
flyway                     |    at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
flyway                     |    at org.flywaydb.commandline.Main.executeOperation(Main.java:242)
flyway                     |    at org.flywaydb.commandline.Main.executeFlyway(Main.java:170)
flyway                     |    at org.flywaydb.commandline.Main.main(Main.java:113)

**Comment by tjs145** [comment]
This is probably the same as https://github.com/flyway/flyway-docker/issues/135. Try the workarounds mentioned there.

**Comment by bhavneshpateloptum** [comment]
Thanks @Barry-RG it resolved the issue by.
