### ISSUE TITLE
Snowflake 8.4 support

### ISSUE THREAD

**Issue by SocDean** [flyway/flyway#3836]
###### Which version and edition of Flyway are you using?

10.7.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Snowflake 8.4

###### Which operating system are you using?

Windows, Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Factory method 'flyway' threw exception with message: Unsupported Database: Snowflake 8.4

###### What did you expect to see?

Nothing

###### What did you see instead?

Error creating bean with name 'flyway' defined in class path resource

Downgrading to version 9.22.3 solves the problem, with the warning "Flyway upgrade recommended: Snowflake 8.4 is newer than this version of Flyway and support has not been tested. The latest supported version of Snowflake is 7.33."

Since Snowflake is often changing versions, and it is a managed platform. Does it make sense to remove the version limit, and instead provide warning like in 9.22.3?

**Comment by Barry-RG** [comment]
The error you describe would indicate that the `flyway-database-snowflake` module has not been included in your project. Please see the pinned issue [here](https://github.com/flyway/flyway/issues/3780)

**Comment by SocDean** [comment]
You are absolutely right. I'm sorry for wasting your time, and thank you very much for the help.
