### ISSUE TITLE
Flyway freezes when running a non-transactional migration in postgresql

### ISSUE THREAD

**Issue by techtangents** [flyway/flyway#3840]
###### Which version and edition of Flyway are you using?
Tested on 10.7.2 and various 9.x versions.
Works fine on 8.5.13

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)
Postgresql 14 via docker

###### Which operating system are you using?
flyway is being run from Mac OS using Java 21
postgres is being run on Docker Desktop

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

```
flyway/flyway-10.7.2/flyway -validateOnMigrate=true -table=schema_version -user=postgres -password=xxxxx -url=jdbc:postgresql://localhost:54323/postgres\
 -locations=filesystem:src/main/resources/db/migration\
 migrate
```

I'm running a set of migrations on a blank db. It's freezing on one migration that has a config file to set it to not run in a transaction:

V21__participant_record_change_primary_key.sql = 
```
CREATE UNIQUE INDEX CONCURRENTLY participant_record_pkey_temp ON participant_record (participant_reference, call_record_id);

ALTER TABLE public.participant_record DROP CONSTRAINT participant_record_pkey;

ALTER TABLE public.participant_record ADD CONSTRAINT participant_record_pkey PRIMARY KEY USING INDEX participant_record_pkey_temp;

```

V21__participant_record_change_primary_key.sql.conf = 

```
executeInTransaction = false
```

###### What did you expect to see?

All migrations complete

###### What did you see instead?

```
Flyway OSS Edition 10.7.2 by Redgate

See release notes here: https://rd.gt/416ObMi
Database: jdbc:postgresql://localhost:54323/postgres (PostgreSQL 14.11)
Schema history table "public"."schema_version" does not exist yet
Successfully validated 39 migrations (execution time 00:00.031s)
Creating Schema History table "public"."schema_version" ...
Current version of schema "public": << Empty Schema >>
Migrating schema "public" to version "1 - schema"
Migrating schema "public" to version "2 - schema"
Migrating schema "public" to version "3 - schema"
Migrating schema "public" to version "4 - schema"
Migrating schema "public" to version "5 - schema"
Migrating schema "public" to version "6 - schema"
Migrating schema "public" to version "7 - schema"
Migrating schema "public" to version "8 - add session id index"
Migrating schema "public" to version "9 - peer report alter column types"
Migrating schema "public" to version "10 - add peer report created index"
Migrating schema "public" to version "11 - add session team index"
Migrating schema "public" to version "12 - add more performance indexes"
Migrating schema "public" to version "13 - create call record table"
Migrating schema "public" to version "14 - alter peer reports add call record id"
Migrating schema "public" to version "15 - create participant record"
Migrating schema "public" to version "16 - alter event add call record"
Migrating schema "public" to version "17 - rename org id col participant record"
Migrating schema "public" to version "18 - add call record id idx peer report"
Migrating schema "public" to version "19 - add participant id idx peer report"
Migrating schema "public" to version "20 - add call record transfer fields"
Migrating schema "public" to version "21 - participant record change primary key" [non-transactional]
```

It hangs there and doesn't complete.

**Comment by tjs145** [comment]
You might need to set [postgresql.transactional.lock](https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/parameters/flyway/postgresql-transactional-lock) to false

**Comment by techtangents** [comment]
How do I set this in a migration-specific config file?

I've tried these variants:

```
executeInTransaction=false
flyway.postgresql.transactional.lock=false
```

```
executeInTransaction=false
postgresql.transactional.lock=false
```

```
executeInTransaction=false
transactionalLock=false
```

```
executeInTransaction=false
postgresqlTransactionalLock=false
```


In each case, I get an error like this:
```
Flyway OSS Edition 10.7.2 by Redgate

See release notes here: https://rd.gt/416ObMi
ERROR: Unknown configuration property: postgresqlTransactionalLock
```

**Comment by techtangents** [comment]
If I add this as a global setting (e.g. via CLI args) it seems to work, but I'm not sure I want that.

**Comment by tjs145** [comment]
Ok I see. Unfortunately script config files only support a subset of the parameters (listed on [this page](https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/script-config-files)), and Postgres transactional lock isn't one of them. 

Flyway applies the lock for the duration of the migration, i.e. it uses the same lock while executing multiple SQL files so I'm not sure how easy it would be to implement a different kind of lock for one specific file.

**Comment by ayush-finix** [comment]
Looks like it was changed in 9.12 I think https://github.com/flyway/flyway/issues/3497
