### ISSUE TITLE
Flyway 10.8 Postgres 14.4 suddenly failing to run migrations - Flyway 10.7 working fine

### ISSUE THREAD

**Issue by tyler-brandt** [flyway/flyway#3841]
###### Which version and edition of Flyway are you using?

`Flyway OSS Edition 10.8.0 by Redgate`

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Flyway v10.7 works fine, this morning upon automatically pulling the new docker image for 10.8 it suddenly started failing. I also confirmed that downgrading back to v10.7 still works fine.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line from within flyway docker image
```flyway/flyway        latest    sha256:6397d69e2e7b197820b3eedd9afb8398443e96ef0373bb953bbb130cd8ee390c   0837e4cc9722   2 hours ago     386MB```

###### Which database are you using? (Type & version)

Postgres 14.4

###### Which operating system are you using?

MacOS 12.6 on apple silicon M1 Pro
Colleague also has the same issue on a x64 ubuntu machine

flyway is running from the latest docker image `flyway/flyway`

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

flyway.conf
```
    flyway.url=jdbc:postgresql://localhost:5432/<db-name-here>
    flyway.user=postgres
    flyway.password=postgres
    flyway.outOfOrder=true
    flyway.locations=filesystem:/flyway/sql
    flyway.baselineVersion=0.0
```

command I ran
```
    echo "Retrieving Flyway Docker Image..."
    docker pull flyway/flyway

    echo "Starting migrations..."
    docker run --network=host \
        -v $PWD/db/flyway/sql:/flyway/sql \
        -v $PWD/db/flyway/conf:/flyway/conf \
        flyway/flyway baseline migrate
```

###### What did you expect to see?

All migrations running normally and successfully just like they did on v10.7

###### What did you see instead?

output
```
Flyway OSS Edition 10.8.0 by Redgate

See release notes here: https://rd.gt/416ObMi
Database: jdbc:postgresql://localhost:5432/<db-name-here>(PostgreSQL 14.4)
Creating Schema History table "public"."flyway_schema_history" with baseline ...
Successfully baselined schema with version: 0.0
Successfully validated 165 migrations (execution time 00:01.079s)
Current version of schema "public": 0.0
WARNING: outOfOrder mode is active. Migration of schema "public" may not be reproducible.
Migrating schema "public" to version "1.000 - init"
ERROR: Migration of schema "public" to version "1.000 - init" failed! Changes successfully rolled back.
ERROR: Migration V1.000__init.sql failed
---------------------------------
SQL State  : 25P02
Error Code : 0
Message    : ERROR: current transaction is aborted, commands ignored until end of transaction block
Location   : /flyway/sql/changes/V1.000__init.sql (/flyway/sql/changes/V1.000__init.sql)
Line       : 1
Statement  : CREATE TABLE category (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type character varying(15) NOT NULL,
    display_name character varying(250) NOT NULL,
    parent_category_id integer NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    last_modified_at timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_category" PRIMARY KEY (id),
    CONSTRAINT "FK_category_category_parent_category_id" FOREIGN KEY (parent_category_id) REFERENCES category (id) ON DELETE RESTRICT
)

Caused by: Migration V1.000__init.sql failed
---------------------------------
SQL State  : 25P02
Error Code : 0
Message    : ERROR: current transaction is aborted, commands ignored until end of transaction block
Location   : /flyway/sql/changes/V1.000__init.sql (/flyway/sql/changes/V1.000__init.sql)
Line       : 1
Statement  : CREATE TABLE category (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type character varying(15) NOT NULL,
    display_name character varying(250) NOT NULL,
    parent_category_id integer NULL,
    created_at timestamp without time zone NOT NULL DEFAULT NOW(),
    last_modified_at timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_category" PRIMARY KEY (id),
    CONSTRAINT "FK_category_category_parent_category_id" FOREIGN KEY (parent_category_id) REFERENCES category (id) ON DELETE RESTRICT
)

Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "LIKE"
  Position: 16
make[1]: *** [migrate-local] Error 1
```

I also tried searching my entire migrations directory for "LIKE" and there was only a single migration. I commented those statements out and still got the same error, leading me to believe flyway 10.8 has a syntax error when checking the flyway_schema_history table. 

Any/all help would be greatly appreciated! For now I will probably version lock our app to pull the docker image for 10.7 but I would like to avoid doing that in the long term

**Comment by tjs145** [comment]
This should be fixed in 10.8.1
