### ISSUE TITLE
Command-line: ERROR: Unexpected error - Does not try to connect

### ISSUE THREAD

**Issue by lunderhage** [flyway/flyway#3859]
###### Which version and edition of Flyway are you using?
```
# flyway version
WARNING: Storing migrations in 'sql' is not recommended and default scanning of this location may be deprecated in a future release
Flyway OSS Edition 10.10.0 by Redgate

See release notes here: https://rd.gt/416ObMi
Plugin Name     | Version 
--------------- | --------
OceanBase       | 10.8.1  
TiDB            | 10.8.1  
YugabyteDB      | 10.8.1  
ClickHouse      | 10.8.1  
Apache Ignite   | 10.8.1  
```
I am using the flyway/flyway:10.10 docker image.

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
It is the latest one.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
PostgreSQL 15

###### Which operating system are you using?
Linux (kubernetes cluster)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I am trying to run
```bash
flyway migrate -X
```

###### What did you expect to see?
That it does connect to the database and start processing my sql scripts.

###### What did you see instead?
```
DEBUG: Java Version: 17.0.10+7
DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /root/flyway.conf
DEBUG: Unable to load config file: /flyway.conf
WARNING: Storing migrations in 'sql' is not recommended and default scanning of this location may be deprecated in a future release
DEBUG: Using configuration:
DEBUG: [flyway] -> 
flyway.locations -> filesystem:/flyway/sql
password -> ********
schemas -> ["public"]
url -> "jdbc:postgresql://dbcluster.myapp-db.svc.cluster.local:5432/myapp_api_broker"
user -> "broker"

DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@63440df3 ...
DEBUG: Unable to resolve location classpath:db/callback.
Flyway OSS Edition 10.10.0 by Redgate

See release notes here: https://rd.gt/416ObMi
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
	at org.flywaydb.core.internal.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:41)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:115)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:243)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:171)
	at org.flywaydb.commandline.Main.main(Main.java:114)
```

This is my config file that resides in /flyway/conf/flyway.conf:
```
[flyway]
  url = "jdbc:postgresql://dbcluster.myapp-db.svc.cluster.local:5432/myapp_api_broker"
  user = "broker"
  password = "supersecretpasswordthatisverysecretandsecureandeverything"
  schemas = ["public"]
```

And I have tried to connect using the details in the config file with the psql client in the same container and that works fine. But flyway does not seem to even try connecting.

**Comment by JasonLuo-Redgate** [comment]
Hi @lunderhage ,
It looks like you're trying to use a `conf` file, but its content is in `toml` format. These are two different types of configuration files.
Hope below docs could be helpful:

- https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/toml-configuration-file

- https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/configuration-files
