### ISSUE TITLE
Remove java.desktop module dependency

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#3860]
###### Which version and edition of Flyway are you using?

latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

n/a

###### Which operating system are you using?

n/a

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Creating a smaller JRE using jdeps and jlink, or creating a native-image both offer ways to reduce deployment size. Unfortunately Flyway still pulls in the entire `java.desktop` module due to a single usage of `java.beans.Expression`:

- https://github.com/flyway/flyway/blob/5511c696a0057a9db744cfa0a2c78ac83c7eef82/flyway-core/src/main/java/org/flywaydb/core/internal/util/ClassUtils.java#L22

###### What did you expect to see?

This should be rewritten to no longer depend on the `java.beans` package, which in turn won't require the `java.desktop` module anymore in custom jlink JREs.

###### What did you see instead?

A reference to an obsolete class from a different era, which unnecessarily bloats jlink JREs. It's 2024. It's time for `java.beans` usages to go the way of the dodo.

**Comment by JasonLuo-Redgate** [comment]
Hi @axelfontaine ,
Glad to receive your request. We have got this done and should be included in next release.
