### ISSUE TITLE
SQL Flyway parse error caused by comment  block containing flyway configuration items

### ISSUE THREAD

**Issue by Phil-Factor** [flyway/flyway#3862]
###### Which version and edition of Flyway are you using?

10.10.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

CLI

###### Which database are you using? (Type & version)

SQL Server 2017

###### Which operating system are you using?

Windows 10

###### What did you expect to see?

I have a SQL Callback called afterInfo__Toggle.sql 'that used to work fine but now triggers an error

###### What did you see instead?

`flyway : ERROR: Unable to parse statement in .\migrations\Callbacks\afterInfo__Toggle.sql at line 1 col 1. See https://rd.gt/3ipi7Pm for more` 
`information. Input length = 1`
`At line:1 char:1`

+ `flyway  info`
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Unable t...nput length = 1:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

`Caused by: java.nio.charset.MalformedInputException: Input length = 1`

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

It was a callback that used to run I expected it to run without an error as it used to in a previous version

`/*`
`Before this code can be used in a callback, you must have the following`
`default value for flyway.placeholders.Toggle set in the project flyway.conf`
`otherwise you'll get an error.`
	`flyway.placeholders.Toggle=Yes` 
`To turn the toggle on, use flyway.placeholders.Turnit=on otherwise`
`flyway.placeholders.Turnit=on`
`in the commandline, this will look like …`
`flyway info '-placeholders.Toggle=Yes' '-placeholders.Turnit=on'` 
`You will, of course, need to add the DCL code that adds or removes`
`membership of the users roles (e.g. HR, Accounts) to the role that`
`allows access`

`*/`

`IF ('${Toggle}' = 'Yes')`
  `BEGIN --only execute this if flyway.placeholders.Toggle=Yes`
    `IF ('on' = '${TurnIt}') --if flyway.placeholders.Turnit=on`
      `BEGIN /* the start of the block that you excecute to switch`
	  `the toggle on */
        SELECT 'We have executed the code for turning the feature on';
      END;
    ELSE IF ('off' = '${TurnIt}')--if flyway.placeholders.Turnit=off
      BEGIN /* the start of the block that you excecute to switch`
	  `the toggle off */`
        `SELECT 'We have executed the code for turning the feature off';`
      `END;`
    `ELSE`
      `BEGIN`
        `SELECT 'We couldn''t recognise your ''${TurnIt}'' instructiions';`
      `END;`
  `END;`

###### What did you expect to see?

A callback executed as usual

###### What did you see instead?

The error message reproduced above

**Comment by JasonLuo-Redgate** [comment]
Hi @Phil-Factor ,

I looked into the issue posted and here are my findings:

- I copied the exact `afterInfo__Toggle.sql` file, but I got a different error message: `Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'the'.`

- This was caused by this line `--if flyway.placeholders.Turnit=off BEGIN /* the start of the block that you excecute to switch`. The root cause is that the `--` commented out the following `BEGIN` key word since they are in the same line.

- After fixing that (Start a new line for that `BEGIN` key word), the statement works fine now.

![image](https://github.com/flyway/flyway/assets/130552403/2f831f7b-79cb-485e-aaca-909e29c85351)

**Comment by Phil-Factor** [comment]
My sample somehow got mangled during the paste-in process, The code used to work fine and hasn't changed. All I did was to upgrade flyway. Obviously, when the error happened, I removed the initial comment block and it then worked fine. 

```
/*
Before this code can be used in a callback, you must have the following
default value for flyway.placeholders.Toggle set in the project flyway.conf
otherwise you'll get an error.
	flyway.placeholders.Toggle=Yes 
To turn the toggle on, use flyway.placeholders.Turnit=on otherwise
flyway.placeholders.Turnit=on
in the commandline, this will look like …
flyway info '-placeholders.Toggle=Yes' '-placeholders.Turnit=on' 
You will, of course, need to add the DCL code that adds or removes
membership of the users roles (e.g. HR, Accounts) to the role that
allows access

```
*/

IF ('${Toggle}' = 'Yes')
  BEGIN --only execute this if flyway.placeholders.Toggle=Yes
    IF ('on' = '${TurnIt}') --if flyway.placeholders.Turnit=on
      BEGIN /* the start of the block that you excecute to switch
	  the toggle on */
        SELECT 'We have executed the code for turning the feature on';
      END;
    ELSE IF ('off' = '${TurnIt}')--if flyway.placeholders.Turnit=off
      BEGIN /* the start of the block that you excecute to switch
	  the toggle off */
        SELECT 'We have executed the code for turning the feature off';
      END;
    ELSE
      BEGIN
        SELECT 'We couldn''t recognise your ''${TurnIt}'' instructiions';
      END;
  END;

```
```

**Comment by JasonLuo-Redgate** [comment]
Hi @Phil-Factor ,

I have copied the exact new text format you posted, and I couldn't reproduce this error. 
The call sql script is running fine locally.

![image](https://github.com/flyway/flyway/assets/130552403/5e831b86-2979-47bd-8f50-a6577c613733)

![image](https://github.com/flyway/flyway/assets/130552403/76b13d0d-4897-4100-ba88-a661bd6cdb67)

**Comment by Phil-Factor** [comment]
It looks like it's been fixed then. I'll upgrade to Flyway 10.11.1 and try it again

**Comment by JasonLuo-Redgate** [comment]
Many thanks @Phil-Factor. I will keep this ticket open for a while and welcome to raise any questions if this issue persists.
