### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by BusyByte** [flyway/flyway#3866]
###### Which version and edition of Flyway are you using?

Started to see ClassCastException in sbt like in this [gist](https://gist.github.com/BusyByte/e8097caafcf2b48cc6ce109a9c48ca27)
on our build server in drone

Rolled back from 10.11.0 to 10.10.0 of flyway and it resolved the issue.

Locally on my macbook it was working fine on the new version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
maven dep from sbt
```sbt
   val flywayV = "10.11.0"
   val flywayCore = "org.flywaydb" % "flyway-core" % flywayV
   val flywayPostgres = "org.flywaydb" % "flyway-database-postgresql" % flywayV
```

###### Which database are you using? (Type & version)
postgres 15.5 container

###### Which operating system are you using?
amazoncorretto 17 container

**Comment by arturaz** [comment]
The issue stems from the fact that Scala wrapper expects System.getProperties to be a Map[String, String]:

```scala
  case class JPropertiesWrapper(underlying: ju.Properties) extends mutable.AbstractMap[String, String]
            with mutable.Map[String, String]
            with mutable.MapLike[String, String, JPropertiesWrapper] {
    def iterator: Iterator[(String, String)] = new AbstractIterator[(String, String)] {
      val ui = underlying.entrySet.iterator
      def hasNext = ui.hasNext
      def next() = {
        val e = ui.next()
        (e.getKey.asInstanceOf[String], e.getValue.asInstanceOf[String])
      }
    }
}
```

(as it should be according to https://stackoverflow.com/questions/873510/why-does-java-util-properties-implement-mapobject-object-and-not-mapstring-st), while something puts a Boolean in the untyped Hashtable.

Given that changing the Flyway version rectifies the issue we believe that something is Flyway.

**Comment by amumurst** [comment]
Could it be this? 
https://github.com/flyway/flyway/commit/00db8d5f5f9defc84d5fc1871f78acc8ccde0380#diff-79abf6b6049fba7bfa35d38f11d573e97773eaa9518250b82f1cddb246dd17b2R49

**Comment by arturaz** [comment]
> Could it be this? [00db8d5#diff-79abf6b6049fba7bfa35d38f11d573e97773eaa9518250b82f1cddb246dd17b2R49](https://github.com/flyway/flyway/commit/00db8d5f5f9defc84d5fc1871f78acc8ccde0380#diff-79abf6b6049fba7bfa35d38f11d573e97773eaa9518250b82f1cddb246dd17b2R49)

Seems likely, it should be `systemProperties.put("polyglot.engine.WarnInterpreterOnly", "false");`.

**Comment by pzygielo** [comment]
> Because `Properties` inherits from `Hashtable`, the `put` and `putAll` methods can be applied to a `Properties` object. Their use is strongly discouraged as they allow the caller to insert entries whose keys or values are not `Strings`. The `setProperty` method should be used instead.

**Comment by JasonLuo-Redgate** [comment]
Hi @arturaz @amumurst @pzygielo , many thanks for raising this bug. 
We will look into it.

**Comment by JasonLuo-Redgate** [comment]
This has been fixed and will be included in the next release of Flyway.
