### ISSUE TITLE
Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Receiver class org.flywaydb.database.postgresql.PostgreSQLDatabase does not define or inherit an implementation of the resolved method 'abstract void ensureSupported()' of abstract class org.flywaydb.core.internal.database.base.Database.

### ISSUE THREAD

**Issue by Peppermint14** [flyway/flyway#3867]
###### Which version and edition of Flyway are you using?

Maven Runtime dependency org.flywaydb, flyway-database-postgresql 10.7.1.

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Using 10.11.0 for both the db dependency and the maven plugin results in the same error.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

flyway-maven-plugin 10.7.1

###### Which database are you using? (Type & version)

Postgres 16.2 (latest) (dockerîzed)

###### Which operating system are you using?

Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Starting the spring-boot (3.2.4) server with `mvn spring-boot:run`

Application-properties:  
![image](https://github.com/flyway/flyway/assets/77902782/af97ae1c-e212-420c-a03c-be3be19d8524)

Properties related to the maven profile used:
![image](https://github.com/flyway/flyway/assets/77902782/4533fc73-4897-4ee0-ba32-6f57fa172b8a)

###### What did you expect to see?

The spring boot server starting normally.

###### What did you see instead?

An error regarding the `flywayInitializer` bean. (See below)

![image](https://github.com/flyway/flyway/assets/77902782/88776215-8829-4625-8127-6804aaf3b785)

![image](https://github.com/flyway/flyway/assets/77902782/b5faaefa-d57f-49c8-b83d-16387e16bf80)

**Comment by JasonLuo-Redgate** [comment]
Hi @Peppermint14 ,
In the Exception message you posted we can see 'void ensureSupported()', while the right method signature is `void ensureSupported(Configuration configuration)`. 

The 'void ensureSupported()' signature was a very old and outdated version, so could you confirm you're using the right version of `flyway-core` module?

**Comment by Peppermint14** [comment]
We weren't using/didn't explicitly specify the `flyway-core` dependency, and I think it, therefore, pulled an older version of `flyway-core`; if I remember correctly, it was 9.22.

After adding the `flyway-core` dependency explicitly and setting it to the right version it worked. 

@JasonLuo-Redgate thanks for your help
