### ISSUE TITLE
Document Error

### ISSUE THREAD

**Issue by ElegantNorlin** [flyway/flyway#3868]
Hello! Thanks for taking the time to read my issue, I found that there is one area of the document that needs to be fixed: as shown in the figure, all hyperlinks similar to this one are invalid on this [page](https://documentation.red-gate.com/flyway/quickstart-how-flyway-works/system-requirements/supported-databases-and-versions). Thanks!

<img width="1268" alt="FC0E391D-7692-4fad-86B3-8DD08B1B251F" src="https://github.com/flyway/flyway/assets/66856403/57bd14e3-cc84-453d-a089-e008895248ab">

**Comment by alistair-RG** [comment]
We're aware of problems on this page, those responsible for it have been reminded ...
That said, which links do you mean ? The expandable sections on the page seem to work

**Comment by ElegantNorlin** [comment]
Thank you for your work, the best thing about flyway is the high efficiency and excellent organization members.

**Comment by Barry-RG** [comment]
Closing this issue as you seem to be confirming that this is fixed. If i am mistaken, please reopen.
