### ISSUE TITLE
Flyway command line FIPS enable & compliant changes ?

### ISSUE THREAD

**Issue by 9-para** [flyway/flyway#3875]
Which version and edition of Flyway are you using?
**Flyway - 8.0.0**

Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

- Flyway Command-line
- MySQL
- Linux

**Flyway command line FIPS enable & compliant changes?**

There is no update in community Forum & official documentation not helpful at all.

i didn't get an answer so checking if there is any documentation that confirms if it supports FIPS or not ?

it would be also fine if need to build it in case instructions are provided with a patch of code anywhere.

Or Flyway does not support the FIPS & all changes should be done manually by going through the library & replacing them?

**Comment by alistair-RG** [comment]
Flyway is a tool and FIPS is, as far as I can tell, a systems approach to handling data at rest and in transit. You could build a compliant system with Flyway but it's not just another feature in the tool itself.
The Redgate sales team might have more information on how to build these kind of systems as they spend more time talking with large enterprises - https://www.red-gate.com/products/flyway/editions#get-in-touch
I'm assuming this question is yours too ? https://forum.red-gate.com/discussion/90568/flyway-command-line-fips-enable-compliant-chagnes
Oh, and Flyway v8 is about 3 years old now so I'd recommend updating that ...
