### ISSUE TITLE
Migration error: Expected command status BEGIN, got SET

### ISSUE THREAD

**Issue by konart** [flyway/flyway#3880]
###### Which version and edition of Flyway are you using?
We are using v10.11.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
The error can be reproduced with the lower versions too

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
cli

###### Which database are you using? (Type & version)
Postgres 15.6

###### Which operating system are you using?
Alpine docker image

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We are trying to run migrations with the following string:
```
    -url=jdbc:postgresql://host:5432/postgres -schemas=some_schema_name -user=username -password=secured -connectRetries=60 migrate
```

###### What did you expect to see?
Something like
```
 Successfully applied N migrations to schema "some_schema_name"...
```

###### What did you see instead?
```
ERROR: Unable to restore connection to its original state
flyway-1  | --------------------------------------------------
flyway-1  | SQL State  : 55000
flyway-1  | Error Code : 0
flyway-1  | Message    : ERROR: portal "" cannot be run
flyway-1  |
flyway-1  | Caused by: org.postgresql.util.PSQLException: Expected command status BEGIN, got SET.
```

**Comment by JasonLuo-Redgate** [comment]
Hi @konart 
This error might suggest that there is some syntax issue in the executed sql file?

**Comment by konart** [comment]
Hey! Sorry for not coming back sooner. It's been some time since we migrated to a different tool (goose) and I've lost track of this issue.

I think in the end the problem was in some sort of connection pooler like https://github.com/yandex/odyssey which was in use.

The issue can be closed.
