### ISSUE TITLE
ignoreMissingPatterns not working

### ISSUE THREAD

**Issue by csternagel** [flyway/flyway#3881]
###### Which version and edition of Flyway are you using?
10.11.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

in Flyway 8 we were relying on the setting (in Maven)

`<ignoreMissingMigrations>true</ignoreMissingMigrations>`

According to the release notes here https://rd.gt/416ObMi the new alternative for this option is now "ignoreMigrationPatterns", which due to the documentation here https://documentation.red-gate.com/fd/ignore-migration-patterns-224919720.html is used as follows:

`<ignoreMigrationPatterns><ignoreMigrationPattern>*:missing</ignoreMigrationPattern></ignoreMigrationPatterns>`

The problem ist that this option does not seem to apply at all. Even worse, when I replace the pattern like

`<ignoreMigrationPatterns><ignoreMigrationPattern>versioned:missing</ignoreMigrationPattern></ignoreMigrationPatterns>`

I get the error message

> Flyway Redgate Edition Required: ignoreMigrationPattern with type 'versioned' is not supported by OSS Edition

which seems to suggest that this option is no longer part of the community edition. But that contradicts the documentation linked above.

Could somebody please clarify the situation?

**Comment by csternagel** [comment]
Sorry, it was actually not MISSING, but FUTURE migrations that caused the problem. I let myself be mislead by the error message

> Detected applied migration not resolved locally: [...]
> If you removed this migration intentionally, run repair to mark the migration as deleted.

**Comment by Barry-RG** [comment]
Thank you for your issue. I'm not sure why the documentation is out of sync. However, from the latest release 10.12.0, these features have been made available at the open source edition. 
https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine

**Comment by JasonLuo-Redgate** [comment]
Just to follow up — does this ticket still need attention?
