### ISSUE TITLE
Migration file is not executed and cheksum is 0

### ISSUE THREAD

**Issue by srinivas6degree** [flyway/flyway#3883]
###### Which version and edition of Flyway are you using?

8.5.13 from Maven repository. OS: Windows 11
###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
We are unable to upgrade to the recent version as we may have to check the compatibility with other frameworks like spring boot

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

As part of spring boot properties as well as Java API

###### Which database are you using? (Type & version)
MySQL 8.0

###### Which operating system are you using?

Windows 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We have a Spring boot server configured with Flyway migration. The target database is MySQL
We have configured the path for the DB Migration files(V and R files)
When we require to changes the table structure and /or add or modify the data, we add V or R migration files and run flyway migration as part of the server startup

###### What did you expect to see?
Expected the migration to go through and be successful. The checksum should have been calculated and the success column should have 1

###### What did you see instead?
The migration file queries/statements werent run. The checksum field had value as 0. However success column had 1

**Comment by Barry-RG** [comment]
Would you be able to provide us with the rest of the row in question from the schema history table? Without additional information it is unclear as to why the checksum would be 0.

**Comment by Barry-RG** [comment]
As this has not been responded to in a while I am going to close the ticket for now. Please feel free to reopen with more information.
