### ISSUE TITLE
Microsoft SQL server token login and Flyway placeholder results in a login error.

### ISSUE THREAD

**Issue by User7845** [flyway/flyway#3884]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 10.11.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Azure Microsoft SQL server

###### Which operating system are you using?
WIndows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I am running into a login issue once I add a Flyway placeholder to the environment variable or to my toml file.

I use the token login from sql server by setting an environment variable FLYWAY_JDBC_PROPERTIES_accessToken.
This works correctly but once I add a Flyway placeholder I run into the error:

If I remove the error disappears when I remove the placeholder from the environment variables and the TOML file.

###### What did you expect to see?

That I can correctly login and execute my migration files

###### What did you see instead?

The error:

ERROR: Unable to obtain connection from database (jdbc:sqlserver://xxxxxx.database.windows.net:1433;databaseName=xxxxx) for user 'null': Login failed for 
user ''. ClientConnectionId:a20e1e0f-02c5-4e12-a347-f35e1b777fc4
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : S0001
Error Code : 18456
Message    : Login failed for user ''. ClientConnectionId:a20e1e0f-02c5-4e12-a347-f35e1b777fc4

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user ''. ClientConnectionId:a20e1e0f-02c5-4e12-a347-f35e1b777fc4

**Comment by User7845** [comment]
I have the following configuration:
flyway.toml:
```
[flyway]
locations = ["filesystem:./sql"]
validateMigrationNaming = true
baselineOnMigrate = true
baselineVersion = "0"
table = "infra_schema_history"
placeholderReplacement = true
defaultSchema = "dbo"


[environments.d]
url = "jdbc:sqlserver://{server}.database.windows.net:1433;databaseName={dbname}"
```
In powershell I retrieve the access token and add it to the environment variables:
`$Env:FLYWAY_JDBC_PROPERTIES_accessToken = (Get-AzAccessToken -ResourceUrl https://database.windows.net).Token`

Then I execute the migration step:

```
        flyway migrate `
          -environment="${{ parameters.environment }}" `
          -workingDirectory="${{ parameters.flywayDeploymentsLocation }}/${{ parameters.flywayDeployment }}/"
```

This works correctly.

Once I add an environment variable containing the FLYWAY_PLACEHOLDERS prefix the login fails.
`$Env:FLYWAY_PLACEHOLDERS_HOSTINGTEAM="test"`

This also happends when I add the variable to the flyway.toml file:
```
[flyway.placeholders]
HOSTINGTEAM= "test"
```

The login works correctly again once I remove the placeholders

**Comment by JasonLuo-Redgate** [comment]
Hi @User7845 ,
Could you help confirm:

- Whether any of your configuration might accidently involve a placeholder replacement "HOSTINGTEAM"?
- Or does this issue happen on any other placeholder, for example, you put:
```
[flyway.placeholders]
myplaceholder = "test"
```

**Comment by JasonLuo-Redgate** [comment]
Just to follow up — does this ticket still need attention?

**Comment by JasonLuo-Redgate** [comment]
I’ll close this issue for now. If the problem persists with version `10.22.0`, please feel free to reopen this ticket or report it again.

**Comment by davidkarlsen** [comment]
This is still an issue

**Comment by davidkarlsen** [comment]
Or at least syntax needs to be:
```shell
-environments.default.jdbcProperties.accessToken=$SQL_ACCESS_TOKEN
```
