### ISSUE TITLE
Artifact flyway-parent is missing starting from 10.11.1 version

### ISSUE THREAD

**Issue by oleg-sukhov** [flyway/flyway#3886]
###### Which version and edition of Flyway are you using?

10.11.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API, Maven plugin

###### Which database are you using? (Type & version)

MySQL

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

After upgrading to version 10.11.1 the build is failed due to not able to download dependencies from https://download.red-gate.com/maven/release repository.

###### What did you expect to see?

Successfully downloaded dependnecy. 

###### What did you see instead?

Dependency not found error

![image](https://github.com/flyway/flyway/assets/8500133/6c98e9b4-4625-42ee-8c54-75a99182a28e)

![image](https://github.com/flyway/flyway/assets/8500133/1666ff7e-36db-41be-a9ca-80cce5d415cc)

**Comment by Barry-RG** [comment]
Thank you for bringing this to our attention. We will investigate what caused this issue with our deployment.
I am unsure if we will be able to redeploy 10.11.1 but I will try and see what can be done. However, we will make sure that it does not happen again moving forward.

**Comment by Barry-RG** [comment]
The 10.12.0 release was used with a fixed release pipeline. If you could update to 10.12.0, you should find the `flyway-parent` project present and this will solve your issue the quickest.

**Comment by oleg-sukhov** [comment]
Thank you, @Barry-RG. I've already upgraded. Indeed, the issue has been solved.
