### ISSUE TITLE
Error Unable to obtain connection from database for user postgres  SQL State  : 08001

### ISSUE THREAD

**Issue by urupaveko** [flyway/flyway#3891]
###### Which version and edition of Flyway are you using?
image: "flyway/flyway:9.22-alpine"
image: postgres:15.4-alpine

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Same issue with flyway 10.12.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Github actions

###### Which database are you using? (Type & version)
image: postgres:15.4-alpine

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Tired to connect by servie name, container_name, localhost, container IP

###### What did you expect to see?
I expect to successful workflow in github actions. 

###### What did you see instead?
Error connections with my DB
![flyway_10_12_0](https://github.com/flyway/flyway/assets/168630023/f5c3dea0-f173-452f-b079-f0ef462720f3)
![flyway_postgres](https://github.com/flyway/flyway/assets/168630023/4e672746-b19a-459b-89df-d22bca71fcb1)

**Comment by Barry-RG** [comment]
Thank you for your issue. I unfortunately cannot recreate the problem you are having. The connection attempt failed would imply that the database may not be ready when Flyway has attempted to connect.
I have recreated your docker compose file, and have been able to connect to the database and run a migration within the docker compose network. However, the command you are using is truncated on the screen shot provided so I am assuming no more configuration beyond what I can see and a `migrate` command. 

Could you please provide the full command as well as any docker compose logs of the initialization of both Flyway and the Database?
Additionally, could you please enable debug mode for Flyway. This can be done by adding `-X` to your command. This should display information in regards to the connectivity, as well as the configuration to check if nothing else has been changed via environment variables within Github Actions.

**Comment by urupaveko** [comment]
@Barry-RG Thanks for your feedback. I will provide Postgre logs, flyway logs and also workflow file.
![flyway_logs](https://github.com/flyway/flyway/assets/168630023/a04ec1ae-50c6-49f5-82ba-c4274377480b)
![postgres_logs](https://github.com/flyway/flyway/assets/168630023/c9640f3b-2628-431f-8a55-599257f067e6)
![workflow_file](https://github.com/flyway/flyway/assets/168630023/a60273ff-8d36-4dbb-a0a7-c0ed10374d4b)

**Comment by vadymurupa** [comment]
I added to my workflow file:

FLYWAY_URL=jdbc:postgresql://db:5432/test -e FLYWAY_USER=postgres -e FLYWAY_PASSWORD=postgres flyway migrate

Successfully run workflow

**Comment by danielriddellsh** [comment]
@urupaveko You ever resolve this? using the flyway desktop i get 

```
Unable to obtain connection from database (jdbc:postgresql://localhost:5432/postgres?ssl=false) for user 'postgres': The connection attempt failed.

SQL State  : 08001
Error Code : 0
Message    : The connection attempt failed.

Caused by: The connection attempt failed.
Caused by: Read timed out
```
