### ISSUE TITLE
Why flyway cannot execute sql again when last time execution failed?

### ISSUE THREAD

**Issue by FloriaLI** [flyway/flyway#3892]
We are using flyway 7.0.0 and mysql 8.0.25, when I tried to create sql and reverse sql to be executed by flyway, I did the complete opposite. So first time the execution failed and there's a fail execution history log in database table 'flyway_schema_history'.
![image](https://github.com/flyway/flyway/assets/19702735/e63c8495-c46f-4101-8279-c6f22a4f8506)

Then I reversed the content of the two sql files and recommit, expecting to execution again for the last execution log is tagged as fail. However,  the sql file did not be executed by flyway just because this version have been executed (even if the execution was actually failed).I seached on Internet and the solutions are just delete the failed history or update the filename to update the version. That's not a good experience.

I agree that we should not repeatedly execution sql when it was executed successfully and should create new sql file to do afterwards operations. However, when flyway check if a sql file was executed, shall we considered if it was executed **_successfully_** instead?Yeah , I mean check if the latest execution history log success=1. 

ps : I readed the latest source code and I'm suprised to see that if a sql version was executed failed , flyway will return a fail state and immediately throw a FlywayValidateException in Flyway.migrate() method. Is it an operation to force developers to delete the failed history in database or update a new version? I don't think that's a good choice. May be a repeated execution on the failed version should be allowed even it is not marked as repeatable?
![RyRG8bot1d](https://github.com/flyway/flyway/assets/19702735/a6b8dffb-a4a5-4478-9bb0-b02e706858b9)

**Comment by Barry-RG** [comment]
Thank you for your issue. Do you get this same issue with the latest version of Flyway?

**Comment by FloriaLI** [comment]
I'm sorry that I can't change the unified version used in our company. However, as I mentioned before, the latest source code shows if a sql version was executed failed , flyway will return a fail state and immediately throw a FlywayValidateException. In other words, there's similar issue with the latest version of Flyway.

**Comment by JasonLuo-Redgate** [comment]
Hi @FloriaLI ,

From the issue description, we know that you're using mysql, which does not support DDL Transactions. In this case, a rollback is not an option for Flyway.

The suggested approach for your case is to run `repair`  https://documentation.red-gate.com/fd/repair-184127461.html

**Comment by FloriaLI** [comment]
Hi @JasonLuo-Redgate ,

I've tried to run repair before migrate in my CI?CD script and it worked !  I'll close this issue later.

Thank you so much !!
