### ISSUE TITLE
Support failed missing migration with ignoreMigrationPatterns

### ISSUE THREAD

**Issue by victornoel** [flyway/flyway#3895]
###### Which version and edition of Flyway are you using?

10.13.0 Community Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Postgresql

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I am using `flywayConfig.ignoreMigrationPatterns(ValidatePattern.fromPattern("*:missing"));`, I have a failed migration in my `schemaversion` table and deleted the corresponding SQL file.

###### What did you expect to see?

The missing failed migration to be ignored during validation. The same as when there is a missing non-failed migration.

I have the memory that it was working like that in previous version of flyway but I am not 100% sure, I migrated to v10 some time ago but didn't discover that issue until now.

###### What did you see instead?

An error telling me the migration is missing:
```
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: 20240214160000
```

**Comment by victornoel** [comment]
I may be mistaken about the behaviour of flyway from previous versions though (I was using 8.5.5)

**Comment by victornoel** [comment]
Hi, I originally created this issue because I thought I had a failed migration in schema, but after more investigation, I found out that my real problem was the following bug: https://github.com/flyway/flyway/issues/3897

Feel free to close this issue if it does not make sense to you.

Thank you!

**Comment by JasonLuo-Redgate** [comment]
Replaced by https://github.com/flyway/flyway/issues/3897.
