### ISSUE TITLE
Update Spanner Database dependencies.

### ISSUE THREAD

**Issue by credmond-git** [flyway/flyway#3900]
###### Which version and edition of Flyway are you using?
10.13.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API through Spring

###### Which database are you using? (Type & version)
Spanner

###### Which operating system are you using?
Windows/Mac/Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We are upgrading all our dependencies and running into issues with the version of the spanner Database JDBC Driver com.google.cloud:google-cloud-spanner-jdbc and com.google.api:gax being pulled in by flyway is about 1 year old. 
It is conflicting with the newer versions of grpc. 

###### What did you expect to see?
I expect newer versions of flyway to contain newer versions of the com.google.cloud:google-cloud-spanner-jdbc and com.google.api:gax  dependencies. 

###### What did you see instead?
The versions of com.google.cloud:google-cloud-spanner-jdbc and com.google.api:gax  are about a year old and conflict with newer versions.

**Comment by credmond-git** [comment]
I have created a pull request to fix this issue https://github.com/flyway/flyway/pull/3899

**Comment by Barry-RG** [comment]
Thank you. Will look at merging
