### ISSUE TITLE
Compatibility with H2 2.2.224

### ISSUE THREAD

**Issue by BlueIce** [flyway/flyway#3905]
###### Which version and edition of Flyway are you using?
10.10.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Reproducible with version 10.13.0.
Looking at the [main branch](https://github.com/flyway/flyway/blob/d3ee52a45c51f0abdeaccef16ea91612ea76d0c8/flyway-core/src/main/java/org/flywaydb/core/internal/database/h2/H2Database.java#L109), the issue seems to exist in the latest version although.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
H2 (version 2.2.224)

###### Which operating system are you using?
Debian 12

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Running Spring Boot 3.3.0 with H2 database.

###### What did you expect to see?
No flyway warning appears in the log.

###### What did you see instead?
On startup, a warning is printed in the log:
> o.f.c.internal.database.base.Database    : Flyway upgrade recommended: H2 2.2.224 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.220.

Would be great if flyway could support H2 version 2.2.224, so that user of the latest Spring Boot version do not encounter a warning in their logs.

Changelogs of the H2 releases since version 2.2.220:

- https://github.com/h2database/h2database/releases/tag/version-2.2.222
- https://github.com/h2database/h2database/releases/tag/version-2.2.224

**Comment by Barry-RG** [comment]
Thank you. Will look into increasing support
