### ISSUE TITLE
Issue with mongo-jdbc-driver dependency

### ISSUE THREAD

**Issue by yaminidhamija** [flyway/flyway#3906]
###### Which version and edition of Flyway are you using?

Latest

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven dependency

Expected: Dependency should be present in maven central repo: https://repo1.maven.org/maven2/com/github/

###### Which database are you using? (Type & version)
mongo

###### Which operating system are you using?
Mac

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Trying to setup flyway with mongo using maven

https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/mongodb

But not able to find the jar:

com.github.kornilova203
mongo-jdbc-driver
1.19
I tried to find out it in maven central repository, But didnt find.

###### What did you expect to see?
Shouldn't be an issue with dependency which is present in flyway-database-mongodb

###### What did you see instead?

Not able to find mongo-jdbc-driver

**Comment by yaminidhamija** [comment]
@RedGateAdmin @Sam-Redgate

**Comment by alistair-RG** [comment]
You'll have to fetch the dependency from github yourself, if you look at the document it says:
> Include the latest MongoDB driver dependency [here](https://github.com/DataGrip/mongo-jdbc-driver) in your buildscript or import into your local maven repository

This is outside of our control
