### ISSUE TITLE
What exactly has changed from flyway 6 to flyway 7 on validation

### ISSUE THREAD

**Issue by ghorio** [flyway/flyway#3911]
###### Which version and edition of Flyway are you using?
Currently using 6.4.2 but trying to migrate to the latest one. During this I noticed that the issue I have is already on version 7

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes, the same issue happens on latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using? (Type & version)
Oracle 11

###### Which operating system are you using?
CentOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Basically using the versin 6.4.2 with command gradle flywayMigrate, everything works fine, but when trying to use the 7.0.1 or the latest one, I encounter multiple below errors
```
 Validate failed:
  Detected applied migration not resolved locally: 0300 AUDIT BB. If you removed this migration intentionally, run repair to mark the migration as deleted.
  Detected applied migration not resolved locally: 0300 AUDIT AAI. If you removed this migration intentionally, run repair to mark the migration as deleted.
  Detected applied migration not resolved locally: 0300 AUDIT CC. If you removed this migration intentionally, run repair to mark the migration as deleted.
......
```
totaling to 400 such errors, when running gradle flywayInfo, I can see that for all those 400 not resolved locally scripts, they are shown as Missing, for example
```
+------------+-----------------+------------------------------------------------------------+----------+---------------------+--------------+----------+
| Category   | Version         | Description                                                | Type     | Installed On        | State        | Undoable |
+------------+-----------------+------------------------------------------------------------+----------+---------------------+--------------+----------+
|            | 1               | << Flyway Baseline >>                                      | BASELINE | 2019-09-13 21:05:33 | Baseline     | No       |
| Repeatable |                 | 0300 AUDIT BB                                        | SQL      | 2019-09-13 21:06:23 | Missing      |          |
 Repeatable |                 | 0300 AUDIT AAI                                        | SQL      | 2019-09-13 21:06:24 | Missing      |          |
| Repeatable |                 | 0300 AUDIT CC                                       | SQL      | 2019-09-13 21:06:24 | Missing      |          |

```
But version 6.4.2 does not fail the gradle flywayMigrate task, version 7.0.1 does fail
###### What did you expect to see?

Either the same validation fail on missing migrations on version 6.4.2 or n ofailing on version 7.0.1 as well

###### What did you see instead?

Successful migration on version 6.4.2 and a failed migration on version 7.0.1 using the same scripts.

Basically what confuses me is why does it not fail on version 6.4.2 but fails on 7.0.1 and also later versions. I know that I could use `ignoreMigrationPatterns = ['repeatable:missing']` config parameter, but still, I would like to understand the change between both versions please.

Thanks

**Comment by JasonLuo-Redgate** [comment]
Hi @ghorio ,

Due to both 6.4.2 and 7.0.1 are too old versions, we're unable to back trace exact changes which introduced this Validate change. 

I would suggest use `ignoreMigrationPatterns` to handle this scenario.
