### ISSUE TITLE
Script migrations (e.g. .py) aren't loaded

### ISSUE THREAD

**Issue by RichardDRJ** [flyway/flyway#3924]
###### Which version and edition of Flyway are you using?

10.15.2 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-Line as packaged in flyway/flyway-docker

###### Which database are you using? (Type & version)

PostgreSQL

###### Which operating system are you using?

Ubuntu 20.04

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

1. Mounted my directory with my migrations at `/migrations` in the Docker container
2. Ran `flyway info migrate info`

`/migrations` directory structure:

```
__init__.py
config.py
V1__initial_setup.py
```

`V1__initial_setup.py` imports `config.py` (as `import .config`).

###### What did you expect to see?

I expected to see my migration picked up and run. When debugging, I expected to see the `ScriptMigrationResolver` class' `resolveMigrations` method called, and I expected that the `CompositeMigrationResolver` class would register `ScriptMigrationResolver` as a migration resolver (possible at line 71, with the plugin register?).

###### What did you see instead?

I saw that my Python scripts were always filtered out as resources:

```
Current version of schema "flyway": null
Schema "flyway" is up to date. No migration necessary.
DEBUG: Memory usage: 57 of 504M
DEBUG: Scanning for filesystem resources at '/migrations'
DEBUG: Scanning for resources in path: /migrations (/migrations)
DEBUG: Scanning for resources in path: /migrations/__pycache__ (/migrations)
DEBUG: Found filesystem resource: /migrations/V1__initial_setup.py
DEBUG: Found filesystem resource: /migrations/__init__.py
DEBUG: Found filesystem resource: /migrations/__pycache__/__init__.cpython-311.pyc
DEBUG: Found filesystem resource: /migrations/config.py
DEBUG: Filtering out resource: /migrations/V1__initial_setup.py (filename: V1__initial_setup.py)
DEBUG: Filtering out resource: /migrations/__init__.py (filename: __init__.py)
DEBUG: Filtering out resource: /migrations/__pycache__/__init__.cpython-311.pyc (filename: __init__.cpython-311.pyc)
DEBUG: Filtering out resource: /migrations/config.py (filename: config.py)
DEBUG: DDL Transactions Supported: true
DEBUG: Schemas: 
DEBUG: Default schema: flyway
DEBUG: Scanning for SQL callbacks ...
DEBUG: Filtering out resource: /migrations/V1__initial_setup.py (filename: V1__initial_setup.py)
DEBUG: Filtering out resource: /migrations/__init__.py (filename: __init__.py)
DEBUG: Filtering out resource: /migrations/__pycache__/__init__.cpython-311.pyc (filename: __init__.cpython-311.pyc)
DEBUG: Filtering out resource: /migrations/config.py (filename: config.py)
DEBUG: CherryPickConfigurationExtension not found
DEBUG: Filtering out resource: /migrations/V1__initial_setup.py (filename: V1__initial_setup.py)
DEBUG: Filtering out resource: /migrations/__init__.py (filename: __init__.py)
DEBUG: Filtering out resource: /migrations/__pycache__/__init__.cpython-311.pyc (filename: __init__.cpython-311.pyc)
DEBUG: Filtering out resource: /migrations/config.py (filename: config.py)
DEBUG: Filtering out resource: /migrations/V1__initial_setup.py (filename: V1__initial_setup.py)
DEBUG: Filtering out resource: /migrations/__init__.py (filename: __init__.py)
DEBUG: Filtering out resource: /migrations/__pycache__/__init__.cpython-311.pyc (filename: __init__.cpython-311.pyc)
DEBUG: Filtering out resource: /migrations/config.py (filename: config.py)
DEBUG: Filtering out resource: /migrations/V1__initial_setup.py (filename: V1__initial_setup.py)
DEBUG: Filtering out resource: /migrations/__init__.py (filename: __init__.py)
DEBUG: Filtering out resource: /migrations/__pycache__/__init__.cpython-311.pyc (filename: __init__.cpython-311.pyc)
DEBUG: Filtering out resource: /migrations/config.py (filename: config.py)
```

I also attempted to specify the `ScriptMigrationResolver` class as a resolver with the CLI argument `-migrationResolvers=org.flywaydb.core.internal.resolver.script.ScriptMigrationResolver`, but I got an error that it doesn't have a default constructor.

**Comment by Barry-RG** [comment]
Can I get confirmation which docker image you are using?
Is it flyway/flyway or redgate/flyway?

**Comment by RichardDRJ** [comment]
Hi Barry, it's `flyway/flyway`

**Comment by Barry-RG** [comment]
I think there has been a bit of miscommunication, both in our documentation and internally. Script Migrations are currently available in Redgate Community edition. As a result, if you were to use `redgate/flyway` at community level you would have access to this feature.
However, we will be putting this into the OSS edition in a future release.
