### ISSUE TITLE
Desktop hangs with "Migrating Database" with nothing in log files.

### ISSUE THREAD

**Issue by nutmix** [flyway/flyway#3926]
###### Which version and edition of Flyway are you using?

Desktop 7.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

we tried upgrading to 7.3.6 but this doesnt work (fails create new project or import projects with java error) so had to revert to the old 7.2.0 version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Desktop

###### Which database are you using? (Type & version)

postgres RDS + username/password auth and SSH tunnel.

###### Which operating system are you using?

Windows 10 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Tried to migrate new scripts.

###### What did you expect to see?

Scripts migrated.

###### What did you see instead?

"Migrating database" and the spinning wheel of death.
Nothing in log files other than the flyway startup info, even with verbose logging enabled.

We tried the following:
1) create a new DB instance (using RDS snapshot feature), with noone connected, and run against that, to make sure the issue was not locking.  Same hang.
2) running against a blank local database. This works.
3) waiting for 3 hours.  Nothing happens.
4) cutting and pasting the SQL from the migration scripts into DBeaver and running the scripts from dbeaver. This works fine.
5) retried several times on several days, always hangs for no reason with no message.

We have no way to know what's going on, and no way to debug due to the lack of logging by flyway and flyway desktop.

**Comment by Barry-RG** [comment]
Thank you for your issue. I am going to close this issue here as this Github account is only for the Open Source Flyway tool and not the Redgate Flyway Desktop application. I can see that you have also opened an [issue](https://forum.red-gate.com/discussion/90789/when-flyway-desktop-hangs-how-can-it-be-debugged-or-even-stopped) on the Redgate forum which is the appropriate location for issues like this. 
We should have a response for you there in due course.
