### ISSUE TITLE
Flyway for Mongo: SRV Record not working

### ISSUE THREAD

**Issue by yaminidhamija** [flyway/flyway#3930]
###### Which version and edition of Flyway are you using?

10.10.0 or 10.16.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin/Command-line

###### Which database are you using? (Type & version)

Atlas Mongo 

###### Which operating system are you using?

Mac

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

flyway.url = jdbc:mongodb+srv://hostname.mongodb.net/dbname
flyway.user = <username>
flyway.password = <password>

via mvn plugin: mvn flyway:flyway

###### What did you expect to see?

successful connection to Atlas Mongo DB

###### What did you see instead?
Getting this issue:
[ERROR] Message : com.mongodb.MongoConfigurationException: Failed looking up TXT record for host
[ERROR] : class javax.naming.spi.NamingManager (in module java.naming) cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to module java.naming

**Comment by yaminidhamija** [comment]
@Barry-RG Request you to please check this out

**Comment by yaminidhamija** [comment]
With Flyway CLI, getting timeout issue:
Caused by: java.sql.SQLException: com.mongodb.MongoConfigurationException: Failed looking up TXT record for host <hostname>
Caused by: com.mongodb.MongoConfigurationException: Failed looking up TXT record for host <hostname.mongodb.net>
Caused by: com.mongodb.spi.dns.DnsException: DNS error
Caused by: javax.naming.CommunicationException: DNS error [Root exception is java.net.SocketTimeoutException: Receive timed out]

PS: I am able to connect through Mongo Compass

**Comment by Barry-RG** [comment]
From the information you have provided, I do not yet have any reason to think that the Mongo integration has an issue yet.
The error seems to suggest a network issue, more specifically a DNS issue. 

1. Are Flyway CLI and Mongo Compass run from the same system?
2. Is Mongo Compass using any proxy configuration?
3. Are you able to do a command line ping or network trace to your Mongo Atlas instance?

**Comment by yaminidhamija** [comment]
@Barry-RG 
1. Yes its on same system
2. No
3. Yes, tried using Dig command

Java dns error is occuring while using maven plugin, Java Version tried is 17 and 21.
From CLI, its the timeout issue

On same terminal, it works fine also with mongosh

**Comment by JasonLuo-Redgate** [comment]
Issue reported as fixed through zendesk channel.
