### ISSUE TITLE
Unsupported Database: PostgreSql 15.7 on CloudSql (GCP)

### ISSUE THREAD

**Issue by aHint0430** [flyway/flyway#3932]
###### Which version and edition of Flyway are you using?
10.16.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
PostgreSql 15.7 on **CloudSql (GCP)**

###### Which operating system are you using?
**CloudSql**

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Trying to migrate the empty DB instance with Java API.

###### What did you expect to see?
DB migration successfully

###### What did you see instead?
Unsupported Database: PostgreSql 15.7 
<img width="878" alt="image" src="https://github.com/user-attachments/assets/7c8880a4-f4d4-4193-8ecc-b5e56f69d288">
（sorry I have to mask some info in the log as the guideline of my company)

**Comment by Barry-RG** [comment]
Hi, can we confirm that you have also included the `flyway-database-postgresql` dependency in your project?

**Comment by aHint0430** [comment]
yes, flyway-database-postgresql and flyway-core are included.

**Comment by aHint0430** [comment]
Here is what the mvn dependency shows:
<img width="945" alt="image" src="https://github.com/user-attachments/assets/998ee29c-521a-4a64-8b39-2ca6f4ef1922">

Thanks.

**Comment by aHint0430** [comment]
Hi, fyi, the issue has been fixed after I upgraded the flyway version to 10.17.0

Thanks.
