### ISSUE TITLE
Artifact for `flyway-database-cassandra` missing in Maven Central

### ISSUE THREAD

**Issue by janhicken** [flyway/flyway#3934]
###### Which version and edition of Flyway are you using?

10.17.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

As of this writing, 10.17.0 is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

PostgreSQL

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I added a dependency to `org.flywaydb:flyway-commandline:10.17.0` in my Maven project.

Resolving dependencies fails however, because the artifact `org.flywaydb:flyway-database-cassandra` is missing in Maven Central despite being a dependency of `org.flywaydb:flyway-commandline:10.17.0`.

###### What did you expect to see?

I'd expect `https://repo1.maven.org/maven2/org/flywaydb/flyway-database-cassandra/10.17.0/flyway-database-cassandra-10.17.0.pom` to be available.

###### What did you see instead?

Maven Central returns a HTTP 404.

**Comment by Barry-RG** [comment]
Apologies, This seems to have been a mistake in our maven central deployment. I will make sure this is fixed in an upcoming release.

**Comment by WilliamL-RG** [comment]
Hi, this has now been fixed and it is available for the 10.17.1 release here: https://repo1.maven.org/maven2/org/flywaydb/flyway-database-cassandra/10.17.1/flyway-database-cassandra-10.17.1.pom
