### ISSUE TITLE
flyway-commandline: jackson-databind jar in drivers/ instead of lib/

### ISSUE THREAD

**Issue by sopgreg** [flyway/flyway#3936]
###### Which version and edition of Flyway are you using?

10.17.0

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We're building our own flyway distribution which includes all our migration scripts and some other addons. For this we use the maven-assembly-plugin, in which we also include the flyway-commandline ZIP pulled from maven central but exclude all drivers, because we bring a newer version of the OJDBC driver ourselves:

```
        <dependencySet>
            <unpackOptions>
                <excludes>
                    <exclude>flyway-${flyway.version}/drivers/**</exclude>
                </excludes>
            </unpackOptions>
        </dependencySet>
        <dependencySet>
            <outputDirectory>flyway-${flyway.version}/drivers</outputDirectory>
            <includes>
                <include>com.oracle.database.jdbc:*</include>
            </includes>
        </dependencySet>
```

Starting flyway won't work this way:

```
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JavaType
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 3 more
```

The reason is, that the jackson-databind library is within the `drivers` folder, while we expected it to be in the `lib` folder

###### What did you expect to see?

jackson-databind-2.15.2 should be in lib folder

###### What did you see instead?

jackson-databind-2.15.2 is in drivers folder

![grafik](https://github.com/user-attachments/assets/89f1e050-0c8e-4ef5-a400-bc547f022c8a)

**Comment by WilliamL-RG** [comment]
Hi,
This has now been fixed in the latest release with `jackson-databind` now in the lib folder
