### ISSUE TITLE
Flyway Teams Edition upgrade required: ignoreMigrationPattern with type 'repeatable' is not supported by Flyway Community Edition

### ISSUE THREAD

**Issue by mohiniyadav** [flyway/flyway#3938]
###### Which version and edition of Flyway are you using?
Flyway 9.0.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java

###### Which database are you using? (Type & version)
MariaDb

###### Which operating system are you using?
NA

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
calling migrate()

**Comment by JasonLuo-Redgate** [comment]
Hi @mohiniyadav ,

As stated in the release notes https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine, this feature was made available in free tier of Flyway since `10.12.0`.
