### ISSUE TITLE
Classpasth Conflict Problem with Spring Boot 3.3.2 and Flyway 10.17.1 for MongoDB 7.0.12

### ISSUE THREAD

**Issue by deepakbisht** [flyway/flyway#3944]
###### Which version and edition of Flyway are you using?
flyway-database-mongodb 10.17.1
mongo-jdbc-driver 1.19.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API (Maven, Spring Boot)

###### Which database are you using? (Type & version)

MongoDB 7.0.12

###### Which operating system are you using?
MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.2</version>
    <relativePath/> 
  </parent>
  <groupId>com.testmongoflyway</groupId>
  <artifactId>migrationpoc</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>migrationpoc</name>
  <description>migrationpoc</description>
  <properties>
    <spring.boot.version>3.3.2</spring.boot.version>
  </properties>

  <dependencies>
    
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
      <version>${spring.boot.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>${spring.boot.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jdbc</artifactId>
      <version>${spring.boot.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <version>${spring.boot.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-mongodb</artifactId>
    </dependency>
    <dependency>

      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-database-mongodb</artifactId>
      <version>10.17.1</version>
      <exclusions>
        <exclusion>
          <groupId>com.github.kornilova203</groupId>
          <artifactId>mongo-jdbc-driver</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
      <dependency>
        <groupId>com.github.kornilova203</groupId>
        <artifactId>mongo-jdbc-driver</artifactId>
        <version>1.19</version>
        <scope>system</scope>
        <systemPath>${project.basedir}/lib/mongo-jdbc-standalone-1.19.jar</systemPath>
      </dependency>
    </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-maven-plugin</artifactId>
        <configuration>
          <url>jdbc:mongodb://localhost:27017/catalog</url>
          <sqlMigrationSuffixes>.js</sqlMigrationSuffixes>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

V1__schema.js

`db.chai.insert({type: "Adrak", cost: 10});`

Application.yaml

`spring:
  application:
        name: migrationpoc
  datasource:
    url: jdbc:mongodb://localhost:27017/catalog
    driver-class-name: com.dbschema.MongoJdbcDriver
  flyway:
    url: jdbc:mongodb://localhost:27017/catalog
    driver-class-name: com.dbschema.MongoJdbcDriver
    environment: "mongodb"
    fail-on-missing-locations: true
    locations: classpath:db/migration/
    sqlMigrationSuffixes:
      - ".js"
    enabled: true

server:
  port: 8089
`

###### What did you expect to see?

Script run successfully.

###### What did you see instead?

` /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.2)

2024-08-14T11:08:24.583-04:00  INFO 61637 --- [migrationpoc] [           main] c.s.m.MigrationpocApplication            : Starting MigrationpocApplication using Java 17.0.12 with PID 61637 (/Users/dbisht/Git/pdh/migrationpoc/target/classes started by dbisht in /Users/dbisht/Git/pdh/migrationpoc)
2024-08-14T11:08:24.585-04:00  INFO 61637 --- [migrationpoc] [           main] c.s.m.MigrationpocApplication            : No active profile set, falling back to 1 default profile: "default"
2024-08-14T11:08:24.937-04:00  INFO 61637 --- [migrationpoc] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8089 (http)
2024-08-14T11:08:24.941-04:00  INFO 61637 --- [migrationpoc] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-08-14T11:08:24.941-04:00  INFO 61637 --- [migrationpoc] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.26]
2024-08-14T11:08:24.956-04:00  INFO 61637 --- [migrationpoc] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-08-14T11:08:24.957-04:00  INFO 61637 --- [migrationpoc] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 342 ms
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] WARNING: The polyglot context is using an implementation that does not support runtime compilation.
The guest application code will therefore be executed in interpreted mode only.
Execution only in interpreted mode will strongly impact the guest application performance.
For more information on using GraalVM see https://www.graalvm.org/java/quickstart/.
To disable this warning the '--engine.WarnInterpreterOnly=false' option or use the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
2024-08-14T11:08:25.236-04:00  WARN 61637 --- [migrationpoc] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: null
2024-08-14T11:08:25.237-04:00  INFO 61637 --- [migrationpoc] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-08-14T11:08:25.240-04:00  WARN 61637 --- [migrationpoc] [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [MongoShell ExecutorService] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 app//com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:539)
 app//com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:396)
 app//com.oracle.truffle.api.library.DynamicDispatchLibraryGen$UncachedDispatch.dispatch(DynamicDispatchLibraryGen.java:300)
 app//com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:541)
 app//com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:396)
 app//com.oracle.truffle.polyglot.PolyglotValueDispatch$PrimitiveValue.<init>(PolyglotValueDispatch.java:1666)
 app//com.oracle.truffle.polyglot.PolyglotValueDispatch.addDefaultValue(PolyglotValueDispatch.java:1652)
 app//com.oracle.truffle.polyglot.PolyglotValueDispatch.createDefaultValues(PolyglotValueDispatch.java:1647)
 app//com.oracle.truffle.polyglot.PolyglotLanguageInstance.<init>(PolyglotLanguageInstance.java:105)
 app//com.oracle.truffle.polyglot.PolyglotLanguage.createInstance(PolyglotLanguage.java:171)
 app//com.oracle.truffle.polyglot.PolyglotSharingLayer.allocateHostLanguage(PolyglotSharingLayer.java:334)
 app//com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:574)
 app//com.oracle.truffle.polyglot.PolyglotContextImpl.createContextArray(PolyglotContextImpl.java:679)
 app//com.oracle.truffle.polyglot.PolyglotContextImpl.<init>(PolyglotContextImpl.java:516)
 app//com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1750)
 app//com.oracle.truffle.polyglot.PolyglotEngineDispatch.createContext(PolyglotEngineDispatch.java:162)
 app//org.graalvm.polyglot.Context$Builder.build(Context.java:1861)
 app//com.mongodb.mongosh.MongoShellContext.<init>(MongoShellContext.kt:14)
 app//com.mongodb.mongosh.MongoShell.<init>(MongoShell.kt:10)
 app//com.dbschema.mongo.mongosh.PrecalculatingShellHolder.lambda$submitNewShell$0(PrecalculatingShellHolder.java:31)
 app//com.dbschema.mongo.mongosh.PrecalculatingShellHolder$$Lambda$788/0x000000a00148e140.call(Unknown Source)
 java.base@17.0.12/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 java.base@17.0.12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 java.base@17.0.12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@17.0.12/java.lang.Thread.run(Thread.java:840)
2024-08-14T11:08:25.245-04:00  INFO 61637 --- [migrationpoc] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-08-14T11:08:25.251-04:00 ERROR 61637 --- [migrationpoc] [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.dbschema.mongo.MongoClientWrapper.lambda$new$3(MongoClientWrapper.java:100)

The following method did not exist:

    'com.mongodb.connection.SocketSettings$Builder com.mongodb.connection.SocketSettings$Builder.connectTimeout(int, java.util.concurrent.TimeUnit)'

The calling method's class, com.dbschema.mongo.MongoClientWrapper, was loaded from the following location:

    jar:file:/Users/dbisht/Git/pdh/migrationpoc/lib/mongo-jdbc-standalone-1.19.jar!/com/dbschema/mongo/MongoClientWrapper.class

The called method's class, com.mongodb.connection.SocketSettings$Builder, is available from the following locations:

    jar:file:/Users/dbisht/.m2/repository/org/mongodb/mongodb-driver-core/5.0.1/mongodb-driver-core-5.0.1.jar!/com/mongodb/connection/SocketSettings$Builder.class
    jar:file:/Users/dbisht/Git/pdh/migrationpoc/lib/mongo-jdbc-standalone-1.19.jar!/com/mongodb/connection/SocketSettings$Builder.class

The called method's class hierarchy was loaded from the following locations:

    com.mongodb.connection.SocketSettings.Builder: file:/Users/dbisht/.m2/repository/org/mongodb/mongodb-driver-core/5.0.1/mongodb-driver-core-5.0.1.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.dbschema.mongo.MongoClientWrapper and com.mongodb.connection.SocketSettings$Builder`

**Comment by cfinlinson-incomm** [comment]
I got `flyway-database-mongodb` to work in my Spring Boot app with the following setup:

Snippet from `pom.xml`
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.1.12</version>
    <relativePath/>
</parent>

<groupId>com.example.demo</groupId>
<artifactId>demo</artifactId>
<version>0.0.1-SNAPSHOT</version>
<name>demo</name>
<description>demo</description>

<properties>
    <flyway.version>10.21.0</flyway.version>
    <java.version>17</java.version>
</properties>

<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-mongodb</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <!-- Dependencies needed for Flyway migrations -->
    <dependency>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-core</artifactId>
        <version>${flyway.version}</version>
    </dependency>
    <!-- This dependency is in preview, so future versions may include breaking changes.
        See https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/mongodb -->
    <dependency>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-database-mongodb</artifactId>
        <version>${flyway.version}</version>
        <exclusions>
            <!-- Exclude this so it can be manually included from local jar -->
            <exclusion>
                <groupId>com.github.kornilova203</groupId>
                <artifactId>mongo-jdbc-driver</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <!-- We have to manually include this jar, since Flyway uses a JDBC driver, even though it's MongoDB. -->
    <dependency>
        <groupId>com.github.kornilova203</groupId>
        <artifactId>mongo-jdbc-driver</artifactId>
        <version>1.19</version>
        <scope>system</scope>
        <systemPath>${project.basedir}/lib/mongo-jdbc-standalone-1.19.jar</systemPath>
    </dependency>
    <!-- This is necessary because Flyway uses a JDBC driver, even though it's MongoDB.
        Without this, the Flyway initializer bean doesn't get created. -->
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-jdbc</artifactId>
    </dependency>
</dependencies>
```

Snippet from `application.yml`:
```
spring:
  application:
    name: demo
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: demo

  datasource:
    url: jdbc:mongodb://localhost:27017/demo
    driver-class-name: com.dbschema.MongoJdbcDriver
  flyway:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
    baseline-on-migrate: true
    sql-migration-suffixes: .js
```

**Comment by deepakbisht** [comment]
I was able to run it. It was due to dependency coming from flywaymongodb and starter jdbc had one common class with same method name but different return type.

Thank you for your response.
