### ISSUE TITLE
mysql关于“--”的注释问题会被识别为语法

### ISSUE THREAD

**Issue by YUKIVen** [flyway/flyway#3946]
###### Which version and edition of Flyway are you using?

10.11.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MySQL 5.7

###### Which operating system are you using?
centos

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
ERROR: Migration of schema `cfwdbinfo` to version "1.1.0.24 - insert table" failed! Please restore backups and roll back database and code!
ERROR: Migration V1.1.0_24__insert_table.sql failed
--------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=808654971) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--后续移动到ted cfwdbinfo库 ****重要****  跨租户
Location   : /svcinit/cfwdbinfo/V1.1.0_24__insert_table.sql (/svcinit/cfwdbinfo/V1.1.0_24__insert_table.sql)
Line       : 3
Statement  : --后续移动到ted cfwdbinfo库 ****重要****  跨租户

alter  table  cfw_vpc_connection ADD COLUMN  peer_appid  varchar(256) NOT NULL  DEFAULT ''

Caused by: Migration V1.1.0_24__insert_table.sql failed
--------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=808654971) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--后续移动到ted cfwdbinfo库 ****重要****  跨租户
Location   : /svcinit/cfwdbinfo/V1.1.0_24__insert_table.sql (/svcinit/cfwdbinfo/V1.1.0_24__insert_table.sql)
Line       : 3
Statement  : --后续移动到ted cfwdbinfo库 ****重要****  跨租户

alter  table  cfw_vpc_connection ADD COLUMN  peer_appid  varchar(256) NOT NULL  DEFAULT ''

Caused by: java.sql.SQLSyntaxErrorException: (conn=808654971) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--后续移动到ted cfwdbinfo库 ****重要****  跨租户
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--后续移动到ted cfwdbinfo库 ****重要****  跨租户
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--后续移动到ted cfwdbinfo库 ****重要****  跨租户

alter  table  cfw_v' at line 1
ERROR, init failed
<img width="1043" alt="企业微信截图_31686fa0-35a6-4f99-9873-11f6ae4ee08b" src="https://github.com/user-attachments/assets/7ff8738e-44c3-4aa2-a9f7-7bd5545a2b3d">

###### What did you expect to see?
为什么“--后续移动到ted cfwdbinfo库 ****重要****  跨租户” 作为注释不可以，相反的在“--”后面加个空格就不会有这个问题，例如，“-- 后续移动到ted cfwdbinfo库 ****重要****  跨租户”。 这个问题应该怎么解决？ 除了直接修改sql文件，还有其他方法吗？

**Comment by JasonLuo-Redgate** [comment]
Hi @YUKIVen ,

This error message came from MySQL, based on the document found here https://dev.mysql.com/doc/refman/8.4/en/comments.html, it mentioned ` the --  (double-dash) comment style requires the second dash to be followed by at least one whitespace`.

**Comment by YUKIVen** [comment]
你好， @JasonLuo-Redgate 
请问Flyway 的解析器可以兼容“--”的注释格式吗？ 例如我的注释格式是“--test”，这个中间并没有空格。
或者有其他方法吗？比如通过Flyway的命令行配置参数，忽略我的这个注释？ 如果修改sql文件来解决这个问题，带来的后果比较不太能接受。

谢谢！

**Comment by JasonLuo-Redgate** [comment]
Hi @YUKIVen ,
Flyway is not supposed to meddle with any content of the SQL script. The script is parsed by MySQL and error comes from MySQL, so there is little Flyway can do in this case.

**Comment by YUKIVen** [comment]
你好，@JasonLuo-Redgate
 我明白了，非常感谢！
