### ISSUE TITLE
skipExecutingMigrations is not working in OSS edition

### ISSUE THREAD

**Issue by catostrophe** [flyway/flyway#3947]
###### Which version and edition of Flyway are you using?
OSS v10.17.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
Oracle 21

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
```shell
export FLYWAY_SKIP_EXECUTING_MIGRATIONS="true"
./flyway migrate
```
or
```shell
./flyway -skipExecutingMigrations="true" migrate
```

###### What did you expect to see?
Successful run with skipped migrations and updated flyway hist table.

###### What did you see instead?
In case of using an env variable:
```
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to parse command line params.
        at org.flywaydb.core.internal.configuration.TomlUtils.toConfiguration(TomlUtils.java:100)
        at org.flywaydb.core.internal.configuration.TomlUtils.loadConfigurationFromEnvironment(TomlUtils.java:81)
        at org.flywaydb.commandline.configuration.ModernConfigurationManager.getConfiguration(ModernConfigurationManager.java:84)
        at org.flywaydb.commandline.configuration.ConfigurationManagerImpl.getConfiguration(ConfigurationManagerImpl.java:43)
        at org.flywaydb.commandline.Main.main(Main.java:108)
```

In case of passing a CLI argument: no effect.

**Comment by catostrophe** [comment]
If I run `flyway -X` I can see that the debug log shows:
```
flyway.skipExecutingMigrations -> true
```

This line is very strange:
https://github.com/flyway/flyway/blob/68538a69d1a6fbf7ebcf285badfd4c3b43b4a9ef/flyway-core/src/main/java/org/flywaydb/core/internal/command/DbMigrate.java#L251

And the reason for it is also strange.

**Comment by catostrophe** [comment]
According to the docs it should be available in the OSS edition:
https://documentation.red-gate.com/fd/skip-executing-migrations-224919747.html

**Comment by WilliamL-RG** [comment]
Hi,
When using environment variables, you need to parse in a boolean instead of a string so in this case you would do `FLYWAY_SKIP_EXECUTING_MIGRATIONS=true`.
`skipExecutingMigrations` has also been fixed for OSS and will be in the next release
