### ISSUE TITLE
Need to be able to register a migration script

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#395]
_Original author: dyo...@gmail.com (December 07, 2012 04:40:23)_

I understand flyway is designed to control all database schema migrations. However, we have an important use case that requires schema changes outside of flyway.  Our database is used to support critical, customer facing applications. When there are performance issue or timeout errors which can be resolved by simple schema changes (e.g. make column wider or add a new index),  we must make immediate changes to resolve customer impacting issues.  But we still need to track that type of changes using flyway. Can you add an option for flyway to register a script in schema_version without actually running the script?  that will help us a lot, and I know that quite few places I worked have the same needs.

Thanks,.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=382_

**Comment by axelfontaine** [comment]
Closing as checksum can be fixed using repair
