### ISSUE TITLE
Missing succesful server migration fails validation even with ignore missing

### ISSUE THREAD

**Issue by victornoel** [flyway/flyway#3951]
###### Which version and edition of Flyway are you using?

10.13.0 Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I haven't tried as it happened in an environment where it's hard to test it out (I checked the changelog and I didn't see anything about that).

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

PostgreSQL 15

###### Which operating system are you using?

Linux/Docker

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Flyway is configured with:
```java
        FluentConfiguration fc = Flyway.configure()
            .locations("classpath:migration/server")
            .outOfOrder(true)
            .ignoreMigrationPatterns(ValidatePattern.fromPattern("*:missing"));
```

In this order:
- created a java-based server migration without any checksum named `V20240829134109__Bla_Bla_Bla`
- flyway applied it successfully on the day after:
```
db=# select * from servermigration where version = '20240829134109';
 installed_rank |    version     |        description        | type |                                 script                                  | checksum | installed_by |        installed_on        | execution_time | success 
----------------+----------------+---------------------------+------+-------------------------------------------------------------------------+----------+--------------+----------------------------+----------------+---------
             25 | 20240829134109 | Bla Bla Bla               | JDBC | migration.server.V20240829134109__Bla_Bla_Bla                           |          | user         | 2024-08-30 06:01:17.703521 |           5730 | t
(1 row)
```
- removed the migration from the code base a few days after
- flyway failed the validation on the day after
```
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: 20240829134109.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:169)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:210)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:156)
```

Surprisingly, if I change the configuration of Flyway to the following, the problem disappear, even though the migration is not in the future:
```java
        FluentConfiguration fc = Flyway.configure();
        fc.locations("classpath:migration/server");
        // allow out of order migrations
        fc.outOfOrder(true);
        fc.ignoreMigrationPatterns(
            // successfully applied migrations that were removed later on
            ValidatePattern.fromPattern("*:missing"),
            // any migration that is dated in the future
            ValidatePattern.fromPattern("*:future")
        );
```

**Comment by tlamr** [comment]
We have hit the same issue after upgrade from flyway 6.x. Thanks for the workaround @victornoel

**Comment by JasonLuo-Redgate** [comment]
Hi @victornoel ,
May I know in your case whether there is no pending migration left? Because in this case, Flyway considered the newest resolved as empty, and accordingly marked any `Missing` script as `Future`. That explains why you need to add `ignoreMigrationPatterns: future`.

**Comment by victornoel** [comment]
@JasonLuo-Redgate pending means that for example, when flyway executes, we have a new migration in the codebase that needs to be applied but is not yet applied when validation runs, is that correct?

If yes, then most certainly there was a pending migration, because usually the pattern I follow is:
- I create a migration
- I deploy and it gets applied
- then I notice that it's not working exactly as I would like
- I rename the migration (change the version date basically) and fix any issue I discovered
- I deploy and I'm expecting
  - that the now missing migration is ignored
  - the new migration is applied

When using SQL-based migrations, it has worked without any issue for a long time I believe, so it seems that java-based migrations are handled differently (on purpose, or maybe not?).

**Comment by JasonLuo-Redgate** [comment]
Hi @victornoel ,

Thanks for the detailed explanation, so you mean this issue only happens for java migrations? It works as expected following the the same procedure for SQL migrations?

**Comment by victornoel** [comment]
@JasonLuo-Redgate actually I may be wrong to conclude it's only impacting Java migrations because I just remembered right now that I already had `*:future` in my `ignoreMigrationPatterns` when applying SQL migrations, so actually maybe the same problem exists there ^^

**Comment by JasonLuo-Redgate** [comment]
Hi @victornoel ,

I followed a similar procedure as described above, but I wasn't able to reproduce the issue:

![image](https://github.com/user-attachments/assets/d4b40356-7043-4efb-9e52-5a839e6f1398)

From the above screenshot we can see, deleted migrations (both SQL and Java) shown as `Missing` as expected, new migrations (both SQL and Java) shown as `Pending` as expected. 

Could you run `info` before deploying the new migration to see whether it's the same?

**Comment by victornoel** [comment]
Hi @JasonLuo-Redgate, sorry for the delay. I finally got the time to try to reproduce and I couldn't either reproduce it.

I suspect this was caused by some kind of broken state in our db or something like that that got resolved in a strange way. All in all, I guess we can close this.

Thank you for investigating and for your patience :)
