### ISSUE TITLE
Flyway public key download site

### ISSUE THREAD

**Issue by oallauddin** [flyway/flyway#3953]
###### Which version and edition of Flyway are you using?
10.17.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
PostgreSQL

###### Which operating system are you using?
Linux

I want to verify the signature of downloaded files. 
https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.17.3/ 
Can I download the public key from a website?  
I could not find guidance on verifying signatures in the Flyway documentation.

**Comment by JasonLuo-Redgate** [comment]
Hi @oallauddin ,

Currently this is not an implemented mechanism yet.
