### ISSUE TITLE
Issue with the Latest Alpine Image

### ISSUE THREAD

**Issue by Ruchira-R** [flyway/flyway#3955]
###### Which version and edition of Flyway are you using?
latest-alpine image

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Postgresql-14

###### Which operating system are you using?
Alpine

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

The flyway migrate/repair command is broken in the latest push -> flyway/flyway:latest-alpine.

XML_SetReparseDeferralEnabled: symbol not found is the error that I'm seeing.

I think this is something related to python3.11 changes. Please take a look

**Comment by Barry-RG** [comment]
Could you please provide us with more logs to help locate the source of this issue? For example, running your commands with the `-X` debug option and providing us with the stacktrace information

**Comment by JasonLuo-Redgate** [comment]
Just to follow up — does this ticket still need attention?

**Comment by Ruchira-R** [comment]
Hmm, maybe it is because of the STS Token that is received(for the password - would've contained spurious characters), which might not be related to flyway. 

Closing this, will reopen it if I see any issue.
