### ISSUE TITLE
MergeUtils is using some Guava API and Guava is optional

### ISSUE THREAD

**Issue by gsmet** [flyway/flyway#3967]
###### Which version and edition of Flyway are you using?

10.20.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This code is still present in `main` (but not sure `main` is actually the latest developments).

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### What did you see instead?

We stumbled upon this in the Quarkus project (https://github.com/quarkusio/quarkus/pull/43921) as we are compiling Flyway to a native executable and GraalVM checks that the classpath is consistent.

`MergeUtils` is using `Sets.union()` which comes from Guava and Guava is an optional dependency brought by Google Cloud Storage so its usage should be avoided. Or a non-optional dependency added but I'm not sure it's worth adding the whole Guava for this relatively simple use case.

See:
https://github.com/flyway/flyway/blob/a66a1a37f9c1b1d9ef8fd7fb2137ff2678d4779b/flyway-core/src/main/java/org/flywaydb/core/internal/util/MergeUtils.java#L79

I would create a PR but I have no idea how you prefer to fix it.

**Comment by Barry-RG** [comment]
Thank you for raising this issue, this should be resolved in our next release

**Comment by gsmet** [comment]
@Barry-RG I would also appreciate a look at https://github.com/flyway/flyway/pull/3968 when someone on your side has time. This is also a bit problematic for Quarkus (but less blocking than this one). Thanks a lot!

**Comment by JasonLuo-Redgate** [comment]
Hi @gsmet ,
The fix has been included the latest release 10.20.1 (https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine), hence closing this ticket. 
Thanks again for reporting this issue.
