### ISSUE TITLE
environment option not working.

### ISSUE THREAD

**Issue by ronald-fenner** [flyway/flyway#3971]
###### Which version and edition of Flyway are you using?
Flyway OSS 10.20.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Docker CLI 10.20.1-alpine

###### Which database are you using? (Type & version)
Mysql

###### Which operating system are you using?
Moc OS 14.6.1 (23G93)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I tried to run the baseline command passing -environment and also tried flyway_environment and its not using it

###### What did you expect to see?
that it would select the specified environment and use that config

###### What did you see instead?
```
DEBUG: Java Version: 17.0.13+11
DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /root/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Using configuration:
DEBUG: Multiple databases found that handle url 'jdbc:mysql://docker.host.internal:3310/lion_apps_development': OceanBase,TiDB,MySQL
DEBUG: [environments.development] ->
[environments.local] ->
[environments.production] ->
baselineOnMigrate -> true
flyway.locations -> filesystem:/flyway/sql
flyway.password -> ********
flyway.user -> admin
url -> jdbc:mysql://docker.host.internal:3310/lion_apps_development
validateMigrationNaming -> true

DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@de3a06f ...
DEBUG: Unable to resolve location classpath:db/callback.
Flyway OSS Edition 10.20.1 by Redgate

See release notes here: https://rd.gt/416ObMi
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
	at org.flywaydb.core.internal.configuration.ConfigurationValidator.validate(ConfigurationValidator.java:45)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:120)
	at org.flywaydb.core.Flyway.baseline(Flyway.java:391)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:287)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:204)
	at org.flywaydb.commandline.Main.main(Main.java:127)
```

Note it looks like it used the last environment it encountered instead of the local environment i was trying to select.
My Conf file looks like
```
[environments.local]
url=jdbc:mysql://lion-apps-mysql:3306/lion_apps
baselineOnMigrate=true
validateMigrationNaming=true

[environments.production]
url=jdbc:mysql://docker.host.internal:3310/lion_apps
baselineOnMigrate=true
validateMigrationNaming=true

[environments.development]
url=jdbc:mysql://docker.host.internal:3310/lion_apps_development
baselineOnMigrate=true
validateMigrationNaming=true
```

I'm actually using a wrapper script to execute the docker run command. That looks like

```
docker run --rm -v "${TOP}/flyway/sql:/flyway/sql" -v "${TOP}/flyway/conf:/flyway/conf" \
  -e FLYWAY_USER="${MASTER_USER}" -e FLYWAY_PASSWORD="${MASTER_PASS}" -e flyway_environment="${ENV}" \
  "${FLYWAY_IMAGE}" "$@"
```

**Comment by JasonLuo-Redgate** [comment]
Hi @ronald-fenner ,

From the debug log, it looks like you are using a `flyway.conf` file and using toml configuration format. `conf` file and `toml` file are two distinct configuration files. 

If you want to use multiple environments, I think your choice shall be `toml`. More details could be found here https://documentation.red-gate.com/fd/toml-configuration-file-224919679.html

**Comment by ronald-fenner** [comment]
Ahh I was looking at an example use from another team that didn't use environments and had a .conf extension. I missed that the sample from the CLI download had a different file extension.
