### ISSUE TITLE
Flyway ignores applied checksums when reporting pending repeatable migrations

### ISSUE THREAD

**Issue by mielecmichal** [flyway/flyway#3972]
###### Which version and edition of Flyway are you using?
10.20.0 Community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Postgres 16.3

###### Which operating system are you using?
Ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I bundle all my migration files into the fat-jar Java application. In the application, I have a check reporting pending Flyway migrations as below. The problem occurs when I edit repeatable migrations (prefixed with R) and deploy a new version of my app.
```java
  private boolean hasPendingFlywayMigrations(Flyway flyway) {
    MigrationInfoService info = flyway.info();
    return info.pending().length > 0;
  }
```

###### What did you expect to see?
During deployment of my app with modified repeatable migration, I expect to see pending repeatable migrations in the new instance of my app and no pending repeatable migrations in the old instance of my app. I expect Flyway in the old instance to realize that the repeatable migration checksum is already present in the applied migration list. Instead, it looks, Flyway only compares the latest checksums. 

###### What did you see instead?
I see both new and old instances reporting pending repeatable migrations.

**Comment by JasonLuo-Redgate** [comment]
Hi @mielecmichal ,

To better understand this issue, just to confirm that you mean you have two flyway instances? Are they sharing the same configuration?

**Comment by mielecmichaltruewealth** [comment]
Hi @JasonLuo-Redgate Yes, I have two flyway instances in two application instances and yes they have the same config values. When a new instance applies repeatable migration, the older instance with previous migration version starts to report pending migration. As a workaround, I had to implement checksum comparison myself, but I would expect such a logic in Flyway.

```java
  public boolean isAnyMigrationNotApplied(MigrationInfoService info) {
    var appliedChecksums = seq(info.applied()).map(MigrationInfo::getChecksum).toSet();

    var versionedAndRepeatable = seq(info.pending()).partition(MigrationInfo::isVersioned);
    var versionedPending = versionedAndRepeatable.v1.toList();
    var repeatablePending =
        versionedAndRepeatable.v2.filter(r -> !appliedChecksums.contains(r.getChecksum())).toList();
    var anyMigrationPending = !versionedPending.isEmpty() || !repeatablePending.isEmpty();
    if (anyMigrationPending) {
      log.info(
          "Pending migrations. Versioned: {} Repeatable: {}", versionedPending, repeatablePending);
    }
    return anyMigrationPending;
  }
```

**Comment by mielecmichal** [comment]
Hi @JasonLuo-Redgate Yes, I have two flyway instances running in two application instances and yes they share the same config values. When a new instance applies repeatable migration, the older instance with previous migration version starts to report pending migration. As a workaround, I had to implement checksum comparison myself, but I would expect such a logic in Flyway.

In other words, for each repeatable migration, we should check first if its checksum is not already on the applied list before marking it as pending.

```java
  public boolean isAnyMigrationNotApplied(MigrationInfoService info) {
    var appliedChecksums = seq(info.applied()).map(MigrationInfo::getChecksum).toSet();

    var versionedAndRepeatable = seq(info.pending()).partition(MigrationInfo::isVersioned);
    var versionedPending = versionedAndRepeatable.v1.toList();
    var repeatablePending =
        versionedAndRepeatable.v2.filter(r -> !appliedChecksums.contains(r.getChecksum())).toList();
    var anyMigrationPending = !versionedPending.isEmpty() || !repeatablePending.isEmpty();
    if (anyMigrationPending) {
      log.info(
          "Pending migrations. Versioned: {} Repeatable: {}", versionedPending, repeatablePending);
    }
    return anyMigrationPending;
  }
```

**Comment by JasonLuo-Redgate** [comment]
Hi @mielecmichal ,

Based on my understanding, although there are two Flyway instances, they both read from a single Schema History Table. Essentially, this means there’s no differentiation between the new and old instances.

**Comment by mielecmichal** [comment]
@JasonLuo-Redgate Let me be more precise. They both connect to the same database and have the same config options. The only difference is the new instance has a newer repeatable migration script.

Let me give you an example:
Old instance has migration `R0001_some_name.sql` in **revision 1** which is applied. I deploy a new instance with `R0001_some_name.sql` in **revision 2**, and it's being applied too. Then the old instance reports `R0001_some_name.sql` in revision 1 as pending in the old instance. This is incorrect as `R0001_some_name.sql` in revision 1 is already applied, and its checksum is already present in the schema history.

Please let me know if there is still something unclear in the above scenario.

**Comment by JasonLuo-Redgate** [comment]
Hi @mielecmichal ,

Flyway tracks the checksum of Repeatable migrations in its internal Schema History Table. While we have two flyway instances here, they are using a single Schema History Table. That's why there is actually no differentiation between the new and old instances. They are effectively the same. 

I think the key misunderstanding here is that Repeatable checksum is tracked by Schema History Table, not by individual flyway instances.

**Comment by mielecmichal** [comment]
>I think the key misunderstanding here is that Repeatable checksum is tracked by Schema History Table, not by individual flyway instances.
I see repeatable migrations tracked by the schema history table. I also see their checksums in the schema history table. Are you sure your statement is correct?

>As long as the checksum of a repeatable migration changed compared to the previous one, flyway will run it.
Flyway running migrations is perfectly fine. What is not fine, IMO, is Flyway reporting already applied migration as pending in the older instance.

**Comment by JasonLuo-Redgate** [comment]
Hi @mielecmichal ,

To better rephrase: Individual Flyway instances, as long as they rely on the same Schema History Table, track Repeatable migrations collectively rather than separately.

Based on the document here https://documentation.red-gate.com/fd/migrations-184127470.html Repeatable migrations are (re-)applied every time their checksum changes.

**Comment by JasonLuo-Redgate** [comment]
This is because it's checksum revision 1 changed compared to the previous record which is revision 2.  Flyway will consider it as a new one to run and mark it as pending. 

Again, Repeatable migrations are (re-)applied whenever their checksum changes, regardless of their presence in the Schema History Table. The key factor is whether the checksum differs from the previous record.
