### ISSUE TITLE
Documentation how to use the flyway-plugin with Oracle after 9.18.0

### ISSUE THREAD

**Issue by lkuendig** [flyway/flyway#3973]
###### Which version and edition of Flyway are you using?
9.22.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using? (Type & version)
Oracle (com.oracle:ojdbc8:19.3.0.0.0)

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
As stated in the release notes [Flyway 9.19.0 (2023-05-23)](https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html) something has changed for oracle. The link provided https://documentation.red-gate.com/fd/oracle-184127602.html returns a 404. Also I cannot find anything useful/working in https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/oracle-database.

When I just update the flyway plugin version I get the error "No database found to handle".

###### What did you expect to see?
The correct plugin/dependency I have to use for oracle.

###### What did you see instead?
Nothing useful/working

**Comment by piers-williams** [comment]
I believe that you'll need the following dependency to use Oracle database with Flyway:

```xml
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-database-oracle</artifactId>
    <version>9.22.3</version>
    <scope>runtime</scope>
</dependency>
```

**Comment by lkuendig** [comment]
thx it worked. for gradle use:

```
buildscript {
    repositories { ... }
    dependencies {
        classpath 'org.flywaydb:flyway-database-oracle:9.22.3'
    }
}
```
