### ISSUE TITLE
How to add some SQL file name judgments on the basis of SqlMigrationResolver？

### ISSUE THREAD

**Issue by designlee** [flyway/flyway#3977]
###### Which version and edition of Flyway are you using?

7.15.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
java API

###### Which database are you using? (Type & version)
mysql

###### Which operating system are you using?
centos

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Execute different SQL in different environments, such as dev, test, prod

**Comment by WilliamL-RG** [comment]
Hello, unfortunately we no longer support version 7.15.0. Please update to the latest version of Flyway which includes environments and TOML configuration. These will enable you to specify a different location of your SQL files per environment. You can find more about that here: https://documentation.red-gate.com/flyway/flyway-cli-and-api/concepts/environment-overrides

**Comment by designlee** [comment]
ok,thanks for you response.
