### ISSUE TITLE
Upgrade `com.h2database:h2` to version 2.3.232

### ISSUE THREAD

**Issue by twwwt** [flyway/flyway#3978]
###### Which version and edition of Flyway are you using?
10.20.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Not relevant, but Java API.

###### Which database are you using? (Type & version)
H2

###### Which operating system are you using?
Not relevant, but Mac OS 15.1.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run Flyway info.

###### What did you expect to see?
Absence of a warning message.

###### What did you see instead?
The following warning on the console:
```
WARN  o.f.c.i.database.base.Database - Flyway upgrade recommended: H2 2.3.232 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.224.
```

Background: We are using version 2.3.232 of the H2 JDBC driver `com.h2database:h2` in our software.

**Comment by Barry-RG** [comment]
Updated in 10.21.0

**Comment by twwwt** [comment]
I have upgraded to 10.21.0. Strangely enough, I'm still getting the exact same warning on the console. I have double-checked the class path to make sure that flyway-core:10.21.0 and com.h2database:h2:2.3.232 is contained and it is not polluted by an older version. Anything else that I could do wrong? Or could it be that the release of Flyway needs something more to be done?

**Comment by twwwt** [comment]
I think I have found it: https://github.com/flyway/flyway/blob/2dbbab3e138519b8c658d80add3bd93427561403/flyway-core/src/main/java/org/flywaydb/core/internal/database/h2/H2Database.java#L109
