### ISSUE TITLE
Matrix of Flyway version against database version that was fully tests 

### ISSUE THREAD

**Issue by taircohen94** [flyway/flyway#3980]
Can we see a matrix that indicated which flyway version was fully tested against the DB version?
This is not indicates which flyway version tested it - https://documentation.red-gate.com/fd/database-version-support-143754067.html

###### Which version and edition of Flyway are you using?
```
      <dependency>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-core</artifactId>
        <version>6.5.7</version>
      </dependency>
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using? (Type & version)

Postgres Aurora 16.4 with:
```
      <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>42.3.7</version>
      </dependency>
```

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

`logger=internal.database.base.Database Flyway upgrade recommended: PostgreSQL 16.4 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 12.   `

###### What did you expect to see?

Can we see a matrix that indicated which flyway version was fully tested against the DB version?

###### What did you see instead?

https://documentation.red-gate.com/fd/database-version-support-143754067.html

**Comment by piers-williams** [comment]
Hi, We wouldn't be able to produce a matrix like that for every version of Flyway, now or in the past.

In your case, it may help to upgrade Flyway's version to latest in order to have the proper support for newer versions of PostgreSQL such as 16.4

**Comment by alistair-RG** [comment]
I'm going to close this now. We don't have this information directly to hand although it does exist in the codebase should you wish to look back over changes to the postgres driver and correlate them to releases ...
https://github.com/flyway/flyway/blob/c9218c6b67cc3fd53d16ea58094903e915dfc100/flyway-database/flyway-database-postgresql/src/main/java/org/flywaydb/database/postgresql/PostgreSQLDatabase.java#L52
