### ISSUE TITLE
Extra `end; $$;` causes versioned script to not be rolled back despite flyway saying it was

### ISSUE THREAD

**Issue by mor-lehr-deel** [flyway/flyway#3990]
###### Which version and edition of Flyway are you using?
Flyway OSS Edition 10.11.0 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes, reproduced on 11.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)
postgres 15.4, 15.6

###### Which operating system are you using?
tested on both linux and macos

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
manually ran this script on my DB:
```
CREATE SCHEMA mor;
CREATE TABLE mor.test(id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY, txt text);
```
flyway.conf:
```
flyway.schemas=mor
flyway.connectRetries=1
flyway.createSchemas=false
flyway.baselineVersion=2024.01.01.01
flyway.baselineOnMigrate=true
```

`V2024.12.04.01__test.sql` (note the extra `END; $$`):
```
DO $$
BEGIN
    INSERT INTO test (txt) values ('abc');
END; $$;
END; $$;
```

###### What did you expect to see?
The versioned script being rolled back due to the syntax error - like with any other syntax error. 

###### What did you see instead?
the error message says the script was rolled back - but it wasn't - the value was inserted to the table.
if I replace the 2nd `END; $$;` with any other syntax error - the script is being rolled back successfully

```
$ > flyway -configFiles=./flyway.conf -locations=filesystem:./ -url=jdbc:postgresql://localhost:5432/postgres -user=someuser migrate
Database password:
WARNING: Interactive prompt behavior is deprecated and will be removed in a future release - please consider alternatives like secrets management tools or environment variables
Flyway OSS Edition 10.11.0 by Redgate

See release notes here: https://rd.gt/416ObMi
Database: jdbc:postgresql://localhost:5432/deel (PostgreSQL 15.6)
Successfully validated 1 migration (execution time 00:00.056s)
Current version of schema "mor": << Empty Schema >>
Migrating schema "mor" to version "2024.12.04.01 - test"
ERROR: Migration of schema "mor" to version "2024.12.04.01 - test" failed! Changes successfully rolled back.
ERROR: Migration V2024.12.04.01__test.sql failed
-----------------------------------------
SQL State  : 42601
Error Code : 0
Message    : ERROR: unterminated dollar-quoted string at or near "$$;"
  Position: 1
Location   : ./V2024.12.04.01__test.sql (/Users/morlehr/flyway_commit/./V2024.12.04.01__test.sql)
Line       : 5
Statement  : $$;

Caused by: Migration V2024.12.04.01__test.sql failed
-----------------------------------------
SQL State  : 42601
Error Code : 0
Message    : ERROR: unterminated dollar-quoted string at or near "$$;"
  Position: 1
Location   : ./V2024.12.04.01__test.sql (/Users/morlehr/flyway_commit/./V2024.12.04.01__test.sql)
Line       : 5
Statement  : $$;

Caused by: org.postgresql.util.PSQLException: ERROR: unterminated dollar-quoted string at or near "$$;"
  Position: 1

```
```
postgres=# select * from mor.test;
 id | txt
----+-----
 1 | abc
```

**Comment by mor-lehr-deel** [comment]
bump. this seems like a bug in flyway, would appreciate if someone can take a look.

**Comment by JasonLuo-Redgate** [comment]
Hi @mor-lehr-deel ,

After some investigation, I think the issue lies in the additional statement `END;`
Based the documentation here https://www.postgresql.org/docs/current/sql-end.html#:~:text=END%20commits%20the%20current%20transaction,that%20is%20equivalent%20to%20COMMIT%20. 
**END commits the current transaction** 

This means this additional statement triggered a commit action, which broken Flyway's rollback action.

**Comment by mor-lehr-deel** [comment]
Thanks for checking and reference, it makes sense. 
One more postgres extension of SQL one needs to be aware of / careful with.
