### ISSUE TITLE
Documentation and help incorrect for 'generate' command in Flyway v11.0.1.

### ISSUE THREAD

**Issue by Phil-Factor** [flyway/flyway#3999]
###### Which version and edition of Flyway are you using?
11.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

CLI

###### Which database are you using? (Type & version)
SQL Server

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Tried to use the generate command with a named diff artifact. I used the examples provided and none worked In the end I discovewred that the version of Flyway I was using said that each command contained the generate. prefix. In fact it rejected this prefix and instead used the basic key 
e.g. -generate.description  didnt work but description did 
      -generate.artifactFilename didn't work but -artifactFilename did
-generate.location didn't work but -location did

The help txt is...
Configuration parameters: (Format: -key=value)
    generate.target             The target to generate the script for, must be either diff.source or diff.target fr
om flyway diff. Uses initial target if unspecified
    generate.changes            A comma seperated list of change ids. If unspecified, all changes will be used.
                                May specify - to read changes from stdin
    generate.types              Comma seperated list of types of script to generate.
                                Valid values: versioned|undo|baseline Default: versioned
    generate.version            The version part of the migration name.
                                If unspecified this will be calculated to either the next migration version if a ve
rsioned migration is specified, or the current version otherwise
    generate.description        The description part of the migration name
    generate.baselineFilename   The filename (or full path) to use for the generated baseline migration. Mutually e
xclusive with description & version
    generate.versionedFilename  The filename (or full path) to use for the generated versioned migration. Mutually 
exclusive with description & version
    generate.undoFilename       The filename (or full path) to use for the generated undo migration. Mutually exclu
sive with description & version
    generate.location           The location to generate the migration to
    generate.artifactFilename   The location of the diff artifact to apply to the target.
                                Defaults: diff.artifactFilename, %temp%/flyway.artifact.diff
    generate.force              If the migration script already exists, overwrite it. Default: false
    generate.timestamp          Add a timestamp to the calculated version if one is not already present.
                                Valid values: always|auto|never Default: auto
                                

###### What did you expect to see?

tried to run the examples

###### What did you see instead?
lots of errors

Flyway : ERROR: Invalid flag: -generate
At line:1 char:1
+ Flyway generate -generate.artifactFilename="PubsArtefact.diff"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Invalid flag: -generate:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by IvoMiller** [comment]
Hi. The help is actually strictly correct, though we might consider updating it anyway. I suspect that the error you are getting is because the `.` in the names needs escaping in PowerShell (but not in bash or windows command prompt).
The working behaviour you are observing is due to namespace short-circuiting, see [here](https://documentation.red-gate.com/flyway/flyway-cli-and-api/concepts/namespaces).

**Comment by Phil-Factor** [comment]
Yes, it looks like PowerShell is getting thrown by the dotted key in the parameter.
if I use the syntax ...
Flyway generate '-generate.description="GeneratedBuildScript"'  '-generate.artifactFilename="PubsArtefact.diff"'
... then it works. Also if I 'splat' the commands ...

$Gen=@(
 '-generate.description=GeneratedBuildScript',
 '-generate.artifactFilename=PubsArtefact.diff'
)
Flyway generate $Gen
... then that works. In all my work so far, I'd been splatting arrays of parameters, which don't suffer the same problem. Because the generate command  had so few parameters it seemed like over-engineering to use arrays of parameters 

What threw me originally was that it worked when I left out the 'generate.' prefix, and also that the examples in the documentation didn't mention the general requirement for escaping the dot in PowerShell.  Why not just leave out the requirement  for the prefix? It seems to serve no useful purpose. complicates life for the users, and I suspect it is being ignored at the moment anyway

**Comment by IvoMiller** [comment]
> Yes, it looks like PowerShell is getting thrown by the dotted key in the parameter. if I use the syntax ... Flyway generate '-generate.description="GeneratedBuildScript"' '-generate.artifactFilename="PubsArtefact.diff"' ... then it works. Also if I 'splat' the commands ...
> 
> $Gen=@( '-generate.description=GeneratedBuildScript', '-generate.artifactFilename=PubsArtefact.diff' ) Flyway generate $Gen ... then that works. In all my work so far, I'd been splatting arrays of parameters, which don't suffer the same problem. Because the generate command had so few parameters it seemed like over-engineering to use arrays of parameters
> 
> What threw me originally was that it worked when I left out the 'generate.' prefix, and also that the examples in the documentation didn't mention the general requirement for escaping the dot in PowerShell. Why not just leave out the requirement for the prefix? It seems to serve no useful purpose. complicates life for the users, and I suspect it is being ignored at the moment anyway

As mentioned, the prefix isn't required. It was initially, before we fully released the new verbs, but it is completely optional when invoking the verbs in isolation like this.
The reason the prefixes need to exist at all is:
- verb chaining; you can invoke multiple verbs in one line and they could have arguments with the same name but different prefix (see examples in the namespace short-circuiting documentation I linked earlier)
- flyway has name associations between command line parameters and config file settings and the config file settings need to be namespaced, both to prevent collisions of names and to give some order/readability to the config file

**Comment by Phil-Factor** [comment]
Very helpful. Yes, once chaining is better known by Flyway users, it makes sense to be able to spell out the correct namespace for ambiguous parameters. For the time being, it makes sense to indicate where a published example won't work in PowerShell. I'll makes sure that all parameters to flyway are cast as strings.
