### ISSUE TITLE
New task to generate a new migration

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#400]
_Original author: apsh...@gmail.com (December 17, 2012 03:10:38)_

Would be great to have a command/task that generates a new migration file. For example, in our projects we use this version scheme:

```
&lt;app-version&gt;.&lt;migrate-version&gt;
```

I'd like to have a command that knows the latest version and can generate a new empty migration. So given a migration like so:

```
V1.1.0.5__add_category.sql
```

If I type a command like:

```
$ ant new-migration add image to category
```

It would create this migration:

```
V1.1.0.6__add_image_to_category.sql
```

Obviously it would need to accept options for whether to create a Java vs. SQL migration, and the version number format would possibly need to be configurable.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=388_

**Comment by nafg** [comment]
@regis-leray in sbt at least, 
```
> show flywayLocations
[info] WrappedArray(classpath:db/migration)
```

**Comment by shapowang** [comment]
+1 I want this feature too, pleassssssssssssse
