### ISSUE TITLE
Directory for flyway properties file

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#413]
_Original author: dyo...@gmail.com (December 26, 2012 21:41:16)_

looks like flyway finds the properties file in the conf directory.  But when I specify a custom properties file on the command line (-configFile), the tool looks in conf's parent directory.

Is it possible to make the tool look in the conf directory for custom properties file so we simply run,
flyway.sh -configFile=&lt;custome file&gt; info
rather than,
flyway.sh -configFile=conf/&lt;custom file&gt; info

We could create symlinks in the parent directory to point to what's in conf.  But having the tool look in a consistent location seems to be cleaner.

Thanks.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=402_

**Comment by KIC** [comment]
Actually this is quite limiting as this does not allow to share migration.properties between toolings as the `locations` are different on absolute path level. There should definitely be an option like:

```
flyway.locations=filesystem-realative-to-properties:/schema-a/
```

so all your tests, compiles and container builds can share the same properties living in different folders of your project.
