### ISSUE TITLE
could password be encrypted in the properties file?

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#416]
_Original author: dyo...@gmail.com (January 03, 2013 01:20:43)_

I'm using flyway to manage my schema changes.  But having clear text password saved in the properties file violates our security policy.  Could the encryption feature be added in flyway to allow us store encrypted password instead?

Thanks.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=405_

**Comment by andrijaperovic** [comment]
could you share the command line tool which works with flyway to pass the encrypted properties? is this something which is distributed as part of flyway? @axelfontaine

**Comment by shorif2000** [comment]
how do you pass in encrypted password
