### ISSUE TITLE
Rollback of a whole migration

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#428]
_Original author: raphael....@googlemail.com (January 21, 2013 13:49:09)_

Dear all,

assume a migration is performed in two steps, i.e. v1 -&gt; v2 -&gt; v3. If the second migration step (v2 -&gt; v3) fails, it is rolled back (as far as possible) and the database remains in v2.

However, it is often useful to roll back the whole migration (as far as possible again) to fall back to the very initial state before the migration (v1 in this case). A respective configuration option would be desired.

As far as I can see, the reason for the present behavior is that the whole migration is performed within a transaction (class com.googlecode.flyway.core.migration.DbMigrator, lines 134-177), and each migration is additionally performed within an inner transaction (class com.googlecode.flyway.core.migration.DbMigrator, lines 245-248). Thus, committing the whole (outer) transaction is no more possible after the first inner transaction has been processed successfully.

As a simple solution, I propose a configuration setting to avoid these inner transactions. This should provide the desired rollback functionality.

Best regards
Raphael

_Original issue: http://code.google.com/p/flyway/issues/detail?id=420_

**Comment by yasserg** [comment]
+1

**Comment by janeklb** [comment]
+1 (also see https://github.com/flyway/flyway/issues/181 which seems to be a duplicate of this issue)
