### ISSUE TITLE
Actian Ingres support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#429]
_Original author: tero.kes...@gmail.com (January 21, 2013 14:21:17)_

http://en.wikipedia.org/wiki/Ingres_(database)

Free community edition downloadable from:
http://www.actian.com/downloads/ingres#community

_Original issue: http://code.google.com/p/flyway/issues/detail?id=421_

**Comment by kentoj** [comment]
It looks like nobody is working on this pull request. Would you accept it if I submitted it? I know Ingres isn't widely supported by many tools. I would like to contribute this if nobody else is going to work on it.

**Comment by axelfontaine** [comment]
Hi Kentoj,

sure!

Cheers
Axel

**Comment by bolke01** [comment]
There has been some work on this area - difficulties with Gradle were reported earlier this year which prevented progress.

The support for Ingres is part of a larger support request for the Ingres, Vector , Matrix , PSQL databases.

I would be happy to share my work and help now that I can get the fly-way core to build.

Regards
Keith Bolam
Actian
Skype: keith bolam
Phone: +44(0)7501467004

On 22 Sep 2015, at 21:24, "Axel Fontaine" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Kentoj,

sure!

Cheers
Axel

-

**Comment by alextercete** [comment]
Closing due to lack of interest.
