### ISSUE TITLE
Support for anonymous blocks in postgresql

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#434]
_Original author: giorgio....@bitnic.it (February 05, 2013 14:59:06)_

I recently run into an issue where flyway didn't seem to understand a postgres DO statement.

The issue itself seems very similar to 144, as it was caused by flyway not understanding double-dollar strings.

If I got the changeset right, the fix for 144 seem to be specific for functions, but in reality double-dollar strings can be used everywhere in postgres.

Eg:
    select $$helo world$$;
    select $X$hello world$X$;

If at all possible, supporting dollar-quoted strings directly in the parser could more elegantly resolve both this issue and 144.

See also:
http://www.postgresql.org/docs/9.2/static/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING
http://www.postgresql.org/docs/9.2/static/sql-do.html
http://code.google.com/p/flyway/issues/detail?id=144
http://code.google.com/p/flyway/source/detail?r=50ab1e2bfa9e

PS: A workaround for this issue is to just use normal strings in DO statements – ie:

```
do '
declare
    ...
begin
    ...
end';
```

(of course this impies one has to double-escape any quotes in the DO body)

_Original issue: http://code.google.com/p/flyway/issues/detail?id=427_

**Comment by pdunauskas** [comment]
this case is closed as implemented, or still flyway does not supports Postgres anonymous code blocks? @axelfontaine
