### ISSUE TITLE
H2 breaks when DATABASE_TO_UPPER=FALSE

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#436]
_Original author: agatti...@gmail.com (February 08, 2013 12:43:49)_

When connecting to H2 with URL: jdbc:h2:mem:test;DATABASE_TO_UPPER=FALSE

Caused by: org.h2.jdbc.JdbcSQLException: Schema &quot;information_schema&quot; not found; SQL statement:
SELECT TABLE_NAME FROM information_schema.TABLEs WHERE TABLE_schema = ? AND TABLE_TYPE = 'TABLE' [90079-170]

To fix, replace &quot;information_schema&quot; with &quot;INFORMATION_SCHEMA&quot; in com.googlecode.flyway.core.dbsupport.h2.H2DbSupport

Using version 2.0.3.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=430_

**Comment by lalili** [comment]
I still see this problem in 1.4.193
I'm working with the following setting:
`jdbc:h2:mem:DATABASE;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;`
