### ISSUE TITLE
Firebird database support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#441]
_Original author: fabio.vi...@gmail.com (February 16, 2013 17:14:28)_

Hi,

I would propose a new feature that would allow flyway to act also against Firebird databases.

I realize that this might be a somewhat niche feature, so feel free to shoot this down if you don't agree.

Btw, awesome product!

_Original issue: http://code.google.com/p/flyway/issues/detail?id=435_

**Comment by pjio** [comment]
+1

**Comment by keitarobr** [comment]
+1

**Comment by evandroamparo** [comment]
+1

**Comment by kumbayainc** [comment]
+1

**Comment by keitarobr** [comment]
+1

**Comment by rodrigonunz** [comment]
+1

**Comment by zanseb** [comment]
+1

**Comment by claudio-goncalves** [comment]
+1

**Comment by HonzaL** [comment]
+1

**Comment by CodeShane** [comment]
+1

**Comment by andrevanzuydam** [comment]
Please test
https://github.com/andrevanzuydam/flyway

**Comment by lvthillo** [comment]
+ 1

**Comment by gsdefender** [comment]
+1

**Comment by IvoSestren** [comment]
+1

**Comment by evandroamparo** [comment]
I voted +1 two years ago. Using MyBatis Migrations now. 😔
Anyway, thanks for the code!
