### ISSUE TITLE
PostgreSQL access over SSL

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#446]
_Original author: oyvin...@gmail.com (March 03, 2013 23:13:51)_

Hi,
currently AFAIK there is no way to connect to a Postgresql database using SSL with flyway. This is currently a requirement for me, and I was wondering whether it would be possible to add support for this.

It should be as simple as adding a parameter &quot;ssl=true&quot; in the JDBC connection string.

An example can be found at
http://jdbc.postgresql.org/documentation/80/connect.html
JDBC URL example:
jdbc:postgresql://localhost/test?user=fred&amp;password=secret&amp;ssl=true

Would be great if you could allow for this. What would probably be even better is if you could allow specifying any arbitrary parameter in the JDBC URL.

I'm currently using the commandline tool, but the same applies probably applies everywhere

_Original issue: http://code.google.com/p/flyway/issues/detail?id=440_

**Comment by apastel** [comment]
When specifying `ssl=true` in flyway.conf and leaving the user and password blank, how do you configure the path to the PKI certificate used for authentication to the Postgres database?

**Comment by benny-medflyt** [comment]
You can append this to the jdbc url:

`?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory`

**Comment by apastel** [comment]
Wouldn't that essentially turn off the SSL validation?

https://jdbc.postgresql.org/documentation/91/ssl-client.html
