### ISSUE TITLE
Allow disabling clean

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#458]
_Original author: l...@luissantos.pt (March 20, 2013 11:01:23)_

Is it possible to add confirmation to the &quot;clean&quot; command?

Adding an &quot;--force-drop-database&quot; option will skip the confirmation.

This doesn't have a security impact but it will &quot;avoid&quot; some problems.

Thanks.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=455_

**Comment by axelfontaine** [comment]
Implemented.

**Comment by cxxr** [comment]
Thanks! Definitely going to use this config option in production.
