### ISSUE TITLE
flyway:clean should drop synonyms

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#473]
_Original author: timan...@gmail.com (April 03, 2013 19:50:06)_

Flyway does not destroy synonyms when I run flyway:clean.

Here is some SQL for creating a synonym:

CREATE TABLE [dbo].[MY_TABLE](ID INT PRIMARY KEY NOT NULL,
DESCRIPTION VARCHAR%2820%29)

CREATE SYNONYM [dbo].[MY_SYNONYM] FOR [dbo].[MY_TABLE]

Flyway does not throw an error, it just keeps the synonym.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=473_

**Comment by andersnorgaard** [comment]
I experience the same on Oracle. Should this issue be reopened?

**Comment by axelfontaine** [comment]
@andersnorgaard Please open a new issue with steps how to reproduce and a minimal SQL file that creates objects Flyway can't clean.
