### ISSUE TITLE
sp_MSForeachtable statement does not get executed with flyway

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#502]
_Original author: kavithap...@gmail.com (June 03, 2013 06:53:56)_

Hi,

I am trying to copy data from one DB to another. Before copying I wan't to turn off all the constraints in the DB. Hence I call the following statement:

exec sp_MSforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL' 

But I get a &quot;query timed out&quot; exception while executing the script with flyway. I have attached the complete script in this issue. 

Please check and provide me a solution for this issue.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=508_

**Comment by ruchirsachdeva** [comment]
Is this bug fixed, or is there any plan to fix this ?
It has been 2 years, and this has not even been assigned to anyone.

**Comment by axelfontaine** [comment]
Are you running in the same issue? I am not sure it can be fixed as Flyway holds a lock on its metadata table while migrating to make this safe for multiple concurrent nodes.

Any suggestions welcome.

**Comment by VenkataMutyala** [comment]
I ran into a similar issue and my work around was to check to see if the the object name contained '%flyway%' **if not**, execute the changes to the object.

**Comment by axelfontaine** [comment]
This is now working.

**Comment by pranay1619** [comment]
I’m facing same issue. Can anyone help me please
