### ISSUE TITLE
Flyway won't retry failed or changed script

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#504]
_Original author: virid...@gmail.com (June 11, 2013 03:14:52)_

I made a mistake in a script and it failed migration. I corrected the mistake and retried, but Flyway just wouldn't work. Upon deleting the script's row from the metadata table, it worked fine. I would expect Flyway to retry the failed script automatically...

I saw a similar behavior when just changing a script. I changed a successful script saying &quot;alter table add column&quot; and it never picked up my change. I expected the change to be noticed and the whole script executed since the hash of the file seems to be recorded by Flyway internally.

Are these issues by design? To me, they feel more like bugs.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=510_

**Comment by yglodt** [comment]
I use Flyway with Spring Boot.
How can I tell Flyway to repair when I run in that autoconfigured environment?
