### ISSUE TITLE
HP NonStop SQL/MX 3.1 support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#507]
_Original author: Stateles...@gmail.com (June 18, 2013 15:54:59)_

Hello,

I am in need of Flyway migrations for the HP NonStop database, so it would be great if this could be added; the syntax is fairly similar to Oracle. I am using SQL/MX version 3.1.

Thanks

_Original issue: http://code.google.com/p/flyway/issues/detail?id=513_

**Comment by alextercete** [comment]
Closing due to lack of interest.
