### ISSUE TITLE
Document how to deal with hotfixes

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#522]
_Original author: axel.fontaine.business@gmail.com (January 13, 2011 13:53:11)_

FAQ entry

_Original issue: http://code.google.com/p/flyway/issues/detail?id=83_

**Comment by chucklu** [comment]
@theaspect  If you maintain two major version at the same time.
Then release-2.1 (V1.0, V1.1, V2.0, **V2.1**) is for an existing production, it's already on v2.0, (v2.1 contains the fix in v1.2).
release-2.1 (V1.0, V1.1, **V1.2**, V2.0, **V2.1**) is for a total new deployed production, the same fix will include in both v1.2 and v2.1(the script was supposed to execute multi times without problem).
