### ISSUE TITLE
Play 2 Plugin

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#538]
_Original author: axel.fontaine.business@gmail.com (August 20, 2012 10:21:53)_

...

_Original issue: http://code.google.com/p/flyway/issues/detail?id=308_

**Comment by axelfontaine** [comment]
@tototoshi If you are interested I can provide you with a repo for this under the GitHub flyway organisation, like say: flyway/flyway-play

If not, no worries. The current solution is fine for me too. Thanks for all the great work so far!

**Comment by tototoshi** [comment]
Great. 

How about this.

 - <= Play 2.3 -> tototoshi/play-flyway (groupId:com.github.tototoshi)
 - >= Play 2.4 -> flyway/flyway-play (groupId:org.flywaydb)

I heard that Play 2.4 will be out in April. (Now 2.4.0-M2)

**Comment by axelfontaine** [comment]
Sounds good! I've created the repo and added you as a contributor. Feel free to start using it whenever you like.

**Comment by tototoshi** [comment]
Thanks. I've force-pushed current HEAD of tototoshi/play-flyway.
