### ISSUE TITLE
MySQL statement not recognized due to multiple comment directives on a single line

### ISSUE THREAD

**Issue by kongslund** [flyway/flyway#558]
Using Flyway version 2.2 I discovered an issue with merging an initial MySQL dump of an existing database schema.

Flyway does not recognize the following as a statement:

```
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`localhost`*/ /*!50003 TRIGGER EntityBeforeInsert BEFORE INSERT 
ON Entity FOR EACH ROW 
BEGIN
    ...
END */;;
```

If I separate the comment directives by a newline such as in the following example then Flyway recognizes the statement:

```
/*!50003 CREATE*/
/*!50017 DEFINER=`root`@`localhost`*/
/*!50003 TRIGGER EntityBeforeInsert BEFORE INSERT 
ON Entity FOR EACH ROW 
BEGIN
    ...
END */;;
```

The troublesome SQL snippet was added by the mysqldump tool.

**Comment by axelfontaine** [comment]
Limitation is in the docs: http://flywaydb.org/documentation/database/mysql.html

**Comment by axelfontaine** [comment]
Fixed. At last!
