### ISSUE TITLE
Locations directory not found on JBoss

### ISSUE THREAD

**Issue by alexisbel** [flyway/flyway#592]
Hello,

We hit a strange bug when deploying flyway in our target environment, where some migration scripts are stored in JBoss "lib" directory (instead of the war).

I narrowed it down to this:
- looking for _db/migrations/module_
  - works if directory exists in WAR classpath
  - **does not work** (not found) if directory exists in lib jars
- looking for _db/migrations/module/_ (with a trailing slash)
  - works in all locations

However, when the locations are set, flyway normalize them and remove the trailing slash if there is one (in the _com.googlecode.flyway.core.util.Location_ constructor). We workaround by putting two slashes at the end of our location, but it is rather ugly.

Obviously this is more of a bug in the classloaders behaviour, but since flyway does not give any control on how the URLs are retrieved, this is problematic. You may want to add a mean to pass location URLs directly.

Cheers,

Alexis.

**Comment by axelfontaine** [comment]
Closing old issue for ancient JBoss version
