### ISSUE TITLE
API access to script runner

### ISSUE THREAD

**Issue by kkrauth** [flyway/flyway#596]
I have certain scripts that I need to run manually. For example, we version packages outside FlyWay migrations so they are run independently. Since I have no way of calling something like flyway.runScript(..), I have to use Spring's JdbcTestUtils to perform the task that FlyWay is more than capable of doing itself. Therefore, having access to some lower-level functions would be highly beneficial. Thank you!

**Comment by jgangemi** [comment]
+1 for something like this. my use case is i'm using flyway to setup an instance of the database for integration tests and i would like to load some some static data that does not need to be versioned/managed.

**Comment by axelfontaine** [comment]
Closing as all previously mentioned use cases can now easily be covered by Flyway.
