### ISSUE TITLE
Doc enhancement: More features for the feature comparison matrix

### ISSUE THREAD

**Issue by gredler** [flyway/flyway#607]
Hi guys,

I've been looking at different DB migration / refactoring tools, and the Flyway feature matrix has been a helpful reference point. However, it is missing a number of features that are important, at least to us:

1. Support for repeatable SQL scripts. This is something that DBMaintain supports [1] and that we like because it allows us to evolve e.g. stored procedures in a single file, making full use of our source control tool (SVN, in our case) to track changes. I understand there's an enhancement in the works that may eventually lead to support for this feature in Flyway [2,3], but it would be useful to see at a glance that it's not supported yet.

2. Support for post-processing SQL scripts. Again, this is something that DBMaintain supports [4] and that seems like a useful feature to us as we evaluate the different tools, and it would be nice to see at a glance what level of support the different tools provide.

[1] http://www.dbmaintain.org/tutorial.html#Incremental_and_repeatable_scripts
[2] https://github.com/flyway/flyway/issues/120
[3] https://github.com/flyway/flyway/issues/80
[4] http://www.dbmaintain.org/tutorial.html#Postprocessing_scripts

**Comment by axelfontaine** [comment]
Done. Also removed all dead and obsolete tools from the comparison.
