### ISSUE TITLE
schema_version replication problem

### ISSUE THREAD

**Issue by stephenmittag** [flyway/flyway#619]
When inserting a row in ther schema_version table statement uses SUBSTRING_INDEX(USER(),'@',1) to fill the installed_by column.

Replicating this statement causes a different value in that column as the replication is done by a different user. In our case the column contains an empty string.

If someone uses a tool for comparing the tables on master and slave (like we do, we use pt-table-checksum) he gets an warning for the differing columns.

**Comment by mauromol** [comment]
Maybe saving the result of calling USER() in a variable and setting it as a static string in the INSERT INTO could prevent the need to use row based replication in MySQL?
