### ISSUE TITLE
Flyway command line tool needs to have classpath specified to work?

### ISSUE THREAD

**Issue by mradamlacey** [flyway/flyway#628]
I am using the command line tool to execute some migrations implemented in a jar file.  This jar file has many dependencies (also jar files).

I invoke flyway like:

```
flyway -locations=db/migration migrate
```

Which finds and executes any .sql files defined in this classpath location, however when it tries to execute a JDBC migration (defined in a .class file in my har) Flyway throws an exception about java.lang.NoClassDefFoundError.

I've tracked the error because of the dependencies for the JDBC Migration class instance is not on the class path.

I then expected that using the command:

flyway -locations=db/migration -jarDir=<path to my jars and dependencies> 

Would set the classpath, however this seems to just override the path that the tool looks for migrations in.

My eventual fix was to modify the command line tool's packaged scripts to add /jars to the class path.  e.g.

```
$JAVA_CMD -cp bin/flyway-commandline-2.2.1.jar:bin/flyway-core-2.2.1.jar:jars/* com.googlecode.flyway.commandline.Main $@ -consoleWidth=$CONSOLE_WIDTH
```

Is this a bug?  Or the expected behavior?  What is the 'correct' way to change the classpath that flyway uses?

Should I submit a pull request for this change (or one that is a bit smarter and reads in a command line argument?)

**Comment by bhumikat** [comment]
I need command line java flyway migration tool.
that is possible with flyway. I tried the thing but still flyway don't identify which jar needs to point  to classpath.
http://stackoverflow.com/questions/37455135/java-command-line-flyway-migration

Let me know if you have any idea.
