### ISSUE TITLE
Support trailing single line comments

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#63]
_Original issue: http://code.google.com/p/flyway/issues/detail?id=63_

**Comment by gemisigo** [comment]
Hi Axel,

What's the ETA for 5.2.0? Seeing that this issue has been dragging since 3.1, I guess it's not that important since it has a relatively easy workaround. What would you estimate the odds of it being fixed in 5.2.0?

**Comment by gemisigo** [comment]
Ohh, I see. So this is gonna linger for a while...

**Comment by axelfontaine** [comment]
Fixed. At last!

**Comment by vojtapol** [comment]
This seems to me broken for me for MySQL `#` comments at the end of the line.
