### ISSUE TITLE
DB2 on z/OS support

### ISSUE THREAD

**Issue by Muni10** [flyway/flyway#638]
Background: We are using flyway for several Oracle based systems and are now starting a new migration for an existing application. We therefore want to use flyway for database migrations there as well.

However, when running the migrations, Flyway is looking up the SYSCAT schema in the DB2 database. This schema does not exist on z/OS. We get the following error message:
DB2 SQL error: SQLCODE: -204, SQLSTATE: 42704, SQLERRMC: SYSCAT.SCHEMATA

Could you investigate this issue?

**Comment by Galanodel** [comment]
Hi, 

I m still facing the same problem in Flyway version 3.2.1.
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:migrate (default-cli) on project db-migration: org.flywaydb.core.api.FlywayException: Unable to check whether schema "TCBS72IBKT" exists: [SQL0204] SCHEMATA in SYSCAT type *FILE not found.

As it is reported to have been solved in version 3.1 (http://flywaydb.org/blog/flyway-3.1.html), maybe there is another reason that I m still getting this error?

Thank you!

**Comment by axelfontaine** [comment]
@cteig Thoughts?

**Comment by cteig** [comment]
Hi @Galanodel  

Do you know the DatabaseMetaData.getDatabaseProductVersion ? 
The Flyway code use the DatabaseProductVersion to identify the data server to which an application is connected. 

If it helps, you can use my little test-project to get it. https://github.com/cteig/databaseProductVersion. Just update to your version of db-driver in the pom dependency and your database url, user and password. Or if you use a database client i.e squirrel, maybe you can find DatabaseProductVersion there. 

Christine

**Comment by Galanodel** [comment]
Hi Christine,

thank you. 
I extracted getDatabaseProductVersion from squirrel, it is: 06.01.0000 V6R1m0. We are using a 9.11 driver version to connect from our application, squirrel, etc ... successfully. 
I downloaded the 6.6 driver version anyway, and tried it, I still get the same error.

Another thing though that I noticed in your example project (databaseProductVersion) is that you use the db2jcc (com.ibm.db2). I am using db2 for AS/400 (jt400). 
So, I take it this is fixed for another database then?

Thanks a lot again!

**Comment by cteig** [comment]
Hi 
Yes I think you are right. For DB2 z/OS, getDatabaseProduct will return a string who starts with "DSN". The pull request is only tested agains DB2 z/OS. 
But, I see it will be usefull to change the check who identify the data server, so it give a better feedback. I will look at it. 

Christine

**Comment by Galanodel** [comment]
Hi Christine,

thanks a lot for your time and effort! I wait eagerly for your news!
