### ISSUE TITLE
Ignore sqlplus set define off command

### ISSUE THREAD

**Issue by crump32** [flyway/flyway#669]
When running a sql script I have SET DEFINE OFF; as the first line, when running this it states missing or invalid option, once I remove the line it works just fine.  Is there any way to preserve the sqlplus command line calls needed for the script?  I do believe dbmaintain has this type of feature where you can run via sqlplus.  Anything would help, Thanks!

**Comment by axelfontaine** [comment]
Fixed.

**Comment by bretthodel** [comment]
Did this get reverted in version 5?  After updating to 5 I got `ora-00922 missing or invalid option` on my lines containing `set define off;`

**Comment by axelfontaine** [comment]
@bretthodel These commands are implemented in Flyway Pro and Enterprise. See https://flywaydb.org/documentation/database/oracle#sqlplus-commands

Please open a new issue if you hit any problem with those.
