### ISSUE TITLE
Gradle plugin org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by SlyDen** [flyway/flyway#690]
Just got exception **java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String** with Gradle 1.10 and Flyway plugin (version 2.3).

Workaround from Gradle's issue tracker http://issues.gradle.org/browse/GRADLE-2566 works for me.

Situation:
I have some string property in **gradle.properties** file (in project's root)
Later I use it in **build.gradle** to configure flyway plugin, like:

``` java
placeholders = ['execUserName' : "${project.execUserName}"]
```

and it gives exception: **java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String**

But

``` java
placeholders = ['execUserName' : "${project.execUserName}".toString()]
```

works like expected.

Not sure if it is Flyway plugin specific error or Gradle's (posted comment to http://issues.gradle.org/browse/GRADLE-2566 too)

May be relevant to https://github.com/flyway/flyway/issues/574

**Comment by aaveshaikh** [comment]
please try this 
 applicationVariants.all { variant ->
             
variant.outputs.all {
                    outputFileName = "${variant.name}-${variant.versionName}.apk"
                }
               
            }
in your build.gradle file
