### ISSUE TITLE
Flyway can't clean views in Postgres that reference tables in other schemas

### ISSUE THREAD

**Issue by jonbca** [flyway/flyway#693]
When I try to clean a database in Postgresql containing a view that references a table in another schema, the clean operation fails with:

```
ERROR: Unable to drop "public"."first_view"
ERROR: Caused by: org.postgresql.util.PSQLException: ERROR: cannot drop type first_view because view first_view requires it
  Hint: You can drop view first_view instead.
ERROR: Occured in org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse() at line 2161
```

My migration's SQL looks like:

``` sql
CREATE SCHEMA other;

CREATE TABLE other.test_table (
  id INTEGER PRIMARY KEY,
  name VARCHAR(64)
);

CREATE VIEW public.first_view (my_id, my_name) AS SELECT id, name FROM other.test_table;
```

and my conf file contains `flyway.schemas=public,other`. I've also tried switching the order to `other,public` with the same result.

This is using PostgreSQL 9.3 and the jdbc4 driver.

**Comment by dafelipe130** [comment]
@zdenek-zikan  +1, I'm having the same issue. Care to share? @jonbca
