### ISSUE TITLE
validateOnMigrate is true by default

### ISSUE THREAD

**Issue by vertex-github** [flyway/flyway#695]
We just had a case where additional SQL was added to an already applied SQL change file.  On databases that already had the SQL change file applied, Flyway ignored the new additions since as far as it was concerned, the changeset had been applied.  However, this led to problems since developers working off fresh DB copies got the new changeset (as did all unit tests that leverage in-memory DBs like H2), pushed changes to prod, and ended up with an inconsistent DB.

Could Flyway also check that the provided SQL files had not been modified since they were applied, and if so report an error (fail fast, rather than ignore the changeset) if this is the case?

**Comment by mosingh123** [comment]
where to set the property false please explain
