### ISSUE TITLE
Add support for executing external scripts using @other_script.sql

### ISSUE THREAD

**Issue by rehand** [flyway/flyway#705]
As Flyway says, that is is compatible with all scripts which can be executed by SqlPlus ('Any Oracle sql script executed by Flyway, can be executed by SqlPlus [...]'), it would be nice to add support for executing other scripts within a script file like the following:

``` sql
@other_script_1.fnc
@other_script_1.syn
@other_script_1.grt
```

Currently, Flyway interprets this as error:

```
ERROR: Error executing statement at line 1: @other_script_1.fnc
@other_script_1.syn
@other_script_1.grt

ERROR: Caused by: java.sql.SQLException: ORA-00900: invalid SQL statement

ERROR: Occured in oracle.jdbc.driver.DatabaseError.throwSqlException() at line 112
```

Is there a way to add support for this? Otherwise I'd have to change all existing scripts in order to be able to use Flyway.

**Comment by cosmin** [comment]
+1 for finding a solution for this problem at some point. Loading the files from class path would work for my use case  and I'm not clear what transaction or error handling limitations this would involve.

**Comment by KevinSheedy** [comment]
+1 Using Flyway for DDL but still depend on SqlPlus for deploying procedures, functions from a **single source of the truth** in our git repo.
It'd be great if we could do it all with Flyway.

**Comment by lukaszewski** [comment]
+1 Would be greate to have this feature. We organize our sources (packages, table definitions, etc.) in different subfolders with (of course) git. With git and specific branches we ensure not to deploy sources in the wrong version. Nowadays we use a kind of install manifest (e.g. 1_5_5.sql) to reference this files. Actually the same way like flyway does it but not automated.

Cheers
Adam L.

**Comment by axelfontaine** [comment]
This should include support for both the `@` and `@@` (files only for now, no URLs) as well as the `SET SUFFIX` command.

To ensure parameters are processed correctly, #1883 should be implemented first.

**Comment by axelfontaine** [comment]
This has now been implemented.
