### ISSUE TITLE
Add comparison with commercial migration products

### ISSUE THREAD

**Issue by lukaseder** [flyway/flyway#707]
I just ran across some redgate products, such as the SQL Packager 7:
http://www.red-gate.com/products/sql-development/sql-packager/

And then, I thought it would be interesting to compare flyway also with these tools in the feature comparison matrix:
http://flywaydb.org/#features

**Comment by axelfontaine** [comment]
Closing as SQL Packager is dead and I am not sure whether we want to go down this path.
