### ISSUE TITLE
Prompt for userId and password in commandline mode

### ISSUE THREAD

**Issue by sachinwalia2k8** [flyway/flyway#724]
I think it is difficult to implement userId and password encryption in flyway.conf file without making other compromises such as exposing encryption keys. How about if in commandline mode flyway prompts user for database credentials? That would still be very secure compared to storing in clear text in conf file.

**Comment by PredatorVI** [comment]
Pull request for fix submitted.  I'm new to the GitHub process.  Hopefully it gets accepted and released soon.

**Comment by axelfontaine** [comment]
This has now been fixed. Prompting will happen automatically if either user or password have not been supplied via any other means.

Cheers
Axel

**Comment by smanoharaw** [comment]
Hi axelfontaine,
I love the product. I tested it yesterday on my Oracle db. very easy to use. But I really need the passwordPrompt functionality? Where can I get the flyway version with this? Or, if I could get the code I can create the jar file? Please let me know how to go about this. We are going live in a month or so. 
Thanks

**Comment by szxnyc** [comment]
Hello,
I'm using version 4.0 and didn't supply a password but not getting prompted. Anything I'm doing wrong here?

**flyway.conf**
`#flyway.password=`

```
[szxnyc@orbiter scripts]$ flyway info
Flyway 4.0 by Boxfuse

ERROR: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost:3306/mydb) for user 'devuser': Could not connect: Access denied for user 'devuser'@'localhost' (using password: NO)
```

**Comment by PredatorVI** [comment]
I downloaded the latest client as well and verified this is not working.  I pulled the latest code in order to debug it but can't seem to build it due to missing dependencies:

**Building flyway-core:**
`Failed to execute goal on project flyway-core: Could not resolve dependencies for project org.flywaydb:flyway-core:jar:0-SNAPSHOT: The following artifacts could not be resolved: sqlline:sqlline:jar:1.1.8, com.sap.db.jdbc:ngdbc:jar:1.103.0: Failure to find sqlline:sqlline:jar:1.1.8 in mynexus`

The only version of sqlline available in maven central is version 1.1.9.

**Building flyway-commandline:**
`The following artifacts could not be resolved: com.oracle:server-jre:tar.gz:windows-x64:8.74, com.oracle:server-jre:tar.gz:linux-x64:8.74, com.oracle:jre:tar.gz:macosx-x64:8.74: Could not find artifact com.oracle:server-jre:tar.gz:windows-x64:8.74 in mynexus.
`
If I need to install custom maven artifacts there doesn't seem to be any instructions on what is needed or where to get it.  

If it takes another 9 months to get a release with this in it, I'm going to be very frustrated.

**Comment by smanoharaw** [comment]
I moved to liquibase since this feature is not working in flyway.

 

Thanks,

Sadhana

**Comment by axelfontaine** [comment]
Build instructions are available here: https://flywaydb.org/documentation/contribute/code/setup and here https://flywaydb.org/documentation/contribute/code/database

You can avoid all those DB-specific dependencies by using -DskipTests

**Comment by PredatorVI** [comment]
@axelfontaine Thanks for the fix.  When might we see an official release build?

Also for the sake of trying to get this thing to build, it still tries to build tests and fails finding sqlline.

Per [https://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-test.html](https://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-test.html),  -DskipTests only skips execution, not compile.  I also tried both -DskipTests and -Dmaven.test.skip=true with no change in the compile error.

So, it still seems to have a non-test dependency that requires sqlline:sqlline:1.1.8 (which is no longer available in Maven Central).  I've included abbreviated output below of each command:

C:\Flyway> **mvn -version**
> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T09:41:4
> 7-07:00)
> Maven home: C:\Dropbox\Tools\apache-maven-3.3.9\bin\..
> Java version: 1.8.0_74, vendor: Oracle Corporation
> Java home: C:\Program Files\Java\jdk1.8.0_74\jre
> Default locale: en_US, platform encoding: Cp1252
> OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

C:\Flyway> **mvn install -P-InstallableDBTest -P-CommercialDBTest**
> [INFO] Scanning for projects...
>  ...
> [INFO] ------------------------------------------------------------------------
> [INFO] Building flyway-core 0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [WARNING] The POM for sqlline:sqlline:jar:1.1.8 is missing, no dependency inform
> ation available
>   ...
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 4.643 s
> [INFO] Finished at: 2016-03-14T11:33:19-06:00
> [INFO] Final Memory: 23M/435M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project flyway-core: Could not resolve depende
> ncies for project org.flywaydb:flyway-core:jar:0-SNAPSHOT: Failure to find sqlli
> ne:sqlline:jar:1.1.8 in nexus
>  ...

C:\Flyway> **mvn clean compile -DskipTests -Dmaven.test.skip=true**
> [INFO] Scanning for projects...
>    ...
> [INFO] ------------------------------------------------------------------------
> [INFO] Building flyway-core 0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [WARNING] The POM for sqlline:sqlline:jar:1.1.8 is missing, no dependency inform
> ation available
  ...
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.000 s
> [INFO] Finished at: 2016-03-14T11:20:34-06:00
> [INFO] Final Memory: 18M/304M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project flyway-core: Could not resolve depende
> ncies for project org.flywaydb:flyway-core:jar:0-SNAPSHOT: Failure to find sqlli
> ne:sqlline:jar:1.1.8 in nexus
>    ...

**Comment by grobmeier** [comment]
@PredatorVI I made the build work with running this command:

```
mvn install -P-InstallableDBTest -P-CommercialDBTest -P-CommandlinePlatformAssemblies -DskipTests=true
```

The first part I got from the docs:
https://flywaydb.org/documentation/contribute/code/database

The second part is from the CLI maven pom:
https://github.com/flyway/flyway/blob/master/flyway-commandline/pom.xml#L10
