### ISSUE TITLE
SQL-based callbacks

### ISSUE THREAD

**Issue by teicher** [flyway/flyway#728]
Hello Axel,
you explained why you didn't implement a post-migrate script (that runs after any and every migration) here:
http://stackoverflow.com/a/7268878/459816
However I do have a great example why we need this: (postgres)
grant select ON all tables in schema public to portalread;
This will grant the permission to all current (!) tables. 
when cleanig and rebuilding, or adding new tables, those will not be accessible.
thus, I need to run this script "always".
Good enough ?
Cheers, Tom.

**Comment by jdoose** [comment]
An annotation in case somebody runs into the same situation as we did:

If the sqlMigrationPrefix is explicitly set to none ("flyway.sqlMigrationPrefix=") the Sql file callbacks do not work:
ERROR: Wrong migration name format: afterEachMigrate.sql(It should look like this: 1_2__Description.sql)

A workaround is to use an sql migration prefix (or the default).

If you, @axelfontaine, think this is a bug I leave it to you to open a new issue.
If it is not a bug, the documentation should be adjusted. If you want we can provide a fix.

**Comment by asv** [comment]
@axelfontaine, what about the problem @jdoose ? I have exactly same problem with sql callbacks, if sql prefix is not specified (Flyway 3.2.1).

**Comment by axelfontaine** [comment]
@jdoose @asv This does indeed sound like a bug. Please file a separate issue.

**Comment by jdoose** [comment]
Done in #1165
