### ISSUE TITLE
Create DEB for command-line tool

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#734]

**Comment by LandonSchropp** [comment]
This would be really helpful with our Docker setup.

**Comment by axelfontaine** [comment]
@LandonSchropp Can't you simply use our [official Docker images](https://hub.docker.com/r/boxfuse/flyway/)?

**Comment by LandonSchropp** [comment]
Ah, I didn't realize that existed. Thanks!

**Comment by alextercete** [comment]
Closing due to lack of interest.
