### ISSUE TITLE
Support multiple tasks of the same type in gradle

### ISSUE THREAD

**Issue by jnizet** [flyway/flyway#738]
I have a unit-test database, and an integration-test database (and I could have more for production, for example), each with a different user/password/url. And I'd like to be able to create flyway tasks for each of them:

```
class PostgresDatabase {
    String name;
    String userName;
    String password;
    String url;

    PostgresDatabase(String name, String userName, String password, String url) {
        this.name = name;
        this.userName = userName
        this.password = password;
        this.url = url;
    }
}

def unit = new PostgresDatabase('unit', 'foo_unit', 'foo_unit', 'jdbc:postgresql://localhost/foo_unit');
def integ = new PostgresDatabase('integ', 'foo_integ', 'foo_integ', 'jdbc:postgresql://localhost/foo_integ');

[integDatabase, unitDatabase].each {db ->
    project.task('flywayMigrate' + db.name.capitalize(), type: org.flywaydb.gradle.task.FlywayMigrateTask) {
        ...
    }
}
```

Unfortunately, that's not as easy as it could be, because the Flyway gradle tasks don't have any property. They all read their properties from a unique flyway extension.

It would be nice to be able to create tasks having unique properties, overriding those from the extension.

It would also be nice to be able to use a flyway-base-plugin, which would only make the tasks available (for my use-case, for example), and a flyway-plugin, relying on the base plugin, and which would add default tasks using the extension.

I've managed to do it by subclassing the Flyway tasks and overriding the `createFlyway()` method, but that's painful, and relies on an undocumented implementation detail.

**Comment by netmikey** [comment]
I don't think there's a need for 2 separate plugins. As Peter Niederwieser (a Gradle core dev) points out in this SO question http://stackoverflow.com/a/18142219/737587 

> Basically the task class(es) need to declare all properties (or more) that the extension has, using the extension properties as defaults. Have a look at the code quality plugins in the Gradle codebase (e.g. `CheckstylePlugin` or `FindbugsPlugin`). By convention, concrete task classes don't have `Task` in their name.

Implementing this would solve all your problems: it would make the current syntax continue working without any change, and it would allow ppl to create new flyway tasks and configure them ad-hoc, effectively overriding the defaults from the extension.

**Comment by ben-manes** [comment]
If this is reintroduced, the [pull request](https://github.com/ben-manes/gradle-flyway-plugin/pull/2) where this feature was originally implemented may be a good reference for whomever resolves this issue.

**Comment by alkamo** [comment]
The issue that tends to make this require a second "plugin" is the configuration. Any way I can envision changing the configuration to support multiple databases would tend to break backwards-compatibility. 

I'd love to tackle this problem again, but I don't have any good ideas about how to manage the configuration while satisfying both needs: 1) support the simplest configuration and 2) only implement a single plugin.

**Comment by alkamo** [comment]
I have a potential solution for this: maintain the existing extension properties and add a collection of extension objects within it as well. If the collection is empty, the plugin continues to function exactly as it does today. Otherwise, it treats the top-level properties as defaults which get overwritten by the specifics in the collection (if they overlap).

This is very similar to what I implemented before, except that it allows the current functionality to persist.

The one problem I've run into with this solution is that I can't figure out how to add containers to the plugin in Java. @axelfontaine, how do you feel about including a dummy java class to fulfill the JavaDoc requirement instead of requiring Flyway.Plugin to be Java?

**Comment by alkamo** [comment]
I now have a functional solution for this issue, using Gradle rules to apply tasks to individual configurations. I am holding off on the pull request for the full solution as the precursor hasn't been merged yet.

**Comment by gregopet** [comment]
I've just come across the same issue with my prod & staging database: any chance of these pull requests getting merged? My current workaround is to scan `project.gradle.startParameter.taskNames` to see which settings to apply in the configuration closure though this obviously prevents me from migrating both databases with a single invocation.

**Comment by cdalexndr** [comment]
An example or an update to your site documentation would be helpful.
