### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by sunym** [flyway/flyway#748]
my flyway file is utf-8 ,and database is mysql also is utf-8 endcoding .

ths flyway file content :+1: 
/*
- 创建Top1000网站
- 20140410
- */
  CREATE TABLE `dm_domain_top10000` (
  `webSiteId`  bigint(20) NULL DEFAULT NULL COMMENT '网站ID' ,
  `webSiteName`  varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '网站名称' ,
  `domain`  varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '域名' ,
  `userType`  varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用户类型(固网,移动)' ,
  `province`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '省份' ,
  `dnsResolNum`  bigint(20) NULL DEFAULT NULL COMMENT 'DNS解析次数' ,
  `inResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '网内解析次数' ,
  `idcResolNum`  bigint(20) NULL DEFAULT NULL COMMENT 'IDC解析次数' ,
  `cacheResolNum`  bigint(20) NULL DEFAULT NULL COMMENT 'Cache解析次数' ,
  `cdnResolNum`  bigint(20) NULL DEFAULT NULL COMMENT 'CDN解析次数' ,
  `pdcResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '直连解析次数' ,
  `otherResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '其他解析次数' ,
  `chtieResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '中国铁通解析次数' ,
  `chtelResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '中国电信解析次数' ,
  `chuResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '中国联通解析次数' ,
  `outOtherResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '网外其他解析次数' ,
  `inIncludeChtieNum`  bigint(20) NULL DEFAULT NULL COMMENT '网内包含铁通解析次数' ,
  `inNoIncludeChtieNum`  bigint(20) NULL DEFAULT NULL COMMENT '网内不包含铁通解析次数' ,
  `outIncludeChtieNum`  bigint(20) NULL DEFAULT NULL COMMENT '网外包含铁通解析次数' ,
  `outNoIncludeChtieNum`  bigint(20) NULL DEFAULT NULL COMMENT '网外不包含铁通解析次数' ,
  `updateDate`  varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '后端跑批日期' ,
  `etlDate`  varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '批次日期' ,
  `domainTop10000Id`  bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id' ,
  PRIMARY KEY (`domainTop10000Id`)
  )
  ENGINE=MyISAM
  DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
  COMMENT='资源视图-资源报表-Top10000域名'
  AUTO_INCREMENT=1
  CHECKSUM=0
  ROW_FORMAT=DYNAMIC
  DELAY_KEY_WRITE=0
  ;

this file can run sucess in mysql.

but  in flyway it find is 

`otherResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '其他解析次数' ,
`chtieResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '中国铁�?解析次数' ,
`chtelResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '中国电信解析次数' ,
`chuResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '中国联�?解析次数' ,
`outOtherResolNum`  bigint(20) NULL DEFAULT NULL COMMENT '网外其他解析次数' ,
`inIncludeChtieNum`  bigint(20) NULL DEFAULT NULL COMMENT '网内包含铁�?解析次数' ,
`inNoIncludeChtieNum`  bigint(20) NULL DEFAULT NULL COMMENT '网内不包含铁通解析次�? ,
`outIncludeChtieNum`  bigint(20) NULL DEFAULT NULL COMMENT '网外包含铁�?解析次数' ,
`outNoIncludeChtieNum`  bigint(20) NULL DEFAULT NULL COMMENT '网外不包含铁通解析次�? ,

Chinese garbled.

please tell me what happen?

**Comment by chariothy** [comment]
I have the same problem, too. After half hour's investigation, I've found the problem is not flyway's.
Just make sure your datasource.url contains characterEncoding=UTF-8:
jdbc:mysql://localhost:3306/mydb?useSSL=false&characterEncoding=UTF-8&autoReconnect=true
