### ISSUE TITLE
The gradle flyway plugin should be able to create new migration files with the correct file naming format.

### ISSUE THREAD

**Issue by berlin-ab** [flyway/flyway#756]
`gradle flywayCreate CreateUser`

This should create a file with the name:

```
src/main/resources/db/migrate/V[date]__CreateUser.sql
```

... so I don't have to remember the correctly format for naming a file and I can get my job done quicker.  I should just be able to run a command and my script should be ready for editing.

**Comment by axelfontaine** [comment]
Duplicate of #400
