### ISSUE TITLE
Option to put Migration Description within the file instead of in the filename.

### ISSUE THREAD

**Issue by shutterstein** [flyway/flyway#757]
Hi, it would be nice if we could have an option to put the description of changes into the top of the file within some kind of a comment/identifier so that we don't have to have a long, verbose filename.  Perhaps a configurable option?

**Comment by vargaendre** [comment]
I'd love to have this feature too.

**Comment by axelfontaine** [comment]
Closing. See my workaround suggestion.

**Comment by vbujanca** [comment]
This would be a nice built-in feature, hopefully you will reconsider.
