### ISSUE TITLE
Gradle plugin depends on testClasses

### ISSUE THREAD

**Issue by hovinen** [flyway/flyway#775]
Currently the Gradle-plugin adds in Java-projects a dependency on testClasses:

    flyway-gradle-plugin/src/main/groovy/org/flywaydb/gradle/task/AbstractFlywayTask.groovy:
    AbstractFlywayTask() {
        group = 'Flyway'
        project.afterEvaluate {
            if (isJavaProject()) {
                this.dependsOn(project.tasks.testClasses)
            }
        }
        extension = project.flyway
    }

In my application, I migrate the schema with Flyway and then, based on the up-to-date schema, generate Java-code which is then compiled. This however results in a circular dependency:

    > gradle compileJava
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Circular dependency between the following tasks:
    :classes
    \--- :compileJava
         \--- :generateJooq
              \--- :flywayMigrate
                   \--- :testClasses
                        \--- :compileTestJava
                             \--- :classes (*)
    
    BUILD FAILED

I have tried everything of which I can think to fix this, from manually removing the dependency to putting the Flyway-migrations into a subproject. I have come to the conclusion that the only feasible solution is to alter the plugin itself to remove the added dependency. Could you please therefore do so? Thank you.

Best regards

**Comment by axelfontaine** [comment]
Fixed as part of #979
