### ISSUE TITLE
Improve Maven plugin's <locations/> semantics

### ISSUE THREAD

**Issue by lukaseder** [flyway/flyway#787]
I understand that the `<locations/>` semantics is to look for files on the classpath *after* the compile phase, if the location strings are unprefixed. This is [documented here](http://flywaydb.org/documentation/maven/migrate.html):

> Locations to scan recursively for migrations. The location type is determined by its prefix.
Unprefixed locations or locations starting with classpath: point to a package on the classpath and may contain both sql and java-based migrations.
Locations starting with filesystem: point to a directory on the filesystem and may only contain sql migrations.

From a Maven perspective, however, that is a bit unexpected. I wouldn't expect any plugin to *depend* on the outcome of the `compile` phase in this way, specifically, because I placed all my SQL scripts in a source directory. So I would expect the default behaviour to be looking for sources in the Maven file structure, specifically in `src/main/resources`, or perhaps in `src/test/resources`.

I'm particularly wondering if the status quo is correct, because of these things:

- I'd like to run Flyway migrations prior to jOOQ code generations in the `generate-sources` phase. This works pretty well already with the `sql-maven-plugin`, which allows to execute SQL files from the src directories, e.g. `<srcFile>src/main/resources/db-h2.sql</srcFile>`
- The warning in the docs is a slight "implementation smell":

    > Important: To make sure new migrations are taken into account, mvn compile must be invoked first!

    I don't think that Maven plugins should make such assumptions. Again, I'd like to run this plugin *before* the compile phase in some cases. This would also be useful, if working together with Hibernate source code generation, or something else.

----
So, the suggestion is merely to enhance the Maven plugin to automatically look also in the Maven project root.

The workaround, so far, is to specifiy a `filesystem` prefix:

```xml
<location>filesystem:src/main/resources/db/migration</location>
```

**Comment by axelfontaine** [comment]
Fixed as part of #979
