### ISSUE TITLE
Provide default implementation for FlywayCallback

### ISSUE THREAD

**Issue by lukaseder** [flyway/flyway#788]
This isn't a concrete use-case, just general feedback.

When providing SPI's like `FlywayCallback`, it is generally useful to also provide a default implementation that is simply empty. This is useful for two reasons:

1. People usually just implement one of the callback methods, not all of them
2. It is easier to implement SPI evolution, because adding new methods to the SPI won't break those implementations that are based off the well-known default implementation

In jOOQ, we do this with all SPIs

**Comment by axelfontaine** [comment]
This has now been implemented.
