### ISSUE TITLE
Implement the "context" pattern in FlywayCallback

### ISSUE THREAD

**Issue by lukaseder** [flyway/flyway#789]
This isn't a concrete use-case, just general feedback.

Over time when APIs and SPIs evolve, we have seen that the optimal way to design such SPIs is by having all methods take a single "context" argument, instead of a more specific argument list. Right now, we have:

```java
void beforeMigrate(Connection connection);
void beforeEachMigrate(Connection connection, MigrationInfo info);
```

From experience, it is quite likely that this SPI needs to break at some point of time in the future, when we realise that `MigrationInfo` is also needed in `beforeMigrate()`, or maybe we'll need some `Map<String, String>`, or whatever.

It might be better to design such an API as follows:

### All methods have the same context argument:

```java
interface CallbackContext {
    /** is never null */
    Connection connection();
    /** is null except for FlywayCallback.beforeEachMigrate() */
    MigrateInfo info();
}

/** ctx.info() is null */
void beforeMigrate(CallbackContext ctx);
/** ctx.info() is not null */
void beforeEachMigrate(CallbackContext ctx);
```

### Each method / method category has its own context argument

```java
interface MigrateContext {
    Connection connection();
}

interface EachMigrateContext {
    Connection connection();
    MigrateInfo info();
}
    
void beforeMigrate(MigrateContext ctx);
void beforeEachMigrate(EachMigrateContext ctx);
```

I'm aware that this cannot be implemented backwards-compatibly right now. But if you agree with the general idea, you can keep this in mind for Flyway 4.0. Or you reject it, if you feel that the change doesn't pull its weight.

**Comment by axelfontaine** [comment]
The combination of interfaces one can implement, including the new ConfigurationAware has proven to be sufficient for now.
