### ISSUE TITLE
Support applying migrations with older version numbers that haven't been applied yet

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#79]
_Original author: gilman.t...@gmail.com (June 16, 2011 05:59:33)_

I've been using Flyway for a while and like it a lot. This issue is a  question about a design decision, and an enhancement request.

Background: my development team recently got into a situation where one developer created a migration with version X, but committed it to source control a few days after a different developer created a migration with version X+1 and committed it right away.

After the first commit, which included the migration with version X+1, we ran Flyway. Flyway applied the X+1 migration to the database as expected. After the other developer committed migration X, we re-ran Flyway. Because migration X had an older version number than the most recent version in the database (X+1), it was never applied at all, but other later migrations (X+2, X+3, etc) were all applied as expected.

This behavior surprised me, because I'm familiar with the Rails ActiveRecord migration behavior. In ActiveRecord, all migration files are examined during the migration process, and it will apply all migrations that have not yet been applied even if their version numbers are &quot;older&quot; than the most recent migration. This behavior means that committers can commit &quot;out-of-order&quot;, and the correct migration sequence will still be maintained. 

Obviously, if migration X+1 relied on the presence of migration X, then applying them out-of-order would be a problem. But, these situations are less likely to come up because the developer of migration X+1 will catch this situation right away when they try to test their code before checking in. To me, this case seems less common than two independent developers committing two independent migrations. In this case, applying older migrations would keep the database in sync even if branches are merged late.

I'm looking into how hard it would be to patch Flyway to support applying older migrations, but I wanted to gather the community's opinion about this behavior first. Was it a deliberate design decision to only apply migrations that are newer than the latest version number? Would applying older-but-unapplied migrations cause problems that I'm just not seeing?

Thanks,
Gil

_Original issue: http://code.google.com/p/flyway/issues/detail?id=138_

**Comment by danrwhitcomb** [comment]
For anyone finding this years later. Flyway 2.0+ supports out-of-order migrations with a flag. https://flywaydb.org/documentation/releaseNotes
