### ISSUE TITLE
Idea of a plugin relying on Hibernate's hbm2ddl tool in order to generate the migration schemas...

### ISSUE THREAD

**Issue by balteo** [flyway/flyway#791]
I would like to suggest and contribute a maven plugin both related to
- Hibernate's hbm2ddl tool
- Flyway
  The idea would be to have this third-party plugin (let's call it: **_Hibernate4Flyway**_ for now) rely on Hibernate's hbm2ddl tool in order to generate a set of incremental schema files following Flyway's naming requirements i.e.

> A version must have the following structure:
> 
> One or more numeric parts
> Separated by a dot (.) or an underscore (_)
> Underscores are replaced by dots at runtime
> Leading zeroes are ignored in each part

Those files would generated by Hibernate's hbm2ddl upon SessionFactory/EntityManagerFactory startup and kept (and optionally edited) so that they could later be applied to the production database during the migrations.

The gap this plugin would fill is best described as follows: as of now, developers can really rely on hbm2ddl only until the first data migration. Once the first database is released in production, developers can still use hbm2ddl but they then have to manually compute the diff between version 1 of database (the one in production) and version 2 (intended for the next release). They then have to manually create the migration script to be later applied by Flyway.

Please comment with questions, suggestions or guidelines so that I know whether my idea is feasible and if that is the case how we can carry on.

**Comment by axelfontaine** [comment]
Closing this old issue. Besides the fact that I am generally unsure about this, it is too Hibernate-specific.
