### ISSUE TITLE
Official Flyway Dockerfile

### ISSUE THREAD

**Issue by ToBeReplaced** [flyway/flyway#797]
Would you consider establishing and supporting a Dockerfile for running flyway?

Here is a complete example that I am using in my own projects:

``` Dockerfile
FROM centos:centos7
MAINTAINER ToBeReplaced

# Get flyway
RUN ["curl", "-O", "http://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/3.0/flyway-commandline-3.0.tar.gz"]
RUN ["yum", "install", "-y", "tar"]
RUN ["tar", "-xzf", "flyway-commandline-3.0.tar.gz"]

# Install java and the jdbc postgres driver
RUN ["yum", "install", "-y", "java-1.7.0-openjdk-headless"]
RUN ["yum", "install", "-y", "postgresql-jdbc"]

WORKDIR flyway-3.0

# Copy the postgres driver to its required location
RUN ["cp", "/usr/share/java/postgresql-jdbc.jar", "jars/"]

ENTRYPOINT ["./flyway"]
```

This allows you to run flyway inside of its own container. Example:

```
docker run --rm -v '/opt/migrations:/opt/migrations' org.tobereplaced/flyway migrate -user=postgres -url='jdbc:postgresql://172.17.0.5:5432/exampledb' -locations='filesystem:/opt/migrations'
```

**Comment by orlade** [comment]
This would be great. A Flyway container could be started alongside the app container in Docker Compose, migrate the database at the injected hostname, then terminate totally independent of the app.

**Comment by claycephas** [comment]
You are welcome to use this as a starting point.
https://hub.docker.com/r/claycephas/flyway/

**Comment by dhoer** [comment]
@axelfontaine any chance that we can get an official flyway repo in 2016?

**Comment by axelfontaine** [comment]
@dhoer Would you be willing to contribute your Dockerfile?

**Comment by dhoer** [comment]
@axelfontaine You bet! https://github.com/dhoer/docker-flyway

**Comment by mfilotto** [comment]
Any update on this one ?

**Comment by axelfontaine** [comment]
This is now available: https://hub.docker.com/r/boxfuse/flyway/

Thanks @dhoer for providing a nice starting point with your repo!

**Comment by dhoer** [comment]
@axelfontaine Thanks for the official release!  

I do have to ask about why volumes were added. It prevents extending the image cleanly e.g.,

```
FROM boxfuse/flyway:5.0.2

ENV MYSQL_DRIVER_VERSION 5.1.45

RUN curl -o /flyway/drivers/mysql-connector-java-${MYSQL_DRIVER_VERSION}.jar
    https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_DRIVER_VERSION}/mysql-connector-java-${MYSQL_DRIVER_VERSION}.jar
```
Unless there is a trick I don't know about, having volumes defined requires the use of [multistage-build](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) pattern, or repeating the entire contents of the dockerfile.

Can volumes be removed from the dockerfile?  They are easy to add and usage can be documented in readme.  But once they are there, base images are hard to extend.

**Comment by axelfontaine** [comment]
@dhoer Good point. Fixed. In the future, please open a new issue against flyway/flyway-docker. Thanks!
