### ISSUE TITLE
Feature request - add support for always running sql files in a certain directory, before or after migrations

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#80]
_Original author: micha...@utest.com (September 26, 2011 14:31:50)_

Hi,

I would propose a new feature that would allow configuring flyway to run a certain sql file or directory of sql files before and/or after the migrations.  Our use case is that some of our metadata is kept in a single master sql file instead of through updates.  The other use case I can see for this is for some databases running pre or post migration database maintenance tasks that are related to doing migrations (e.g. PostgreSQL vacuum command)

I realize that this might be a somewhat niche feature, so feel free to shoot this down if you don't agree.

Btw, awesome product!

_Original issue: http://code.google.com/p/flyway/issues/detail?id=165_

**Comment by rotscher** [comment]
Don't know if there are other solutions around, but let me share an approach which worked in our projects using a callback: https://inftec.atlassian.net/wiki/display/TEC/2015/04/23/Flyway+repeatable%3A+yet+another+approach

**Comment by asaarnak** [comment]
Could use native support for repeative scripts folder for:
1. Views 
2. To override environment specific values after restoring from dump.
Should run when file checksum has changed.
