### ISSUE TITLE
Add a goal to maven target to validate formal correctness

### ISSUE THREAD

**Issue by pauxus** [flyway/flyway#804]
It would be useful to have a maven:check goal which tests the configuration and the provided migrations without connection to a database (i.e. do they follow the naming conventions, are there no double definitions of the same version etc.).

This goal could also optionally compare against a text file containing checksum (and create or ammend this checksum.file).

This would be useful in cases where the migration is provided as separate archive and installed by system operations.

**Comment by axelfontaine** [comment]
I decided not to pursue this at this moment.
