### ISSUE TITLE
Use guice (or any other dependeny injection framework)

### ISSUE THREAD

**Issue by pauxus** [flyway/flyway#808]
Hi Axel!

Just to start a discussion. What about introducing a dependency injection framework (guice) for say 4.0? 

This would introduce another dependency (which would be needed to be shaded in, I think), but offer some advantages:

In addition to make the code clearer in some places (especially reduce the large constructor calls), it would also allow jdbc migrations, custom resolvers and callbacks to access configuration data in a much more flexible way (without the need for an addtional interface like proposed in #805).

Cheers,

Stephan

**Comment by emaillenin** [comment]
+1 for injecting retrofit clients into JDBC migrations.
