### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by steveteng** [flyway/flyway#810]
Is there a timeline for supporting mongodb?

**Comment by kumlien** [comment]
+1

**Comment by pbelmann** [comment]
+1

**Comment by Scatchell** [comment]
+1

**Comment by planadecu** [comment]
+1

**Comment by taoli717** [comment]
+1

**Comment by miffels** [comment]
+1

**Comment by jterhune** [comment]
+1

**Comment by dasAnderl** [comment]
+1

**Comment by marcuslinke** [comment]
+1

**Comment by sharpner** [comment]
+1

**Comment by tazio** [comment]
+1

**Comment by gionn** [comment]
+1

**Comment by manuelmazzuola** [comment]
+1

**Comment by abhelaksh** [comment]
+1

**Comment by pjelar** [comment]
+1

**Comment by aRakhunJang** [comment]
+1

**Comment by savulchik** [comment]
+1

**Comment by chafikhnini** [comment]
+1

**Comment by MichaelNesterenko** [comment]
+1

**Comment by wa1demar** [comment]
+1

**Comment by sharpner** [comment]
is #998 relevant for this?

**Comment by niothiel** [comment]
+1

**Comment by s3tqr2w** [comment]
+1

**Comment by xala3pa** [comment]
+1

**Comment by FinalGuy** [comment]
+1

**Comment by cworks** [comment]
+1

**Comment by axelfontaine** [comment]
@cworks Thanks for the 1000th star. Please get in touch by email...

**Comment by cworks** [comment]
Howdy Axel,

1000 stars…I’d say folks want Mongo in the mix :-)

Just starting to look at flyway and work through some tutorials.  I’m not a DBA but have a Java background and I love love love the usefulness, simplicity and flexibility of flywaydb.  Hoping to introduce it into our development environment at work.


Good stuff…keep up the good work,
~Corbett

**Comment by roykachouh** [comment]
+1

**Comment by vlapo** [comment]
+1

**Comment by liqweed** [comment]
+1

**Comment by mactanner** [comment]
+1

**Comment by moleksyuk** [comment]
+1

**Comment by fernando-romero** [comment]
+1

**Comment by rs6g10** [comment]
+1

**Comment by ymauray** [comment]
+1

**Comment by knes1** [comment]
+1

**Comment by abhelaksh** [comment]
<body

**Comment by arthurportasptc** [comment]
+1

**Comment by Journerist** [comment]
+1

**Comment by lordofthejars** [comment]
+1

https://dzone.com/articles/mongodb-incremental-migration

**Comment by niekname** [comment]
+1

**Comment by rinoto** [comment]
How many +1 must a man write down, befooore he gets Mongo migration support...
The answer my friend is flyway in the wind, the aaaanswer is flyway in the wind....

**Comment by jamiemjennings** [comment]
+1

**Comment by connollyst** [comment]
+1

**Comment by juanpablof** [comment]
+1

**Comment by oltoko** [comment]
+1

**Comment by thotro** [comment]
+1

**Comment by lverledens** [comment]
+1

**Comment by rinoto** [comment]
For the interested, as it seems that this issue is not going to get fixed in the short run, I have created a "mongo schema migration tool" that, although of course not sophisticated as flyway, it does what it needs to do:  https://github.com/rinoto/migramongo

**Comment by brennan-collins** [comment]
I've been working on adding mongo integration, if anyone is interested in checking it out or has any recommendations on what can be added, you can find it here: https://github.com/brennan-collins/flyway/tree/mongoIntegration

**Comment by adomorenok** [comment]
+1

**Comment by aadrian** [comment]
+1

**Comment by khatkar** [comment]
Working with @brennan-collins to finish this up. Almost there. Please refer to https://github.com/khatkar/flyway/tree/jsMongoMigration

**Comment by khatkar** [comment]
Mongo migration feature is now production ready.  https://github.com/risksense/flyway/tree/release-4.0.3-mongodb

@axelfontaine Can you please take a look? Feedback will be appreciated.

**Comment by nedkoh** [comment]
+1 @axelfontaine Is there a chance that this feature can included in the next release? Seems to me that there is a lot of demand for this and as many of us shift from relational to NOSQL DBs this will be even more popular. MongoDB is in Gartner's magic quadrant so that will be a clear benefit for Flyway.

**Comment by jbosnjak** [comment]
+1

**Comment by massisjr** [comment]
+1

**Comment by maheshmahadevan** [comment]
Is this working

**Comment by voplex95** [comment]
+1

**Comment by agiannone** [comment]
+1

**Comment by zkendall** [comment]
+1

**Comment by joha78** [comment]
+1

**Comment by massisjr** [comment]
+1

**Comment by gprince** [comment]
+1

**Comment by MMJM** [comment]
+1

**Comment by zoltan-majzik-epam** [comment]
+1

**Comment by 9spokes** [comment]
+

**Comment by alebabai** [comment]
+1

**Comment by ezidio** [comment]
+1

**Comment by vadimich** [comment]
+1

**Comment by jamesjieye** [comment]
+1

**Comment by solairerove** [comment]
+1

**Comment by Faoxis** [comment]
+1

**Comment by fmacicasan** [comment]
+1

**Comment by pennstatephil** [comment]
+1

**Comment by kilmore** [comment]
+1

**Comment by TheRealMarcusChiu** [comment]
+1

**Comment by cbartosiak** [comment]
+1

**Comment by kirang20** [comment]
+1

**Comment by pandurangpatil** [comment]
+1

**Comment by javablick** [comment]
+1

**Comment by roberto-dynamix** [comment]
+1

**Comment by bobkilla** [comment]
+1 any news?

**Comment by giulio-sefaira** [comment]
+1

**Comment by masterBrog** [comment]
+1

**Comment by mikeehun** [comment]
+1

**Comment by oltoko** [comment]
+1

**Comment by ElenaTarasova** [comment]
+1

**Comment by burtsevyg** [comment]
+1

**Comment by adastrov** [comment]
+1

**Comment by cameron-r** [comment]
+1

**Comment by norfolk-gtr** [comment]
+1

**Comment by Hronom** [comment]
+1

**Comment by dcdh** [comment]
+1

**Comment by sharonYoobic** [comment]
+1

**Comment by neolytian** [comment]
+1

**Comment by joshiatxcira** [comment]
+1

**Comment by NetLord8** [comment]
+1

**Comment by Sinouplen** [comment]
+1

**Comment by chefhoobajoob** [comment]
+1

**Comment by vepo** [comment]
+1

**Comment by huzeyfeborazan** [comment]
+1

**Comment by iarriola** [comment]
+1

**Comment by douglasjam** [comment]
+1

**Comment by dream83619** [comment]
+1

**Comment by martinaware** [comment]
+1

**Comment by khatkar** [comment]
https://github.com/flyway/flyway/issues/810#issuecomment-264031798

**Comment by cwiejack** [comment]
+1

**Comment by thecaddy** [comment]
+1

**Comment by Taller** [comment]
+1

**Comment by koneru9999** [comment]
+1

**Comment by NayanSrivastav** [comment]
+1

**Comment by kumarRaj** [comment]
We should get this. Has been open for a very long time.

**Comment by devsteff** [comment]
+1

**Comment by MeghaNagari** [comment]
+1

**Comment by alexandredavi** [comment]
+1

**Comment by rafael-s-rocha** [comment]
+1

**Comment by toorajam** [comment]
+1

**Comment by AmitArie** [comment]
+1

**Comment by mestrega** [comment]
+1

**Comment by SherjeelSikander** [comment]
+1

**Comment by mtablado** [comment]
+1

**Comment by Michstumpf** [comment]
+1

**Comment by jblacker** [comment]
+1, but more importantly are we assuming that PR #1482 is dead?  If so, I am thinking about forking from that PR.  Does anyone knows if it was in working condition prior to the branch going stale?

I can work on eliminating those conflicts on the branch at least.

Longer term though I'd really like to see that changeset abstracted further to allow for implementation of generic NoSQL databases with different runners such as this one that allows for javascript files.

**Comment by khatkar** [comment]
@jblacker I wrote #1482 and it is certainly dead. Refer to my comment earlier https://github.com/flyway/flyway/issues/810#issuecomment-264031798

I confirm that https://github.com/risksense/flyway/tree/release-4.0.3-mongodb  is working. I have used it in production. Feel free to fork but keep in mind that newer flyway release has changed quite a bit so it won't be easy to rebase on new code.

**Comment by jblacker** [comment]
@khatkar Why'd that PR end up dying?  I didn't see any back & forth or comments on why it was opened for so long.  

My plan (although no idea on timeline here) is to fork from master in _this_ repo, and implement what you did for Mongo in a database agnostic way splitting SQL & NoSQL instead of SQL & Mongo specifically.  Then cherry picking some of your changes back in to support MongoDB.  If I do this would you be able to test the Mongo & Spring specific stuff?  I'd like to create an implementation to support DynamoDB specifically with enough abstraction to add whatever NoSQL database / NoSQL scripting language (i.e. MongoScript)

**Comment by khatkar** [comment]
@jblacker Nobody from the Flyway community reviewed that PR. I was maintaining it for couple of months, resolving conflicts and updating code, but no review from Flyway was the main reason I stopped updating my PR. If you start nosql support I can help with the code review. But, first confirm with the repository maintainers if this is something they will be willing to merge.

**Comment by jblacker** [comment]
@khatkar Great point.

@flyway / @boxfuse / @axelfontaine or any active maintainers - Would a feature that implements NoSQL support in an extendable fashion (starting with MongoDB & DynamoDB) be considered for review & merge?  Any additional dependencies to support this would be strictly optional.

**Comment by jamesjieye** [comment]
Anyone tried https://github.com/mongeez/mongeez, is it good? 

I haven't checked it out yet. But a migration tool fro NoSQL is definitely a NEED!!

**Comment by Hronom** [comment]
@jamesjieye check the latest commit there (2016 year) seems like not supported properly...

Right now there is no supported solutions for migration tool for MongoDB.

**Comment by jamesjieye** [comment]
@Hronom Thank you for the heads up. 

Just wondering what makes supporting migration of NoSQL database like MongoDB, DocumentDB so hard? Is it because of the schema-less?

For us, we always create `$jsonSchema` to define the structure of the document in each collection. Schema-less doesn't mean that we do not need to properly define database's structure. That would make the migration really hard. On the other hand, when we have not strictly, but properly defined schema by using `$jsonSchema`, would migration still be that hard?

The steps of how Flyway migrates described here https://flywaydb.org/getstarted/how is very similar to how we are managing the migration of MongoDB schema right now, although we do that manually, which is not ideal.

Anyone interested in building a migration tool specific for MongoDB, DocumentDB?

**Comment by olvjma** [comment]
https://github.com/cloudyrock/mongock forked from mongobee. Springboot issues :(

**Comment by milifili** [comment]
+1

**Comment by egnaf** [comment]
+1

**Comment by jope35** [comment]
+1 for dynamodb

**Comment by javiermrz** [comment]
+1

**Comment by tleveque** [comment]
+1

**Comment by PhilippS93** [comment]
+1

**Comment by rivierej** [comment]
+1

**Comment by phauer** [comment]
To all the "+1" people: Have you checked out [Mongock](https://github.com/cloudyrock/mongock)? I guess that's what you are looking for.

**Comment by dvarlashyn** [comment]
+1

**Comment by wagner-morais** [comment]
+1

**Comment by mostafa-zaid** [comment]
+1

**Comment by rushang7-eGov** [comment]
+1

**Comment by adityajain311995** [comment]
+1

**Comment by Jaquark** [comment]
+1

**Comment by grvsachdeva** [comment]
+1

**Comment by almogtavor** [comment]
+1

**Comment by gekalogiros** [comment]
+1

**Comment by lynch19** [comment]
+1

**Comment by augustoscher** [comment]
+1

**Comment by boris-cleo** [comment]
+1

**Comment by ahmed-lotfy** [comment]
+1

**Comment by dcdh** [comment]
Use PostgreSQL with jsonb column instead. Works fine.

**Comment by NMikle** [comment]
@Barry-RG, seems the dependency suggested in the guide is broken as it relies on the library that could not be found anywhere except for direct download from the JetBrains.com website
Here is output trying to follow the guide:
```
test-project:main: Could not find com.github.kornilova203:mongo-jdbc-driver:1.18.
Required by:
    project : > org.flywaydb:flyway-database-mongodb:10.4.0
```
The problematic code from the pom.xml file in https://github.com/flyway/flyway/blob/main/flyway-maven-plugin/pom.xml:
```
<dependency>
            <groupId>com.github.kornilova203</groupId>
            <artifactId>mongo-jdbc-driver</artifactId>
            <version>1.18</version>
</dependency>
```
The missing dependency seems to be mongoDb driver from this page: https://www.jetbrains.com/datagrip/jdbc-drivers/
Not sure where exactly it is supposed to be downloaded from, I've tried couple of Jetbrains repositories from this page https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html#specify-the-repository-url but none of them seem to contain desired library.

This happens both when you do
```
implementation("org.flywaydb:flyway-database-mongodb:10.4.0")
```
in your build.gradle(.kts) configuration and when trying to build this library from source.

**Comment by mmwinther** [comment]
@NMikle I resolved this in the following way (Configuration for Gradle with the Kotlin DSL):

1. Download the standalone jar file from https://github.com/DataGrip/mongo-jdbc-driver/releases
2. Move the JAR to a directory in your repo (e.g. `libs`)
3. Importantly, you must *rename* the jar to `mongo-jdbc-driver-1.19.jar` (with the correct version). This is because the name of the jar must correspond to the name of the artifact so that Gradle can resolve it locally.
4. Include the relevant local directory as a repository in `build.gradle.kts`
     ```
     repositories {
         mavenCentral()
         flatDir {
             dirs("libs")
         }
     }
     ```
5. Include the dependency in the normal way `implementation("com.github.kornilova203:mongo-jdbc-driver:1.19")`
