### ISSUE TITLE
Improve the locations syntax for the Gradle plugin

### ISSUE THREAD

**Issue by mauromol** [flyway/flyway#813]
Right now, I must specificy this:

``` groovy
flyway { locations = [ 'filesystem:sql/new'] }
```

What is unexpected is that this does not work:

``` groovy
flyway { locations = 'filesystem:sql/new' }
```

It would be convenient to use when an only location is needed. In Groovy this is natural.

Also, all over Gradle the usual way to specify files or locations is through the use of `Project.file(...)`: I think this should be allowed as an alternative to the 'filesystem:...' string syntax.

Accepting also a `FileCollection` would then be great (as per `Project.files(...)` or `Project.fileTree(...)`), but I think this would require a change to the Flyway core to be correctly supported.

**Comment by axelfontaine** [comment]
Closing as this is a very niche requirement with very little added value that has seen no additional support over the last 4 years.

**Comment by mauromol** [comment]
It's a pity. The use of files and file collections is the standard way of specifying paths and file resources in Gradle, rather than a niche requirement :-(
