### ISSUE TITLE
If-condition in scripts

### ISSUE THREAD

**Issue by yudindi** [flyway/flyway#818]
Hi all,

I suggest to introduce conditional constructs like {if:var}SOME SQL{endif} in addition to the simple variable substitution avialble in FlyWay. Below is my reasoning.

It's a common case to have a local Oracle XE development database on developer machines and deploy the application to Oracle Enterprise DB for other environments. Once the applications starts to make use of Oracle partitioning, it is impossible to run the same DDL on XE (since XE does not support partitioning).
For example:
CREATE TABLE FOO (ID NUMBER(10), TEXT VARCHAR2(100)) PARTITIONED BY ID INTERVAL(1);
CREATE INDEX IDX_FOO (ID) LOCAL;
These features are used mostly for performance which means that if we had omitted them, the application would still function normally. That makes it a good compromise to use no partitions on local XE and have them on remote environments.

As I understood, the recommender way to solve that in FlyWay is to have different changes for different databases, eg. xe and nonxe. However, I see it inconvenient in this case. Suppose we have a table with 100 columns, partitioned by the first column. If we create two changes for xe/nonxe, the files would be identical except for the last line, which clearly breaks DRY principle.

Another option is to have a preprocessor step to change all files by some regexp, however, I expect it can increase complexity of maven builds and introduce stale files issues (if you decide to run your changes on a different db without running some "mvn clean package").

The best way I can think so far is to introduce ${if:variable} conditional into FlyWay next to simple variable substitution. E.g. your script would look like:
CREATE TABLE
<100 columns here...>
${ifnot:xe} PARTITION BY ID RANGE(1) ${endif}
I suggest to use ${if:!var} or ${ifnot:var} constructs instead of ${if:nonxe} because if someone forgets to set xe var, it would fail trying to create a partition. However, if we forget to put a nonxe flag, it will pass silently and create a non-partitioned table in production, and that is much worse.

What are your thoughts on that?

**Comment by axelfontaine** [comment]
I agree with @davidkarlsen 's proposed workaround. Closing.
