### ISSUE TITLE
Applying a hotfix migration

### ISSUE THREAD

**Issue by gekart** [flyway/flyway#821]
In the case of a hotfix the flyway admin wants to "manually" apply a single migration. 

Say in PROD v10 is newest and in TEST v20. The hotfix consists of v10.1. Now, in order to get v10.1 applied on TEST one needs to use outOfOrder. This works. 

However, I do not want outOfOrder to be active in general in our automatic deployment workflow, so I need to turn it on for the hotfix and then turn it off. I need to make precautions that there is no other ignored migration on the filesystem. In a very complex delivery scenario with test data and master data deliberately left as "ignored", outOfOrder ends up being indeterministic. The current approach is to delete the migration filesystem, copy the hotfix and then apply the migration outOfOrder.

When you know what you are doing, a simple -hotfix=v10.1 might be the most elegant solution. The migration is marked as outOfOrder on TEST and succesful on PROD.

A comment on the determinism of the approach: it is no less deterministic than outOfOrder.

**Comment by axelfontaine** [comment]
Closing old issue.
