### ISSUE TITLE
Unable to set default schema in Flyway when using Oracle remote links

### ISSUE THREAD

**Issue by dwclark** [flyway/flyway#832]
I have a problem in working with Oracle. Specifically, setting the default schema in the session is causing me to be unable to use database links. I am using the Flyway API because my situation requires somewhat complicated behavior during the migration.  My problem is as follows:
- I am using mutliple schemas and setting the correct properties in the Flyway class.  Let's call them SCHEMA1, SCHEMA2, and SCHEMA3
- I log in as a user with SYSDBA privileges, in this case the user name is CIUSER. The DataSource logs me in as a SYSDBA, which means the default schema is SYS.
- I have a remote database link which I use in the migration.  Let's call it REMOTE_LINK.  This allows me to write insert statements like "INSERT INTO foo SELECT \* FROM foo@REMOTE_LINK". This remote link is in the SYS schema and is accessible by CIUSER.
- When Flyway performs the migrations, it issues an "ALTER SESSION SET CURRENT_SCHEMA=SCHEMA1", meaning the default schema is SCHEMA1.
- This results in Oracle not locating REMOTE_LINK.  The user CIUSER is correct, but Oracle is now looking for REMOTE_LINK in SCHEMA1.  It is not there.  This problem is extremely difficult to diagnose because the schema and the user appear to be correct initially.  I think this is partially the fault of Oracle, it should look for REMOTE_LINK in SYS if the user is SYSDBA, but for whatever reason it does not.

The ideal solution for me would be to keep the default schema as SCHEMA1 for the Flyway connection that does updates to the metadata table, but NOT execute "ALTER SESSION SET CURRENT_SCHEMA=SCHEMA1" for the connection performing the actual migrations. Another solution would be to have the Flyway class support a property to not change default schemas for the connection performing the migrations.

**Comment by MikielAgutu** [comment]
@dwclark This is pretty old now. Is it still relevant? Does the workaround unblock you?

This looks fairy tricky to fix, and quite niche. Perhaps it should be logged as a limitation of Flyway's Oracle support in the docs.

**Comment by jaa2261** [comment]
We have the same issue and have had to use the workaround of creating a stored proc owned by the schema that runs dynamic sql to create the link. 
There's a similar workaround required for when you have materialized views.
If the fix isn't straight forward I think it would be good to at least properly document the workarounds.

**Comment by DoodleBobBuffPants** [comment]
We will be documenting this limitation for now, see https://github.com/flyway/flywaydb.org/pull/272
