### ISSUE TITLE
Support Liquibase migration steps

### ISSUE THREAD

**Issue by chrisdutz** [flyway/flyway#835]
Hi,

I had developed a solution for automatic db-schema migration about 4-5 Years ago. In this I could define a migration almost the same way I can with flyway (I too have schema and java migration steps), but with one major difference. I specify my migration steps using Liquibase (http://www.liquibase.org/). By this the migrations can work on any database platform and the scripts don't have to be provided for different db-types. Another thing I don't know if Flyway supports this, is conditional step execution. So I could have steps only executed if the precondition for this step is met.

I was thinking about open-sourcing my library, but thought that it would be cooler if I didn't spawn yet another db-migration tool, but mabe to add my distinguishing feature to a popular already existing tool.

Would you guys be interested in me helping out to add Liquibase migration steps to Flyway?

Chris

**Comment by MikielAgutu** [comment]
@regis-leray @chrisdutz This is pretty old now. Do you still think it's valuable?

**Comment by chrisdutz** [comment]
Well I did really like the db-agnostic way of defining migration steps using liquibase. But I have to admit I haven't really been using RDBs for quite some time now ;-) Just close it, if I run into this again I can just open a new one together with a PR.
