### ISSUE TITLE
Splice Machine support

### ISSUE THREAD

**Issue by soneymathew** [flyway/flyway#837]
www.splicemachine.com
Please can you confirm if any special changes are needed for supporting this hbase backed rdbms ?
Or can we assumed that since they use derby as developer interface all scenarios will get automatically supported ?
If support is official please consider adding that DB support to the webpage

disclaimer : I am not working with them , I am planning to learn and use it, so evaluating it.

**Comment by alextercete** [comment]
Closing due to lack of interest.
