### ISSUE TITLE
Flyway as an abstraction for migrating anything from one version to another

### ISSUE THREAD

**Issue by derylspielman** [flyway/flyway#838]
Hey, Axel! At the last local Java meetup I went to on continuous delivery a question came up which I thought was interesting, "What tools are there to help put continuous delivery in place?" Unfortunately my answer was that there is no one stop shop to implement continuous delivery and you must "piecemeal" various solutions together unless using commercial tools like Amazon Opsworks. Flyway takes a known version and runs migrations up to a target version. I am finding a need in the CD space for an abstraction of that concept to be applicable to any kind of target and not just a database.

For example I have couchdb migration scripts and views to create as part of a release, ldap  modifications/additions that needs versioning alongside my application, ad-hoc deployment steps to run some ETL job, and configuration management updates using puppet/chef that should run one version to the next. The list goes on.

I can see Flyway's concepts more as an abstraction layer that basically maintains some "thing" and its version, and you extend it to plug in your "thing" to be migrated. One of these "things" may be a database, another thing could just be shell scripts to run, etc. Do you agree that there is need for this abstraction when implementing any part of CD and can you see Flyway used in this context instead of just db migrations?

**Comment by smoyer64** [comment]
I know this is an old issue but I've been working on "shoe-horning" CouchDB migrations into FlywayDB.  Obviously you're never going to do SQL migrations using an NoSQL database but there's so much value in FlywayDB via the Java migrations.

I understand the risk of diluting FlywayDB as a product but the ability to extend the FlywayDB's DbSupport would allow those of us who wanted to migrate non-SQL databases (or almost anything?) to create new products based on FlywayDB.  It's definitely very connection and JDBC oriented which makes it a bit more of a challenge yet.

Right now I'm essentially forcing an alternate JDBC driver to be loaded that says it's "SQLite" but actually performs some of the functions against CouchDB and fakes the rest.  It's a truly horrible piece of code.

**Comment by Joosakur** [comment]
This kind of generic support for storing the state of versioned migrations and accessing it e.g. through a REST API so that multiple micro-services could utilize it as a shared resource without having their own DB would be really really nice.
