### ISSUE TITLE
Multiple Modules Support in Flyway

### ISSUE THREAD

**Issue by manishsharmajpr** [flyway/flyway#848]
I want to create only one schema one table ( for schema version control ). This schema may contains some modules, these modules should be managed separately.
eg:
  Common : 1.0.0 -> 1.1.0 -> 1.2.0
  user management : 1.0.0 -> 2.0.0
  authentication : 1.0.0 -> 1.0.1

That means that we have an application with multiple modules, each module has its own version control. Than we could upgrade one of these modules without know the version of other modules.

How can we achieve this with flyway ? I do no want to create different table for each module.

**Comment by gsinghab2** [comment]
> This is not supported. If you have different modules with different lifecycles, you will need different Flyway instances, each with their own metadata table.
> 
> Works as designed.



> , you will need different Flyway instances, each with their own metadata table.

Can you elaborate on this, what do you mean by different instances of flyway. I am using gradle plugin and tries using different flyway table for different modules but got following error instead:

```
Error occurred while executing flywayMigrate
  Found non-empty schema(s) `schemaName` but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
```
