### ISSUE TITLE
Allow for manually setting database type

### ISSUE THREAD

**Issue by cthielen** [flyway/flyway#849]
I'd like Flyway to migrate in my testing environment just as it does in my production environment, except my production environment uses MySQL and my testing environment uses H2 with MySQL mode turned on.

Flyway is not aware of MySQL mode however, and generates the schema_version table designed for H2, while H2 is only validating MySQL-style commits.

This problem could be avoided if Flyway didn't try to guess the database type but instead let me set it.

**Comment by axelfontaine** [comment]
This seems to work now. Can you build the latest version of the sources and confirm?

**Comment by axelfontaine** [comment]
Closing due to lack of response from reporter.
