### ISSUE TITLE
Better support for DDL statements that cannot run within a transaction

### ISSUE THREAD

**Issue by pards** [flyway/flyway#851]
Overriding DbSupport.supportsDdlTransactions does not prevent FlyWay from attempting to execute DDL statements in a transaction.

I was trying to implement Netezza support, but found that ALTER TABLE statements fail when executed in a transaction.

See
http://www-01.ibm.com/support/knowledgecenter/SSULQD_7.1.0/com.ibm.nz.dbu.doc/r_dbuser_ntz_sql_func_categories_transaction_control.html

**Comment by kryptt** [comment]
Is there currently any way to get arround this ?

I am getting `ERROR: ALTER TYPE ... ADD cannot run inside a transaction block` for a postgres migration myself..

**Comment by pards** [comment]
Not to my knowledge.
Netezza is forked from Postgres, so it sounds like the same problem

**Comment by kryptt** [comment]
I stumbled onto the limitations section of the postgres page for your docs: 
http://flywaydb.org/documentation/database/postgresql.html

and managed to re-write the query in a transaction safe way (pasting it here, if someone else stumbles across this: 
```sql
ALTER TYPE action_type RENAME TO stale_action_type;

CREATE TYPE action_type AS ENUM(
  'loginFailure',
  'loginSuccess',
  ...
);

ALTER TABLE mytable ALTER COLUMN action TYPE action_type USING action::text::action_type;

DROP TYPE stale_action_type;
```

**Comment by trygvis** [comment]
@kryptt Thanks!

For the archive, you can use full expressions for the `USING` clause:

``` SQL
ALTER TABLE foo
ALTER COLUMN bar TYPE new_type USING (
CASE bar :: TEXT
WHEN 'AAA'
  THEN 'BBB'
ELSE bar :: TEXT END) :: new_type;
```

**Comment by realsonic** [comment]
@kryptt Thanks a lot for W/A. I have the same problem too.

**Comment by axelfontaine** [comment]
This has been fixed for PostgreSQL via auto-detection. Please open new issues for other databases.
