### ISSUE TITLE
Custom tablespace for schema history table

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#865]
- Optional support for databases that have this feature.
- Use default tablespace unless set
- Ignored for databases that don't support this

**Comment by crgardner** [comment]
Is there now first class support in Flyway to specify the tablespace in Oracle?  If so, how do you configure it?

**Comment by sbelan** [comment]
@axelfontaine, I tried custom table space with latest beta version and its still failing at the time of alter table. Please find below details.
Flyway gradle version: 6.0.0-beta2

Before using beta version I was getting below exception
`ERROR: permission denied for tablespac xyz`

Now I am using beta version and provided parameter **flyway.tablespace=xyz** and getting below exception

`
Migration  failed
  -----------------
  SQL State  : 42501
   Error Code : 0
  Message    : ERROR: permission denied for tablespace xyz
   Location   :  ()
  Line       : 14
  Statement  : ALTER TABLE "postgres"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank")`

Could you please help?
