### ISSUE TITLE
DB2 schema clean fails for expression-based index

### ISSUE THREAD

**Issue by crannym** [flyway/flyway#867]
On a DB2 schema calling flyway.clean() fails with 
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-658, SQLSTATE=42917, SQLERRMC=IDX_CUSTOMER_NAME_1_V, DRIVER=4.17.29.

In DB2, creating an expression-based index:-
CREATE INDEX IDX_CUSTOMER_NAME ON CUSTOMER(LOWER(FIRSTNAME) ASC)
also generates an associated view: IDX_CUSTOMER_NAME_V.

When dropping all schema objects, dropping views before tables results in the above error.

**Comment by jonlarsson** [comment]
I'm getting the same error with flyway 3.2.1 as well.
