### ISSUE TITLE
DI and Flyway

### ISSUE THREAD

**Issue by jochenw** [flyway/flyway#869]
Right now, it is unclear to me, if I can have Flyway to play nice with DI. More precisely, I'd like my DI system to inject into JDBC Migrations. Right now, I put the Injector into a static variable, but that doesn't seem quite right.

Suggestion: Invent a new interface, say

```
public class IObjectFactory {
Object newInstance(String pClassName);
}
```

and make the Flyway class to use that interface. A default implementation would be trivial:

``
public class DefaultObjectFactory ìmplements IObjectFactory {
protected abstract ClassLoader getClassLoader(); // Delegate to Flyway.getClassLoader().
public Object newInstance(String pClassName) {
final ClassLoader cl = getClassLoader();
if (cl == null) {
return Class.forName(pClassName);
} else {
return cl.loadClass(pClassName);
}
}

```

For Guice, I'd implement a custom implementation like this:

```

public class GuiceObjectFactory extends DefaultObjectFactory {
private final Injector injecor;

public Object newInstance(String pClassName) {
final Object instance = super.newInstance(pClassName);
injector.injectMembers(instance);
}

```


Let me know, if you'd like to see a pull request.
```

**Comment by alextercete** [comment]
Flyway 6 now allows providing a list of preinstantiated Java migrations, so you could use any DI framework to create those instances (which could have dependencies) and pass them to Flyway as part of your configuration:

>`public FluentConfiguration javaMigrations​(JavaMigration... javaMigrations)`
The manually added Java-based migrations. These are not Java-based migrations discovered through classpath scanning and instantiated by Flyway. Instead these are manually added instances of JavaMigration. This is particularly useful when working with a dependency injection container, where you may want the DI container to instantiate the class and wire up its dependencies for you.
Parameters:
`javaMigrations` - The manually added Java-based migrations. An empty array if none. (default: none)
