### ISSUE TITLE
Error using flyway command line tool when passing 'sys as sysdba' via the -user parameter

### ISSUE THREAD

**Issue by MikeTheyCallMe** [flyway/flyway#874]
When using the flyway command-line tool, the -user parameter does not properly parse "sys as sysdba". I've tried using quotes (single, double), no quotes, escape characters, special characters. Seems "sys as sysdba" gets tokenized and only "sys" is passed into the connection.

I've reviewed and replicated the code (Flyway.java, JdbcUtils, DriverDataSource) in my IDE. I found that if I double-quote the "sys as sysdba", my jdbc connection is created successfully. Else, I get:

"Unable to obtain Jdbc connection from DataSource" (from JdbcUtils) as well as ORA-28009: connection as SYS should be as SYSDBA or SYSOPER" (from oracle).

I'm using flyway v.2.2.1 and jdk 1.7

Please advise if there is a fix for this.

**Comment by minhuber** [comment]
Alex, encountered the very same issue as reported by MikeTheyCallMe

Fixed it by introducing "" for $@ in the ./flyway script and then it works "like a charm" under linux.

Current: "$JAVA_CMD" -cp "$CP" org.flywaydb.commandline.Main $@
Fixed: "$JAVA_CMD" -cp "$CP" org.flywaydb.commandline.Main "$@"

**Comment by minhuber** [comment]
just wanted to provide the very same in a merge request and discovered that this has been fixed already.
:+1:
