### ISSUE TITLE
Submit Gradle Plugin to Gradle Plugin Portal

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#895]
Before Gradle can include our plugin, we need you to fix two things: 
1. the 'gradle-plugin' attribute must be set on version level in bintray
2. plugin id should be qualified (Breaking change)

more details at http://plugins.gradle.org/submit

**Comment by davidmc24** [comment]
It's possible for a plugin to have multiple ids, which would allow this to not be a breaking change.  I've got an example of one technique to do that here:

https://github.com/commercehub-oss/gradle-avro-plugin

The basic idea is to maintain the existing `flyway-gradle-plugin/src/main/resources/META-INF/gradle-plugins/flyway.properties` file that allows use with the existing unqualified plugin id, and add an additional properties file for the new qualified plugin id.

In my example, I went one step beyond that, wrapping the plugin class to log a deprecation warning when the unqualified plugin id is used.

https://github.com/commercehub-oss/gradle-avro-plugin/blob/master/src/main/java/com/commercehub/gradle/plugin/avro/UnqualifiedAvroPlugin.java

**Comment by axelfontaine** [comment]
That's great news! That would allow for a smooth transition starting with 3.2. We could deprecate the old Id and remove it in 4.0. Is there a way for a plugin to know under which id it was used?

Would like to provide a PR?

Thanks
Axel

**Comment by davidmc24** [comment]
The way I managed awareness of the ID was to register a different class for each ID.  I'll start work on a pull request.

**Comment by davidmc24** [comment]
Now that #946 is merged, it should be possible to submit the gradle plugin to the plugin portal after the 3.2 release.

**Comment by axelfontaine** [comment]
Yes, that's the plan. Thank you again for the PR :-)

**Comment by axelfontaine** [comment]
Done -> https://plugins.gradle.org/plugin/org.flywaydb.flyway
