### ISSUE TITLE
Allow custom migration resolver to access SQL migration executor

### ISSUE THREAD

**Issue by ataastar** [flyway/flyway#897]
Hi!

I apologize if it's a solved a problem
we have fixes script structure. Example:
20141201/1_update.sql
20141201/2_update.sql
20141202/1_update.sql
..
1. So we need the possibility to resolve migration info other way instead of MigrationInfoHelper
Or
2. override SqlMigrationResolver or implement MigrationResolver
I look after to implement custom migration resolver, but it can't access the parameterized objects (dbSupport, locations, ...)
Is there a way to override SqlMigrationResolver or implement MigrationResolver and access the configured object? 
I'm sorry but I could not find any examples

Thanks in advance,
Attila

**Comment by DoodleBobBuffPants** [comment]
Solved as we allow providing your own [MigrationResolver](https://flywaydb.org/documentation/configuration/parameters/resolvers)
