### ISSUE TITLE
Flyway baselines new schemas, since they always have a schema_version table.

### ISSUE THREAD

**Issue by benheilers** [flyway/flyway#898]
I have a tenant-per-schema system, where each schema has it's own schema_version table.

So I already have some existing schemas, but new schemas will be added as well.  My integration tests to create new schemas are failing.  I see it is because of this code in Flyway.java starting at line 929:

                new DbSchemas(connectionMetaDataTable, schemas, metaDataTable).create();

                if (!metaDataTable.hasBaselineMarker() && !metaDataTable.hasAppliedMigrations()) {
                    List<Schema> nonEmptySchemas = new ArrayList<Schema>();
                    for (Schema schema : schemas) {
                        if (!schema.empty()) {
                            nonEmptySchemas.add(schema);
                        }
                    }

Line 929, the call to create(), ends up creating the table SCHEMA_VERSION with the schema_marker.
Specifically, the call MetaDataTableImpl.addSchemasMarker() creates this table just after the schema is created.

Line 934, the call to empty(), returns false, because the schema does have this one single table SCHEMA_VERSION.

So now we think this brand new schema is non-empty, and we end up baselining the schema.  Then the brand new migration script fails because it is trying to add a column to a table which should have been created in the baselined scripts.

Is this a bug, or am I mis-using baseline somehow?  I want my existing schemas to be baselined up to a certain point without my future schemas failing to create.

**Comment by axelfontaine** [comment]
It turns out we even had a testcase for this actually validating the wrong behavior!

Thanks for reporting. Fixed.

Cheers
Axel
