### ISSUE TITLE
Command-line: -q switch for quiet mode

### ISSUE THREAD

**Issue by plentz** [flyway/flyway#915]
please add an option to be less verbose. instead of:

```
Flyway (Command-line Tool) v.3.1

Database: jdbc:mysql://foo.com:1433/ (MySQL 5.6)
Validated 8 migrations (execution time 00:00.028s)
Current version of schema `bar`: 7
Schema `bar` is up to date. No migration necessary.
```

maybe outputting only if something goes wrong. it could be very useful mainly if you run a lot of migrations in batch

**Comment by axelfontaine** [comment]
Yes, this makes sense.

Since we already have
-X to set the log level to DEBUG

this would now add
-q to set the log level to WARN

Pull request welcome.

**Comment by sanjayd** [comment]
Created PR #920 - if that looks good, I can create a corresponding PR for flywaydb.org

**Comment by plentz** [comment]
you guys rock :)
