### ISSUE TITLE
After running flywayMigrate in SBT there is no straightforward way to know current db version

### ISSUE THREAD

**Issue by j-unior** [flyway/flyway#917]
We migrate from MVN to SBT. One of the features that we used in MVN plugin was `${flyway.current}` that we used to write inside the *MANIFEST.MF* file (and used it for support info in runtime). After reading the SBT plugin doc I was unable to find an easy way to get the current db version, so it could be nice-to-have task that returns it.

**Comment by axelfontaine** [comment]
This is indeed currently only available for Maven, and I agree it would make sense for SBT too.

Pull request welcome.

@cdedie Thoughts?

**Comment by cdedie** [comment]
I have a look at the maven implementation and will provide a pull request with something similar.

**Comment by j-unior** [comment]
In fact I had forked and  wrote a task that should work, yet did not have time to check it. If you're busy with other tasks you can leave it to me.

**Comment by cdedie** [comment]
Perfect. Go ahead!

**Comment by j-unior** [comment]
Ok, I after testing this issue on our build I've come to some conceptional issue. As I mentioned earlier we put our current DB version in _MANIFEST.MF_, that means it happens in _package_ scope. It was easily done in maven when we could run the _migrate_ goal in whatever phase we'd like to, so we did that before our tests used to run (we were also testing the DAO's on the way). Unfortunately in SBT things aren't that easy, because all SBT plugin tasks are bound to _Runtime_ scope, which on the one hand makes a perfect sense to me (if you want to update your remote server before deployment), yet it becomes less convenient if you want your migrations happen before the tests run. In fact we did a little hack, to make the migrations happen before the tests, just running them in a separate SBT test listener (well, now I understand that I can simply take the DB version there and write it somewhere in the target dir, instead of having a dedicated task). I will pull request the couple lines of the task itself, but I would like to know your opinion regarding the task scopes (whether _Runtime_ is the only appropriate way). Thanks :-)

**Comment by cdedie** [comment]
Here is the pull request for multiple Configuration support:
https://github.com/flyway/flyway/pull/891
Runtime and Test are already predefined and you add additional Configuration in your build definition.

flywayInfo should return the MigrationInfoService. 
https://github.com/cdedie/flyway/commit/439ee7e5d206af5775d9da8434141ba233f32400

That way you can define your own task
writeVersionFile <<= (flywayInfo in Runtime, streams) map {
  (info, s) => s.log.info(info.current().getVersion()
},
 
@j-unior What do you think?

**Comment by j-unior** [comment]
Great! It's the best decision indeed.

**Comment by axelfontaine** [comment]
Fixed. Thanks @cdedie !
