### ISSUE TITLE
Explicitly drop Views then doing a Flyway.clean() on a PostgreSQL db

### ISSUE THREAD

**Issue by gergelyszakacs** [flyway/flyway#918]
Database Views are not dropped when a Flyway.clean() is issued. If the migration scripts baseline the database with some existing tables that cannot be touched and just adds some Views (probably in a different schema than the tables themselves) then the clean() call will leave those Views in place. So a new feature is needed that explicitly drops these Views.

**Comment by axelfontaine** [comment]
I am trying to understand your exact scenario.

DB with existing Schema A with table A1
Flyway.schemas set to B
Flyway creates schema B and a migration adds a view B1 that maps to A.A1
Flyway.clean (schema B only) does not drop B1

Is this correct?

**Comment by gergelyszakacs** [comment]
Hi Axel,

Thanks for getting back to me so soon. Yes, this is my scenario.


--
Gergő

**Comment by logicbomb** [comment]
:+1: the fix as implemented by @gergelyszakacs  resolves the issue

**Comment by teicher** [comment]
Hi Axel, looks to me like this will not work for materiaized views. (need to call DROP MATERIALIZED VIEW ...)
Cheers, Tom.

**Comment by axelfontaine** [comment]
@teicher Please file a new issue and include a script that Flyway fails to clean.

**Comment by teicher** [comment]
Okay Okay, with 3.2.1 it works even for materialized views. But not due to 1dae524, I'd say ;-)

**Comment by teicher** [comment]
Okay, so the dependency between views (and materialized ones) is the problem:
https://github.com/flyway/flyway/issues/1129
