### ISSUE TITLE
After init: java.lang.IllegalArgumentException: No enum constant org.flywaydb.core.api.MigrationType.BASELINE

### ISSUE THREAD

**Issue by BjoernKW** [flyway/flyway#925]
After executing mvn flyway:init and then running migrations via Java code for the first time I get the following error:

java.lang.IllegalArgumentException: No enum constant org.flywaydb.core.api.MigrationType.BASELINE

Changing the value of the type column to INIT in the first row in schema_version fixes this but it'd be great if Flyway had a MigrationType.BASELINE type so init can be done with mvn and migrations via code later on.

**Comment by axelfontaine** [comment]
Please upgrade to 3.1 and try again. Did it work?

**Comment by BjoernKW** [comment]
You’re right I’ve been using 3.0 in the Java code. I can’t test it right now but from how MigrationType looks with 3.1 it should work. Thanks.
