### ISSUE TITLE
 invalid sha1 on dependency download

### ISSUE THREAD

**Issue by minecslab** [flyway/flyway#926]
I'm encountering download problem on flyway-sbt. This is the log:

[warn] problem while downloading module descriptor: http://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/3.1/flyway-sbt-3.1.pom: invalid sha1: expected=<!doctype computed=04561590522d6523938492beddc36a05e538f480 (1177ms)
[warn] 	module not found: org.flywaydb#flyway-sbt;3.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/mine123/.ivy2/local/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/flywaydb/flyway-sbt_2.10_0.13/3.1/flyway-sbt-3.1.pom
[warn] ==== Sonatype OSS Snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/flywaydb/flyway-sbt_2.10_0.13/3.1/flyway-sbt-3.1.pom
[warn] ==== Scalaz Bintray Repo: tried
[warn]   http://dl.bintray.com/scalaz/releases/org/flywaydb/flyway-sbt_2.10_0.13/3.1/flyway-sbt-3.1.pom
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.1/ivys/ivy.xml
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/flywaydb/flyway-sbt_2.10_0.13/3.1/flyway-sbt-3.1.pom
[warn] ==== Flyway: tried
[warn]   http://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/3.1/flyway-sbt-3.1.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.flywaydb#flyway-sbt;3.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.flywaydb:flyway-sbt:3.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn]

It used to work on my local and our jenkins but now it fails.

**Comment by axelfontaine** [comment]
Please try again. Nothing has changed on this end.

**Comment by axelfontaine** [comment]
My suspicion is that this happened while GitHub pages was updating the site for some unrelated change.

I'll look into moving the repo to bintry in the future to avoid this: #927

**Comment by j-unior** [comment]
We're falling on the same issue. A workaround for meanwhile: upload to amazon S3 bucket with the following layout: org/flywaydb/flyway-sbt_2.10_0.13/3.1/flyway-sbt-3.1.jar and org/flywaydb/flyway-sbt_2.10_0.13/3.1/flyway-sbt-3.1.pom and add your bucket as a repository.
