### ISSUE TITLE
Move SBT plugin repo to Bintray

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#927]

**Comment by j-unior** [comment]
Any estimations on this subject? May I help you somehow?

**Comment by axelfontaine** [comment]
There is not much you can do to help. The SBT is currently uploaded manually on the flywaydb.org repo as part of the release process. Ideally I would like everything to be on Maven Central. However due to SBT's inability to consume plugins using the naming convention enforced by Maven Central, we have to use an alternative. As we found out the flywaydb.org solution is not without issues, so now we'll try bintray, but unfortunately it will be a manual upload as well.

**Comment by axelfontaine** [comment]
This should not be necessary anymore with the new hosting setup.
