### ISSUE TITLE
Apache Phoenix Support

### ISSUE THREAD

**Issue by jmahonin** [flyway/flyway#929]
Phoenix (http://phoenix.apache.org/) is an open source relational DB over HBase that exposes a JDBC driver.

I've got a working implementation as well as unit tests that I'll be putting in a pull request. It works against a stand-alone Phoenix cluster, but the tests run against an in-memory HBase cluster. Some comments from the commit message below:

It has been set up as an EmbeddedDB, although the Phoenix tests
should be disabled by default unless run in the new 'PhoenixDBTest'
profile.

Notable changes to core classes:

* MetaDataTableImpl:

Due to Phoenix's peculiar syntax, the hardcoded statements in
addAppliedMigration() and updateChecksum() won't work. It now
attempts to load a .sql template and run that, if it exists.

* MigrationTestCase:

Added checks for applied migrations of type MigrationType.SCHEMA
and adjusted asserts accordingly. Also added a 'getBaseDir()'
method, and replaced direct calls to BASEDIR with this. Several of
the tests in MigrationTestCase can then be used in the Phoenix
tests by overriding that method.

**Comment by anirudha13** [comment]
@jmahonin I have ulterior motives in seeing this work merged with the mainline. Please let me know how I can help.

**Comment by jmahonin** [comment]
@anirudha13 Me too!

If you could do some quick testing with it and let me know how it goes, that'd be appreciated. We're using it internally already, and it passes the migration test suite, but having some assurance from another party would be appreciated.

**Comment by anirudha13** [comment]
@jmahonin ran some very basic tests using the flyway command line utility from this pull request. Things work like a charm. Will keep you updated if something breaks.

**Comment by jmahonin** [comment]
Fantastic. Out of curious its, what version of Phoenix were you using?

**Comment by jmahonin** [comment]
*sigh* On mobile, excuse the typos. "Out of curiosity" :)

**Comment by anirudha13** [comment]
v4.3.1 with HBase - 0.98.6 CDH 5.3.2

**Comment by chiastic-security** [comment]
Good work, guys!

Is this likely to make it into a release in the near future? I'm wanting to use flyway with Phoenix, and not sure whether to wait for it to be pulled in, or find another way.

**Comment by anirudha13** [comment]
@jmahonin while running the unit tests I get this failure, 

```
Running org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest
Tests run: 29, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,054.234 sec <<< FAILURE! - in org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest
validateClean(org.flywaydb.core.internal.dbsupport.phoenix.PhoenixMigrationMediumTest)  Time elapsed: 22.929 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.flywaydb.core.migration.MigrationTestCase.validateClean(MigrationTestCase.java:267)
```

Any idea why this is failing?

**Comment by jmahonin** [comment]
Hmm, very strange, I'm getting the same. I must have pushed a wrong branch, or missed a commit. Will investigate further.

**Comment by jmahonin** [comment]
I got myself in a tangle with my personal repo and the company repos it looks like. I've closed that PR and updated a new one here. The unit tests pass for me.

https://github.com/flyway/flyway/pull/1012

**Comment by axelfontaine** [comment]
@jmahonin Is there a reason why the metadata table creation statement lacks the not null constraints it should have?

**Comment by jmahonin** [comment]
In Phoenix, you can only specify 'NOT NULL' constraints on columns which are part of the primary key. Since the primary key in this case is 'installed_rank', it's the only column which gets that constraint.

Is this causing any issues or side-effects?

**Comment by axelfontaine** [comment]
No, just wanted to make sure it wasn't an accidental omission.
