### ISSUE TITLE
HANA Support

### ISSUE THREAD

**Issue by pentavalle** [flyway/flyway#931]
Could you add support for SAP HANA?
I've seen a forked repo that already added support: https://github.com/DeltaFlight/flyway

**Comment by miffels** [comment]
Hi all,

I am currently looking into this and I hope that we will be able to contribute our additions to the project.

@axelfontaine Just as a general question, how would you proceed with the integration of a language that differs syntactically? Unfortunately I could not locate any examples of similar cases in the other database support modules. For instance, this is a valid FK constraint from the test scripts:

```
CONSTRAINT couple_user1_fk FOREIGN KEY (name1) REFERENCES test_user(name),
```

whereas in HANA, it should look like this:

```
FOREIGN KEY (name1) REFERENCES test_user(name),
```

We are currently running regexes against the input of ``SqlStatementBuilder#addLine(String)`` and insert replacements where appropriate, but even though it works surprisingly well, it just feels wrong and is bound to fail at some point.

Best,
Michael

**Comment by miffels** [comment]
Hi all,

I almost forgot to post a follow-up since so many things happened during the past weeks. We had a look at the internals of Flyway and came to the conclusion that it's best suited for Standard SQL dialects since there is no abstract query representation internally. For other SQL families, such as HANA SQL, we found that there could only be either a hacky regex-based implementation or a major rewrite of the core components. We finally switched to another tool that has an abstract statement representation which would allow us to generate proper HANA SQL queries.

Best,
Michael

**Comment by rolfp** [comment]
Hi,
we appreciate support for HANA in flyway. For basic functionality, there obviously is no trouble:
https://scn.sap.com/community/hana-cloud-portal/blog/2013/02/11/migrating-your-applications-database-using-flyway
Why is HANA SQL an issue for database migration?

Best regards
Rolf

**Comment by miffels** [comment]
I actually explained in my last post @rolfp. You lose database independency. There are other tools, though, that come with proper abstractions and SQL generators, so there really is no point to force things via Flyway.

**Comment by rolfp** [comment]
I see. This is not a HANA specific statement. If you want database independency, flyway is not your choice. You better go with e.g. LiquiBase (I am sure you found it already)..If you only need support for 1-2 database platforms, the simplicity of flyway becomes a great advantage over unfamiliar and unreadable SQL abstractions. 
We are going to take the steps to HANA support. Extension of SqlStatementBuilder is some effort for coding and testing - we have to handle nested sqlscript BEGIN-END blocks to find out where a CREATE PROCEDURE block ends, so we probably will need to count the depth of nesting. We did not yet find a template for this - OracleStatementBuilder just relies on the "7" as ending marker for PL/SQL blocks. As soon as this becomes stable we will provide a fork and a pull request.
