### ISSUE TITLE
No consequent actions for resources under test structure.

### ISSUE THREAD

**Issue by zip4ever** [flyway/flyway#932]
As a software engineer, I frequently use Flyway to steer the database migrations. Besides the usual database DDL changes, I want to use it also for sharing test data amongst developers. Of course, I do want the DDL changes to be applied in every environment (development and production), where I want the test data only to be applied in the development environment.

My first taught was about putting the test data creation scripts under
-	The (Java) test sources folder, package db.migration for the Java files
-	The test resources folder, subfolders db/migration for the SQL files

Whilst the maven command 
mvn compile flyway:migrate
Successfully detects the sql files withing the test structure, Java files are ignored.

I would expect that both files would be picked up by the system, facilitating the insert / synchronization of test data.

**Comment by axelfontaine** [comment]
This should work. Please post a small repo to reproduce the problem.

Cheers
Axel

**Comment by zip4ever** [comment]
I have uploaded a sample to https://github.com/zip4ever/FlywayIssue

As you can see, I have both sql and Java files underneath the normal structure, as underneath the test data
![flyway_files](https://cloud.githubusercontent.com/assets/8710775/5773471/34a4ae0a-9d63-11e4-90c3-4742c53a2a2c.png)

If I run a mvn compile flyway:migrate on an empty schema, I get the following result:
[INFO] Current version of schema "public": << Empty Schema >>
[INFO] Migrating schema "public" to version 20150112
afterEachMigrate: Version 20150112: Database setup
[INFO] Migrating schema "public" to version 20150112.1
afterEachMigrate: Version 20150112.1: Create missing table vacationrights
[INFO] Migrating schema "public" to version 20150112.2
afterEachMigrate: Version 20150112.2: Store Legal Holidays for next 50 years
[INFO] Migrating schema "public" to version 20150115
afterEachMigrate: Version 20150115: Add test data
[INFO] Successfully applied 4 migrations to schema "public" (execution time 00:07.293s).

Thus, the sql file underneath test is applied, where the java file is ignored.

**Comment by zip4ever** [comment]
Update: even after adding the locations explicitly, the Java file is not picked up:

                    <locations>
                        <location>db/migration</location>
                        <location>filesystem:src/test/java/db/migration</location>
                        <location>filesystem:src/test/resources/db/migration</location>
                    </locations>

I think that it has somehting to do with the compiled file not being picked up. Is there any workaround for this?

Can I in some way have migration files which are only ran on development, whilst the packaged application contains the files that may run on production?

**Comment by axelfontaine** [comment]
Sorry, I wasn't thinking. Try with testCompile  instead and it should work.

**Comment by zip4ever** [comment]
No problem, works indeed. Thanks for the support!

**Comment by PorkLip** [comment]
Just found this old issue and using testCompile did not work for me. The solution I ended up using was:
1.  Create a test-jar for the maven module that contains the classes in src/test/java/ that I want to included in the migration when developing / running test.
