### ISSUE TITLE
Convert the account into an organization

### ISSUE THREAD

**Issue by tototoshi** [flyway/flyway#934]
Is there any reason this account is a personal account?

ref: https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by nachiketde-edt** [comment]
Hi Sorry,

I was out on vacation. I intend to use this for personal use.
Is mail id causing any issues?

Sorry for late reply.

Thanks,
Nachiket

**Comment by axelfontaine** [comment]
I had looked at this in the past, but somehow I think at the time there was no free plan for orgs.

Done.
