### ISSUE TITLE
Filename without description

### ISSUE THREAD

**Issue by DmitriyBlack** [flyway/flyway#936]
Hello.
I would like to have an option to have files without descriptoin. By defalt filenames with no description are looking not good (like "V2014.12.12__.sql"). I would be nice if in case filename doesn't contains separator, then it will consider description as empty, and not throwing and Exception. This was filenames will be without trailing separator (instead of "V2014.12.12__,sql", we'll have "V2014.12.12,sql")

**Comment by blootac** [comment]
I'd argue that this would be bad practice and would encourage much larger migration scripts with no description or comments for other users. 
We prefer much smaller changes so the file name & description much more closely resembles the action in the files.

**Comment by DmitriyBlack** [comment]
But It is still possible to create file without description, but the name is not looking good. It is a good thing to allow users to decide what strategy to use in their project: To give big descriptions, or not to give at all.

**Comment by dmitraver** [comment]
I also think that this feature can be handy as it can help detecting migration versions conflict when you work with a tools like Gerrit where two people can submit separate patch sets with the same migration name and it can be successfully merged into master. Such code will fail on deployment as Flyway will detect two migrations with a same version as the code is already in master. I workaround this issue by setting a separator like "V" and setting a prefix as an empty string. In this way you can have smth like 12V for the version. You can write a test that detects that nobody uses other names. It would be really nice if you can set a separator as an empty string so you can leave everything but a version number or smth like V12.

**Comment by khatkar** [comment]
I will support @blootac. I think it is a very good approach to have human readable description for files so that you don't have to look inside the migration script to understand what it is doing. Also, from debug perspective, it is helpful to show a user friendly error description about the failed migration.
Imagine a use case with a migration V1.sql failing. The error log would say V1 failed. Then the user has to open up the V1.sql file, read it and see what this file does. On the other hand a migration file like V1_Update_emp_name.sql clearly indicates (at high level) what this script must be doing. 

Naming is very important in programming, be it variable/function names or file names.

**Comment by dmitraver** [comment]
@khatkar I see your point but if you are working on a big code base with a dozens of developers it becomes a pain to resolve script conflicts. Having arbitrary descriptions don't create a merge conflict. This is why we workaround this issue by having 1V.sql script names. I think it should be configurable what style you would like to use.

**Comment by khatkar** [comment]
@dmitraver You are correct in the sense that merge conflicts are easily noticeable with version only file names. But then why would you have two scripts with the same version doing the same work. If two developers are working on the same migration script then this is a development workflow issue. Ideally, a migration script should be a single unit of work, completed by one developer at a time.

**Comment by axelfontaine** [comment]
This is actually already possible using

```
flyway.setSqlMigrationSeparator(".sql");
flyway.setSqlMigrationSuffix("");
```

**Comment by wenzis** [comment]
very nice!
