### ISSUE TITLE
Validate length of table property to prevent errors

### ISSUE THREAD

**Issue by gurinderu** [flyway/flyway#937]
Needed to implement PK  and Index names constcuctor. Now it's implemented in craeteMetaDataTables.sql.For example for Oracle
ALTER TABLE "${schema}"."${table}" ADD CONSTRAINT "${table}_pk" PRIMARY KEY ("version");

CREATE INDEX "${schema}"."${table}_vr_idx" ON "${schema}"."${table}" ("version_rank");
CREATE INDEX "${schema}"."${table}_ir_idx" ON "${schema}"."${table}" ("installed_rank");
CREATE INDEX "${schema}"."${table}_s_idx" ON "${schema}"."${table}" ("success");

So, it can produce too long identifier error.

**Comment by gurinderu** [comment]
I think best solution is create API for creating custom PK.
Validation can't help us.

**Comment by axelfontaine** [comment]
Closing as Oracle 12.2 and newer now support much longer identifiers, drastically reducing the need for this.
