### ISSUE TITLE
Placeholder quoting 

### ISSUE THREAD

**Issue by gurinderu** [flyway/flyway#938]
checkForUnmatchedPlaceholderExpression and checkForUnmatchedPlaceholderExpression replace and check input text by pattern ${(.+?)}, but we can skip this.

For example we have sql:
insert into test values('${test'}); I don't want replace this text, but flyway tries to replace this text, but can't and after they throw exception in checkForUnmatchedPlaceholderExpression.

**Comment by axelfontaine** [comment]
Placeholders are replaced first, before any sql language parsing takes place. If you do not want them replaced, you can use a different prefix or suffix.

Works as designed.
