### ISSUE TITLE
Multiline comment closing not detected properly

### ISSUE THREAD

**Issue by david-mas** [flyway/flyway#939]
Flyway cannot tell the multi line comment closing apart when there is a single line comment attached to it. Using flyway-maven-plugin, version 3.1
Example below.
```sql
/**
--insert something
INSERT INTO mytable (id, data1, data2)VALUES (3,1,'hi');
**/-- Comment on the same line attached to the multiline closing
--these statements are not imported because end of multiline is not detected
INSERT INTO mytable (id, data1, data2)VALUES (1,1,'hi');
/**
--insert something
INSERT INTO mytable (id, data1, data2)VALUES (4,1,'hi');
**/
--these statements are imported the above multiline is detected
INSERT INTO mytable (id, data1, data2)VALUES (5,1,'hi');
```

Note this is valid sql syntax and therefore the script loads correctly on the dmbs.

**Comment by axelfontaine** [comment]
Fixed. I actually took the opportunity to simplified the comment parsing code which I wasn't happy about for a long time.

Cheers
Axel
