### ISSUE TITLE
Make DbSupportFactory more flexible/pluggable

### ISSUE THREAD

**Issue by mdeinum** [flyway/flyway#941]
It would be nice that support for new databases would be more or less pluggable. Now it is quite hardcoded inside the DBSupportFactory. 

One solution could be to use the Java Service Provider API to dynamically register delegate factories. That way it would be easier to extend the functionality of Flyway with new/updated databases.

**Comment by axelfontaine** [comment]
Thanks for your suggestion. This is not something I am considering as it would open many more interfaces publicly as part of the SPI. This is turn reduces our ability to freely refactor internals.

Each release adds support for additional databases. Submit an issue and a pull request. We'll work through the process and once it's ready, we'll merge it in the main distribution.

Cheers
Axel
