### ISSUE TITLE
Allow to use paths relative to flyway.conf location

### ISSUE THREAD

**Issue by alexei-osipov** [flyway/flyway#944]
Right now `locations` defined in `flyway.properties` are relative to current working directory. This may be a command line tool location or location of `pom.xml` for Maven plug-in. This makes it very difficult to use single `flyway.properties` to run some set of migrations.

Example file structure:
`/someproject/migrations/flyway.properties`
`/someproject/migrations/sql/V1__aaa.sql`
`/someproject/migrations/sql/V2__bbb.sql`
`/someproject/pom.mxl`
`/tools/flyway/flyway.cmd`

Right now if I want to run migrations from maven plug-in with option `configFile` I have to set `flyway.locations` to `migrations/sql` in it. If I want to use same `flyway.properties` from command line tool I have to explicitly override `locations` with absolute path to sql file folder.

So I suggest to add a boolean option `locationsAreRelativeToConfig`. If it set to `true` then location of `flyway.properties` (or another file provided by `configFile` option) should be used as base directory for `locations`. So for example above it will be possible to set
`flyway.locations=filesystem:sql`
and use `flyway.properties` file both from maven plug-in and command line tool.

**Comment by axelfontaine** [comment]
Thanks for the suggestion. I am not a fan of adding a config property for this. However... This behavior is currently unspecified. We could therefore specify it to be relative to either the current directory or, like you suggest, the directory the config was loaded from.

I'll need to put some thought into this as the what the implications are exactly.

**Comment by punkstarman** [comment]
I think that execution from the command line should resolve non-classpath relative paths by using the working directory (not the install directory), and the build tool should use the project root.
I beleive that this behaviour is in line with most command line and build tools.
The change would only affect the wrapper scripts.

**Comment by punkstarman** [comment]
I have successfully used the following wrapper scripts:

# Unix
```bash
# Save current directory
cygwin=false
case "`uname`" in
  CYGWIN*) cygwin=true;;
esac

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# Set the current directory to the installation directory
INSTALLDIR=`dirname "$PRG"`

# Use JAVA_HOME if it is set
if [ -z "$JAVA_HOME" ]; then
 JAVA_CMD=java
else
 JAVA_CMD=$JAVA_HOME/bin/java
fi

CP="$INSTALLDIR/lib/*:$INSTALLDIR/drivers/*"

if $cygwin; then
  CP=$(cygpath -pw "$CP")
fi

"$JAVA_CMD" -cp "$CP" org.flywaydb.commandline.Main $@

# Save the exit code
JAVA_EXIT_CODE=$?

# Exit using the same code returned from Java
exit $JAVA_EXIT_CODE
```

# Windows
```batchfile
@REM
@REM Copyright 2010-2014 Axel Fontaine
@REM
@REM Licensed under the Apache License, Version 2.0 (the "License");
@REM you may not use this file except in compliance with the License.
@REM You may obtain a copy of the License at
@REM
@REM         http://www.apache.org/licenses/LICENSE-2.0
@REM
@REM Unless required by applicable law or agreed to in writing, software
@REM distributed under the License is distributed on an "AS IS" BASIS,
@REM WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@REM See the License for the specific language governing permissions and
@REM limitations under the License.
@REM

@Echo off

setlocal

@REM Use JAVA_HOME if it is set
if "%JAVA_HOME%"=="" (
 set JAVA_CMD=java
) else (
 set JAVA_CMD="%JAVA_HOME%\bin\java.exe"
)

%JAVA_CMD% -cp "%~dp0\lib\*;%~dp0\drivers\*" org.flywaydb.commandline.Main %*

@REM Save the exit code
set JAVA_EXIT_CODE=%ERRORLEVEL%

@REM Exit using the same code returned from Java
EXIT /B %JAVA_EXIT_CODE%
```

**Comment by RichardJECooke** [comment]
+1 for relative paths. First thing I'm Googling as a brand new user.

**Comment by hotzen** [comment]
+1 as well

**Comment by zetzet** [comment]
++: relative paths would be super helpful

**Comment by jedvardsson** [comment]
Yes, I agree that it would be helpful to have some way to make references relative to the configuration file itself. I suggest looking at e.g. TypeScript and how it uses `./`to denote that the referenced module is located relative to the referencing file. Thus `file:myconfigs` can still mean relative to the working dir and `file:./myconfigs` can mean relative to the config file.

Alternately, we could use a variables like $workdir and $confdir to be even more explicit.

**Comment by miro-ur** [comment]
+1, relative paths would be super

**Comment by r0mdau** [comment]
+1

**Comment by JDFagan** [comment]
This also should apply to flyway.conf (not just flyway.properties) as well, I want to simply define this:

`flyway.locations=./sql/`

So that flyway can pickup my sql from Git repo in repo sub-directory where . represents current directory of my project root (i.e., my git repo directory).

**Comment by axelfontaine** [comment]
This has now been implemented for all client:

- Command-line: relative to the current directory
- Maven: relative to the `pom.xml` directory
- Gradle: relative to the `build.gradle` directory

**Comment by lbreuss** [comment]
Regarding the maven plugin, other plugins provide a **`workingDirectory`** parameter.
- http://www.mojohaus.org/exec-maven-plugin/exec-mojo.html#workingDirectory
- http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#workingDirectory

For my schema unit tests, I would really like to use the original bundled `/src/main/resources/util/flyway/conf/flyway_latest.conf`, that references `filesystem:../../database/`. Now if during test phase I direct flyway-maven-plugin to use the config file at `/target/util/flyway/conf/flyway_latest.conf`, the relative path does not evaluate to `/target/database/`, but to `/../../database/`, which is an inexistent path and even outside the maven project. Currently, as a workaround, I have to use a filtered version of flyway_latest.conf.

Sorry to bring this 944 up again. I would have loved that the original posters desired behaviour would become the default: relative to the conf file. 

I think in any case it would still be a good idea to allow the plugin to explicitely change to a `workingDirectory`.

**Comment by axelfontaine** [comment]
@lbreuss This is essentially a new feature request. Please file a new issue for that.

**Comment by lbreuss** [comment]
Agree. #1877

**Comment by npryce** [comment]
Doesn't seem to work correctly for Gradle with subprojects.

In the debugger I can see that the workingDirectory property of the task is ignored, and not used to initialise the Flyway object.

When run as a task in the subproject, this works fine.  When run via the top-level project, it fails to find migrations.

**Comment by ayush-finix** [comment]
> Doesn't seem to work correctly for Gradle with subprojects.
> 
> In the debugger I can see that the workingDirectory property of the task is ignored, and not used to initialise the Flyway object.
> 
> When run as a task in the subproject, this works fine. When run via the top-level project, it fails to find migrations.

@npryce I have this issue as well, did you find a fix or is this fixed?
