### ISSUE TITLE
Would it be possible to break up the -core module into separate modules for each DB

### ISSUE THREAD

**Issue by vertex-github** [flyway/flyway#948]
We're trying to develop support for OrientDB, but we noticed that since every DB is referenced in the flyway-core module, it looks like we need all the drivers for all the DBs installed and available.

Could the core module not be broken up into flyway-core, and then a whole series of flyway-db-xyz modules that would contain the .sql resources and appropriate files for that specific DB

The core module could run a classpath scan for an annotation on startup to find and register all the various DB flavors, and then ask each implementation for the name of the DB that they support (so that the hardcoded list of DBs in DbSupportFactory can be replaced with a dynamic list).

If each module was separate (for each DB), then we could develop support in isolation without having to worry about all the other DBs that we're not touching/impacting.

**Comment by axelfontaine** [comment]
This is not something I am considering at this point. However, please note that you do not need all drivers installed. You can run the build using ```mvn -P-CommercialDBTest``` to avoid all drivers not available on Maven Central. There are additional profiles available in the POM if you also want to disable all open-source non-inmemory DBs (PG, MySQL, ...).

Cheers
Axel
