### ISSUE TITLE
Create Homebrew formula for command line client

### ISSUE THREAD

**Issue by Pyrolistical** [flyway/flyway#952]
Would love to see the command line client in Homebrew
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by axelfontaine** [comment]
I couldn't agree more. Let's tackle this post 3.2 when the command-line client will also ship with a private JRE.

**Comment by sharpner** [comment]
+1

**Comment by frodeaa** [comment]
flyway formula was added by https://github.com/Homebrew/homebrew/pull/38391

**Comment by axelfontaine** [comment]
@frodeaa Thank you very much! It is now officially announced: http://flywaydb.org/blog/homebrew.html
