### ISSUE TITLE
checksum saved in DB but sql script never worked before

### ISSUE THREAD

**Issue by stuart1975** [flyway/flyway#953]
Hello,
I created a Vxxx__.sql file and added sql code and run flyway:migrate. The script did not run well because of an syntax error. I fix the syntax error and run again migrate but now it is saying me that the file checksum is wrong. 

It makes not much sense to save the checksum in DB if the script never has run before without error. Checksum should only be saved after first error free run.

**Comment by axelfontaine** [comment]
I assume you are using a DB without DDL transaction support (Oracle, MySQL, Hsql, H2, Derby). The failed script has been recorded has changes may have happened to your DB. Use repair() to fix it.

Please reopen if my assumption is wrong.

Cheers
Axel
