### ISSUE TITLE
Gradle plugin: Most Flyway tasks don't really need dependency to testClasses

### ISSUE THREAD

**Issue by wstrzalka** [flyway/flyway#962]
eg. flywayInfo, flywayClean

This creates unnecessary coupling and problems trying to do some more complicated scenarios with flyway.

As a sample use case - my build has dependency to a task that regenerates DAO objects from database. I'd like to make it dependendent on the flywayInfo task output in order to decide if it's needed to regenerate DAO or not. But when all flyway tasks depend on build this causes circular dependency. 
It's possible to remove this dependency later on but that are quite a bad smells - both having dependencies that are not needed and even more - removing existing one later on.

**Comment by wstrzalka** [comment]
Let me follow up myself - actually the dependency to testClasses is not really always needed even by flywayMigrate.
The way I use it is with filesystem location so I do not want to compile my sources in order to apply patch the DB. Especially that it's not always in the compilable state :) 

Summarizing - IMHO this dependency shall be "lazy load" - if it's found really needed.

**Comment by ben-manes** [comment]
The original implementation required users to add the Java task dependency, because I had the same requirement (generated jOOQ database models). Understandably this isn't the common case, so instead you have to remove the task explicitly, e.g. `flywayClean.dependsOn -= testClasses`.

**Comment by ben-manes** [comment]
fyi, this is a duplicate of #775

**Comment by wstrzalka** [comment]
First off all - sorry for duplicating stuff :)
I had already workarounded the issue by removing the dependency this way. Now I'm trying to make it beautiful.
