### ISSUE TITLE
Add 'String getLocation();' method to org.flywaydb.core.api.MigrationInfo

### ISSUE THREAD

**Issue by ospyros** [flyway/flyway#963]
Hello Axel,

out application runs on Oracle and Postgres and tables are spread to a number of schemas for better organization. 

The issue is with Oracle where our enterprise customers can not provide us with administrative priviledges in their production databases. But unless  a user is granted administrator priviledges there is no way to create a table in another schema To work around this we did the following:

1. Created the following subfolders (one subfolder per schema):
    sql/main_schema
    sql/2nd_schema
    sql/3rd_schema
etc.

2. Used the proxy connection feature:
ALTER USER [2nd_schema] GRANT CONNECT THROUGH [main_schema];
ALTER USER [3rd_schema] GRANT CONNECT THROUGH [main_schema];

3. And a flyway callback:
```
  public void beforeEachMigrate(Connection connection, MigrationInfo info) {
     String migrationLocSuffix = getSuffix(info.getLocation().toLowerCase());
     if (!migrationLocSuffix.equals("main_schema") {
       Properties props = new Properties();
       props.put(OracleConnection.PROXY_USER_NAME, migrationLocSuffix);
       OracleConnection cn = (OracleConnection) connection;
       try {
         cn.openProxySession(OracleConnection.PROXYTYPE_USER_NAME, props);
         isProxySessionOpen = true;
       } catch (SQLException e) {
         isProxySessionOpen = false;
         ....
       }       
    }    
  }
```

So we can work on other schemas using the main_schema user (where schema_version table is created). But we need the migration 'location' which is not currently available in the official release. 

I played around a little bit and it seems I have a working version. The schema_version table now has the following structure:

```
version_rank	NUMBER(38,0)	No		1	
installed_rank	NUMBER(38,0)	No		2	
version	VARCHAR2(50 BYTE)	No		3	
description	VARCHAR2(200 BYTE)	No		4	
type	VARCHAR2(20 BYTE)	No		5	
******
location	VARCHAR2(200 BYTE)	No		6
******
script	VARCHAR2(1000 BYTE)	No		7	
checksum	NUMBER(38,0)	Yes		8	
installed_by	VARCHAR2(100 BYTE)	No		9	
installed_on	TIMESTAMP(6)	No	CURRENT_TIMESTAMP 	10	
execution_time	NUMBER(38,0)	No		11	
success	NUMBER(1,0)	No		12	
```

and a sample location is the following: 'sql/2nd_schema/V1_3_1__Init.sql'

If you think this feature is worth including let me know and I will proceed with a pull request. Not sure how the column will be added in existing installations though.

Thanks again for the great tool,

Spyros

**Comment by axelfontaine** [comment]
Hi Spyros,

thanks for your offer. This can however be worked around today by prefixing the database objects with the schema name. That in combination with the fact it is really a niche feature, tells me this doesn't belong in the main distribution.

Cheers
Axel

**Comment by ospyros** [comment]
Axel,

can you please elaborate a bit on the work around, possibly with an example? Apologies if it should be obvious from the documentation.

Thanks again,

Spyros

**Comment by ospyros** [comment]
I think I just got it... It is in the 'script' property. Thanks for the tip!
