### ISSUE TITLE
flyway.cmd hangs during Nullsoft install (version 2.2) - and (version 3.1)

### ISSUE THREAD

**Issue by kalverson** [flyway/flyway#964]
This is the stack trace of the process that is hanging.  I took two dumps which are the same.

JStack trace dump:
"main" prio=6 tid=0x0095dc00 nid=0xc3c runnable [0x00c1f000]
   java.lang.Thread.State: RUNNABLE
                at java.io.FileOutputStream.writeBytes(Native Method)
                at java.io.FileOutputStream.write(FileOutputStream.java:345)
                at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
                at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
                - locked <0x09794c08> (a java.io.BufferedOutputStream)
                at java.io.PrintStream.write(PrintStream.java:482)
                - locked <0x097847b0> (a java.io.PrintStream)
                at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
                at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
                at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
                - locked <0x09794c48> (a java.io.OutputStreamWriter)
                at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
                at java.io.PrintStream.write(PrintStream.java:527)
                - locked <0x097847b0> (a java.io.PrintStream)
                at java.io.PrintStream.print(PrintStream.java:669)
                at java.io.PrintStream.println(PrintStream.java:806)
                - locked <0x097847b0> (a java.io.PrintStream)
                at com.googlecode.flyway.commandline.ConsoleLog.info(ConsoleLog.java:45)
                at com.googlecode.flyway.core.command.DbMigrate.applyMigration(DbMigrate.java:242)
                at com.googlecode.flyway.core.command.DbMigrate.access$700(DbMigrate.java:47)
                at com.googlecode.flyway.core.command.DbMigrate$1.doInTransaction(DbMigrate.java:189)
                at com.googlecode.flyway.core.command.DbMigrate$1.doInTransaction(DbMigrate.java:138)
                at com.googlecode.flyway.core.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:56)
                at com.googlecode.flyway.core.command.DbMigrate.migrate(DbMigrate.java:137)
                at com.googlecode.flyway.core.Flyway$1.execute(Flyway.java:869)
                at com.googlecode.flyway.core.Flyway$1.execute(Flyway.java:819)
                at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1191)
                at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)
                at com.googlecode.flyway.commandline.Main.executeOperation(Main.java:118)
                at com.googlecode.flyway.commandline.Main.main(Main.java:86)

After killing the process in task manager, the Nullsoft script continues onward.  This is what was logged for the Flyway cmd v2.2

Flyway (Command-line Tool) v.2.2
Creating Metadata table: "public"."schema_version"
Current version of schema "public": << Empty Schema >>
WARNING: outOfOrder mode is active. Migration of schema "public" may not be reproducible.
Migrating schema "public" to version 1
Migrating schema "public" to version 20130509135925
Migrating schema "public" to version 20130522101017
Migrating schema "public" to version 20130529073934
Migrating schema "public" to version 20130530133442
Migrating schema "public" to version 20130531092351
Migrating schema "public" to version 20130603142533
Migrating schema "public" to version 20130612130757
Migrating schema "public" to version 20130619075512
Migrating schema "public" to version 20130624102236
Migrating schema "public" to version 20130701152113
Migrating schema "public" to version 20130701153656
Migrating schema "public" to version 20130702080708
Migrating schema "public" to version 20130709095610
Migrating schema "public" to version 20130709105005
Migrating schema "public" to version 20130709105029
Migrating schema "public" to version 20130715091932
Migrating schema "public" to version 20130715170544
Migrating schema "public" to version 20130716152812
Migrating schema "public" to version 20130716172245
Migrating schema "public" to version 20130717145742
Migrating schema "public" to version 20130717150654
Migrating schema "public" to version 20130724082756
Migrating schema "public" to version 20130724152901
Migrating schema "public" to version 20130726104825
Migrating schema "public" to version 20130731115426
Migrating schema "public" to version 20130801114247
Migrating schema "public" to version 20130806104915
Migrating schema "public" to version 20130809152344
Migrating schema "public" to version 20130820145740
Migrating schema "public" to version 20130821122812
Migrating schema "public" to version 20130821151606
Migrating schema "public" to version 20130822133858
Migrating schema "public" to version 20130828143615
Migrating schema "public" to version 20130828152955
Migrating schema "public" to version 20130829090330
Migrating schema "public" to version 20130903104810
Migrating schema "public" to version 20130905115025
Migrating schema "public" to version 20130911154021
Migrating schema "public" to version 20130912152323
Migrating schema "public" to version 20130916150657
Migrating schema "public" to version 20130917093504
Migrating schema "public" to version 20130918160958
Migrating schema "public" to version 20131007150632
Migrating schema "public" to version 20131105150744
Migrating schema "public" to version 20131127134451
Migrating schema "public" to version 20131204115716
Migrating schema "public" to version 20131210130211
Migrating schema "public" to version 20131210131118
Migrating schema "public" to version 20140108132401
Migrating schema "public" to version 20140110111645
Migrating schema "public" to version 20140120140054
Migrating schema "public" to version 20140225164313
Migrating schema "public" to version 20140226112910
Migrating schema "public" to version 20140227184805
Migrating schema "public" to version 20140530144059
Migrating schema "public" to version 20140611111838
Migrating schema "public" to version 20140611154308
Migrating schema "public" to version 20140613100702
Migrating schema "public" to version 20140616102303
Migrating schema "public" to version 20140701114043
Migrating schema "public" to version 20140715140456
Migrating schema "public" to version 20140926133410
Migrating schema "public" to version 20141001065237
Migrating schema "public" to version 20141015150738
Migrating schema "public" to version 20141029091228
Migrating schema "public" to version 20141029162056
Migrating schema "public" to version 20141031164147
Migrating schema "public" to version 20141203144425
Migrating schema "public" to version 20141211122632
Migrating schema "public" to version 20150120140400
Migrating schema "public" to version 20150127124533
Migrating schema "public" to version 20150128103341
flyway.cmd (HelpSystems Web) returned 1

I also tried v 3.1 which hangs up even sooner before doing any of the migrations at all.  I see the in the source that DbMigrate.java:189 is some kind of failed migration processing.  Could it be hanging up there for some reason?

**Comment by kalverson** [comment]
For v3.1 here is my Nullsoft log which contains flyway debug output

Flyway (Command-line Tool) v.3.1
DEBUG: Adding location to classpath: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\drivers\postgresql-9.2-1002.jdbc4.jar
Database: jdbc:postgresql://localhost:5432/robotweb (PostgreSQL 9.2)
DEBUG: DDL Transactions Supported: true
DEBUG: Schema: public
DEBUG: Scanning for filesystem resources at 'C:/Program Files (x86)/Help Systems/HelpSystems Web Server/flyway/sql' (Prefix: '', Suffix: '.sql')
DEBUG: Scanning for resources in path: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql (C:/Program Files (x86)/Help Systems/HelpSystems Web Server/flyway/sql)
DEBUG: Filtering out resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V1__create_system_settings.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130509135925__add_admin_user.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130522101017__add_iseries_securities.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130529073934__create_ldap_settings.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130530133442__create_security_setting.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130531092351__add_logger_settings.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130603142533__add_defined_iseries.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130612130757__create_credentials.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130619075512__add_alias_index.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130624102236__user_preferences.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130701152113__create_user.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130701153656__create_session.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130702080708__add_products_list.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130709095610__add_relmod_to_definediseries.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130709105005__create_user_profile.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130709105029__create_iseries_credentials.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130715091932__add_session_timeout.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130715170544__alter_session_id_column.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130716152812__add_start_time_to_session.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130716172245__add_authentication_type_to_authenticated_user.sql
DEBUG: Found filesystem resource: C:\Program Files (x86)\Help Systems\HelpSystems Web Server\flyway\sql\V20130717145742__set_columns_to_not_null_authenticated_user.sql
thread status is 1
checks thread is running. Returns 1 if flyway has exited, 0 if still running, -1 on error. /ASYNC mode only.
flyway.cmd ran ok (HelpSystems Web) returned 1

and here is the Jstack.exe -l 7020 (output)

2015-03-02 08:12:45
Full thread dump Java HotSpot(TM) Client VM (24.45-b08 mixed mode):

"Service Thread" daemon prio=6 tid=0x1811f000 nid=0x1ef8 runnable [0x00000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread0" daemon prio=10 tid=0x1811a000 nid=0x1da4 waiting on condition [0x00000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Attach Listener" daemon prio=10 tid=0x18118c00 nid=0xff8 waiting on condition [0x00000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" daemon prio=10 tid=0x18115800 nid=0xed4 runnable [0x00000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Finalizer" daemon prio=8 tid=0x180e8800 nid=0xd0 in Object.wait() [0x185cf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x04540b78> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x04540b78> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:189)

   Locked ownable synchronizers:
	- None

"Reference Handler" daemon prio=10 tid=0x180e2400 nid=0x510 in Object.wait() [0x1838f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x04540c00> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
	- locked <0x04540c00> (a java.lang.ref.Reference$Lock)

   Locked ownable synchronizers:
	- None

"main" prio=6 tid=0x00a0dc00 nid=0x490 runnable [0x0206f000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	- locked <0x045909e0> (a java.io.BufferedOutputStream)
	at java.io.PrintStream.write(PrintStream.java:480)
	- locked <0x04580c70> (a java.io.PrintStream)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	- locked <0x04590a20> (a java.io.OutputStreamWriter)
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
	at java.io.PrintStream.write(PrintStream.java:527)
	- locked <0x04580c70> (a java.io.PrintStream)
	at java.io.PrintStream.print(PrintStream.java:669)
	at java.io.PrintStream.println(PrintStream.java:806)
	- locked <0x04580c70> (a java.io.PrintStream)
	at org.flywaydb.commandline.ConsoleLog.debug(ConsoleLog.java:40)
	at org.flywaydb.core.internal.util.scanner.filesystem.FileSystemScanner.scanForResources(FileSystemScanner.java:56)
	at org.flywaydb.core.internal.util.scanner.Scanner.scanForResources(Scanner.java:46)
	at org.flywaydb.core.internal.callback.SqlScriptFlywayCallback.<init>(SqlScriptFlywayCallback.java:76)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1315)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:919)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
	at org.flywaydb.commandline.Main.main(Main.java:87)

   Locked ownable synchronizers:
	- None

"VM Thread" prio=10 tid=0x180e1000 nid=0xf44 runnable 

"VM Periodic Task Thread" prio=10 tid=0x18139400 nid=0x1c38 waiting on condition 

JNI global references: 148

**Comment by axelfontaine** [comment]
Thanks for the report. I don't have the time to debug this right now (why would it hang on println?), but I will gladly accept a PR that fixes the issue.

Cheers
Axel

**Comment by kalverson** [comment]
Thank you for your reply Axel.  This issue turned out to be an issue with the Nullsoft plug-in ExecDoc.  The 3.1 version of flyway.cmd works fine.
