### ISSUE TITLE
Problem with double quotes - Command Line 3.1

### ISSUE THREAD

**Issue by sogft** [flyway/flyway#965]
Hi,
we have a problem when we try to migrate the following sql : 

-- -----------------------------------------------------                                                 
-- procedure get_stats_bonus_cumul
-- -----------------------------------------------------
DROP procedure IF EXISTS `get_stats_bonus_cumul`;
DELIMITER //
CREATE PROCEDURE `get_stats_bonus_cumul` (isdn BIGINT, bid VARCHAR(100), dt0 DATE, dt1 DATE)
BEGIN
  DECLARE sql_cmd      VARCHAR(10000);

  SET sql_cmd = CONCAT(
  'SELECT
    s1.msisdn AS msisdn,
    b.bonus_name AS bonus_name,
    "',dt0,'" AS from_date,
    "',dt1,'" AS to_date,
    s1.qty_earned - COALESCE(s0.qty_earned,0) AS qty_earned,
    s1.qty_used - COALESCE(s0.qty_used,0) AS qty_used,
    s1.qty_expired - COALESCE(s0.qty_expired,0) AS qty_expired,
    b.recommended_price,
    b.optin,
    b.unit
  FROM stats_bonus s1
  LEFT JOIN stats_bonus s0 ON (s0.msisdn = s1.msisdn AND s0.agg_date="',dt0,'")
  LEFT JOIN bonuses b ON (s1.bonus_id = b.bonus_id)
  WHERE s1.agg_date="',dt1,'"');
  
  IF NOT (isdn = 0) THEN
    SET sql_cmd = CONCAT(sql_cmd, ' AND s1.msisdn=',isdn);
  END IF;

  IF(bid <> '') THEN
     SET sql_cmd = CONCAT(sql_cmd, ' AND b.bonus_id IN (',bid,')');
  END IF;
  
  SET @sqlstatement = sql_cmd;
  PREPARE sqlquery FROM @sqlstatement;
  EXECUTE sqlquery;
  DEALLOCATE PREPARE sqlquery;

END
//

DELIMITER ;

The problem is related to the double quote followed to the single quote . 

The issue resolved on https://github.com/flyway/flyway/issues/611 consider only the single quote followed to the double quote. 

Please, can you fix this bug, we have a lot of this files to migrate .

Thanks.

**Comment by axelfontaine** [comment]
Can you distill it down to the simplest possible statement that fails? (I am assuming you are using MySQL...)

Cheers
Axel

**Comment by sogft** [comment]
Hi Axel,
yes, can you try this statement , the same error : 

CREATE PROCEDURE `get_stats_bonus_cumul` (isdn BIGINT, bid VARCHAR(100), dt0 DATE, dt1 DATE)
DELIMITER
//

BEGIN
  DECLARE sql_cmd      VARCHAR(10000);
  SET sql_cmd = CONCAT(
  'SELECT
    "',dt0,'" AS from_date,
  FROM stats_bonus s1
  WHERE s1.agg_date="',dt1,'"');


  SET @sqlstatement = sql_cmd;
  PREPARE sqlquery FROM @sqlstatement;
  EXECUTE sqlquery;
  DEALLOCATE PREPARE sqlquery;
END

//

DELIMITER ;


I confirm you that we use Mysql.

Thanks,
Marco.

**Comment by sogft** [comment]
Thanks Axel for a quick resolution !
