### ISSUE TITLE
Add Gradle Plugin support for SQL file LifeCycle Callbacks

### ISSUE THREAD

**Issue by sagneta** [flyway/flyway#967]
Presently the Gradle Plugin only supports Java callbacks. More often all that is required are simple SQL files which are supported in the command line tools. 

Specifically I am speaking of the LifeCycle SQL files: http://flywaydb.org/documentation/callbacks.html

Thank you,
  Steve

**Comment by axelfontaine** [comment]
SQL callbacks have been supported since 3.1. Add a file with the callback you want (ex. afterMigrate.sql) in one of the configured locations and you should be good to go.

Please reopen if you run into an issues.

Cheers
Axel
