### ISSUE TITLE
Android migration scripts on classpath are invisible

### ISSUE THREAD

**Issue by lstrzelecki** [flyway/flyway#970]
I have android project with two modules:
`app` (apk)
`core` (jar)
Module `apk` has dependency to `core` which has on classpath migration script (`core/src/main/resources/db/migration/V1__Create_person_table.sql`).

On main Activity I call 

``` java
SQLiteDatabase db = openOrCreateDatabase(DB_NAME, 0, null);
ContextHolder.setContext(this);
Flyway flyway = new Flyway();
flyway.setDataSource("jdbc:sqlite:" + db.getPath(), "", "");
flyway.setLocations("classpath:db/migration");
flyway.migrate();
```

But migration script wasn't executed. Of course with assets it works.

Here is project which shows whole configuration: https://github.com/issue-example/flywaydb/tree/issue/android_migration_script_on_classpath_jar

**Comment by axelfontaine** [comment]
Thanks for the report. Would you like to contribute a pull request?

Cheers
Axel

**Comment by lstrzelecki** [comment]
ill try in near future

**Comment by axelfontaine** [comment]
Any news?

**Comment by SStorm** [comment]
+1 very obnoxious misfeature!

**Comment by MikielAgutu** [comment]
Blocked by https://github.com/SQLDroid/SQLDroid/pull/91. SQLDroid's JDBC driver needs to be compatible with Flyway before we look at fixing this.

**Comment by MikielAgutu** [comment]
https://github.com/SQLDroid/SQLDroid/pull/91 has now been merged. When they release we can confirm the fix works pick this up again.

**Comment by DoodleBobBuffPants** [comment]
In Flyway V8 we will be removing support for Android, so closing this issue

More information [here](https://github.com/flyway/flyway/issues/3247)
