### ISSUE TITLE
Fail on invalid command-line options

### ISSUE THREAD

**Issue by EduardoPiairo** [flyway/flyway#977]
Hello,

I was applying a set of migrations using Flyway Command-line. I wanted to use the option -target to specify the target version because a had more scripts (to migrate in future). However, when i wrote the option i wrote it wrong: "flyway -targte=20150326 migrate" and all scripts were migrated (it wasn't wat i wanted).

Wrong options shouldn't permite execute commands. In situations like this an error could be printed to user in order to correct it. In other words, options should be validated.

Thanks,
Eduardo Piairo

**Comment by axelfontaine** [comment]
Hi Eduardo,

yes, I fully agree fail-fast is preferable here.

Cheers
Axel

**Comment by axelfontaine** [comment]
I turned this into a warning instead of an error due to potential compatibility issues with people using flyway.conf between multiple tools
