### ISSUE TITLE
Feature Request: "Tags" or some other form of filtering

### ISSUE THREAD

**Issue by amirabiri** [flyway/flyway#978]
In our setup there are multiple instances of our application in different locations, i.e US, EU, ... etc.

The majority of the schema is common of course. However there are sometimes location-specific quirks. So for example there are 2-3 tables unique to US, another one unique to EU, etc.

To support this we would currently need 2 flyway instances on the same schema (correct me if I'm wrong), with different schema_version tables, etc.

It would be preferable if we could 'tag' a migration and then filter based on tags. Tag-less migrations are always included, but tagged migrations are only included if the tag appears in the parameters, for example:

    flyway migrate ... -tags=US

This feature is supported by [FluentMigrator](https://github.com/schambers/fluentmigrator/wiki/Filter-migrations-run-based-on-Tags) for example.

**Comment by axelfontaine** [comment]
This is already supported in the form of multiple locations: http://flywaydb.org/documentation/faq.html#db-specific-sql

Cheers
Axel

**Comment by amirabiri** [comment]
I tried the multiple locations route but that requires paying careful attention to the version numbers, which are then also split across multiple directories, so easy to make an error with.
