### ISSUE TITLE
Unable to run a JdbcMigration class in sbt 0.13.8 against scala 2.11 compiled project

### ISSUE THREAD

**Issue by alexmnyc** [flyway/flyway#980]
Unable to run a JdbcMigration class in sbt 0.13.8 against scala 2.11 compiled project.  It seems like the class is run against SBT JVM which is using 2.10. Is there a workaround to do this?
Thank you.

**Comment by axelfontaine** [comment]
Thanks. Please provide the steps to reproduce this issue.

Cheers
Axel

**Comment by axelfontaine** [comment]
Any news?

**Comment by axelfontaine** [comment]
Closing due to lack of response from reporter.
