### ISSUE TITLE
Flyway will not scan classpath locations if they contains a dot in directory name

### ISSUE THREAD

**Issue by FlorianGWE** [flyway/flyway#982]
Our directory structure for static SQL migration files contains a dot ('.') in the directory name.
If these files a all part of a resource Jar and we will now configure Flyway with location starting direct with this directory it will not find any migration file. 

Example Directory structure:
   archive-2.6
   ...
   archive-3.3

`...locations=classpath:archive-3.3, classpath:/org/archive/migrations`

Following workaround works:
- replace '.' with '_' :-)
- add a parent directory 'sql' and configure `locations=classpath:sql, classpath:...` , but now we scan some directories we won't have in the scan.

I take a look into the implementation of Location and see `path.replace(".", "/");`. 
First I think may a quot for dot support will help.

**Comment by FlorianGWE** [comment]
I try a quote implementation for '.' dot but it works ~ 

I have a bad felling, because I have not seen the code where it is necessary to transform the package name into the directory name for the scan operation. 

Or is it for compatible reason and should support use package name for locations configuration.
It will be better to know why this implementation exists and which use case exists before change the location mechanism, than it is also possible to support for all these use cases test cases.

**Comment by axelfontaine** [comment]
Thanks for reporting. Yes, this support exists for allowing the usual Java package notation. One solution could be to scan both with and without the replacement and aggregate the results.

Or if the location contains a character that is invalid for a package name, only scan without replacement.

Example:
abc.def => scan both abc/def and abc.def
ab_c.def => only scan ab_c.def

Thoughts?

**Comment by FlorianGWE** [comment]
Yes, this sounds to be a good solution for this problem.

**Comment by dkellenb** [comment]
I stumbled across the same issue today. Would be good to have it fixed. Scanning for folders without the replacements and with the replacements of `. ` sounds good.

**Comment by huntersan9** [comment]
Also confirming that this happens using the maven plugin (5.0.7 and 5.1.0) with defaults.

**Comment by MikielAgutu** [comment]
After further consideration we've decided that using dots as path separators isn't something we want to support. It adds a level of complexity on our end, when it's simple to use a slash.

For Flyway 7 we will deprecate this feature. In the meantime, from 6.0.7 onwards we will produce a warning.

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).
