### ISSUE TITLE
Redshift COPY not working

### ISSUE THREAD

**Issue by cajnoj** [flyway/flyway#983]
Migration fails during a COPY statement. In Redshift, COPY has a CREDENTIALS clause for Amazon S3 credentials. I think that the problem is that a semicolon separates between the AWS access-key and the AWS secret access-key inside the credentials string. Tried escaping the semicolon but it didn't help.

Error text:
Migration V<num>__<desc>.sql failed
SQL State  : 42601
Error Code : 0
Message    : ERROR: unterminated quoted string at or near "'aws_access_key_id=...

**Comment by cajnoj** [comment]
Found the reason.
flyway gives special treatment to the COPY statement in order to support COPY FROM STDIN - a feature that isn't available in Redshift.

**Comment by axelfontaine** [comment]
Thanks for investigating. Can you post an example statement that fails?

**Comment by cajnoj** [comment]
Take as an example:

`COPY schemaname.tablename
FROM 's3://bucketname/filepath'
CREDENTIALS 'aws_access_key_id=ZZZZZ;aws_secret_access_key=bbbbb' GZIP;`
