### ISSUE TITLE
Cannot connect to a MySQL database that starts with a number

### ISSUE THREAD

**Issue by Jacob-Swanson** [flyway/flyway#984]
I am attempting to baseline a database called "280" using the command line tool. The database's name cannot be changed. I have pasted the error below. 
```
ERROR: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost/280) for user 'root': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '280' at line 1
```
Based on my usage of Flyway, it looks like as long as the database begins with a letter it works correctly.

**Comment by axelfontaine** [comment]
Hmmm Flyway doesn't do any special processing here. The connection string is passed as is to the driver. So I would raise an issue at http://dev.mysql.com/downloads/connector/j/

I am afraid there is not much we can do on this end.

Cheers
Axel

**Comment by Jacob-Swanson** [comment]
Thanks for pointing me in the right direction.
