### ISSUE TITLE
Migrations in multiple Maven modules are incorrectly combined

### ISSUE THREAD

**Issue by sgrimm-sg** [flyway/flyway#987]
I have a Maven project that contains two separate modules, each of which builds a server to talk to its own database instance. If I run the Flyway migrate goal in either of the modules individually, it works fine, but if I run it from the parent (usually implicitly as part of "mvn test" or some other goal) it looks like it retains knowledge of the migrations between modules.

Specifically, the migration in the first module Maven visits works fine (or rather, it detects that there's no work to do). But then when Maven moves on to the second module, I get

```
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:migrate (default) on project payment: org.flywaydb.core.api.FlywayException: Found more than one migration with version 1
[ERROR] Offenders:
[ERROR] -> (module 1)/target/classes/db/migration/V1__CreateUserTables.sql (SQL)
[ERROR] -> (module 2)/target/classes/db/migration/V1__CreateClientsTable.sql (SQL)
[ERROR] -> [Help 1]
```

If it matters, I'm using jOOQ and have followed the advice in [this jOOQ blog post](http://blog.jooq.org/2014/06/25/flyway-and-jooq-for-unbeatable-sql-development-productivity/) to configure Flyway to run in the generate-sources phase so that jOOQ code generation uses an up-to-date schema. My complete plugin configuration is the same in both modules, with `${db.url}` differing between the two:

```xml
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>3.2.1</version>
                <configuration>
                    <url>${db.url}</url>
                    <user>${db.user}</user>
                </configuration>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>migrate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>${postgresql.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

Again, this works fine in module 2 if I run Maven directly from that module.

Happy to provide any additional diagnostic information.

**Comment by axelfontaine** [comment]
Can you try changing the flyway config in the various modules to have location=src/main/resources/db/migration ?

Did this work?

Cheers
Axel

**Comment by sgrimm-sg** [comment]
Yes, that seems to have worked in my dev environment; thanks! In case 
anyone else is reading this, the exact thing I added to pom.xml is, in 
Flyway's <configuration> section:

<locations>
<location>filesystem:src/main/resources/db/migration</location>
</locations>

**Comment by skomarla** [comment]
Hello,

I have a similar issue where modules are incorrectly combined.  I do set the location property to filesystem:src/main/resources/db/migration, but I also use a java callback that runs other scripts.

I use a pattern where the java call loads a txt file, that contains a list of other scripts to run (i.e. before-migrate-scripts.txt, after-migrate-scripts.txt).  I share this java callback across two modules which provide their own content for these files.  The java callback looks for these files in the classpath

for example:

	@Override
	public void beforeMigrate(Connection conn) {

		try {
			PlaceholderReplacer placeholderReplacer = new PlaceholderReplacer(new HashMap<String, String>(), "${", "}");
			String encoding = "UTF-8";

			String metaFile = "db/before-migrate-scripts.txt";

			executeScriptsInFile(conn, placeholderReplacer, encoding, metaFile);
		} catch (IOException e) {
			throw new FlywayException(e);
		}
	}

	private void executeScriptsInFile(Connection conn, PlaceholderReplacer placeholderReplacer, String encoding,
			String metaFile) throws IOException {
		System.out.println("processing scripts in " + metaFile);

		ClassLoader classLoader = Thread.currentThread().getContextClassLoader();

		DbSupport dbSupport = DbSupportFactory.createDbSupport(conn, false);
		InputStream inputStream = classLoader.getResourceAsStream(metaFile);
		if (inputStream == null) {
			System.err.println("Unable to obtain inputstream for resource: " + metaFile);
			return;
		}

		BufferedReader br = new BufferedReader(new InputStreamReader(inputStream));

		String line = br.readLine();
		while (line != null) {
			line = line.trim();
			if (line.length() > 0 && !line.startsWith("#")) {
				ClassPathResource resource = new ClassPathResource(line, classLoader);
				if (resource.exists()) {
					System.out.println("executing: " + line);
					SqlScript sqlScript = new SqlScript(dbSupport, resource, placeholderReplacer, encoding);

					sqlScript.execute(new JdbcTemplate(conn, 0));
				} else {
					System.err.println(line + " does not exist");
				}

			}
			line = br.readLine();
		}
	}

What is happening is when the second module runs, it is loading the before-migrate-scripts.txt from the first module.  This does not seem correct. How can I work around this without hacking a custom solution per module?

I dumped the classpath via:

		URL[] urls = ((URLClassLoader) classLoader).getURLs();

		for (URL url : urls) {
			System.out.println(url.getFile());
		}

and it is clear to me that when the second module runs, the original classpath still exists and the new module's locations are being appended to it..

**Comment by skomarla** [comment]
I continued to dig, and I'm pretty sure its a maven problem. I'm still on 2.2,1 since this is a fairly large project.  I found this issue: https://issues.apache.org/jira/browse/MNG-1323 which is fixed in maven 3, but doesn't help me in maven 2.2.1
