### ISSUE TITLE
Introduce option to fail migrate if has a version that is newer than the latest available migration

### ISSUE THREAD

**Issue by timbuethe** [flyway/flyway#989]
If the schema contains a migration that is newer than the latest available, `migrate` logs a warning but doesn't fail. For example:

    Schema xxx has a version (1.1.1) that is newer than the latest available migration (1.0.1) !

I suggest to introduce an option to fail migration if this is detected to prevent running an older version of software on a newer database schema.

This is related to, which would lead to failing if a migration isn't found:
https://github.com/flyway/flyway/issues/988

Related stackoverflow question:
http://stackoverflow.com/questions/29541845

**Comment by blootac** [comment]
+1

**Comment by rapguit** [comment]
+1

**Comment by PeeZu** [comment]
+1

**Comment by syedtariqislam** [comment]
+1

**Comment by diwakartimilsina** [comment]
+1

**Comment by axelfontaine** [comment]
Added new ignoreFutureMigrations flag (default = true)

**Comment by Zevaxx** [comment]
+1
