### ISSUE TITLE
MERGE/INSERT throw ORA-911 if use SELECT based data selection

### ISSUE THREAD

**Issue by nitingautam** [flyway/flyway#990]
I noticed that while migration of MERGE/INSERT scripts which contain no field name it throw ORA-0911 error...see below one of example in which in first line fieldnames/column names are specified but in next rows not, technically they are correct  but Flyway breaks on this. Can you help please?

INSERT INTO ss.CODETBL(FIELDNAME,FIELDVALUE,IDS)
SELECT FIELDNAME,FIELDVALUE,IDS FROM
(
SELECT 'ACCT_TYPE_CD' FIELDNAME, '$' FIELDVALUE,'SAMP' IDS FROM DUAL UNION ALL
SELECT 'ACCT_TYPE_CD', 'L','SAMP' FROM DUAL UNION ALL
SELECT 'ACCT_TYPE_CD', 'C','SAMP' FROM DUAL 
)
D
WHERE NOT EXISTS
(
    SELECT 1 FROM SS.CODETBL 
    WHERE D.FIELDNAME = FIELDNAME 
    AND D.FIELDVALUE = FIELDVALUE
    AND D.IDS = IDS
);

**Comment by nitingautam** [comment]
Any one noticed this one ?

**Comment by axelfontaine** [comment]
Thanks for the report. I'll look at it in time for the next release.

**Comment by nitingautam** [comment]
Thanks axel, any approx date when this will be available as a fix =)

**Comment by axelfontaine** [comment]
Probably around the end of June. You are of course welcome to sponsor a fix if you need this sooner: http://flywaydb.org/support/#sponsor

Cheers
Axel

**Comment by nitingautam** [comment]
Thanks

**Comment by nitingautam** [comment]
Is this fix released?

**Comment by nitingautam** [comment]
Is this fixed?

**Comment by axelfontaine** [comment]
I am afraid there is not much we can do on Flyway's side. I just added a test case for the parser and everything is working as expected, which means it is the Oracle JDBC driver which is rejecting this.

Cheers
Axel
