### ISSUE TITLE
Want possibility to use project specific validation for migration  

### ISSUE THREAD

**Issue by FlorianGWE** [flyway/flyway#991]
The default Flyway migration validation is fixed and can only use as is or must complete disabled if not all validation checks can be fullfilled.

For some project situation it will be nice to if it will be possible to disable or change some of the default validation strategies. 

If the strategies can be configured a project get possibility to change the default validation behaviour.

**Comment by FlorianGWE** [comment]
I have already have a sample implementation to change the default validation processing. 
It need some code clean up and documentation.

At the moment it miss only maven-plugin and gradle-plugin support.

**Comment by axelfontaine** [comment]
What exactly is it that isn't working for you in the current implementation? Please help me understand your usecase.

Cheers
Axel

**Comment by FlorianGWE** [comment]
It is a little our own problem, because we started without of Flyway and we have many customer databases with different versions.
Than project start to setup and migrate databases with Flyway. We also made some wrong decisions in how to use Flyway or manage our scripts - so we learn more and more. But versions with wrong decisions are out and on customer side. 
We use currently version 3.0.

We have following scenarios:
- We use different scripts for installation and migration (identically version number)
- With some customer data we detect that our migration has no acceptable performance. so we must change this script content with (nop) and bring a different script out, but the version is out and some customer database contains the old script. 
- we have special migration scripts for Flyway to bring the database to actual version (starting point is a database without a Flyway support). 

Following validation checks will fail ;-)
- Checksum because we have changed files for new installation and update. Can be detected by script name. 
- missing resolved migration in classpath, but we can specifiy the versions for that missing is ok

**Comment by axelfontaine** [comment]
Hmmm that can be solved by issuing repair though...

**Comment by FlorianGWE** [comment]
ok I will try it. 

what will be the workflow of a automatically update (migration) program?

- migrate 
  - migration failed 
  - so how the program should handle this? 
    I have no chance for a user interaction, because a end user will do the update migration.

**Comment by axelfontaine** [comment]
Thank you for the pull request. However I still don't believe this cannot be solved using the current functionality. Did you try using repair as I suggested?

**Comment by FlorianGWE** [comment]
Hi Axel,

I tried migrate and repair, but for our setup it will not work, because
- I forgot that we also have some databases out that are do not contaiin all SQL scripts that are part of our update processing-> so the database have missing scripts. 
Repair can only handle checksum correction. see Documentation

What we want to do is 
- it will be okay if a previous update is missing in the database. so we have a different update path from this database to the current version. So this version have no got a patch update in a previous version.
- a checksum failure should only be reported if the script names are identically for specific version.
- report an error if for a version contains in database it exists no version in SQL scripts.
With all these check we want to find failures done by developer during:
- change migration files after they where shipped
- delete migration files after they where shipped

=>
So currently we can not enable validation check, because we can not automatically repair the update processing.

**Comment by axelfontaine** [comment]
This should now be covered by #1352
