### ISSUE TITLE
Allow to run Java-based Migrations in an integrated manner with JPA

### ISSUE THREAD

**Issue by marlonpatrick10** [flyway/flyway#992]
Java-based migrations are a powerful way to perform complex transformations in the database.

At the moment however, the only way to make such transformations is using JDBC pure (Spring Jdbc Template also) through the Connection object that is passed to MigrationExecutor.

However, if we could get instead of a Connection an EntityManager would enable the developer to Java-based migrations using your JPA entities which would give more power to this feature of the Flyway.

I'm using this strategy in a project that work, however, in a manner not very orthodox, since at the time I create the EntityManager in my migrate method and ignore the Connection object that is passed to this method.

My idea would be that the Flyway object rather than pass a Datasource I could pass a EntityManagerFactory, so this factory could create an EntityManager and pass to the "JPAMigrations".

In addition, there could be some ways to pass the necessary information for the Flyway itself create the EntityManagerFactory. For example, in mavem plug might be something like:

    <configuration>
        <persistenceunit>
            <name>myPersistenceUnit<name/>
            <properties>
                <property>
                    <name>overridedProperty1</name>
                     <value>overridedProperty1Value</value>
                </property>  
            </properties>
        </persistenceunit>
    </configuration>

**Comment by axelfontaine** [comment]
This creates a chicken and egg problem, where the very structures your entities depend upon may not yet have been created by the migrations.

This is not something I want to include in the main distribution at this time.

Cheers
Axel
