### ISSUE TITLE
Excessive querying of Oracle ALL_OBJECTS dictionary

### ISSUE THREAD

**Issue by dankirberger** [flyway/flyway#994]
Our production Oracle database is made up of thousands of schemas (we group client data by schema).

We use Flyway to iterate over the schemas to apply migrations (each schema is targeted individually with its own schema_version table and a new connection). The overall process is great, but the iterating over projects has led to a lot of overhead. Our DBA reports the following query being executed excessively and expensively:
```
SELECT NULL AS table_cat, 
o.owner AS table_schem, 
o.object_name AS table_name, 
o.object_type AS table_type, 
NULL AS remarks 
FROM all_objects o 
WHERE o.owner LIKE :1 ESCAPE :"SYS_B_0" 
AND o.object_name LIKE :2 ESCAPE :"SYS_B_1" 
AND o.object_type IN (:"SYS_B_2", :"SYS_B_3", :"SYS_B_4") 
ORDER BY table_type, table_schem, table_name\\
```

From what I can tell, this query can be generated from calls to connection.getMetaData() which Flyway uses for general database detection tasks.

Is there any way this could be avoided? Any configuration option that can be added to avoid these kinds of calls and use the passed in value?

**Comment by axelfontaine** [comment]
A little investigation showed that connection.getMetaData() is only invoked twice per migration() call. In fact in your case, as you loop through the schemas, if you do it programmatically while reusing the Flyway object instance, it is only once per migrate() call as of the second one.

That doesn't seem that excessive to me. Are you sure it is generating that much load?

**Comment by dankirberger** [comment]
We have 4 flyway instances (running multithreaded). Each of these queries are very expensive with how many objects we have in production (within all of the different schemas).

I can do more troubleshooting, it is just difficult currently as our production environment is the only one at this scale, Flyway flies in our lower environments.

**Comment by dankirberger** [comment]
We have our own command line java app that wraps Flyway. I created a quick aspect to report on anything that calls getMetaData() within the flyway jar for our app:
```
public aspect ConnectionMetaDataAdvisor {
	Logger LOG = LoggerFactory.getLogger(ConnectionMetaDataAdvisor.class);

	Object around(): call(* *.getMetaData(..)) {
		StringBuilder msg = new StringBuilder();
		msg.append("getMetaData() called!\n");
		msg.append("Caller: " + thisEnclosingJoinPointStaticPart.getSignature().toShortString() + "\n");
		msg.append("Callee: " + thisJoinPointStaticPart.getSignature().toShortString() + "\n");
		LOG.info(msg.toString());
		LOG.info(ExceptionUtils.getFullStackTrace(new Exception()));
		return proceed();
	}	
}
```

The following resulted from calling migrate() on a single Flyway object:
http://pastebin.com/d5XFKw9d

This is the same for our logic that loops over each schema, and our "main" schema migrate logic that simply targets a single schema with a Flyway object.

**Comment by dankirberger** [comment]
Hmm, my attempt to bypass this issue with that aspect did not seem to help The aspect (juicy bit below) seems to fire appropriately but is not buying us any time. Again, this issue only shows up in our large production environment:
``` 
Object around(): call(* *.getMetaData(..)) {
		
		if(cachedMetaData.get() == null){
			LOG.info("method=getMetaDataAdvice message=cachingMetaData");
			Object retVal = proceed();
			cachedMetaData.set(retVal);
			return retVal;
		} else {
			LOG.info("method=getMetaDataAdvice message=returningCachedMetaData");
			return cachedMetaData.get();			
		}
	}

**Comment by dankirberger** [comment]
Closing this issue. DBA team ran the SQL tuner on the query in question, all is well.
