### ISSUE TITLE
AWS s3 access required when building the fyway-core / flyway-gradle-plugin

### ISSUE THREAD

**Issue by bolke01** [flyway/flyway#996]
Using the command " mvn compile    -P-CommercialDBTest "  to build the flyway-gradle-plugin fails due to a need for the s3 access.

can someone help to resolve this oddity.  

Note I'm inside the filrewall in the office, but I can successfully telnet out to the s3 site.

CENTOS01 flyway-gradle-plugin]# telnet s3.amazonaws.com 80
Trying 54.231.97.74...
Connected to s3.amazonaws.com.
Escape character is '^]'.

telnet> 

I have an account and the settings fle has teh required infor and using 
"  mvn   -s /root/.m2/conf/settings.xml -P-CommercialDBTest help:effective-settings"

shows what I believe is correct info - several variants have been tried as you can see.
>>>>

<settings xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
  <localRepository xmlns="http://maven.apache.org/SETTINGS/1.1.0">/root/.m2/repository</localRepository>
  <proxies xmlns="http://maven.apache.org/SETTINGS/1.1.0">
    <proxy>
      <username>MY-ACCOUNT</username>
      <password>***</password>
      <port>80</port>
      <host>s3.amazonaws.com</host>
    </proxy>
  </proxies>
  <servers xmlns="http://maven.apache.org/SETTINGS/1.1.0">
    <server>
      <username>MY-ACCOUNT</username>
      <password>***</password>
      <privateKey>/root/.ssh/id_rsa</privateKey>
      <passphrase>***</passphrase>
      <id>flyway-repo</id>
    </server>
    <server>
      <username>MY-ACCOUNT</username>
      <password>***</password>
      <privateKey>/root/.ssh/id_rsa</privateKey>
      <passphrase>***</passphrase>
      <id>flyway-snapshot</id>
    </server>
    <server>
      <username>MY-ACCOUNT</username>
      <password>***</password>
      <privateKey>/root/.ssh/id_rsa</privateKey>
      <passphrase>***</passphrase>
      <id>aws-snapshot</id>
    </server>
  </servers>
  <pluginGroups xmlns="http://maven.apache.org/SETTINGS/1.1.0">
    <pluginGroup>org.apache.maven.plugins</pluginGroup>
    <pluginGroup>org.codehaus.mojo</pluginGroup>
  </pluginGroups>
</settings>

<<<<<

<<< run log showing error >>>>

CENTOS01 flyway-gradle-plugin]# mvn compile    -P-CommercialDBTest 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building flyway-gradle-plugin 0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: s3://flyway-repo/release/org/flywaydb/flyway-core/0-SNAPSHOT/maven-metadata.xml
Downloading: s3://flyway-repo/snapshot/org/flywaydb/flyway-core/0-SNAPSHOT/maven-metadata.xml
[WARNING] s3://flyway-repo/release - Connection refused
[WARNING] s3://flyway-repo/snapshot - Connection refused
[INFO] Logged off - flyway-repo
[INFO] Logged off - flyway-repo
[WARNING] Could not transfer metadata org.flywaydb:flyway-core:0-SNAPSHOT/maven-metadata.xml from/to flyway-repo (s3://flyway-repo/release): The S3 wagon needs AWS Access Key set as the username and AWS Secret Key set as the password. eg:
<server>
  <id>my.server</id>
  <username>[AWS Access Key ID]</username>
  <password>[AWS Secret Access Key]</password>
</server>

[WARNING] Could not transfer metadata org.flywaydb:flyway-core:0-SNAPSHOT/maven-metadata.xml from/to aws-snapshot (s3://flyway-repo/snapshot): The S3 wagon needs AWS Access Key set as the username and AWS Secret Key set as the password. eg:
<server>
  <id>my.server</id>
  <username>[AWS Access Key ID]</username>
  <password>[AWS Secret Access Key]</password>
</server>

[WARNING] Failure to transfer org.flywaydb:flyway-core:0-SNAPSHOT/maven-metadata.xml from s3://flyway-repo/release was cached in the local repository, resolution will not be reattempted until the update interval of flyway-repo has elapsed or updates are forced. Original error: Could not transfer metadata org.flywaydb:flyway-core:0-SNAPSHOT/maven-metadata.xml from/to flyway-repo (s3://flyway-repo/release): The S3 wagon needs AWS Access Key set as the username and AWS Secret Key set as the password. eg:
<server>
  <id>my.server</id>
  <username>[AWS Access Key ID]</username>
  <password>[AWS Secret Access Key]</password>
</server>

[WARNING] Failure to transfer org.flywaydb:flyway-core:0-SNAPSHOT/maven-metadata.xml from s3://flyway-repo/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of aws-snapshot has elapsed or updates are forced. Original error: Could not transfer metadata org.flywaydb:flyway-core:0-SNAPSHOT/maven-metadata.xml from/to aws-snapshot (s3://flyway-repo/snapshot): The S3 wagon needs AWS Access Key set as the username and AWS Secret Key set as the password. eg:
<server>
  <id>my.server</id>
  <username>[AWS Access Key ID]</username>
  <password>[AWS Secret Access Key]</password>
</server>

Downloading: s3://flyway-repo/release/org/flywaydb/flyway-core/0-SNAPSHOT/flyway-core-0-SNAPSHOT.pom
[WARNING] s3://flyway-repo/release - Connection refused
[INFO] Logged off - flyway-repo
Downloading: s3://flyway-repo/snapshot/org/flywaydb/flyway-core/0-SNAPSHOT/flyway-core-0-SNAPSHOT.pom
[WARNING] s3://flyway-repo/snapshot - Connection refused
[INFO] Logged off - flyway-repo
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.711 s
[INFO] Finished at: 2015-04-21T19:05:40+01:00
[INFO] Final Memory: 9M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project flyway-gradle-plugin: Could not resolve dependencies for project org.flywaydb:flyway-gradle-plugin:jar:0-SNAPSHOT: Failed to collect dependencies at org.flywaydb:flyway-core:jar:0-SNAPSHOT: Failed to read artifact descriptor for org.flywaydb:flyway-core:jar:0-SNAPSHOT: Could not transfer artifact org.flywaydb:flyway-core:pom:0-SNAPSHOT from/to flyway-repo (s3://flyway-repo/release): The S3 wagon needs AWS Access Key set as the username and AWS Secret Key set as the password. eg:
[ERROR] <server>
[ERROR] <id>my.server</id>
[ERROR] <username>[AWS Access Key ID]</username>
[ERROR] <password>[AWS Secret Access Key]</password>
[ERROR] </server>
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
CENTOS01 flyway-gradle-plugin]#

**Comment by axelfontaine** [comment]
You need to build flyway-core locally first. Did that work?

**Comment by bolke01** [comment]
Hi,

the flyway-core built OK (at least thats what I see) 

using the command 
"mvn   -s /root/.m2/conf/settings.xml  -PCommandlinePlatformAssemblies  -P-CommercialDBTest  package"


Tests run: 213, Failures: 0, Errors: 0, Skipped: 1

[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.10:check (jdk6-apis-only) @ flyway-core ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ flyway-core ---
[INFO] Building jar: /home/actian/GIT/upstream/my-flyway/flyway-core/target/flyway-core-0-SNAPSHOT.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building flyway-gradle-plugin 0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:enforce (enforce-jdk6-or-later) @ flyway-gradle-plugin ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ flyway-gradle-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ flyway-gradle-plugin ---
[INFO] Not compiling main sources
[INFO] 
[INFO] --- gradle-maven-plugin:1.0.5:invoke (gradle-build) @ flyway-gradle-plugin ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] flyway-parent ...................................... SUCCESS [  0.918 s]
[INFO] flyway-core ........................................ SUCCESS [  5.323 s]
[INFO] flyway-gradle-plugin ............................... FAILURE [  0.327 s]
[INFO] flyway-maven-plugin ................................ SKIPPED
[INFO] flyway-sample ...................................... SKIPPED
[INFO] flyway-gradle-plugin-largetest ..................... SKIPPED
[INFO] flyway-maven-plugin-largetest ...................... SKIPPED
[INFO] flyway-sample-webapp ............................... SKIPPED
[INFO] flyway-sample-osgi ................................. SKIPPED
[INFO] flyway-sample-osgi-fragment ........................ SKIPPED
[INFO] flyway-osgi-largetest .............................. SKIPPED
[INFO] flyway-commandline ................................. SKIPPED
[INFO] flyway-commandline-largetest ....................... SKIPPED
[INFO] flyway-ant ......................................... SKIPPED
[INFO] flyway-ant-largetest ............................... SKIPPED
[INFO] flyway-sbt ......................................... SKIPPED
[INFO] flyway-sbt-largetest ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.121 s
[INFO] Finished at: 2015-04-22T10:27:42+01:00
[INFO] Final Memory: 47M/590M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.5:invoke (gradle-build) on project flyway-gradle-plugin: Execution gradle-build of goal org.fortasoft:gradle-maven-plugin:1.0.5:invoke failed: A required class was missing while executing org.fortasoft:gradle-maven-plugin:1.0.5:invoke: org/slf4j/impl/NewMojoLogger
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.fortasoft:gradle-maven-plugin:1.0.5
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/org/fortasoft/gradle-maven-plugin/1.0.5/gradle-maven-plugin-1.0.5.jar
[ERROR] urls[1] = file:/root/.m2/repository/org/gradle/gradle-tooling-api/1.6/gradle-tooling-api-1.6.jar
[ERROR] urls[2] = file:/root/.m2/repository/org/codehaus/groovy/groovy-all/2.0.6/groovy-all-2.0.6.jar
[ERROR] urls[3] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.flywaydb:flyway-gradle-plugin:0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :flyway-gradle-plugin

though if I try to use the install command - I get a Java failure starting with 

MigrationMediumTest
migrateConcurrently(org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLConcurrentMigrationMediumTest)  Time elapsed: 0.149 sec  <<< ERROR!
org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:postgresql://localhost/flyway_db) for user 'flyway': Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:302)

**Comment by axelfontaine** [comment]
You need to run install not package.

**Comment by bolke01** [comment]
Hi - Still failing on gradle - something is amis.

what are  "org.fortasoft:gradle-maven-plugin:1.0.5:" and  "invoke: org/slf4j/impl/NewMojoLogger" attempting to do?

tests were disabled to get the instal phae to work,

"mvn   -s /root/.m2/conf/settings.xml  -P-CommandlinePlatformAssemblies  -P-CommercialDBTest -P-InstallableDBTest  install " 


[INFO] --- gradle-maven-plugin:1.0.5:invoke (gradle-build) @ flyway-gradle-plugin ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] flyway-parent ...................................... SUCCESS [  1.108 s]
[INFO] flyway-core ........................................ SUCCESS [ 27.703 s]
[INFO] flyway-gradle-plugin ............................... FAILURE [  0.147 s]
[INFO] flyway-maven-plugin ................................ SKIPPED
[INFO] flyway-sample ...................................... SKIPPED
[INFO] flyway-gradle-plugin-largetest ..................... SKIPPED
[INFO] flyway-maven-plugin-largetest ...................... SKIPPED
[INFO] flyway-sample-webapp ............................... SKIPPED
[INFO] flyway-sample-osgi ................................. SKIPPED
[INFO] flyway-sample-osgi-fragment ........................ SKIPPED
[INFO] flyway-osgi-largetest .............................. SKIPPED
[INFO] flyway-commandline ................................. SKIPPED
[INFO] flyway-commandline-largetest ....................... SKIPPED
[INFO] flyway-ant ......................................... SKIPPED
[INFO] flyway-ant-largetest ............................... SKIPPED
[INFO] flyway-sbt ......................................... SKIPPED
[INFO] flyway-sbt-largetest ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.504 s
[INFO] Finished at: 2015-04-22T15:46:41+01:00
[INFO] Final Memory: 38M/660M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.5:invoke (gradle-build) on project flyway-gradle-plugin: Execution gradle-build of goal org.fortasoft:gradle-maven-plugin:1.0.5:invoke failed: A required class was missing while executing org.fortasoft:gradle-maven-plugin:1.0.5:invoke: org/slf4j/impl/NewMojoLogger
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.fortasoft:gradle-maven-plugin:1.0.5
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/org/fortasoft/gradle-maven-plugin/1.0.5/gradle-maven-plugin-1.0.5.jar
[ERROR] urls[1] = file:/root/.m2/repository/org/gradle/gradle-tooling-api/1.6/gradle-tooling-api-1.6.jar
[ERROR] urls[2] = file:/root/.m2/repository/org/codehaus/groovy/groovy-all/2.0.6/groovy-all-2.0.6.jar
[ERROR] urls[3] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.flywaydb:flyway-gradle-plugin:0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]

**Comment by axelfontaine** [comment]
Hmm what does mvn -v say?

**Comment by bolke01** [comment]
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T20:10:27+00:00)
Maven home: /usr/local/apache-maven/apache-maven-3.3.1
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_45/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-431.el6.x86_64", arch: "amd64", family: "unix"

(Note I'm going to appologies up front if I appear new to Maven - I built a hello world example on Friday last week and then am attempting to add new Database support connectors for Vector/VectorH and Matrix (aka ParAccel) as my first project.  - I'm an old-time C programmer stretching my arms...)

**Comment by axelfontaine** [comment]
This works, otherwise Travis CI wouldn't be able to build.

Closing.

**Comment by pazaan** [comment]
@bolke01, the problem you're having with gradle-maven-plugin happens when you use maven 3.3.1 or 3.3.3. See https://issues.apache.org/jira/browse/MNG-5817 and https://github.com/if6was9/gradle-maven-plugin/issues/15. I came across the same thing on my OS X box when trying to get things ready to add support for Hive and Impala.
Flyway's Travis CI works because it's using 3.2.5.
You can either download and install maven 3.2.5 if you want to run on the command line, or alternatively just run you maven lifecycle commands from inside IntelliJ - the bundled version of Maven 3 in IntelliJ seems to work fine for me.

**Comment by axelfontaine** [comment]
I'm happy to merge a PR for this if it fixes things with Maven 3.3.x

**Comment by ndimiduk** [comment]
I'm seeing the same problem.

```
$ mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: /usr/local/Cellar/maven32/3.2.5/libexec
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```

**Comment by ndimiduk** [comment]
Is there a mvn incantation that will allow me to build flyway from source without depending on the proprietary jars? I'm only interested in using it for OSS DB's for which jars available in maven central.

**Comment by mikebridge** [comment]
@ndimiduk  This works for me in maven 3.2.5, taken from [.travis.yml](https://github.com/flyway/flyway/blob/master/.travis.yml)

```sh
mvn install -P-CommercialDBTest -P-CommandlinePlatformAssemblies -DskipTests=true
```

**Comment by dviersel** [comment]
Unless I'm mistaken, I don't think I read a solution to the S3 access in this thread. 

I am trying to build flyway from source including the assemblies but it keeps complaining that S3 access is refused. I manually downloaded the jre binaries and placed them within my local .m2/repository however, I think that maven is still trying to fetch the associated pom files. 

Any idea anyone?

**Comment by ptahchiev** [comment]
Same issue - maven cannot connect to flyway s3 bucket.

**Comment by pradheeps** [comment]
How to resolve the S3 issue?Can someone post the setting.xml with the server details set.

**Comment by carljmosca** [comment]
Was the S3 issue ever resolved?

**Comment by axelfontaine** [comment]
S3 was never an issue. If you read the error message it actually says it can't find flyway-parent or flyway-core. If you build those locally, it finds them and everything works as expected.

**Comment by carljmosca** [comment]
I have read it.  I have also built flyway-core locally.  It's parent that I cannot build and get the message.

[ERROR] Failed to execute goal on project flyway-core: Could not resolve dependencies for project org.flywaydb:flyway-core:jar:0-SNAPSHOT: Failed to collect dependencies at com.microsoft.sqlserver:sqljdbc4:jar:4.0.2206.100: Failed to read artifact descriptor for com.microsoft.sqlserver:sqljdbc4:jar:4.0.2206.100: Could not transfer artifact com.microsoft.sqlserver:sqljdbc4:pom:4.0.2206.100 from/to flyway-repo-private (s3://flyway-repo/release): The S3 wagon needs AWS Access Key set as the username and AWS Secret Key set as the password. eg:
[ERROR] <server>
[ERROR] <id>my.server</id>
[ERROR] <username>[AWS Access Key ID]</username>
[ERROR] <password>[AWS Secret Access Key]</password>
[ERROR] </server>
[ERROR] -> [Help 1]

**Comment by axelfontaine** [comment]
You are missing additional dependencies in your local Maven repo (`com.microsoft.sqlserver:sqljdbc4:jar:4.0.2206.100` in this case).

This is how you can set them up: https://flywaydb.org/documentation/contribute/code/database

**Comment by carljmosca** [comment]
Thank you, that clears up some stuff.  I should have found that, sorry for the trouble.

**Comment by atcollins06** [comment]
I'm new to trying to build flyway.  I'm running into the issue with the com.microsoft.sqlserver:sqljdbc4:jar:4.0.2206.100 dependency mentioned above. The resolution is to look at the link: https://flywaydb.org/documentation/contribute/code/database.  This link apparently does not exist anymore.  Is there an updated link?

**Comment by axelfontaine** [comment]
@atcollins06 This version is not required anymore. Flyway now uses the new OSS SQL Server driver. See https://github.com/flyway/flyway/blob/master/pom.xml#L140

Just build from master and you should be fine.
