### ISSUE TITLE
Malformed class name after upgrading to 3.2

### ISSUE THREAD

**Issue by TomDmitriev** [flyway/flyway#997]
I've been using flyway-gradle-plugin on my project successfully before trying to migrate from the version 3.0 to 3.2.1. Now I get `Malformed class name` whenever I try execute `gradle flywayMigrate` or `gradle flywayInfo`. There isn't an error stacktrace even when I add --debug or --info. What I think may be causing the issue is that some of my migrations are written in groovy (they extend org.flywaydb.core.api.migration.jdbc.JdbcMigration). The issue is also reproducable on flyway-gradle-plugi 3.1.

**Comment by axelfontaine** [comment]
Thank you for the report, but frankly I don't really know what we could do on our end, as we rely and standard Java classloading. I see this more as a groovy compiler problem.

Thoughts?

**Comment by TomDmitriev** [comment]
Well, I thought you guys might've encountered something similar. If not,
I'm going to do some debugging and let you know what I find.

**Comment by TomDmitriev** [comment]
Sorry, I've been occupied with other things for quite some time. It turned out that the issue was cause by this bug in groovy https://issues.apache.org/jira/browse/GROOVY-5351 which was fixed in groovy 2.4.x. So, after upgrading the groovy version, everything works fine again!
