### ISSUE TITLE
Decoupling the Flyway API from JDBC, support NoSQL databases

### ISSUE THREAD

**Issue by harry12345** [flyway/flyway#998]
Decoupling the Flyway API from JDBC.
Flyway should support NoSQL database handling.
For example: Cassandra, RIAK, Mongo DB etc.

**Comment by white-bee** [comment]
isn't what Java migrations for?

**Comment by harry12345** [comment]
For data migration/data load java it is ok.
But how to manage the migration info history without jdbc/rdbms?

**Comment by axelfontaine** [comment]
This is not an immediate priority at this point.

**Comment by axelfontaine** [comment]
Closing old issue.
